### ISSUE TITLE
Cloning: error: filename in tree entry contains backslash" '\'. 

### ISSUE THREAD

**Issue by tlucas-mn** [desktop/desktop#10008]
We have a repository that can be cloned using latest git for windows and git for unix command lines but cannot be cloned using github desktop.
The error message is error: filename in tree entry contains backslash" '\'.  I don't see any files containing \'s in the repo but it is possible there is one somewhere in the tree.    

I have seen  mentions that this issue has already been fixed in git for windows 2.25 so apparently it is a know issue.   

1) When will this be fixed in github desktop ?
2) is there a work around for cloning this repo in github desktop while waiting for the fixed version to be release?

**Comment by rafeca** [comment]
Thanks for filing this issue!

The only two workarounds that I can think at the moment are either cloning the repository from outside of Desktop or identify the commit that introduced the filename with a backslash and remove it from the history (I would suggest against this since it'll change the repository history and this can cause tons of side-effects and friction).

Good news is that we're planning to update the git version Desktop uses very soon, we still haven't decided which version we'll upgrade to (we are cautious and we avoid upgrading to the latest one unless there are compelling reasons to do so), but it's going to be at least v2.26.x.

**Comment by niik** [comment]
Hi @tlucas-mn, in addition to what @rafeca said there's a workaround that involves temporarily disabling the security vulnerability counter-measure that's causing this issue, see my response in https://github.com/desktop/desktop/issues/10004#issuecomment-644075555.

For now I'm going to close this issue in favor of https://github.com/desktop/desktop/issues/9904. Please follow along there to see when we're ready to ship an updated version of GitHub Desktop.
