### ISSUE TITLE
Cloning error - 'filename in tree entry contains backslash: '\''

### ISSUE THREAD

**Issue by jjwagner** [desktop/desktop#10004]
### Describe the bug

Cloning fails with a huge wall of useless text and no visible button to clear it.

### Version & OS

Github desktop 2.5.2
Windows 10 Pro 2004

### Steps to reproduce the behavior

1. Go to File->Clone Repository...
2. Click on URL, then paste 'https://github.com/jjwagner/moodle' as URL
3. Select a local path
4. Click Clone
5. "Receiving objects" will climb to about 68%, then apparently crash?
6. folder disappears from filesystem
7. Click on Help->Show logs in Explorer to see logs.

### Expected behavior

I expected a clean fork of a popular project to clone using Github Desktop

### Actual behavior

Github desktop crashes without any sort of explanation

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

> 2020-06-15T00:25:21.771Z - error: [ui] `git -c credential.helper= -c protocol.version=2 clone --recursive --progress -- https://github.com/jjwagner/moodle.git D:\GitHub\moodle` exited with an unexpected code: 128.

many lines later:

> error: filename in tree entry contains backslash: '\'

**Comment by jjwagner** [comment]
Googling the error reveals that this was a problem for the Windows Git cli client. There's a workaround, discussed here:

https://github.community/t/windows-git-clone-error-error-filename-in-tree-entry-contains-backslash-32-mib-s/2935

I can't find any way to run git commands with the Desktop, so I can't see how this workaround will help me.

**Comment by niik** [comment]
Hi @jjwagner, thanks for opening this and I'm sorry that you've encountered this problem! This seems to be the same issue as #9904 and it's caused by a protective measure added to mitigate a security vulnerability in Git for Windows (the official command line interface that GitHub Desktop relies on behind the scenes). In https://github.com/moodle/moodle/commit/b4ede3f342b27b385bc95b84b0acbbce4e792369 a file was created containing a `\` character in its filename. This is forbidden on Windows  and while it was swiftly removed in https://github.com/moodle/moodle/commit/9a1a27b8fafafb8c1bc003db958b6cd7682f6e56 it's still triggering this behavior.

We're working on upgrading our built-in version of Git to a version which fixes this problem but until that release ships the temporary workaround is to either set the `core.protectNTFS` config variable as stated in the link you provided.

> I can't find any way to run git commands with the Desktop, so I can't see how this workaround will help me.

GitHub Desktop doesn't ship a command line interface but you can download the Git command line tools for Windows from https://git-scm.com/download/win. It's also possible to open the Git config file in an editor and add it manually (the config file is located in your home directory and is named `.gitconfig`).

<img width="648" alt="image" src="https://user-images.githubusercontent.com/634063/84652604-272dc200-af0c-11ea-81e7-2d896e0d5a0c.png">

```
[core]
	protectNTFS = false
```

Please be aware that this will disable the security vulnerability protection mechanism until you remove that section again.

> Cloning fails with a huge wall of useless text and no visible button to clear it.

Thanks for pointing this out, this has recently been addressed in #9945 and this is what I see when I  attempt to clone that repository now. That fix will be included in the next production release of Github Desktop.

<img width="632" alt="Screen Shot 2020-06-15 at 13 14 16" src="https://user-images.githubusercontent.com/634063/84651876-eda88700-af0a-11ea-9398-d1be8ccb76f8.png">

I'm going to close this issue in favor of #9904 so please follow along there for a notice of when we're getting ready to ship a fix.
