### ISSUE TITLE
Show currently checkout branch name in repositories list

### ISSUE THREAD

**Issue by omzy** [desktop/desktop#10037]
In the repositories list please can we have a small label next to the repository name (or in the hover tooltip) to indicate the branch name that is currently checked out?

A lot of my projects use multiple repositories, and sometimes when things don't work it's because one of the repositories isn't on the correct branch.

Currently we have to switch to the repository to find out the branch name. It would be good to be able to open the repositories list and get this information at a glance.

**Comment by tierninho** [comment]
@omzy Thank you for the suggestion --I think you are the first to request this!

Here is a mockup of the request, so we can have a visual:
![Screen Shot 2020-06-18 at 7 30 32 AM](https://user-images.githubusercontent.com/14828183/85053260-efa25e00-b135-11ea-9aee-d78654288b24.png)

I'm gonna let this sit for others to weigh in.

**Comment by gpinkas** [comment]
I would also really appreciate that feature. What about displaying the branch name beside the repository name like so?

![image](https://user-images.githubusercontent.com/54795296/136230488-2a4b1335-bf25-450e-8480-6241b88692e7.png)

**Comment by niik** [comment]
Hi @omzy, I'm doing a bit of issue cleanup and this feature has been requested before in https://github.com/desktop/desktop/issues/8158 so I'm going to close this issue in favor of that. That issue is currently closed as we haven't prioritized it but please add a 👍 reaction to that issue, we use that and other factors when we decide what work to prioritize.
