### ISSUE TITLE
Create new local repository as organisation

### ISSUE THREAD

**Issue by damienbutt** [desktop/desktop#10054]
### Describe the feature or problem you’d like to solve

When creating a new local repository and choosing to initialize it with a license, the copyright is assigned to the personal user. There is no way to specify that the repository is being created as an organisational repository and have the copyright assigned to the organisation. 

### Proposed solution

Add user/organisation option when creating a new local repository?

**Comment by steveward** [comment]
Thanks for the feedback @damienbutt. GitHub (the website) does put the organization name in the license when you create a new repository, so I agree that it would be nice to have feature parity here. However, GitHub Desktop doesn't have any concept of what organization you want to create the repository under until you click `Publish Repository`. I'm not sure of the full scope of work that would be necessary to implement this change, but since it's a rather minor thing to quickly update the LICENSE file I don't think this is something we will change anytime soon. I'm going to close this out and label it as an enhancement -- if we hear further feedback about this we can revisit it again in the future. Thanks for using GitHub Desktop!
