### ISSUE TITLE
Unable to push my repo from disktop app to GitHub

### ISSUE THREAD

**Issue by Alex-Moh** [desktop/desktop#10055]
Tried to push my entire Project Files from Desktop app to GitHub. 
1. Created a new branch under a private repository via Desktop app.
2. Pushed the changes-> took very long to publish & at the end it threw this error:
[GitHubErrorLog.txt](https://github.com/desktop/desktop/files/4814345/GitHubErrorLog.txt)

![image](https://user-images.githubusercontent.com/36487579/85322109-c5350580-b493-11ea-85b3-76139275503a.png)

**Comment by JDMathew** [comment]
Hi Alex, This looks like a network error. Have you tried publishing again?

**Comment by Alex-Moh** [comment]
Hi Justin,

As a matter of fact I have tried 5 times with the same error message!

-Thanks

**Comment by tierninho** [comment]
@Alex-Moh Thanks for the issue. It looks like you are pushing up a large amount of files and it timed out.

You may be running into GitHub's 2GB push limit. You can try pushing your repository in chunks via the command line by using the following command:

`git push <remotename> <commit SHA>:<branch>`

Also, if you had already committed a large file to your repository prior to adding it to Git LFS I would recommend using the `git-lfs-migrate` tool. Let me know if you run into any issues.

**Comment by Alex-Moh** [comment]
@tierninho Thanks for the insight - I believe big size of fie did cause the issue. That being said, now the real issue is that those files neither exist on my local repository folder nor in the GitHub - how am I to recover them?

**Comment by tierninho** [comment]
@Alex-Moh Yikes! Possible to send over the full logs from that day? See the Help menu in Desktop.

**Comment by Alex-Moh** [comment]
[GitHubErrorLog.txt](https://github.com/desktop/desktop/files/4820559/GitHubErrorLog.txt)

**Comment by tierninho** [comment]
Was that the full log or did you redact it? It seems to be missing some content.

**Comment by Alex-Moh** [comment]
@tierninho Above log is the whole error message that I received from GitHub.

**Comment by steveward** [comment]
@Alex-Moh apologies for the delay in following up with this.

>That being said, now the real issue is that those files neither exist on my local repository folder nor in the GitHub - how am I to recover them?

The files exist in your repository's history, which is why they need to be removed. The [`git-lfs-migrate`](https://github.com/git-lfs/git-lfs/blob/master/docs/man/git-lfs-migrate.1.ronn) tool will work, or you can use one of the options in [this help article](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/removing-sensitive-data-from-a-repository) to remove the file from your repository's history. You can then track the file using Git LFS.  

I'm going to close this out since I believe we've diagnosed the issue. Let me know if you run into any problems with these steps and I can assist you further.
