### ISSUE TITLE
Menu still says "Update from master" even when "master is not a branch name in my repo

### ISSUE THREAD

**Issue by aboretto** [desktop/desktop#10067]
### Describe the bug

Menu still says "Update from master" even when "master is not a branch name in my repo

### Version & OS

Version 2.5.2
Mac OS X Catalina

### Steps to reproduce the behavior

1. Launch App
2. Select menu "Branch"
3. Scroll down to 'Update from...'

### Expected behavior

I dont have a branch called master, I have "main".  I believe "master is hardcoded in the UI, it shouldn't be. it should infer the default branch from git.

master is a term we are trying to remove from our repo due to the connotations for the history of Slavery in the US.  Please do not hard code this term

<img width="273" alt="github_desktop_bad_term" src="https://user-images.githubusercontent.com/7189789/85424581-f57cb280-b52c-11ea-82c5-81d406948a4e.png">

**Comment by billygriffin** [comment]
Thanks for the issue @aboretto. That value isn't hardcoded, so it's likely there's a mismatch. See screenshot below with this project's default branch of `development`. 

<img width="307" alt="Screen Shot 2020-06-23 at 9 41 30 AM" src="https://user-images.githubusercontent.com/5091167/85425193-1e557580-b536-11ea-9153-f20fdffb981c.png">

I have a couple questions that will hopefully help us sort it out:
- Does your repo on GitHub.com show that the default branch is `main`? 
- Are you signed in to GitHub in Desktop?
- If yes to both of the other questions, have you fetched from this repo since you did the rename?

Let us know!

**Comment by aboretto** [comment]
Thanks for the quick reply

> I have a couple questions that will hopefully help us sort it out:
> 
> Does your repo on GitHub.com show that the default branch is main?

It is on an internal server, not Github
The default branch is main


> Are you signed in to GitHub in Desktop?
Yes I am

> If yes to both of the other questions, have you fetched from this repo since you did the rename?
I have fetched and here is the output from the finder

git status
On branch main
Your branch is up to date with 'origin/main'.



I have restarted both the App and my machine.  IS there a way to force the App to reset a cache?

Thanks so much

**Comment by niik** [comment]
> It is on an internal server, not Github

This is likely the reason. Since Git doesn't have a concept of a default branch, only a strong  convention GitHub Desktop relies first and foremost on the GitHub API to determine what the default branch is. If a repository isn't hosted on GitHub.com where users are able to [unambiguously configure the default branch name](https://help.github.com/en/github/administering-a-repository/setting-the-default-branch) we fall  back to another, less common convention of resolving the default branch which is to look at the current remote `HEAD` symbolic ref if such a reference exists. If there's no such symbolic ref we will fall back to the branch name that Git uses during creation time (which at the moment is still `master`).

You can check whether the default remote of your local repository has a HEAD symbolic  ref by executing the following command (this assumes your remote is named `origin`)

```
$ git symbolic-ref refs/remotes/origin/HEAD
refs/remotes/origin/development
```

In this example GitHub Desktop would resolve the default branch name to `development`

If you don't have a HEAD symbolic ref or if it is pointing to the wrong branch (the ref is created when cloning and not typically updated after that) you can first verify that your server is reporting the correct branch name:

```
$ git ls-remote --symref origin | grep HEAD
ref: refs/heads/development	HEAD
16cd1c59f6462ebcf3f3ecba38906df22a4b397b	HEAD
```

Here we can see (this is using the Desktop repository as an example) that the remote is telling us that the default branch is `development`.

You can then update (or create) the symbolic ref to point to (in your case) the `main` branch by executing

```
git symbolic-ref refs/remotes/origin/HEAD refs/heads/main
```

After doing all that it's possible that you might have to also restart GitHub Desktop for the changes to take effect.

If you don't have access to a Git command line environment you can open the manually create a file named `HEAD` in the `.git/refs/remotes/origin` folder and populate it with the  following contents

```
ref: refs/heads/main
```

**Comment by tierninho** [comment]
Closing this out as it appears there is enough information resolve it. Happy to reopen if needed. Thank you!

**Comment by FISHMANPET** [comment]
I've got this same issue, for me on a public repository (so it may be easier for you to debug some things).  I'm seeing some behavior that's indicating to me that there's some kind of bug here as well.

I'm running 2.5.3-beta2 on Windows 10.

This is is a fork of a public repository that had recently switched its default branch from master to main, and I followed suit in my branch.  I set my default branch in GitHub to main, and the branch selection menu properly shows main as the default branch.  I deleted the master branch in my repo, and then GitHub Desktop said that main was unpublished, and I should publish it to GitHub.  When I did that, it creates a new master branch in GitHub.  Master doesn't show up as a branch that's available for me to choose in the branch selection menu, but it's there somehow.

Using the comment above, I saw that the remote origin was still set to Master, so I used the instructions above to update that:
```
PS C:\Users\bajurny\Documents\GitHub\PSGSuite> git symbolic-ref refs/remotes/origin/HEAD
refs/remotes/origin/master
PS C:\Users\bajurny\Documents\GitHub\PSGSuite> git remote show origin
* remote origin
  Fetch URL: https://github.com/FISHMANPET/PSGSuite.git
  Push  URL: https://github.com/FISHMANPET/PSGSuite.git
  HEAD branch: main
  Remote branches:
    feature/ContactMgmt_issue53          tracked
    feature/add_ConfigName_parameter     tracked
    feature/sheets_batch_update          tracked
    feature/use_queues_for_Drive_uploads tracked
    feature_requests_125_150_152         tracked
    gh-pages                             tracked
    gsheets                              tracked
    main                                 tracked
    master                               tracked
  Local branches configured for 'git pull':
    gsheets merges with remote gsheets
    main    merges with remote master
  Local refs configured for 'git push':
    gsheets pushes to gsheets (up to date)
    main    pushes to main    (up to date)
PS C:\Users\bajurny\Documents\GitHub\PSGSuite> git remote set-head origin -a
origin/HEAD set to main
PS C:\Users\bajurny\Documents\GitHub\PSGSuite> git symbolic-ref refs/remotes/origin/HEAD
refs/remotes/origin/main
PS C:\Users\bajurny\Documents\GitHub\PSGSuite>
```

Those changes have stuck, but GitHub Desktop is still trying to publish the phantom Master branch to GitHub, and the menu "update from <default>" still says "update from master" rather than "update from main."

So I think there's something buggy here.  I also think that odds are good there's going to be a lot of people changing their default branch name, so it might be useful for GitHub Desktop to do something with the remote origins, if that's what's necessary.  But in this case, this is a public GitHub repository so per the comment above, the client should have properly detected the updated Default branch, though it apparently didn't.

**Comment by FISHMANPET** [comment]
Looking closely it looks like my local branch main is configured to merge with remote master rather than remote main...

Realizing this isn't a git support forum, I would say the benefit of GitHub Desktop is it's abstracting a lot of the guts of git, and this seems like a case (especially because this is going to be happening to lots of people) where GitHub Desktop could do something to fix local copy?

**Comment by FISHMANPET** [comment]
ok figured out where I got myself into trouble:
I used `git branch -m master main` per [this](https://www.kapwing.com/blog/how-to-rename-your-master-branch-to-main-in-git/) guide and pushed that to the remote, but that guide doesn't have you update the origin, so I found ` git push origin -u main` in [this](https://blog.b12.io/migrating-your-default-git-branch-to-main-a0fb706e3668) (which links to [this gist](https://gist.github.com/phooky/8b473f30dad4b8ee160b6e2a07db6e78)).  That updated my local main to point to remote main.

I'd gotten myself into a very weird state, and obviously I got there outside of GitHub Desktop, but GitHub Desktop was also sorta just going along with it.  I'd say maybe having local branches that push to a different branch on the remote is probably something that GitHub Desktop could warn about and try to fix (with some option to disable that if you're gonna be someone with an advanced git use case that still wants to use a GUI) it.
