### ISSUE TITLE
Getting this fatal error again and again instead of having good internet connection.

### ISSUE THREAD

**Issue by anyonehomep1mane** [desktop/desktop#10070]
Hello Support,

From last 2-3 day i am getting this fatal error while using Github Desktop Application.

I am having good internet connection but still it giving me fatal error which you can see in below screenshot.

So it my kind request you to please look into this problem and provide a solution.
 
![image](https://user-images.githubusercontent.com/42736459/85493199-18be6500-b5f4-11ea-92ce-c922db07161a.png)

**Comment by steveward** [comment]
@anyonehomep1mane thanks for the report. Usually this error indicates you are behind a proxy that requires authentication. Here's how you can set that up:

1. Go to the file menu and select `Repository` > `Open in Terminal` (macOS) or `Open in command prompt` (Windows)
2. Run the following command:

`git config --global http.proxy http://proxyuser:proxypwd@proxy.server.com:8080`

Replace `proxyuser` with your proxy username and `proxypwd` with your proxy password. Also, `proxy.server.com:8080` needs to point to the URL of your proxy server.

Let me know if you have any issues getting this set up.

**Comment by anyonehomep1mane** [comment]
@steveward Thanks for sharing solution. I will try implementing it. If i face any issue then i will let you know. Thanks!

**Comment by DebabrataDipta** [comment]
hey man, I have used git using this because in college I used to proxy, but now that I am not using a proxy anymore, my GitHub is showing fatal it is trying to connect with my proxy but since it is not there for that reason, it shows me being unable to connect with the server. How can i sort this thing out or tell me a way to delete the proxy from the server
