### ISSUE TITLE
Add an Option That Moves Files to Trash When Discarding Stash Changes

### ISSUE THREAD

**Issue by JosephTLyons** [desktop/desktop#10071]
### Describe the feature or problem you’d like to solve

When you discard any normal changes, you are asked to confirm the action, and then files are sent to the trash, but this doesn't seem to be the case with discarding stashes.  Discarding stash changes seems to be destructive.  I accidentally clicked on it and somehow managed to make it through the confirmation modal as well before I realized what had happened.  I checked the trash, but the files were not there.

### Proposed solution

It will allow users to rescue files from stashes that they accidentally discarded.

**Comment by niik** [comment]
Hi @JosephTLyons, thanks for opening this!

You're right that we don't move discarded stashes to the trash. While an appealing idea it's complicated by the fact that we would then first have to checkout the stash contents before moving them to trash which isn't really possible if there are changes in the working directory and has the potential of causing problems even if there weren't.

We have discussed a more comprehensive approach to undoing destructive actions in the application but that's still a ways out I'm afraid.

Luckily for us there's a (albeit not discoverable or user friendly) way of getting back the discarded stash. Since a stash is essentially a commit all of the changes in that stash are part of the Git object database and as long as the repository hasn't been garbage collected recently you should be able to find the stash again. I don't know which operating system you're on but if you [locate the logs directory](https://github.com/desktop/desktop/blob/19640b429f13102ea2a9cf7396b34992155dbadf/docs/installation.md#data-directories) on your machine and search for `dropped stash` you should find one or more entries looking like this

```
2020-06-22T09:14:51.120Z - info: [ui] [AppStore. _dropStashEntry] dropped stash with commit id fdbcbf9f49c84053d2a3801810161dbc3f96ea2f
```

Matching the date and time to when you approximately discarded your stash you can use the SHA1 at the end of that line to show and restore your stash entry again

```
$ git show fdbcbf9f49c84053d2a3801810161dbc3f96ea2f
commit fdbcbf9f49c84053d2a3801810161dbc3f96ea2f
Merge: 3390729f7 b49b49967
Author: Markus Olsson <j.markus.olsson@gmail.com>
Date:   Thu Jun 18 15:15:22 2020 +0200

    On stash-menu-fixes: !!GitHub_Desktop<stash-menu-fixes>
```

Restoring:

```
$ git stash apply fdbcbf9f49c84053d2a3801810161dbc3f96ea2f 
```

I hope that helps you get your stashed changes back!

**Comment by JosephTLyons** [comment]
@niik, thank you very much for the information!  I appreciate the extremely detailed write up.  Your suggestions saved my code; I was able to retrieve it entirely.  Such a huge relief.  Many thanks for your willingness to help me out here, I thought it was entirely gone!

**Comment by niik** [comment]
Really happy you were able to find your missing stash @JosephTLyons! We're gonna keep thinking about ways to enable undoing more widely in the app but as I talked about earlier I don't believe sending them to trash is a feasible approach right now so I'm going to close this out.
