### ISSUE TITLE
Cannot see files uploaded to repo and cannot merge with desktop.

### ISSUE THREAD

**Issue by Gaalidas** [desktop/desktop#10080]
### Describe the bug

Will not merge the repo with my desktop version.

### Version & OS

Version 2.5.3 / Window 10

### Steps to reproduce the behavior

1. Open repo in desktop app.
2. Click on "Pull Origin"
3. Notice message "Unable to merge unrelated histories in this repository."
4. Get frustrated and submit report.

### Expected behavior

It's pretty simple.  I want my github repo to show the files I just committed and merge with the readme I created when I started the repo on the github website.

### Actual behavior

The error message I described, a list of things I have uploaded that will not show and existing on the website at all despite having just committed them.

### Screenshots

Not applicable here.

### Logs

There is no method of attaching a file in this text editor GUI that I can find.  Here's a clip from it:
`(The error was parsed as 29: Unable to merge unrelated histories in this repository.)
2020-06-24T16:26:10.981Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: GCommon - Gaalidas (has token)
2020-06-24T16:26:11.671Z - error: [ui] `git -c credential.helper= -c protocol.version=2 pull --progress origin` exited with an unexpected code: 128.
stderr:
fatal: refusing to merge unrelated histories`

### Additional context

Just a question for those of us who don't speak github lingo: What the heck does it mean when it says "unrelated histories"?  I'm just trying to get my filers to show up in my repo!  I'm not asking for anything that isn't expected of a github repo.

**Comment by tierninho** [comment]
The “fatal: refusing to merge unrelated histories” Git error occurs when two unrelated projects are merged (i.e., projects that are not aware of each other’s existence and have mismatching commit histories).

Consider the following two cases that throw this error:

  - You have cloned a project and, somehow, the .git directory got deleted or corrupted. This leads Git to be unaware of your local history and will, therefore, cause it to throw this error when you try to push to or pull from the remote repository.

  - You have created a new repository, added a few commits to it, and now you are trying to pull from a remote repository that already has some commits of its own. Git will also throw the error in this case, since it has no idea how the two projects are related.

**Solution**
The error is resolved by toggling the `allow-unrelated-histories` switch. After a git pull or git merge command, add the following tag:

`git pull origin master --allow-unrelated-histories`

More information can be found [here](https://github.com/git/git/blob/master/Documentation/RelNotes/2.9.0.txt#L58-L68), ​ on Git’s official documentation.

**Comment by Infini-Creation** [comment]
Hi @tierninho,

I know it's a pretty old issue but I've got the same one recently and... fix is to use git CLI command with switch. WHY ?

What the point of having a GUI and cannot just check a mere box on commit for instance to allow this OR provide extra option(s) for commit allowing to add the switch directly through _github desktop_ ?

Should I create a new issue about that ?
