### ISSUE TITLE
Path variable is overwritten rather than appended when GitHub Desktop is installed or updated

### ISSUE THREAD

**Issue by CKingX** [desktop/desktop#10100]
### Describe the bug

When GitHub Desktop is installed or updated, it overwrites the User Path variable when it includes the GitHubDesktop folder in the Path rather than appending to it.

### Version & OS

Version 2.5.3 (though I updated to it which caused the problem in addition to the first time when I installed GitHub Desktop (though I didn't realize it was GitHub Desktop that caused it and it was only after installing this update that I realized that it happened again, and the only path that remained was the GitHubDesktop\bin folder. 

OS: Windows 10 Pro 1909.

### Steps to reproduce the behavior

1. Either reinstall GitHub Desktop or wait for an update. After installing it, the Path variable will lose all other 

### Expected behavior

The GitHubDesktop\bin folder should be appended to the Path variable (or ignored if it already exists when an update is being installed)

### Actual behavior

The Path variable is overwritten and all other Path variables are lost, breaking functionality of other apps and scripts.

**Comment by tierninho** [comment]
Thanks for the issue @CKingX . Currently it is not possible to customize the installation location of GitHub Desktop. This is a constraint in the installation framework we use, Squirrel.Windows (see Squirrel/Squirrel.Windows#314). At this time we do not have plans of changing the installer we use for GitHub Desktop.

cc @niik or @rafeca to add some more insight.

**Comment by CKingX** [comment]
Just to clarify, the issue here is not changing the installation location in the Path. Just that, it erases any other entry in the Path variable. For example, if you install the Windows Terminal app from Windows Store, it adds the `C:\Users\[User]\AppData\Local\Microsoft\WindowsApps` to the User Path variable. However, after updating GitHub Desktop, it overwrites the entire Path variable with its own GitHubDesktop\bin folder in the AppData, rather than appending to the existing Path variable. After the update, commands like `wt` to launch the Terminal stop working as it overwrites the Path variable

**Comment by niik** [comment]
Thanks for clarifying @CKingX!

I wasn't quite able to reproduce this myself but I did spot something a bit odd. I uninstalled GitHub Desktop and removed the `GitHubDesktop\bin` entry from the path env var:

<img width="502" alt="Screen Shot 2020-06-30 at 12 30 45" src="https://user-images.githubusercontent.com/634063/86116505-d7372980-bacd-11ea-943f-59adbdd6e3a1.png">

I then installed GitHub Desktop again and looked at the new environment variable:

<img width="501" alt="Screen Shot 2020-06-30 at 12 32 01" src="https://user-images.githubusercontent.com/634063/86116842-60e6f700-bace-11ea-99ef-930713c78fdf.png">

So while in my case it doesn't appear as if anything got it looks like the `%USERPROFILE%` got auto-expanded and resolved. Looking into this some more it would appear that this is an artifact of how we load the `PATH` environment variable.

We currently load the `PATH` env var through powershell:

https://github.com/desktop/desktop/blob/d6f7518f43bd7f9f55e56737e2845474fe2c7ebb/app/src/lib/process/win32.ts#L20-L38

This was introduced in https://github.com/desktop/desktop/pull/1925/commits/9820f7f988e04ea4b268f1462f6dbe6bb6d8c473#diff-fc992a6c0da9f6047bd328ec09982ec2R111 and copied from Atom https://github.com/atom/atom/pull/10326/files.

The reason for this odd-looking way of loading the path variable is that the previous method of using `reg.exe query HKCU\Environment` could fail due to a ban on registry modification in a group policy on Windows even though reg.exe was only reading a value, not modifying it. This peculiarity was the reason behind implementing our own registry library (https://github.com/desktop/desktop/pull/3492).

If we switch the loading (though not writing) of this environment variable to `registry-js` we need to test it with paths containing non-ascii characters as well.

@CKingX could you do the same thing as I did above and screenshot the before and after?

**Comment by CKingX** [comment]
Interesting. So, I decided to do a test of my own. After uninstalling, and adding WindowsApps just to be sure, I disabled NoVirusThanks OSArmor and ran the installer again (to simulate update). The installer correctly appended the Path variable. Later, I enabled OSArmor and reinstalled, only for the Path variable to be reset.

So I disabled OSArmor again, and uninstalled and reinstalled GitHub Desktop. I then installed it again and the installer did not seem to reset the Path variable. I uninstalled GitHub Desktop again and enabled OSArmor. Then, after reinstalling, it reset the Path variable again.

Seems like OSArmor was causing the problem. I have now uninstalled OSArmor.

Thanks for your help!
