### ISSUE TITLE
github desktop encountered an  error

### ISSUE THREAD

**Issue by ahuan9527** [desktop/desktop#10139]
Invariant Violation: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at i (file:///app/renderer.js:59924:13)
    at s (file:///app/renderer.js:59934:5)
    at Xe (file:///app/renderer.js:61100:9)
    at file:///app/renderer.js:61392:102
    at co (file:///app/renderer.js:61666:28)
    at go (file:///app/renderer.js:61727:115)
    at fo (file:///app/renderer.js:61718:12)
    at bo (file:///app/renderer.js:61807:88)
    at rr (file:///app/renderer.js:62751:13)
    at ir (file:///app/renderer.js:62767:37)

Version: 2.5.3
OS: Windows 10.0.18363

**Comment by niik** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

In particular we're interested in hearing when this error occurs for you and if it's consistently reproducible. Has GitHub Desktop worked previously or is this a new installation?

Thanks for understanding and meeting us half way :grinning:

**Comment by steveward** [comment]
Closing this issue out due to inactivity @ahuan9527. If you are able to fill out the template to provide more information we would be happy to revisit it.
