### ISSUE TITLE
Getting authentication error

### ISSUE THREAD

**Issue by azolfaghari1368** [desktop/desktop#10134]
### Describe the bug

When I want to fetch origin as well as when I want to publish a new branch, I get " We were unable to authenticate with code.vt.edu. Please enter your username and password to try again." I enter my username and password in my git lab website (code.vt.edu) but they do not work.

### Version & OS

Version 2.5.3
Windows 10
### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help expla
![Error_Git](https://user-images.githubusercontent.com/54087872/86520052-c9a3db80-be0e-11ea-9f1e-d650a7ddf556.png)
![Error_Git](https://user-images.githubusercontent.com/54087872/86520058-d1638000-be0e-11ea-8450-d9389f3b28de.png)

in your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by niik** [comment]
Thanks for the report! Could you upload a log file from GitHub Desktop so that I could get some more information about this issue? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue. Thanks!

**Comment by steveward** [comment]
Closing this issue out due to inactivity @azolfaghari1368. if you are able to upload a log file we can look into this further.
