### ISSUE TITLE
Github desktop repository push "hanged up unexpectedly"

### ISSUE THREAD

**Issue by ms609** [desktop/desktop#10140]
### Describe the bug

When pushing commits that contain large files, I see
```
error: RPC failed; curl 56 Failure when receiving data from the peer
fatal: the remote end hung up unexpectedly
```

### Version & OS

GitHub Desktop v2.5.3
Windows 10

### Steps to reproduce the behavior

1. Commit binary files of a modest to large size (exact size seems variable, c. 2MB) using GitHub Desktop
2. Push commit(s) to origin using GitHub Desktop (also fails using Git CMD)
3. See error

The affected repos are hosted on GitHub.  My internet connection is stable.  I encounter the issue whether I connect using a proxy or not.

I've run `git config http.postBuffer 524288000`.  Git LFS is not an option.

### Expected behavior

The files should be uploaded: it's possible to upload the same files using the GitHub drag-n-drop interface, so there can't be any issues with hitting storage limits.

### Actual behavior

I see a popup with:
```
Enumerating objects: 16, done.                                                  
Counting objects: 100% (16/16), done.                                           
Delta compression using up to 8 threads
Compressing objects: 100% (10/10), done.                                        
Writing objects: 100% (10/10), 3.82 MiB | 24.92 MiB/s, done.                    
Total 10 (delta 4), reused 0 (delta 0)
error: RPC failed; curl 56 Failure when receiving data from the peer
fatal: the remote end hung up unexpectedly
fatal: the remote end hung up unexpectedly
Everything up-to-date
```

### Logs

[2020-07-06.desktop.production.log](https://github.com/desktop/desktop/files/4878402/2020-07-06.desktop.production.log)

### Additional context

I have allowed GitHub Desktop through the firewall, following #6193. 

This issue affects multiple repositories.  

Commits that do not involve large files are pushing fine.

**Comment by niik** [comment]
Hi @ms609, I'm sorry to hear you're having problems pushing files. Are you by chance located behind a proxy server? That's the most common type of issue we see when pushes fail. GitHub.com doesn't have a hard limit at 2Mb so the most likely scenario here is that there's some service either at your company or at your internet service provider that's blocking big POST requests.

Given that it also fails for you when you're pushing using the Git CLI there's not much we can do from the Desktop side since we rely on the Git CLI as well. I would recommend seeing if there's anything helpful for you at https://docs.github.com/en/github/getting-started-with-github/troubleshooting-connectivity-problems#troubleshooting-slow-downloads-and-intermittent-slow-connections and if there isn't I'd recommend reaching out to [GitHub Support](https://support.github.com) directly for help with troubleshooting your connection.

Terribly sorry that I don't have better news for you.
