### ISSUE TITLE
use 'open with default program' while file path contains Chinese

### ISSUE THREAD

**Issue by dianban** [desktop/desktop#10167]
### Describe the bug

When the file path contains Chinese, use 'open with default program' throw error

### Version & OS

Github Desktop Version 2.5.3
Windows 10

### Steps to reproduce the behavior

1. Go to 'changes'
2. Right click on a file which path contains Chinese
3. Click on 'Open with default program'

### Expected behavior

Open file with default program

### Actual behavior

Throw error 'Unable to open file I:\testProject\test1\中文\1.txt in an external program. Please check you have a program associated with this file extension'

### Screenshots

![image](https://user-images.githubusercontent.com/16113155/86873063-1e747a00-c0cd-11ea-8a99-5d5606612c57.png)

### My solution
desktop\app\src\ui\lib\open-file.ts
```
export async function openFile(
  fullPath: string,
  dispatcher: Dispatcher
): Promise<void> {
  let result = null
  if (__DARWIN__) {
    result = await shell.openExternal(`file://${fullPath}`)
  } else {
    result = await shell.openItem(`file://${fullPath}`)
  }

  if (!result) {
    const error = {
      name: 'no-external-program',
      message: `Unable to open file ${fullPath} in an external program. Please check you have a program associated with this file extension`,
    }
    await dispatcher.postError(error)
  }
}
```
I don't know whether it applies to all

**Comment by tierninho** [comment]
@dianban Thanks for filing this. The error is not due to the Chinese characters, but because you have `\` in the file name. I got the same error when I tried:

```
Unable to open file /Users/tierninho/Documents/GitHub/Pink/rrr\bbb.txt in an external program. Please check you have a program associated with this file extension
```

Remove the `\` and it should work fine.

**Comment by critical-bug** [comment]
I have the same issue as @dianban described. The error is not due to `\`, the Windows path separator, as I tested below.

### Version & OS
GitHub Desktop Version 2.6.3

```
Edition	Windows 10 Pro
Version	20H2
Installed on	‎2020/‎11/‎08
OS build	19042.804
Experience	Windows Feature Experience Pack 120.2212.551.0
```
### Steps to reproduce the behavior

1. In any local repository, create a file `あ.md` with any content
2. In GitHub Desktop's Changes tab, right click it and select `Open with default program`
3. You see the error saying `Unable to open file …\あ.md in an external program. Please check you have a program associated with this file extension`

    ![](https://user-images.githubusercontent.com/124340/109508742-13c18780-7a98-11eb-8a1d-cd88634af075.png)

4. Create or edit a file whose name doesn't contain multibyte character
5. Right click it and select `Open with default program`

    ![](https://user-images.githubusercontent.com/124340/109508954-52574200-7a98-11eb-829e-4ad837ae53ad.png)

6. You don't see any error

![](https://user-images.githubusercontent.com/124340/109509015-5f743100-7a98-11eb-9fa8-9b37ea8d68ba.png)

#### Logs
```
2021-03-01T13:28:55.661Z - info: [ui] [AppStore] loading 5 repositories from store
2021-03-01T13:28:55.662Z - info: [ui] [AppStore] found account: critical-bug (critical-bug)
2021-03-01T13:28:55.845Z - info: [ui] [BranchPruner] Last prune took place in 17 hours - skipping
2021-03-01T13:28:55.905Z - info: [ui] launching: 2.6.3 (Windows 10.0.19042)
2021-03-01T13:28:55.905Z - info: [ui] execPath: 'C:\Users\yosi\AppData\Local\GitHubDesktop\app-2.6.3\GitHubDesktop.exe'
2021-03-01T13:29:09.097Z - error: [main] Call to openExternal failed: 'Error: Failed to open'
2021-03-01T13:29:12.000Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.406s)
2021-03-01T13:39:35.199Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 7.622s)
```
