### ISSUE TITLE
Desktop cloning loading continuously w/o error

### ISSUE THREAD

**Issue by althafphussain** [desktop/desktop#10174]
1.While initiating clone, the interface shows continuously for hours without any error.
2.The destination directory doesnt have any cloned data

![image](https://user-images.githubusercontent.com/67654738/86971034-24279980-c179-11ea-946c-1c8d6d55310b.png)

Status on destination directory
![image](https://user-images.githubusercontent.com/67654738/86971263-884a5d80-c179-11ea-8499-aa7c68b3057b.png)

**Comment by steveward** [comment]
Thanks for the report @althafphussain. Could you upload the log file from GitHub Desktop so that I could get some more information about this issue? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs...`
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by althafphussain** [comment]
Hello @steveward Thanks for help, attached the logs here.
[logs.zip](https://github.com/desktop/desktop/files/4897693/logs.zip)

**Comment by steveward** [comment]
Thanks for sharing the logs. I am not seeing any indication of what could be causing the clone operation to fail. Are you behind a firewall or proxy that could be interfering with your connection? Are you running any security software that could be blocking GitHub Desktop?

**Comment by tierninho** [comment]
@althafphussain  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
