### ISSUE TITLE
Cannot "show in explorer" in some projects

### ISSUE THREAD

**Issue by khiav223577** [desktop/desktop#10187]
### Describe the bug

The "show in explorer" command raise errors in some of my projects while "open in Command Prompt" and "open in Sublime Text" works.

It will work fine if I rename the folder from `echo` to `echo123`, but it will raise the same errors after I rename it back to original name.

### Version & OS

Version 2.5.3
Windows 10 Build 19041.329

### Steps to reproduce the behavior

![image](https://user-images.githubusercontent.com/4011729/87220527-09327080-c397-11ea-8029-5d61e5ad3023.png)

### Expected behavior

Open the exploror

### Actual behavior

Raise an error dialog. See the screenshot below.

### Screenshots

![image](https://user-images.githubusercontent.com/4011729/87220437-48ac8d00-c396-11ea-8378-0acf6c9ccb16.png)

### Logs

[2020-07-11.desktop.production.log](https://github.com/desktop/desktop/files/4906521/2020-07-11.desktop.production.log)

**Comment by rafeca** [comment]
Hey @khiav223577!

I've been able to reproduce the problem in v2.5.3 by doing the following:

1. Create a random folder (name doesn't matter).
2. Copy any Windows executable to that folder (e.g `c:/windows/system32/cmd.exe`).
3. Create a repository with the same name as the executable.

After these steps, I get the following error when trying to "Show in Explorer":

![image](https://user-images.githubusercontent.com/408035/87295582-baefaf80-c505-11ea-984c-f8deb6b4c96b.png)

@khiav223577 do you have by any chance any `echo.exe` file (or other similar files) inside your `回音 git 版/` folder?

I'm going to check whether https://github.com/desktop/desktop/pull/9987 fixes this problem, since it refactors a bit that same logic.

**Comment by rafeca** [comment]
> I'm going to check whether #9987 fixes this problem, since it refactors a bit that same logic.

Update: that PR doesn't solve this issue so we need to look for another solution to this.

**Comment by khiav223577** [comment]
> @khiav223577 do you have by any chance any `echo.exe` file (or other similar files) inside your `回音 git 版/` folder?

It does have. And the bug only happens when there is `echo.exe` inside `回音 git 版/` folder. :fearful:

**Comment by rafeca** [comment]
Thanks for the information @khiav223577 !

I've checked and this seems to be caused by electron, where the call to `shell.openExternal('c:\myFolder\mySubfolder')` will try to open any file called `shell.openExternal('c:\myFolder\mySubfolder.xxx')` before trying to open the folder.

A workaround to this issue is to add a final slash at the end of the path when trying to open a folder: `shell.openExternal('c:\myFolder\mySubfolder\')`. I'm gonna send a PR to fix this.

Thanks a lot @khiav223577 for reporting this and helping Desktop getting better!
