### ISSUE TITLE
Hide remote branches in branch list

### ISSUE THREAD

**Issue by paulmasson** [desktop/desktop#10191]
My apologies if this is the wrong place to ask the question, but I haven't found any documentation for my situation. I contribute to an open-source academic project SageMath that keeps its main Git repository on a Trac server and a cleaner copy on GitHub. For reasons of documentation, merged branches are never deleted in the main Trac repository. In order to be able to contribute, my Git setup must have references to both repositories.

When using the older version of Desktop on latest macOS, I would only see local branches, never remote. Having just switched to the newer version, my branch list now includes every single old branch in the Trac repository, making it useless in practice. If I could just filter out every branch beginning with "trac" then there would be no issue. Is there a way to do this?

Thanks!

**Comment by rafeca** [comment]
Hey @paulmasson, this is the correct place to ask such questions (or report bugs, suggest features,...) 😃 

To answer your question, it's currently not possible with Desktop to hide remote branches and we haven't considered implementing such feature since we haven't seen many people requesting this feature (I think it's the first time I hear it 😜).

As a workaround, you can configure your repository to make `git` only fetch certain branches from the "Trac" remote (for example to only fetch the `master` branch there). This has the added benefit that `git` won't have to download every old branch when you fetch.

To do so, you'll have to modify your `git` repository config (In the `.git/config` file in your repository folder). From there you can find the configuration for the trac remote, which will look like something like:

```
[remote "trac"]
	url = xxxxxx
        fetch = +refs/heads/*:refs/remotes/trac/*
```

You can change the fetch line to only fetch the `master` branch by changing it to something like `fetch = +refs/heads/master:refs/remotes/trac/master` (you can also add wildcards or multiple fetch lines, see the docs [here](https://git-scm.com/book/en/v2/Git-Internals-The-Refspec)).

**Note**: Beware with the remote name. I've assumed that in your case it was `trac` but you'll have to change the code that I pasted if you have a different remote name.

Hope this helps. I'm going to close this issue since I don't think we're going to implement hiding remote branches in the near future (we're a very small team and we have to prioritize work on issues that help the maximum amount of users), but if we see that this becomes a popular demand or circumstances change we'll reconsider it.
