### ISSUE TITLE
Email validation on welcome and preferences screen

### ISSUE THREAD

**Issue by Pragya007** [desktop/desktop#10209]
### Describe the feature or problem you’d like to solve

I unknowingly added email to desktop which simply doesn't exist and still it was making commits with my name as desktop is linked with it but when I went through the commits author was having a general avatar and no account because email doesn't exist and it didn't showed any alert.

### Proposed solution

While adding email we can validate it first if it is existing or not.
I would like to add this feature and contribute to desktop if this got verified by the team.

**Comment by rafeca** [comment]
Thanks for reporting this issue @Pragya007 !

When you say "While adding email we can validate it first if it is existing or not.", I'm not sure we can easily validate if the actual email exists, but we can definitely check whether the introduced email has a valid syntax.

When we detect an incorrect email I think we should display some soft warning, but I don't think we should block the user from saving it, since we ourselves don't require the email for anything and maybe there are some scenarios where users put invalid emails in purpose.

> I would like to add this feature and contribute to desktop if this got verified by the team.

Yes please! 😃 

Just to give a bit of direction, an easy way to implement this would be to change the email input element to be of `type=email`, which would do the email validation natively. Then we could add some subtle warning style (e.g by changing the border of the input or a small [warning octoicon](https://primer.style/octicons/alert-16) on the right side of the input) using the `:invalid` CSS selector.

Note that there are two places where we would need this validation:

1. In the welcome flow:

<img width="764" alt="Screen Shot 2020-07-15 at 13 22 51" src="https://user-images.githubusercontent.com/408035/87539511-4e5be880-c69e-11ea-9174-dd7048a272e8.png">

2. In the preferences modal:

<img width="795" alt="Screen Shot 2020-07-15 at 13 38 23" src="https://user-images.githubusercontent.com/408035/87540757-7ea48680-c6a0-11ea-8482-a2d7f8536049.png">

Hope this helps, let me know what you think!

**Comment by Pragya007** [comment]
Thank you @rafeca .. Sure I will proceed accordingly then as suggested by you..

**Comment by Pragya007** [comment]
@rafeca  Hey I am trying to change [this](https://github.com/desktop/desktop/blob/cd4cc7891f610ff378bc656540ac983e27fe3262/app/src/ui/lib/configure-git-user.tsx#L187) and trying to add type but it is showing only(text | password | search)

Should I add explicit validation?

**Comment by rafeca** [comment]
> @rafeca Hey I am trying to change this and trying to add type but it is showing only(text | password | search)

@Pragya007 oh interesting! our text input component doesn't define `password` as a valid type. You can safely add `password` to the list of valid types in:

https://github.com/desktop/desktop/blob/cd4cc7891f610ff378bc656540ac983e27fe3262/app/src/ui/lib/text-box.tsx#L45

**Comment by Pragya007** [comment]
Thanks!! @rafeca

**Comment by Pragya007** [comment]
@rafeca Kindly review this PR.
