### ISSUE TITLE
Ability to reset to previous commit

### ISSUE THREAD

**Issue by franktzheng** [desktop/desktop#10207]
### Describe the feature or problem you’d like to solve

I much prefer GitHub Desktop to using the CLI, and with basic rebasing functionality, I can do 90% of what I need in Desktop. The remaining 10% almost always involves resetting to a previous commit and cleaning up my changes, using `git reset`. It'd be great if this relatively simple functionality could be baked into the desktop application.

### Proposed solution

When right-clicking a commit, alongside "Revert this Commit" and "Create Tag," add an option to "Reset to this Commit," which simply runs the command `git reset <commit_hash>`. One downside is if the commits being reset have not been pushed upstream yet, it's not possible to undo this action. It's probably a good idea to pop up a warning in when this option is clicked (i.e. "Are you sure you want to undo the following commits? <list commits being reset> This action cannot be undone.").

**Comment by rafeca** [comment]
Thanks for creating the issue @franktzheng !

Apart from reverting commits (which will create a new commit), Desktop currently offers the possibility to "undo" the latest commit, which will completely get rid of the commit and put its changes in the working copy:

<img width="672" alt="Screen Shot 2020-07-15 at 13 42 40" src="https://user-images.githubusercontent.com/408035/87541160-1bffba80-c6a1-11ea-97c3-96410ec5df18.png">

We only allow undoing the latest commit when it has not been pushed to the remote yet. This is to guide users to revert commits that have been pushed rather than deleting them (since deleting a commit that have been pushed can have unintended side-effects to other collaborators).

Regarding resetting to a specific commit, I don't think we want to go to that path: we could totally enable such feature if resetting to that commit would not cause pushed commits to be deleted, but in that case the user can also undo the needed commits until they get to the desired commit (it's going to be a few more clicks, but we don't believe it's a common enough action to justify adding another context menu item to commits).

I'm going to close this issue for now since I don't think we're going to work on this in the immediate future, but in order to get a bit more context for the future, in which scenarios do you usually reset to an old commit? is it to remove recent commits that you've done or there are other scenarios where you do this?

Thanks!

**Comment by franktzheng** [comment]
Thanks for the response @rafeca. I think that's understandable, given the lack of other unsafe actions in Desktop right now.

As for why I would find this feature useful, I'm sure this does not apply to everyone, but I often find that the order I work on things doesn't necessarily match the order I'd like commits in a PR. For instance, I might work a bit on part A -> work a bit on part B -> work a bit on part A, and I'd like the commits to be AB rather than ABA. I do use the undo feature a lot here, but if I've ever already pushed upstream (I think there are other actions, maybe rebasing, that also cause this), I can't undo anymore. I'm not really sure how other people work, but [this does seem like a feature people do use](https://stackoverflow.com/questions/34790794/going-back-to-a-previous-commit-in-github-desktop).

**Comment by rafeca** [comment]
Thanks for the information @franktzheng ! It helps a lot to understand the workflows that our users follow.

> Also I'm not sure how contributions work here, but if you ever do change your mind in the near future I would be willing to work on this issue.

We'll take this into account! 👍
