### ISSUE TITLE
Custom Repository Group

### ISSUE THREAD

**Issue by lekhasy** [desktop/desktop#10201]
### Describe the feature or problem you’d like to solve

I'm currently working on several projects. Each project has a set of repos (about 5-7 repos).
The problem is there are too many repo on repository list, which make it pretty hard to find one.
Although filter box is pretty good, but i'm just tired typing and typing and typing finding my repo because i have to switch between repos very often.
So, when switching between projects, i would like to focus only on relevant repos.

### Proposed solution

So, it would be nice if i can create a repository group, adding/ removing repos to/from the group.
Also, i would like to have a way to focus on that group only: I can click on a "focus" button next to the group name and github desktop will only show repos of that group. I can click on the "back" button to exit focus mode.
Note that we can add one repo to several groups.

**Comment by rafeca** [comment]
Thanks for the feedback @lekhasy ! 

@OysteinAmundsen Thanks for the suggestion!

We took this scenario into account as part of #6460, which included a range of possibilities and trade-offs that were made to accommodate multiple requests and features around repository organization. At this point, we are holding off on adding custom grouping for now.

We have previous issues, like [this one](https://github.com/desktop/desktop/issues/2038) or [this other one](https://github.com/desktop/desktop/issues/10157) that cover pinning favorite repositories which looks like would be useful for you. They are closed at the moment since we don't have immediate plans to work on this but they will get reopened when the time comes to re-examine repository organization.

I'm going to close this issue for now, since as I mentioned we don't have immediate plans to implement custom repository grouping.

Thanks for using Desktop!

**Comment by ghnp5** [comment]
I was just coming here to suggest the exact same.  @lekhasy   @rafeca

Either create our own grouping/folders for organizing the repos,
or at least GitHub Desktop could group the repos based on the folder they're at.

So, if we have some directory structure like:

Repos
- Partners
   - Repo 1
   - Repo 2
- Common
   - Repo 3
   - Repo 4
- DevTools
   - Repo 5
   - Repo 6
- ProjectSomething
   - Repo 7 Web
   - Repo 8 API

GitHub Desktop could have an optional View to reorganize and sort repos this way.
