### ISSUE TITLE
Cant able to fetch the changes after initial clone

### ISSUE THREAD

**Issue by Arulprasanna5** [desktop/desktop#10203]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Steps to reproduce the behavior

1. Go to 'GitHub Desktop'
2. Click on 'Pull Origin.'

### Actual behavior -- git: 'remote-https' is not a git command. See 'git --help'.

A clear and concise description of what actually happened.

Add screenshots to help explain your problem, if applicable.
![Git issue](https://user-images.githubusercontent.com/65146321/87411601-97039b00-c5e5-11ea-81ce-ff27987f3b5c.PNG)

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by rafeca** [comment]
@Arulprasanna5 thanks for the report.

Often this is caused by an issue with your installation of GitHub Desktop. Could you try performing a fresh installation of GitHub Desktop by following these steps?

Here's how to do that:

1. Close GitHub Desktop
2. Open File Explorer
3. Go to `%LocalAppData%` and delete the `GitHubDesktop` directory
4. Reinstall GitHub Desktop from http://desktop.github.com

Let me know if that does not get things working.
