### ISSUE TITLE
Switched branches from A to B, instead brought changes from B to A

### ISSUE THREAD

**Issue by hsdonkin** [desktop/desktop#10217]
### Describe the bug

Used the desktop app to switch branches, and instead I could see I was on branch A with branch B changes added for a potential commit.

### Version & OS

V2.5.2 
OSX 10.12.6

### Steps to reproduce the behavior

Switch branches

### Expected behavior

Switch from branch A to branch B, leaving changes behind.
Not have my changes on branch B present on branch A!

### Actual behavior

Still on branch A, but with changes from branch B present.

### Screenshots

Branch B should not have any files named "Fully", but here we are
![image](https://user-images.githubusercontent.com/49598076/87691686-bc0c2100-c73f-11ea-871b-d2404f68f03d.png)
.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.
[2020-07-16.desktop.production.log](https://github.com/desktop/desktop/files/4932526/2020-07-16.desktop.production.log)

**Comment by rafeca** [comment]
Thanks for filing this report @hsdonkin!

Is it possible that these files were ignored in branch A but not in branch B, so when switching branches you see them as added files?

I have a couple of questions to be able to investigate the issue:

1- What happens if you switch back branches?
2- What are the contents of your `.gitignore` file in both branches?

Thanks!

**Comment by tierninho** [comment]
@hsdonkin  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
