### ISSUE TITLE
Authentication Error Occured

### ISSUE THREAD

**Issue by MoonCodeing** [desktop/desktop#10222]
### Describe the bug

Authentication Error Occured
"Requires Authentication"

### Version & OS

Version 2.5.3 and Windoows 10

### Steps to reproduce the behavior

1. Go to Repository
2. Click on Publish Repository
### Expected behavior

It should just publish

### Actual behavior

Instead asks for "Authentication"

**Comment by steveward** [comment]
Thanks for the report @MoonCodeing. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by steveward** [comment]
Closing this issue out due to inactivity @MoonCodeing. If you are able to upload a log file to provide more information we would be happy to revisit it.
