### ISSUE TITLE
Whitelabeling github desktop

### ISSUE THREAD

**Issue by HarvsG** [desktop/desktop#10249]
### Describe the feature or problem you’d like to solve

I hope to run a branded coporate git server and would like to use a GUI client for some of my users. Currently the github desktop client supports non Github URLs but the branding and user-flow is very GitHub centred.

It would be great if I could edit the user-flow slightly and also whitelabel some of the apearance

### Proposed solution

If this is permitted then it would be great to great to create a `/custom` directory where users can customise certain elements and then re-build the application.

**Comment by steveward** [comment]
Thanks for the feedback @HarvsG. Changing the application in this way isn't something that we would likely ever do since its intention is to be a GitHub-focused application. Other users have forked GitHub Desktop and customized it in various ways, so that would be my best recommendation if you want to try things out. I'm going to close this out, but thanks for using GitHub Desktop!

**Comment by HarvsG** [comment]
@steveward Would you be able to point me in the direction of one of these forks

**Comment by steveward** [comment]
@HarvsG some examples would be [GitHub Desktop portable](https://github.com/daemondevin/GitHubDesktopPortable) and the [unofficial Linux fork](https://github.com/shiftkey/desktop). We just ask that you abide by the [MIT license](https://github.com/desktop/desktop#license).
