### ISSUE TITLE
GitHub Desktop Windows application doesn't refresh and show repositories created on github.com

### ISSUE THREAD

**Issue by jadivinayak** [desktop/desktop#10307]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by steveward** [comment]
Thanks for the report @jadivinayak. Just to clarify the issue -- when you go to `File` > `Clone Repository` you are not seeing the repositories associated with your GitHub account? 

Could you upload the log file from GitHub Desktop so that I could get some more information about this issue? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`. The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by niik** [comment]
Thank you for your issue!

We haven't gotten a response to our questions.
With only the information that is currently in the issue, we don't have enough
information to take action. I'm going to close this but don't hesitate to reach
out if you have or find the answers we need, we'll be happy to reopen the
issue.
