### ISSUE TITLE
Button to commit should reflect name of the current branch

### ISSUE THREAD

**Issue by Lmpessoa** [desktop/desktop#10318]
### Describe the feature or problem you’d like to solve

While the app correctly displays the name of the current branch on top of the screen, the button to commit says "Commit to **master**" (bold is not mine but the app's doing). That pulled me from using the app to commit since I had the impression the commit is going to be made to the master branch instead of the current branch (used the command line for this commit).

### Proposed solution

Change the commit button label to "Commit to %branch" where %branch is the name of the currently active branch.

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.
![Screenshot](https://user-images.githubusercontent.com/151406/89287967-3dfab600-d62b-11ea-98c4-64a2c279b5c0.png)

**Comment by steveward** [comment]
@Lmpessoa thanks for the report. The branch name in the commit button should update when you change branches, so this looks like a bug. Are you able to reproduce this in multiple repositories? Are you running Windows or macOS? 

I was unable to reproduce this issue on my machine.

**Comment by Lmpessoa** [comment]
I tried reproducing and found this out: By switching to the branch inside the app the button updated correctly, but when I created the branch from the command line and just then opening the app it recognised correctly the current branch but did not change the button label. The app was closed when the branch was created and showed up like the screenshot when open.

**Comment by niik** [comment]
I was able to reproduce this when the branch in question was unborn (i.e had no commits yet).

### Steps to reproduce

- `git init test`
- `cd test`
- `git checkout -b 'im-an-unborn-branch`

<img width="483" alt="image" src="https://user-images.githubusercontent.com/634063/89321993-ea688680-d683-11ea-8417-7ca1377cc2a8.png">

This seems to be because we (rather sloppily) fall back to `master` when don't have a current (born) branch, see

https://github.com/desktop/desktop/blob/development/app/src/ui/changes/commit-message.tsx#L482

Gonna open a PR to address this

**Comment by Lmpessoa** [comment]
I guess this is it. Since the branch I was on was an orphaned one, might fall on the same spot.

**Comment by SR2374** [comment]
My laptop todhiba 7 udgrade to windows 10 but is too much slow
