### ISSUE TITLE
Unable to Commit Changes to branch or master

### ISSUE THREAD

**Issue by pranesh-n** [desktop/desktop#10329]
### Describe the bug

Unable to commit changes from Github desktop

### Version & OS

Version 2.5.3on Windows 10.0.18362

### Steps to reproduce the behavior

1. Click Commit to <branch> (edit) 

### Expected behavior

Expect changes to commit to branch

### Actual behavior

Error message pops up. Seen in log also

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

attached
[2020-08-05.desktop.production.log](https://github.com/desktop/desktop/files/5028137/2020-08-05.desktop.production.log)

**Comment by steveward** [comment]
Thanks for the report @pranesh-n. It looks like you are running into https://github.com/desktop/desktop/issues/3034. 

Here's the error in the log file (that is showing for a large number of files):

`warning: LF will be replaced by CRLF`

For repositories that are shared between different operating systems we recommend adding the line `* text = auto` to your `.gitattributes` file. This will normalize your line endings, but you will need to commit this change once it is made. See [this help article](https://docs.github.com/en/github/using-git/configuring-git-to-handle-line-endings) for some more information. I'm going to close this issue out since the underlying bug is already being tracked, but let me know if you continue to have any issues.

**Comment by pranesh-n** [comment]
Thanks for your note @steveward . I'll try the fix suggested. Just thought I'd let you know that I'm using this repository on just Windows, not another OS. 

The repository is using Jekyll

**Comment by pranesh-n** [comment]
Hello @steveward, my .gitattributes on local already had * text = auto. However, I'm still running into the bug.
