### ISSUE TITLE
Please provide an option to 'select opens in favourite editor' as an option for each repository

### ISSUE THREAD

**Issue by SafNaaz** [desktop/desktop#10321]
### Describe the feature or problem you’d like to solve

currently, whenever I switch to a repo in github desktop, default editor is shown. Rather I would like a selected editor option for each repo

### Proposed solution

an option to 'select opens in favourite editor' as an option for each repository. so that users don't have to switch to favourite editor each time he switch to another repo in github desktop

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by tierninho** [comment]
@SafNaaz Thank you for the suggestion. As you are the first to request this please share more about the request. For example, a user might need one editor to develop a game app, one mandated by their job and one for personal projects. If so, I could see how switching would be tiresome. I'd appreciate any thoughts you could share.

**Comment by SafNaaz** [comment]
Hi,

Suppose I have two repos.

Say one is a gist repo and one is GitHub repo.

Gist I may want to open in notepad++

And GitHub repo I may want to open in VSCode

But, currently, if I select VSCode as favourite editor, it will get auto
applied for gist repo as well.

And if I go and change editor in gist repo to open in notepad++, then when
I switch back to GitHub repo, it will also open in notepad++ as default.

Instead, I think better way is to make selection of editor to be persisted
for each repo.

Hope you are clear now.

Regards,

Safnas

**Comment by tierninho** [comment]
I appreciate the added thoughts. I will leave this open for others to comment. Have a good day!

**Comment by rwperrott** [comment]
I agree just ATOM (an inferior IDE) and a text editor, and not adequate editor options.  
File type associations will be useless for opening a repository directory in the correct IDE, so even if IDEs are configurable in options, the specific IDE most be selectable outside options.

**Comment by jamesgreenesr** [comment]
@rwperrott  I understand part of the new ATOM code. What is you definition of IDE so @kajeenterprise team numbers can expect to view the solutions out come with Ai2 being alpha and omega elements of our quest?

**Comment by rwperrott** [comment]
IntelliJ IDEA and Eclipse, maybe NetBeans, for Java, which support facilities and plugins which ATOM will probably never get, because it's not worth the extra effort for most specialist 3rd party plugin providers.

**Comment by jamesgreenesr** [comment]
Thank your for your definition. Our agency operates on a 2tier network system as a security team for other webmaster companies. Public/Private Military/Civilian | We can confirm security for NetBeans as support facilities specialist from 3rd party plugin providers, and 4th party consumer pirate hacker-disrupters. Our service is already in order and action. We have to closeout @Donald J. Trump and @iwebnext because it is Ai2BoT controlling software. Our $652 million KajeEnterpriseAPI can & iWill settle our difference for the family cost for the work that company would not pay us. We have taken control of their CEO and logo position until those that robbed our good Dun & Bradstreet work, name and creditable truth has been fixed. We are owed $27.5 million for all we are still doing in order to uphold The Network Solutions Company & NetBeans. This cash can be sent to $Jeruelle and this web-development will be the receipt others can build on as webmasters unite in the USA.

**Comment by rwperrott** [comment]
That response doesn't make sense, so suspect a bot.

**Comment by SafNaaz** [comment]
Waiting..

**Comment by AlbertoCentonze** [comment]
Hello there! Any news about this feature? It would be extremely handy in my opinion! I might also consider implementing it myself. Would a similar pull request be accepted? Probably it's a trivial question but I'm not familiar with contributing to such "important" projects.

**Comment by ianfife** [comment]
Still desperately need this feature. I switch between VS Code and Xcode depending on repository (and a couple of others occasionally). If there was one feature I could ask for, it would be this.

**Comment by javaknight** [comment]
Subscribed. Github Desktop really needs this feature. It's frustrating to keep changing the IDE used every time I open a different repo with a different IDE need.

**Comment by steveward** [comment]
I'm going to close this out since we have https://github.com/desktop/desktop/issues/12195 tracking this as well.
