### ISSUE TITLE
cloning problem

### ISSUE THREAD

**Issue by pilotmf** [desktop/desktop#10336]
### Describe the bug
i can't clone any repositorty
i can't clone any kind of repository
### Version & OS
windows 7 professional
Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by steveward** [comment]
Thanks for the report @pilotmf. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs...`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
