### ISSUE TITLE
Syntax highlighting is broken for new private property symbol in javascript/typescript 

### ISSUE THREAD

**Issue by Jaeiya** [desktop/desktop#10355]
### Describe the bug

When looking at a diff written in Typescript or Javascript, if there are any private class properties using the new `#` symbol, they are highlighted in a near unreadable red color.

### Version & OS

Windows 10
Github Desktop 2.5.3

### Steps to reproduce the behavior

1. Create a javascript/typescript file
2. Add a class with a private member using the new `#` symbol
3. Open the diff in Github Desktop

### Expected behavior

The diff should show proper syntax color highlighting.

### Actual behavior

All lines containing the new `#` symbol, color the code lines an almost unreadable red.

### Screenshots
![image](https://user-images.githubusercontent.com/2054218/89743081-74359c80-da54-11ea-894f-a22652971af8.png)

**Comment by niik** [comment]
Hey @Jaeiya, thanks for reporting this. GitHub Desktop uses the [CodeMirror](https://github.com/codemirror/codemirror) project for syntax highlighting. This issue appears to have been reported in https://github.com/codemirror/CodeMirror/issues/6249, fixed in https://github.com/codemirror/CodeMirror/commit/a67ed9a4ab810b1630e7d698362a3a33c96ca024, and subsequently released in CodeMirror 5.54.0.

GitHub Desktop currently uses [CodeMirror 5.49.2](https://github.com/desktop/desktop/blob/006d191eeb09792f1b4c4c7112780a2a018fb941/app/package.json#L24) so this issue should get resolved the next time we update CodeMirror. Unfortunately I don't think we'll get that into this next production release.

It would be really helpful if you'd be willing to update the [typescript](https://github.com/desktop/highlighter-tests/blob/master/typescript.ts) and [javascript](https://github.com/desktop/highlighter-tests/blob/master/javascript.js) test files in our highlighter-tests project to add this pattern so that we can verify that it's fixed once we update CodeMirror.

**Comment by mnznz** [comment]
gh repo clone all-contributors/all-contributors-bot
