### ISSUE TITLE
Fetch origin automatically

### ISSUE THREAD

**Issue by jiangwy17** [desktop/desktop#10360]
### Describe the feature or problem you’d like to solve

Fetch origin automatically.

### Proposed solution

Convenience.

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by tierninho** [comment]
@jiangwy17 Thanks for the suggestion. We do a fast forward merge for branches that you're not on as part of the auto-fetching process in the background, but not for your current branch because that can get dicey. This felt like a reasonable compromise and still does, so I'm going to close this as something we don't intend to support, but I'm curious why the current implementation is falling down for your use case.
