### ISSUE TITLE
Untrusted server issue when log in github account

### ISSUE THREAD

**Issue by BastenLi** [desktop/desktop#10377]
OS: Windows 10

As the screenshot shows, each time when try to log in, the untrusted server issue occurred, even if clicked "add certificate" button.

**Comment by niik** [comment]
Hi @BastenLi, it seems the screenshot never made it. Could you try to upload it and a log file from GitHub Desktop so that I could get some more information about this issue? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue. Thanks!

**Comment by tierninho** [comment]
As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
