### ISSUE TITLE
File Added to .gitIgnore still shows up

### ISSUE THREAD

**Issue by mridulsood01** [desktop/desktop#10379]
### Describe the bug

We have two files in root names as following (without double quotes)
"jenkinsfile-mule"
"jenkinsfile-node"

If we right-click and add them to .gitignore it still shows up in the Git Hub desktop as changed files.

Secondly, same files if we discard shows back up with the first name as capital i.e.
"Jenkinsfile-mule"
"Jenkinsfile-node"

### Version & OS
Version 2.5.3
Windows 10 Pro

Open 'About GitHub Desktop' menu to see the Desktop version. Also, include what operating system you are using.

### Steps to reproduce the behavior

1. Clone a new Repo from github 
2. Without any changes two files come up as modified namely "jenkinsfile-mule"
"jenkinsfile-node" which are present in the root of the repo
3. If these files are discarded they again show up as modified but first letter changes to capital
4. If these files are added to .gitignore still they are showing up in Github desktop.

### Expected behavior

If files are added to .gitignore they should not show up as modified in git hub desktop

### Actual behavior

After adding files to .gitignore they show up as modified in git hub desktop hence gitignore is not parsed and ignoring the files

### Screenshots

Step 1: right after cloning a fresh repo (no modification done)
[
![image](https://user-images.githubusercontent.com/49532274/90241131-1637f900-de48-11ea-937b-60c37a932464.png)
](url)

Step 2: Creating a new testfile for comparison going forward
![image](https://user-images.githubusercontent.com/49532274/90241191-310a6d80-de48-11ea-9645-76e6a36a2612.png)

Step 3: Adding all three files to gitignore by right clicking and adding
![image](https://user-images.githubusercontent.com/49532274/90241266-51d2c300-de48-11ea-9fe4-8eb0ce04d00b.png)

Step 4: testfile gets removed once it is added to gitignore, however other two files still show up in the github desktop

### Logs

[2020-08-14.desktop.production.log](https://github.com/desktop/desktop/files/5074127/2020-08-14.desktop.production.log)

**Comment by niik** [comment]
Hi @mridulsood01, sorry to hear you're having issues. I believe this is due to those two files already having been committed to the repository. Git will not ignore a file that is already tracked in the repository.

In order to not have the files be tracked you would have to first move the files outside of the repository directory. This will cause Git to believe they've been deleted. You then make a commit recording that removal and causing the files to not be tracked any more. You can then move the files back into the repository and they will no longer show up as modified files (if you don't care about the contents of the files you can straight up delete the files as well).

I hope that helps!

xref https://github.com/desktop/desktop/issues/2923

**Comment by pigravity** [comment]
2021 and bug still persists. What a fancy app it is !
