### ISSUE TITLE
Not being able to switch accounts

### ISSUE THREAD

**Issue by JinstoNim** [desktop/desktop#10406]
So, I am trying to switch accounts on github, I've closed it, I've uninstalled it, and it still didn't allow me to switch my account

**Comment by steveward** [comment]
@JinstoNim you can switch accounts in GitHub Desktop by going to `File` > `Options` > `Accounts`. I hope that helps!

**Comment by JinstoNim** [comment]
I already did that, so many times

**Comment by steveward** [comment]
@JinstoNim are you having issues logging in? Any details you can share about the problem you are experiencing would be helpful.

**Comment by JinstoNim** [comment]
Whenever I log out, it still keeps me in as my first account, and, all of the files show, I can log in to another account, and when I try to download anything from my last account, it just gives me an error, it seems as if it is completely visual, but I can't see any files that are from my second account.

**Comment by steveward** [comment]
Could you share a screenshot of what you are seeing? 

When you log out of your account in GitHub Desktop all of the local repositories will remain. You also need to make sure that you modify the email address in `File` > `Options` > `Git` so that it matches the email address of your currently logged in GitHub account. My guess is that you are seeing commits appear as your secondary user due to not updating the email address. We have some plans to address this in the future but I don't have a timeline for when that may happen. See this help doc for some more information about commit attribution:

https://docs.github.com/en/github/committing-changes-to-your-project/why-are-my-commits-linked-to-the-wrong-user

**Comment by steveward** [comment]
It would also be helpful if you could upload the log file from GitHub Desktop.

To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
