### ISSUE TITLE
Discard changes keep on crushing

### ISSUE THREAD

**Issue by yaliharel10** [desktop/desktop#10428]
I accedently put the repository in the wrong place, in the Github Desktop app. But new the app wants to sync all of my files. When I discard all of my changes my laptop keeps on crushing because it can't remove 80000 files at once. I've also tryed to use git bash using the comand git reset --hard but it didn't seem to work, further more git clean -fd dosen't delete any changes. And I can't even delete the repository.

**Comment by steveward** [comment]
@yaliharel10 did you accidentally create a repository in a system directory? If so, I would recommend navigating to that directory and deleting the hidden `.git` directory. This will allow you to remove the repository from GitHub Desktop since it will no longer be detected. You can then create a new repository and store it in the correct directory. Let me know if that doesn't resolve this issue and we can look into it further.
