### ISSUE TITLE
Error could not read Username for 'https://github.com': terminal prompts disabled

### ISSUE THREAD

**Issue by gaurav24bisht** [desktop/desktop#10465]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by steveward** [comment]
@gaurav24bisht thanks for the report. Please refer to our [help document](https://github.com/desktop/desktop/blob/development/docs/known-issues.md#ask-pass-trampolinebat-errors---2623-4124-6882-6789) for steps about how to resolve this issue on your machine. One of the more common causes has been the modified registry entries. Let me know if you have any questions about the steps. It would also be helpful if you could fill out the template in the issue body so that we can assist you further.
