### ISSUE TITLE
Can't update submodule in repo!

### ISSUE THREAD

**Issue by beanhacker** [desktop/desktop#10471]
### Describe the bug
    after i clone one repo which has submodule, i update the one file of submodule,  the github desktop appear  that the submodule i has updated  has one update should to be commited, content as below:
        Subproject commit 8be2d4c755347c68e513f471d786ec4aa24ea2e0
       Subproject commit 8be2d4c755347c68e513f471d786ec4aa24ea2e0-dirty
   
but when i submit this update, it get me a notice that  
     Commit failed - exit code 1 received

then i want to discard this change, when i do this on update line, my update in submodule has discard,  but it still notice me that i have one update wait to be submitted.

so i mean after i have update the submodule, the repo then can not be used never!!!

questions are below:
why my submodule can not update in github desktop?
why one submodule update caused repo can not be used?

### Version & OS
   github desktop: 2.5.4

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by steveward** [comment]
Thanks for the report @beanhacker. The bug with not being able to commit submodule updates is being tracked in https://github.com/desktop/desktop/issues/1770. The inability to discard a submodule is being tracked in https://github.com/desktop/desktop/issues/10403. We're also tracking submodule improvement in https://github.com/desktop/desktop/issues/7523 -- please follow along there for updates.

My best recommendation would be to work with submodules from the command line -- see https://git-scm.com/book/en/v2/Git-Tools-Submodules for a helpful resource. You can also try adding the submodule directly (see https://github.com/desktop/desktop/issues/1770#issuecomment-673734293) and then committing the changes in GitHub Desktop. I'm going to close this out since these issues are being tracked elsewhere, but let me know if you have any other questions.
