### ISSUE TITLE
Repository unavailable due to DMCA takedown still visible in Desktop app

### ISSUE THREAD

**Issue by jerry1333** [desktop/desktop#10475]
### Describe the bug

Repository unavailable due to DMCA takedown is still visible in Desktop app but unavailable to clone (asks for username and password).

### Version & OS

Version 2.5.4 & Windows 10

### Steps to reproduce the behavior

1. Clone repository that has been taken down due to DMCA
2. App asks for username and password and don't clone repo.

### Expected behavior

Don't show repositories taken down due to DMCA takedown.

### Screenshots
![Adnotacja 2020-08-30 212855](https://user-images.githubusercontent.com/984193/91667846-d6d80080-eb07-11ea-8028-7e4098437a7b.png)

![Adnotacja 2020-08-30 212557](https://user-images.githubusercontent.com/984193/91667794-69c46b00-eb07-11ea-9a6a-a8c735a50879.png)

### Logs

I think its not needed.

### Additional context

Sample repository: https://github.com/jerry1333/drpdecompress

**Comment by dhunmoon** [comment]
Access to this repo is disabled but the repo is still not deleted from GitHub why it shows in your list and since access to the repo is restricted you are not allowed to Clone it.

**Comment by steveward** [comment]
@jerry1333 thanks for contributing. What @dhunmoon said is correct -- when a repository is flagged due to a DMCA takedown it is not fully deleted from GitHub, which is why it is still showing up in the list. Since DMCA takedowns aren't an overly common occurrence this isn't something that we will likely try to account for in GitHub Desktop.

You can [delete the repository](https://docs.github.com/en/github/administering-a-repository/deleting-a-repository) and then click the refresh spinner in the repository list in GitHub Desktop -- that should remove the entry.

**Comment by jerry1333** [comment]
I agree that this is not common but why show something I can't clone?
Second this is inconsistent with github.com user page where this repositories are not shown.
And last one - I cant delete this repository - there is no repository settings option avalible.
![Adnotacja 2020-08-31 194727](https://user-images.githubusercontent.com/984193/91750103-d0f32580-ebc2-11ea-8b7b-7de7c0ea99d4.png)

**Comment by steveward** [comment]
@jerry1333 apologies, I forgot the delete option was not available for DMCA takedowns. You can [contact support]( [GitHub Support](https://support.github.com/) and they should be able to assist you with removing the repository. If this issue is something that comes up a lot we may consider better ways to handle it, but as we are a small team we need to prioritize what we work on. Thanks again for reporting this and using GitHub Desktop.

**Comment by jerry1333** [comment]
Understood, just keep it in mind for future 👍

**Comment by dhunmoon** [comment]
The reason you can not delete a DMCA content because it can be used in further review from your side so that you can challenge it or from the side who raised the DMCA.

**Comment by frozzicold** [comment]
ja gey

**Comment by frozzicold** [comment]
ja gey
