### ISSUE TITLE
Have to left click and hold to "select branch to compare" in Windows UI - single or double click not working

### ISSUE THREAD

**Issue by DennisWormald** [desktop/desktop#10479]
Have to left click and hold to "select branch to compare" in Windows UI - single or double click not working

### Version 2.5.4 on Windows 10 most recent update - this problem didn't happen with the last version.

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Steps to reproduce the behavior

1. Go to Windows UI in repository with 2 or more branches that are currently identical
2. Make a change to the active branch 
3. Click "Commit to $branch_name"
4. On the "Current branch" menu, click and select any other branch
5. Click on "history" on the left tab/pane
6. Click on "Select branches to compare"
7. Left click (or double click) on the previous branch you were just on (under "Recent branches")
8. See error

![error](https://user-images.githubusercontent.com/29453368/91788505-b61ac280-ec4f-11ea-8964-29a864b39507.jpg)

### Expected behavior

You should be able to see the merge into "other branch name" button at the bottom of the left pane
![Expected](https://user-images.githubusercontent.com/29453368/91788501-b450ff00-ec4f-11ea-8597-92167b2b03a0.jpg)

### Actual behavior

You can't see the merge into "other branch name" button at the bottom of the left pane

### Additional context

If you click and hold you can sometimes get it to work, but its unpredictable.

**Comment by rafeca** [comment]
Thanks for the report @DennisWormald ! I've been able to reproduce it on macOS as well.

It's quite possible that the issue got introduced by https://github.com/desktop/desktop/pull/9977. Interestingly, I can't see the issue on my development version of Desktop, only in the production one, so it may be some caused by some race condition of events.

**Comment by rafeca** [comment]
Update: I've been able to reproduce in my development version (it just not reproduces 100% of times there), and tried reverting #9977 and is still reproducible, so the issue may come from a different change

**Comment by dhunmoon** [comment]
@rafeca This is not a new bug I have experienced something similar in the past as well. it goes way deep. At that point in UI if you double click instead on the single click it goes to the point where you can see `Behind` and `Ahead` changes.
 #10473 This bug is also along the same line. 
 Not just that it goes a little bit deeper and there are many other small hiccups I generally face while comparing branches. I think it has something to do with how the state has been managed(I could be completely wrong though)

I will create a new Issue regarding what I have faced.(and maybe add it to here also)
