### ISSUE TITLE
how the hell does lfs work

### ISSUE THREAD

**Issue by HowTheHellDoIdoThis** [desktop/desktop#10470]
ok i want to clarify i know nothing about github. 
I am going to say some absolutely STUPID crap, And you all are probably going to be laughing at me. I have literally no idea where I am or how any of this works so just bear with me.

I'm using github for windows for collaboration in Unity because I don't like the filesize limit on unity's collab, and so when I got github for windows setup, I got surprised to see a n o t h e r stupid filesize restriction, like 100mb or something. So i googled it found github lfs. And downloaded the installer and installed it. So then I was like "well now what" and saw on the page, it said to "run 'git lfs install'". so like, what the hell? where am i supposed to be running this?

So then I throw myself down 16 more forum posts, and then eventually some youtube videos where I learn about this knockoff command prompt thing called git, that NO ONE EVER mentioned. so I install that, I run the commands, then I press the big blue push button on github windows, expecting it to magically work, which to no one's surprise, it didn't. I also learned that github windows doesn't even know where the hell git is. and then a find out through another youtube video that github for windows and mac already has it, with a screenshot of some older version of github MAC using it, and I go back to github windows. Ain't shit saying anything at all about lfs.

Was it using lfs this whole time? was 100mb just the limit for lfs? that seems dumb. please just tell me what I'm doing wrong because I'm sure there's like 30 things.

**Comment by dhunmoon** [comment]
# What is Git LFS?
If you have a file with size more than 100 MB then it becomes really difficult for Git to track changes on those files. That's where Git LFS comes in, in your Git you can track different file types to be managed as LFS then instead of putting those files with your repository Git creates a pointer to those files but the files are stored in Git LFS servers.

----
### Do you have Git installed and added to your path variable correctly?
You can check that by running `git --version` command in your `cmd`. If you have Git set up correctly you should see something like `git version 2.27.0.windows.1`, which means you have Git installed correctly.

### 1. Check whether your Git lfs is installed correctly or not.
You can do that by running `git lfs install` command in either `cmd` or `git-bash`(it comes with you git installation)
If not then follow the [link](https://docs.github.com/en/github/managing-large-files/installing-git-large-file-storage) below it will guide you how to install it [Installation Guide](https://docs.github.com/en/github/managing-large-files/installing-git-large-file-storage)

### 2. Configuring Large File storage
 Even if all the above steps are done GitDesktop doesn't automatically start tracking the large files you have to tell it which files to track
Follow the [link](https://docs.github.com/en/github/managing-large-files/configuring-git-large-file-storage) it will guide you how to [configure lfs](https://docs.github.com/en/github/managing-large-files/configuring-git-large-file-storage)

#### A quick summary of what you will find on the page.
1. `git lfs track "*.prefab"` run this command from your repository folder to add all `.prefab` files to get tracked as lfs. It should give you `Adding path *.prefab` as output if it worked fine.

### 3. Finally
After that is done it creates a '.gitattributes' file. now you can just do normal commit form either `cmd` or `GitDesktop` and you should be good.

**Comment by steveward** [comment]
@HowTheHellDoIdoThis thanks for contributing. Git LFS is [included with GitHub Desktop](https://docs.github.com/en/desktop/installing-and-configuring-github-desktop/about-git-large-file-storage-and-github-desktop), but there you will need to configure the tracked files via the command line or by editing your `.gitattributes` file directly. @dhunmoon shared some great information to help you get started, but let know if you have any specific questions about getting this working and I'd be happy to help. I'm going to close this issue out.

**Comment by HowTheHellDoIdoThis** [comment]
> @HowTheHellDoIdoThis thanks for contributing. Git LFS is [included with GitHub Desktop](https://docs.github.com/en/desktop/installing-and-configuring-github-desktop/about-git-large-file-storage-and-github-desktop), but there you will need to configure the tracked files via the command line or by editing your `.gitattributes` file directly. @dhunmoon shared some great information to help you get started, but let know if you have any specific questions about getting this working and I'd be happy to help. I'm going to close this issue out.

Thanks. If you don't mind me asking how am I supposed to edit gitattributes? notepad won't let me save things in github's program files folder apparently and just says to contact myself.
