### ISSUE TITLE
[FEATURE_REQUEST]: Ability to view the list of all stashes available in a branch

### ISSUE THREAD

**Issue by happyvig** [desktop/desktop#10481]
### Describe the feature or problem you’d like to solve

Since stashing is one of the commonly used operations, it would be very helpful if we can add the ability to view the **list of all stashes available in a branch**, in addition to the showing **only the top most stash**.

![image](https://user-images.githubusercontent.com/2972622/91835116-8d51f780-ec66-11ea-9cf2-de6b0154b058.png)
### Proposed solution

List all available stashes in the branch beneath the currently showing top most stash.

**Comment by dhunmoon** [comment]
@happyvig , I don't think that you can have multiple stashes on a branch in GitDesktop if you stash a change and you have an existing stash then it gets overwritten with the new stash.  correct me if I am wrong 😄 .

Stash created by GitDesktop generally has a description structure `!!GitHub_Desktop<branch-name>`.  Even if you save multiple stashes via `git bash` or `cmd` it still shows the latest stash item with the description `!!GitHub_Desktop<branch-name>`.

**Comment by tierninho** [comment]
> I don't think that you can have multiple stashes on a branch in GitDesktop if you stash a change and you have an existing stash then it gets overwritten with the new stash. correct me if I am wrong

This is correct. Only one stash per branch.

Thank you for the suggestion!

**Comment by nikita-kiryanov** [comment]
@tierninho Why maintain such a limitation? Isn't it easier to just `git stash -u` when the stash command is invoked, `git stash list` the contents of the stash in another tab, and `git stash pop` whatever the user selected to click restore on? I constantly find myself having to go back to the command line because I want to stash something without overwriting something I previously stashed.
