### ISSUE TITLE
unable to select multiplefiles and commit

### ISSUE THREAD

**Issue by VaishnaviNallagari** [desktop/desktop#10480]
![image](https://user-images.githubusercontent.com/62652357/91824839-08141600-ec59-11ea-84a9-166def0c3b43.png)

**Comment by niik** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

From the image you've sent it's hard to say what's going on but the commit button is disabled due to the required summary text field being blank.

Thanks for understanding and meeting us half way :grinning:
