### ISSUE TITLE
i am trying from decade to click on commit to master button but it's not responding

### ISSUE THREAD

**Issue by Chikus9** [desktop/desktop#10498]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by niik** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by dhunmoon** [comment]
#### The Commit button is disabled generally because of 2 reasons.
1. If you have selected nothin to commit.
2. If you have multiple files selected to commit and the `Summary` field has no value.
___Note__: For a single file, GitDesktop fills that field for you, but if you commit multiple files then you have to write it yourself_

> There is some other issue in that case Filling the bug report template and adding your Application logs helps Developers to identify and fix the issue in a much efficient way.

**Comment by tierninho** [comment]
As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
