### ISSUE TITLE
Enterprise GitHub Avatar and Name Are Incorrect on Pushed Commits

### ISSUE THREAD

**Issue by masongrosko** [desktop/desktop#10508]
### Describe the bug

When pushing commits from GitHub desktop to Enterprise GitHub the avatar and name are incorrect. 

Not sure exactly how to explain it. But instead of using the avatar and username of the enterprise account it is logged in to, it uses the last name of the author and credits them twice as two different users, with no avatar.

### Version & OS

Version 2.5.4, Windows

### Steps to reproduce the behavior

1. Create a change
2. Commit the change
3. Push the change to the remote
4. Visit GitHub enterprise and see the mistake

### Expected behavior

In previous versions the pushed commits would get the user avatar as well as the username of the enterprise account, and show them alongside the commits.

### Actual behavior

In this version the pushed commits get no avatar, they just take my last name as the author name and it credits me as two different users?

### Screenshots

A commit from Version 2.5.3
![image](https://user-images.githubusercontent.com/69281238/92246704-bef7d800-ee8b-11ea-975a-87c75f97539b.png)
![image](https://user-images.githubusercontent.com/69281238/92247024-3a598980-ee8c-11ea-9f6a-7d1390dea770.png)

A commit from Version 2.5.4
![image](https://user-images.githubusercontent.com/69281238/92246850-f6668480-ee8b-11ea-8dab-d5f7c2bfeaff.png)
![image](https://user-images.githubusercontent.com/69281238/92246926-0da57200-ee8c-11ea-9573-148c2d45f6a3.png)

### Logs

I do not believe this is applicable, let me know!

### Additional context

I wonder if it has anything to do with [this commit](https://github.com/desktop/desktop/commit/3930a70d844a81ea053bb41a8ebac0faeab404d0#diff-f483f44c73d1d234dccbf71543e76203L1158-L1163)

**Comment by niik** [comment]
Hi @masongrosko, sorry to hear you're having problems. It looks like the issue here is that the email address used for commits is not associated with the user on GitHub Enterprise. I would recommend looking at the raw commit details to see what email address those commits where made with. Looking at the commit screenshot above I imagine they're from a url similar to

`https://github.company.com/desktop/prototype/commit/f1042e697703dd986eda7a2bdf747117300d272f`

If you append `.patch` to that URL you should see the raw commit details, i.e:

`https://github.company.com/desktop/prototype/commit/f1042e697703dd986eda7a2bdf747117300d272f.patch`

Using the commit you linked to we can apply the same suffix and get 

https://github.com/desktop/desktop/commit/3930a70d844a81ea053bb41a8ebac0faeab404d0.patch

Looking at that patch you can see the name and email I used when creating that commit:

![image](https://user-images.githubusercontent.com/634063/92248494-15373c00-eec9-11ea-84fe-d49e2e520fcb.png)

You can configure the global user name and email in GitHub Desktop under the options dialog (mine says preferences because I'm currently on a mac):

![image](https://user-images.githubusercontent.com/634063/92248582-3730be80-eec9-11ea-804b-850fe5f90fb4.png)

Note that it's also possible to configure user and email on a per-repository level but not via GitHub Desktop. See also [this help article](https://docs.github.com/en/github/committing-changes-to-your-project/why-are-my-commits-linked-to-the-wrong-user) for more information.

Please let me know what you find. I doubt that this is a problem related to a regression within GitHub Desktop. The commit you linked to had to do with what avatar to show in the app itself. Due to technical limitation we're not able to load the avatar you configured in your GitHub Enterprise instance so we have to fall back to using gravatar based on the email address the commit was attributed to.

**Comment by masongrosko** [comment]
Ah okay that makes sense. The two commits are attributed to two different emails as you said.
![image](https://user-images.githubusercontent.com/69281238/92250954-bdc9a980-ee91-11ea-9fb1-4a43d4366212.png)
![image](https://user-images.githubusercontent.com/69281238/92250842-996dcd00-ee91-11ea-9af2-15d230610d29.png)


Adjusting the config solved the issue! However, the email was already set to be the .com email while the name was incorrect, adjusting the name to match screenshot 1 aligned it.
![image](https://user-images.githubusercontent.com/69281238/92250490-282e1a00-ee91-11ea-8c39-85d1012650e5.png)

Thanks for the quick help!

**Comment by WestVooD-sf** [comment]
> ### Describe the bug
> 
> 
> 
> When pushing commits from GitHub desktop to Enterprise GitHub the avatar and name are incorrect. 
> 
> 
> 
> Not sure exactly how to explain it. But instead of using the avatar and username of the enterprise account it is logged in to, it uses the last name of the author and credits them twice as two different users, with no avatar.
> 
> 
> 
> ### Version & OS
> 
> 
> 
> Version 2.5.4, Windows
> 
> 
> 
> ### Steps to reproduce the behavior
> 
> 
> 
> 1. Create a change
> 
> 2. Commit the change
> 
> 3. Push the change to the remote
> 
> 4. Visit GitHub enterprise and see the mistake
> 
> 
> 
> ### Expected behavior
> 
> 
> 
> In previous versions the pushed commits would get the user avatar as well as the username of the enterprise account, and show them alongside the commits.
> 
> 
> 
> ### Actual behavior
> 
> 
> 
> In this version the pushed commits get no avatar, they just take my last name as the author name and it credits me as two different users?
> 
> 
> 
> ### Screenshots
> 
> 
> 
> A commit from Version 2.5.3
> 
> ![image](https://user-images.githubusercontent.com/69281238/92246704-bef7d800-ee8b-11ea-975a-87c75f97539b.png)
> 
> ![image](https://user-images.githubusercontent.com/69281238/92247024-3a598980-ee8c-11ea-9f6a-7d1390dea770.png)
> 
> 
> 
> A commit from Version 2.5.4
> 
> ![image](https://user-images.githubusercontent.com/69281238/92246850-f6668480-ee8b-11ea-8dab-d5f7c2bfeaff.png)
> 
> ![image](https://user-images.githubusercontent.com/69281238/92246926-0da57200-ee8c-11ea-9573-148c2d45f6a3.png)
> 
> 
> 
> ### Logs
> 
> 
> 
> I do not believe this is applicable, let me know!
> 
> 
> 
> ### Additional context
> 
> 
> 
> I wonder if it has anything to do with [this commit](https://github.com/desktop/desktop/commit/3930a70d844a81ea053bb41a8ebac0faeab404d0#diff-f483f44c73d1d234dccbf71543e76203L1158-L1163)
> 
>
