### ISSUE TITLE
Every update, repositories are "lost"

### ISSUE THREAD

**Issue by Braunson** [desktop/desktop#10548]
### Describe the bug

Whenever there is a GitHub for Windows app update, on restart of the app, the repositories registered in the app (locally downloaded) are removed and I have to add every one of them back one by one which is annoying as there are 70+ of them.

~~Feature Suggest: Instead of allowing "Add an Existing Repository from your hard drive.." give the option to "Add multiple Repositories from a folder" so I can just select the entire local `/GitHub` folder if this is going to keep happening.~~ Looks like I can drag many repository folders into GH, still frustrating.

### Version & OS

Windows 10 Home
GH Desktop: 2.5.3

### Steps to reproduce the behavior

N/A

### Expected behavior

Post update and restart of the desktop app should still show my local downloaded repositories

### Actual behavior

Post update and restart of the desktop app does not show any local repositories anymore

### Screenshots

N/A

### Logs

```
2020-09-10T15:10:52.477Z - info: [ui] [AppStore] loading 0 repositories from store
2020-09-10T15:10:52.478Z - info: [ui] [AppStore] found account: Braunson (Braunson Yager)
2020-09-10T15:10:52.811Z - info: [ui] launching: 2.5.3 (Windows 10.0.18363)
2020-09-10T15:10:52.811Z - info: [ui] execPath: 'C:\Users\geekybeaver\AppData\Local\GitHubDesktop\app-2.5.3\GitHubDesktop.exe'
2020-09-10T15:10:53.096Z - info: [ui] Stats reported.
```

### Additional context

N/A

**Comment by niik** [comment]
Hi @Braunson, thanks for opening this. This is the first time I've heard about tracked repositories being lost when updating the app. How long has this been happening? I see that you're on a release that's two versions behind, is that because you've been avoiding upgrading?

Is there any other information you can tell us about your system that could explain this? The repositories are stored in the `AppData\Roaming\GitHubDesktop` folder. Can you see any reason why that folder would be affected by an upgrade?

**Comment by Braunson** [comment]
@niik This has been happening for the last 3+ updates. It says I'm up to date (there was an auto-downloaded update yesterday that had me click "restart" to restart the app). I'd rather be up to date.

See https://bit.ly/2DNmDFZ is what I see after clicking About > Check for update.

The repositories themselves are actually stored in `C:\Users\geekybeaver\Documents\GitHub`. I can't see any issue at all, I have more than enough disk space (saw that mentioned on another issue). I have a typical Win 10 system, nothing fancy. I use the GitHub for Windows Desktop GUI as well as the CLI occasionally.

**Comment by niik** [comment]
@Braunson just to be sure since we've had a few issues previously with people installing the app from untrusted sources (including the Microsoft Store) do you know where you downloaded the app from? Could you do me a favor and uninstall the app completely following the steps below and then reinstall it from https://desktop.github.com. You should then be on version 2.5.5.

1. Close GitHub Desktop
2. Open File Explorer
3. Go to `%LocalAppData%` and delete the `GitHubDesktop` directory
4. Go to `%AppData%` and delete the `GitHub Desktop` directory
5. Reinstall GitHub Desktop from http://desktop.github.com

> The repositories themselves are actually stored in `C:\Users\geekybeaver\Documents\GitHub`

Ah, sorry, my response here was a bit hastily written. What I meant was that GitHub Desktop stores **the list of tracked repositories** within `AppData\Roaming\GitHubDesktop`.

**Comment by Braunson** [comment]
@niik Thank you. I've reinstalled things. I can confirm I did originally install GitHub Desktop from the desktop.github.com website. I guess we can close this until it happens again.

**Comment by steveward** [comment]
Dropping https://github.com/desktop/desktop/issues/8788 in here as a similar report since I stumbled upon it when searching  for a different issue.

**Comment by steveward** [comment]
Another instance in https://github.com/desktop/desktop/issues/11620.
