### ISSUE TITLE
Getting error when I am trying to push my branch

### ISSUE THREAD

**Issue by unknownchap** [desktop/desktop#10558]
I have got access to the repository which is not mine, I keep receiving this error even though I'm sure that I have access.
The error is as follows:
"The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed"

I am gonna attach the log.

Cheers
[2020-09-11.desktop.production.log](https://github.com/desktop/desktop/files/5205431/2020-09-11.desktop.production.log)

**Comment by tierninho** [comment]
@unknownchap Thanks for the report.

- I would attempt logout/login and try accessing the repo again. Are you cloning or performing another action?
- If you run into this, don't bother filling it out as the issue is likely elsewhere:
![Screen Shot 2020-09-10 at 3 44 37 PM](https://user-images.githubusercontent.com/14828183/92840403-be27e000-f37c-11ea-883f-ca6e3037ce51.png)
- If above doesn't work, try revoling Desktop access in your settings (https://github.com/settings/applications), then go to Desktop and re-auth by logout/login again, etc...

Let us know how it goes!

**Comment by unknownchap** [comment]
Thank you for your prompt response, 
I have cloned it on my mac, create a new branch, made some changes and I wanted to publish my branch. I just tried all the above solutions nothing works for me.

**Comment by tierninho** [comment]
Do you have any existing repos that you can verify that work okay (fetch/push/pull)?

I take you have access from the repo owner and you are not using a proxy?

Could be keychain issue. Workaround is:

- Open Keychain Access.app
- Right-click on the login keychain for Desktop and try locking it
- Right-click on the login keychain and try unlocking it
- Sign into your GitHub account again

**Comment by tierninho** [comment]
As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
