### ISSUE TITLE
Can't find "Folder"

### ISSUE THREAD

**Issue by crozdale** [desktop/desktop#10589]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by steveward** [comment]
Thanks for reaching out @crozdale!

Would you mind filling out the rest of the issue template so that we can better understand what is causing the problem you are experiencing? Without that information it will be difficult to help you further. It would especially be helpful if you could upload the log file from GitHub Desktop, which will give more details about the specific error you are seeing. 

To access the log files go to the  menu in GitHub Desktop and select `Help` > `Show Logs...`. The log files are created daily -- please send over a log file as an attachment from a day where you experienced the issue

**Comment by crozdale** [comment]
There is a 6.96 GB folder named My-Web-Sites on my desktop. It is located at C:\Users\HP\Desktop. I try to drag and drop it in my local Desktop Git  to a folder called /.gitignore because I want to push it to my Online Git repository so as to be shared with a collaborator. I get a response saying: Can't Find "My-Web-Sites"

**Comment by crozdale** [comment]
I expect the folder to be transferred to the destination

**Comment by steveward** [comment]
@crozdale thanks for sharing that. The `.gitignore` is a file, not a directory so you can't drag files into there. It's intended to be used to ignore specific files/paths in your repository. It sounds like you may have moved your `My-Web-Sites` repository somewhere else -- I would try searching for it in File Explorer and then moving it to something like `C:\Users\HP\GitHub`. You should be able to use the `Locate` option in GitHub Desktop to navigate to the directory and add it.

**Comment by steveward** [comment]
I'm going to close this out as I believe my answer above should resolve your issue. Let me know if you are still having problems!
