### ISSUE TITLE
The History Tab shows my other account's display picture

### ISSUE THREAD

**Issue by syedhaffiz** [desktop/desktop#10614]
### Describe the bug

The History Tab shows my other account's display picture even though I made sure I have logged in with the proper account. It does not change even after closing or opening the App.

### Version & OS

Version 2.5.5 & Windows 10 Pro

### Steps to reproduce the behavior

1. Make sure you have two different accounts with different display pictures
2. Log into the first account, commit and push some changes
3. Now logout and log into the other account and commit and push some changes
4. Keep note of the display picture in the History Tab

### Expected behavior

Given display picture should be shown

### Actual behavior

The other profile's display picture is shown in the History Tab
In the below screenshot, the image with the face is not linked to this account. It belongs to a different account I signed in earlier.

### Screenshots

![image](https://user-images.githubusercontent.com/64581082/93818325-dbf81d80-fc77-11ea-90f0-96eee4a3f79f.png)

**Comment by steveward** [comment]
Thanks for the report @syedhaffiz. This is likely due to your old avatar being cached -- you should be able to fix this by manually deleting the `GitHubUserDatabase` in Developer Tools. Here's how to do that:

1. Go to the menu in GitHub Desktop and select `View` > `Toggle Developer Tools`
2. Go to `Storage` > `IndexedDB` > `GitHubUserDatabase`
3. Select `Delete database`
4. Close and restart GitHub Desktop

That should hopefully update your avatar -- let me know if it doesn't help.

**Comment by niik** [comment]
@steveward @syedhaffiz I wonder if this is actually related to the difference between the signed in account and the commit author information.

Please see https://github.com/desktop/desktop/issues/10608#issuecomment-695978826 and see if that applies to you scenario.

**Comment by steveward** [comment]
`@niik oh good catch -- I missed the "other account" part. @syedhaffiz please ignore my reply. When you log in with different GitHub accounts you need to make sure you update the email address in `File` > `Options` > `Git` so that it matches an email address used with your currently logged in account. See [this help article](https://docs.github.com/en/github/committing-changes-to-your-project/why-are-my-commits-linked-to-the-wrong-user). I'm going to close this out.

**Comment by syedhaffiz** [comment]
But can this email and name be changed automatically when the user signs with the account and not entirely related to Github Desktop like a constant?

**Comment by niik** [comment]
> But can this email and name be changed automatically when the user signs with the account and not entirely related to Github Desktop like a constant?

Not at the moment, no. We're looking at ways to make it easier to detect when there's a mismatch between the signed in account and the globally configured name and email (see https://github.com/desktop/desktop/issues/610) and we're evaluating other approaches but for the moment you need to manually update the commit author name and email when switching accounts.

**Comment by steveward** [comment]
@syedhaffiz the best workaround I have is use the [includeIf](https://git-scm.com/docs/git-config#_includes) feature of Git to use different .gitconfig files (i.e. for personal and work repositories).

**Comment by mahrcheen** [comment]
I had some random identicon after changing login and email - **deleting <username>\AppData\Roaming\GitHub Desktop helped me**
