### ISSUE TITLE
Logout and login new acc -> pull project -> commit still from old acc

### ISSUE THREAD

**Issue by hongocha** [desktop/desktop#10667]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by niik** [comment]
Hi, thanks for opening this. I suspect you are confusing **permissions** with commit **attribution**. Git allows you to set your email address to any known email address. I can find the email address of someone on GitHub and then impersonate them by using that email in my `.gitconfig`, but this does not mean that I have any sort of push access to their repositories. See [this help article](https://help.github.com/en/github/committing-changes-to-your-project/why-are-my-commits-linked-to-the-wrong-user) which states the following:

>Note: If your commits are linked to another user, that does not mean the user can access your repository. A user can only access a repository you own if you add them as a collaborator or add them to a team that has access to the repository.

When you log in with different GitHub accounts you need to make sure you update the email address in Options/Preferences so that it matches an email address used with your currently logged in account.

![image](https://user-images.githubusercontent.com/634063/93764250-12e81800-fc13-11ea-90a4-42b45f7c9b00.png)

I hope that helps clarify things.
