### ISSUE TITLE
Please add stage files

### ISSUE THREAD

**Issue by e1399579** [desktop/desktop#10668]
Sometimes i need compare staged code and unstaged code, it's very useful.

**Comment by niik** [comment]
Hi @e1399579, thanks for opening this.

GitHub Desktop has a long history of not exposing a staging area. I can see how it can be useful but it's an explicit design choice we've made in order to simplify the interface and it's not one that we're looking to change in the near term.

I hope there's still areas of GitHub Desktop that you find useful.
