### ISSUE TITLE
How do multiple local commit merge into a push?

### ISSUE THREAD

**Issue by yinzhenkun** [desktop/desktop#10673]
![image](https://user-images.githubusercontent.com/41945280/94406771-19433a80-01a5-11eb-9afc-e706dc683a73.png)

**Comment by niik** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by niik** [comment]
Closed in favor of #10674
