### ISSUE TITLE
Github

### ISSUE THREAD

**Issue by vodafone001** [desktop/desktop#10730]
https://www.github.com/ContributorCovenant/contributor_covenant/tree/release/LICENSE.md

**Comment by niik** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
