### ISSUE TITLE
Add visual feedback to the Pull origin button (UX issue)

### ISSUE THREAD

**Issue by kevincannon** [desktop/desktop#10749]
(👋 I read the guidelines and think this is the right place to post, but if not, please let me know where is best, thanks)

### Describe the feature or problem you’d like to solve
When you press the Pull Origin button, there is no pressed state, and there's no in-progress state.

This means that it feels like the button is broken because there is zero feedback to the user that anything is happening.

![github_desktop](https://user-images.githubusercontent.com/5065238/95329724-b4c06380-08a7-11eb-96e1-b697f9303adc.gif)

### Proposed solution

1. (quick fix) Add a mouse-down state
2. (slightly larger fix) Add a progress indicator while it's downloading.

### Additional context

Mockup of a rough solution:

![github_desktop](https://user-images.githubusercontent.com/5065238/95355636-0c6dc780-08c6-11eb-95c6-3df2f5f2060f.gif)

**Comment by niik** [comment]
Hi @kevincannon, thanks for opening this. Could you upload a log file from GitHub Desktop so that I could get some more information about this issue? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`.

The Pull button definitely has a progress mode already, see below from when I just clicked it on my machine

![2020-10-09 12-15-11 2020-10-09 12_17_31](https://user-images.githubusercontent.com/634063/95571870-6a66f000-0a29-11eb-8ce5-c47a0cc31ff5.gif)

So I believe something is up with your environment. How long have you been unable to pull changes?

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue. Thanks!

**Comment by kevincannon** [comment]
@niik Thanks for the reply, so it's a different issue than I thought.

Here's my logs for today, where I just opened the app, and pressed "Pull Origin" a few times. Everything else seems to be working fine though, I can switch branches etc. If I do a `git pull` via the command line the desktop app seems to update fine.

Hopefully it's useful.

[2020-10-12.desktop.production.log](https://github.com/desktop/desktop/files/5364541/2020-10-12.desktop.production.log)

**Comment by niik** [comment]
@kevincannon it seems your application credentials have gone stale or become corrupt causing errors when GitHub Desktop attempts to communicate with GitHub.com. Could you try signing out and back in again by going to the preferences dialog and see if that changes things for you?

```
2020-10-12T07:52:05.446Z - warn: [ui] fetchAccount: failed with endpoint https://api.github.com
Error: Bad credentials
    at Ne (/webpack:/app/src/lib/http.ts:170:11)
```

**Comment by kevincannon** [comment]
That seems to have worked. Thanks for the help.

It would be good to throw an alert or something in that situation, as I never would have figured that out.

**Comment by kevincannon** [comment]
Closing this ticket because it's not relevant any more.

**Comment by niik** [comment]
> It would be good to throw an alert or something in that situation, as I never would have figured that out.

Agreed, we don't have a good concept of whether an account is "valid" or not in the app and it's caused several confusing issue like yours in the past. Thanks for confirming that you got it working!
