### ISSUE TITLE
Switching branches never ending loop and heavy CPU load

### ISSUE THREAD

**Issue by jevail** [desktop/desktop#10744]
### Describe the bug

When switching branches via the button in the toolbar, or switching to a pull request, the button keeps alternating multiple times a second between the Current Branch and the requested branch. This continues sometimes for some seconds, sometimes endless, while the CPU is under heavy load.

### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Steps to reproduce the behavior

1. Go to main screen of GitHub Desktop
2. Click on 'Current Branch'
3. Choose a random branch

### Expected behavior

GitHub checks out the selected branch

### Actual behavior

The button alternating between current branch and requested branch multiple times a second.  

### Screenshots

Can't upload a video of the screen.
<img width="1220" alt="Schermafbeelding 2020-10-06 om 20 56 26" src="https://user-images.githubusercontent.com/24815508/95247676-6f078a80-0816-11eb-99e6-e29fe83352a3.png">

<img width="1043" alt="Schermafbeelding 2020-10-06 om 20 53 17" src="https://user-images.githubusercontent.com/24815508/95247319-002a3180-0816-11eb-9aef-5517bf5a9453.png">

### Logs

[2020-10-06.desktop.production.log](https://github.com/desktop/desktop/files/5336077/2020-10-06.desktop.production.log)

**Comment by steveward** [comment]
Thanks for reporting this @jevail. This behavior sounds similar to reports like https://github.com/desktop/desktop/issues/10733. I'm going to roll this into https://github.com/desktop/desktop/issues/10625 since we are tracking CPU issues there. We haven't been able to reliably reproduce this issue, but I appreciate the steps you shared as they are helpful in tracking this down.
