### ISSUE TITLE
UX: Improve repo chooser when several equal named projects are registered

### ISSUE THREAD

**Issue by staabm** [desktop/desktop#10766]
### Describe the feature or problem you’d like to solve

I clone a lot of projects. even cloning the same repo multiple times is a regular step in the current workflow (because e.g. some reposes are dependencies of other projects and thefore the same repos are cloned on different folders in the filesystem).

this results in a repo chooser like

![grafik](https://user-images.githubusercontent.com/120441/95562753-dc850800-0a1c-11eb-93ed-5821e9590e6c.png)

as you can already imagine its pretty hard to find the correct repo, as the chooser only show the repo name (which is equal for all locations).

atm. I need to hover all entries one by one to get a tooltip revealing the actual filesystem location, so I can find the one I am actually looking for.

### Proposed solution

I could think of different ways to solve this:

a) show the filesystem path when several equal named projects are in the game

b) allow to define a custom user chosen label per repo, so I can manually define what will show up in the repo chooser

c) I guess there are several others ways which might work

**Comment by steveward** [comment]
Thanks for the detailed feedback @staabm. I agree this is definitely not ideal for situations where you need to work with multiple copies of the same repository. We took this scenario into account as part of #6460, which included a range of possibilities and trade-offs that were made to accommodate multiple requests and features around repository organization. At this point, we are holding off on custom grouping and labeling for now. Since we don't have any current plans to change this I am going to close this out, but this will likely be something we revisit again in the future.
