### ISSUE TITLE
Stop using Electron as an install framework

### ISSUE THREAD

**Issue by EmberHeartshine** [desktop/desktop#10768]
### Describe the feature or problem you’d like to solve

GitHub Desktop is ostensibly for developers. You know, the kind of person who prefers control and customization over "it just works". The MSI installer is not a full solution as it still does not allow you to install to a chosen directory. At the moment it simply extracts GitHubDesktop.exe to %PROGRAMFILES% and does not actually install GutHub Desktop.

### Proposed solution

Electron is great for products that assume the end user doesn't know anything about file systems, the difference between user and Administrator mode, &c. Github for Desktop is not one of those products. One-click installers are frankly absurd for any project that targets developers as end users, and it's one of the things that makes [Atom](https://atom.io/) unappealing as well.

If you really want to keep using a one-click installer, at least give the MSI installer the option to set install directory via command line.

### Additional context

#4371 #1086 and frankly, any developer can tell you the same thing,

**Comment by niik** [comment]
Hi @EmberHeartshine, thanks for opening this. I appreciate that the lack of customization in the installer is troublesome for you and I'm sorry to hear that. Trying to find a balance between ease of use and customizability is tricky but [our philosophy](https://github.com/desktop/desktop/blob/development/docs/process/what-is-desktop.md) is to favor work that improves ease of use.

Even if that wasn't the case we're simply much too small of a team to maintain a custom installation option, we've tried that in the past and it's not a path we want to or are able to go down again.

As such I think the most productive thing to do here since this is something you really want from Desktop is for you to work with Electron and/or the Squirrel.Windows projects to come up with a installation and software update solution that would meet your needs and at the same time benefit all electron projects. I think that the VSCode team has been able to find a middle ground solution for Windows, perhaps that's something worth looking into?

I'm going to close this as opting out of the installation framework that Electron gives us isn't in the cards for the project at this time.

**Comment by EmberHeartshine** [comment]
Electron fails items 1, 3, and 4 of your core philosophy.

**Comment by Calinou** [comment]
Would providing a packaged ZIP archive *in addition to* the existing installer fulfill this use case? This is probably the simplest option that gives more control to the user at the same time.
