### ISSUE TITLE
Installed VIM and now getting failures about cygpath

### ISSUE THREAD

**Issue by larrywal** [desktop/desktop#10783]
I have been using Github desktop for Windows just fine for a long time.  Just installed VIM on this machine, and now checkins are barfing with the attached error.  Seems like maybe it's pointing gitHub desktop at the wrong git.exe?  Assuming so, what's the easiest way to fix it up?
![image](https://user-images.githubusercontent.com/43455985/95664928-9f924180-0b00-11eb-9027-c1687c88ce66.png)

**Comment by niik** [comment]
Similar to https://github.com/desktop/desktop/issues/9278

GitHub Desktop ships with an internal version of Git which we use for all actions inside the app. As such the environment within which your commit hooks execute will likely not exactly match that of your normal environment.

Unfortunately, without debugging this environment specifically it's hard to reason about what husky and/or the lint-staged script is having an issue with. Please take a look at  https://github.com/desktop/desktop/issues/9351 and see if the workaround in https://github.com/desktop/desktop/issues/9351#issuecomment-604425781 is applicable to your situation.

For now I'm afraid that's all we can do here. Sorry that I don't have a better answer for you but since this error doesn't come from Desktop I'm afraid you're going to have to debug husky/lint-staged to get to a solution

**Comment by larrywal** [comment]
@niik -- FYI FWIW changing my husky command from

"pre-commit": "lint-staged" to

"pre-commit": "npx lint-staged" fixed it.

Not sure if that helps.

**Comment by niik** [comment]
Glad to hear you got it working @larrywal, thanks for reporting back!
