### ISSUE TITLE
Thanks for the detailed report @nonsensery. I was able to reproduce this as well, and although I feel like this has been reported previously I was unable to find an existing issue (that may have been a bug with line selection, though).

### ISSUE THREAD

**Issue by VineGaming** [desktop/desktop#10781]
Thanks for the detailed report @nonsensery. I was able to reproduce this as well, and although I feel like this has been reported previously I was unable to find an existing issue (that may have been a bug with line selection, though).

_Originally posted by @steveward in https://github.com/desktop/desktop/issues/10743#issuecomment-705102352_

**Comment by niik** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
