### ISSUE TITLE
Smarter local path suggestion when cloning a repo

### ISSUE THREAD

**Issue by tooomm** [desktop/desktop#10794]
### Describe the feature or problem you’d like to solve
When cloning a repo, the local path is always the last known value and doesn't give a smart suggestion.
So all users have to adjust the given value because always reusing the last one most likely leads to problems. :)

### Proposed solution
The suggested local path should use the same org/repo pattern as the github source.

Is it just me derivating the local path from the repo url to manage the local storage better?
At least I'm sure nobody uses the same local path for different repo clones over and over again. :)

E.g. cloning `https://github.com/desktop/desktop` would end up in my local default path to store github stuff, followed by folders for the org and repo: `...\desktop\desktop`
At best the user could set a default local storage path e.g. c:\users\username\github\ and the clone dialog appends the org/repo style on top of that.

**Comment by niik** [comment]
Thanks for the suggestion @tooomm! 😃 

Having the repository owner as part of the path of the cloned project has been asked before in https://github.com/desktop/desktop/issues/8461 . We haven't seen many people requesting this change though, so right now we're not considering implementing it (we try to keep the configuration settings of Desktop as minimal as possible to not overwhelm our users).

Anyways, feel free to subscribe to https://github.com/desktop/desktop/issues/8461 to get updates, since we may revisit this in the future as we learn more from how people use Desktop and having one issue where all requests are cross-referenced to helps us gauge interest.

I'm going to close this issue in favor of https://github.com/desktop/desktop/issues/8461

**Comment by tooomm** [comment]
Thanks for linking the other issue.

>When cloning a repo, the local path is always the last known value 

As a users I always want to change that to not override stuff... Can we do something about that in between?
