### ISSUE TITLE
Windows - commit message profile picture does not update

### ISSUE THREAD

**Issue by jonivesto** [desktop/desktop#10802]
### Describe the bug

Profile picture next to the commit message input does not update if you log out and login into another account.

### Version & OS

Windows 10
GitHub Desktop Version 2.5.6

### Steps to reproduce the behavior

1. Have a repository open and user logged in
2. File->Options->Log out from the user account
3. Log into another user account
4. Profile picture next to the commit message input has not updated to the current account's profile picture.
5. Close and re-open the app
6. Profile picture still has not updated to the current account's profile picture.
7. Delete `C:\Users\jonivesto\AppData\Roaming\GitHub Desktop`
8. Open the app and log in
9. Profile picture still has not updated to the current account's profile picture.

### Expected behavior

Profile picture shows the current account's profile picture

### Actual behavior

Profile picture shows picture of the previously logged out user account.

**Comment by mannyg253** [comment]
What are u talking about

**Comment by niik** [comment]
> 4\. Profile picture next to the commit message input has not updated to the current account's profile picture.

Hi, thanks for opening this. I suspect you are confusing **permissions** (i.e accounts) with commit **attribution**. Git allows you to set your email address to any known email address. The picture next to the account in the options dialog is that of the currently signed in account whereas the picture next to the commit message box is that of the currently set up commit author . See [this help article](https://help.github.com/en/github/committing-changes-to-your-project/why-are-my-commits-linked-to-the-wrong-user) which states the following:

>Note: If your commits are linked to another user, that does not mean the user can access your repository. A user can only access a repository you own if you add them as a collaborator or add them to a team that has access to the repository.

When you log in with different GitHub accounts you need to make sure you update the email address in Options/Preferences so that it matches an email address used with your currently logged in account.

![image](https://user-images.githubusercontent.com/634063/93764250-12e81800-fc13-11ea-90a4-42b45f7c9b00.png)

I hope that helps clarify things.

**Comment by jonivesto** [comment]
Got it. Was a noob question after all😃
