### ISSUE TITLE
Error when uploading files

### ISSUE THREAD

**Issue by Damian294** [desktop/desktop#10817]
I get a error when pushing files to origin
![github fout](https://user-images.githubusercontent.com/65031458/95797479-f0b45800-0cef-11eb-9531-a7415ccc053b.PNG)

**Comment by Damian294** [comment]
I dont know what his means. I never have problems with github

**Comment by niik** [comment]
Hi @Damian294, it looks like you're trying to upload very large files to GitHub. The maximum individual file size on GitHub is 100Mb, see https://docs.github.com/en/free-pro-team@latest/github/managing-large-files/what-is-my-disk-quota for more information on quotas. If you want to track large files in Git we recommend you look into [Git Large File Storage](https://docs.github.com/en/free-pro-team@latest/github/managing-large-files/versioning-large-files).

Since this isn't a problem with GitHub Desktop specifically I'm going to close this and ask that you check out https://support.github.com for more information.
