### ISSUE TITLE
We couldn't find that repository. 

### ISSUE THREAD

**Issue by danny-xl8** [desktop/desktop#10827]
### Describe the bug

When cloning a repository (Note that repository is correct), it keeps getting an error. Error will be: We couldn't find that repository. Check that you are logged in, the network is accessible, and the URL or repository alias are spelled correctly. 

### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

Version 2.5.6 and macOS Mojave 10.14.6

### Steps to reproduce the behavior

1. Go to 'Github Desktop'
2. Click on 'Current Repository'
3. Click the 'Add dropdown'
4. Click the 'Clone Repository'
5. Type in your 'URL or username/repository'
6. Click 'Clone'
7. See Error

### Expected behavior

I keep getting the error several times and randomly the repository that I want to clone is getting cloned. 

### Actual behavior

When clicking on the Clone it keeps getting the Error: We couldn't find that repository. Check that you are logged in, the network is accessible, and the URL or repository alias are spelled correctly. 

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by niik** [comment]
Thanks for the report! Could you upload a log file from GitHub Desktop so that I could get some more information about this issue? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

If you could also provide a screenshot of the dialog including the URL that you entered that'd be helpful. Since you say that the clone eventually succeeds it sure sounds to me like connectivity problems.

Thanks!

**Comment by danny-xl8** [comment]
Here is the log from the day I experienced the issue. 
[2020-10-14.desktop.production.log](https://github.com/desktop/desktop/files/5387288/2020-10-14.desktop.production.log)

Here is the screenshot of the dialog and URL

![Screen Shot 2020-10-15 at 12 21 15 PM](https://user-images.githubusercontent.com/58492790/96176397-28362680-0ee1-11eb-90ba-98f1913d3408.png)

**Comment by niik** [comment]
Hi @danny-xl8, it seems like GitHub Desktop isn't able to locate your credentials which in turn leads to requests being denied due to hitting the unauthenticated rate limit of the GitHub API

```
2020-10-14T19:37:53.027Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: xl8_pylibs - danny-xl8 (empty token)
```

```
Error: API rate limit exceeded for 73.162.23.34. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
```

Could you please try opening preferences and signing out and then back in again using your GitHub.com account? Hopefully that should allow GitHub Desktop to access the credentials again. If that still doesn't work please try the [workaround](https://github.com/desktop/desktop/blob/development/docs/known-issues.md#the-username-or-passphrase-you-entered-is-not-correct-error-after-signing-into-account---3263) for making sure that Desktop is able to access keychain.

**Comment by danny-xl8** [comment]
Hi @niik I see now. Yes and now it works perfect. Thankss!

**Comment by niik** [comment]
Thanks for reporting back @danny-xl8!

**Comment by Tvmpteam** [comment]
I am too getting the same issue but i am unable to clone after doing signing off and logging in again.
Is there any other way to solve this issue
