### ISSUE TITLE
Branch names are not getting deleted even after deleted from VC (VSTS)

### ISSUE THREAD

**Issue by saranrajui** [desktop/desktop#10830]
### Describe the bug

Assume github desktop is linked with vsts repo. Even after the branches are deleted from vsts, it still shows in the branch's list( confuses much time to perform the action in the wrong branch)

### Version & OS
v.2.5.6
Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Steps to reproduce the behavior

1. Go to 'vsts and create a branch under master or develop or any valid branch'
2. Click on 'clone it to local '
2.1 link local repository (cloned) to github desktop
2.2 delete branch from vsts directly( not from github desktop)
3. fetch latest from github desktop and see the branch list, I can see deleted branches still appears

### Expected behavior

Deleted branches shouldn't appear in github desktop

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by niik** [comment]
Hi @saranrajui, thanks for opening this. GitHub Desktop will run `git fetch --prune` whenever you fetch from your repository in the application. See https://git-scm.com/docs/git-fetch#_pruning for more information on that.

Pruning will take care of deleting remote refs but if you've already checked out the branch locally you'll have a local branch which is tracking the remote branch (see https://git-scm.com/book/en/v2/Git-Branching-Remote-Branches).

Local branches that's not ahead of the default branch will get removed from GitHub Desktop eventually by our local branch pruner but as a safety precaution we don't prune until it's been at least two weeks since the last time the branch was checked out locally.
