### ISSUE TITLE
fatal: Unable to process path

### ISSUE THREAD

**Issue by Harishankar-GitHub** [desktop/desktop#10864]
### Describe the bug

Not able to push few files. GitHub Desktop says fatal: Unable to process path filename too long.
But I copied the whole folder into another repository. I'm able to commit without any issues.

### Version & OS

Version 2.5.6, Windows 10 Home

The file names are not that long. I must be able to commit.

**Comment by niik** [comment]
Hi @Harishankar-GitHub, when using Git on Windows there's a file path limit of 260 characters. That means that if your file name **including the full directory path** exceeds 259 characters you won't be able to commit. So it's not just the file name but also the full path to your repository that plays into it which is likely why you were able to work around it by copying the folder to another location.

https://github.com/git-for-windows/git/blob/cc9d75958dc66a9e985548c0a2c00e110cdeb3ee/Documentation/config/core.txt#L573-L578

Git for Windows has a configuration setting to enable support for paths greater than 259 characters but it comes with its own set of problems and is untested with GitHub Desktop.

```
core.longpaths::
	Enable long path (> 260) support for builtin commands in Git for
	Windows. This is disabled by default, as long paths are not supported
	by Windows Explorer, cmd.exe and the Git for Windows tool chain
	(msys, bash, tcl, perl...). Only enable this if you know what you're
	doing and are prepared to live with a few quirks.
```

The only workaround if you need to work with really long paths in your repository is to try to keep the path to your repository as short as possible (`i.e c:\dev\repo` rather than `c:\Users\Harishankar\Documents\GitHub\repo`).

**Comment by StuckInsideJake** [comment]
What about Mac?

**Comment by steveward** [comment]
@StuckInsideJake you shouldn't run into long paths issues on macOS since the limit is 1000+ characters. If you're having problems feel free to open up a new issue.

**Comment by samborlang-pyrtuh** [comment]
Hi @niik thank you for this, when I shorten my file path name then it worked.

**Comment by Species521** [comment]
> Hi [@Harishankar-GitHub](https://github.com/Harishankar-GitHub), when using Git on Windows there's a file path limit of 260 characters. That means that if your file name **including the full directory path** exceeds 259 characters you won't be able to commit. So it's not just the file name but also the full path to your repository that plays into it which is likely why you were able to work around it by copying the folder to another location.
> 
> https://github.com/git-for-windows/git/blob/cc9d75958dc66a9e985548c0a2c00e110cdeb3ee/Documentation/config/core.txt#L573-L578
> 
> Git for Windows has a configuration setting to enable support for paths greater than 259 characters but it comes with its own set of problems and is untested with GitHub Desktop.
> 
> ```
> core.longpaths::
> 	Enable long path (> 260) support for builtin commands in Git for
> 	Windows. This is disabled by default, as long paths are not supported
> 	by Windows Explorer, cmd.exe and the Git for Windows tool chain
> 	(msys, bash, tcl, perl...). Only enable this if you know what you're
> 	doing and are prepared to live with a few quirks.
> ```
> 
> The only workaround if you need to work with really long paths in your repository is to try to keep the path to your repository as short as possible (`i.e c:\dev\repo` rather than `c:\Users\Harishankar\Documents\GitHub\repo`).

How is file path length even my problem? You are just pushing your problems to the users again.
