### ISSUE TITLE
error: refname refs/heads/master not found

### ISSUE THREAD

**Issue by tusharg1** [desktop/desktop#10862]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by TaisandI** [comment]
Sent from my Verizon, Samsung Galaxy smartphone

**Comment by niik** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by Cl0uddotc0m** [comment]
No bug I was mistakenly bogging down my CPU and don't even know how a bug got submitted I apologize and will try to be more careful so as not to have this a reoccurring issue.
