### ISSUE TITLE
not support  one project use multiple Git remote repositories

### ISSUE THREAD

**Issue by orange-jacky** [desktop/desktop#10876]
### Describe the feature or problem you’d like to solve

I setup my .git/config follow this url 
https://bytescout.com/blog/setup-and-use-git-repositories-for-one-project.html

in terminal , it works
macbookpro:issue_server fredlee$ git push github master
Everything up-to-date
macbookpro:issue_server fredlee$ git push origin master
Everything up-to-date
macbookpro:issue_server fredlee$ git push --tags github master
Everything up-to-date
macbookpro:issue_server fredlee$ 

A clear and concise description of what the feature or problem is.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.
i operate in git desktop, it reports this
![image](https://user-images.githubusercontent.com/461594/96540656-d6224600-12d0-11eb-9857-d1620b66b8fe.png)

**Comment by steveward** [comment]
Thanks for the feedback @orange-jacky. We're tracking support for multiple remotes for repositories in GitHub Desktop in https://github.com/desktop/desktop/issues/1442. Even though the issue is closed due to use not prioritizing it at the moment we are still gathering feedback there. Thanks for letting us know you would like to see this implemented.

**Comment by ghost** [comment]
Tevfik güçlüler
