### ISSUE TITLE
Cannot fetch, cannot push

### ISSUE THREAD

**Issue by roza-leyderman** [desktop/desktop#10893]
### Describe the bug

I cannot fetch, cannot push. It hangs indefinately.

Opened a new account, went through steps to re-establish all connections, pulled down repository, was able to make changes, committed, and the push hangs.

### Version & OS

OS: Mohave
Version 2.5.6

### Steps to reproduce the behavior

1. Get new branch.
2.make a change to repo and commit.
3. available actions are to push to origin.
4. push does not happen

### Expected behavior

For push to succeed

### Actual behavior

Push hangs

### Screenshots

Add screenshots to help explain your problem, if applicable.
![image](https://user-images.githubusercontent.com/73082422/96744088-85b2f300-1379-11eb-9686-ea68bddb23e4.png)

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

### Additional context

We use Git CLI. Switching to GitHub app to solve this problem 
, yet seeing it hang again,,

**Comment by steveward** [comment]
Thanks for the report @roza-leyderman. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
