### ISSUE TITLE
Not able to publish repo and also not deleting

### ISSUE THREAD

**Issue by techlysolutions** [desktop/desktop#10909]
We are trying to publish repository on remote server. It was a already published code but due to some errors we have deleted this repo from remote server and trying to publish with different name.

Now, it not publishing nor deleting the repo as well as branch.

kindly,  resolve the issue so that we could publish repo.

**Comment by steveward** [comment]
Thanks for the report @techlysolutions. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
