### ISSUE TITLE
lock-issue Desktop version of Github

### ISSUE THREAD

**Issue by Funakoshi70** [desktop/desktop#10924]
### Describe the feature or problem you’d like to solve
Whene using GitHub desktop I'm facing a lock window while try to push documents. However, whene, I accessed the web version of GitHub i found all the pushes I've made.

**Comment by niik** [comment]
Thanks for the report! Could you upload a log file from GitHub Desktop so that I could get some more information about this issue? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue. Thanks!
