### ISSUE TITLE
Anyway to keep changed repo (local changes) at top in left list

### ISSUE THREAD

**Issue by surinder83singh** [desktop/desktop#10946]
### Describe the feature or problem you’d like to solve

Most of time i forget to push some changes while working on more than 5 repos at a time. 
Auto sync dont show all changes at once also some time it fails to tell modified repos.

### Proposed solution

there should be a way to see that all in a single place at top in list, or at-least search should support :updated or there should be button "Modified/Updated" beside search input

There can be a way to select repos for priority sync (faster sync) + at top

**Comment by steveward** [comment]
@surinder83singh thanks for the feedback. We discussed a number of possibilities for repository organization in https://github.com/desktop/desktop/issues/6460, but this is one that was not mentioned. I'm going to close this out since we do not have any plans to make any further modifications to the repository list, but this may be something we consider again in the future. I'll add this to the OP in #6460.
