### ISSUE TITLE
Binary Conflict resolution *Still* doesn't work

### ISSUE THREAD

**Issue by IFW-OMS** [desktop/desktop#10967]
### Describe the bug

when merging if a conflict is detected between binary files an option is presented to the user for the user to select which version of the binary file to retain, this selection does not work however as selecting the incoming file does not result in the file being replaced with the incoming version, instead the original file is retained but the conflict is marked as resolved.

### Version & OS

Windows 10 Pro
Github Desktop V2.5.6

## Steps to reproduce the behavior

1. merge two branches that have a conflicted binary file
2. in the conflict resolution pop-up select the incoming file
3. inspect file contents, resulting file is not the incoming version

this was detected when working with LabVIEW source code as the source is stored in binary files where the contents are easy to determine

### Expected behavior

the incoming file should replace the existing file

### Actual behavior

regardless of which option is selected the existing file is retained

### Additional context

This appears to be a duplication of issue #8059 which is marked as closed..

**Comment by niik** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

It's impossible to know without reproduction steps or any other information but we've recently fixed one issue related to merging binary files in https://github.com/desktop/desktop/pull/10826. It's possible that could be related.

**Comment by IFW-OMS** [comment]
noted - I raised this using the 'reference in new issue' option from my comment on the duplicate, closed issue which resulted in no template being presented. I've updated the issue with the full information.

**Comment by steveward** [comment]
@IFW-OMS I've been working to try and reproduce this but have been unsuccessful. When I create a merge conflict in a binary image file the correct file change is merged in based on selection. I've tested this out both when merging local branches and `origin/<branch>` into local. 

Would you mind seeing if you are able to reproduce this issue? There may be something I am missing.

**Comment by steveward** [comment]
@IFW-OMS as we haven't heard back from you I am going to close this issue out. If you are able to reproduce this again please let me know.

**Comment by azad-derakhshani-GS** [comment]
I'm still experiencing this issue, no matter if I choose `use the modified file` or `use the modified file from [name of feature branch]`, it always uses the file from the target branch instead of using the file from the feature branch.

@steveward Should I just open a new ticket or would you prefer we re-open this one?
