### ISSUE TITLE
Add a soft reset as an alternative to revert for items shown in History tab.

### ISSUE THREAD

**Issue by sdiedrichsen** [desktop/desktop#10976]
In case you committed some sources accidentally, you may want to reset this change (git reset --soft HEAD~1) instead of reverting it. This gives you back all the changes and you can redo your commits, split them, add pretty comments, etc. 
Sure, this has some limitations, but if the top item would offer this, that would be perfect.

**Comment by niik** [comment]
Hi @sdiedrichsen, this is in fact exactly what the `Undo` button underneath the commit message form in the changes view does (we use `mixed` rather than `soft`).

<img width="256" alt="image" src="https://user-images.githubusercontent.com/634063/98347761-26f7a580-2018-11eb-887f-943c929e922f.png">

We also have to do a little bit of magic to allow you to undo the initial commit:

https://github.com/desktop/desktop/blob/59820f4ae290bfa334f104b39cc0e27d2a7a8efa/app/src/lib/stores/git-store.ts#L699-L706

You can undo as long as you haven't pushed your commits to the remote as that would require you to force-push your changes to the remote. Resetting local commits, and reverting commits that have been pushed already is usually the safest approach unless you're familiar enough with Git to appreciate the potential complexities of force-pushing to a branch that others might have access to.

I hope that helps!

**Comment by sdiedrichsen** [comment]
You're correct. I tried a non-sense commit there it was, the local Undo button. That's what I needed. Thank you!

**Comment by gabriels1234** [comment]
Undo Commit seems gone from Version 3.4.21 
Please bring back:
`git reset --soft HEAD~1`

<img width="201" alt="Image" src="https://github.com/user-attachments/assets/b11d94d4-f019-430a-bd40-5e7491dae915" />
