### ISSUE TITLE
Windows CredMan: Replace the "GitHub - " prefix by "GitHub-" to remove problematic spaces

### ISSUE THREAD

**Issue by Catfriend1** [desktop/desktop#11011]
### Describe the feature or problem you’d like to solve

GitHub Desktop by default adds credentials for repos hosted on the local network to the Windows credential store. (manage-able by the cmdline built-in "cmdkey.exe") The script below is used to clear all stored passwords on machine shutdown of the maintenance machine. Windows' "cmdkey.exe" has a bug - it cannot delete entries named like the ones from GitHubDesktop.

> GitHub - domain.tld/url/to/repo.git

Because there's a space in it. No workaround available, running Win10 here.

### Proposed solution

For the security concerned users, please consider:

a) Making the password save optional (by a check box in settings, for example) when a new repo is cloned by GitHubDesktop.

b) Replace the "GitHub - " prefix by "GitHub-" to remove the problematic spaces.

Thank you.

### Additional context

> credential-manager-clear-all.cmd
```
@echo off
REM
for /f "tokens=2 delims==" %%A in ('cmdkey /list ^| findstr "target" ^| findstr /v /c:"virtualapp"') do ( echo %%A & cmdkey /delete:"%%A" | find "." )
REM
goto :eof
```

**Comment by niik** [comment]
Hi @Catfriend1, I'm sorry to hear that the way we store credentials on Windows is causing problems for you. Had we known that this would have been an issue when initially implementing credential storage we certainly would have opted for a solution without spaces but given that this has been in the wild since the initial release of Desktop now the risk and complexity of changing the format and migrating (or supporting two formats) is not something we'd feel comfortable with given that this is the first time we've encountered it being a problem.

I'm sorry if that's not what you wanted to hear. I wonder if you could get around this limitation of cmdkey by leveraging a powershell module like [CredentialManager](https://www.powershellgallery.com/packages/CredentialManager/2.0) ([source](https://github.com/davotronic5000/PowerShell_Credential_Manager)). I'm by no means well versed in Powershell but it seems to me like something like the following could work.

```
Get-StoredCredential -AsCredentialObject | % { $_.TargetName } | % { Remove-StoredCredential -Target $_  }
```

Either way, I hope you figure out a solution to your problem but from the Desktop side I'm afraid we'll keep the existing format unless we have a reason to re-evaluate the risk vs reward of changing it.

**Comment by ghost** [comment]
please delete issue
