### ISSUE TITLE
When using browser profiles in Chrome Github Desktop opens a random profile and cannot login through browser

### ISSUE THREAD

**Issue by harald-nav** [desktop/desktop#11016]
### Describe the bug

When using browser profiles in Chrome Github Desktop opens a random profile and cannot login through browser, as the redirect back to the app is not verifiable. This could be a Chrome bug, though why not use an internal browser for authentication?

### Version & OS
Version 2.5.7; Windows 10 18363.1139
Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Steps to reproduce the behavior

Open two browser profiles (to discern between azure/office 365 auth, for instance).

Log in to GitHub Desktop with a user that requires browser auth for permission granting.
 
### Expected behavior

The Client should use an internal browser and not depend on unpredictable outside environments.

### Actual behavior

It is impossible to log into GitHub accounts that are protected with more than Username/Password/2FA, like enterprise OAuth.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Log folder has not been created by GitHub Desktop.

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

### Additional context

Yeah, I probably shoud use real git in stead, I just wanted to test this app for once.

**Comment by niik** [comment]
Hey @harald-nav, thanks for opening this, sorry to hear you're having problems signing in to the app. Are you able to temporarily switch the default browser to another browser to work around the problem?

> Github Desktop opens a random profile

When you say random profile do you mean that it open either one of the two profiles you've created or another profile entirely? I'm not familiar with using different profiles in Chrome but we launch the system configured browser like any other application would (relying on the operating system to invoke the default system browser). Do you run into similar problems when you click on hyperlinks for other Desktop applications for example?

> The Client should use an internal browser and not depend on unpredictable outside environments.

We definitely considered this but it's generally a recipe for disaster as we're unable to stay on top of the latest versions of Chromium which causes many single sign on solutions to reject authentication due to an outdated browser. By leveraging the system browser we can also avoid the user having to enter their credentials as they're usually signed in already. And lastly, should they not be signed in they may have a password management system in place in their browser which makes signing in less of a hassle.

> as the redirect back to the app is not verifiable

I don't understand what it means that the "redirect is not verifiable" are you getting an error message in Chrome? If so, could you take a screenshot of it?

**Comment by harald-nav** [comment]
I found the reason why this issue happened, this is (mostly) not an issue with Github Desktop.
To reduce the number of local admins we use Microsoft Software Center for application distribution. We subscribe to chocolatey for prepackaged common application and they have done an error in the packaging of Github Desktop, installing it to System in stead of All Users/program files. This is a common problem when app installers try to avoid admin privileges and install their executables under application data, in stead of program files.
