### ISSUE TITLE
Support U2F Authentication

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#1111]
We announced this [a while ago](https://github.com/blog/2071-github-supports-universal-2nd-factor-authentication), and here's how to get it setup for [your account](https://help.github.com/articles/configuring-two-factor-authentication-via-fido-u2f/), and here's a Node library for it: https://www.npmjs.com/package/u2f

It'd be nice to support this as well as our other 2FA modes, I think I've got a couple lying around at home somewhere.

**Comment by shiftkey** [comment]
Given the existing apps didn't support this, I'm going to move it to at least our post-1.0 thinking.

**Comment by joshaber** [comment]
Thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I'm going to add the `future-proposal` label to this issue and close it out, so that we don't get overwhelmed with our backlog! We'll revisit these as part of our next planning session.

**Comment by K4r0qtuYNE5G4qgZ** [comment]
Did just run into an issue because GitHub account is secured with U2F but the freshly updated GitHub Desktop didn't support U2F and asked for the now less secure mobile 2FA. And of course i didn't have the mobile ready while the U2F Security key was plugged in and ready.

**Comment by billygriffin** [comment]
This may be reasonable to support when it's more mature, and it looks like Electron 4 will likely have support for the underlying protocols (https://github.com/electron/electron/issues/15404). For now though, I'm going to remove the `future-proposal` label to indicate that this isn't something we intend to work on in the near term, and we'll evaluate as things progress and adoption rises.
