### ISSUE TITLE
new to computer technology

### ISSUE THREAD

**Issue by mcneal20011** [desktop/desktop#11128]
i am fairly new to computers so i need major help is there a way i can just have things done for me step by step so i can understand them. i am a computer dummy. i wish all my stuff could be automated with artificial intelligence

**Comment by dhunmoon** [comment]
Git Desktop is a visual extension of Git, which is mainly used to add version control to your source code. The issues section in Github is mostly used to report and solve problems that users encountered in the Git Desktop application.

Since your question is not specific to Git Desktop, I think you can ask this question on other Forums like [Quora](https://www.quora.com/).
