### ISSUE TITLE
Commit failed - exit code 128 received, with output: '*** Please tell me who you are.

### ISSUE THREAD

**Issue by douglasbryan94** [desktop/desktop#11143]
### Describe the bug

The commit fails and produces an error message as follows (Commit failed - exit code 128 received, with output: '*** Please tell me who you are.)

### Version & OS

GitHub Desktop version 2.6.0
Windows 10 Education Version 20H2

### Steps to reproduce the behavior

1. Attempt to commit changes

### Expected behavior

The commit to publish as normal

### Actual behavior

The commit fails and produces an error message as follows (Commit failed - exit code 128 received, with output: '*** Please tell me who you are.)

### Screenshots

![image](https://user-images.githubusercontent.com/21163842/100528889-a27beb00-31af-11eb-867f-bec9f00eec0c.png)

### Logs

[2020-11-29.desktop.production.log](https://github.com/desktop/desktop/files/5611430/2020-11-29.desktop.production.log)

**Comment by douglasbryan94** [comment]
Running 'git config --global user.email {email}' resolves the issues.

Am unsure of how the ID values were lost to begin with.

**Comment by steveward** [comment]
I'm glad to hear you were able to get things working @douglasbryan94. It looks like your email address may have been automatically set by your system name, which can cause this type of issue. Had you previously configured your name and email for Git? GitHub Desktop prompts you to do this in the initial welcome flow.

I'm going to close this out since the issue has been resolved.
