### ISSUE TITLE
No longer showing option to merge the main branch in the History tab if behind

### ISSUE THREAD

**Issue by adamreisnz** [desktop/desktop#11154]
### Describe the bug

Up until the last update, the History tab would contain a button offering you to update the branch you are working on if it was behind the main branch.

After updating, this button no longer shows up, despite the branch being 23 commits behind:

![image](https://user-images.githubusercontent.com/490562/100710604-d7d54280-3414-11eb-81b4-3b0d98e70280.png)

### Version & OS

Version 2.6.1-beta1
OS X 10.14.6

### Steps to reproduce the behavior

1. Switch to a branch that is behind the main branch
2. Observe that no notification dot appears on the History tab
3. Click on the History tab
4. Observe that no button appears

### Expected behavior

For the button to appear. I have grown used to it and it's good to see/know at a glance that the branch is behind the main branch.

### Actual behavior

Button doesn't show up

### Screenshots

See above

### Logs

N/A

**Comment by billygriffin** [comment]
Hi @adamreisnz, thanks for the issue. I'm a bit surprised this was showing up for you, but we just unshipped it entirely in https://github.com/desktop/desktop/pull/11134, but that hasn't been released to beta yet so I'm not sure what might've caused the difference between the last version and current one you're on.

Regardless, it was inconsistent and obtrusive, and for most people it wasn't that helpful. So instead of fixing it to make it even more prominent, we decided to unship it because we weren't certain that it added much value. Since this was intentional, I'm going to close this issue, and I'm sorry that you did find value in it and will now miss it. We may revisit in the future, but for now the costs seemed greater than the benefits.

**Comment by adamreisnz** [comment]
Ah bummer, yeah that's a pity. I was worried that might have been the case.
I am on the beta version, and it seems to have been unshipped there.

I do agree that the location was a bit odd, but I hope you consider revisiting in the future and putting a similar feature/option somewhere else.

For posterity, this is how it looked like:

![image](https://user-images.githubusercontent.com/490562/100791094-a2187400-347d-11eb-9f91-9ca4e489e617.png)

Such an easy 1-click merge! Ah! 😢

**Comment by adamreisnz** [comment]
PS: would it be possible to place it in this help screen, which already has some similar options?

![image](https://user-images.githubusercontent.com/490562/100791184-bf4d4280-347d-11eb-9b45-6599f8ca901c.png)

**Comment by mpstaton** [comment]
I've been looking around for a half hour where I can merge a branch into the main repo. Can't find it anywhere.  Out for blood.
