### ISSUE TITLE
Make changes list scrollbar consistent with the diff viewer scrollbar

### ISSUE THREAD

**Issue by iAmWillShepherd** [desktop/desktop#11174]
### Describe the feature or problem you’d like to solve

The scrollbar on the diff view is dope, but the ones on the changes and history lists ain't great. Having them look consistent would certainly add to the polish of the UI.

### Proposed solution

Make all the scrollbars in the app look consistent. 
* **Changes/History**
	* The scroll bar thumb thingy for changes and history component should be made darker
	* ☝️ The active state should be even darker
	* The scroll bar track should be the same color as the one in the diff viewer
* **Diff View**
	* Add an active state to the scroll bar thumb thingy

### Additional context

The light-gray scrollbar track on the left doesn't fit with the dark theme, especially when the right scrollbar's track is dark gray.

<img width="961" alt="Screen Shot 2020-12-04 at 2 13 19 PM" src="https://user-images.githubusercontent.com/1715082/101152274-447e5600-363c-11eb-89fb-156302c59574.png">

I noticed these classes control Windows behavior, but I couldn't find any macOS specific styles in the ten mins I was willing to dedicate to this.

https://github.com/desktop/desktop/blob/6e51ed68797cacb8c6ca405e46b21cf7d8cf5df5/app%2Fstyles%2Fthemes%2F_dark.scss#L39-L53

#### Changes list
![2020-12-04 15 14 38](https://user-images.githubusercontent.com/1715082/101157412-85c63400-3643-11eb-8ba2-48d6afb8cabf.gif)

#### Diff viewer
Notice how there isn't an active/hover state?
![2020-12-04 15 14 58](https://user-images.githubusercontent.com/1715082/101157463-9c6c8b00-3643-11eb-8707-989006b66be6.gif)

**Comment by niik** [comment]
Hey @iAmWillShepherd!

I believe this happens when you use the option to always show scrollbars in macOS (or if you've got an external mouse plugged in and are using the "depending on trackpad or mouse" option). For now the way to get around this is to instead use the `When scrolling` mode which renders the correct styled scrollbar for both themes.

![image](https://user-images.githubusercontent.com/634063/101157755-ef861400-362a-11eb-8e9d-8c70fd4538ab.png)

The reason the diff scrollbar looks good is that it's a fake DOM scrollbar as opposed to a native one rendered by macOS. If you switch to split diff mode you'll see the same problem there as that view uses native scrollbars. I whipped up a quick [jsfiddle](https://jsfiddle.net/5c1794qv/1/) to illustrate the problem

![image](https://user-images.githubusercontent.com/634063/101166838-3aa72380-3639-11eb-9ee8-c22376d51f22.png)
 
This is running with `Always` show scrollbars, in Safari, with the Dark theme enabled for the OS and it's still showing the light scroll bar.

We could probably make our own styles for the scrollbar using CSS but the moment we do we loose that native look and feel. I wonder if this is something that needs to be resolved in electron or perhaps even in Chromium since both Safari and Chrome have the same problem.

> I noticed these classes control Windows behavior,

Yeah, the Windows scrollbars are so terrible that we have no choice other than to make our own there.

**Comment by iAmWillShepherd** [comment]
😃 👋 @niik 

> I believe this happens when you use the option to always show scrollbars in macOS

Yep, that's the issue. That setting was set to Automatic for me, and I do have a mouse connected today, so I'm going to blame that... and Apple 🤕


> If you switch to split diff mode you'll see the same problem there as that view uses native scrollbars.  

TIL there's a split diff mode! I legit didn't see that, and the little gear icon went unnoticed by me. Maybe it should stand alone off to the right to make it more prominent? 🤷 

> Yeah, the Windows scrollbars are so terrible that we have no choice other than to make our own there.

🤣 💀
  
I haven't looked at Windows in a minute; I'll take your word on it. My two cents is to do a custom one: Slack and Spotify are doing it (not implying y'all should follow them 😅 ), and it doesn't seem to take away too much from experience.

Your suggested workaround appeased me, so I don't feel either way strongly. Happy to close this issue if you don't think it's worth the trouble 👍

**Comment by niik** [comment]
> TIL there's a split diff mode! I legit didn't see that, and the little gear icon went unnoticed by me. Maybe it should stand alone off to the right to make it more prominent? 🤷

Yeah, you're not alonge. It shipped in 2.6.0 and the "NEW" indicator next to the gear that's visible in your sceenshots was my attempt at telling our users about it without being obtrusive. I guess I may have erred on the side of being too unobtrusive.

> I haven't looked at Windows in a minute; I'll take your word on it. My two cents is to do a custom one: Slack and Spotify are doing it (not implying y'all should follow them 😅 ), and it doesn't seem to take away too much from experience.

Yeah, that's fair. I haven't been bothered by the slack scrollbar now that you mention it.

> Your suggested workaround appeased me, so I don't feel either way strongly. Happy to close this issue if you don't think it's worth the trouble 👍

I think it's a legit issue, albeit one with a decent workaround. We'll see if @ampinsk has any ideas or if she can get some thoughts from folks from the design systems team on how to best address this so we'll keep it open but I'm happy you were able to work around it!

**Comment by ampinsk** [comment]
Hey @iAmWillShepherd! Thanks for the suggestion! I don't have too much opinion here other than if native scrollbars are giving us trouble then I think making our own isn't a huge hit to the "native" feel. I'd rather err on cohesiveness within the app than native elements for the sake of it.
