### ISSUE TITLE
"Commit Failed - exit code 1 recieved" when Committing Change to Branch

### ISSUE THREAD

**Issue by stevenadavidso** [desktop/desktop#11170]
I am currently having the aforementioned issue while committing changes to a branch on my local network. I have researched this and found many others have had the same issue, only problem is I'm less technically knowledgeable of 'nested .git files'. I understand what they are, but not how to identify them in my repo and get rid of them to remediate this issue. I had no issues when I created a 'New Folder' and added in documents to commit and merge branch in to Master. But, ever since then I am having this error. Please advise.

**Comment by steveward** [comment]
I'd be happy to help get this sorted @stevenadavidso. The `exit code 1` error can be caused by a few things, so it would be helpful if you could upload your log file from GitHub Desktop which will give us some more information.

To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue. 

>only problem is I'm less technically knowledgeable of 'nested .git files

Nested `.git` files means that you have a repository within your repository. If you are on a Windows machine you can enable hidden files and folders and check to see if there are any rogue `.git` directories. The most common issue has been users accidentally creating it in their root user folder. You could also just search for `.git` directories on your machine and see if that returns anything.

**Comment by stevenadavidso** [comment]
Thanks, Steve. Here is my log from yesterday where I did attempt to upload a file (WEBB_2_18_PD) in “env_depl_impl/WEBB_2.0_18” folder I created on my local network. I will search for any .git directories in the meantime. Let me know if you need any further information.

Steven Davidson​
|
Scrum Master
steven.davidson@libertyits.com<mailto:steven.davidson@libertyits.com>
[Liberty IT Solutions]<https://www.libertyits.com/>
[SDVOSB]
CONFIDENTIALITY NOTICE: This email and any attachments are intended solely for the use of the named recipient(s). Please do not forward or copy without the author’s consent. Any dissemination of this email by anyone other than an intended recipient is strictly prohibited. If you have received this email in error, please permanently delete the email and all attachments from your system. All information contained in this document are considered proprietary and shall not be reproduced, transmitted or shared with any individual or company outside the specific group for which this information is strictly intended.

**Comment by stevenadavidso** [comment]
[2020-12-03.desktop.production.log](https://github.com/desktop/desktop/files/5643222/2020-12-03.desktop.production.log)

**Comment by stevenadavidso** [comment]
Any update on this issue? I can send another prod log if needed.

**Comment by steveward** [comment]
@stevenadavidso I'm seeing this error in the log file:

```
'\\v08.med.va.gov\ORL\Users\VHAORLDAVIDS\My Documents\GitHub\bms-product'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
```

Are you storing your repositories in a shared network drive? Can you share a few more details about your setup?
