### ISSUE TITLE
Do a left-right swap of the split diff presentation

### ISSUE THREAD

**Issue by jkbullard** [desktop/desktop#11182]
### Describe the feature or problem you’d like to solve

The new "split diffs" presentation (#10617) is great, and extremely welcome!

However, **showing the old version on the left and the new version on the right is confusing for Xcode users.**  (Xcode is the primary IDE for Apple's operating systems.) That's because for many years Xcode has done the opposite: it shows the old version on the right and the new version on the left.

It might also be a problem for users of right-to-left languages.

### Proposed solution

Three possible solutions are:

 1. Provide a preference (in the "Appearance" section) to allow new/old to be shown as left/right or right/left. The preference could be titled "Swap diff left-right" or similar.
 2. Provide a third option in the "gear" menu, "Diff display: Split reverse" or similar, in addition to the existing "Unified" and "Split".
 3. Automatically show the diff as new-on-left on macOS. (Which does not address possible preferences of right-to-left language users.)

**Comment by billygriffin** [comment]
Hi @jkbullard, thanks so much for the issue and for sharing the context! Because this feature is meant to map very closely to GitHub.com's implementation of split diffs, we don't have plans to add an additional option to reverse the panes. We'll discuss internally if there's any plans to roll this out more broadly on GitHub.com but given that we haven't heard this feedback previously, we'll probably stick with the current layout. I know that's not ideal, but still really appreciate the issue and you letting us know.
