### ISSUE TITLE
Keep on Refreshing. Infinite loop in push and pull

### ISSUE THREAD

**Issue by pvasantha** [desktop/desktop#11191]
### Describe the bug

If we fetch branch or push to the branch. It keeps on refreshing. It looks like an infinite loop.
Could you please check this?

### Version & OS

Version 2.6 of GitHub desktop
Windows 10(minor release 9.0)

### Steps to reproduce the behaviour

1. Just change branh to master/ create branch
2. Push changes  to any branch
3. Sometimes pull also keep on loading

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by steveward** [comment]
Thanks for the report @pvasantha. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
