### ISSUE TITLE
responsive react

### ISSUE THREAD

**Issue by kalpesh1711** [desktop/desktop#11203]
4 video fix height but add more video not a responsive

**Comment by niik** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by kalpesh1711** [comment]
![12_9_2020, 12_46_02 PM](https://user-images.githubusercontent.com/73703967/101614310-cd2d3580-3a32-11eb-9fc0-3813e6a6c153.png)

**Comment by kalpesh1711** [comment]
see upper screen shot

**Comment by kalpesh1711** [comment]
I want 4 video height is fixed. but add new more video show to responsive on 768px
