### ISSUE TITLE
"Bring my changes" prompt on master

### ISSUE THREAD

**Issue by mstein-ck** [desktop/desktop#11228]
There is a setting allowing you to set behavior when switching branches and changes are present. One option is to prompt on every switch. This does not seem to take affect when switching from master branch. Can this setting apply to all branches?

P.S. The master branch in my repo is protected.
P.P.S. I have not tried setting the option to always stash my changes. I don't know if that will work on master either.

**Comment by billygriffin** [comment]
@mstein-ck We made the design choice to not prompt when someone is switching away from a protected branch and to just bring changes by default as Git does. This is likely something we aren't going to change, but I'm curious why you're hoping to leave changes behind on a protected branch.

**Comment by mstein-ck** [comment]
I will usually have stub code or test keys in my code that I use for testing master as well as feature branches. I rely on this prompt when switching so I can bring over code if I want it committed and leave code if I don't.

Another scenario that comes up is I will start developing a new feature on master and then have to switch over quickly to a feature branch to push or test something. I will have to stash my changes first, then switch, when normally I would rely on the prompt.

I work in more of a dev-ops capacity and I understand that these scenarios may not come up as often in a regular development environment.

**Comment by billygriffin** [comment]
@mstein-ck Got it, that makes total sense, thank you. For that purpose, I'd recommend using the menu item `Branch` -> `Stash all changes` or associated keyboard shortcut prior to switching. We're definitely open to changing this if we hear it a lot more but for now we're going to stick with it because it was intended to make it more convenient and faster for the majority of use cases. Thanks!
