### ISSUE TITLE
a branch with this name already exists

### ISSUE THREAD

**Issue by jmwall24** [desktop/desktop#11259]
### Describe the bug

When trying to access PRs from other team members from the PR tab, I get the error message 'a branch with this name already exists' even though it doesn't. If I manually search for the PR branch in the normal branch tab, it allows me to open the branch.

### Version & OS

GHD Version 2.6.1 and Windows 10

### Steps to reproduce the behavior

1. Go to 'current branch tab'
2. Click on 'Pull Requests'
3. Scroll down to 'a PR from a fellow team member'
4. See error message 'a branch with this name already exists'

### Expected behavior

Should open the PR branch

### Actual behavior

Does not open the PR branch

### Logs

[2020-12-19.desktop.production.log](https://github.com/desktop/desktop/files/5720241/2020-12-19.desktop.production.log)

**Comment by niik** [comment]
Hi @jmwall24, thanks for opening this. I'm going to roll this into https://github.com/desktop/desktop/issues/11238 which has been fixed in https://github.com/desktop/desktop/pull/11242 but not yet released to production. For now the workaround is, as you've already found, to checkout the branch manually. Sorry for the inconvenience!

**Comment by kuno23** [comment]
no solution for this in 2021???

**Comment by jlund24** [comment]
this is still happening in GitHub Desktop for Mac. Does anyone know of a workaround?
