### ISSUE TITLE
Don't automatically select all files for committing

### ISSUE THREAD

**Issue by exiva** [desktop/desktop#11256]
### Describe the feature or problem you’d like to solve

Selecting everything by default to stage for commit can be unwanted effect, creating the need to revert commits unnecessarily. The behavior of staging _everything_ is unique to Github Desktop. I think it should mimic other Git desktop applications and you have to manually pick to not accidentally commit something not intended.

### Proposed solution

Turn off selecting all files for staging by default.

**Comment by billygriffin** [comment]
Hi @exiva, thanks for the issue! This is an intentional design choice to make the most common flows more convenient, and while I understand that you may prefer to start with everything deselected, this isn't something we're likely to change unless there's a lot of feedback that the current design isn't working for people. The primary feedback we've gotten on this choice over the years has been overwhelmingly positive. Thanks again for the issue, and hope you start to build muscle memory around it that makes this a nonissue for you.
