### ISSUE TITLE
Apple Silicon Native App

### ISSUE THREAD

**Issue by alexclst** [desktop/desktop#11275]
Now that Apple has released Macs with Apple Silicon chips, Github Desktop really needs to become a Universal app. The app runs halfway decently under Rosetta, but I almost always run into a few error messages shortly after launching the app. So, an update that takes into consideration the Apple Silicon Macs should be made.

**Comment by niik** [comment]
Hi @alexclst, thanks for opening this. We're working towards being able to ship arm64 builds for Desktop (see #11142, #11021, and #9691 for some of the ongoing work). We've recently been able to produce a build of Desktop for arm64/macOS but we still have a fair bit of work to do on our backend side with delivery and automatic updates.

> I almost always run into a few error messages shortly after launching the app

We'd appreciate it if you could open issues specifically for these error messages. We're not aware of any errors caused by 
 the app running under rosetta 2 translation (we are aware that the app does not run on the developer transition kit which is expected) and we'd be very keen on details. I'm running Desktop myself on one of the new mac minis with the M1 processor without seeing any of these error messages.

**Comment by alexclst** [comment]
Thanks @niik. I just dug deeper into the errors and realized they stemmed from my local git config, so fixed them, and they aren't the app itself.

**Comment by niik** [comment]
> Thanks @niik. I just dug deeper into the errors and realized they stemmed from my local git config, so fixed them, and they aren't the app itself.

Thanks for following up, we really appreciate it. Keep an eye on our [release notes](https://desktop.github.com/release-notes) for news about arm64 support on macOS. Our hope is to be able to auto-upgrade you to a native binary once we're ready to ship it. Happy holidays!

**Comment by Ein-Tim** [comment]
Hey @niik 

#9691 & #11683 have been merged and tagged for version 2.7.3.
https://github.com/desktop/desktop/blob/development/changelog.json#L9 says for version 2.8.1-beta2:
"From now on, macOS x64 builds running on Apple Silicon devices will auto update to arm64 builds".

I'm on version 2.8.1 but still have the Intel version. 
https://desktop.github.com/release-notes/ Doesn't mention this at all.
Whats the status of this?

Regards, Tim

**Comment by sergiou87** [comment]
Hello @Ein-Tim! 👋 

That note about auto-updating to arm64 builds only affects beta builds for now. Version 2.8.2 (which will be released tomorrow, if everything is goes as expected) will include arm64 support, but you will need to download the arm64 build manually from https://desktop.github.com

After that, if we don't detect any major issues with those arm64 builds, we will enable the auto-update from x64 to arm64 in Apple silicon devices. But that will need yet another release to take effect. Until then, users will need to download the arm64 build manually.

I hope that helps!

**Comment by Ein-Tim** [comment]
Hey @sergiou87 

Thank you for your nice reply! Yes that helps! Can't wait to try the arm64 build out then!

Have a nice day!
