### ISSUE TITLE
Can't push with slow internet. Curl error

### ISSUE THREAD

**Issue by johnfortnitekennedyG** [desktop/desktop#11289]
### Describe the bug

I am trying to push a 21mb file for a release of my program, I have really bad internet (in a rural area) but stable enough to upload it. 110~kbps upload and connection seems to be being dropped after it reaches 4.1mb uploaded?, a curl error is being thrown.

Enumerating objects: 6, done.
Counting objects: 100% (6/6), done.
Delta compression using up to 12 threads
Compressing objects: 100% (3/3), done.
error: RPC failed; curl 55 Send failure: Connection was aborted
fatal: the remote end hung up unexpectedly00 KiB/s 
Writing objects: 100% (4/4), 21.90 MiB | 126.00 KiB/s, done.
Total 4 (delta 1), reused 3 (delta 0), pack-reused 0
fatal: the remote end hung up unexpectedly
Everything up-to-date

### Version & OS

Version 2.6.0 and using Windows 10

**Comment by steveward** [comment]
@baloger thanks for writing in. Unfortunately there is not much we can do on our end about unstable internet. Some users have had success using SSH in place of HTTPS when encountering connection issues. If you are interested in setting up SSH you can follow [these guides](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/connecting-to-github-with-ssh). Please note that GitHub Desktop has some [known SSH issues](https://github.com/desktop/desktop/issues/2579) and you will need to change the remote URL to use SSH since GitHub Desktop defaults to HTTPS. You can change the remote URL of your repository by going to `Repository` > `Repository Settings` > `Remote`. 

I'm going to close this out, but let me know if I can help with any other questions you have.

**Comment by johnfortnitekennedyG** [comment]
Thank you for answering. I'll try using SSH to push and report back.
