### ISSUE TITLE
Unexpected 'This folder contains files. Git can only clone to empty folders.' error

### ISSUE THREAD

**Issue by mahenzon** [desktop/desktop#11314]
### Describe the bug

On repo search error "This folder contains files. Git can only clone to empty folders." is shown, but no folder is selected yet

### Version & OS
Version 2.6.1
macOS 11.1 (20C69) 

### Steps to reproduce the behavior

1. Go to the GitHub Desktop
2. Click on 'Add' -> 'Clone repository...'
3. Start typing something in search (to search through your available repositories)
4. See error at the top (screenshot attached)

### Expected behaviour

Error is shown when some folder is selected

### Actual behaviour

Error is shown when searching, no folder was selected yet

### Screenshots

<img width="551" alt="image" src="https://user-images.githubusercontent.com/20804158/103441863-0a679a80-4c62-11eb-939b-64b5eb1c3a11.png">

### Additional context

I have previously selected custom folder, not using the default in Documents. Already cloned several repos there. This error doesn't affect behaviour anyhow, new repos can be cloned without any problems. I assume there's some bug in the logic if showing this error.
My _main_ folder is: `~/Projects` and it's selected, when I click a repo in the list to clone, it automatically changes to `~/Projects/my-project`

**Comment by M4N0JKUM4R** [comment]
Did you solve this?

**Comment by b0989596914** [comment]
i could't understand with it

**Comment by soham117** [comment]
Any updates? I am having the same issue on windows

**Comment by HanumaUkkadapu** [comment]
I too got the error when I tried to clone a repo that's already present on my local machine. I might have cloned it at some point. As its present already and it contains some files, it throws that error.

Check whether the repo you are having problem with exists in your local machine. If it's there, then try the option **Add Local Repository**.

**Comment by MitchSchwartz** [comment]
same error, the explorer window seems to want me to point it to a file even though it should want a directory.

**Comment by seth1299** [comment]
Having the same error, trying to clone to an empty folder and it does not work. Windows 10 Home Edition.

Edit: Found a fix. If you manually type out the address bar of the folder location instead of clicking "Choose... Add", it bypasses this error message and allows you to clone to the empty folder.

**Comment by arti1117** [comment]
I solved this issue by deleting the directory in the local path.

![check your path](https://user-images.githubusercontent.com/43284101/162340269-a3520cd2-f24e-4d43-8e18-a00795393340.png)

**Comment by Daniboy370** [comment]
This is how I (hopefully) workaround this problem. By simply addressing through the relevant directory, and clicking :
Code >> Open with GitHub Desktop

![image](https://user-images.githubusercontent.com/46421909/173327800-61bda9c7-1002-42eb-b905-bd3844ed2ffd.png)

**Comment by tidy-dev** [comment]
Curious if people are still seeing the issue. With release 2.9.13 back on April 13th, we fixed the clone dialog to not require a file.

**Comment by Epigee** [comment]
For me, this issue was telling me that my LOCAL repository already existed, and contained files, so I could not clone the Remote Repo into THE SPECIFIC local folder that I was specifying. 

To solve this, make sure the local directory that you're trying to clone the repo too either A: Doesn't exist (Git hub will create the new folder when you try to clone) or B: Is empty. 

Broken: Because there are files in my target local.
<img width="368" alt="image" src="https://user-images.githubusercontent.com/97752405/182033740-247ae851-b106-464d-a9f4-63d11e9e0f82.png">

Fixed: I removed the file.
<img width="432" alt="image" src="https://user-images.githubusercontent.com/97752405/182033777-2f9f2554-f66e-4921-8a3a-42006226dcba.png">

**Comment by kurtbruners** [comment]
The Problem is the local Path.

For example you cloned /labs
Then GitHub Desktop wants to put that under /Documents/GitHub/labs

Now you want to clone from a different master repo e.g. biglamp/labs
Then GitHub Desktop want to still put that under /Documents/GitHub/labs

Therefore the error is thrown. Which is why you just need to edit the local path folder name to e.g. /Documents/GitHub/labsFORK_biglamp

**Comment by Sreejit-Sengupto** [comment]
Just delete the repos/folers from the local path. Search for Github folder (wherever you have installed it ) and then just delete the repo you are cloning, from your system. Then try cloning again.

**Comment by VolkanDurmaz** [comment]
Go to your local GitHub storage location and clear old file which is named as your new repo.

**Comment by ashimachanpuriya** [comment]
> 

thanks

**Comment by malikjaved** [comment]
Please check if there is already a repo with the same name on your machine. If yes, delete that first and then clone it. It should work.

**Comment by sojwal-patil** [comment]
You already have Same folder as your repo name in your local machine first delete that folder and try again

**Comment by mishalshoaib** [comment]
Go to Documents\Github folder and delete the already existing file folder of repo then clone again.It worked for me

**Comment by harsh2084** [comment]
> ### Describe the bug
> On repo search error "This folder contains files. Git can only clone to empty folders." is shown, but no folder is selected yet
> 
> ### Version & OS
> Version 2.6.1 macOS 11.1 (20C69)
> 
> ### Steps to reproduce the behavior
> 1. Go to the GitHub Desktop
> 2. Click on 'Add' -> 'Clone repository...'
> 3. Start typing something in search (to search through your available repositories)
> 4. See error at the top (screenshot attached)
> 
> ### Expected behaviour
> Error is shown when some folder is selected
> 
> ### Actual behaviour
> Error is shown when searching, no folder was selected yet
> 
> ### Screenshots
> <img alt="image" width="551" src="https://user-images.githubusercontent.com/20804158/103441863-0a679a80-4c62-11eb-939b-64b5eb1c3a11.png">
> 
> ### Additional context
> I have previously selected custom folder, not using the default in Documents. Already cloned several repos there. This error doesn't affect behaviour anyhow, new repos can be cloned without any problems. I assume there's some bug in the logic if showing this error. My _main_ folder is: `~/Projects` and it's selected, when I click a repo in the list to clone, it automatically changes to `~/Projects/my-project`









It is possible that you already have a copy of the folder on your local device try deleting it and then cloning using url 
it'll work

**Comment by Lucas-Czarnecki** [comment]
The issue seems to be back with the latest update. I was trying to clone a repo that did not exist locally. Currently I am unable to clone any repo including existing repos I've worked with in the past.  

Fortunately, @Daniboy370 's posted workaround from 2022 still works for anyone experiencing the same issue.

**Comment by Sourabhiscoding** [comment]
Got the same issue, any other way to resolve it ?

**Comment by NurhayatYurtaslan** [comment]
> Got the same issue, any other way to resolve it ?

choose "add local repository" and solved error

**Comment by LightCoder177** [comment]
I believe the issue can be resolved by deleting the local repo in your OneDrive and try cloning it again. It works for me.

**Comment by Marlooon2004** [comment]
You need to delete first the local files in your computer and then paste de url of the file

**Comment by imberest** [comment]
I think I am having same issue with GitHub Desktop app. If you want to clone a repo into your root project folder (it contains other project folders) you will see this error. To clone with Desktop app you would create additional folder, it will be empty so the app will clone in it. The problem is that you will have additional folder for each cloned project...
Other way to do, which i just tested and it worked is to use CMD:
Make sure you're inside your **Projects/** folder
`cd path/to/Projects`
Clone the repo normally (it creates its own folder)
`git clone https://github.com/username/project.git`
This will create a folder like:
`Projects/cloned-project/`

Once these steps are done, then you can open local repo in GitHub Desktop App by
`File>Add local repository...` or press CTRL+O
