### ISSUE TITLE
Stuck at 37% upon cloning

### ISSUE THREAD

**Issue by stephanieraymos** [desktop/desktop#11321]
### Desktop clone is stuck on 37% and has been stuck for about ten minutes.

Won't move forward.

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

**Comment by steveward** [comment]
Thanks for the report @stephanieraymos. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by stephanieraymos** [comment]
I had a scss file and did not gitignore the cache so that was why. Thanks.
