### ISSUE TITLE
Support VSCode Insiders for MacOS

### ISSUE THREAD

**Issue by Androz2091** [desktop/desktop#11350]
### Describe the feature or problem you’d like to solve

I'd like to be able to define Visual Studio Code Insiders as the default editor. However, it's not in the External Editors list in the settings of the app.

### Additional context

OS: MacOS Big Sur
Prod: Mac Mini m1

**Comment by steveward** [comment]
Thanks for the report @Androz2091. VSCode Insiders is a [supported editor](https://github.com/desktop/desktop/blob/development/docs/technical/editor-integration.md#macos). I just installed it again to verify it was detected by GitHub Desktop. If you recently installed the Insiders edition you may need to relaunch GitHub Desktop so that the editor is detected. Let me know if that doesn't get things working.

**Comment by Androz2091** [comment]
You are right, I don't know why it didn't work but I now see the option. Sorry, I will try to restart next time... 😅
