### ISSUE TITLE
unix lines endings wsl2 wsl windows subsystem for linux  

### ISSUE THREAD

**Issue by ngmariusz** [desktop/desktop#11365]
### Describe the bug

i want to use github desktop running on windows
with browser runnig on windows
but together with wls2 (windows subsystem for linux)

### Steps to reproduce the behavior

go to any repo github and clik open with github deskop button (clone)

### Expected behavior

unix (wsl) line endings are respected 
or
choise is given
or
introduce desktop github option to configure upfront

### Actual behavior

windows line endings and repo unusable on wsl

### Additional context

-

windows 10 / wsl2 / ubuntu 20

-

related: https://stackoverflow.com/questions/29045140/env-bash-r-no-such-file-or-directory 

	quote: ->  the larger question is why you've ended up with \r\n

**Comment by steveward** [comment]
Thanks for the issue @ngmariusz. Microsoft has [recommendations for line endings](https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-git#git-line-endings) when working with WSL. You can also find GitHub's recommendations for managing line endings [in this help article](https://docs.github.com/en/free-pro-team@latest/github/using-git/configuring-git-to-handle-line-endings). The setup I usually recommend is to use a per-repo `.gitattributes` file to manage line endings and ensure compatibility between operating systems.

Since this is a specific Git for Windows and WSL issue and not directly related to GitHub Desktop I am going to close this out. Thanks for using GitHub Desktop!
