### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by surya-charan** [desktop/desktop#11366]
I am trying to login the github account in github desktop app but it is not loggig in. can you help me in it.

**Comment by steveward** [comment]
Thanks for the report @surya-charan. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
