### ISSUE TITLE
import a repository that was previously maintained by eclipse

### ISSUE THREAD

**Issue by ralfhauser** [desktop/desktop#11376]
### Describe the bug

I can import is as local repository Y:\Intra ant it sees the history, but I cannot
a) synchronize
      and
b) since it is gigabytes of data, I do not want to loose my uncommitted changes, thus I do not want to do an overwriting/clean checkout

### Version & OS

Version 2.6.1, Windows 10

### Steps to reproduce the behavior

Add the local path

### Expected behavior

I can synchronize and pull what has changed remotely and push what I changed on my side

### Actual behavior

i) I did not find any button to synchronize
ii) when I press the "Publish Branch" nothing happens

### Screenshots

What I see in History 
![grafik](https://user-images.githubusercontent.com/1681677/104287500-d3418680-54b6-11eb-921f-76682d3d9f5a.png)

And what happens when I want to clone it avoiding downloading everything again
![grafik](https://user-images.githubusercontent.com/1681677/104287552-e6eced00-54b6-11eb-8b4d-ed006ab74ca9.png)

### Logs

non so far

### Additional context

eclipse works fine on small repositories, but not with this one

**Comment by steveward** [comment]
@ralfhauser thanks for the report. Does the repository already exist on GitHub or GitHub Enterprise? Is `git.privasphere` a GitHub Enterprise server or a different third-party host? Any details you can share about your specific setup would be helpful.

Can you also go to `Repository` > `Repository Settings` > `Remote` and check if there is an existing remote associated with the repository?

**Comment by ralfhauser** [comment]
@steveward  Thanks for the quick reply.
Yes it is a thrid-party GitLab server.

![grafik](https://user-images.githubusercontent.com/1681677/104344048-f1ca7080-54fc-11eb-9b00-524745c4b668.png)

**Comment by steveward** [comment]
For GitLab repositories you need to follow [the steps in this document]( https://github.com/desktop/desktop/blob/development/docs/integrations/gitlab.md) to generate a token. The problem here is that normally the authentication step is achieved when you receive an authentication failed error, which it doesn't look like is happening for you. You could try pushing via the command line and then switch over to GitHub Desktop to see if that syncs things up for you.

Cloning the repository again should also work -- my guess is the 'folder contains files' error is being thrown because the repository exists at that path already. Is that the case?

**Comment by steveward** [comment]
Closing this issue out due to inactivity @ralfhauser. Let me know if you're still having problems and we can look into this further.
