### ISSUE TITLE
Github desktop does not redirect me

### ISSUE THREAD

**Issue by fatihcayir2001** [desktop/desktop#11408]
I try to sign in github desktop but it does not redirect me

### Version & OS

2.6.2

![image](https://user-images.githubusercontent.com/69792539/104856478-fa1f1300-5923-11eb-9bbe-40f6c9cff676.png)

I waited a lot but it does not do anything

**Comment by niik** [comment]
Hey @fatihcayir2001, sorry to hear you're having problems signing in to GitHub Desktop. When you click that button GitHub Desktop is supposed to launch your browser to complete the sign in process. What browser are you using? Could you try switching your system to use another browser temporarily to see if that resolves the issue?

Could you also please upload a log file from GitHub Desktop so that I could get some more information about this issue? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Explorer (macOS) or Explorer (Windows)`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue. Thanks!

**Comment by fatihcayir2001** [comment]
> Hey @fatihcayir2001, sorry to hear you're having problems signing in to GitHub Desktop. When you click that button GitHub Desktop is supposed to launch your browser to complete the sign in process. What browser are you using? Could you try switching your system to use another browser temporarily to see if that resolves the issue?
> 
> Could you also please upload a log file from GitHub Desktop so that I could get some more information about this issue? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Explorer (macOS) or Explorer (Windows)`.
> 
> The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue. Thanks!

thanks a lot when i changed system browser it worked <3

**Comment by Prince6yt** [comment]
I am having the same issue currently , i cannot sign in into my github desktop the redirect doesn't work
