### ISSUE TITLE
laravel

### ISSUE THREAD

**Issue by sitangwesa** [desktop/desktop#11414]
I am in learning phase of laravel. I am running my localhost on 8080 port, i.e., localhost:8080 works instead of localhost only. I am using xampp and want to change the url localhost:8080/lsapp/public to lsapp.dev Please guide me how to do that...

**Comment by sitangwesa** [comment]
please help me

**Comment by JoueBien** [comment]
This issue tracker is for the Git Hub Desktop Client not any of the other tooling you might be using. 🤦‍♂️

You're probably going to get better help in the Laravel forms https://laracasts.com/discuss or in the XAMP forms here. https://community.apachefriends.org/f/  
It's been a while since I've written Laravel but you don't need XAMP to run Laravel. You can start it 
with: 
```
php artisan serve  --port=80
```
on the command line. That is providing your database is running somewhere and php is a path variable.
The artisan docs can be found here https://laravel.com/docs/8.x/artisan

As for running it an actual URL you need a proper web server with a DNS name set up. If you looking for guides written from the XAMP crew then this would be the place to start https://www.apachefriends.org/hosting.html

**Comment by sitangwesa** [comment]
thanks
