### ISSUE TITLE
Open in Desktop not working.

### ISSUE THREAD

**Issue by jsyjbaba** [desktop/desktop#11412]
Description
Turn on Computer. Start GitHub Desktop: It works.
Close Github Desktop and reopen: Doesnt work anymore.
Since some days opening GitHub Desktop doesnt work at all.
Reinstalling GitHub helped sometimes, but the problems described in 1. and 2. were still there.

Version
GitHub Desktop version: [2.6.2]

OS version: [Windows 10. Version 2004]

Steps to Reproduce
[See description]
Reproduces how often: [100% until Github Desktop doesnt open at all]

**Comment by ethan-manninen** [comment]
I was having this issue too, I think I found a fix by going to the file location of GitHub Desktop and opening the previous version [2.6.1]. After opening this version, a suggestion came up to restart in the newer version. I clicked this and GitHub Desktop reloaded and seems to work fine now.

**Comment by steveward** [comment]
Thanks for the report @jsyjbaba.

Is GitHub Desktop launching at all -- i.e. do you see a blank window? Are there any processes running?

Could you also upload the log file from GitHub Desktop so that I could get see if it has any useful information? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`. The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by wowgamr** [comment]
Hello @steveward!
I have same problem. Here is my log.
[2021-01-22.desktop.production.log](https://github.com/desktop/desktop/files/5857924/2021-01-22.desktop.production.log)
