### ISSUE TITLE
Use  :code_dir/:organization/:repository as default checkout location

### ISSUE THREAD

**Issue by notxcain** [desktop/desktop#11422]
It would be very handy to have `:code_dir` in settings and then have `:code_dir/:organization/:repository` as a default checkout repository.

It might be only me, but this is how I organize repositories. It mirrors an actual structure on GitHub and prevents accidental checkouts into wrong directory.

**Comment by steveward** [comment]
Thanks for the issue @notxcain. We haven't heard much feedback about repository organization on disk, since most users seem to care more about the in-app repository organization (i.e. https://github.com/desktop/desktop/issues/6460).

Is there a specific reason the directory structure matters on your local disk since GitHub Desktop does sort by organization? Is it just for better local navigability?

**Comment by notxcain** [comment]
Yes, it's more about hiearchy on disk. I don't care much about in-app organization because I always use search. But my inner perfectionist gets nervous when I checkout into wrong dir.

**Comment by steveward** [comment]
@notxcain thanks for the extra details. Having the repository owner as part of the path of the cloned project has been asked before in https://github.com/desktop/desktop/issues/8461 . We haven't seen a lot of feedback about this as of yet, so right now we're not considering implementing it (we try to keep the configuration settings of Desktop as minimal as possible to not overwhelm our users).

Feel free to subscribe to https://github.com/desktop/desktop/issues/8461 to get updates, since we may revisit this in the future as we learn more from how people use Desktop and having one issue where all requests are cross-referenced to helps us gauge interest.
