### ISSUE TITLE
Option to keep changes for unselected files when discarding all changes

### ISSUE THREAD

**Issue by urmilshroff** [desktop/desktop#11432]
### Describe the feature or problem you’d like to solve

When discarding all local changes made in a branch, provide a toggle to keep the changes that were made to unselected files.

### Proposed solution

This will offer more granularity and control to users in certain cases. For example, in the confirmation dialog below, a simple check box to keep the unselected file (```lib/pages/contact_information_screen.dart```) from being discarded can be provided.

<img width="1027" alt="Screenshot on 2021-01-21 at 6 58 04 PM" src="https://user-images.githubusercontent.com/8844095/105370310-7a49bf00-5c29-11eb-90b5-88ca3d970bc6.png">

**Comment by billygriffin** [comment]
@urmilshroff Thanks for the issue. So in this example, you selected to discard *all* files. You're also able to multi-select individual files to include discard using shift+click or cmd+click, and then right clicking to see, for example, "Discard 2 selected changes". Since what you're describing is possible and we'd prefer not to introduce further confusion with an additional checkbox at the time of discarding, I'm going to close this issue. Thanks again.

**Comment by urmilshroff** [comment]
> @urmilshroff Thanks for the issue. So in this example, you selected to discard *all* files. You're also able to multi-select individual files to include discard using shift+click or cmd+click, and then right clicking to see, for example, "Discard 2 selected changes". Since what you're describing is possible and we'd prefer not to introduce further confusion with an additional checkbox at the time of discarding, I'm going to close this issue. Thanks again.

Alright, thanks for the clarification and your time. Have a nice day!
