### ISSUE TITLE
Branches are not displayed in the branches dropdown menu

### ISSUE THREAD

**Issue by alexnel24** [desktop/desktop#11470]
### Description

When in a repo the branches dropdown menu displays a logo of GitHub. I cannot switch from master to a different branch using this dropdown. 

### Version & OS

MacOS Catalina (not able to update to Big Sur)
Version10.15.7

### Steps to reproduce the behavior

1. Have multiple branches
2. Be in safari
3. Tap on the branches dropdown menu.
### Expected behavior

All Branches are displayed

### Actual behavior

GitHub logo displayed (cat head with two eyes and smile)

### Screenshots

Add screenshots to help explain your problem, if applicable.

**Comment by alexnel24** [comment]
Also can't process my screenshot file.

**Comment by sergiou87** [comment]
Hello @alexnel24! 👋  I'm sorry you're having these issue, but I'm afraid we need more info to diagnose the problem.

- Are you using the Desktop app? I ask because that `2. Be in safari` sounds like you might be having trouble with github.com and not the GitHub Desktop app.
- If you are, which version of the app are you using? You can open 'About GitHub Desktop' menu to see the Desktop version.
- Could you attach some logs from the app? You can get your logs by opening the `Help` menu and selecting `Show Logs...`.

Also, if you could try again to upload an screenshot of the problem, that'd be awesome 😄
