### ISSUE TITLE
Authentication failed

### ISSUE THREAD

**Issue by DakshaT** [desktop/desktop#11474]
Installed githubDesktop 
I am facing Authentication failed issue.
I tried logging in , but repeatedly giving authentication failure.
from browser same userid and password works properly

**Comment by steveward** [comment]
Thanks for the report @DakshaT. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
