### ISSUE TITLE
Sync Branches

### ISSUE THREAD

**Issue by FANMixco** [desktop/desktop#11502]
### Describe the feature or problem you’d like to solve

Currently, the GitHub for Desktop app can have different branches to the ones in GitHub. This can even happen even if you deleted a branch from GitHub.

### Proposed solution

I'd like that the branches from GitHub for Desktop could be synchronized with ones in GitHub. There could be a button for it.

### Additional context

N/A

**Comment by steveward** [comment]
@FANMixco thanks for contributing. Any branches that are on GitHub should be fetched and available for checkout from the branches list in GitHub Desktop. Local branches in your repository will not be available on GitHub until you publish them to the remote repository.

GitHub Desktop does not automatically delete local branches that have been deleted in the remote repository since we do not want to make assumptions about whether or not you want to delete the branch locally. Branches that have been **merged** and **deleted** on GitHub are automatically removed from your local repository in GitHub Desktop after 2 weeks (if you have not checked out the branch locally in the meantime). 

I hope that helps explain things, but let me know if you have any other quesitons..
