### ISSUE TITLE
Window icon does not function like other Windows apps

### ISSUE THREAD

**Issue by ZMYaro** [desktop/desktop#11532]
### Describe the bug

The GitHub icon on the left end of the title bar functions like any other part of the title bar, instead of functioning like the window icon for most Windows apps.

### Version & OS

Version 2.6.2, Windows 10.

### Steps to reproduce the behavior

1. Open GitHub Desktop on Windows
2. Single-click or double-click the window icon

### Expected behavior

Opens menu with window actions (minimize, maximize, close, etc.) on single-click; closes window on double-click.

### Actual behavior

Functions like the rest of the title bar—does nothing on single-click; maximizes window on double-click.

**Comment by steveward** [comment]
@ZMYaro thanks for the feedback. This is the standard behavior for Electron applications (VSCode and Discord behave this way as well for example). 

>Opens menu with window actions (minimize, maximize, close, etc.) on single-click

You can right-click or control-click on the icon/title bar to access this context menu. I hope that helps! Since this isn't something we are going to change at this time I am going to close this issue out.
