### ISSUE TITLE
Update from master does not work unless history tab is open

### ISSUE THREAD

**Issue by WillGoldstein** [desktop/desktop#11533]
### Describe the bug

When running Branch -> Update from master (CTRL+SHIFT+U), you get a success message if you do it with the Changes tab open, but code does not pull. Do it with the history tab open, and it works.

### Version & OS

2.6.2, Windows 10 Pro 20H2 build 19042.746

### Steps to reproduce the behavior

1. Go to the GUI
2. Be on a branch from master that does not match master
3. Have Changes tab open (not History)
4. Branch -> Update from master
5. Notice your code did not change. Go see your files, etc.
6. Switch to History tab and repeat step 4 above and see files will update

### Expected behavior

I'd expect the tabs not to matter

### Actual behavior

Tabs seem matter

**Comment by steveward** [comment]
@WillGoldstein thanks for the report. I was unable to reproduce this with a quick test on macOS. Are you able to make a GIF or short video of this behavior and share it?

It'd also be helpful if you could upload the log file from GitHub Desktop so that we can see if anything unusual is happening. 

To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
