### ISSUE TITLE
Compare commits

### ISSUE THREAD

**Issue by mpirescarvalho** [desktop/desktop#11542]
### Describe the feature or problem you’d like to solve

Sometimes we need to compare changes of two distinct commits, or even compare all changes between two commits. There sould be a possibility to select more than one commit in commit history panel
### Proposed solution

Allow selection more than one commit

![image](https://user-images.githubusercontent.com/20830847/107101261-8327bc80-67f5-11eb-8370-0fb54e1e2404.png)

**Comment by tidy-dev** [comment]
Hi @mpirescarvalho - I was searching for similar issues to yours and came across #6757.  I believe your request is along the same lines of being able to generate a diff of files - tho, yours appears to be specific to individual commits instead of branches. However, I believe it is on the same lines and am going to close this one in favor of tracking the enhancements of diffs/compares in one issue. Thank you for your input!
