### ISSUE TITLE
My account is linked but my commits are not being registered with my username and github avatar

### ISSUE THREAD

**Issue by pfiterman** [desktop/desktop#11551]
### Describe the bug

I have been going through an issue since monday, february 8th. When I commit my repositories changes, even if my github account is linked to Github Desktop, my username is not being registered

### Version & OS

Windows 10
GitHub Desktop 2.6.3

### Steps to reproduce the behavior

Even Though my account is linked my github avatar changed.
![image](https://user-images.githubusercontent.com/27889296/107381643-d176dd00-6acd-11eb-9bb6-d4e5561000e0.png)

### Expected behavior

My repositories' changes commited should be registered with my username account logged in Github Desktop.

**Comment by billygriffin** [comment]
Hi @pfiterman, thanks so much for the issue. The problem is likely that your Git config is different from the email address on your GitHub account. If you go to Preferences > Git, you should be able to update your name and email there. Just make sure the email matches one of the email addresses on your GitHub account in https://github.com/settings/emails. 

Separately, we're working to improve this in #610, so it was helpful to see how this happened for you. If you'd be willing, would you mind sharing if you have any ideas for how your Git config diverged from your GitHub email?

**Comment by pfiterman** [comment]
Thanks @billygriffin, I appreciated your feedback. My e-mail's domain was wrong (@mail.com instead of @gmail.com) in Preferences > Git. I have no clue how it happened as I didn't changed it.

About the issue #610 I have been using Atom and GitHub Desktop in parallel sometimes, maybe after update my Atom Text Editor it was performed some changes in my Git config incorrectly

**Comment by billygriffin** [comment]
Thanks @pfiterman for the additional info! Our approach for #610 is that when you're using Desktop, we'll use the primary email address from your GitHub account, unless you specify otherwise. I think this would've prevented the problem you ran into. So that's nice to see. Sorry this happened and glad to see you got it resolved. ❤️
