### ISSUE TITLE
Local Repos Issue

### ISSUE THREAD

**Issue by ZZAAAKK** [desktop/desktop#11577]
### Describe the bug

All of my local repos have been removed from the desktop app - I can't add them back in with the file path, or by searching and selecting the folder. I'm able to clone the latest version from GH website, but this is outdated and will result in a lose of work.

### Version & OS

Version 2.6.3
OS: Windows 10 Home (Version 2004, Build: 19041.804)

### Steps to reproduce the behavior

I can no longer open the application to detail the steps, but I went to add a repo from local folder > search > select folder > literally nothing happened. My only option is to clone.

### Expected behavior

The 'Add repository' button will be enabled, and the repo added upon clicking it.

### Actual behavior

The 'Add repository' button will remain disabled, and you cannot proceed.

### Screenshots

N/A

### Logs

I can't open the application any more.

### Additional context

N/A

**Comment by tidy-dev** [comment]
@ZZAAAKK Thank you for the report.

The 'Add repository' button will be disabled if you are not selecting a directory with .git (making it a git repository). 
Here is an example of reproducing this. 
![image](https://user-images.githubusercontent.com/75402236/108053387-58bad800-701b-11eb-93eb-03bfc251599d.png)

To confirm if your repo has the .git folder in it, navigate to the directory and with [hidden items viewable](https://support.microsoft.com/en-us/windows/view-hidden-files-and-folders-in-windows-10-97fbc472-c603-9d90-91d0-1166d1d9f4b5#:~:text=Open%20File%20Explorer%20from%20the,folders%2C%20and%20drives%20and%20OK.) 
Look for the .git file
![image](https://user-images.githubusercontent.com/75402236/108053643-adf6e980-701b-11eb-900a-34ff146a6810.png)

Since you mention not being able to open GitHub Desktop anymore, have you tried uninstalling it and reinstalling? 

Also, have you tried accessing this repo through other git software such as another client or the command line?

**Comment by steveward** [comment]
@ZZAAAKK since we have not heard back from you I am going to close this issue out. Let us know if you are still having problems and we can investigate further. Thanks!
