### ISSUE TITLE
Cannot login to Github Desktop

### ISSUE THREAD

**Issue by silica-dev** [desktop/desktop#11594]
### Describe the bug

Whenever I try to log in to GitHub desktop on my laptop, it does not work. GIFs of the exact behavior are provided further below

### Version & OS

The "About GitHub Desktop" button is greyed out for me, but it should be the most recent Pop! OS package. Here is my neofetch:
![neofetch](https://user-images.githubusercontent.com/43558271/107975852-b6511500-6f86-11eb-8f29-ddc42cb0dce4.png)

### Steps to reproduce the behavior

I have uploaded videos of the error in action [here](https://drive.google.com/drive/folders/1zVpHHyzoPpnWP3052E1RIhWxKBp8yD7x?usp=sharing).

### Expected behavior

I expect to be logged in after I log in.

### Actual behavior

Instead, nothing happens.

### Screenshots

Video recordings have been included above.

### Logs

Logs have been included in the aforementioned drive folder in case they would be useful.

**Comment by sergiou87** [comment]
Hi @Silicasandwhich! 👋 

Thank you for your report, specially for those videos/GIFs which make it easier for us to understand the problem ❤️ 

From what I see, that seems to be an old version of the app, because the user & password way of signing in is not supported anymore. Now, why it doesn't work with the web browser flow? Maybe that's something that got fixed in more recent releases, I can't say for sure, but I'd recommend you to update to the latest version and try again.

In any case, I'm afraid GitHub Desktop doesn't officially support Linux as of today. You can subscribe to #1525 in order to get notified when that happens.

Meanwhile, I'd recommend looking for help in https://github.com/shiftkey/desktop/ which is the closest you can get to official up-to-date Linux builds for GitHub Desktop.

I hope that helps!

**Comment by PauloBoaventura** [comment]
the problem still persists in the ubuntu version
