### ISSUE TITLE
v2.6.3 introduced multiple windows bug with Sublime Text 3

### ISSUE THREAD

**Issue by intrepidws** [desktop/desktop#11593]
### Describe the bug

I utilize projects in Sublime Text 3. When I have a project open in Sublime, and click the "Open in Sublime Text" option from within GitHub Desktop - it now opens a separate Sublime window. Prior to the current version of GitHub Desktop, this action would open the file within my currently active ST3 window (and project).

A rather large refactoring was done to the way that external editors are handled as part of 2.6.3 (I think) and I wonder if it's related?

https://github.com/desktop/desktop/pull/11400

### Version & OS

GitHub Desktop v2.6.3, Sublime Text 3.2.2 and Mac OS 10.14.6.

### Steps to reproduce the behavior

1. Have Sublime Text 3 open with an active project.
2. Have GitHub Desktop open to the same project.
3. In GitHub desktop, right-click on a changed file and select "Open in Sublime Text".
4. File will open in a new window, rather than the existing open ST3 window.

### Expected behavior

Prior to GitHub Desktop 2.6.3, the file would open in the existing open ST3 window - which is the preferred behavior.

### Actual behavior

The file opens in a new window, which means that it isn't open in the project context.

**Comment by intrepidws** [comment]
I just tested the same functionality in Nova, which has the same problem.

**Comment by sergiou87** [comment]
Hi @intrepidws!!

Thank you for your report ❤️  I think you're right and #11400 introduced a change in the behavior. We basically changed the way external editors in macOS were spawned to use Apple's `open` instead. That basically allows us to provide just the bundle identifier of the editor, so we don't need to keep hardcoding paths to specific executables inside the editors' bundle.

I just tested with VS Code and the files are opened in the same window, not a new one, just as you expected. With Sublime Text, it creates a new window every time. However, that seems to be Sublime Text's expected behavior, and you can [use a specific setting](https://woorkup.com/sublime-text-open-files-same-window/) to change it to your liking. I just tested it and works fine.

I can't tell about Nova, but maybe it has a similar setting for this 🤔 

Please, let me know if that helps to address your issue!

**Comment by intrepidws** [comment]
@sergiou87 Thanks for the tip, that worked! I didn't realize quite how much that I depended on how it worked previously until it was taken away from me! Thanks so much.
