### ISSUE TITLE
Slow download speed

### ISSUE THREAD

**Issue by GitScorz** [desktop/desktop#11618]
I usually download things at 10 or 12 mb per second and with the github desktop app it locks the speed of the download at 1.50 mb. Is there anything that i can do?

### Version & OS
Windows 10

https://prnt.sc/zyydn6

**Comment by steveward** [comment]
@GitScorz there are a number of things that can affect the network speed of Git operations, including variables like your network speed and your proximity to GitHub's servers. You can use https://github-debug.com/ to get a rough idea of your connection speed to GitHub. For a second data point I average 12-13MiB/s during clone operations in GitHub Desktop.

Since this isn't a specific GitHub Desktop issue I'm going to close this out. If you feel like you are experiencing slow Git operations I would recommend reaching out to [GitHub Support](https://support.github.com/).
