### ISSUE TITLE
Cannot push remote

### ISSUE THREAD

**Issue by kingjay888** [desktop/desktop#11651]
### Describe the feature or problem you’d like to solve
Hi

I had created an Organisation under my account, and add only me as the collaborator and gave admin access..

When i try to make changes and push to the repository in the Organisation it fails because of organisation error..

I am able to push remotely to other repository in my accunt, i am just not able to push to the repository under the new Organisation that i had created.. Please advise. Thanks

A clear and concise description of what the feature or problem is. If this is a bug report, please use the bug report template instead.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by steveward** [comment]
@kingjay888 thanks for the report. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
