### ISSUE TITLE
Error Dialog when switch branch

### ISSUE THREAD

**Issue by selimdoyranli** [desktop/desktop#11652]
### Describe the bug

I get the same error when changing branches, merge or pull. But after closing the window I continue normally

### Version & OS

Version 2.6.3 & Windows10 Pro

### Steps to reproduce the behavior

1. On `feature/my-branch`
2. Click to change branch for 'develop'
3. See error

### Expected behavior
No error dialog.

### Actual behavior
Error dialog.

### Screenshots
![switchfail](https://user-images.githubusercontent.com/22690563/109129611-de4c2f80-7761-11eb-9131-725f018f0a1a.png)

### Logs

> stderr:
Switched to branch 'develop'
/c/Users/user/AppData/Roaming/npm/yarn: line 5: cygpath: command not found
internal/modules/cjs/loader.js:883
  throw err;
  ^

> Error: Cannot find module 'C:\Users\user\AppData\Local\GitHubDesktop\app-2.6.3\resources\app\git\node_modules\yarn\bin\yarn.js'
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:725:27)
>     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
>     at internal/main/run_main_module.js:17:47 {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: []
> }
> 
> 2021-02-25T08:56:14.262Z - info: [ui] [Timing] Action 'checkout branch from list' for 'Devbase.Monster.Maps.Frontend' took 0.535s
> 

### Additional context

-

**Comment by steveward** [comment]
@selimdoyranli thanks for the report. It looks like your configuration is looking for node modules in the installation directory of GitHub Desktop. There's been previous discussion around these types of configuration errors in https://github.com/desktop/desktop/issues/10999, https://github.com/desktop/desktop/issues/9278, and https://github.com/desktop/desktop/issues/10326. 

I'd recommend taking a look at https://github.com/desktop/desktop/issues/10326 as that seems most similar to the issue you are running into. Since this error doesn't come from GitHub Desktop I'm afraid there isn't much we can do on our end to assist you with debugging this, but please let us know if you are able to track down the specific configuration that is causing this error as it may be helpful to other users in the future.
