### ISSUE TITLE
Disable automatic updating

### ISSUE THREAD

**Issue by stellathecat** [desktop/desktop#11668]
### Describe the feature or problem you’d like to solve

I use Citrix Receiver, and for some reason it can not handle the newest updates of GitHub Desktop.

### Proposed solution

Disable automatic updating.

### Additional context

I am using an installer .exe from May 2019 (which works on Citrix)

**Comment by tidy-dev** [comment]
@stellathecat  Thank you for your issue. I understand how disabling automatic updates would be a quick fix in your situation. However, the Desktop team would really like to know more about the root cause. Would you mind providing more information on what does not work in  the latest version, and which version exactly does work? (You can find the version in the about modal)
