### ISSUE TITLE
After renaming branch, clicking Pull Request points to the new branch, but commits are on the old one

### ISSUE THREAD

**Issue by alvinek** [desktop/desktop#11671]
### Describe the bug

After renaming branch from GitHub Desktop (Branch -> Rename), adding some commits and pushing them, then clicking "Create Pull Request), GitHub Desktop opens GitHub webpage with new named branch, but no changes can be seen. Changes are on the old branch. 

### Version & OS

GitHub Desktop  version: 2.6.3
OS: Windows 10

### Steps to reproduce the behavior

1. Create new branch and push it to GitHub.
2. Rename that branch.
3. Add some commits.
4. Push them to GitHub.
5. Click on "Create Pull Request".
6. Opened URL points to the new named branch without any commits.

### Expected behavior

I can think about 2 options:
1. GitHub Desktop adds commits to the old named branch and clicking "Create Pull Request" points to the old named branch.
2. GitHub Desktop adds commits to the new branch and clicking "Create Pull Request" points to the new named branch.

I think this is caused by git renaming mechanism itself. 

### Actual behavior

After renaming, GitHub Desktop commits to the old branch. Clicking "Create Pull Request" opens URL with new named branch compared to main, but no commits are visible. They are on the old branch. 

### Screenshots

Screenshots not needed

### Logs

2021-03-02T14:21:06.329Z - info: [ui] Executing push: git -c credential.helper= -c protocol.version=2 push origin xxx/newName:xxx/oldName--progress (took 6.337s)
2021-03-02T14:21:10.970Z - info: [main] opening in browser: https://github.com/zzz/yyy/pull/new/xxx%2FnewName

**Comment by tidy-dev** [comment]
@alvinek Thank you for your issue.

I can see where this is confusing, but is as you point out caused by git's renaming mechanism. Thus, when you rename a local branch, it only does so locally but still tracks the previous name remotely.  Thus, what you are seeing is actually expected behavior.

This is why we display this warning message when renaming a branch that is already being tracked remotely. 
![image](https://user-images.githubusercontent.com/75402236/109682855-c94e1280-7b4c-11eb-83bb-1b675e199324.png)


To reach the outcome I believe you are aiming for,
I would recommend creating a new branch based off of the branch with the undesired name, push it to remote. Then, delete the branch with the undesired name.
