### ISSUE TITLE
Discard Changes Takes a Ridiculous Amount of Time

### ISSUE THREAD

**Issue by GStrydom** [desktop/desktop#11680]
### Describe the bug

Discard Changes Taking Very Long

### Version & OS

Cant tell because it's STILL discarding changes.  OS is Win 10.

### Steps to reproduce the behavior

1. Simply choose Discard Changes

### Expected behavior

The operation to complete in a reasonable amount of time

### Actual behavior

Just keeps going

**Comment by steveward** [comment]
Thanks for the report @GStrydom. It'd be helpful if you could share the log file from GitHub Desktop so that I can take a closer look at the time Git operations are taking to complete.

To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
