### ISSUE TITLE
Allow to use an external git binary

### ISSUE THREAD

**Issue by fabiiomiiguel** [desktop/desktop#11699]
### Describe the feature or problem you’d like to solve

If I want to use an external git binary I can't, because it's only possible to use the bundled one.

### Proposed solution

Allowing to use another binary, makes the user was more control. This also allows you to disable lfs if you don't want to use that in my repository.

### Additional context

An example from the Sublime Merge settings.

![image](https://user-images.githubusercontent.com/27894544/109982681-0b688700-7cfa-11eb-946e-c610f1c55c3d.png)

**Comment by billygriffin** [comment]
Thanks for the issue @fabiiomiiguel! Because Desktop uses very specific Git commands under the hood, to ensure stability and reliability we need to have control over which Git is being used in the app. I'm curious if there's a specific reason why you want to use a different version of Git for Desktop operations specifically, but we have no plans to change this and therefore I'm going to close this issue.

**Comment by fabiiomiiguel** [comment]
Thanks for your response! @billygriffin the specific reason is that I want to disable lfs but that is not possible with github desktop.

**Comment by billygriffin** [comment]
@fabiiomiiguel Sorry about that. We package LFS to make sure it's available for those who need to use it, but hopefully it shouldn't be obtrusive for people who don't need it. I've never used LFS in my day-to-day development and I don't notice it's there. Not sure if that's helpful, but really appreciate your thoughts. ❤️
