### ISSUE TITLE
Cannot add submodules

### ISSUE THREAD

**Issue by lmrodriguezr** [desktop/desktop#11714]
### Describe the bug

When I add a submodule through the CLI (using `git submodule add`), and then make a commit and push using GitHub Desktop, the changes in `.gitmodule` are pushed but the actual submodule folder stays as uncommited change forever. Annoyingly, the CLI `git commit` doesn't seem to see that folder, so the only solution seems to be to re-add the module with `git submodule add --force` and then `git commit` from the CLI.

### Version & OS

macOS 10.15.7
GitHub Desktop 2.6.5

### Steps to reproduce the behavior

1. Add a submodule to repo using `git submodule add <URL-TO-REPO> <PATH-TO-FOLDER>`
2. In GH Desktop, select all changes
3. Commit
4. See how the <PATH-TO-FOLDER> stays as non-commited change

### Expected behavior

The commit button should commit the actual submodule, not just the entry in `.gitmodules`

### Actual behavior

The submodule is never pushed to the repo in github.com

**Comment by steveward** [comment]
@lmrodriguezr thanks for the report. Unfortunately there are some limitations when working with submodules in GitHub Desktop. This issue is being tracked in https://github.com/desktop/desktop/issues/1770, and broader submodule issues are being tracked in https://github.com/desktop/desktop/issues/7523. You can follow along in those issues for updates about this.
