### ISSUE TITLE
Urgent

### ISSUE THREAD

**Issue by vimalmary** [desktop/desktop#11728]
warning: LF will be replaced by CRLF in README.md.
The file will have its original line endings in your working directory
error: lstat("Symtech_TA/packages/Microsoft.AspNet.WebApi.Client.5.2.6/lib/portable-wp8+netcore45+net45+wp81+wpa81/System.Net.Http.Formatting.dll"): Filename too long
fatal: Unable to process path Symtech_TA/packages/Microsoft.AspNet.WebApi.Client.5.2.6/lib/portable-wp8+netcore45+net45+wp81+wpa81/System.Net.Http.Formatting.dll

**Comment by steveward** [comment]
@vimalmary thanks for the issue. This error is warning you about line endings changing. GitHub has a helpful article that discusses managing line endings here:

https://docs.github.com/en/github/using-git/configuring-git-to-handle-line-endings

Adding a per-repository `.gitattributes` file is my recommendation since it allows you to normalize line-endings across different operating systems. Let me know if you have any questions.
