### ISSUE TITLE
"Open in Desktop" opens pr/ not branch

### ISSUE THREAD

**Issue by gemal** [desktop/desktop#11733]
![image](https://user-images.githubusercontent.com/69105/110310556-f85bfc80-8002-11eb-8911-73cb7f89dd57.png)

I use Open in Desktop and here it clearly says it will open `minor1136` branch but when Github Desktop opens this link I get:

![image](https://user-images.githubusercontent.com/69105/110310677-1aee1580-8003-11eb-8d34-0201fe31d38d.png)

which looks very wrong

Using Dektop version 2.6.6-beta1

**Comment by sergiou87** [comment]
Hi @gemal! I'm sorry that's confusing, but as far as I can tell, what is happening is that your clone is a fork, and when GitHub Desktop "switches to a PR", it doesn't check out to the PR's branch and instead it will create a `pr/12345`. Therefore everything seems like expected behavior to me.

Using `pr/27412` will prevent a collision between the PR's branch in your fork (`origin/minor1136`), and the PR's branch in the original repo (`upstream/minor1136`).

I hope that explanation helped. I'm gonna close this issue, but let me know if there is anything else I can do to help or explain better.
