### ISSUE TITLE
fatal: bad config line 1 in file C:/Users/pc/.gitconfig

### ISSUE THREAD

**Issue by Arka-cell** [desktop/desktop#11746]
Hello, I have Windows 10 and I previously worked with Git. I wanted to switch into GitDesktop, downloaded it, installed correctly, but since then any get command in both Git and GitDesktop shows:

`fatal: bad config line 1 in file C:/Users/pc/.gitconfig`

I verified my gitconfig in a text editor and I found that it was empty.

**Comment by steveward** [comment]
@Arka-cell thanks for the report. Could you upload your `.gitconfig`? It definitely should not be empty unless it's not writeable due to a specific permissions issue.

**Comment by Yidna16** [comment]
I verified my gitconfig in a text editor and I found that it was empty.

**Comment by Yidna16** [comment]
Hello, I have Windows 10 and I previously worked with Git. I wanted to switch into GitDesktop, downloaded it, installed correctly, but since then any get command in both Git and GitDesktop shows:

fatal: bad config line 1 in file C:/Users/pc/.gitconfig

I verified my gitconfig in a text editor and I found that it was empty.

**Comment by hussainshamim16** [comment]
> Hello, I have Windows 10 and I previously worked with Git. I wanted to switch into GitDesktop, downloaded it, installed correctly, but since then any get command in both Git and GitDesktop shows:
> 
> `fatal: bad config line 1 in file C:/Users/pc/.gitconfig`
> 
> I verified my gitconfig in a text editor and I found that it was empty.

same problem

**Comment by Yidna16** [comment]
Maybe delet the configuration file then export new
