### ISSUE TITLE
Can't commit

### ISSUE THREAD

**Issue by LeaHabel** [desktop/desktop#11771]
### Describe the bug

I want to commit but can't do so. I get this error message: (sorry it's very long)

warning: LF will be replaced by CRLF in SampleScene/Assets/Game.meta.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in SampleScene/Assets/Game/Materials.meta.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in SampleScene/Assets/Game/Materials/New Material.mat.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in SampleScene/Assets/Game/Materials/New Material.mat.meta.

[... this error shown for every file in my folder]

error: open("SampleScene/Temp/UnityLockfile"): Permission denied
fatal: Unable to process path SampleScene/Temp/UnityLockfile

### Version & OS

Version 2.6.6 & Windows 10

**Comment by steveward** [comment]
@LeaHabel thanks for the issue. 

This CRLF error is warning you about line endings changing. GitHub has a helpful article that discusses managing line endings here:

https://docs.github.com/en/github/using-git/configuring-git-to-handle-line-endings

Adding a per-repository `.gitattributes` file is my recommendation since it allows you to normalize line-endings across different operating systems.

The other error is specifically related to Unity:

```
error: open("SampleScene/Temp/UnityLockfile"): Permission denied
fatal: Unable to process path SampleScene/Temp/UnityLockfile
```

You will want to add the recommended `.gitignore` for Unity to ignore the `Temp` directory. You can find that ignore file here:

https://github.com/github/gitignore/blob/master/Unity.gitignore

Once you add that to your repository you should not run into this issue. Let me know if you have any questions.

**Comment by Daddy2200** [comment]
> ### Describe the bug
> 
> 
> 
> I want to commit but can't do so. I get this error message: (sorry it's very long)
> 
> 
> 
> warning: LF will be replaced by CRLF in SampleScene/Assets/Game.meta.
> 
> The file will have its original line endings in your working directory
> 
> warning: LF will be replaced by CRLF in SampleScene/Assets/Game/Materials.meta.
> 
> The file will have its original line endings in your working directory
> 
> warning: LF will be replaced by CRLF in SampleScene/Assets/Game/Materials/New Material.mat.
> 
> The file will have its original line endings in your working directory
> 
> warning: LF will be replaced by CRLF in SampleScene/Assets/Game/Materials/New Material.mat.meta.
> 
> 
> 
> [... this error shown for every file in my folder]
> 
> 
> 
> error: open("SampleScene/Temp/UnityLockfile"): Permission denied
> 
> fatal: Unable to process path SampleScene/Temp/UnityLockfile
> 
> 
> 
> ### Version & OS
> 
> 
> 
> Version 2.6.6 & Windows 10
> 
> 
> 
> 
> 
>
