### ISSUE TITLE
Add support for committing and pushing with --no-verify

### ISSUE THREAD

**Issue by WilliamABradley** [desktop/desktop#11802]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is. If this is a bug report, please use the bug report template instead.

The problem lies when a commit hook is failing for some reason outside of your control, we need a way in the interface to commit or push with the --no-verify flag set, this way we can still commit and push without resorting to the CLI to do it, when Github Desktop encounters these errors.

### Proposed solution

How will it benefit Desktop and its users?

If we had a button to commit no verify after a commit error modal, that would be very handy, if you really need to commit, and someone has say, broken the commit hooks.

Perhaps if the commit button in the main interface became a button with dropdown (Like in the Github PR interface for merge vs squash, etc.), that gave us the option for a single commit to --no-verify.

**Comment by billygriffin** [comment]
Thanks @WilliamABradley, I'm going to close this as it's a similar problem as #9351 and others that we've seen come up like it. I responded there that we'd love it if someone (particularly someone who has experienced this directly) wants to take a shot at adding a "Commit anyway" button to the failure dialog. We're likely not going to add an explicit checkbox for --no-verify just because this is a relatively rare case for the broader set of users, but for those running into it, we definitely want to provide a better way out than switching to CLI.
