### ISSUE TITLE
Desktop cannot open to a specific branch from a repo page using "Open in Desktop" from GitHub.com

### ISSUE THREAD

**Issue by danielb987** [desktop/desktop#11810]
### Describe the bug

I want to open this tag as a branch in GitHub Desktop.
https://github.com/JMRI/JMRI/tree/v4.23.2

The web site has a green button "Code" which opens a dropdown menu with the menu item "Open with GitHub Desktop". I click on that and I get a question if I want to open GitHub Desktop and I say OK. GitHub Desktop opens, but nothing happens. The branch is not opened in GitHub Desktop.

Note that this works with Pull Requests. On PRs, there is a white button "Open with" which opens a dropdown menu with the option "Open in Desktop". This works fine.

### Version & OS

GitHub Desktop 2.6.6. I have checked for updates and GitHub Desktop tells that I have the latest version.

Windows 8.1.
Firefox and Brave (chromium based browser)

### Steps to reproduce the behavior

1. Go to https://github.com/JMRI/JMRI/tree/v4.23.2
2. Click on the green button "Code".
3. Select "Open with GitHub Desktop".
4. Tell the browser to open GitHub Desktop.
5. GitHub Desktop opens.
6. Nothing happens. The branch is not opened.

### Expected behavior

GitHub Desktop should create a new branch for this tag.

git checkout -b newbranch v1.0

### Actual behavior

Nothing happens. GitHub Desktop opens, but nothing happens.

Note that this works fine for Pull Requests but not for tags.

### Logs

```
2021-03-16T09:57:11.157Z - info: [ui] execPath: 'C:\Users\daniel\AppData\Local\GitHubDesktop\app-2.6.6\GitHubDesktop.exe'
2021-03-16T09:57:45.436Z - info: [main] Received possible protocol arguments: 4
2021-03-16T09:57:45.436Z - info: [main] Processing protocol url
2021-03-16T09:57:45.537Z - info: [ui] [BranchPruner] Last prune took place in 8 hours - skipping
```

**Comment by say25** [comment]
I could be wrong but I don't believe the URL from .Com gives us enough information to run this correctly. I think we only get the repo name not a branch or tag name

**Comment by danielb987** [comment]
> I could be wrong but I don't believe the URL from .Com gives us enough information to run this correctly. I think we only get the repo name not a branch or tag name

It seems that you are correct.

Open a tag with GitHub Desktop seem to give the link:
`x-github-client://openRepo/https://github.com/JMRI/JMRI`

But open a PR with GitHub Desktop seem to give the link:
`x-github-client://openRepo/https://github.com/JMRI/JMRI?branch=pr%2F9707&pr=9707`

So this seems to be a bug with the GitHub web page. Where do I report these bugs?

**Comment by say25** [comment]
I'm not sure where you would report this feature request.

In addition, branches (non-PR branches) also only give the repo URL (example `x-github-client://openRepo/https://github.com/JMRI/JMRI`) today.

**Comment by danielb987** [comment]
Thanks for your answer. I don't think it's a feature request, but rather a bug report. The GitHub web page has the option `Open with GitHub Desktop` and this option doesn't work.

Is there anyone on the GitHub Desktop team that has any contact with members of the GitHub web site team?

**Comment by say25** [comment]
CC: @billygriffin for triage, etc.

**Comment by billygriffin** [comment]
@danielb987 Thanks for the issue and sorry for my slow response. This feature was never intended to open to a specific branch or tag from the repo page, though I absolutely understand why you might want that. As you mentioned, this does work for PRs which is where it was specifically designed to check out the PR branch to get you right into the right context.

We're working on support for creating a new branch from a previous commit *within* Desktop, but not yet from GitHub.com at this point. I'm going to mark this as a potential enhancement.

**Comment by danielb987** [comment]
@billygriffin 
If I could enter a tag in GitHub Desktop and create a branch from that, it would be great. It's not necessary to be able to do it from GitHub web site.

Another thing that would have been great is to be able to open another user's branch that has not yet a PR. Sometimes a user creates a branch and wants someone else to test it, and as far as I know, it's not yet possible to do that in GitHub Desktop. It would be great if I could enter that branch, for example `silverailscolo:eb-responsive-jmri` in GitHub Desktop, and then get a new branch based on that branch.

**Comment by tidy-dev** [comment]
@danielb987 As long as that user has pushed their branch to the repository and you have fetched the latest in your GitHub Desktop that users branch should appear in the branch dropdown menu and can be filtered down to.

For example, my teammate created this branch `create-branch-from-commit` and I can tell it is not local to my machine because it is prefaced with `origin/` my remote signifier.
![image](https://user-images.githubusercontent.com/75402236/117437244-f24ca400-aefd-11eb-863e-edae7542e647.png)

Once you have checked out that branch, you can open the create branch dialog either from the app level branch menu or by hitting 'New Branch` next to the filter in the branch dropdown menu. In that create branch dialog menu, you will have the option to branch from your default branch or your currently checked out branch (your other user's branch)

![image](https://user-images.githubusercontent.com/75402236/117437529-55d6d180-aefe-11eb-92b0-d26b21490f43.png)

**Comment by goyalyashpal** [comment]
> We're working on support for creating a new branch from a previous commit _within_ Desktop
_https://github.com/desktop/desktop/issues/11810#issuecomment-833930017_

that would be super niiiice.

---
also, just discovered i couldnt filter in issue search on ghweb by `my-reaction:`

**Comment by billygriffin** [comment]
Since we've shipped the branch creation from previous commits to beta and you're able to open remote branches in Desktop and @danielb987 said his [use case is satisfied](https://github.com/desktop/desktop/issues/11810#issuecomment-833944745) with the earlier one, I'm going to close this. Obviously if we hear strong desire for this from the dotcom side we can revisit, but in the interest of prioritizing just want to make sure we're trying to solve the most important problems. Thanks y'all.

**Comment by goyalyashpal** [comment]
https://desktop.github.com/release-notes/?env=beta > 2.8.3-beta1 > #3474
