### ISSUE TITLE
System Theme Update defaults to System Theme even if you had selected something else

### ISSUE THREAD

**Issue by tidy-dev** [desktop/desktop#11814]
### Describe the bug

If you had your system theme set to dark, but the app theme set to light. Then, you pull the 2.7.0-beta3 update. You will be set onto the system theme. This may be an unavoidable outcome, but wanted to document it here so we can remember to figure out if we can keep users previous settings.

### Version & OS

2.7.0-beta3

### Steps to reproduce the behavior

Before install of 2.7.0-beta3.
Set your system to dark mode.
Set Desktop to light mode.
Install 2.7.0-beta3.

### Expected behavior

Remember my manually set theme preference.

### Actual behavior

Changes my theme to dark mode and setting set as system theme.

**Comment by tidy-dev** [comment]
@say25 Hey! This is appears to be a minor regression as a result of #11629. Wondering if you would like to take a look?

**Comment by say25** [comment]
A few things here:
1. I thought this was the intentional behavior per the `Uses System Theme as Default` being the issue name and what we talked about. 

    Also @niik commented on #9959

     > I'm likely misinterpreting here but I don't believe we have any initial signup theme selection in the welcome flow. Regardless I think that once we have "auto" as the default we won't need any initial selection.

2. This is obviously possible but to me this is more of a feature (highlighting the System theme option) than a bug. What would would have to do if we went down this road is for first install of 2.7.0+ check initial LocalStorage value and use it but afterwards go based on `remote.nativeTheme.themeSource`.
![image](https://user-images.githubusercontent.com/7467062/111363359-f1b23280-865d-11eb-9e39-fc6f707ca8ec.png)
