### ISSUE TITLE
Cloning speed

### ISSUE THREAD

**Issue by Bonnary** [desktop/desktop#11897]
### Describe the bug

the cloning speed in my laptop is 11 KB/s even though my Internet speed is 4MB/s

### Version & OS

Version 2.7.1

### Expected behavior

hope did you guys fixing this soon because it took so long just to clone my 200MB

 repository

### Actual behavior

After the new update, this happened

### Screenshots

Add screenshots to help explain your problem, if applicable.
(https://user-images.githubusercontent.com/69995568/112986907-4ee4d280-918c-11eb-948c-070dcf33daec.png)
(https://user-images.githubusercontent.com/69995568/112987025-7340af00-918c-11eb-9b79-a3f7dfda8c20.png)

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by steveward** [comment]
Thanks for the issue @Bonnary. There are a number of things that can affect the network speed of Git operations, including variables like your network speed and your proximity to GitHub's servers. You can use https://github-debug.com/ to get a rough idea of your connection speed to GitHub. For a second data point I average 12-13MiB/s during clone operations in GitHub Desktop.

Since this isn't a specific GitHub Desktop issue I'm going to close this out. If you feel like you are experiencing slow Git operations I would recommend reaching out to [GitHub Support](https://support.github.com/).
