### ISSUE TITLE
Github Desktop cloned an unexpected git repository

### ISSUE THREAD

**Issue by ylht** [desktop/desktop#11913]
### Describe the bug

I create a repository named A on Github and then rename the repository to B. Finally, I recreate a new repository named A again. However, when I use Github Desktop to clone A, I got the B repository instead of the newly created repository.

I can clone the newly created repository A by CLI and IntelliJ IDEA.

In fact, when I check the logs, I find that Github Desktop changed the repository address from A to B. I suspect that a repository address redirection happened here?

### Version & OS
Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

Version 2.7.1 MacOS 11.2

**Comment by steveward** [comment]
Thanks for the report @ylht. It looks like you are running into https://github.com/desktop/desktop/issues/3855. This bug is something we would like to get a fix out for in an upcoming release. You can follow along there for updates.

You can resolve this issue by closing GitHub Desktop and deleting the cache directory: 

`~/Library/Application\ Support/GitHub\ Desktop/Cache`

**Comment by ylht** [comment]
Thank you
