### ISSUE TITLE
ssh login using Github desktop

### ISSUE THREAD

**Issue by NLuffy** [desktop/desktop#11918]
I am unable to push/pull from me git enterprise account even after having logged. It works fine with git bash but on github desktop it show error

win 10

Version 2.7.1
### Steps to reproduce the behavior

1. Login to github using enterprise account
2. add a local repository which was synced using git bash.
3. press 'Fetch Origin'

###Error Message
Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.

### Expected behavior

Pull and push should work fine.

### Actual behavior

Shows an error dialogue box with 4 option all of which I have already checked.
[2021-04-01.desktop.production.log](https://github.com/desktop/desktop/files/6245052/2021-04-01.desktop.production.log)

**Comment by steveward** [comment]
@NLuffy thanks for the issue. GitHub Desktop does not have great SSH support, which is why the application defaults to using HTTPS. Is there a specific reason you are choosing to use SSH over HTTPS?

You may be running into an issue where GitHub Desktop favors the embedded SSH. See [this comment](https://github.com/desktop/desktop/issues/5641#issuecomment-421801704) for steps on how to resolve this. Let me know if that isn't the case.

**Comment by NLuffy** [comment]
@steveward I had already tried that and it doesnt work for github desktop. Git bash shows no problem. I am using this becoz company has advised to use ssh over https.

**Comment by steveward** [comment]
@NLuffy can you try launching GitHub Desktop via the command line by using the `github` command? Sometimes that fixes SSH environment issues -- let me know if it gets things working for you.

**Comment by LeszekKalibrate** [comment]
Start Git Bash, then:
`eval "$(ssh-agent -s)"`
` ssh-add ~/.ssh/id_xxxxxx` <-- your id

`$ github`

surprise, it works, but...
Close github
Open github from shortcut - does NOT work.

**Comment by NLuffy** [comment]
No it also doesnt work @steveward

**Comment by h8nor** [comment]
Yepp, even [this solution](5641#issuecomment-421801704) doesn't work for the `GitHub Desktop`. Only [curves solutions](11883) are offered.
But additional settings don't require app `MINGW64` (after installing Git).

**Comment by LeszekKalibrate** [comment]
This workaround with sshd makes Github working, but Bash cmd stopped working.
https://github.com/PowerShell/Win32-OpenSSH/issues/1234

**Comment by steveward** [comment]
@NLuffy did you verify that your SSH key was added and `ssh-agent` was running? @LeszekKalibrate shared the specific steps for that above.

We're tracking broader SSH improvements in https://github.com/desktop/desktop/issues/2579. I'd recommend following along there for updates, since this is something we have on our radar.

**Comment by h8nor** [comment]
@steveward Can you complete the signature function SSH on the GitHub Desktop for the month?

**Comment by AneesHl** [comment]
> Start Git Bash, then: `eval "$(ssh-agent -s)"` ` ssh-add ~/.ssh/id_xxxxxx` <-- your id
> 
> `$ github`
> 
> surprise, it works, but... Close github Open github from shortcut - does NOT work.

This helps with the same issue I'm having on macOS currently.
