### ISSUE TITLE
Not able to Clone the wiki page from GitHub Desktop on Windows 10

### ISSUE THREAD

**Issue by dybnguyen** [desktop/desktop#11927]
Using the GitHub Desktop application on Windows 10, it failed to clone the wiki page of my repo.
This appears to be the issue on the GitHub Desktop client program. If you have a work around for this client, please let me know.

![image](https://user-images.githubusercontent.com/25090124/113479708-91453280-945e-11eb-9b8e-c70f1909647b.png)

**Comment by steveward** [comment]
Thanks for the report @dybnguyen. GitHub Desktop does not have great support for wikis at this time -- see https://github.com/desktop/desktop/issues/3839 for the tracking issue with known bugs. I'd recommend cloning the wiki via the command line and working with it there. I'm going to close this issue out since we are already tracking these issues in #3839.
