### ISSUE TITLE
Cloning

### ISSUE THREAD

**Issue by PrajwalK-7** [desktop/desktop#11932]
### Describe the feature or problem you’d like to solve
While cloning  i faced problem.
while downloading showing errors if i give retry again starting from 0 mb
A clear and concise description of what the feature or problem is. If this is a bug report, please use the bug report template instead.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by steveward** [comment]
Thanks for the report @PrajwalK-7. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
