### ISSUE TITLE
"Discard modified line..." option greyed out

### ISSUE THREAD

**Issue by OneLookSigns** [desktop/desktop#11948]
Right click on a modified line (where the line has been changed, not just added or removed entirely) to get the "Discard modified line..." option to pop up. The option is greyed out when it shouldn't be?

The ability to discard solely added or removed lines seems to work but not for modified lines.

Version 2.7.1
Windows 10

**Comment by say25** [comment]
I believe this only works in side-by-side diff viewing.

**Comment by steveward** [comment]
@OneLookSigns you can use the split diffs view to discard specific lines in your changes like @say25 mentioned. For unified diffs discarding single lines is disabled in a group of changes that adds and removes lines. See [this help article](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/committing-and-reviewing-changes-to-your-project#3-discarding-changes) for more information. I'm going to close this out, but let me know if you have any further questions.

**Comment by OneLookSigns** [comment]
@steveward Thanks for letting me know. I'm not entirely sure I understand if or why it's been disabled intentionally for unified diffs specifically. Good to know regardless.

**Comment by givihuda** [comment]
I'm confused on when this can be used... every time I try to discard a line, the option is grayed out. I'm wondering: why is the option there if I can never use it?

![image](https://user-images.githubusercontent.com/74785256/116710404-f5d8ac00-a98e-11eb-9634-6bb10b0aa877.png)

My changes aren't unusual, it could be 1 or more characters in a line of text, or the whole line.

PS: I've never had an issue discarding lines or hunks in other git GUIs, like SourceTree.

**Comment by tidy-dev** [comment]
@givihuda I am sorry for the confusion.  When discarding a line that results in an addition and subtraction, you must discard the the group associated with it. Thus, when using the unified diff (as your screenshot appears), you have to open the context menu on the group handle of the entire line 26 (which is displayed as a group of two lines on the screen).  Because split diff naturally, shows the addition/subtraction of one line horizontally, it is enabled for the entire line. 

Here is a screenshot showing the vertical bar in unified diff from [the article](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/committing-and-reviewing-changes-to-your-project#3-discarding-changes) that was linked above that explains it more. 

![image](https://user-images.githubusercontent.com/75402236/116870201-10559400-abe0-11eb-8632-6370493903d8.png)
