### ISSUE TITLE
'Connect to Github' window repeatedly pops up

### ISSUE THREAD

**Issue by SleepyVoodle** [desktop/desktop#11960]
### Describe the bug

A sign in window for Github keeps popping up when using Unity, even though I am currently signed in. Multiple windows appear over time.

### Version & OS

Version 2.7.2 - Win 10

### Steps to reproduce the behavior

Pop up window occurs regardless of activity.

### Screenshots

![Github_popup](https://user-images.githubusercontent.com/60592251/113962096-6c8bf900-986a-11eb-8097-2f7dd1163c4a.png)

**Comment by billygriffin** [comment]
@SleepyVoodle Sorry about that, that sounds frustrating. I'm not actually sure what that window is - are you sure it's coming from GitHub Desktop? I'm wondering if it's related to the GitHub for Unity extension potentially, or something else that I might not be thinking about.

Let me know if there's any additional context you could provide that might help us figure this out. Thanks again!

**Comment by steveward** [comment]
@SleepyVoodle that window looks like the auth dialog for the Git Credential Manager. Is it possible something is shelling out to Git and prompting the auth dialog?

**Comment by SleepyVoodle** [comment]
It pops up whenever I use Unity.
I end up with a dozen of them stacked up. :I

Do you have any idea what I could try to make it stop?
Admittedly I don’t know much about Unity (or GitHub), I’m learning for a
project I’m helping with.

Thanks so much for getting back to me!
-J

...

**Comment by steveward** [comment]
The [authentication flow for GitHub for Unity](https://github.com/github-for-unity/Unity/blob/master/docs/using/authenticating-to-github.md) doesn't show that prompt, so I'm not sure what else could be causing it. You could also try seeing what Git processes are running when this occurs to see if you can isolate where it may be coming from. I would also recommend reaching out to Unity support to see if they have any idea.

I'm going to close this out since it isn't a specific GitHub Desktop issue.
