### ISSUE TITLE
could not read Username for 'https://github.com': terminal prompts disabled

### ISSUE THREAD

**Issue by anasazmi571** [desktop/desktop#11961]
### Describe the bug

After updating GitHub Desktop to version 2.7.2, fetching, pulling or pushing commits result in the error below:

> error: cannot spawn C:\Users\anas.azmi\AppData\Local\GitHubDesktop\app-2.7.2\resources\app\desktop-trampoline\desktop-trampoline.exe: Function not implemented
fatal: could not read Username for 'https://github.com': terminal prompts disabled

I've tried signing out and back in, and also revoking authorization in GitHub > Settings > Applications > Authorized OAuth Apps and re-authorizing it, but none have worked.

Meanwhile, both the Git command prompt and the Version Control bar in Visual Studio Code can do these operations without issue.

### Version & OS

Version: 2.7.2
Operating system: Windows 10

### Steps to reproduce the behavior

1. Update GitHub Desktop to version 2.7.2.
2. Open a repository.
3. Commit a change.
4. Click "Push origin".

### Expected behavior

Git operations like fetch, push & pull to be completed successfully.

### Actual behavior

A dialog box appears, saying:

> error: cannot spawn C:\Users\anas.azmi\AppData\Local\GitHubDesktop\app-2.7.2\resources\app\desktop-trampoline\desktop-trampoline.exe: Function not implemented
fatal: could not read Username for 'https://github.com': terminal prompts disabled

### Screenshots

![Screenshot 2021-04-08 112555 - blocked out](https://user-images.githubusercontent.com/34757452/113964450-1c0e9e80-985e-11eb-9695-e87439e9cd91.png)

**Comment by sergiou87** [comment]
Hi @anasazmi571! 👋 

I'm sorry about this issue. I'm not entirely sure what the problem is, but it seems like that `desktop-trampoline.exe` file cannot be opened. Could you take a look at that path and see if the file exists?

I wonder if you're using an Antivirus and it deleted the file or put it in quarantine.

Please let me know if any of that helps!

**Comment by anasazmi571** [comment]
Hi, @sergiou87 .

`desktop-trampoline.exe` indeed exists in the path above. Though when I tried to run the exe through command prompt, a message popped up saying the program is blocked by group policy. 
![Like so.](https://user-images.githubusercontent.com/34757452/114122339-a6203b00-9922-11eb-95e3-08232052ffa1.png)

**Comment by sergiou87** [comment]
Thanks for the prompt response @anasazmi571. Unless I'm missing something, that means an antivirus of some kind blocked the file. Antivirus usually allow you to see a list of blocked files and a way to unblock them.

Could you check if your antivirus has anything like that?

**Comment by anasazmi571** [comment]
I don't think my antivirus blocked the file (I'm using Windows Defender). I suspect that it's related to my company's IT group policy of some kind. Double clicking the application produced this:

![image](https://user-images.githubusercontent.com/34757452/114151238-7f2c2e00-994f-11eb-9909-76588f585f92.png)


This same error has happened before on March 3rd when version 2.6.3 was released. The 2.6.4 update, released the next day, fixed the issue.

**Comment by sergiou87** [comment]
@anasazmi571 Yes, that's because 2.6.3 introduced this same `desktop-trampoline.exe` executable, and in 2.6.4 we removed it for other reasons (see #11701 and #11696). Now those problems are fixed, it seems 🤞 , so running the `desktop-trampoline.exe` file should be safe and the way to go.

I just Googled a bit for solutions to this problem you have, please take a look at some of these links in case it helps:
- https://www.minitool.com/news/this-program-is-blocked-by-group-policy.html
- https://www.isunshare.com/blog/this-program-is-blocked-by-group-policy-error-windows-10/

In Windows Defender, you can also check the Thread History to see if it had anything to do with this problem. It also allows you to add exceptions: https://www.thewindowsclub.com/exclude-a-folder-from-windows-security-scan

Please let me know if any of that helped, so we can hopefully help other users or somehow fix it from our end, if that's possible. Thank you!!
