### ISSUE TITLE
Can't select and tick/untick simultaneously multiple files in the Changes tab

### ISSUE THREAD

**Issue by ozmurat** [desktop/desktop#11974]
### Describe the feature or problem you’d like to solve

When there's too much changed files in Changes tab, things get too crowded. Sometimes I'd get confused which ones should I select to push. And I can't multiselect to tick/untick the changes.

### Proposed solution

I'd suggest two solution for this:
- Changes tab could be like a folder structure where we can collapse and uncollapse folders. And ticking/unticking a folder would tick/untick all the nested folders and files.
-  Add a multiselect support 

### Additional context

![image](https://user-images.githubusercontent.com/80270681/114184256-4be89f80-994d-11eb-90c5-48f639b60f29.png)

**Comment by sergiou87** [comment]
Hello @ozmurat! 👋 

You can actually tick/untick multiple files at the same time, if you select them and then press <kbd>Space</kbd> in your keyboard.

On macOS you can select multiple non-contiguous files by holding the <kbd>Command</kbd> key, but I haven't been able to replicate the same on Windows using <kbd>Control</kbd>, but at least you can select contiguous files in both holding <kbd>Shift</kbd>.

Other than that I think we could probably fix/improve multiselection so that it works as any other list in any other app.

Anyway, I hope that helps until any work is done on this area!

**Comment by Daddy2200** [comment]
**bypass**

**Comment by sergiou87** [comment]
We have decided we're not gonna implement this, since the default system behavior matches what GitHub Desktop does. Selecting multiple files and pressing <kbd>Space</kbd> as mentioned above should work. I was wrong and pressing <kbd>Control</kbd> on Windows to select multiple commits files works too.
