### ISSUE TITLE
Bug on GitHub Desktop - Bad pull request

### ISSUE THREAD

**Issue by RLOAYZA** [desktop/desktop#11989]
### Describe the bug

I have a change in my branch A, and i realised that the changes need to be on branch B, so i changed the branch and brought the changes into the other branch, i pushed the changes and when i switch the branch again i see a message to do the merge but i dont have changes to merge.

### Version & OS

Version 2.7.2 - Windows 10

### Steps to reproduce the behavior

1. Change some things
2. Switch branch
3. Bring the changes
4. Push the changes
5. Switch into the first branch
6. This is the error

### Expected behavior

A clear windows with nothing extra to do

### Actual behavior

A windows saying that a pull request is necesary
### Screenshots

Error desktop
![image](https://user-images.githubusercontent.com/77587681/114437459-33b29380-9b8c-11eb-82fd-caab8595cae8.png)

Error GitHub web
![image](https://user-images.githubusercontent.com/77587681/114437501-3f9e5580-9b8c-11eb-9584-69d666ed17d0.png)

### Additional context

The other branch was the main

**Comment by tidy-dev** [comment]
@RLOAYZA If I understand your scenario correctly, you have your default branch `main` and another branch - for example `test-branch`. And when you are on your `test-branch`, you see the suggestion to create a pull request. This is the apps expected behavior for a published branch. It is simply a suggestion because creating a pull request is commonly the expected goal for a non-default branch. 

GitHub Desktop does not do any comparison against the default when providing the suggestion as there are pitfalls in doing so such as you may want to do a pull request against some other branch. 

I hope this helps. Thank you for your feedback!
