### ISSUE TITLE
Need button delete commit history for github website 

### ISSUE THREAD

**Issue by Ravisut** [desktop/desktop#11994]
how to delete commit history  in github website for beginner

**Comment by steveward** [comment]
@Ravisut if you need to remove a file due to sensitive data you can follow [this guide](https://docs.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository). If you just want to undo the commit you can use the [revert option in GitHub Desktop](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/reverting-a-commit) and then push the commit that reverts the change up to GitHub. I hope that helps! If you have any further questions I'd recommend contacting [GitHub Support](https://support.github.com/).
