### ISSUE TITLE
Git is not installed along with Github Desktop as mentioned in the github desktop guide

### ISSUE THREAD

**Issue by vmahadev** [desktop/desktop#12051]
### Describe the bug

As per the instructions installed Github Desktop but git is not installed automatically.

https://github.com/git-guides/install-git

Install Git Using GitHub Desktop
Installing GitHub Desktop will also install the latest version of Git if you don't already have it. With GitHub Desktop, you get a command line version of Git with a robust GUI. Regardless of if you have Git installed or not, GitHub Desktop offers a simple collaboration tool for Git. You can learn more here.

### Version & OS

Windows 10 Home 

Desktop Version 2.7.2 

### Steps to reproduce the behavior

1. Download Github Installer at https://desktop.github.com '
2. Run the installer
3. Open Command Prompt
4. type git and press enter

### Expected behavior

With GitHub Desktop, you get a command line version of Git with a robust GUI.

### Actual behavior

Command line version of Git is not installed 

### Screenshots

Self Explanatory doesn't need a screenshot

**Comment by sergiou87** [comment]
Hi @vmahadev! 👋 

I think you're right and we should update the documentation (because we won't bundle a version of git that you can easily use from command line). If you opened the command prompt from GitHub Desktop (using `Repository` -> `Open in Command Prompt`) you would've been asked to install Git first following this guide: https://help.github.com/articles/set-up-git/#setting-up-git

We'll get the documentation fixed. Thank you for the report! ❤️
