### ISSUE TITLE
Is GitHub Desktop compatible with dev.azure repositories?

### ISSUE THREAD

**Issue by ericoporto** [desktop/desktop#12055]
This is just a question really, could not find a channel to ask from reading the README. 

Is GitHub Desktop supposed to be compatible with Azure Repos in dev.azure.com ?

The user interface from GitHub Desktop is really good and I am curious if I could use it with Azure repositories and expect it to work with it.

**Comment by steveward** [comment]
Thanks for the issue @ericoporto. GitHub Desktop does support third-party integrations -- you will need to generate an authentication token since we do not provide direct authentication, though. The Azure DevOps guide can be found here:

https://github.com/desktop/desktop/blob/development/docs/integrations/azure-devops.md

I'm going to close this out, but let me know if you run into any issues!
