### ISSUE TITLE
Can't publish repository 

### ISSUE THREAD

**Issue by iccontemporary** [desktop/desktop#12063]
Whenever I try to publish my repository, it loads all the way until the end and then fails last second. 

This is the error I get:

Total 4990 (delta 2243), reused 0 (delta 0), pack-reused 0
fatal: the remote end hung up unexpectedly
Everything up-to-date

**Comment by steveward** [comment]
Thanks for the report @iccontemporary . Could you upload the full log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by iccontemporary** [comment]
Thanks, I realized it's actually because my file is over 2gb! Working on downsizing it and then trying again.

**Comment by steveward** [comment]
Thanks for the update -- that would definitely cause this type of issue. [Git LFS](https://docs.github.com/en/github/managing-large-files/configuring-git-large-file-storage) is recommended for large files. Let me know if you have any questions about setting that up.
