### ISSUE TITLE
getaddrinfo() thread failed to start

### ISSUE THREAD

**Issue by GLITCHEDITZ16** [desktop/desktop#12077]
When I am trying to add a repositry if mine i am getting an error which says ``getaddrinfo() thread failed to start`` please help

**Comment by steveward** [comment]
Thanks for the report @GLITCHEDITZ16. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
