### ISSUE TITLE
[UI Enhance] add icons button in header

### ISSUE THREAD

**Issue by danny007in** [desktop/desktop#12078]
![GitHubDesktop_2Fbqrn2pTT](https://user-images.githubusercontent.com/50356015/116233606-20e9b280-a779-11eb-8e98-3fa25aaf08d8.png)

**Comment by steveward** [comment]
Thanks for the feedback @danny007in. Since the fullscreen and settings menu are both already accessible via the menu and keyboards shortcuts we have no plans to add separate icon buttons for them.

Regarding notifications -- this is something we are thinking through, specifically around pull requests. I'd recommend following along with https://github.com/desktop/desktop/issues/11517 for updates about this.
