### ISSUE TITLE
Cannot stage per line in unified diffs when hiding whitespace 

### ISSUE THREAD

**Issue by mischnic** [desktop/desktop#12109]
### Describe the bug

I used to be able to click on the code gutter to unstage specific lines of a file.

### Version & OS

Version 2.8.0
macOS 10.15.5

### Steps to reproduce the behavior

1. Go to a changed file in diff view
2. Try to click on the blue gutter of a line

### Expected behavior

The line should be unstaged / unselected for commiting

### Actual behavior

Nothing happens

### Additional context

I do hope this is a bug and not an intentional change

**Comment by billygriffin** [comment]
@mischnic Thanks so much for reporting! ~This is definitely not an intentional change.~ edit: looks like the particular combination is an intentional change

Two questions? 
- Are you using split or unified diffs?
- Do you have "Hide whitespace changes" selected?

I'm able to reproduce this bug, but only when I'm on unified diffs *and* have selected "Hide whitespaces changes," so it feels possibly related to the new feature in 2.8. We'll prioritize looking at this next week, and thank you again for the issue! ❤️ 

@say25 Certainly no obligation, but if you have ideas here, I'd love to hear them.

**Comment by mischnic** [comment]
Thanks for the quick reply 👍 

> but only when I'm on unified diffs and have selected "Hide whitespaces changes,"

Yes, the three other combinations work fine for me as well.

**Comment by say25** [comment]
This is currently disabled by design. We thought this was the simplest thing to iteratively ship.

https://github.com/desktop/desktop/pull/6818#issuecomment-491837408

**Comment by billygriffin** [comment]
Agh, right @say25, apologies and thank you for the pointer. We can discuss this more and try to figure out a way to at least convey to people why the feature they're used to isn't available anymore (in this particular circumstance), or maybe some other solution.

**Comment by mischnic** [comment]
I didn't think about how hiding whitespaces changes and per line staging together are problematic, but that totally makes sense. At least some kind of tooltip when hovering over the gutter/clicking on it would be great.

**Comment by tidy-dev** [comment]
@mischnic @billygriffin There is 🙂
![Screen Shot 2021-05-03 at 7 32 20 AM](https://user-images.githubusercontent.com/75402236/116871172-d84f5080-abe1-11eb-81dc-ddc4d479af63.png)

But, maybe needs to be on click as well?

**Comment by mischnic** [comment]
Wow, I didn't see that 🙈 

But yeah, maybe this could be made more apparent.

**Comment by billygriffin** [comment]
The lag of tooltips strikes again! Thanks @tidy-dev. We'll chat about this internally and see if we can figure out a more obvious solution. 😄

**Comment by sergiou87** [comment]
Addressed here: https://github.com/desktop/desktop/pull/12129

Thanks again for your report! I hope those changes help 😄
