### ISSUE TITLE
Unicode display in comparison plane

### ISSUE THREAD

**Issue by cupress** [desktop/desktop#12128]
### Describe the feature or problem you’d like to solve

Unicode characters don't display in the comparison plane.

### Proposed solution

We preview editorial changes made by a freelance editor, and it's important to ensure that the correct Unicode characters are being used.

**Comment by sergiou87** [comment]
Hi @cupress! 👋  Thank you for your report.

Could you share a screenshot explaining what's missing? Does this bug exist in both split and unified views?

**Comment by cupress** [comment]
![GitHub-unicode](https://user-images.githubusercontent.com/12968131/117022881-9b10be80-acc6-11eb-8e5d-05532cc8c3f8.PNG)

**Comment by cupress** [comment]
I think I'm in the default view, which is split? I'm new to this product.

**Comment by sergiou87** [comment]
Oh, no worries!

This would be the split view (2 columns, one for green and one for red changes):
![image](https://user-images.githubusercontent.com/1083228/117034434-97e7f380-ad03-11eb-9622-1af214d64db8.png)


And this is the unified view (1 column with both green and red changes):
![image](https://user-images.githubusercontent.com/1083228/117034500-a7ffd300-ad03-11eb-84a9-dca1647b6d92.png)

And in that gear button at the top you can switch between them:
![image](https://user-images.githubusercontent.com/1083228/117034583-c239b100-ad03-11eb-8ec4-7becf0db376d.png)

I'd be curious to know if it doesn't happen in the Unified view. And I wonder that, because the way Unified and Split views present the text you see is quite different.

Thanks for taking the time to share a screenshot! That definitely helps 😄

**Comment by cupress** [comment]
Thanks for that detail. I'm still seeing the  little ? character in place of the Unicode in the Unified view. I'm using GitHub Desktop version 2.80 on Windows 10 version 20H2.

**Comment by cupress** [comment]
Ah, I just figured out that the editor is _not_ using Unicode for that character, he used é. I should have checked the underlying XML before opening this ticket. Thank you for your patient assistance, and sorry for the unnecessary ticket.

**Comment by sergiou87** [comment]
No problem, I'm glad you found the solution! 😄
