### ISSUE TITLE
File selector instead of folder selector when cloning a repository

### ISSUE THREAD

**Issue by antoinedespres** [desktop/desktop#12149]
### Describe the bug

When cloning a repository, the "Choose..." button opens a file selection window instead of a folder selection window.

### Steps to reproduce the behavior

1. Go to "File"
2. Click on "Clone repository"
3. Click on "Choose..."

### Expected behavior

We are supposed to choose a path, not a file

### Actual behavior

A file selection window appeared instead (a Save as window)

### Screenshots

See attached screenshot
![image](https://user-images.githubusercontent.com/58844676/117186289-f6cc6c00-adda-11eb-8cb2-8dcbb3d2fd3e.png)

### Logs

Not needed

### Additional context

None

**Comment by tidy-dev** [comment]
@antoinedespres Thank you for your feedback. We chose to [refactor to use the save dialog](https://github.com/desktop/desktop/pull/11949). This is because when you clone you should be creating a new folder. Thus, whatever is in that top text field `Nom due fichier` will be the directory that it creates for you.

**Comment by jjlittlezz** [comment]
Ok do it
