### ISSUE TITLE
access denied

### ISSUE THREAD

**Issue by Malibakiso1** [desktop/desktop#12144]
The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed

**Comment by steveward** [comment]
@Malibakiso1 thanks for the issue. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by Malibakiso1** [comment]
Hi, @steveward  the issue has been resolved, the admin gave access. thanks

**Comment by steveward** [comment]
Glad to hear you things are working now!
