### ISSUE TITLE
Pre- and Post-Pull Scripts

### ISSUE THREAD

**Issue by dangowans** [desktop/desktop#12161]
### Describe the feature or problem you’d like to solve

Before my systems administrator pulls the latest code into production from GitHub Desktop, he has to stop a Windows service.  After the pull is finished, he has to run `npm install`, then restart the service.  It would be great if when he opens up GitHub Desktop to pull the latest code, a script could run before and after the pull that could handle those tasks.

### Proposed solution

Have the ability to assign scripts that would run before and after the pull process.  I'm not sure if the scripts should sit in the repository itself or locally somewhere else as they may be unnecessary or sensitive at times.  If the scripts are specially named files in the repository, maybe prompt the user, asking if they wish to run the pre- and post-pull scripts or not.

**Comment by steveward** [comment]
Thanks for the issue @dangowans. At this time we don't have any plans to allow running custom scripts apart from the already available Git hooks. Is there a specific reason the `git pull` needs to be run in GitHub Desktop instead of in something like a PowerShell script? You could install Git for Windows to make Git available and then write a PowerShell script to automate this process.

I'm going to close this out, but thanks for using GitHub Desktop!
