### ISSUE TITLE
can't find "repo" error

### ISSUE THREAD

**Issue by staabm** [desktop/desktop#12185]
### Describe the bug

my PC got stuck and I had to cut the power to get it working again.
after restarting windows my git reposes which seem to had some activity at the time the PC got stuck seem to be "broken" now.

![grafik](https://user-images.githubusercontent.com/120441/117622304-cbe36e80-b172-11eb-8499-0ec55e8a5a02.png)

clicking the "Clone Again"-button brings up a error dialog:

![grafik](https://user-images.githubusercontent.com/120441/117622372-e0276b80-b172-11eb-9b5e-f2434e194358.png)

clicking "retry clone" brings back the same dialog.
clicking "cancel" brings me back to the initial view (see 1st screenshot).

a `git status` on the commandline errors with `fatal: unterminated line in .git/packed-refs: ...`

### Version & OS

windows 10x64, latest updates
github desktop 2.8.1
git version 2.31.0.windows.1

### expected result

the error state in github desktop is a bit misleading, especially because there seems to be a more detailed/precise error message git could provide, as can be seen from the `git status` line.

I guess DX wise it would be great if github desktop could somehow incorporate the underlying git error message into the dialog, so the enduser is not stuck with a dialog which cannot solve the actual problem.

**Comment by staabm** [comment]
after googling my error message, I was able to recover the git repo by just deleting the `.git/packed-refs` file, as described here: https://stackoverflow.com/a/56401291.

please see my initial report as a inspiration of how github desktop could have helped the end user and don't close it as is, since I was able to fix my problem at hand on my own.

I guess a lot of less experienced users would have deleted their local repository, re-cloned everything and lost all the work not yet pushed to a remote.

**Comment by tidy-dev** [comment]
@staabm I glad you were able to resolve your issue. As this was a result of the .git files becoming corrupted/in a bad state, it would likely be a lot of effort to even attempt to provide the user with instructions since there could be multiple ways that a git repository could be in a bad state especially as a result of a mid-flight cut off (not a typical user pattern). Thus, this is not currently on our roadmap, but thank you for the report and even tho this is closed it will be out there for other users to find. 🙂

**Comment by staabm** [comment]
Thx for the reply. 

Do you think it could be helpful to note/add a Tip, that the git cli might provide further insights in case of errors?

**Comment by tidy-dev** [comment]
@staabm When we attempt to read a directory as a git repository and it fails,  it means we can't find the repo (or something that looks like the repo) where we think it is stored at. Thus our current message to the user `Can't find repo_name` is an accurate note. Tho I can see in your scenario that is not the most direct note and potentially confusing since you look in the directory and it appears it is there. 

Potentially if we were to change our message to something like `It was last seen.... Check again. If it is still there, it is in an unreadable/corrupt state.` 

I think this would just lead a less experienced user to remove/reclone (effectively the on/off of a repo) and not do as you did and find out how to modify/delete things in the .git files

Thus, the only way to lead a user to correcting their .git files would be to always display an error snippet here that would be searchable. This would definitely be a design change warranting further discussion/research into other possible errors here.
