### ISSUE TITLE
bad credentials

### ISSUE THREAD

**Issue by Andrey75YAGI** [desktop/desktop#12236]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by steveward** [comment]
@Andrey75YAGI normally a `bad credentials` error can be resolved by logging out and then logging back in to GitHub Desktop. If that does not get things working it would be helpful if you could upload the log file from GitHub Desktop so that we could get some more information.

To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
