### ISSUE TITLE
Function to add categories to the repository list.

### ISSUE THREAD

**Issue by AsierArizti** [desktop/desktop#12254]
Function to add categories to the repository list.

using the same scheme that git desktop has for organizing repositories with "Recent" and "Other", that the user can organize his repositories by groups with an add category button

![image](https://user-images.githubusercontent.com/62993835/119093816-7af43580-ba10-11eb-9e1b-7d32f0c62a80.png)

**Comment by steveward** [comment]
Thanks for the feedback @AsierArizti. At this time we don't have any plans to allow for custom group names since we already group repositories by user/org/recent/other. Repository list reordering is something we may look into in the future, and is being tracked in issues like https://github.com/desktop/desktop/issues/8183 and https://github.com/desktop/desktop/issues/11608. I'm going to close this out since we're tracking repository list improvements in multiple issues.
