### ISSUE TITLE
Branch : Set Default

### ISSUE THREAD

**Issue by goyalyashpal** [desktop/desktop#12311]
### Describe the feature or problem you’d like to solve

Some way to set a branch as default from GHD - this is available in `/settngs/branches` > [Default branch🡭](https://docs.github.com/en/github/administering-a-repository/managing-branches-in-your-repository/changing-the-default-branch) in GHWeb

### Proposed solution

option in branch's context menu

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

GHWeb (available)
![image](https://user-images.githubusercontent.com/19423063/120037637-94ecd400-c01f-11eb-8b2c-0ff93105bc15.png)

GHD (suggestion)
![image](https://user-images.githubusercontent.com/19423063/120037571-7981c900-c01f-11eb-9320-4e05fd1e4fa2.png)

---
duplicate search: [default branch](https://github.com/desktop/desktop/issues?page=2&q=is:issue+is:open+default+branch)

**Comment by goyalyashpal** [comment]
tangentially related (same topic): https://github.com/desktop/desktop/issues/11530

**Comment by billygriffin** [comment]
Thanks for this one as well @yashpalgoyal1304. Because it's not a super common use case to change default branches, I think we're ok for now leaving this as just available on GitHub.com unless we hear a lot more feedback that people are wanting to do this in Desktop. A lot of work went into the implementation on dotcom and I think we'd prefer to rely on that doing its job as opposed to trying to do anything outside of that context. Hope that makes sense, and sorry this isn't something we plan to support.

I definitely agree that #11530 would be nice to allow folks to immediately delete the local branch with the old default branch name.

**Comment by tpilewicz** [comment]
I use Github Desktop not only for repos hosted on Github.com, but also for repos on Gitlab and Bitbucket. This feature would be useful for people in my situation. Currently, its absence means that on my repos that are not hosted on Github and that don't have `master` as their default branch, Github Desktop simply doesn't know what the default branch is.
