### ISSUE TITLE
Failed to authenticate Gitlab - Ask for password, but it should ask for personal token instead

### ISSUE THREAD

**Issue by olIoNyaMIXATu** [desktop/desktop#12323]
### Describe the bug

Can't login in Gitlab

### Version & OS

Version 2.8.2 (x64)
Windows 10 20H2 (build 19042.985)

### Steps to reproduce the behavior

1. Open a repo with origin to GitLab
2. Commit
3. Push
4. Github Desktop asks to authenticate
5. Can't login.

### Expected behavior

Login is successfull

### Actual behavior

Login is unsuccessfull

### Screenshots

![immagine](https://user-images.githubusercontent.com/48022087/120183854-c91eeb00-c1ff-11eb-9b6d-f328c52e9926.png)

**Comment by sergiou87** [comment]
Hello @ArmelliniFederico! 👋 

Are you using your account password or a personal access token?

Not sure if it's a requirement with GitLab accounts, but maybe it helps? https://stackoverflow.com/a/51133684

**Comment by olIoNyaMIXATu** [comment]
Hi, I've followed the stackoverflow link you posted and now it all works. 

"Password", as you can see in my screenshot, is misleading: how an user can know that he has to generate a personal token?

**Comment by sergiou87** [comment]
Yes, I understand the confusion: git asks for username and password (which is what we prompt there), it just happens that GitLab (and GitHub nowadays) requires a Personal Access Token to be used as a password. I'll discuss with the team about other ways to clarify this.

Unless I'm wrong, the dialog showing you the "authentication error" listed a few reasons why it failed to authenticate. Would it help to have another bullet point in it suggesting to use a Personal Access Token instead of your account password?

In any case, I'm happy it worked!! 😄

**Comment by olIoNyaMIXATu** [comment]
Yes, please add more info to the dialog in order to make it easier to understand the issue

Thank you

**Comment by Ruoh3kou** [comment]
This also confuses me, showing password but entering token....
