### ISSUE TITLE
Error on app startup

### ISSUE THREAD

**Issue by toddpage** [desktop/desktop#12346]
### Describe the bug

On startup get an error message, but app still works

### Version & OS

OS X 10.11.6

### Steps to reproduce the behavior

1. Start app

### Expected behavior

app opens without error message

### Actual behavior

app opens with error message

### Screenshots

![Screen Shot 2021-06-02 at 9 22 03 AM](https://user-images.githubusercontent.com/34070658/120497564-22178c00-c384-11eb-8392-f3b2d000e81b.png)

### Logs

[2021-06-02.desktop.production.log](https://github.com/desktop/desktop/files/6585205/2021-06-02.desktop.production.log)

**Comment by sergiou87** [comment]
I see you're using macOS El Capitan (10.11) , which is kind of old, and is hard for us to keep compatibility with it (already had compatibility issues, see https://github.com/desktop/desktop/issues/11516#issuecomment-773176786). Right now, git lfs is built using macOS Mojave's SDK (10.14).

Is this something new with the latest version (2.8.3, released today) or did it happen before?

**Comment by MacTerrassa** [comment]
Hi, I have the same problem. And it starts at the previous version 2.8.2 and continues at 2.8.3. I think that the previous 2.8.1 opened correctly, although I have not used it for a long time. But neither of the last two opens correctly. 
I understand that they are "old" systems (I also use 10.11.6), but if it is not possible to correct the operation in them, why not indicate new requirements? Obviously, I prefer that they keep the support :-) but if it is not possible, the logical thing is to indicate it. And better if they keep a really compatible previous version available to download to those who need it.
Thanks

**Comment by sergiou87** [comment]
> but if it is not possible to correct the operation in them, why not indicate new requirements?

The truth is we haven't been able to confirm is ourselves, and we didn't see any reports indicating otherwise (until now 😅 ). We'll evaluate and see what we can do about it, thank you for your feedback! And sorry for any inconvenience this could've caused you 😥

**Comment by elder-n00b** [comment]
Hi, I have the same problem too (Version 2.8.3 (x64) on macOS 10.11.6).
It's because of `clock_gettime()` used by `git-lfs`. The function was added in macOS 10.12 as far as I know.
I found [Drop obsolete OS support #4328](https://github.com/git-lfs/git-lfs/pull/4328) but it only mentions CentOS 6 and Debian 8.
~~A fallback implementation like [this one](https://gist.github.com/alfwatt/3588c5aa1f7a1ef7a3bb) could probably help keeping the compatibility.~~
I think this should be reported to git-lfs. -- Edit: opened [4520](https://github.com/git-lfs/git-lfs/issues/4520).
Error message and log file just in case:
[ERROR__GitHubDesktop__clock_gettime.txt](https://github.com/desktop/desktop/files/6611279/ERROR__GitHubDesktop__clock_gettime.txt)
[2021-06-07.desktop.production.log](https://github.com/desktop/desktop/files/6611434/2021-06-07.desktop.production.log)

**Comment by elder-n00b** [comment]
In case it matters, the previous git-lfs 2.13.2 release works on macOS 10.11.6 as is.  
Maybe just downloading that one on systems before 10.12 will do for a while (no `git lfs prune` [bug](https://github.com/git-lfs/git-lfs/pull/4407)[fix](https://github.com/git-lfs/git-lfs/pull/4449) though).  
Also, the nice guys at git-lfs told me how to recompile it on 10.11 (see [here](https://github.com/git-lfs/git-lfs/issues/4520#issuecomment-857912248)), that's unsupported but works.
