### ISSUE TITLE
When I try to add a new repo. I get an error in the cloning process as filename too long for some of my files.  I am working on a windows (windows 10) machine. expected behavior: repo cloned successfully.

### ISSUE THREAD

**Issue by reholman-CLGX** [desktop/desktop#12352]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by steveward** [comment]
@reholman-CLGX thanks for the issue. I'm going to quote [this reply](https://github.com/desktop/desktop/issues/8023#issuecomment-515110259) which has helpful information about this:

Because of a Windows API limit paths longer than `MAX_PATH` (260 characters) on Windows are not supported by default in Git for Windows, which is used in Desktop. [This document](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file) talks about the limitation and the workaround (using the extended-length path syntax).

Have you set `core.longpaths` to `true` before cloning to opt-in for using the extended-length path support?

```
$ git config --global core.longpaths true
```

There's some caveats to this from the [Git for Windows documentation](https://github.com/git-for-windows/git/blob/d003d728ffa6c0006da875ec6318d3f6b28a4ddb/Documentation/config/core.txt#L560-L565) which is why we don't enable this by default:

```
core.longpaths::
	Enable long path (> 260) support for builtin commands in Git for
	Windows. This is disabled by default, as long paths are not supported
	by Windows Explorer, cmd.exe and the Git for Windows tool chain
	(msys, bash, tcl, perl...). Only enable this if you know what you're
	doing and are prepared to live with a few quirks.
```

Let me know if you have any further questions about this.
