### ISSUE TITLE
i could not able to do "fetch origin" 

### ISSUE THREAD

**Issue by hitheshthummala** [desktop/desktop#12363]
### Describe the bug

even though i have stable internet connection i could not able to do fetch origin and pull/push using the desktop app, i always need to use terminal for that, it is showing error connection or timeout etc....

### Version & OS

Version 2.8.3 (x64), windows 10 os,

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by steveward** [comment]
Thanks for the report @hitheshbynark. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
