### ISSUE TITLE
Regression: can no longer toggle lines to be included/excluded from commit

### ISSUE THREAD

**Issue by martinbean** [desktop/desktop#12360]
### Describe the bug

When viewing a file, I used to be able to click a line number in the left-hand gutter to include/exclude that line from the pending commit. Now, the changed lines are still highlighted in blue, but clicking a line number doesn’t do anything.

### Version & OS

Version 2.8.3 (x64)

### Steps to reproduce the behavior

1. Open any file.
2. Click a line number in the file gutter.

### Expected behavior

Clicking a line number highlighted in blue will de-select that line from the pending commit. Clicking the same line number again would re-select it.

### Actual behavior

Nothing, as described above.

### Screenshots

![github-desktop](https://user-images.githubusercontent.com/167312/120708657-c2200300-c4b3-11eb-987c-d8444650a342.gif)

**Comment by tidy-dev** [comment]
@martinbean Hi! This is disabled if you have Hide Whitespace Changes checked due to to complications attempting to commit a partial diff if when white spaces are hidden. Can you see if you have that checked? I am unable to reproduce this otherwise

![image](https://user-images.githubusercontent.com/75402236/120715760-11a20700-c493-11eb-886c-c41c51bdc89b.png)

**Comment by martinbean** [comment]
@tidy-dev Yeah, that was it. Thanks.
