### ISSUE TITLE
Taking unusually long time to fetch origin or commit changes. Also, showing wrong information such as "branch is up to date with master" even when it's not, or not picking up the remote changes from others branches all of a sudden

### ISSUE THREAD

**Issue by ameyjain99** [desktop/desktop#12401]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by steveward** [comment]
Thanks for the report @amey-tech. Could you upload the log file from GitHub Desktop so that I could get some more information about these issue? The log file should show Git operation performance and if there are any connection issues.

To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
