### ISSUE TITLE
same issue, please do not close until solved

### ISSUE THREAD

**Issue by burgil** [desktop/desktop#12411]
same issue: please do not close until solved https://github.com/desktop/desktop/issues/12400

**Comment by billygriffin** [comment]
@orrburgel Since @steveward has been corresponding with you in the original issue and politely [asked you](https://github.com/desktop/desktop/issues/12400#issuecomment-856766529) to continue discussing there, and you ignored his request and continued to create new issues, this constitutes harassment and I'm therefore temporarily banning you from the project.
