### ISSUE TITLE
Windows is adding support to change default terminals

### ISSUE THREAD

**Issue by just1a-person** [desktop/desktop#12463]
### Describe the feature or problem you’d like to solve

Windows is adding support to change default terminal when launching command line apps. If a user launches `powershell.exe` or `cmd.exe`, it will open in their default terminal.

### Proposed solution

Remove Windows Terminal (or any other terminal applications) from shell options (after this feature is released in the main builds of Windows).

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

![Option to choose default terminal](https://user-images.githubusercontent.com/75578443/122254656-f13e6780-ceea-11eb-86fe-46eebb1348d2.png)

**Comment by steveward** [comment]
@itsme-alan thanks for the issue. Just to outline things:

- Starting with Windows 10 build 21390 users can select a default terminal, either Windows Console Host (the default) or Windows Terminal Preview.
- If Windows Console Host is selected then PowerShell, etc. will open in its own console window
- If Windows Terminal Preview is selected then PowerShell etc. will open inside Windows Terminal

I can understand your reasoning here, but I don't think it's necessary to remove this integration just because this feature will be available. Not all users may end up changing the default terminal even if they do have the new Windows Terminal installed.

I'm going to close this issue out, but we can revisit this again in the future if it's something that we continue to get feedback about.
