### ISSUE TITLE
Every time I merge a branch and delete it on remote, prompt me to delete locally

### ISSUE THREAD

**Issue by owenbrownzc** [desktop/desktop#12472]
### Describe the feature or problem you’d like to solve
I wind up with branches on my local that have already been merged.

### Proposed solution
GitHub Desktop prompts me "these branches have been merged and deleted. Shall we delete locally?"

How will it benefit Desktop and its users?
They don't have to remember to delete the branch.

(alternative solutions would be just to tell me which branches got merged, if the commit hashes match)

**Comment by steveward** [comment]
Thanks for the feedback @owenbrownzc. GitHub Desktop will automatically delete local branches associated with a remote branch that have been merged into the default branch after 14 days have passed. We also recently added the ability to quickly delete branches via the branch menu. Since we have both those features at this time we don't have any plans to add a prompt about this. I'm going to close this out.
