### ISSUE TITLE
Github Desktop - Fails to Push Commits over SSH if the SSH Key has Passphrase

### ISSUE THREAD

**Issue by akshayshrivastav** [desktop/desktop#12484]
### Describe the bug

Github desktop does not ask for SSH Passphrase ( if any set ) which gives an error while pushing commits

### Version & OS

Windows 10
Version 1909 ( OS Build 18363. 1556 )

### Steps to reproduce the behaviour

1. Generate an SSH Key with a passphrase
2. Clone your repository via SSH
3. Edit any file in that repository and commit the change
4. Push commit via git CLI, it will ask you for the passphrase and it will push your commit **but and but** if you push this commit via GitHub desktop it will show you an error as below

![image](https://user-images.githubusercontent.com/30490481/122665831-474f2b80-d1c7-11eb-8ec5-e9af3ceb2038.png)

### Expected behaviour

Expected behaviour should be to ask for a passphrase via popup and store it for future reference / some other workaround. But it should ask for a passphrase ideally instead of showing the error.

### Actual behaviour

![image](https://user-images.githubusercontent.com/30490481/122665840-58983800-d1c7-11eb-96e5-dd8e79ba37dc.png)

**Comment by steveward** [comment]
@akshayshrivastav866 thanks for the issue. We are tracking this in https://github.com/desktop/desktop/issues/2579, and I would recommend following along there for improvements to SSH. 

Are you still having issues getting SSH working? I'm going to close this out since we are aware of this, but let me know if I can help with any problems you are having.
