### ISSUE TITLE
GitHub Desktop keeps adding the Windows line separators 

### ISSUE THREAD

**Issue by fabtjar** [desktop/desktop#12482]
I'm using Windows 10 with WSL2. When using git in the terminal within WSL and my IDE (PyCharm) all the line separators are the unix style how I want them. As soon as I open GitHub Desktop it converts the line separators to the Windows version (^M) for my one file (manage.py). 

I try to discard changes through the desktop app and in the terminal and it doesn't seem to be doing anything. If I close GitHub Desktop and undo the changes everything works as expected.

This still happens when the IDE isn't open.

Using:
Windows 10 - Version 20H2 (OS Build 19042.985)
Ubuntu 20.04.2 LTS
WSL2

**Comment by steveward** [comment]
@fabtjar thanks for the issue. This is the expected behavior when going from *nix  => Windows -- see [Microsoft's note](https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-git#git-line-endings). You can read [this help article](https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings) for more information about managing line-endings. I generally recommend adding a `.gitattributes` files with `* text = auto` as that ensures line-endings are normalized for all users. Once you do that and commit those changes you shouldn't run into any further issues.

If you'd like to disable line-ending conversions in this specific repository you can add this line to the `.gitattributes` file:

`* -text`

I hope that helps!

**Comment by jyin-tc** [comment]
This SHOULD NOT be expected behaviour, as it causes issues like git thinking every line has been changed because it decided to add the windows line endings to everything, there should be a setting in github desktop to disable this globally.

**Comment by fabtjar** [comment]
> This SHOULD NOT be expected behaviour, as it causes issues like git thinking every line has been changed because it decided to add the windows line endings to everything, there should be a setting in github desktop to disable this globally. 

I'm not sure if the desktop app handles global settings but I got it set globally with git on my machine from looking into the above comment.

**Comment by MsKarMagick** [comment]
It completely ignores `* -text` in the .`gitattributes` and messes up all my lines and hashes. Aggravatingly infuriating and as stated above **SHOULD NOT** be treated as expected  behavior.

**Comment by HoangNguyen679** [comment]
Does anyone have solution for this problem ？ When I pull a repository, open Github Desktop, it told me there are more than 5000 files changed. All the files have new ending ^M (CRLF) instead of (LF) in Ubuntu environment. I think it is definitely not the expected behavior.
