### ISSUE TITLE
Show Quick Access also if there are changes

### ISSUE THREAD

**Issue by danielehrhardt** [desktop/desktop#12483]
### Describe the feature or problem you’d like to solve

It would really nice to have this Quick Access Features even if there are pending changes. Currently, this Page is not accessible when there a changes. 
![image](https://user-images.githubusercontent.com/19570043/122643450-3394be00-d110-11eb-9eaa-eee00a8f4643.png)

### Proposed solution

Add a new Tab, something like "Overview" or "General"
![image](https://user-images.githubusercontent.com/19570043/122643466-48715180-d110-11eb-8b5c-d695af1d1e89.png)

**Comment by tidy-dev** [comment]
@danielehrhardt Thanks for the input. We try to be very intentional when adding new features to the UI to make sure we don't add unnecessary complexity and since all of these suggested actions are available in repository menu and via a keyboard shortcut at all times. Creating a new general tab would likely not add enough value to the application; as opposed to where we have it now when the user has no changes and thus friendly prompts instead of a blank screen provides additional value.
