### ISSUE TITLE
Allow cloning for admins of non-owned, private repositories

### ISSUE THREAD

**Issue by kdarras** [desktop/desktop#12502]
I am an admin of a private repository that is owned by the organisation I work for, but not by my personal GitHub account. I would like to manage it using GitHub desktop, but it does not show up in the list of my repositories (which is consistent with the online list under "your repositories") and I cannot clone it either (which is not consistent with the online behavior, since I can close it from that interface).

If I am an admin of a repository, it should sow up under "Your repositories".
If this is not possible, GitHub desktop should at least be consistent with the online platform and allow cloning of that repository.

I use Ubuntu 20.04 with GitHub Desktop from https://gist.github.com/berkorbay/6feda478a00b0432d13f1fc0a50467f1

**Comment by steveward** [comment]
@kdarras thanks for the issue. Any repositories that you have correct access permissions to should appear in GitHub Desktop under the organization account. They will not appear under your user  since they are not associated with that account.

Can you go to the `Clone Repository` > `GitHub.com` view and verify that the repository is not listed under the organization?

**Comment by kdarras** [comment]
I do not have access to the organisation account. But from my user account, indeed the repository that I administer with it is not listed under Clone Repository > GitHub.com.

**Comment by steveward** [comment]
@kdarras are you able to clone the repository via the command line? It'd be helpful if you could share your log file so that we could get a better idea of the issue. You are using the unofficial Linux fork, which we generally recommend opening issues for in https://github.com/shiftkey/desktop/issues, but I can take a look at the log file and see if there is anything indicating the issue.

To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs...`.

**Comment by kdarras** [comment]
Yes I was able to clone it with the command line with `git clone` in the terminal and this generally works well (commit, push, fetch, etc.)

I am really confused because after this, I managed to clone it only once with the Desktop app, but I could not reproduce it after removing the repository. I am based in China so it may depend on the VPN, current logged in state, etc. Often I cannot even authenticate with the Desktop application and connections time out. I feel like my description is not very helpful, but attach the log of what I have been doing here, for what it's worth.

I asked the organisation owner to check the OAuth restrictions in the meantime.

**Comment by kdarras** [comment]
[2021-06-28.desktop.production.log](https://github.com/desktop/desktop/files/6724255/2021-06-28.desktop.production.log)

**Comment by kdarras** [comment]
I asked the organisation owner to check the OAuth restrictions in the meantime.

**Comment by shiftkey** [comment]
```2021-06-28T07:01:16.358Z - error: [ui] Failed to look up canonical clone url for 'https://github.com/SAT-Lab-GitHub/ecocam/'
Error: Although you appear to have the correct authorization credentials, the `SAT-Lab-GitHub` organization has enabled OAuth App access restrictions, meaning that data access to third-parties is limited. For more information on these restrictions, including how to enable this app, visit https://docs.github.com/articles/restricting-access-to-your-organization-s-data/
    at Ve (/home/kdarras/webpack:/app/src/lib/http.ts:170:11)
    at ut.fetchRepositoryCloneUrl (/home/kdarras/webpack:/app/src/lib/api.ts:620:11)
    at qv.resolveCloneURL (/home/kdarras/webpack:/app/src/ui/clone-repository/clone-repository.tsx:614:7)
    at Object.clone [as onSubmit] (/home/kdarras/webpack:/app/src/ui/clone-repository/clone-repository.tsx:631:11)
```

**Comment by steveward** [comment]
@kdarras thanks for sharing the log. Based on what @shiftkey shared above from the log it looks like you need to request permission to use GitHub Desktop due to the organization restricting OAuth applications. You can find the for how to do that here:

https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/managing-your-membership-in-organizations/requesting-organization-approval-for-oauth-apps

I'm going to close this out, but let me know if you have any further issues.

**Comment by kdarras** [comment]
Yes you are right, this is likely the issue. I have been trying to confirm the past week but the repository owner still has not changed the OAuth settings.
