### ISSUE TITLE
Need create tag name more friendly

### ISSUE THREAD

**Issue by nghuyy** [desktop/desktop#12509]
Hey.

 I think, when we create new tags name, need show all tag history like

![image](https://user-images.githubusercontent.com/1293057/123372230-66760080-d5ad-11eb-854f-5c048d36e0eb.png)

it usefull way for create new tag with version or check duplicate tag or simple select new copy

**Comment by ADustyOldMuffin** [comment]
Since I'm free now I'd love to take this!

**Comment by ADustyOldMuffin** [comment]
@sergiou87 Is this open for picking up? If so is there any design that needs to happen before?

**Comment by sergiou87** [comment]
Nope, I'd wait a bit until we have time to discuss it ~~next week~~ in the upcoming weeks (maybe I went ahead too fast with the labels, sorry 🤣).

**Comment by sergiou87** [comment]
Hi again @ADustyOldMuffin! Sorry it took us so long to get back to you 😓 

We've discussed this and we think something like an auto-completion approach doesn't make much sense, since in the end you're not allowed to create duplicated tags. Instead, we think it might be better to just show a list of the last 3 tags right below the textfield to create the new tag:

![2021-07-20 at 11 08](https://user-images.githubusercontent.com/1083228/126294473-37620a59-4852-47ea-8b93-6c457a56f9c2.png)

That way the user can see the format used in existing tags.

It can be even a bit smarter by showing the last 3 tags that start with whatever the user has typed so far (in some kind of autocompletion fashion), allowing the user to explore/discover the created tags by typing, in case they're looking for a tag that is not among the last 3 tags.

What do you think?

**Comment by ADustyOldMuffin** [comment]
I can certainly take a stab at it! It sounds like a good start.
