### ISSUE TITLE
Commit exemption no longer working

### ISSUE THREAD

**Issue by YoungMayor** [desktop/desktop#12504]
### Describe the bug

Selective commit on files no longer working ever since update to latest version 

### Version & OS

Version 2.9.0 (x64) on MacOS

### Steps to reproduce the behavior

1. Modify a file on a repository 
2. Select out some lines that you do not want to be committed
3. Enter commit message and commit
4. The lines deselected for the commit are committed 

### Expected behavior

In previous versions of Github Desktop, the selected lines would have not been committed

### Actual behavior

In this current version, they got committed

### Screenshots

No Screenshots

### Logs

No Logs

**Comment by sergiou87** [comment]
Hello! Thank you for your report. I just tested this and it's working fine for me:

https://user-images.githubusercontent.com/1083228/123243249-1fbbd400-d4e3-11eb-94ea-dbc69caa60ee.mov

Can you provide more details (or even a video) about what happens in your case specifically?

**Comment by nycdotnet** [comment]
Hi - I am having this problem as well.

Video repro:

https://user-images.githubusercontent.com/3755379/123808034-61bb9000-d8be-11eb-9ac1-fa666dbbc4c7.mp4

**Comment by sergiou87** [comment]
Thank you for that video @nycdotnet! It was very useful 😄 

I think your problem is slightly different to what @YoungMayor described, since in his case he can deselect the lines but they get committed anyway.

In your case, @nycdotnet, I think the problem might be you have "Hide whitespace changes" enabled:

![2021-06-29 at 18 12](https://user-images.githubusercontent.com/1083228/123832337-8a1aad00-d905-11eb-90f6-e4c23e4eb6a2.png)

After that's enabled, if you hover over the line gutters for long enough, you will see a tooltip like this:

![2021-06-29 at 18 12](https://user-images.githubusercontent.com/1083228/123832494-afa7b680-d905-11eb-8a27-e1f59a1eb1f8.png)

**Comment by nycdotnet** [comment]
You are correct.  Thank you for the reminder @sergiou87 - clearly the huge billboard on the gear didn't get through to me.  :-(
