### ISSUE TITLE
file appearing as modified when not

### ISSUE THREAD

**Issue by RubenTanner** [desktop/desktop#12519]
### Describe the bug

after saving a file when no changes have been made the file appears as modified in VS code and Github Desktop even though no changes have been made

### Version & OS

Version 2.9.0 (x64). Windows 10

### Steps to reproduce the behavior

1) Open a file on VS code
2) make a modification and save
3) Delete the modification and return the document back to its original state
4) save the document

### Expected behavior

once changes are undone the Modified tag should be removed as nothing has been modified

### Actual behavior

the tag did not disappear on VS code nor on Github Desktop

### Screenshots

Add screenshots to help explain your problem, if applicable.

Original File
![VS code state 1](https://user-images.githubusercontent.com/76174821/123513892-aad5cf00-d687-11eb-8acd-de7ea7bb4ff8.PNG)

Modification made and saved
![VS code state 2](https://user-images.githubusercontent.com/76174821/123513906-b7f2be00-d687-11eb-9d9a-05c4853a851b.PNG)
![GD code state 1](https://user-images.githubusercontent.com/76174821/123513955-f38d8800-d687-11eb-8b55-581c8b28e9dc.PNG)

Modification undone and returned to original state
![VS code state 3](https://user-images.githubusercontent.com/76174821/123513911-c5a84380-d687-11eb-900b-e34ef4877c6e.PNG)
![GD code state 3](https://user-images.githubusercontent.com/76174821/123513973-0dc76600-d688-11eb-9013-378b8bc5c55e.PNG)

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

[2021-06-26.desktop.production.log](https://github.com/desktop/desktop/files/6720138/2021-06-26.desktop.production.log)

**Comment by steveward** [comment]
@RubenTanner this is often caused by line endings changes. What does the output of `git diff` from the command line share?

If you're having line-endings issues you may want to add a `.gitattributes` file with a `* text=auto` line. This should normalize the line endings and prevent this issue within this specific repository. See [this guide](https://docs.github.com/en/github/getting-started-with-github/configuring-git-to-handle-line-endings#per-repository-settings). Let me know if that helps!
