### ISSUE TITLE
switch to commit

### ISSUE THREAD

**Issue by Tsuj100** [desktop/desktop#12510]
Hope to provide the function to switch to a commit

**Comment by sergiou87** [comment]
Thank you for your feedback! ❤️  Right now we're providing an approximation to this by creating a branch from any commit since 2.9.0: #12160

Is this helpful for you?

We're discussing a more "direct" way to reset to a previous commit, but first we need to discuss about how to prevent that users will end up in a state where they don't know how to get back without "losing" their work.
