### ISSUE TITLE
File name in "Merge Conflict" is too short 

### ISSUE THREAD

**Issue by Aryaman73** [desktop/desktop#12515]
### Describe the bug

File name in "Merge Conflicts" wraps too early, making it effectively useless in figuring out what files have conflicts😕 I think the obvious solution is to decrease the padding between the text and the button since there is clearly enough space, but I also think the text name should be allowed to wrap to the next line. 

### Version & OS

Version 2.8.3 (x64), MacOS

### Steps to reproduce the behavior

1. Create files with long names or files deeply nested in a bunch of folders.
2. Create conflicting branches and trigger a merge conflict.

### Expected behavior

You can see the full file name.

### Actual behavior

File name is truncated.

### Screenshots

<img width="533" alt="image" src="https://user-images.githubusercontent.com/53343807/123477300-d5fae880-d5cb-11eb-955d-92f68a753250.png">
### Logs

Not Applicable

### Additional context

Not Applicable

**Comment by steveward** [comment]
Thanks for the feedback @Aryaman73. You can hover over the file to see the full file path -- would that be helpful for situations like this? How often are you running into this issue?

We shipped improvements to this in https://github.com/desktop/desktop/issues/6666 and have not heard much feedback about this since.
