### ISSUE TITLE
We were unable to authenticate with gist.github.com. Please enter your usemame and password to try again

### ISSUE THREAD

**Issue by Jarvine** [desktop/desktop#12521]
### Can no longer clone using Github Desktop

This is issue appears to be the same as the other similarly named issues, but I can't find one related to Ubuntu 18.04.

### Version & OS

Version 2.0.4-linux1, Ubuntu 18.04

### Steps to reproduce the behavior

1. Go to File
2. Click on Clone repository
3. On the Clone a repository window, click URL tab and enter https://github.com/pymc-devs/resources/tree/master/Rethinking

### Expected behavior

The repository is cloned in a folder (local path), as always.

### Actual behavior

Authentication failed....

![image](https://user-images.githubusercontent.com/36288542/123519958-45301580-d67c-11eb-9b15-300cd463f7ea.png)

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by Mrlinkwii** [comment]
:wave: linux isn't offically supported ( as per  https://github.com/desktop/desktop/issues/1525#issuecomment-783584346 ) but theirs a linux fork you can use   https://github.com/shiftkey/desktop/ to post said issue their  if its still occuring   also the version your using is old id recommend updating to the latest version also

**Comment by sergiou87** [comment]
Also, username/password is not supported anymore for repos hosted in GitHub and other services. Instead of the password, you must use a [Personal Access Token](https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token). We want to change that prompt to indicate this. You can find help for services other than GitHub in https://github.com/desktop/desktop/tree/development/docs/integrations

I'm gonna assume that's the problem and close this one out, if it doesn't help please let me know and I'll be happy to reopen it and follow up 😄
