### ISSUE TITLE
Cloning my fork actually clones the main branch

### ISSUE THREAD

**Issue by lucianowayand** [desktop/desktop#12565]
### Describe the bug

Cloning my fork actually clones the main branch, i created the repo then transfered to my organization, now i want to work on my changes before sending a PR but i cant without making a branch in the organization's repository. I can use it in the terminal with no problems.

When i clone using the github-desktop app it just clones the master and as i have acess to the main one my changes would be commited to the main.

### Version & OS

Version 2.8.1-linux2

### Steps to reproduce the behavior

1. Go to 'Current repository'
2. Go to 'Add'
3. Go to clone repository
4. Put the link of the forked repo (this one in my case: `https://github.com/lucianowayand/site-colmeia`)
5. Go to clone
6. Adds back the organization repo

### Expected behavior

Clone the fork in a separated folder

### Actual behavior

Clones the organization main repo

### Screenshots

![image](https://user-images.githubusercontent.com/36968613/124382197-96539100-dc9c-11eb-8ecf-2cf0673c63e4.png)

### Logs

https://pastebin.com/xS3kwV4k

**Comment by steveward** [comment]
Thanks for the issue @lucianowayand. I believe you are running into https://github.com/desktop/desktop/issues/12494, since transferring a repository also sets up a redirect for that repository.

I'd recommend trying to clear out the cached data in GitHub Desktop to see if that gets things working. Here's how to do that:

1. Open `Developer Tools` (View > Toggle Developer Tools)
2. Click the `Application` tab
3. Select 'Clear Storage' from the list
4. Click 'Clear Site Data' to clear out the cached data 
5. Restart GitHub Desktop

That should get things working, but let me know if it doesn't and we can dig into this further.
