### ISSUE TITLE
Authentication failed - GitHub Desktop

### ISSUE THREAD

**Issue by DubStepMad** [desktop/desktop#12596]
### Describe the bug

Authentication fails when fetching from repo

### Version & OS

Version 2.9.0 (x64)
Windows 10 Enterprise

### Steps to reproduce the behavior

1. Open Client.
2. Let it load the local repo.
3. Click 'Fetch Origin'

### Expected behavior

I expect it to be able to pull the latest files without this error.

### Actual behavior

Error pops up, stopping me from doing anything.

### Screenshots

![image](https://user-images.githubusercontent.com/13799856/125206200-da86f880-e27d-11eb-9c4f-9ac63807e1fa.png)

### Logs

[2021-07-11.desktop.production.log](https://github.com/desktop/desktop/files/6797444/2021-07-11.desktop.production.log)

### Additional context

I have signed out and back in with no luck, I have also restarted the application as well by signing out, restarting, signing in and then restarting again

**Comment by steveward** [comment]
Thanks for the issue @DubStepMad. It looks like you are using SSH authentication:

```
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```

We recommend using HTTPS since GitHub Desktop does have some known problems when using SSH. If you want to switch to HTTPS you can go to `Repository` > `Repository Settings` > `Remote` and edit the remote URL there to the HTTPS url of your repository. 

If you would like to use SSH I would recommend making sure `ssh-agent` is running and your key has been added. See [this guide](https://docs.github.com/en/github/authenticating-to-github/troubleshooting-ssh/error-permission-denied-publickey) for help debugging this error.

I'm going to close this out since we have identified the issue, but let me know if you run into any further problems.
