### ISSUE TITLE
Fetch Origin Error

### ISSUE THREAD

**Issue by mehmet-erdogdu** [desktop/desktop#12601]
### Describe the bug
I keep getting this error from time to time for some repos.

- The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.

### Version & OS
Git version 2.31.1.windows.1
Github Desktop 2.9.0 x64
Windows 11 Enterprise 21H2 22000.65 x64

### Steps to reproduce the behavior

1. Open Github Desktop
2. Select your repo
3. Fetch Origin a few times

### Screenshots
![image](https://user-images.githubusercontent.com/44897996/125416754-f453cd2d-2fe3-4286-86b3-6a89837e5d84.png)

**Comment by steveward** [comment]
Thanks for the report @mehmet-erdogdu. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by mehmet-erdogdu** [comment]
This is log file: [2021-07-14.desktop.production.log](https://github.com/desktop/desktop/files/6813726/2021-07-14.desktop.production.log)

**Comment by steveward** [comment]
@mehmet-erdogdu thanks for the log. I confirmed that the repository has been archived and you no longer have access to it. You will need to contact the owner of that repository and request access again. Let me know if you have any other questions about this.

**Comment by mehmet-erdogdu** [comment]
Sometimes I use Visual Studio, everything works when I commit and sync there. This is a Github Desktop specific case

**Comment by steveward** [comment]
@mehmet-erdogdu if this is happening in multiple repositories then I can investigate those, but I verified the specific repository in the log file that was failing to fetch is a repository that you no longer have access to.

**Comment by mehmet-erdogdu** [comment]
https://www.loom.com/share/149cda21fdee40cba9e944fa7d1466e4

**Comment by mehmet-erdogdu** [comment]
Only this repo

**Comment by mehmet-erdogdu** [comment]
What you think for this video

**Comment by steveward** [comment]
I believe I figured out the issue. You don't have permissions to access the `upstream` remote, but you do have permission to access a fork of the upstream. GitHub Desktop is attempting to fetch upstream changes but is throwing the error since you do not have access permissions. Unfortunately removing the upstream remote won't resolve this since we automatically add it back.

This is similar to https://github.com/desktop/desktop/issues/3715, and since it is something we could improve I'm going to reference this issue in that thread.
