### ISSUE TITLE
[BUG] Visual URL is wrong

### ISSUE THREAD

**Issue by RedDevilus** [desktop/desktop#12672]
### Describe the bug

The URL shown on the commit when you hover over the linked Pull Request is wrong.

### Version & OS
GitHub Desktop 2.9.0
Windows 10 (20H2)

### Steps to reproduce the behavior

1. #NUMBER to commit summary or description

### Expected behavior

`https://github.com/PCSX2/pcsx2/pull/4620`
instead of `https://github.com/PCSX2/pcsx2/issues/4620`

### Actual behavior

While it's visually wrong, GitHub does reroute it correctly.

### Screenshots

![image](https://user-images.githubusercontent.com/24227051/126886354-88677ac9-53ab-4589-9d7f-e1764310ac0a.png)

### Logs

/

### Additional context

/

**Comment by sergiou87** [comment]
Hi!! 👋  Thanks for your report ❤️ 

The problem is that `#number` can reference both an issue and a pull request, and we can't know what it is unless we send a request to check it, which feels kind of overkill.

As you say, when you click that, GitHub should be smart enough to redirect you to the pull request 4620 if needed, since they're all treated the same way. So I don't think it's worth doing anything to detect if it's a pull request or an issue beforehand 😳
