### ISSUE TITLE
Branch Descriptions - Display and Edit

### ISSUE THREAD

**Issue by rgardner-wiley** [desktop/desktop#12691]
### Describe the feature or problem you’d like to solve

It would be nice if the GUI allowed users to both edit and read branch descriptions (available since Git v1.7.9)

### Proposed solution

Git users often suffer branch name constraints (e.g. company policy requires git branch name equal a corresponding Jira ticket ID). Sometimes these constraints strip context from branch names, or make for non-meaningful branch names on a feature branch. When there are many such branches in a repository, switching to the right branch, or searching for a branch related to some work is cumbersome because it often requires that the user lookup each branch name in another system to gain context. Simply having the branch description available within the Desktop branch drop-down menu would mitigate this annoyance. Being able to edit the description within Desktop is icing on the cake!

### Additional context

I'm not a UX guy, so whatever design choice seems best
![image](https://user-images.githubusercontent.com/63114627/127405091-5f141019-14b4-4740-99be-7e680e3fc0c1.png)

**Comment by billygriffin** [comment]
Hi @rgardner-wiley, thanks for the issue. I'm skeptical that branch descriptions are widely used enough to warrant that level of prominence in the app, and I think this is the first issue we've ever seen for it. We have an issue to improve the context of the branch list and potentially add more to make it more usable (https://github.com/desktop/desktop/issues/8048), but honestly this feels like too niche to be something we'd support in Desktop. Of course, if it turns out there's a critical mass of users someday using branch descriptions and there's a strong value proposition, we would absolutely reconsider that, but that's where my head is at currently. Thanks again for the issue, and I'm going to close it to convey that we don't intend to work on this unless something changes.

**Comment by stell** [comment]
Just wanted to add that branch descriptions inside Desktop would be great. Most of us are using it, and we have so many (partly similar) branches, that it's hard to exactly know what it was about.

**Comment by jonathangkoehn** [comment]
This would be helpful for us as well. Especially since we have many branches one for each feature. Sometimes it is hard to fit a proper name to the feature and a description would be awesome.

**Comment by blais** [comment]
Was looking for a way to add a branch description today, a bit sad it's not able to be shown on github.

**Comment by Neil-Marrison-Skyral** [comment]
Branch descriptions are very useful to give more context and meaning to the purpose for a branch, especially after a period of time has past.
I suspect one of the main reasons they are not widely used, is becauses, essentially, GitHub does not support them.  If they were easy to add, edit and view, they would undoubtly be used a lot more.

**Comment by plangleyprogress** [comment]
agree that branch descriptions in github would be evry useful.  Sort of amazing that there is not a good way to see them today

**Comment by wilx** [comment]
Git 2.51 seems to have [`--edit-description`](https://git-scm.com/docs/git-branch#Documentation/git-branch.txt---edit-description) feature. Would it be possible to implement this now?
