### ISSUE TITLE
Cannot authenticate using CLI even with correct credentials

### ISSUE THREAD

**Issue by Tylersuard** [desktop/desktop#12739]
### Describe the bug
I try to push my repo using the command line.  A window pops up and asks for my login info, I enter it correctly, and it fails.  The command line asks me to enter my github username and password, which again fails.

### Version & OS
Windows 10.  I do not have 2FA enabled.  

### Steps to reproduce the behavior

1. make a change to any repo on a local machine
2. type git add and then git commit
3. type git push
4. attempt to enter credentials and then fail

### Expected behavior

I expected to be able to push changes to my remote repo using the command line.

### Actual behavior

It asked for my username and password, I made sure they were correct many times, and I am able to log into the website and Github Desktop using them, just not the command line.

**Comment by tsvetilian-ty** [comment]
Hey @Tylersuard 👋 

Your question is a bit out of scope for that project, but a possible reason for your issue is that you use an account password to log in. I think that you need to generate a personal token to use as a password. Here is a link to the article that introduces changes to the authentication flow: https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ 

I'm not sure if that is the exact problem you have but you can try 🤞

**Comment by steveward** [comment]
@Tylersuard since this issue tracker is for GitHub Desktop i'm going to close this out, but hopefully @tsvetilian-ty's response gets you on track. You can also reach out to [GitHub Support](https://support.github.com/) for assistance.

**Comment by Tylersuard** [comment]
Issue resolved: I needed to create a personal access token and use that instead of my password.
