### ISSUE TITLE
Tree view option for `Changes` tab

### ISSUE THREAD

**Issue by maxkoshevoi** [desktop/desktop#12730]
### Describe the feature or problem you’d like to solve

When lots of files are changed, it's hard to navigate all of them with a list view.

### Proposed solution

Add `Tree view / List view` switch to the changes tab.

### Additional context

I think this is a duplicate of some issue, but I didn't found it.
I'll add more detailed description and use cases if this is not duplicate.

**Comment by maxkoshevoi** [comment]
Found this original issue: https://github.com/desktop/desktop/issues/2417
Can it be reopened please? It's been closed since 2017 and there's clearly a demand for it.

**Comment by Kira-NT** [comment]
Agree. It's just painful not to have this feature in 2021. I basically have to use Visual Studio Code *(so I can see my changes nice and clean)* and GitHub Desktop *(so I can have access to some advancement and useful features VSC doesn't have)* at the same

**Comment by chetanism** [comment]
+1
![Screenshot 2021-09-15 at 11 17 39 AM](https://user-images.githubusercontent.com/2418542/133377705-97bb3eb3-7e36-4286-b20e-499bca6c9c51.png)

My project is divided into different modules ui, api etc. Each commit needs to have changes to a single module. It would be so much easier to just select my module directory to commit instead of deselecting everything and then selecting each file in the module to commit.

Also, most of the changes are already reviewed in the IDE itself, so not necessarily I need to look at every file before adding it. An option to switch between tree/list view would be useful.

**Comment by niik** [comment]
Hey @maxkoshevoi, sorry for not responding sooner. As you've already noted there's a previous issue for this request so I'm going to close this in favor of the original. That an issue is closed does not mean we won't re-evaluate at a later date, just that we're not prioritizing the feature at this time. Please give the original issue a 👍 reaction and read through the precious comments to see if you have a use case or argument that's not represented there already. Cheers!

@chetanism Would you mond posting your use case in https://github.com/desktop/desktop/issues/2417 so that we can keep all feedback around this consolidated? Thanks!

**Comment by chetanism** [comment]
Sure @niik I'll do that. Thanks for taking a note here!
