### ISSUE TITLE
Unable to commit pending folder

### ISSUE THREAD

**Issue by amarsinghnewspark** [desktop/desktop#12763]
### Describe the bug
I am uploading my repository to git but one folder is not getting  uploaded.
it is saying every thing is up to date nothing to track. 
See Screenshot -: https://prnt.sc/1nd25ca

### Version & OS

Open the 'About GitHub Desktop' menu to see the GitHub Desktop version. Also include what operating system you are using.

### Expected behavior

Write a clear and concise description of what you expected to happen.

### Actual behavior

Write a clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by steveward** [comment]
Thanks for the report @amarsinghnewspark. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
