### ISSUE TITLE
cannot push

### ISSUE THREAD

**Issue by Hamzabilal181** [desktop/desktop#12760]
### Describe the feature or problem you’d like to solve

Write a clear and concise description of what the feature or problem is. If this is a bug report, please use the bug report template instead.

### Proposed solution

Please share how this will it benefit Desktop and its users?

### Additional context

Please include any other context, like screenshots or mockups, if applicable.

**Comment by steveward** [comment]
Thanks for reaching out @Hamzabilal181!

Would you mind filling out the rest of the issue template so that we can better understand what is causing the problem you are experiencing? Without that information it will be difficult to help you further. It would especially be helpful if you could upload the log file from GitHub Desktop, which will give more details about the specific error you are seeing. 

To access the log files go to the  menu in GitHub Desktop and select `Help` > `Show Logs...`. The log files are created daily -- please send over a log file as an attachment from a day where you experienced the issue.
