### ISSUE TITLE
'remote-https' is not a git command

### ISSUE THREAD

**Issue by charanbingi** [desktop/desktop#12775]
### Describe the feature or problem you’d like to solve

Write a clear and concise description of what the feature or problem is. If this is a bug report, please use the bug report template instead.

### Proposed solution

Please share how this will it benefit Desktop and its users?

### Additional context

Please include any other context, like screenshots or mockups, if applicable.

**Comment by steveward** [comment]
Thanks for the report @charanbingi. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
