### ISSUE TITLE
Not able to access private repo

### ISSUE THREAD

**Issue by picarro-smahajan** [desktop/desktop#12779]
### Describe the bug
The new enforcement of github credentials is not allowing github desktop to clone the repo

### Version & OS
Version 2.9.0 (x64)

### Steps to reproduce the behavior

1. Go to Githubdesktop
2. Click on File --> Clone repository
3. Scroll down to repo-name
4. Click Clone
5. See the Error

### Expected behavior
The repos must be cloned properly and further work can be done
Write a clear and concise description of what you expected to happen.

### Actual behavior

Write a clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by steveward** [comment]
Thanks for the report @picarro-smahajan. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by picarro-smahajan** [comment]
Hello Steve,
PFA

**Comment by steveward** [comment]
@picarro-smahajan it looks like you tried to send an attachment via email reply, but unfortunately you need to upload it directly in the issue by drag-and-drop. Sorry about that.

**Comment by picarro-smahajan** [comment]
Apologies Steve Here is the attachment 
[2021-08-16.desktop.production.log](https://github.com/desktop/desktop/files/7000140/2021-08-16.desktop.production.log)

**Comment by steveward** [comment]
Thanks for sharing that. It looks like the clone is failing due to you not having access to the associated submodules of this repository. This is a known issue (see https://github.com/desktop/desktop/issues/3242). You can either request that those specific submodules be added to the team you are a member of in the organization or you can clone the repository via the command line (without the submodules) by running a basic `git clone <repo_URL>`. You can then add that repository to GitHub Desktop.

I hope that helps. Let me know if you have any other questions.

**Comment by picarro-smahajan** [comment]
Thanks Steve Appreciated.

Regards
Sanjay

From: Steve Ward ***@***.***>
Date: Thursday, 19 August 2021 at 12:33 AM
To: desktop/desktop ***@***.***>
Cc: Sanjay Mahajan ***@***.***>, Mention ***@***.***>
Subject: Re: [desktop/desktop] Not able to access private repo (#12779)

Thanks for sharing that. It looks like the clone is failing due to you not having access to the associated submodules of this repository. This is a known issue (see #3242<https://us-east-2.protection.sophos.com?d=github.com&u=aHR0cHM6Ly9naXRodWIuY29tL2Rlc2t0b3AvZGVza3RvcC9pc3N1ZXMvMzI0Mg==&i=NjA5ZGFmN2Q4OWYzZmIwZTRiZjE2ZTI3&t=UlJrZU1zcmlOSEM4SDUwRjF6WHZCQUNTNVhyZHQwM3VJbk0zV1Fsb0ZPbz0=&h=6bbaaaa48aab462db5afd560a751694c>). You can either request that those specific submodules be added to the team you are a member of in the organization or you can clone the repository via the command line (without the submodules) by running a basic git clone <repo_URL>. You can then add that repository to GitHub Desktop.

I hope that helps. Let me know if you have any other questions.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://us-east-2.protection.sophos.com?d=github.com&u=aHR0cHM6Ly9naXRodWIuY29tL2Rlc2t0b3AvZGVza3RvcC9pc3N1ZXMvMTI3NzkjaXNzdWVjb21tZW50LTkwMTM1Njk5Nw==&i=NjA5ZGFmN2Q4OWYzZmIwZTRiZjE2ZTI3&t=UEpYQ1F0YUQ2TmJvd09aWVhBK0krQVcyQnlZY2Z0K0ltdGNlMnYvdWZiVT0=&h=6bbaaaa48aab462db5afd560a751694c>, or unsubscribe<https://us-east-2.protection.sophos.com?d=github.com&u=aHR0cHM6Ly9naXRodWIuY29tL25vdGlmaWNhdGlvbnMvdW5zdWJzY3JpYmUtYXV0aC9BVUpVTkNPRUNTTjJDWkFYM0NCM0o2TFQ1UDdYSEFOQ05GU001Q0lCSDNNUQ==&i=NjA5ZGFmN2Q4OWYzZmIwZTRiZjE2ZTI3&t=N2lpelVZK0lTZFdhT3QvWWVMVkUyMmIwOTE2Lzlvbi9ZQW1JL1FydXRNbz0=&h=6bbaaaa48aab462db5afd560a751694c>.
Triage notifications on the go with GitHub Mobile for iOS<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android<https://us-east-2.protection.sophos.com?d=google.com&u=aHR0cHM6Ly9wbGF5Lmdvb2dsZS5jb20vc3RvcmUvYXBwcy9kZXRhaWxzP2lkPWNvbS5naXRodWIuYW5kcm9pZCZ1dG1fY2FtcGFpZ249bm90aWZpY2F0aW9uLWVtYWls&i=NjA5ZGFmN2Q4OWYzZmIwZTRiZjE2ZTI3&t=L0dQNFdIdFByUTZRYXVoL2NYd3JabkZ3bUhXSStWQm82QnRoMDkwRTBUQT0=&h=6bbaaaa48aab462db5afd560a751694c>.
