### ISSUE TITLE
How about adding a manual sorting feature to the Repo List?

### ISSUE THREAD

**Issue by faha9923** [desktop/desktop#12855]
### Describe the feature or problem you’d like to solve

When I have multiple projects running at the same time, the repo list is easy to be filled and becomes unordered.

### Proposed solution

Could you plz add a feature like, I can create a **folder** to hold repos, and I can **click and drag** a repo to anywhere I want. This is just my opinion, but I think this feature can help users manage their projects easier.

Thx!

**Comment by sergiou87** [comment]
Thanks for the feedback @ faha9923. At this time we don't have any plans to allow for custom group names since we already group repositories by user/org/recent/other. Repository list reordering is something we may look into in the future, and is being tracked in issues like https://github.com/desktop/desktop/issues/8183 and https://github.com/desktop/desktop/issues/11608. I'm going to close this out since we're tracking repository list improvements in multiple issues.
