### ISSUE TITLE
Inform user that selecting individual lines to commit isn't possible.

### ISSUE THREAD

**Issue by JonasSamuelsson** [desktop/desktop#12862]
### Describe the feature or problem you’d like to solve

Enabling `Hide Whitespace Changes` prevents you from selecting individual lines to commit.
There is information about this in the UI where the feature is enabled, but that is not enough in my opinion.
There is a big chance you don't remember that little piece of information, and also there is no indicator that `Hide Whitespace Changes` is enabled.

### Proposed solution

Show a popup or similar (with a `Sorry, you can't select individual lines while Hide Whitespace Changes is enabled.` message) when trying to select individual lines & hide whitespace is enabled.

**Comment by JonasSamuelsson** [comment]
#12848

**Comment by sergiou87** [comment]
Thanks for your suggestion! ❤️ 

Right now we show a tooltip if you hover over the line gutter for long enough:
![image](https://user-images.githubusercontent.com/1083228/131297519-363e9922-2f4e-45e3-a036-cc4f5985ede4.png)

However, I agree that discoverability of this limitation is kind of bad 😞  Showing something when the user interacts with it would make it more clear.

**Comment by JonasSamuelsson** [comment]
I didn't know about the hover, since the mouse has to be still for some time it never showed for me.

**Comment by sergiou87** [comment]
Yeah, it's terrible 😂  Sorry!!

**Comment by ash14** [comment]
Came here to report what I assumed was a regression. 

FWIW the tooltip doesn't appear when hovering over the border of a split diff.

+1 to showing this message on click rather than on hover.

**Comment by aholtzma-am** [comment]
Can the tooltip delay be changed to something smaller, like zero?

**Comment by dmauro** [comment]
Hey just coming in to say that I just have been operating under the presumption that GitHub simply couldn't do individual line commits because I had "hide whitespace changes" option enabled. PLEASE make this UI a little better. Perhaps when you try clicking in the gutters with that option enabled there is some way to provide feedback to the user that they need to disable that option to be able to do per-line staging.

**Comment by Chris-Petty** [comment]
This has bothered me for what feels like months, wasn't sure why it was happening. I've been hiding whitespace changes since around the feature was introduced. Started looking at alternative products because of it! Colleague found this relatively low flying issue thankfully.

> Hey just coming in to say that I just have been operating under the presumption that GitHub simply couldn't do individual line commits because I had "hide whitespace changes" option enabled. PLEASE make this UI a little better. Perhaps when you try clicking in the gutters with that option enabled there is some way to provide feedback to the user that they need to disable that option to be able to do per-line staging.

I agree with this guy. I've clicked many times on the gutter hoping it'd work, never hovered. Aaand this is the same as OPs suggestion, more or less 😁 .

**Comment by DhanyaHerath** [comment]
+1 on this! I've been listening to my coworker complain about this for weeks because he assumed it was a regression - I started googling just to make it stop 😅  Single select is super cool so it would be sad to see people not realise it's here!

**Comment by say25** [comment]
Sorry guys this is my fault, I mean even more ideally we'd find a way to make single select work with hide whitespace on or off but alas its something rather hard to solve

**Comment by Chris-Petty** [comment]
@say25 NP, I can see why it'd be tricky! In the interim clearing up the user feedback would help- woo the PR above looks good!

**Comment by sergiou87** [comment]
Hello! 👋 

We just released version 2.9.4 which includes an improvement @niik beautifully crafted for this 😍  We hope it makes this scenario much clearer now! 😄

**Comment by Chris-Petty** [comment]
@sergiou87 @niik Had a quick play around, nice! This would have definitely informed me when I was unaware, scared and confused 😁
