### ISSUE TITLE
Please implement an actual staging feature

### ISSUE THREAD

**Issue by gracks** [desktop/desktop#12870]
Currently, if you check the box to stage a file in your changelist, and then make additional changes to that file, those changes just get merged in, they're not differentiated.  You can't have unstaged changes to the same file that you have ticked as staged.  This means there's no concept in Github Desktop of carving off reasonable changes from unstaged to staged when they affect the same file in your changelist.  Sourcetree has this feature and it's incredibly useful, I use it constantly.

The ability to put locally curate your staged changes is hugely valuable.

**Comment by niik** [comment]
Hi @gracks, thanks for opening this. Not utilizing the staging area in GitHub Desktop is an intentional design decision that's been with us since the very beginning. We believe that the benefits of having a simplified approach to committing outweighs the benefits of using a staging area for users more well-versed in Git's inner workings. This follows our [design guidelines](https://github.com/desktop/desktop/blob/development/docs/process/what-is-desktop.md#3-github-desktop-prioritizes-workflows-for-beginners-and-collaborative-teams). See https://github.com/desktop/desktop/issues/4475 for a previously opened issue on the topic.
