### ISSUE TITLE
The crc number of a check-in has its final digit clipped off

### ISSUE THREAD

**Issue by KutanaDev** [desktop/desktop#12873]
### Describe the bug
Within Azure DevOps you can view the github History of a project.
Within GitHub Desktop for Windows 2.9.2 x64 you can view the same history.

However, the crc number is displayed differently in the two views. 

Here's a screen-shot from Azure:
![image](https://user-images.githubusercontent.com/10958419/131496221-d8f188f7-4078-41cb-bcc0-520f6f70641e.png)

and here's a snap of the _same_ revision taken from GitHub Desktop:

![image](https://user-images.githubusercontent.com/10958419/131496051-c0e2a64c-0335-474c-a0a7-23e067ef30d0.png)

You can see that one reports the crc as c6c8386d but the other reports it as c6c8386

GitHub Desktop is clipping off the final digit.

### Version & OS

GitHub Desktop Windows 2.9.2 x64

### Steps to reproduce the behavior

1. Go to GitHub Desktop and display the History of a project.
2. Go to Azure Devops and display the History of the same project.
3. Compare the details reported for the same check-in.
4. See error - the reported crc is different.

### Expected behavior

The details should be the same in both views.

### Actual behavior

GitHub Desktop clips the final digit of the check-in CRC

**Comment by niik** [comment]
Hi @KutanaDev, thanks for opening this.

GitHub Desktop relies on Git itself to provide the an abbreviated ambiguous commit id. In many repositories 7 characters is enough to non-ambiguously identify a commit so that's what Git chooses. If you were to load the Desktop repository itself into desktop you'd likely see 9 character commit ids since there's enough commits in the repository that there's a risk of conflict using only 7 characters.

You can test this yourself by running `git log --abbrev-commit` in your repository. Or you can read more about it in https://git-scm.com/book/en/v2/Git-Tools-Revision-Selection#_short_sha_1.

The short of it is that we rely on Git to provide us with commit ids of reasonable length rather than picking an arbitrary length ourselves which could end up conflicting. I'm not sure what approach Azure Devops have taken though.

You can always copy the full unabbreviated commit id by right-clicking on a commit and selecting Copy-SHA:

![image](https://user-images.githubusercontent.com/634063/131498062-9f23636f-a7b2-4f3e-ab89-5e5b2cf05968.png)

**Comment by KutanaDev** [comment]
Thank you for your patient answer. When I copied SHA like you said I got this:
c6c8386d2b7569b9cf07f8d2b884034e93575ee8
So both GitHub Desktop and Azure DevOps are truncating the SHA, but as you said, they truncate at different points.
