### ISSUE TITLE
Unable to use PAT with GitHub Desktop

### ISSUE THREAD

**Issue by yasirrose** [desktop/desktop#12878]
### Describe the bug
As GitHub changed the login policy and implement new security updates and we need the PAT to login and fetch and code on the Linux servers but on windows there is only one option to Login using browser which is very annoying as the token expires very quickly and I need to login again and again.

### Version & OS
Version 2.9.2 (x64) Windows 10 Pro 20H2

**Comment by steveward** [comment]
@yasirrose thanks for the issue. The authentication token GitHub Desktop generates shouldn't be expiring unless it is being revoked or is corrupt. Can you share some more details or some log files from days you have experienced this issue so that we could take a closer look?

To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
