### ISSUE TITLE
refresh

### ISSUE THREAD

**Issue by rishikesh-janrao** [desktop/desktop#12898]
Github desktop should support manual refresh button to fetch updated change in github.com.
Also should ask owner to keep or discard changes if there are any update.

Scenario:
When user renames branch in web, It does not get renamed in desktop client.

**Comment by steveward** [comment]
@rishikesh-janrao thanks for the issue.

> should support manual refresh button to fetch updated change in github.com.

You can click the `Fetch origin` to check if there are any new changes to the remote repository on GitHub. GitHub Desktop also performs periodic background fetches to keep your repositories up-to-date.

>When user renames branch in web, It does not get renamed in desktop client.

We don't automatically update the local branch to match the remote branch name, but it's easy to quickly rename the branch in GitHub Desktop by right-clicking on the branch and selecting `Rename`. You can see in [this article](https://docs.github.com/en/github/administering-a-repository/managing-branches-in-your-repository/renaming-a-branch#updating-a-local-clone-after-a-branch-name-changes) that this is the expected behavior.

I'm going to close this out, but let me know if you have any further questions.
