### ISSUE TITLE
Cannot add SSH key to SSH agent

### ISSUE THREAD

**Issue by ghost** [desktop/desktop#12907]
I cannot  add my private SSH key to my SSH agent. Every time I try it says public key denied. I followed all the steps  to generating and adding SSH keys but it still returns the same problem. I am thinking of giving up now.

**Comment by steveward** [comment]
@Houston-Khanyile thanks for the issue. Are you wanting to use SSH with GitHub Desktop, or just via the command line? GitHub Desktop defaults to using HTTPS connections if you would prefer to use that over SSH. If you are having issues setting up SSH it would be helpful if you can share the specific errors you are seeing.

**Comment by ghost** [comment]
I'm trying to use it on the command line. The error that I normally get is "Public Key access denied". When I revert to HTTPS  it refuses to let me push stuff because it says I must ensure I have permission to the account.

**Comment by steveward** [comment]
@Houston-Khanyile I'd verify that the repository you are pushing to is one that you have access to. You can check the remote url of your local repository by running `git remote -v`.

If you're interested in using GitHub Desktop you can download it  at http://desktop.github.com. If you continue to have issues I'd recommend reaching out to [GitHub Support](https://support.github.com/). Since this issue tracker is for GitHub Desktop only I am going to close this out.
