### ISSUE TITLE
Removing Files via Switching Branches Leaves Empty Directories

### ISSUE THREAD

**Issue by BellCubeDev** [desktop/desktop#12949]
### Describe the bug
Write a clear and concise description of what the bug is.

### Version & OS

Version 2.9.3 (x64)
Windows 10 21H1 (build 19043.1165)
Windows Feature Experience Pack 120.2212.3530.0

### Steps to reproduce the behavior

1. Create a basic repo with some files in multiple folder trees
2. Create a branch, then remove all files from some directories
3. Switch to branch in GitHub Desktop
4. Check for and open the now-empty folders

### Expected behavior

When Github Desktop removes files from a folder, I expected it to check for files in each affected folder and remove it if none exist.

### Actual behavior

Folders remain untouched, but files are still removed

### Screenshots

Taken in VSCode to easily demonstrate issue, but Git operations preformed in GitHub Desktop

#### Before switching branch
![Files in folders before branch switch](https://user-images.githubusercontent.com/33764825/132961339-d68530fc-1ef0-4fa9-9185-675d0f06e898.png)

#### After switching branch
![No files in folders after branch switch, yet folders remain](https://user-images.githubusercontent.com/33764825/132961329-87b5c2b6-4069-4542-920f-e335ca2d88e2.png)

### Logs

Looks error-free to me
```
2021-09-11T20:48:29.313Z - info: [ui] [Timing] Action 'checkout branch from list' for 'bellcubedev/AdditionalClockwork' took 0.000s
2021-09-11T20:48:31.245Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: AdditionalClockwork - BellCubeDev (has token)
2021-09-11T20:48:33.688Z - info: [ui] [Timing] Action 'stash and checkout' for 'bellcubedev/AdditionalClockwork' took 2.444s
```

**Comment by niik** [comment]
Hi @BellCubeDev, thanks for opening this

> I expected it to check for files in each affected folder and remove it if none exist.

I understand why you'd expect that but in this case GitHub Desktop is following the behavior of Git. Git doesn't care about directories (simplified), only files. That's why you see various methods to include "empty" directories such as [adding a .gitkeep](https://www.theserverside.com/blog/Coffee-Talk-Java-News-Stories-and-Opinions/gitkeep-push-empty-folders-git-commit) file.

If you were to use the Git command line or most other Git UIs which follow Git's conventions you'd see the same behavior.

I hope that makes sense! I'm going to close this given that ww consider this to be correct (albeit confusing) behavior.
