### ISSUE TITLE
Visual Studio Community Integration Needed

### ISSUE THREAD

**Issue by herboren** [desktop/desktop#12946]
Feature needed to be implemented
Integration provides no feature for visual studio community as an editor.

Windows 10

![image](https://user-images.githubusercontent.com/987794/132929139-d572b52b-d22c-4e20-9f41-d5d50a80b782.png)

**Comment by niik** [comment]
Hi @herboren, thanks for opening this. We'd be happy to add support for Visual Studio Community Edition. Is this something you would like to contribute?

Please see [our documentation on adding editors](https://github.com/desktop/desktop/blob/development/docs/technical/editor-integration.md) for more details on how to go about doing that.

Given that we haven't had support for VS "classic" before there might be some trickiness when it comes to actually launching it with a file or directory but the first step would be detecting it and seeing what works and what doesn't

**Comment by herboren** [comment]
I don't mind trying to get it to work. Is there some way to validate on my side if this works. I have already modified the code and on a fork, but have no way to compile or run the changes. I don't want to push the commit if I can't debug somehow 🤔

**Comment by niik** [comment]
Hey @herboren, please check out our documentation on how to [set up a development environment](https://github.com/desktop/desktop/blob/development/docs/contributing/setup.md) in order to be able to test your changes locally

**Comment by devsebastian** [comment]
@say25 @niik I have pushed a PR solving this issue: https://github.com/desktop/desktop/pull/13395
please have a look and let me know if any other step is involved. Thanks and regards.

**Comment by Nico-Connor-Personal** [comment]
Implementing Visual Studio support required an unconventional approach since Visual Studio doesn't use a unique registry key like most other IDEs.

Thankfully as of Visual Studio 2017 v15.2, Microsoft includes a CLI tool called [vswhere](https://github.com/microsoft/vswhere) with the visual studio installer to help locate the install path of their IDE.  

Unfortunately, since this is an external program, it is much slower than looking at the registry to find the install path.  

Since currently available editors are calculated at startup, using vswhere could slow down the whole startup of GitHub desktop.

To use vswhere we first need to change the way available editors are loaded.  Instead of loading them at run-time we should load them when needed as per this issue: https://github.com/desktop/desktop/issues/14666

Once the above issue is completed we could implement visual studio support using vswhere.

**Comment by steveward** [comment]
Requested in https://github.com/desktop/desktop/issues/16565.

**Comment by steveward** [comment]
GitHub Desktop now supports adding a [custom external editor](https://docs.github.com/en/desktop/configuring-and-customizing-github-desktop/configuring-a-default-editor-in-github-desktop?platform=windows#configuring-a-custom-editor), so I'm going to close this out as Visual Studio can be added by pointing to `devenv.exe`.
