### ISSUE TITLE
why I can't commit success 

### ISSUE THREAD

**Issue by 2210655640** [desktop/desktop#12948]
![image](https://user-images.githubusercontent.com/45776861/132951595-a0a240be-e517-4353-b112-56e2802e4f52.png)

**Comment by niik** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
