### ISSUE TITLE
Facing error while publishing the cloned Repo

### ISSUE THREAD

**Issue by L016687** [desktop/desktop#12956]
Hi Team,

I am facing an issue on the Git hub desktop while publishing the Cloned Repo ,
the error is : 
"The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed."
please help me to resolve the issue .
![git error](https://user-images.githubusercontent.com/89831960/133220566-f61d74c8-aefd-4b2b-9c16-d5474f94ace6.PNG)

**Comment by niik** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

The screenshot and information you posted doesn't contain enough information for us to deduce what the problem is but please make sure you're signed in correctly (check in the preferences/options dialog and try signing out and back in again) and with an account that has access to the repository in question.

Thanks for understanding and meeting us half way :grinning:

**Comment by Asvsmadhav** [comment]
****🔰😶
