### ISSUE TITLE
git: 'remote-https' is not a git command. See 'git --help'.

### ISSUE THREAD

**Issue by medhatjachour** [desktop/desktop#13014]
### Describe the bug
Write a clear and concise description of what the bug is.

### Version & OS

Open the 'About GitHub Desktop' menu to see the GitHub Desktop version. Also include what operating system you are using.

### Expected behavior

Write a clear and concise description of what you expected to happen.

### Actual behavior

Write a clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by sergiou87** [comment]
Thanks for the report @medhatjachour. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the File menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
