### ISSUE TITLE
Getting SSL certificate expire error

### ISSUE THREAD

**Issue by yuvarajs1** [desktop/desktop#13079]
<img width="1440" alt="Screen Shot 2021-10-07 at 3 23 54 PM" src="https://user-images.githubusercontent.com/47660168/136362311-cbe083e0-e65a-490a-9119-248b2f51ca3d.png">

**Comment by niik** [comment]
Hi @yuvarajs1, thanks for reaching out. The problem you're seeing is due to an expired certificate on your hosted GitLab instance. Assuming your system clock is set correct there's unfortunately nothing we can do to help out here since Desktop is behaving as intended (alerting you to a possible security issue). I would suggest reaching out to the administrator(s) of your hosted GitLab instance internally at your company to alert them to the issue.

Best of luck!
