### ISSUE TITLE
git push react-native github desktop

### ISSUE THREAD

**Issue by luismendes070** [desktop/desktop#13097]
### Describe the bug
Write a clear and concise description of what the bug is.

### Version & OS

Open the 'About GitHub Desktop' menu to see the GitHub Desktop version. Also include what operating system you are using.

### Expected behavior

Write a clear and concise description of what you expected to happen.

### Actual behavior
error: cannot spawn .git/hooks/pre-push: No such file or directory
error: waitpid for .git/hooks/pre-push failed: No child processes
error: failed to push some refs to 'https://github.com/poligonosapp/poligonosdemos.git'

Write a clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by tidy-dev** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
