### ISSUE TITLE
Add multiple folders on "Add existing repository"

### ISSUE THREAD

**Issue by darkBoft** [desktop/desktop#13103]
### Describe the feature or problem you’d like to solve

"Github for desktop" is in many user cases not the first client or the first contact with git repositories. In my case, I've got hundreds of repos, grouped by multiple folders.

So in case of adding all my repos I need to do this for each repo and each folder.

It would be a nice quality of live improvement instead of adding "just one" repo at a time, adding whole folders full with repos with just one click.

### Proposed solution

On switching to github for desktop this will make it much easier to add all the existing repos on your device.

Also if you copy & pasted some repos between devices (old to new pc e.g.) this will be very helpful.

**Comment by niik** [comment]
Hey @darkBoft, thanks for reaching out! You should be able to drag and drop multiple folders on top of the GitHub Desktop window in order to add them all at once, see https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/adding-and-cloning-repositories/adding-a-repository-from-your-local-computer-to-github-desktop.

Not the most discoverable certainly but still, should get you unblocked. I'll close this in favor of https://github.com/desktop/desktop/issues/2978 which is related to the same issue.
