### ISSUE TITLE
Focus (highlight) is broken when clicking from history commit to file changes

### ISSUE THREAD

**Issue by JackEllis** [desktop/desktop#13118]
### Describe the bug
When looking over the history, you can click a commit and see the file changes. The moment you click on one of the files, to see the changes, the selected history item loses it's focus (see below). Our use case is that we review historical commits to put together our public changelog.

### Version & OS

Version 2.9.4 (arm64

### Steps to reproduce the behavior

1. Go to "History" tab
2. Click a commit
3. Click a file

### Expected behavior

The file should highlight, and the parent commit should stay highlighted

### Actual behavior

The file highlights but the commit focus (highlight) disappears, making it hard to remember which commit you were browsing

### Screenshots
In this screenshot, I clicked on my "Remove old code" commit. I'd expect that to remain highlighted

![image](https://user-images.githubusercontent.com/537943/137168621-86369f6a-9dbb-4474-ba02-645965b3f066.png)

### Extra
Thanks for the great product by the way. I use it every day and I love it. You've done a great job.

**Comment by steveward** [comment]
Thanks for reporting this @JackEllis! @niik opened https://github.com/desktop/desktop/pull/13115 to fix this, so I'm going to close this issue out.

**Comment by givihuda** [comment]
I don't know whether to comment here or on the fix pull, or make a new issue, but I'm here because I have the same problem; when I click a commit in the History tab, then click on file to see its changes, the highlighted commit on the left unhighlights, and sometimes I forget which one I was on... it's discombobulating.

I'd show screenshots but I'm not good at blurring out proprietary info...

I'm on macOS Big Sur 11.6.1, GitHub Desktop version 2.9.4 (x64)... but I've noticed the issue since Catalina as well (Q2 this year), and I keep my GitHub Desktop up to date. PS I'm not updating my macOS to Monterey until next year, but that's obviously not the issue anyway.

EDIT: Did I miss a config setting somewhere...?

**Comment by tidy-dev** [comment]
@givihuda The fix is currently in beta. You are welcome to [try out beta by downloading it here.](https://github.com/desktop/desktop#beta-channel) . Otherwise, it will be in the next prod release, sorry for the inconvenience.
