### ISSUE TITLE
Git - remote: Repository not found

### ISSUE THREAD

**Issue by sofkay** [desktop/desktop#13174]
### Describe the feature or problem you’d like to solve

Write a clear and concise description of what the feature or problem is. If this is a bug report, please use the bug report template instead.

### Proposed solution

Please share how this will it benefit Desktop and its users?

### Additional context

Please include any other context, like screenshots or mockups, if applicable.

**Comment by steveward** [comment]
Thanks for reaching out!

Would you mind filling out the rest of the issue template so that we can better understand what is causing the problem you are experiencing? Without that information it will be difficult to help you further. It would especially be helpful if you could upload the log file from GitHub Desktop, which will give more details about the specific error you are seeing. 

To access the log files go to the  menu in GitHub Desktop and select `Help` > `Show Logs...`. The log files are created daily -- please send over a log file as an attachment from a day where you experienced the issue.

**Comment by sofkay** [comment]
Hello Steve!

When I try to "git push -u origin main" to connect the existing command prompt to a specific repository, it says: "remote: Repository not found. fatal: repository 'https://github.com/SOFKAY/REPOSITORY.git/' not found". I've authenticated the GitHub account  in my  browser and with a personal token. I'm not sure why this issue is happening.

**Comment by steveward** [comment]
Is `"remote: Repository not found. fatal: repository 'https://github.com/SOFKAY/REPOSITORY.git/'` the actual error message you are seeing? If so, then it looks like your `origin` remote URL is not configured correctly. You can check/edit this in GitHub Desktop by going to `Repository` > `Repository Settings` > `Remote`. Make sure that URL points to your repository on GitHub.
