### ISSUE TITLE
Selected file in changes file list doesn't stay highlighted once it is scrolled out of view

### ISSUE THREAD

**Issue by agusterodin** [desktop/desktop#13191]
### Describe the bug
The selected file in the "changes" file list doesn't stay highlighted once it is scrolled out of view. This is new behavior as of October 2021. Having the file highlighted really helps me see at a glance what exact file I am looking at.

### Version & OS

GitHub Desktop 2.9.4 (arm64)

MacOS 12.0.1 (the issue was also present before upgrading to Monterey).

### Steps to reproduce the behavior

1. Make a bunch changes to multiple files in a repository (enough to cause the "changes" file list to become scrollable).
2. Click a file in the "changes" file list to see changes in file.
3. Change scroll position in the "changes" file list such that the currently selected file is no longer visible.
4. Change scroll position back such that currently selected file is visible again. 
5. Observe that the file is no longer highlighted.

### Expected behavior

Selected file in "changes" file list always remains highlighted when it is visible in the scrolling viewport.

### Actual behavior

Selected file in "changes" file list gets unhighlighted once scrolled away from.

### Screenshots

https://user-images.githubusercontent.com/10248395/138905352-1715db6f-050c-4c20-a6db-b60d6af7f0ee.mov

### Logs

N/A

### Additional context

N/A

**Comment by sergiou87** [comment]
Thanks for the report @agusterodin!

From what I see, if you use the dark theme it at least preserves some kind of dull highlighting:
![image](https://user-images.githubusercontent.com/1083228/138917833-669af3b2-dd58-449d-ade4-b466ca39b972.png) ➡️  ![image](https://user-images.githubusercontent.com/1083228/138917855-e3e77aed-3290-4e58-a67a-237d56286be2.png)

Does this other behavior in the dark theme match what you observed prior to October 2021?

I think this is probably a regression introduced in #12833 or one of the subsequent fixes, we'll look into it 😄

**Comment by agusterodin** [comment]
> Thanks for the report @agusterodin!
> 
> From what I see, if you use the dark theme it at least preserves some kind of dull highlighting: ![image](https://user-images.githubusercontent.com/1083228/138917833-669af3b2-dd58-449d-ade4-b466ca39b972.png) ➡️  ![image](https://user-images.githubusercontent.com/1083228/138917855-e3e77aed-3290-4e58-a67a-237d56286be2.png)
> 
> Does this other behavior in the dark theme match what you observed prior to October 2021?
> 
> I think this is probably a regression introduced in #12833 or one of the subsequent fixes, we'll look into it 😄

Yes, switching to dark mode provides expected experience. Visual/UX regression only present in light mode. 

I really appreciate it!

**Comment by tooomm** [comment]
I want to add to this, as I've experienced this in a slightly different use case (running Version 2.9.4, x64, Windows 10).

>Yes, switching to dark mode provides expected experience. Visual/UX regression only present in light mode.

Same issue is present when selecting a changed file to review its details.
It gets highlighted in blue, but once you click anywhere or e.g. select a text in the file for copying, the highlighting is gone.

I can confirm, this issue is only present in light mode.
When using dark mode, the grey highlighting is still visible and the user is still able to see which of the files is selected and currently shown.

Such a subtle grey highlighting should be used in the light theme as well!

**Comment by sergiou87** [comment]
Hi @tooomm and @agusterodin !! I think this should've been fixed in the latest beta, thanks to #13115

Could you please [try it out](https://github.com/desktop/desktop#beta-channel) and confirm it works fine for you?

I'll close this, please let me know if it doesn't work and I'll reopen it 😄

**Comment by tooomm** [comment]
Thanks for pointing to it - it fixes my issue!

But how can I switch back to stable releases?! 🙈 
There is no setting in options or about. I do not want to automatically use every beta version from now on. @sergiou87

**Comment by tidy-dev** [comment]
>But how do I can switch back to stable releases?! 

If you are on Mac, you will still have your production version in your application folder (or where ever you installed it too). Go to your application folder and open the production version. If you have Beta and Prod in the same directory and are unsure which one is which, you will want to completely quit GitHub Desktop (otherwise either icon will open the currently running one), open one of them, and look at App Menu > About Desktop to determine. You can simply delete the beta if you no longer want it (I just renamed it to GitHub Desktop Beta so I could differentiate).

If you are on Windows, just reinstall the production version.

**Comment by tooomm** [comment]
Thanks for the explanation and help.

Will the automatic update check install the next stable release even if I'm on a beta version?
Will any subsequent beta now auto install as new version as well?

**Comment by tidy-dev** [comment]
In short, they behave as separate applications. If you open a prod version of the app, you will get prod updates. Similarly for Beta.

> Will the automatic update check install the next stable release even if I'm on a beta version?

No. If you are on a beta version it will check for the next available beta version and update when there is one.

> Will the automatic update check install the next stable release even if I'm on a beta version?

No. If you are on prod app, you will always get latest prod updates. If you are on beta app, you will always get latest beta updates.

**Comment by tooomm** [comment]
Ok, I will need to manually re-install and switch to stable/production then... 🙈
Too bad there is no easy way to quickly switch between channels.
