### ISSUE TITLE
Prevent checking for hacks

### ISSUE THREAD

**Issue by richaplinvs** [desktop/desktop#13197]
### Describe the feature or problem you’d like to solve

It's common to hack some code for testing that you'd never want checked in but often times you forget and it gets checked in.

### Proposed solution

A commented keyword/phrase (e.g. no-commit-hack) that could be scanned prior to allowing the commit button to be active.

This will save wasted time investigating errors from your accidentally checked in hacks.

**Comment by steveward** [comment]
Thanks for the request @richaplinvs. For quick testing of one-off changes I'd recommend creating a new local branch, since that can be easily deleted later. At this time we don't have plans to implement any sort of local scanning of changes. I'm going to close this out for the time being to help keep our issue tracker manageable, but we can continue to gather feedback about this type of feature here.
