### ISSUE TITLE
Cannot push to a Gist

### ISSUE THREAD

**Issue by steveharoz** [desktop/desktop#13274]
### Describe the bug
I cannot push changes to a gist, even though I can clone and pull. It works fine for github.com repositories.

### Version & OS
Version 2.9.4 (x64)
Windows 10

### Steps to reproduce the behavior
1. Clone a gist that you made
2. Make some changes and commit
3. Push it

### Expected behavior
It should work, and I know it's worked in the past.

### Actual behavior
see error screenshot below

### Screenshots
![image](https://user-images.githubusercontent.com/2257540/140484298-4049d0e8-6863-40e0-81c3-9f2006ce6aab.png)

**Comment by sergiou87** [comment]
> and I know it's worked in the past

Thanks for your report @steveharoz ! Has it worked with your current version of GitHub Desktop (2.9.4)?

**Comment by steveharoz** [comment]
@sergiou87 
It doesn't work with the two gists I tried.

**Comment by sergiou87** [comment]
@steveharoz do you know which is the last version of GitHub Desktop where it worked?

**Comment by steveharoz** [comment]
It's been months since I tried, so no sorry.

**Comment by steveward** [comment]
@steveharoz this is a known bug -- when trying to push commits to a gist, GitHub Desktop will fall back to basic authentication and not detect your current credentials. As a workaround for this you should be able to drop into the command line and run a `git push` to push your changes. 

See https://github.com/desktop/desktop/issues/2973 for more information about some of the known issues with using gists in GitHub Desktop.  I am going to reference this issue in #2973 and close it out for the time being as we're not prioritizing gists in GitHub Desktop at this time.

**Comment by HarryStevens** [comment]
I came here because I'm having the same problem as @steveharoz. However, I also cannot push to a Gist from the command line. 

I use GitHub with my organization, and I have to clone with HTTPS. When I push, I enter my Personal Access Token instead of my password, and it returns a 500 error. I get the same error when I try to push with GitHub Desktop.

Terminal:
![Screen Shot 2022-11-28 at 11 41 58 AM](https://user-images.githubusercontent.com/6527267/204333125-a47623c2-53ed-4531-9163-3cb38e992e08.png)

Desktop:
<img width="700" alt="Screen Shot 2022-11-28 at 11 55 06 AM" src="https://user-images.githubusercontent.com/6527267/204336247-e2dff8d2-52f3-4abb-82f3-bbcb07f0c659.png">

There is no other way to add images to Gists, so I need to be able to push files somehow.

**Comment by onacit** [comment]
Is it normal when I still get this error in 2023?

**Comment by sanjarcode** [comment]
I got the error on my Apple MacBookPro 13" (macos Ventura, M1 processor). 

Solution - explicitly add `gist.github.com` as Host and HostName.
Example: added this to my `~/.ssh/config`:
```yaml
# existing
Host github.com
  HostName github.com
  User git
  IdentityFile ~/.ssh/play_user
  IdentitiesOnly yes
  AddKeysToAgent yes

# add (Gist works now)
Host gist.github.com
  # was needed since Gist push wasn't working
  HostName gist.github.com
  User git
  IdentityFile ~/.ssh/play_user
  IdentitiesOnly yes
  AddKeysToAgent yes
```

Didn't need to run ssh-agent or anything, it just worked.

**Comment by Malix-Labs** [comment]
Exact same thing as @HarryStevens, error 500 on both CLI and desktop.
Guess gists aren't ready yet
