### ISSUE TITLE
Better to keep the remote branch in the Branches list in Github Desktop after the branch is checked out to local

### ISSUE THREAD

**Issue by lena567** [desktop/desktop#13311]
After a remote branch is checked out to local, only the local branch is displayed in the Branches list.
When choosing a branch to merge into current branch, user can only choose the local one.
To merge all updates on the remote, user needs to switch to the local branch and fetch the latest update, and then switch back to merge. If don't switch and fetch, some updates may be lost. This is inconvenient.

**Comment by steveward** [comment]
@lena567 thanks for the issue. GitHub Desktop performs automatic background fetching to keep your local branches up-to-date. You can verify you have this enabled by going to `File` > `Options` > `Advanced` > `Background updates`. If the branch cannot be fast-forwarded (due to conflicting changes, for instance) then you will need to switch to the branch in order to update it. No changes should be 'lost` if they have not been pulled from the remote branch, but there is a potential for merge conflicts. I hope that helps explain things -- let me know if you have any further questions.
