### ISSUE TITLE
not able to sign in in github desktop

### ISSUE THREAD

**Issue by Sai1825** [desktop/desktop#13377]

**Comment by Sai1825** [comment]
im not able to log in to the git hub in my computer

**Comment by sergiou87** [comment]
Hi @Sai1825!

Are you having trouble with GitHub Desktop (the app: https://desktop.github.com/) or with GitHub.com (the website)?

**Comment by Sai1825** [comment]
desktop itself

**Comment by sergiou87** [comment]
Thanks! Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
