### ISSUE TITLE
Не могу войти в свой профиль.

### ISSUE THREAD

**Issue by 1Bax** [desktop/desktop#13374]
### Describe the bug
Write a clear and concise description of what the bug is.

### Version & OS

Open the 'About GitHub Desktop' menu to see the GitHub Desktop version. Also include what operating system you are using.

### Expected behavior

Write a clear and concise description of what you expected to happen.

### Actual behavior

Write a clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by sergiou87** [comment]
Hello @1Bax !

I'm sorry but no one in the team speaks Russian, so I used Google Translate to understand your message:

> I can't log into my profile

If that's correct, could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
