### ISSUE TITLE
Unable to view the changes made on GitHub Desktop 

### ISSUE THREAD

**Issue by Ayeshajaaved** [desktop/desktop#13379]
It shows the changes in the list but doesn't preview them, says 'No content changes found' whereas there are changes actually.

GitHub Desktop Version 2.9.4 (x64)

-----------------------------------------------------------------------------------------------------------------------
<img width="960" alt="2021-11-24_21-28-08" src="https://user-images.githubusercontent.com/93701605/143277277-cfc8b50e-8cad-425a-a684-81701bd5fc52.png">
<img width="960" alt="2021-11-24_21-27-56" src="https://user-images.githubusercontent.com/93701605/143277283-e4f2fff9-951f-472c-ae42-66ba00707c11.png">

**Comment by sergiou87** [comment]
Thanks for the report @Ayeshajaaved . Usually this is caused by line-ending or file mode changes. You can try running `git config core.fileMode false` to see if ignoring file mode changes helps in this instance, and I would also recommend normalizing your line-endings since you are using Windows and macOS. See [this guide](https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings) for how to do that. 

It'd also be helpful if you could share the output of `git config --list --show-origin` to verify there aren't any configuration issues that could be causing this.
