### ISSUE TITLE
Windows10: Why "taskkill /im explorer.exe /t /f" cannot close GithubDesktop.exe

### ISSUE THREAD

**Issue by bobdog1986** [desktop/desktop#13382]
### Describe the bug

When execute "taskkill /im explorer.exe /t /f" in a batch file, the explorer process and any child processes started by it will be closed.
But GithubDesktop.exe still alive.

### Version & OS

Version 2.9.4 (x64), on Windows 10

### Steps to reproduce the behavior

1. Execute a batch file with code "taskkill /im explorer.exe /t /f"

### Expected behavior

The explorer process and any child processes started by it should be closed.

### Actual behavior

GithubDesktop.exe still alive

### Additional context

This issue may not a bug but a question.

**Comment by sergiou87** [comment]
Thank you for your report @bobdog1986 but since this is not an actual bug I'd rather close it.

Regarding your question, I haven't checked, but maybe due to the way Electron (in which GitHub Desktop is based) works, GitHubDesktop.exe might not be a direct child of explorer.exe. You can probably see that by using Process Explorer.

In any case, there isn't much we can do about this, sorry 😞

**Comment by bobdog1986** [comment]
I guess the real reason is that when we click GithubDesktop.exe(<400KB) it will call app-{ver}/GithubDesktop.exe(100MB+) via a batch.
![image](https://user-images.githubusercontent.com/9330555/143516539-ca4509c3-8d1d-4adb-a3e2-2c62c6a4c602.png)
