### ISSUE TITLE
Scroll bar is gone

### ISSUE THREAD

**Issue by MSG2735** [desktop/desktop#13393]
The scroll bar on the changes area is gone i cant even use the scroll wheel and im using Windows 11 latest insider version

**Comment by MrAtheist** [comment]
+1... running v2.9.5-beta3 in windows 10 and  i have to resort to "dragging" instead of "scrolling"

**Comment by jorisw** [comment]
Same on Mac. I can no longer scroll the file view.

Version 2.9.5-beta3 (x64), macOS Monterey 12.0.1

**Comment by jorisw** [comment]
FYI https://desktop.github.com offers v2.9.4 that doesn't have this bug

**Comment by JungleDnl4322** [comment]
Nice name hun  Enviado desde Correo para Windows De: MrAtheistEnviado: sábado, 27 de noviembre de 2021 12:36 a. m.Para: desktop/desktopCC: SubscribedAsunto: Re: [desktop/desktop] Scroll bar is gone (Issue #13393) +1... running v2.9.5-beta3 in windows 10 and i have to resort to "dragging" instead of "scrolling"—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tidy-dev** [comment]
@MSG2735 and @jorisw Thank you for the bug report! I confirmed that the unified diff view of the changes scroll bar no longer works.

Another work around currently would be to use the split view. There is a gear icon in top right hand corner.
![image](https://user-images.githubusercontent.com/75402236/143867783-a3aa66e3-6c88-4755-b056-db847fbbec68.png)

**Comment by sergiou87** [comment]
Fixed already in #13403, we will deploy a beta with the fix soon. Sorry about that!! 😱
