### ISSUE TITLE
Make universal app for macOS

### ISSUE THREAD

**Issue by rakleed** [desktop/desktop#13424]
### Describe the feature or problem you’d like to solve

I'm used to downloading apps, and they are universal by default. But you have a big "Download for macOS" button to download x86-64 app, and to download arm64 app I have to click on a small link, which is inconvenient.

### Proposed solution

Make a universal app. Or at least when I click on "Download for macOS" offer to select the desired version.

### Additional context

https://github.com/electron/universal

**Comment by tidy-dev** [comment]
@rakleed Thank you for the feedback! Looking over that real quick and I see that it requires that a user always have both the non arm64 and arm64 installed at the same time making the app install double as big so that they can run either one. Tho, I can see the benefit you are pointing out, it is probably not worth cost for the majority of our non-arm64 users and we already have to have individual build for windows.  Similarly, the link to the arm64 builds are less prominent as it is a small percentage of users. Maybe in the future this will need revisiting tho, so thank you again for the suggestion!
