### ISSUE TITLE
Setup Error

### ISSUE THREAD

**Issue by KendallDoesCoding** [desktop/desktop#13454]
### Describe the bug
Setup Bug, I managed to download the app but this bug comes whenever you install the exe file from the official website and when you try to download it

### Version & OS
Current Version on Github Desktop Website
Windows OS

### Steps to reproduce the behavior

1. Go to 'Downloads'
2. Click on 'GithubDestopSetup-x64'
3. Scroll down to '...'
4. Tap Setup Log
5. See Logs

### Expected behavior
I believe this is a bug as I managed to download to software, it's just a code error, according to me

### Actual behavior
Couldn't install Github Desktop error (even though I could and did)

### Screenshots
![image](https://user-images.githubusercontent.com/84712013/144808029-b0aa055c-3725-41ad-b1d6-e22ff8c49843.png)

### Logs
Logs are not showing when clicked Show Setup Logs

**Comment by steveward** [comment]
Closing in favor of #13455.

**Comment by KendallDoesCoding** [comment]
@steveward Please reopen, for this I got a error messege with the logs for #13455, I downloaded it, but I couldnt clone anything nor did it show in my applications, I opened this because I got a popup when I tried installing this.

**Comment by steveward** [comment]
@KendallDoesCoding you shared the same image in #13455, so I figured it would be easier to consolidate your issues for easier tracking. If you are still having issues with installing GitHub Desktop then it'd be helpful if you can share the setup log. You should be able to find the log file here:

`%LocalAppData%\GitHubDesktop\SquirrelSetup.log`

I'd definitely recommend trying to fully disable Norton Antivirus to see if that helps-- it's been a common cause of performance and installation issues in the past. You should be able to whitelist GitHub Desktop in Norton so that it doesn't interfere:

https://support.norton.com/sp/en/us/home/current/solutions/v3672136

You would want to exclude `C:\Users\Your_user\AppData\GitHub Desktop` and `C:\Users\Your_user\AppData\Local\GitHubDesktop`.

**Comment by KendallDoesCoding** [comment]
@steveward I turned off norton and got another kinda setup error without a view log button

![image](https://user-images.githubusercontent.com/84712013/148173190-5b68772e-e053-40e9-a425-0af1092670c6.png)
