### ISSUE TITLE
Only commit selected files instead of checked files

### ISSUE THREAD

**Issue by komape** [desktop/desktop#13469]
### Describe the feature or problem you’d like to solve

Every time I do a lot of changes I have multiple files to commit. I don't want to commit them in one commit but in multiple commits. Coming from other tools I'm very used to select the files I want to commit, enter a message and hit commit. By selecting, I mean to click a file in the 'changed files' list, hold CTRL and click another one. I expect that the selected files are comitted. Instead GitHub commits all files because all files are checked per default. If I'm lucky I realize this before clicking on 'Push'. If not I'm pushing "wrong" commits.

### Proposed solution

If multiple files are selected, only commit those. I know, this is very confusing with the check boxes. Maybe it's an option to enable manually in the settings. Or do it like VS Code where each file has to be added to the commit manually instead of adding all files by default as GitHub Desktop does. 

The current approach is very confusing as I always expect GitHub Desktop to commit the selected files.

**Comment by niik** [comment]
Hi @komape, I can understand the confusion here. In the initial version of GitHub Desktop it wasn't possible to select multiple files by holding CTRL and clicking on them. When we added that functionality in order to support discarding multiple files we unfortunately found ourselves with two ways to "select" files.

Changing the way users select which files to include in a commit would be much too disruptive at this point. A tip that hopefully will make this a bit easier for you is that once you've selected the files you wish to include you can click the spacebar to toggle the checkbox for those files.

Hope that helps!
