### ISSUE TITLE
Better support for worktrees

### ISSUE THREAD

**Issue by askzy** [desktop/desktop#13485]
### Describe the feature or problem you’d like to solve

I created 3 worktrees of the same repo that I work on, each on different branches and containing different commits that I have. Right now they all look the same in github desktop because the name shown is the remote repo name, and they of course have the same remote repo name.

### Proposed solution

Include some basic info (e.g. the path to the worktree?) to differentiate which worktree I'm looking at in Github Desktop

**Comment by askzy** [comment]
<img width="256" alt="Screen Shot 2021-12-08 at 5 14 55 PM" src="https://user-images.githubusercontent.com/1498322/145316567-0799208a-d6bc-4d6e-9f23-be468108c1e4.png">

**Comment by steveward** [comment]
Thanks for the feedback @askzy. The best solution for this until we improve worktree support (https://github.com/desktop/desktop/issues/907) would be to use the alias feature (right-click -> Create Alias) to differentiate between them. I'm going to close this out since we're tracking broader support for worktrees in #907. I hope that helps!
