### ISSUE TITLE
Unable to clone github repo 

### ISSUE THREAD

**Issue by saras-koiri** [desktop/desktop#13487]
### Describe the bug
Write a clear and concise description of what the bug is.

I am unable to clone the repo with the URL:
https://github.com/eugenp/tutorials

### Version & OS
Open the 'About GitHub Desktop' menu to see the GitHub Desktop version. Also include what operating system you are using.

Version 2.9.4 (x64)
Windows 10

### Steps to reproduce the behavior

From GitHub.com go to the repo URL and click on "Open with GitHub Desktop" from the Code button.

### Expected behavior

I expect the repo to be cloned in GitHub desktop.

### Actual behavior

Got an error. See screenshot

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

### Additional context

[2021-12-09.desktop.production.log](https://github.com/desktop/desktop/files/7685623/2021-12-09.desktop.production.log)
![github error](https://user-images.githubusercontent.com/93994046/145409926-2d7cd6df-f66a-41b4-8abd-c28f37d7651d.png)

**Comment by steveward** [comment]
@saras-koiri thanks for the issue. It looks like the clone operation is timing out:

```
error: RPC failed; curl 56 Failure when receiving data from the peer
error: 1574 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
```

I was able to clone the repository successfully, so my guess is that this is a network connection issue. Are you on a reliable network connection? If you can try from a different network that may help narrow down if that could be the specific cause. 

One thing some users have had success with is to switch to using SSH instead of HTTPS. To do this you would need to setup a new SSH key by following [this guide](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent) and then [add it to your GitHub account](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account). Once you've done that you can try cloning using the SSH URL (`git@github.com:eugenp/tutorials`) via `File` > `Clone Repository` > `URL`. Let me know how that goes.

**Comment by saras-koiri** [comment]
Hi,

Yes my network is reliable, my speed is around 180Mbps. I was able to clone
the repo via my Eclipse Git plugin using the SSH url. I was not able to use
the SSH URL in GitHub Desktop. This I find very strange and it seems like
an issue with my GitHub Desktop app.

When I try via Github Desktop I get an authentication failed error even
though I am able to use the same SSH public key from Eclipse.

[image: image.png]

Regards

**Comment by niik** [comment]
Hi @saras-koiri. Are you able to use the repository in GitHub Desktop if you manually add it to GitHub Desktop after cloning with Eclise? You can add it by either dragging the directory to GitHub Desktop or by clicking on the `File` menu, followed by `Add Local Repository`.

If you're able to add the repository to Desktop could you then try changing the remote url back to the `https` url following the steps that @steveward laid out above?

With that we should be able to tell whether the issue is only with cloning over https or if the issue lies elsewhere.

**Comment by saras-koiri** [comment]
Yes I was able to add the repo to Github Desktop. Not sure what steve's
steps were but I changed the URL in Repository Settings from SSH to HTTPS.
That worked and I can see the repo in GitHub Desktop.


[image: image.png]

[image: image.png]

[image: image.png]

Regards

**Comment by steveward** [comment]
@saras-koiri based on your reply it sounds like you were able to get things working -- let me know if that is not the case and we can assist further!

**Comment by thatc0py** [comment]
Hi all, 

Can some help me with this issue?
When cloning over ssh, it works time to time, I mostly receive below error message:
 
![image](https://user-images.githubusercontent.com/37700827/163174271-60dd1870-4fc3-4333-a4e2-5663033e5584.png)

If I clone same repo using Git Bash, everything is fine.
Cloning over HTTPS also works ok from both, Github Desktop and Git Bash.
