### ISSUE TITLE
Check and Update all repositories with one click

### ISSUE THREAD

**Issue by ionultd** [desktop/desktop#13489]
Hi,

A lot of GitHub users have numerous repositories that gets quite tedious to manually update so they often resort to running a scheduled/cron script to do so. Please make this ability part of GitHub Desktop so that all us users have to do is hit one button to start a repositories wide pull and update. Especially useful for new users instead of scouring the internet for the best update script.

Thx

**Comment by steveward** [comment]
Thanks for the issue @ionultd. GitHub Desktop automatically fetches and fast-forwards your repositories in the background (see [this explanation](https://github.com/desktop/desktop/issues/4950#issuecomment-397694857). Adding a `Pull all` has been previously discussed in #2460 and #6482, but at this time we have not decided to move forward with this due to it not being an area that we see as a pain point in GitHub Desktop. There are also scenarios where problems can arise when performing a pull (like merge conflicts).

I'm going to close this out, but let me know if you have any further questions.

**Comment by GHNewbiee** [comment]
@steveward 

>but at this time we have not decided to move forward with this due to it not being an area that we see as a pain point in GitHub Desktop

It's a pain point in users! Common sense says "UX First" similar to "Safety First"!

**Comment by Tommuh** [comment]
Not a pain point?
Me and my associates have to update 150+ private repos daily. This feature is highly appreciated.

**Comment by GHNewbiee** [comment]
At least a `Fetch all` button. For God shake! Automatic fetches do not work all the times. We have to manually do it one by one!

**Comment by GHNewbiee** [comment]
If one knows an alternative desktop with at least a `Fetch all` button, please let us know here. *Tia*

**Comment by jharris-symetrix** [comment]
Major pain point for me.  Automatic updating doesn't do the job of the actual fetch/pull.
Regarding the point of possible merge conflicts, we have people who use git in a read-only fashion and just want an easy way to get the latest versions of dozens of repos, so that's not an issue.  It could also simply skip repos that weren't in sync.

**Comment by GHNewbiee** [comment]
I have lately observed that right after `Github Desktop` starts, very soon the repositories are fetched. I am not an IT folk. But I have the sense that at present client does not automatically initialize the fetch operation as `request`. Server is the one which decides to start fetching. I suspect it depends upon traffic and other technical factors.

That's why manual request through a button is not provided since it would be developed into a pain point to the `Github` itself!!! Please `Github folks`, stop trying to feed us with grass!

**Comment by RawMajkel** [comment]
I am using GitHub Desktop for 5-8 years now and if I want to be 100% sure that every repository is fetched and up-to-date, I have to click on each one of them separately (which isn't too convenient).

Please consider adding an option to fetch all at once.

**Comment by tomse** [comment]
+1 for a "fetch all button"

and thank you for github desktop - without it I'd probably still be using SVN 😂

**Comment by keirankavanagh** [comment]
+1 I'd love a fetch all button.

**Comment by Neofrek** [comment]
+1
Even if you skip the repos that would cause a merge conflict, it would be a great help for me and my team
