### ISSUE TITLE
Unable to clone the repository

### ISSUE THREAD

**Issue by keerthanas39** [desktop/desktop#13514]
When I try to clone the repository it showing repository not found and authentication failed. Kindly help me to overcome from this as soon as possible.

**Comment by niik** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by keerthanas39** [comment]
Hii, 
Even though I have access for git repository and I have logged into my account with the github desktop as well. When I tried to clone by using URL and my credentials like user name and PAT it shows authentication failed .

![Screenshot (60)](https://user-images.githubusercontent.com/93176908/145800896-322dc0b8-1a6f-47f0-bc41-35ed85bed5fc.png)

**Comment by steveward** [comment]
@keerthanas39 thanks for the screenshot. Are you attempting to clone a repository that is hosted on GitHub, or a different Git hosting service? If it is a github.com repository can you verify that you are logged in by going to `File` > `Options` > `Accounts`?

**Comment by keerthanas39** [comment]
I am attempting to clone the repository from github.com and I have logged into my account by going to File > Options > Accounts, still I am facing the same issue which I shared in the screenshot.

**Comment by niik** [comment]
Hey @keerthanas39, could you upload a log file from GitHub Desktop so that I could get some more information about this issue? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Explorer`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue. Thanks!

**Comment by keerthanas39** [comment]
[2021-11-18.desktop.production.log](https://github.com/desktop/desktop/files/7711107/2021-11-18.desktop.production.log)
[2021-11-19.desktop.production.log](https://github.com/desktop/desktop/files/7711108/2021-11-19.desktop.production.log)
[2021-12-10.desktop.production.log](https://github.com/desktop/desktop/files/7711109/2021-12-10.desktop.production.log)
[2021-12-13.desktop.production.log](https://github.com/desktop/desktop/files/7711110/2021-12-13.desktop.production.log)
[2021-12-14.desktop.production.log](https://github.com/desktop/desktop/files/7711111/2021-12-14.desktop.production.log)
[2021-10-26.desktop.production.log](https://github.com/desktop/desktop/files/7711112/2021-10-26.desktop.production.log)

**Comment by keerthanas39** [comment]
[2021-12-14.desktop.production.log](https://github.com/desktop/desktop/files/7711210/2021-12-14.desktop.production.log)


this is the updated one which I tried recently

**Comment by niik** [comment]
@keerthanas39 Could you try following the steps below to see if that resolves your issue?

1. Log out of your account in GitHub Desktop by opening `File -> Options` and clicking `Sign out`
2. Open Window's Credential Manager (search for credential manager in the search field next to the start menu button)
3. Click on Windows credentials
4. Remove any generic credentials that start with `GitHub -`
5. Sign back into your account in GitHub Desktop using `File -> Options` and clicking `Sign in`

**Comment by steveward** [comment]
@keerthanas39 as we have not heard back from you I am going to close this issue out. Let us know if you are still having problems and we can investigate further.
