### ISSUE TITLE
Support for folder based on a list of GitHub desktop repositories

### ISSUE THREAD

**Issue by Ali-YousefiTelori** [desktop/desktop#13538]
### Describe the feature or problem you’d like to solve

We have +80 repositories in the GitHub desktop app, we need a category system based On the Github desktop app.

### Proposed solution

this feature will clear space of the repositories in my desktop application and easy to manage them, for example, we have Flight repositories, Hotel repositories, and Train Repositories, etc, so it will help us to clear and easy to manage them like folders based on an operation systems

### Additional context

![desktop](https://user-images.githubusercontent.com/5262218/146147718-93b3712d-c2b1-4c0b-868d-a587a97fe552.png)

**Comment by niik** [comment]
Hi @Ali-YousefiTelori, thanks for the suggestion!

We took this scenario into account as part of #6460, which included a range of possibilities and trade-offs that were made to accommodate multiple requests and features around repository organization. At this point, we are holding off on adding custom grouping for now.

I'm going to close this issue for now, since as I mentioned we don't have immediate plans to implement custom repository grouping.

See also https://github.com/desktop/desktop/issues/1533 for an earlier similar request.

Thanks for using Desktop!
