### ISSUE TITLE
To See Current barnch of every repositories?

### ISSUE THREAD

**Issue by Ali-YousefiTelori** [desktop/desktop#13539]
### Describe the feature or problem you’d like to solve

We have +80 repositories in the GitHub desktop app, we need to see all of the current branches of repositories at a glance.

### Proposed solution

For example, this feature will clear for us to see what branches are not in Develop so we will fix it and check out it to Develop to prevent developer mistakes, because maybe the developer forgot to checkout to develop and they change the main branch that is updated on our live servers

### Additional context

![desktop](https://user-images.githubusercontent.com/5262218/146152132-0bcc056f-f6ed-4043-8a2f-7148d2f3571e.png)

**Comment by niik** [comment]
Hi @Ali-YousefiTelori, this feature has been requested before in https://github.com/desktop/desktop/issues/8158 so I'm going to close this issue in favor of that. That issue is currently closed as we haven't prioritized it but please add a 👍 reaction to that issue, we use that and other factors when we decide what work to prioritize.
