### ISSUE TITLE
unresolved conflicts in working directory

### ISSUE THREAD

**Issue by VivBlue** [desktop/desktop#13535]
##
### Describe the feature or problem you’d like to solve

when i press the pull and fetch button, a status popped out " unresolved conflicts in working directory'. it stopping me from updateing. 

### Proposed solution

Please share how this will it benefit Desktop and its users?

### Additional context

Please include any other context, like screenshots or mockups, if applicable.

**Comment by Jynxninth** [comment]
Looking at the https://github.com/desktop/desktop/blob/development/.github/CONTRIBUTING.md#before-submitting-an-enhancement-suggestion

Clicking on th etemplate list does nothing but take you here 
https://github.com/desktop/desktop/blob/development/.github/ISSUE_TEMPLATE/problem-to-raise.md

**Comment by steveward** [comment]
@VivBlue this error indicates there are conflicts that need to be resolved and committed before you can perform a pull. You should see the conflicted files in the `Changes` tab. Let me know if you have any questions about how to resolve merge conflicts.

**Comment by Jynxninth** [comment]
I am attempting a "Guided" personal experience i am only trying to pull with myself because I don't understand/follow the https://github.com/github/docs/blob/main/CONTRIBUTING.md is because I am very new to coding this is a "to myself" thing, but I've uploaded pdfs that show my ideas because I am not a part of the contributing team.
