### ISSUE TITLE
Authentication Failed

### ISSUE THREAD

**Issue by twilms24** [desktop/desktop#13570]
I can't push Repositories.
There seems to be no way to fix this.

**Comment by steveward** [comment]
Thanks for the report @twilms24. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by 6645594094** [comment]
Ola

**Comment by JungleDnl4322** [comment]
wtf,  OLA VA CON H
