### ISSUE TITLE
Unable to push changes to the repository

### ISSUE THREAD

**Issue by rohitattaluri552** [desktop/desktop#13578]
When I'm trying to push my local changes to the repository, I'm getting some weird error.

Here I'm attaching the screenshot for you reference. 

Help me out fixing the issue asap.

<img width="1552" alt="Screenshot 2021-12-22 at 6 33 40 PM" src="https://user-images.githubusercontent.com/61145279/147097140-f1bc9a9e-110a-4f96-a19f-501cfa79cd33.png">
<img width="1552" alt="Screenshot 2021-12-22 at 6 33 29 PM" src="https://user-images.githubusercontent.com/61145279/147097114-14f09251-889a-4daf-aea9-c29dc94d8c43.png">

**Comment by steveward** [comment]
Thanks for the issue @rohitattaluri552. A pre-receive hook failure indicates something on the server side is blocking the push. Are you behind a proxy? The 504 gateway error indicates there's likely something in your network causing this problem. Since this is a specific network issue and is for a BitBucket repository, I'd recommend reaching out to their support for assistance debugging this. I'm going to close this out.
