### ISSUE TITLE
Post Log4J - Where am I supposed to find a command line git without powershell now?

### ISSUE THREAD

**Issue by mlane3** [desktop/desktop#13582]
# The Problem
 I would like to re-raise the issue of needing a command line get or an alternative to the depreciation of command line git for GitHub desktop.
https://github.com/desktop/desktop/issues/340
The alternative was PowerShell git as suggested by your employees here: 
https://stackoverflow.com/questions/34565238/where-does-github-desktop-install-command-line-version-of-git
In light of Log4J, we have realized at my organization that the same injection is possible for non-admin users using any PowerShell command regardless of whether or not they are privileged on that computer.   We debating about phasing out Github Desktop for similar reasons. 

In fact, a fun history fact for you all is that the Cyberattack on Atlanta was due to Powershell exploit in an python package.  Log4J has made us realize that other programs can have the same exploit.  You really should not use or recommend PowerShell as an executable method other than during initial installation. 

### Question
In light of log4J, we need a command line git again as github desktop does not provide the features that would alleviate security concerns at my organization dealing similar exploits we are seeing to log4J but involve powershell. 

**Where can I find a portable(1) command line(2), and https:// (3) supported git, so my government organization can manage change requests and public packages provided by the government properly?**

(1) Refers to no other folder or the C:\ Drive.  Github Desktop currently has a bug that refers to a non-local drive depending on how we configure it for the first time (SSH default vs no SSH default)
(2) Does no call to PowerShell at all and only uses command line at the non-administrative level
(3) Does not require SSH out of the box, but can use https:// to connect to github.com

**Comment by steveward** [comment]
@mlane3 thanks for the issue. [Git for Windows ](https://git-scm.com/download/win) does not require using PowerShell, and provides a portable version from the link I provided. You can select your terminal of choice from within GitHub Desktop by going to `File` > `Options` > `Shell`. Git Bash is the default terminal built into Git for Windows. GitHub Desktop also defaults to using HTTPS unless you specifically configure a new SSH key and clone a repository using SSH Git URLs.

I hope that helps explain things. I'm going to close this out since we don't have any plans to change our approach here, but let me know if you have any questions.
