### ISSUE TITLE
cloneing

### ISSUE THREAD

**Issue by GCRanpariya** [desktop/desktop#13621]
repository   is not cloneing  to this PC.

**Comment by steveward** [comment]
Thanks for the issue @GCRanpariya.

Would you mind filling out the rest of the issue template so that we can better understand what is causing the problem you are experiencing? Without that information it will be difficult to help you further. It would especially be helpful if you could upload the log file from GitHub Desktop, which will give more details about the specific error you are seeing. 

To access the log files go to the  menu in GitHub Desktop and select `Help` > `Show Logs...`. The log files are created daily -- please send over a log file as an attachment from a day where you experienced the issue.
