### ISSUE TITLE
Desktop will not clone wiki

### ISSUE THREAD

**Issue by lauren-mods** [desktop/desktop#13673]
### Describe the bug

When attempting to clone a Github Wiki in (a private repo), Github Desktop says 'we could not find that repository'

### Version & OS
Windows 10 (64), Github Destop 2.9.6

### Steps to reproduce the behavior

1. Go to the 'clone this wiki' button on a Github private wiki.
2. Copy exactly the path
3. Go to Github desktop
4. Select 'clone repository'
5. Select 'from URL'
6. Enter URL
7. Click 'clone'

### Expected behavior

Wiki is cloned as local repo

### Actual behavior

Dialogue menu returns error: "we could not find that repository."

### Screenshots
![Screenshot 2022-01-14 134539](https://user-images.githubusercontent.com/71786398/149526179-06ed0a75-a560-4e25-800c-bf8a2940cdae.jpg)
I redacted some personal info, but you can see what I mean.

**Comment by lauren-mods** [comment]
Please note I did ensure that there is content in the wiki before attempting this and I do have full ownership of repo and wiki

**Comment by sergiou87** [comment]
Hi @lauren-mods, thanks for the issue, and sorry you're running into that. We don't have great support for wikis in Desktop unfortunately, and we're tracking that in #3839, so please follow along there. For full transparency, I don't anticipate we'll be working on this anytime in the near future because our team is small and we have to prioritize things that are likely to significantly benefit a greater percentage of users. Thanks again!
