### ISSUE TITLE
Create branch: `Cmd + Enter` submits the form

### ISSUE THREAD

**Issue by majouji** [desktop/desktop#13680]
### Feature request

In the Create a Branch dialog, I’d love to be able to "submit"/confirm using <kbd>Cmd + Enter</kbd>, like in other parts of the GitHub Desktop app and web apps.

### Additional context

<img width="486" alt="image" src="https://user-images.githubusercontent.com/23482161/149682968-04f403c9-327f-48ec-b7e1-acb278e1435b.png">

**Comment by DJEtechnology** [comment]
CMD

**Comment by DJEtechnology** [comment]
SOY NUEVO

**Comment by niik** [comment]
Hey @majouji, just pressing `Enter` should be enough to create that branch, is that not the case for you?

Submitting forms using `Cmd + Enter` is a convention in GitHub.com's web interface but with the exception of the Commit form we haven't adopted it elsewhere, in part because it's not a macOS/Windows convention and in part because we haven't seen the need for it given that just `Enter` is usually enough. Is this a pattern that you've seen in other apps?

**Comment by majouji** [comment]
> Hey @majouji, just pressing `Enter` should be enough to create that branch, is that not the case for you?
> 
> Submitting forms using `Cmd + Enter` is a convention in GitHub.com's web interface but with the exception of the Commit form we haven't adopted it elsewhere, in part because it's not a macOS/Windows convention and in part because we haven't seen the need for it given that just `Enter` is usually enough. Is this a pattern that you've seen in other apps?

Ha! Guess the muscle memory was too strong with the Cmd key. It works! Thank you :D
