### ISSUE TITLE
Can't log in (once again) via GitHub desktop

### ISSUE THREAD

**Issue by tomas-lopez-elias** [desktop/desktop#13696]
Hi, once again I received again error while trying to log in to Github enterprise.

url https://github.kyndryl.net, using Github desktop 2.9.6 (x64) in macOS. Error Verify that URL is correct, using 2.8 version or older and you are connected to internet.

**Comment by sergiou87** [comment]
Hi @tomas-lopez-elias 👋 

Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

Thanks!
