### ISSUE TITLE
WHY IS THAT COMMIT TO MAIN BUTTON IS NOT WORKING

### ISSUE THREAD

**Issue by alibk1** [desktop/desktop#13692]

**Comment by steveward** [comment]
@alibk1 thanks for the issue! Can you verify you've entered a commit message? The commit button stays disabled until a commit message has been written.

**Comment by alibk1** [comment]
In Github Desktop interface, i have written summary and description and clicked to the button "Commit To Main". Button is enabled, and i have clicked and tried maybe 10000 times it is not working.

**Comment by alibk1** [comment]
@steveward

**Comment by alibk1** [comment]
![Ekran Alıntısı](https://user-images.githubusercontent.com/87261435/150120185-e14da484-bab2-4bfc-b6da-95ffafd15c16.PNG)

**Comment by steveward** [comment]
@alibk1 apologies for the delay. are you still having issues committing? Since you're trying to commit a large number of files it's likely you're hitting the limit threshold of GitHub Desktop. You can try committing directly via the command line for that initial commit. Let me know if you have any questions.

**Comment by absingh-495** [comment]
i'm facing same issue here tried everything but the commit to main button is not working.

**Comment by DanielYamini** [comment]
Unsubscribe
