### ISSUE TITLE
Error enumerating objects 11386, counting objects ,etc

### ISSUE THREAD

**Issue by Benzitczo** [desktop/desktop#13693]
![download](https://user-images.githubusercontent.com/36309164/150068246-c35fe513-6663-4cca-9c37-d3971efad61c.png)
for unity upload update.

**Comment by steveward** [comment]
Thanks for the issue @Benzitczo. It looks like the push is timing out due to the large size of the repository. Are you using Git LFS with this repository?

**Comment by Benzitczo** [comment]
> 

Yes, but I don't have git lfs I just use github desktop all files.

But already a solution maybe 4 GB size yes. (that can't 8 GB error)

**Comment by steveward** [comment]
@Benzitczo for Unity projects I would recommend using Git LFS. Unfortunately there is not much we can do about push timeouts on our end. Some users have had success switching to SSH instead of HTTPS when pushing larger files. You can read how to set up SSH here:

https://docs.github.com/en/authentication/connecting-to-github-with-ssh

Once you have set up a valid SSH key you will just need to switch the `origin` remote URL in GitHub Desktop by going to `Repository` > `Repository Settings` > `Remote`. I hope that helps!
