### ISSUE TITLE
Organization repositories, where user has access via team membership not showing up in repo list in Github desktop.

### ISSUE THREAD

**Issue by reos-rcrozier** [desktop/desktop#13717]
### Describe the bug

I have an organization with multiple repositories. I have granted user access to some repositories via team membership. However, in Github desktop, when users go to add a repository and select 'clone', these repositories do not appear on the list of repositories available to clone for that organisation. I have to go and add them ad individuals to the repo for them to appear.

### Version & OS

Windows 10
Github Desktop 2.9.6 (x64)

**Comment by steveward** [comment]
Thanks for the issue @reos-rcrozier. I tested and verified that repositories show up correctly for teams, so it's likely a specific permissions issue.

If your org has SAML SSO enabled that could be the problem since outside collaborators aren't required to authenticate with an identity provider to access the resources in an organization with SAML SSO. If that's the case I would recommend having them trying to log out/log back in to verify they're going through the SAML SSO flow. See [this guide](https://docs.github.com/en/enterprise-cloud@latest/authentication/authenticating-with-saml-single-sign-on/about-authentication-with-saml-single-sign-on#about-oauth-apps-and-saml-sso) for more info. Let me know if that helps.
