### ISSUE TITLE
not able to publish branch

### ISSUE THREAD

**Issue by ItsmeRushil** [desktop/desktop#13757]
unable to publish branch 
its showing  
fatal: unable to access ' https://github.com/ItsmeRushil/cartoon.git/':getaddrinfo() thread failed to start
![Screenshot (926)](https://user-images.githubusercontent.com/98411314/151383507-c8f0ad15-fa44-48c5-9375-d59cd1d61c22.png)

**Comment by steveward** [comment]
Thanks for the report @ItsmeRushil. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
