### ISSUE TITLE
Repository not showing

### ISSUE THREAD

**Issue by HarshD488** [desktop/desktop#13755]
### Describe the bug
Write a clear and concise description of what the bug is.

### Version & OS

Open the 'About GitHub Desktop' menu to see the GitHub Desktop version. Also include what operating system you are using.

### Expected behavior

Write a clear and concise description of what you expected to happen.

### Actual behavior

Write a clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by steveward** [comment]
Thanks for reaching out @HarshD488!

Would you mind filling out the rest of the issue template so that we can better understand what is causing the problem you are experiencing? Without that information it will be difficult to help you further. It would especially be helpful if you could upload the log file from GitHub Desktop, which will give more details about the specific error you are seeing. 

To access the log files go to the  menu in GitHub Desktop and select `Help` > `Show Logs...`. The log files are created daily -- please send over a log file as an attachment from a day where you experienced the issue.

**Comment by Fudoshiki** [comment]
same issue wtih `gpp.format = ssh`

**.gitconfig**

```gitconfig
[gpg]
  format = ssh
```

<img width="835" alt="Снимок экрана 2022-02-03 в 00 11 43" src="https://user-images.githubusercontent.com/4083992/152221462-5ad8fd5a-a060-4fd0-bdf0-f39552de54ba.png">

If I comment this line

<img width="587" alt="Снимок экрана 2022-02-03 в 00 10 28" src="https://user-images.githubusercontent.com/4083992/152221352-fac2e87d-0a63-48dc-b858-26bfc8fcf543.png">

When I uncomment again and click on any commit

<img width="928" alt="Снимок экрана 2022-02-03 в 00 11 08" src="https://user-images.githubusercontent.com/4083992/152221415-e74567b5-2f92-4552-b611-c8b86d79620a.png">
