### ISSUE TITLE
Error git command "git: 'remote-https' is not a git command. See 'git --help'."

### ISSUE THREAD

**Issue by Palakon-ATC** [desktop/desktop#13785]
### Describe the bug
Write a clear and concise description of what the bug is.
Error git command.

Version 2.9.6(x64) & OS Windows 11 (Build 22538.1010)

Open the 'About GitHub Desktop' menu to see the GitHub Desktop version. Also include what operating system you are using.

### Steps to reproduce the behavior

1. Go to : All project
2. Click on : Fetch origin or Push origin
3. See error : message box git: 'remote-https' is not a git command. See 'git --help'.

![image](https://user-images.githubusercontent.com/87563572/151735310-6734277e-0925-431c-9b26-b7c3a5b0ea5c.png)

[2022-01-31.desktop.production.log](https://github.com/desktop/desktop/files/7967870/2022-01-31.desktop.production.log)

**Comment by sergiou87** [comment]
Hello @Palakon-ATC! 👋 

We've seen this issue in the past on machines with an antivirus (like Windows Defender) enabled, which puts some of the binaries in GitHub Desktop in quarantine. Please, check if that's the reason. You might need to reinstall GitHub Desktop to recover those binaries.

I'll close this assuming that's the reason for your problem, but otherwise let me know and I'll be happy to reopen it.

**Comment by Palakon-ATC** [comment]
> 



> Hello @Palakon-ATC! 👋
> 
> We've seen this issue in the past on machines with an antivirus (like Windows Defender) enabled, which puts some of the binaries in GitHub Desktop in quarantine. Please, check if that's the reason. You might need to reinstall GitHub Desktop to recover those binaries.
> 
> I'll close this assuming that's the reason for your problem, but otherwise let me know and I'll be happy to reopen it.

Hi @sergiou87 
I allow all folder Git on Eset Nodt32.
I think the problem is gone.
thx a lot for support.
