### ISSUE TITLE
Pushing to github repositories takes forever

### ISSUE THREAD

**Issue by haesleinhuepf** [desktop/desktop#13800]
### Describe the bug

In some cases, when pushing to a repository, it hangs forever in this stage:

![image](https://user-images.githubusercontent.com/12660498/151867594-ab66c6ab-ad6a-40f0-8b47-5d4a7d462a3e.png)

When I then restart github desktop and push the same change again, it works (sometimes).

### Version & OS

Open the 'About GitHub Desktop' menu to see the GitHub Desktop version. Also include what operating system you are using.

Version 2.9.6 (x64)

### Steps to reproduce the behavior

It happens on many repositories, when pushing to github.com

### Expected behavior

It would be nice if pushing would succeed or if an error would pop up.

### Actual behavior

It hangs forever in the above visualized stage.

### Screenshots

See above

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable. The last log file entries have nothing to do with me pushing to the repository.

### Additional context

On Windows 10 the same works nicely. I only observe this behaivour on an new Apple Mac with M1 Max CPU.

**Comment by sergiou87** [comment]
Thank you for your report @haesleinhuepf !

It's weird because usually, git operations take longer on Windows. I do see you're using an x64 version instead of one built for Apple's M1 processors (which should run much faster). You can download it from https://central.github.com/deployments/desktop/desktop/latest/darwin-arm64 or just wait until the next update, it should automagically switch to arm64 builds.

From our website https://desktop.github.com, you can find those builds here:

![2022-02-01 at 09 42](https://user-images.githubusercontent.com/1083228/151937335-673fb185-4503-455b-9eda-448aa1b7d1f9.png)

Please try those arm64 builds and let me know if it helps!

**Comment by zeelsheladiya** [comment]
don't know why but. when it happens to me. somehow I open or close my browser's new tab. and when I come back to my GitHub desktop application. the task was done. then I started to do this every time and it was working every time whenever I get never-ending pushing requests.

**Comment by haesleinhuepf** [comment]
> Please try those arm64 builds and let me know if it helps!

Thanks for this hint @sergiou87! I've been trying this for one week now and it works like a charm.

Feel free to close this issue 🙌

**Comment by samanthahuff** [comment]
> 

I am using the arm64 version and still having this issue

**Comment by MadeByDouglas** [comment]
I still have this issue, v3.0.8 arm64, its very annoying. sometimes it works pretty quick and normal, other times just hangs part way. I check other parts of my network they seem fine. Now in this case the upload is a little bigger, but its still overall pretty small (1.2mb of images) so that should be within expected size right?

<img width="1072" alt="Screen Shot 2022-09-23 at 10 05 31 AM" src="https://user-images.githubusercontent.com/10858053/192014684-665a5ff6-a2a6-4ad9-b118-93b2202394ba.png">

**Comment by steveward** [comment]
@MadeByDouglas can you share a log file from a day you experienced this issue? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`. Thanks!

**Comment by MadeByDouglas** [comment]
sure, lets see this should be it
[2022-09-23.desktop.production.log](https://github.com/desktop/desktop/files/9636199/2022-09-23.desktop.production.log)

**Comment by MadeByDouglas** [comment]
I rebooted my machine, (MacBook Air M1) then tried pushing, it worked like a charm. So not sure what thats about, but I'll attach the updated log here. Also, noticeably, just quitting and restarting just the app did not help at all which I had tried.

[2022-09-23.desktop.production.log](https://github.com/desktop/desktop/files/9636345/2022-09-23.desktop.production.log)

**Comment by alecfilios** [comment]
same here

**Comment by JavascriptCoder999** [comment]
same here

**Comment by alanhkarp** [comment]
@MadeByDouglas did you quit or just close the window?  Closing the window did not resolve the problem for me, but quitting did.

**Comment by MadeByDouglas** [comment]
I was quitting the app, Command Q etc.

**Comment by MuhammadMazhar313** [comment]
still facing Same issue  in Version 3.2.1 (x64)

![Screenshot 2023-04-07 at 1 19 21 AM](https://user-images.githubusercontent.com/34936746/230486046-e2a305dc-f757-405a-81ba-5c43d8b4ae2f.png)

**Comment by alanhkarp** [comment]
I've had the same problem a couple of times in the past month or so.  Quitting the application and reopening it has worked for me every time.

**Comment by Mrgoudan** [comment]
Had the same issue. Quitting thing worked for me too. Don't know why tho

**Comment by thekoenekamp** [comment]
Facing this issue in Version 3.2.4 (arm64)

Quitting didn't work for me. Even restarting my Mac didn't change anything. (M1 Pro) - @sergiou87 @steveward 

EDIT:
There was just an update, works again for me.
