### ISSUE TITLE
not able to login to git desktop

### ISSUE THREAD

**Issue by MerlinFrancis** [desktop/desktop#13818]
not able to login to git desktop. it always prompts for username and password. the original credentials are not taking 
![image](https://user-images.githubusercontent.com/50442287/152505770-1a9ea869-e6ce-4c19-bc40-6ecf109d65ae.png)

**Comment by niik** [comment]
Thanks for the report! Could you upload a log file from GitHub Desktop so that I could get some more information about this issue? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue. Thanks!
