### ISSUE TITLE
A partially set-up user is able to pull code from an organisations repo

### ISSUE THREAD

**Issue by VictrixHominum** [desktop/desktop#13836]
### Describe the bug
A user who has not fully setup their account is able to clone code from a repo

p.s. not sure if this is a bug, but it feels like an unintended behaviour so I'm raising it

### Version & OS

Version: 2.9.6
OS: Windows 10

### Steps to reproduce the behavior

1. Have an existing org and repo on Github
2. Have a new joiner who is new to Github, create an account, but NOT enter the verification code sent to their email to finalise
3. Invite said user to your organisation with permissions to read and write to the repo
4. Have them pull the repository
5. Then have them try to publish a branch or push a change 
6. Authentication Error pops up

### Expected behavior

A user who isn't fully set up should not
1) be able to pull a repo
2) Error message should display that the user needs to finalise setup

### Actual behavior

A user who isn't fully set up:
1) Can clone a repo
2) Gets an unhelpful error message

### Screenshots

N/A

### Logs

N/A

**Comment by niik** [comment]
Hi @VictrixHominum, thanks for reaching out. The behavior of "partially" set up users isn't something we on the GitHub Desktop team can control, that behavior would be the same regardless of using GitHub Desktop or some other tool.

As for presenting a more helpful message as to why the push failed we'd love to do that but I wasn't aware that we made such a distinction. Could you  upload a log file from GitHub Desktop on that user's machine so that I could get some more information about this issue? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue. Thanks!
