### ISSUE TITLE
添加编译器

### ISSUE THREAD

**Issue by vchjkf5** [desktop/desktop#13833]
在文件，选项，开发集成里添加更多的编译器

**Comment by niik** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:


-----


感谢您伸出援手！

我们要求在所有新问题上填写模板。 我们这样做是为了
我们可以确定我们拥有解决您的问题所需的所有信息
高效提交。 这允许维护人员花费更多时间进行修复
错误、实施增强以及审查和合并拉取请求。

感谢您的理解和半途而废：咧嘴笑：
