### ISSUE TITLE
GitHub Enterprise User Showing

### ISSUE THREAD

**Issue by say25** [desktop/desktop#13848]
### Describe the bug
GitHub Enterprise User Showing in commit history

### Version & OS

Version 2.9.7-beta2 (x64) - Windows 10

### Steps to reproduce the behavior

1. On a GHE repo, got to commit history

### Expected behavior

GitHub History matches GHES webpage

### Actual behavior

GitHub History does not match GHES webpage

### Screenshots

<img width="614" alt="image" src="https://user-images.githubusercontent.com/7467062/153093911-ebba3223-114f-428b-99e9-78525b1df18e.png">

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

### Additional context

This seems to have been introduced with the  changes to add Avatars from GHES 3.0+. https://github.com/desktop/desktop/pull/13719

We are currently on GHES 3.1.14

**Comment by niik** [comment]
:wave: @say25!

I'd be surprised if the avatars work would have had an impact here but anything is possible. I'm guessing that this is a commit made using the web interface on GHES (or rebased by GHES), correct?

This "user" should be identified as a web flow committer by https://github.com/desktop/desktop/blob/e9b6653a3a527a0c5d2255f643f03eeaaa7d5bf3/app/src/lib/web-flow-committer.ts#L34-L37

and then filtered out by

https://github.com/desktop/desktop/blob/e9b6653a3a527a0c5d2255f643f03eeaaa7d5bf3/app/src/models/avatar.ts#L67-L78

Would you be able to toss a breakpoint on either of those lines in DevTools and see what's causing it to not be recognized? I'm guessing that there's been some change in the logic on GHES side (or it's never worked in Desktop I guess) because after reading the filter logic I would have expected the address to be something like ghe-noreply@**github**.coxautoinc.om and not just the apex domain.

---
**Oh interesting**: So it apparently GHES customers can customize their noreply-email in admin tools. I thought it was statically defined based on the hostname of the GHES instance 🤦 Is it possible someone changed that address on your instance recently @say25 and that's why you're seeing it now?

**Comment by say25** [comment]
> Is it possible someone changed that address on your instance recently @say25 and that's why you're seeing it now?

Very possible! I know we are actively working on moving from GHE 3.1.X to GHE 3.3.X maybe things moved
