### ISSUE TITLE
Can't actually log out

### ISSUE THREAD

**Issue by vargat99** [desktop/desktop#13858]
### Describe the bug
After clicking the log out button I still logged in, not even restarting my compter logs me out

### Version & OS

Version 2.9.6 (x64)
OS: Windows 10

### Steps to reproduce the behavior

1. Go to File/Options
2. Click on 'Log out
3. Retrurn to main sreen

### Expected behavior

I should be logged out, and be presented with the login screen

### Actual behavior

I remain logged in

### Screenshots

![image](https://user-images.githubusercontent.com/78794230/153309968-193bf14f-1987-4cb9-b281-e2372df72cf8.png)
![image](https://user-images.githubusercontent.com/78794230/153310009-686db4b1-b19c-410d-98b6-b4d5cc3d2d34.png)

### Logs

[2022-02-09.desktop.production.log](https://github.com/desktop/desktop/files/8036919/2022-02-09.desktop.production.log)

**Comment by sergiou87** [comment]
Hi @vargat99 ! 👋 

What you're seeing is indeed the correct behavior: you were logged out (as you can see in the Preferences -> Accounts screen), but you still keep access to all the repositories you have cloned in your machine.

You can check you are logged out because you no longer have access to the list of Pull Requests, or you can't mention other users in the commit message box, nor reference issues from the repository with `#`.

I hope that helps!

**Comment by vargat99** [comment]
Ohhh, I see.
Thanks for the quick reply and clarification.
