### ISSUE TITLE
How to delete repository

### ISSUE THREAD

**Issue by MahmudurRaiyan** [desktop/desktop#13860]
### Describe the bug
Write a clear and concise description of what the bug is.
i just cant get the opting to delete after conforming it 
### Version & OS

Open the 'About GitHub Desktop' menu to see the GitHub Desktop version. Also include what operating system you are using.

### Expected behavior

Write a clear and concise description of what you expected to happen.

### Actual behavior

Write a clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

### Additional context

![Capture](https://user-images.githubusercontent.com/98677513/153344617-cc061946-284f-44e1-8377-c7572ea0830f.PNG)

**Comment by MahmudurRaiyan** [comment]
pls help me

**Comment by sergiou87** [comment]
Hi, this issue doesn’t appear to be related to the GitHub Desktop application so I’m going to close this issue. In any case, I think you have to write `MahmudurRaiyan/html-project1` instead of just `html-project1` to delete the repository. You can find help for this issue at [GitHub support](https://support.github.com).

Best of luck!
