### ISSUE TITLE
Installer not installer but installer

### ISSUE THREAD

**Issue by UnrealKaraulov** [desktop/desktop#13884]
Написало что будет обновление после перезапуска, но не обновилось.

Скачивал вручную установщик - не устанавливается.

Скачивал msi установщик - не устанавливается.

Программа умерла, есть ли замена этой программе?

**Comment by niik** [comment]
Automatic translation:

> Wrote that there would be an update after the restart, but it was not updated.
> I downloaded the installer manually - it does not install.
> I downloaded the msi installer - it does not install.
> The program has died, is there a replacement for this program?

Response:

Are you using Windows or macOS, and which version?

Could you upload a log file from GitHub Desktop so that I could get some more information about this issue? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue. 

---

Вы используете Windows или macOS и какую версию?

Не могли бы вы загрузить файл журнала с GitHub Desktop, чтобы я мог получить дополнительную информацию об этой проблеме? Чтобы получить доступ к файлам журнала, перейдите в меню файлов в GitHub Desktop и выберите «Справка» > «Показать журналы в Finder (macOS) или проводнике (Windows)».

Файлы журнала создаются ежедневно. Пожалуйста, загрузите файл журнала в качестве вложения за день, когда возникла проблема.

**Comment by UnrealKaraulov** [comment]
Windows версия , все я не могу ее использовать потому что она более не хочет устанавливаться. Exe установщик самоудаляется, а msi ничего не делает (пробовал удалить, изменить, обновить - ничего).

Не запускается! Не обновляется! Я получил новое обновление сегодня, одно сломало GITHUB DESKTOP и никак не возможно восстановить.

**Comment by niik** [comment]
> Windows version, but I can't use it because it doesn't want to install anymore. Exe installer self-deletes, and msi does nothing (tried to delete, change, update - nothing).
>
> Doesn't start! Is not updated! I got a new update today, one broke the GITHUB DESKTOP and there is no way to fix it.

Have you tried rebooting your machine before attempting to install?

---

> Вы пытались перезагрузить компьютер перед попыткой установки?

**Comment by UnrealKaraulov** [comment]
Yes я перезагружал, это не помогает. Установка просто закрывается.

**Comment by niik** [comment]
To get some more information about why the installation is failing it would be helpful if you could send over the log file that the Squirrel installer generates.

You should be able to find the log file here:

`%LocalAppData%\GitHubDesktop\SquirrelSetup.log`

If no log file is being generated there you should be able to find one in the SquirrelTemp directory:

`%LocalAppData%\SquirrelTemp\SquirrelSetup.log`

Please send that over as an attachment.

---

Чтобы получить дополнительную информацию о том, почему установка не удалась, было бы полезно, если бы вы могли отправить файл журнала, который генерирует установщик Squirrel.

Вы должны быть в состоянии найти файл журнала здесь:

`%LocalAppData%\GitHubDesktop\SquirrelSetup.log`

Если файл журнала не создается, вы сможете найти его в каталоге SquirrelTemp:

`%LocalAppData%\SquirrelTemp\SquirrelSetup.log`

Пожалуйста, пришлите это как вложение.

**Comment by UnrealKaraulov** [comment]
First directory is empty
![image](https://user-images.githubusercontent.com/88730285/154074410-e65de885-77af-430c-b3d0-ab7c6d185fd7.png)
Second directory:
![image](https://user-images.githubusercontent.com/88730285/154074480-b84bae93-18aa-4c9f-83a4-2d3f09fbe8f4.png)

**Comment by UnrealKaraulov** [comment]
@niik I think error: remote server is not avaiabled! 404 ERROR. ?????

**Comment by niik** [comment]
The 404 error is expected and only relates to the application icon so that shouldn't be an issue.

Could you try manually removing the first folder?

%LocalAppData%\GitHubDesktop\SquirrelSetup.log

---

Ошибка 404 ожидается и относится только к значку приложения, так что это не должно быть проблемой.

Не могли бы вы попробовать вручную удалить первую папку?

`%LocalAppData%\GitHubDesktop\SquirrelSetup.log`

**Comment by UnrealKaraulov** [comment]
Нет никакой реакции на удаление папки `%LocalAppData%\GitHubDesktop`

**Comment by UnrealKaraulov** [comment]
@niik Thanks problem fixed, but i don't know what!))
