### ISSUE TITLE
Blank screen when the app starts

### ISSUE THREAD

**Issue by YangFong** [desktop/desktop#13906]
### Describe the bug

When I started the program yesterday, I found a blank screen. Later, I found that it was automatically updated to the new version 2.9.7. So I uninstalled 2.9.6 and got the correct response. The current new version 2.9.7 does not work properly on my computer.

### Version & OS

GitHub Desktop: 2.9.7
System: Windows 11 21H2 

### Expected behavior

Normal use

### Actual behavior

The application has a blank screen and no other response

### Screenshots

![image](https://user-images.githubusercontent.com/70502828/154193027-9a8e31e1-53de-40b2-8bd4-48c8249c1a40.png)

### Logs

Unable to open the app, need to tell me what specific files to provide

**Comment by steveward** [comment]
@YangFong thanks for the report. You're likely running into something similar https://github.com/desktop/desktop/issues/3757. Could you try reinstalling GitHub Desktop by following these steps?

1. Close GitHub Desktop
2. Open File Explorer
3. Go to `%LocalAppData%` and delete the `GitHubDesktop` directory
4. Go to `%AppData%` and delete the `GitHub Desktop` directory
5. Reinstall GitHub Desktop from http://desktop.github.com

Let me know if that does not get things working.

**Comment by YangFong** [comment]
@steveward I have tried this method and it does not work. 2.9.6 is ok

**Comment by YangFong** [comment]
I didn't use artboards to make the screen look white. Until the problem is fixed, I can use the previous version

![image](https://user-images.githubusercontent.com/70502828/154279263-92913ccf-4882-467a-843a-2b9bf1cead07.png)

![image](https://user-images.githubusercontent.com/70502828/154279479-b834ec2f-90ee-4c2c-a024-35c03af0d0bb.png)

**Comment by mcmcelro** [comment]
I have the same issue. Version 2.9.7 completely broke the application on my machine. It doesn't load at all. When it loads, which only happens if I attempt to run it again, it displays only a blank white window.

## Version & OS
Github Desktop 2.9.7
System: Windows 10 20H2

Expected behavior, actual behavior, and screenshots the same as above. Nothing is logged.

Completely wiping out all files and registry settings related to Github Desktop does not resolve the problem.

I've seen the guides that say to delete everything in %appdata%\GitHub Desktop, but that does nothing. The app is still broken. I had to install version 2.9.6 from a third-party site because there was no official way to install an older version from the official site.

When the application runs, four processes are spawned (see **[v2.9.7 params.txt](https://github.com/desktop/desktop/files/8080461/v2.9.7.params.txt)**). If I terminate the process with no parameters, the one with `--type=renderer` remains and must be terminated separately.

I noticed that the processes have very different parameters from version 2.9.6 (see **[v2.9.6 params.txt](https://github.com/desktop/desktop/files/8080460/v2.9.6.params.txt)**).

**Comment by tidy-dev** [comment]
@YangFong and @mcmcelro 

We had [one user report](https://github.com/desktop/desktop/issues/3757#issuecomment-1041821273) that their windows user name had special characters in and it prevented them from being able to open the app with it being stored? Does that apply to either of you?

**Comment by tidy-dev** [comment]
Notes: on investigating this and based on https://github.com/desktop/desktop/issues/3757#issuecomment-1041821273, I found this [electron bug](https://github.com/electron/electron/issues/30966) that would impact release 2.9.7. However, when I try to reproduce, I do not get white/blank app - it just simply does not open, but shows in task manager. Thus, may not be same root cause.

**Comment by clocke-nextech** [comment]
Same issue here.  My report is exactly as @mcmcelro stated.  v2.9.7 and now the 2/16/2022 release of v2.9.8 both broken.  Unable to find a version of v2.9.6 to revert back to working.

**Comment by mcmcelro** [comment]
@tidy-dev My user name is a 5-digit number, so no special characters here. The behavior is the same as what you described regarding the electron bug - the processes appear in Task Manager, but the application does not open. The second time I run the application, a white screen appears.

By the way - I get the same results in v2.9.8 as well.

**Comment by mcmcelro** [comment]
In #13922 ,  the poster said that the actual behavior was:

> Does not automatically restart after the update
> If the app is started manually, shows an unmovable white rectangle

I noticed that on my machine, when I closed v2.9.6 today, v2.9.8 was installed and launched automatically, but the processes remained in the background with no UI. When I attempted to run v2.9.8, I saw the white rectangle.

**Comment by YangFong** [comment]
@tidy-dev My username is normal. I just tried 2.9.8 and the problem still exists。

**Comment by sergiou87** [comment]
Thanks everyone for your reports! ❤️ 

While you have that white screen, could you please press <kbd>Control</kbd> + <kbd>Shift</kbd> + <kbd>I</kbd>? It should show the Developer Tools, which in its `Console` tab might give a hint about the reason why it failed to run:

![image](https://user-images.githubusercontent.com/1083228/154437761-8efd6a1f-e61a-4175-af32-76ed8a0b2653.png)

Also, please look for your log files in `C:\Users\[your-user-name]\AppData\Roaming\GitHub Desktop\logs` and share them here, since those could be useful to diagnose the issue 🤞

**Comment by YangFong** [comment]
@sergiou87 I managed to open it, but there was nothing. I'm uploading the log file, hoping it'll help.

![image](https://user-images.githubusercontent.com/70502828/154438949-15242fdd-640e-465e-adea-72e34182f79c.png)


[2022-02-17.desktop.production.log](https://github.com/desktop/desktop/files/8087003/2022-02-17.desktop.production.log)

**Comment by sergiou87** [comment]
Thank you @YangFong! 🙇‍♂️ 

Unfortunately, your logs don't have anything we can use either 😢  Another option I can think of to diagnose this is using Git Bash or Cygwin (whatever unix-like terminal you have), go to your `~/AppData/Local/GitHubDesktop/app-2.9.8` folder and running `GitHubDesktop.exe` from there. You would probably need these commands:
```bash
$ cd ~/AppData/Local/GitHubDesktop/app-2.9.8
$ ./GitHubDesktop.exe
```

By doing this, I'd hope that you'd see in the console any errors that GitHub Desktop could output:

![image](https://user-images.githubusercontent.com/1083228/154440956-4b3b6f6e-ad59-43d0-8ccd-cfe91b078b7f.png)

**Comment by YangFong** [comment]
@sergiou87 Here are my results.

![image](https://user-images.githubusercontent.com/70502828/154441828-66e7ad02-e7d6-42c4-b4ff-51b8a185109c.png)

**Comment by sergiou87** [comment]
Thanks again for the quick reply 😄 

That indeed matches the Electron/Chromium bug that @tidy-dev mentioned before: https://github.com/electron/electron/issues/30966

Just in case, what happens if you run `./GitHubDesktop.exe --disable-gpu` in that last step? Does it make anything difference?

**Comment by YangFong** [comment]
@sergiou87 I managed to open it!

![image](https://user-images.githubusercontent.com/70502828/154443418-94c6e9b3-ea2e-4839-b713-3c64890a3f79.png)


![image](https://user-images.githubusercontent.com/70502828/154443373-0829b29a-b02c-45a9-9d4b-03bdec5aed57.png)

**Comment by sergiou87** [comment]
Yay!! That's great news 😄 

Not sure if this will work, but if you want to keep running the app from a shortcut (from Desktop or the Start Menu), maybe you can edit the shortcut to add that `--disable-gpu` parameter:

![image](https://user-images.githubusercontent.com/1083228/154445975-82893010-ee8e-434d-b230-73d2324673fe.png)

**Comment by YangFong** [comment]
> Yay!! That's great news 😄
> 
> Not sure if this will work, but if you want to keep running the app from a shortcut (from Desktop or the Start Menu), maybe you can edit the shortcut to add that `--disable-gpu` parameter:
> 
> ![image](https://user-images.githubusercontent.com/1083228/154445975-82893010-ee8e-434d-b230-73d2324673fe.png)

In addition to using 2.9.6, this is also an available solution.

**Comment by sergiou87** [comment]
I'm gonna leave the link to the 2.9.6 build (for Windows x64) here since this is a very annoying issue: https://centralreleases.blob.core.windows.net/github-desktop/releases/2.9.6-9196a1ae/GitHubDesktopSetup-x64.exe

Thank you again for your help and sorry for all the trouble, I hope we can get a proper fix for this soon 😞

**Comment by sergiou87** [comment]
@YangFong (or someone else) could you do me a favor and try out this test build? https://centralreleases.blob.core.windows.net/github-desktop/releases/2.9.9-test1-288b4926/GitHubDesktopSetup-x64.exe

Please, try it out (making sure the shortcut doesn't have the `--disable-gpu` parameter in it) and let me know if it works!!

It basically [downgrades Electron to v15.3.7](https://github.com/desktop/desktop/commit/487a846b2bc0d36c99cf45ebf464d9f837b475e6), which _in theory_ doesn't have this white screen issue, but I can't know for sure until someone tests it for me 😅 

Thanks in advance!!

**Comment by YangFong** [comment]
> @YangFong (or someone else) could you do me a favor and try out this test build? [centralreleases.blob.core.windows.net/github-desktop/releases/2.9.9-test1-288b4926/GitHubDesktopSetup-x64.exe](https://centralreleases.blob.core.windows.net/github-desktop/releases/2.9.9-test1-288b4926/GitHubDesktopSetup-x64.exe)
> 
> Please, try it out (making sure the shortcut doesn't have the `--disable-gpu` parameter in it) and let me know if it works!!
> 
> It basically [downgrades Electron to v15.3.7](https://github.com/desktop/desktop/commit/487a846b2bc0d36c99cf45ebf464d9f837b475e6), which _in theory_ doesn't have this white screen issue, but I can't know for sure until someone tests it for me 😅
> 
> Thanks in advance!!

No problem, I don't think I added any parameters.

![image](https://user-images.githubusercontent.com/70502828/154475881-b11fcd90-a249-4aa5-8931-db440db2a7e9.png)

**Comment by sergiou87** [comment]
That was quick! And it works!!! That's great news 😄 thank you again 🙇‍♂️ 🙇‍♂️ 🙇‍♂️ 🙇‍♂️

**Comment by clocke-nextech** [comment]
I concur that the v2.9.9 test version from the link above now launches successfully!  Thank you!

**Comment by tidy-dev** [comment]
@YangFong or @clocke-nextech  Thank you so much for testing this out for us!  Would you be willing to do us another favor and test out another test build with a[ newer electron version](https://github.com/desktop/desktop/commit/749a5c07d836af72806d837e992cc669e528c191)?

https://centralreleases.blob.core.windows.net/github-desktop/releases/2.9.9-test2-4038d108/GitHubDesktopSetup-x64.exe

**Comment by mcmcelro** [comment]
@tidy-dev 
2.9.9-test1: works as expected!
2.9.9-test2: white screen again.

**Comment by clocke-nextech** [comment]
@tidy-dev I have the same results  as @mcmcelro 
v2.9.9-test1: works
v2.9.9-test2: white screen

**Comment by tidy-dev** [comment]
Sadness.. But, thank you for testing @mcmcelro and @clocke-nextech!

**Comment by tidy-dev** [comment]
:wave: Another test release to try if anyone is willing?
This is Electron 17 - the latest stable electron version.
https://centralreleases.blob.core.windows.net/github-desktop/releases/2.9.9-test3-a3a284da/GitHubDesktopSetup-x64.exe

**Comment by clocke-nextech** [comment]
@tidy-dev v2.9.9-test3 launches successfully

**Comment by tidy-dev** [comment]
Awesome! Thank you for the quick testing!

**Comment by tidy-dev** [comment]
@YangFong @clocke-nextech @mcmcelro @miyasudokoro We have just released a hotfix with Electron 17 to production. You should be able to [download the latest](https://desktop.github.com/). Please let us know if that does not work for you. Thank you all again for your tremendous help in debugging and testing out fixes for this issue!

**Comment by kingmad998** [comment]
Looks like this was tied to the 2.9.7 update on Windows 11. [characterconverter](http://characterconverter.com) Downgrading fixed it, so hopefully newer versions avoid the same blank-screen issue.
