### ISSUE TITLE
File upload issue

### ISSUE THREAD

**Issue by fiyinadedigba** [desktop/desktop#13918]
### Describe the bug
I tried uploading a file but i keep getting 'This file is empty' error message, however the file is not empty

### Version & OS

Open the 'About GitHub Desktop' menu to see the GitHub Desktop version. Also include what operating system you are using.

### Expected behavior

Write a clear and concise description of what you expected to happen.

### Actual behavior

Write a clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by steveward** [comment]
@FiyinfoluwaAshamu thanks for the issue. Can you share a few more details about the exact steps you are taking? Are you trying to commit a file in GitHub Desktop? 

Could also you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by SpudGunMan** [comment]
on OSX the last two builds have broken files and folders and the latest build from today appears to have broken it more OSX12.2 its very annoying and I cant get good version tracking on my folders this is a mess
