### ISSUE TITLE
Emojis appear as white icon.

### ISSUE THREAD

**Issue by ahmet-cetinkaya** [desktop/desktop#13911]
### Describe the bug
Emojis appear that in commit as white icon.

### Version & OS

Version 2.9.7 (x64)
Windows 11

### Steps to reproduce the behavior

1. Go to 'History Tab'

### Expected behavior

Emojis appear that in commit normally like previous version.

### Actual behavior

Emojis appear that in commit as white icon in current version.

### Screenshots

![image](https://user-images.githubusercontent.com/53148314/154212071-3c2b3998-15e7-4865-a283-c184a0c9454f.png)

### Logs

-

### Additional context

-

**Comment by niik** [comment]
So good news and bad. Turns out this is because of a [Chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1266022) which is fixed in Chrome 97+. It only affects unicode emoji rendered with font weight 600 or above.

So the good news are that by changing the font weight we can get the regular emojis back. The bad news is that we don't have a good way to select the unicode emoji ranges and apply those styles.

Also this problem disappears in the next major version of Electron but we've _just_ bumped so I'm not sure how willing we are to get on that train just yet.

## Electron 16.0.8 (used in 2.9.7)

![image](https://user-images.githubusercontent.com/634063/154248295-f84fbdd6-9503-482d-83b7-2842338cdd5f.png)

## Electron 11.5.0 (used in 2.9.6)

![image](https://user-images.githubusercontent.com/634063/154248493-0a5b51fa-1568-47a7-865c-0f51528ec256.png)

## Electron 17.0.1 (latest stable)

![image](https://user-images.githubusercontent.com/634063/154248698-c4d6ceed-1500-4834-9761-915b4604db9c.png)
