### ISSUE TITLE
couldn't connect with VS code

### ISSUE THREAD

**Issue by joevaikka** [desktop/desktop#13923]
I opened my github desktop and tried to open my repository in VS code but it shows an error. It gave an option to 'exit and restart'. I tried that too but still it shows the error again and again.I have attached the error it shows while connecting with VS code. Please helpme with this issue.
Thank you.

<img width="464" alt="github error" src="https://user-images.githubusercontent.com/98135202/154340642-5922c647-dabd-4706-8807-6c2cc19c4c30.png">

**Comment by steveward** [comment]
@joevaikka thanks for the issue. We often see these issues with VSCode caused by problems with the system PATH. Has opening VSCode from GitHub Desktop previously worked on your machine? 

One common cause has been `system32` not being in your system PATH. See my [comment here](https://github.com/desktop/desktop/issues/13005#issuecomment-925139252) for the steps to check this on your machine. If that doesn't seem to be the issue it'd be helpful if you could share your full PATH for us to take a look at.

**Comment by joevaikka** [comment]
I tried what you told me to do and system32 was in my system PATH.I have send the output of the command prompt to look upon my issue.
Thank you.


C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\System32\OpenSSH\;C:\MinGW\bin;C:\Android;C:\Windows\System32;C:\Program Files\Git\cmd;C:\Users\joeva\AppData\Local\Microsoft\WindowsApps;C:\Users\joeva\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\joeva\AppData\Local\GitHubDesktop\bin

**Comment by sergiou87** [comment]
Hi @joevaikka ! 

The screenshot you posted mentions Cygwin instead of VS Code. Do you know why would that be? 

Also, could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by joevaikka** [comment]
I don’t know where that from but anyway I have deleted that Cygwin files and I have also attached the file you asked for. Could you please rectify the issue as early as possible.

Thank you!

**Comment by sergiou87** [comment]
I'm sorry @joevaikka but the log file didn't get uploaded. As far as I know you can't do that from your email, you must open the issue on GitHub and attach the file directly in the comment 😕

**Comment by joevaikka** [comment]
I have attached the file you have asked. Hope you can rectify my problem soon.

Thank you

[2022-02-09.desktop.production.log](https://github.com/desktop/desktop/files/8103197/2022-02-09.desktop.production.log)

**Comment by steveward** [comment]
@joevaikka I'm seeing a few miscellaneous errors but nothing specifically correlated to the VSCode issue you are encountering. Has opening VSCode previously worked on your system? The log file also shows you being on an older version than the one you mentioned (v2.9.6), are you able to upload a log file from a specific day you encountered this error?
