### ISSUE TITLE
Not able to create and push repository from Visual studio 2019 or any visual studio .

### ISSUE THREAD

**Issue by SAPTECHNICAL** [desktop/desktop#13926]
### Describe the bug
Not able to create and push repository from Visual studio 2019 or any visual studio .

### Version & OS
Github version 2.9.7 (x64)
OS : 
Edition	Windows 10 Pro
Version	20H2
Installed on	‎10/‎19/‎2021
OS build	19042.1466
Experience	Windows Feature Experience Pack 120.2212.3920.0

### Expected behavior

Write a clear and concise description of what you expected to happen.

### Actual behavior

Write a clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by sergiou87** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
