### ISSUE TITLE
'spawn UNKNOWN' error in 'check for updates'

### ISSUE THREAD

**Issue by bistcuite** [desktop/desktop#13976]
### Describe the bug
When i clicked on check for updates in 'About GitHub Desktop` in  help menu i got this error :
![Capture](https://user-images.githubusercontent.com/85484922/155277538-6cf64902-452a-452c-827e-446f59d9ce6c.PNG)

### Version & OS
v2.9.3 x64

### Steps to reproduce the behavior

1. Go to 'Help' menu
2. Click on 'About GitHub Desktop'
3. Click on 'Check for updates'
3. See error

### Expected behavior
'spawn UNKNOWN'

### Screenshots
![Capture](https://user-images.githubusercontent.com/85484922/155277538-6cf64902-452a-452c-827e-446f59d9ce6c.PNG)

**Comment by steveward** [comment]
Thanks for the report @bistcuite. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
