### ISSUE TITLE
Add releases to desktop

### ISSUE THREAD

**Issue by fluentmoheshwar** [desktop/desktop#13979]
### Describe the feature or problem you’d like to solve
I need releases in desktop version of github.

### Proposed solution

Please share how this will it benefit Desktop and its users?
I don't need to go to github.com when i want to publish releases

### Additional context

Please include any other context, like screenshots or mockups, if applicable.

**Comment by steveward** [comment]
Thanks for the issue @biswasmoheshwar. At this time we don't have any plans of duplicating the release feature that's on github.com since there are a number of things that would be non-trivial to implement (like asset uploading). Creating tags in GitHub Desktop and then quickly jumping to the browser to create a release is likely going to be the best workflow for the time being. Thanks for using GitHub Desktop!

**Comment by fluentmoheshwar** [comment]
I think that's enough. thanks for your reply.On Feb 24, 2022 4:13 AM, Steve Ward ***@***.***> wrote:
Thanks for the issue @biswasmoheshwar. At this time we don't have any plans of duplicating the release feature that's on github.com since there are a number of things that would be non-trivial to implement (like asset uploading). Creating tags in GitHub Desktop and then quickly jumping to the browser to create a release is likely going to be the best workflow for the time being. Thanks for using GitHub Desktop!
