### ISSUE TITLE
Cloning a forked repo to local machine

### ISSUE THREAD

**Issue by chsheth** [desktop/desktop#13988]
Hi, I am cloning a forked repo to my local machine (windows) using GitHub Desktop. I also tried using git bash in VS code. GitHub Desktop errors out and git bash gives me an errors (unable to get local SSL certificate).

Can you please help?
Thanks

.

**Comment by steveward** [comment]
Thanks for the report @chsheth. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by chsheth** [comment]
Thanks for the note. I have the log attached here.

I have forked a repo, and used github desktop to git clone it to a location
on my local machine. The wizard just hangs without copying down the files.
When I try in Terminal in VS Code, it gives me an error message. When I use
the git extension in VS code, it gives me an SSL certificate error.

Thanks.

**Comment by steveward** [comment]
@chsheth unfortunately file uploads do not work via email reply -- you'll need to attach the log file directly in this issue. Thanks!

**Comment by chsheth** [comment]
Ok, I will do that.

**Comment by chsheth** [comment]
[2022-02-23.desktop.production.log](https://github.com/desktop/desktop/files/8133483/2022-02-23.desktop.production.log)

Do you see the log file now?

**Comment by steveward** [comment]
This is the only error I'm seeing:

```
stderr:
fatal: destination path 'C:\Users\csheth\OneDrive - AAA Club Alliance Inc\Documents\GitHub' already exists and is not an empty directory.
```

That error indicates you need to try cloning the repository to a different directory. Since you mentioned an SSL error I'm not sure if that's the actual issue. Can you share the specific SSL error you are seeing in the error message? Are you behind a proxy/firewall that could be interfering with your connection?

**Comment by chsheth** [comment]
Here is the SSL error when I try to clone a repo from github

![SSLerror](https://user-images.githubusercontent.com/38884348/155903973-ac7ba315-a08c-4736-b2f7-86bf47e2c26b.png)
.

**Comment by steveward** [comment]
Thanks for sharing that. Are you running any security/antivirus software on this machine? It'd also be helpful if you could run the following command and let me know the full output:

`git config -l --show-origin`

That should show if there are any configuration issues that could be causing this.

**Comment by chsheth** [comment]
Thanks for the help. I will close the ticket. I tried a few things and they didnt work, so I have downloaded the repo to complete my work. Thanks again!
