### ISSUE TITLE
Unable to discard changes on Windows using WSL

### ISSUE THREAD

**Issue by microbecode** [desktop/desktop#13981]
### Describe the bug

I have a repo on a Windows 11 WSL2 drive (\\wsl.localhost\Ubuntu\home\,.,). When I try to discard changes to a file, it gives me a popup "Failed to discard...Recycle Bin is set to delete items immediately".

Windows recycle bin is not set to delete files immediately, but on its default setting.

### Version & OS

- Windows 11
- GitHub Desktop 2.9.10
- WSL version 2

### Steps to reproduce the behavior

1. Use a repo in WSL
2. Try to discard changes to a file

### Expected behavior

Changes should be discarded.

### Actual behavior

I get a popup: 
![image](https://user-images.githubusercontent.com/20242241/155310759-62307a6f-bb0d-4839-bebd-cba40abaae84.png)

### Logs

No logs are generated

**Comment by sergiou87** [comment]
Thanks for your report! This is being tracked along with #13888 and there is a tentative fix in #13904, so I'm gonna close this in favor of those two.

**Comment by microbecode** [comment]
Thanks for the reply. I read both of those before posting, but as far as I could tell it's not the same thing. My application doesn't hang (#13888) and there already is the "don't show again" checkbox and unsure how retry would help (#13904). But I take your word for it, and will look forward to the next release with a fix

**Comment by sergiou87** [comment]
Sorry I didn't go into much detail! Basically, the API that we used to move items to the recycle bin changed and now throws an exception when moving items to the recycle bin is not possible (either because Recycle Bin is set to delete items immediately, or because you're on WSL where the Recycle Bin doesn't exist 😓 ).

That change is what caused #13888, and our initial fix was to catch that exception and display it to our users (the reason for this very issue you reported).

With #13904 we're replacing that error you get with a re-confirmation dialog, now making it very explicit to users that the changes will be discarded permanently, and with the ability to skip that re-confirmation dialog after the first time.

I hope that helps clarifying how #13904 will solve your issue 😄  Thank you for your patience and sorry about this!
