### ISSUE TITLE
Commit not updating after push commit button

### ISSUE THREAD

**Issue by Yacobh** [desktop/desktop#14062]
### Describe the bug
When push the button commit, the stashed changes remain in the tab `changes` I need to click on `history` then back to changes, and then back to `history` to fully update the flow

### Version & OS

Version 2.9.10 (x64)
MacOs Catalina 10.15.7

### Steps to reproduce the behavior

1. Open a branch
2. Make some changes 
3. Click on the button "commit to (the name of your branch)" 
4. The changes are not updated. it looks like no commit had been done

### Expected behavior

Write a clear and concise description of what you expected to happen.

### Actual behavior

Write a clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by DonniexSmurko** [comment]
I can read a lil of what it is but still quite don't understand

**Comment by DonniexSmurko** [comment]
I get a lil but still don't understand

**Comment by Yacobh** [comment]
When I click **commit to**
![Screen Shot 2022-03-03 at 08 52 36](https://user-images.githubusercontent.com/9374390/156559910-64735275-c703-4960-aef5-2970d288c568.png)
The interface blinks and nothing change (but you already commit). If you press again commit the following message appear
![Screen Shot 2022-03-03 at 08 53 11](https://user-images.githubusercontent.com/9374390/156559919-5f1e9b76-3f60-48f5-9379-963b01bd6bfd.png)
if you go to history, it looks like nothing was commited
![Screen Shot 2022-03-03 at 08 53 28](https://user-images.githubusercontent.com/9374390/156559925-0c59b0e0-5be7-4620-8b7c-e56d2905a086.png)
And just when you come back to changes, the interface is updated with the changes
![Screen Shot 2022-03-03 at 08 53 38](https://user-images.githubusercontent.com/9374390/156559928-a2dec7c7-af74-4f75-bb8f-0e4332bfba8a.png)
and you can see it in the history
![Screen Shot 2022-03-03 at 08 53 50](https://user-images.githubusercontent.com/9374390/156559929-72fb34e9-202f-4b7f-8833-5a12d69a81b5.png)

**Comment by steveward** [comment]
Thanks for the issue @Yacobh. Could you share the log file so that I could see if there is any further information there?

To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by Yacobh** [comment]
[2022-02-10.desktop.production.log](https://github.com/desktop/desktop/files/8180424/2022-02-10.desktop.production.log)

**Comment by steveward** [comment]
Thanks for the log. I'm not seeing anything there related to committing, just fetch errors. A couple of questions to debug this further:

- Is this happening in multiple repositories, or just this specific one?
- Are you consistently able tor reproduce this?

If you are able to consistently reproduce this it would be helpful to know what happens when you attempt to commit via the command line. If you aren't familiar with how to do that let me know and I can provide some specific steps. Let me know if you see any errors.

**Comment by Yacobh** [comment]
It looks like the update to version 2.9.11 fixed the problem, I'm not able to reproduce the error anymore
