### ISSUE TITLE
gitignore negations seem to be ignored

### ISSUE THREAD

**Issue by adrianbj** [desktop/desktop#14089]
### Describe the bug
Negation statements like `!/site/modules/Test/**` are ignored. The same statement works fine in Gitkraken and on the command line.

### Version & OS

Version 2.9.11 on MacOS

### Steps to reproduce the behavior

1. Add these rules:
```
/site/modules
!/site/modules/Test/**
```
2. Modify something in `/site/modules/Test/
3. Open GH Desktop to see changes

Note that the changes aren't shown because the negation for the Test subfolder is not working.

### Expected behavior

It should detect that the Test subfolder should NOT be ignored

### Actual behavior

It is ignored.

Thanks!

**Comment by niik** [comment]
Hi @adrianbj, thanks for reaching out!

We call upon `git status` to get the list of modified files which we then show to the user so I don't know why there'd be a difference between what you see in your own command line.

Testing your example myself I set it up like this

```
Markuss-MacBook-Pro:ignore-test markus$ tree
.
└── site
    └── modules
        ├── Test
        │   └── changed-file-in-test
        └── changed-file

3 directories, 2 files
```

Running `git status --ignored --untracked-files=all` here shows both files as ignored is expected behavior according to [the documentation](https://git-scm.com/docs/gitignore#_pattern_format) (emphasis mine)

> An optional prefix "!" which negates the pattern; any matching file excluded by a previous pattern will become included again. **It is not possible to re-include a file if a parent directory of that file is excluded**. Git doesn’t list excluded directories for performance reasons, so any patterns on contained files have no effect, no matter where they are defined. Put a backslash ("\") in front of the first "!" for patterns that begin with a literal "!", for example, "\!important!.txt".

Therefore I believe that in order to accomplish what you want you need to make sure the site, moduels, and Test directories aren't excluded (which is fine since Git doesn't track directories). Changing your ignore file to exclude the `Test` directory specifically seems to do what you want it to.

```
Markuss-MacBook-Pro:ignore-test markus$ cat .gitignore 
/site/modules/**
!/site/modules/Test
!/site/modules/Test/**
Markuss-MacBook-Pro:ignore-test markus$ git status --ignored --untracked-files=all
On branch master
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   .gitignore

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	site/modules/Test/changed-file-in-test

Ignored files:
  (use "git add -f <file>..." to include in what will be committed)
	site/modules/changed-file

no changes added to commit (use "git add" and/or "git commit -a")
```

Could you try with the approach I outlined above and see if there's still a discrepancy between GitHub Desktop and the command line?

**Comment by adrianbj** [comment]
Hi @niik - thank you so much for the thoughtful response. I am not sure what happened when I was comparing GH Desktop to Gitkraken and the command line, but today they all seemed to be behaving the same.

I finally got what I wanted with:

```
/site/modules/**
!/site/modules/Test/
!/site/modules/Test/**
```

Turns out the biggest issue was actually a typo to the subfolder (doh!) - I had modified the final part of the path for example purposes in this post.

So sorry to waste your time.
