### ISSUE TITLE
Donwload not works

### ISSUE THREAD

**Issue by GORECKIPL** [desktop/desktop#14096]
### Describe the bug
Write a clear and concise description of what the bug is.

### Version & OS
Version 2.9.11 (x64) Windows 10 
Open the 'About GitHub Desktop' menu to see the GitHub Desktop version. Also include what operating system you are using.

### Steps to reproduce the behavior

1. Go to 'clone repi from internet->  URL -> not exist in github. '

### Expected behavior

Write a clear and concise description of what you expected to happen.

### Actual behavior

Write a clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.
[2022-03-05.desktop.production.log](https://github.com/desktop/desktop/files/8190657/2022-03-05.desktop.production.log)

### Additional context

site<->Program - not works

**Comment by sergiou87** [comment]
Hi @GORECKIPL ! 👋 

Looking at the logs, it seems like you're writing the wrong URL in the Clone dialog. Try just writing `esp8266/ESPWebServer` like this:
![image](https://user-images.githubusercontent.com/1083228/157004709-6720871f-f84a-4886-b9d2-16b6a75cabe5.png)

That should work, otherwise let me know!
