### ISSUE TITLE
Attempting to publish branch on Windows breaks

### ISSUE THREAD

**Issue by Milo123459** [desktop/desktop#14094]
### Describe the bug
Write a clear and concise description of what the bug is.

### Version & OS

Version 2.9.11 and Windows 11

### Steps to reproduce the behavior

https://user-images.githubusercontent.com/50248166/156858142-99e7abc2-2365-4ad6-a5be-4e7f4ed5eae7.mp4

### Expected behavior

It doesn't say it cannot find bash

### Actual behavior

Says it cannot find bash

### Screenshots

https://user-images.githubusercontent.com/50248166/156858187-08d3910f-7d77-4fa0-a798-3863e8a8d3cc.mp4

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by niik** [comment]
Hey @Milo123459, thanks for reaching out! Are you by any chance using any Git hooks in your repository? This is an error I could see happening if you had a pre-push hook installed. The environment that GitHub Desktop runs Git in isn't the same as when run using a terminal so you may have to explicitly specify the path to the shell in your hook.

Could you also upload a log file from GitHub Desktop so that I could get some more information about this issue? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Explorer`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue. 

Thanks!

**Comment by Milo123459** [comment]
Hey,
There are Git hooks, yes. Here are the logs:
[2022-03-07.desktop.production.log](https://github.com/desktop/desktop/files/8200134/2022-03-07.desktop.production.log)

**Comment by niik** [comment]
Hey @Milo123459, thanks for the logs, they did confirm the issue being with hooks. I believe this is the same issue as https://github.com/desktop/desktop/issues/12562 so I'm going to close this in favor of that. Please take a look at the responses in that issue to see if any of the workaround could apply to you and subscribe to the issue for any updates.

**Comment by johannesschobel** [comment]
Dear @Milo123459 , have you found a solution for your issue?!
All the best and thanks for helping

**Comment by johannesschobel** [comment]
Dear @niik ,
do you have any more information on this issue or / and how to solve this? This is a major issue for developing sophisticated products (i.e., when you rely on `husky` or other git hooks) using GitHub Desktop. GH Desktop is the best client and i really (!) would like to stick to it.

All the best and thanks for helping,
Johannes
