### ISSUE TITLE
Add option to quickly merge upstream branch into current branch

### ISSUE THREAD

**Issue by uttiya10** [desktop/desktop#14145]
### Describe the feature or problem you’d like to solve

There are many times I want to merge the upstream default branch into my current branch, such as when working in a PR with conflicts. 

Github Desktop currently offers a quick way to merge the default branch, but this branch refers to your fork, instead of the upstream repo:
![image](https://user-images.githubusercontent.com/56562649/157763050-259c5bac-d8d5-44e3-9f6a-5b5337a1b156.png)

### Proposed solution

When the user's fork behaviour settings is "to contribute to the parent repository", this menu item should offer to merge from the upstream repo, instead of your fork.

**Comment by niik** [comment]
> When the user's fork behaviour settings is "to contribute to the parent repository", this menu item should offer to merge from the upstream repo, instead of your fork.

I think this is the behavior I would expect as well given that we offer to create a new branch based on the upstream default branch

<img width="414" alt="image" src="https://user-images.githubusercontent.com/634063/157836672-07ad29e8-6468-449b-8689-f430b87740b7.png">

I'm a bit worried about unintended side-effects of this change but I can't point to anything in particular right now. I think we should change the menu item to read `Update from upstream/[defaultbranch]` which probably means we ought to make the branch menu a bit wider (on Windows) but that seems like it's long overdue already given that we truncate static menu items.

Would you like to take a stab at implementing this so that we can give it a proper review and see if there's any merit to my concerns?

You should be able to rely on `findDefaultUpstreamBranch` to help you figure out what branch to update from

https://github.com/desktop/desktop/blob/3a5c4432c7587cbdca974df215abdeb371ac00cc/app/src/lib/branch.ts#L8-L18
