### ISSUE TITLE
Trouble installing Desktop

### ISSUE THREAD

**Issue by embisac10** [desktop/desktop#14171]
### Describe the feature or problem you’d like to solve

not able to install github desktop on my machine. I am a beginner and want to install github on my machine since joining. I have downloaded and tried x86 and it was not successful just tried that from your site just now and an error just after installing tells me not installed

### Proposed solution

Please share how this will it benefit Desktop and its users?

### Additional context

Please include any other context, like screenshots or mockups, if applicable.

**Comment by niik** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
