### ISSUE TITLE
Make "View on GitHub" point to the current branch or PR

### ISSUE THREAD

**Issue by ericboucher** [desktop/desktop#14224]
### Search for existing feature requests

- [X] I have searched the issue tracker and confirmed that I was unable to find existing issues for the feature I am requesting.

### The feature request

I feel like the main "View on GitHub" button on the right-hand side should open the current branch or the open PR if we are looking at a branch that has one.

It is a lot easier to go back to the main page of the repo if that's what we want than going to these two pages, which is a very common flow.

### Proposed solution

Simply re-routing the "View on GitHub" button to:

1. the PR page if the branch we are on has one
2. the code page for the branch if it does not

### Additional context

Happy to help contribute / QA. And thanks for the amazing work!

**Comment by tidy-dev** [comment]
@ericboucher Thank you for the suggestion! I will label this an enhancement. Tho, I do not see us changing the behavior of the long standing "View on GitHub" buttons for Repositories. The one on the right-hand side (am assuming you are referring to the context menu) mirrors the behavior of the "View on GitHub" in the "Repository" main menu. And therefore logically opens the repository on GitHub.
![Screen Shot 2022-03-23 at 9 36 42 AM](https://user-images.githubusercontent.com/75402236/159712405-8f45e35a-7dbd-46a4-ad5e-55acb94a7500.png)

Likely if this were to be implemented, it would be to add a similar feature to the "Branch" main menu and branch context menus as we all ready have one in the branch menu for pull requests. ("Show Pull Request" is same as "View Pull Request on Github"... which if this were taken up.. I would be happy if someone updated that verbiage to match :) )
![image](https://user-images.githubusercontent.com/75402236/159712593-4e4acc85-f61f-49fc-8ca4-f8b7d108a654.png)

**Comment by ericboucher** [comment]
@tidy-dev Thanks for the prompt response. I really like what you and @tsvetilian-ty came up with.

I was actually thinking about changing the right-hand-side "View on GitHub" behavior. I understand that it would be a big change, but I do feel like the current behavior is not what you would expect as a new user. One alternative could be to add the new button "View PR on GitHub" / "View Branch on GitHub" as another option in the right-hand-side panel?

Or we could continue with the blue-box that pops up with that flow:
- "Publish your branch" (blue) - already implemented

if published:
- "Create a Pull Request" (blue) -> add a second button or a just a note on the new shortcut to see the branch (#14231 )

if a pr exists:
- "View PR on GitHub" (grey), reuses the same box/position

**Comment by tidy-dev** [comment]
@ericboucher Thanks you for your suggestions and wanting to improve the app.

I believe now I understand that you were referring to:
![image](https://user-images.githubusercontent.com/75402236/160128406-57c7ac82-cd2b-4f85-8f78-ade65100716f.png)

Sorry for the misunderstanding.  I can see your point of view where since opening an editor or opening in terminal does open that repository to the current branch; and, that it may seem logical for the View the Repo on Github to do the same. However, editing the current branch is the primary action of an editor or terminal. There are numerous reasons to go to a repo on GitHub like reviewing the readme, view current issues, view current prs, see the history of file, see contributors.. etc. I don't believe we get many requests from users to view their branch on GitHub. Without having a huge number of requests or data to back up the most common reason a user goes from Desktop to their repository on GitHub, we would be hesitant to add a more narrow action to such a prominent area of the app.

Additionally, those blue areas are what we call the "Suggested Next Actions" and are based on a typical git flow of "Check out/Create a branch", "Commit some work", "Publish your branch", and "Create a pull request"; we would be hesitant to add things to them that are not inline with helping the user in this flow.

**Comment by ericboucher** [comment]
Seems reasonable :)

And no worries, I'll have the shortcut I need soon so I'm happy!

**Comment by Buddhaman617** [comment]
HELLO
