### ISSUE TITLE
PR relative dates are in the future

### ISSUE THREAD

**Issue by bdenhollander** [desktop/desktop#14238]
### Search existing issues

- [X] I have searched the issue tracker and confirmed that I was unable to find existing issues for the problem I am experiencing.

### The problem

Relative dates on the PR tab are in the future. Instead of `in x days` and `tomorrow` it should `x days ago` and `yesterday`.

### Release version

2.9.12

### Operating system

Windows 10

### Screenshots

![image](https://user-images.githubusercontent.com/44237618/160010770-91704af4-8fa0-46f4-b8b3-b2e4252cccd5.png)

**Comment by uttiya10** [comment]
The root cause seems to be in the relative time formatter:
https://github.com/desktop/desktop/blob/e116214d96e14f8613a5147a5593c0d5e43d0f74/app/src/lib/format-relative.ts#L17-L20

The ternary operator used in ` const sign` seems to be flipped, resulting in -1 for positive numbers and 1 for negative numbers.
Unfortunately, alot of other code now relies on this logic, so fixing it will cause more formatting issues.

Solution 1 (Best):
Fix the logic and update all use cases of this function.

Solution 2:
Just update the `pull-request-list-item.tsx` file as shown:
```diff
--- a/app/src/ui/branches/pull-request-list-item.tsx
+++ b/app/src/ui/branches/pull-request-list-item.tsx
@@ -76,7 +76,7 @@ export class PullRequestListItem extends React.Component<
       return undefined
     }

-    const timeAgo = formatRelative(this.props.created.getTime() - Date.now())
+    const timeAgo = formatRelative(Date.now() - this.props.created.getTime())
     const subtitle = `#${this.props.number} opened ${timeAgo} by ${this.props.author}`

     return this.props.draft ? `${subtitle} <E2><80><A2> Draft` : subtitle
```

**Comment by KendallDoesCoding** [comment]
This can also be a issue as your computer time is wrong, so please check that.
