### ISSUE TITLE
Undoing a commit doesn't delete any new tag associated with it

### ISSUE THREAD

**Issue by RecursiveVision** [desktop/desktop#14252]
### Search existing issues

- [X] I have searched the issue tracker and confirmed that I was unable to find existing issues for the problem I am experiencing.

### The problem

I created a commit and added the tag "Release-2.0" to it.

I then right-clicked the commit in the menu and hit "Undo commit", then deleted all the file changes.

The tag "Release-2.0", however, persisted and I still had a prompt to push the tag to the online repository which I could not get rid of, despite the tag not being on any commits.

### Release version

Version 2.9.12 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Create a commit.
2. Add a new tag to it.
3. Right-click the commit and undo the commit.
4. The tag persists.

### Log files

Unfortunately the logs were deleted.

**Comment by steveward** [comment]
Thanks for the issue @RecursiveVision. This is actually the expected behavior -- an annotated tag is stored as a separate object in the Git database. 

At this time we don't have a tag list that shows all tags available for deletion, but this is something that has been brought up in https://github.com/desktop/desktop/issues/4829. You can use `git tag -d <tagname>` from the command line to delete the tag as a workaround. I hope that helps!

**Comment by RecursiveVision** [comment]
@steveward I see! Well, I look forward to that new feature then.

Cloning the repository again fixed it - I'll just have to be more careful for now.
