### ISSUE TITLE
creating a new repo from an existing directory is confusing and annoying

### ISSUE THREAD

**Issue by skeddles** [desktop/desktop#14318]
### The feature request

i always end up with /repo/repo

### Proposed solution

hire a ux consultant

**Comment by niik** [comment]
This issue is not aligned with the standards outlined in our [Code Of Conduct](https://github.com/desktop/desktop/blob/development/CODE_OF_CONDUCT.md). Please be respectful when communicating in this repository. You may consider this a warning.

I will close this in favor of https://github.com/desktop/desktop/issues/11413 which I believe is referencing the same underlying source of confusion.

**Comment by ikaris28** [comment]
> ### The feature request
> i always end up with /repo/repo
> 
> ### Proposed solution
> hire a ux consultant
> 
> ### Additional context
> _No response_

**Comment by ikaris28** [comment]
he stole

**Comment by ikaris28** [comment]
> he stole

my data
