### ISSUE TITLE
Issue in push the code to repository 

### ISSUE THREAD

**Issue by AB013BX** [desktop/desktop#14330]
### The problem

Hi Team,

I am not able to push the code to repository from github IDE.

when i try to push the code from terminal getting time out issue.

Please provide your support to resolve the issue.

Regards,
Vijay

### Release version

version 2.9.12

### Operating system

Windows 10

**Comment by steveward** [comment]
Thanks for the report @AB013BX. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by AB013BX** [comment]
Hi Team,

Please find the attached log file.

Regards,
Vijay

**Comment by steveward** [comment]
@AB013BX unfortunately log files do not upload as attachment when sent via email replies. You will need to add the log file directly to the issue.

**Comment by AB013BX** [comment]
Hi Team,

I have raise new incident regarding the issue and attached all the details along with log file and screen shot.

For your reference incident Id  Not able to push the code to repository #14359

Hope it will be helpful to resolve the issue.

Regards,
Vijay
