### ISSUE TITLE
Potentially Unsafe

### ISSUE THREAD

**Issue by jivstudio** [desktop/desktop#14358]
### The problem

Cannot set "Trust Repository" with github Desktop v2.9.14. Clicking on the button does nothing. 

### Release version

2.9.14

### Operating system

Windows 10

**Comment by jjunno** [comment]
Came here to this. W10, Client 2.9.14 x64. The repository is located on in \\wsl$, the button does nothing. Tried running as administrator with no effect.

**Comment by jjunno** [comment]
@juliasummersmtb see https://github.com/desktop/desktop/issues/14336#issuecomment-1098490973

**Comment by bulentAkgul** [comment]
Same here

**Comment by arkayenro** [comment]
same thing.  it also marked every single repository as unsafe so its pretty much broken

**Comment by niik** [comment]
This issue is being tracked in https://github.com/desktop/desktop/issues/14336. Please subscribe to that to follow along. The [latest update](https://github.com/desktop/desktop/issues/14336#issuecomment-1098490973) as of writing this is that WSL and NAS (or path beginning with `//`) will not work. This is due to a security fix in Git for Windows and we're working with that team to come up with a permanent fix. In the meantime there are links to the installer for an older version of Desktop here: https://github.com/desktop/desktop/issues/14336#issuecomment-1098309322.
