### ISSUE TITLE
Trust repository button does not work

### ISSUE THREAD

**Issue by verboisRDL** [desktop/desktop#14356]
### The problem

I have a Ubuntu Server (Microk8s) dev server from which I execute my code while developping. It's always been working until today (is it the update?). But I just got this error message : 

The Git repository at //192.168.2.7/gesprod_frank/ appears to be owned by another user on your machine. Adding untrusted repositories may automatically execute files in the repository.

If you trust the owner of the directory you can add an exception for this directory in order to continue."

So I clicked the "Trust repository..." button. The ... must mean there will be further options. But the button doesn't do anything.

I'm stuck.

### Release version

2.9.14 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

Clone your repository on a network share.
Try to connect to that network drive

### Screenshots

![image](https://user-images.githubusercontent.com/53010302/163272131-44aa5324-7573-4c2a-8754-02e3e3cf690b.png)

**Comment by bompus** [comment]
Please see https://github.com/desktop/desktop/issues/14336#issuecomment-1098490973

**Comment by apudiu** [comment]
I'm having same issue,
Repo in WSL (connected via mapped network drive)
Windows 10 x64

**Comment by niik** [comment]
This issue is being tracked in https://github.com/desktop/desktop/issues/14336. Please subscribe to that to follow along. The [latest update](https://github.com/desktop/desktop/issues/14336#issuecomment-1098490973) as of writing this is that WSL and NAS (or path beginning with `//`) will not work. This is due to a security fix in Git for Windows and we're working with that team to come up with a permanent fix. In the meantime there are links to the installer for an older version of Desktop here: https://github.com/desktop/desktop/issues/14336#issuecomment-1098309322.
