### ISSUE TITLE
Error opening git repository on GIT desktop

### ISSUE THREAD

**Issue by monikakaro** [desktop/desktop#14363]
### The problem

Hello,

After latest git desktop update it showing this error and trust repository button do nothing. 
![image](https://user-images.githubusercontent.com/71114989/163375287-7056a088-3e17-494b-8bb3-fa7721aca204.png)

![image](https://user-images.githubusercontent.com/71114989/163376847-263346ca-f325-4cac-bc1d-c99b0af4efc6.png)

### Release version

Version 2.9.14 (x64)

### Operating system

Windows 10

**Comment by niik** [comment]
This issue is being tracked in https://github.com/desktop/desktop/issues/14336. Please subscribe to that to follow along. The [latest update](https://github.com/desktop/desktop/issues/14336#issuecomment-1098490973) as of writing this is that WSL and NAS (or path beginning with `//`) will not work. This is due to a security fix in Git for Windows and we're working with that team to come up with a permanent fix. In the meantime there are links to the installer for an older version of Desktop here: https://github.com/desktop/desktop/issues/14336#issuecomment-1098309322.
