### ISSUE TITLE
Exception for untrusted repository

### ISSUE THREAD

**Issue by jkirkby-cqs** [desktop/desktop#14362]
### The problem

When adding a local repository that is owned by another user, the hyperlink to add an exception does not perform any action.

### Release version

Version 2.9.14 (x64)

### Operating system

Windows 10 Enterprise

### Steps to reproduce the behavior

1.Go to 'Add' under Current repository
2.Click on 'Add existing repository
3.Choose an existing local repository that is owned by another user
4. Click 'add an exception for this directory'

### Screenshots

![image](https://user-images.githubusercontent.com/93606414/163372005-af0c9a7f-ca40-4a0d-a5cd-07f73fb9fbdf.png)

**Comment by niik** [comment]
This issue is being tracked in https://github.com/desktop/desktop/issues/14336. Please subscribe to that to follow along. The [latest update](https://github.com/desktop/desktop/issues/14336#issuecomment-1098490973) as of writing this is that WSL and NAS (or path beginning with `//`) will not work. This is due to a security fix in Git for Windows and we're working with that team to come up with a permanent fix. In the meantime there are links to the installer for an older version of Desktop here: https://github.com/desktop/desktop/issues/14336#issuecomment-1098309322.
