### ISSUE TITLE
Potentially unsafe

### ISSUE THREAD

**Issue by leonkllr0** [desktop/desktop#14361]
### The problem

There are problems when working on WSL and Github latest version. So you cannot add repository as trusted if you link your repository directly inside WSL.

### Release version

Version 2.9.14 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

- Create any repository inside WSL, for example: \\wsl$\Ubuntu-20.04\home\repository-name
- Try to add repository to the Github Desktop (you will see the message: The Git repository at `\\wsl$\Ubuntu-20.04\home\repository-name` appears to be owned by another user on your machine. Adding... If you trust the owner of the directory you can add an exception for this directory in order to continue. 
- And then button "add an exception for this directory" doesn't do anything.

**Comment by niik** [comment]
This issue is being tracked in https://github.com/desktop/desktop/issues/14336. Please subscribe to that to follow along. The [latest update](https://github.com/desktop/desktop/issues/14336#issuecomment-1098490973) as of writing this is that WSL and NAS (or path beginning with `//`) will not work. This is due to a security fix in Git for Windows and we're working with that team to come up with a permanent fix. In the meantime there are links to the installer for an older version of Desktop here: https://github.com/desktop/desktop/issues/14336#issuecomment-1098309322.
