### ISSUE TITLE
Unable to clone repo

### ISSUE THREAD

**Issue by rwlpf** [desktop/desktop#14360]
### The problem

after update of git hub desktop attempted to pull repo got error message.  So asked to clone repo into empty folder, downloaded, finished, error message "D:\GitHubRepos\Resources isn't a Git repository."

### Release version

 2.9.14 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

see above, delete local copy of repo several times same error message

**Comment by bombitmanbomb** [comment]
Same issue here, After updating all of my repo's are listed as not being a Git Repository.

**Comment by niik** [comment]
Thanks for the report! Could you upload a log file from GitHub Desktop so that I could get some more information about this issue? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue. Thanks!

**Comment by hoggatt** [comment]
@niik I am having the same issue. In my case (and I'm guessing OP's case), I'm trying to clone a repo into an "untrusted" folder (ie, a folder I do not own). This gives me an error and doesn't show the project in the UI even though the project is cloned on my system. 

**Workaround**: If I try to 'add an existing repository', I get a popup that asks me to add an exception:
![image](https://user-images.githubusercontent.com/37279082/164056718-3e0e2300-d692-45f4-b43c-cff8cd3180ad.png)
This ends up working, but is a huge hassle and not the indented way of cloning a repo. 

**Fix**: it would be nice if we could trust the parent folder we are cloning all sorts of projects into instead of having to trust all projects independently. For some reason doing this on from the command line is not working for me but I'm guessing whatever you guys implemented for v 2.9.14 will work to trust the parent folder. Maybe implement something similar to VS Code that lets you trust the parent's directory.

**Comment by niik** [comment]
Hey @lhoggatt17, thanks for reaching out. The issue of clone failing was fixed in https://github.com/desktop/desktop/pull/14374 and has been released to our [beta channel](https://desktop.github.com/beta/). We're planning on shipping an updated version to our production channel this week but feel free to download our beta channel to work around the problem right now.

We're unfortunately limited here by what the Git project chooses to implement. I know they've added the ability to disable the unsafe detection entirely by adding `*` to the `safe.directory` but we currently don't surface that in Desktop. They have not implemented any way to trust the parent directory yet.

```
git config --global --add safe.directory "*"
```

**Comment by steveward** [comment]
@rwlpf as we haven't heard back from you I am going to close this issue out. If you're still having issues let us know and we can investigate further.
