### ISSUE TITLE
Github desktop has stopped working for WSL2

### ISSUE THREAD

**Issue by silviobernardo** [desktop/desktop#14370]
### The problem

The applications has stopped working properly with WSL (Windows Subsystem for Linux). Maybe for it be an mapped directory.
This issue/bug has started to happening just after I updated it to the latest version.

I had to delete the repository and I could not anymore to clone ANY git repository to a WSL folder. But if I try to close those repository to a ordinary/phisical windows folder it runs great. That means the problem is happing just with WSL.

### Release version

2.9.14 (x64)

### Operating system

Windows 11

**Comment by tidy-dev** [comment]
This issue is being tracked in https://github.com/desktop/desktop/issues/14336. Please subscribe to that to follow along. The https://github.com/desktop/desktop/issues/14336#issuecomment-1098490973 as of writing this is that WSL and NAS (or path beginning with //) will not work. This is due to a security fix in Git for Windows and we're working with that team to come up with a permanent fix. In the meantime there are links to the installer for an older version of Desktop here: https://github.com/desktop/desktop/issues/14336#issuecomment-1098309322.
