### ISSUE TITLE
Cannot trust directory

### ISSUE THREAD

**Issue by Francismori7** [desktop/desktop#14378]
### The problem

Cannot trust directory

### Release version

2.9.14

### Operating system

W10

### Screenshots

![image](https://user-images.githubusercontent.com/520647/163463379-6af95bf2-74eb-4e5f-909e-c6bcb7199fe9.png)

### Additional context

Blue button does nothing

**Comment by steveward** [comment]
This issue is being tracked in https://github.com/desktop/desktop/issues/14336. Please subscribe to that to follow along. This is due to a security fix in Git for Windows and we're working with that team to come up with a permanent fix. In the meantime there are links to the installer for an older version of Desktop here: https://github.com/desktop/desktop/issues/14336#issuecomment-1098309322.
