### ISSUE TITLE
Trust Repositiry not working

### ISSUE THREAD

**Issue by robtoll** [desktop/desktop#14375]
### The problem

Github desktop suddenly asked me today if I trust a potentially unsafe repo.
The repo is located on a mapped drive and may have different permissions.
There are 2 options displayed in Github Desktop. "Trust Repository" or "Remove".
The "Trust Repository" button doesn't do anything, so now I can;t use this software.
I tried rebooting, and running as admin. No luck.

### Release version

2.9.14 x64

### Operating system

win10

### Steps to reproduce the behavior

add a rapo from a mapped drive or network location. You may need to have different permissions on the mapped drive or network location to replicate this bug.

### Screenshots

![ghd](https://user-images.githubusercontent.com/16472960/163438106-a063cf2b-19b3-4f48-aeab-da99e6e8adbe.jpg)

**Comment by tidy-dev** [comment]
This issue is being tracked in https://github.com/desktop/desktop/issues/14336. Please subscribe to that to follow along. The [latest update](https://github.com/desktop/desktop/issues/14336#issuecomment-1098490973) as of writing this is that WSL and NAS (or path beginning with `//`) will not work. This is due to a security fix in Git for Windows and we're working with that team to come up with a permanent fix. In the meantime there are links to the installer for an older version of Desktop here: https://github.com/desktop/desktop/issues/14336#issuecomment-1098309322.

**Comment by robtoll** [comment]
This is very well appreciated, especially the quick response.
My apologies for opening a new issue
