### ISSUE TITLE
On updating GitHub Desktop (Windows), "[local repo] is potentially unsafe" is new message

### ISSUE THREAD

**Issue by dmehta** [desktop/desktop#14373]
### The problem

On updating GitHub Desktop (Windows) to Version 2.9.14 (x64), after restarting GitHub Desktop, I immediately received the following message: "[local repo] is potentially unsafe". This is a new message that I have never encountered before and I'm not sure what triggered it.

I click on "Trust repository..." button but no other window, screen, or pop-up comes up. Please advise. I cannot commit nor see the repo.

### Release version

Version 2.9.14 (x64)

### Operating system

Windows 10.0.19044 Build 19044

### Steps to reproduce the behavior

1. Open repo that is on a network folder
2. Receive message: "[local repo] is potentially unsafe"
3. Clicking "Trust repository..." does not yield a follow-up dialog.

### Screenshots

![image](https://user-images.githubusercontent.com/235864/163429185-efc5d414-dbde-4bbf-91e8-42d78305d63d.png)

**Comment by niik** [comment]
This issue is being tracked in https://github.com/desktop/desktop/issues/14336. Please subscribe to that to follow along. The [latest update](https://github.com/desktop/desktop/issues/14336#issuecomment-1098490973) as of writing this is that WSL and NAS (or path beginning with `//`) will not work. This is due to a security fix in Git for Windows and we're working with that team to come up with a permanent fix. In the meantime there are links to the installer for an older version of Desktop here: https://github.com/desktop/desktop/issues/14336#issuecomment-1098309322.
