### ISSUE TITLE
No longer able to "Add existing repository..."

### ISSUE THREAD

**Issue by Alberto-Beguerie-RT** [desktop/desktop#14377]
### The problem

I tried to add an existing repository using the "Add" > "Add existing repository...". 

I pressed the "Choose..." button and selected the existing repository path. The path string updated in the "Local path" field; however, the "Add repository" button never enabled itself and the following warning message popped up: 

"The Git repository at <path to repository> appears to be owned by another user on your machine. Adding untrusted repositories may automatically execute files in the repository. If you trust the owner of the directory you can add an exception for this directory in order to continue."

There is a link on the "add an exception for this repository" text; however, it doesn't work either.

For clarity, the existing repository I'm trying to add is trusted and worked fine before the latest update. 

Thank you in advance!

### Release version

Version 2.9.14 (x64)

### Operating system

Windows 10

**Comment by steveward** [comment]
This issue is being tracked in https://github.com/desktop/desktop/issues/14336. Please subscribe to that to follow along.  This is due to a security fix in Git for Windows and we're working with that team to come up with a permanent fix. In the meantime there are links to the installer for an older version of Desktop here: https://github.com/desktop/desktop/issues/14336#issuecomment-1098309322.
