### ISSUE TITLE
Cannot Add Local WSL2 Repository on Windows 10

### ISSUE THREAD

**Issue by mikecummings10** [desktop/desktop#14371]
### The problem

As of the latest release (Version 2.9.14 (x64)), on Windows 10 Pro (10.0.19043 Build 19043), I am no longer able to add a local WSL2 repository to GitHub Desktop. Attempting to add the repository results in the following message: 

> The Git repository at '//wsl$/Ubutunu-20.03/home/...' appears to be owned by another user on your machine. Adding untrusted repositories may automatically execute file in the repository.
> 
> If you trust the owner of the directory you can add an exception for this directory in order to continue.

Clicking the "add an exception for this directory" link does nothing and the "Add repository" button is disabled.

This previously worked without issue.

### Release version

2.9.14 (x64)

### Operating system

Windows 10 Pro (10.0.19043 Build 19043)

### Steps to reproduce the behavior

1. Click File > Add local repository...
2. Navigate to any repository beginning with path "\\wsl$\Ubuntu-20.04\"
3. Cannot proceed

### Additional context

Have also tried running GitHub Desktop as an administrator.

**Comment by mikecummings10** [comment]
May be related to https://stackoverflow.com/questions/71849415/cannot-add-parent-directory-to-safe-directory-on-git

**Comment by tidy-dev** [comment]
This issue is being tracked in https://github.com/desktop/desktop/issues/14336. Please subscribe to that to follow along. The https://github.com/desktop/desktop/issues/14336#issuecomment-1098490973 as of writing this is that WSL and NAS (or path beginning with //) will not work. This is due to a security fix in Git for Windows and we're working with that team to come up with a permanent fix. In the meantime there are links to the installer for an older version of Desktop here: https://github.com/desktop/desktop/issues/14336#issuecomment-1098309322.
