### ISSUE TITLE
Can't find "Repo"

### ISSUE THREAD

**Issue by soulagent** [desktop/desktop#14390]
### The problem

Github desktop can't seem to find the repo. Searched up solutions and tried to remove the GithubDesktop folder in %appdata%, even doing a clean reinstall. Then tried to pull my repo and for a split second, it seemed to work, but it then said it can't find the repo.

Even tried locating said folder that was just cloned but still could not "find" the repo.
Everything was working just fine yesterday. This seemed to affect my other repos as well.

Attempting to create a fresh new repo from Github Desktop also produces the same issue.

### Release version

v 2.9.14 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

Old Repo
1. Clean install of Github Desktop
2. Sign in
3. Attempt to clone any repo
4. After cloning, observe the error.

### Log files

[2022-04-16.desktop.production.log](https://github.com/desktop/desktop/files/8500171/2022-04-16.desktop.production.log)

### Screenshots

![image](https://user-images.githubusercontent.com/18515679/163681133-e4dd98fb-bf2e-42ab-9742-30ded53636d2.png)

**Comment by soulagent** [comment]
Removed repo and tried installing in another drive and this time log seemed to be different
[2022-04-16.desktop.production.log](https://github.com/desktop/desktop/files/8500193/2022-04-16.desktop.production.log)
?

**Comment by marticliment** [comment]
Having this issue too on the latest beta, after the issue #14336 being fixed.

**Comment by niik** [comment]
This issue is being tracked in https://github.com/desktop/desktop/issues/14336. Please subscribe to that to follow along. The [latest update](https://github.com/desktop/desktop/issues/14336#issuecomment-1099881641) as of writing this is that we've shipped an update to our [beta channel](https://desktop.github.com/beta/) which solves the issue of WSL and NAS (or path beginning with `//`) not working. We're planning on shipping an updated version to our production channel this week.
