### ISSUE TITLE
'project title' is potentially unsafe github desktop

### ISSUE THREAD

**Issue by jacobghunter** [desktop/desktop#14404]
### The problem

Something happened to where my GitHub desktop doesn't allow me to open any of my previous projects because they are 'potentially unsafe' and they 'appear to be owned by another user on my machine.' I am on windows using WSL 2 and I don't have another user on my computer or another GitHub account. I have tried git config --global --add safe.directory 'directory', which actually added the project folders to the safe directory, but GitHub desktop still doesn't work. The 'Trust Repository' button also doesn't seem to do anything, and after uninstalling and reinstalling I have the same issue.

### Release version

2.9.14 (x64)

### Operating system

Windows 10

### Log files

[2022-04-15.desktop.production.log](https://github.com/desktop/desktop/files/8508523/2022-04-15.desktop.production.log)

### Screenshots

![image](https://user-images.githubusercontent.com/98200224/163887887-9ee8f678-3730-474f-8178-7cfcfa912f11.png)

![image](https://user-images.githubusercontent.com/98200224/163887907-596ba4e5-b1d0-4171-ba9b-d88420c26767.png)

**Comment by tsvetilian-ty** [comment]
@jacobghunter try out the latest version in the [beta channel](https://desktop.github.com/beta/). Here is a comment that gives move information on the issue: https://github.com/desktop/desktop/issues/14336#issuecomment-1099881641

**Comment by jacobghunter** [comment]
@tsvetilian-ty That worked, thank you so much!

**Comment by niik** [comment]
As @tsvetilian-ty already said, this issue is being tracked in https://github.com/desktop/desktop/issues/14336. Please subscribe to that to follow along. The [latest update](https://github.com/desktop/desktop/issues/14336#issuecomment-1099881641) as of writing this is that we've shipped an update to our [beta channel](https://desktop.github.com/beta/) which solves the issue of WSL and NAS (or path beginning with `//`) not working. We're planning on shipping an updated version to our production channel this week. / /
