### ISSUE TITLE
Add possibility to delete a tag.

### ISSUE THREAD

**Issue by fabiocaccamo** [desktop/desktop#14409]
### The feature request

It would be very useful to have the possibility to delete a tag and push it.

### Proposed solution

This operation could be added to the right-click contextual menu of commits that are tagged.

### Additional context

This is what I actually do using terminal because GitHub Desktop doesn't support it (yet).

```bash
git tag -d 0.1.0
git push origin :0.1.0
```

**Comment by niik** [comment]
Hey @fabiocaccamo, thanks for reaching out! As you've already noticed GitHub Desktop does not support deleting tags that have been pushed to the remote. The reasoning behind this decision is outlined in [this comment](https://github.com/desktop/desktop/issues/9938#issuecomment-638779503). I'm going to close this issue out since this request is already captured in #9938, please subscribe to that issue to follow along with any development. Thanks for using GitHub Desktop!
