### ISSUE TITLE
Cannot add Repo from Network Drive

### ISSUE THREAD

**Issue by hungdx6** [desktop/desktop#14416]
### The problem

Dear contributors,

Since last week, my Github Desktop has didn't allow me to add repo from network drive and ask me to "add an exception for this directory". I cloned a repo to network drive and it cloned well but after that, the repo has been removed from Github Desktop. Please help me

### Release version

2.9.14

### Operating system

Windows 10

### Screenshots

![image](https://user-images.githubusercontent.com/54889631/164169415-2f0b3d0d-243f-453d-a91c-101dd2220e83.png)

I clicked "add an exception for this directory" but it did nothing.

**Comment by niik** [comment]
This issue is being tracked in https://github.com/desktop/desktop/issues/14336. Please subscribe to that to follow along. The [latest update](https://github.com/desktop/desktop/issues/14336#issuecomment-1099881641) as of writing this is that we've shipped an update to our [beta channel](https://desktop.github.com/beta/) which solves the issue of WSL and NAS (or path beginning with `//`) not working. We're planning on shipping an updated version to our production channel this week.

**Comment by hungdx6** [comment]
Beta version fixed it
