### ISSUE TITLE
Potentially unsafe when owner is 'Everyone'

### ISSUE THREAD

**Issue by TheByKotik** [desktop/desktop#14425]
### The problem

Related to https://github.com/desktop/desktop/pull/14344?
It's probably a git issue

When owner of a directory is 'Everyone' it is still marked as 'potentially unsafe'

### Release version

2.9.15 (x64)

### Operating system

Windows 10 Pro 21H2 19044.1645

### Log files

[2022-04-21.desktop.production.log](https://github.com/desktop/desktop/files/8529563/2022-04-21.desktop.production.log)

### Screenshots

![bug](https://user-images.githubusercontent.com/40791562/164422414-d41da7b3-5311-43f0-8833-a1af451be84f.png)
![image](https://user-images.githubusercontent.com/40791562/164423120-39029bee-5dc3-4465-8dcb-c3afb8a820a6.png)

**Comment by tsvetilian-ty** [comment]
Hi @TheByKotik you are right. It is related to the implementation from git, but it's not an issue! At the moment, git checks if the owner matches the current user and by design **doesn't** consider Windows User Groups (Everyone is a user group).

You can check out this issue: https://github.com/git-for-windows/git/issues/3798

**Comment by tidy-dev** [comment]
As @tsvetilian-ty pointed out, that git is checking against the individual user and therefore you must mark it as safe if you trust the user group "Everyone". :) (The other alternative is to put your repository in a folder that only your user is owner of)
