### ISSUE TITLE
Reconcile divergent branches

### ISSUE THREAD

**Issue by aenzor** [desktop/desktop#14423]
### The problem

hint: You have divergent branches and need to specify how to reconcile them.
hint: You can do so by running one of the following commands sometime before
hint: your next pull:
hint: 
hint:   git config pull.rebase false  # merge
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint: 
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
fatal: Need to specify how to reconcile divergent branches.

I have no idea how to do this on github desktop app

### Release version

2.9.15

### Operating system

windows 10

### Steps to reproduce the behavior

try to pull origin

**Comment by steveward** [comment]
@aenzor This is a message that started showing up in Git v2.27 in the command line. You can choose one of the options mentioned in the `hints` to stop it from occurring. The `git config pull.rebase false` is the default setting. You can read more about the settings in [the official Git docs](https://git-scm.com/docs/git-pull). GitHub Desktop will respect your choice in the global `.gitconfig`.

**Comment by carriontrooper** [comment]
> @aenzor This is a message that started showing up in Git v2.27 in the command line. You can choose one of the options mentioned in the `hints` to stop it from occurring. The `git config pull.rebase false` is the default setting. You can read more about the settings in [the official Git docs](https://git-scm.com/docs/git-pull). GitHub Desktop will respect your choice in the global `.gitconfig`.

How do I do this, I'm having the same problem as well. If possible, using the Github Desktop program, since it's what I got.

**Comment by ConorZAM** [comment]
I had this issue just now and I managed to get around it by clicking undo on the push I'd made and then pulling origin. After that I could push my commit again and everything worked fine. Usually GitHub desktop won't let me push a commit if there are changes to fetch first, I think the divergence came about because it let me do that somehow.

**Comment by techgique** [comment]
In case anyone is still working with a version without the fix merged, the undo approach worked with a single commit, but it might be a mess if there is more than one.

Recommend just editing the `~/.gitconfig` file and adding this to the end of the file rather than having to install the `git` command line tools for users who won't otherwise use the CLI. Also avoids installing Xcode on MacOS.

```
[pull]
    rebase = false
```

**Comment by KerimTarikQE2282** [comment]
i just used the force flag wouldnt that be a solution? and then fix the issues when the conflict happens, although I wouldn't recommend this for larger projects
