### ISSUE TITLE
Github Desktop won't save my username and app password

### ISSUE THREAD

**Issue by mmmgalea** [desktop/desktop#14432]
Hello,

I don't know whether this is an issue or something that I need to do but Github Desktop keeps prompting me for my username and app password every time I fetch or push after a few hours of inactivity - is this normal?

**Comment by steveward** [comment]
@mmmgalea thanks for the report -- that definitely shouldn't be happening. Is this happening with a standard GitHub account, and not a different service like GitLab?

The log file should show some information about invalid credentials, so it would be helpful if you could upload a log file from a day this occurred so that we could take a look. To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.

**Comment by steveward** [comment]
@mmmgalea as we haven't heard back from you I am going to close this issue out. Let us know if you are still having problems and we can investigate further.

**Comment by mmmgalea** [comment]
Hi Steve,
thanks for the speedy reply.
As far as I know, my account is a standard GitHub account. Not sure if
you can see anything on your side that displays otherwise.
I have attached the latest version of my Github desktop log.
Thanks and Regards,
Matt

----- Original Message -----

**Comment by steveward** [comment]
@mmmgalea unfortunately you will need to attach the log file directly in an issue comment -- email attachments will not make it through. Thanks.

**Comment by mmmgalea** [comment]
Hi Steve,
here is the log file:

[2022-10-11.desktop.production.log](https://github.com/desktop/desktop/files/9759636/2022-10-11.desktop.production.log)

Regards,

Matt

**Comment by sergiou87** [comment]
Hopefully this is already fixed with the latest auth-related changes #18700 

Otherwise let us know and we will reopen it!
