### ISSUE TITLE
Unverified Commits

### ISSUE THREAD

**Issue by azadkarakus** [desktop/desktop#14434]
### The problem

Even though I created the GPG key, the commits I made through the GitHub Desktop application are seen as unverified.

### Release version

Version 2.9.15 (x64)

### Operating system

Windows 10

**Comment by steveward** [comment]
@azadkarakus thanks for the issue. GPG signing should work in GitHub Desktop even though we don't officially support it --[ these are the steps](https://gist.github.com/xavierfoucrier/c156027fcc6ae23bcee1204199f177da) I usually point users to who are looking to get it working.  Can you verify things are setup correctly? I'll also try and test this out since we've had one other report of this recently (https://github.com/desktop/desktop/issues/14357).

For reference we are tracking GPG support in https://github.com/desktop/desktop/issues/78.

**Comment by steveward** [comment]
@azadkarakus as we haven't heard back from you I am going to close this issue out. If you're still having issues let us know and we can investigate further.

**Comment by azadkarakus** [comment]
Unfortunately the problem still exists.

**Comment by steveward** [comment]
@azadkarakus I recently tested this and commit signing worked as expected -- have you verified that you have told Git about the correct GPG key?
