### ISSUE TITLE
Eslint v7 to v8

### ISSUE THREAD

**Issue by danny007in** [desktop/desktop#14444]
### The feature request

I can Create PR

### Proposed solution

For eslint up-to-date

**Comment by sergiou87** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
