### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by Indranil-sawant** [desktop/desktop#14445]
### The problem

the https protocol is not supported

### Release version

sds

### Operating system

wsl

**Comment by steveward** [comment]
Thanks for the report @Indranil-sawant. Could you please fill out the issue form so that we could have further information?

Could you also upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by steveward** [comment]
@Indranil-sawant as we haven't heard back from you I am going to close this issue out. Let us know if you are still having problems and we can investigate further.
