### ISSUE TITLE
Files commited with change permissions are commited but not published

### ISSUE THREAD

**Issue by adharsri** [desktop/desktop#14449]
### The problem

If we change a file permission using 
`git update-index --chmod=+x <filename>`
the change is detected and can be committed. However, on pushing it, the same is not reflected in the branch it's pushed to.

### Release version

2.9.15 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Change any file permission using `git update-index --chmod=+x <filename>`
2. Stage and commit the file.
3. Push the changes

Expected: The files should appear in the target branch with updated permissions
Observed: The files are not listed at all.

**Comment by steveward** [comment]
@adharsri thanks for the issue. There are some known issues with file mode changes in GitHub Desktop -- see https://github.com/desktop/desktop/issues/3870 and https://github.com/desktop/desktop/issues/11685#issuecomment-790296403. The best workaround for now is to commit file mode changes using Git Bash. I'm going to close this out since we're tracking this issue in #3870.
