### ISSUE TITLE
Constantly asked for ssh key passphrase after window becomes active

### ISSUE THREAD

**Issue by neiled** [desktop/desktop#14459]
### The problem

Once I cmd-tab back to Github Desktop I'm asked for the passphrase to this ssh key.
I'm not sure even what this key is used for, and I definitely don't know the passphrase.

### Release version

Version 3.0.0 (arm64)

### Operating system

MacOs 12.3.1 (21E258)

### Steps to reproduce the behavior

Hard to say, started doing it a few weeks ago.

### Screenshots

<img width="789" alt="image" src="https://user-images.githubusercontent.com/2861/165386222-f2d2f8d3-d802-4be2-8e93-0b911719c701.png">

**Comment by sergiou87** [comment]
Was any of your repositories in GitHub Desktop cloned via SSH? If so, that's why it's asking you for the passphrase of your key.

If you don't know the passphrase, I'm not sure how you cloned such repository in the first place, unless you copied the repository folder from somewhere else and added it to GitHub Desktop 🤔 

If you don't know/want to enter that passphrase, my advice is that you either remove whatever repo was cloned via SSH or just re-clone it via HTTPS.

I hope that helps!

**Comment by neiled** [comment]
So there are only 4 repos that it knows about. All of them can pull/push no problems and none of them directly ask me for a key when I perform any action.

**Comment by sergiou87** [comment]
Weird… I'd expect pull/push operations to prompt the passphrase. Could you try removing them from GitHub Desktop (not from your hard drive) one by one until you stop getting that prompt?

Maybe if we know which repo is causing this exactly we can understand why 🤔

**Comment by neiled** [comment]
Thanks. OK sounds good, I'll remove them over time, takes maybe 10 mins or so for the popup to come back so will see how it goes.

**Comment by steveward** [comment]
@neiled as we haven't heard back from you I am going to close this issue out. Let us know if you are still having problems and we can investigate further!
