### ISSUE TITLE
Add ability to make diff more cohesive (larger hunks) for better partial commits

### ISSUE THREAD

**Issue by Niko-O** [desktop/desktop#14455]
### The feature request

Sometimes you remove one function in a file and, as an unrelated change, add another one in its place. When you do that, the diff algorithm tends to get very confused:
![Bad](https://user-images.githubusercontent.com/4943909/165230407-e68a54aa-5289-44a7-808e-7f31e3d0fdbf.png)
The diff here is not really useful, and in more complicated situations it can actually be very confusing. And it quickly becomes practically impossible to only commit a subset of the intended changes.

To get around this, one has to create a manual copy of the file, then successively undo changes in the problematic area until the diff becomes readable enough, then select those changes and commit them, then restore the copy.

### Proposed solution

This would be much better:
![Good](https://user-images.githubusercontent.com/4943909/165230557-ad58f55f-88b3-41e8-8501-756a8ed9570e.png)
If there is a way of telling the diff algorithm "Treat these lines as one big removal and these other lines as one big addition", then the diff becomes much more readable.

**Comment by sergiou87** [comment]
AFAICT, none of git's diff algorithms support this, sorry 😞 

If that ever changes, we'll be happy to discuss our options. Thank you for your feedback! ❤️

**Comment by Niko-O** [comment]
Are the diff algorithms part of this repository? If not, where are they?

**Comment by bhaller** [comment]
I ended up here since the same problem was bugging me.  Note that StackOverflow posted on their blog about this recently:

https://stackoverflow.blog/2024/08/05/this-developer-tool-is-40-years-old-can-it-be-improved/

Their conclusion is that we all waste a whole lot of time dealing with poorly presented diffs, and that improvement is both possible and needed (although non-trivial).

Is there an open issue on Git itself, regarding the need for a better diff algorithm?  The lack of such an algorithm seems to be the reason why this issue was closed.  It'd be great to see motion on this.
