### ISSUE TITLE
Local repository deleting after opening GitHub Desktop

### ISSUE THREAD

**Issue by brunsons98** [desktop/desktop#14466]
### The problem

Sometimes, after opening GitHub Desktop, my local repositories seem to delete themselves. Before opening the app, the files will appear all right in my file explorer for my local repository, but either immediately after or shortly after opening the GitHub Desktop app, the app will say that my local repository no longer exists, and sure enough, the files are now gone from my file explorer. Does not seem to happen every time and difficult to predictably recreate or avoid - the issue can happen earlier in the day, I will re-clone the repositories and work on them fine, commit changes, and close the desktop app, and if I open the app again later that day, the issue will not occur. The deletion may happen when I go a few days between opening the desktop app, but still unsure exactly what triggers it.

### Release version

Version 3.0.0 (x64)

### Operating system

Windows 10

### Log files

[2022-04-27.desktop.production.log](https://github.com/desktop/desktop/files/8578307/2022-04-27.desktop.production.log)

### Additional context

This has been specifically happening with my GitHub enterprise account and repositories I have access to through there - just was not able to navigate to this error reporting page using that account.

**Comment by sergiou87** [comment]
Sorry to hear that 😢 

I don't think there is anything in GitHub Desktop that could trigger that behavior. If something is deleting those folders, it must be something external to Desktop, so I'm gonna close this issue. Just to throw some ideas… maybe an antivirus putting your repositories in quarantine (or just deleting them) because it thinks they're malicious? Are you in some kind of multi-user environment where some other user could delete them by mistake?
