### ISSUE TITLE
Cannot push local changes

### ISSUE THREAD

**Issue by Omega-The-III** [desktop/desktop#14478]
### The problem

Attempting to push local changes to branch does nothing. Github Desktop push icon loads for a few seconds and when its done it still says there are local commits to be pushed.
![Animation](https://user-images.githubusercontent.com/57790446/165958801-66e6c166-103e-4459-a017-5702f226b9d5.gif)
 

### Release version

3.0.0 (64x)

### Operating system

Windows 10

**Comment by sergiou87** [comment]
@Omega-The-III  Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by steveward** [comment]
@Omega-The-III as we haven't heard back from you I am going to close this issue out. Let us know if you are still having problems and we can investigate further.
