### ISSUE TITLE
Automatically fetch repositories cloned through the terminal.

### ISSUE THREAD

**Issue by Bavuett** [desktop/desktop#14518]
### The feature request

I love GitHub Desktop, but sometimes I use the terminal to clone repositories because it's faster.

It would be great if GitHub Desktop would periodically check a known folder for newly cloned repositories and would automatically add them to the list, so people could manage them using this client without manually adding them everytime.

### Proposed solution

On startup, check for a folder where the user stores his repositories and add them to GitHub Desktop.

I have no experience with React so I can't work myself on the feature, but it would be awesome if someone worked on this.

### Additional context

I have no mockups, unfortunately.

**Comment by yvettep321** [comment]
yes agree

**Comment by cooljeanius** [comment]
on macOS the folder-watching could be done with `fseventsd`, while on other platforms I think kqueues could work

**Comment by Bavuett** [comment]
Hey @tidy-dev, sorry for bothering you! I'm trying to work on this feature but I can't run the `yarn build:dev` completely because I get this error: 

![image](https://user-images.githubusercontent.com/43916566/214558957-cd36f4b0-3f27-4156-99fb-557a0e5b35d1.png)

~~Is there any way you can help? I've never used yarn before, so I am a bit disoriented.~~

**EDIT: Nevermind, syncing my fork fixed it!**

 Have a good day! :)

**Comment by Bavuett** [comment]
Alright, figured everything out! Officially working on it!

**Comment by tidy-dev** [comment]
@Bavuett Sorry, I didn't see this earlier. Glad you got it working! 

I love your enthusiasm to improve GitHub Desktop! Just to forewarn you, the GitHub Desktop team uses the enhancement label only to signify that this is an enhancement request as opposed to a bug report. It is not an acceptance of this suggestion as something we have discussed and we will support like issues we labeled with a help-wanted. (Of course, we get pull requests for unacknowledged issues all the time and some of them to make it in :) ).

**Comment by Bavuett** [comment]
Will take this into account, thanks for the heads up! ;)

**Comment by Bavuett** [comment]
Replying to [this comment](https://github.com/desktop/desktop/pull/16018#issuecomment-1406376557) by @sergiou87:

Hey Sergio! Yeah, I've understood what @tidy-dev told me. I insisted to work on the feature just because, as a student, I wanted to experience what it means to contribute to Open Source projects and work on code that was not originally created by me. I understand that the feature may not ever see the "light of the day", and I'm sorry if I've wasted your time at work with my PR. I've closed it so GitHub doesn't send you notifications while I'm working on it.

Regarding the feature: my idea was to let the user choose, in the app's settings, a folder where they store their Git projects in order to automatically add them to Desktop if, for some reason (cloned through the terminal, for example), the app does not have them.

While I wait for your feedback regarding the feature, I thank you again for your heads up and for making sure that I do not waste my time. As you may already have understood by reading this, though, I'd like to work on it anyways because I believe that this is a formative experience and I'd like to learn about how the things I use everyday work under the hood. I know that reading the source code may accomplish this anywas, but I tend to prefer the "learning-by-doing" method. I wish to both of you a good day, and thanks again for the time you dedicated to me!

**Comment by tidy-dev** [comment]
@Bavuett Just a follow up since you showed a lot interest in working on this. We discussed it in our team sync. In a very long ago past version, we had something similar -> a scanning feature for repositories. We had many bugs and maintenance issue as a result from things where the scanning features incorrectly detected folders and how it handled nested folders (things like submodules). Additionally, we may be concerned the performance impact such a scanning scanning feature could entail. At this time, we are not interested in supporting this feature, and therefore, I am closing this issue.

That said, we love your enthusiasm, and if you come up with something on your fork and think it warrants discussion, feel free to share video/screenshots of it here with your reasoning on why it should be supported. We especially appreciate when contributors think through the potential (positive and negative) impacts introducing the feature might entail as well as any other solutions considered.

**Comment by steveward** [comment]
@Bavuett also wanted to mention that you can add a repository to GitHub Desktop from the command line using the `github <path/to/repo>` command. I use it quite a bit to quickly add repos I've cloned via the command line.
