### ISSUE TITLE
Many files listed as changed with "No content changes found"

### ISSUE THREAD

**Issue by Lunarexxy** [desktop/desktop#14616]
### The problem

Often, GitHub Desktop will show files as changed, despite their contents not actually changing. Clicking on them, the preview on the right side will show "No content changes found"

Perhaps they were re-saved with identical contents and their modified time changed, or their permissions changed, I'm not sure. Either way, GitHub Desktop counts them as changed and prepares them to be committed anyway, even though committing them with no changes is impossible. (I even tried, they are either discarded from the commit, or an error message is shown suggesting that no filed were chosen to be committed.)

Since these files can't be committed anyway, I think these files shouldn't be listed in the Changes tab as if they could be.

(This issue is the same as #3987 but that issue was closed with no resolution, aside from a vague feature request about line ending warnings. It's still an unfixed bug 4 years later, and I think it should be listed as such. Someone kept saying to open a new issue, so here you go.)

### Release version

3.0.0

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Change timestamp of some file in the repository
2. Open repository in GitHub Desktop

**Comment by tsvetilian-ty** [comment]
@Lunarexxy, your issue is most likely caused by line-ending. It often occurs when the repo is used in multiple OSs. Here is how to configure it: https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings

Check [`git.core.fileMode`](https://git-scm.com/docs/git-config#Documentation/git-config.txt-corefileMode) if you think that a permission change might be the reason.

**Comment by tooda02** [comment]
I'm having the same issue between two Windows machines (a desktop and a laptop), so it's unlikely to be line endings.  The repo is of a Unity project that originated on the desktop but needs to be copied to the laptop so it's available during a trip.  After syncing the repos, I manually copied the Unity Assets directory from the desktop to the laptop because it contains a number of files not stored in GitHub, such as DLLs.  After the copy, all of Unity's "meta" files (files generated by Unity that contain extra information about assets) showed up as changed on the laptop but with "No content changes found" on the right panel.  Here's a screenshot:

![image](https://user-images.githubusercontent.com/11247671/221631357-c1e0c334-be9b-4142-af1e-df5d8ffb769f.png)

**Comment by steveward** [comment]
@tooda02 can you open the repository in the command line and run `git diff <file>` against one of those files to see what that outputs?

**Comment by tooda02** [comment]
Sorry, it turns out the issue is line endings after all.  Here's the output from running your suggested command on the highlighted file above:

git diff CustomModelEditor.cs.meta
warning: LF will be replaced by CRLF in Assets/Scripts/Level Editor/CustomModelEditor.cs.meta.
The file will have its original line endings in your working directory

So I expect the best approach is to discard all the changes on the laptop side (since the repo maintained by the desktop is ok the way it is).  Are there any pitfalls to this approach?

**Comment by tooda02** [comment]
Also, is there a settings difference between the two installations that would cause this?  "git config --global --get core.autocrlf" returns an empty line on both boxes

**Comment by steveward** [comment]
Setting `core.autocrlf` to `true` will convert line endings to LF when you commit, and is the recommended setting for Windows. You can also set up a `.gitatribbutes` file to manage line endings on a per-repo basis. See [this article](https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings).

**Comment by serluis** [comment]
On branch x
Your branch is up to date with 'origin/x'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   .idea/dataSources.xml
	modified:   src/main/java/TicketDAO.java

no changes added to commit (use "git add" and/or "git commit -a")

**Comment by UNITOLIAM** [comment]
try this:
$ git config core.fileMode false

**Comment by fge3-pl** [comment]
Found this as top search result for this issue. I was able to fix this issue so here's some findings hoping it'll help future folks stumbling across this.

Just to summarize the background context:
- Text files on Windows end each line with a different character (called CRLF) than on Mac or Linux (called LF)
  - The issue arises when you have some people working with Mac and some with Windows. It causes chaos with source control because some files get created with CRLF and some with LF.
- The solution is then all text files are stored inside of Git with LF, but Git auto-converts them to CRLF when you're working on Windows.
  - This is achieved with setting `* text=auto` inside the .gitattributes file.
  - Checkout https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings for more information about this.
  
This may just solve your issue, but I was still running into this. It turns out my specific problem was with Unity!
I followed everything in the doc above, but I still had a file that registered as a change and when running `git diff` it would say `warning: LF will be replaced by CRLF`.

To verify that it is a line endings change that is causing the issue: 
- Open the file in Sublime Text. In the bottom right it'll say Windows for CRLF, or Unix or LF.
- Since I'm on a Windows machine, I expected the file to say Windows, but it actually said Unix.
- I changed to file back to Windows line endings in Sublime Text and then the change went away! Aha!
- Then if I changed it back to Unix it would show up as a change again.

So it turns out whenever I opened Unity it would save out some random Settings.json files as LF for some reason, even on Windows. I was able to fix this by just changing those files to use LF endings in my `.gitattributes` file: `*Settings.json text eol=lf`
