### ISSUE TITLE
Clone Fail client loop disconnect

### ISSUE THREAD

**Issue by Howlfei** [desktop/desktop#14617]
### The problem

I have been trying to clone some files for a project. It is consistently getting to 16% and then the process just stops. I've gone through every troublshoot I could find that looked even remotely relevant. me and the person hosting the main files have tried editing data, reseting networks, reset computer. everyone else on the team has been able to clone the files just fine. we have all done the exact same steps. I am the only one consistently running into any issue.

The exact error that keeps popping up is attached below
though I don't trust it to open properly so in brief.
Fetch pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: getch pack: invalid index-pack output

At first, I thought it might be my internet, but after it has consistently failed at 16% for the umpteenth time I think a random internet disconnect is unlikely.
![Screenshot 2022-05-14 105627](https://user-images.githubusercontent.com/105470160/168447879-d7d173b6-b2fd-40e9-b292-508849126743.png)

### Release version

3.0.0 (x64)

### Operating system

windows 11

### Steps to reproduce the behavior

1: clone repository
2: click URL
3: paste URL and select file location
4: click "clone"
5: reaches 16% 
6: wait for 2 hrs before giving an error report as it hangs/stalls at 16%

### Log files

[2022-05-14.desktop.production.log](https://github.com/desktop/desktop/files/8693872/2022-05-14.desktop.production.log)

### Screenshots

![Screenshot 2022-05-14 105627](https://user-images.githubusercontent.com/105470160/168448192-a8f65236-60b7-4dcb-b02e-226cfaa4326c.png)

### Additional context

NA

**Comment by mehdiGihub** [comment]
شكرا لك على مابذلته لمساعدتي

بتاريخ ١٤‏/٠٥‏/٢٠٢٢ ٢١:١١، كتب "Howlfei" ***@***.***>:

**Comment by mehdiGihub** [comment]
شكرا لك

**Comment by steveward** [comment]
Thanks for the report @mehdiGihub. This looks like a large repository (over 6GB based on the log). Unfortunately with large repositories like this you can often encounter clone failures due to connection issues. Is this repository using Git LFS?

You could try cloning the repository via SSH to see if that succeeds -- it can often be more reliable for larger clones like this. You can read [this article](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent) for help on setting up a new SSH key. Once you've set up a new SSH key you can clone via the `File` > `Clone Repository` > `URL` option using the SSH URL. Let me know if that helps.
