### ISSUE TITLE
Local Repos showing nothing besides the root of the C Drive.

### ISSUE THREAD

**Issue by entraptaa** [desktop/desktop#14647]
### The problem

Been trying to add a local repository of my bot to GitHub Desktop so I can update my repo again but trying to add the local repository brings me to the root of the C Drive.

### Release version

3.0.0

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Go to File.
2. Click: Add local repository.
3. Choose any folder.
4. Click: Add Repository.

### Log files

[2022-05-20.desktop.production.log](https://github.com/desktop/desktop/files/8745799/2022-05-20.desktop.production.log)

### Screenshots

![GitHubDesktop_35SoHxsK5I](https://user-images.githubusercontent.com/33435468/169625663-4310fd94-bd93-49a3-b17a-0fae33615b5d.gif)

**Comment by tsvetilian-ty** [comment]
@RiftSTW are you sure that "New MongoDB" is a git repository? Perhaps "New MongoDB" is not repo, and the top-level is in `C:\`. If "New MongoDB" is not initialized, you can use the `Create a New Repository on your hard drive...` button

Steps to check what is the top-level repository

1. Open your terminal of choice
2. Navigate to "New MongoDB"
3. Type `git rev-parse --show-toplevel`

If the output is `C:/`, use the `Create a New Repository on your hard drive...` button to initialize "New MongoDB" as a repository

**Comment by entraptaa** [comment]
Fixed my issue yesterday but thanks for the reply.

**Comment by ADlovebee** [comment]
Is how is work please tell me if is ok thank you.Sent from Mail for Windows From: RiftSTWSent: Saturday, May 21, 2022 6:30 PMTo: desktop/desktopCc: SubscribedSubject: Re: [desktop/desktop] Local Repos showing nothing besides the root of the C Drive. (Issue #14647) Fixed my issue yesterday but thanks for the reply.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***> 

	
        
		Virus-free. www.avast.com

**Comment by ADlovebee** [comment]
Thank you I will go in check ok Sent from Mail for Windows From: Tsvetilian YankovSent: Saturday, May 21, 2022 1:24 PMTo: desktop/desktopCc: SubscribedSubject: Re: [desktop/desktop] Local Repos showing nothing besides the root of the C Drive. (Issue ***@***.*** are you sure that "New MongoDB" is a git repository? Perhaps "New MongoDB" is not repo, and the top-level is in C:\. If "New MongoDB" is not initialized, you can use the Create a New Repository on your hard drive... buttonSteps to check what is the top-level repositoryOpen your terminal of choiceNavigate to "New MongoDB"Type git rev-parse --show-toplevelIf the output is C:/, use the Create a New Repository on your hard drive... button to initialize "New MongoDB" as a repository—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***> 

	
        
		Virus-free. www.avast.com
