### ISSUE TITLE
Not able to push commits

### ISSUE THREAD

**Issue by DishaN25** [desktop/desktop#14686]
### The problem

I have been trying to push commits after making changes to my branch for an hour now. The changes are not getting pushe
<img width="1440" alt="Screenshot 2022-05-27 at 7 11 33 PM" src="https://user-images.githubusercontent.com/87308259/170711112-6351e2b9-7522-4431-9260-3ab4aa3c018f.png">
d

### Release version

3.0.0 (x64)

### Operating system

MacBook Pro v12.3.1

**Comment by sergiou87** [comment]
Hi @DishaN25 ! 👋  Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by sergiou87** [comment]
I see you are pushing 214 commits. Do you know how many megabytes of data are included in those commits?

**Comment by DishaN25** [comment]
2022-05-27.desktop.production.log.zip

**Comment by DishaN25** [comment]
[2022-05-27.desktop.production.log.zip](https://github.com/desktop/desktop/files/8795464/2022-05-27.desktop.production.log.zip)

**Comment by DishaN25** [comment]
Please revert. My changes are not pushing through

**Comment by tsvetilian-ty** [comment]
The issue is `Could not resolve host: github.com`. @DishaN25, this indicates a connection problem. Ensure anti-virus or proxy software is not blocking the connection, and add GitHub Desktop to the excluded list.
