### ISSUE TITLE
account login 

### ISSUE THREAD

**Issue by alisilenus** [desktop/desktop#14684]
### The problem

hi!
i'm new in github.
i create a new account and there is  some proplem of "Push origin" in windows application.
the errore is "The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed."

### Release version

Version 3.0.0 (x64)

### Operating system

windows 10

### Steps to reproduce the behavior

1.Go to "GitHub Desktop"
2. Click on "Push origin"
3.  Errore "The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed."

### Screenshots

![github_error](https://user-images.githubusercontent.com/106349701/170689879-48c82b69-b160-465f-9b57-083ba46f0714.png)

**Comment by sergiou87** [comment]
Hi @alisilenus! 👋  Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
