### ISSUE TITLE
Lag in Github desktop

### ISSUE THREAD

**Issue by rit-hub** [desktop/desktop#14698]
### The problem

Delay in response any user input almost 10s

### Release version

3.0.0

### Operating system

windows 11

**Comment by Bezzo100-lab** [comment]
`/storage/emulated/0/Download/ASF-501c3.pdf`

**Comment by steveward** [comment]
@rit-hub thanks for the issue. Could you upload a log file from GitHub Desktop so that I could get some more information about these performance issue? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue. 

For reference we're tracking reports of this in https://github.com/desktop/desktop/issues/13586, so I'm going to close this out in favor of that issue. Please feel free to still upload your log file so that we can take a look. Thanks!
