### ISSUE TITLE
Minimization after using shortcuts.

### ISSUE THREAD

**Issue by Zubbbz** [desktop/desktop#14690]
### The feature request

It would be neat if Desktop would minimize after using any of these shortcuts. I think it would also be nice to be able to toggle this functionality. 
These shortcuts ↓↓↓
![image](https://user-images.githubusercontent.com/37497090/170857139-14af8ee1-b345-4eff-add4-aa64d63682ed.png)

### Proposed solution

Add an option under the advanced category "Minimize GitHub Desktop on shortcut". While that option is enabled, if you use a shortcut to launch your external editor, or any other shortcut, then GitHub Desktop should minimize.
![image](https://user-images.githubusercontent.com/37497090/170857208-e173f736-bee1-4879-bd83-2227d064d2f6.png)

**Comment by niik** [comment]
Hi @Zubbbz, thanks for reaching out!

I'm afraid minimizing the app after running shortcuts isn't something that we're planning on implementing. Partly because that behavior would be so unexpected that it would require a preference to enable it which would mean very few users would benefit from it and we're a very small team with limited resources. Given that this is the first time we're seeing this particular request we have to assume it's not a widely requested feature.

This pattern isn't one I've encountered before in other applications and I'm curious if this is something you've seen or used before?

I'm going to close this issue as it's not something we're planning on addressing but if you have any more context or insights that could help us re-evaluate if this comes up more frequently please leave them here.
