### ISSUE TITLE
unable to load on visual studio

### ISSUE THREAD

**Issue by Evani-maker** [desktop/desktop#14705]
I keep encountering an error each time i try to use my vs code terminal , it pops up this error code:
Error: spawn C:\WINDOWS\system32\cmd.exe ENOENT
    at __node_internal_captureLargerStackTrace (node:internal/errors:464:5)
    at __node_internal_errnoException (node:internal/errors:594:12)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

Version: 3.0.0
OS: Windows 10.0.10240

**Comment by tsvetilian-ty** [comment]
👋 @Evani-maker check out https://github.com/desktop/desktop/issues/14202#issuecomment-1072376656. tldr make sure that `ComSpec` environment variable is set to `%SystemRoot%\system32\cmd.exe`. Restart GitHub Desktop after the change!

**Comment by tsvetilian-ty** [comment]
@Evani-maker let's keep the conversation regarding your issue here, so the team knows when it's resolved and when to close it 😅 And if someone has a similar problem, they can follow the progress in one place.

Quote: https://github.com/desktop/desktop/issues/14202#issuecomment-1146494897
> make a video on how to change to %SystemRoot%\system32\cmd.exe

Right-click the Windows icon > "System" >  "Advanced System Settings" > "Enviroument Variables" > In "System variables" you should have "ComSpec" > Double click it and change "Variable value" to `%SystemRoot%\system32\cmd.exe`
