### ISSUE TITLE
Use OS Window Border

### ISSUE THREAD

**Issue by splendidnut** [desktop/desktop#14739]
### The feature request

Please provide an option to display the OS window border.

### Proposed solution

Display the window border provided by the OS.

**Comment by steveward** [comment]
Thanks for the issue @splendidnut. See [this comment](https://github.com/desktop/desktop/issues/9011#issuecomment-587664162) for the reasoning as to why we aren't providing a window border at this time. I'm going to close this out since this isn't something that is on our radar, but thanks for letting us know you'd like to see it implemented.

**Comment by splendidnut** [comment]
Well, that's disappointing.  So are you saying I need to contact the Electron team if I'd like to see this issue fixed in this fashion?
