### ISSUE TITLE
LinkButtons doesn't truncate properly due to inline-flex rule

### ISSUE THREAD

**Issue by joshaber** [desktop/desktop#1474]
1. Make a commit which includes a URL in the summary.
2. Check out History.

![screen shot 2017-05-15 at 5 36 41 pm](https://cloud.githubusercontent.com/assets/13760/26085432/3d53221e-39b2-11e7-9a58-c5e6b5b9e1c8.png)

**Comment by Johann-S** [comment]
Fixed by : https://github.com/desktop/desktop/commit/ef2a58b4718958083a1330d73479b673c3296a0e
Because now url aren't link so they are truncated

**Comment by joshaber** [comment]
Awesome 🤘

**Comment by niik** [comment]
For future reference it looks like this is caused by our [inline-flex](https://github.com/desktop/desktop/blob/432738e426f83c309375291f0d5da86132f167ae/app/styles/ui/_button.scss#L58) rule on link-button-component, see http://stackoverflow.com/q/28362688/2114

I'm pretty sure we only use that inline-flex rule so that we can position the icon properly when the linkbutton component has one. I think we should 

We should probably still make sure that link buttons truncate properly. Either by finding a way for link buttons with images to not use `inline-flex` or by creating a dedicated `OcticonLinkButton` which would be able to replace most, if not all, of our linkbutton+icon uses in the app right now and would let us simplify the normal LinkButton.

**Comment by joshaber** [comment]
Closing as the original issue is fixed. We can track any technical debt we have separately.
