### ISSUE TITLE
"My Branches"

### ISSUE THREAD

**Issue by ghost** [desktop/desktop#14783]
### The feature request

In branches dropdown, it would be nice to have a separate row for "my branches", branches that my user has created or contributed to.

### Proposed solution

In repos with a large number of branches, this could help reduce the time spent in the dropdown searching for the correct branch.

**Comment by steveward** [comment]
Thanks for the issue @AndyVoutour! At this time we don't have plans to make changes to the branch list, since the recent branches feature and filtering capabilities cover most cases where you would need to navigate to a branch.

One helpful trick you can use is to prefix your branch name with your username and a slash (i.e. steveward/feature-branch). The slash gives it a hierarchical grouping and now you can search for just your username and find all the branches you've created.

Creating an early pull request off of a new branch is another helpful solution, as it allows you to search via the PR title or by username in the `Pull Requests` tab.

I hope that helps! I'm going to close this out since it isn't something we're planning to work on, but let me know if you have any questions.
