### ISSUE TITLE
Filter branches by creator

### ISSUE THREAD

**Issue by paulnpdev** [desktop/desktop#14806]
### The feature request

it would be cool if I could filter branches to only include mine, or some other specified user.

### Proposed solution

add dropdown with list of users who created the branches
add creating-user to the existing branch dropdown

**Comment by steveward** [comment]
@paulnpdev thanks for the issue! At this time we don't have plans to make changes to the branch list, since the recent branches feature and filtering capabilities cover most cases where you would need to navigate to a branch.

One helpful trick you can use is to prefix your branch name with your username and a slash (i.e. steveward/feature-branch). The slash gives it a hierarchical grouping and now you can search for just your username and find all the branches you've created.

Creating an early pull request off of a new branch is another helpful solution, as it allows you to search via the PR title or by username in the `Pull Requests` tab.

I hope that helps! I'm going to close this out since it isn't something we're planning to work on, but let me know if you have any questions.

**Comment by tidy-dev** [comment]
Other friendly suggestion is to follow https://github.com/desktop/desktop/issues/8048 for any future branch list improvement discussions. (tho as mentioned above, there are not any on the roadmap at this time)
