### ISSUE TITLE
Improve "leave changes and switch branch" stash overwrite with explicit confirmation

### ISSUE THREAD

**Issue by gnowland** [desktop/desktop#14832]
### The feature request

The "Your current stash will be overwritten by creating a new stash" message on the "stash my changes and switch branches" dialog is **way too subtle**:

<img width="443" alt="Screen Shot 2022-06-17 at 2 28 43 PM" src="https://user-images.githubusercontent.com/4430119/174404089-18f4be59-e036-45b3-893d-7ea948127eca.png">

A destructive procedure such as overwriting a current stash should require an **explicit confirmation of intent**, ideally in a separate dialog, as mocked in #10956.

### Proposed solution

![97893314-69c42f80-1d31-11eb-8ef5-fbf1c10eadef](https://user-images.githubusercontent.com/4430119/174404403-04d3c2cf-361f-483d-bffb-695ea98b09bb.png)

### Additional context

I've hit the "switch branch" button too quickly a couple of times (muscle memory, combined with the destructive action being highlighted blue) before realizing what i've done 😫 thank goodness for `git fsck`...

**Comment by fbastien** [comment]
Agreed, this is currently way too much dangerous, my team mates lost too much precious hours of work (and trust in Git) because of this!

I would go even further, with following propositions :
- If such confirmation popin is implemented, add a third button "merge stashes"
  (**OR** allow multiple stashes per branch)
- In the settings, add an option to automatically apply existing stash if any when checking out a branch (which would prevent forgetting then overwriting existing stashes on branches)
  This could be for instance bellow the "If I have changes and I switch branches..." setting, something like that:
  - **If I switch to a branch where I left some changes...**
    - [ ] Ask me if I want to restore the changes from the stash ⬅️ (I would advise this as a default)
    - [ ] Always leave the changes in the stash ⬅️ (This is the current behaviour)
    - [ ] Always restore the changes from the stash

**Comment by gnowland** [comment]
This has been implemented!

**Comment by fbastien** [comment]
@gnowland Do you know in which version it has been implemented? I can't find anything about it in release notes nor any pull request directly related to this...
