### ISSUE TITLE
error when upload the project

### ISSUE THREAD

**Issue by androTech0** [desktop/desktop#14846]
### The problem

I can't upload my project , because the program has error it the network not connected!!

### Release version

Version 3.0.2 (x64)

### Operating system

Windows 10

**Comment by sergiou87** [comment]
@androTech0  Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by JoGeorgeCodes** [comment]
What do you mean "it the network not connected?"
