### ISSUE TITLE
Keyboard shortcut on New Branch modal window

### ISSUE THREAD

**Issue by mikecole** [desktop/desktop#14858]
### The feature request

When entering a summary of a new commit, the "Commit" button correctly functions when pressing CTRL+Enter on the keyboard. I would like the "Create branch" button on the "Create a branch" modal to do the same.

### Proposed solution

On the "Create a branch" modal, after keying in the branch name, I would like the CTRL+Enter key combination on the keyboard to trigger the "Create branch" button. This will make the UI more consistent.

### Additional context

![image](https://user-images.githubusercontent.com/1166315/175129685-2b58afe6-63d6-4e19-aaae-29e6855ae951.png)

**Comment by tidy-dev** [comment]
@mikecole The create branch dialog currently follows a common UI convention that hitting Enter will submit a simple dialog form. Curious if you were aware of this and just looking for a quick way to submit the form? 

Other thoughts:  I think the simple dialog form and the commit summary form are not the same context (thus don't need to be consistent) since the commit summary is not singled out as in a dialog. Also, if a user is in the commit description the Enter button already has a function for a new line, thus necessitating a Ctl+Enter.

**Comment by mikecole** [comment]
@tidy-dev No, I did not realize Enter submitted that form, so that will meet my needs. Thank you.
