### ISSUE TITLE
VERY VERY SLOW

### ISSUE THREAD

**Issue by DanielAgerman** [desktop/desktop#14881]
### The problem

very slow i know you americans love your fast internet but in the rest of the world we dont have such luxuries

### Release version

dunno

### Operating system

win 11

### Steps to reproduce the behavior

DOING ANYTHING

**Comment by sergiou87** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by DanielAgerman** [comment]
> Thanks for reaching out!
> 
> We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.
> 
> Thanks for understanding and meeting us half way 😀

Hi there thank you very much for fixing the issue. I can see now that it was never really an issue and that trying to upload a 1 Gigabyte file at 450 Kilobytes per second is totally reasonable for 2022. Thanks heaps.
😀
