### ISSUE TITLE
updated default branch isn't shown in branch list until after restart

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#1489]
### Description

If the default branch is changed on the GitHub or GitHub Enterprise server, this is refreshed in the local IndexedDB but not displayed until a restart.

### Version

What version of GitHub Desktop are you running? This is displayed under the
`About GitHub Desktop` menu item. If you are running from source, include
the commit by running `git rev-parse HEAD` from your local repository.

**GitHub Desktop version:** 1.5.1

**OS version:** macOS Sierra 10.12.4

### Steps to Reproduce

1. Create a new repository, make a commit, publish to GitHub
1. Create a new branch, named `second-branch` 
1. Publish the branch to the server
1. Visit the repository's branches settings page: `https://github.com/{account}/{repository}/settings/branches`
1. In the branch selector page, select the branch `second-branch` and press `Update`.
1. Switch back to the application and switch between repositories to force a refresh
1. Open the branch list

**Expected behaviour:** Default branch is listed as `second-branch`

**Actual behaviour:** Default branch is still `master`

**Reproduces how often:** it reproduces despite switching or performing a fetch until the app is restarted.

**Comment by joshaber** [comment]
I've been poking at this off and on for a couple days now. The root cause is that `GitStore`s [are created](https://github.com/desktop/desktop/blob/b564e05a8f491c955255a24477a2207de5c571ac/app/src/lib/dispatcher/git-store.ts#L108) with a `Repository` and we cache `GitStore`s [by their repository's ID](https://github.com/desktop/desktop/blob/b564e05a8f491c955255a24477a2207de5c571ac/app/src/lib/dispatcher/app-store.ts#L507).

This means properties of the repository (notable, its `gitHubRepository`'s `defaultBranch`) can change without the `GitStore` being recreated.

I've looked at a few couple ways of fixing the issue:

1. Stop caching `GitStore`s. This fixes the problem but makes switching between repositories noticeably slower.
1. Recreate the `GitStore` lazily if the repository whose store was requested isn't structurally equal to the one that already has a store. This kinda works but is subject to races because the old `Repository` instance with the same ID might still be hanging around and could call `getGitStore` and smash our updated `GitStore`.

The root problem is that we're aliasing data that can change by an unchangeable ID.

My current thought is to add a `hash` property to `Repository` which is dependent on `Repository`s properties. We can use this as the key for `GitStore` lookup and caching instead of the repository ID.

This has the advantage of reifying a pattern we're already using in a number of places: checking for structural equality between `Repository` instances.

Any thoughts are welcome.

**Comment by jhammersholt** [comment]
I still have this issue - changing dafault branch on github.com does not update it in the desktop app even if i restart the app

**Comment by Jacob-Stevens-Haas** [comment]
This appears to still be an issue... I'm working on a GitHub enterprise server, GitHub Desktop 1.6.2, and Windows 10 Enterprise version 1709.

Changed default branch to `master` in GitHub enterprise, not reflected in GitHub Desktop.  Used command line to remove the `alternate` branch.  As a result, GitHub desktop doesn't list a default branch, just the one branch (`master`) in "Other Branches"

**Comment by taotien** [comment]
This still happens on 1.6.5. Default branch doesn't update even with a restart of the app.

**Comment by Robjam** [comment]
Just ran into this, removing the repository and adding as an existing repository seems to update the default repository.
