### ISSUE TITLE
Diff context expansion options are not appearing for larger files

### ISSUE THREAD

**Issue by tecodan** [desktop/desktop#14910]
### The problem

When viewing changes for files > 4MB I am noticing the context expansion buttons are not appearing. These are the Expand Up, Expand Down buttons, and the Expand Whole File option on the context menu.

This is what we normally see when it is working:
![image](https://user-images.githubusercontent.com/49328/177453804-d1c74ca9-3ad0-4ff1-99c1-c4b3067a0e8b.png)

But for larger files, these are missing:
![image](https://user-images.githubusercontent.com/49328/177454166-0ce43395-8746-46c0-a9ec-70e68ed06979.png)

### Release version

3.0.3 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Locate a file at least 4mb in size in your repository that has an uncommited change (In my case this was a JSON formatted file)
2. From the Changes view, select that file
3. On the Diff screen (right pane) will show those changes. Notice the missing expansion buttons, and the option to view entire file

### Screenshots

Refer to Issue description

**Comment by tidy-dev** [comment]
@tecodan Thanks for reaching out! Unfortunately, there is a [max content length](https://github.com/desktop/desktop/blob/535d4a124093a4bfde9091afb683f943647b417f/app/src/ui/diff/syntax-highlighting/index.ts#L20-L29) before we our parser starts being truncated. When that is hit, we cannot accurately determine the expansion hunks; thus, this is expected behavior.
