### ISSUE TITLE
Rebase conflict resolution hang

### ISSUE THREAD

**Issue by leesheppard** [desktop/desktop#14927]
### The problem

When rebasing branch and fixing conflicts, clicking on `Continue Rebase` can at times just hang on that modal and not proceed forward to next step. The app appears to be locked up as pressing the button no longer functions. Quitting the app and restarting does resolve the state.

<img width="490" alt="Screen Shot 2022-07-08 at 10 47 29 am" src="https://user-images.githubusercontent.com/287232/177894450-f8d44931-1ead-49f7-8570-9410048c493f.png">

### Release version

Version 3.0.3 (x64)

### Operating system

Mac

### Steps to reproduce the behavior

1. Rebase the branch
2. Go through merge conflicts
3. By second or third conflict, you'll find clicking on the Continue Rebase no longer progresses the app

### Screenshots

<img width="490" alt="Screen Shot 2022-07-08 at 10 47 29 am" src="https://user-images.githubusercontent.com/287232/177905940-cdb59c1a-02f2-4375-bf0f-85c5af3b82f0.png">

**Comment by niik** [comment]
Thanks for the report! Could you upload a log file from GitHub Desktop so that I could get some more information about this issue? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue. Thanks!
