### ISSUE TITLE
AUTHENTICATION PROBLEM

### ISSUE THREAD

**Issue by ghost** [desktop/desktop#14984]
WHENEVER I TRY TO CLONE A FILE IT KEEPS SAYING "FATAL REPOSITORY'' THIS FATAL REPOSITORY THAT

**Comment by sergiou87** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
