### ISSUE TITLE
"Publish branch" button mentions GitHub for non-GitHub repos

### ISSUE THREAD

**Issue by mdiep** [desktop/desktop#1498]
### Description

<img width="259" alt="publish-branch" src="https://cloud.githubusercontent.com/assets/1302/26119204/7b54cf62-3a3a-11e7-960a-02d6e074eca7.png">

For a non-GitHub repo, that button doesn't actually publish to GitHub. (It doesn't seem publish anywhere because it's not picking up authentication… but that's a different bug.)

### Version

**GitHub Desktop version:** 0.5.3
**OS version:** 10.12.4

### Steps to Reproduce

1. Open a repo that has a non-GitHub remote

**Comment by shiftkey** [comment]
> For a non-GitHub repo, that button doesn't actually publish to GitHub.

Good point. What sort of remote is this (Bitbucket/GitLab/self-hosted)? 

> (It doesn't seem publish anywhere because it's not picking up authentication… but that's a different bug.)

Yeah, we haven't focused on non-GitHub accounts. We had some tricks with the existing applications but those haven't been brought across.

I'll let @desktop/core chime in on their feels here.

**Comment by mdiep** [comment]
This particular repo was BitBucket Server, unfortunately. 😞

**Comment by niik** [comment]
Seems to me like conditionalizing the 'GitHub' part to say 'origin' (or whatever the default remote is) when the remote can't be identified as GitHub or GitHub Enterprise would solve this.

It would require tweaking [these lines](https://github.com/desktop/desktop/blob/ccb6a02e6b0c2f15e5d3f62ce20e4776d8fa84a8/app/src/ui/toolbar/push-pull-button.tsx#L131-L132) a bit.

Unfortunately that would only nets us a superficial improvement due to 👇 

> It doesn't seem publish anywhere because it's not picking up authentication… but that's a different bug.

This is https://github.com/desktop/desktop/issues/852 which we're currently planning to tackle in beta.

We should revisit this once #852 lands

**Comment by j-f1** [comment]
Why not just remove the gray text for non-GitHub remotes? It wouldn’t really add anything if the button said “**Publish branch**`\n`Publish this branch”

**Comment by joshaber** [comment]
Seems reasonable to me 👍

**Comment by mahenderd2** [comment]
It's still happening for gitlab repositories 
![image](https://user-images.githubusercontent.com/20254448/81087896-e3609980-8f17-11ea-9d26-1fd0f2b17028.png)
