### ISSUE TITLE
off screen and unable to adjust window size

### ISSUE THREAD

**Issue by EliNeedham** [desktop/desktop#14989]
### The problem

When in full screen mode github desktop is cutting off the submit button for commits. It does it when it's full screen and when it isn't. When it isn't full screen the window won't allow me to change the size in order to be able to click the button. As a result I have to exit and relaunch constantly in order to be able to commi
![githubdesktopbug](https://user-images.githubusercontent.com/69863475/179572969-939c1e4b-f1ff-43b2-b75f-4d7f89f283b8.JPG)
t

### Release version

Version 3.0.5 (x64)

### Operating system

Windows 10 

### Steps to reproduce the behavior

launch github desktop, make changes in your code, try to make a commit - the button to submit the commit is off screen.

### Screenshots

![githubdesktopbug](https://user-images.githubusercontent.com/69863475/179573226-3633bf0d-6fa2-4336-a8ae-f881495a710b.JPG)

**Comment by tsvetilian-ty** [comment]
Hey @EliNeedham thanks for the report! That issue looks related to a known set of problems caused by the Electron version used in GitHub Desktop. I suggest trying the GitHub Desktop version from the [beta channel](https://desktop.github.com/beta/); the version contains an updated Electron version that will potentially fix your issue. 

If you don't feel comfortable using a beta version, you should wait for the update to reach the production channel!

I will label the issue with `more-info-needed`, so if you decide to try out the beta, let us know if it resolves your issue.
