### ISSUE TITLE
hello github i found a bug in github dekstop app

### ISSUE THREAD

**Issue by Namanreal** [desktop/desktop#14995]
### The problem

hey i was using github dekstop for first time and when i upload and i go to publish branch it ask's me username and pass and when i fill it correctly it said me Authentication failed now i cant login and publish my project pls help me 

### Release version

3.0.5.0

### Operating system

windows 11

### Screenshots

![image](https://user-images.githubusercontent.com/90764638/179759703-40a3fc35-d172-43aa-bb80-b30ffbe89971.png)

**Comment by sergiou87** [comment]
Hi @Namanreal ! 👋  Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
