### ISSUE TITLE
The current branch is already published to github

### ISSUE THREAD

**Issue by DeathGOD7** [desktop/desktop#15017]
### The problem

Well, it just shows create pull request option even when there is only one branch. I don't know how to fix or remove it. Push or pull commits work but then afterward it would just show the "Create a pull request" dialog.

### Release version

Version 3.0.5 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

Unknown

### Log files

[2022-07-22.desktop.production.log](https://github.com/desktop/desktop/files/9167026/2022-07-22.desktop.production.log)

### Screenshots

![image](https://user-images.githubusercontent.com/36422471/180422250-f9b75dc7-3a46-464f-acaf-81ca2bc05ee5.png)

**Comment by sergiou87** [comment]
@DeathGOD7 unless I'm missing something, that should only happen if `master` is not the default branch in your repository. Do you know if `master` is the default branch? Or is that repository a fork maybe?

**Comment by DeathGOD7** [comment]
I think it's the default in my GitHub repo and it is also in my local repo.
Link to the repo : https://github.com/DeathGOD7/FIFA-3D-Importer-Exporter/

**Comment by sergiou87** [comment]
Was `master` always the default branch or did it change at some point? I think that must be it, because there is a bug (see https://github.com/desktop/desktop/issues/14266, hopefully fixed in #14985) that prevents Desktop from working properly when the default branch changes.

The condition to show that "Create PR" action depends on: being a GH repo, not being the default branch, and not having a PR created
https://github.com/desktop/desktop/blob/14a9b7c6efe70066c5bd6e3842b7bcf8e613c9ad/app/src/ui/changes/no-changes.tsx#L363-L371

If you do `View` -> `Toggle Developer Tools`, then click on the `Application` tab, and then on the left pane `IndexedDB` -> `Database - file://` -> `gitHubRepositories`, and look for your repo in the list, then expand it and you will see the `defaultBranch` persisted for your repo (probably something different than `master`).
![2022-07-25 at 09 38](https://user-images.githubusercontent.com/1083228/180723645-b8f46c72-0121-47a7-bf09-5f5da4550419.png)

**Comment by DeathGOD7** [comment]
> Was `master` always the default branch or did it change at some point? I think that must be it, because there is a bug (see #14266, hopefully fixed in #14985) that prevents Desktop from working properly when the default branch changes.

It was main and I changed from the GitHub page and did all the commands it suggested to run in the local remote repo.

Also, the developer inspect tools seem to get all old and previous named repo that is no longer available locally or on GitHub.
And for info, the repo used to be closed source but I made it open-source for people to get involved in its development.
(It used to be named like second but I changed the name after it got open-source. Also, there was a docs repo named exact same which got deleted or merged together the same day it went open-source.)

Image (Based on your request.... and it is main) :
![image](https://user-images.githubusercontent.com/36422471/182082771-0529f15e-9862-47f1-9a7f-8bd50d2cac52.png)
  
Thank you for looking into it. And sorry for late response.

**Comment by DeathGOD7** [comment]
Also, I even tried to clear the site cache from the developer tool. (didn't help and I had to add the repo to the list again :) )

**Comment by sergiou87** [comment]
@DeathGOD7 if you changed the branch name, hopefully the bug is fixed in the latest beta from https://desktop.github.com/beta

Please, give it a try and let me know if that helps!

**Comment by DeathGOD7** [comment]
> @DeathGOD7 if you changed the branch name, hopefully the bug is fixed in the latest beta from https://desktop.github.com/beta
> 
> Please, give it a try and let me know if that helps!

Well, it is fixed in beta but I don't want to use the beta version as there might be some bugs. I will wait for the stable release.
I wish we could use 2 installs of GitHub desktop like beta and stable release.

**Comment by sergiou87** [comment]
@DeathGOD7 the stable release 3.0.6 with the fix is out! 😄 

I assume this can be closed if it worked fine in beta for you. Thanks for your feedback and patience! 🙇‍♂️
