### ISSUE TITLE
Helper tool dialogue box popping up ceaselessly

### ISSUE THREAD

**Issue by HedvigS** [desktop/desktop#15023]
### The problem

This is the same/similar as #10777 #3616 and I'm struggling to solve it. I've tried reading through the thread but I don't understand what's going on or what I should do. I would like to avoid manipulating root access on my machine.

Filling out the required information does not make it go away. I'm on a macbook pro, OS 11.6.4. Github desktop Version 3.0.2 (x64)

### Release version

3.0.2 (x64)

### Operating system

Mac OS 11.6.4

### Steps to reproduce the behavior

1. Have Github Desktop Running
2. get dialogue box
3. fill out admin details
4. nothing seems to happen, dialogue box appears after minutes again.

### Screenshots

![Screenshot 2022-07-23 at 13 46 39](https://user-images.githubusercontent.com/5327845/180603629-74bb585b-1a05-4061-974d-79114bbcd432.png)

**Comment by sergiou87** [comment]
Hello @HedvigS 👋 

This happens because there is something in your computer (I'm guessing some kind of backup restoration tool?) that is bringing back a previous installation of GitHub Desktop, but messes up the file permissions, causing this problem.

As mentioned in https://github.com/desktop/desktop/issues/3616#issuecomment-400371047, you might need to `chown` the app's folder, which basically means you need to open a terminal and run `sudo chown -R <your-mac-username> "/Applications/GitHub Desktop"` or just delete GitHub Desktop and install it again.

Every time that "restoration tool" (or whatever it is) replaces the app will mess up the permissions and you will need to do this again 😞 

I hope that helps!

**Comment by jasonburrows** [comment]
I have this - new install, not restored from backup.  I have two users on the computer, both admin, and it happens with both of them.  

I get the permissions thing, but I use this application with multiple user accounts - all this solution does is let me choose which user has the problem.  It isn't a real solution.  

No other applications have this issue regardless of which user I'm logged in as.  

...if I'm being prompted for an admin account anyway - why doesn't it just manage the permissions itself?

**Comment by sergiou87** [comment]
Hey @jasonburrows ! This seems to be a problem with [the way Electron apps auto-update](https://www.electronjs.org/docs/latest/api/auto-updater) themselves via [Squirrel.Mac](https://github.com/Squirrel/Squirrel.Mac) 

That's why this problem should *ideally* be fixed on Squirrel.Mac or Electron, not on Desktop 😕
