### ISSUE TITLE
Impossible to delete a tag

### ISSUE THREAD

**Issue by leonardo-collazo** [desktop/desktop#15039]
### The problem

I have a commit with two tags and I can't delete both tags.

### Release version

Version 3.0.5 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Go to tab "History"
2. Select the commit with two tags
3. Right click the commit
4. Select the option "Delete tag tagName"
5. But the tagName is disabled. I can't select it.

### Screenshots

![GitHub Desktop 7_27_2022 12_29_17 AM](https://user-images.githubusercontent.com/88118667/181161843-d6a10d61-2c79-4bfa-8410-60fe70db1341.png)

### Additional context

In the screenshot is not visible the disabled options because the screenshot does not capture the menu when your right click the commit

**Comment by tsvetilian-ty** [comment]
@KidBourbon thanks for reaching out! The issue is that the tags are already pushed to the server. Currently, GitHub Desktop doesn't support any type of retagging operations on tags pushed to a remote. You can read more about it in https://github.com/desktop/desktop/issues/9938#issuecomment-638779503

**Comment by leonardo-collazo** [comment]
Hello Tsvetilian Yankov. Thanks for the information!
