### ISSUE TITLE
Publish GitHub Desktop in the Windows Store

### ISSUE THREAD

**Issue by Studio384** [desktop/desktop#1504]
Make GitHub available in the Windows Store.

#### Provide a step-by-step description of the suggested enhancement in as much detail as possible. This additional context helps the maintainers to understand the enhancement from your perspective
N/A

#### Explain why this enhancement would be useful to GitHub Desktop users.
Provide a central place to update GitHub, support for UWP APIs (like live tiles), and make it available for Windows 10 S users.

#### Include screenshots and animated GIFs if relevent to help you demonstrate the steps or point out the part of GitHub Desktop which the suggestion is related to. You can use this tool to record GIFs on macOS and Windows.
N/A

#### List some other applications where this enhancement exists, if applicable.
Photoshop Elements, iTunes (soon), WhatsApp (soon), Evernote, Office, etc.

**Comment by citrusui** [comment]
I'm not sure if this is possible with the use of Electron. [See here.](https://msdn.microsoft.com/en-us/library/windows/apps/dn764944.aspx#pol_10_2)

> Apps that browse the web must use the appropriate HTML and JavaScript engines provided by the Windows Platform.

**Comment by Studio384** [comment]
There are already plenty of Electron apps in the Store. GitHub Desktop doesn't browse the web. It doesn't apply. The Visual Studio Code team is also looking into this bridge, so it is definitely possible.

Heck, there is even a guide on the Electron website itself: https://electron.atom.io/docs/tutorial/windows-store-guide/.

**Comment by shiftkey** [comment]
> The Visual Studio Code team is also looking into this bridge, so it is definitely possible.

@Studio384 I'm very curious about their findings, as there might be things their app does that don't play nice in a sandboxed mode (for example, we invoke Git a lot).

**Comment by Studio384** [comment]
Microsoft/vscode#19239

**Comment by dgsimone15** [comment]
I also think it's a good idea to bring GitHub to the store

**Comment by duble0** [comment]
Converting a win32 in appx will transform the concept of "software" because is important go in the same direction of changes that new generations loves. When I was young my friends want know Linux, but today new students want know how write apps, this is the time mark! So transform github in app adding to it simplicity and confort to the user. A software converted in UWP using a virtualized Registry and File System, so not spread files around PC that cause a general degradation of OS. Furthermore install and uninstall is easy, you could have easily GitHub in every pc you are logged, if there is a bug in your software it can't compromise the OS because UWP run sandoboxed. In other the developer could use telemetry for the app that report about what are the problems and after correct it, all app already installed will be update automatically.  Remember that software converted in UWP could run on Windows S and every normal Windows 10 PC, so you can also change your distribution method for take the advantages that I wrote; in the future could also be use in holographic devices for work. Least but last: Windows 10 S is already launched, this system is focused in education area and GitHub is a perfect way for show to the world important projects in my opinion school is the place to sprout open source projects.
We don't know what will be in the evolution of technology but we must be prepared for the changes!

**Comment by citrusui** [comment]
@Studio384 thanks for the link. This is actually really interesting though... in the same sense, could Atom be ported to the Store? It doesn't technically browse the web, or, at least, [not yet.](http://blog.atom.io/2017/05/16/git-and-github-integration-comes-to-atom.html)

**Comment by RichiCoder1** [comment]
@citrusui Yup! It absolutely could.

@shiftkey TL;DR for @Studio384 issue link (which is great), you can put Github Desktop in the store and opt out of the sandbox, you just won't be xplat (mobile, xbox, holo) since you're not UWP. Still a great delivery and update model though.

**Comment by dgsimone15** [comment]
You also have access to the Windows Dev Center that saves you a lot of time and costs during development. Use beta testers, check your application's performance, distribute it differently from nations, use feedback system integrated into the Etc ... Etc ...
Sorry for my poor english

**Comment by shiftkey** [comment]
Tagging this as `future-work` as our 1.0 work and stabilization is the current focus.

**Comment by duble0** [comment]
Ok, sorry you probably want know something more about functions...I think that could be easy and functional ad a notification in Windows action center when somebody do a new commit on your repo, or you can implement function with Windows Flow and Graph.
Or why not using the OneDrive cloud to synchronize online file with mobile devices that use android or iOs...

**Comment by duble0** [comment]
@shiftkey I think that a simply conversion with Centennial take not so much time, one you are in the Store you can optimize your software every time you desire and a beautiful thing is that all people will be automatically updated. This is a good way for rapid improvement!...for example you can add a message inside the appt that after an update explain the changes and request a feedback...

**Comment by duble0** [comment]
@citrusui @shiftkey @RichiCoder1 @dgsimone15 @Studio384 
Hi folks! a guy of [UWP Open Source Community](https://github.com/UWP-Open-Source-Community) had just converted your Desktop release. you can try it [here](https://1drv.ms/u/s!Ak7XeOLujuj5gWuyQE35jC75WZdf)
Anyway ok, there are some problems in the software as downloaded from your website...

**Comment by rogersachan** [comment]
@Studio384 See https://github.com/felixrieseberg/electron-windows-store on the bridge.

Regarding VSCode's exploration into this, they have been successful - but they are working on how testing and building would be done.

**Comment by rogersachan** [comment]
> For those interested in the results of the investigation… We used the desktop app converter to convert VS Code to a UWP app that uses the Desktop Bridge (aka a “Centennial” application) that provides a Windows Store setup experience and access to a subset of the full UWP API. The conversion worked quite well and we were able to side load VS Code as a Windows Store application with **no loss of functionality**.

> So, this closes the investigation for the product itself. The next investigation we would need to do is understand **how to adapt our internal build systems to produce daily/monthly builds that can be published through the Store**. Once that is understood, we will decide if and when it makes sense to move forward with this effort and actually put it on the backlog.

**Comment by rogersachan** [comment]
To sum it up, VSCode's issue is that they need to have a build system so they can do nightly betas on the store. I assume that GitHub has no plans on doing nightlies for desktop.

**Comment by duble0** [comment]
> For those interested in the results of the investigation… We used the desktop app converter to convert VS Code to a UWP app that uses the Desktop Bridge (aka a “Centennial” application) that provides a Windows Store setup experience and access to a subset of the full UWP API. The conversion worked quite well and we were able to side load VS Code as a Windows Store application with no loss of functionality.
> So, this closes the investigation for the product itself. The next investigation we would need to do is understand how to adapt our internal build systems to produce daily/monthly builds that can be published through the Store. Once that is understood, we will decide if and when it makes sense to move forward with this effort and actually put it on the backlog.
I think that this method is similar to Telegram Preview, or WhatsApp Desktop Preview, right?

**Comment by rogersachan** [comment]
@duble0 Correct. This is the easiest and most compatible way to go.

**Comment by joshaber** [comment]
Thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I'm going to add the `future-proposal` label to this issue and close it out, so that we don't get overwhelmed with our backlog! We'll revisit these as part of our next planning session.

**Comment by datdhruv** [comment]
Hi, since the last discussion, Microsoft has opened up their store for different [frameworks than UWP](https://blogs.windows.com/windowsdeveloper/2021/09/28/microsoft-store-more-apps-more-open/), Like Electron.
VS Code is now Distributed via the MS Store and so is are Browsers like Firefox and Opera

Maybe the Future is now? And we can look into publishing to the MS Store for easier accessibility. (Would love to help out!)
