### ISSUE TITLE
have option to pull from upstream

### ISSUE THREAD

**Issue by feinbd** [desktop/desktop#15052]
### The feature request

currently a branch can pull or update from master.  however when i work on my branch, I don't want to have to go to the command line and update my master from upstream and then update my branch from master.  

This is a common operation, i need to do it every time i have a PR approved or start any new work to pick up work from others.

### Proposed solution

currently i have to go to git bash and pull from upstream/master, it would be nice if there were a way to pull from there in the quick options or if there were a "pull..." command and it let you select that branch (if it's not easy to tell what the main branch of upstream is called, we're switching from master to main for instance so sometimes it's one, sometimes it's the other).  

having this on the main screen where you can open in editor, create a PR, etc would be helpful as this is something done every time before work begins.

**Comment by steveward** [comment]
Thanks for the issue @feinbd. We did recently merge https://github.com/desktop/desktop/pull/14199 which allows for quickly updating from the upstream default branch. You can also select upstream branches to merge from when using `Merge into current branch`. This is something we're looking into making easier in the future, though. See https://github.com/desktop/desktop/issues/8509 for the issue that was previously created to track these improvements. I'm going to close this out since we are tracking this elsewhere.

**Comment by feinbd** [comment]
thank you!  love the product by the way!
