### ISSUE TITLE
Always refreshing repository, never stop

### ISSUE THREAD

**Issue by indra11wijaya** [desktop/desktop#15065]
### The problem

Always refreshing repository, never stop

### Release version

Version 3.0.5 (x64)

### Operating system

Windows 10

### Screenshots

![image](https://user-images.githubusercontent.com/78585876/182346017-41ed9f0c-23a2-411f-96c9-9d2238f3a88c.png)

**Comment by steveward** [comment]
Thanks for the issue @indra11wijaya. Could you send over the log file from GitHub Desktop so that I could get some more information about this error?

To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by indra11wijaya** [comment]
[2022-08-03.desktop.production.log](https://github.com/desktop/desktop/files/9247245/2022-08-03.desktop.production.log)

**Comment by steveward** [comment]
Thanks for the log @indra11wijaya, here's the relevant error:

```
2022-08-03T01:36:29.891Z - error: [ui] Branch fast-forwarding failed
Error: Failed to execute getBranchesDifferingFromUpstream: EPERM
```

This looks like a permissions issue. Is this only happening on one specific repository, or can you reproduce it across multiple repositories in GitHub Desktop?
