### ISSUE TITLE
argon assault udemy 3 

### ISSUE THREAD

**Issue by DavidJB2** [desktop/desktop#15077]
### The problem

when trying to commit the files i get a lock file is in place and i cant commit the repository

### Release version

Version 3.0.5 (x64)

### Operating system

windows 10

**Comment by steveward** [comment]
Thanks for the report @DavidJB2. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by DavidJB2** [comment]
[2022-08-04.desktop.production.log](https://github.com/desktop/desktop/files/9260503/2022-08-04.desktop.production.log)
there is the file

**Comment by DavidJB2** [comment]
i am taking a game developing course so i need my data uploaded so the teacher might let me know what could be the issue on my probs in the course, and i am quite new using this srry for that.

**Comment by steveward** [comment]
@DavidJB2 the error in the log is showing an issue with long paths -- you can resolve that specific issue by running this command:

`git config --global core.longpaths true`

The lock file issue isn't showing in the log, but normally that's caused by an application holding the file open. Does it show the lock file in the error message? You can delete the lock file if it's not going away and try committing again.

**Comment by DavidJB2** [comment]
nope how would i go determining which is the lock file that the github desk is impliying cuz i dont remeber putting anything like that.

**Comment by DavidJB2** [comment]
nvm that somehow it seems to be uploaded now, i am not 100% sure but seems that way.

**Comment by DavidJB2** [comment]
it just posted that there is a lock file but let me check that now xd
