### ISSUE TITLE
Sync my git repos in GitHub Desktop with my project folder

### ISSUE THREAD

**Issue by teonbrooks** [desktop/desktop#15070]
### The feature request

For my different projects, I organize all the project folders under one folder (e.g. codespace/project_a, codespace/project_b). It would be awesome if there were an option in GitHub Desktop to import the parent folder and it would import the children project folders. At the moment, I have to import each project individually.

### Proposed solution

Under the Add Menu, I would like there to be an import a codespace of repositories, where it would traverse across the children project folders and then look for the .git directory, and add the project folders that have one.

**Comment by steveward** [comment]
Thanks for the issue @teonbrooks. You can select multiple repositories in your file browser and drag-and-drop them into GitHub Desktop to add them all at once. I hope that is helpful! I'm going to close this out since at this time we don't have plans to add a specific import feature, but this has been previously requested in https://github.com/desktop/desktop/issues/1574.
