### ISSUE TITLE
Template error

### ISSUE THREAD

**Issue by juni-core** [desktop/desktop#15083]
error: invalid path 'templates/bundles/TwigBundle/Exception/error.html.twig '
Updating 3e78f5b..2976c65
![Capture](https://user-images.githubusercontent.com/78807623/183222440-51d8a420-4a15-4d4e-95ed-9793b1fac030.JPG)

**Comment by steveward** [comment]
Thanks for the issue @juni-core. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
