### ISSUE TITLE
Scroll

### ISSUE THREAD

**Issue by securing-ab** [desktop/desktop#15080]
### The problem

I was randomly scrolling and encountered this error:
TypeError: Cannot read properties of undefined (reading 'find')
    at file:///app/renderer.js:2:32799
    at file:///app/renderer.js:2:33028
    at Qr (file:///app/renderer.js:2:98770)
    at Ts.operation (file:///app/renderer.js:2:202285)
    at t (file:///app/renderer.js:2:32424)
    at file:///app/renderer.js:2:94750
    at Vr.t (file:///app/renderer.js:2:94785)
    at Vr (file:///app/renderer.js:2:94811)
    at HTMLDocument.<anonymous> (file:///app/renderer.js:2:98930)

### Release version

3.0.5

### Operating system

Windows 10.0.25169

**Comment by steveward** [comment]
Thanks for the report @securing-ab. What specific area of the app were you scrolling through?

Could you also upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue. Thanks.
