### ISSUE TITLE
Desktop Issue , problems pushing to origin

### ISSUE THREAD

**Issue by Loyzahk** [desktop/desktop#15090]
### The problem

Hello, I have been trying to upload some files to my repository, I have tried it from GitDesktop and from Git (terminal)
In both cases I get the same problem.

This problem happens to me in both of my Operating Systems.

### Release version

Version 2.9.5

### Operating system

Windos 10 Pro Doffy / Kali Linux 

### Screenshots

It stays frozen here for a long time
![Screenshot_1](https://user-images.githubusercontent.com/95712901/183274461-9b3759c4-8e96-402d-949f-d147d9250811.png)

and then it throws me this error
![Screenshot_2](https://user-images.githubusercontent.com/95712901/183274538-65080209-91a0-483d-b7d4-78f0ccd6ba15.png)

### Additional context

Enumerating objects: 491, done.
Counting objects: 100% (491/491), done.
Delta compression using up to 8 threads
Compressing objects: 100% (475/475), done.
Writing objects: 100% (490/490), 145.28 MiB | 190.48 MiB/s, done.
Total 490 (delta 188), reused 0 (delta 0), pack-reused 0
error: RPC failed; curl 55 Send failure: Connection was aborted
send-pack: unexpected disconnect while reading sideband packet
fatal: the remote end hung up unexpectedly
Everything up-to-date

**Comment by steveward** [comment]
@Loyzahk thanks for the issue. Unfortunately this type of error can often just be caused by a connection issue. Are you trying to push a large number of files? Are you on a reliable network? Are you behind any sort of proxy or firewall? If you can try pushing on a different network that would help narrow down the issue.

Some users have also had success switching to use SSH instead of HTTPS. If you're interested in learning how to set a new SSH key you can follow [this guide](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent).

**Comment by Loyzahk** [comment]
There are no heavy files, the total of the entire repository is 6 GB, but no file exceeds 100 megabytes, anyway I thought it was because of the weight of the files, and then try to upload the repository in parts.
It only lets me push to origin if the file is 1 mb

I am on a Wi-Fi network that a neighbor has entrusted to me, because I recently became independent and since then I have not been able to contract internet service, the internet is not very stable, but at certain times when no one is using it, the internet reaches a speed of 500kb/s, and until then, I hadn't had any problems doing push to origin, but I'm sure it has something to do with it.

I will try to see that guide, and if it does not work for me, I will try to use another internet network, in case I continue with my problem, I will make a publication again.
