### ISSUE TITLE
commit button is not visible in github desktop

### ISSUE THREAD

**Issue by akshatsolanki1205** [desktop/desktop#15112]

**Comment by akshatsolanki1205** [comment]
![Screenshot (44)](https://user-images.githubusercontent.com/111217813/184543553-df03a1d5-5e5a-4bcd-b963-309956e817ff.png)

**Comment by kaushal1999** [comment]
facing the same issue

**Comment by niik** [comment]
Hey @akshatsolanki1205, thanks for reaching out. What is your screen resolution? GitHub Desktop has a minimum size of the Desktop app is 960x660 px and it looks like you may be running into that limitation. The image you sent is 1920x1080 and I'm guessing you're running that at 200% DPI so effectively 960x540.

See https://github.com/desktop/desktop/issues/1702 for more information on the minimum height

**Comment by tsvetilian-ty** [comment]
There are similar reports such as https://github.com/desktop/desktop/issues/14989, https://github.com/desktop/desktop/issues/14136, and https://github.com/desktop/desktop/issues/14074. These issues are caused by the Electron version used in GitHub Desktop. 

You could try out the [beta version](https://desktop.github.com/beta/) that contains an updated electron version!
