### ISSUE TITLE
Cannot Add Multiple Accounts

### ISSUE THREAD

**Issue by be-thomas** [desktop/desktop#15115]
### The problem

The Github Desktop has a bug, i.e., it doesn't let you add multiple accounts.

This is NOT a feature request. Its A BUG.
Because managing user accounts is a core feature and it is definitely included in the development specification of Git Desktop .
However it is missing the implementation. Therefore it is a bug.

There had been a feature request before which had been closed - #3707 
it had been denied & dismissed completely (I see it was closed a while ago).
It should be "bug report" and not a "feature request". As it is nearly impossible for such a core feature to not be in development specification.

Can we please fix this bug?

### Release version

Version 3.0.5 (x64)

### Operating system

Windows 11

### Steps to reproduce the behavior

1. Open Github Desktop
2. Go to File > Options > Accounts
3.  There is no option to "Add Account"

**Comment by FrenkyDema** [comment]
+1

**Comment by be-thomas** [comment]
Since that old issue was closed, we can track the progress in this new issue, or that old issue must be re-opened.
Thanks

**Comment by steveward** [comment]
@be-thomas thanks for the feedback, but please don't open duplicate issues if there is an existing issue that is already tracking feedback for the same feature request. Even if an issue is closed it does not mean it is something we will not consider implementing in the future.  This is something we have been discussing since we understand that it's becoming more common for users to have multiple accounts, and we may revisit the existing issue again. 

I'm going to close this out, but please subscribe to #3707 for updates.

**Comment by rsodre** [comment]
I agree on closing duplicates, but what kind of update can we expect on a **closed** issue?

**Comment by utkarshraj123180** [comment]
No issue leave it
