### ISSUE TITLE
Not letting me login when using ubuntu

### ISSUE THREAD

**Issue by THageman88** [desktop/desktop#15131]
### The problem

It is currently not letting me log into github to upload a repository. I made sure everything is up to date and it still keeps giving me error login at the terminal side , the exact message is
 Username for 'https://github.com': Thageman88
Password for 'https://Thageman88@github.com':
remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/THageman88/first-repo.git/' 

how do I fix this?

### Release version

3.0.5

### Operating system

windows 11

### Screenshots

![image](https://user-images.githubusercontent.com/111379263/185241059-130bdbc5-0e8e-48a5-b0c7-91f96ba16516.png)

**Comment by tsvetilian-ty** [comment]
@THageman88 thanks for reaching out! Your issue doesn't seem to be related to GitHub Desktop. It looks like you're trying to login through the terminal with your GitHub password, but since [August 13, 2021](https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/) you need to use [personal access token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token).

In GitHub Desktop, you can use the automated way to sign in to GitHub (File > Options > Sign In > Continue with browser). If you still want to do it in the terminal, make sure you get your [PAT](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token)

I'll close the issue.

**Comment by SamuelRUM** [comment]
I have this issue even when logging in through GitHub desktop

**Comment by ClaudioA1992** [comment]
i'm having the same issue while trying to push or fetch from a private repo. Tried adding ssh key, private token, and nothing. But then i created the folder again and cloned it after i posted it online manually and then i had no problem on that. But i still cannot connect a local Jenkins instance on a Ubuntu VM to Github, sends the "Failed to connect to repository : Command "git ls-remote -h -- git@github.com:{username}/NodeJenkinsTest.git HEAD" returned status code 128: ..."

**Comment by PauloBoaventura** [comment]
the problem still persists in the ubuntu version

**Comment by ubirehman** [comment]
Problem still persists in Ubuntu 22.04. Tried passing PAT but still won't let you authenticate.

**Comment by silkux** [comment]
The only way I can use the terminal in Ubuntu is by creating a token here: https://github.com/settings/tokens , and saving it carefully. Instead of the password, you have to use the generated token. Be careful to always save the token process... it's a very annoying and unnecessary process.

**Comment by silkux** [comment]
and then use the new token  not  the password of your account when terminal ask for pass

**Comment by silkux** [comment]
You cant download github desktop on ubuntu
