### ISSUE TITLE
can't locate Visual Studio Code

### ISSUE THREAD

**Issue by simonmcconnell** [desktop/desktop#15132]
### The problem

When vscode is installed with Scoop, GitHub Desktop is ignorant to its existence.

Any reason we can't specify the location manually?

### Release version

3.0.5

### Operating system

Windows 11

### Steps to reproduce the behavior

1. Install Scoop
2. Install vscode through Scoop
3. Open GitHub Desktop
4. Experience sadness

**Comment by steveward** [comment]
Thanks for the issue @simonmcconnell. This has been previously reported in https://github.com/desktop/desktop/issues/7033#issuecomment-533857544 as well. Work is being done in https://github.com/desktop/desktop/pull/14843 to make the editor integrations more robust -- I would recommend following along there for updates. I'm going to close this out since we're tracking these issues in #7033.
