### ISSUE TITLE
my file is not committing 

### ISSUE THREAD

**Issue by chiZomDillibe** [desktop/desktop#15156]
### The problem

I've tried uploading my file or committing but its delaying 

### Release version

3.05

### Operating system

windows 10

**Comment by steveward** [comment]
Thanks for the report @chiZomDillibe. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
