### ISSUE TITLE
The installation was showing "The entry point wasn't found in KERNEL32.dll".

### ISSUE THREAD

**Issue by Arjunpride15** [desktop/desktop#15173]
[problem.docx](https://github.com/desktop/desktop/files/9432881/problem.docx)

**Comment by niik** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
