### ISSUE TITLE
Rebase keyboard shortcut doesn't work

### ISSUE THREAD

**Issue by splintor** [desktop/desktop#15186]
### The problem

The menu item `Branch` -> `Rebase Current Branch...` is marked to have the Cmd+Shift+E keyboard shortcut (on Mac), but using that shortcut has no affect.

### Release version

3.0.6

### Operating system

Mac OS version 12.5.1 (Chip: Apple M1 Pro)

**Comment by tidy-dev** [comment]
@splintor I was unable to reproduce this issue. However, there are times when these menu items are disabled. For example, when merge, squash, or rebase is in progress, you can see this by opening the merge modal and then opening the dropdown menu to see them greyed out. Did you have any other process ongoing when trying to do this OR any other reproduction steps to add?

**Comment by splintor** [comment]
@tidy-dev I am able to start the rebase dialog from the `Branch` menu, but not using the keyboard shortcut, so I don't think the action is disabled.
I am able to raise the merge dialog using `Cmd+Shift+M`, and I'm able to raise the Squash and Merge dialog using `Cmd+Shift+H`, but when I press `Cmd+Shift+E` nothing happens... 😢

**Comment by tidy-dev** [comment]
That is curious. Wondering if you have a [conflicting shortcut](https://support.apple.com/guide/mac-help/change-a-conflicting-keyboard-shortcut-on-mac-mchlp2864/12.0/mac/12.0)?

**Comment by splintor** [comment]
Nope, I have no conflicting shortcuts...

**Comment by tidy-dev** [comment]
Hmm.. Does the rebase dialog open as expected when clicking on the menu item and does a rebase start as expected? Also mind sharing your log files in case there is an error being thrown?

**Comment by splintor** [comment]
Yes, rebase works as expected when started from the menu. I use it all the time - that's why I want the shortcut...
How do I get my log files? I don't see any errors in the Developer Tools.

**Comment by tidy-dev** [comment]
Logs can be found by going to the Help menu. `Help > Show Logs in Finder`

**Comment by splintor** [comment]
No error is being thrown when I open the Rebase dialog via the menu, or when I press Cmd+Shift+E (and nothing happens).

**Comment by tidy-dev** [comment]
Asked the team if anyone had heard of something like this and there has been issues for shortcuts involving special keys like + or -  coupled with non-US keyboard layouts. This keyboard shortcut doesn't have + or - and since the other shortcuts work I would think that this wouldn't apply... but figured I would note it here. 

At this point, I have no further ideas on how to test it and without a way to reproduce, I cannot investigate further.  I will leave this open tho in case we have another user that runs across this and we can find some similarity between environments to try to pin point it down.

**Comment by splintor** [comment]
OK, thanks!

**Comment by splintor** [comment]
Not sure if it was fixed or if anything changed in my env, but with the recent version of GitHub Desktop, Cmd+Shift+E now opens the Rebase dialog.
