### ISSUE TITLE
Head is not publish to github

### ISSUE THREAD

**Issue by starydv7** [desktop/desktop#15184]
### The problem

Not able to push code

### Release version

latest

### Operating system

window 10

### Steps to reproduce the behavior

Not able to push code

**Comment by steveward** [comment]
Thanks for the report @starydv7. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
