### ISSUE TITLE
not enough memory to process

### ISSUE THREAD

**Issue by gatorlanphear** [desktop/desktop#15188]
### The problem

I cannot get GitHub desktop to sign in to the web - When I try to "Clone Repository" and the desktop app wants me to sign in via github.com and I continue through browser, I receive the ERROR: Not enough memory resources are available to process this command.

I cannot rectify this. Please advise.
gator

### Release version

I don't know. I just downloaded it today

### Operating system

Windows 11 Home

### Steps to reproduce the behavior

1. open GitHub desktop
2. File > Clone repository
3. Github.com Sign in
4. Continue with browser
5. Open GithubDesktop.exe
6. then error pops up: Not enough memory resources are available to process this command

### Screenshots

![Screenshot 2022-08-28 121554](https://user-images.githubusercontent.com/112341620/187090808-40832bb4-37b2-46db-a598-f4a27cc669f2.jpg)

**Comment by steveward** [comment]
Thanks for the report @gatorlanphear. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
