### ISSUE TITLE
Slow actions

### ISSUE THREAD

**Issue by kmcdaniel-d2l** [desktop/desktop#15195]
### The problem

Since updating on August 24th, Commiting and pulling have been noticeably slower. Taking around 30 seconds for a single action. Whereas, these actions would have been fairly instantaneous previously.

### Release version

Version 3.0.6

### Operating system

Windows 10

### Steps to reproduce the behavior

Commit any sized change to a repo

**Comment by steveward** [comment]
Thanks for the report @kmcdaniel-d2l. We've been tracking similar issues in https://github.com/desktop/desktop/issues/13586. Could you upload the log file so I could take a look?

To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue. 

Since we are already tracking reports of this I'm going to close this issue out and reference it in #13586. You can follow along there for updates on this.
