### ISSUE TITLE
Can't create a Desktop account

### ISSUE THREAD

**Issue by Naldo47** [desktop/desktop#15206]
### The feature request

Can't create a tutorial repository, because it sait the users already exists, but it don't.

### Proposed solution

shange or rmove.

**Comment by steveward** [comment]
Thanks for the report @Naldo47. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by Naldo47** [comment]
Hi Steveward thanks for your help, What happened is that I am trying to download the desktop and when I try to create a" tutorial respository" it says  that the "user already exists please move it out of the way or remove it and then try again" but I did and still don't work. What do I have to do to solve this, thanks.

**Comment by Naldo47** [comment]
[2022-08-30.desktop.production.log](https://github.com/desktop/desktop/files/9473578/2022-08-30.desktop.production.log)
 Hi this is the file.

**Comment by steveward** [comment]
@Naldo47 apologies for the delay -- I'm not seeing any errors in the log file related to tutorial creation. Can you share a screenshot of the error you are seeing?

**Comment by steveward** [comment]
Closing as stale -- let us know if you are still having issues and we can investigate further.
