### ISSUE TITLE
Upload files exceeding limit

### ISSUE THREAD

**Issue by Javen05** [desktop/desktop#15207]
### The problem

I can't upload my files that exceed limit to github even afterusing GitHub Desktops

### Release version

no clue

### Operating system

Windows 11

### Steps to reproduce the behavior

1. Github Desktop App
2. Create local repo and upload files
3. Upload Repo to Github
4. Only gitAttributes got uploaded on GitHub Website

**Comment by steveward** [comment]
Thanks for the issue @Javen05. Are you referring to the large file limits? Can you share a few more details about the errors you are encountering?

Could you also upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
