### ISSUE TITLE
Remember login

### ISSUE THREAD

**Issue by Lars-jnk** [desktop/desktop#15203]
### The problem

There was a time when my login data was remembered for several weeks. Now I have to enter my password nearly everytime, even at the same day.
Fix it asap!

### Release version

latest

### Operating system

win10

**Comment by sergiou87** [comment]
Hi @Lars-jnk !

Sorry about that, it's a known regression (see #15163) that has just been fixed in the latest 3.0.7 that we just released a few hours ago. You can update immediately from the About dialog. If it doesn't find a release (**it's not enabled to _all_ users yet**), try hold <kbd>Alt</kbd> on your keyboard and then click on the `Ensure Last Version` button to force the upgrade:

https://user-images.githubusercontent.com/1083228/187416390-01ee032d-8dca-4635-ab0e-a3c4c87e4c5d.mov

You can also download it from https://desktop.github.com

**Comment by Lars-jnk** [comment]
That was really good example for asap and it seem to work so far. :)

Thanks guys!
