### ISSUE TITLE
Octokat returns an empty string when connection is refused

### ISSUE THREAD

**Issue by niik** [desktop/desktop#1522]
I added an entry to my hosts file to stop all trafic to `api.github.com` and then tried to launch the app. It didn't work.

Turns out that when a request in Octokat fails du to a connection refused error the only thing we get back is an empty string. No error, no nothing.

This is even more disconcerting given that the whole octokat client is untyped (`any`) so we tell blatant lies to the type system.

Take this example

![image](https://cloud.githubusercontent.com/assets/634063/26130704/3f1e2fb4-3a96-11e7-8c96-e02bb9a473d0.png)

We assert that we return a readonly array of emails when in fact we might end up returning an empty string if there's a connection error.

We probably need to go fix this in octokat and then make sure that we deal with the ensuing errors because right now we're hiding potential incoherent state.

I'll open up a PR shortly to take work around the blockers that prevent the app from launching but we'll need a better strategy for this, and soon.

**Comment by shiftkey** [comment]
> We probably need to go fix this in octokat and then make sure that we deal with the ensuing errors because right now we're hiding potential incoherent state.

:thumbsup: they've been pretty great at taking in our changes already, so I think they'd be open to improving this as well

**Comment by philschatz** [comment]
Howdy!  I'm the developer of Octokat.

https://github.com/philschatz/octokat.js/pull/170 switches Octokat to use the `fetch` API directly which might help with this problem. You can test it by using the pre-release version`v0.9.0-0`.

If that does not work, I will probably need to switch Octokat to yield an object that contains:

1. the `Response` object
1. any parsed headers (like `rate_limit` and `Link:` headers needed for pagination)
1. and the result

Those would be breaking changes but I could probably fix up `desktop`.

It may take a little while to make those changes since I work on Octokat in my spare time.

Regarding typescript definitions, that would be a great feature; I can try that once the `response.status == 0` is working for you.

**Comment by niik** [comment]
@philschatz Switching to fetch sounds like a wonderful plan, thanks for letting us know about it!

**Comment by shiftkey** [comment]
Updating to 0.9.0 seems to yield better errors from the `fetch` API:

<img width="1414" alt="screen shot 2017-05-25 at 1 24 39 pm" src="https://cloud.githubusercontent.com/assets/359239/26448440/8f0863ba-414d-11e7-82f6-d2877b4a2d9e.png">

@niik was this how you were testing the behaviour? Or is there something else I should do in here?

<img width="600" src="https://cloud.githubusercontent.com/assets/359239/26448332/f00130a8-414c-11e7-9c23-1840bee2a8e8.png">

**Comment by shiftkey** [comment]
Picking this one up as I think updating to `0.9.0` will help here

**Comment by niik** [comment]
> @niik was this how you were testing the behaviour? Or is there something else I should do in here?

Yup, that's exactly how I was doing it
