### ISSUE TITLE
Update from parent branch

### ISSUE THREAD

**Issue by SHOSH-NI** [desktop/desktop#15233]
### The feature request

When working on your own branch you often need to update from another branch.

GitHub Desktop already offers:

- Update from DEFAULT_BRANCH_NAME
- Merge / Squash & merge into current branch
- Rebase current branch

But lacks an easy access to the one likely option you usually will need the most -
To merge from the parent branch your work is based on.

With the easiest way to do so requires scrolling inside the "Merge / Squash & merge into current branch" option until you find that branch, leading to a workflow where you usually end up using "Merge / Squash & merge into current branch" multiple times.

### Proposed solution

Either an option to change `Update from DEFAULT_BRANCH_NAME` to `Update from parent branch` which will require a lookup each time the window is opened or to keep up to date this information at some other procedure.

Or changing `Update from DEFAULT_BRANCH_NAME` to instead point to the most recent branch you merged commits from.
Which could also be based on the current branch, having this information saved separately for branches you've worked on locally.

### Additional context

![Screenshot (3)](https://user-images.githubusercontent.com/26509613/188499553-b635e082-86f2-4005-82d0-3008fb872e72.png)

**Comment by tidy-dev** [comment]
@STRONG-MAD Thank you for your suggestion! I can surely understand having a workflow were this feature could be handy. However, GitHub Desktop supports the standard git flow of creating feature branches off of a main or default branch. Additionally, the concept of "updating from a parent branch" is not naturally supported by git (the underlying technology of Desktop) via the command line since branches are just references to specific starting commits.
