### ISSUE TITLE
Authentication is Failed

### ISSUE THREAD

**Issue by Venk6195** [desktop/desktop#15234]

**Comment by Venk6195** [comment]
authentication failed

**Comment by sergiou87** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
