### ISSUE TITLE
Can't log in to Gitlab

### ISSUE THREAD

**Issue by machiecodes** [desktop/desktop#15254]
### The problem

Trying to log into Gitlab when the popup happens with my Username and a freshly generated PAT, but no matter how many I make or how long I wait, it simply fails to validate and the popup reappears.

### Release version

3.0.7

### Operating system

Windows 11

### Steps to reproduce the behavior

Clone a repo from Gitlab
Make a change
Try to open a pull request
Attempt to log in with your Gitlab username and PAT
Fail to authenticate

**Comment by steveward** [comment]
@RickyTheRacc thanks for the issue. Are you following [these steps](https://github.com/desktop/desktop/blob/development/docs/integrations/gitlab.md) to authenticate to GitLab? 

It would be helpful if you could share the log file from GitHub Desktop so that I could see the specific errors. To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
