### ISSUE TITLE
Have a sync with original branch button for forked repos.

### ISSUE THREAD

**Issue by jacoby149-pt** [desktop/desktop#15250]
### The feature request

If I fork a repo, I have to go on github.com to sync branches with the original repo, there is no easy button in Github Desktop to sync.

### Proposed solution

Make a button that lets you sync a branch with the original repo it comes from.

**Comment by steveward** [comment]
Thanks for the issue @jacoby149-pt. We did recently merge https://github.com/desktop/desktop/pull/14199 which allows for quickly updating from the upstream default branch. You can also select upstream branches to merge from when using `Merge into current branch`. This is something we're looking into making easier in the future, though. See https://github.com/desktop/desktop/issues/8509 for the issue that was previously created to track these improvements. I'm going to close this out since we are tracking this elsewhere.

**Comment by thienanh0706** [comment]
Ok
