### ISSUE TITLE
Cannot upload Unity Project

### ISSUE THREAD

**Issue by vararth** [desktop/desktop#15252]
### The problem

Cannot upload Unity Project

### Release version

No Idea

### Operating system

Windows 10

### Steps to reproduce the behavior

Make a Unity Project
Install Github Desktop
Make a github repo
Copy the Assets, ProjectSettings and Packages folder into the repo

**Comment by steveward** [comment]
Thanks for the report @vararth. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
