### ISSUE TITLE
@SleepyVoodle

### ISSUE THREAD

**Issue by navjeevan-alone** [desktop/desktop#15262]
the same problem is happening with vs code. i get github login popup whenever i open vs code. This may be because i deleted some background processes from task manager but not sure it can be  a bug.

**Comment by tsvetilian-ty** [comment]
Thanks for reaching out!

We require the template to be filled out when submitting all issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

I will close this issue. Please open a new one with a filled template so we can be helpful :)
