### ISSUE TITLE
Clone wiki locally does not work

### ISSUE THREAD

**Issue by mgas2021** [desktop/desktop#15274]
### The problem

- Goto e.g. [vscode-docs wiki](https://github.com/microsoft/vscode-docs/wiki)
- copy the url by [Clone this wiki locally](https://github.com/microsoft/vscode-docs.wiki.git)
- clone repository from the url https://github.com/microsoft/vscode-docs.wiki.git

Result:

![image](https://user-images.githubusercontent.com/95370357/189822575-40fb7363-65d9-412f-aa43-3edf496cee6e.png)

manual clone via shell 

![image](https://user-images.githubusercontent.com/95370357/189822934-9d5a9db1-cd94-426e-8079-2e6d727f3e00.png)

### Release version

Version 3.0.7 (x64)

### Operating system

Windows 10

**Comment by sergiou87** [comment]
Hi @mgas2021, thanks for the issue, and sorry you're running into that. We don't have great support for wikis in Desktop unfortunately, and we're tracking that in #3839, so please follow along there. For full transparency, I don't anticipate we'll be working on this anytime in the near future because our team is small and we have to prioritize things that are likely to significantly benefit a greater percentage of users. Thanks again!
