### ISSUE TITLE
local changes are not reflected in Github dash board

### ISSUE THREAD

**Issue by cap-mprathy** [desktop/desktop#15280]
### The problem

local changes are not reflected in the Github dashboard

### Release version

Version 3.0.8 (x64)

### Operating system

windows

**Comment by sergiou87** [comment]
@cap-mprathy  Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
