### ISSUE TITLE
GitHub Desktop reopens deleted branch and tries to rebase it

### ISSUE THREAD

**Issue by Qwertypop04** [desktop/desktop#15296]
### The problem

GitHub Desktop is opening a deleted branch and trying to rebase it, by readding all files that have been deleted in the develop branch since this branch was opened. This includes some that were deleted through the PR that was made from this branch

### Release version

Cannot find 'About GitHub Desktop' menu item

### Operating system

Windows 10

### Steps to reproduce the behavior

Have branch
Delete branch after PR is merged
Wait (does not happen immediately)
Branch restores itself and bug occurs

**Comment by steveward** [comment]
Thanks for the report @Qwertypop04. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by Qwertypop04** [comment]
Sure. Here's the log from today
[2022-09-16.desktop.production.log](https://github.com/desktop/desktop/files/9587007/2022-09-16.desktop.production.log)

**Comment by steveward** [comment]
@Qwertypop04 apologies for the delay. It looks like you are storing repositories in OneDrive -- my guess it that these deleted files are being restored by OneDrive, which is causing the issue you are experiencing. I would recommend storing your repositories outside of OneDrive. I'm going to close this out, but let me know if that does not get things working.

**Comment by Qwertypop04** [comment]
I see, hopefully that helps, thanks!
