### ISSUE TITLE
Discard changes in GitHub Desktop without moving them to Recycle Bin

### ISSUE THREAD

**Issue by boorac** [desktop/desktop#15293]
### The feature request

GitHub Desktop provides the ability to discard all changes (non-committed, non-stashed ) at once. When you discard changes in GitHub Desktop, all changes (or rather, all files that contain changes) on a currently checked-out branch are moved to the Recycle Bin, which is also a very nice feature as it creates a backup for you in case you regret the discard and want your changes back.

But sometimes I do not want my files in the Recycle Bin, I just want to get rid of them.

After the discard operation is complete, I have to manually delete the discarded files from the Recycle Bin. Is it possible to discard files without moving them to the Recycle Bin?

### Proposed solution

Provide an option to permanently delete files on discard:
* Global option
* Per-discard option (e.g. checkbox)

**Comment by steveward** [comment]
Thanks for the issue @boorac. This is an interesting idea, but setting up a custom option like this isn't likely something we will implement. Windows has good options these days for customizing the emptying of the Recycle Bin, so I'd recommend using that so that you don't need to manually clear things out.

For reference we do support the case where the Recycle Bin is disabled as well (see https://github.com/desktop/desktop/pull/13904).

**Comment by HernandoNJ** [comment]
Restarting the pc worked for me
