### ISSUE TITLE
Version 3.0.7 won't update to version 3.0.8

### ISSUE THREAD

**Issue by remlapmot** [desktop/desktop#15291]
### The problem

As far as I can the latest stable version is now 3.0.8. However, in version 3.0.7 when I click *Check for Updates* on both my Windows and M1 Mac neither seem to find the newer version as usual.

(I appreciate I can just download the installer to obtain the newer version.)

### Release version

3.0.7

### Operating system

Windows 11 and macOS Monterey 12.6

### Steps to reproduce the behavior

On Windows

1. Help
2. About GitHub Desktop
3. Check for Updates

GitHub Desktop fails to detect newer version available.

### Screenshots

On Windows 11

![image](https://user-images.githubusercontent.com/3777473/190580039-db7b03d1-6161-44af-af6e-0856b49e67be.png)

On macOS

![image](https://user-images.githubusercontent.com/3777473/190580097-5283bf5b-55a4-4fb3-845a-3a639a4fa6f8.png)

**Comment by niik** [comment]
Hey @remlapmot, thanks for reaching out. We're rolling out the 3.0.8 release gradually to users and expect to reach 100% rollout some time early next week. We're taking this more conservative approach since we're including an update of Electron in this version and want to make sure it doesn't cause any unexpected side effects. If you want you can hold down the `Alt` key while in the About dialog which will let you immediately update to 3.0.7. Sorry for the confusion!

cc @sergiou87 fyi

**Comment by remlapmot** [comment]
Thanks. Sorry, I didn't realise you could do that.
