### ISSUE TITLE
You can no longer run console commands in the Chromium developer tools

### ISSUE THREAD

**Issue by ChiriVulpes** [desktop/desktop#15300]
### The problem

Typing any character into the Chromium developer tools console crashes the app and causes `EvalError: Possible side-effect in debug-evaluate`

### Release version

3.0.8

### Operating system

Windows 10.0.19044

### Steps to reproduce the behavior

1. View > Toggle Developer Tools
2. Type any character into the console.

### Log files

[2022-09-17.desktop.production.log](https://github.com/desktop/desktop/files/9590667/2022-09-17.desktop.production.log)

### Additional context

In every prior version of GitHub Desktop, you could run console commands in the developer tools. I used this every time I updated [to apply custom CSS to `app/index.html`](https://gist.github.com/ChiriVulpes/83afaa0e1cf21d6852f5349b10e7eb3a) — it was more important back when there wasn't a dark theme, but there are still some problems I have that my stylesheet fixes that persist (#11404) so I'd really like to be able to apply it still. (Also the custom syntax theme helps my ability to read the code, too.)

**Comment by niik** [comment]
Hey @ChiriVulpes, thanks for reaching sorry for the inconvenience here. In the last version of GitHub Desktop we updated our version of Electron to v19 which unfortunately includes this bug. We had a workaround for this in our development builds but that unfortunately didn't make it into the production builds. We've since merged a fix (https://github.com/desktop/desktop/pull/15276) but that hasn't made it into either our production or beta builds yet.

Given that you're no stranger to modifying the app you could apply the fix manually until we're able to ship a production build by modifying the `index.html` file in `%LOCALAPPDATA%\GitHubDesktop\app-3.0.8\resources\app\index.html` to include a 

```html
<script>window.onerror = e => e === 'Uncaught EvalError: Possible side-effect in debug-evaluate'</script>
```

Anywhere before the script tag which includes `render.js`

**Comment by ChiriVulpes** [comment]
Closing as it was fixed as of the subsequent update.
