### ISSUE TITLE
Github integration for github repos, like code branches, issues, PRs, and actions.

### ISSUE THREAD

**Issue by yw662** [desktop/desktop#15308]
### The feature request

We can view github issues, PRs and actions with the Github Android app, and even with some VSCode extensions, but when it comes to github desktop, it is no more than yet another git GUI, with little github integration.
It would be cool if the application can do sth. on github so we won't need to open the web page. Or at least it should be able to show the repo link. So the requested features are:

* (When working with a repo with a github remote), show a link to the repo somewhere.
* List all branches from github in the branch tag, not only those cloned locally, and make it possible to check remote status and work with them.
* And an `issues` tag to work with github issues.
* And the same thing for PRs and actions (or more).

### Proposed solution

Being able to be integrated tightly with github is what makes Github Desktop different from all other git GUIs. If Github Desktop can replace the website in daily routines, or at least provide a link to it, it could be super useful and convenient.

**Comment by steveward** [comment]
Thanks for the issue @yw662. Implementing specific GitHub features 1:1 in GitHub Desktop isn't always feasible due to the rate of change on github.com, but we're always considering ways we can integrate better. We are a small team and as a result have to manage the scope of features that we focus on.

>(When working with a repo with a github remote), show a link to the repo somewhere.

There are a few ways you can do this already -- via the context menu in the repository list, or using the menu/available [keyboard shortcuts](https://docs.github.com/en/desktop/installing-and-configuring-github-desktop/overview/keyboard-shortcuts). Hopefully that's helpful!

>List all branches from github in the branch tag, not only those cloned locally, and make it possible to check remote status and work with them.

All the branches associated with the repository are listed in the branch dropdown -- is there something specific you are looking for here?

>And an issues tag to work with github issues.

We discussed issue management within GitHub Desktop in https://github.com/desktop/desktop/issues/8989, and at this time we do not have plans to implement this type of feature.

We do provide issue integration into commit messages. You can reference issues in commit messages by using the #<issue_number>. When you type this out it will bring up a list of issues for you to scroll through if you want to close out a specific issue with a commit. When this commit is merged into your default branch it will automatically close the referenced issue. I hope that helps!

>And the same thing for PRs and actions (or more)

Tighter PR integration is something that we're working on, see https://github.com/desktop/desktop/pull/15277 as an example of the work that is in progress.  We also provide the ability to [view and re-run checks ](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/working-with-your-remote-repository-on-github-or-github-enterprise/viewing-and-re-running-checks-in-github-desktop) if you're working with GitHub Actions. 

We also have [notification integration](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/working-with-your-remote-repository-on-github-or-github-enterprise/configuring-notifications-in-github-desktop) in GitHub Desktop that helps keeps you up-to-date on events happening in your repository.

I'm going to close this out, but thanks for the feedback and feel free to follow up with any additional questions.

**Comment by yw662** [comment]
Are these features public repos only or are they for private repos as well ?

I am currently working on a private girhub repo on macos, but the "view on GitHub" option is not usable.

**Comment by steveward** [comment]
If the repository is hosted on GitHub or GitHub Enterprise then the links should work. Do you have any other repos you can check?
