### ISSUE TITLE
github desktop is crashing on my computer

### ISSUE THREAD

**Issue by johndgrandson** [desktop/desktop#15329]
I downloaded github desktop on my pc and it is extremely slow it takes a good few seconds to click on anything, not only that but since i installed it my vs code has also been slow which makes it very boring to practice, i find it strange even because my pc has ssd and 8g of ram, I already looked if it was something with antivirus, it doesn't seem to be the case

**Comment by sergiou87** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by johndgrandson** [comment]
what do i have to do?

**Comment by sergiou87** [comment]
Hey @johndgrandson! When you create a new issue in this repo, select `Bug report`, and you will get a form with different fields. Just enter the requested info in that form and that's it 😄 

![2022-09-28 at 16 17](https://user-images.githubusercontent.com/1083228/192803333-b03a8be7-172f-4be6-9013-4eb1fbdb74b4.png)

I'm gonna close this issue so you can create another one filling the template form for `Bug report`s. Thank you!
