### ISSUE TITLE
Allow repo list to be grouped by organization or provide option to show full repo name

### ISSUE THREAD

**Issue by dvnkshl** [desktop/desktop#1533]
For users who are part of multiple github projects/organizations it would be nice to either be able to group the repo list by organization or have the option to show the full repo name on the list view.

e.g.
<img width="736" alt="screen shot 2017-05-16 at 11 20 21 pm" src="https://cloud.githubusercontent.com/assets/3625028/26141046/c1ba2e62-3a8e-11e7-94db-dca756e0bb88.png">

**Comment by xt0rted** [comment]
This was a feature request I had with the old native version. I'd like to see a way to group the repos so I'd have my own personal repos, forks of other projects, and repos for work.

**Comment by andyfleming** [comment]
Huge +1 here.

Folders to create groups would be ideal. A number of solutions would work.

The specific use cases that hit me with this lacking feature-area are:

* needing a way to group by folder and/or by organization to more easily browse among 50 repos in my sidebar
  * The downside or organizing by org is that forks might be listed in an unintuitive way. Also I might want to organize projects within and org
* 2 clones of a repository in separate locations (and needing to be able to differentiate between the two somehow)

**Comment by adamreisnz** [comment]
Perma +1 from me. I've been advocating for a feature like this since the early days of the Github for Mac beta.

**Comment by sbonami** [comment]
I'd love to filter repo list by keyword/tag as well. Just looking at sdks vs apps or react vs redux, etc. would be great by utilizing Github's repo tags.

**Comment by shiftkey** [comment]
@sbonami are you referring to [Topics](https://blog.github.com/2017-01-31-introducing-topics/)? 

These are currently available as a [preview API](https://developer.github.com/v3/repos/) but this would be an interesting idea to move out it's own issue if you'd like to expand on how this would work when filtering.

**Comment by sbonami** [comment]
@shiftkey Topics, yeah 😅 I'll create a new issue, thanks!

**Comment by raeesbhatti** [comment]
I opened https://github.com/desktop/desktop/pull/5160, that makes small changes to show owner login and repo name in current repository and repositories list.
<img width="1072" alt="screen shot 2018-07-14 at 6 34 59 am" src="https://user-images.githubusercontent.com/10067728/42719503-1053f23a-8730-11e8-85f7-ab40a35c1b97.png">

**Comment by shiftkey** [comment]
Tentatively labelling this as `user-research` as I think we need to think about the original problem a bit. 

@desktop/design would love some :eyes: and ❓s about this when you have bandwidth.

**Comment by adamreisnz** [comment]
Personally I'd prefer it if the repo's could be grouped by organisation rather than having the organisation display in front of the repo name, e.g. in a similar way as they are currently "grouped" by **Github.com** and others.

However, given how this solution is probably easier to accomplish, and also given that there is a about a kilometre of white space available in the repo's list (see screenshot), this would at least alleviate the problem of not being able to differentiate repo's if they have the same name.

![image](https://user-images.githubusercontent.com/490562/44608301-6b3b6880-a847-11e8-9f02-f1dfdadaaf72.png)

I personally don't care if my repo's are on Github or elsewhere, so the current grouping doesn't really add any value for me. Grouping by Github organisation/user would be much more valuable, and this could probably be combined with the current grouping, e.g.:

**some org**
  repo1
  repo 2
**other org**
  repo1
  foo
  bar
**someuser**
  repo3
  repo 4
**not on github**
  any other
  repos
  not on github

**Comment by BarryMode** [comment]
1. It would be helpful to sort repos into custom categories (ex. by tag or folder). Here are two reasons why this should be implemented.

a. I have three different places I work for that use repos, none of which have a Github organization. The sorting would be helpful in separating the projects where GitHub doesn't have a natural way to automatically sort them for me.
b. Filtering is great, but it doesn't help you find a repo that has a name you can't remember.
c. Repos are most likely already organized into folders by the user in the native file system. Isn't this redundant? Well yes, it is. So are many other things. You can use git in terminal. In that sense, Github Desktop is redundant. Let's not avoid valuable features just because it's redundant. Maybe that's not way this isn't implemented, I'm just trying to address possible reasons why it hasn't happened yet. (this issue has existed for over a year).

2. An additional feature or alternative to the above would be to at least have methods of sorting the repos. Sort into trees by user, by organization, by the site it's hosted on (the current default), by date, by name, etc.

> I personally don't care if my repo's are on Github or elsewhere, so the current grouping doesn't really add any value for me

Agreed.

**Comment by StefanoCecere** [comment]
if GitHub is really intersted in pushing Desktop into pros, this feature is mandatory!
we have tons of repos under several organizations.. i would like to group my repos in subgroups, too (SourceTree does it well)

**Comment by adamreisnz** [comment]
Is there any update on this issue? We have just moved a bunch of repo's to an organisation, and where before the lack of this feature was manageable, as we could filter repo's based on prefix to see all the repo's belonging to this organisation, this is now no longer possible as the prefix has been removed.

Being able to filter by organisation and to see the organisation where it says "Current repository" would be a great UX improvement.

**Comment by adamreisnz** [comment]
I would love to help get this moving. I'm not familiar with the code structure of the app, but am willing to give it a crack. Shall I open a new PR to write out what needs to happen and how this feature would work, in order to obtain some feedback first?

**Comment by adamreisnz** [comment]
@billygriffin just pinging you to see if I can get some feedback on how to best progress this issue.

I was also thinking of another somewhat different approach, which may or may not be of interest: instead of grouping by organisation, which may work for some people but not for others, or instead of the overhead of working with custom groups, what if we could place a file in our project folder (`.githubdesktop`) and specify some meta data in there, like the preferred display name for the repository, or the preferred group.

**Comment by billygriffin** [comment]
@adamreisnz Thanks for the ping, and 😬 sorry for the delay in responding. We have at least 8 issues (a few of which are referenced in this issue above) we're evaluating in the course of trimming down `future proposal` labeled issues that are similar in nature to this, but essentially the question boils down to "how we group and organize repositories to present to users visually." Lots of people have suggested very different ways of doing this, which indicates that we need to be thoughtful about the approach we take so we're solving the core problem(s) for the largest percentage of users. But everyone on our team agrees that it can improve from where we are today. 

Since that discussion is just kicking off internally, I'd be interested in seeing what you propose and how it might break out in different scenarios. No need to make a PR if you're able to do it in this issue, unless it's easier for you to get it working in code and see how it feels from there (whatever your preference is fine with us). Generally, I'd say we'd like to avoid customization where possible if there's something that will work pretty well for the vast majority of users, as most people don't customize and we want the experience to be good out of the box. It might also be helpful to frame the problems you'd be seeking to solve and which ones a proposed solution solves and which ones it doesn't (like this issue breaks out: https://github.com/desktop/desktop/issues/6107).

Let me know your thoughts, and thanks for your willingness to explore this. 😄

**Comment by adamreisnz** [comment]
Gotcha, sounds good I'll try to stick with things that will work well for most users. I'll review all comments and feedback from this issue from top to bottom again, and will try to put a proposal together here.

**Comment by billygriffin** [comment]
Thanks so much to all who have responded here. I'm going to close this issue in favor of #6460, where we're trying to examine the problem as holistically as possible and understand the range of possibilities. Everything here is super useful feedback, and we're definitely taking it into account as we look at potential design solutions. cc: @desktop/design
