### ISSUE TITLE
Repo name is not concise

### ISSUE THREAD

**Issue by stanier** [desktop/desktop#15340]
I'm not sure how long the current repo name has been in use, but this is the first time I have encountered it and it did absolutely nothing to tell me what the project was about or who built it, neither did the tagline.

"desktop/desktop - Simple collaboration from your desktop" as it would show up on the Trending page or any other public repo aggregator (sans the author/org avatar, which only some show) does not immediately register as "GitHub Desktop - A tool for easily conducting git workflows from your desktop, by GitHub".  From within the ambiguity of "desktop/desktop - Simple collaboration from your desktop", we could also incorrectly extract the meaning of "collaborative productivity suite"

Does it not make sense for at least the tagline to indicate what the project is *actually* about?  I fail to see how such a broad tagline is productive, it comes across to me as if the intent were to be purposefully vague in hopes of attracting more eyes-- something like "Focus on what matters instead of fighting with Git" as seen on the desktop.github.com landing page would at least tell people "hey this is a git-centric tool"

**Comment by steveward** [comment]
Thanks for the issue @stanier! We hadn't revisited this description since inception, so thanks for bringing this up.  I mulled over a few phrases and did ultimately like the simplicity from our marketing page of "Focus on what matters...". I've updated it to that, and hopefully that provides a better indication of what the product is about. I'm going to close this out, but let me know if you have any further feedback!
