### ISSUE TITLE
Desktop is unusable

### ISSUE THREAD

**Issue by Techtense** [desktop/desktop#15357]
### The problem

SLOW AS HELL WHEN TRYING TO USE THE INTERFACE. I Can't type or do anything without lag

### Release version

3.0.8

### Operating system

Windows 11

### Steps to reproduce the behavior

Open the program and try to open anything in a repo

### Additional context

PC is i7-6770k with 16gb of RAM so it is not a performance issue

**Comment by steveward** [comment]
Thanks for the report @Techtense. Are specific Git operations taking a long time (i.e. committing, pushing), or is the app just lagging (i.e. switching between repositories)? 

Could you also upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by x15212** [comment]
I don’t know how I got on here I can’t remember my password to unsubscribe
