### ISSUE TITLE
Impossibile to skip stash discard prompt

### ISSUE THREAD

**Issue by riccardodivirgilio** [desktop/desktop#15376]
### The problem

The prompt for discarding stash changes always shows up, even if all prompt are disabled from settings.

### Release version

3.0.8

### Operating system

macOS 12.6

### Steps to reproduce the behavior

1. Create some changes and then stash them
2. Click the discard button to discard them
3. A prompt shows up

### Screenshots

<img width="1646" alt="Screenshot 2022-09-28 at 11 21 47" src="https://user-images.githubusercontent.com/187641/192742578-5647319c-08de-440a-8f49-ea6d1888900f.png">
<img width="636" alt="Screenshot 2022-09-28 at 11 24 52" src="https://user-images.githubusercontent.com/187641/192742673-c442a57a-83ca-4221-a02b-e0d6f3f7671d.png">

### Additional context

https://github.com/desktop/desktop/pull/15243
https://github.com/desktop/desktop/issues/15134

**Comment by tsvetilian-ty** [comment]
👋 @riccardodivirgilio

The option to disable this popup is added in https://github.com/desktop/desktop/pull/15243 and is available for download in the latest [beta release](https://desktop.github.com/beta/).

**Comment by wonsuchai** [comment]
ขอบคุณครับ.  Sent from Mail for Windows From: riccardodivirgilioSent: 28 กันยายน 2565 16:25To: desktop/desktopCc: SubscribedSubject: [desktop/desktop] Impossibile to skip stash discard prompt (Issue #15376) The problemThe prompt for discarding stash changes always shows up, even if all prompt are disabled from settings.Release version3.0.8Operating systemmacOS 12.6Steps to reproduce the behaviorCreate some changes and then stash themClick the discard button to discard themA prompt shows upLog filesNo responseScreenshotsAdditional context#15243#15134—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
