### ISSUE TITLE
Sign in in Desktop app is not working --> push go to desktop app is done but nothing happens in app

### ISSUE THREAD

**Issue by Brodersm** [desktop/desktop#15383]
### The problem

Sign in in Desktop app not possible. Tried it with Microsoft Edge and Google Chrome browser. With both it doesn't work. 

### Release version

 3.0.8 (x64)

### Operating system

Windows 10

**Comment by steveward** [comment]
Thanks for the report @Brodersm. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
