### ISSUE TITLE
Failed to execute getStatus: ENOENT

### ISSUE THREAD

**Issue by Admiralng** [desktop/desktop#15384]
### The problem

![image](https://user-images.githubusercontent.com/105179015/193038604-8b4f524e-bd08-4a49-a865-dc479aa7b415.png)

Anytime I try to open my github desktop, it displays the message above. Should I just download another one or try installing another one?

### Release version

Version 3.0.8 (x64)

### Operating system

Windows 10

**Comment by sergiou87** [comment]
@Admiralng  Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by Mosoeunyane** [comment]
Anytime I try to open my github desktop, it displays the message above. Should I just download another one or try installing another one?please help

**Comment by Mosoeunyane** [comment]
i tried everything
