### ISSUE TITLE
delayed working

### ISSUE THREAD

**Issue by bobbybenny8084** [desktop/desktop#15390]
### The problem

started yesterday, my GitHub desktop application is working with a delay of about 4 or 5 seconds. it happens only in this window, no issues in any other windows i use. here, even the commands i type appear 4 seconds later and the cursor movement is also delayed.

### Release version

3.0.8

### Operating system

windows 10

**Comment by steveward** [comment]
Thanks for the report @bobbybenny8084. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
