### ISSUE TITLE
Edit->Undo does not work, only Undo quick button works

### ISSUE THREAD

**Issue by SaschaNaz** [desktop/desktop#1541]
### Version

**GitHub Desktop version:** 0.5.3

**OS version:** Windows 10.0.15063

### Steps to Reproduce

1. Commit anything
1. Try Edit->Undo
1. Try Undo quick button[](url)

![github-undo](https://cloud.githubusercontent.com/assets/3396686/26146202/4abb5934-3b2a-11e7-95f1-425450bdc219.gif)

**Expected behaviour:** Edit->Undo should work

**Actual behaviour:** Edit->Undo doesn't work

**Reproduces how often:** 100%

### Logs

No logs.

**Comment by tierninho** [comment]
Related to: https://github.com/desktop/desktop/issues/1392

**Comment by niik** [comment]
Thanks for opening this @SaschaNaz.

> Edit->Undo doesn't work

See https://github.com/desktop/desktop/issues/1392#issuecomment-299601119, the undo menu item is a system convention and refers to text input. It's a bit confusing but we're not eager to change it. We also have limited insight into electron's undo stack so we're not able to infer what action the undo menu item would take. We're also not able to push items to the undo stack ourselves.

I'm going to close this out as we classify this as expected behavior.
