### ISSUE TITLE
Parada inesperada do github desktop

### ISSUE THREAD

**Issue by Agentofshadows** [desktop/desktop#15431]
### The problem

Parada inesperada do github desktop

### Release version

3.1.1

### Operating system

windows 11

### Screenshots

![Screenshot (177)](https://user-images.githubusercontent.com/18728163/194729892-83bee53f-ee4e-473e-a616-30d0f117b3b8.png)

**Comment by sergiou87** [comment]
Hello! 👋 

This kind of error usually happens due to some of the following reasons:
- Your machine is behind a proxy. Try disabling it.
- You have some antivirus or firewall installed. Try disabling them.
- Your internet (usually wifi) connection is unstable. Try using wired network.

Please, check if any of those apply to you and if so, if the suggested workarounds actually work 🤞
