### ISSUE TITLE
Please add native WSL support (without network mapped drive)

### ISSUE THREAD

**Issue by apudiu** [desktop/desktop#15443]
### The feature request

I think gitHub desktop should support WSL natively.

### Proposed solution

Adding the support

**Comment by steveward** [comment]
Thanks for the issue @apudiu. Can you expand upon this feature request? GitHub Desktop already supports adding repositories directly from WSL. Is there something specific you are looking for?

**Comment by jayjay101010** [comment]
Just saying this is my emAil julia Katherine haney ....not anyonr else

**Comment by kingyyy** [comment]
yes please

**Comment by apuatcfbd** [comment]
@steveward Thanks for the query.
But I'm unable to add existing repo from WSL, can you tell me how? when I try to open one, then I'm not seeing WSL path (Except mapped network drive to WSL),

I'm also facing issue when I commit from WSL & then GitHub Desktop shows that all files changed. I think this is related to line ending. you can check the screenshot (currently repo is in WSL - which is an imported distro of ubuntu 20.04) https://prnt.sc/YzEjHq81crxX
Vice versa happens when I commit from GitHub desktop & try to commit from ide (PHPStorm)
(I always want unix line ending, `git config --global core.autocrlf` is set to `input`)

**Comment by steveward** [comment]
@apudiu dragging-and-dropping the repository right into GitHub Desktop works without issue. the path should look like `\\wsl$\Ubuntu-20.04\home\username\path\to\repository`. 

>I'm also facing issue when I commit from WSL & then GitHub Desktop shows that all files changed. 

You may be hitting [this issue](https://github.com/desktop/desktop/issues/9443) related to file mode changes. There's a potential workaround [here](https://github.com/desktop/desktop/issues/9443#issuecomment-734737634).

If you are hitting line-endings issues I would recommend adding a `.gitattributes` file to ensure consistent line-endings behavior. See [this doc](https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings#per-repository-settings) for info.

I'm going to close this out since this isn't a specific GitHub Desktop issue, but let me know if you have any further questions.

**Comment by apuatcfbd** [comment]
I've following .`gitattributes` file but I was still facing above mentioned issue (screenshot: https://prnt.sc/4wPuMJcKe75r)
```
# Auto detect text files and perform LF normalization
* text=auto

# Files that should always LF
*.js text eol=lf
*.jsx text eol=lf
*.ts text eol=lf
*.tsx text eol=lf
*.json text eol=lf
*.scss text eol=lf
*.css text eol=lf
*.txt text eol=lf
*.csv text eol=lf
*.env text eol=lf

```

**Comment by steveward** [comment]
Can you open the repository in the command line and see what `git diff composer.json` returns?

**Comment by apuatcfbd** [comment]
It returns nothing (https://prnt.sc/DDg9HqO7RSZi) (GitHub Desktop: https://prnt.sc/Rnz7l3kQxooV)

**Comment by apuatcfbd** [comment]
@steveward no other tool is behaving like this, including VS Code (https://prnt.sc/eSMJij1pNXlB). In this circumstances I'd like to say that this is GitHub desktop's bug so this issue should be opened again.

I'm seeing that all type of file's are changed including binaries (https://prnt.sc/QEwkDF9mo8F3).
I'm willing to provide as much info as you need. I really like the way GD (GitHub Desktop) works, Please let me know if you need more details.

**Comment by aleixrodriala** [comment]
I built a fork that does this — native WSL support without going through the network mapped drive. It runs a small daemon inside WSL that handles git and file operations directly over TCP: [GithubDesktopWSL](https://github.com/aleixrodriala/GithubDesktopWSL)

Think of it like the VS Code Remote WSL extension but for GitHub Desktop. Auto-syncs with upstream releases and installs side-by-side. Would love feedback!
