### ISSUE TITLE
Feature Request: diff config for context size

### ISSUE THREAD

**Issue by fluffynuts** [desktop/desktop#1544]
### Description

It would be really handy to be able to change the context size for a diff. It would also be super-handy (at least, for me) to be able to make that context size "infinite", meaning "show me the entire file with diffs in place". I find context to be very helpful when trying to figure out what a patch is about.

### Version

**GitHub Desktop version:** 0.5.3

**OS version:** Microsoft Windows [Version 10.0.15042]

### Steps to Reproduce

No real steps to repro as this isn't an issue, it's a request. However, I'd expect this to be a setting in options, including the "infinite" option to always show the full file.

**Comment by joshaber** [comment]
Thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I'm going to add the `future-proposal` label to this issue and close it out, so that we don't get overwhelmed with our backlog! We'll revisit these as part of our next planning session.

**Comment by DARKMEDION** [comment]
-
