### ISSUE TITLE
Feature suggestion: Option to add/modify keybindings

### ISSUE THREAD

**Issue by manparvesh** [desktop/desktop#1545]
### Description

I think it would be a great help for several people to be able to use different keyboard shortcuts that meet their needs. For example, for focusing on different panels / text areas. I am sure there are many other uses for this.

**Comment by shiftkey** [comment]
@manparvesh could you provide some examples from the current app?

**Comment by manparvesh** [comment]
- Currently there is no option to view all keyboard shortcuts in one place. One needs to open the menu for checking. If it can be put in the settings window, it would be great.
- Also, for existing shortcuts like new branch or new repository, it is possible that one would prefer a different shortcut, something that they are familiar with or that is easy to remember for them (like `Ctrl + B` for new branch instead of `Ctrl + Shift + N`)
- Currently, there is no shortcut to focus on the commit box to enter the message. After pushing, the focus is lost and I have to click on the box to focus, and then `Ctrl + P` for push.

**Comment by greystate** [comment]
> Currently, there is no shortcut to focus on the commit box to enter the message. After pushing, the focus is lost and I have to click on the box to focus, and then Ctrl + P for push.

What 's even worse with that is that the shortcut in the old version `Ctrl + Shift + C` now does the "Compare on GitHub" action, which I accidentally trigger all the time now :-)

**Comment by langsmith** [comment]
Would absolutely love a keyboard shortcut to open a repo folder in Terminal.

Related, not sure why command+T was chosen as the shorcut to open a repository, especially when command+R isn't even used for some other command...

**Comment by joshaber** [comment]
Thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I'm going to add the `future-proposal` label to this issue and close it out, so that we don't get overwhelmed with our backlog! We'll revisit these as part of our next planning session.

**Comment by billygriffin** [comment]
Hi folks! We don't plan to add user-specified keyboard shortcuts to the app, so I'm going to remove `future proposal` here. However, we (and the community) have added quite a few individual keyboard shortcuts since this issue was created, and we're happy to chat about individual shortcuts that would make workflows more convenient in individual issues. Thanks for the idea!
