### ISSUE TITLE
Pulling repo does not update list of all new commits, but will if pulled immediately again

### ISSUE THREAD

**Issue by mostlyhuman** [desktop/desktop#15454]
### The problem

I use Github Desktop to pull repositories from Epic's Unreal repo.  When I launch desktop it automatically pulls, but when complete will not show the most recent commits.  But if I then immediately pull again it will update theml

### Release version

3.1.1

### Operating system

Windows 11

### Steps to reproduce the behavior

it may not require these exact steps but this is what I have done

1) Add the Epic Unreal Engine repository
2) Switch to the 5.1 branch
3) wait awhile and then open desktop and let it automatically fetch
4) compare the history with the current commits, it will not have the latest ones
5) click to fetch again and then the history will update to show the latest commits

### Log files

[2022-10-13.desktop.production.log](https://github.com/desktop/desktop/files/9780262/2022-10-13.desktop.production.log)

**Comment by steveward** [comment]
Thanks for the issue @mostlyhuman. GitHub Desktop performs a fast-forward merge for branches that you're not on as part of the auto-fetching process in the background, but not for the currently-checked out branch. It sounds like you are hitting the expected behavior here, so I'm going to close this out. Let me know if you have any further questions.
