### ISSUE TITLE
Fails to detect changes in filename case

### ISSUE THREAD

**Issue by rodneytamblyn** [desktop/desktop#15466]
### The problem

- created a file "Litebreeze-installer.dmg"
- updated file name to "litebreeze-installer.dmg"
- GH desktop still reports capitalised file name.  
- tried shifting the renamed file into a subfolder - GH desktop correctly recognises new file naming, but on shifting it back to the downloads folder it reverts to the (cached?) Capitalised (incorrect) naming
- 
![image](https://user-images.githubusercontent.com/1562956/196013273-4c5d186a-0751-4278-ab7f-7f3c750e3e33.png)

![image](https://user-images.githubusercontent.com/1562956/196013234-3a136e94-7157-48b1-a6df-d560a6676e1b.png)

### Release version

3.1.1

### Operating system

OSX 12.5

### Steps to reproduce the behavior

See problem statement above.

### Screenshots

Screenshots attached to problem statement.

**Comment by niik** [comment]
Hi  @rodneytamblyn, thanks for opening this and sorry to hear you're having problems. The behavior you're observing has to do with the macOS file system by default being case-insensitive but case-preserving. That is, a file named `Litebreeze-installer.dmg` and a file named `litebreeze-installer.dmg` are both the same (as opposed to popular file systems on Linux where you could have `Litebreeze-installer.dmg` and `litebreeze-installer.dmg` side-by-side.

See this article about [Git case sensitivity](https://docs.microsoft.com/en-us/azure/devops/repos/git/case-sensitivity?view=azure-devops) for more information.

For now there are a few ways to go about solving this. Either you open a command line prompt and run the command specified in the article above (i.e. `git mv -f Litebreeze-installer.dmg litebreeze-installer.dmg` followed by `git commit`. Or if you want to stay in GitHub Desktop you first rename `Litebreeze-installer.dmg` to `litebreeze-installer_tmp.dmg`, make a commit, and then rename `litebreeze-installer_tmp.dmg` to `litebreeze-installer.dmg` and commit.

You can also [rename the file directly on GitHub.com](https://docs.github.com/en/free-pro-team@latest/github/managing-files-in-a-repository/renaming-a-file) and then pull that change to your repository.

I hope that helps!

**Comment by jdavidmr1016** [comment]
I had the same issue on Windows so the behavior isn't related to the OS it produced a bug very hard to find some times because on local build is working great but the deploying of that code is failing always. 
The workaround was rename the file from `Invoices.tsx`to `invoice.tsx` Wich  is bad on our naming conventions

**Comment by niik** [comment]
> Windows so the behavior isn't related to the OS 

Both Windows and macOS have case-insensitive, case-preserving file systems (as opposed to Linux). In this original issue the user was using macOS which is why I specifically mentioned it.

> The workaround was rename the file from Invoices.tsxto invoice.tsx Wich is bad on our naming conventions

Temporarily renaming is one of several ways to solve this, renaming on the GitHub website another, please see this article about [Git case sensitivity](https://docs.microsoft.com/en-us/azure/devops/repos/git/case-sensitivity?view=azure-devops) for more information. You can rename the file back to `invoices.tsx` now and it'll should work just fine.
