### ISSUE TITLE
can't login

### ISSUE THREAD

**Issue by abhigyant1** [desktop/desktop#15469]
### The problem

I am not able to login or not do anything

### Release version

3.11

### Operating system

64-bit

**Comment by steveward** [comment]
Thanks for the report @abhigyant1. Are you seeing any specific error messages when attempting to log in? Could you also upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
