### ISSUE TITLE
Error during commit with husky and code 127

### ISSUE THREAD

**Issue by gabe-piltzer-zendesk** [desktop/desktop#15472]
### The problem

I have been using Husky and GitHub Desktop together for months with no issue. Today I tried to commit and ran into the following error.

env: node: No such file or directory
husky - pre-commit hook exited with code 127 (error)
husky - command not found in PATH=full path concealed

I went to my terminal and did a `git commit` and it worked without issue (ran the pre-commit hook and committed).

### Release version

v3.1.1 (x64)

### Operating system

MacOS Monterey v12.6

### Log files

[2022-10-17.desktop.production.log](https://github.com/desktop/desktop/files/9804493/2022-10-17.desktop.production.log)

### Screenshots

![image](https://user-images.githubusercontent.com/91081358/196282132-325f26ad-51e7-4fa0-8e2b-c5dee13d44c2.png)

**Comment by steveward** [comment]
Thanks for the issue @gabe-piltzer-zendesk. This looks like the same as reports in https://github.com/desktop/desktop/issues/12562. There are a few potential workarounds in that issue that I would recommend taking a look at. I'm going to close this out since we are tracking this in #12562, but please drop feedback into that issue if you had success with a specific workaround.

**Comment by Avilayoma** [comment]
Sound https://news.ycombinator.com/item?id=33249215
