### ISSUE TITLE
Add Repository > Clear menu option to run `git clean -fdx`

### ISSUE THREAD

**Issue by Sergio0694** [desktop/desktop#15485]
### The feature request

GitHub Desktop is great, and I find myself being able to use it for almost everything, _except_:

- `git clean -fdx`
- `git rebase -i HEAD~N` for when I want to drop commits

This proposal is to track the first one so it can be done without leaving GitHub Desktop. This is a very common operation when checking out to different branches in cases where you want to ensure all temporary files (eg. build artifacts) are also cleaned.

### Proposed solution

We could add a new Repository > Clear menu option here, right before the first separator:

<img width="560" alt="image" src="https://user-images.githubusercontent.com/10199417/196672966-93261382-3211-4a91-84d6-67e98f150188.png">

Clicking that would just run `git clean -fdx` for the user on the selected repository.

**Comment by steveward** [comment]
Thanks for the issue @Sergio0694. GitHub Desktop provides the equivalent of `git clean` with the `Discard changes` functionality that can be accessed by right-clicking on a file or from the 'x changed files' header. 

<img src="https://user-images.githubusercontent.com/1174461/37114275-b4968720-21fc-11e8-911f-e5e09927a448.png" width="400" />

I'm going to close this out, but let me know if you have any follow up questions or thoughts.

**Comment by Sergio0694** [comment]
@steveward I'm sorry, but I'm not sure that's actually the same feature. I do use that too quite often, but that only does what it says, ie. discards all changes in the current working tree. What I'm asking for is `git clean -fdx`, which delete all files/folders in the whole repo that are not committed/tracked 😅

**Comment by steveward** [comment]
@Sergio0694 Thanks for the clarification. I can see that using discard would be cumbersome over large sets of changes where you can't discard all due to the tracked vs. untracked issue (and I did forget that the `-x` flag targets ignored files as well, so apologies for the misunderstanding on my part).

At this time this likely isn't a feature we'd add since we tend to push back against overloading the menus with custom Git commands, but it may be something we revisit again in the future. I'm going to keep this closed but will mark it as an enhancement for future consideration and we can continue to gather feedback.

For reference we are also tracking interactive rebase in https://github.com/desktop/desktop/issues/12354.
