### ISSUE TITLE
URL in a commit message is disappeared in history panel when the item is selected

### ISSUE THREAD

**Issue by alrz** [desktop/desktop#1548]
### Version

**GitHub Desktop version:**  0.5.3

**OS version:** Windows 7 and 10 (repro'd)

### Steps to Reproduce

1. make a commit with a url in the message
1. go to history panel
1. select the commit

**Expected behavior:** url is readable

**Actual behavior:** url disappeared 

**Reproduces how often:** always

**Comment by niik** [comment]
@alrz Could you share an example URL that reproduces this behavior and perhaps a screenshot to illustrate? :bow:

**Comment by joshaber** [comment]
I noticed this the other day too and forgot to report it 😞 For example, https://github.com/desktop/desktop/commit/95506061c6acb317f73b46f08f382f41e37e0b15:

![screen shot 2017-05-17 at 10 17 52 am](https://cloud.githubusercontent.com/assets/13760/26158527/1f8a751e-3aea-11e7-91f3-deae8d7f1018.png)

I assume the link and selection are the same blue color.

**Comment by niik** [comment]
Ah, I see. So, this is sort of related to https://github.com/desktop/desktop/issues/1456 in that I don't think we should render linkbuttons at all in these cells. Links should be clickable in the details view in history but not in the individual commit cells. We might want to introduce a different mode for the parser so that it emits spans instead of links while still parsing the content.

**Comment by alrz** [comment]
Sorry I couldn't upload the screenshot on this machine; thanks @joshaber for the repro.
