### ISSUE TITLE
I need Help with my Rep

### ISSUE THREAD

**Issue by EpisoDes1** [desktop/desktop#15504]
### The problem

I didnt had any backup so i made a  repository on github so i could make my code up to date but when i uploaded data on github using github app it was ok that time but then when i open code back my code was changed to original code provided by the real producer (My Gamemode is Based on SFCNR by LoReanc_) Any Way i can get my old files back?????????????

### Release version

Version 3.1.2 (x64)

### Operating system

Window 7

### Steps to reproduce the behavior

I lost all my updated data i didnt know enough about github please help me

### Log files

Everything is infront of you

**Comment by steveward** [comment]
@EpisoDes1 thanks for the issue. I'm not quite sure what happened here, but if your changes were committed you should be able to recover them by resetting to a previous commit in the repository's history. Is there a commit in the history that overwrote your changes? 

You can right-click on a previous commit and select `Create Branch from this Commit` to create a new branch, which will then allow you to view the changes in the repository's previous state. You can also open up the repository in the command line and run `git reflog`, which will give a history of what happened in the repository and should help us diagnose what caused this.

**Comment by EpisoDes1** [comment]
NO i Can't Do it it already changed everything
I revert the changes but That didn't Worked it said Changes reverted But They files didnt changed
any other way?
![image](https://user-images.githubusercontent.com/85149586/197702073-5545b344-6a74-4249-afa7-a5cf81706438.png)

**Comment by steveward** [comment]
Can you share the output of `git reflog` from the command line? I can guide you through resetting your repository back to a previous commit.

**Comment by EpisoDes1** [comment]
![image](https://user-images.githubusercontent.com/85149586/197950166-cc3671bb-2669-4d6b-b2ba-e34bad042dd5.png)

**Comment by steveward** [comment]
Thanks for sharing that. Is there a commit there that you would like to reset your repository back to? Once you figure that out you can reset your branch by following these steps:

1. Make a backup of your repository in case anything goes wrong
2.  Copy the SHA of the commit that you would like to reset back to
3. Run the command `git reset --hard <SHA>`
4. Your current branch will now be reset without any of the commits you did not want.

You can also test this out using the `Create Branch from Commit` option when right-clicking on a commit in the `History` view. It performs a similar function but instead of resetting the current branch it creates a new branch.

**Comment by EpisoDes1** [comment]
Sir it doesnt work
I wanna know why it mixed my files with original files?

**Comment by steveward** [comment]
@EpisoDes1 what specifically didn't work? If you can provide further details that would be helpful.
