### ISSUE TITLE
The application is extremely slow and hangs frequently

### ISSUE THREAD

**Issue by aybe** [desktop/desktop#15515]
### The problem

Pretty much every single time I switch to the application, I have to wait about 30 seconds or so for the application to become responsive and be usable again.

Below, the logs for the last three days, hopefully you may be able to provide some cues on what is causing this.

Thanks for your assistance!

### Release version

Version 3.1.2 (x64)

### Operating system

Microsoft Windows [Version 10.0.19044.2130]

### Log files

[2022-10-23.desktop.production.log](https://github.com/desktop/desktop/files/9856384/2022-10-23.desktop.production.log)
[2022-10-24.desktop.production.log](https://github.com/desktop/desktop/files/9856385/2022-10-24.desktop.production.log)
[2022-10-25.desktop.production.log](https://github.com/desktop/desktop/files/9856386/2022-10-25.desktop.production.log)

**Comment by sergiou87** [comment]
It looks like the different git commands are taking really long to complete. We've seen this in users with some kind of real-time protection from antivirus. Could that be your case? Maybe you can temporarily disable your antivirus if you have one and see if performance improves 🤞

**Comment by aybe** [comment]
While disabling it effectively removes the problem, the thing is, it used to work smoothly for years with the antivirus enabled.

I've asked the vendor and currently waiting for a reply, I will update this issue once I hear back from them.

**Comment by sergiou87** [comment]
From what we've seen, antivirus seem to take a while after an update of the app to trust it again. No idea what the heuristics are based on (maybe how many users of their antivirus are reporting that the new GitHub Desktop update is safe or something like that?), but sometimes antivirus decide to start removing files of GitHub Desktop after an update, considering them harmful, other times they make it super slow 😕 

GitHub Desktop is properly signed and all that, so we'd expect it to be trustworthy for antivirus and firewalls, but there is only so much we can do 😞 

Since you have pinned it down to the antivirus, I'm gonna close this issue. Thanks for reporting back and please let us know if your vendor gives you any useful hints about _why_ this happened!

**Comment by aybe** [comment]
Sorry for the late answering, I didn't get any meaningful reply, turning off the protection for the time being.
I'll see how it goes within the next weeks, if they ever catch up. FWIW, the software is Bitdefender Total Security.
