### ISSUE TITLE
Feature Request: Edit History

### ISSUE THREAD

**Issue by alrz** [desktop/desktop#1553]
- Edit commit message (with a warning if the commit is already pushed)
- Reorder commits by drag and drop (with a warning if any of commits are already pushed)
- Select and squash subsequent commits (with a warning if any of commits are already pushed)

**SmartGit** has something like this today.

**Comment by shiftkey** [comment]
@alrz there's some neat ideas in here that are probably worth exploring further, but given we didn't support these in the existing apps it's not on our radar for 1.0.

**Comment by rlabrecque** [comment]
Yeah these are the types of features that we need going forward. Those sound great.

**Comment by joshaber** [comment]
Thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I'm going to add the `future-proposal` label to this issue and close it out, so that we don't get overwhelmed with our backlog! We'll revisit these as part of our next planning session.

**Comment by j-f1** [comment]
[This blog post](http://tonsky.me/blog/reinventing-git-interface) might be interesting to look at when the time comes — it looks like a very user-friendly way to manipulate history.

**Comment by billygriffin** [comment]
@alrz Thanks for the ideas. We want to make sure we're solving core problems and not just support feature sets because they exist in other apps, and a primary one here is covered in https://github.com/desktop/desktop/issues/1644 which we're going to be looking at more closely. I'm going to remove `future-proposal` from this to reflect that we're not going to support these things in the near future, but as we continue to learn more from our users, we'll certainly continue to evaluate instances where amending parts of history could be useful. Thanks again!

**Comment by billygriffin** [comment]
@alrz I appreciate your thoughts. All these suggestions relate to amending things that have happened previously and may or may not exist on the remote. We think it's an interesting space, but we want to ensure we're listening to broad user needs and not just implementing features because they would be cool. I appreciate that these may be useful for you and we're definitely not ignoring the idea that it might be helpful for folks to be able to alter things from previous commits. Thanks again.
