### ISSUE TITLE
Contextual Menu (right click) to open a repo in Finder, Atom, or external editor.

### ISSUE THREAD

**Issue by stevemoser** [desktop/desktop#1554]
### Description

I would like to open a repo in another application.

### Version

**GitHub Desktop version:** 0.5.3

**OS version:** macOS 10.12.4 (16E195)

### Steps to Reproduce

1. Click the current repo drop down.
2. Right click on a repo

**Expected behaviour:**
A contextual menu shows with options to open a repo in Finder, Atom, or external editor (maybe this last part would be supported via a plugin?).

**Actual behaviour:**
The only option shown is to remove the repo.

Github for Mac currently implements this functionality.

**Comment by shiftkey** [comment]
@desktop/core should this be `up-for-grabs` from this because it involves things we haven't discussed for the 1.0 scope - enabling "Open in Atom" or an external editor.

:thumbsup: on adding "Open in Finder" and "Open in Terminal" to the context menu, if we want that back for 1.0.

**Comment by rickydazla** [comment]
"Open in Atom Beta" would be great too

**Comment by nathanpitman** [comment]
'Open project/repo in Atom' is much missed from the old desktop client.

**Comment by blacktop** [comment]
"Open in iTerm2 (or Hyper once they fix displaying long log/text files) because the default terminal in OSX is ugly" would be great too! 😉

**Comment by rlabrecque** [comment]
So lets try to scope this.

Here's everything I think we would want for a first pass of both this and #1566 since they cover very similar ground:

#### Open in Explorer/Finder

- [x] System Menu (Under Repository, Ctrl+Shift+F)
- [] Repo list -> Repo context menu
- [] Changes -> File context menu

#### Open in external program/editor/Atom

- [] Changes -> File context menu
- [] Repo list -> Repo context menu
- [x] Changes -> Selected file if it's a binary. http://i.imgur.com/hIBnwpj.png
- [] Default to Atom if we can find it installed to keep things in the GitHub brand.
- [] Allow the user to specify their default editor in the options.
- [] For repos: have this open the options for you to specify your editor?
- [] For files: If Atom is not installed then have just open the default Edit verb if available, otherwise open the file normally with [openFile](https://github.com/desktop/desktop/blob/3dc8738e711131047f9973398a5dac08e2cd206e/app/src/lib/open-file.ts), or would we want it to open the options to specify the editor too?
- [] Maybe have a recommendation to install Atom in the options? Brand marketing™©®
- [] Future: Make it file type based? You could have atom as the default, then specify say photoshop for images. Perforce's client does this and it's VERY useful.

#### Open Terminal/Command Prompt

- [x] System Menu (Under Repository, no hotkey set)
- [] Repo list -> Repo context menu
- [] Store whether the user has seen this dialog before and only show it once (Maybe with a never show again checkbox?) http://i.imgur.com/g7Vv4gk.png
- [] Option to select your terminal in Options->Advanced

Let me know if I'm missing anything. Mention me if this list ever needs updating.

**Comment by joshaber** [comment]
"Open in Terminal" and "Show in Finder" are added in #2008.

I split the "Open in Editor" work out into its own issue (#2009).
