### ISSUE TITLE
clone failed

### ISSUE THREAD

**Issue by kirankumar-ctrl** [desktop/desktop#15545]
Permission denied.

Would you like to retry cloning

**Comment by steveward** [comment]
Thanks for the report @kirankumar-ctrl. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
