### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by kirubasriRamasubbu** [desktop/desktop#15556]
not updated in changes

**Comment by kirubasriRamasubbu** [comment]
![Screenshot (16)](https://user-images.githubusercontent.com/111935235/199678194-0b69a4b8-ee0b-430d-9d21-76927cc081e1.png)

**Comment by tsvetilian-ty** [comment]
Thanks for reaching out!

We require the template to be filled out when submitting all issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway 😀
