### ISSUE TITLE
Always getting credentials error

### ISSUE THREAD

**Issue by FatihBekdemir** [desktop/desktop#15574]
### The problem

In my private repository, I have updated my git credentials in the _netrc file under my C:\Users\XXX folder, but still I am getting the following error when I click Fetch Origin button.

fatal: remote error: Credentials set (netrc or input once) are invalid for input user 'XXX'. Please check your credentials before launching new commands.

### Release version

Version 3.1.2 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Update the my git credentials in the _netrc file.
2. Go to click Fetch Origin button.
3. You see "fatal: remote error: Credentials set (netrc or input once) are invalid for input user 'XXX'. Please check your credentials before launching new commands" Error

### Log files

2022-11-07T12:48:38.983Z - error: [ui] `git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin` exited with an unexpected code: 128.
stderr:
fatal: remote error: Credentials set (netrc or input once) are invalid for input user 'XXX'. Please check your credentials before launching new commands.

### Screenshots

![Error](https://user-images.githubusercontent.com/14282789/200314445-5c906b48-41cc-4033-a4cc-0b24abb5828d.PNG)

**Comment by steveward** [comment]
@FatihBekdemir thanks for the issue. Are you working with a repository hosted on GitHub? Is there a specific reason you are wanting to use `.netrc`? Generally I wouldn't recommend that since you're storing passwords in plain text. GitHub Desktop also stores its own credentials separately, so you will want to make sure you are logged in to your GitHub account and have a valid token by going to `File`> `Options` > `Accounts`.

If you are wanting to also use the command line I would recommend using [Git Credential Manager](https://docs.github.com/en/get-started/getting-started-with-git/caching-your-github-credentials-in-git?platform=windows#git-credential-manager) which provides support for multi-factor authentication and a number of Git hosting services.

**Comment by FatihBekdemir** [comment]
Hello Steveward,
My repository is not hosted on GitHub, but on a private server. That's why in order for me to connect that server, I am setting up my .netrc file. The problem here is some time to time, this login-password needs to be regenerated and in this time refreshing the token in the .netrc file and deleting the generic credential in Windows Credentials Manager is not enough for GitHub Desktop.

After removing the already saved credentials from Windows Credentials Manager, if I try to run some git command on my repo, windows prompt me to enter the login name and password, which is totally fine. However, inside the Github Desktop, there is no option to force you to re-ask your login credentials on the same repo.

**Workaround is:** Remove the GitHub Desktop from the PC, delete the installation folder and any traces of GitHub Desktop, then when cloning again, is asking for the credentials like Windows was asking. After that everything starts working again.

Git Credential Manager AFAIK is called implicitly by Git and I don't have to do anything special. If there is any other way I can utilize the GCM, then please let me know.

**Comment by steveward** [comment]
Thanks for the update. Would using SSH be a possibility with your private server? That may be easier to work with in a specific case like this.
