### ISSUE TITLE
TypeError: Cannot read property '__reactInternalInstance$jhcl9oakqvvlttco8ywuerk9' of null

### ISSUE THREAD

**Issue by joshaber** [desktop/desktop#1558]
https://haystack.githubapp.com/desktop/needles/Zqxd13opJM0IgBulUnNCLQ

```
TypeError: Cannot read property '__reactInternalInstance$jhcl9oakqvvlttco8ywuerk9' of null
at Object.V [as getClosestInstanceFromNode] (file:///app/renderer.js:1:15371)
at L (file:///app/renderer.js:3:134325)
at z (file:///app/renderer.js:3:134547)
at L.perform (file:///app/renderer.js:1:88741)
at Object.batchedUpdates (file:///app/renderer.js:3:132824)
at Object.batchedUpdates (file:///app/renderer.js:1:37864)
at dispatchEvent (file:///app/renderer.js:3:135534)
```

**Comment by shiftkey** [comment]
`__reactInternalInstance$jhcl9oakqvvlttco8ywuerk9'`

![](https://cloud.githubusercontent.com/assets/359239/26181696/7f112a5c-3bb5-11e7-8db1-413758cc2d9e.gif)

**Comment by joshaber** [comment]
My current theory is this is related to https://github.com/desktop/desktop/issues/1507, where we'd throw an exception while the component was mounting. It wouldn't be too surprising if React was broken after that.

So I'm gonna close this 🙏 and we can re-open if it's still happening on 0.5.4.

**Comment by cancerberoSgx** [comment]
Make sure to call `wrapper.update()` before the method is throwing the error (like `wrapper.simulate()`). I think that of error is thrown (enzyme) when the wrapper points to nodes that no longer exists (because the page was re-rendered or the original nodes replaced/changed for some reason ). `update()` solved the problem in my case ( error thrown when calling `wrapper.simulate()` - working with enzyme / jsdom)

**Comment by shiftkey** [comment]
@cancerberoSgx thanks for the suggestion - however we're not using Enzyme in the project so this likely isn't a factor. I haven't heard any recent incidents of this but we'll keep an eye on things just in case.
