### ISSUE TITLE
Compatibility Issue with Node18

### ISSUE THREAD

**Issue by felixarjuna** [desktop/desktop#15625]
### The problem

The current version of GHD is not compatible with the node version 18. 

### Release version

latest

### Operating system

Windows 10

### Steps to reproduce the behavior

yarn install
yarn build:dev

**Comment by niik** [comment]
Can you provide some more detail on what happens when you try to build? Text output or screenshots of the error would be appreciated. Right now we're targeting Node 16 so this won't be considered a blocking issue for now but obviously we'll want to get to Node 18 when we move to a version of Electron which targets that.

**Comment by felixarjuna** [comment]
First Error 
![image](https://user-images.githubusercontent.com/79026094/201930207-b8aa3c42-e303-4064-b1d2-6ec771bae020.png)

**Comment by tsvetilian-ty** [comment]
Hey @felixarjuna it looks like your issue is with a dependency, `eslint-plugin-jsdoc` version `37.7.0` doesn't support node 18. The support for node 18 is added in `39.2.5`. You could try running the yarn command with the `--ignore-engines` flag.

**Comment by felixarjuna** [comment]
It works. Thank you so much @tsvetilian-ty

**Comment by tsvetilian-ty** [comment]
Great 🙌 I'll close the issue
