### ISSUE TITLE
Allow skipping the identity portion of the installer

### ISSUE THREAD

**Issue by rossipedia** [desktop/desktop#1563]
I have a fairly custom git CLI configuration, and part of that is I _intentionally_ keep `user.name` and `user.email` out of my `~/.gitconfig` file. Rather, I configure my identity on a per-repo basis.

I think the installer should allow skipping _any_ action that modifies `~/.gitconfig`. This is mainly a "power user" feature, and could just be a small "skip ->" link or similar at the bottom of that page of the installer:

![image](https://cloud.githubusercontent.com/assets/96213/26165029/d0307fde-3aeb-11e7-95b6-9daf11558ed7.png)

**Comment by shiftkey** [comment]
Before letting you skip this step I'd like to make the app more robust when you don't have an email setup https://github.com/desktop/desktop/issues/1364

**Comment by niik** [comment]
I think that this is a pretty advanced flow that @rossipedia is using and I'm not sure it's worth the risk to add a skip link for this view that users only see once. We recommend that you have your username and email set up in the global git config.

The negative consequences for a user that's not well-versed in how Git that hits skip outweigh the benefit to a pro-user who knows how to unset these after the welcome flow.

**Comment by rossipedia** [comment]
> We recommend that you have your username and email set up in the global git config.

Ahh well I guess GH Desktop isn't the client for me then. Cheers!

**Comment by niik** [comment]
> Ahh well I guess GH Desktop isn't the client for me then. Cheers!

I'm very sorry to hear that. Just so that we're clear, are you hitting this in any other place than the welcome flow? As far as I know we don't update the global user.name/user.email settings anywhere but in the welcome flow and the Preferences dialog. Once that's done we actually take [great care to respect](https://github.com/desktop/desktop/blob/master/app/src/lib/git/var.ts) commit identities configured in individual repositories.

I think there are ways to enable what you want but I want to tread very carefully so that users who aren't as well versed in Git configuration end up without a commit identity set. Questions about commits not showing up on people's contribution graph is quite common in our support queue and is very frequently caused by git configuration mistakes. Our intent with the welcome flow is to automatically provide a sane setup with data from the API that also respects things like private emails (https://github.com/desktop/desktop/issues/1019)

**Comment by rossipedia** [comment]
Yeah, I can get behind that. I realize that my workflow isn't a common one by far. Essentially, I've always had issues with Github Desktop and my `%userprofile%\.gitconfig` folder (on Windows).

I store my `.gitconfig` in Dropbox, and symlink to it in my home folder. Editing my `.gitconfig` file creates a hassle because then I have to go in and verify that the symlink is still intact, and also find and fix the things that have been changed (my `.gitconfig` is fairly sizable). Also, editing my config unconditionally always feels intrusive to me. I have my setup, and it works well for how I work. I'd _like_ to integrate GH Desktop into my workflow, but as far as I'm concerned, any tool that enforces it's assumptions about how I should work or have my system configured is ill-behaved at best, if not flat-out broken.

I am absolutely sympathetic to the problems you're trying to solve, though. They're definitely real, and the general use case should be as much "fall into the pit of the success" as possible.

Maybe setup can detect if you have an existing `.gitconfig`, and only show the skip button if there is one.

**Comment by rossipedia** [comment]
Ok, I can admit when I'm being bone-headed. Turns out I can leave the email field blank during this step, and it does exactly what I want. Sorry for the big deal out of nothing!
