### ISSUE TITLE
SVG file's namechange from lower-case to upper-case was disregarded.

### ISSUE THREAD

**Issue by MCSipahioglu** [desktop/desktop#15648]
### The problem

Building my website I load an image from my ./assets folder named "B1.lurien.svg". At one point I changed this files name to "B1.Lurien.svg" Github Desktop did not see this change and hence in my repo "B1.lurien.svg never updated.

### Release version

Version 3.1.2 (x64)

### Operating system

Windows 10

**Comment by tsvetilian-ty** [comment]
Thanks for the issue @MCSipahioglu. Windows fs is case-insensitive but case-preserving. GitHub Desktop is not detecting changes because, as far as the filesystem is concerned the files `B1.lurien.svg` and `B1.Lurien.svg` are the same. 

Check this article about [Git case sensitivity](https://learn.microsoft.com/en-us/azure/devops/repos/git/case-sensitivity) for more information. As suggested In the section "Fixing case conflicts", you could use `git mv -f <conflicting name> <non-conflicting name>` to fix the issue
