### ISSUE TITLE
give me back my drag-to-rebase feature

### ISSUE THREAD

**Issue by LegolasX** [desktop/desktop#15665]
### The feature request

I have been using drag a commit cell to another to rebase for a long time.But after I change my Mac and redownload GithubDesktop, this feature is gone! I really need it! plz give me back! 

### Proposed solution

give me back my drag-to-rebase feature

**Comment by niik** [comment]
Hey @LegolasX. What happens when you try to drag commits? Nothing? I'm able to reorder and squash commits just fine so I'm going to need a little bit more detail such as screenshots or screen recordings to try and figure out what's going on here.

![2022-11-22 14-22-46 2022-11-22 14_23_57](https://user-images.githubusercontent.com/634063/203324961-3ae05ab8-2b50-4d95-884a-28f928410ae8.gif)

**Comment by LegolasX** [comment]
when I grag a commit, nothing happens at all.
you can see my screen recording with mouse movement recoring as well.
just like I can't drag a commit at all.
https://user-images.githubusercontent.com/22345438/203916262-1dd0a22d-3273-49bc-9bc1-5b48767993de.mov

**Comment by LegolasX** [comment]
I am so sorry . it seems that I accidentally use a old version of github desktop 2.6.6 on my icould. therefore it doesnot get updated automatically... After I update my app to 3.1.2, everything works just fine like it used to. Thanks very much and sorry for your trouble!
