### ISSUE TITLE
Unable to run GitHub Desktop on Mac OS with M1 processor

### ISSUE THREAD

**Issue by broslavski** [desktop/desktop#15686]
### The problem

After downloading the desktop version of the program from [here](https://central.github.com/deployments/desktop/desktop/latest/darwin-arm64) I try to run the program, but without success. I get the following error: **“GitHub Desktop” is damaged and can’t be opened. You should move it to the Bin**.

### Release version

Latest for today

### Operating system

macOS: 13.0.1 (22A400)

### Steps to reproduce the behavior

1. Download **GitHubDesktop-arm64.zip** archive from [here](https://central.github.com/deployments/desktop/desktop/latest/darwin-arm64).
2. Unpack the contents of the archive.
3. Drag and drop **GitHub Desktop** file from the **GitHubDesktop-arm64** folder to the **Applications**.
4. Double click the **GitHub Desktop** icon to launch the App.
5. See the error: **“GitHub Desktop” is damaged and can’t be opened. You should move it to the Bin**.

### Screenshots

<img width="372" alt="Screenshot 2022-11-26 at 16 35 56" src="https://user-images.githubusercontent.com/39467594/204094588-6519353f-3f84-464f-9ac2-f6bbdf6868d5.png">

### Additional context

MacBook Pro 16-inch 2021
Chip: Apple M1 Pro
macOS: 13.0.1 (22A400)

**Comment by tidy-dev** [comment]
Would you mind trying to install regular (not  arm64) [version](https://central.github.com/deployments/desktop/desktop/latest/darwin) and see if it works? 

If it does work, it will prompt you to upgrade to the arm64 version if it determines your OS supports it.

**Comment by broslavski** [comment]
It doesn't work. The same behavior as for the ARM version.

**Comment by tidy-dev** [comment]
Ah ok. We have had a [user report some similar](https://github.com/desktop/desktop/issues/3862) and that user noted they fixed it by adjusting their security preferences. That would be my first inclination as well is that something on your machine is blocking it. Any security preferences/antivirus you know may be different on your machine?

**Comment by broslavski** [comment]
No. The situation is different here. I know that some programs cannot be started because of a security lock and additional confirmation is required to open the program. But here there is not even that notification. Just an prompt to move it to the Bin.

**Comment by tidy-dev** [comment]
Thanks you for that info. 
> some programs cannot be started because of a security lock and additional confirmation

Yes. I am familiar with this, and is not what I was referring too -> that is a standard macOs response to untrusted sources of software (not corrupted software).

I was wondering if there was something non-standard about your environment that you have setup in your security preferences or if you had specifically installed antivirus software.  The error you are getting is indicating that something about the program cannot be run (maybe blocked by an antivirus software) and therefore the program is marked as corrupted such that it is recommended to discard it. The [linked user report](https://github.com/desktop/desktop/issues/3862) had the same message as you as well and indicated they had "too" tight security; tho they didn't specify what that meant and as I am unable to replicate this issue, I wondered if you knew of any tighter security settings of software that is on your machine?

**Comment by broslavski** [comment]
No. My system settings are pretty standard. I don't have any anti-virus or security software installed.

**Comment by tidy-dev** [comment]
Ok. I did some brief googling and it seems the general recommendations when any application that is from a trusted source does this is to restart your machine and re download the installer and if that doesn't work check to see if your machine needs any updates, perform updates, restart, and re download. 

Sorry I cannot be of much help, but I am unaware of anything specific to GitHub Desktop that may cause this issue. Let me know if either of the above works.

**Comment by broslavski** [comment]
Yes, of course. I'll let you know if anything works. In principle, I can work with GitHub through the Web interface. But maybe my information will be useful in development, so I decided to write about my problem. Anyway, thank you for the support.

**Comment by shmoeaz** [comment]
@tidy-dev , I am getting the same error and from some of the googling I did, found that Apple apparently "quarantines" apps that are extracted from zip files downloaded from the internet. With my upgrade to macOS Ventura, rather than just warning me about the risk and allowing me to override, it actually said the app was damaged and prompted to move to trash.
If you go to 'Privacy & Security' in the preferences, you can tag the app to open any ways, which will resolve the issue.
Hope this helps.
Any chance of GitHub Desktop getting a proper .dmg/.pkg installer file that will better play with proper macOS configurations?

**Comment by tidy-dev** [comment]
@shmoeaz Thanks for the info. I will bring it up to the team (tho likely after the new year).

**Comment by steveward** [comment]
@shmoeaz @broslavski I'm on macOS Ventura (not arm64, though), and was unable to reproduce the issue. Are you both running M1 machine? I tried modifying various security settings as well.  Is there anything specific in your machine setup that I could be missing to help reproduce this? We're trying to narrow down what could be causing this since we haven't seen many reports of it (and figured that would be the case if it was easily encountered on Ventura).

**Comment by shmoeaz** [comment]
@steveward , I am on a new M1 Max and was setting my machine up for the first time at late November, so at time, the machine settings were factory. The machine came with MacOS Monterey and I was able to install GitHub Desktop without any issues as I recall. A few days later I let the system upgrade to Ventura and it was here that I ran into issues. 
I don't know if the App installed with Monterey was still marked as quarantine but was still operational under Monterey, hthen when Ventura was installed it became a little more strict. I'm not sure. However, I removed the GitHub Desktop and tried to reinstall and received the same message, 'the app was damaged'.  It was here that I started researching and learned about Apple quarantine for apps that are extracted from zip files downloaded from the internet.
Hope this helps.

**Comment by broslavski** [comment]
I haven't yet encountered problems with applications downloaded from the Internet (except GitHub Desktop). All of them run either immediately or after confirmation through settings. With GitHub Desktop, I just get an error notification, prompting to delete the program to the bin, which cannot be bypassed in any way. Today I tried the installation again and got the same result.

**Comment by erinmclear** [comment]
I'm having the same issue. Any new updates? I just get the error "Github Desktop can't be opened."

**Comment by steveward** [comment]
@erinmclear were you previously running an older version of GitHub Desktop, or this occurring after a fresh install? See [the pinned issue](https://github.com/desktop/desktop/issues/16052) for more information if you had an older version of GitHub Desktop installed on your machine and are experiencing a crash on launch.

**Comment by erinmclear** [comment]
This was after a fresh install. Running Ventura 13.1 and get this error.
<img width="818" alt="Screenshot 2023-02-03 at 11 04 39 AM" src="https://user-images.githubusercontent.com/8235851/216661043-79fb5af2-b50d-4c62-98e5-35b4b6c862b1.png">

**Comment by steveward** [comment]
@erinmclear there are a few things I'd recommend trying:

- Trying restarting your machine and then launching the app
- Make sure you are launching the app from the `/Applications` directory
- Install a fresh copy of GitHub Desktop to verify there isn't an installation issue

**Comment by BennyX8** [comment]
I've had same issue for some days now. So I downloaded a fresh version of GitHub Desktop and the issue is gone.

I believe this was deliberate as there was a security issue detected by GitHub...more details [here](https://github.blog/2023-01-30-action-needed-for-github-desktop-and-atom-users/)

**Comment by smileBeda** [comment]
> “GitHub Desktop” will damage your computer. You should move it to the Bin.

I have used this since years, on the same laptop.
This is 100% unrelated to new computer, or whatever.

This is the report:
[report.zip](https://github.com/desktop/desktop/files/10682398/report.zip)

This is urgent, and I am uncomfortable using it anymore given the rather distressing message without further reasoning.

If this is really related to https://github.blog/2023-01-30-action-needed-for-github-desktop-and-atom-users/ as @BennyX8 above mentioned (also my suspicion) then I am _highly_ disappointed in how this is handled, I received ZERO email or whatever notification, and if you are capable to throw such notice to my screen when I start up the app, then AT LEAST you could also add an explanation that does not stop one's heart.

Truly, I am reconsidering even re-using an app that handles security issues like that

**Comment by steveward** [comment]
@smileBeda it does look like your issue was from the revoked certificate, as I see this in the log you shared:

```
"exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGKILL (Code Signature Invalid)"},`
```

The crash message you saw was a system dialog, and not something that we would have been able to modify to indicate. I'm sorry for the frustration.

To resolve this you can download the app from https://desktop.github.com and install it again. Your stored repositories and account information will not be lost. See the [pinned issue](https://github.com/desktop/desktop/issues/16052) as well for further information.

**Comment by jack89roberts** [comment]
I've had the same problem on an Intel Mac with the "GitHub Desktop is Damaged and Can't be Opened" message multiple times this year, I think since upgrading to Mac OS Ventura 13.1. Deleting and reinstalling tends to fix the problem for a while, but it's always come back eventually (re-appeared today after a few weeks with no issues).

**Comment by topyihao** [comment]
I have the same problem. I reinstall the GitHub desktop and the problem solved.

**Comment by jack89roberts** [comment]
> I've had the same problem on an Intel Mac with the "GitHub Desktop is Damaged and Can't be Opened" message multiple times this year, I think since upgrading to Mac OS Ventura 13.1. Deleting and reinstalling tends to fix the problem for a while, but it's always come back eventually (re-appeared today after a few weeks with no issues).

It happened again today, 2 weeks later. This (from https://github.com/desktop/desktop/issues/15686#issuecomment-1358232072) seemed to solve it, at least for now:

> If you go to 'Privacy & Security' in the preferences, you can tag the app to open any ways, which will resolve the issue.

**Comment by terrenceferguson** [comment]
> > I've had the same problem on an Intel Mac with the "GitHub Desktop is Damaged and Can't be Opened" message multiple times this year, I think since upgrading to Mac OS Ventura 13.1. Deleting and reinstalling tends to fix the problem for a while, but it's always come back eventually (re-appeared today after a few weeks with no issues).
> 
> It happened again today, 2 weeks later. This (from [#15686 (comment)](https://github.com/desktop/desktop/issues/15686#issuecomment-1358232072)) seemed to solve it, at least for now:
> 
> > If you go to 'Privacy & Security' in the preferences, you can tag the app to open any ways, which will resolve the issue.

I couldn't find this setting under "Privacy & Security" in Preferences, but I did find it whenever I went to the application itself and selected "Get Info" from the context menu:

<img width="916" alt="image" src="https://github.com/desktop/desktop/assets/19277507/b725924b-69f9-400e-8c2f-bd91de0e784a">

**Comment by steveward** [comment]
Closing this out as stale.

**Comment by undesicimo** [comment]
Moving the unzipped executable to the Applications folder before running seems to solve the not trusted prompt

**Comment by dknauss** [comment]
This problem still exists.

**Comment by imeligilani** [comment]
> [@tidy-dev](https://github.com/tidy-dev) , I am getting the same error and from some of the googling I did, found that Apple apparently "quarantines" apps that are extracted from zip files downloaded from the internet. With my upgrade to macOS Ventura, rather than just warning me about the risk and allowing me to override, it actually said the app was damaged and prompted to move to trash. If you go to 'Privacy & Security' in the preferences, you can tag the app to open any ways, which will resolve the issue. Hope this helps. Any chance of GitHub Desktop getting a proper .dmg/.pkg installer file that will better play with proper macOS configurations?

Thanks mate, it worked.

**Comment by pgwilliams** [comment]
Same issue here with an M2 Max running Sequoia 15.5

Under Privacy & Security, the only option I can see to relax is "Allow applications from : App Store & Known Developers"  so I'm not getting an option to allow untrusted applications to open on a per application basis.

I did unzip on the command line.   I'll try again using some other extractor, and also not put the download into the Downloads folder...
