### ISSUE TITLE
GH Desktop stopped working after update to MacOS 13 Ventura

### ISSUE THREAD

**Issue by cmoser13** [desktop/desktop#15705]
### The problem

Since I have updated my Mac to OS 13 I get multiple errors when opening the Desktop App. It is only related to my local repos that are saved on external drives though. My repos saved on my machine do not get the error.  It appears to happen when trying to fetch and also when trying to commit. 

`Command failed: /Applications/GitHub Desktop.app/Contents/Resources/app/git/bin/git log b885c110a7a27005dd0b12cfea6e825940203b5a -C -M -m -1 --no-show-signature --first-parent --raw --format=format: --numstat -z --`

### Release version

3.1.2

### Operating system

OS 13 Ventura

### Steps to reproduce the behavior

1. Open GitHub Desktop 

### Screenshots

<img width="614" alt="Screenshot 2022-11-30 at 1 23 43 PM" src="https://user-images.githubusercontent.com/6320048/204878071-66fb56a8-2b91-4cab-b109-0dc9a32dc1bd.png">

[2022-11-30.desktop.production.log](https://github.com/desktop/desktop/files/10134456/2022-11-30.desktop.production.log)

**Comment by steveward** [comment]
Thanks for the report @cmoser13. Just to confirm -- are these repositories on external USB drives or mounted network drives?

Could you also upload the entire log file so that we could take a look? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by cmoser13** [comment]
Yes this only happens on external drives and also my mounted Synology. 

[2022-11-30.desktop.production.log](https://github.com/desktop/desktop/files/10134464/2022-11-30.desktop.production.log)

**Comment by steveward** [comment]
@cmoser13 I was able to reproduce this as well with a network mounted drive. We're tracking this in https://github.com/desktop/desktop/issues/15539 so I'd recommend following along there for updates as we investigate this.
