### ISSUE TITLE
Feature Request: Toggle --assume-unchanged

### ISSUE THREAD

**Issue by alrz** [desktop/desktop#1571]
Toggle `-assume-unchanged` (from git update-index)  for a changed file, basically, it excludes the file from changes without actually discarding them. Useful for when you want to ignore some changes (because it's user-specific or just not yet pushed to upstream e.g a pull request is not merged yet) so that they do not clutter actual changes you're working on.

**SmartGit** has this feature.

**Comment by joshaber** [comment]
Hi @alrz, could you tell us more about what this would accomplish? What's the use case here?

**Comment by alrz** [comment]
@Joshaber I've updated the opening comment.

**Comment by shiftkey** [comment]
Yeah, our relationship with the index has been Complicated™ since forever. First I'd like for us to get it better aligned with Git's model - #1397 is a first step down that path - and then look at how that affects how we display things in the app.

@alrz

> Useful for when you want to ignore some changes (because it's user-specific or just not yet pushed to upstream e.g a pull request is not merged yet) so that they do not clutter actual changes you're working on.

`git update-index --assume-unchanged {file}` isn't something I use a lot, so I'd like to wrap my head around the flow better. Can you describe a bit about your workflow from the CLI, and particularly how it fits with how you then commit changes? Do you return to the `assume-unchanged` files at some point to track them again, or is this purely a measure to ignore changes but keep them around for convenience?

**Comment by alrz** [comment]
>Can you describe a bit about your workflow

As an example, I had a PR to update .gitignore for a repo but as long as it was not merged I had to cherry-pick my commit and make .gitignore assume-unchanged, I would not bring it back until it's merged I can sync with upstream. Another use case is when you want to make some user-specific changes, e.g. you might use a different database config on your own machine, then you probably want to assume-unchanged your config file to have it excluded from the change set to prevent accidental commit.

**Comment by joshaber** [comment]
Thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I'm going to add the `future-proposal` label to this issue and close it out, so that we don't get overwhelmed with our backlog! We'll revisit these as part of our next planning session.

**Comment by danielb987** [comment]
I think it is very important to have the ability to create files, get them into the repository, and then ignore them.

I'm new to git and I'm using Github Desktop on Windows and Linux, and when I create a new Netbeans Java project, NetBeans create some project files that I want to have in my repository, but I never want these files to be changed by someone else that starts to work on my project.

I have this problem when I start a project on my Windows computer and then also clone it to my Linux computer. Netbeans needs its project files, but it stores some local info that never should go into the repository.

The point is that three different users working on the same project will have three different Netbeans project files, but they all need the project files. These files may be changed as soon as I open the Project in Netbeans. So the files needs to be in the repository but they should never be updated in the repository. If I'm not able to ignore these files, the files will be changed back and forth between the commits for the different users..

I belive that many users missunderstand what "gitignore" does. Searching Google for "github desktop ignore not working" gives a lot of hits. I did that misstake myself. https://github.com/desktop/desktop/pull/3164#issuecomment-340971165

So the user interface is missleading people which not fully understands how git works.

**Comment by billygriffin** [comment]
I'd like to solve this as a problem as opposed to just arbitrarily adding a toggle for an infrequently used git operation. We have https://github.com/desktop/desktop/issues/2537 open to evaluate how gitignore is used in Desktop and ensure that's more intuitive for folks, so I think we ought to look at it in that context. If we end up using --assume-unchanged under the hood to enable a certain functionality that make certain flows work as users would expect, that's certainly in the realm of possibility. I'm going to remove `future-proposal` here.
