### ISSUE TITLE
as I am making a commit, I am getting that error.

### ISSUE THREAD

**Issue by HashirAsmat** [desktop/desktop#15721]
### The problem

Error:
Windows Subsystem for Linux has no installed distributions.
Distributions can be installed by visiting the Microsoft Store:
https://aka.ms/wslstore

### Release version

Version 3.1.2 (x64)

### Operating system

Windows 10

### Screenshots

![github-error](https://user-images.githubusercontent.com/103664858/205502670-9893153d-1136-4b48-9a61-960b342180ae.PNG)

### Additional context

can u please tell me how to solve the issue... i have already reinstalled the desktop Github but still getting the same error.

**Comment by steveward** [comment]
Thanks for the issue @HashirAsmat, we saw this previously in https://github.com/desktop/desktop/issues/11015. 

Do you have any pre-commit hooks in this repository? Does this happen in multiple repositories, or just one specific repository?

**Comment by hybridview** [comment]
Same happening here after Github Desktop updated itself. I tried to commit a file from different (older) project and it surprisingly worked. The project I am having issues with, I added today right before Github Desktop updated, so that's another variable I will have to work out. I have no pre-commit hooks that I know of (I've never used them, so not sure how to check).

**Comment by hybridview** [comment]
I tracked down the source of my issue, but do not understand what the problem is. By removing BOTH parts below, the commit works without error.

In my root package.json, 2 parts always trigger the error (whether only 1 exists or both).
1) Under scripts: If the string fragment "pre-commit" exists anywhere on a line, it triggers the error. Even prefixing with xx, yy, etc does not help. I need to fully remove all "pre-commit" string fragments.
2) The "husky" hooks part also triggers the error.

	"license": "MIT",
	"scripts": {
		"**xxpre-commit**": "cd api && npm run **zzpre-commit** && cd ../client && npm run **yypre-commit**",
		"install-dependencies": "npm install && cd api && npm install && cd ../client && npm install",
		"build": "cd api && npm run build && cd ../client && npm run build",
		"start:production": "cd api && npm run start:production && cd ../client && npm run start:production"
	},
  "devDependencies": {
    "husky": "^8.0.3"
  },
  "husky": {
    **"hooks": {
      "pre-commit": "npm run pre-commit"
    }**
  },
	"dependencies": {}
  
}

**Comment by hybridview** [comment]
The config fragment below is adjusted to prevent the crash. ALL of those changes are needed to allow a commit. Very strange.

	"license": "MIT",
	"scripts": {
		"pr_-_ommit": "cd api && npm run pr_-_ommit && cd ../client && npm run pr_-_ommit",
		"install-dependencies": "npm install && cd api && npm install && cd ../client && npm install",
		"build": "cd api && npm run build && cd ../client && npm run build",
		"start:production": "cd api && npm run start:production && cd ../client && npm run start:production"
	},
	"devDependencies": {
		"husky": "^8.0.3"
	},
	"_x_husky": {
		"hooks": {
			"pr_-_ommit": "npm run pr_-_ommit"
		}
	},
	"dependencies": {}
}
