### ISSUE TITLE
Capture and report `unresponsive` and `crashed` events

### ISSUE THREAD

**Issue by joshaber** [desktop/desktop#1573]
For now they should just go through the same exception reporting mechanism we're already using.

**Comment by shiftkey** [comment]
For reference, these are events raised by `webContents`, not `app`.

**Comment by shiftkey** [comment]
@joshaber it looks like there are complementary `unresponsive` and `responsive` events - do we want to really interrupt the user whenever it does become `unresponsive`, in case it does come back?

<img width="693" src="https://user-images.githubusercontent.com/359239/28676812-0bf3bc1c-72c2-11e7-88d8-0a2f8bd3ec06.png">

**Comment by shiftkey** [comment]
Actually, this is what I think we should do for these events:

 - `crashed`: log locally and report, maybe should show something to the user because this isn't a recoverable scenario.
 - `unresponsive` - set a timer for a period of time - (10 seconds? less? i dunno) and if the timer elapses, log locally and report. If `responsive` is then raised, abort the timer.

There's not much additionally that we can provide within this context, but getting some data on this will help with identifying trickier environmental issues.

**Comment by joshaber** [comment]
Yup, I agree 👍

**Comment by shiftkey** [comment]
Moving this to `help-wanted` because I think it's some low-hanging fruit for someone to pick up. 

 - [API docs for `webContents`](https://electronjs.org/docs/api/web-contents)
 - [`app-window.ts`](https://github.com/desktop/desktop/blob/development/app/src/main-process/app-window.ts) is where we hook into `webContents` events, so that seems like the ideal place to enable this

**Comment by billygriffin** [comment]
Since nobody has picked this up, I’m going to close it for now but happy to reopen if we don’t feel like we’re getting the error reporting we’re hoping for.
