### ISSUE TITLE
GitHub Desktop 3.1.2 Windows 11

### ISSUE THREAD

**Issue by Jordan1489** [desktop/desktop#15745]
### Release version

3.1.2

### Operating system

Windows 11

### **I would like to clarify before the update that I performed windows 11 it worked. If you have solutions or info or if you encounter the same problems. I uninstalled and reinstalled several times even old versions always the same problem.**

**Comment by niik** [comment]
Hey @Jordan1489, thanks for reaching out. We're going to need more information about what you're experiencing before we can troubleshoot. The latest version of Desktop (3.1.2) definitely "works" on Windows 11 so without more information regarding your particular environment and what you're experiencing we won't be able to help. As for your question regarding RAM, 8Gb would be more than enough to run Desktop so that's not likely to be an issue.

Please reply with more details on what's happening, i.e. is the app not opening at all, is it hanging, do you see an error message or some kind of dialog?

Could you upload a log file from GitHub Desktop? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by Jordan1489** [comment]
### **@niik** 

### **The application tries to open in the task manager without success. I don't understand.**

### **I tried to see where the Github Desktop logs are but I don't see where it is exactly.**

### **Thanks.**

![image](https://user-images.githubusercontent.com/83274832/206187275-0b6c7180-0fce-4724-a388-666b3156962a.png)

**Comment by steveward** [comment]
@Jordan1489 thanks for sharing that. Are you running any antivirus/security software on this machine that could be preventing GitHub Desktop from opening?

If that isn't the case I'd recommend trying a fresh install just to confirm there isn't an installation issue.

Here's how to do that:

1. Close GitHub Desktop
2. Open File Explorer
3. Go to `%LocalAppData%` and delete the `GitHubDesktop` directory
4. Go to `%AppData%` and delete the `GitHub Desktop` directory
5. Reinstall GitHub Desktop from http://desktop.github.com

Let me know if that helps.

**Comment by Jordan1489** [comment]
@steveward 

### **I followed the procedure and even checked if I had system errors always the same problem I would like to clarify that this problem occurred after a big update of windows 11 a few days ago. Is it related or not I wonder.**

**Comment by Jordan1489** [comment]
###  **I allowed myself to do a new post on this issue because I saw in the github forum all its problems were on windows 10 and not windows 11, I don’t know if other people are in the same case as me on windows 11.**
### **Thank** you,

**Comment by elliot-huffman** [comment]
I have Windows 11 22H2 and it is working for me.
Please see my screenshot:
![image](https://user-images.githubusercontent.com/5030490/206757117-7b71dc9e-ccb2-44c4-8491-e1ebef3afbe3.png)

**Comment by steveward** [comment]
@Jordan1489 are you running any security/antivirus software on this machine that could be interfering with GitHub Desktop? I have a test machine running Windows 11 and was unable to reproduce this issue.

**Comment by Jordan1489** [comment]
### @steveward I disabled my antivirus always the same problem.

### @elliot-huffman I don't see where that's what you're doing thank you.

### I also updated everything with the order "winget upgrade -h -all" So I don't know if I'm going to find a way out and no way to contact GitHub to escalate errors.

**Comment by niik** [comment]
Could you upload a log file from GitHub Desktop? The logs can be found in `%APPDATA%\GitHub Desktop\logs\`. The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue. Thanks!

**Comment by Jordan1489** [comment]
@niik  I found this as a log file. Thank you.
![image](https://user-images.githubusercontent.com/83274832/207297406-4b9cc02a-e9b8-4a1d-b75b-8813f5cef982.png)

**Comment by niik** [comment]
@Jordan1489 thanks but that's unfortunately not a GitHub Desktop log file. You'll have to locate the `logs` directory within your `%AppData%\GitHub Desktop` folder. Typically this will be something like `C:\Users\niik\AppData\Roaming\GitHub Desktop\logs` although instead of `niik` it would be your username. In that folder you should see a bunch of files named after the date they were created

<img width="880" alt="image" src="https://user-images.githubusercontent.com/634063/207334915-8af39dfa-e95e-4995-9c4f-314f6cb33ab6.png">

Please pick a recent one of these files and attach it here.

**Comment by Jordan1489** [comment]
![image](https://user-images.githubusercontent.com/83274832/207352706-c25c7864-0c01-4f37-a885-fe1dfa80303b.png)

@niik 
### I installed and uninstalled github desktop several times by deleting the folder several times it did not create logs.

**Comment by niik** [comment]
@Jordan1489 this is confusing but the folder your screenshot is showing is where the application itself is installed "AppData\\**Local**\\GitHubDesktop". You'll need to look in the "AppData\\**Roaming**\\GitHub Desktop" folder instead, that's where the logs are written to.

**Comment by Jordan1489** [comment]
![image](https://user-images.githubusercontent.com/83274832/207355692-e43ee380-af15-403a-91ef-fd8cd2419521.png)
@niik  found thank you sorry I left in the wrong thank you for your help.

**Comment by steveward** [comment]
Can you drag-and-drop a few of those files into an issue reply to upload them here? Thanks!

**Comment by Jordan1489** [comment]
@steveward I put the most recent files thank you.


[2022-12-10.desktop.production.log](https://github.com/desktop/desktop/files/10218967/2022-12-10.desktop.production.log)
[2022-12-11.desktop.production.log](https://github.com/desktop/desktop/files/10218968/2022-12-11.desktop.production.log)
[2022-12-12.desktop.production.log](https://github.com/desktop/desktop/files/10218969/2022-12-12.desktop.production.log)
[2022-12-13.desktop.production.log](https://github.com/desktop/desktop/files/10218970/2022-12-13.desktop.production.log)

**Comment by Jordan1489** [comment]
@steveward @niik 

### No one found anything wrong with the logs I posted. Thanks.

**Comment by steveward** [comment]
@Jordan1489 apologies for not getting back to you -- are you still having issues running GitHub Desktop on your machine?
