### ISSUE TITLE
Feature request: Add multiple existing local repos at a time ("Scan for repos")

### ISSUE THREAD

**Issue by reisenberger** [desktop/desktop#1574]
### Description

A useful feature when migrating from a previous client: Add multiple existing local repos at a time.  

For instance, if all my repos are in `c:\users\xxx\Documents\Github` (or similar), it would make sense to be able to point to that single folder, recursively search the folders below and add all repos found.

### Version

**GitHub Desktop version:** 0.5.3

**Comment by rlabrecque** [comment]
Can we just go one step further and have a scan for repos button? I want to scan my whole D:\ drive, but I don't want to include all the repos from there.

Ideally the UI would give me a list, a 'select all' button, and an 'import selected'. I could then select what I want with ctrl/shift+click or a checkbox next to each repo.

**Comment by ryangribble** [comment]
I found that I was able to multi-select multiple repo folders (80+ infact) and drag/drop them onto the app, and it added them all as repos.

Not saying it shouldnt be a more obvious/first class feature, but just letting you know if you need to do it currently - you can drag/drop multiple folders from Explorer or Finder

**Comment by reisenberger** [comment]
Good to hear that @ryangribble - saving me some time here.

Digging deeper, in my case, I've grouped repos pulled down by folder-per-owner (ie /owner/repo-name), so I can't multiselect much (items to multi-select are in different owner folders ...).  

For the project devs: a recursive folder search followed by multi-select checkboxes (as @rlabrecque suggests) would be ideal.  

Trying hard to like the new GitHub Desktop, but migrating from the old is still making me import 80-or-so repos one-by-one ...

**Comment by joshaber** [comment]
Thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I'm going to add the `future-proposal` label to this issue and close it out, so that we don't get overwhelmed with our backlog! We'll revisit these as part of our next planning session.

**Comment by andrewsav-datacom** [comment]
@joshaber could it be in scope for "Better onboarding"?

**Comment by EddieOne** [comment]
I finally upgraded, 😢

**Comment by steveward** [comment]
Feedback from https://github.com/desktop/desktop/issues/6400:

>Description
I use a folder probably like most programmers where I keep my projects on my hard drive. I tend because of organisation to shift some projects or rename them cause the desktop app to lose the repository. I would love for the Desktop app to have a functionality that you can do either/or/and that allows to add multiple repositories add once:
>
>1. User select
The user can selected a folder through browsing. That folder and sub-folders will be scanned for existing repositories and added onto the app's list.
>
>2. Default folder in settings
Through either a button or/and on startup, the app looks through the given folder list in its settings. And scans each of those folders and possible sub-folders for repositories.

**Comment by shiftkey** [comment]
@karl-ravn opened #7737 which relates to this area:

> When you have a lot of projects that you use occasionally and just installed Github Desktop, it's a pain to sit and add the projects one by one.
> 
> Looking at your competitor SourceTree, they have a "Scan directory" which finds _all_ git-projects and adds them. This is very convenient and must be a super simple feature to add since it's just a directory traversal and adding anything in there in case it's not already present in your list.

**Comment by rkrug** [comment]
See - https://github.com/desktop/desktop/issues/7737#issuecomment-507160113 effectively use SourceTree to scan and find the repos, and drag and drop all of them into the github app.

**Comment by Niellesx** [comment]
https://ref.kickex.com/07101d78c69f867d2e431efc36c6e1c1

**Comment by steveward** [comment]
Feedback from #11939:

>It would be a good solution for users because they don't want to import every repository one by one.
Because it is hard to import each and every remote github repositories in to the github desktop app.

**Comment by EddieOne** [comment]
This has been solved. I believe it is possible to drag folders into the GitHub app as needed.

**Comment by RichiCoder1** [comment]
Echoing the above feedback. I organize various orgs and oss into separate folder and mostly operate via the (excellent) gh cli these days. I'd like to use the GH Desktop more, especially with the recently added notification support, but the thought of adding (and organizing) all 100+ repositories is daunting. Especially compared to SourceTree or GitKraken.

**Comment by steveward** [comment]
Requested in https://github.com/desktop/desktop/issues/15674.

**Comment by tidy-dev** [comment]
Requested in #15696

**Comment by bohrasankalp** [comment]
+1 for this feature in roadmap soon.

**Comment by acovaci** [comment]
@steveward Looks like all of the other feature req link here but this one was closed without implementation? I'd really like this functionality too :)

**Comment by acovaci** [comment]
@tidy-dev @steveward Looks like all of the other feature req link here but this one was closed without implementation? I'd really like this functionality too :)

**Comment by ftrotter** [comment]
FYI, the face that drag and drop supports many folders at once solved my use-case. And there is even a something on the interface that suggest that you can drag and drop. But I ignored that because I thought it only worked one at a time. 

It should just say "You can add lots of repos at once this way!" and that would have prevented a search for me!

**Comment by steveward** [comment]
In https://github.com/desktop/desktop/issues/17793 it was requested to have the option to quickly remove and add back repositories that have been moved on disk.

**Comment by joceqo** [comment]
i don't get why didn't do it yet i'm not the most experience dev but i could quickly made a workaround since i put all my repositories in desktop 
```
  const desktopPath = path.join(os.homedir(), '/desktop')
  const process = spawn('find', [desktopPath, '-name', '*.git', '-type', 'd'])
```
 and calling `_addRepositories` on all thoses results

**Comment by AnweshGangula** [comment]
> I found that I was able to multi-select multiple repo folders (80+ infact) and drag/drop them onto the app, and it added them all as repos.

Works perfectly

**Comment by steveward** [comment]
Requested in https://github.com/desktop/desktop/issues/19662.

**Comment by sergiou87** [comment]
Requested in https://github.com/desktop/desktop/issues/20695

**Comment by noisecrime** [comment]
Just going to add another request for this feature, having just had a disk corruption that ended up clearing all the repositories from my Github Desktop installation, leaving me having to re-add almost 300 repositories across various root folders and drives.

Drag & Drop is not a solution in this case as it is still going to take  a considerable amount of time as repositories are spread under dozens of sub folders across several drives.

I'm somewhat staggered that a request that has consistently been made since at least 2017 has been denied. The stated reason has been its not on the road map, but that doesn't explain why it isn't.  Granted I've seen a few suggestions that would take effort to implement with a UI etc, but a simple scan root directory and import all git repos found should be relatively straightforward and address the majority of use-cases.

In the meantime I've written a powershell script (https://gist.github.com/noisecrime/558b696af624616fa5de14cb04497c21) that semi-automates part of the process. It relies on building a text file that lists all your .git directories then this script opens each in turn ( advanced via key press) and waits for you to click the 'add repository' button in Github Desktop.

I wish Github Desktop at least had a command line option to 'add' a given local repository automatically, that would make this process a little bit easier. For example github -add <folder path> -LTS, which would skip the 'add repository' dialog and in this case enable LTS support if required.

**Comment by DereC4** [comment]
> I found that I was able to multi-select multiple repo folders (80+ infact) and drag/drop them onto the app, and it added them all as repos.
> 
> Not saying it shouldnt be a more obvious/first class feature, or to be able to select a top level folder and have it scan all subfolders... but just letting you know if you need to do it currently - you can drag/drop multiple folders from Explorer or Finder

thank you very much half a decade later
