### ISSUE TITLE
(Live) Staging

### ISSUE THREAD

**Issue by moritztim** [desktop/desktop#15760]
### The feature request

As soon as changes are selected, stage them, or add an option to do so manually.

### Proposed solution

This would help, if you want to do some more complicated commit command but use the existing UI in GH Desktop to stage specific changes, instead of doing that manually.

### Additional context

![image](https://user-images.githubusercontent.com/90388353/206865361-96e2aaef-15d6-4aaf-8a61-9316df6cbc89.png)
There could be an extra option here called "Stage/Add selected changes"

![image](https://user-images.githubusercontent.com/90388353/206865409-fe4d533c-fc20-4625-9b63-162d864e7100.png)
or here

![image](https://user-images.githubusercontent.com/90388353/206865463-d2f16afa-bf6d-4745-bbe0-dc282898db9c.png)
or down at the end of the changes panel

**Comment by niik** [comment]
Hey @moritz-t-w, thanks for reaching out. Not directly integrating with Git's staging area is an intentional design decision of Desktop. It, as with any tradeoff, has both positive and less positive implications. In this case we still believe that not incorporating the concept of a staging area (and all the complexity that entails with partial stages, etc) within the app lets us offer a better experience to our users. While we understand that it's not for everyone and while I can personally see how the feature you're suggesting could be of use to me we're not looking to change this particular decision in the near term.
