### ISSUE TITLE
Git LFS Not initializing on Github Desktop for PC

### ISSUE THREAD

**Issue by DoubleDaveEnt** [desktop/desktop#15778]
### The problem

I have cloned Repo and I can not find a Github LFS setting option.

### Release version

3.1.2

### Operating system

Windows 11

**Comment by sergiou87** [comment]
If the repository already has LFS, it should Just Work™ from GitHub Desktop.

Otherwise, [as mentioned in the docs](https://docs.github.com/en/desktop/installing-and-configuring-github-desktop/configuring-and-customizing-github-desktop/about-git-large-file-storage-and-github-desktop), I'm afraid you need to initialize Git LFS in the repo from the command line following [these instructions](https://docs.github.com/en/repositories/working-with-files/managing-large-files/configuring-git-large-file-storage).

Is that helpful?

**Comment by Beny-Hacker** [comment]
I'm also having trouble downloading large files that need LFS
In gitbash it works fine

Release version
3.3.11
Operating system
Windows 11

**Comment by kevincastejon** [comment]
It used to be automatically proposed by github desktop when creating the repo, not anymore...
