### ISSUE TITLE
Commit to main possible with merge conflict

### ISSUE THREAD

**Issue by AVTCHe** [desktop/desktop#15786]
### The problem

Commit with merge conflict ignored and pushed to main, leading to project settings being reset to default. 

### Release version

Version 3.1.2 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

Open Unity Project Settings
Change
Merge conflict shown in Github Desktop, commit anyway

Merge with main 
pull main
Project settings in unity reset because of merge conflict

**Comment by steveward** [comment]
Thanks for the report @AVTCHe. It is possible to commit when dismissing the merge conflict modal, but you will see this dialog:

<img width="640" alt="Screenshot 2022-12-16 at 10 44 37 AM" src="https://user-images.githubusercontent.com/721500/208135712-b55967cb-fcc5-4e9d-908c-2a166dcd9697.png">

I'm going to close this out as this is expected behavior, but if you encountered another issue (like not seeing that dialog), then let me know and we can investigate further.
