### ISSUE TITLE
Github desktop Repository Publishing

### ISSUE THREAD

**Issue by souley16pd** [desktop/desktop#15833]
### The problem

I am trying to publish (push) a specific folder from my PC called "Vsc-Experiments"  to one of my github repos. I am getting the error message "The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed." I have been trying to fix this for hours, uninstalled/installed github desktop multiple times, erased the app completely from my system to reset settings, logged out, tried gitbash, different ways of pushing that repo but it won't work. Other repos I have work fine. During the push process, it looks like Github desktop is referencing a repo on Github.com called "pd-vs-Scripts-Backup" but I deleted that repo manually from Github site.

### Release version

3.1.2(x64)

### Operating system

Windows 11

### Steps to reproduce the behavior

1. I add the repo in github desktop by dragging and dropping it / I also tried a new repo and copied that repo's content in that new repo
2. initial commit, new branch, Publish etc etc... that's when I get the error message

### Screenshots

![github desktop issue](https://user-images.githubusercontent.com/96851433/209754395-ff8a0950-f218-4cdd-ac9f-c9b39de7e360.png)

**Comment by tidy-dev** [comment]
Hi @souley16pd, 

I was able to reproduce your situation by:
1. Create a repo on GitHub.com called 'testing-non-existent'
2. Cloned this repo to my computer via GitHub Desktop. I now have a folder called 'testing-non-existent'
3. I went to GitHub.com and deleted 'testing-non-existent'.
4. Now I went back GitHub Desktop and tried to fetch or push to receive the error.

This means what it says, the repo you have locally has a remote set up that doesn't exist, thus when it tries to talk it can't. You can see the remote by going to file main menu of Repository > Repository Settings > Remote.
![image](https://user-images.githubusercontent.com/75402236/209839863-e9c8c9f1-ca55-41a2-8019-48936988f263.png)

_Side note for following steps: If you go to this image and you see pd-vs-Scripts-Backup.git, but you want it to point to GitHub.dotcom repo of 'Vsc-Experiments'. You should change it so that it has vsc-experiments.git on the end so it is point to the remote you want it to. (This would indicate to me that you renamed this folder at some point, but that does not rename the repo config_

You have two ways you can resolve this:
1. (Probably simplest) Go to GitHub.com and create the matching repository. Thus for me since I have a remote of `https://github.com/tidy-dev/testing-non-existent.git`.  I create a repository named `testing-non-existent`. Try to fetch in GitHub Desktop. You should no longer see the error and can push/pull as you like. (If you return to dotcom, you should see it update to match your local)


2. (A little more complicated.. tho maybe what you are expecting of Desktop) Make GitHub Desktop believe it is local repository that does not have a remote so that it will publish a new repository.
   a. Open your repository folder. For me that is a folder named 'testing-non-existent'
   b. Make it so I can see hidden files
   c. Open the hidden folder of `.git`
   d. Open the `config` file.
   e. Delete [remote "origin"] and the indented lines below until next bracketed entry.
   f. Save the config
   g. Go back to GitHub Desktop. Click "Publish repository"
   
![image](https://user-images.githubusercontent.com/75402236/209841031-bde7b343-c406-4667-bb4c-104f0cd78cb9.png)

Follow the dialog to publish your repository to GitHub.com.

Let me know if you run into any problems.

**Comment by souley16pd** [comment]
Woooow, I didn't expect an answer so quickly. Y'all are awesome. Kudos to you. I will try your suggestions when I get home. Thank s a bunch and happy holidays.
