### ISSUE TITLE
Custom .gitignore from dropdown menu 

### ISSUE THREAD

**Issue by kvten** [desktop/desktop#15835]
### The feature request

Allow user to add customized `.gitignore` files from "Git Ignore" dropdown menu in "Create a New Repository".

Currently possible with [command line option](https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files#configuring-ignored-files-for-all-repositories-on-your-computer) but not most beginner-friendly.

### Proposed solution

A folder inside the application for user to drag & drop their templates and/or allow user to add path.

**Comment by tidy-dev** [comment]
@kenf1 Thanks for the suggestion! We have a similar request (tho not in the Create Repo dialog) in https://github.com/desktop/desktop/issues/2197. I am going to close in favor of tracking feedback for this here. Additionally, we have an[ open PR working on adding git ignore templates](https://github.com/desktop/desktop/pull/14943) to the "Ignored Files" tab of the "Repository Settings".

**Comment by Zshandi** [comment]
@tidy-dev I just came across this in seeing if this was currently somehow possible. The issue you linked to (https://github.com/desktop/desktop/issues/2197) seems to me to be completely independent of the suggestion from @kenf1. It looks to me like that issue is for the ability to choose a _non-custom_ template from the "Repository Settings" if there is no .gitignore for the repository yet.

This suggestion, however, is for the ability to add _custom_ .gitignore templates from the regular template selection in the "Create a New Repository" menu. They are related in that they both involve .gitignore settings, but one can be implemented without the other, so I do not think this should have been closed in favor of that one, since there is not mention of a _custom_ .gitignore option in that other issue. Of course, having custom templates could also be applied to that new template selection location, but they are still independent.

I, for one, would definitely like to see some way to add a custom .gitignore template, and I think this should be re-opened.
