### ISSUE TITLE
Feature Request: Git console built right into the client.

### ISSUE THREAD

**Issue by rlabrecque** [desktop/desktop#1586]
Most git clients allow you to get to the command line pretty easily, it would be cool if we could have a command line built right in to the client too.

I think ideally this would expand down from the top quake 1 style, it would display all the git commands that have been run, and allow you to run your own git commands right in the application.

It would be nice to be able to run things like MenuIDs and MenuEvents from there too. Maybe with a leading '/' or something.

See also: #1570

**Comment by joshaber** [comment]
Thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I'm going to add the `future-proposal` label to this issue and close it out, so that we don't get overwhelmed with our backlog! We'll revisit these as part of our next planning session.

**Comment by billygriffin** [comment]
Thanks for the suggestion @rlabrecque! After discussing this internally and observing people using the app, we're not sure adding a shell inside Desktop will be that beneficial for most users. We have a keyboard shortcut to easily open in whatever shell you have configured, and we haven't heard that that's broadly causing problems for people to justify incorporating an integrated console. We're happy to re-evaluate if our current assumptions are off base and we learn more from users about how this would be most valuable. I'm going to remove `future-proposal` to reflect that we don't intend to support this in the near term. Thanks again!
