### ISSUE TITLE
Add an option to hide/disable pushing to a branch

### ISSUE THREAD

**Issue by PatrickDanino** [desktop/desktop#15909]
### The feature request

When you have one or more changes that have yet to be pushed, a button appears right next to the current branch tab that will automatically (and without confirmation) try to push your changes. If you are working on a production branch, this is potentially irreversible.

### Proposed solution

Either move this button somewhere else, add a confirmation dialog that you can disable and/or add an option to disable pushing changes at all.

**Comment by steveward** [comment]
Thanks for the issue. I'd recommend looking into using [protected branches,](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches), which will allow you to prevent accidental pushes to production branches. I hope that helps!

**Comment by ndunsworth** [comment]
Protected branches is not the solution when its more of an application UI/UX problem.  There are plenty of gotchas to your proposed solution which a person in authority of a repo might still be able to accidentally push.

You have buttons that are dual use which is terrible.  In part because said buttons, depending on state, can be a "_Create_" or "_Update_".

When I'm on a remote branch the button is "_Fetch_". When I'm on a local branch that does not exist on remote its "_Publish_".

This leads to a unwanted situation if you forget your on a local unpublished branch and mean to do a fetch because you thought you were on main.

It should absolutely confirm that you want to create on the remote or have the ability to set an option to.

And the same thing goes for the blue "Publish your branch" widget that appears in the right pane.  Its in the exact same spot that the rebase widget appears.

I don't want to see this widget ever when working on a local branch that does not exists on remote.  NEVER!.  And yet I'm constantly dancing around terrified of hitting the button in the toolbar or the pane.
