### ISSUE TITLE
GitHub Desktop encountered an error

### ISSUE THREAD

**Issue by wes-the-dev** [desktop/desktop#15973]
### The problem

Anytime I open it, it shows this error, and I can't close the application normally, I can only click Exit and Restart but it keeps bringing this up
TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:371:5)
    at onParseError (node:internal/url:552:9)
    at new URL (node:internal/url:628:5)
    at C:\Users\JOSC\AppData\Local\GitHubDesktop\app-3.1.4\webpack:\[name]\app\src\main-process\authenticated-avatar-filter.ts:34:46
    at Array.map (<anonymous>)
    at C:\Users\JOSC\AppData\Local\GitHubDesktop\app-3.1.4\webpack:\[name]\app\src\main-process\authenticated-avatar-filter.ts:34:16
    at C:\Users\JOSC\AppData\Local\GitHubDesktop\app-3.1.4\webpack:\[name]\app\src\main-process\main.ts:332:50
    at IpcMainImpl.<anonymous> (app\src\main-process\ipc-main.ts:64:12)
    at IpcMainImpl.emit (node:events:526:28)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:11014)

Version: 3.1.4
OS: Windows 10.0.19044
![error git](https://user-images.githubusercontent.com/39949076/213635931-75f6d412-3db4-483e-95aa-bce27d2a24d0.JPG)

### Release version

Version 3.1.4.

### Operating system

Windows 10.0.19044

### Steps to reproduce the behavior

1. I open the application and only this come up, i will attach the prompt that appears
![error git](https://user-images.githubusercontent.com/39949076/213635885-9b595775-ed3f-475a-907d-22ca3644bba1.JPG)

**Comment by steveward** [comment]
Thanks for the report @wes-the-dev. I haven't seen this specific 'Invalid URL' error before. Can you try resetting GitHub Desktop to see if that gets things working? It'd be helpful to know if this is possibly caused by a specific repository loading, since the error seems related to avatars.


Here's how to reset the application:

1. Close GitHub Desktop (you may need to use the Task Manger if you are unable to close the application directly)
2. Remove all of the files in `%APPDATA%\GitHub Desktop\`
3. Restart GitHub Desktop

You will need to log in and add your repositories again. Let me know if you are able to launch the app after resetting without issue.
