### ISSUE TITLE
Not solved but DEFINITELY closed

### ISSUE THREAD

**Issue by Zubrelin** [desktop/desktop#15979]
Welp! Guess that's all, folks. I attempted to delete this, since the question's been closed and nothing of value was lost or gained, with the advice given unfortunately not working... but I can't. So, uh, oops! I still appreciate the help, though. Kind of a bummer, too! I hoped it'd work.

I'll stop being dead and sporadic now, though. Everyone have a nice day! Nothing happened here! Forget this! Thank you!

**Comment by LouisGobert** [comment]
Hi, I have the same issue since GitHub Desktop 3.1 on Ubuntu. But no problem with GitHub Desktop on Windows

**Comment by steveward** [comment]
It looks like you need to get GitHub Desktop approved:

```
2023-01-21T08:02:58.247Z - error: [ui] Failed to look up repository clone info for 'https://github.com/Pre-Fortress-2/pf2beta.git'
Error: Although you appear to have the correct authorization credentials, the Pre-Fortress-2 organization has enabled OAuth App access restrictions, meaning that data access to third-parties is limited. For more information on these restrictions, including how to enable this app, visit https://docs.github.com/articles/restricting-access-to-your-organization-s-data/
```

You can [request approval](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-your-membership-in-organizations/requesting-organization-approval-for-oauth-apps) for GitHub Desktop. Since this is the Linux version, if you have any further issues I'd recommend looking at the [Linux fork](https://github.com/shiftkey/desktop/issues) for similar issues.
