### ISSUE TITLE
When changing branch name stashed changes cannot be popped/applied from inside github desktop

### ISSUE THREAD

**Issue by ADustyOldMuffin** [desktop/desktop#15977]
### The problem

If you have a stash on a branch and them rename the branch then all stashed changes will not be accessible from inside Github Desktop and you will have to pop/apply the stash by some other means.

### Release version

3.1.4

### Operating system

MacOS

### Steps to reproduce the behavior

1. Have active changes on a branch in Github Desktop
2. Stash these changes
3. Rename the branch you stashed the changes on
4. Observe no prompt saying you have stashed changes no longer being present, but in git you can view that there are stashed changes under the old branch name.

**Comment by ADustyOldMuffin** [comment]
Slightly related to https://github.com/desktop/desktop/issues/13156 as if you could view all stashes then this would not be an issue.

**Comment by steveward** [comment]
Thanks for the issue. If you rename a branch with a stash you will see a warning:

![](https://user-images.githubusercontent.com/721500/132693760-2a29d1d9-e025-4142-9133-f6730c334f18.png)

Since https://github.com/desktop/desktop/issues/13156 is open and a potential solution I'm going to close this issue out in favor of keeping our issue list consolidated.

**Comment by steveward** [comment]
Also see https://github.com/desktop/desktop/issues/7283 for a previous issue on this.
