### ISSUE TITLE
Unable to go on Github on Chrome/Unable to Clone Repository from GitHub Desktop

### ISSUE THREAD

**Issue by TDLAXD** [desktop/desktop#15994]
### The problem

Suddenly one day I couldn't get on GitHub on OperaGX nor Chrome. It just says Internet Connection problem but I've tried everything I can and It's still seem unresponsive. I tried the VPN feature provided by OperaGX and it worked. But it was so annoying to turn that on just to get on GitHub + GitHub Desktop does not work at all. Would appreciate any help I can get!

### Release version

Version 3.1.4

### Operating system

Windows 10

### Log files

[2023-01-23.desktop.production.log](https://github.com/desktop/desktop/files/10491327/2023-01-23.desktop.production.log)
[2023-01-24.desktop.production.log](https://github.com/desktop/desktop/files/10491329/2023-01-24.desktop.production.log)

**Comment by steveward** [comment]
@TDLAXD thanks for the report. This definitely looks like a network issue:

```
fatal: unable to access 'https://github.com/TDLAXD/world-template.git/': Could not resolve host: github.com
```

Since you're also having issues accessing GitHub in the browser it seems that something on your network is preventing you from accessing GitHub services. Are you behind a proxy or firewall that could be blocking access to GitHub?  You can go to https://github-debug.com/ to try and diagnose your connection issues. I'd recommend reaching out to [GitHub Support](https://support.github.com/) to assist you further.

Since this is not a specific issue with GitHub Desktop I'm going to close this out, but if you continue to have specific issues with GitHub Desktop after your network problems are resolved please let us know.
