### ISSUE TITLE
Cannot Clone Repositories Due To Certificate Warnings

### ISSUE THREAD

**Issue by Br1ghteyZ** [desktop/desktop#16014]
### The problem

Cannot Clone Repositories Due To Certificate Warnings

### Release version

3.1.3.0

### Operating system

Windows 10 21h2

### Steps to reproduce the behavior

Tried to clone a repository and a window pops up saying the certificate isn't valid despite installing EVERY certificate in the line of trust

**Comment by steveward** [comment]
Thanks for the report @Br1ghteyZ. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
