### ISSUE TITLE
Problem to push files to web

### ISSUE THREAD

**Issue by marcuscpimentel** [desktop/desktop#16037]
### The problem

Using Github Desktop, when I click in the push options to upload the files, nothing happens. 

### Release version

Version 3.1.5 (x64)

### Operating system

Windows 10

**Comment by steveward** [comment]
Thanks for the report @marcuscpimentel. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
