### ISSUE TITLE
Showing unexpected code "1" when I open github desktop

### ISSUE THREAD

**Issue by Yawan-1** [desktop/desktop#16036]
### The problem

Today, I open `Github Desktop`  and It showed error then the App froze and I had to go to the **Task Manager** to close the app and I tried opening the app again but it didn't open.

After few hours, I tried again and It is not even opening.

I can't really get the release version because the App is not even trying to open But I guess it is the latest version because It automatically updates every time I launched the app before.

### Release version

3.1.5

### Operating system

Windows 10

### Steps to reproduce the behavior

Error showed right When I open the desktop, and I have seen it two times. It is not starting again.

### Log files

Git returned an unexpected exit code "1" which should be handled by the caller (getStatus)

### Screenshots

![Github 1](https://user-images.githubusercontent.com/79757968/215484174-b7dab694-21e6-4d24-9876-df24a5d96522.png)

### Additional context

I also restarted my computer but github is still not opening. Should I reinstall `Github Desktop` app ?

**Comment by sergiou87** [comment]
Hey @Yawan-1 ! 👋  Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

If you want, you can also try to uninstall following these steps:

1. Quitting GitHub Desktop and restarting your machine to ensure no rogue processes are hanging about
1. Uninstalling GitHub Desktop
1. Deleting (or moving/renaming temporarily) the `C:\Users<YourUserName>\AppData\Roaming\GitHub Desktop` folder. This folder has all your GitHub Desktop settings and the list of repositories.
1. Downloading and installing GitHub Desktop again from https://desktop.github.com

**Comment by Yawan-1** [comment]
Hello @sergiou87, I wasn't able to open Github last time because It wasn't even opening so I couldn't find any logs without opening the `Github Desktop`. I tried restarting the computer but the problem was still the same (was not opening). Then I uninstalled the app and installed it again and Now The problem is gone(for now). There is no problem/error for now.

**Comment by sergiou87** [comment]
Glad to hear that! Thanks for reporting back ❤️
