### ISSUE TITLE
CMD + backspace behaviour changed

### ISSUE THREAD

**Issue by joeldrapper** [desktop/desktop#16048]
### The problem

Previously, CMD + backspace would discard changes to the selected files, now it remove the repo from the app.

### Release version

3.1.5

### Operating system

macOS

### Steps to reproduce the behavior

1. Make some changes
2. Select a file
3. Press CMD + backspace

**Comment by sergiou87** [comment]
Hello! Thanks for your report ❤️ 

Looking at https://github.com/desktop/desktop/blob/10e26b690f2a900e3ef69a468b8b2b0e9cdb3be4/app/src/main-process/menu/build-default-menu.ts#L371-L377
and also at https://github.com/desktop/desktop/blob/10e26b690f2a900e3ef69a468b8b2b0e9cdb3be4/app/src/main-process/menu/build-default-menu.ts#L294-L300

I think that's always been the behavior, at least for 2.5 years (see https://github.com/desktop/desktop/pull/7650). In order to discard changes, you should use CMD + Shift + Backspace

I hope that helps!

**Comment by joeldrapper** [comment]
Something definitely changed recently. Perhaps it was just backspace without CMD. CMD + SHIFT + Backspace discards all files, not just the selected files.

**Comment by sergiou87** [comment]
@joeldrapper hmmm I don't see anything in the code to suggest that 😕 Are you able to pinpoint this change of behavior to a specific date or version of Desktop?
