### ISSUE TITLE
The problem of circling Carton

### ISSUE THREAD

**Issue by limingzhuzhu** [desktop/desktop#16055]
After each operation, such as commit, pull and push, it will turn around and get stuck. You must restart the github desktop to work normally

**Comment by steveward** [comment]
Thanks for the report @limingzhuzhu. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
