### ISSUE TITLE
Personal access token not working in github enterprise

### ISSUE THREAD

**Issue by sanjanaDinith** [desktop/desktop#16061]
### The problem

i was using github desktop to connect to my workplace gitlab account and first time i was able to use personal access token to sign in. however today my personal access token expired and there is no way to add a new personal access token, i tried providing my username and PAT as my password, that brings auth error.
![Screenshot 2023-02-04 at 8 21 03 AM](https://user-images.githubusercontent.com/121815390/216742687-fc0887c9-8eef-4a70-b045-3bc1c1b3b0a2.png)

### Release version

Version 3.1.5 (arm64)

### Operating system

MacOs ventura 13.2

### Steps to reproduce the behavior

1. log in to gitlab using PAT.
*works for a while... until PAT expires.
2. Try to auth again with new PAT
3. Enter username
4. Enter PAT instead of password
*Auth failed.

**Comment by steveward** [comment]
@sanjanaDinith thanks for the issue. I would try opening Keychain Access and searching for `gitlab` to see if you find a `GitHub - gitlab.*` key. That should be the token that GitHub Desktop was using for your GitLab instance. Then try deleting it and authenticating again.

If that doesn't work please share the log file so that we can take a closer look.
