### ISSUE TITLE
Branch name's first letter changes to capitalised if small case

### ISSUE THREAD

**Issue by akshitrcrm** [desktop/desktop#16071]
### The problem

let's say I create a branch on GitHub web named "bug/security-fix"

When it fetch origin in Github Desktop, it shows me that branch as "Bug/security-fix"

If I push any change to this branch from GitHub Desktop, a new branch is created with the capitalised "B" and my changes are not pushed in the original branch I created from web app.

If I do a "git fetch and git checkout bug/security-fix" from terminal, then the desktop app asks to publish this branch and then it throws this error:

<img width="641" alt="Screenshot 2023-02-06 at 2 06 06 PM" src="https://user-images.githubusercontent.com/69840129/216923984-f784a2c0-ac08-412c-b687-72475412d6bd.png">

### Release version

Version 3.1.5 (arm64)

### Operating system

macOS Ventura 13.0.1 (22A400)

### Steps to reproduce the behavior

1. Create a branch on GitHub web named "bug/security-fix"
2. Fetch origin in Github Desktop

### Log files

[2023-02-06.desktop.production.log](https://github.com/desktop/desktop/files/10661124/2023-02-06.desktop.production.log)

### Screenshots

<img width="641" alt="Screenshot 2023-02-06 at 2 06 06 PM" src="https://user-images.githubusercontent.com/69840129/216924703-27503757-5112-4bb2-80fa-d910ed705acf.png">

**Comment by niik** [comment]
Hi @akshitrcrm, thanks for reaching out!

I believe what has happened here is that you've previously created a local branch that started with a capitalized `Bug/` and that's why new branches created on your machine starting with lowercase `bug/` automatically get converted to `Bug/`.

To understand why we need a little background on how Git stores branches. Inside of a repository there's a `.git/refs/heads` folder where (most, we'll get to that later) of your branches are stored in files named like the branch name. So if you have a branch called `main` there's likely a file called main at `.git/refs/heads/main` and the contents of that file will be the object id ("sha") of the commit that branch is pointing at.

Now, if you create a branch called `Feature/auth` Git will store that commit sha in a file called `auth` within a folder called `Feature`. So the full path to that branch will be `.git/refs/heads/Feature/auth`.

Default file systems on Windows and macOS are case insensitive yet case preserving. Meaning that if you ask macOS to write a file at `feature/auth` and there's already a folder called `Feature` it will happily write that file to `Feature/auth` without making a fuzz about it since they're considered equal. Note that this is not the case on case-sensitive file systems like Linux typically use. On a filesystem like EXT3 it's perfectly acceptable to have two files side by side which only differ by case. This leads to a whole slew of unintuitive problems when a repository is contributed to from users with different file system capabilities.

Back to your issue here. If the first branch using a `bug/` prefix you created locally (either manually or by checking it out from the remote) was capitalized then that will set the precedence for all branches created thereafter that starts with `bug/`.

You can solve this either by packing all your refs (https://git-scm.com/docs/git-pack-refs) which will move the branches from files in a directory hierarchy into a file with one branch per line. As you change the branch (commit to it) it will be moved out from the file and into the directory hierarchy again so what case you'll end up using will depend on the case of the first bug-prefixed branch you start working on.

Ideally you should try to avoid having branch names where components (parts separated by `/`) differ in case. It's an easy mistake to make but as you can see above the consequence are far from intuitive. Unfortunately I believe that in the case of GitHub Desktop not being able to understand that a branch you just checked out is already published that problem will exist if you try to use the command line interface of Git as well and since we rely on Git to tell us whether a branch has an associated remote tracking branch there's not much we can do to resolve this in-app.

I'm sorry I don't have better news for you but I hope I've provided a bit of insight into why this confusing behavior arises and what you can do to work around it.

**Comment by TalhaAbid1** [comment]
### I was having this issue as well, and it was driving me crazy. 
* I had something like feature/name but git branch -a showed me FEATURE/name Or May be Feature/name. Renaming the branch, deleting and recreating it, nothing worked. What finally fixed it:

> [!NOTE]  
> Go into `.git/refs/heads`

###  ✔️ You'll see a FEATURE folder. Rename it to feature
### ✔️ You'll see a Feature folder. Rename it to feature


> [!IMPORTANT]  
> If You Can't Find Your `.git` Folder
>GO TO Parent Directory And Check View Hidden Files
> There You Find You `.git` Folder

**Comment by bsuhagia** [comment]
@TalhaAbid1  This issue is driving me crazy. I checked my `.git/refs/heads` but it does not have FEATURE or Feature folder. It only contains a master file.

**Comment by rj-wowza** [comment]
I do not have any capitalized folders in `./git/refs/heads` but all of the branches are capitalized when pushed to github. For example, I just created `deploy-20240611` today, and the PR was captialized in Github. This causes problems with the `semantic-release` package, where it will ignore valid PRs that should generate release notes because the PR title is capitailzed (i.e. `Fix` instead of `fix`)

![Screenshot 2024-07-11 at 2 26 09 PM](https://github.com/user-attachments/assets/9e28eec0-ee88-4a6e-9a29-1b12a9be36c8)
![Screenshot 2024-07-11 at 2 24 34 PM](https://github.com/user-attachments/assets/7d5ee0d0-8c0e-4c71-beb5-f85110abb56b)

**Comment by rudraHHAX** [comment]
> I do not have any capitalized folders in ./git/refs/heads but all of the branches are capitalized when pushed to github. For example, I just created deploy-20240611 today, and the PR was captialized in Github. This causes problems with the semantic-release package, where it will ignore valid PRs that should generate release notes because the PR title is capitailzed (i.e. Fix instead of fix)

@rj-wowza did you find any resolution to your scenario ?

**Comment by zhead** [comment]
I might be late to the party but I was having this issue and found a solution.
My capitalization was being cause by the folder in git/refs/remotes/origin being written capitalized. renaming it there solved it for me (in my case I was seeing Feature instead of feature)

<img width="299" height="177" alt="Image" src="https://github.com/user-attachments/assets/621ec30f-63c9-4480-a394-5397cda65875" />

**Comment by scifisatan** [comment]
THANK YOU @TalhaAbid1

**Comment by sabirshah67uu** [comment]
sabirshah

**Comment by jfogi** [comment]
This is NOT FIXED. I still have this issue and there definitely was no local branch beforehand. Branches are always created on remote and pulled down, this is a bug in GHD.
