### ISSUE TITLE
GitHub desktop not honoring virtualenv pylint managed to poetry

### ISSUE THREAD

**Issue by rjalexa** [desktop/desktop#16087]
### The problem

GitHub desktop launches pre-commit hooks but fails with pylint not found.
Same pre-commit from command line works ok.
virtualenv managed with poetry and pylint installed only within the venv, not in the base environment (not desirable).
how to make gh desktop aware of the venv?

### Release version

3.1.5 arm64

### Operating system

Mac OS Ventura 13.1

### Steps to reproduce the behavior

Try committing

### Log files

[2023-02-02.desktop.production.log](https://github.com/desktop/desktop/files/10689832/2023-02-02.desktop.production.log)

**Comment by steveward** [comment]
Thanks for the report @rjalexa. Hooks will run inside of GitHub Desktop's environment which means they won't necessarily have access to the same environment variables as you'd normally have when using the command line. Does launching GitHub Desktop from the command line using the `github` command work? 

I'm going to close this out since we already have a number of issues tracking problems with hooks.

**Comment by rjalexa** [comment]
Hi there Steve. Installed the command line helper and launched "github" from within the "poetry shell" virtual environment, and as you suggested all seems ok now.
Very relieved or would had to transition to GitKraken with its learning curve.
Thanks !!!!

**Comment by steveward** [comment]
Glad to hear that worked!

**Comment by AdeelH** [comment]
GitKraken also runs into a similar problem and the solution is also the same: launch it from the command line from the correct environment.
