### ISSUE TITLE
Unable to find newly created branch on GitHub desktop

### ISSUE THREAD

**Issue by KumarAshish12** [desktop/desktop#16086]
### The problem

I created new branch on gitlab which is mapped with my GitHub destop. The branches newly created is not showing under current branch tab. Older branches are visible though.

### Release version

Version 2.9.6 (x64)

### Operating system

Win 10

### Steps to reproduce the behavior

Go to GitHub desktop
Click on current branch tab
<Unable to saw newly created branches>

**Comment by steveward** [comment]
@KumarAshish12 have you tried clicking `Fetch origin` to see if the branch shows up? 

If that doesn't work, could you upload the log file from GitHub Desktop so that I could get some more information about this? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
