### ISSUE TITLE
Pushing Results in "python: Permission denied"

### ISSUE THREAD

**Issue by mitchlotierzo-poliigon** [desktop/desktop#16101]
### The problem

When I try to push commits to the repo's origin, I get a `env: python: Permission denied` error. I'm able to simply do a `git push` from the CLI, but it's not as convenient. The repo in question is setul up using a SSH address and ai have my SSH keys set correctly, if that is any help.

### Release version

3.1.6

### Operating system

macOS Monterey (12.6.3)

### Steps to reproduce the behavior

1. Commit some changes to the branch.
2. Attempt to push those changes via app.
3. Check logs for error output.

**Comment by steveward** [comment]
Thanks for the report @mitchlotierzo-poliigon. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
