### ISSUE TITLE
Cannot commit on public repo - unborn HEAD

### ISSUE THREAD

**Issue by Jasonlee1995** [desktop/desktop#16141]
I don't have left spaces on my local laptop, so I use google drive and used it to commit and push.
(and it works well still yesterday)

But I found that I cannot do commit like below.

<img width="700" alt="image" src="https://user-images.githubusercontent.com/49643709/219023163-9e04b661-ea42-4acf-bdea-a70b324dba52.png">
<img width="400" alt="image" src="https://user-images.githubusercontent.com/49643709/219023255-b3747115-6f06-4fac-86d9-f37f5e9b42e1.png">

I googled and find the issues on [stackoverflow](https://stackoverflow.com/questions/66449211/a-lock-file-already-exists-in-the-repository-which-blocks-this-operation-from-c) and do the same thing as they recommended, but it didn't worked to me.

I also checked my log file and I think potential cause may be the logs below so searched `fatal: mmap failed: Operation timed out` or `fatal: fetch-pack: invalid index-pack output` but cannot find the same issues like me.

```
Receiving objects:   0% (1/149)
Receiving objects:   1% (2/149)
fatal: mmap failed: Operation timed out
fatal: fetch-pack: invalid index-pack output
```

[2023-02-15.desktop.production.log](https://github.com/desktop/desktop/files/10742598/2023-02-15.desktop.production.log)

Any recommendations for solving this issue?

I used the same settings since 2022 but this thing never happened and also yesterday so find it weird.

**Comment by steveward** [comment]
@Jasonlee1995 thanks for the issue. We recommend not storing Git repositories in file syncing services, since it can potentially cause issues like this. In this case it looks like you may need to delete a lock file:

`fatal: cannot lock ref 'HEAD': Unable to create '/Users/jason/Library/CloudStorage/GoogleDrive-blaklj1995@gmail.com/내 드라이브/LeetCode_Python/.git/refs/heads/main.lock`

Deleting that `main.lock` file should resolve that specific issue.

The `mmap` error means your system is running out of memory. I've seen reports of this happening with OneDrive. I would try turning off Google Drive's syncing to resolve this. I hope that helps!
