### ISSUE TITLE
Undo for discard changes

### ISSUE THREAD

**Issue by anthumchris** [desktop/desktop#16143]
### The feature request

We can currently right-click changed file lines and click "Discard changes". Could we add an undo feature for this?

### Proposed solution

After confirming "Discard changes" for certain lines in a file, we have no way to instantly undo the history of "discard changes" we made on the file. This forces us to leave GitHub Desktop and re-enter the lines or undo the changes from the editor if we are lucky enough to have the file open at the time of "Discard changes" in GitHub Desktop

**Comment by steveward** [comment]
@AnthumChris thanks for the issue. GitHub Desktop shows a prompt with a warning and explicitly mentions that the changes are recoverable from the Recycle Bin/Trash on your machine. Since discarded changes have not been committed/staged we are unable to provide an easier "undo" feature. I'm going to close this out since this isn't something we'll be able to implement at this time.

**Comment by bryan1anderson** [comment]
@steveward what about when you discard a specific line in a specific file?
