### ISSUE TITLE
latest version is toooo slow

### ISSUE THREAD

**Issue by lagrandebarriere** [desktop/desktop#16158]
### The problem

the latest version of github desktop is extremely slow and freezes my computer !

### Release version

3.1.7

### Operating system

windows 10 education

**Comment by xnousnow** [comment]
Does the computer freeze even when you open it and do nothing else? Also, your computer can be old so It freezes.

**Comment by lagrandebarriere** [comment]
I had no problem before the update, mandatory ? why by the way,
I wanted to keep the previous version.
I have a 16GB i7.6700,
it's clearly the new version that is in question.
I can no longer write normally in the "editbox",
it's very slow ... it works but very very slowly, one letter per second...
Should I install or update external tools that github depends on?

**Comment by steveward** [comment]
@lagrandebarriere thanks for the issue. Are you seeing high CPU usage when GitHub Desktop slows down? It'd be helpful if you could open Task Manager to take a look and see if GitHub Desktop has high-CPU usage when this happens. It'd also be helpful if you could upload a log file to this issue so that we can see if Git operations are taking longer than usual to complete.

To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`. The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by lagrandebarriere** [comment]
I found the culprit of all these slowdowns, it's my vpn, I deactivate it
and git works normally again. Now I don't know why it happened at the same
time as the new version of GitHub Desktop. Thanks for your help anyway.

Le mar. 21 févr. 2023 à 20:00, Steve Ward ***@***.***> a
écrit :
