### ISSUE TITLE
The remote disconnected. Check your Internet connection and try again.

### ISSUE THREAD

**Issue by tormyvancool** [desktop/desktop#16169]
### The problem

Each time I try to upload something, after a while I get: 
The remote disconnected. Check your Internet connection and try again.

The solution is to manually upload the files.

### Release version

Version 3.1.7 (x64)

### Operating system

Windows 11 Pro 64biys

### Steps to reproduce the behavior

1. Publish branch
2. 2.after a while I get this issue

### Log files

[2023-02-19.desktop.production.log](https://github.com/desktop/desktop/files/10776479/2023-02-19.desktop.production.log)

### Screenshots

![image](https://user-images.githubusercontent.com/32305535/219938707-49904d55-fc63-4d8a-9b30-f72e504eee66.png)

**Comment by bsureshkrishna** [comment]
Same here.. very small repository (39MB). I just cloned a new repository and now things work.

**Comment by steveward** [comment]
@tormyvancool thanks for the issue. Unfortunately it looks like the operation was timing out due to the size of the repository:

```
Writing objects: 100% (146/146), 2.23 GiB | 2.28 MiB/s, done.
Total 146 (delta 16), reused 0 (delta 0), pack-reused 0
fatal: the remote end hung up unexpectedly
Everything up-to-date
```

Your repository is over 2GB, and GitHub generally recommends trying to keep things under 1GB for optimal performance. I'm going to close this out since you were able to resolve the issue.
