### ISSUE TITLE
[Bug] The whole ui/window lost in the latest version 3.1.9-beta1 on MacOS

### ISSUE THREAD

**Issue by darkduckgo** [desktop/desktop#16188]
### The problem

as the title says, the whole ui/window lost in the latest version 3.1.9-beta1 on MacOS..

and due to it doesn't alert any windows, I can't take a screenshot easily

### Release version

3.1.9-beta1

### Operating system

MacOS 10.15.7

### Steps to reproduce the behavior

1. use the previous beta version
2. upgrade to the latest one (click the `update` button in the UI) and the app will exit & restart
3. now we will lost the whole UI window & feels like ummmmm 😢

### Additional context

It is highly recommended that we have a way to **roll back to the previous version**. (doesn't means reinstall the app and re-config all the settings/repo), the critical bug has too much impact on usage in dev

**Update:** 
reinstall the `stable` version (3.1.8) from the website could fix this problem & keep the most of the local settings, thanks @splorp

**Comment by splorp** [comment]
Whoops. I just opened a similar issue for macOS High Sierra.

#16189

**Comment by darkduckgo** [comment]
> Whoops. I just opened a similar issue for macOS High Sierra.
> 
> #16189

Jesus, wonder how could u revert to the previous version?

**Comment by splorp** [comment]
> wonder how could u revert to the previous version?

I downloaded the current non-beta release.

https://desktop.github.com/

**Comment by attheshow** [comment]
Downloading the non-beta version worked for me too.

**Comment by niik** [comment]
Thank you all for letting us know about this! Turns out the beta release was missing #16151 which fixed a crash that didn't manifest itself in development builds. We've pulled the bad release from the beta channel and will be releasing [3.1.9-beta2 soon](https://github.com/desktop/desktop/pull/16194) to replace it.

In the meantime you can manually download the last stable release using the links in the README (pasted below for convenience) and replace your existing app with it.

 - [macOS](https://central.github.com/deployments/desktop/desktop/latest/darwin?env=beta)
 - [macOS (Apple silicon)](https://central.github.com/deployments/desktop/desktop/latest/darwin-arm64?env=beta)
 - [Windows](https://central.github.com/deployments/desktop/desktop/latest/win32?env=beta)
 - [Windows (ARM64)](https://central.github.com/deployments/desktop/desktop/latest/win32-arm64?env=beta)

Gonna merge this into https://github.com/desktop/desktop/issues/16191
