### ISSUE TITLE
Certificate error for *.github.com

### ISSUE THREAD

**Issue by KadeerAmin** [desktop/desktop#16187]
### The problem

When I try to take any action in github desktop I get the following error:

<img width="1072" alt="image" src="https://user-images.githubusercontent.com/21316846/220402275-c9dd640a-0e1e-4b4b-a8d6-3b0ef6358229.png">

I only use github hosted private repositories so this seems to be a bug to me that github desktop does not trust github's API certificate.

### Release version

3.1.8

### Operating system

MacOS 11.7.3

### Steps to reproduce the behavior

Open github desktop
Click fetch origin

**Comment by justinpenner** [comment]
I just started seeing the same error this morning. Running GitHub Desktop 3.1.7 (x64) on macOS 12.6.3.

When I click "Show Certificate" everything seems fine. The certificate is not expired, and in fact was renewed last week.
![image](https://user-images.githubusercontent.com/46039243/220411209-904c4e26-8257-4c2e-a25a-982a67c608a0.png)

My only hunch is that something weird is happening with the certificate dates? Aren't SSL certificates normally good for 1 year? This one seems to be for 13 months.
![image](https://user-images.githubusercontent.com/46039243/220412130-a6f47845-3c5c-4094-9f33-9ed59b86d51f.png)
Maybe Desktop is checking that the certificate is within a range of the expiry date minus 12 months, and we're outside of that range right now since it's Feb 21?

**Comment by steveward** [comment]
@KadeerAmin @justinpenner I'm not seeing any issues with this, but we have had sporadic reports of this in https://github.com/desktop/desktop/issues/7925. Are either of you behind a proxy/firewall or using a VPN?

**Comment by KadeerAmin** [comment]
I am working behind a firewall. I have attempted to trust github's certificate to stop the error from popping but it continues to do so despite the cert being trusted. Here are logs if that helps.

<img width="1072" alt="image" src="https://user-images.githubusercontent.com/21316846/220770675-9c7a3110-a6f2-42b9-be93-2601bebe922e.png">

[2023-02-22.desktop.production.log](https://github.com/desktop/desktop/files/10808706/2023-02-22.desktop.production.log)

**Comment by steveward** [comment]
@KadeerAmin I assume your system clock is set correctly? Are you seeing SSL issues anywhere else?

Can you run `openssl s_client -connect api.github.com:443` from the Terminal?

**Comment by justinpenner** [comment]
@steveward I'm not behind a proxy or VPN. Nothing special as far as a firewall – just a router from my ISP that hasn't been touched in a long time. My system clock is correct and synced to time.apple.com.

One thing that could be relevant is that I upgraded from Catalina to Monterey a few days ago, before this started happening.

I pasted the openssl command you suggested and it seems to have run successfully without any errors or mention of a certificate issue. Here's the log (I've removed anything that looks like it might be a private code or key):
```
CONNECTED(00000005)
depth=2 C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert Global Root CA
verify return:1
depth=1 C = US, O = DigiCert Inc, CN = DigiCert TLS Hybrid ECC SHA384 2020 CA1
verify return:1
depth=0 C = US, ST = California, L = San Francisco, O = "GitHub, Inc.", CN = *.github.com
verify return:1
---
Certificate chain
 0 s:/C=US/ST=California/L=San Francisco/O=GitHub, Inc./CN=*.github.com
   i:/C=US/O=DigiCert Inc/CN=DigiCert TLS Hybrid ECC SHA384 2020 CA1
 1 s:/C=US/O=DigiCert Inc/CN=DigiCert TLS Hybrid ECC SHA384 2020 CA1
   i:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Global Root CA
---
Server certificate
-----BEGIN CERTIFICATE-----
[REDACTED]
-----END CERTIFICATE-----
subject=/C=US/ST=California/L=San Francisco/O=GitHub, Inc./CN=*.github.com
issuer=/C=US/O=DigiCert Inc/CN=DigiCert TLS Hybrid ECC SHA384 2020 CA1
---
No client certificate CA names sent
Server Temp Key: [REDACTED], 253 bits
---
SSL handshake has read 2699 bytes and written 289 bytes
---
New, TLSv1/SSLv3, Cipher is [REDACTED]
Server public key is 256 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : [REDACTED]
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: [REDACTED]
    Start Time: 1677171001
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
---
closed
```

**Comment by justinpenner** [comment]
Looking at this again today, I have a bunch more information that might help to narrow down the problem.

I thought maybe I could dig around in Keychain Access for some clues about the certificate issue, but the only github-related entry I could find was the application password entry for GitHub Desktop:
![image](https://user-images.githubusercontent.com/46039243/221433275-67f7f12b-9c5d-45d8-ba2f-c29b889c4671.png)
I deleted this entry, which logged me out of the GitHub Desktop app, and the certificate error stopped popping up. Now, if I try to log in again, the certificate error pops up immediately.
![image](https://user-images.githubusercontent.com/46039243/221433425-2f03aee1-81e4-456d-98b7-bc9c55340613.png)
After I cancel the error message, I am not logged in.
![image](https://user-images.githubusercontent.com/46039243/221433457-57871f65-5061-4912-ae44-f696672454e2.png)
But now at least I'm able to perform actions that don't require auth, including fetch origin, without triggering any certificate errors.

I also noticed that github.com works fine in Chrome (my default browser) but it does not open in Safari at all:
![image](https://user-images.githubusercontent.com/46039243/221433056-31ecb3f6-8526-414e-bac3-f4fe01b3c31d.png)
I also get the same message for api.github.com. I do not have any proxies set up, and proxy settings anyway seem to be at the system level on macOS (if you open proxy settings from Chrome and Safari preferences, they both take you to System Preferences>Network>Advanced>Proxies). Chrome is set to the default DNS settings, and Safari doesn't have DNS settings anyway, so I think they should be using the same DNS servers. Then I tried running `curl https://github.com` in Terminal, which works fine and retrieves the HTML content of the Github homepage, which was puzzling since I figured curl might have the same problem as Safari, assuming the network settings are the same.

Is any of that helpful?

**Comment by sergiou87** [comment]
> I also noticed that github.com works fine in Chrome (my default browser) but it does not open in Safari at all

That is surprising 🤯 But at least it means it's not a problem with Desktop specifically.

Is github.com the only web getting you those certificate issues in Safari? Have you checked Safari's / Desktop's Development tools (Network tab) to see if there is anything relevant in the requests that are failing?

Maybe it's worth comparing requests to github.com from Safari and Desktop vs the same request from Chrome 🤔

**Comment by KadeerAmin** [comment]
Just wanted to echo from my side the command you requested that I run
```
CONNECTED(00000005)
depth=2 C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert Global Root CA
verify return:1
depth=1 C = US, O = DigiCert Inc, CN = DigiCert TLS Hybrid ECC SHA384 2020 CA1
verify return:1
depth=0 C = US, ST = California, L = San Francisco, O = "GitHub, Inc.", CN = *.github.com
verify return:1
---
Certificate chain
 0 s:/C=US/ST=California/L=San Francisco/O=GitHub, Inc./CN=*.github.com
   i:/C=US/O=DigiCert Inc/CN=DigiCert TLS Hybrid ECC SHA384 2020 CA1
 1 s:/C=US/O=DigiCert Inc/CN=DigiCert TLS Hybrid ECC SHA384 2020 CA1
   i:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Global Root CA
---
Server certificate
-----BEGIN CERTIFICATE-----
[REDACTED]
-----END CERTIFICATE-----
subject=/C=US/ST=California/L=San Francisco/O=GitHub, Inc./CN=*.github.com
issuer=/C=US/O=DigiCert Inc/CN=DigiCert TLS Hybrid ECC SHA384 2020 CA1
---
No client certificate CA names sent
Server Temp Key: [REDACTED]
---
SSL handshake has read 2699 bytes and written 289 bytes
---
New, TLSv1/SSLv3, Cipher is [REDACTED]
Server public key is 256 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : [REDACTED]
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: [REDACTED]
    Start Time: 1677686917
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
---
closed
```

**Comment by KadeerAmin** [comment]
Wanted to add a quick video of the developer tools console output. Note that most fetches are failing with the following error: `Failed to load resource: net::ERR_CERT_AUTHORITY_INVALID`

https://user-images.githubusercontent.com/21316846/222199531-af2599ac-300e-4880-b648-a3a532bdbf05.mov

**Comment by justinpenner** [comment]
> Is github.com the only web getting you those certificate issues in Safari?

Yes, github.com is the only website that isn't working for me on Safari. I don't use Safari much, but I've been trying to switch over to Safari from Chrome. Being unable to access github.com has put that on hold for now.

> Have you checked Safari's / Desktop's Development tools (Network tab) to see if there is anything relevant in the requests that are failing?

I can't get Safari's devtools to show anything except the local requests for the error page itself, even if I tick "Preserve log" and refresh a couple times:

![image](https://user-images.githubusercontent.com/46039243/222223076-bd469baa-ba64-4b01-a9fb-bb46977b6d9d.png)

Here's Desktop's devtools after I try to sign in. Network tab is showing the same error code `ERR_CERT_AUTHORITY_INVALID` mentioned by @KadeerAmin.

![image](https://user-images.githubusercontent.com/46039243/222225978-179eb898-1c99-48d6-b8a8-688149d009a6.png)

**Comment by ongaq** [comment]
I had the exact same symptoms, but restarting my macOS fixed it!

**Comment by justinpenner** [comment]
> I had the exact same symptoms, but restarting my macOS fixed it!

OMG, can someone mark this as solved while I slink away in embarrassment? I never really think about restarting my Mac because it almost never needs to be done. It's not like Windows machines that need a reboot every day or so – I sometimes realize it's been weeks or months since I've rebooted my Mac.

So I'm logged into GitHub Desktop now and there's no sign of any certificate errors. @KadeerAmin I hope this works for you too!

**Comment by sergiou87** [comment]
No worries! I'm happy that worked 😄  Thanks for letting us know 🙇‍♂️
