### ISSUE TITLE
Windows do not appear in macOS High Sierra

### ISSUE THREAD

**Issue by splorp** [desktop/desktop#16189]
### The problem

Updated GitHub Desktop to the 3.1.9-beta1 on my two machines running macOS High Sierra and windows no longer appear after launching the application.

This includes the main application window, as well as the Preferences, About, New Repository, &c.

None of these windows appear when their respective menu items are selected.

Reverting to Desktop 3.1.8 fixes the issue.

### Release version

3.1.9-beta1 

### Operating system

macOS 10.13.6 High Sierra

### Steps to reproduce the behavior

1. Update Desktop to 3.1.9-beta1 
2. Launch application
3. Note that the main window does not appear
4. Select “Preferences…” or “About GitHub Desktop” from the “GitHub Desktop” menu
5. Note that neither window appears

**Comment by attheshow** [comment]
Same issue here. Same version.

**Comment by rstmsn** [comment]
Same here. MacOS 10.13.6, GitHub Desktop 3.1.9-beta1

**Comment by niik** [comment]
Thank you all for letting us know about this! Turns out the beta release was missing #16151 which fixed a crash that didn't manifest itself in development builds. We've pulled the bad release from the beta channel and will be releasing [3.1.9-beta2 soon](https://github.com/desktop/desktop/pull/16194) to replace it.

In the meantime you can manually download the last stable release using the links in the README (pasted below for convenience) and replace your existing app with it.

 - [macOS](https://central.github.com/deployments/desktop/desktop/latest/darwin?env=beta)
 - [macOS (Apple silicon)](https://central.github.com/deployments/desktop/desktop/latest/darwin-arm64?env=beta)
 - [Windows](https://central.github.com/deployments/desktop/desktop/latest/win32?env=beta)
 - [Windows (ARM64)](https://central.github.com/deployments/desktop/desktop/latest/win32-arm64?env=beta)

**Comment by niik** [comment]
We've just shipped [3.1.9-beta2](https://github.com/desktop/desktop/pull/16194) which fixes this issue. You can download it from the links posted in my previous comment. Thank you for your patience as we worked to resolve this and our apologies for the friction it caused! We appreciate your help testing out our beta releases ❤️

**Comment by attheshow** [comment]
Thanks so much for the quick fix! Downloading the latest beta now! 😊🏅

**Comment by splorp** [comment]
Thanks, @niik … appreciate the speedy fix.

I can confirm that 3.19-beta2 works as expected under macOS High Sierra.
