### ISSUE TITLE
Github Desktop Beta macOS Beta not opening since last update

### ISSUE THREAD

**Issue by DanielOberlechner** [desktop/desktop#16191]
### The problem

Github Desktop Beta macOS Ventura Beta not opening since last update.
I've updated the program to the newest version and since then its not opening.

Top context menu Github Desktop, File, Edit is showing up, program has a dot in the task bar but no visible windows.

### Release version

Newest Release can't tell which version exactly

### Operating system

macOS Ventura 13.3 Beta

### Steps to reproduce the behavior

Open program -> no visible window

### Screenshots

<img width="1728" alt="Bildschirmfoto 2023-02-21 um 19 29 52" src="https://user-images.githubusercontent.com/10922763/220429528-eb25684e-7b20-43f8-861c-ca885f90e1bd.png">

### Additional context

If more information is needed, just hit me up here on Github :)

**Comment by splorp** [comment]
> Newest Release can't tell which version exactly

Locate the application in the Finder, select “Get Info” from the “File” menu. The version number will appear in the “General” section of the “Info” window.

**Comment by attheshow** [comment]
Same issue here. Version is 3.9.1-beta1.

**Comment by rstmsn** [comment]
Same issue here. Using MacOS 10.13.6. GitHub Desktop version 3.1.9-beta1

**Comment by niik** [comment]
Thank you all for letting us know about this! Turns out the beta release was missing #16151 which fixed a crash that didn't manifest itself in development builds. We've pulled the bad release from the beta channel and will be releasing [3.1.9-beta2 soon](https://github.com/desktop/desktop/pull/16194) to replace it.

In the meantime you can manually download the last stable release using the links in the README (pasted below for convenience) and replace your existing app with it.

 - [macOS](https://central.github.com/deployments/desktop/desktop/latest/darwin?env=beta)
 - [macOS (Apple silicon)](https://central.github.com/deployments/desktop/desktop/latest/darwin-arm64?env=beta)
 - [Windows](https://central.github.com/deployments/desktop/desktop/latest/win32?env=beta)
 - [Windows (ARM64)](https://central.github.com/deployments/desktop/desktop/latest/win32-arm64?env=beta)

**Comment by niik** [comment]
We've just shipped [3.1.9-beta2](https://github.com/desktop/desktop/pull/16194) which fixes this issue. You can download it from the links posted in my previous comment. Thank you for your patience as we worked to resolve this and our apologies for the friction it caused! We appreciate your help testing out our beta releases ❤️
