### ISSUE TITLE
Show organisation name if multiple repos with same name

### ISSUE THREAD

**Issue by sqeezelemon** [desktop/desktop#16198]
### The feature request

Currently, if I have repositories with the same name in multiple organisations, I would only see the repo name in the Current Repository area and would need to open the repository selection to check the organisation to fully identify the repo.

### Proposed solution

If the app detects that there are multiple repositories with the same name, it should also show the organisation name in the Current Repository area.

### Additional context

Let's say there are 3 repos in the app:
* `org1/repo`
* `org2/repo`
* `org1/other`

If I select `org1/repo` or `org2/repo`, the app would show the full repo name (i.e. `org1/repo` or `org2/repo`) instead of showing just the name (`repo`) like it does now. If, however, I select the repo with a unique name (`org1/other`), it would only show the name (`other`).

**Comment by tidy-dev** [comment]
@sqeezelemon The expected behavior of the repository list is to group the repositories by owner which would be in your use case the organization. This is what I am seeing; thus, I unable to reproduce your issue. 

Here you can see. I have desktop/desktop and tidy-dev/desktop
![image](https://user-images.githubusercontent.com/75402236/220970916-a1381869-bf68-48c3-a0d2-e664d04d4879.png)

And for the case where you actually do have two copies of the exact same repository like desktop/desktop and desktop/desktop. You can right click to invoke the context menu and "Create Alias" to differentiate any repo you want to describe different than it's name.
