### ISSUE TITLE
error: unable to unlink old 'RIDDER2D/Saved/Logs/RIDDER2D.log': Invalid argument

### ISSUE THREAD

**Issue by Spi0nDK** [desktop/desktop#16196]
### The problem

Whenever I press the "Pull origin" after my friend sent me something from Unreal Engine it gives me this error: "error: unable to unlink old 'RIDDER2D/Saved/Logs/RIDDER2D.log': Invalid argument" and I have no clue how to fix it. I also get this error: "warning: Cannot merge binary files: RIDDER2D/Intermediate/CachedAssetRegistry.bin (HEAD vs. 44160b843d06ae0165334e130bce26e9937595b7)"

### Release version

Version 3.0.7

### Operating system

Windows 10

### Screenshots

![Udklip](https://user-images.githubusercontent.com/73273853/220644348-1684fd52-2297-4a99-b4fd-7c5e55905a2d.PNG)

**Comment by steveward** [comment]
@Spi0nDK it looks like you're trying to merge binary files that differ. You should be able to resolve that error by using the following commands:

To use your file:
`git checkout --ours -- path/to/file.bin`

To use the file from the remote:
`git checkout --theirs -- path/to/file.bin`

For the "unable to unlink old' -- is that file possibly open in another application? It looks like another process is potentially locking the file.

I'm going to close this out since issue is not related to GitHub Desktop. I would recommend reaching out directly to [GitHub Support](https://support.github.com/) for assistance if you are unable to resolve this.
