### ISSUE TITLE
GitHub Desktop does not open when WSL cannot be accessed

### ISSUE THREAD

**Issue by wrrnlim** [desktop/desktop#16235]
### The problem

Occasionally, WSL does not launch (see microsoft/WSL#5836). If a repository on the WSL filesystem was the previously opened one in Desktop, Desktop would also be unable to launch. This makes it so I have to fix the issue with WSL before I can access any repository on Desktop, even for repositories on the Windows filesystem.

### Release version

3.1.8

### Operating system

Windows 10

**Comment by sergiou87** [comment]
@wrrnlim  Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

Thank you!
