### ISSUE TITLE
Adding Pulsar as a supported editor

### ISSUE THREAD

**Issue by mdibella-dev** [desktop/desktop#16231]
### The feature request

Hello,

Since the discontinuation of the code editor [Atom](https://github.blog/2022-06-08-sunsetting-atom/), the community has been working with full zeal on its successor [Pulsar](https://github.com/pulsar-edit). In the meantime, the work has left the beta stage and version 1.0 has been released.

It would be nice if the desktop team could consider adding Pulsar to the options for external editors.

Thanks

### Proposed solution

A PR to make Pulsar available for macOS platforms via GitHub Desktop has already been released. (https://github.com/desktop/desktop/pull/16220)

### Additional context

N/A

**Comment by jessedmatlock** [comment]
+1

**Comment by BenoitPoulet** [comment]
Not only for MacOS, for every OS please.

**Comment by mdibella-dev** [comment]
The PR #16220 **is now merged,** thx to @tidy-dev

If I gain access to other systems (Linux, Windows), I will gladly take care of the implementation of an appropriate integration.

Of course, others are also invited to suggest an appropriate solution.

**Comment by peterkaminski** [comment]
No action necessary, this is an informational comment.

The Pulsar integration wasn't working for me; Pulsar did not show up in Desktop as an editor choice, even though I had Pulsar installed.

The problem turned out to be that I had an early version of Pulsar (1.100), and the bundle identifier was "Electron".

The fix was to install the newest version of Pulsar (1.104) and to restart Desktop. Pulsar now shows up as an editor choice.

To check a bundle identifier, you can use this command:

```shell
codesign -dv /Applications/Pulsar.app
```

Read the "Identifier=" line.

**Comment by steveward** [comment]
GitHub Desktop now provides support for [adding custom editors](https://docs.github.com/en/desktop/configuring-and-customizing-github-desktop/configuring-a-default-editor-in-github-desktop?platform=windows#configuring-a-custom-editor), so you can add Pulsar by following the steps in that linked help article. I'm going to close this out.
