### ISSUE TITLE
Support for OAuth flow

### ISSUE THREAD

**Issue by bbodenmiller** [desktop/desktop#16248]
### The feature request

When user has configured OAuth flow (browser) as detailed at https://github.com/GitCredentialManager/git-credential-manager/blob/main/docs/gitlab.md GitHub Desktop should use that for auth

### Proposed solution

Users will be able to use without username and password

**Comment by niik** [comment]
Hey @bbodenmiller, I'm afraid GitHub Desktop doesn't ship with, or use the GitCredentialManager so that's not something we can support at this time. Please see our guide for authenticating against GitLab remotes here: https://github.com/desktop/desktop/blob/development/docs/integrations/gitlab.md

**Comment by bbodenmiller** [comment]
@niik last I checked it also doesn't ship with git. When a git credential manager is installed & configured why not respect it?

**Comment by niik** [comment]
> @niik last I checked it also doesn't ship with git. When a git credential manager is installed & configured why not respect it?

GitHub Desktop ships with a custom built minimal Git environment. We don't use the globally configured Git Credential Helper in part because we don't have any control over how it prompts for credentials (i.e. does it require an interactive terminal or will it present a UI?) but mostly because when we designed our auth infrastructure the state of credential helpers was quite different than it is today. We don't have anything conceptually against leveraging external tools other than the cost of implementing and maintaining such a solution is far from free
