### ISSUE TITLE
Local branch still tracking branch that was deleted on remote

### ISSUE THREAD

**Issue by dedad1** [desktop/desktop#16246]
### The problem

When I try to rename a branch that has been published but subsequently deleted I get a warning saying that "This branch is still tracking origin/Ver1.0.0 and renaming this branch will not change the branch name on the remote".  After I rename the branch and publish it it shows up with the old name on remote.

The reason this is a problem is because my companies new policies require us to have new branch with a ticket number and version number in the name every time we push an update. And my companies anivirus makes Github Desktop unbearably slow so renaming a branch is much faster than deleting the old local branch, creating a new local branch, and taking the changes with it to the new branch.

### Release version

Version 3.2.0

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Create a new branch
2. Publish the new branch
3. Delete the branch on remote
4. Rename the branch
5. Publish the renamed branch

### Screenshots

![image](https://user-images.githubusercontent.com/31525872/222809228-82523557-53f3-44c7-8d79-22e4f4e68d8b.png)

**Comment by steveward** [comment]
@dedad1 thanks for the issue. The tracking info isn't changing since the local branch still exists. The rename doesn't change the remote tracking branch name. You can workaround this by running `git push origin -u <new_branch_name>`, or by using `git branch --unset-upstream` and then publishing again from GitHub Desktop. 

Since this type of workflow isn't common I'm going to close this out, but if you want to share anything further related to the performance issues you mentioned you can do so in https://github.com/desktop/desktop/issues/14950.

**Comment by dedad1** [comment]
Hi @steveward, thanks for the quick reply, unfortunately git bash refuses to work with my account, I think it's because my saml got messed up because I was laid off and rehired. Is the remote tracking branch name saved in an editable file?

**Comment by ojwoodford** [comment]
@steveward I've run into this problem more than once after renaming branches.

@dedad1  Did you try `git branch --unset-upstream` in the command line? This only operates locally, so shouldn't require credentials to your remote account. It worked for me.

**Comment by kbazzani** [comment]
@steveward I just ran into this problem as well.  I'd say its a fairly common workflow were one would expect to be able to rename a branch (that was deleted on GitHub.com) and publish it with the new branch name.
