### ISSUE TITLE
Default branch is stuck on a detached HEAD

### ISSUE THREAD

**Issue by Steph-Pelletier** [desktop/desktop#16244]
### The problem

My GH Desktop client has gotten into a weird state where the default branch is a detached HEAD. The default branch has been set to heads/main when it should be main, and when I select heads/main it says I'm on a detached HEAD. When running git status the output is HEAD detached at refs/heads/main.
Using git through the CLI I can checkout the main branch, but in GH Desktop I cannot see the main branch under my list of branches unless I specifically check it out in the command line.

I've tried uninstalling and reinstalling the client, signing in and signing out, deleting the repo from the client then re-adding it, and setting the global git config default branch. Nothing has worked so far.

'Important: This is exactly same issue has #13193, marked as solved, but no solution is described in the ticket

Thanks,
Stephane

### Release version

3.1.7

### Operating system

Windows 10

### Steps to reproduce the behavior

Unknown

### Additional context

This is exactly same issue has #13193, marked as solved, but no solution is described in the ticket

**Comment by steveward** [comment]
@Steph-Pelletier thanks for the report. 

Can you share the output of the following commands?
`git branch -a`
`git fsck`

Also, can you verify that you don't have any tags with the name `main`? Running `git tag` will list those. I just want to confirm there aren't clashing ref names.

**Comment by Steph-Pelletier** [comment]
Hi Steveward,
For the `git branch -a`:
![image](https://user-images.githubusercontent.com/102295303/223039578-7a4a30b6-1521-4d9a-8fbf-3cd3510ce906.png)
I'm actually on the 'detached Head branch'. 
By using `git switch main`, I can easily go back to my *main* branch, but **this is impossible by using GitHub Desktop** >> In this case, I'm always going back to this detached branch...

The `git fsck` shows a lot of warning, I imagine because of my 'tag' naming, but nothing more.
![image](https://user-images.githubusercontent.com/102295303/223041066-134ab24c-57f8-40d4-8295-05bb4fa6d485.png)

I also check that there is no tag named `main`

Thanks for help

**Comment by niik** [comment]
Hey @Steph-Pelletier, thanks for reaching out. This issue is happening because you have a remote as well as a branch named `main` (and also a remote branch `main/main`). If you try using `git checkout main` on your CLI you'll see the same problem that GitHub Desktop is having. We've been looking at switching (no pun intended) our use of `git checkout` to `git switch` for this exact reason but we haven't gotten there quite yet. While we work to resolve this your best workaround will be to rename that remote from `main` to something else using `git remote rename main newname`
