### ISSUE TITLE
Even after loggin out and switching account I am being shown the old account repositories

### ISSUE THREAD

**Issue by NeeleshShekhar** [desktop/desktop#16252]
### The problem

Even after loggin out and switching account I am being shown the old account repositories. I logged out from my previous account and logged in with another, yet I am shown the old repo, and the error that the repo do not exist or I dont have access to them

### Release version

Version 3.2.0 (x64)

### Operating system

Windows 11

**Comment by niik** [comment]
Hey @NeeleshShekhar, this is expected behavior. When you clone a repository it creates a complete copy of that repository on your local machine. This repository can still be used to commit and checkout code but without the correct credentials you won't be allowed to push those changes to the remote (GitHub.com).
