### ISSUE TITLE
git@github.com: Permission denied (publickey).

### ISSUE THREAD

**Issue by JayJiangCT** [desktop/desktop#16279]
### The problem

I have been using SSH to complete various operations in the repo, and there have been no problems before. But today, when I was fetching the branch, the client reminded me "Authentication failed. Some common reasons include...".So I opened the terminal to verify the SSH connection, and everything seemed to be normal, and I could also complete various operations through the command line.
<img width="569" alt="image" src="https://user-images.githubusercontent.com/59813406/223946282-a7e2450c-614d-431c-b29e-42058c7f0883.png">

### Release version

Version 3.2.0 

### Operating system

macOS Monterey Version 12.6.2

**Comment by steveward** [comment]
Thanks for the report @JayJiangCT. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by JayJiangCT** [comment]
Yeah, sry to reply. I’ve solved this question. Thanks
for your feedback.

Best regards,
Jay
Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
