### ISSUE TITLE
Merge Conflicts Often Left Unresolved

### ISSUE THREAD

**Issue by Mashimaro7** [desktop/desktop#16292]
### The problem

Even if you resolve merge conflicts, sometimes the conflicts remain in the files. I've had this happen multiple times. Another related issue, merge conflicts sometimes don't get resolved if you click merge before the conflicts have a chance to appear. Why can't there be a tool built in to GitHub Desktop that lets you resolve issues whenever you want? This is by far not my only issue I've run into related to conflicts when it comes to merging 2 branches... 

### Release version

Version 3.2.0

### Operating system

Windows 11

### Steps to reproduce the behavior

1. Have a conflict
2. GitHub fails to resolve conflict

**Comment by steveward** [comment]
@Mashimaro7 thanks for the issue. Are you manually resolving merge conflicts in your editor, or choosing the use ours/theirs  option in the dropdown? GitHub Desktop won't clean up all of your files if you're manually resolving merge conflicts. There is a reported issue where pulling fails due to unresolved merge conflicts, even though the merge conflicts have been resolved (https://github.com/desktop/desktop/issues/11959). Could that be the issue you are experiencing?

>merge conflicts sometimes don't get resolved if you click merge before the conflicts have a chance to appear.

You can't click the "Create a merge commit" button until the detection finishes. Can you share the specific behavior or share a video of this behavior?

If you can share some further screenshots/video/details about the issues are experiencing that would be helpful.
