### ISSUE TITLE
GitHub Desktop adds files that shouldn't be added (untracked files).

### ISSUE THREAD

**Issue by lghtlr** [desktop/desktop#16302]
### The problem

GitHub Desktop automatically starts tracking new files from Android Studio. In Android Studio itself, these files are "unresolved", and in the console version of git they are also "untracked". This hasn't happened before. If the files were "untracked", they didn't show up in GitHub Desktop and I could add them manually from Android Studio.

### Release version

Version 3.2.0 (x64)

### Operating system

Windows 11

### Screenshots

Android Studio:
![image](https://user-images.githubusercontent.com/70912742/224542760-c1f3e4bf-adb5-43c5-ac69-b944eba99e41.png)

Console git:
![image](https://user-images.githubusercontent.com/70912742/224542895-c79b92f6-c94e-4b03-be26-27995d478d9d.png)

But in GitHubDesktop they added automatically.
![image](https://user-images.githubusercontent.com/70912742/224542913-55773dd6-a80c-459e-acc8-793f14dfdc15.png)

### Additional context

On the Internet, I found answers that GitHub Desktop is not designed to hide untracked files. If so, why didn't untracked files show up in the GitHub Desktop list before?

**Comment by steveward** [comment]
Thanks for the issue @lghtlr. Not utilizing the staging area in GitHub Desktop is an intentional design decision that's been with us since the very beginning. We believe that the benefits of having a simplified approach to committing outweighs the benefits of using a staging area for users more well-versed in Git's inner workings. This follows our [design guidelines](https://github.com/desktop/desktop/blob/development/docs/process/what-is-desktop.md#3-github-desktop-prioritizes-workflows-for-beginners-and-collaborative-teams). See https://github.com/desktop/desktop/issues/4475 for a previously opened issue on the topic.
