### ISSUE TITLE
desktop client does not change branch

### ISSUE THREAD

**Issue by Zack-83** [desktop/desktop#16309]
### The problem

The desktop client does not allow to change branch if there were synchronization issues in the present branch. It only utters an error message and bumps back to the present branch.

![image](https://user-images.githubusercontent.com/37865804/224708062-5f0a1df3-d255-4d3e-9f98-04e658cdf1d5.png)

### Release version

3.2.0. x64

### Operating system

Windows 10

### Steps to reproduce the behavior

![image](https://user-images.githubusercontent.com/37865804/224709102-7c128c97-b2c6-48b6-a435-4564c08c081b.png)

1. You start on this state (branch with nonsynchronized changes).
2. You realize you are on the wrong branch.
3. You select another branch.
4. It does not work.

**Comment by steveward** [comment]
@Zack-83 thanks for the issue. This looks like a permissions issue based on the error. Can you share a log file from GitHub Desktop so that I can take a look at what the underlying error might be?

To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
