### ISSUE TITLE
fetch n pull issue

### ISSUE THREAD

**Issue by nachiketmore-bombayfintech** [desktop/desktop#16312]
### The problem

there is always problem to fetch and pull after PR. I have so many local branches in repo. code not pushed to remote from application but same will be done on visual studio. and if we again fetch on application then pending push with count is shown again in both (application as well as visual studio) same happens with visual studio code also.

### Release version

Version 3.2.0 (x64)

### Operating system

windows 11

### Steps to reproduce the behavior

1. commit changes, 
2. try to push

1. raise PR 
2. approve pr
3. again go to feature branch
4. click on fetch origin

**Comment by steveward** [comment]
@nachiketmore-bombayfintech thanks for the issue. Could you try reproducing this issue and then sharing the log file from GitHub Desktop so that I could take a look at what might be happening here?

To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`. Thanks!
