### ISSUE TITLE
Feature Request: Graph history view

### ISSUE THREAD

**Issue by rlabrecque** [desktop/desktop#1634]
Just testing the waters on this one but, one thing that I'm missing from all of the more 'advanced' clients is essentially `git log --graph`.

This would just display all branches in one history view, with a nice little DAG graph showing how the repo fits together.

Pretty much like this:
![image](https://cloud.githubusercontent.com/assets/2047188/26226176/07f210ca-3be8-11e7-8e04-bb8d2cb9f9ef.png)
(Taken from Stack Overfloew: http://stackoverflow.com/a/9074343)

![image](https://cloud.githubusercontent.com/assets/2047188/26226206/3cfa86da-3be8-11e7-87a3-f6cf03e4ba93.png)
(SourceTree)

**Comment by mshahat** [comment]
Would that be considered related to the Comparison Graph in the current non beta version ? I can't see as part of the current beta ?

**Comment by rlabrecque** [comment]
I guess so, sort of, could you only select two branches in the native version though? Having it vertical and tied to the actual commits is quite a bit nicer too though.

**Comment by b1rdex** [comment]
IMO, full tree is too complex and we should decide the main reason to add this feature.
Native desktop had this:

![](https://githubengineering.com/images/cross-platform-ui-in-github-desktop/comparison-graph-os-x.png)

These was pretty neat feature in GitHub Desktop and I used to it.
Main differencies between this and native `git log --graph`:
- comparing two branches — very easy to see if branch is outdated
- action to merge from original branch
- local commits (not pushed) are marked and notable

**Comment by mshahat** [comment]
![image](https://cloud.githubusercontent.com/assets/8035442/26395657/aa4381f4-4068-11e7-807c-c627363f0e03.png)

This simple Comparison Graph was very usable, and is definitely something you'd want to make sure is there. It's a good compromise than the overwhelming Git graph. 

Cheers,

**Comment by joshaber** [comment]
Thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I'm going to add the `future-proposal` label to this issue and close it out, so that we don't get overwhelmed with our backlog! We'll revisit these as part of our next planning session.

**Comment by mikeytag** [comment]
@joshaber I know you're kicking the can on this one, but I find this feature one of the most valuable features of the earlier native Desktop version. As such, are there plans to deprecate or make the earlier versions not work? I'm hoping not so I can keep using the earlier version until the visual branch makes it into the new release.

Please note, I'm not trying to be a jerk about this. I love GitHub and really enjoy the Desktop experience. I've just settled into workflows that the visual branch really helps with.

**Comment by shiftkey** [comment]
@mikeytag check out our [roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md#11) for 1.1 - we want to tackle the relationship between the current branch and _some other context_. We're still thinking more on this, but our learnings from the classic apps and the comparison graph will help us here.

**Comment by joshaber** [comment]
>are there plans to deprecate or make the earlier versions not work?

To answer this specifically, when the beta hits 1.0, the classic apps will be deprecated. We will no longer support them.

That said, we _don't_ plan to disable them or disallow their continued use in any way.

**Comment by stebiger** [comment]
I am sorry if I am about to open that topic but I am not sure what the actual output of that discussion was.

Will there be any visualization for my repository? I can't find it on the roadmap even future versions but I also can not read any decisions about that in this issue.

**Comment by rlabrecque** [comment]
@stebiger A full graph view is not on the table (at this time), but something like the classic app had is pending for Milestone [1.1](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md#11). The big difference between this issue/request and what might be coming in 1.1 is the scope exposed to the end user.

**Comment by orangeswim** [comment]
Would like to see this feature as other configuration management software have this as a standard. I know I'm not adding anything new, except to say that there are people who want this for git desktop.

**Comment by edwinveldhuizen** [comment]
I also really want to see back this feature. I've still been using the old native GitHub desktop app because of the graph missing in the "new" app.

We're working with tens of different branches and the original graph gave a really good overview of which commits are in master that are not yet in my local branch.

**Comment by carrotalan** [comment]
+1 - I'll have to switch back to SourceTree until this is present

**Comment by lordtherick** [comment]
Agreed - the visualisation is a great selling point for change control and the operations team to see who and where changes were introduced. 
I would like to offer the business a GitHub ecosystem and this is definitely a tick in the negative column. (even a separate GitHub app would be acceptable for us)

**Comment by gary-menzel** [comment]
I've only just upgraded to the latest version and agree with other comments here.  I had some issues just before upgrading and the mini-graph helped identify that there was a problem. It was then suggested I upgrade and now that problem would be much harder to identify (although, there may be new features that help in this latest version that I am not aware of).

**Comment by shiftkey** [comment]
> I've only just upgraded to the latest version and agree with other comments here. I had some issues just before upgrading and the mini-graph helped identify that there was a problem. 

@gary-menzel what sort of problems were you encountering that the graph helped you out?

**Comment by gary-menzel** [comment]
There were some synchronisation issues between forks and despite having tried a few mechanisms to resolve it, the old version showed another colleague (based on the graph nodes that didn't look right) what needed to happen to resolve it.

**Comment by LeahPike** [comment]
I would love to have this comparison graph back, I feel a bit lost in the new one without it giving me an overview.

![image](https://user-images.githubusercontent.com/6124100/34069537-e5bd9546-e24b-11e7-8416-9f49ecd68cfd.png)

**Comment by gutrix** [comment]
I've personally moved to GitKraken until GitHub desktop re-implements this feature.

**Comment by DrZYin** [comment]
My two cents on this issue:

If you google "git guis", the first result is this page: https://git-scm.com/downloads/guis/

It lists 20+ git guis, each with a screenshot. Look at each screenshot and you'll realize they're all taken at the tree view. (except Github Desktop of course)

This comes down to "what the author thinks is important" vs "what average users think is important". The latter may actually come from "what users' boss and users' business partners think is important".

I personally believe this issue should at least make it into the roadmap. Our core contributors are all very good at git, they may feel the treemap has never been a useful thing in their experience, but average users may want it for different kinds of reasons.

**Comment by j-f1** [comment]
BTW, that screenshot is out-of-date. Is there an up-to-date screenshot I can PR?

**Comment by rlabrecque** [comment]
> This comes down to "what authors feel is important" vs "what users feel is important". The latter may actually come from "what their boss and their business partners can understand".

That's my biggest worry with highly analytic driven productivity applications. It's the reason why both SourceTree and GHD got rid of the project sidebar. :( Different people have different workflows.

In my case the tree/flow view helps me better visualize what my team is doing and where I am in respect to the other branches.

> BTW, that screenshot is out-of-date. Is there an up-to-date screenshot I can PR?

Which screenshot?

**Comment by j-f1** [comment]
> Which screenshot?

That was more of a question for the other @desktop folks, but I meant the GitHub Desktop screenshot on the Git page linked above.

**Comment by kinghuang** [comment]
The lack of a graph view is the reason I've stuck with the older native client (#2885). There's no way I'm upgrading without it.

**Comment by Am1rr3zA** [comment]
WoW, I got a new mac and install GitHub desktop and see the graph is gone, I don't understand why. I was only using GitHub desktop because of this graph. So now going back to source tree

**Comment by roee-leverate** [comment]
Downloaded Github Desktop few days ago.  Overall nice until I couldn't find the log. I really like our cant but The graph is most needed. either moving back to SourceTree or switching to Kraken which looks great from first look.

**Comment by lrgsteven** [comment]
I evaluated it for use by a mixed team of devs, designers and artists working remotely, and lack of a full graph makes it less appealing than alternatives like SourceTree.

**Comment by r-laporte** [comment]
Downloaded it recently. Seemed to be a good replacement for all other git guis we use. But in our project with many branches and many teams, the lack of the tree graph makes it too short of a useful tool. Hopefully it will be added in the future and we'll consider changing to this one again. Meanwhile we're forced to use another tool :(

**Comment by KMFSousa** [comment]
The older client is superior to the new one for pretty much just this reason. Without this you're actively losing people to sourcetree, gitkraken and other alternatives.

**Comment by sursir** [comment]
I don't believe The Graph history is removed rather than improve it.

**Comment by const-int** [comment]
Are you planning to add this feature in the near future?

**Comment by gary-menzel** [comment]
I've tried to work with this new github client since my original comment earlier in this thread and it just is not as useful as SourceTree.  So, I'm leaving github desktop behind.

**Comment by individual61** [comment]
Why on Earth would such a useful feature be removed? I am a very visual person, and this made git finally "click" for me. Please put it back on the roadmap!

**Comment by edwinveldhuizen** [comment]
@mshahat @rlabrecque @b1rdex @joshaber @mikeytag @shiftkey @stebiger @carrotalan @lordtherick @gary-menzel @orangeswim @LeahPike @gutrix @DrZYin @j-f1 @kinghuang @Am1rr3zA @roee-leverate @lrgsteven @r-laporte @KMFSousa @sursir @const-int @individual61 

Please sign and share this petition:
https://www.change.org/p/github-bring-back-the-visual-history-graph-on-github

Maybe this will work better than commenting in this old closed issue.. 😊

**Comment by amputek** [comment]
+1 - The Graph was incredible useful. Would love to see this added to the new Desktop

**Comment by jaketyo** [comment]
@kinghuang I tried 1.0, but I was forced back because of the lack of graph view.

I think that should have been part of the feature-partiy when building the new app. Seems odd to remove a massively useful feature and call it an improvement.

**Comment by mikeytag** [comment]
I gave the new Desktop app a try for 2 weeks. I really did, but just went back to the old client for one reason: the graph view. I found myself lost too many times in the new one without the visual reference. Crossing my fingers hoping the dev team takes notice of how many people want the graph view back. For every person on this thread there are thousands of users that don't take the time to talk about it and just switch to something else.

FWIW, the speed in the new app is nice. It's just a more confusing experience.

**Comment by timdeng2324** [comment]
so just wondering, was this revisited as part of the next planning session and will it make a future release? it's been a while.

**Comment by iAmWillShepherd** [comment]
@timdeng2324 we did revisit this and decided to prioritize other things ([roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md)); however, it is still something that could potentially get prioritized in our next planning session.

**Comment by raeleus** [comment]
Please do. The only reason I don't go back to SourceTree is that the requests they have ignored aren't as annoying as the ones found here.

**Comment by mikeytag** [comment]
@iAmWillShepherd would it be ok if I forked and took a crack at adding a view like the one that was in the native app? I know I went too far with my issue about this recently, and if I feel so strongly about the feature I should just try to implement it myself.

However, I want to be respectful of you guys and I don't want a PR to be seen as harassment if I were to code it and there is a business decision to not do the view for some reason. I've been reading the developer docs to make sure that whatever I do adheres to the coding standards the team expects.

**Comment by iAmWillShepherd** [comment]
@mikeytag 

> would it be ok if I forked and took a crack at adding a view like the one that was in the native app?

The short answer is yes. We wouldn't mind if you forked Desktop to add this feature, but...

The desktop team has not settled on whether we will tackle this yet, so us accepting a PR at this point is unlikely. Why? Simply because we'd like to make sure that whatever we build or accept from the community fits within the overall design of the application.

If you are keen on having this ASAP and don't mind that their is potential your PR won't get merged, then by all means, do it 👍 . Who knows, it may be a good starting point should we decide to pursue this. Otherwise, I'd recommend holding off until we have a good idea of how we want this to work.

I know this response isn't ideal, but I wanted to be as transparent as possible. 😃

**Comment by mikeytag** [comment]
@iAmWillShepherd 

Thank you for the reply. I hear you on a PR being merged. I've been interested in Electron development and may go for it just to scratch my own itch and learn something along the way. I understand on the PR acceptance.

FWIW, I really loved the simple implementation in the old native app that just compares the current branch against one other with a default to the default GitHub branch. There's a bit of animation going on in the old one so it may throw me for a loop, but I'm planning at trying to recreate that view and add a menu option to make it visible/hidden. That way you guys could accept the PR if the default was hidden on that pane. I'm not the first to request this so it may be a good compromise?

All that's left is for me to find the time to tackle it and get it to work.

**Comment by mikeytag** [comment]
Thanks @j-f1 ! This may have just gotten a lot easier.

**Comment by mikeytag** [comment]
Found it at Contents/Resources/comparison-graph

It looks like they used jQuery and a couple plugins with some svg stuff.

**Comment by JeanCollas** [comment]
It seems that is a popular demand, that has been backed by a large number of people (not including all who don't ask for it but would like it), and which is coming back frequently.
How could it be so complicated? "The desktop team has not settled on whether we will tackle this yet" :(

**Comment by bmcdonnell-ionx** [comment]
I don't understand how people comfortably work without getting a visual overview of the repo, i.e. full tree view.

**Comment by middiu** [comment]
this is a must have

**Comment by albinekb** [comment]
I have never ever used that and have never needed it. I don't think this is a must have @middiu @bmcdonnell-ionx

**Comment by bmcdonnell-ionx** [comment]
@albinekb, how do you discern the relationships of your branches to each other, at a glance or all at once? e.g. `feature-abc` branch is 3 commits ahead of `master`, and `master` is 2 commits ahead of `feature-abc`; `feature-abandoned` is 30 commits behind master. And how do you tell which commits those are?

**Comment by trusktr** [comment]
Literally the only reason I left my terminal to try GitHub Desktop was hoping there was a visual graph. The rest I can do just fine in a terminal.

**Comment by JeanCollas** [comment]
@joshaber is there any chance to see this back on the roadmap?

This would really be useful. On my view, much more than several other "improvement" done the last months...  I still don't understand why it disappeared...

**Comment by bmcdonnell-ionx** [comment]
@trusktr,

FYI, in a terminal you can get a visual graph as sort of ANSI art with some options to `git log`. I like to create an alias in my `.gitconfig`:

```
[alias]
    tree = log --all --graph --decorate --pretty=oneline --abbrev-commit
```

Here are some [other variants](https://stackoverflow.com/questions/1057564/pretty-git-branch-graphs).

And other GUI clients have a tree view (e.g. Git for Windows and Git Extensions).

**Comment by etbassler** [comment]
I just switched computers and thought I would tryout Github Desktop. I will be going back to Sourcetree or another solution because of this functionality.

**Comment by corysmc** [comment]
I miss the old Github branch visualization. I'll keep using the deprecated Github UI until this is added to the electron version.

**Comment by langgaibo** [comment]
Amazed that this feature is still lacking. I guess nobody making roadmap decisions works with more than one or two other devs at a time. Must be nice 😬

**Comment by j0rdnh** [comment]
+1 for this feature, I'll be switching back to SourceTree until it's added.

**Comment by Sergio1C** [comment]
> +1 for this feature, I'll be switching back to SourceTree until it's added.

and me bro

**Comment by jaketyo** [comment]
> +1 for this feature, I'll be switching back to SourceTree until it's added.

I'm still using the legacy desktop. Still works very well!

Makes me wonder why so much development effort is going into a tool that the community strongly feels is worse.

**Comment by kinghuang** [comment]
Yeah, I'm still using the legacy desktop app, too. Graph aside, the new app just doesn't work as well as the legacy app.

**Comment by kinghuang** [comment]
@kireerik True, the new app's improved since it's original launch.

The biggest issue I have, other than the lack of a graph, is that I can't work with multiple repositories simultaneously. With the legacy app, I can have multiple windows and tabs open to easily work with several repositories at once. No such option on the new one. And, the lack of a permanently visible repositories list makes it even worse. I'm working on three different repositories right at this moment, and the legacy app makes it a breeze.

![screen shot 2019-01-29 at 4 45 08 pm](https://user-images.githubusercontent.com/27340/51948328-4b573480-23e5-11e9-8182-60eb783e38c3.png)

Plus, the minimum window size in the new app is too big! :)

**Comment by kireerik** [comment]
@kinghuang Yes. I am using legacy too. Mostly because the layout including the visible repository list is much better.

**Comment by Nathananan** [comment]
Shocking there isn't a branch graph. Its super useful. If its not on your current roadmap then your roadmap is wrong imo...

**Comment by j-f1** [comment]
Proposal: put the graph view above the diff shown when comparing two branches.

**Comment by lannex** [comment]
+1 for this feature, I think it's essential.

**Comment by marcocastignoli** [comment]
This feature is the only thing that keeps me using GitKraken instead of GitHub Desktop! Please bring back this feature!

**Comment by aurnoi1** [comment]
Please bring back this feature: "A branch graph is worth a thousand code lines".

**Comment by intricco-Chris** [comment]
Please bring back the timeline.
It was the only way for me to explain branches, show progression, and status to NON programmers.
Management may scrap our use of this.

**Comment by jftaulbee** [comment]
I found this feature request in a Google search looking for an option to enable git graphs. Very disappointed to see this is not a feature. I'm evaluating different Git clients for my manager and I guess I'll recommend Git Kraken or Sourcetree as an alternative. I hope you reconsider and add this as a feature soon.

**Comment by Jakintosh** [comment]
Just going to be another person throwing in their two cents that I've been ignoring the update dialogs for years(?) at this point, because this feature is literally the main reason I use this desktop app. It's a GUI app for a command line tool... give us the "G" part!

**Comment by JamesRichardsonTTP** [comment]
Adding my vote for this fairly obvious feature :) Literally no reason not to include it. Have it as an option if you like, but this really is a basic requirement for a GUI app...

Is there a way to install the old version that includes the branch tree?

**Comment by ssatguru** [comment]
Adding my vote. Switching to kraken for now.

**Comment by JeanCollas** [comment]
@joshaber Why is this issue still closed? :(
It is requested several times a month, it proves that this is a major issue of the software, which is great besides that.

**Comment by billygriffin** [comment]
Hi @JeanCollas and all, thanks for the follow up. We're still continuing to work through the future proposal issues to determine whether we intend to support them - we now have around 40 remaining down from upwards of 150. I appreciate that many people have come to expect a feature this in Git GUI tools, but we've also found that it can cause confusion for many people because it can be tricky to depict the graph in a way that's very intuitive. We've also never seen this or anything like it as a request from brand new users to Git and version control, which makes it seem like something that people have gotten used to from other tools and not necessarily something that's solving a super pressing need. We're not opposed to this and that's why it has `future proposal` still - we're just working our way through all the possibilities of features to support and it's still under consideration. After our next release we'll be much more focused on moving toward some resolution on the issues remaining in that category, and I appreciate your patience.

**Comment by JeanCollas** [comment]
@billygriffin I understand that can cause confusion for some people, that is why it should be optional (hiddable?). 
However I found the former Github desktop graph (2 lines) very intuitive and easy to use (see capture from @b1rdex above):
- to get information on past commits
- understand how we are compared to a reference branch
- understand merges
- understand what has been and not been pushed etc

It should not be more complex than this, the multi-branch graph is very confusing. However the way it had been designed in the previous github version was awesome and very clear.

It may also be because not everybody think and materialize process the same way, and when lists are fine for some people, a graph with very few shapes is much more clear for other.
It is just a way of understanding what happens. It doesn't even need to trigger any action besides giving information. Like a significant gain of time.

Thanks for your work, the newer versions are much more stable than 1 year ago, and now I really hope that you will find some time to work on this specific issue.

**Comment by billygriffin** [comment]
Thanks @JeanCollas, that's a really helpful breakdown of how you see what might belong in Desktop and what might be too expansive - I really appreciate you taking the time to describe in what scenarios it's most useful as well, and definitely helpful when we're able to revisit including this as a feature. Thanks again!

**Comment by ZYinMD** [comment]
The github version is not bad:
https://github.com/desktop/dugite/network
The gitlab version is similiar, a equally simple implementation, but feels a lot better.
You don't need any functionalities, just a plain static graph.

**Comment by superfliege** [comment]
Please bring back this feature. It is one of the main use cases..

**Comment by zhoujian365** [comment]
I don't see any point using a "GUI client" without a graph.

All other tasks we can just do fine with command line.

**Comment by JosephTLyons** [comment]
Just jumping in to mention my wishes to have this feature back as well.

**Comment by lukasz-bendykowski-fluke** [comment]
@billygriffin I understand how this works when you have lots of issues to cope and prioritize, you will never make all users happy. You've written that you didn't get requests for this feature from git newbies. And this makes sense as newcomers have often no idea about branching, and work with Git in a simplified way, committing and pushing directly to the master branch. However, when you work in a more experienced team on a bigger project, you will need to work on feature branches. It's super convenient to have a graph history view to track all dependencies between branches. One look and you know when the branch was created, what is its origin, how many commits it is ahead/behind, how many commits it has, how many branches are still not merged, or when a specific branch was merged. I agree it can be complicated for newcomers, but do you aim mainly them, or advanced users as well? Our team is switching from BitBucket to GitHub at the moment and knowing about this feature missing in a desktop app nobody is dumping Sourcetree. I hope this will be considered as a higher priority feature in the product roadmap. Thanks for the great application anyhow guys, great work!

**Comment by billygriffin** [comment]
Thanks @lukasz-bendykowski-fluke for the additional context, that's really helpful. I didn't mean to suggest that GitHub Desktop is just for beginners, but we've found that understanding what problem people are actually trying to solve vs. what people have gotten used to is an interesting way to frame something like this. That's why I referenced the beginners piece, because this does seem like something where people who are used to approaching branching through a graph find it helpful, but for those who are new to the concept, I've actually found that introducing a visual graph causes more confusion than clarity.

To be absolutely clear, we have not yet made a decision on how to proceed on this - we have 29 remaining future proposals and working our way down to zero, at which point these will either be closed for good or reopened as something we intend to support. But thoughtful comments like yours and @JeanCollas' are really helpful in us understanding the use case of folks moving over from other tools and the absence of a graph not really working for them. Thanks again. ❤️

**Comment by bmcdonnell-ionx** [comment]
@billygriffin, it wouldn't have to be "front-and-center" by default. It could be an option you allow users to enable. (Personally, I not sure if I might like to make it always visible in a pane, vs. just a window that you open by menu option or keyboard shortcut. But I think you could implement the UI in such a way that it's easily discover-able, but not in the way of users who would be confused or annoyed by it.)

Thanks for the status update.

**Comment by pnadar** [comment]
Why use a software that does not have a fundamental graph feature that has you can find in a 15 year old clients like smartsvn etc. Move to sourcetree.

**Comment by Tom-Evers** [comment]
I'm trying not to be a dick about this, because I like GitHub and its products, but I ended up here looking for this very basic feature in the desktop app that is apparently not implemented yet.
I have to say: how is it that you've got a feature request that has 89 replies and well over 100 upvotes, obviously describing functionality that is essential to many, with people left and right saying "I love GitHub but I can't use it this way"...
...and the reaction is: it's in future proposals, it might be implemented. _We'll see._

It all just rubs me the wrong way, so I might come across as a bit toxic. I'm sorry for that.
What I'm trying to say: a graphical view for something that is difficult to visualize for so many people isn't something that "might be implemented in the future". It should be top priority.

**Comment by alanscandrett** [comment]
Like @Tom-Evers I cam here trying to find out whether there is a tree view of some sort, now that we are migrating from mercurial to git. 

Coming from using tortoise-hg's fantastic tree view it is surprising to see that isn't even an option here, especially given[ how many other clients feature a tree view](https://git-scm.com/download/gui/windows).

I just don't see how you can possibly communicate what can be seen here by glancing at a colored tree, as you could in text format.
![image](https://user-images.githubusercontent.com/23227595/63667578-b8199c80-c817-11e9-8c8a-5c930217a206.png)

**Comment by fhfournier** [comment]
Adding my vote. i had to switch from GitKraken because he is no longer free!

**Comment by langgaibo** [comment]
Hi folks how's everyone's day? Oh me? I was just flipping the desk calendar that says "months of denial that `git log --graph` should be reimplemented into the GUI" to 28, kind of weird tbh

**Comment by MichaelBelgium** [comment]
@fhfournier 

>Adding my vote. i had to switch from GitKraken because he is no longer free!

Same here. Pain in the ass to find a replacement - and stupid decision of gitkraken devs to charge money if u wanna work with private repo's.
Although github desktop looks like a solid replacement but it's missing a lot of visuals. 
For example the "drag-n-drop" feature of branches to one or another to merge/rebase/... is what i absolutely loved about Gitkraken. And the visualization of branches is really well done. Hopefully github desktop can have this in the future too.

Or just another way to see more than one branch in the window (or history tab or w/e).

**Comment by brianpenghe** [comment]
Please bring back the graph visualization! It's extremely useful!

**Comment by Jakintosh** [comment]
Checking in on this thread every couple months to see if there's been any movement is both very comical, and extremely sad.

**Comment by intricco-Chris** [comment]
I've been following this thread so long... I give up.
Obviously Microsoft does not listen to customers.

Maybe they will listen when enough of us drop them.
Microsoft if you read this, email me when you update. 
Till then, I will suffer with BitBucket in protest.

**Comment by james0807** [comment]
There's clearly more to this than they are letting on... there is literally no reason to avoid implementing this feature unless someone is preventing them from doing so.

**Comment by rlabrecque** [comment]
For the record I ended up with https://git-fork.com/ as my primary tool for now.

**Comment by kinghuang** [comment]
I actually did try GitKraken for a little while. But, I found it a little hard to get used to. I guess I've just spent too much time with the old, native GitHub Desktop client.

I'm still using the native GitHub Desktop app as my main client, right now.

**Comment by MichaelBelgium** [comment]
> @fhfournier @MichaelBelgium and anyone else here. Why not just use GitKraken? It think $2/mo as a contribution towards two incredibly useful products is more than fair. If it's out of matter of principle I get it. Still, honestly I think the lack of attention this has received warrants a move to most other products regardless.

I considered to pay for it but they only accept credit cards. I even applied for a free license as i'm a teacher, it got approved but I still gotta have a credit card - which i dont have. So too bad ... :/

**Comment by billygriffin** [comment]
Hi folks, this isn't the venue for discussion of things unrelated to this issue as when we do pick long-running issues up, it creates noise and it's difficult to sort through the feedback related to the actual problem we're trying to solve. Therefore, I'm going to hide the responses that don't pertain to the feature as off-topic. If it goes too far off the rails, we'll have to lock the issue. For examples of responses that *are* helpful in determining the extent of the problem and informing possible solutions, please see these:

- https://github.com/desktop/desktop/issues/1634#issuecomment-483420857
- https://github.com/desktop/desktop/issues/1634#issuecomment-505834757

I appreciate the frustration that this feature isn't yet in the product, and I also totally understand that for some people this may be the best feature of a GUI. For many others, it's not necessary at all, and we do our best to balance those tradeoffs in what features we prioritize. Thanks for your input and understanding.

We will update this issue if we do decide to pick it up as something we'll be working on. Thanks for your patience.

**Comment by jaketyo** [comment]
It's like if an automaker stopped making anything with a back-row of seats, just because some of the buyers don't want it. Even though it's the minimum requirement for a majority.

**Comment by suhailmahmood** [comment]
I don't get it. How can GitHub desktop be a git client without having a graphical commit history? Answer: it isn't, and it can't be without graphical commit history.  Who thinks _it's not necessary at all_? If you are not working on this, I can't imagine what else you can be possibly working on?

**Comment by floyebolu** [comment]
A simple "I also would very much like this too."

**Comment by sneistat** [comment]
I KJM

**Comment by EntityCuber** [comment]
Do it

**Comment by Jakintosh** [comment]
The joke here is whatever features you are working on that are "higher priority" than this one don't matter for any of us, because we refuse to even use the product until this feature is added. I thought it was a holy grail to have a huge chorus of users telling you exactly what single feature they need to make a product very valuable to them, so it's kinda weird that the approach here is to tell everyone they're wrong and hide all their comments ¯\_(ツ)_/¯

**Comment by intricco-Chris** [comment]
Is anyone aware of what Google uses? I know they listen to customers. I doubt they put up with this.

**Comment by kireerik** [comment]
Maybe we could reuse the source code of the existing [network graph](https://help.github.com/en/github/visualizing-repository-data-with-graphs/viewing-a-repositorys-network) feature and simplify it to make it work as it does here (https://github.com/desktop/desktop/issues/1634#issuecomment-303664433).

@billygriffin What do you think?

**Comment by pnadar** [comment]
> Is anyone aware of what Google uses? I know they listen to customers. I doubt they put up with this.

I heard they use perforce, one big repo with every thing they have done.

**Comment by billygriffin** [comment]
Hi folks, I appreciate that this is frustrating for you. We've all had times when we wish the tools we use would just have *that one feature* that means the most to us, and I understand that this one is particularly meaningful for many of you who have responded in this thread. We don't typically lock conversations and don't like doing it because it eliminates the possibility for people to explain their use cases and offer insight that helps us prioritize features and provides context for how we can best solve the problem if/when we choose to pick up the issue.

Thanks to those of you who have participated respectfully in this issue and provided useful context. As I mentioned previously, we haven't yet decided whether or how we intend to pick this up, but we'll certainly update the issue when we do so y'all are able to make an informed decision if your usage of Desktop relies on this feature being a part of the app.

**Comment by tidy-dev** [comment]
From https://github.com/desktop/desktop/issues/19135

The feature request
Overview
We kindly request the implementation of a graph view feature in GitHub Desktop to visualize branch history and relationships. This feature has been highly requested by users for several years, as evidenced by previous issues https://github.com/desktop/desktop/issues/5468 and https://github.com/desktop/desktop/issues/1634.

Rationale
A graph view would significantly enhance users' ability to understand and navigate complex repository structures by:

Providing a clear visual representation of branch relationships
Facilitating easier tracking of merge history
Improving overall project comprehension, especially for larger teams and projects
Proposed solution
The graph view should:

Display a visual representation of branches and their relationships
Show commit history across all branches in a single view
Include a DAG (Directed Acyclic Graph) to illustrate how different parts of the repository fit together
Allow for easy navigation and exploration of the commit history
Additional context
User Impact
Implementing this feature would:

Streamline workflow for developers managing multiple branches
Reduce the need to switch between GitHub Desktop and command-line tools for visualizing repository structure
Enhance the overall user experience, particularly for visual learners and those working on complex projects
Previous Discussions
While this feature has been requested before (issues https://github.com/desktop/desktop/issues/5468 and https://github.com/desktop/desktop/issues/1634), the persistent interest from the community highlights its continued relevance and importance to users.

Conclusion
We believe that adding a graph view for branch history visualization would significantly enhance GitHub Desktop's functionality and user satisfaction. We respectfully request that the development team reconsider implementing this feature in future updates.

Thank you for your consideration.
