### ISSUE TITLE
Removing Account Name

### ISSUE THREAD

**Issue by HopeWaddell** [desktop/desktop#16353]
### The problem

I want to remove account HopeWaddell and start over.  Please help or tell me how to do the change. Thanks

### Release version

None

### Operating system

None

**Comment by sweezyio** [comment]
You can remove an account by going to `File > Options... > Sign out`.

**Comment by tidy-dev** [comment]
@HopeWaddell It is unclear if your issue is specific to GitHub Desktop or if you are wanting to close your GitHub account.  If you are wanting to sign out of GitHub Desktop you can follow the instruction @sweezyio provided above. Otherwise, if you are having trouble closing your GitHub account, you can [contact GitHub Support](https://support.github.com/request). Closing this issue, feel free to answer with further clarification if needed. :)
