### ISSUE TITLE
Commit newlines get eaten when separating title and body

### ISSUE THREAD

**Issue by annevk** [desktop/desktop#16372]
It seems that GitHub Desktop searches for the first double newline and determines everything before that to be the commit title. This doesn't work for projects like https://github.com/WebKit/WebKit and also doesn't follow how GitHub itself determines what to display as the commit title and commit body.

It seems like it should instead search for the first newline.

**Comment by annevk** [comment]
(Same version and OS as #16373. Apologies for not using the template.)

**Comment by sergiou87** [comment]
Hello 👋 
GitHub Desktop is actually using `git log`'s `format` parameter, using `%s` for the summary (first line) and `%b` for the body (the rest). It's git who's actually looking for 1/2 new lines 😞 

I played with these commands to make sure that was it:
```
git log main --date=raw --max-count=100 --format="%s" --no-show-signature --no-color -n 1 --
git log main --date=raw --max-count=100 --format="%b" --no-show-signature --no-color -n 1 --
```

This gives you first the summary ("first line") of the first commit in `main`, and the body (rest of message), respectively. So I'm inclined to think this is, to some extent, expected behavior, or at least compliant with what git itself understands is the summary and the body in a commit message 😕
