### ISSUE TITLE
Destructively faulty discard behaviour

### ISSUE THREAD

**Issue by moritztim** [desktop/desktop#16406]
### The problem

I selected a bunch of lines in a newly added file and discarded them (by right clicking > discard added lines...) but only the top line was affected. I kept the same selection and right clicked > discard again and the whole file got discarded. This obviously could have been very bad, since discarding is permanent.

### Release version

`Version 3.2.0 (x64)`

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Open a freshly created (c sharp class) file in the changes menu
2. Unselect all of the lines
3. Select the top 6 lines
4. right click on the left of the file view
5. click `Discard added lines...`

### Log files

No logs of the timeframe in question found.

### Screenshots

The right click menu didn't show up in the video, but I'm clicking on `Discard added lines...`

https://user-images.githubusercontent.com/90388353/228318500-d151db4c-0942-4989-afb2-2e5234b5621d.mp4

### Additional context

If you change the selection, only the first line is affected again, it only discards everything when you discard the same selection twice.

**Comment by sergiou87** [comment]
Thanks for your report! ❤️ 

While the UX might be confusing, this is expected behavior: it doesn't take into account what you have selected (that's considered for commits, nothing else), but what you're right-clicking on.

In this case, there are two different scenarios you're running into:
1. Right clicking just one line by hovering over its line number. The context menu will say `Discard Modified Line` in singular
![2023-03-29 at 12 07](https://user-images.githubusercontent.com/1083228/228501440-6b0f0b25-4982-45fb-879f-276d04c69e76.png)
2. Right clicking on a whole code hunk by hovering over the line gutter (which highlights all lines). The context menu will say `Discard Modified Lines` in plural

https://user-images.githubusercontent.com/1083228/228502102-77e30b59-6112-41eb-a652-0911b34f30af.mov

**Comment by moritztim** [comment]
Oh wow, I've always done it this way, but apparently, I never selected multiple lines to discard
