### ISSUE TITLE
Extract commit or tag state as tarball/zipball (git archive)

### ISSUE THREAD

**Issue by gencer** [desktop/desktop#1642]
Can we get some kind of export functionality based on selected commit or tag?

For example; We may find one of the previous commit and right click on it and then export as zipball or tarball archive (just like GitHub Web does) at that state. So we can explore our code better.

**Note**: I searched zip/tar and extract words. Did not find anything yet.
**Note 2:** I did not find any **tags** tab currently. But when it implemented we can use extract feature for that too.

**Comment by niik** [comment]
Hey @gencer, it sounds to me like what you're describing is very similar to [git archive](https://git-scm.com/docs/git-archive). Would you say that is more or less what you want?

> I did not find any tags tab currently. But when it implemented we can use extract feature for that too.

We're tracking tags support in #257, please subscribe and follow along there

**Comment by gencer** [comment]
I subscribed there. Thanks!

To be more clear, Yes. I exactly featuring for `git archive`.

`git  archive -o ~/archive.zip da39a3ee5e6b4b0d3255bfef95601890afd80709`

**Comment by joshaber** [comment]
Thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I'm going to add the `future-proposal` label to this issue and close it out, so that we don't get overwhelmed with our backlog! We'll revisit these as part of our next planning session.

**Comment by billygriffin** [comment]
Hi @gencer, thanks for the suggestion! Because this isn't something we hear as a frequent part of people's workflow and because it's easily done from GitHub.com or from the CLI, I'm going to remove the `future-proposal` label here to indicate that we don't intend to support it. However, if we hear that it's becoming a pain point for people, we're happy to revisit. Thanks!
