### ISSUE TITLE
Enhancement: Amend last commit

### ISSUE THREAD

**Issue by 1pete** [desktop/desktop#1644]
### Description

Amend last commit feature is very useful and exists in many git clients, but not in GitHub Desktop.
It would be nice if we have it in GitHub Desktop too.

Current workaround is click `Undo` and commit again but I've to carefully check what I want to commit again.

### Version
**GitHub Desktop version:** 0.5.5

Thanks.

**Comment by xt0rted** [comment]
I typically commit the missed/extra changes and then rebase & squash, this would certainly speed that process up.

**Comment by joshaber** [comment]
Thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I'm going to add the `future-proposal` label to this issue and close it out, so that we don't get overwhelmed with our backlog! We'll revisit these as part of our next planning session.

**Comment by levinit** [comment]
useful function

**Comment by meyer** [comment]
@joshaber do you all accept PRs for features outside the current roadmap?

**Comment by j-f1** [comment]
@desktop/design Does this need some design 💭?

If not, feel free to go ahead, @meyer.

**Comment by shiftkey** [comment]
Please hold off on this. We haven't had a chance to evaluate these proposals, and I'm pretty sure this needs some design thought. @meyer if you have thoughts on how this should look/feel/behave feel free to share them in here as a starting point.

**Comment by DanTup** [comment]
I find myself really often committing things with the message "f" as a reminder to `rebase -i` and mark as `fixup` later. Sometimes I forget and I push these changesets :(

Would be good to see this - maybe a tickbox near the commit button for "Amend last commit" - ticking it should allow committing without entering a summary/description (or ticking it could pre-fill the previous messages if the fields are blank, for easier typo-correction).

Oh, and show a warning if the previous changeset may have been pushed ;-) (I'm not sure if Git has any equiv of Mercurial's phases?)

**Comment by JaneSmith** [comment]
For what it's worth, the three major reasons I use SourceTree instead of GitHub Desktop whenever possible are:
1. Multi-file selection (for discarding, staging, etc.).
2. Branch relationship visualisation.
3. Amend last commit.

The first is apparently being worked on already in a pull request, and hopefully will be in GitHub Desktop soon. The second one is kind of on the roadmap, although perhaps not in the form I want (a visual graph). That leaves the last one. Being able to quickly and easily amend the last commit is very useful to me.

**Comment by phuibonhoa** [comment]
I use amend all the time on Gitx and really miss it when I've tried to swap to GHD.  

They have an amend checkbox, if you check it:
  * the previous commit message shows up in the commit message box to edit
  * any changes in the previous commit are now in the staged state

Because things are by default not staged in Gitx this works well.  You can add / remove stuff as needed.  Since things default to staged on GHD, it presents a problem since it might be hard to tell what was part of the commit previous commit and what are new changes. 

<img width="1505" alt="fo_on_o" src="https://user-images.githubusercontent.com/14584/40712366-64ece9e2-63b2-11e8-95b5-fe11bc3666c8.png">

**Comment by cdmihai** [comment]
I often (several times per day) fixup the previous commits, and I use [`git commit --fixup`](https://www.raphael-brugier.com/blog/git-commit-fixup/) and `rebase -i --autosquash` to quickly do it. Having UI support for this would be really helpful. 

This is a generalization of `git commit --amend`. Rather than fixing up the latest commit, the UI client could have an option to choose an arbitrary commit to fixup. The UI could make amending the last commit the fast UI option, and then require some extra click to get to fixing up any commit.

**Comment by billygriffin** [comment]
From #5953:

> While not directly related to inter-branch rebasing described [in that issue], the fixup/amend (#1644) feature request may be a great addition to the larger rebase workflows being considered.

At the very least, could we consider re-opening that issue as part of the larger re-prioritization of the milestone?

**Comment by digitalmaster** [comment]
Amending last commit is a pretty standard part of my workflow (usually before pushing my branch). Would be awesome to be able to just "add changes to last commit".

**Comment by rsodre** [comment]
Amending is such a simple command, and so useful.
90% of times I go to terminal is to do it.
Please reconsider!

**Comment by ulgens** [comment]
Seeing the state of this issue is just sad ☹️

**Comment by taidinh-tiki** [comment]
Disappointed, make me switch back to SourceTree

**Comment by Neustradamus** [comment]
It is not solved, can you reopen this ticket?

@billygriffin has informed me in https://github.com/desktop/desktop/issues/9981 but this ticket has been closed like mine.

**Comment by billygriffin** [comment]
This is labeled future proposal as something we're still considering, so it being closed is not an indication that we're not open to supporting it. For those of you who have weighed in on this, I'd love to understand why this would be so much more useful than using "Undo," especially since this request is scoped to the last commit. Would you mind providing some examples where "Undo" isn't working and how you'd imagine this might solve a different problem or problems?

**Comment by cdmihai** [comment]
> Would you mind providing some examples where "Undo" isn't working and how you'd imagine this might solve a different problem or problems?

I prefer UI actions that are a 1-1 mapping to git features. This lessens the cognitive load for me. I don't want to understand what the difference is between the git semantics and UI semantics. Based on past experiences with UI version control clients, I don't trust commands that do not map in verbiage and semantics to the underlying tool. When there'll be a `git undo` operation, and if the UI client has the same semantics without any add-on semantics, I'll use it.

Also, personally, I use `git commit --fixup` a lot, as usually I split my work in 2-4 bigger conceptual changes, and I often have to update commits which are not the latest commit. Ideally I'd like a tool where I can easily choose which commit to fixup with my staged changes.

**Comment by Neustradamus** [comment]
@billygriffin: It is not logic to close unsolved ticket.

When the commit has been pushed, it is too late to click on "Undo" button.

I recall same that I have done in my ticket:
------------------------------------------------------------
### Describe the feature or problem you’d like to solve

Current repository -> History -> Right click on last commit:

We have not possibility to change the title and the description of the last commit.

### Proposed solution

Add the function in GitHub Desktop.

### Additional context

Do not forget the "git push -f" after the "git commit --amend".

**Comment by Neustradamus2** [comment]
A problem of communication there is ^^

@billygriffin, all steps here:

1/ We do a commit:
- https://i.ibb.co/zZM12Cs/github-screenshot-ticket-9981-and-1644-1.png

2/ After push origin:
- https://i.ibb.co/fX0kwGQ/github-screenshot-ticket-9981-and-1644-2.png

3/ Go history tab:
- https://i.ibb.co/W5pX9tx/github-screenshot-ticket-9981-and-1644-3.png

4/ Right click on last commit (it is like all commits):
- https://i.ibb.co/Tb3qpS1/github-screenshot-ticket-9981-and-1644-4.png

No amend possibility, we launch git in command line in the repository folder:
`git commit --amend`

A window appears, we change the title and the description, then we save the file, and close the window, in GitHub Desktop we have:
- https://i.ibb.co/qyRk2mC/github-screenshot-ticket-9981-and-1644-5.png

Warning do not click on "Pull origin"!

Go in command line, repository folder, and do:
`git push -f`

Now we can see in GitHub Desktop:
- https://i.ibb.co/z8qFFjT/github-screenshot-ticket-9981-and-1644-6.png

All steps are here.

Thanks in advance and for your comprehension.

**Comment by meyer** [comment]
@billygriffin here’s the amend view in Fork, the git client I’m using at the moment:

![amend view screenshot](https://user-images.githubusercontent.com/13781/84557071-a341c300-acdc-11ea-8fb1-f6baf1714aee.png)

I can stage or unstage either entire files or ranges of characters in files. It’s incredibly powerful, especially for cleaning up little bits and pieces that accidentally make it into big commits.

I suppose I could undo and redo a commit, but I’d rather just edit it.

**Comment by meyer** [comment]
@billygriffin The larger issue to me when I originally commented on this issue was that it seemed like off-roadmap outside contributions were not welcome here. I understand you all have sprints and roadmaps and all that. I understand there’s some burden of proof on an external contributor for the necessity of a feature. Gotta keep the quality bar high. I was ready to contribute this feature but I got shut down with no recourse. [Several](https://github.com/desktop/desktop/issues/3819) [times](https://github.com/desktop/desktop/issues/3820), in fact. What was I to do? Lobby for this feature to be added to the roadmap? How? I figured that’s what the issue tracker was for.

I realised that I wanted GitHub Desktop to be something that it was probably never going to be, so my solution was to find a different git GUI. Sure, it sucks that my git GUI is not the one from GitHub, the company that hosts all my projects, but I haven’t lost any sleep over that. I know opensource is weirder at big companies, so no hard feelings here. You all have a plan that’s working for zillions of people and that’s awesome. It just doesn’t work for me.

That said, I commented on this issue in 2018. Times have drastically changed and I bet GitHub Desktop has drastically changed too. I haven’t tried it in a while, so I can’t really comment on the current state of the undo flow.

**Comment by billygriffin** [comment]
@meyer Thanks for sharing what you like about the flow in Fork, I really appreciate that.

To your broader point, that’s totally fair. With such a small team, we haven’t really cracked the code on how to incorporate community contributions for larger features, and we don’t want to signal interest only then for someone to do a bunch of work and then shut it down. It’s unfortunately a tradeoff we’ve chosen to allow our developers to focus more on making steady progress on the things we’ve tried to prioritize to add the most value. But it does have a downside as you point out in not bringing as many people into our community to build this together as we might in an ideal world.

And I’m very much of the opinion that you should use whatever tools work best for you.  GitHub Desktop is not going to be the right choice for everyone, and that’s ok and I just appreciate you sharing your perspective. ❤️

**Comment by Neustradamus** [comment]
Dear all, I think that the ticket can be reopen?

Can you look all steps?

I have done an complete review of our current problem:

1/ We do a commit:
- https://i.ibb.co/zZM12Cs/github-screenshot-ticket-9981-and-1644-1.png

2/ After push origin:
- https://i.ibb.co/fX0kwGQ/github-screenshot-ticket-9981-and-1644-2.png

3/ Go history tab:
- https://i.ibb.co/W5pX9tx/github-screenshot-ticket-9981-and-1644-3.png

4/ Right click on last commit (it is like all commits):
- https://i.ibb.co/Tb3qpS1/github-screenshot-ticket-9981-and-1644-4.png

No amend possibility, we launch git in command line in the repository folder:
`git commit --amend`

A window appears, we change the title and the description, then we save the file, and close the window, in GitHub Desktop we have:
- https://i.ibb.co/qyRk2mC/github-screenshot-ticket-9981-and-1644-5.png

Warning do not click on "Pull origin"!

Go in command line, repository folder, and do:
`git push -f`

Now we can see in GitHub Desktop:
- https://i.ibb.co/z8qFFjT/github-screenshot-ticket-9981-and-1644-6.png

All steps are here.

Thanks in advance and for your comprehension.

**Comment by ithinuel** [comment]
@billygriffin 

I use a lot partial commits (picking in/out specific lines and chunks) so that I can keep my debug in place (typically printfs) while only committing the meaning full changes.

Undo loses all that selection and I have to redo everything again. It's quickly a pain to have to redo that when adding just one extra line or even just changing the commit's text.
I use gitk on linux and github desktop on the mac machine.
This feature is so crucial in my flow that I use the `git rebase -i HEAD~...` in cli instead after doing the extra commits.

**Comment by sdegutis** [comment]
Came here because I'm trying to uninstall Emacs which is only on this computer so I can use Magit, which still has two things that Github Desktop doesn't yet: interactive rebasing, and amending.

I can live without interactive rebasing, or use the CLI for those rare times I need it, but I do the same thing as @ithinuel by committing only portions of files, often leaving parts uncommitted for a while until it's done cooking. I wasn't aware Desktop has this limitation.

We are always in a constant state of working out whether to be static or dynamic, to change our workflow or our tools, so it's reasonable if I have to just change how I code, at least a little bit, for the very ideal goal of uninstalling Emacs from my computer. But surely this has to be a very easy feature?

From a UI perspective, it's an "Amend Last Commit" checkbox that, when checked, puts the last commit message up into the commit text field and textarea. From a programming perspective, when that's checked, you pass another flag. Right? Or am I missing something? I haven't read this whole thread, only the last few messages where company policy is brought up. So maybe there's other technical reasons? But surely, policy can be bypassed it if it's this simple, right?

**Comment by sdegutis** [comment]
Just glanced through the source code, and it looks like pretty typical Microsoft TypeScript code that uses React. I'm comfortable with all of these, having dealt extensively with the source code of Monaco and VS Code for previous client work. If you can point me to the files where changes would be needed, I might be able to tackle this feature next weekend.

**Comment by billygriffin** [comment]
Hi @sdegutis, thanks for the response. Because this is excluded to the last commit, I think we'd want to consider this as part of the existing "Undo" functionality and make it a more proper "Undo" that preserves the state you were in prior to making the commit. The biggest hurdle here is that the app needs to be able to recreate the state of which files were selected for the commit, and the partial elements of those files also selected.

If you want to explore the technical part of this just assuming it becomes part of the "Undo" flow, we'd love to see what that looks like.

I'm also going to reopen this to indicate that it's something that we're notionally interested in supporting.

**Comment by sdegutis** [comment]
> The biggest hurdle here is that the app needs to be able to recreate the state of which files were selected for the commit, and the partial elements of those files also selected.

One suggestion is to just make use of git's staged/unstaged idea. It's built into git, and I was actually surprised and disappointed when I tried Desktop the other day and realized it used its own internal state for this.

At which point, undo becomes a simple git reset command that probably just does `git reset --soft` or something.

Having the Amend checkbox be separate than Undo also has the UX advantage of not making me have to scan all my previous lines of commit just to find my current changes that I wanted to add to it.

And from a separate UX perspective, it makes it harder to use Desktop to change/discard just my current changes that I was thinking of amending, if I change my mind, since now it's mungled into the old commit again after clicking Undo.

**Comment by billygriffin** [comment]
I appreciate that but it was an intentional choice not to mess with the index until commit time, and we're likely not going to change that core concept of the app just to support this feature. So we'd like for this implementation to align with the existing design of the app.

**Comment by sdegutis** [comment]
Strange design choice, but fair to stick with existing decisions. Can you point me to the discussions/rationale that led to this choice? I'm very curious how that could have been decided on, what kind of benefits overrode the obvious problems.

**Comment by billygriffin** [comment]
@sdegutis Here's some historical context on staging: https://github.com/desktop/desktop/issues/4408#issuecomment-379527584

But as I mentioned, we're not planning to revisit that decision anytime soon and this issue is unrelated to that. Please let me know if you'd like to look into exploring the technical aspects of preserving the state you were in prior to a commit as part of "Undo."

**Comment by sdegutis** [comment]
Thanks for the link, and sure.

**Comment by sdegutis** [comment]
I think there is a lot of value in this feature, however it is implemented.

That said, I'm less confident it'll be as quick as I estimated before, knowing that reinventing portions of git inside the app is potentially required.

But more importantly, I'm less enthusiastic about helping to improve what I now see is a git client whose caveats show that it favors non-technical users, which mostly excludes me from its target audience.

**Comment by billygriffin** [comment]
That's totally fine @sdegutis, no worries if you'd prefer not to work on it. GitHub Desktop is used daily by a ton of people, both technical and non-technical, but it's definitely a more opinionated design, and that isn't always going to align with the preferences of everyone. We genuinely want people to use the tools that work best for them to build awesome stuff on GitHub.

**Comment by sdegutis** [comment]
Like I said, I'm not opposed to working on it, I'm just not as enthusiastic or confident as before. And I'm not entirely outside the target audience, either, as I'm so far using it in place of Magit with acceptable success.

But I'm still convinced your design decision doesn't even help your own goal. If you compare the outcomes of both sides of the decision, non-technical users have no disadvantage to the git index being changed invisibly behind the scenes for them, and technical users have the ability for Github Desktop to work in conjunction with other apps, e.g. Terminal or VS Code.

That's the only reason I'm still mentioning this. But now that I think I've explained it as clearly as I can both here and in #4408 , I feel comfortable dropping the topic. Thanks for your time and patience in reading my feedback and communicating about these questions and concerns.

**Comment by rsodre** [comment]
> Hi @sdegutis, thanks for the response. Because this is excluded to the last commit, I think we'd want to consider this as part of the existing "Undo" functionality and make it a more proper "Undo" that preserves the state you were in prior to making the commit. 

I think Amend and Undo are two completely different things. By undoing, I understand to erase the last commit, there's a git command for that (git reset), which could also be supported. That's good!

But Amend is used to add something else to the previous commit. I often commit 10 files, and while working on the next feature, I have already 10 more files edited, and find something would fit better on the last commit. Amend allows me to just insert that one small fix to it. If I undo the last commit just for that, now I have 10 previously commited files with 10 new ones, all on the same place. I've done that, and that's chaos, please don't mix those two concepts!

I understand having an Undo feature is good for people uninitiated with git, but don't agree with this approach. Instead of creating a new workflow and inserting git concepts in it, we should try to make already stablished git concepts and workflows user-friendly. Having separated Undo and Amend make things clearer for experienced users, without over-complicate things. Let new users learn git, easily, without noticing!

**Comment by sdegutis** [comment]
> Let new users learn git, easily, without noticing!

In fact, one cool feature would be to have hover-tooltips that show the exact command a button would perform behind the scenes, so users can learn how to do the same thing with CLI if ever needed.

**Comment by sdegutis** [comment]
After trying out Github Desktop for a week or two, I'm convinced I'm not part of the target audience, and given the conflation of high-level and low-level concepts, I'm not sure who the target audience is. But in any case, I have to unfortunately withdraw my offer to help with this app. But it will be interesting to see how this app sparks and encourages competition in Git GUIs.

**Comment by rakhmanov** [comment]
I think it cold be done elegantly by adding a button chevron on the Commit button.
If you think it is still will confuse a user, make those options enabled through configuration with something like "enable advance commit options" which will enable the chevron with drop down menu on the commit button which can house additional options like "amend previous commit"

**Comment by goyalyashpal** [comment]
Moving over my input from #12283 

---
### Describe the feature or problem you’d like to solve

Sometimes a bad change in local repo might be mistakenely committed. 
To avoid them being pushed, currently, it seems that only option is to delete the repository. Which feels like a nuclear option imo.

### Proposed solution

Ability to delete/remove local non-pushed commits

How will it benefit Desktop and its users?

In the above problem, this will be a life savour if there is big sized project.

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

---
For ux suggestion:

1. it slips from the view. as it seems to be sticking in the ui boundaries. the padding from bottom can be improved to make it more vertically center aligned.
![gimp-2 10_BIYUlegY6l](https://user-images.githubusercontent.com/19423063/119547186-6cac6d80-bdb2-11eb-801a-b7c3c3a18594.png)

2. views on giving the undo button there?? 
![GitHubDesktop_T7VvfuY6Jv](https://user-images.githubusercontent.com/19423063/119545749-c90e8d80-bdb0-11eb-9437-1217bf162252.png)

---
also, the undo-ing doesnt work well in case there are commits after the wrong commit.

**Comment by VorTechnix** [comment]
> 
> 
> ...GitHub Desktop is used daily by a ton of people, both technical and non-technical, but it's definitely a more opinionated design, and that isn't always going to align with the preferences of everyone. We genuinely want people to use the tools that work best for them to build awesome stuff on GitHub.

I stumbled on this issue because i found myself needing this feature (amend) this morning. As someone who started using Desktop as a non-technical user, having become a technical user over time I find it sad that the more I learn about "real" git the more I grow out of Desktop.

In any case thanks to the developers for making Desktop, it really served me well as a new GitHub user. Not going to lie I'm off to look for alternative now but I'll try to keep checking back for when this feature (and hopefully interactive rebasing) are added.

**Comment by sergiou87** [comment]
Thanks for your feedback!

In case you're interested, we're actively working on adding "amend" to the app: https://github.com/desktop/desktop/pull/12353

And regarding interactive rebase, squashing is already available in beta (#12235) and reordering commits will be Soon™ (#12299).

**Comment by VorTechnix** [comment]
Thanks for the heads up and for your work on this.
