### ISSUE TITLE
Renaming Branch leaves stash behind in non-existing branch

### ISSUE THREAD

**Issue by Nucs** [desktop/desktop#16442]
### The problem

When having a stash (through the client) and renaming current branch, the stash stays under the old branch.
The old branch no longer exists and unless handled correctly, the stashed changes can be lost.

### Release version

3.2.0

### Operating system

Windows 10

### Steps to reproduce the behavior

Create a branch, do not publish it
Introduce changes, stash them
Rename branch.
You no longer have stashed changes

**Comment by niik** [comment]
Hey @Nucs, thanks for reaching out. I agree this should be considered a bug and I'll mark it as such! Fixing this will require some thinking since we rely on the stash reflog message to determine which stashes was created by desktop and to which branch they belong and there's no good standardised way of manipulating (beyond adding and pruning) a reflog in Git today. We may have to resort to recreating the stash and dropping the old one 🤔

**Comment by steveward** [comment]
Related issue: https://github.com/desktop/desktop/issues/7283. @Nucs we do show a warning on branch renames that contain a stash -- did you notice that when renaming? We have had a few reports about this behavior over the years so I'm trying to determine if users aren't catching the warning.

**Comment by Nucs** [comment]
@steveward I missed it, a prompt confirmation would've been unmissable.

**Comment by Tantaia111** [comment]
Hfk
