### ISSUE TITLE
GitHub Desktop won't start on Windows. At all.

### ISSUE THREAD

**Issue by AdasBadass** [desktop/desktop#16458]
### The problem

This has been going on for a few weeks now and even after restarting my computer it just won't work. I can try to start it as many times as I want, absolutely nothing happens.

### Release version

3.0.2

### Operating system

Windows 10 Home

**Comment by steveward** [comment]
@AdasBadass thanks for the report. Just to confirm -- are you seeing a white screen or anything on startup?

Could you share the log file from GitHub Desktop so that I could get see if anything useful is being shown there?
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue. 

If you would like to try a fresh installation you can follow these steps:

1. Close GitHub Desktop (you may need to force quit an existing background process if the app is running but not visible)
2. Open File Explorer
3. Go to `%LocalAppData%` and delete the `GitHubDesktop` directory
4. Go to `%AppData%` and delete the `GitHub Desktop` directory
5. Reinstall GitHub Desktop from http://desktop.github.com

Let me know if that helps at all.

**Comment by AdasBadass** [comment]
@steveward Thanks, I've just checked the AppData directory and noticed there are sub-dirs with various versions. My shortcut was apparently linked to the wrong version for some reason. It now works.

**Comment by vytautas-palukaitis** [comment]
> @steveward Thanks, I've just checked the AppData directory and noticed there are sub-dirs with various versions. My shortcut was apparently linked to the wrong version for some reason. It now works.

If anyone else has this issue I can confirm that the method which @steveward suggested worked for me as well. All I needed to do was change my shortcut to run from app-3.3.14 directory and not app-3.3.15 (it might have been corrupted)

**Comment by Haseeb1424** [comment]
I've found @steveward's method to be effective in resolving the issue. To rectify the problem, I located the corrupted version in the AppData directory and verified the correct version. Subsequently, I removed the corrupted instance. It's worth noting that even the latest version of GitHub Desktop was affected by corruption.

**Comment by KimSangWoo1** [comment]
In my case, modifying the version path did not solve the problem, but when I just ran the GithubDesktop installation, the previous versions were automatically deleted and executed normally.

**Comment by cnfan** [comment]
Hi,everyone.I had the same problem and I had solve it.The steps are:
1. Uninstall Git,Github CLI and Github Desktop from windows system.
2. Delete '%AppData%/GitHub Desktop' and '%LocalAppData%/Github Desktop'.(I think this step maybe not necessary)
3. Then I install [Github Desktop](https://apps.microsoft.com/detail/XPFFZHJFTHG8VQ?ocid=pdpshare) from Microsoft Store.(This is the key step.If you install from the GitHubDesktopSetup-x64.exe package,it will not work.)
4. Then restart your computer.(Maybe not necessary)
