### ISSUE TITLE
Unable to publish respositery

### ISSUE THREAD

**Issue by gautam0341** [desktop/desktop#16469]
It shows require authentication and i am unable to publish respositery

**Comment by steveward** [comment]
Thanks for the report @gautam0341. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
