### ISSUE TITLE
Repositories not showing

### ISSUE THREAD

**Issue by Kirito139** [desktop/desktop#16544]
### The problem

I created a new private repo on GitHub recently, and was wanting to manage it on GitHub desktop. However, when I opened the app, the repository was nowhere to be seen. I can't figure out a way to add it other than cloning it, please help!

### Release version

Version 2.9.12

### Operating system

macOS 13.2.1

### Steps to reproduce the behavior

1. create a new repository on the github website. mine was private
2. open the github desktop application
3. open the repository list

### Log files

[2023-04-17.desktop.production.log](https://github.com/desktop/desktop/files/11246008/2023-04-17.desktop.production.log)

### Screenshots

![Screenshot 2023-04-16 at 8 48 11 PM](https://user-images.githubusercontent.com/99382674/232373430-0e51f457-43ed-463f-9270-f2bee90ecef3.png)
![Screenshot 2023-04-16 at 8 49 15 PM](https://user-images.githubusercontent.com/99382674/232373543-55da30fd-e6bf-4176-bd3e-17e5be4e322b.png)

**Comment by tidy-dev** [comment]
Hi @Kirito139! This is expected behavior. To add a repository to your list, you must clone it. GitHub Desktop does not automatically clone all your GitHub repos.  This gives users control over what is downloaded to their machines.

**Comment by Kirito139** [comment]
wouldn't that mean the desktop version would be out of sync with the website version, since cloning only copies it?

**Comment by tidy-dev** [comment]
Yep. GitHub Desktop is a gui for Git version control software - otherwise accessed via the command line. But, in essence, you have your repository hosted remotely and then you and anyone you share it with (team, collaborators) may make a clone of the remote repository. From there, you can use commands like `fetch` and `pull` to sync your local copy with your remote. Inversely, you may make commits on your local copy and need to `push` them to upload them to your remote repository. 

Here is a [pretty good overview of git](https://www.freecodecamp.org/news/what-is-git-learn-git-version-control/) and [documentation on repositories on GitHub ](https://docs.github.com/en/repositories)if you would like to learn more about how version control software works.

**Comment by Kirito139** [comment]
ok thanks!
