### ISSUE TITLE
Can't Discard Change

### ISSUE THREAD

**Issue by EGMetaverse** [desktop/desktop#16590]
### The problem

I tried to discard all changes in my project but it doesn't do anything. Also no error.

### Release version

3.2.1

### Operating system

Windows 10

**Comment by sergiou87** [comment]
@EGMetaverse 👋  Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
