### ISSUE TITLE
Pull in a submodule doesn't finish if there is a conflict

### ISSUE THREAD

**Issue by devel4848** [desktop/desktop#16642]
### The problem

Pulling the remote inside a submodule, with conflicting changes on the remote and on the submodule, doesn't finish.
The usual "Resolve conflict" window doesn't open. GitHub Desktop shows that there is a file in a conflict state, but gives no way for the user to mark the conflict as solved and finish the pull operation. From the command line, the submodule appears to be in the middle of a merge or of a rebase operation.
Tested with `git config pull.rebase false` (pull with merge) and `git config pull.rebase true` (pull with rebase),  same issue.

If there are concurrent changes with no conflict in the remote and the submodule, the pull with merge or rebase works as expected.

### Release version

Version 3.2.2 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1. create a non empty repo `repo1`
2. create a 2nd repo, `repo2`, with `repo1` as a submodule
3. make a change to a file in `repo1` and commit the change in `repo1`
4. change the same file in the submodule `repo2/repo1`, and commit the change in the submodule
5. from the  `repo2/repo1` submodule, trigger a "Pull"

**Comment by steveward** [comment]
Thanks for reporting this @devel4848. Can you share the log file from GitHub Desktop so that we can take a look at what's happening in the app?

To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`. The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue. 

 I'll also take a look and see if I can reproduce this -- thanks for the steps.
