### ISSUE TITLE
Before doing an operation that could lose changes ask if there are unsaved changes

### ISSUE THREAD

**Issue by Giszpenc** [desktop/desktop#16641]
### The feature request

User is doing some work and has unsaved changes in Visual Studio.
User wants to merge so proceeds to Stash.
User goes to a command line and does a git merge (because refresh does not refresh when parent branch is not Develop which is also annoying).
User does a Restore All from Stash.
User finds his pending changes gone.

### Proposed solution

Before doing the Stash (and other operations that could cause trouble like switch branch and probably a bunch of others) ask the user if they are sure as they will lose any pending changes.   For all the purists, perhaps there should be a don't ask again checkbox.

If you tell me that user is a git (as in the term before the tool came out) and should save first, I would agree.  But speaking from experience, when working late under pressure, one can lose track of some details such as a tiny little asterisk at the top of a file.

Alternatively, the underlying Git could have an event that tools can subscribe to that is triggered before an operation like stash that can result in lost work.  It would then be the responsibility of the tool (like Visual Studio) to stop the operation and ask the user to save.  This is probably more correct as it would handle cases where user is making changes such as stash from the command line.  However, I am not going to figure out where to report an enhancement request directly on Git.  Feel free to open a feature request there.

**Comment by EarthDweller** [comment]
Delete many changes...

Better to use
`git stash save --include-untracked`

**Comment by EarthDweller** [comment]
@tidy-dev
(T＿T)

**Comment by tidy-dev** [comment]
@Giszpenc If I understood correctly,

You: 
1. opened a file in your editing tool and made some changes.
2. did not hit save, thus the file did not show as a change in GitHub Desktop (in others GitHub Desktop was unaware of this change)
3. Stashed and some operation
4. Popped stash
5. Returned to editing tool to see changes you made overwrittten.

If this is case, it is not something we are inclined to forewarn users about as it is their interaction with another tool. That tool should be one to handle what happens when something attempts to overwrite a file that is open in that tool. For example, I know in Visual Studio Code that if I do this type of action, it will show my pending changes still yet in the editor but if I attempt to save it has a popup to let me know the file has since changed and doing so will overwrite the new file.


Other notes:
- `git stash save --include-untracked` is specifying staged versus not staged. This issue is highlighting a change that is not even saved to file yet and therefore is not detectable to stage.

**Comment by EarthDweller** [comment]
@tidy-dev I kill my changes that way:

1. Was working with files in repo
2. Uncheck all files
3. Check some files to commit with diff messages
4. Realized, that I need to merge with /rebase to/ another branch
5. Pressed «Choose a branch to merge into [BRANCH_NAME]»
6. I choosed branch and pressed «Create a merge commit»
7. GitHub Desktop asked me:
> Unable to merge when changes are present on your branch. The following files would be overwritten:
> [list of files]
> You can stash your changes now and recover them afterwards
> {Stash changes and continue} {Close}
9. I pressed «Stash changes and continue»
10. Then GitHub Desktop merged with /rebased to/ another branch
11. Then I go to «Stashed Changes» option and pressed «Restore»
12. But restored not all, only ~previously «checked» changes~... no, I don't know why not all files were restored

**Comment by tidy-dev** [comment]
Ah @EarthDweller  This sounds like a different issue. (Unless I completely misunderstood the OP) Would you mind opening another issue to track that scenario. I believe you are right that it should stash All not just checked or at the very least give the user the option.

**Comment by EarthDweller** [comment]
> Ah @EarthDweller This sounds like a different issue. (Unless I completely misunderstood the OP) Would you mind opening another issue to track that scenario. I believe you are right that it should stash All not just checked or at the very least give the user the option.

https://github.com/desktop/desktop/issues/17393
@tidy-dev That way?

**Comment by tidy-dev** [comment]
Yep. Thank you!

**Comment by AHMED22377** [comment]
@          Ah @EarthDweller  This sounds like a different issue. (Unless I completely misunderstood the OP) Would you mind opening another issue to track that scenario. I believe you are right that it should stash All not just checked or at the very least give the user the option.

**Comment by EarthDweller** [comment]
@AHMED22377 , you want from me to text some comment?
