### ISSUE TITLE
Built-in auto-updater doesn't see new 3.2.3 version

### ISSUE THREAD

**Issue by rakleed** [desktop/desktop#16661]
### The problem

The built-in auto-updater does not see the new 3.2.3 version, although judging by [the release notes](https://desktop.github.com/release-notes/), it has already been available since May 3rd.

### Release version

Version 3.2.2 (arm64)

### Operating system

macOS 13.3.1 (a) (22E772610a)

### Steps to reproduce the behavior

1. Install GitHub Desktop 3.2.2
2. Open `About GitHub Desktop` menu
3. Click `Check for Updates`

### Log files

[2023-05-07.desktop.production.log](https://github.com/desktop/desktop/files/11415550/2023-05-07.desktop.production.log)

### Screenshots

![Screenshot 2023-05-07 at 19 58 19](https://user-images.githubusercontent.com/19418601/236691582-d9cd32f3-8e3b-45ad-a340-40944d8f08ff.png)

### Additional context

Previously, a new version also appeared on the site, but the built-in auto-updater usually updated the app within 1–2 days, but here it has not seen the update for more than 4 days.

And why is the new version available late in the built-in auto-updater? If you are using a staged update, then why?

**Comment by sergiou87** [comment]
Hello! Yes: it's staged update. We manually increase the % of users that get the update depending on the importance of the update and reports we get, that's why it sometimes takes longer than others. Also, what users get the update for every % is random in every update.

In any case, if everything looks ok we will increase it to 100% today.

Meanwhile if you're in a hurry to get the latest updates, you can <kbd>Option</kbd> + Click on the `Check for Updates` button will bypass the staged update and get you the latest version.

I hope that helps!

**Comment by rakleed** [comment]
I can understand a staged update for users who don't manually check for an update and are waiting for an automatic update in the background. But if I have already entered the update section and manually clicked `Check for Updates`, then why don't you offer to download the new version in this case? Why only when pressing `Option` at the same time?

**Comment by battsteam** [comment]
someone hacked me

________________________________

**Comment by rakleed** [comment]
@sergiou87 ping

**Comment by sergiou87** [comment]
Hey @rakleed ! 👋 

So we do this because we don't want people to update just yet. The option + click  is just an "escape hatch".
