### ISSUE TITLE
Make Recent repos configurable

### ISSUE THREAD

**Issue by cehardin** [desktop/desktop#16686]
### The feature request

It is very limiting to only have 3 recent repos show up. I would like 5 to 10 of them to show up there. Better yet, make it configurable. :-)

### Proposed solution

For users with large numbers of micro-service repos, it's handy to have more recent repos available.

**Comment by steveward** [comment]
Thanks for the feedback @cehardin.

We avoid trying to add more custom settings when possible, and in the future if we were to revisit this it would likely be more for the purpose of providing an option of pinning repositories, since that has been another often requested feature (see https://github.com/desktop/desktop/issues/8183). For now, however, we have no plans on changing the repository list, as we have other priorities and this is a small team with very limited capacity.

I'm sorry that I don't have better news at this time.
