### ISSUE TITLE
i have a big problem

### ISSUE THREAD

**Issue by miku111** [desktop/desktop#16728]
### The problem

i use desktop client ,and login my account ,then add a exist local project to my account , but the commiter name is not my name

### Release version

3.2.3 

### Operating system

windows 11 

### Screenshots

<img width="565" alt="屏幕截图 2023-05-20 002257" src="https://github.com/desktop/desktop/assets/84562264/00d55fb9-b2c5-4e6a-915a-6a032bf712b3">
<img width="713" alt="屏幕截图 2023-05-20 002239" src="https://github.com/desktop/desktop/assets/84562264/80366563-92f3-4ff8-9125-2e09ca73eb1b">

**Comment by sergiou87** [comment]
This usually happens because the email used for the commits is not associated with your GitHub account.

Do you have this warning in the commit area? If so, clicking on it should help to fix the issue 😄 

![2023-05-19 at 18 35](https://github.com/desktop/desktop/assets/1083228/007a11c9-e3ca-4f93-8779-cc6a12c00dec)
