### ISSUE TITLE
Problem with git desktop: 

### ISSUE THREAD

**Issue by udnie** [desktop/desktop#16733]
The git desktop shows I've uncommitted files and won't refresh my local staging folder, I think it's what is referred to as a local repo.  It's the folder I copy my code to when ready for final testing and it's the one that gets pushed to github.
How do I refresh it to the current state and make these commits go away?

**Comment by sergiou87** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

If you don't know how to do this, you can close this issue and [create a new one](https://github.com/desktop/desktop/issues/new?assignees=&labels=&projects=&template=bug_report.yaml).

Thanks for understanding and meeting us half way 😀
