### ISSUE TITLE
Unable to Sign in Via Browser to Github Desktop

### ISSUE THREAD

**Issue by Zaryab13** [desktop/desktop#16732]
### The problem

I am trying to log in into my github via browser inside Github Desktop but for some reason it is loading infinitely.

![git](https://github.com/desktop/desktop/assets/93703454/15846722-1a29-46a1-8526-bd6b933c5b67)

### Release version

3.2.3

### Operating system

Window 11

### Steps to reproduce the behavior

1. Go to file.
2. Open settings
3. Sign in via browser
4. when redirected back from browser to App.
5. See infinite scrolling of pre-loader and acc do not log in.

### Screenshots

![git](https://github.com/desktop/desktop/assets/93703454/1069f907-d465-4b30-aff1-30e3b3ce204a)

**Comment by sergiou87** [comment]
@Zaryab13  Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by Darian2604** [comment]
I have the same issue how can I sign in?
