### ISSUE TITLE
Fetching origin hang on

### ISSUE THREAD

**Issue by horuszhao** [desktop/desktop#16744]
### The problem

because some reason(network or git server issue) , it's hang on when fetching origin, must restart  desktop to fetch again.
<img width="257" alt="image" src="https://github.com/desktop/desktop/assets/4836089/7a7c7fb7-483f-44c8-b0fa-f0f2600196bf">

### Release version

Version 3.2.3 (x64)

### Operating system

mac os

**Comment by sergiou87** [comment]
@horuszhao  Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
