### ISSUE TITLE
Add local repository not working

### ISSUE THREAD

**Issue by Bikeman868** [desktop/desktop#16767]
### The problem

I started working on something that I thought would be throwaway, so did not add it to GitHub initially, but now I want to open source it. I already used Git locally to see diffs and rollback changes as I worked.

I opened Github Desktop and chose File | Add local repository, and completed the dialogs. Now I have a "Publish" button, but when I click it an error box pops up saying "fatal: no path specified; see 'git help pull' for valid url syntax"

Executing the command `git remote -vv` produces:
```
<new>    (fetch)
<new>    (push) 
```

### Release version

3.2.3 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Create a Git repository locally using `git init`.
2. Commit some changes to the master branch.
3. Open Github Desktop
4. Choose File | Add local repository
5. Choose the repo from step 1
6. Click on the "Publish" button

### Screenshots

![image](https://github.com/desktop/desktop/assets/5679259/b64b918b-54b5-4971-818b-a24f266d4f75)

**Comment by sergiou87** [comment]
Weird, I did not see that behavior. In my case I see a `Publish REPOSITORY` button (not `Publish BRANCH`), and it worked as expected creating the repo on my GitHub account and immediately after, pushing the branch 🤔 

Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by Bikeman868** [comment]
[2023-05-24.desktop.production.log](https://github.com/desktop/desktop/files/11580948/2023-05-24.desktop.production.log)

**Comment by sergiou87** [comment]
Thank you! I think the problem is related to that `<new>` that I don't know it it make it there. Try doing this from the command line `git remote remove "<new>"` and then try to Publish again from GitHub Desktop. Hopefully that helps 🤞

**Comment by Bikeman868** [comment]
I fixed this problem right away by resorting to the command line and
setting up the remote correctly.
Only reporting the issue to improve the product.
Thanks for looking into it.
