### ISSUE TITLE
Super slow in WSL1 and WLS2 while VS Code is blazing fast

### ISSUE THREAD

**Issue by xairoo** [desktop/desktop#16780]
### The problem

Haven't used Desktop for a few month.

A repo is listed as "Publish branch" when I start GitHub Desktop. (Super small repo with about 30 files that is stored in WSL2)

"Publish branch" will gone after about 30 seconds and is getting replaced with "Fetch origin".
When I click "Fetch origin" it will take ~30 seconds.
File changes take also long, ~30 seconds until they are visible in Desktop.
This happens only to repos that are stored in WSL2 and WSL1 (I converted it to test it).
When changing the same repo within a windows partition it works totally normal and fast.

Doing all the same with VS Code (connected to WSL) is like it should work: nearly instant.
Tested this also with the same repo on a windows partition and within WSL2.

I had the same problem about 1 month ago on my other Windows 11 PC (one at home, one at work).
Both have totally different hardware and both have the same Windows versions.

The log are totally fine.
CPU consumption is really low.

Maybe it's related to https://github.com/desktop/desktop/issues/16780.

### Release version

3.2.3 (x64), 3.2.2-beta2

### Operating system

Windows 11 (10.0.22621 Build 22621)

**Comment by xairoo** [comment]
It's too long ago and I forgot it. But the problem is gone on my other PC. Haven't used GitHub Desktop for a while on that system until now.

I know that I have uninstalled Docker Desktop. But today I installed it again - without any problems. Docker Desktop creates two new WSL instances.

But no idea why it still doesn't work on the second one 🤔

Anyway, both systems have the same Windows build/updates and also the same GitHub Desktop version.

**Comment by steveward** [comment]
@xairoo thanks for the issue. I'll take a look and see if I can reproduce any issues like this on my Windows machine. 

>Maybe it's related to https://github.com/desktop/desktop/issues/16780.

Was there a different issue you wanted to reference that was related?

It may also be helpful if you could share the log file so that we could take a look and see the timing of specific Git operation. Thanks!

**Comment by battsteam** [comment]
I don’t have my computer right now won’t have it for a week or two

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by xairoo** [comment]
@steveward vacation time, sorry for the delay and sorry for that wrong link, can't find it in my history.

Anyway...
Just updated to 3.2.4-beta1 without a change.
VS Code works still instantly (also when I update the file with a separate program or through the shell).
I also tried `--disable-gpu --disable-software-rasterizer` without an improvement.

[2023-06-14.desktop.beta.log](https://github.com/desktop/desktop/files/11745876/2023-06-14.desktop.beta.log)

As you can see the log is fine (any way to enable debug logging?).
Also it doesn't show the crazy delay (the end of the operation isn't logged).

Btw. @battsteam doesn't belong to me.

**Comment by xairoo** [comment]
It was related to Avira. I had to disable scanning network drives and shares, that fixed it. Will be slow again if enabled, double checked it. Anyway, now it works. Also it works fine with Bitdefender.
Sorry! Never had any trouble with anti virus software since Windows NT or so.

**Comment by saumyaborwankar** [comment]
I think I'm still having this issue, where it takes an average of ~2 seconds for every git log and its very very slow. I have attached my logs. Let me know if you need more info from me.
[2024-03-11.desktop.production.log](https://github.com/desktop/desktop/files/14564130/2024-03-11.desktop.production.log)

**Comment by aleixrodriala** [comment]
I had the exact same experience, VS Code with the Remote WSL extension is instant but Desktop takes 30+ seconds for everything. I ended up building a fork that takes the same approach as VS Code — running things natively inside WSL instead of going through 9P: [GithubDesktopWSL](https://github.com/aleixrodriala/GithubDesktopWSL)

| Operation | Fork | Official | Speedup |
|-----------|-----:|---------:|--------:|
| git status | 2 ms | 43 ms | **20x** |
| git log | 2 ms | 41 ms | **24x** |
| Open repo | 16 ms | 173 ms | **11x** |

Installs side-by-side with official Desktop and auto-syncs with upstream releases. Would love feedback if anyone tries it!
