### ISSUE TITLE
Committing to main

### ISSUE THREAD

**Issue by Bendeee** [desktop/desktop#16783]
### The problem

Hey, I have had issues with losing a folder with loads of python files that are need for my school and self projects. Out of nowhere it disappeared. It was named "py". Now I have problems with commiting five folders with again, loads of files ( html,c#,python). 
The error message I get is "Your branch is up to date with Main2, "untracked files" than it lists my folder names ", reason why it's named Main2 is because I tried fixing it with another main but still no success. 

![Képernyőkép 2023-05-25 182723](https://github.com/desktop/desktop/assets/112851260/90f833ba-774d-48d8-806a-5d78193349ef)

Then, when I click on the folder where I commit to main, it says the folders are empty. Which is not true beacuse there are files in them.
![Képernyőkép 2023-05-25 182937](https://github.com/desktop/desktop/assets/112851260/650416eb-ce2e-4176-868c-c64f44808ee2)

### Release version

3.2.3 x64

### Operating system

Windows 11

**Comment by steveward** [comment]
@Bendeee thanks for the issue. Git doesn't track folders, it tracks files, so those items you see in the changes list are being detected as files. If there were files inside the folders then they would all show up like "<foldername>/<filename.js>".

I'm not quite sure what's going on here based on the screenshot -- could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`. The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
