### ISSUE TITLE
Error when pushing to origin: "The remote disconnected. Check your Internet connection and try again."

### ISSUE THREAD

**Issue by CodeyWinslow** [desktop/desktop#16797]
### The problem

I have a single commit locally that amounts to about 2.6GB when compressed, but when I try to push to the remote repo, it always fails. According to the log, it gets to 100% write progress before failing because "the remote end hung up unexpectedly."

### Release version

Version 3.2.3

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Use cloned repo of a Unity project
2. Add art packages to project ~6GB
3. Commit locally using GitHub Desktop
4. Push to origin
5. Observe error

### Log files

[2023-05-28.desktop.production.log](https://github.com/desktop/desktop/files/11583342/2023-05-28.desktop.production.log)

### Additional context

I added a couple art packages to my Unity project, the commit for which is the target of this issue. No individual file is very large (>100MB), so I haven't tried using Git LFS

**Comment by steveward** [comment]
@CodeyWinslow thanks for the issue. Unfortunately with larger pushes like that there's a high possibility of a timeout, even if the individual files aren't that big. I would recommend setting up Git LFS if possible since it's the recommended route when working with Unity projects.

You could try using the command line to push a subset of commits by using the following command:

`git push origin commit-SHA:branch`

For example, if you have three commits A (4d3bf9) - B (e55b5f) - C (c109e0) and wanted to push A and B to your `main` branch you would run this command:

`git push origin e55b5f:main`

You could also try switching to using SSH to see if you have better success. See [this guide](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent) for setting up a new SSH key.

You will also need to change the URL of your repository to use SSH. You can do this in GitHub Desktop by going to `Repository` > `Repository Settings` > `Remote`. You will want the URL to look like `git@github.com:<user>/<repo>.git`. 

I hope that helps! I'm going to close this out as this is a connection problem and not a specific issue with GitHub Desktop, but let me know if you have any further questions.
