### ISSUE TITLE
History list don't display TAG after Squash

### ISSUE THREAD

**Issue by SuperSoldado** [desktop/desktop#16817]
### The problem

Describe the bug
History list don't show Tags if Tagged commit is later squashed

Version & OS
Version 3.2.3 (x64) on Windows 10

Steps to reproduce the behavior
Commit "MyCommitStuff_1" in master
In "History" list, right click over and pick "Create Tag..." and commit
Commit "MyCommitStuff_2" in master
Squash MyCommitStuff_2 over MyCommitStuff_1
After this the Tag is lost in "History"

Expected behavior
Squash other commits over a Tagged commit should maintain the Tag

Actual behavior
The Tag is not displayed in History

Screenshots
![Untitled](https://github.com/desktop/desktop/assets/38852373/a3ec7a45-af49-4d16-881d-3a00f22486d7)

### Release version

3.2.3 x64

### Operating system

windows 10

**Comment by sergiou87** [comment]
Hi @SuperSoldado ! 👋 

I'm afraid that's how tags work on git. If you check, the commit you tagged has changed its SHA after the squash. That's because it's **a new commit**. The tag still belongs to the old commit (which still exists).

You will need to delete the existing tag (both locally and remotely, if you want), and create it again on the squashed commit.

I hope that helps!
