### ISSUE TITLE
Push to origin is stuck

### ISSUE THREAD

**Issue by alessandro-ceccarelli** [desktop/desktop#16816]
### The problem

I'm using Github desktop to push to repository. It seems stuck while adding a 4.6MB file.

### Release version

Version 3.2.3 (arm64)

### Operating system

Mac M2 on Ventura 13.2.1 (22D68)

### Screenshots

<img width="304" alt="Screenshot 2023-06-01 alle 01 03 36" src="https://github.com/desktop/desktop/assets/49490430/62ca6134-00c1-4445-933d-8617f916a30b">

**Comment by steveward** [comment]
Thanks for the report @alessandro-ceccarelli. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
