### ISSUE TITLE
Facing issue to commit the changes from github desktop

### ISSUE THREAD

**Issue by Amrutha-KK** [desktop/desktop#16820]
Facing issue to commit the changes from github desktop

**Comment by steveward** [comment]
Thanks for the report @Amrutha-KK. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
