### ISSUE TITLE
push to origin write speed is capped at 1-2mbps

### ISSUE THREAD

**Issue by SpyderDoesStuff** [desktop/desktop#16828]
### The problem

I'm trying to publish my repo to GitHub, but the write speed seems to be capped at 1-2mbps. upon completing the upload, it gives me an error stating "the remote disconnected. check your internet connection and try again." after seeing this, i immediately tested my internet speed and it was at 100+mbps. this is the second time I've had this issue since this update released and I hope it gets fixed soon!

### Release version

3.2.3 (64x)

### Operating system

windows 11 22H2

### Steps to reproduce the behavior

1: create new repo
2: add files to the repo
3: commit changes
4: push to origin

### Log files

[2023-06-03.desktop.production.log](https://github.com/desktop/desktop/files/11644255/2023-06-03.desktop.production.log)

### Screenshots

![Screenshot 2023-06-03 161144](https://github.com/desktop/desktop/assets/116987090/b1c2d157-643b-4d92-b345-c8e2e6f1361c)
![Screenshot 2023-06-03 161651](https://github.com/desktop/desktop/assets/116987090/c52a84ec-2f43-4e20-b84d-384f54c3999a)

### Additional context

it seems to uncap the write speed when disconnecting the device from the internet and then reconnecting it. but i still receive the same error when it finished the upload

**Comment by steveward** [comment]
@Venage5603 thanks for the issue. Network issues are tricky to diagnose, and there isn't much we can do from our end about them since the underlying Git operations are failing. You can test your GitHub connection [here](https://github-debug.com/).

If you're using Git LFS with a large repository you can try using this config option to increase the timeout:

`git config lfs.activitytimeout 30`

This config sets the maximum time in seconds that the HTTP client will wait for the next TCP read or write. The default is 10 seconds.

There are also some HTTP timeout config operations that may help, or at lease provide additional diagnosis about the timeout. One user previously had success with these commands:

`git config --global http.lowSpeedLimit 1000`
`git config --global http.lowSpeedTime 20`

The `lowSpeedLimit` configures the minimum bytes per second, and the `lowSpeedTime` is the number of seconds. If the operation is lower than that threshold for the set time it will timeout. Adjusting those values may help with timeouts.

I'm going to close this out since this isn't a specific issue with GitHub Desktop.
