### ISSUE TITLE
No Internet Connection on multiple file uploads

### ISSUE THREAD

**Issue by jainishkothary** [desktop/desktop#16845]
### The problem

I am getting No Internet Connection error whenever I try to upload multiple files all together. I need to publish them in fractions in order to get them published in one try.

### Release version

3.2.3

### Operating system

MacOS Ventura

### Screenshots

<img width="1440" alt="Screenshot 2023-06-06 at 9 50 47 AM" src="https://github.com/desktop/desktop/assets/64587880/e7ae7bca-2571-49ea-ba61-0405ad566dab">

**Comment by steveward** [comment]
Thanks for the report @jainishkothary. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by jainishkothary** [comment]
Hey There,

PFA

On 06-Jun-2023, at 7:34 PM, Steve Ward ***@***.***> wrote:



Thanks for the report @jainishkothary<https://github.com/jainishkothary>. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by steveward** [comment]
@jainishkothary issue attachments don't come through via email replies, you'll need to upload the log file directly in this issue.

**Comment by jainishkothary** [comment]
[2023-06-06.desktop.production.log](https://github.com/desktop/desktop/files/11666948/2023-06-06.desktop.production.log)

Please check if this is viewable. By the way thanks a lot for the swift response.

**Comment by steveward** [comment]
Thanks, that did come through. I'm seeing this specific error in the log file that looks like it could be the cause:

```
remote: error: inflate: data stream error (invalid code lengths set)        
remote: fatal: pack has bad object at offset 14067984: inflate returned -3        
error: remote unpack failed: index-pack failed
To https://github.com/BugwareSolutions/SC.git
 ! [remote rejected] main -> main (failed)
error: failed to push some refs to 'https://github.com/BugwareSolutions/SC.git'
```

GitHub will reject pushes with corrupt objects, which is why this is erroring out. Could you open the repository in the command line and run `git fsck` and let me know the full output of that command? That should hopefully give a better indication of what the issue is.
