### ISSUE TITLE
Git name not updating when changing account

### ISSUE THREAD

**Issue by millennIumAMbiguity** [desktop/desktop#16857]
### The problem

When logging out for a git account and then logging in with a different account, the name does not update.

### Release version

3.2.3 x64

### Operating system

Windows 11 Home 22H2 22621.1778

### Steps to reproduce the behavior

1. Open options.
2. Select Accounts.
3. Logout of a signed-in account.
4. Login with a different account.
5. Select Git.
6. Note that `Name` is of the previous account.

### Screenshots

![Logged in with a second account](https://github.com/desktop/desktop/assets/37588844/39d700cc-06b7-4532-9911-d80c7c4734c7)
![incorrect user name](https://github.com/desktop/desktop/assets/37588844/9beee9b6-ea6b-49ff-a820-109ddf751f3b)
![Clear image of account B with commit user name of account A](https://github.com/desktop/desktop/assets/37588844/a760f8f3-6513-4010-82b9-2062c34927d1)

**Comment by steveward** [comment]
Thanks for the feedback @millennIumAMbiguity. This is the expected behavior, and we show a warning when you attempt to commit with the wrong email address that allows you change to the correct email:

<img width="375" alt="Screenshot 2023-06-08 at 12 06 58 PM" src="https://github.com/desktop/desktop/assets/721500/494e6cbe-f4fe-4aca-8632-64bd091ff1d4">

**Comment by millennIumAMbiguity** [comment]
I see I missed mentioning that part, but I do in fact update the email. otherwise, the commit would be on the other account. I will make a new issue with proper images and reproduction steps.
