### ISSUE TITLE
Git name not updating after changing account and updating email

### ISSUE THREAD

**Issue by millennIumAMbiguity** [desktop/desktop#16858]
### The problem

When logging out for a git account and then logging in with a different account and then updating the email, the name does not get updated.

### Release version

3.2.3 x64

### Operating system

Windows 11 Home 22H2 22621.1778

### Steps to reproduce the behavior

1. Open options.
2. Select Git to see your name and email. *(Image 1)*
3. Select Accounts. *(Image 2)*
4. Logout of a signed-in account.
5. Login with a different account. *(Image 3)*
6. Update Email. *(Image 4)*
7. Note that it says *"Committing as"* followed by the name of the previous account. *(Image 5)*
8. Open options.
9. Select Git.
10. Note that `Name` is of the previous account. *(Image 6)*

### Screenshots

Image 1
![image](https://github.com/desktop/desktop/assets/37588844/13747602-04a9-462e-9bbe-59950659970c)

Image 2
![image](https://github.com/desktop/desktop/assets/37588844/ea184c8f-530a-4a30-bb69-cb427ec4b24a)

Image 3
![image](https://github.com/desktop/desktop/assets/37588844/7e12711c-72ff-41aa-beab-e99624714373)

Image 4
![image](https://github.com/desktop/desktop/assets/37588844/f787860d-4da5-42b9-b4e8-09d65155662d)

Image 5
![image](https://github.com/desktop/desktop/assets/37588844/ee8da7ed-ca6d-4793-a7b3-8ed236ee9079)

Image 6
![image](https://github.com/desktop/desktop/assets/37588844/e591d131-ee1c-4a9d-9c47-3f27348f8074)

**Comment by steveward** [comment]
Thanks for the issue @millennIumAMbiguity. This is the intended behavior, as changing the name would mean modifying the local `.gitconfig` file and this is not something we want to automatically do without user interaction. We haven't heard a lot of feedback about this since most users use the same name, but want their email changed to ensure Git attribution is correct. In the future when we ship multi-account support (https://github.com/desktop/desktop/issues/3707) this may be something we can consider again, but I am going to close this out for the time being since it's not something we're planning to change.
