### ISSUE TITLE
Fail to fetch code to github when useing github desktop

### ISSUE THREAD

**Issue by robinsnp** [desktop/desktop#16856]
### The problem

When I use the desktop to fetch or pull or push my code to github, the error message is:  _**fatal: unable to access 'https://github.com/robinsnp/XXX.git/': schannel: SEC_E_UNTRUSTED_ROOT (0x80090325)**_ 。  I have tried to sign out and re-sign in my account, but it did not work. I enabled two-factor authentication on 5th June, I am not sure whether this matters.

### Release version

3.2.3 (x64)

### Operating system

Windows 10 

### Steps to reproduce the behavior

1. Push commits to the origin remote.
2. Error occurs.

### Log files

[2023-06-08.desktop.production.log](https://github.com/desktop/desktop/files/11683519/2023-06-08.desktop.production.log)

### Screenshots

![1](https://github.com/desktop/desktop/assets/109929660/e7f3b386-c8d6-43c8-8b82-c69f4d3d426b)

**Comment by robinsnp** [comment]
I don't know what happened ,but it now works.

**Comment by 192933488S** [comment]
Robin, what happend? _Don't know_ is vague. Any simple ideas how to work around this?

### Same issue here:

```
Cloning into 'C:\xxx'...
fatal: unable to access 'https://xxx/': 
schannel: SEC_E_UNTRUSTED_ROOT (0x80090325) - The certificate chain was issued by an authority that is not trusted.
```

### Comments:

1. This is not _fatal_, no one died; think of another word to describe this issue
2. This could be simply a tick-boxed hack, as in "[x] accept non-trusted CA and continue cloning"

### Updates:

Having invested some more time into this awkward issue, and for the afterworld,  numerous approaches exist, such as https://stackoverflow.com/questions/53210531/ssl-certificate-problem-unable-to-get-local-issuer-certificate-in-git, but after some changes, reinstallation, etc., the error morphed into:

`fatal: unable to update url base from redirection:`

...

This issue is cross-clients, affecting:

- SmartGit
- Github Desktop
- SourceTree (albeit it tries to login, do something, but ultimately fails to clone)

Also there exist numerous gitconfig's deployed across various folders. This needs sorting out from first principle. What is what, and which is called by which, e.g., Github Desktop.

### Workaround (after deep-debugging):

The hack goes as follows (for the rest of the world):

- Search all "gitconfig" on your machine to be sure, which are exist
- Uninstall all other Git clients and search again "gitconfig". The result should be several folders, depending how often you updated GitHub:

```
C:\Users\XXX\AppData\Local\GitHubDesktop\app-3.3.1\resources\app\git\etc\gitconfig
C:\Users\XXX\AppData\Local\GitHubDesktop\app-3.3.3\resources\app\git\etc\gitconfig
```

- Use ONLY the latest gitconfig
- Exclude/disable CA checking/validating

```
[http]
	sslBackend = schannel
	schannelUseSSLCAInfo = false
	sslVerify = false
```

Lastly, for security reasons, make sure that at some point in time your git-repo-hosting-service-provider depreciates the self-signed CA and provides officially signed certificates.
