### ISSUE TITLE
Bug in GitHub Desktop

### ISSUE THREAD

**Issue by Metaluis90** [desktop/desktop#16864]
### The problem

Certains files are not being updated in the Desktop Version of GitHub. Specifically, pictures files with .tga extensions are not being recognized by GitHub anymore.

![image](https://github.com/desktop/desktop/assets/108318037/e88df3de-2002-49b9-b66a-4073f59ecb48)

As you can see, GitHub is recognizing there's a file that has been modified in the repository.
But as you can see, there are two files that were added to test the issue. One, a .txt file, and the other one, a .tga file

![image](https://github.com/desktop/desktop/assets/108318037/7cc86d02-d5da-47f7-97f9-8e9b21036f21)

Then if I add a new file

![image](https://github.com/desktop/desktop/assets/108318037/55c98cf8-395e-4928-a63e-468ea533c70f)

Github correctly recognized its addition.

![image](https://github.com/desktop/desktop/assets/108318037/7217297f-5f1b-4b21-bcea-a8b1331ba328)

Then agai, if I try to add the .tga extension file, for some reason GitHub doesnt' recognize it.

![image](https://github.com/desktop/desktop/assets/108318037/fd483336-c6b3-491d-8dbe-7c1447a73c80)

![image](https://github.com/desktop/desktop/assets/108318037/6e7462bd-a004-4fde-a611-17d232d438dc)

### Release version

3.2.3 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

You just need to add .tga extensiomn files

**Comment by steveward** [comment]
@Metaluis90 thanks for the issue. This is likely due to the file extension being ignored in your `.gitignore` file. You can check if this is the case by going to `Repository` > `Repository Settings` > `Ignored Files`. You can read more about ignoring files [here](https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files). Let me know if that isn't the issue and we can investigate further.
