### ISSUE TITLE
Make staging line hunks more obvious

### ISSUE THREAD

**Issue by iAmWillShepherd** [desktop/desktop#1688]
As it stands, staging a line is not obvious. I think we should add a ➕  icon on each line's hover state.

**Comment by shiftkey** [comment]
cc @niik @donokuda for design feels

**Comment by joshaber** [comment]
This is something we've struggled with for a while. Our stats for Classic indicated that people don't use selective committing much, and we've wondered if that's because it's hard to discover.

**Comment by rlabrecque** [comment]
So I use it in SourceTree constantly but I didn't realize GHD had this feature until now.

It's really really elegant right now, but yeah discoverability seems to be an issue.

**Comment by niik** [comment]
> As it stands, staging a line is not obvious. I think we should add a ➕ icon on each line's hover state.

I don't believe adding a plus icon would fix this discoverability issue, we already have hover states. Rather than adding an icon (and I'll note that the :plus: symbol already has a defined meaning in a diff) I think we should look at this as an onboarding issue. We didn't bring the tutorial over but we've talked in the past about having unobtrusive 'ProTips' just like github.com has.

![image](https://cloud.githubusercontent.com/assets/634063/26354510/15a2dff2-3fc5-11e7-9096-deedb04b4714.png)

![image](https://cloud.githubusercontent.com/assets/634063/26354814/95db6828-3fc6-11e7-95bf-ee1eef88f7d4.png)

From this we could then link to a help article which explains the feature in more detail.

**Comment by Janpot** [comment]
In the changes view, staged/non-staged lines are indicated with a checkbox, in the diff on the right it's this strange selection thing in the gutter. To me, the checkboxes are really obvious to indicate which files to stage and which not. Maybe it's just a matter of emphasising the duality between staging whole files and staging lines. By which I mean, maybe you can try adding similar checkboxes to the left of the staged lines instead of that selection gutter thing?

**Comment by joshaber** [comment]
>I think we should look at this as an onboarding issue.

I'm not entirely sure. People don't read words.

Back In The Day, Mac Classic had a banner at the top of the diff for this reason:

![github-app-showing-index-html-diff](https://cloud.githubusercontent.com/assets/13760/26356185/35eda0c0-3f99-11e7-9147-dbfc8376572e.png)

**Comment by enriquecaballero** [comment]
Line staging doesn't seem to be working for me in the new GHD. It commits the entire file. Is this an existing issue?

**Comment by joshaber** [comment]
@enriquecaballero No, that sounds like a separate bug. Please open a new issue!

**Comment by enriquecaballero** [comment]
Will do

**Comment by enriquecaballero** [comment]
https://github.com/desktop/desktop/issues/1831

**Comment by kylefox** [comment]
@joshaber 

> This is something we've struggled with for a while. Our stats for Classic indicated that people don't use selective committing much, and we've wondered if that's because it's hard to discover.

This is partly why I didn't use it in Classic. It was hard to discover but also _use_. It wasn't clear from the UI if clicking a line staged or unstaged it. I could never remember how it worked, and thus stopped using it entirely.

The new GitHub app suffers from the same problem IMO. In fact, I just tried and it seems to do the _opposite_ of what I expect — when I click a line, I expect that line to be explicitly staged and everything else unstaged. That is, I should click to indicate which lines to stage, rather that which lines to unstage.

**Comment by donokuda** [comment]
> The new GitHub app suffers from the same problem IMO. In fact, I just tried and it seems to do the opposite of what I expect — when I click a line, I expect that line to be explicitly staged and everything else unstaged. That is, I should click to indicate which lines to stage, rather that which lines to unstage.

Currently in Desktop, we have all the files and lines selected by default following the assumption that people will want to commit all the lines at once.

However, what if we had all files/lines deselected at first:

![screen shot 2017-06-02 at 10 14 27 am](https://cloud.githubusercontent.com/assets/1174461/26736972/1b21e882-477d-11e7-8e0c-eb25fde38c15.png)

If you clicked on the checkbox in the changed files header, then it'll select all the lines (and visually change the line gutter for the diff.) We can have a `X lines selected` counter in the file header to help communicate the state of partial commits:

![clickclickclick](https://cloud.githubusercontent.com/assets/1174461/26737228/17c8b282-477e-11e7-9709-8c0e820473b9.gif)

![screen shot 2017-06-02 at 10 20 22 am](https://cloud.githubusercontent.com/assets/1174461/26737020/4a3d3f54-477d-11e7-8ba9-d1010354ae3b.png)

The visual change and counter might be enough to inform about partial committing:

![screen shot 2017-06-02 at 10 14 37 am](https://cloud.githubusercontent.com/assets/1174461/26737113/a055f66a-477d-11e7-896c-7249a10d353e.png)

💭's? Once downside I can imagine is that it adds an extra step to add all files, but it might be worth it if it helps encourage our users to "craft" their commits instead of committing everything at once.

**Comment by kylefox** [comment]
Personally, I'm fine with all files/lines being staged automatically — 99% of the time, I'm committing everything, and it would be a bit of a nuisance to tick the files every commit (at least with the way I use git).

However — one of your screenshots _perfectly_ illustrates the source of my confusion:

![](https://cloud.githubusercontent.com/assets/1174461/26737113/a055f66a-477d-11e7-896c-7249a10d353e.png)

To me, _it's not clear which 2 lines are selected for staging._ I think the source of my confusion is that the lines _not_ selected still maintain the green background used to indicate staged changes when the whole file is staged.

I think when viewing a diff where only some lines are selected, there should be a visual change to indicate lines that are changed but not staged. Here's a quick example of what I mean — by no means am I suggesting using this design specifically, I'm just suggesting some way to make staged & unstaged lines more visually distinct.

![staged-lines](https://cloud.githubusercontent.com/assets/37838/26738544/c115f662-478b-11e7-86e8-df77082e3eb6.png)

Not sure I'm making any sense here 😂

**Comment by enriquecaballero** [comment]
> 99% of the time, I'm committing everything

![futurama-fry](https://cloud.githubusercontent.com/assets/7918284/26740420/7aba73a6-47a3-11e7-9404-ee11f757c7d4.jpg)

**Comment by rushrtb2112** [comment]
99% of the time....I don't commit everything.  Line by line committing is a necessity and one i look forward too.

**Comment by kylefox** [comment]
@enriquecaballero @rushrtb2112  I prefer to make very frequent, very small commits as much as possible, which I guess minimizes the amount of line-by-line staging I need to do compared to others

> Line by line committing is a necessity and one i look forward too.

I agree that it's a necessity — it's possible to do this now. My point is simply that (to me) the UI doesn't make it clear which lines are staged vs which aren't.

**Comment by donokuda** [comment]
> I think when viewing a diff where only some lines are selected, there should be a visual change to indicate lines that are changed but not staged. Here's a quick example of what I mean — by no means am I suggesting using this design specifically, I'm just suggesting some way to make staged & unstaged lines more visually distinct.

Oh, I ❤️ this direction so far! I'll cut a branch to get a feel of the interaction. The only change I'm thinking of doing is to have the checkmark aligned to the left of the line number columns so it's easier to scan vertically.

**Comment by donokuda** [comment]
Here's a gif of the interaction for indicating which lines are staged. If you want to try it out yourself, feel free to pull down the [`check-myself` branch](https://github.com/desktop/desktop/tree/check-myself) and give it a go.

![clickclickclick](https://user-images.githubusercontent.com/1174461/26854904-1e4f4ba0-4acd-11e7-9b12-06e5092c5d2b.gif)

I feel like this makes it clearer which lines are staged; _however_, I'm not sure this solves the discoverability issue of being able to stage individual lines. Any thoughts?

@rlabrecque I would love to hear more since you mentioned that this is a feature that you do use, but couldn't discover it in Desktop. Are there some visual cues or interactions that would help inform you that this feature exists?

**Comment by rushrtb2112** [comment]
@donokuda That looks really nice.  Makes it well known what lines you want to have set to goto staging.  Can you highlight a series of lines and then right click a menu item to `stage selected lines`?  Also it might be cool to set the ability to stage a chunck of code, maybe on the patch breaks (`@@` lines).  I attached an image so you can see what i was thinking for it.

<img width="672" alt="stagehunk" src="https://user-images.githubusercontent.com/17084577/26877935-9af66c92-4b59-11e7-8b00-d357aa9a269d.png">

the other cool ability would be to allow someone to discard changes from this view.  (stretch goal)
I like where it's going and can't wait to be able to use it in stable.

**Comment by Janpot** [comment]
It's nice but it still doesn't scream "click me" in a way a checkbox does. I'd go further and make that real checkboxes to the left of the gutter instead of making the whole gutter blue.

**Comment by joshaber** [comment]
I really like this direction @donokuda 💖 

>It's nice but it still doesn't scream "click me" the way a checkbox does. I'd try to go even further and make that real checkboxes to the left of the gutter instead of making the whole gutter blue.

I somewhat agree. Now that we're making the positive, selected case clearer, I wonder if we need to make the negative, unselected case clearer too. I don't have any concrete ideas, aside from more or less copying checkboxes 😁

**Comment by Janpot** [comment]
<img width="215" alt="26877935-9af66c92-4b59-11e7-8b00-d357aa9a269d" src="https://user-images.githubusercontent.com/2109932/26881329-655ca914-4b97-11e7-876a-4e568941ad86.png">

You could also just keep a square at the left of the line blue, as a sort of hybrid between a checkbox and what's currently there. looks more like a checkbox, but less cluttered with boxes and lines.

**Comment by simurai** [comment]
A concern to make it look like lots of "real" checkboxes might be that then people try to click on each individually and don't realize that click & dragging is soo much nicer. Not that it's easy to discover now, but just that having lots of checkboxes makes it seem "the only way".

> @kylefox I think the source of my confusion is that the lines not selected still maintain the green background used to indicate staged changes when the whole file is staged.

Maybe  greyed/faded out like:

![ignored-lines](https://user-images.githubusercontent.com/378023/26908152-d5042278-4c33-11e7-9375-7ba72ed9c408.png)

Then these lines feel more like "being ignored for the next commit". Downside: Harder to read once you deselect them. Also there could be a checkbox in front of the file name above. So that once you start clicking on the blue selection and see the checkbox turns to `[-]`, you might realize that it's "removing from the current selection". Or maybe have some sort of selected vs total lines counter: `(13/14)`.

It's somewhat tricky because when coming from another git client, you typically make a selection first and then click another button to stage or unstage. And you can toggle between staged and unstaged changes. But in GitHub Desktop it's more a "keep things selected that should be part of the next commit". I think it's a nice workflow once you can forget about "having to stage/unstage" as a middle step. Would be really interesting to know if GitHub Desktop's approach is easy to use for somebody new to git or hasn't used other clients yet.

**Comment by rushrtb2112** [comment]
@janpot i wouldn't want one single way to stage.  Having multiple ways will satisfy the majority.  to start with, i'd be happy with the checkboxes and multi line selection checkability.

**Comment by kylefox** [comment]
@simurai I definitely like the idea of making the "modified but not staged" lines visually distinct. Maybe they could be highly desaturated variants of the existing green/red? Almost like 50% opacity or something.

**Comment by j-f1** [comment]
I think it should also be more discoverable that hovering over the `+` and `-` markers stages or unstages the whole contiguous chunk.

**Comment by adamreisnz** [comment]
I like the direction this discussion is going, but  personally, I would suggest to ditch the current blue selected state color, because I don't think it adds any value. I'd much rather see the green/red color for added/removed lines in the gutter, and have line selection work via subtle checkboxes, and deselected lines be greyed out as @simurai suggested above.

The bright blue looks very messy to me, and it was funny to see you talking about discoverability of this feature, because I did not know it was possible, even after using the old client for several years.

I literally stumbled upon this thread because I was trying to search for an issue that explains why on earth the gutter lines are coloured that outrageous blue 😆 

I'd really much prefer the green/blue extending over the gutter, it's much easier on the eyes:

![image](https://user-images.githubusercontent.com/490562/28867651-e288bfcc-77ca-11e7-97a8-1f1de3fef2a0.png)

Since the gutters are so [wide](https://github.com/desktop/desktop/issues/2102), there's plenty of space left for a checkbox of sorts as @donokuda designed.

**Comment by pkamb** [comment]
Just tried GitHub Desktop for Mac, tried to stage line-by-line, and it appeared as if the feature did not exist in the app. Gave up, googled for it, and ended up here.

I thought the blue was some kind of glitchy/broken residual from selecting lines (for copy-and-paste) in the editor window. It's the same color.

<img width="275" alt="screen shot 2017-08-03 at 10 31 00 am" src="https://user-images.githubusercontent.com/342355/28934809-293a3cd6-7837-11e7-96f0-e5ab7b7fd6cc.png">

There's currently no ability to right click on a line of code. That's the first thing I tried. `Right Click > "Stage Line"`. If that had worked, and turned the gutter blue, it would be a major clue that I could just click the gutter in the future.

I also looked in the menubar. `menubar > Help > Search Box > type "stage"` and get no results. A menubar command to stage would allow me to find the feature the first time, then use the fancy gutter way on subsequent times.

Left clicking a line to select should offer a similar clue. A button that pops up to "Stage Line" or similar.

Selecting ~5 lines of text out of a bigger diff, and then staging all of those lines at once, would be my primary way to stage. Currently it's impossible to select lines in the code viewer area and then stage them. You have to work in the completely separate staging gutter area. I'd suggest uniting the two areas and allowing staging from either.

**Comment by iAmWillShepherd** [comment]
Thanks for the feedback @pkamb. Our team is currently working on improving this and we will surely take your feedback into consideration.

**Comment by pkamb** [comment]
Another related issue I have, but perhaps outside the scope of this discussion, is that I find the "single view" of staged/unstaged files and lines extremely confusing.

SourceTree has a "Staged" area and an "Unstaged" area. The app either comes out of the box this way, or can be set up like this.

Your staged *lines* get moved into the stage, the remaining lines remain in the unstaged. This lets you view the diff of only what you've staged, as if the rest of the diff does not exist. This will show the diff exactly as it will be committed. 

This is much easier to view IMO than doing the mental math of adding up each Blue line, and discarding the non-blue lines. The resulting diff may not be what you expect.

Doing a view like this would allow you to get rid of the blue highlighting and checkmarks entirely. A line of code is either in the Stage or Unstaged area.

**Comment by adamreisnz** [comment]
@pkamb yeah, it's one of the things I actually *dislike* about source tree. It makes working with files and commites more complicated than it needs to be, as you need to look for files in two different places and context switches often, slowing your work flow down I found. 

I love the simplicity of github desktop, and having all files in one place, using the checkboxes to stage/unstage, it's very intuitive in my opinion.

I've tried several times to start using source tree, but keep coming back to github desktop instead (well, the old version for now). I would like Github to keep it's simplicity, which I think is one of it's strengths. If you're after more features and more control, use source tree instead I'd say.

**Comment by joshaber** [comment]
We agree with @adamreisnz. We currently have no plans to split the file list into separate Staged/Unstaged sections.

**Comment by hazendaz** [comment]
This is an interesting thread.  I commit chunks all the time.  The problem I have with the new version is that it does not handle contiguous lines properly not that it doesn't work or I didn't know what it was doing.  In fact, at the moment the new version behaves exactly like gitkraken and sourcetree in that regard by breaking continuous line commits.  I would much rather prefer to get back what the vintage version provided in that it is smart about what was selected so I don't end up with items landing incredibly wrong in the file.  Generally I'm going this level of commits in pom files so elements moving aroud don't matter much outside of looking very funny but it is a core reason why, at least with my company, we have not yet decided this is prime time.  It's really my only hangup because otherwise this works extremely well.  And I certainly would never want to see separated views which is why sourcetree is garbage :(

**Comment by donokuda** [comment]
> The problem I have with the new version is that it does not handle contiguous lines properly not that it doesn't work or I didn't know what it was doing. In fact, at the moment the new version behaves exactly like gitkraken and sourcetree in that regard by breaking continuous line commits. I would much rather prefer to get back what the vintage version provided in that it is smart about what was selected so I don't end up with items landing incredibly wrong in the file.

Hi @hazendaz! Can you provide an example that demonstrates what you would expect to be selected vs what currently happens? I'm not sure what you mean by "breaking continuous line commits." Does that have something to do with soft vs hard line-wrapping in the diff?

**Comment by hazendaz** [comment]
Hi @donokuda, what I mean is if I have say the following xml.

```xml
<abc.version>1.2.0</abc.version>
<def.version>1.2.0</def.version>
``

And I change both versions to say 1.2.1 but then want to commit one line at a time.  So I select the reference to abc for before and after and commit.  In the vintage github desktop, it would properly commit against the respective place in the file.  However, with new version and every last other tool I've seen this behaviour instead will result in the xml file getting the elements flipped for example as this.

```xml
<def.version>1.2.0</def.version>
<abc.version>1.2.1</abc.version>
``

Now on the next commit when I select the 'def' line to commit, it will flip it back.

```xml
<abc.version>1.2.1</abc.version>
<def.version>1.2.1</def.version>
``

As a result of that behaviour I mostly still use the old version at home to keep commits clean.  However, I am using this at my day job due to the old one not working on virtualized desktops.  And as such, I've at this point just learned to deal with the behaviour.  I guess pre version 1.0.0 I figured this would sort itself out.  Oddly on occassion it actually does commit in the right order but I've yet to determine exactly how or why it occassionlly works.  More often than not it flips the elements.  I have this problem most significantly with xml files where I group maven artifact versions in properties section so those change frequently all at once then I like to commit each one separately in case I need to revert one out plus the clarity it gives for versions I've updated.  I know I could just update one line at a time and suffer some productivity or just allow the issue.  This does no harm in xml files but if this were to occur in other file types it would cause significant headache.  However, in my experience I've never had a situation that would warrant commit this way in other file types.  So I'm always hit with this on xml only.  But I'm sure it is there regardless of file type.

**Comment by reyronald** [comment]
> @pkamb yeah, it's one of the things I actually dislike about source tree. It makes working with files and commites more complicated than it needs to be, as you need to look for files in two different places and context switches often, slowing your work flow down I found.

@adamreisnz  Wow, that's shocking for me to read, since I have the exact opposite opinion. I'm with @pkamb  on this. I love using the split staging view and have grown so used to it that basically I feel like a fish out of the water when I'm using a tool that doesn't have it. I find it adds a lot of power to the code reviewing experience before commiting. 

> I love the simplicity of github desktop, and having all files in one place, using the checkboxes to stage/unstage, it's very intuitive in my opinion and every action is done with far less clicking than in source tree.

Just wanted to point out that SourceTree has a "No staging" view that doesn't split anything, and looks and works exactly like GitHub Desktop minus the possibility to stage lines or files (it's called "No staging" after all), that I suppose you would prefer.

Also, a split view for staging is how Visual Studio Code's (vscode) integrated Git tools work too:

![stage-view](https://user-images.githubusercontent.com/7514993/34847719-b5c62554-f6f2-11e7-95f1-73c814737981.gif)

> I've tried several times to start using source tree, but keep coming back to github desktop instead (well, the old version for now). I would like Github to keep it's simplicity, which I think is one of it's strengths. If you're after more features and more control, use source tree instead I'd say.

I thought it could be added to GHD as an option, in a "choose to view the changes however you like" way so that both users like you and me could benefit, and I don't think it would take away its simplicity or alter the scope of the tool that much at all, which was what I was going to suggest coming here before getting discouraged by some of the comments against it :/

-----

> We agree with @adamreisnz. We currently have no plans to split the file list into separate Staged/Unstaged sections.

@joshaber That's a shame! =(, I created #3771 hoping this could be added before reading all of this discussion. Hope it can be reconsidered because I truly miss it when using GHD!

**Comment by aa758770072** [comment]
不怎么样

**Comment by goyalyashpal** [comment]
> Maybe greyed/faded out like:
_simurai_ at https://github.com/desktop/desktop/issues/1688#issuecomment-306973222

just saying for my vote: it was much difficult to read for me. (hint: color blindness and accessibility issues). also, the diffs within the lines (when just some part of the line changes) would become even hard to scan through. and the difficult to read thing while feels small, but it becomes a real pain gradually.

**Comment by goyalyashpal** [comment]
---
> second gutter, which are stacked checkboxes
_janpot at https://github.com/desktop/desktop/issues/1688#issuecomment-306798103_

i like this suggestion. minimalist yet recognisable and covers the use case.

---
> i wouldn't want one single way to stage/unstage. Having multiple ways will satisfy the majority. to start with, i'd be happy with the checkboxes and multi line selection checkability.
_rushrtb at https://github.com/desktop/desktop/issues/1688#issuecomment-307073853_

can u please explain what u mean, idont get that. 'cz as per my understanding, janpot's suggestion is just a ui change, and doesnt reduce any mode of interaction like u are saying. multi line selection is still possible with that design.

**Comment by n8-dev** [comment]
All options should be implemented.
You should have the ability to choose your preferred way.

Arguing about whats best doesn't solve the fact that people work and like different things.

**Comment by madhavajay** [comment]
Whats the status of this? I got a new machine and thought id try to replace `sourcetree` again, but it seems theres still no gui client with staging split and hunks... Clearly im not the only one who prefers this superior mental model of composing my commits?

**Comment by eduwass** [comment]
I agree with @madhavajay , Sourcetree still has the most intuitive GUI I've seen in terms of staging/unstaging splits and hunks, would love to see GitHub desktop take notes from this.

**Comment by ParkerRobb** [comment]
Had to read this thread to figure out line-by-line staging in GitHub Desktop. 😆

It's 2023, folks. Accomplishing this simple task should not be as counterintuitive as it currently is!

**Comment by goranovs** [comment]
It's 2024 and I had to google my way to this issue.  Also, I had to read the whole discussion here to understand how the feature actually works. Now that I know it looks super simple and handy, but omg there was no way I was going to figure this out on my own.

I'm used to VS Code and I was searching for "right click" menu option similar to VS Codes "stage selected ranges". If there was such an option I assume eventually it was going to click for me what the "blue selection" means when I click the option few times.

Maybe I'm already too old, but for me the "blue selection" was there just for no reason. I mean it was invisible for me.

**Comment by tidy-dev** [comment]
@goranovs We have some new accessibility changes coming out soon that are [currently in beta](https://desktop.github.com/beta/) that adds checks to these controls to make them more obvious. Also, they are now keyboard accessible. We are also shipping a new accessibility tab in the app setting to turn them off for users who prefer the slimmer existing view.



![Showing some changes with the checkmark.](https://github.com/desktop/desktop/assets/75402236/c63c125d-b916-4b50-9b52-2bf75c05590b)

**Comment by tidy-dev** [comment]
^ Closing this (see last comment)

**Comment by ParkerRobb** [comment]
Looks nice! Thank you for including!
