### ISSUE TITLE
Not receiving windows notifications

### ISSUE THREAD

**Issue by iii-james** [desktop/desktop#16894]
### The problem

I am not receiving windows notifications. I have "Enable notifications" checked under Options -> Notifications. I checked my Windows 10 settings under Notifications & actions but GitHub Desktop is not listed.

### Release version

3.2.4

### Operating system

Windows 10

### Screenshots

![image](https://github.com/desktop/desktop/assets/46497848/5968d08f-df2d-4cdb-b996-6ee623c01fcb)

**Comment by steveward** [comment]
Thanks for the report @iii-james.  Was the repository where you were expecting notifications from selected in GitHub Desktop? We currently only show notifications for the active repository.

**Comment by iii-james** [comment]
Yes it was. I tried again to make sure by creating an issue with another account and assigning the issue to the same user account I am signed in on the desktop. I am working on a private repo using an organization. I added a team and a member. I am trying out GitHub Desktop so I will be notified if I am assigned an issue to work on or for pull requests etc and not have to rely on having the website up looking at the bell beside my profile or missing an email. Not sure what a notification would look like. Is it like a toast message popping up?

**Comment by sergiou87** [comment]
Hi @iii-james ! 👋 

GitHub Desktop will only notify you about your Pull Requests when:
1. They are reviewed
2. Their checks fail
3. Someone comments on them

And that will only happen if Desktop has the repository of those Pull Requests selected.

GitHub Desktop will not notify you any other events like mentions or issue assignments, in order to minimize the noise you get through it.

I hope that helps!

**Comment by iii-james** [comment]
@sergiou87 Thanks for the clarification.
