### ISSUE TITLE
Not Updating from within v3.2.3 macOS

### ISSUE THREAD

**Issue by alvarnell** [desktop/desktop#16896]
### The problem

I am not receiving notification of the update when using v3.2.3.

### Release version

3.2.3

### Operating system

macOS Big Sur 11.7.8

### Steps to reproduce the behavior

1. Launch GitHub Desktop.
2. Wait a few minutes (now a full day plus)
3. No notification of an update available.

**Comment by sergiou87** [comment]
Hello! We do staged updates. We manually increase the % of users that get the update depending on the importance of the update and reports we get, that's why it sometimes takes longer than others. Also, what users get the update for every % is random in every update.

Meanwhile if you're in a hurry to get the latest updates, you can <kbd>Alt</kbd> + Click on the `Check for Updates` button will bypass the staged update and get you the latest version.

I hope that helps!
