### ISSUE TITLE
Branches are not updated from none GitHub Repos

### ISSUE THREAD

**Issue by crouser83** [desktop/desktop#16906]
### The problem

I am working an a project with GitLab and used GitHub Desktop (GHD) to push and pull. GHD detects new branches but does not delete them in the 'switch-branch-menu'  when they are merged or deleted on GitLab. Because of that, I have a long list of all ever created branches to choose from, but the GitLabl repo only contains the main branch. <br>
Another issue is the naming of the branches, which are seemingly also not updating, because some of my branches to choose from have totally different names as in GitLab. 

### Release version

Version 3.2.3 (x64)

### Operating system

Win 10

**Comment by steveward** [comment]
Thanks for the issue @crouser83. GitHub Desktop does prune branches that have been deleted on the remote after 14 days of no local activity (see https://github.com/desktop/desktop/issues/750 for discussion around this), but at this time it is only for repositories hosted on github.com. At this time we don't have plans to implement this for other hosting services, but there are a number of scripts available that provide ways to quickly delete branches that have been deleted using the command line. 

>Another issue is the naming of the branches, which are seemingly also not updating, because some of my branches to choose from have totally different names as in GitLab.

This is the expected behavior. I'm not sure what GitLab shows, but GitHub shows this warning when renaming a branch on gihtub.com:

<img width="441" alt="Screenshot 2023-06-21 at 9 25 38 AM" src="https://github.com/desktop/desktop/assets/721500/e2a7d8f7-8245-4030-a737-38500c55e3d5">

You can use the steps mentioned there to update the local branch names. I hope that helps!
