### ISSUE TITLE
Showing wrong dates when cherry-picking commits

### ISSUE THREAD

**Issue by focux** [desktop/desktop#16929]
### The problem

When you cherry-pick a commit, it shows the original date of the commit you are cherry-picking instead of showing the current commit date as it shows in Github.com

### Release version

3.2.4 (arm64)

### Operating system

macOS Ventura 13.4

### Steps to reproduce the behavior

1. Cherry-pick an old commit to a new branch
2. Look at the date of the new commit on the history tab

### Screenshots

<img width="612" alt="image" src="https://github.com/desktop/desktop/assets/3316818/12610f81-35ea-4ff7-a077-40e7d93b5447">

**Comment by steveward** [comment]
Thanks for the issue @focux. Git has both an author date and commit date. The author date shows when the commit was originally made, while the commit date is changed if a commit is modified (like in a cherry pick or rebase). GitHub Desktop is showing the author date, which is why you are seeing this difference. If you run `git log --pretty=fuller` from the command line you can see the two dates there. I hope that helps.
