### ISSUE TITLE
Cannot update to or install lastest release (3.2.4)

### ISSUE THREAD

**Issue by slycordinator** [desktop/desktop#16921]
### The problem

3.2.4 was released on June 13th 2023 and is the latest release according to https://desktop.github.com/release-notes/

But when one selects to download the latest installer from https://desktop.github.com/ , it provides the 3.2.3 installer.

And when running 3.2.3, selecting "About GitHub Desktop" then "Check for Updates", the program displays that 3.2.3 is the latest version.

### Release version

3.2.3

### Operating system

windows 10

### Steps to reproduce the behavior

1. Go to https://desktop.github.com/release-notes/
2. See that 3.2.4 is the latest release
3. Go to https://desktop.github.com/
4. Click "Download for Windows 64-bit"
5. Run installer
6. Verify that it installs 3.2.3

Or
1. Go to https://desktop.github.com/release-notes/
2. See that 3.2.4 is the latest release
3. Run installed 3.2.3 version
4. Select "Help" -> "About GitHub Desktop"
5. Click "Check for Updates"
6. See that it says that 3.2.3 is the latest version

**Comment by niik** [comment]
Hey @slycordinator, thanks for reaching out and thanks for filling out the repro steps!

We gradually roll out updates and we temporarily paused that rollout over the weekend to investigate a potential issue. We've started back up again slowly today but it will take a while before we reach 100% rollout. Once the update is available to you the client will automatically download it and let you know that it's ready to be installed. If you don't want to wait you can hold down the `Alt` key in the about dialog while pressing the check for updates button. That will skip the rollout queue and get you the latest available update. If that doesn't find a new update it's because we've paused the rollout again.

**Comment by sergiou87** [comment]
We roll out releases progressively to prevent major bugs from spreading quickly.

In any case, you can skip this process by pressing <kbd>Alt</kbd>  an clicking on the `Check for Updates` button in the About dialog.
