### ISSUE TITLE
Repo not updating

### ISSUE THREAD

**Issue by bbisson** [desktop/desktop#16976]
### The problem

Repo not updating and won't undo pending changes from another branch that shouldn't have been carried over to main.

### Release version

3.2.4

### Operating system

MacOS Ventura

### Steps to reproduce the behavior

1. Open a branch with changes
2. Switch to another branch and leave changes - changes from previous branch are carried over
3. Switch to main and leave changes. Attempt to discard changes, update main, etc. Changes are still displayed

**Comment by steveward** [comment]
Thanks for the report @bbisson. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
