### ISSUE TITLE
Permanent repository browser window

### ISSUE THREAD

**Issue by SergeiTerentev** [desktop/desktop#16974]
### The feature request

Please add possibility to pin repository browser window that appear when choosing the repo and contains filter input and add button. 

### Proposed solution

It's would be great if the window stay visible always.

**Comment by niik** [comment]
Hi @SergeiTerentev, thanks for reaching out! I believe this issue is similar to, and can be rolled up into, #1593 which we decided to track as part of https://github.com/desktop/desktop/issues/6460.

At the moment we don't have any plans for allowing the repository sidebar to stay open all the time but we appreciate your feedback as it helps us inform future direction. #1593 contains some more reasoning around this as well as some tips on the keyboard shortcuts that we already support for quickly switching repositories.
