### ISSUE TITLE
The new app

### ISSUE THREAD

**Issue by adamreisnz** [desktop/desktop#1701]
I've had a brief look at the new github desktop app, but when compared to the old github desktop for mac app, it's really disappointing. There's features missing, it's hard to find your way around, even harder to navigate repo's now, and issues that were raised in the desktop mac repo *still* haven't been addressed in the new version. In fact, some have arguably been made worse.

For example, it's still not possible to either manually sort/arrange your repo's (yes I have dozens and the list is becoming very long), or at least have them be organised by organisation. This was already a pain in the old app and the feature has been requested by dozens of users, but what's worse now in the new app is that for some reason it shows the top level **folder name** as the repo name, instead of the actual repo name. 

If I have an app called `foo` which is split up in two repo's, e.g. `foo-client` and `foo-server`, yet on my computer I conveniently store those repo's in `foo/client` and `foo/server`, these repo's show up in the new app not as `foo-client` and `foo-server` as they did in the old app, but as `client` and `server` instead. Needless to say if you have *many* apps with that kind of structure, you simply can't tell which repo you're currently looking at. It just says `client`. Which one of the 20? Whoever came up with that idea must have only ever had unique folder names for every single project/repo.

When I saw the new app I was hoping these obvious and often requested pain points would at least have been addressed, because development of the old mac client was obviously halted a while ago, so I wasn't expecting any improvements anytime soon. But to put something out there that's worse for features and UX, and completely disregard all the feedback that the mac beta users have been providing diligently for the past few years is really saddening.

**Comment by joshaber** [comment]
Hi @adamreisnz, thanks for the honest feedback!

I'll be the first to admit we did a really poor job managing the feedback that you and others helpfully provided. Part of the motivation for being open source this time around is so that we can be more responsive to feedback.

>For example, it's still not possible to either manually sort/arrange your repo's

We're not opposed to this, but our stats also tell us that most users don't have that many repositories which is why we haven't prioritized it historically. Of course, that might be something of a self-fulfilling prophecy. If the repositories list is unwieldy past 10 repositories, who's gonna wanna add 100?

I'd welcome an issue about this. Surprisingly we don't seem to have one yet.

>but what's worse now in the new app is that for some reason it shows the top level folder name as the repo name, instead of the actual repo name.

I reopened https://github.com/desktop/desktop/issues/664 to track this.

---

I'm gonna close this to keep our issues list actionable. I totally understand if you feel burned or burnt out, but if you don't, please know that we welcome any issues you might want to open.

**Comment by adamreisnz** [comment]
@joshaber thanks for taking it well! I realize this wasn't really actionable, but felt I needed to voice my concern. I will keep an eye on the project and see how it evolves. Once the largest pain points have been taken away I'll give it another shot. 

And good for going open source with it, that will definitely be beneficial in the long run I think.
