### ISSUE TITLE
Deleted all my files

### ISSUE THREAD

**Issue by LittleDog117** [desktop/desktop#17045]
### The problem

I tried fetching files and then it deleted all the work I did. I can't seem to find my work anywhere.

### Release version

idk

### Operating system

windows 10

**Comment by ShadowWalker918** [comment]
It’s because your using a program that wasn’t finished ！I was in a contract with google Samsung and MDN, someone released it before it was ready, but it was designed to do exactly what ur saying it’s doing… The only way to fix it is to complete the program requirements. I would tell u exactly what to do but then I’d screw myself. They won’t admit what they did so I won’t tell them how to fix it either. But keep doing what ur doing if it’s something you enjoy.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: LittleDog117 ***@***.***>
Sent: Friday, July 7, 2023 10:04:01 PM
To: desktop/desktop ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [desktop/desktop] Deleted all my files (Issue #17045)


The problem

I tried fetching files and then it deleted all the work I did. I can't seem to find my work anywhere.

Release version

idk

Operating system

windows 10

Steps to reproduce the behavior

No response

Log files

No response

Screenshots

No response

Additional context

No response

**Comment by sergiou87** [comment]
@LittleDog117  Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
