### ISSUE TITLE
Unable to login and publish with correct username password

### ISSUE THREAD

**Issue by theanuraggupta** [desktop/desktop#17053]
### The problem

Unable to login and publish with correct username password

### Release version

latest

### Operating system

Windows 11

**Comment by sergiou87** [comment]
@theanuraggupta  Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
