### ISSUE TITLE
Selecting/deselecting large amount of tracked items in changes will hang the client.

### ISSUE THREAD

**Issue by AG4W** [desktop/desktop#17050]
### The problem

I work in game development, we usually have a very large amount of small files that are tracked - which is why I run into this issue quite often.

Selecting/deselecting a large number of files (>20k) will usually break the client. (changes scroll view no longer works, and the rest of the client behaves in unexpected ways)

### Release version

Version 3.2.6 (x64)

### Operating system

Windows 11

### Steps to reproduce the behavior

1. Add a very large amount of files to be tracked as changes (50-100k)
2. Select top file, and using shift+left-click on the last file, selecting all changes.
3. Hit space to attempt to deselect/select.

**Comment by tidy-dev** [comment]
@AG4W Thank you for the report. A PR for [commit list performance enhancements](https://github.com/desktop/desktop/pull/16880) recently was merged. You are welcome to [try it out in beta](https://desktop.github.com/beta/). Otherwise, it will likely be next month before it rolls into production. I am going to close this since there was a known performance bug in prod, however, if you test beta and find the same issue. Feel free to comment back.
