### ISSUE TITLE
Display notifications on the desktop app, just like the mobile app

### ISSUE THREAD

**Issue by nokite** [desktop/desktop#17061]
### The feature request

The desktop app does not display desktop push notifications.
I find it hard to keep track of what's happening with PRs in my repository.
(emails are extremely noisy and there's very very limited customization. The github website does not seem to support desktop notifications (the ones that the browser shows in collaboration with the OS. So there's no good alternative)

### Proposed solution

Let the desktop Github app show desktop notifications, and make it possible to customize them (notify only on mentions, only on PRs where you were active etc...). The goal is to get only the notifications that you care about.
Take the Android Github app as an example, it does a relatively good job.

**Comment by sergiou87** [comment]
Hello @nokite ! 👋 

While we understand your request, we (the GitHub Desktop team) decided to support only a minimum set of notifications that are relevant to the user. GitHub Desktop is not a GitHub client, but a Git client with a reasonable integration with GitHub. GitHub Desktop doesn't intend to support all the features GitHub has, which is why being able to handle the same kinds of notifications and in the same way is out of the scope.

Right now, GitHub Desktop supports these notifications **related to the selected repository**:
- When CI checks failed for one of your PRs
- When someone reviews or comments one of your PRs

I hope that helps to understand our decision. Unfortunately, right now we're not considering adding more notifications to Desktop.

**Comment by DTTerastar** [comment]
Lame, Especially since iOS does this already...
