### ISSUE TITLE
installGlobalLFSFilter: UNKNOWN On opening GitHub Desktop 2.6.3

### ISSUE THREAD

**Issue by CoolBasiliskNPP** [desktop/desktop#17066]
### The problem

I have the same issue as the following: https://github.com/desktop/desktop/issues/11610

I have tried doing the fixes mentioned in that thread for example: (https://github.com/desktop/dugite-native/releases/download/v2.26.2-3/dugite-native-v2.26.2-8da9a6e-windows-x64.tar.gz) but it didn't work.

### Release version

2.6.3

### Operating system

Windows 10

**Comment by sergiou87** [comment]
Hey @CoolBasiliskNPP ! 👋  We've seen issues like this in the past due to the presence of antivirus or firewalls putting some of GitHub Desktop's executables in quarantine, or even just removing them.

I'd suggest to disable any antivirus, firewall, etc. you might have, and then uninstall and reinstall GitHub Desktop and see if that makes a difference 🤞
