### ISSUE TITLE
Push to origin takes forever

### ISSUE THREAD

**Issue by monoffoto** [desktop/desktop#17096]
### The problem

I created a repository online and right after that I committed a "READMY" file. This showed up in my Github Mac OS app.
All right then. 
I put some other files in my project directory on my iMac, committed them and clicked on "Push origin" button in the Github desktop app:
Nothing is showing up under "Code" on the repository page on Github in the browser.
"Push to origin" in the desktop app is still loading and loading...

I did this before ones just to test this out and it worked flawlessly.
Then I decided to delete my test repository and created a new one from scratch like I did before.

### Release version

3.2.6 (x64)

### Operating system

Mac OS Ventura 13.4.1 (c)

### Steps to reproduce the behavior

clicked "Commit to main", worked
clicked "Push origin", takes forever

### Log files

[2023-07-20.desktop.production.log](https://github.com/desktop/desktop/files/12110408/2023-07-20.desktop.production.log)

### Screenshots

<img width="954" alt="Bildschirmfoto 2023-07-20 um 16 33 11" src="https://github.com/desktop/desktop/assets/140064669/4f357b8a-97ee-4df4-80ef-941d337f831d">

**Comment by steveward** [comment]
Thanks for the issue @monoffoto. Network issues are tricky to diagnose, and there isn't much we can do from our end about them since the underlying Git operations are failing:

```
Writing objects: 100% (1174/1174), 30.33 MiB | 23.87 MiB/s, done.
Total 1174 (delta 8), reused 0 (delta 0), pack-reused 0
fatal: the remote end hung up unexpectedly
Everything up-to-date
```

How large is the repository you are working with? 

There are some HTTP timeout config operations that may help, or at lease provide additional diagnosis about the timeout. One user previously had success with these commands:

`git config --global http.lowSpeedLimit 1000`
`git config --global http.lowSpeedTime 20`

The `lowSpeedLimit` configures the minimum bytes per second, and the `lowSpeedTime` is the number of seconds. If the operation is lower than that threshold for the set time it will timeout. Adjusting those values may help with timeouts.

If neither of those suggestions work it may be worth trying to set [up a SSH key](https://docs.github.com/en/authentication/connecting-to-github-with-ssh), which some users have had more success with when encountering network issues. You could then switch the remote URL to use SSH in GitHub Desktop by going to `Repository` > `Repository Settings` > `Remote`. 

I'm going to close this out as this isn't a specific GitHub Desktop issue, but I hope that helps.

**Comment by monoffoto** [comment]
The repository is 69,1 MB

**Comment by monoffoto** [comment]
2ng thing I can not understand:
Under Settings - Pages my GitHub Page is never created...
I have properly set the branch as main. The page should have appeared within minutes.

**Comment by monoffoto** [comment]
<img width="1349" alt="Bildschirmfoto 2023-07-20 um 17 28 35" src="https://github.com/desktop/desktop/assets/140064669/451f0518-2175-4905-8753-eceb742b9214">
