### ISSUE TITLE
clone of asset has a problem

### ISSUE THREAD

**Issue by kamyarjafari** [desktop/desktop#17107]
### The problem

hello
The clone has a problem (0x1000000fa32d122c18a6a31c009ce5e71674f22d06a581bb0a15575e6addadcc::usda::USDA/
file in aptos) and it don't let me to open asset in github 

please aprrove it

best regard

### Release version

Version 3.2.6 (x64)

### Operating system

windows 7

**Comment by tidy-dev** [comment]
@kamyarjafari Sorry for your issue. Could you please provide more context or reproduction steps to your issue? Additionally the log file can be very helpful. :)

**Comment by kamyarjafari** [comment]
![asset download](https://github.com/desktop/desktop/assets/140299662/5443e433-9b37-4a27-815b-944af25a81c2)
![when the finished download](https://github.com/desktop/desktop/assets/140299662/c90885db-53d6-4bcd-b830-a8bc00b3d4c1)
![cant open file properly](https://github.com/desktop/desktop/assets/140299662/75ddeb81-45e1-4c86-865b-f7a61f6fe9c2)
![open with visual studio](https://github.com/desktop/desktop/assets/140299662/96e5b37e-693c-48e0-a96b-e8d679fa6ab5)

**Comment by kamyarjafari** [comment]
I have sent you the steps in sequence
I followed all the steps according to the instructions
I checked again with Windows 10 and other systems, and the same error occurred

**Comment by steveward** [comment]
@kamyarjafari thanks for the screenshot. It looks like one of the files has`:` (colons) in the filename, which is causing the checkout to fail due to this not being allowed on Windows. Windows has [naming conventions](https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions) that exclude certain reserved characters. If you rename the file it should get things working again. You can do this directly on GitHub.

You can also try to bypass this by using the following config option:

`git config --global core.protectNTFS false`

Just a warning that this could have unintended consequences. I hope that helps!
