### ISSUE TITLE
Husky pre-commit hook prevents commiting

### ISSUE THREAD

**Issue by przemyslaw-zan** [desktop/desktop#17103]
### The problem

GH Desktop throws an error during commiting when repository has [husky](https://github.com/typicode/husky) pre-commit hooks. This was previously discussed in https://github.com/desktop/desktop/issues/15721, and even though a workaround was provided, the bug is still there.

### Release version

3.2.6

### Operating system

Windows 22H2 19045.3208

### Steps to reproduce the behavior

1. Set up repository:

`./.husky/pre-commit`:

```bash
#!/bin/bash

echo foo
```

`./package.json`:

```json
{
    "dependencies": {
        "husky": "^8.0.2"
    },
    "scripts": {
        "postinstall": "node -e \"require( 'husky' ).install()\""
    }
}
```

2. Run `npm install`
3. Attempt to commit using GH Desktop.

### Log files

[2023-07-21.desktop.production.log](https://github.com/desktop/desktop/files/12130581/2023-07-21.desktop.production.log)

### Screenshots

![image](https://github.com/desktop/desktop/assets/69513154/73dd3104-aa8f-49b0-990f-7a0bdf4cb7f4)

**Comment by steveward** [comment]
@przemyslaw-zan thanks for the issue. Most users have been able to resolve this by adding Git (C:\Program Files\Git\bin) to your PATH (you'll need to have Git installed). See https://github.com/desktop/desktop/issues/12586#issuecomment-1223600474.

Hopefully that gets things working. I'm going to close this out since we already have a few open issues related to problems with hooks, but if you have any further questions let me know.

**Comment by przemyslaw-zan** [comment]
@steveward Thank you, the fix you provided worked indeed!

And just in case someone stumbles upon this issue in the future, could you please provide references to the hook related issues you mentioned?
