### ISSUE TITLE
Renamed files appear as added and removed

### ISSUE THREAD

**Issue by guidezpl** [desktop/desktop#17109]
### The problem

Renamed files appear as added and removed

### Release version

Version 3.2.6 (arm64)

### Operating system

macOS

### Steps to reproduce the behavior

1. Rename a file
2. Two entries appear, one for deletion and one for addition
<img width="354" alt="image" src="https://github.com/desktop/desktop/assets/6655696/e48909e7-dfb7-4ac7-836f-8678213f07f5">

3. Commit
4. Only one entry shows up
<img width="280" alt="image" src="https://github.com/desktop/desktop/assets/6655696/bb652bf2-2b86-49b9-ae7d-4f89e2e55a7e">

**Comment by tidy-dev** [comment]
@guidezpl Thanks for the report! This is actually expected behavior as GitHub Desktop is a git client is reflecting what Git returns to us. For the working directory, Git just sees a rename as new file and a deleted file, but for the history view Git does some more advanced diff comparison on the last commit versus the current commit to determine if there is a rename.

Here is a [nice blog post ](https://chelseatroy.com/2020/05/09/question-how-does-git-detect-renames/)on it if you would like to learn more.
