### ISSUE TITLE
Github Desktop has lost all local info

### ISSUE THREAD

**Issue by BazzaCuda** [desktop/desktop#17137]
### The problem

The latest version has just installed itself. When I run it, it now shows a "Let's get started!" panel.

It seem to have lost all knowledge of my local repositories and the links to their online versions.

It's as if I've started over with a completely fresh install.  So it's not checking for differences between my local repos and the online ones as it usually would. If I click on one of my online repos it suggests cloning it. But I already have it locally with fresh updates ready to upload.

Worse, Github Desktop doesn't seem to provide any facility for me to tell it about my local repos.

### Release version

3.12

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Launch Github Desktop.
2. The "Let's Get Started!" activity panel is displayed.

### Log files

[2023-07-27.desktop.production.log](https://github.com/desktop/desktop/files/12202612/2023-07-27.desktop.production.log)
[2023-07-28.desktop.production.log](https://github.com/desktop/desktop/files/12202613/2023-07-28.desktop.production.log)

My two most recent log files.
Github Desktop was used during the second log file to commit updates to my online repos.
It also includes the time when GD was shut down and restarted following the update.

### Screenshots

![Clipboard Image](https://github.com/desktop/desktop/assets/22550919/1e3ad991-241f-44d1-b301-b271ca685617)

**Comment by BazzaCuda** [comment]
In the clear light of day (instead of the mad panic I was in late last night), I've just noticed the "Add Local Repository" option.
I will have to steadily work my way through my 33 repos. Even so, the update shouldn't have lost all this info, in my opinion. I will be dreading seeing the next "An update is available and will be installed on the next startup" message.

**Comment by chevette17** [comment]
#17137

**Comment by sergiou87** [comment]
Hey @BazzaCuda ! Sorry you're experiencing this issue.

This latest version we deployed upgrades Electron. When that happens, everything should still work fine. The behavior you describe only happens when you go to an **older** version of Electron.

Looking at the logs you shared, it seems that you were running version 3.1.2 of GitHub Desktop 👍 , then upgraded to 3.2.7 👍  where Desktop even refreshed your 66 repos 👏 , but then somehow you ended up in 3.1.2 again 😱😱😱 That's what broke the stored stuff for you:
```
2023-07-28T08:59:48.533Z - info: [ui] launching: 3.1.2 (Windows 10.0.19044)
2023-07-28T08:59:48.542Z - info: [ui] execPath: 'C:\Users\Baz\AppData\Local\GitHubDesktop\app-3.1.2\GitHubDesktop.exe'
... 
2023-07-28T15:04:18.891Z - info: [ui] launching: 3.2.7 (Windows 10.0.19044)
2023-07-28T15:04:18.895Z - info: [ui] execPath: 'C:\Users\Baz\AppData\Local\GitHubDesktop\app-3.2.7\GitHubDesktop.exe'
2023-07-28T22:34:51.496Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 66 repositories took 12.1s of which 0.0s paused, total 12.1s
…
2023-07-28T22:37:21.898Z - info: [ui] launching: 3.1.2 (Windows 10.0.19044)
2023-07-28T22:37:21.905Z - info: [ui] execPath: 'C:\Users\Baz\AppData\Local\GitHubDesktop\app-3.1.2\GitHubDesktop.exe'
```

Is that your personal machine or is it managed by some IT department at work? Maybe _something_ is enforcing the use of 3.1.2, which would also explain why you are in that version from October 2022 🤔

**Comment by BazzaCuda** [comment]
Hi, that explains a lot, thanks. I have updated my desktop menu tool to launch the new version.
However, it also highlights a massive flaw, in my opinion. 
You assume that everyone launches GD from the shortcut in Start Menu/Programs/Github Inc./ which clearly gets updated during the installation of the new version.

You've (i.e. Github Inc) assumed that nobody has copied the shortcut to their desktop or pinned the application to the taskbar, or used the location of the exe in any desktop tool used to launch apps, like Rocket Dock, or my own software, CustomMenu.
In my opinion, this a ludicrous assumption to make on Windows.

In fact, the update message is very misleading in that it clearly states that the new version will launched on restart**.  This will only ever be true for users who use the Start Menu shortcut.
** It implies that an update-in-place will occur.

Whilst it's great that you keep the previous versions as a fallback option, the current version's folder name should not contain the version number so that all possible shortcuts that the user has created, or tools the user has configured to launch the app remain valid.

We'll save the discussion for why the software is installed in AppData rather than in Program Files (where the new folder would be more obvious) for another time.

**Comment by sergiou87** [comment]
We're really sorry you ran into this issue, I see how things can get messy 😭 I think most (if not all) Electron-based applications use Squirrel to package and create installers, and also to manage updates. [Electron itself has integrated support with Squirrel for autoupdating](https://www.electronjs.org/docs/latest/api/auto-updater#windows), and it's [Squirrel](https://github.com/Squirrel/Squirrel.Windows), AFAIK, the component that takes all those decisions for us (having 1 subfolder per version as fallback, then 1 "global" exe, installing it in AppData…).

Not trying to make excuses here, just trying to explain the _why_. And relying in a tool like this, already integrated with Electron, is a big relief for us since we (the GitHub Desktop team) are a very small team with not many resources. It's also true that I can't recall other issues being reported around this 🤔

**Comment by BazzaCuda** [comment]
Ok, thanks Sergiou. For the record, I still think Github Desktop is superb and I couldn't do without it. Now that I've sorted out my problem, I'm back in love with it again ;)
