### ISSUE TITLE
github desktop can't fucking push my commit to remote

### ISSUE THREAD

**Issue by hanle97** [desktop/desktop#17151]
### The problem

because of fk authorizing issue i have been loggin and log out for 8 milions time, both on web browser and the shitty app itself, still not fk work but the intellij built-in Git was pushing just fine, DON'T tell me that intellij got your stupid app conflicted because the error showed up didn't cover that case

### Release version

3.2.7

### Operating system

Windows 10

### Steps to reproduce the behavior

commit
push
authorize failed error show up

**Comment by sergiou87** [comment]
[Code of Conduct](https://github.com/desktop/desktop/blob/development/CODE_OF_CONDUCT.md)

**Comment by GitBizNow** [comment]
unfortunately this happens when you have large company full of non innovative idiots creating bad solutions while the creative non conforming creative genius people cant get a job because they dont fit the mold, are to eccentice, or dei or other nonsense. Just part of being human I guess, afterall most shit floats
