### ISSUE TITLE
Crash Execution - Github Desktop 3.2.7 binary

### ISSUE THREAD

**Issue by rio-rattenrudel** [desktop/desktop#17168]
### The problem

I can't execute Github Desktop by auto-update from 3.1.2 to 3.2.7
Version 3.1.2 works fine and I can't disable auto-update. that's a pitfall.

I get following Exception:

---------------------------
GitHubDesktop.exe - Einsprungpunkt nicht gefunden
---------------------------
Der Prozedureinsprungpunkt "DiscardVirtualMemory" wurde in der DLL "KERNEL32.dll" nicht gefunden. 
---------------------------
OK   
---------------------------

### Release version

3.2.7

### Operating system

Win7 x64

### Steps to reproduce the behavior

1. Execution

**Comment by sergiou87** [comment]
Hey @rio-rattenrudel ! 👋 

That's really weird, you shouldn't even be able to auto-update because we dropped support for Windows 7 and disabled the auto-update in #16566 

Could you please open the developer tools (View menu -> Toggle Developer tools) and type the following into the console

```
require('os').release()
```

Please let us know what that tells you and we'll continue investigating on our end

Thank you!

**Comment by sergiou87** [comment]
Oh I see the problem, you were on 3.1.2 which doesn't prevent auto-updating. My advice is that you install 3.2.6 from this link and stay in that version until you update your operating system (which we highly recommend you):

- GitHub Desktop 3.2.6 for Windows: https://centralreleases.blob.core.windows.net/github-desktop/releases/3.2.6-de80a354/GitHubDesktopSetup-x64.exe

**Comment by rio-rattenrudel** [comment]
3.2.6 works fine!

**Comment by rio-rattenrudel** [comment]
thx for fast support. so i have to stay on that version?

**Comment by steveward** [comment]
@rio-rattenrudel you will have to stay on that version until you upgrade operating systems. Let us know if you have any further questions.

**Comment by Marat-Tanalin** [comment]
> Oh I see the problem, you were on 3.1.2 which doesn't prevent auto-updating. My advice is that you install 3.2.6 from this link and stay in that version until you update your operating system (which we highly recommend you):

It would probably make sense for the new version incompatible with Windows 7 to not update to itself, so that the update-prevention mechanism would work regardless of what the previous installed version is and whether that previous version is aware of not updating to a Windows-7-incompatible version.
