### ISSUE TITLE
I am unable to push files

### ISSUE THREAD

**Issue by Nikhilgarepalli** [desktop/desktop#17174]
I am unable push files without force command pls help in this regard

**Comment by steveward** [comment]
Thanks for reaching out @Nikhilgarepalli!

Would you mind filling out the rest of the issue template so that we can better understand what is causing the problem you are experiencing? Without that information it will be difficult to help you further. It would especially be helpful if you could upload the log file from GitHub Desktop, which will give more details about the specific error you are seeing. 

To access the log files go to the  menu in GitHub Desktop and select `Help` > `Show Logs...`. The log files are created daily -- please send over a log file as an attachment from a day where you experienced the issue.

**Comment by TLP0079** [comment]
Hey there? ok so once you have your github desktop running you will need to access you git repository. once you have located it, choose wgat file you want to push. after that then add a comment and description then  just click the push button. hope that was helpful.
