### ISSUE TITLE
Invalid numstat Line

### ISSUE THREAD

**Issue by HDBEARMAN** [desktop/desktop#17173]
### The problem

When trying to preview a pull request on GitHub desktop the error Invalid numstat line comes up.
It's still possible to use create pull request and do the pull request as normal in the browser but annoying I can't preview beforehand in the desktop app.

### Release version

Version 3.2.7

### Operating system

Windows 10

### Screenshots

![image](https://github.com/desktop/desktop/assets/112472872/3bfd5770-594e-4a11-aba3-2dda27af7e89)

**Comment by sergiou87** [comment]
@HDBEARMAN  Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
