### ISSUE TITLE
Incorrect Error Message: Endless Fetching of Unrelated Commit History

### ISSUE THREAD

**Issue by FireACNC** [desktop/desktop#17187]
### The problem

When attempting to publish an Xcode project to a remote repository using GitHub Desktop, a misleading error message appears during the "Fetch" process, resulting in an endless fetching loop.

The root cause of the issue is that the remote main branch and the local branch have unrelated commit histories, preventing a successful fetch. However, the displayed error message does not provide relevant information about this issue, leading users to believe that the fetch is still possible.

I apologize if the steps I followed to add my project to the remote repository were not appropriate, but I do believe this is a bug. Typing `git pull origin main --allow-unrelated-histories` can solve the fetching issue and enable publishing the branch.

### Release version

3.2.7

### Operating system

macOS 13.1

### Steps to reproduce the behavior

1. Create an Xcode project.
2. Make and commit some changes.
3. Create a git repository on the GitHub website.
4. Add a README file or commit other changes.
5. In the terminal, cd into the Xcode project folder.
6. run the following commands:
`git init`
`git remote add origin https://github.com/<username>/<remote_repository_name>.git`
7. Open GitHub Desktop, add repository, and select the Xcode project folder.
8. Click "Publish Branch".
9. Click "Fetch" when prompted.
10. Wait for the fetching to complete, then click "Publish Branch" again. The same error message will appear.

### Screenshots

<img width="1360" alt="Screenshot 2023-08-06 at 8 04 05 PM" src="https://github.com/desktop/desktop/assets/98172796/6e790e82-c750-4d37-adad-707ba36f1d8d">

**Comment by tidy-dev** [comment]
👋 @FireACNC Thank you for the report! I verified the behavior. Tho, I am not sure if it can be classified bug as it is due to a configuration that Git is not geared for, and we usually we do not recommend that a user use the `--allow-unrelated-histories` flag. That said, it is a scenario that one could fall into without much difficulty. I am going to mark as an enhancement. Thinking, if this scenario is programmatically easy to detect, we could redirect user to a better flow (suggest to create a new clean repository remotely or if after more investigation the `allow-unrelated-histories` flag makes sense, we could add it for this use case). 

As for recommended flows: 

The most straight forward path is  
1) Create your repository on GitHub website. Clone it locally, then add your project files to it. Commit and push.

However, if you want to create it out of your existing directory: 

2) Command Line: Follow the instructions https://docs.github.com/en/migrations/importing-source-code/using-the-command-line-to-import-source-code/adding-locally-hosted-code-to-github#adding-a-local-repository-to-github-using-git

3) GitHub Desktop: Use the `Create Repository` dialog on GitHub Desktop to initialize your project folder.
![CleanShot 2023-08-07 at 08 10 42](https://github.com/desktop/desktop/assets/75402236/51fabf7b-68cb-4540-b601-fc6db6599ceb)

     In this dialog, the `Name` field should be your project's directory name and the `Local Path` should be path to the project's directory (or parent directory). 

    Troubleshooting:
    - If your local path = your project's directory, it will make a git repo in your project's directory. 
    - If your name does not = your project's directory name, it will create a git repo in a directory of that name. 
  
    After that, if you hit `Publish` in GitHub Desktop, it will present you with the `Publish` dialog allowing you to create a repository on GitHub's website through GitHub Desktop.

**Comment by FireACNC** [comment]
@tidy-dev Thank you so much for the detailed reply with clear explanations and instructions! That makes sense!
