### ISSUE TITLE
Feature request: support extensions

### ISSUE THREAD

**Issue by ajsb85** [desktop/desktop#1718]
Dearest.

The idea is to integrate our custom tools and workflow.

We can call it as extensions, plugins, packages, add-ins, add-ons, components, modules, widgets...

Thank you.

**Comment by Naramsim** [comment]
Yes, good call, something along what [N1](https://nylas.github.io/nylas-mail/) and [Hyper](https://github.com/zeit/hyper) do

**Comment by joshaber** [comment]
It'd be really helpful if/when we think about this to have some examples of the types of packages folks would want to build.

**Comment by ajsb85** [comment]
# Scenarios for third-party packages

## Commitizen

When you're working in a Commitizen friendly repository, you'll be prompted to fill in any required fields and your commit messages will be formatted according to the standards defined by project maintainers.

## git-flow

A collection of Git extensions to provide high-level repository operations for Vincent Driessen's branching model.

## QuickOpener

Sometimes while using GitHub desktop you want to explore a particular file on the file system browser, or maybe launch a command in a terminal to do something with it.

## git-autoconfig

Working with git repos where you can have multiple emails (like one for work, one for github, one for bitbucket, etc...) can be painfull. This extension forces you to set localy user.email and user.name for each project under git that you open with vscode.

## Syntax highlighting

Theme options to replace default GitHub syntax highlighting to Zenburn, Solaris Dark, etc...

## Custom templates

- README 	General information
- AUTHORS 	Credits
- THANKS 	Acknowledgments
- CHANGELOG 	A detailed changelog, intended for programmers
- NEWS 	A basic changelog, intended for users
- INSTALL 	Installation instructions
- COPYING / LICENSE 	Copyright and licensing information
- BUGS 	Known bugs and instructions on reporting new ones

**Comment by shiftkey** [comment]
Thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I added the `future-proposal` label to this issue and closed it so that we won't get overwhelmed with our backlog! We will revisit this in our next planning session.

In the mean time, feel free to experiment with these ideas or just provide feedback.

**Comment by ajsb85** [comment]
Ok, keep in touch.

**Comment by tabruno** [comment]
Hi, .. I wrote in about this and was asked to chime in here....
I realize GitHub Desktop is fairly new.  However, it could really use some "open-ness" in the way of custom "add ons" (similar for example w/ that supported in MS VSD).  On VSD's "Tools" menu they facilitate custom external tools via a few simple inputs (eg. "Title", Command Line, Arguments, Initial Directory).  Example:  We are striving to integrate GitHub w/ JIRA (using the DVCS connector) but on "commits" it requires the JIRA ticket ID be included in the Commit Summary.  So that must be typed in every time.  If we were able to craft our own custom tool which fetches the JIRA ticket ID from somewhere we could automate this and relieve developers the typing.  It doesn't seem to me this added "custom tool" feature would require much effort its simply a "shell out" to a Windows Command line.  Thanks.

**Comment by billygriffin** [comment]
@ajsb85 Thanks for the issue here. We're not opposed on principal to things that might enrich the experience and provide for varying workflows, but we want to keep the overall experience as intuitive and simple as possible, so we try to prioritize things that will benefit a critical mass of people, and not just a small subset. We may choose to build a more "open" GitHub Desktop down the road, but we have no intention of supporting extensions in the near term. Therefore I'm going to remove `future proposal` here to indicate that this isn't something we intend to work on and to keep our backlog manageable. As with everything, we're always open to being wrong or reconsidering if we think there's sufficient evidence to do so. And we'd also be open to you framing an individual problem in a new issue that you think something *like* one of the extensions you listed might help with, and we can consider various solutions. Thanks again!

**Comment by steveward** [comment]
From https://github.com/desktop/desktop/issues/18062:

> >Similar to VS Code, VS and many other software the most developers use, it supports in some way user created plugins or extensions. This allows for developers to streamline and customise their experience using the software.
> 
> These plugins could add buttons, change UI layout or UI colors amongst other things.
> 
> For a practical example: in the Unity game engine, certain files are saved in YAML. Manually solving merge conflicts of these type of files will often create corrupted results. Unity ships a UnityYAMLMerge tool with their engine, but using it requires some commands. For in the game industry, dealing with the CMD is difficult for non-devs like designers and artists. Having an extra button in Github desktop that could run a command in the repository would be amazing.
>
