### ISSUE TITLE
Changing case of filenames not reflected

### ISSUE THREAD

**Issue by richxrich** [desktop/desktop#17196]
### The problem

Changing the case of a filename on a file that already exists in the repository does not change the case and keeps the case as per what is on github.com 

### Release version

3.2.7

### Operating system

Windows 11

### Steps to reproduce the behavior

1. Create a file in UPPER case for example - put anything inside in the file
2. Commit.
3. Change the case to lower case of the file and change the content so github desktop will pickup on the file change
4. Notice that the filename has not changed to lowercase and it still UPPER case and will continue to stay this way.

**Comment by steveward** [comment]
Thanks for the issue. This is the expected behavior based on `core.ignorecase`. You can use `git mv <old_file_name> <new_file_name>` from the command line to rename the file -- Git will detect this change and allow you to commit it. See https://github.com/desktop/desktop/issues/2672#issuecomment-329011490 for further details.I hope that helps!
