### ISSUE TITLE
Lost My Project

### ISSUE THREAD

**Issue by ShivamNimbalkar** [desktop/desktop#17218]
features of the git hub desktop it should give error as file size is too large to commit  but it commited that file and  as i tried to push the changes it give the the error of network disconnected which is so pathetic now i have left with nothing but  a bunch of empty folders.
let me know if i can any way possible backup the project.
remaining Rest In ✌ my project
[README.md](https://github.com/desktop/desktop/files/12328991/README.md)

**Comment by Mhudzmhudz** [comment]
Same to you hope you try again

**Comment by steveward** [comment]
Thanks for the report @ShivamNimbalkar. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by ShivamNimbalkar** [comment]
[2023-08-13.desktop.production.log](https://github.com/desktop/desktop/files/12337823/2023-08-13.desktop.production.log)
Log File Attached

**Comment by steveward** [comment]
I am seeing the network issue:

```
Writing objects: 100% (8449/8449), 538.81 MiB | 3.07 MiB/s, done.
Total 8449 (delta 4829), reused 8448 (delta 4829), pack-reused 0
fatal: the remote end hung up unexpectedly
Everything up-to-date

(The error was parsed as 4: The remote disconnected. Check your Internet connection and try again.)
```

I'm also seeing this error:

```
fatal: unable to access 'https://github.com/ShivamNimbalkar/AI_IN_Metaverse.git/': Could not resolve host: github.com
```

It seems like there are some network issues going on. Are you on a reliable network connection? Unfortunately network issues are tricky to diagnose, and there isn't much we can do from our end about them since the underlying Git operations are failing.

There are some HTTP timeout config operations that may help, or at lease provide additional diagnosis about the timeout. One user previously had success with these commands:


`git config --global http.lowSpeedLimit 1000`
`git config --global http.lowSpeedTime 20`


The `lowSpeedLimit` configures the minimum bytes per second, and the `lowSpeedTime` is the number of seconds. If the operation is lower than that threshold for the set time it will timeout. Adjusting those values may help with timeouts.

If neither of those suggestions work it may be worth trying to set [up a SSH key](https://docs.github.com/en/authentication/connecting-to-github-with-ssh), which some users have had more success with when encountering network issues. You could then switch the remote URL to use SSH in GitHub Desktop by going to `Repository` > `Repository Settings` > `Remote`. I hope that helps.
