### ISSUE TITLE
Apply from an old url, got some files not changed.

### ISSUE THREAD

**Issue by Seckawijoki** [desktop/desktop#17223]
### The problem

After setting a new url in command line, apply the changes of files from old url workspace, which results in some files not changed.

### Release version

3.2.7

### Operating system

Windows 10

### Steps to reproduce the behavior

1. stash in old url
2. set a new url
3. apply the old stash

### Screenshots

![image](https://github.com/desktop/desktop/assets/21171645/e96e6603-58e0-4307-bc1c-b7bd726ec582)

**Comment by sergiou87** [comment]
Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
