### ISSUE TITLE
"Check for Updates" not pulling latest update data.

### ISSUE THREAD

**Issue by evanmoak** [desktop/desktop#17234]
### The problem

I have GitHub desktop version 3.2.7 installed currently. When I click "Check for Updates" I get the following message: "You have the latest version. (last checked just now)"

To date the most recent version on (8/16/2023) according to the GitHub Desktop [release notes](https://desktop.github.com/release-notes/) is 3.2.8. 

My friend is also using 2.9.6 and the button is not working for him either. 

### Release version

3.2.7

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Go to "Help"
2. Click "About GitHub Desktop"
3. "Check for Updates"

### Log files

[2023-08-16.desktop.production.log](https://github.com/desktop/desktop/files/12363102/2023-08-16.desktop.production.log)

### Screenshots

![image](https://github.com/desktop/desktop/assets/112496018/696ccd90-162e-4844-b515-eb5b47e715e0)

### Additional context

We have a firewall proxy at work, but I do not believe this is the issue. We normally do not have issues installing or pushing/pulling from GitHub.

**Comment by sergiou87** [comment]
Hello! We do staged updates. We manually increase the % of users that get the update depending on the importance of the update and reports we get, that's why it sometimes takes longer than others. Also, what users get the update for every % is random in every update.

Meanwhile if you're in a hurry to get the latest updates, you can <kbd>Alt</kbd> + Click on the `Check for Updates` button will bypass the staged update and get you the latest version.

I hope that helps!
