### ISSUE TITLE
Ability to render markdown files

### ISSUE THREAD

**Issue by YanisBft** [desktop/desktop#17248]
### The feature request

When editing a markdown file (i.e. a README file), you can only view the diff in Github Desktop. It would be great to be able to view the rendered version of the file as well.

### Proposed solution

Markdown files, especially README, are files you can edit easily in a lightweight editor, like notepad++ or things like that. Unfortunately, you cannot view how it's rendered in these editors. That's why having a rendered view of markdown files would be very useful in Desktop.

**Comment by jacortinas** [comment]
Thank you for the feedback, @YanisBft. I'm going to be adding the content of this issue to desktop/desktop#8687 where we are capturing feedback on markdown and README rendering. At this time this feature is not on our radar (which is why the issue is closed), but this may be something we look into in the future.
