### ISSUE TITLE
Unable to download GitHub Desktop in my Mac (Apple M2 Pro)

### ISSUE THREAD

**Issue by sanjana-xalts** [desktop/desktop#17244]
### The problem

It says me error "Download failed, please check the internet connection and try again", although I do have a stable internet connection.

Steps I followed to download:
1. https://desktop.github.com/   Clicked on Download for macOS
2. Expanded the zip file
3. Moved and opened the Github desktop application and the error with the below attached image popped up.

<img width="787" alt="Screenshot 2023-08-18 at 11 53 49 AM" src="https://github.com/desktop/desktop/assets/141630595/fca80de2-3af3-4614-8a78-cf4c49568053">

### Release version

3.2.9

### Operating system

macOS Ventura Version 13.3

### Steps to reproduce the behavior

Steps I followed to download:
1. https://desktop.github.com/   Clicked on Download for macOS
2. Expanded the zip file
3. Moved and opened the Github desktop application and the error with the below attached image popped up.

**Comment by sergiou87** [comment]
That might be because you're downloading GitHub Desktop for Intel-based Macs, and for some reason macOS is not using Rosetta to run it 🤔  Could you try this other link that says "Apple silicon Mac"?

![Screenshot of https://desktop.github.com with an arrow pointing at the link to download GitHub Desktop for Apple silicon Macs](https://github.com/desktop/desktop/assets/1083228/f0a22367-454d-4fa1-932a-45b4836e6702)
