### ISSUE TITLE
Can't find *repo name*

### ISSUE THREAD

**Issue by RusJJ** [desktop/desktop#17257]
### The problem

GH Desktop just started to fail in the repo loading. My project is not that big but bigger than 3kb code...
Even a small change appeared somewhere in the code, there is a chance GH Desktop will then show "Can't find "**repo name**"". There is 3 buttons: locate, clone again, remove. If i re-locate the repository, for a frame i can see the changes i made, but then the same error appears.

### Release version

Latest autoupdated

### Operating system

Windows 10

**Comment by RusJJ** [comment]
Okay, a little change. This is happening if i add a missing SUBMODULE content of SUBMODULE. For some reason updating/adding submodule doesnt download it's submodule's contents.

**Comment by sergiou87** [comment]
@RusJJ  Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by RusJJ** [comment]
Of course! When that happened, i've enabled developer mode to see what's happening so i opened console. i saw some stuffs but the error 128 appeared. I can find it again at the line 81
[2023-08-21.desktop.production.log](https://github.com/desktop/desktop/files/12399092/2023-08-21.desktop.production.log)

**Comment by sergiou87** [comment]
Thank you! Even looking at the logs I don't understand how you got to this state 😳 

Would you mind writing a detailed list with the steps I need to follow or record a video of getting a perfectly working repo into this state?

**Comment by RusJJ** [comment]
Okay, here is how i got this error and how i fixed it:
1. I have a repository **S** that i want to add as a submodule to my repository **A**. Repository **S** uses repository **B** as it's own submodule.
2. Im adding **S** as a submodule but git for some reason does not download repository **B**, only is creating an empty folder.
3. Im trying to compile the code but getting an error that files are missing. Because folder of repo **B** is empty. Im copying them by myself and **the error occurs**.
4. A simple fix: im doing my things. When i want to upload my own changes to repo **A**, i clean up the folder for repo **B** (which is a submodule of **S**, and **S** is a submodule of **A**), the error is gone because the folder of SUBMODULE of SUBMODULE is empty.
Hope you will understand this.

**Comment by RusJJ** [comment]
k, a little update: this is happening because of a file ".git" in a folder of submodule that is a submodule.

**Comment by sergiou87** [comment]
Thanks @RusJJ ! I think copying the files of a subrepo instead of letting git do its own thing is what caused the issue 🤔 

After adding `S` in step 2, you must run `git submodule update --init --recursive` to make sure it downloads any submodule.

Since this doesn't look like a GitHub Desktop issue, I will close it out.

**Comment by RusJJ** [comment]
But it may be the problem who forgot about --recursive argument. A simple file ".git" in a folder is breaking the local repo.
