### ISSUE TITLE
bring back the win7, win8 & 8.1 support

### ISSUE THREAD

**Issue by rodrigo1593** [desktop/desktop#17298]
### The feature request

i want latest github desktop version to work again on """""older""""" versions of windows. from win7 onwards.

### Proposed solution

look it doesnt make any sense to do that, we can actually take an older pc and threat it like a server, or take it to do separated things lol

### Additional context

i hate that damn error when i try to install it

**Comment by niik** [comment]
@rodrigo1593 I'm sorry that the deprecation of Windows 7, 8, and 8.1 is causing problems for you. Unfortunately we're unable to support these operating systems since Chromium (and therefore Electron) have dropped support for these. Staying on an old version of Electron would mean we would be unable to provide critical security updates for other, still supported, operating systems.

At your own risk you can install the last supported version of GitHub Desktop from this link: https://github.com/desktop/desktop/issues/17168#issuecomment-1664215745. That version will not auto-update.

**Comment by MaplePhoenex** [comment]
In case anybody else is still looking, this version works on Windows 8.1

[/MaplePhoenex/Github-Desktop-2.2.4](https://github.com/MaplePhoenex/Github-Desktop-2.2.4)

**Comment by RK-CBE** [comment]
> In case anybody else is still looking, this version works on Windows 8.1
> 
> [/MaplePhoenex/Github-Desktop-2.2.4](https://github.com/MaplePhoenex/Github-Desktop-2.2.4)

thanks

**Comment by Sherwin727** [comment]
Thanks man, you helped me a lot

**Comment by rackajuhu** [comment]
"Unfortunately we're unable to support these operating systems since Chromium (and therefore Electron) have dropped support for these." Just write a native application in C# or C++ and leave that $£^%^ Electron alone...

**Comment by veganaiZe** [comment]
Here's a direct link to the version [3.2.6 executable](https://github.com/desktop/desktop/releases/download/release-3.2.6/GitHubDesktopSetup-x64.exe) and its [release page](https://github.com/desktop/desktop/releases/tag/release-3.2.6).

**Comment by rackajuhu** [comment]
It's been almost a year since I wrote that comment... Literally rn I can't build the website from main branch because it keeps hanging on the commit...
