### ISSUE TITLE
Pushing to origin 

### ISSUE THREAD

**Issue by zzyzzyxx** [desktop/desktop#17308]
### The problem

Pushing to origin  does not finish. It just keeps on and on and on

### Release version

3.3.0 (x64)

### Operating system

Win10

**Comment by steveward** [comment]
Thanks for the report @zzyzzyxx. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
