### ISSUE TITLE
Pushing to Origin stuck indefinitely 

### ISSUE THREAD

**Issue by lcodetechgitrep** [desktop/desktop#17335]
### The problem

Trying to push xcode project, its stuck indefinitely , tried all the commands like increasing buffer size, compression configuration, nothing works.

![New Note](https://github.com/desktop/desktop/assets/48748102/6d34484f-ae92-447b-bc21-f6b1502e5ca3)

### Release version

Version 3.3.1 (arm64)

### Operating system

Ventura 13.3

**Comment by steveward** [comment]
Thanks for the report @lcodetechgitrep. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by evolkmann** [comment]
@steveward I am experiencing similar issues where operations take very long end sometimes fail completely (not only pushing).

Attached is my log from today where I experienced the issue (as well as in the last few days since I last updated).

I am using Version 3.3.1 (arm64).

[2023-09-08.desktop.production.log](https://github.com/desktop/desktop/files/12556462/2023-09-08.desktop.production.log)
<img width="1338" alt="Bildschirmfoto 2023-09-08 um 08 55 37" src="https://github.com/desktop/desktop/assets/24471188/4077e250-701e-4d6f-9468-4c39c9fc9c07">

**Comment by steveward** [comment]
@evolkmann that looks like a network issue -- are you behind a proxy or firewall?
