### ISSUE TITLE
Fixing #16442 broke my local git workflow

### ISSUE THREAD

**Issue by Dante-Broggi** [desktop/desktop#17348]
### The problem

Fixing #16442 broke my git workflow:
When working locally having multiple branches _feels_ like too much overhead to have multiple stashes,
so instead I had stashes at `branch`, `branch-`, `branch--`, `branch---`, etc, and renamed between them.

Now Github Desktop renames the stash when renaming the branch, obscuring the previous stash I had on the new name,
at least I can recover the now-lost stashes by transferring the stashes into temporary commits.

Relevant xkcd: https://xkcd.com/1172/ 😆 

### Release version

Version 3.3.1 (arm64)

### Operating system

macOS Ventura 13.5.1

### Steps to reproduce the behavior

\<setup old>
1. create branch `test`
2. stash something on branch `test`
3. rename branch `test` to `test-`
4. stash something on branch `test-`
5. rename branch `test-` to `test`

\</setup>
\<setup new>
1. create branch `test`
2. stash something on branch `test`
3. create branch `test-`
4. stash something on branch `test-`
5. delete branch `test-`

\</setup>
6. rename branch `test` to `test-`
7. Expect-fail the stash created on branch `test-` to appear in the Github Desktop UI
8. Find the stash created on branch `test`
9. Unstash
10. Expect the stash created on branch `test-` to appear in the Github Desktop UI

### Additional context

Acceptable solutions for me would include:
supporting multiple stashes on a branch,
adding an option to stash on a new branch & providing a migration to create a branch for each hidden stash,  
or making the behavior added by #16442 configurable.

**Comment by steveward** [comment]
Thanks for the detailed issue @Dante-Broggi, I'll bring this up for discussion to the team internally.

**Comment by steveward** [comment]
Thanks again for bringing this up @Dante-Broggi. We discussed this internally and unfortunately at this time we won't be changing this behavior, since fixing the branch rename issue was a priority due to the feedback we were receiving. Since you mentioned support for multiple stashes would be solution I would recommend following along with https://github.com/desktop/desktop/issues/12699. I'm going to close this out, and I'm sorry that I don't have better news.
