### ISSUE TITLE
getting authentication fail issue.

### ISSUE THREAD

**Issue by adikrsingh03** [desktop/desktop#17357]
### The feature request

getting authentication fail issue.

### Proposed solution

getting authentication fail issue.

**Comment by steveward** [comment]
Thanks for the report @adikrsingh03. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
