### ISSUE TITLE
can´t push anything to my github anymore from the desktop app

### ISSUE THREAD

**Issue by Satisfraction** [desktop/desktop#17400]
### The problem

im getting the following error:

Cannot push these commits as they contain an email address marked as private on GitHub. To push anyway, visit https://github.com/settings/emails, uncheck "Keep my email address private", then switch back to GitHub Desktop to push your commits. You can then enable the setting again.

but i have no email at all in any of the code or the images i´m trying to push.

### Release version

Version 3.3.1 (x64)

### Operating system

windows 11

### Steps to reproduce the behavior

in the desktop app i commit my changes
press 'push origin'
then the error comes up

### Log files

[2023-09-17.desktop.production.log](https://github.com/desktop/desktop/files/12642631/2023-09-17.desktop.production.log)

**Comment by steveward** [comment]
@Satisfraction this issue is due to the email that was used for commit attribution. See [this article](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address) for reference on how Git uses your email. 

If you go to https://github.com/settings/emails and uncheck the "Keep my email address private" option you should be able to resolve this. See [this article](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/blocking-command-line-pushes-that-expose-your-personal-email-address). I hope that helps! Let me know if you have any further questions.

**Comment by arnvidhr** [comment]
What if not? Can we just edit specific commit email address somewhere on our local filesystem to put right email in it and to commit normally? This is sort of hack, but anyway.  I just navigated via GitHub desktop settings, while I'm not very much Github or Git focused, decided to change an email and caused troubles with my next commit. So as it is only on local repository now, or my file system, on my computer, can I just edit that email and to revert back to previous one, which was ok all the time? Maybe you know which file to add? Why do you offer that people exposed their emails?

**Comment by arnvidhr** [comment]
In my case, it wasn't intentional. I've been working with Github Desktop for a long time and I decided to go through the settings and set my real email there, thinking it's better that way. I just forgot that it can't be used. And I already had pretty serious changes - I pressed commit and this error occurred.

I copied the changed files elsewhere and started looking for how to cancel the last commit, because I didn't want to expose my mail for stupid mistake. Well, after copying the files elsewhere, I clicked exactly - Undo commit in Git Desktop and everything was fixed without blood.

To be honest, I didn't even understand what happened. Slightly disoriented now. I pressed Undo, and it seems that everything returned to the state before pressing Commit, if I remember correctly, and then I just made a new commit with a good email, which I set before, and everything happened beautifully.

I hope it will help someone, to live, without exposing of your email, when no any other options offered on the discussion.

**Comment by bbitarello** [comment]
As @arnvidhr says, you can click undo on that commit. Then, go to GH desktop settings > Git > email and select from the dropdown menu the option that has @users.noreply.github.com at the end. Then try to commit and push again. It worked for me. 
Cheers
