### ISSUE TITLE
Check for Updates doesn't detect latest version

### ISSUE THREAD

**Issue by Justin-JHG** [desktop/desktop#17415]
### The problem

have been noticed it for the last couple releases. 
the release notes says there is a new release, but when clicking on 'Check for Updates' button it won't find the new release.

### Release version

3.3.1

### Operating system

windows server 2016

**Comment by sergiou87** [comment]
Hello! We do staged updates. We manually increase the % of users that get the update depending on the importance of the update and reports we get, that's why it sometimes takes longer than others. Also, what users get the update for every % is random in every update.

Meanwhile if you're in a hurry to get the latest updates, you can <kbd>Alt</kbd> + Click on the `Check for Updates` button will bypass the staged update and get you the latest version.

I hope that helps!

**Comment by Justin-JHG** [comment]
wow, `alt` click, secret button :) 

got it, thank you @sergiou87
