### ISSUE TITLE
Can't Rebase When There's Conflict Along with Submodule Updates in Main Branch

### ISSUE THREAD

**Issue by kevinqfu** [desktop/desktop#17412]
### The problem

When I try to rebase my branch on main branch, if there are both conflicts and some submodule updates, it would fail to rebase. It would try to rebase, but then stuck in a loop, letting me click "continue rebase" again and again.

### Release version

3.3.1

### Operating system

Mac OS 13.5.2

### Steps to reproduce the behavior

1. Make sure your "main" branch has a submodule
2. Create a new branch named "my-branch" based on main branch
3. Update submodule in main branch with some commit A
4. Make some other commit in main branch with commit B
5. Make a commit C in "my-branch" that conflicts with commit B
6. Rebase "my-branch". It fails to rebase.

**Comment by sergiou87** [comment]
I cannot reproduce this: I was able to to rebase, fix my conflicts caused by commit C (and B), and clicked on `Continue Rebase` which effectively continued and finished the rebase successfully 😕 

Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by kevinqfu** [comment]
@sergiou87 actually looks like this is already fixed in my github desktop. I am unable to repro now. Thank you for the quick response!
