### ISSUE TITLE
Scrolling diffs are cutoff after long commit message and description

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#1742]
If a user has a long commit message and description, the diff section is cut off if the user expands the description.

v0.5.8, OS X 10.11.5

Reproduce:
- commit with a long commit msg and description
- Scroll down in the committed diff to expand the description section. The actual diff is buried and user cannot scroll down to see it.

When collapsed all is ok:
<img width="874" alt="screen shot 2017-05-24 at 11 26 56 am" src="https://cloud.githubusercontent.com/assets/14828183/26411767/b76c5a02-4074-11e7-97ef-5045a85ff38b.png">

When expanded, diff section cannot be accessed:
<img width="885" alt="screen shot 2017-05-24 at 11 27 08 am" src="https://cloud.githubusercontent.com/assets/14828183/26411768/b772510a-4074-11e7-8d47-fbc7682f2f99.png">

No logs.

**Comment by niik** [comment]
Good catch @tierninho. We should truncate the commit title and figure out a way to show it as part of an expanded description. This goes back to the long standing action item that me and @donokuda have

> - [ ]  @donokuda and @niik to ponder better ways to show an expandable commit message

We'll have to bring that up at the next design sync up and try to figure something out. I'm gonna put this in the 1.0 milestone for now because we should fix this before going 1.0
