### ISSUE TITLE
Cant find repository

### ISSUE THREAD

**Issue by Juane99** [desktop/desktop#17440]
### The problem

When I try to open a repository in Github Desktop a message that says "Cant find repository" appears

### Release version

3.3.3

### Operating system

Windows 11

### Screenshots

![image](https://github.com/desktop/desktop/assets/33232217/54a0f1a7-0f3c-47e2-927e-44ea0e84d882)

**Comment by steveward** [comment]
Thanks for the report @Juane99. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by Juane99** [comment]
Hello, thank you for your reply. I was looking at the logs and the problem was that I added a folder of 80GB size to the repository. This folder exceeded the 'git status' byte threshold and gave an error. When I remove the folder everything works correctly again. Thanks for your help!

**Comment by steveward** [comment]
Glad to hear things are working now!
