### ISSUE TITLE
Lost stash changes

### ISSUE THREAD

**Issue by glauberdjs** [desktop/desktop#17443]
### The problem

When resolving conflicts between branches, to be able to merge, all changes in stash were lost. Fix this as soon as possible.

### Release version

 3.3.3

### Operating system

Windows

### Steps to reproduce the behavior

Merge branchs
Stash changes
Resolve conflicts
Restore stash changes
all stash are lost

**Comment by steveward** [comment]
@glauberdjs Thanks for the report. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue. 

If the stash was dropped it should be recoverable, see my [comment](https://github.com/desktop/desktop/issues/15912#issuecomment-1380608475) about this.

You can run `git reflog show --all` to include stashes in the reflog to see if it's recoverable from there.
