### ISSUE TITLE
Github Desktop and Web views are completely different

### ISSUE THREAD

**Issue by johnnyroodt** [desktop/desktop#17513]
### The problem

When I log in to Github Desktop I see one list of Repositories:
GLTFUtility, three.js, MaterialX, Unity-URP-Cookbook etc etc. 

But when I log in via the Browser I get a complete different set:
RT3D, EffectiveC, SystemsCafeCudaRuntime, LearnGithub, DigitalSpaces 

It probably got messed up with my personal email address: johnroodt@gmail.com

The one I am using to log into both the Desktop app as well as the Web portal is my professional address:   john@rogamur.com.

Please can you merge these so that I get the same view on the Desktop app as well as the Web portal?

Thanks

### Release version

Version 3.3.3 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Login to Github Desktop using email address:   john@rogamur.com
2. Login to Github Web using email address:   john@rogamur.com

### Screenshots

![github_web](https://github.com/desktop/desktop/assets/63031178/87787861-463e-49fe-b895-f26570f163f0)
![github_desktop](https://github.com/desktop/desktop/assets/63031178/7b24378f-ea97-4c6f-ab76-a03b4e6c9d1a)

**Comment by johnnyroodt** [comment]
Or maybe that's the way it has to be? Maybe I just have to clone my repos to my Desktop via the Github Desktop app?

**Comment by steveward** [comment]
@johnnyroodt thanks for the question. You have to clone your repositories to your local machine in order to get them into GitHub Desktop. If you log in with a different account you will still see repositories from other accounts in the repository list. You can see them the repositories available for your currently logged-in account if you go to `File` > `Clone Repository...`. I hope that helps, let me know if you have any further questions.
