### ISSUE TITLE
Link to global git config

### ISSUE THREAD

**Issue by tristanbea** [desktop/desktop#17544]
### The feature request

I'd like to open the global git config from both the file menu and Options, on the 'git' tab.

### Proposed solution

It's not clear where this file is located (or that it even exists) for new users. This would help with discovery as well as create convenient shortcuts.

**Comment by DylanDevelops** [comment]
I'll try to work on this if this is something we want. I'd argue however, that this is necessary in `Settings > Git` but not needed in the `File` menu but let me know if anyone disagrees!

**Comment by DylanDevelops** [comment]
Would we like a button that when clicked, brings you to the folder containing your.gitconfig file or would we like a box that displays the path to your git config file?

**Comment by tristanbea** [comment]
A path with an adjacent link-out button that opens the folder would be great, IMO.

**Comment by tristanbea** [comment]
Preference for path if only one of those options can be supported.

**Comment by steveward** [comment]
@DylanDevelops thanks for your interest in contributing. I'll add this for us to discuss in our team sync and will get back to you if this is something we want to potentially have worked on.

**Comment by DylanDevelops** [comment]
@steveward perfect! Just keep me posted I'll be around!

**Comment by steveward** [comment]
Thanks again for your interest in working on this @DylanDevelops! We discussed this in our team sync today and are 👍🏻 for a PR. A few things we discussed:

- Rather than adding a new button, we think making the "edit your global Git config" phrase a link to directly open the .gitconfig is a good approach. 
- The link can directly open the global .gitconfig in the default external editor. We think this makes the process more straightforward versus opening in Finder/File Explorer. If no default external editor has been selected the link should not be present.

If you have any questions about this approach let us know!

**Comment by DylanDevelops** [comment]
@steveward Are you able to help me implement this change? I'm a little new to this project so I want to make sure that I do it in a good way!

Git Preferences File and the text needed to edit: https://github.com/desktop/desktop/blob/13ce339f814861d3bac635fe8e4250a070f8d7b8/app/src/ui/preferences/git.tsx#L154

After that, can you help me know how to open a file in the chosen external editor? Sorry for all the questions!

**Comment by tidy-dev** [comment]
👋  If you look on the `IPreferencesProp` in `preferences.tsx`, you will see `selectedExternalEditor` is already passed in and is `string | null`. This can be used to determine whether there should be a link.

An example of when we open files in external editors is for the changed files list or history files list. If you go digging you will find that those use cases have callbacks up to the `onOpenInExternalEditor` method in the `app.tsx`. You will similarly need setup callbacks from the `git.tsx` up to the `app.tsx` with the path to the global git config.

For the global git config path, you may find `getGlobalConfigPath` method  in `git/config.ts` helpful.

Hopefully that is enough to get you going. :)

**Comment by DylanDevelops** [comment]
Sounds good. I am super new to typescript so I think I'm doing it right. I'm not sure what your guys' rules are on having a lot of commits in a pull request, so I don't wanna open one to get your help on it just yet unless that is okay. Otherwise, I can send you guys screenshots here to get some help. Let me know!

**Comment by DylanDevelops** [comment]
@tidy-dev and @steveward,
I left a comment on the draft pull request I created. When you guys get the chance, let me know if you can help me with that one question. Thanks for letting a newbie like me take a shot at something like this! :)

**Comment by Sukhkaur93** [comment]
[](url)
