### ISSUE TITLE
comit

### ISSUE THREAD

**Issue by pedronunes1234** [desktop/desktop#17563]
### The feature request

Não estou conseguindo comitar

### Proposed solution

.

### Additional context

.

**Comment by pedronunes1234** [comment]
.

**Comment by steveward** [comment]
Thanks for reaching out @pedronunes1234 !

Would you mind filling out the rest of the issue template so that we can better understand what is causing the problem you are experiencing? Without that information it will be difficult to help you further. It would especially be helpful if you could upload the log file from GitHub Desktop, which will give more details about the specific error you are seeing. 

To access the log files go to the  menu in GitHub Desktop and select `Help` > `Show Logs...`. The log files are created daily -- please send over a log file as an attachment from a day where you experienced the issue.
