### ISSUE TITLE
PR request changes base branch to main when showing preview screen

### ISSUE THREAD

**Issue by john-lebens-highspot** [desktop/desktop#17571]
### The problem

I need to merge to prod so I create a branch based on prod. 

1. After pushing my commits I click on Preview Pull Request. 
2. This action automatically sets the branch I am merging into as main instead of the branch I am building off of(prod). 
3. I don't realize this change happened so I create my PR. 
4. Then I realize on git that I am trying to merge into main so I have to change it back to prod. 
5. Though my PR is fine on my end, it is not fine on buildkite so I have redo all these steps.

### Release version

Version 3.3.3 (arm64)

### Operating system

Mac OS Sonoma 14.0 (23A344)

### Steps to reproduce the behavior

1. create a branch not based off of main
2. commit some changes
3. Preview pull request
4. Notice that in the preview it automatically sets the branch to merge to is main and not the branch you are working off of

**Comment by tidy-dev** [comment]
@john-lebens-highspot Thank you for the suggestion. I believe it is in the same line of thought as https://github.com/desktop/desktop/issues/15233. Unfortunately, the concept of "updating from a parent branch" or merging into parent branch is not naturally supported by git (the underlying technology of Desktop) via the command line since branches are just references to specific starting commits.
