### ISSUE TITLE
GitIgnore not excluding files and folders

### ISSUE THREAD

**Issue by tooltinker** [desktop/desktop#17584]
### The problem

GitIgnore does not excludes
*,cache
*.exe
*.pdb

in MS Visual Studio 2019

### Release version

3.3.4 (x64)

### Operating system

Windows 11

### Steps to reproduce the behavior

1. "Repository"
2. "Repository Settings"
3. "Git Ignored Files"

### Log files

[2023-10-19.desktop.production.log](https://github.com/desktop/desktop/files/13035390/2023-10-19.desktop.production.log)

### Screenshots

![github Git Ignore not excludes](https://github.com/desktop/desktop/assets/33137452/c6d803c9-4348-46a5-a17a-49e856fad073)

**Comment by steveward** [comment]
@tooltinker thanks for the issue.  If the files have been previously committed to your repository they need to be removed in order to be ignored. You'll need to run this command from the command line:

`git rm --cached <file>`

You should then be able to ignore the files. Let me know if you have any further questions.
