### ISSUE TITLE
Latest branch 

### ISSUE THREAD

**Issue by ond-FelixP** [desktop/desktop#17594]
### The problem

After pulling the latest branch I am getting a push origin when I haven't commited anything in local

### Release version

Version 3.3.3 (x64)

### Operating system

Windows 11

### Screenshots

![commit](https://github.com/desktop/desktop/assets/134945677/b7a50ef1-4251-4ec0-9b41-b94c8a99397b)

**Comment by DylanDevelops** [comment]
![276882949-b7a50ef1-4251-4ec0-9b41-b94c8a99397b](https://github.com/desktop/desktop/assets/48571264/14553358-fed3-47e7-92b3-681766a32171)

You are getting a `push origin` message because changes await push. Sometimes, when you pull, changes need to be made, and this is what it looks like happened with you. However, this isn't a bug with GitHub Desktop, and this issue should be closed.

**Comment by steveward** [comment]
@FelixPhilipCoin like @DylanDevelops mentioned, if a fast-forward is not possible then a merge commit will be created, which is what the "merge branch 'develop'...." commit you are seeing is. This [section from Pro Git](https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging) has a good explanation. I hope that helps!
