### ISSUE TITLE
Cant Commit.

### ISSUE THREAD

**Issue by Chimdi6** [desktop/desktop#17613]
### The problem

The last 2 commits I've saved worked.
But this time I tried to commit, it's a problem.
It took me around 2 hours to try and figure it out when it said, "Error code". But it still doesn't allow me. I even tried redownloading GitHub. But now any change I make doesn't even let me commit nor even show the changes. Can you find out why?

### Release version

3.34

### Operating system

Windows 11

**Comment by steveward** [comment]
Thanks for the report @Chimdi6. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
