### ISSUE TITLE
Not showing remote branches

### ISSUE THREAD

**Issue by jaimelg27** [desktop/desktop#17637]
### The problem

GitHub Desktop is not showing remote branches, although fetch origin is done. The remote repository is from Azure DevOps.

### Release version

Version 3.3.4 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Cloning a Azure DevOps Repository.
2. Fetching origin.
3. Trying to change from master to other branch.
4. No branches displayed on branches menu.

### Screenshots

![image](https://github.com/desktop/desktop/assets/61801163/fcddee71-2f17-44a7-bb5b-26f20c4c0499)

**Comment by jaimelg27** [comment]
The remote repository is from Azure.

**Comment by niik** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

Please take special care to include any details that can help us in troubleshooting this such as screenshots, logs, error messages, custom setups, etc.

Thanks for understanding and meeting us half way :grinning:

**Comment by jaimelg27** [comment]
Added information on initial message.

**Comment by niik** [comment]
:wave: Thanks for filling out the template. Unfortunately there's not much information there for us to be able to troubleshoot with. Could you please select the `Repository` -> `Open In Terminal` menu item and run the command `git branch -a` as well as and paste the output here.

Could you also upload a log file from GitHub Desktop so that I could get some more information about this issue? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue. Thanks!
