### ISSUE TITLE
getting this error message when click on preview pull request button

### ISSUE THREAD

**Issue by ashanftw** [desktop/desktop#17659]
### The problem

getting this error message when click on preview pull request button

### Release version

Version 3.3.5 (x64)

### Operating system

windows 11

### Steps to reproduce the behavior

1. open github desktop
2. click on "preview pull request" button

### Screenshots

![image](https://github.com/desktop/desktop/assets/49266123/5f3ea13c-28c1-4129-837b-d9f8efe3094a)

**Comment by niik** [comment]
Thanks for the report! Could you upload a log file from GitHub Desktop so that I could get some more information about this issue? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue. Thanks!

**Comment by ashanftw** [comment]
[2023-11-02.desktop.production.log](https://github.com/desktop/desktop/files/13239687/2023-11-02.desktop.production.log)


some assets file is missing as i see

fatal: path 'assets/icons/active_icon.png' does not exist in '3ac1e2d31cd6394e90e284939ac3fe3a9c06c7ff^'

(The error was parsed as 32: The path does not exist on disk.)

@niik

**Comment by niik** [comment]
Thanks for the update @ashanftw, I've been able to reproduce this and have published a [reproduction branch ](https://github.com/desktop/desktop/compare/niik/reproduction-17659) (`niik/reproduction-17659`) that can be checked out in Desktop to reproduce this.

I don't have time to look into it further right now but it's specifically about image diffs of deleted images. Here's the stack just before we hit this

![Image](https://github.com/desktop/desktop/assets/634063/2efa7831-d7b0-40c5-ad51-0176f4e5bb11)

https://github.com/desktop/desktop/blob/555274f8818eb26886575fbcfe2878422879d226/app/src/lib/git/diff.ts#L442

It's trying to look up the original image (before deletion) in a commit where it's already been deleted.

cc @tidy-dev since I believe you've got the most context around this logic

**Comment by Karliz24** [comment]
> ¡Gracias por el informe! ¿Podrías cargar un archivo de registro desde GitHub Desktop para poder obtener más información sobre este problema? Para acceder a los archivos de registro, vaya al menú de archivos en GitHub Desktop y seleccione `Help`> `Show Logs in Finder (macOS) or Explorer (Windows)`.
> 
> Los archivos de registro se crean diariamente; cargue un archivo de registro como archivo adjunto del día en el que experimentó el problema. ¡Gracias!

**Comment by FarukNoyon** [comment]
718975707

**Comment by Karliz24** [comment]
9e3b772b8cabbd8cadc7522ebe3dde3279e79d9e
