### ISSUE TITLE
Update causes high disk usage

### ISSUE THREAD

**Issue by sjorford** [desktop/desktop#17667]
### The problem

When Github Desktop downloads an update in the background, it causes up to 100% disk usage making the computer unresponsive

### Release version

3.3.3

### Operating system

Windows 11

### Log files

[2023-11-03.desktop.production.log](https://github.com/desktop/desktop/files/13247339/2023-11-03.desktop.production.log)

**Comment by steveward** [comment]
@sjorford thanks for the issue. Is your local disk nearly full? That would definitely cause this issue, but unfortunately there isn't much we can do from our end for cases like this. We try to keep our installation size as minimal as we can, and we are tracking opting out of auto-updates in https://github.com/desktop/desktop/issues/3410 if you'd like to follow along there.

I'm going to close this out, but let me know if you have any further questions.

**Comment by sjorford** [comment]
Just to be clear, it is the disk *rate* that is 100%, not the free space - I have over 50 GB free. The download/install seems to use a very high rate of disk I/O which stops all other programs from responding. Lots of other programs autoupdate and I don't see similar behaviour with any of them. Let me know if any technical info would be useful.

**Comment by steveward** [comment]
Apologies, I didn't realize you were referencing disk utilization. We've had quite a few users in the past hit issues when they run out of space during updates/installation due to having smaller SSDs. This is the first case I've seen of disk utilization issues being reported. I just tested an update on a Windows 11 machine and the update peaked at 4%, so I'm not sure what would be causing this on your machine.

Is there any antivirus/security software on this machine that could be causing this? Those are common culprits of performance issues.

**Comment by sjorford** [comment]
Good thinking - I've whitelisted "C:\Users\Stuart.Orford\AppData\Local\GitHubDesktop\Update.exe" in my AV, will see if that makes a difference.
