### ISSUE TITLE
GitHub desktop login error

### ISSUE THREAD

**Issue by alien3456J** [desktop/desktop#17679]
### The problem

Im trying to log in to github desktop and I get an error "Not enough memory resources are available to process this command." This happens when you log in from the desktop redirecting you to the webpage you're logged in from. 

I suggest: make it to where you can manually log in with your username and password. 

![Login issue](https://github.com/desktop/desktop/assets/98231250/38ee3a2d-eb3d-45b4-abde-3cfe7f813d14)

### Release version

Version 3.3.5 (x64)

### Operating system

windows 11

### Steps to reproduce the behavior

1. click on login within the github desktop 
2. redirects you to github online and asks you to login
3. brings you back to the desktop version and pops up with the error "Not enough memory resources are available to process this command." 

### Screenshots

![Login issue](https://github.com/desktop/desktop/assets/98231250/ce885efb-38b0-4aa0-abcf-e96016b5ff46)

**Comment by DanielYamini** [comment]
Unsubscribe

**Comment by steveward** [comment]
Thanks for the report @alien3456J. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
