### ISSUE TITLE
After stash all changes has been disappear

### ISSUE THREAD

**Issue by SudhanshuAESS** [desktop/desktop#17692]
### The problem

After stash all changes has been disappear

### Release version

 3.3.5 

### Operating system

windows

**Comment by steveward** [comment]
Thanks for the issue @SudhanshuAESS. If the stash was dropped it should be recoverable, see my [comment](https://github.com/desktop/desktop/issues/15912#issuecomment-1380608475) about this. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.

You can run `git reflog show --all` from the command line to include stashes in the reflog to see if it's recoverable from there. Let me know what that shows.
