### ISSUE TITLE
Not Opening with double from Desktop

### ISSUE THREAD

**Issue by Zero2Back** [desktop/desktop#17719]
### The problem

Not Opening with double from Desktop

### Release version

Version 3.3.4 

### Operating system

Windows 10

**Comment by steveward** [comment]
Thanks for reaching out @Zero2Back!

Would you mind filling out the rest of the issue template so that we can better understand what is causing the problem you are experiencing? Without that information it will be difficult to help you further. It would especially be helpful if you could upload the log file from GitHub Desktop, which will give more details about the specific error you are seeing. 

To access the log files go to the  menu in GitHub Desktop and select `Help` > `Show Logs...`. The log files are created daily -- please send over a log file as an attachment from a day where you experienced the issue.
