### ISSUE TITLE
Feature: Prune local squash-merged branches

### ISSUE THREAD

**Issue by kamranayub** [desktop/desktop#1771]
Related to #750 

### Description

The Squash and Merge feature on GH is super nice for maintaining clean master history and we use it for every PR we deal with. The downside is it's a huge pain to prune local branches because Git doesn't realize we merged it. I feel like this *shouldn't* (?) be a problem with a GH client though, because it could query to determine whether or not the branch was squashed or even examine the commits to determine if there were new local commits vs. what was squashed. You guys know more about what'd be possible but it feels like it's doable.

This would be a fantastic time-saver feature!

**Comment by joshaber** [comment]
Thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I'm going to add the `future-proposal` label to this issue and close it out, so that we don't get overwhelmed with our backlog! We'll revisit these as part of our next planning session.

**Comment by billygriffin** [comment]
Hi @kamranayub thanks so much for the suggestion. We're starting work on #750 and we're going to think about this in the context of that one. Depending on the technical complexity, we may be able to account for this use case. But since we are considering it there, I'm going to remove `future proposal` here. Thanks again!
