### ISSUE TITLE
Tiny Ask: More space for current branch name

### ISSUE THREAD

**Issue by albertbori** [desktop/desktop#17720]
### The feature request

In a large organization, there is often need for more descriptive branch names.

In Github Desktop, the "Current Branch" section in the header cuts off longer branch names, even when there is plenty of screen real estate:
![image](https://github.com/desktop/desktop/assets/1742709/14afcc1f-9115-426e-a796-216dfcfdd1a7)
![image](https://github.com/desktop/desktop/assets/1742709/9ad5774a-bb64-47ce-82aa-0d5aba8e1709)

### Proposed solution

Options:
a) Use a dynamic width based on the content (with a responsive maximum)
b) Increase the static width for larger screen-sizes.

**Comment by steveward** [comment]
Thanks for the issue @albertbori. This is being tracked in https://github.com/desktop/desktop/issues/4569, and there has been some discussion about making these resizable. See https://github.com/desktop/desktop/issues/17388#issuecomment-1770801890 -- that issue is specifically about the fetch/pull button, but the refactor would make both resizable. 

Since this is being tracked elsewhere I'm going to close this out, but thanks for the feedback!
