### ISSUE TITLE
Github Desktop not showing details under commits

### ISSUE THREAD

**Issue by noisefloor-ltd** [desktop/desktop#17727]
### The problem

Hello,

I'm new to using GitHub. I'm having an issue where the desktop application isn't showing details of added .uassets/audio files for a commit. When I initially installed and made changes to the .gitattrubutes it listed out what I had added but anything from UE4 it wont show as a listed change.
![github help](https://github.com/desktop/desktop/assets/88103519/1ecf143b-066b-42a1-a2ec-61e13cdd99af)

Can someone help? 

### Release version

3.3.5

### Operating system

Windows 11

**Comment by steveward** [comment]
@noisefloor-ltd thanks for the issue. Can you check the .gitignore file of this repository to see if that could be causing these files to be ignored by Git? You can check this in GitHub Desktop by going to `Repository` > `Repository Settings` > `Ignored Files`.

**Comment by noisefloor-ltd** [comment]
@steveward yeah! I'm not seeing anything obvious here is what is listed:
Binaries
DerivedDataCache
Intermediate
Saved
.vscode
.vs
*.VC.db
*.opensdf
*.opendb
*.sdf
*.sln
*.suo
*.xcodeproj
*.xcworkspace

**Comment by steveward** [comment]
I think I may have misunderstood the initial issue -- it looks like what you're referencing is that the diff isn't showing, not the file itself.

Since the file is being tracked by LFS it won't show the diff, but you can try to configure it to diff the file if it is a text file. See this:

https://github.com/git-lfs/git-lfs/blob/main/docs/man/git-lfs-faq.adoc#working-with-git-features

I hope that helps! I'm going to close this out, but let me know if you have any further questions.
