### ISSUE TITLE
Merging branch corrupted my RC2 file

### ISSUE THREAD

**Issue by ajtruckle** [desktop/desktop#17732]
### The problem

I merged my branch and it corrupted myrc2 file in Visual Studio. It was all gibberish. I had to copy from backup.

### Release version

Version 3.3.5 (x64)

### Operating system

Windows 11

### Steps to reproduce the behavior

As already stated

### Log files

[2023-11-15.desktop.production.log](https://github.com/desktop/desktop/files/13370302/2023-11-15.desktop.production.log)

### Screenshots

Sorry,  I already restored my backup

### Additional context

RC2 file is a secondary resource file - text based. Although GD refuses to show its contents. I do have a `.getattributes` file with:

`*.rc2 text`

Makes no difference.

**Comment by steveward** [comment]
Thanks for the issue @ajtruckle. This sounds like more of an underlying Git issue, or a Visual Studio issue. I'm not familiar with .rc2 files, but it looks like you have already discussed the diff issue in https://github.com/desktop/desktop/issues/16589.

Since you were able to resolve this issue I'm going to close this out.

**Comment by ajtruckle** [comment]
I have the same problems with my RC file now. It shows up as a binary file in GitHub Desktop. I had a corruption after merging of a branch and had to backtrack to a backup file.
