### ISSUE TITLE
Integrate wiki repository

### ISSUE THREAD

**Issue by moritztim** [desktop/desktop#17768]
### The feature request

Check if each repo has a wiki associated with it and allow the user to clone and open the wiki. Then somehow associate the two.

### Proposed solution

This would be a great usability improvement making everything feel more connected

**Comment by steveward** [comment]
Thanks for the issue @moritz-t-w. At this time wikis aren't something that we will likely prioritize, and there are a number of longstanding issues around supporting them that would need to be addressed before any further integration (like https://github.com/desktop/desktop/issues/3839). I'm going to close this out since it isn't something that's on our radar, but we can revisit this again in the future if we continue to hear feedback. Thanks for letting us know you'd like to see this implemented.
