### ISSUE TITLE
Setting to disable the automatic file selection

### ISSUE THREAD

**Issue by grizzlydev-sarl** [desktop/desktop#17778]
### The feature request

I'd like very much to have a mean to disable the automatic selection of files.

Problem: I have a bunch of files that I've modified, and I don't necessarily want to commit them all (if any at all), but Github Desktop will automatically select files to prepare a commit.

Example: If I startup Github Desktop, it will select all the files immediately. I then have to uncheck all of them, and reselect the one I want to commit. 

Worst: sometimes after a commit, Github Desktop will randomly select some files to prepare the next commit. I don't always notice because the selection isn't always visible if it's lower in the scroll box.

I don't want that. I don't need that. 
It's error prone, and I've had a few problems where some changes were commited (and pushed) while they weren't supposed to.

### Proposed solution

Could you please add a setting to disable the automatic selection of changed files?

### Additional context

Version 3.3.5 (x64)
MacOS Big Sur

**Comment by niik** [comment]
Hey @grizzlydev-sarl, thanks for reaching out! I appreciate the detailed description of your motivation for being able to toggle this option.

I'm going to refer you to https://github.com/desktop/desktop/issues/1788 which seems to be a similar request and more specifically to the answer provided in https://github.com/desktop/desktop/issues/1788#issuecomment-463857779, replicated below:

> I completely understand the argument here and I'm sympathetic to it philosophically. However, after talking through this based on our experience to date, we just haven't seen this come up as a frequent pain point for many users. If we swapped the default, a ton of users who enjoy the way it works today would be furious, and generally we prefer to keep toggles to only the highest impact things. I totally understand how this can cause mistakes, but given that it's quick to undo a commit if something unexpected is committed, it's also fairly easy to back out of. For now, I'm going to close this issue to communicate that we don't intend to work on it.
>
> However, we definitely think the concept has validity and we're open to changing our minds as we continue to learn more from users. Thanks again for the feedback.

I'm going to close this issue out in favor of https://github.com/desktop/desktop/issues/1788 but please add a 👍 reaction in that issue to signal that this is something you'd like to see. We continuously look at most active issues (closed or otherwise) and revisit decisions.
