### ISSUE TITLE
Scroll on Commit Diff keeps jumping around

### ISSUE THREAD

**Issue by madhaven** [desktop/desktop#17776]
### The problem

The scroll bar and content on the diff view of a file in the commit selected from the history tab is glitching.

### Release version

Version 3.3.5 (x64)

### Operating system

Windows 10 x64

### Steps to reproduce the behavior

I use a unified view and I don't have my "hide whitespaces" checked.
I'm checking out my history, I select a commit, I select a file and I am watching the diff.
As I scroll down, I expand some of the hidden lines by clicking the arrows on the left margin on the diff code.
when I try to scroll down fast, the scrollbar and the diff scroll position glitches and flickers across a different position.

**Comment by niik** [comment]
Hey @madhaven, thanks for reaching out. Does this only happen when you expand hidden lines in a diff? Do you think you could capture a video of the behavior?

We have recently made changes to the rendering of unified diffs that I'm certain is responsible for this behavior

**Comment by tidy-dev** [comment]
I was able to reproduce this:

I found a particularly long file so that the expand hunk down button will work multiple times. I expand down once and scroll to see expander again, then, hit expand down again, now, the top of the diff will be at line x, if I try to scroll down quickly to see the expander again, it will scroll for a second and then jump back to line x and then continue scrolling. 

https://github.com/desktop/desktop/assets/75402236/2fc0a97a-577b-4178-94b7-26179eafaee0

**Comment by tidy-dev** [comment]
Also noticed on same file after same repro steps if I was scrolled all the way to the bottom, and then I use my keyboard to scroll up. Just hit the keyboard button 2 times, it all the sudden jumps to the top.  Not sure if this is the same issue from the other one above, but I believe this one is a regression from https://github.com/desktop/desktop/pull/17259 of which I have another PR https://github.com/desktop/desktop/pull/17499 open that moves away from the auto focus approach for other buggy reasons. 


https://github.com/desktop/desktop/assets/75402236/4efb5e80-468d-4daf-8e57-c19e3264ef67

**Comment by madhaven** [comment]
@steveward , @tidy-dev 
Thanks for keeping up.
I was not able to provide inputs

@tidy-dev 
I was curious how you got to the root of the problem and fixed it.
I would also like to know the process.

**Comment by tidy-dev** [comment]
> I was curious how you got to the root of the problem and fixed it.

Because I caused it. 🙈   I was recently working on keyboard accessibility of the expand buttons and using `autofocus` property to focus the next one after expansion. It worked great when there are buttons on the screen to focus; however, autofocus will cause scrolling to "scroll to view" of an element. Combined with virtual scrolling  applied on diff, it caused this jumpiness. The fix that was just shipped to [beta](https://desktop.github.com/beta/) was to refactor to a better approach that keeps track of the buttons that are currently rendered by the virtual scrolling and if moves focus to the closest one. This should prevent attempts to scroll to out of screen buttons.

**Comment by madhaven** [comment]
thank you @tidy-dev 
That was educative.
