### ISSUE TITLE
submodule https can't push commit because of auth fail

### ISSUE THREAD

**Issue by tooOpen** [desktop/desktop#17777]
### The problem

![이미지 (1)](https://github.com/desktop/desktop/assets/9246872/498dc4c1-2eb3-4049-8edf-970ae964e283)

my project has submodule.
some of my team can't push submodule commit!!
possible to pull but not push!
above popup came out.
I need your help
I recommended github desktop to my team.
and now my team will ** me
please let me know how to solve this problem.

I already read below issue page
https://github.com/desktop/desktop/issues/16023
but this can't help me 

pleeeeeeeeeeeeeeeeeeeeeeeease
help me!!

### Release version

3.3.1

### Operating system

win10

### Steps to reproduce the behavior

submodule push

### Screenshots

![이미지 (1)](https://github.com/desktop/desktop/assets/9246872/ce26b403-2750-4f44-963f-bc4e26785837)

**Comment by steveward** [comment]
Thanks for the report @tooOpen. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
