### ISSUE TITLE
not getting the option to add path to environment when installing github on dekstop

### ISSUE THREAD

**Issue by sea-vt** [desktop/desktop#17816]
### The problem

I am trying to make an update to my quarto blog but every time I make a commit through github desktop, I get an error saying "untacked files, use 'git add'...", so I try doing that, but when I reinstall github (after uninstalling and deleting all github desktop associated files, I dont get the option to add the path to environment like I should. and get the same error when updating my blog

### Release version

3.3.5

### Operating system

windows 11 home x64

### Screenshots

<img width="456" alt="git error" src="https://github.com/desktop/desktop/assets/143035445/90af87c2-08c7-40d8-b7b7-b59a914c855a">

**Comment by steveward** [comment]
Thanks for the report @sea-vt. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
