### ISSUE TITLE
Keep getting this when trying to clone 

### ISSUE THREAD

**Issue by MsIndigoChan** [desktop/desktop#17811]
### The problem

![image](https://github.com/desktop/desktop/assets/114777640/9302791b-5fd2-48bf-be4f-3da78a251dc0)

### Release version

Version 3.3.5 (x64)

### Operating system

windows 11

**Comment by steveward** [comment]
Thanks for the report @MsIndigoChan. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
