### ISSUE TITLE
Remote Disconnected

### ISSUE THREAD

**Issue by EmaaMeta** [desktop/desktop#17833]
### The problem
Hi,

I'm getting the error "error: the remote disconnected. Check your internet connection and try again" when pushing files to GitHub. This error appears after the files have been compressed to 100% and writing begins, typically at 99% or 98% progress.

I've tried several solutions found online, including:

Using different internet providers and Wi-Fi networks
Confirming no proxy or VPN usage
Logging out and logging back into GitHub
Clearing the Git cache using git config --global --unset credential.helper and git config --global --unset url."https://github.com".insteadOf
Enabling firewall and security software
Unfortunately, none of these solutions have resolved the issue. I've noticed other users reporting the same problem.

I would appreciate any help in resolving this issue.

Regards,

### Release version

Version 3.3.5 (x64)

### Operating system

Windows 11 Home

### Steps to reproduce the behavior

push to origin after adding all file in show in explore

**Comment by steveward** [comment]
Thanks for the report @EmaaMeta. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue. 

That should hopefully give some more information about the underlying network error.

**Comment by EmaaMeta** [comment]
[2023-12-06.desktop.production.log](https://github.com/desktop/desktop/files/13590753/2023-12-06.desktop.production.log)
attach log as requested

**Comment by steveward** [comment]
It looks like Git operations are timing out due to the size of the push:

```
error: RPC failed; HTTP 500 curl 22 The requested URL returned error: 500
send-pack: unexpected disconnect while reading sideband packet
```

If you are having issues pushing a set of changes you can try using the command line to push a subset of commits by using the following command:

`git push origin commit-SHA:branch`

For example, if you have three commits A (4d3bf9) - B (e55b5f) - C (c109e0) and wanted to push A and B to your `main` branch you would run this command:

`git push origin e55b5f:main`

You could also try switching to using SSH to see if you have better success. See [this guide](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent) for setting up a new SSH key.

You will also need to change the URL of your repository to use SSH. You can do this in GitHub Desktop by going to `Repository` > `Repository Settings` > `Remote`. You will want the URL to look like `git@github.com:<user>/<repo>.git`. 

I hope that helps! I'm going to close this out as this is a connection problem and not a specific issue with GitHub Desktop, but let me know if you have any further questions.

**Comment by eliasrafaael** [comment]
eu tambem tenho esse problema
