### ISSUE TITLE
Getting a 503 error

### ISSUE THREAD

**Issue by probeman** [desktop/desktop#17850]
### The problem

Trying to update the repository from GitHub desktop and getting this error:

fatal: unable to access 'https://bitbucket.org/probeman/probe-software-probe-for-epma.git/': The requested URL returned error: 503

### Release version

3.3.6

### Operating system

Win 11 pro

### Steps to reproduce the behavior

Click Push Origin

**Comment by steveward** [comment]
Thanks for the issue @probeman. The 503 error indicates the service is unavailable, so this is likely something on Bitbucket's end. I would recommend reaching out to them if you are having issues. If you can access the repository via the command line and not GitHub Desktop, it would be helpful if you could upload the log file from GitHub Desktop so that we could get some more information about the error.

To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue. 

I'm going to close this out, but let me know if you're having specific problems using GitHub Desktop.
