### ISSUE TITLE
I rename the file name. But when I stash and restore it again, the rename feature disappears.

### ISSUE THREAD

**Issue by mehmet-erdogdu** [desktop/desktop#17860]
### The problem

I rename the file name. But when I stash and restore it again, the rename feature disappears.

### Release version

3.3.5

### Operating system

Windows 11

### Screenshots

![image](https://github.com/desktop/desktop/assets/44897996/7f0e6ce1-04e8-4183-8e6e-fc08b684baf4)
stash all changes
after
restore
![image](https://github.com/desktop/desktop/assets/44897996/25db5b95-a160-4265-956e-d76ce84f5ee4)

**Comment by steveward** [comment]
@mehmet-erdogdu thanks for the issue. I did some digging into this and it looks like it's because we don't use the --index flag when restoring the stash. From the Git manual:

```
If the --index option is used, then tries to reinstate not only the working tree's changes, but also the index's ones. However, this can fail, when you have conflicts (which are stored in the index, where you therefore can no longer apply the changes as they were originally).
```

If you commit the changes you'll notice the rename is preserved, so I'm going to close this out as it's not something we'll likely change at this time.
