### ISSUE TITLE
not registering the commits and updates on the Github repository online

### ISSUE THREAD

**Issue by Shahbi88** [desktop/desktop#17877]
### The problem

The app is not communicating the commits to the repository online. I have been committing multiple things on VS code and updating on Github desktop app but when I went to the website, the repository stopped showing my last commits and updates.

### Release version

Version 3.3.6 (arm64)

### Operating system

mac

**Comment by steveward** [comment]
Thanks for the report @Shahbi88. Could you share a few more details or screenshots of the issue you are experiencing? Are you pushing your changes in GitHub Desktop and encountering an error?

Could you also upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by Shahbi88** [comment]
Hi Steve

Thanks for your reply. I was able to get to the bottom of the issue.

Best wishes

Rihab

On 15 Dec 2023, at 15:14, Steve Ward ***@***.***> wrote:


Thanks for the report @Shahbi88 <https://github.com/Shahbi88>. Could you share a few more details or screenshots of the issue you are experiencing? Are you pushing your changes in GitHub Desktop and encountering an error?

Could you also upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by steveward** [comment]
Glad to hear things are working now!
