### ISSUE TITLE
Feature Request: option to opt-out auto check changed files

### ISSUE THREAD

**Issue by 1pete** [desktop/desktop#1788]
### Description

Currently when you change file, it will be appeared checked in Changes tab.

I know this is a good feature but it would be nice if there is option in Preferences to opt-out this feature.

### Version

**GitHub Desktop version:** 0.5.8

**Comment by joshaber** [comment]
I wonder if we could be smarter about this. Maybe if the user unchecks all files, we remember that and don't check new files? I'm not sure if that'd be confusing or make sense.

**Comment by alanaasmaa** [comment]
+1 One for thisone too. I was using SourceTree but now i have used Github Desktop for this week.

This feature is one that annoys me most. Im used to manually check what i want to commit.

**Comment by shiftkey** [comment]
@xgdgsc commented in #4835:

> Currently whenever I restart github desktop, it would be started in a status of checking all of the untracked files in that repo.
> ...
> The default should be not checking any file or remember the previous state. Because usually when you don' t have a complete gitignore file (and don' t bother to add in many cases) , you would get a lot of untracked files, and when I want to commit some file, I now have to uncheck all and then select the files I need after every restart. The default behavior for most git GUIs I used is checking no file.
> ...
> For example, sourcetree, gitkraken and smartgit doesn' t have that "checkbox" and when I want to commit I only have to launch the app, select those changed files and do the commit, while I have to first uncheck all when using github desktop. They show the staging status more clearly, which is replaced by the checkbox here. Default to selecting those tracked modified (not selecting untracked) files on launch would be good to me (sourcetree does this, if I remember right).

**Comment by orbitrod** [comment]
It would be nice to have this feature.  I find myself accidentally committing files all the time, because I forgot to uncheck them.

**Comment by Tswiggs** [comment]
Bump!  I recently switch to github client from sourcetree and this is a real pain point for me.  I always have untracked files that I don't want to commit.  I feel that having this default to true is the opposite of how a developer should go about staging files, they should be opt in and require the dev to explicitly say "i want this file".  When you have the default behavior select all, it encourages thoughtlessness.

**Comment by billygriffin** [comment]
Hi folks and thanks @Tswiggs for the friendly bump. I completely understand the argument here and I'm sympathetic to it philosophically. However, after talking through this based on our experience to date, we just haven't seen this come up as a frequent pain point for many users. If we swapped the default, a ton of users who enjoy the way it works today would be furious, and generally we prefer to keep toggles to only the highest impact things. I totally understand how this can cause mistakes, but given that it's quick to undo a commit if something unexpected is committed, it's also fairly easy to back out of. For now, I'm going to close this issue to communicate that we don't intend to work on it.

However, we definitely think the concept has validity and we're open to changing our minds as we continue to learn more from users. Thanks again for the feedback.

**Comment by cameron-elliott** [comment]
Just another enthusiastic vote for this idea. Not a sourcetree user, just used to the other model, where you must click each hunk to commit it, but I am getting better at 'git reset --soft HEAD~1'.
Really love Desktop, thanks.

**Comment by xgdgsc** [comment]
Automatically checking binary new file is plain stupid.

**Comment by nguyentrong101094** [comment]
This is a pain for me. Why can't it be a toggleable option? If any users want it off by default, they can turn it off.
I'm used to separating my changes to multiple commits. I will not commit all of my changes in 1 single commit.

**Comment by Taitava** [comment]
I think this feature is crucial.

> I totally understand how this can cause mistakes, but given that it's quick to undo a commit if something unexpected is committed, it's also fairly easy to back out of.

There can be cases when I do not notice that something extra was committed right after making the commit. Then I come back a week later and wonder why a commit contains changes that should not be there. Also, how does undoing a commit work if you have already pushed the commit to another repository?

For me, lacking the possibility to turn off auto selecting changes is a show stopper. I have to use other tools instead of Github Desktop until this is fixed, it affects too much my workflow. Sad, because Desktop feels nice and modern otherwise.

**Comment by capatosta** [comment]
Bump for this issue. Simple toggle 'Automatically stage changes' would be great.

**Comment by deanna-cooney** [comment]
> If we swapped the default, a ton of users who enjoy the way it works today would be furious

We're not asking for the default to change, just to be able to toggle it.

Sourcetree was having problems with the git hooks on a repo i work on so i swapped to GitHub Desktop last week. But this has been a major pain point for me and will likely result in me going back to Sourcetree. I'd prefer to be confident in what is staged and inconvenienced actually committing than concerned i've committed the wrong code and then waste time doing a second review post commit and possibly having to deal with fixing mistakes. Quite frankly it's extra stress i don't need.

FWIW, i do have another issue with GitHub Desktop. But this one is far more grievous than the other. If this one were fixed i could live with the workaround i've come up with for the second issue.

> we just haven't seen this come up as a frequent pain point for many users.

Just thought i'd point out there may be many who try GitHub Desktop, get frustrated by this behavior on their first commit, and go back to their old Git GUI client without reporting why. I almost did.

**Comment by jdeboer** [comment]
@billygriffin Please can we have a toggle added to the option so we can choose to turn off automatic staging of changes if we want? Since the automatic staging was introduced I have all too often found myself accidentally committing changes that I didn't intent to commit, or sometimes changes sneaking in half way through writing my commit message (e.g. if a file was added or changed in the background) - having to go back to undo commits because of this is painful.

**Comment by palhal** [comment]
After trying numerous graphical git replacements I landed on GitHub Desktop. I really like the modern and simpe design. However, the decision to automatically check changed files surprises me.

I often make temporary changes for debugging (eg log output). With the current behavior it's easy to accidentally include such changes in a commit. A new toggle to change the current behavior would be really nice. It also sounds like something that's trivial to implement.

**Comment by mycalingram** [comment]
> Just thought i'd point out there may be many who try GitHub Desktop, get frustrated by this behavior on their first commit, and go back to their old Git GUI client without reporting why. I almost did.

Just wanted to point out, this is exactly the case for me. I mostly use git command line since my preferred git client is not on my companies approved software list anymore. However, it's still useful to me to use some kind of GUI for times when I have made changes to many files and I want to quickly review the changes before I create a pull request.

>  If we swapped the default, a ton of users who enjoy the way it works today would be furious, and generally we prefer to keep toggles to only the highest impact things

This stance is basically alienating yourself from users coming from other clients or command line since your client functions in the opposite way of the default git behavior. A simple toggle would accommodate both your current userbase and new conversions.

**Comment by CreepyGnome** [comment]
@billygriffin 
> I completely understand the argument here and I'm sympathetic to it philosophically. However, after talking through this based on our experience to date, we just haven't seen this come up as a frequent pain point for many users. If we swapped the default, a ton of users who enjoy the way it works today would be furious, and generally we prefer to keep toggles to only the highest impact things. I totally understand how this can cause mistakes, but given that it's quick to undo a commit if something unexpected is committed, it's also fairly easy to back out of. For now, I'm going to close this issue to communicate that we don't intend to work on it.

First I don't think anyone asked for this change to be the new DEFAULT the title even states "opt-out" as the request. Leave the current functionality as the default just allow your users who hate this default functionality to stop it. Trust your users and give them advance checkboxes and settings to twiddle to make GH Desktop work how they like to work.  This approach can make a number of users happy and maybe bring back others who left because GH not willing to provide advanced settings to tweak something that is important to a set of users.

I know I am one of those users who checks in every 6 months or so to see if you have "fixed" a number of blocking issues that keep me from using GH Desktop in my workflow.  This is one of the few issues remaining that is blocking me really from making this my GUI tool to use side by side with the CLI.

The approach GH has taken to this tool feels like you don't want advanced users, you want ones who use a tool as is and if they don't like that then don't use the tool. I know it's a free tool, however, you alienate a large group of GIT users who what to have a powerful advanced git GUI.

**Comment by nguyentrong101094** [comment]
this program is open source? if there is anyone who forks this project and can add this option to it, I'd be so grateful.

**Comment by danaysi** [comment]
Maybe default it to "true" to check all the file changes but give us a preference where we can default it to uncheck all always and manually add it ourself.  I got in trouble with this several times already at work cause i forget to uncheck all the files

**Comment by Dhranios** [comment]
I'd like to see this on a per-file basis; kind of like gitignore, but then unchecking. There's some files I don't want auto-checked, but there's others that I do want auto-checked.

**Comment by twarfield** [comment]
Same here; don't understand why this can't be a toggle-able option.

**Comment by JordyDeGroeve** [comment]
Still not possible? 😞
TBH, allowing to toggle (but still keeping the default) would greatly improve the workflow for many devs.

**Comment by tedmiston** [comment]
This is such an insane default for an otherwise great GUI Git client.

No other Git client auto stages all files from changes.  Calling it a feature is such a huge stretch... a feature that's a footgun by default is a _bug_.

This is a huge pain point that leads me to having to undo commits in GitHub Desktop every single day to remove files that shouldn't have been staged when making multiple commits in quick succession.

All we need is one tiny checkbox in `Preferences > Advanced` for "Disable Auto-stage".

**Please consider your more advanced users that are coming from other Git clients experimentally trying GitHub Desktop to see if it's worth further adoption.  This is a big enough pain point for me that I'll probably go back to Tower personally until the bug is fixed.**

**Comment by bardouni** [comment]
I uncheck +10 files to know exactly what i check
I notice that i need to update something 
I go to update it 
Im back and yay, now I have to uncheck everything again and start over.
I always give up on GithubDesktop and go back to sourcetree because of this

**Comment by Taitava** [comment]
@bardouni I can totally relate to this.
`auto check !== commit what a user wants to commit`
`auto check === commit what a program wants to commit`

**Comment by arielaco** [comment]
Just want to echo @tedmiston

**Comment by nguyentrong101094** [comment]
at this point, it's better to fork Github Desktop and code it yourself rather than begging the developer to add a simple function.
[Fork](https://fork.dev/) is a better alternative for folks who wants to manually select what they want to commit.

**Comment by tedmiston** [comment]
@arielaco I appreciate that.  Unfortunately I've reported several bugs and odd behaviors of this Git client here and the maintainers just ignore or close everything and don't actually listen to their users or "make something people want".

It's interesting how GitHub can make some software that's pretty good, builds on user feedback, reaches mass adoption (even winning its market)... and then with GitHub Desktop do a complete 180 and (1) regularly annoy most of its users by behaving in unconventional and idiosyncratic ways, (2) just straight up ignore all user feedback wrt said diversions, and (3) be incompatible with GitHub's one of two ways to store repos.

This client could become good, but whoever controls it inside GitHub seems to be staunchly resisting actually making any changes to improve the UX based on user feedback, even when it is now many users, very loudly.

Unfortunately, I think it will take either a fork or just switching to a new client.

In theory, this product is "maintained" and regularly pumps out frequent releases; in practice, GH has built a bike with training wheels, their userbase has become more knowledgeable and advanced and yet they refuse to take the training wheels off.

**Comment by agata-zk** [comment]
+1. Opt-out should work both for checking changed files and adding new files.

I came here after having to deal with accidentally added+committed sensitive file (using GitHub Desktop to which I recently switched) and seeing github's recommendations on [avoiding accidental commits](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository#avoiding-accidental-commits-in-the-future). 

How ironic that you advise against using commands like `git add .` and recommend using this UI client - when the client itself doesn't have the opt-out from this behaviour.

**Comment by dvankley** [comment]
Bump. Accidentally committed some sensitive data yesterday, and removing it is a giant pain. Would much prefer an option for making file staging opt-in.

**Comment by GaborNBNL** [comment]
@billygriffin
> Hi folks and thanks @Tswiggs for the friendly bump. I completely understand the argument here and I'm sympathetic to it philosophically. However, after talking through this based on our experience to date, we just haven't seen this come up as a frequent pain point for many users. If we swapped the default, a ton of users who enjoy the way it works today would be furious, and generally we prefer to keep toggles to only the highest impact things. I totally understand how this can cause mistakes, but given that it's quick to undo a commit if something unexpected is committed, it's also fairly easy to back out of. For now, I'm going to close this issue to communicate that we don't intend to work on it.
> 
> However, we definitely think the concept has validity and we're open to changing our minds as we continue to learn more from users. Thanks again for the feedback.

You seem to be the one to determine that this will not be fixed, so I will address you.

This is a problem that every developer I currently work with finds inexcusable, and forces them to find other graphical Windows GIT clients.
You do not seem to understand the argument here, and seem to ignore everything that explains it clearly and supports the position of many, many more than you see here.
One of the reasons you do not seem to find enough users with this problem to determine it is a frequent pain, is that people see reactions like yours and drop this client immediately, knowing that it is useless to want decent software and a decent team to maintain it when they have to rely on you.

It is not the default for any other client I have seen to auto select all files to commit, the default is to have to explicitly select the files and/or folders that need to be committed.
This is all explained by others, and you have been given the chance to enhance the app as to expand the userbase, but instead your argument against is that there are not enough people coming to you to say this is a problem and misunderstanding the request so it is unreasonable.

In any case, with any software, it should be a tool, doing only what it should do, and if it should do more, it should do it like the user would do it.
The software should never go against the wishes of the user, it should never get to decide for the user.

As someone else already said:

@Taitava:
> @bardouni
> I can totally relate to this.
> `auto check !== commit what a user wants to commit`
> `auto check === commit what a program wants to commit`

**Comment by danaysi** [comment]
A simple setting to set this as default or not would solve the problem.

--
Regards,
Dana Garcia
Web Developer
786-325-3789

**Comment by tabstan4** [comment]
adding another +1 to this request. I tried GitHub Desktop out a couple years ago, and went back to other clients because of this behavior. Thought I'd try it out again today, and nope. Think I like the rest of the app, but this is a deal killer. Guess I'll try it again in a couple more years.

**Comment by Taitava** [comment]
I have been subscribing to this feature request since Dec 20, 2020, and hoping for the decision to change. So it's been almost fours years now. I tried GitHub Desktop back then, and have waited for this before continuing using it. 

The request was opened in May 2017 (and closed 2019), so just a couple of years and it will be ten years old. It's not hard to predict that on the day of the 10th anniversary, this request will still be closed and unimplemented.

I'll hit the 🔕 **Unsubscribe** button now.

```diff
- 1 potential user
```

**Comment by mertasan** [comment]
I'm really surprised this feature hasn't been added after all this time. As of today, I’m ditching GitHub Desktop just because it’s missing.

**Comment by ian-ellis** [comment]
It would be great if there was also a way to actually stage changes. "Checking" a file doesn't actually stage the file. If you run `git status` from the cli those "checked" files are not staged. As someone who likes to use git guis for visual things like staging hunks and lines, viewing history etc then switching to the cli to commit, so i can use flags like --fixup, this is a bit of a miss for me. Its really strange to have the behaviour of a gui work the opposite way to the cli

**Comment by borgbean** [comment]
Unfortunate that this is still such a huge problem. I would highly recommend that anyone reading this issue switch git clients. "Just don't make mistakes" is a strategy that works fine until it doesn't. You WILL check something in you did not mean to.

**Comment by aellis-rbx** [comment]
Bump. I'm in a corporate environment and this is the only approved git client. I was shocked there's not a setting to toggle this behavior off. I'm also seeing lots of git locks blocking other git commands i'm trying to run and I'm assuming it's this app staging files in the background?
