### ISSUE TITLE
Possibility to launch a custom executable against changed files, before they will be displayed on the list!

### ISSUE THREAD

**Issue by EmanueleBonin** [desktop/desktop#17889]
### The feature request

Some languages doesn't have only text source files, so git can't show the difference from new and old version. But in some languages there is the possibility to create a text rappresentation o the binary files that contain the code inside of it. 
For example Visual FoxPro use dbf files to descript forms, classes, reports etc. and inside of this files there is the code used in the various objects described by dbf itself.
Is possible to extract this code in to a text file that can be managed by github desktop.

### Proposed solution

Adding in the option menu a fullpath of an exe program that will be execute when github desktop will scan for changed files, and passing file names as parameters.
In this way the user can create a ìn executable that can read the passed file name to take some action. One of this action could be the creation of a new text file with text rappresentation of the binary files.

**Comment by niik** [comment]
Hey @EmanueleBonin, thanks for reaching out!

While we don't have any plans to support this natively in the Desktop app at this time Git already have support for the scenario you're describing. See ["Performing text diffs of binary files"](https://git-scm.com/docs/gitattributes#_performing_text_diffs_of_binary_files) in the Git documentation. Desktop will currently respect the configuration and display the converted text diff. Note however that since Desktop has no way of knowing that a diff has been transformed things like partial committing will either just not work or produce undesirable results. If you choose to experiment with diff filters you have to keep track of which files are being converted yourself and make sure to only commit them as a whole.


related: https://github.com/desktop/desktop/issues/15136

**Comment by EmanueleBonin** [comment]
Thank U
