### ISSUE TITLE
Github dekstop showing error while I tried to open VScode 

### ISSUE THREAD

**Issue by Simer13** [desktop/desktop#17907]
### The problem

Error: spawn cmd.exe ENOENT
    at __node_internal_captureLargerStackTrace (node:internal/errors:490:5)
    at __node_internal_errnoException (node:internal/errors:620:12)
    at Process.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Github desktop was working just fine but then suddenly it started showing this error when i tried to open vs code through it. 

### Release version

Version: 3.3.6

### Operating system

OS: Windows 10.0.22621

### Additional context

I uninstalled and reinstalled all the things again , but still it is giving me the same error.

**Comment by tidy-dev** [comment]
@Simer13 This is usually due to an access problem. Are you aware of any environment changes that could have lead to an access change? Could you try moving your repository to the C drive and re-adding it to GitHub Desktop?

Other have solved this by adding `C:\Windows\system32` to their environment path. 

Here are [several similar issues](https://github.com/desktop/desktop/issues?q=is%3Aissue%20state%3Aclosed%20Error%3A%20spawn%20cmd.exe%20ENOENT) if you would like to browse to see other  users solutions.

**Comment by Simer13** [comment]
@tidy-dev My environmental path is already set to C:\Windows\system32. Earlier I made some changes to the environmental variables due to the error occurring in the node version. But github dekstop still worked for a while after that. I will try to find the solution through the issues you gave. Thank you !

**Comment by tidy-dev** [comment]
You are welcome. I am going to close this for now, but feel free to comment back if you have more questions or find a solution you would like to share. :)
