### ISSUE TITLE
Can't Use Github Desktop Over Proxy 

### ISSUE THREAD

**Issue by divyanshu-kunwar** [desktop/desktop#17928]
I have setup the proxy in git config but still there is a 407 Error . Moreover I am not able to fetch or list any repository when connected to this proxy network .

**Comment by steveward** [comment]
Thanks for the report @KUNWAR-DIVYANSHU. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
