### ISSUE TITLE
error

### ISSUE THREAD

**Issue by moflehsami** [desktop/desktop#17944]
### The problem

error: RPC failed; curl 18 transfer closed with outstanding read data remaining
error: 4453 bytes of body are still expected

### Release version

Version 3.3.6 (x64)

### Operating system

windows 11

**Comment by steveward** [comment]
Thanks for the report @moflehsami. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
