### ISSUE TITLE
bug while fetching

### ISSUE THREAD

**Issue by kashaf172725** [desktop/desktop#17941]
### The problem

My github desktop give error:
remote: Enumerating objects: 11207, done.        
remote: Counting objects: 100% (125/125), done.        
remote: Compressing objects: 100% (47/47), done.        
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
error: 7277 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
how to resolve?

### Release version

3.3.6

### Operating system

windows

**Comment by steveward** [comment]
Thanks for the report @kashaf172725. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by kashaf172725** [comment]
thats error has been resolved it is just my network error. thanks anyway
