### ISSUE TITLE
Can't commit in GitHub

### ISSUE THREAD

**Issue by Anush199530** [desktop/desktop#17959]
### The problem

Hey, I tried to commit, but it doesn't work. Even if I open a new project, I have the same problem. Does someone have a solution for this? 
![image](https://github.com/desktop/desktop/assets/141546279/94b489f4-8d3e-49db-a155-a940ef0f180e)

### Release version

Version 3.3.6 (x64)

### Operating system

windows 11

**Comment by steveward** [comment]
Thanks for the report @Anush199530. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
