### ISSUE TITLE
entry point not found

### ISSUE THREAD

**Issue by shivahiremat** [desktop/desktop#17969]
### The problem

the proceduer entry point Discardvirtualmemory could not be located in the dynamic link library

### Release version

3.3.6.0

### Operating system

window 8

**Comment by steveward** [comment]
Thanks for the report @shivahiremat. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by cmcnicoll** [comment]
Got the same error and uninstalled. Getting the same error when trying to reinstall. Is this related to OS end of support?
```
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	GitHubDesktop.exe
  Application Version:	3.3.6.0
  Application Timestamp:	651560bd
  Fault Module Name:	top\app-3.3.6\GitHubDesktop.exe!DiscardVirtualMemory
  Fault Module Version:	6.3.9600.21620
  Fault Module Timestamp:	65175333
  Exception Code:	c0000139
  Exception Offset:	00000000000ed170
  OS Version:	6.3.9600.2.0.0.272.7
  Locale ID:	1033
  Additional Information 1:	ac05
  Additional Information 2:	ac0507478d1c5bd693cfc4fe3987e900
  Additional Information 3:	ac05
  Additional Information 4:	ac0507478d1c5bd693cfc4fe3987e900
```

**Comment by steveward** [comment]
@cmcnicoll that OS looks like Windows Server 2012 based on a quick Google search -- if so, that could definitely be the cause of the issue. Is that the OS you are running?

**Comment by cmcnicoll** [comment]
Yes, getting the error on an old instance that I haven't started up in months.
