### ISSUE TITLE
Forgot email

### ISSUE THREAD

**Issue by fqsbits** [desktop/desktop#18008]
### The feature request

A way that when we forget the email connected to a GitHub page created by us, to receive an email, so we can remember. 

### Proposed solution

Just add another option in "Forgot password" called username instead of only "e-mail".

**Comment by mostofa420** [comment]
No

**Comment by niik** [comment]
Hey @fqsbits, thanks for reaching out. Unfortunately since GitHub.com doesn't have an option to recover forgotten password based on username alone there's not much GitHub Desktop can do to support this. Your best bet would be to contact GitHub support directly via https://github.com/contact. Since we can't add this option ourselves I'm going to close this issue and wish you the best of luck recovering your account
