### ISSUE TITLE
Cannot push origin, throws "Authentication failed".

### ISSUE THREAD

**Issue by ItsTact** [desktop/desktop#18014]
### The problem

The repository that I'm trying to push to is part of an organization (and it's just stuff for a website), but while I can fetch, I can't push or commit anything. I've tried all of the fixes and have looked at all the previous issues, but none of them seem to be a solution. I've tried relogging, uninstalling and reinstalling different versions of GitHub Desktop, and other things, but none seem to do anything different except throw this error. I don't use SSH and my organization doesn't require tokens. This was not a problem before I moved the repository to an organization, but I have admin access in that organization so it shouldn't even be a problem. Pushing my own repositories still works though.

### Release version

3.3.5-linux2 (x64)

### Operating system

Ubuntu 22.04.3 LTS

### Steps to reproduce the behavior

1. Push origin
2. Get error message
![image](https://github.com/desktop/desktop/assets/69988786/827cad01-6cdc-47d0-b44d-7471bb34abca)

### Log files

[2024-01-14.desktop..log](https://github.com/desktop/desktop/files/13932465/2024-01-14.desktop.log)
[2024-01-14.desktop.production.log](https://github.com/desktop/desktop/files/13932467/2024-01-14.desktop.production.log)

### Additional context

I know you guys don't technically support Linux but I don't seem to be the only one having this problem.

**Comment by niik** [comment]
Hey @ItsTact, sorry to hear you're having issues using Desktop. In the future I'd recommend opening issues related to the Linux fork of Desktop in the [https://github.com/shiftkey/desktop](shiftkey/desktop) repository as the community there will have the most context around common linux fork issues.

That said I'm fairly certain that the problems you're encountering is due to the "Third party application access policy" not permitting the use of the Desktop fork for Linux. See https://github.com/shiftkey/desktop/issues/972 and https://github.com/shiftkey/desktop/issues/217.

I'm going to close this issue and refer you to the Linux fork repository for more help troubleshooting.
