### ISSUE TITLE
inability to push codes from vs code terminal

### ISSUE THREAD

**Issue by kingsley-chukwuani** [desktop/desktop#18011]
i cant push codes from my terminal

**Comment by niik** [comment]
Hi, this issue doesn’t appear to be related to the GitHub Desktop application so I’m going to close this issue but  if you believe that's a mistake feel free to comment and we can revisit.
 If you choose to reopen or open a new issue please fill out the entire issue template so that we can have the best chance of helping your troubleshoot.

If you require assistance with a particular project on GitHub it's best to open an issue in the repository of that project. If you have a general support question please check out [GitHub support](https://support.github.com).

Best of luck!
