### ISSUE TITLE
issue with github desktop

### ISSUE THREAD

**Issue by RomainGShippeo** [desktop/desktop#18038]
### The problem

folder named "/" makes github desktop refuse to fetch from project.

### Release version

Version 3.3.6 (x64)

### Operating system

windows 11

### Steps to reproduce the behavior

1. create a folder in git
2. add a file named "/"
3. try to fetch the git repo

### Screenshots

![image](https://github.com/desktop/desktop/assets/109064255/835da689-c265-40ab-82c5-fdf4dfe4b833)

**Comment by steveward** [comment]
Thanks for the report @RomainGShippeo. This is actually a Windows convention, since `/` is not a valid path name on Windows. See [naming conventions](https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN#naming_conventions). You can either rename that folder, or workaround this by setting the following [config option](https://git-scm.com/docs/git-config#Documentation/git-config.txt-coreprotectNTFS):

`git config core.protectNTFS false`

Please note that this config option could have side effects. I hope that helps!
