### ISSUE TITLE
Failed tutorial Repository. First time on Github

### ISSUE THREAD

**Issue by nolimitmaliq** [desktop/desktop#18033]
### The problem

I keep getting this error message after I delete the file from my laptop. Also on my Githun front page, the desktop/tutorial has a locked sign. I don't know what that means.

Failed creating the tutorial repository.

You already have a repository named "desktop-tutorial" on your account at GitHub.com.

Please delete the repository and try again.Failed creating the tutorial repository.

You already have a repository named "desktop-tutorial" on your account at GitHub.com.

Please delete the repository and try again.

### Release version

Version 3.3.6 (x64)

### Operating system

Windows !!

### Screenshots

<img width="966" alt="image" src="https://github.com/desktop/desktop/assets/120054869/4052a2dd-27d9-4089-b51d-ec6838c3de73">

**Comment by nolimitmaliq** [comment]
It is windows 11

**Comment by tidy-dev** [comment]
Hi @nolimitmaliq,  GitHub Desktop is detecting that you already have a repository at `https://github.com/nolimitmaliq/desktop-tutorial`. In order to go through the tutorial again, you must[ delete that repository from your github.com](https://docs.github.com/en/repositories/creating-and-managing-repositories/deleting-a-repository) as well as locally (which it sounds like you already have done).
