### ISSUE TITLE
Feature Request: Push tags created by command line

### ISSUE THREAD

**Issue by camilacanhete** [desktop/desktop#18031]
### The feature request

Github Desktop doesn't have a command to push tags created by command line to remote, like this: `git push --tags origin`

### Proposed solution

Would be interesting to add tag commands in the future, specially when they're created outside the application (by command line)

**Comment by steveward** [comment]
Thanks for the issue @camilacanhete. This has been previously reported in https://github.com/desktop/desktop/issues/11121, and is due to performance concerts. Is there a specific workflow you are using where you need this functionality? Some tools automatically generate tags, and it would be helpful to know if that's the case here.

**Comment by camilacanhete** [comment]
Hi @steveward, I'm using a custom script that automatically increases the version of the application and creates a tag based on this version. Worth to mention this is not pushed to Github, but Azure DevOps. I've tested a little and even `--follow-tags` don't work in this case, maybe a git incompatibility with Azure. So to push tags, I have to use `git push --tags origin`. Even a menu option where I can do this manually would be fine for me, but currently Github Desktop has no option to force push on tags.

**Comment by steveward** [comment]
Thanks for sharing that. This likely isn't something we'll implement in the near-term, but I'll collect this feedback into https://github.com/desktop/desktop/issues/11121 so we have it in one area for future consideration.
