### ISSUE TITLE
Use Latest Electron JS version

### ISSUE THREAD

**Issue by fisforfaheem** [desktop/desktop#18055]
### The feature request

kindly use latest version of Electron

### Proposed solution

Upgrade Electron version

**Comment by sergiou87** [comment]
Hello @fisforfaheem 

We try to stay 1 version behind the latest stable and do that update every once in a while since upgrading Electron has some overhead for us. 

Since we have our own schedule to update Electron, I'm gonna close this issue. But is there any specific feature of bugfix in the latest Electron version that you're looking for?

**Comment by fisforfaheem** [comment]
I was experiencing weird issues in windows 10 on lately.
On old laptop

**Comment by sergiou87** [comment]
Anything specific? I'd say updating Electron usually fixes AND causes weird issues, so maybe those you're experiencing get fixed but then you get new ones in return 😓
