### ISSUE TITLE
Getting Error

### ISSUE THREAD

**Issue by deepika-sdmit** [desktop/desktop#18054]
Getting following error while pushing the code  from Git Desktop
**The remote disconnected. Check your Internet connection and try again.** 

And also following error while logging in from visual studio or Git GUI

**You are marked as spam, and therefore cannot authorize a third party application.**

**Comment by steveward** [comment]
Thanks for the report @deepika-sdmit. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by keerthimalloju** [comment]
You are marked as spam, and therefore cannot authorize a third party application
