### ISSUE TITLE
WSL: imaginary line ending changes get added by the desktop client

### ISSUE THREAD

**Issue by maoschanz** [desktop/desktop#18067]
### The problem

- i have a repository that is entirely managed through WSL (cloned using WSL's git, edited using VS-Code's "WSL remote" integration, etc.), and it only uses normal LF line endings accordingly
- when i type `git status` in a WSL bash terminal, it only lists actual changes
- HOWEVER, when i try to use github desktop, i get hundreds of "changed files" because this app wants to change all line endings from LF to CRLF
- tutorials to turn this off are useless, since the only git i can configure is my WSL one, and it's correctly set up to NOT do that

Please fix this behavior, or the very least provide a GUI element to switch off whatever is causing this mess

### Release version

3.3.8

### Operating system

windows 10

### Steps to reproduce the behavior

1. open wsl
2. clone
3. edit a single file
4. open github desktop
5. cry

**Comment by steveward** [comment]
Thanks for the issue @maoschanz. This isn't a GitHub Desktop specific issue -- it's due to how line-endings are handled. WSL uses LF, and Windows uses CRLF, which is why you're seeing this behavior when working with GitHub Desktop.

The easiest way to resolve this would be to add `.gitattributes` file with a `* text=auto` line. This should normalize the line endings and prevent this issue within this specific repository. See [this guide](https://docs.github.com/en/github/getting-started-with-github/configuring-git-to-handle-line-endings#per-repository-settings). Let me know if you have any other questions.
