### ISSUE TITLE
Unable to open command prompt even though Git is installed

### ISSUE THREAD

**Issue by MrEikono** [desktop/desktop#1808]
### Description
I'm unable to open a command prompt through Repository > Open command prompt even after installing Git 2.13.0 and following the instructions in https://help.github.com/articles/set-up-git .

### Version

**GitHub Desktop version:** 0.5.8
**OS version:** Microsoft Windows [Version 10.0.10586]

**Expected behaviour:** A command prompt opens

**Actual behaviour:** No command prompt opens, and GitHub Desktop shows this instead --
![image](https://cloud.githubusercontent.com/assets/12767408/26523560/0c4964d2-42cf-11e7-862f-a2d1dc316fce.png)

**Reproduces how often:** 100% of the time

### Logs
No idea how this got here, since the date modified is today, about 90 minutes ago. It is a log, though.
[2017-05-27.desktop.production.log.txt](https://github.com/desktop/desktop/files/1033721/2017-05-27.desktop.production.log.txt)

#### Additional Information
I'm willing to bet reinstalling the _official_ version of GitHub Desktop would solve this problem, since that would bring back Git Shell, but it seems kind of unnecessary to have both installed.

**Comment by shiftkey** [comment]
@MrEikono could you launch Command Prompt and run this command: `echo %PATH%`

You should see something like this, and `C:\Program Files\Git\cmd` should be there:

<img width="973" alt="screen shot 2017-05-28 at 6 40 41 pm" src="https://cloud.githubusercontent.com/assets/359239/26532371/3cfbf7b4-43d5-11e7-8770-18d53a2b37f5.png">

If you can't see it listed there, it probably means you chose `Use Git only from Git Bash` in the installer:

<img width="515" src="https://cloud.githubusercontent.com/assets/359239/26532391/e0bc48c2-43d5-11e7-825d-d0dedd8d123b.png">

Let me know what you find

**Comment by MrEikono** [comment]
Yup, the problem was that I chose `Use Git from Git Bash only`.

**Comment by e-beach** [comment]
I am experiencing this problem, and the suggested solution does not work for me.

When I run `echo %PATH%` from Command Prompt, the result includes `C:\Program Files\Git\cmd`. But Git is not on the path in the window that opens when I press "open command prompt" from GitHub Desktop.  It appears `cmd.exe`  has different environment variables for GitHub Desktop than from starting via the windows interface.

This may be because GitHub Desktop starts cmd.exe with the window title `C:\WINDOWS\system32\cmd.exe` which [apparently can affect behavior](https://stackoverflow.com/questions/34068830/whats-the-difference-between-command-prompt-and-cmd).

**Comment by shiftkey** [comment]
@e-beach please open a fresh issue with repro steps so we can troubleshoot this further

**Comment by SimranKnight** [comment]
now im getting angry... the git hub is installed and there is no folder in the c drive

**Comment by shiftkey** [comment]
@SimranKnight can you please open a new issue and fill out the template, so we can understand your situation better?

**Comment by OSHI7** [comment]
Still experiencing this issue.
