### ISSUE TITLE
Bug Report: "There are no changes to commit." Error Incorrectly Shown in Non-Master Branch

### ISSUE THREAD

**Issue by VaporFoxLash** [desktop/desktop#18109]
### The problem

I encountered a bug in GitHub Desktop where, while working in a non-master branch, the application incorrectly displayed a "No changes to commit" message. However, after a manual refresh, it correctly identified changes and allowed me to push the changes, showing that the commit I made was successful but the response was wrong.

### Release version

Version 3.3.8 (arm64)

### Operating system

macOS 14.2.1 (23C71)

### Steps to reproduce the behavior

Create a new branch
Make changes and see if they reflect on the GitHub desktop
Type commit message and hit commit; you should get an error saying, "There are no changes to commit."
Hit "fetch origin"; now it should say "push origin"

### Screenshots

![Screenshot 2024-01-31 at 11 11 16](https://github.com/desktop/desktop/assets/25909065/3c53d78e-7f2e-44f8-9160-e7f581336038)

**Comment by steveward** [comment]
Thanks for the issue @VaporFoxLash. 

>allowed me to push the changes, showing that the commit I made was successful but the response was wrong.

Do you mean commit your changes here? The commit option shouldn't even be enabled unless there are uncommitted changes -- was there anything in the `Changes` tab?

Could you also upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`. The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by VaporFoxLash** [comment]
It showed the changes and allowed me to type a commit message and click commit but when I click on it it shows the the error, after hitting "fetch origin" it allows to push, showing that the commit that returned an error was successful. Yes there were updated files in the changes tab.

Here are the logs below

[2024-01-29.desktop.production.log](https://github.com/desktop/desktop/files/14122504/2024-01-29.desktop.production.log)

**Comment by VaporFoxLash** [comment]
![](https://github.com/desktop/desktop/assets/25909065/b7531e70-a5d5-4b8a-af7e-eac102e786e3)

**Comment by steveward** [comment]
Can you try opening the command line and committing there?

`git add -A`
`git commit -m "commit message"`

There have been previous issues (like https://github.com/desktop/desktop/issues/16264) where this error has been triggered due to specific repository issues, so I'm hoping committing via the command line will surface this.
