### ISSUE TITLE
Unable to publish repo from Github Desktop

### ISSUE THREAD

**Issue by DinoJazvin** [desktop/desktop#18119]
### The problem

When using github desktop, when I create a local repo and attempt to publish it to Github, I get an error reading "Requires Authentication". I am already signed in the app with my github credentials. 

### Release version

3.3.8

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Log into your account on desktop
2. Create repo on your local machine
3. Attempt to publish repo to Github (should get an error message reading "Requires Authentication")

### Screenshots

<img width="717" alt="github error" src="https://github.com/desktop/desktop/assets/43155539/c9d19ad6-6cca-4eec-b2df-4ad4ae1c3a2f">

**Comment by steveward** [comment]
Thanks for the report @DinoJazvin. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
