### ISSUE TITLE
Delete

### ISSUE THREAD

**Issue by akhicsg** [desktop/desktop#18142]

**Comment by steveward** [comment]
Thanks for the report @akhicsg. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by akhicsg** [comment]
Hi Steve, I cannot share the log due to security issue. Apologies.

**Comment by akhicsg** [comment]
I will refer online for some help.

**Comment by akhicsg** [comment]
Please delete this ticket.
