### ISSUE TITLE
Windows installer is truncating the user's `PATH` variable

### ISSUE THREAD

**Issue by spiltcoffee** [desktop/desktop#18176]
### The problem

Took me a while to realise this was even happening, but I discovered that the Windows installer is truncating the user's `PATH` variable when it's larger than 1024 characters.

I believe it has to do with this function here that calls `setx`:
https://github.com/desktop/desktop/blob/0a20e1fa2b8802fb26f8d57fef531791c779c28e/app/src/lib/process/win32.ts#L30-L43

As noted [here](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/setx), `setx` has a limit of 1024 characters:
> Be aware there's a limit of 1024 characters when assigning contents to a variable using setx.

Now, granted, a PATH of 1024 characters might be on the larger side of things, but for the installer to silently butcher my PATH, and *fail* to achieve it's goal of inserting itself onto the PATH, is a rather frustrating thing to experience.

For completeness, this issue also occurs on uninstall.

### Release version

3.3.8

### Operating system

Windows

### Steps to reproduce the behavior

1. Have a user `PATH` longer than 1024 characters.
2. Install or Uninstall GitHub Desktop
3. Observe that the `PATH` is now truncated to 1024 characters.

### Log files

n/a

**Comment by sergiou87** [comment]
Nice catch!

From what I see, there are a few possible workarounds:
1. [Edit that env var in the registry](https://superuser.com/a/387625) (`HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Environment`) but that doesn't broadcast `WM_SETTINGCHANGE` to other processes so they can grab he new value. I see some ideas like [using `setx` right after that to set a variable to its own value](https://superuser.com/questions/387619/overcoming-the-1024-character-limit-with-setx#comment559592_387625).
2. Write a native Node module that uses [`System.Environment.SetEnvironmentVariable`](https://learn.microsoft.com/en-us/dotnet/api/system.environment.setenvironmentvariable?view=net-8.0) and use that instead of `setx`.
3. Use a PowerShell script to do this job with `[Environment]::SetEnvironmentVariable('PATH', "$newPath",'Machine');`
4. Detect when the resulting `PATH` is longer than 1024 and don't do anything in that case (other than _somehow_ surface that problem to the user).

With registryjs (1) should be pretty simple, although I can't tell how reliable that hacky use of `setx` right afterwards is. (3) also sounds simple but not sure if there could be other potential issues with the use of external scripts.
