### ISSUE TITLE
Getting Issue on application startup

### ISSUE THREAD

**Issue by haweris** [desktop/desktop#18212]
Whenever I open the application it says "listen EADDRNOTAVAIL: address not available 127.0.0.1", and then no repository loads or fetches.
<img width="1083" alt="Screenshot 2024-02-24 at 11 11 35 AM" src="https://github.com/desktop/desktop/assets/60925939/3cb0766a-e0a3-45dd-bf6e-94ea1bc40a7e">

**Comment by steveward** [comment]
Thanks for the report @haweris. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by haweris** [comment]
Here are the logs for that day:
[2024-02-23.desktop.production.log](https://github.com/desktop/desktop/files/14397964/2024-02-23.desktop.production.log)

**Comment by steveward** [comment]
I'm not seeing the error showing that's popping up in Desktop, but there is a different network error showing up on updates:

```
2024-02-23T17:35:12.160Z - error: [ui] Error checking for updates
Error: The network connection was lost.
```

Are you behind a firewall or proxy that could be interfering with network connections in GitHub Desktop? Could you run `ping localhost` from the terminal to see what that returns?
