### ISSUE TITLE
Repository is unavailable everytime i try to clone

### ISSUE THREAD

**Issue by philosipher** [desktop/desktop#18210]
### The problem

I'm new to github but have followed every step I'm supposed to, but no matter which repository I clone into desktop it says repository is unavailable and fails.

### Release version

Github desktop

### Operating system

Windows 10

**Comment by steveward** [comment]
Thanks for the report @philosipher. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
