### ISSUE TITLE
Cannot clone repository

### ISSUE THREAD

**Issue by kalinbac** [desktop/desktop#18216]
### The problem

I set up a new mac book pro 14, i wanted to clone my private repos to my new mac book. Only one of my projects was cloned, after third or fourth try. While trying to clone others, I keep getting this error.
remote: Enumerating objects: 3648, done.        
remote: Counting objects: 100% (54/54), done.        
remote: Compressing objects: 100% (49/49), done.        
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
error: 5329 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

### Release version

Version 3.3.9 (arm64)

### Operating system

Sonomo 14.3.1

**Comment by brenoepics** [comment]
@kalinbac what happens when u try cli?
what about something like this? 
https://stackoverflow.com/questions/38618885/error-rpc-failed-curl-transfer-closed-with-outstanding-read-data-remaining

**Comment by steveward** [comment]
@kalinbac thanks for the issue. Unfortunately there isn't much we can do from our end regarding connection timeouts like this, but there are some things you can try including options that @brenoepics shared in that link. One thing that sometimes works is to use SSH instead of HTTPS if you continue to hit these issues.

Are you behind a firewall/proxy/security software that could also be interfering with your connection?

You can also check out https://github-debug.com/ to see how reliable your connection to GitHub is.
