### ISSUE TITLE
GitHub Desktop not updating and still thinks it's the latest version

### ISSUE THREAD

**Issue by IdfbAn** [desktop/desktop#18226]
### The problem

For whatever reason, even though it's still on version 3.2.1, [not the latest](https://desktop.github.com/release-notes/), GitHub Desktop thinks I have the latest version and isn't updating because of that.

### Release version

3.2.1 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1. In the "Help" menu, click on "About GitHub Desktop"
2. Click on "Check for Updates"
3. "You have the latest version (last checked just now)"

### Screenshots

![GitHubDesktop_VtzoaVyoTW](https://github.com/desktop/desktop/assets/48176725/f8a7c337-ef94-48cc-b995-4a92ea6e3e23)

### Additional context

It's been a while since I've last used GitHub Desktop, so maybe it's because of that?

**Comment by steveward** [comment]
Thanks for the issue @IdfbAn. GitHub Desktop does staged updates. We manually increase the percentage of users that get the update depending on the importance of the update and reports we get, which is why it sometimes takes longer to receive an update. What users receive the update is random for each release.

If you're in a hurry to get the latest updates, you can `Alt + Click` on the `Check for Updates` button to bypass the staged update and get you the latest version.

**Comment by IdfbAn** [comment]
> Thanks for the issue @IdfbAn. GitHub Desktop does staged updates. We manually increase the percentage of users that get the update depending on the importance of the update and reports we get, which is why it sometimes takes longer to receive an update. What users receive the update is random for each release.
> 
> If you're in a hurry to get the latest updates, you can `Alt + Click` on the `Check for Updates` button to bypass the staged update and get you the latest version.

That did work, but why couldn't I even update to at least 3.2.2?
