### ISSUE TITLE
Failed authenticatiom

### ISSUE THREAD

**Issue by BigJoey2505** [desktop/desktop#18241]
### The problem

University computers are failing authentication whenever i try to fetch origin

### Release version

3.0.5

### Operating system

Windows 10

**Comment by steveward** [comment]
Thanks for the report @BigJoey2505. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by Kurnianazara10** [comment]
Good
