### ISSUE TITLE
Error: cannot spawn .git/hooks/pre-commit: No such file or directory

### ISSUE THREAD

**Issue by Typhon0130** [desktop/desktop#18251]
### The problem

I am using GitHub Desktop while working on Git
when click on commit button, getting below error
'error: cannot spawn .git/hooks/pre-commit: No such file or directory"
But if I use VS code instead of GitHub Desktop, it's going well for commit.

### Release version

3.35(*64)

### Operating system

Windows 10 Pro

### Steps to reproduce the behavior

Change some files -> Commit to `branch name` -> `error: cannot spawn .git/hooks/pre-commit: No such file or directory`

### Screenshots

![image](https://github.com/desktop/desktop/assets/125342474/3e3f949b-f414-48a1-b015-9db5c1bc0c73)

### Additional context

I have already fixed this issue via this [link](https://github.com/desktop/desktop/issues/14063)
But when I commit to remote, I have to always move the pre-commit file from .git/hooks folder to another folder.
After commit, I have to repeat action again.
Is there any other good way without move the pre-commit file?
Thanks

**Comment by steveward** [comment]
@Typhon0130 thanks for the issue. There are some known issues with GitHub Desktop and pre-commit hooks, often caused by environment setup. Are you using Husky? There are some workarounds that have been shared in https://github.com/desktop/desktop/issues/12562 to get Husky working, like https://github.com/desktop/desktop/issues/12562#issuecomment-1006506536.
