### ISSUE TITLE
Files cant be found

### ISSUE THREAD

**Issue by KemuntoSereti** [desktop/desktop#18261]
Trying to publish my project files but they cant be located

**Comment by sergiou87** [comment]
Thanks for reaching out!

We require [the template](https://github.com/desktop/desktop/issues/new?template=bug_report.yaml) to be filled out on all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by KemuntoSereti** [comment]
Done

**Comment by steveward** [comment]
Closing in favor of https://github.com/desktop/desktop/issues/18263.
