### ISSUE TITLE
GitHub Desktop encountered an error

### ISSUE THREAD

**Issue by AnuradhaDilshan** [desktop/desktop#18262]
### The problem

Error:  spawn C:\Windows\system32\cmd.exe EACCES
When I try to open my VS Code using GitHub Desktop, It shows this error and restart over and over again.

### Release version

3.3.10

### Operating system

Windows 10

### Screenshots

![error](https://github.com/desktop/desktop/assets/101551005/62a8d72b-3f25-4b75-8c65-eb7cf44e219e)

**Comment by steveward** [comment]
Thanks for the issue @AnuradhaDilshan. We've seen errors opening VSCode due to path issues, but that usually shows an ENOENT error, not EACCESS.

Could you open the command prompt and share the output of echo `%PATH%`?

If `System32` is not in your `PATH`, you will need to edit your `PATH` by following [this article](https://www.howtogeek.com/118594/how-to-edit-your-system-path-for-easy-command-line-access/) and adding the following line:

`C:\Windows\system32`

**Comment by AnuradhaDilshan** [comment]
After installation of Windows 10 Version 22H2 for x64-based Systems (KB5034843), that issue was solved. Thanks for the immediate reply about this issue and please do more background search about this matter, I think it can be happen again and again @steveward.
