### ISSUE TITLE
Logging out of one account and in to another does not show that new accounts repositories.

### ISSUE THREAD

**Issue by microapiframework** [desktop/desktop#18269]
### The problem

So I have a few different github accounts for different purposes (work, open source, private projects, etc). When I use the File -> Options -> Sign Out.. and then use that again (such a strange way to use different accounts.. who came up with this design?) to log in to another, then open my browser using the chrome switcher to use different user (where different github account is tied to), so that when I go to browser to authenticate it uses the right browser window.. that all seems to work in that it DOES authenticate me to my second (or third, etc) account thru the browser. What does NOT happen is the main display STILL shows the previous (first) account's repo. There is no updated info for the new account, no way to pull the new accounts repos, etc. It's like multiple account switching is entirely broken or does not work in the Windows desktop app.

### Release version

latest (Windows 11 64 bit as of 3/7/2024)

### Operating system

Windows 11 64bit

### Steps to reproduce the behavior

File
Options
Sign out
File 
Options
Sign in
Auth in browser with diff github account
See display has not updated to show any repos/details of newly signed in github account.. still shows the repo from the first. No option anywhere to pull/update/switch repos to the newly signed in one. 
<mind boggled how this got past QA>

**Comment by steveward** [comment]
Thanks for the issue @microapiframework. This is the expected behavior, since the repositories shown in the repository list are your local repositories. To clone new remote repositories you can go to `File` -> `Clone repository` and select a repository.

GitHub has had a policy of one user per account, which is why GitHub Desktop has supported only one account for github.com. However, we do understand that things have changed and there are many users who require multiple accounts, so we do have that on our radar to support in the future. You can follow along in #3707 for updates about this.
