### ISSUE TITLE
Account Avatar issue if multiple accounts

### ISSUE THREAD

**Issue by j-vitali** [desktop/desktop#18267]
### The problem

Basically I use 2 accounts, and inside the history commits I see different avatar images, it can be impobbile because on 1 account I have no access to that repository (it's private and of an organization one)

### Release version

latest

### Operating system

mac

### Steps to reproduce the behavior

1. login with 2 or more accounts
2. push commit many times
3. switch user
4. see history users avatars

### Screenshots

<img width="392" alt="Screenshot 2024-03-07 alle 17 17 07" src="https://github.com/desktop/desktop/assets/161858414/88b5cbc6-d5b4-4f82-a7df-fbd3199723a8">

**Comment by sergiou87** [comment]
If you put your mouse on each avatar, do you see the very same email address or a different one?

**Comment by j-vitali** [comment]
> If you put your mouse on each avatar, do you see the very same email address or a different one?

Basically I changed also the email of the profile, passign from github to original one, that's why I think.

<img width="392" alt="Screenshot 2024-03-08 alle 08 00 59" src="https://github.com/desktop/desktop/assets/161858414/5012093f-d0b9-4876-a924-e3e086f644e7">

<img width="392" alt="Screenshot 2024-03-08 alle 08 55 24" src="https://github.com/desktop/desktop/assets/161858414/fc83ffdc-e7c9-4d3f-9d60-f2e90a469778">


But even I changed the email, I think it has nothing to do with the allowed user who pushed commits.

**Comment by sergiou87** [comment]
GitHub Desktop uses the committer email address to build the URL of the avatar that is displayed in that list.

However, what authorizes you to commit into a private repo is the token of the account you're logged in with in the `Settings -> Account` dialog, not the email address used when making the commit.

Not sure if that answers your question, nor if I have understood what the problem is 😅
