### ISSUE TITLE
Track stats by day

### ISSUE THREAD

**Issue by joshaber** [desktop/desktop#1830]
The way in which we currently collect and report stats claims to be per-day, when they actually may have been collected over multiple days.

Currently we:

1. Record stats.
1. Submit once per calendar day.
1. Clear them after we've submitted them.
1. Goto (1).

But if we aren't able to submit stats or the user doesn't actually launch the app, there could be a long delay between when the stats events actually happened and when they are reported. It also means a single stats submission could include multiple days worth of stats.

Instead, we should capture stats in dated bundles and submit them as such.

**Comment by shiftkey** [comment]
@telliott27 any thoughts on this?

**Comment by telliott27** [comment]
I think this could be worth looking into, because the current method does lead to some inaccuracy in regards to when the activity happened. However, having precise dates is not crucial right now for the types of questions we are asking with our metrics. This could be part of a larger conversation about our metrics during our mini-summit perhaps?

**Comment by shiftkey** [comment]
Yeah, I'm also open to moving this to somewhere more relevant if we want to wrap our heads around this more formally.

**Comment by telliott27** [comment]
I've added it to my agenda for the mini-summit, so I think we can just close this issue out if you'd like.

**Comment by iAmWillShepherd** [comment]
This likely will affect the outcome of the migration from Dexie, so I'm going to add this issue to that project.
