### ISSUE TITLE
Git LFS Not initializing on Github Desktop for PC

### ISSUE THREAD

**Issue by Beny-Hacker** [desktop/desktop#18324]
### The problem

I have cloned Repo and I can not download large files that need LFS
In git bash, it works well.
I installed LFS.
git prune didn't help.

### Release version

3.3.11 (x64)

### Operating system

Windows 11

### Steps to reproduce the behavior

1. Clone repo
2. download large files that need LFS

### Log files

remote: Enumerating objects: 1, done.        
remote: Counting objects: 100% (1/1), done.        
remote: Total 1 (delta 0), reused 0 (delta 0), pack-reused 0        
From https://github.com/********************.main main       -> origin/main
Auto packing the repository in background for optimum performance.
See "git help gc" for manual housekeeping.
warning: There are too many unreachable loose objects; run 'git prune' to remove them.

**Comment by steveward** [comment]
Thanks for the issue @Beny-Hacker. Git LFS should work with GitHub Desktop. Could you upload the entire log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`. The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by Tarmogos** [comment]
Sorry for this missunderstanding. I dont know what i have done😅Best regards Tobias.Skickat från min iPhone02.04.2024 kl. 21:12 skrev github-actions[bot] ***@***.***>:﻿
Thank you for your issue!
We haven’t gotten a response to our questions above. With only the information that is currently in the issue, we don’t have enough information to take action. We’re going to close this but don’t hesitate to reach out if you have or find the answers we need. If you answer our questions above, this issue will automatically reopen.
