### ISSUE TITLE
Problem with pushing

### ISSUE THREAD

**Issue by Havenobrain** [desktop/desktop#18328]
### The problem

When I try to push necessary folder to a new repository, for some reason git open repository that already doesn't exist and tells me that this reposirtory doesn't exist. So it can't execute push

### Release version

Version 3.3.4 (x64)

### Operating system

macOS Monterey 12.4

**Comment by steveward** [comment]
Thanks for the report @Havenobrain. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
