### ISSUE TITLE
GitHubDesktopSetup-x64 3.3.12 Installation Failure on Win 8.1 x64

### ISSUE THREAD

**Issue by ayuanx** [desktop/desktop#18339]
### The problem

Failure to install on Win 8.1 x64.

### Release version

GitHubDesktopSetup-x64 3.3.12

### Operating system

Win 8.1 x64

### Steps to reproduce the behavior

Run "GitHubDesktopSetup-x64.exe" or "GitHubDesktopSetup-x64.msi", neither works.

### Log files

---------------------------
GitHubDesktop.exe - Entry Point Not Found
---------------------------
The procedure entry point DiscardVirtualMemory could not be located in the dynamic link library C:\Users\XXXXX\AppData\Local\GitHubDesktop\app-3.3.12\GitHubDesktop.exe. 
---------------------------
OK   
---------------------------

[Window Title]
GitHub Desktop

[Main Instruction]
GitHub Desktop has stopped working

[Content]
A problem caused the program to stop working correctly. Please close the program.

[Close the program]

**Comment by tidy-dev** [comment]
@ayuanx Support for Windows 8.1  has been deprecated. Unfortunately we're unable to support these operating systems since Chromium (and therefore Electron) have dropped support for these. Staying on an old version of Electron would mean we would be unable to provide critical security updates for other, still supported, operating systems.

At your own risk you can install the last supported version of GitHub Desktop from this link: https://github.com/desktop/desktop/issues/17168#issuecomment-1664215745. That version will not auto-update.

**Comment by ayuanx** [comment]
Well, isn't that great. I am not using disgusting Win10 anytime soon.

I will just use official git instead.

**Comment by MaplePhoenex** [comment]
In case anybody else is still looking, this version works on Windows 8.1

[/MaplePhoenex/Github-Desktop-2.2.4](https://github.com/MaplePhoenex/Github-Desktop-2.2.4)
