### ISSUE TITLE
Unable to sign into github via github desktop

### ISSUE THREAD

**Issue by umbraweb** [desktop/desktop#18383]
### The problem

I am unable to sign into github with github desktop. Whenever I try it just opens github requests to open github desktop. When I allow it to it just shows the screen that has the button to continue with browser. If I click that button it just starts all over again. This has happened, not just on tumbleweed, but also on ubuntu. I am using Chrome as the web browser.

### Release version

3.3.6

### Operating system

openSUSE Tumbleweed

### Steps to reproduce the behavior

1. Sign into your github account through github desktop 2. press continue with browser 3.when it asks permission to open github desktop give it permission.

**Comment by steveward** [comment]
@umbraweb sorry to hear you're having trouble. In the future I'd recommend opening issues related to the Linux fork of GitHub Desktop in the [shiftkey/desktop](https://github.com/shiftkey/desktop) repository as the community there will have the most context around common issues with the Linux fork.

The problem you're encountering may be due to the `Third party application access policy` not permitting the use of the Desktop fork for Linux. See https://github.com/shiftkey/desktop/issues/972 and https://github.com/shiftkey/desktop/issues/217.

I'm going to close this issue but you can reference those issues or other authentication issues in the issue tracker over in the fork.
