### ISSUE TITLE
GitHub Desktop 3.3.12 cannot find (3.3.13) available update

### ISSUE THREAD

**Issue by ricardonevesmusic** [desktop/desktop#18419]
### The problem

Hi

When going to "Help" → "About GitHub Desktop" → "Check for Updates", the software cannot find new/available updates.

In this case, I'm referring to the GitHub Desktop 3.3.13 that's been released this week and is available (at least according to the release notes section in the website).

Hope you can assist me in the steps to take to fix this situation, so that I can update to the new version.

Thank you,
Ricardo

### Release version

3.3.12

### Operating system

Windows 10 x64

### Screenshots

![GitHubDesktop_xCj5pEAOZf](https://github.com/desktop/desktop/assets/64813627/c3e7f61d-b566-4a52-9642-6d30a16b27a1)

**Comment by sergiou87** [comment]
Hello! We do staged updates. We manually increase the % of users that get the update depending on the importance of the update and reports we get, that's why it sometimes takes longer than others. Also, what users get the update for every % is random in every update.

Meanwhile if you're in a hurry to get the latest updates, you can <kbd>Alt</kbd> + Click on the `Check for Updates` button will bypass the staged update and get you the latest version.

I hope that helps!

**Comment by ricardonevesmusic** [comment]
> Hello! We do staged updates. We manually increase the % of users that get the update depending on the importance of the update and reports we get, that's why it sometimes takes longer than others. Also, what users get the update for every % is random in every update.
> 
> Meanwhile if you're in a hurry to get the latest updates, you can Alt + Click on the `Check for Updates` button will bypass the staged update and get you the latest version.
> 
> I hope that helps!

Yes.

This got solved pretty fast.

I was able to update a little later the same day without having to use the provided hint/shortcut.

Thank you.
