### ISSUE TITLE
New Version for Silicon Mac just breaks the Git Functioanality

### ISSUE THREAD

**Issue by lakhbawa** [desktop/desktop#18416]
### The problem

We are using bitbucket for our company repositories.

After i updated github desktop version on my MacBook pro m1. Git functionality in github desktop and using normal git command just stopped working.

### Release version

3.3.13

### Operating system

Mac OS m1 - 14.4 (23E214)

### Steps to reproduce the behavior

git pull, git push, no command is working 

### Screenshots

![image](https://github.com/desktop/desktop/assets/44654385/d53614a6-ba47-473a-a108-a1d02a58780e)

**Comment by tidy-dev** [comment]
@lakhbawa Sorry for your troubles and thank you for reaching out. I notice in your screenshot that you are attempting to connect to your repository through a terminal and using ssh. 

1. Could verify you do have access to the repository. (I know not likely this issue but just double checking no settings at bitbucket changed on you)
2. Could you try cloning this repository through https instead of ssh?

GitHub Desktop ships with it's own packaged versions of git. Thus, it is unusual that you would see the same behavior in your terminal as with GitHub Desktop if it was an issue was a result of the recent release. This appears that something has changed in your authentication of your connection to your repository.

**Comment by lakhbawa** [comment]
I do have correct access @tidy-dev If i reinstall the previous version of GitHub desktop it just works fine, and git commands in console also start working. but breaks on new version install

**Comment by sergiou87** [comment]
Could you check what `which git` says on your terminal @lakhbawa ?

GitHub Desktop installation shouldn't affect git on the command line 🤔

**Comment by lakhbawa** [comment]
which git
/usr/bin/git

it's happening for all repositories of bitbucket but it is working okay for GitHub repositories.

I can assure you, i have full access to the repositories. As soon as I uninstall 3.3.13 and restart the system. it starts working. It is a very frustrating experience.

**Comment by lakhbawa** [comment]
Version 3.3.13 (x64) works okay, but as soon as I install Version 3.3.13 (arm64) version, it breaks the whole git and git desktop.

But the update process is automated, I cannot even stop it from updating git desktop

![image](https://github.com/desktop/desktop/assets/44654385/005dd044-8447-4b7d-bb02-edd44e47886f)

**Comment by sergiou87** [comment]
I'm surprised because GitHub Desktop brings its own bundled git which doesn't override the system one, so there should be no way installing or uninstalling Desktop would break git from the command line 🤔 

Could you try running this?
```
ls -l `which git`
```
In case that `/usr/bin/git` is actually a symlink to some other file.
Also `git -v` with and without Desktop installed would be interesting. For me, that outputs `git version 2.39.3 (Apple Git-145)` (I'm on an M3 MBP with Sonoma 14.4)

For me it works with both bitbucket and GitHub repos, cloned via https and ssh.

Could you share your full logs? To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

Thanks!

**Comment by lakhbawa** [comment]
![image](https://github.com/desktop/desktop/assets/44654385/8587bc73-7995-4cc2-aee5-3cea2ff0bb2e)
![image](https://github.com/desktop/desktop/assets/44654385/ae0cd992-b56d-4868-adaa-886319f09321)
[2024-04-10.desktop.production.log](https://github.com/desktop/desktop/files/14935699/2024-04-10.desktop.production.log)

**Comment by lakhbawa** [comment]
Can you please take the MacO's silicon version back and release it after doing proper testing? It has broken my workflow.

## Steps of Getting the Issue
* Download and Install the Github Desktop Version 3.3.13, which is by default Non Silicon
* Git fetch, Git Pull, and everything works at the point for GitHub and bitbucket repos
* Git Desktop gives the notification, Restart the Github desktop to Upgrade Github desktop to Silicon Exclusive version
* I Restart the Github desktop or Open the Github desktop again after closing it by accident or something
* Silicon version gets installed automatically and opened when i open Github Desktop
* Bitbucket repositories stop working both in the Github desktop and normal git commands
* Everything breaks
* Git commands do not work in any terminal as well
## Steps I take to solve the Issue
* Uninstall Github desktop
* Try git commands in the terminal even after restarting
* No git command works
* Restart the system
* Git commands start working

**Comment by lakhbawa** [comment]
@sergiou87

**Comment by steveward** [comment]
@lakhbawa I'm not able to reproduce this issue either , so it seems like an issue specific with your system unfortunately.

> * > * Git commands do not work in any terminal as well

Are you seeing any errors outside of the `operation time out` errors related to SSH in the terminal or Desktop? Can you run `ssh -vT git@bitbucket.org` and let me know what that outputs?

Can you try also using HTTPS instead of SSH like @tidy-dev recommended above to see if that succeeds?

**Comment by lakhbawa** [comment]
I am getting the error both in terminal and desktop @steveward 

### Without Github Desktop installed

```
[SKIPPED SOME PART]
authenticated via ssh key.

You can use git to connect to Bitbucket. Shell access is disabled
debug1: client_input_channel_req: channel 0 rtype exit-status reply 0
debug1: channel 0: free: client-session, nchannels 1
Transferred: sent 3376, received 2504 bytes, in 0.1 seconds
Bytes per second: sent 34649.8, received 25700.0
debug1: Exit status 0
```

**Comment by lakhbawa** [comment]
Our company uses SSH only for authentication, so i don't think https thing will be useful for me, but i am gonna try anyway

**Comment by lakhbawa** [comment]
## After Installing Github Desktop and Upgrading Silicon Version:

Struck here: 

![image](https://github.com/desktop/desktop/assets/44654385/2419f7ae-aac2-4c12-b49c-f67d928c37e2)

**Comment by lakhbawa** [comment]
still struck

**Comment by lakhbawa** [comment]
i even tried removing the bitbucket from the known_hosts file, but no benefit

**Comment by lakhbawa** [comment]
any update? @steveward @tidy-dev

**Comment by tidy-dev** [comment]
@lakhbawa Multiple of us have tried bitbucket and have silicon machines. We cannot reproduce this and if it was a widespread issue, we would likely be seeing more reports. This appears to be something with your unique environment. Do you have any coworkers (or another machine) that use Desktop and are they seeing the same issue? 

At this point, I am not sure what else to try, but I found it interesting that your steps to solve was to uninstall desktop and them you had to restart for git command line to start working. Have you tried restart your computer after installing Desktop and seeing errors? iif so, while desktop is installed and after restart, does your git command line work?

**Comment by lakhbawa** [comment]
I tried @tidy-dev it did not help as well. I talked with another developer as well, we couldn't solve the issue. I ended up moving to the PHPStorm git utility. 
basically after installing GitHub desktop silicon version `ssh -T git@bitbucket.org`  stops working. when i uninstall and restart it starts working again.

Please let me know when you fix the issue, Thanks anyway

**Comment by lakhbawa** [comment]
Update: It turned out to be a network/firewall issue. 

Description for the sake of records for anyone else who faces the same issue in the future:
* The issue was specific to the network i use, When I would switch to another network, it would start working
* the firewall was blocking SSH to bitbucket from my device
* The network team has resolved the issue for me. So now both Git and GitHub desktop are working fine for me.
