### ISSUE TITLE
branch name filter needs to replace or filter a "#" followed by a number

### ISSUE THREAD

**Issue by sdiedrichsen** [desktop/desktop#18434]
### The problem

As a convenience, I use the bug ticket URL as a base for a branch name. E.g. 
rdar://123456 (Top #1 crash: CrashTracer: Logic Pro X )
For a branch name, I delete the "rdar://" and off I go. Somehow, the "#1" drives our jenkins CI crazy. In this case, I created a different branch without the "#1", which went thru all integration checks. 
Somehow, GitHub interprets the "#1" as pull request number one and expands the branch name somewhere.

### Release version

Version 3.3.13 (arm64)

### Operating system

MacOs 14.4.1

### Steps to reproduce the behavior

1. Create a branch with a name containing #1. 
2. Commit something, publish it and create a pull request.

**Comment by tidy-dev** [comment]
@sdiedrichsen Thanks for the report. Could you clarify if you are seeing a issue in GitHub Desktop, GitHub.com, or in Jenkins?

This is a the issue tracker for GitHub Desktop , if GitHub.com or Jenkins cannot parse a branch name with a `#`, I would request you open an issue with the software the issue is occurring in.
