### ISSUE TITLE
No memory

### ISSUE THREAD

**Issue by GuDuDeFe** [desktop/desktop#18440]
### The problem

Cloning into 'C:\Users\XX\Desktop\InventorySystem'...
remote: Enumerating objects: 442, done.        
remote: Counting objects: 100% (442/442), done.        
remote: Compressing objects: 100% (424/424), done.        
remote: Total 442 (delta 7), reused 431 (delta 2), pack-reused 0        
Receiving objects: 100% (442/442), 514.16 KiB | 2.79 MiB/s, done.
Resolving deltas: 100% (7/7), done.
Downloading Content/Characters/Mannequin_UE4/Animations/Jog_Fwd.uasset (203 KB)
Error downloading object: Content/Characters/Mannequin_UE4/Animations/Jog_Fwd.uasset (81b4dd2): Smudge error: Error downloading Content/Characters/Mannequin_UE4/Animations/Jog_Fwd.uasset (81b4dd2a00331ba3086ce06a8673667359183399c5fb1ab924060e2c84720691): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

Errors logged to 'C:\Users\XX\Desktop\InventorySystem\.git\lfs\logs\20240410T161346.5768514.log'.
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: Content/Characters/Mannequin_UE4/Animations/Jog_Fwd.uasset: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

### Release version

3.3.13

### Operating system

windows 10

**Comment by steveward** [comment]
@GuDuDeFe thanks for the issue. Unfortunately this is due to your LFS data quota running out. See [this set of articles](https://docs.github.com/en/billing/managing-billing-for-git-large-file-storage) for more information about LFS billing. If you have any questions I'd recommend reaching out to [GitHub Support](https://support.github.com/) for assistance. I'm going to close this out, but thanks for using GitHub Desktop!
