### ISSUE TITLE
Github Desktop New Repository Creation not working

### ISSUE THREAD

**Issue by rainerhamal** [desktop/desktop#18457]
### The problem

I tried to create a new repo from the desktop app using my windows machine. The app won't create anything. It doesn't show or do anything. It just sits there after I press create repository.

### Release version

Version 3.3.13 (x64)

### Operating system

Windows11

**Comment by steveward** [comment]
Thanks for the report @rainerhamal. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
