### ISSUE TITLE
Unable to connect with GitHub(option to connect with ---unable to open VSCode page disappears)

### ISSUE THREAD

**Issue by Illumina-ahedaoo** [desktop/desktop#18455]
### The problem

Unable to connect with GitHub(option to connect with ---unable to open VSCode page disappears)

### Release version

GibHub Desktop(64 Bit) - 3.3.13

### Operating system

Windows 10 Pro

### Screenshots

![Screenshot (17)](https://github.com/desktop/desktop/assets/162972599/ddba462b-7ae1-48ca-b2b2-46b1f9d6c539)
![Screenshot (18)](https://github.com/desktop/desktop/assets/162972599/1c7805a2-02a1-4a22-b57d-799ca0f915e8)
![Screenshot (17)](https://github.com/desktop/desktop/assets/162972599/bdffebfc-6309-41f5-bc50-795c0f148ec4)
![Screenshot (18)](https://github.com/desktop/desktop/assets/162972599/ac984c37-cb59-42c7-8f0b-627d1f410ddd)

**Comment by steveward** [comment]
@Illumina-ahedaoo thanks for the issue. I'm not sure I fully understand the issue you are encountering based on the screenshots. Are you unable to push your changes to GitHub? Any details you can share would be helpful.

Could you also upload the log file from GitHub Desktop so that I could get some more information about the issues you are encountering? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
