### ISSUE TITLE
Authentication failed. Some common reasons include:

### ISSUE THREAD

**Issue by aryo-dimas** [desktop/desktop#18464]
i dont know how fix it

**Comment by steveward** [comment]
Thanks for the report @aryo-dimas. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
