### ISSUE TITLE
Disambiguate repositories with the same name

### ISSUE THREAD

**Issue by joshaber** [desktop/desktop#1848]
Repositories are named by their GitHub repository or the on-disk directory if they can't be associated with a GitHub repository. This can pretty easily lead to naming collisions.

Some prior art:

<img width="194" alt="ad77f1b0-7cb7-11e4-846e-c62f6005509b-1" src="https://cloud.githubusercontent.com/assets/13760/26647207/89f9c8c8-460c-11e7-888b-2fde522c3a4a.png">

In this case, we have multiple clones of the same repository. So we start by disambiguating by GitHub owner name (`robrix`) and then, since that's still ambiguous, we append the containing directory name (`External` vs. `Swift`).

**Comment by joshaber** [comment]
This probably needs some Design Think /cc @donokuda @niik

**Comment by joshaber** [comment]
@niik @donokuda Could you guys talk this over at the next design roundup?

**Comment by joshaber** [comment]
To make this even more concrete, how do you all feel about a first step of prefixing the name with the owner?

**Comment by donokuda** [comment]
> To make this even more concrete, how do you all feel about a first step of prefixing the name with the owner?

I feel Goodman about prefixing the name with the owner here. If it covers the (albeit arbitrary) 80% of cases, then that's better than how we currently handle it. We could de-emphasize the owner so that the repo name is still easily scannable.

<img src='https://user-images.githubusercontent.com/1174461/27232884-7beb1eb4-526c-11e7-946b-29eb8339bfe3.png' width='300' />

Exposing extra information such as the directory starts to get a little trickier. I played around with adding the folder name to the right of the repo list, but not sure how that would play out with longer repo names or with folders with the same name (but different path.)

I think it's a start in disambiguating at the folder level. Totally open to ideas on how to iterate on it further.

**Comment by joshaber** [comment]
We can open another issue to disambiguate further based on path if the need arises.

**Comment by wshaver** [comment]
Ran into this issue today, where we have one repo with two very different branches. A months-long merge process from two separate teams. Both branches installed locally. Would be lovely to tell which one you're in at a glance. Both in the big repo list, and in the "current repository" thing when the list is closed.
