### ISSUE TITLE
[3.3.14 (x64)] macOS 14: Unable to fetch authenticated user 

### ISSUE THREAD

**Issue by Chenjp** [desktop/desktop#18481]
## Failed to login with Safari Browser. 
* Safari side: You are being redirected to the authorized application.
* GitHub Desktop side: Unable to fetch authenticated user 

### Release version

3.3.14 (x64)

### Operating system

macOS 14.4

**Comment by steveward** [comment]
Thanks for the report @Chenjp. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
