### ISSUE TITLE
GitHub desktop crasch

### ISSUE THREAD

**Issue by jakub22116** [desktop/desktop#18483]
### The problem

After fetching or try to enter options GitHub crash.  In home window there is message "Looks like there are no repositories for ...", I am sure there is repositories, i can see them in GitHub on browser. Also before this bug i was able to see them in GitHub Desktop. 
log:
warn: [ui] Error refreshing account 'acount'
TypeError: Failed to execute 'fetch' on 'Window': Invalid value

### Release version

3.3.14 (x64)

### Operating system

Windows 10

**Comment by sergiou87** [comment]
Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
