### ISSUE TITLE
Extreme slowdown with large commit messages

### ISSUE THREAD

**Issue by racosgrove** [desktop/desktop#18495]
### The problem

Large commit messages cause the interface to freeze for long periods, sometimes requiring the application to be restarted.

This will occur regularly if using 'squashed commits' which can accumulate very large commit messages for divergent branches.  The slow down occurs in both the History tab, and also the Changes tab when amending a commit and attempting to select/delete the message.  Generally this can be accomplished but sometimes it must be done outside of Github desktop due to the application freezing.  Other clients/web interfaces do not seem to have the same coping issues with long messages.

### Release version

3.3.14

### Operating system

MacOS Sonoma 14.1

### Steps to reproduce the behavior

1. Create a large commit message 
2. Open the history tab and observe application freeze for lengthy period
3. Amend commit and observe Git message form input freeze for lengthy period

**Comment by steveward** [comment]
Thanks for the report @racosgrove. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue. 

The log file should show the length of time operations are taking to complete.
