### ISSUE TITLE
Software stops running in the background

### ISSUE THREAD

**Issue by 821938089** [desktop/desktop#18548]
### The problem

When I wanted to discard over a thousand files, I minimized the software because it was taking too long. However, when I reopened it after some time, I found that it still hadn't finished executing.
Exactly when I minimized the software, the discard process paused until I reopened it.

### Release version

3.3.14

### Operating system

Windows 10

### Steps to reproduce the behavior

1. discard 1000+ file
2. minimize software

**Comment by steveward** [comment]
Thanks for the report @821938089. I'm going to add this to https://github.com/desktop/desktop/issues/7155 where we are tracking this issue.

**Comment by 821938089** [comment]
Related issue https://github.com/electron/electron/issues/9567

**Comment by Mancitiss** [comment]
@steveward is this issue and #7155 really related? If I understand correctly #7155 is about discarding changes being slow. This issue is about discarding changes PAUSE when Github Desktop is in background. It does not do anything at all when it is not visible on the screen, only when I let it sit idling on the foreground (focus or not) does it begin to continue discarding changes. if it is just slow then the number of files it deletes should still be scale with time as if it was running on foreground for the entire time, however, to me it just stuck there while in background (not visible on the screen).

**Comment by 821938089** [comment]
issue 7155 is actually outdated, the moveItemToTrash method is already asynchronous in the current source code, but the executor is still designed for blocking api's, there is no concurrent execution, leading to inefficiencies in moving files to the recycle bin.

Moreover, there is a bug in this executor that causes it to pause in the background.
