### ISSUE TITLE
GitHub Desktop - Flagged by Virus Total Vendors

### ISSUE THREAD

**Issue by paul-cossey** [desktop/desktop#18549]
### The problem

Hi, Folks 

Not really a bug, but the latest version of GitHub Desktop for macOS is being flagged by a couple of vendor on Virus Total. 

I'm pretty sure these are false positives, but you may wish to work with vendors to correct the errors. 

https://www.virustotal.com/gui/file-analysis/ODJjMTMyNDExOWU4M2RiMzRhOGI5YWYwM2I0YWMxZjk6MTcxNDc0MDk3OA== 

Thanks! 

### Release version

3.3.14

### Operating system

macOS

### Steps to reproduce the behavior

Download GitHub Desktop for macOS (Intel or Apple Silicon)
Upload to https://www.virustotal.com

**Comment by steveward** [comment]
Thanks for sharing this @paul-cossey! This does happen quite often when we update GitHub Desktop, especially with Git updates. I have reached out to some vendors in the past when we receive reports of this, and often they will self-resolve. I'll keep an eye out for further reports, but thanks again for the heads up!

**Comment by mhrono** [comment]
@steveward FWIW, 3.3.17 is _still_ being flagged on VirusTotal: https://www.virustotal.com/gui/file/3f503171e8eb6139ff6cd693dd59798f1e3216233f06985bf663ba34496e1b98/detection/f-3f503171e8eb6139ff6cd693dd59798f1e3216233f06985bf663ba34496e1b98-1715274325

Because of this, automations I have in place to keep my macOS fleet up to date are being held back. >0 VT detections on a package trigger the automation to fail. I can handle this manually and accept it as a false positive, but it'd be great to...not have to do that.

For additional context, the following tools are in use for this automation:
- [AutoPkg](https://github.com/autopkg/autopkg)
- [jamf-upload](https://github.com/grahampugh/jamf-upload)
- [VirusTotalAnalyzer](https://github.com/hjuutilainen/autopkg-virustotalanalyzer)

Happy to chat further and discuss workflows if necessary. AutoPkg (and the VirusTotalAnalyzer post-processor) are _very_ popular tools within the MacAdmins community, so this is likely affecting many more folks than take the time to open an issue or otherwise report it. I understand some of this is out of GitHub's control, especially interacting with third parties scanning your code/packages, but anything that can potentially be done to reduce the risk of false positives would be awesome.

**Comment by steveward** [comment]
Thanks for sharing that @mhrono. I'll reopen this for further investigation.

**Comment by steveward** [comment]
I [uploaded the most recent version](https://www.virustotal.com/gui/file/89eea11eeb85d533d48e343b71fb97d82dc2f5e8bd2c78daf44ea418897160ff) of GitHub Desktop and only one vendor (Ikarus) was flagging that version. I've reached out to Ikarus to get them to mark this as a false positive, and will follow up here when they confirm the change.

**Comment by paul-cossey** [comment]
Thanks, @steveward!

**Comment by paul-cossey** [comment]
Morning, @steveward 

I just rescanned our initial alert https://www.virustotal.com/gui/file/79dd7a600c1598cbf32603570aed72a57a3f52495bff30f795e401256bf4352b?nocache=1 

And we now have a clean bill of health! 🎉 

I'm happy for this to be closed if you are. 

Thanks for you efforts on this, much appreciated

**Comment by aukgit** [comment]
Hey @steveward 

It seems like you don't know how the virus is detected, you are doing something in your application that is not the right way. Probably you are calling APIs in a bad manner.

Please check which version is getting flagged by installing Avast and check the code differences.

Please fix it.
