### ISSUE TITLE
Autocomplete from issues repo

### ISSUE THREAD

**Issue by jpike88** [desktop/desktop#1855]
### Description

Autocomplete should be able to incorporate results from say, an issues repo. We work on a project that exists across two repos and use an issues repo to manage it. It's driving me insane using github desktop and not being able to specify an issue number easily in my commit messages.

### Version

**GitHub Desktop version:**0.5.9

**OS version:** macOS 10.12.4

### Steps to Reproduce

N/A

**Comment by joshaber** [comment]
Thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I'm going to add the `future-proposal` label to this issue and close it out, so that we don't get overwhelmed with our backlog! We'll revisit these as part of our next planning session.

**Comment by billygriffin** [comment]
Thanks @jpike88 for the idea. While I appreciate that using issues in a separate repo can make the issue autocompletion not particularly helpful, we haven't heard this as a commonly desired feature, so we're going to remove `future-proposal` to indicate that we don't intend to work on it. If we see this come up more frequently, we're absolutely open to revisiting that decision, and I'm sorry it's tricky to make work for your workflow.
