### ISSUE TITLE
Add support for proxy icons

### ISSUE THREAD

**Issue by nuno-agostinho** [desktop/desktop#1857]
### Description

The Electron version of GitHub Desktop is missing proxy icon support (available in the non-Electron version).

### Version

**GitHub Desktop version:** 0.5.9
**OS version:** 10.12.4

### Steps to Reproduce

1. Open any repository.

**Expected behaviour:** 
![screen shot 2017-06-01 at 12 17 06](https://cloud.githubusercontent.com/assets/3199157/26677562/79d4ed52-46c4-11e7-82e8-b7a7fab78d93.png)

**Actual behaviour:**
![screen shot 2017-06-01 at 12 21 27](https://cloud.githubusercontent.com/assets/3199157/26677693/f57a8c82-46c4-11e7-8e55-b73f19d0a852.png)

**Comment by shiftkey** [comment]
> proxy icon support

I'm not exactly clear what this refers to, even with the screenshots. Could you elaborate?

**Comment by shiftkey** [comment]
Was just pointed to [this article](http://www.macworld.com/article/1150425/business/proxyicons.html) which helps a bit with understanding the features. Due to switching over to using Electron and having to do all the UI work ourselves, this was something we lost. 

I'll leave this open for a bit to gauge interest.

**Comment by shiftkey** [comment]
@nuno-agostinho this idea is interesting for the future if we want to revisit the native integration that we lost in the transition to Electron, but it is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I added the `future-proposal` label to this issue and closed it so that we won't get overwhelmed with our backlog! We will revisit this in our next planning session.

**Comment by shiftkey** [comment]
I'm dropping the `future-proposal` label here because there doesn't seem to be much interest in it, and because the work required to reimplement the equivalent behaviour in Electron will take away from other more urgent work.

**Comment by j-f1** [comment]
If we switch to the native title bar, there’s an Electron API to add that proxy icon.

**Comment by shiftkey** [comment]
@j-f1 can you link to it here? I skimmed the `BrowserWindow` docs but couldn't spot it.

**Comment by j-f1** [comment]
It’s [`BrowserWindow#setRepresentedFilename`](https://devdocs.io/electron/api/browser-window#winsetrepresentedfilenamefilename-macos).
