### ISSUE TITLE
Pushing to origin infinity loading

### ISSUE THREAD

**Issue by iVoltion** [desktop/desktop#18570]
### The problem

I'm trying to push one small 3d asset to github, which has been working for the past 4 weeks but today, no... I'm trying to push that asset but it keeps and keeps loading. Can someone help me, i dont really know what to do anymore.
![Capture d’écran 2024-05-08 121214](https://github.com/desktop/desktop/assets/59234182/aaedf526-4c2f-4e27-bb1a-0cd427379f29)

### Release version

Version 3.3.15 (x64)

### Operating system

Windows 10

**Comment by sergiou87** [comment]
Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by sergiou87** [comment]
@iVoltion We are investigating and we'd appreciate if you could run `git remote -v` in the affected repo and share the output (redacting if necessary)

Or opening `Repository` -> `Repository Settings` and share a screenshot of the `Remote` section of that dialog. Thank you!

**Comment by philipplentzen** [comment]
Same for me, I'm on Version 3.3.15 (x64). A few hours ago GitHub Desktop offered me to install a new Version, which I did. Since then the Issue is present.

Last logs since launching, already pressed push (still spinning):
```
2024-05-08T16:43:40.797Z - info: [ui] launching: 3.3.15 (Windows 10.0.22631)
2024-05-08T16:43:40.837Z - info: [ui] execPath: 'C:\Users\_username_\AppData\Local\GitHubDesktop\app-3.3.15\GitHubDesktop.exe'
2024-05-08T16:43:44.684Z - info: [ui] Executing updateRemoteHEAD: git -c credential.helper= remote set-head -a origin (took 1.116s)
2024-05-08T16:44:48.751Z - info: [ui] Executing checkoutBranch: git -c credential.helper= checkout --progress _branchname_ --recurse-submodules -- (took 1.198s)
2024-05-08T16:44:49.836Z - info: [ui] [Timing] Action 'checkout branch from list' for '_repo_' took 2.291s
2024-05-08T16:44:58.344Z - info: [ui] Executing merge: git merge _branchname_ (took 1.790s)
```

_Tried to remove secret information_

**Comment by sergiou87** [comment]
@philipplentzen could you share the remote url (redacting whatever you need) following the steps from my latest comment? Thank you! 🙏

**Comment by philipplentzen** [comment]
This is the result of `git remote -v`

![image](https://github.com/desktop/desktop/assets/29258187/3a018423-dc85-45f7-8d03-480895723e50)

**Comment by iVoltion** [comment]
Here's the log and the result of git remote -v
[2024-05-08.desktop.production.log](https://github.com/desktop/desktop/files/15252314/2024-05-08.desktop.production.log)
![Capture d’écran 2024-05-08 130040](https://github.com/desktop/desktop/assets/59234182/96f56d44-3761-4211-8ebe-81659ad9b5a3)

**Comment by niik** [comment]
@philipplentzen @iVoltion We're preparing a new release which hopefully addresses these issue and at the very least should give us more data to troubleshoot. We expect to publish this to our beta channel in a little bit and we'd really appreciate it if you could try it out once it's shipped so that we know if we can go ahead and release that to everyone.

We'll reply back here as soon as the update has shipped with instructions on how to get the latest release.

**Comment by niik** [comment]
@philipplentzen @iVoltion We've just published 3.3.16-beta1 and would appreciate if you could download it from https://desktop.github.com/beta/ and give it a go and report back to us with the results.

If you're still not able to push please attach a log file again so that we can troubleshoot further

**Comment by tidy-dev** [comment]
@philipplentzen @iVoltion We have released the changes in beta to 3.3.16, but we do a slow rollout so you may not see an automatic update until it completes over the next few days. However, you can download the latest at https://desktop.github.com/ if you would like it sooner.

We would love an update on whether you are still see this issue in the new version.

**Comment by tidy-dev** [comment]
@philipplentzen @iVoltion We are still seeing reports of this and are tracking under. https://github.com/desktop/desktop/issues/18579 

Could you confirm if your repository is using Git LFS?

**Comment by philipplentzen** [comment]
@tidy-dev Installed Version 3.3.17 (x64) and it's working again. Thanks for the quick response and fixes.

**Comment by tidy-dev** [comment]
Great! Thanks for the feedback and sorry for the inconvenience
