### ISSUE TITLE
Unable to authenticated in a Self Hosted GitLab Instance

### ISSUE THREAD

**Issue by Raitorick** [desktop/desktop#18588]
### The problem

Hi Team.

Today after my GitHub Deskop get an update ,i have a problem when i was trying to fetch my branch.

![image](https://github.com/desktop/desktop/assets/41167823/d6633151-7795-4669-acfc-2b7b3c8ab97f)

First show me a form to prompt my credentials again, and when i put it show me the next screen.

![image](https://github.com/desktop/desktop/assets/41167823/1f54463d-0080-4736-ac85-97e399828596)

Before today i was worked correctly for more than 2 years

Thanks

### Release version

3.3.17( (x64)

### Operating system

Windows 10

### Screenshots

![image](https://github.com/desktop/desktop/assets/41167823/9763010b-5a1b-457c-80e2-9a4f3edd1677)

![image](https://github.com/desktop/desktop/assets/41167823/a13c76ea-8378-474b-88c8-6af164f56fbb)

**Comment by sergiou87** [comment]
@Raitorick  Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by Raitorick** [comment]
[2024-05-09.desktop.production.log](https://github.com/desktop/desktop/files/15265096/2024-05-09.desktop.production.log)



Sure, this is my log from today.

**Comment by sergiou87** [comment]
Also if you could tell us the output of `git remote -v` (or a screenshot of the `Repository` -> `Repository Settings…` dialog, in the `Remote` tab) after redacting anything you need, that'd be very useful.

Thank you and sorry about this!

**Comment by Raitorick** [comment]
![image](https://github.com/desktop/desktop/assets/41167823/cf2b012a-a572-4d49-ac91-f23f7352d5a6)

origin  http://192.168.2.128:8082/DiegoRivera1998/proyecto-en-blanco.git (fetch)
origin  http://192.168.2.128:8082/DiegoRivera1998/proyecto-en-blanco.git (push)

**Comment by sergiou87** [comment]
Thank you, we will investigate 🙏

**Comment by Raitorick** [comment]
Thanks, I aprreciate it.

I will keep in touch

**Comment by niik** [comment]
Hey @Raitorick, we've identified a problem with `http` (vs `https`) remotes where instead of prompting you for a new set of credentials when the request fails we keep using the old ones. We'll get onto finding a proper fix for that but in the meantime we'd really like your help to troubleshoot this a bit further.

First off you're going to have to clear the stored credentials for your host by opening DevTools (View menu -> Toggle Developer Tools). Then go to the Applications tab, click on Local Storage in the sidebar and locate the entry called `genericGitAuth/username/192.168.2.128` and delete it by right clicking and selecting delete.

![Image](https://github.com/desktop/desktop/assets/634063/5cec8b74-5e3d-48c9-b751-f13fa492f189)

Once you've deleted that you should get a new prompt for username and password on your next attempt to fetch, push, or pull.

While I'm not familiar with self hosted GitLab instances I know that the hosted version requires you to use an access token. Username and password is no longer valid. Please make sure that you enter your username and access token in the prompt dialog and let us know how that goes.

If you're still getting errors after having enterer username + PAT please make sure that you can clone on the command line using the same username and PAT.

**Comment by Raitorick** [comment]
Thank you very much.

I Delete the credential like you told me, and when i put i again in the prompt, it works correctly.

Thanks

**Comment by niik** [comment]
@Raitorick I'm so glad that resolved your issue and I'm very grateful that you were able to test it out and respond so quickly. Much appreciated! I've opened https://github.com/desktop/desktop/pull/18589 to fix the underlying issue and we'll get that into the next production release.

**Comment by Raitorick** [comment]
Thanks for all.

Take care!
