### ISSUE TITLE
GITHUB DESKTOP FAILS TO CLONE REPOSITORY

### ISSUE THREAD

**Issue by HassannKhan** [desktop/desktop#18595]
### The problem

It worked fine in the start but when I increased my usage of github, Github desktop client fails to download random repository at random times. This issue is not related to one repository, It happens at random time for random repository. 
![githubError](https://github.com/desktop/desktop/assets/91652736/62d575ba-7a26-44e4-be20-13d60c6c7719)

I am currently downloading the repo directly, making my changes in the code and than uploading the code again after creating a new repo. This is very frustrating but I can not stop making a backup of my changes neither can I stop making changes in my code. Somebody please help me sort this issue. Thanks in advance 

### Release version

 3.3.17

### Operating system

Windows 10

**Comment by steveward** [comment]
@Hassan1Khan thanks for the issue. 

Network issues are tricky to diagnose, and there isn't much we can do from our end about them since the underlying Git operations are failing. Some users have had success running the following config option:

`git config --global http.postBuffer 524288000`

There are also some HTTP timeout config operations that may help, or at lease provide additional diagnosis about the timeout. One user previously had success with these commands:

`git config --global http.lowSpeedLimit 1000`
`git config --global http.lowSpeedTime 20`

The `lowSpeedLimit` configures the minimum bytes per second, and the `lowSpeedTime` is the number of seconds. If the operation is lower than that threshold for the set time it will timeout. Adjusting those values may help with timeouts.

If neither of those suggestions work it may be worth trying to set [up a SSH key](https://docs.github.com/en/authentication/connecting-to-github-with-ssh), which some users have had more success with when encountering network issues. You could then switch the remote URL to use SSH in GitHub Desktop by going to `Repository` > `Repository Settings` > `Remote`. 

I'm going to close this out as there isn't anything we can do from our end to resolve this, but if you have any further questions let me know.

**Comment by Hassan1Khan** [comment]
You don't get to close the issue since my issue is not resolved. You can assign it to someone else who is not in hurry to mark it close.


When I said I am using Github Desktop, I clearly indicated I am not familiar with these command prompt lines neither do I know how to use them.



Would you be kind enough to guide me with the step by step process or would you just leave me scratching my head over gibberish text that you have given me?

**Comment by steveward** [comment]
You can run the commands by going to `Repository` > `Open in <command line app>`. You will need to install Git if you have not done so.

I would first try running the `git config --global http.postBuffer 524288000` command to see if that gets things working. If you have questions about the other commands I can assist further.

You can also use https://github-debug.com/ to test your connection to GitHub and then reach out to [GitHub Support](https://support.github.com/) to see if they can assist you further.

**Comment by HassannKhan** [comment]
If cloning of a repository is failed, how will I run said command for it? Or do you mean this command will run generally for all repositories if I set it for one?

**Comment by steveward** [comment]
This command will set the config option in the global .gitconfig file, which will apply to any commands that are run in GitHub Desktop and on the command line. You don't need to run it during cloning.

**Comment by DMLRBLX** [comment]
Can confirm that this works 👍. You're a genius! Thank you so much
