### ISSUE TITLE
not cloning repo

### ISSUE THREAD

**Issue by harisferoz-centric** [desktop/desktop#18601]
### The problem

I am unable to clone the repo since 24 hours as this message keeps on coming
error: RPC failed; curl 56 Failure when receiving data from the peer
error: 2739 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
my internet speed is 80-100 MBPS

### Release version

Version 3.3.17 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

simply clone repository via github desktop

**Comment by steveward** [comment]
@harisferoz-centric sorry to hear you're having trouble.

Network issues are tricky to diagnose, and there isn't much we can do from our end about them since the underlying Git operations are failing. Some users have had success running the following config option:

`git config --global http.postBuffer 524288000`

There are also some HTTP timeout config operations that may help, or at lease provide additional diagnosis about the timeout. One user previously had success with these commands:

`git config --global http.lowSpeedLimit 1000`
`git config --global http.lowSpeedTime 20`

The `lowSpeedLimit` configures the minimum bytes per second, and the `lowSpeedTime` is the number of seconds. If the operation is lower than that threshold for the set time it will timeout. Adjusting those values may help with timeouts.

If neither of those suggestions work it may be worth trying to set [up a SSH key](https://docs.github.com/en/authentication/connecting-to-github-with-ssh), which some users have had more success with when encountering network issues. You could then switch the remote URL to use SSH in GitHub Desktop by going to `Repository` > `Repository Settings` > `Remote`. 

I'm going to close this out as there isn't anything we can do from our end to resolve this, but if you have any further questions let me know.
