### ISSUE TITLE
Display how many files changed in History

### ISSUE THREAD

**Issue by pgoergler** [desktop/desktop#1862]
### Description

It could be great to see in commit history how many files where changed for each commit.
(This features exists in previous version of Github desktop)

### Version

**GitHub Desktop version:** [0.5.9] (beta)

**OS version:** [Mac OS]

**Comment by shiftkey** [comment]
@pgoergler any thoughts on how we could do this visually? Or are you attached to the existing style?

**Comment by pgoergler** [comment]
I like the existing one, and i prefer the existing 'history' design, because i can navigate throw the commits & files without using my mouse

**Comment by shiftkey** [comment]
This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I added the `future-proposal` label to this issue and closed it so that we won't get overwhelmed with our backlog! We will revisit this in our next planning session.
