### ISSUE TITLE
github for windows no longer working at all

### ISSUE THREAD

**Issue by Jezza1232** [desktop/desktop#18690]
### The problem

its like the hole app is now shutdown nothing to do with online works at all but EVERYTHING els system wide works without a problem its just your app fix it cant clone a darn thing

### Release version

.....

### Operating system

windows 10 

### Steps to reproduce the behavior

.....

### Log files

.....

### Screenshots

.....

### Additional context

  ....

**Comment by sergiou87** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by Jezza1232** [comment]
Will do thanks
