### ISSUE TITLE
The main branch does not automatically pull changes after commits/pr.

### ISSUE THREAD

**Issue by Samarancona01** [desktop/desktop#18713]
### The problem

The problem here is that a few weeks ago I could merge pull requests or simply commit changes (not locally) (for example someone else committed something on the main branch) and from another branch doing fetch I noticed that the main branch was also updating correctly and automatically (simply noticing the last update time stamp) . Now, however, I find myself in the situation where I have to manually go to the main branch, pull and then return to my work branch to update.

### Release version

Version 3.4.0 (x64)

### Operating system

Windows 11

**Comment by steveward** [comment]
Thanks for the issue @Samarancona01. GitHub Desktop performs fetch operations periodically in the background, and when it does so, it fast-forwards the outdated branches automatically. Sometimes it isn't possible to fast-forward due to changes in the local branch, which is when you would see the `Pull origin` option. I hope that helps explain things!
