### ISSUE TITLE
command not found error

### ISSUE THREAD

**Issue by cw-ritik** [desktop/desktop#18723]
### The problem

after upgrading github desktop to the latest version. it is not showing error while committing or publishing branch 

### Release version

Version 3.4.0 (x64)

### Operating system

Windows 11

### Steps to reproduce the behavior

try to commit it will give error

**Comment by sergiou87** [comment]
Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
