### ISSUE TITLE
Unable to push changes

### ISSUE THREAD

**Issue by madhuk1218** [desktop/desktop#18772]
### The problem

Unable to login even though provided with the correct credentials
![Screenshot 2024-06-05 150436](https://github.com/desktop/desktop/assets/133898471/173b7602-cb04-483b-a404-757e87291506)

### Release version

Version 3.4.0

### Operating system

Windows

**Comment by Arjunpride15** [comment]
plz apply for 2FA authenticator. Before that, install apps like WinOTP Authenticator or Google Authenticator

**Comment by sergiou87** [comment]
@madhuk1218 does the app prompt you for credentials?

**Comment by madhuk1218** [comment]
Yes. It is prompting for credentials. When entered, it is showing an error.

**Comment by steveward** [comment]
@madhuk1218 just to confirm, is this a GitHub or GitLab repository?

**Comment by madhuk1218** [comment]
I am using GITHUB UI

**Comment by steveward** [comment]
@madhuk1218 can you try logging out and logging back in by going to `File` > `Options` > `Accounts`?

**Comment by madhuk1218** [comment]
I am able to login. But when i try to push files, it is asking again for
password and ultimately not allowing me to push any data

Attached are the screen-shots

Thanks,
Madhu

**Comment by sergiou87** [comment]
Unfortunately attaching logs or screenshots via email doesn't work 😞 You need to share them with us from GitHub.com

 Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by madhuk1218** [comment]
Hi,

Please find attached logs.

Thanks,
Madhu

**Comment by steveward** [comment]
@madhuk1218 you'll need to upload them directly in an issue reply -- you can just drag-and-drop the files in.
