### ISSUE TITLE
not able to publish project

### ISSUE THREAD

**Issue by Arjunpride15** [desktop/desktop#18777]
### The problem

I want to publish my project, and I am not able to see the publish button. Plz help me.

### Release version

latest version

### Operating system

Windows 11

**Comment by sergiou87** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
