### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by AlexA2002** [desktop/desktop#18782]
### The problem

I tried multiple times to sign in, but the authentication fails. GitHub Desktop has redirected me to the browser, and I logged in successfully, but when it redirects me again to GitHub Desktop and I try to push to main, this error appears:

 Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.
- If you use SSH authentication, ensure the host key verification passes for your repository hosting service.
- If you used username / password authentication, you might need to use a Personal Access Token instead of your account password. Check the documentation of your repository hosting service.
I have already checked evry single one and I have everything needed.

### Release version

Version 3.4.1

### Operating system

Windows 10

**Comment by kane0723** [comment]
I have same problem after update latest version.

**Comment by steveward** [comment]
Thanks for the report @AlexA2002. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
