### ISSUE TITLE
Authentication failed. Some common reasons include:

### ISSUE THREAD

**Issue by sarugan** [desktop/desktop#18790]
### The feature request

Authentication failed. Some common reasons include:

### Proposed solution

![Screenshot_1](https://github.com/desktop/desktop/assets/127179578/e6a24bc1-3df6-4ad4-a1d6-147fccc8b602)

**Comment by sergiou87** [comment]
Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
