### ISSUE TITLE
Cannot clone repository in GitHub Desktop

### ISSUE THREAD

**Issue by letanloc1998** [desktop/desktop#18797]
### The problem

I received the error bellow when clone the repository in GitHub Desktop.
However, I can clone this repository when I used git command.
I cannot clone but I can fetch the existing repository with GitHub Desktop
This issue happened both windows and macos.

```

error: RPC failed; curl 92 HTTP/2 stream 7 was not closed cleanly: CANCEL (err 8)
error: 5654 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

```

### Release version

Version 3.4.1 (arm64)

### Operating system

Windows and MacOS

### Steps to reproduce the behavior

Clone the repository used Github Desktop.

**Comment by letanloc1998** [comment]
Temporary fixing:

```
git config --global pack.window 1
git config --global pack.depth 1
```

**Comment by steveward** [comment]
@letanloc1998 sorry to hear you're having trouble.

Network issues are tricky to diagnose, and there isn't much we can do from our end about them since the underlying Git operations are failing. Some users have had success running the following config option:

`git config --global http.postBuffer 524288000`

There are also some HTTP timeout config operations that may help, or at lease provide additional diagnosis about the timeout. One user previously had success with these commands:

`git config --global http.lowSpeedLimit 1000`
`git config --global http.lowSpeedTime 20`

The `lowSpeedLimit` configures the minimum bytes per second, and the `lowSpeedTime` is the number of seconds. If the operation is lower than that threshold for the set time it will timeout. Adjusting those values may help with timeouts.

If neither of those suggestions work it may be worth trying to set [up a SSH key](https://docs.github.com/en/authentication/connecting-to-github-with-ssh), which some users have had more success with when encountering network issues. You could then switch the remote URL to use SSH in GitHub Desktop by going to `Repository` > `Repository Settings` > `Remote`. 

I'm going to close this out as there isn't anything we can do from our end to resolve this, but if you have any further questions let me know.

**Comment by letanloc1998** [comment]
`git config --global http.postBuffer 524288000`
and
`git config --global http.lowSpeedLimit 1000`
`git config --global http.lowSpeedTime 20`

Those configurations didn't work, I already tried those configurations before using my configurations.

This configuration worked

```
git config --global pack.window 1
git config --global pack.depth 1
```

**Comment by letanloc1998** [comment]
I suggest Github desktop support SSH when pull/fetch repository.
