### ISSUE TITLE
Can't push

### ISSUE THREAD

**Issue by Tommy55Git** [desktop/desktop#18810]
### The problem

It says that i need to push 11 commits. When i push it stays the same and doesn´t push. And keeps asking to push it.

### Release version

Version 3.4.1

### Operating system

Windows 10

### Steps to reproduce the behavior

Click on push origin or ctrl+p.

**Comment by steveward** [comment]
Thanks for the report @Tommy55Git. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
