### ISSUE TITLE
Cannot push/pull/fetch

### ISSUE THREAD

**Issue by lukegordon333** [desktop/desktop#18845]
### The problem

Pushing/pulling/fetching just spins and spins with no result

### Release version

Version 3.4.1 (x64)

### Operating system

Windows Server 2016

**Comment by steveward** [comment]
Thanks for the report @lukegordon333. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by lukegordon333** [comment]
[2024-06-19.desktop.production.log](https://github.com/user-attachments/files/15904490/2024-06-19.desktop.production.log)

**Comment by steveward** [comment]
@lukegordon333 I'm not seeing anything there indicating why operations are stalling. Are you using SSH or HTTPS with this repository? Is this happening in multiple repositories? Are you behind a firewall or any other security software that could be interfering with your connection?

**Comment by lukegordon333** [comment]
I'm not sure to be honest. However it is happening on multiple different servers and repositories. I can commit changes but pushing/pulling/fetching is not working.

**Comment by niik** [comment]
Could you try the latest beta from https://desktop.github.com/beta and on Settings -> Advanced, enable Git Credential Manager? 

<img src="https://github.com/user-attachments/assets/e5f0affb-5e59-452e-ad83-eee710585456" width="626" />

Please, let us know if that works!
