### ISSUE TITLE
Error when publishing branch in a brand new repository.

### ISSUE THREAD

**Issue by OMajestatico** [desktop/desktop#18840]
### The problem

I'm making a game using python. And, to keep the process online, I had the idea to publish it on GitHub
So i created a repository, placed the files there, and commited it. It happened with no problems.
But when I try to publish the **main** branch to GitHub, this apears on my screen:
```
fatal: protocol error: bad line length 183
send-pack: unexpected disconnect while reading sideband packet
error: failed to push some refs to 'https://github.com/OMajestatico/pulsus_master.git'
Enumerating objects: 72, done.
Counting objects: 100% (72/72), done.
Delta compression using up to 8 threads
Compressing objects: 100% (60/60), done.
Writing objects:  30% (22/72)
```

I don't know if this question is duplicated. Please, tell me if it is.

### Release version

Version 3.4.1 (x64)

### Operating system

Windows 10

### Screenshots

![image](https://github.com/desktop/desktop/assets/87951955/0384f332-dd86-45ea-af7c-aedd1db6eea7)

### Additional context

I don't know if it happens in all my repositories, I think no.
Could you guys help me, please?

**Comment by steveward** [comment]
@OMajestatico thanks for the issue. These types of errors usually indicate a network connection issue. Are you on a reliable connection? Are you trying to push a large repository?

You can test your connection by going to https://github-debug.com/. Network issues are tricky to diagnose, and there isn't much we can do from our end about them since the underlying Git operations are failing. Some users have had success running the following config option:

`git config --global http.postBuffer 524288000`

There are also some HTTP timeout config operations that may help, or at lease provide additional diagnosis about the timeout. One user previously had success with these commands:

`git config --global http.lowSpeedLimit 1000`
`git config --global http.lowSpeedTime 20`

The `lowSpeedLimit` configures the minimum bytes per second, and the `lowSpeedTime` is the number of seconds. If the operation is lower than that threshold for the set time it will timeout. Adjusting those values may help with timeouts.

If neither of those suggestions work it may be worth trying to set [up a SSH key](https://docs.github.com/en/authentication/connecting-to-github-with-ssh), which some users have had more success with when encountering network issues. You could then switch the remote URL to use SSH in GitHub Desktop by going to `Repository` > `Repository Settings` > `Remote`. 

Let me know if you have any questions about that.

**Comment by OMajestatico** [comment]
I will try it, 'cause i can it now, but thanks for the help! I gonna return you when i test it.
Thanks again!

**Comment by OMajestatico** [comment]
Hey! I just tried the `git config --global http.postBuffer 524288000` command and it worked! Thanks for the help dude!
