### ISSUE TITLE
GitHub Desktop Got Very Slow (Poor Performance)

### ISSUE THREAD

**Issue by gabriel-piltzer-trimble** [desktop/desktop#18850]
### The problem

Over the past month or 2 GitHub Desktop appears to have gotten even slower than usual.

### Release version

3.4.1 (x64)

### Operating system

Windows 11

### Steps to reproduce the behavior

1. Authenticate in GitHub Desktop with username and password.
2. Clone a repo
3. Basic operations like fetch or pull are taking 10-20 seconds.

### Log files

[2024-06-19.desktop.production.log](https://github.com/user-attachments/files/15915505/2024-06-19.desktop.production.log)

**Comment by niik** [comment]
Hey @gabriel-piltzer-trimble, thanks for reaching out. I'm sorry to hear of the apparent slowdowns you're experiencing. Unfortunately I don't see anything out of the ordinary in the log file you provided. Most fetches complete within 1-2 seconds and some take longer. My experience tells me this is likely related to your environment or network somehow. I've not experienced any slowdowns myself and we haven't received any other reports similar to yours.

As a first step I would install (if you haven't already) Git for Windows and experiment with fetching/pulling using the terminal to see if the issue is reproducible there. I also see some mentions of GitHub Desktop failing to read due to excessively large output making me suspect that the repository in question could contain large files and/or large number of changes which could affect the performance.

You could also try removing all repositories from GitHub Desktop and then adding repositories back one by one to see if any particular repository introduces the performance regression.

If you find anything specific to Desktop please let us know and we'll reopen this but for now I'm afraid I don't see anything actionable with regards to Desktop.
