### ISSUE TITLE
Authorise github desktop

### ISSUE THREAD

**Issue by asharahul** [desktop/desktop#18859]
### The problem

I can not authorised my GitHub desktop. please solve this problem.

### Release version

3.4.1  (x64)

### Operating system

windows 10

### Additional context

I can not authorise my GitHub desktop.

**Comment by niik** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

In this case the description is too vague to act on. Please update the issue to include detailed description of the problem you're encountering (and preferably screenshots). A log file is always helpful as well. To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

Thanks for understanding and meeting us half way :grinning: Once you've updated the issue please add a comment to that effect and we'll take another look.

**Comment by ilya-corneli** [comment]
same(
