### ISSUE TITLE
Face issues in cloning repositories and sametimes on pull requests

### ISSUE THREAD

**Issue by Elves-Chissique** [desktop/desktop#18861]
### The problem

Cloning into 'C:\Users\pedro\Documents\GitHub\Projecto-Igreja'...
remote: Enumerating objects: 135, done.        
remote: Counting objects: 100% (135/135), done.        
remote: Compressing objects: 100% (87/87), done.        
error: RPC failed; curl 56 Failure when receiving data from the peer
error: 288 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

Would you like to retry cloning ?

### Release version

Version 3.3.8 (x64)

### Operating system

windows 11

### Screenshots

![GuitHub Desktop](https://github.com/desktop/desktop/assets/63803044/f77c713b-186b-4640-b9bb-a267105384ce)

**Comment by niik** [comment]
@Elves-Chissique thanks for the issue. These types of errors usually indicate a network connection issue. Are you on a reliable connection? Are you trying to push a large repository?

You can test your connection by going to https://github-debug.com/. Network issues are tricky to diagnose, and there isn't much we can do from our end about them since the underlying Git operations are failing. Some users have had success running the following config option:

`git config --global http.postBuffer 524288000`

There are also some HTTP timeout config operations that may help, or at lease provide additional diagnosis about the timeout. One user previously had success with these commands:

`git config --global http.lowSpeedLimit 1000`
`git config --global http.lowSpeedTime 20`

The `lowSpeedLimit` configures the minimum bytes per second, and the `lowSpeedTime` is the number of seconds. If the operation is lower than that threshold for the set time it will timeout. Adjusting those values may help with timeouts.

If neither of those suggestions work it may be worth trying to set [up a SSH key](https://docs.github.com/en/authentication/connecting-to-github-with-ssh), which some users have had more success with when encountering network issues. You could then switch the remote URL to use SSH in GitHub Desktop by going to `Repository` > `Repository Settings` > `Remote`. 

Best of luck!
