### ISSUE TITLE
Windows ARM architecture not detected on desktop.github.com

### ISSUE THREAD

**Issue by wojtekmaj** [desktop/desktop#18879]
### The problem

When accessing desktop.github.com from a Windows ARM machine, I was offered the "Download for Windows (64bit), despite ARM builds being [available](https://central.github.com/deployments/desktop/desktop/latest/win32-arm64).

### Release version

n/a

### Operating system

Windows 11 ARM64

### Steps to reproduce the behavior

1. Go to https://desktop.github.com/ on a Windows ARM machine
2. Observe what the main CTA button says and where it links to

**Comment by wojtekmaj** [comment]
Huh or maybe I am wrong and this link is not intended for use? https://armrepo.ver.lt/ says GitHub Desktop is available for ARM though, but it might be a ticket for _them_, too...

**Comment by niik** [comment]
Hi @wojtekmaj, thanks for reaching out! Arm support on Windows is still in beta and that's why it's not available as a separate download on desktop.github.com. 

We're holding off on shipping to production until Git for Windows is able to support arm64 (https://github.com/git-for-windows/git/issues/3107)

You can download our beta version which will automatically update to the arm64 version.

Hope that helps!

**Comment by viveksh1** [comment]
> Hi [@wojtekmaj](https://github.com/wojtekmaj), thanks for reaching out! Arm support on Windows is still in beta and that's why it's not available as a separate download on desktop.github.com.
> 
> We're holding off on shipping to production until Git for Windows is able to support arm64 ([git-for-windows/git#3107](https://github.com/git-for-windows/git/issues/3107))
> 
> You can download our beta version which will automatically update to the arm64 version.
> 
> Hope that helps!

Are there any plans to release the arm64 Windows builds to production now that Git for Windows has native arm64 Windows builds?

https://github.com/git-for-windows/git/issues/3107

https://github.com/git-for-windows/git/releases/latest
