### ISSUE TITLE
Website optimization for download section

### ISSUE THREAD

**Issue by kaganergovan** [desktop/desktop#18874]
### The feature request

Hello,

So far I reset my Mac and as an essential first apps, I went desktop.github.com to download client, however I realized that still Apple Silicon version is below the download button as secondary. I think huge part of Mac users - especially devs - already switched silicon macs.

### Proposed solution

It should be new button with dropdown or secondary button to more accessible.

**Comment by niik** [comment]
Hey @kaganergovan, thanks for reaching out! I'm happy to hear you consider Desktop an essential app :smile:

I took a look at our numbers like you suspected arm64 does outnumber x64 (but x64 is still quite common). That said, when users download the x64 version on an Apple Silicon machine it will run just fine and it will automatically update itself to the arm64 version. The opposite is not true however, if a user on an Intel Mac downloads the Apple Silicon version it will not launch.

So in order to minimize friction for all users we're going to wait to change the default a little while longer. I have made scheduled a reminder for the team to re-evaluate this in the fall.
