### ISSUE TITLE
lag in macOS release

### ISSUE THREAD

**Issue by Zweihorn** [desktop/desktop#18898]
### The problem

As of today 2024-06-26 20:25 CEST the proposed latest _macOS_ download **does not deliver current version 3.4.2** but the older version 3.4.1 as of 2025-06-05 instead.

This is true for _both x86 and arm64 macOS versions_, unfortunately.

  * https://central.github.com/deployments/desktop/desktop/latest/darwin
  * https://central.github.com/deployments/desktop/desktop/latest/darwin-arm64

However, latest version should be 3.4.2 as of 2024-06-25 obviously.
  * https://desktop.github.com/release-notes/

Reload page did not help and problem continued over several downloads.

### Release version

3.4.2

### Operating system

macOS

### Steps to reproduce the behavior

Normal web use of a.m. download page for GitHub Desktop

### Log files

n.a.

### Screenshots

n.a.

### Additional context

Firefox ESR 115.12.0esr

Not an issue with GitHub Desktop itself but with the GIT release process in the back or human error, apparently,

**Comment by steveward** [comment]
@Zweihorn thanks for the issue. We gradually roll out updates and we temporarily paused the rollout to verify there aren't any issues. 

Once the update is available to you the client will automatically download it and let you know that it's ready to be installed. If you don't want to wait you can hold down the Alt key in the about dialog while pressing the check for updates button. That will skip the rollout queue and get you the latest available update. If that doesn't find a new update it's because we've paused the rollout. 

If you're interested in helping us test out the latest builds please check out our [beta channel](https://github.com/desktop/desktop?tab=readme-ov-file#beta-channel).

**Comment by steveward** [comment]
Just to confirm since my previous reply was not worded the best -- we've currently paused the rollout of this release and plan to proceed very gradually due to the changes introduced, so the shortcut I mentioned above to force the update will not work. We appreciate your patience as we roll this release out!

**Comment by Zweihorn** [comment]
> @Zweihorn thanks for the issue. We gradually roll out updates and we temporarily paused the rollout to verify there aren't any issues.

Not happy.  IMHO this would need you or your team to make amendments to the so-called release info immediately, please.

* https://desktop.github.com/release-notes/

@steveward - Please be more transparent on issues like this or you will loose some user's trust, I fear.

Thanks for your efforts and keep on the good work.

🌻
