### ISSUE TITLE
Customise Github Path

### ISSUE THREAD

**Issue by JoecosB** [desktop/desktop#18897]
### The feature request

The original GitHub path for MacOS is ~./documents/GitHub, but this path is in apple's icloud too. I don't want it to happen

### Proposed solution

Let users customise the path for your local git in preferences.

**Comment by niik** [comment]
Hey @JoecosB, thanks for reaching out! The default clone path should be based on the last location that you cloned to. If you clone the next repository into a different directory (like `~/GitHub`) that should be persisted for future clones until you change the path again.

I appreciate that this isn't all that discoverable and we've had requests before that indicate people are looking for an explicit option (https://github.com/desktop/desktop/issues/2106).

Could you please give cloning into a different directory a shot so that we can rule out this being a bug or not?

**Comment by JoecosB** [comment]
I have done cloning into `~/GitHub` in terminal(not in Github Desktop), but the next clone in GitHub desktop still goes into `~/Documents/Github`. 

<img width="960" alt="QQ20240626-213455@2x" src="https://github.com/desktop/desktop/assets/130775789/00e93300-2003-4e85-8896-323c9ddc14eb">

Furthermore, after I moved the whole directory by `mv ./Documents/Github ./Github`, GitHub Desktop can no longer find my repositories, because `./Documents/Github` no longer exists. To solve this problem, I have to click into all my repos and click the "Locate..." button to relocate the moved repo. Thats indeed why I want to customise the default local git path.

<img width="960" alt="QQ20240626-213345@2x" src="https://github.com/desktop/desktop/assets/130775789/23bd7546-2988-496d-8275-663809c556d1">

I may have mistaken your instructions, but I hope there will be a better way to locate my local git directory! Maybe I can set the default git path of GitHub Desktop, and the app finds git repositories by given default path, instead of finding path by selected repository!

**Comment by niik** [comment]
> I have done cloning into ~/GitHub in terminal(not in Github Desktop),

Hey @JoecosB, my apologies, I should have been more specific. When you clone in GitHub Desktop you can set the destination folder like so

![Image](https://github.com/user-attachments/assets/1c5d526e-649f-4c37-bb2c-29ad51ce2c39)

See the Local path text box? If you change the location there to `/Users/joecos_kun/GitHub/[repo name]` GitHub Desktop should remember that's where you want all your future clones to go. The repositories that you've already cloned locally you'll have to move manually and then tell GitHub Desktop where you moved them just like you did already.

**Comment by JoecosB** [comment]
Thank you for your instructions :^)
