### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by dotnetgoldmine** [desktop/desktop#18904]
### The problem

Cloning into 'C:\Users\\Documents\GitHub\abc'...
remote: Enumerating objects: 2070, done.        
remote: Counting objects: 100% (796/796), done.        
remote: Compressing objects: 100% (422/422), done.        
error: RPC failed; curl 92 HTTP/2 stream 7 was not closed cleanly: CANCEL (err 8)
error: 469 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

Would you like to retry cloning ?

### Release version

Version 3.4.1 (x64

### Operating system

windows 11

### Log files

tepad++ v8.6.8 bug-fixes & new enhancements:

 1. Fix a crash in Column Editor caused by an arithmetic overflow.
 2. Fix the issue where any negative repeat value in Column Editor causes a hang.
 3. Fix an extra space being inserted in HEX mode issue in Column Editor.
 4. Fix a visual glitch of the toolbar pressed buttons in dark mode.
 5. Add auto-indent feature for Python.
 6. Fix the issue where "show control characters" settings not remembered when switching to another tab.
 7. Fix the missing monitoring disabled state icon from the fluent icon set on the toolbar.
 8. Adjusted the inaccurate naming of indent settings in thee Preferences dialog.
 9. Fix the issue where the customized color of active tab in inactive view is missing.
10. Introduce a new plugin command "NPPM_GETTABCOLORID" to retrieve the current tab color ID.
11. Allow the tree view dark mode customization for plugins.
12. Fix the popup dialog for updating not metioning 'Notepad++'.

Get more info on
https://notepad-plus-plus.org/downloads/v8.6.8/

Included plugins:

1.  NppExport v0.4
2.  Converter v4.6
3.  Mime Tool v3.1

Updater (Installer only):

* WinGUp (for Notepad++) v5.2.9

### Screenshots

testtepad++ v8.6.8 bug-fixes & new enhancements:

 1. Fix a crash in Column Editor caused by an arithmetic overflow.
 2. Fix the issue where any negative repeat value in Column Editor causes a hang.
 3. Fix an extra space being inserted in HEX mode issue in Column Editor.
 4. Fix a visual glitch of the toolbar pressed buttons in dark mode.
 5. Add auto-indent feature for Python.
 6. Fix the issue where "show control characters" settings not remembered when switching to another tab.
 7. Fix the missing monitoring disabled state icon from the fluent icon set on the toolbar.
 8. Adjusted the inaccurate naming of indent settings in thee Preferences dialog.
 9. Fix the issue where the customized color of active tab in inactive view is missing.
10. Introduce a new plugin command "NPPM_GETTABCOLORID" to retrieve the current tab color ID.
11. Allow the tree view dark mode customization for plugins.
12. Fix the popup dialog for updating not metioning 'Notepad++'.

Get more info on
https://notepad-plus-plus.org/downloads/v8.6.8/

Included plugins:

1.  NppExport v0.4
2.  Converter v4.6
3.  Mime Tool v3.1

Updater (Installer only):

* WinGUp (for Notepad++) v5.2.9

### Additional context

testtepad++ v8.6.8 bug-fixes & new enhancements:

 1. Fix a crash in Column Editor caused by an arithmetic overflow.
 2. Fix the issue where any negative repeat value in Column Editor causes a hang.
 3. Fix an extra space being inserted in HEX mode issue in Column Editor.
 4. Fix a visual glitch of the toolbar pressed buttons in dark mode.
 5. Add auto-indent feature for Python.
 6. Fix the issue where "show control characters" settings not remembered when switching to another tab.
 7. Fix the missing monitoring disabled state icon from the fluent icon set on the toolbar.
 8. Adjusted the inaccurate naming of indent settings in thee Preferences dialog.
 9. Fix the issue where the customized color of active tab in inactive view is missing.
10. Introduce a new plugin command "NPPM_GETTABCOLORID" to retrieve the current tab color ID.
11. Allow the tree view dark mode customization for plugins.
12. Fix the popup dialog for updating not metioning 'Notepad++'.

Get more info on
https://notepad-plus-plus.org/downloads/v8.6.8/

Included plugins:

1.  NppExport v0.4
2.  Converter v4.6
3.  Mime Tool v3.1

Updater (Installer only):

* WinGUp (for Notepad++) v5.2.9

**Comment by steveward** [comment]
@dotnetgoldmine are you encountering an issue with GitHub Desktop? The first portion of your issue looks like it's from the log file/error output, but the rest of the template does not look related. The error you're encountering looks like a network related issue. Are you on a reliable connection? Are you trying to push a large repository?

You can test your connection by going to https://github-debug.com/. Network issues are tricky to diagnose, and there isn't much we can do from our end about them since the underlying Git operations are failing. Some users have had success running the following config option:

`git config --global http.postBuffer 524288000`

There are also some HTTP timeout config operations that may help, or at lease provide additional diagnosis about the timeout. One user previously had success with these commands:

`git config --global http.lowSpeedLimit 1000`
`git config --global http.lowSpeedTime 20`

The `lowSpeedLimit` configures the minimum bytes per second, and the `lowSpeedTime` is the number of seconds. If the operation is lower than that threshold for the set time it will timeout. Adjusting those values may help with timeouts.

If neither of those suggestions work it may be worth trying to set [up a SSH key](https://docs.github.com/en/authentication/connecting-to-github-with-ssh), which some users have had more success with when encountering network issues. You could then switch the remote URL to use SSH in GitHub Desktop by going to `Repository` > `Repository Settings` > `Remote`. 

Let me know if you have any questions about that.
