### ISSUE TITLE
How to `git clone` NOT-including submodules?

### ISSUE THREAD

**Issue by dacaiguoguogmail** [desktop/desktop#1890]
default Recurse Submodules, where to close it?

**Comment by shiftkey** [comment]
@dacaiguoguogmail we don't currently expose this as an option.

Can you tell me a bit about why you need to disable this, so I can understand the scenario better?

**Comment by dacaiguoguogmail** [comment]
I clone `https://github.com/CocoaPods/Core.git ` when I found clone submodules
But I do not need it.

**Comment by joshaber** [comment]
Thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I'm going to add the `future-proposal` label to this issue and close it out, so that we don't get overwhelmed with our backlog! We'll revisit these as part of our next planning session.

**Comment by billygriffin** [comment]
@dacaiguoguogmail Thanks for the idea! Because this isn't something we've heard broadly from others, I'm going to remove `future proposal` to indicate that we don't intend to support an option like this in the near term. However, we're always open to changing our view if we see evidence that it would be helpful for many others. Thanks again!

**Comment by dacaiguoguogmail** [comment]
OK
