### ISSUE TITLE
Clone Repository issue

### ISSUE THREAD

**Issue by m-muneeb169** [desktop/desktop#18911]
i've send my email id to my ambassador and he give me the access to clone the repository / project. In starting , it clone accurately and i started working on that project, but now when i try to push the code to make website live, then it shows an error of denied access. Even, when i try to clone the repository / project again, it shows an error of denied access, even i've an access and the project files,issues,pulls accurately open. Also i checked this again from the ambassador system, he give me an access to work on it and after push the code of this. Here are my credentials isses, i think , My collegues said to me, there are an credentials issues of vs code and github. you log in from different mails to vs code and on github, So kindly as soon as possible , Respond me and resolve this my issue, Thanks.

**Comment by m-muneeb169** [comment]
![Screenshot (537)](https://github.com/desktop/desktop/assets/167106234/18a2e436-6d4d-4185-bf23-cbf18350d9c8)

**Comment by m-muneeb169** [comment]
![Uploading Screenshot (538).png…]()

**Comment by m-muneeb169** [comment]
![Screenshot (538)](https://github.com/desktop/desktop/assets/167106234/38c7a6b0-d46f-4488-9941-1558ea45faa4)

**Comment by steveward** [comment]
Thanks for the report @m-muneeb169. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
