### ISSUE TITLE
Git hub Desktop Login Issue

### ISSUE THREAD

**Issue by Uksharma2611** [desktop/desktop#18923]
Hey! I'm facing issues while loggin in github desktop with browser

**Comment by sergiou87** [comment]
@Uksharma2611  Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
