### ISSUE TITLE
Intermittently Unable to Reauthenticate Azure DevOps Repository Connection

### ISSUE THREAD

**Issue by dynamiccookies** [desktop/desktop#18930]
### The problem

Sometimes when the Azure DevOps Personal Access Token (PAT) expires, I'm only given the following error message without an option to re-enter the PAT:
![thumbnail_image002](https://github.com/desktop/desktop/assets/9450183/4138e755-38cf-431e-82e5-5f1d2acbdf23)

Then, when I click the Open Options button, I'm only given GitHub.com and GitHub Enterprise as account options:
![thumbnail_image001](https://github.com/desktop/desktop/assets/9450183/e48e4e34-1ea0-43d3-9b2a-5ea1c5869c09)

### Release version

3.4.1

### Operating system

Windows 10 Enterprise, version 22H2, OS build 19045.4529

### Steps to reproduce the behavior

Unfortunately this isn't easily reproducible.

1. Clone a repository from Azure DevOps using the URL option in GitHub Desktop
![Screenshot 2024-07-02 134943](https://github.com/desktop/desktop/assets/9450183/e810166c-9bca-46f7-afea-ac0fae06601d)

2. When prompted for authentication credentials, use the Generate Git Credentials button on the ADO repo
![thumbnail_image001 (1)](https://github.com/desktop/desktop/assets/9450183/da5166a8-ebf8-468c-bd91-bea518895da5)

3. Now you need to wait until the authentication expires, 
    a. BUT most of the time that's ok because it presents you with the Authentication Failed popup where you can re-enter the Personal Access Token from ADO
    ![thumbnail_image001 (2)](https://github.com/desktop/desktop/assets/9450183/5a90f65c-556a-4928-9725-d6f9a7968150)

    b. Only sometimes you're given the error message with no option to re-enter the PAT
    ![thumbnail_image002](https://github.com/desktop/desktop/assets/9450183/186bef6e-647a-4a70-94c1-e59fc1996723)

### Log files

Unfortunately, I cannot upload the log files because this happened on my work computer and that's not allowed. I'll try to reproduce on my personal computer through a person ADO account. I'll upload logs if/when I can reproduce.

### Additional context

I've verified this has happened to myself and coworkers, but it is intermittent. Most of the time we're just prompted with the popup that asks for the PAT again. 

The only work around I've found is to clone a completely different repo, which will then prompt for the PAT.

I know I'm entering this as a Bug, but it could be changed to a Feature Request if the solution is to just add the URL account details on the Options screen:
![thumbnail_image001](https://github.com/desktop/desktop/assets/9450183/7db821c5-3b32-4301-af3c-7167cb5c30ef)

**Comment by sergiou87** [comment]
Hello @dynamiccookies  👋 

Please, download the latest 3.4.2 from https://desktop.github.com 

This version hasn't been rolled out as an auto-update to all users _yet_ but (and because) it includes support for Git Credential Manager, which will be super helpful for exactly this situation. Just open `Settings -> Advanced` and make sure `Use Git Credential Manager` is checked.

Next time you fetch it will prompt you to login on Azure DevOps, and Git Credential Manager will take care of creating PATs as needed (or will use an OAuth token, I'm not sure) so you don't need to worry again.

![Image](https://github.com/user-attachments/assets/8b51baf8-436b-4969-8660-e7922de3f7a8)

Please let me know if that helps!
