### ISSUE TITLE
Experiencing an error with `GIT_CONFIG_VALUE_0` when using pre-commit

### ISSUE THREAD

**Issue by paulloz** [desktop/desktop#18945]
### The problem

Hello, this issue is a follow-up to:
- pre-commit/pre-commit#3245

For context, `pre-commit` is a framework to manage, and run git hooks. Until last week, I never experienced any issue working with it in coordination with GitHub Desktop. As described in the linked issue, though, there seem to be some error happening now when committing only part of your local changes (as in: there are still unstaged changes in the working directory). At that point, `pre-commit` will automatically stash all the unstaged changes before running the hooks, and subsequently unstash them. During the unstash, the following error occurs:

```
An unexpected error has occurred: CalledProcessError: command: ('C:\\Users\\paulloz\\AppData\\Local\\GitHubDesktop\\app-3.4.2\\resources\\app\\git\\mingw64\\bin\\git.EXE', '-c', 'core.autocrlf=false', 'apply', '--whitespace=nowarn', 'C:\\Users\\paulloz\\.cache\\pre-commit\\patch1720022447-4396')
return code: 128
stdout: (none)
stderr:
    error: missing config value GIT_CONFIG_VALUE_0
    fatal: unable to parse command-line config
```

Of course, this happens exclusively when working through GitHub Desktop, and not when working from the CLI.

It's a tad hard to list clean reproduction steps, as the error happening or not seem to depend on several factors. Nevertheless, I can provide more info if needed, feel free to ask.

Cheers.

### Release version

Version 3.4.2 (x64)

### Operating system

Windows 10

**Comment by sergiou87** [comment]
👋  I've read the other issue you link and I'm not sure if it's Desktop fault…

Just to confirm, these are indeed added by GitHub Desktop on v3.4.2:
```
'GIT_CONFIG_KEY_0': 'credential.helper'
'GIT_CONFIG_KEY_1': 'credential.helper'
'GIT_CONFIG_VALUE_0': ''
'GIT_CONFIG_VALUE_1': 'desktop'
```

The reasoning is [`credential.helper` is a list of values](https://git-scm.com/docs/gitcredentials#Documentation/gitcredentials.txt-helper:~:text=If%20there%20are,you%20would%20like%29.), so if we want to set it to only one value (instead of appending anything to the existing list) we have to first set it to empty string, and then append the only value we want (in this case, `desktop`).

It'd be very useful if we could know, at the point where that command is run, whether or not that `GIT_CONFIG_VALUE_0=''` env variable is present and therefore (I hope) passed to git. My suspicion, and of course I might be completely wrong, is _something_ is ignoring `GIT_CONFIG_VALUE_0` because it's empty.

**Comment by paulloz** [comment]
I mostly agree, I think it is either that, or the env not being passed down correctly.

**Comment by sergiou87** [comment]
Since I'm unable to repro this, would you be able to try and inspect what's getting to that `git` call? 🙏

**Comment by paulloz** [comment]
After a bit of fiddling around, here's my understanding. Windows does not allow environment variables to be set to empty strings (empty string essentially means the variable does not exist). So when a new process is created from python, it doesn't actually grab the empty variable. Here are all the `GIT_*` variables received by the child process when the error occurs:
```
{
  'GIT_AUTHOR_DATE': '@1720439312 +0200',
  'GIT_AUTHOR_EMAIL': '[REDACTED]',
  'GIT_AUTHOR_NAME': 'Paul Joannon',
  'GIT_CONFIG_COUNT': '2',
  'GIT_CONFIG_KEY_0': 'credential.helper',
  'GIT_CONFIG_KEY_1': 'credential.helper',
  'GIT_CONFIG_VALUE_1': 'desktop',
  'GIT_EDITOR': ':',
  'GIT_EXEC_PATH': 'C:\\Users\\paulloz\\AppData\\Local\\GitHubDesktop\\app-3.4.2\\resources\\app\\git\\mingw64\\libexec\\git-core',
  'GIT_INDEX_FILE': '.git/index',
  'GIT_SSH_COMMAND': 'C:/Windows/System32/OpenSSH/ssh.exe', 'GIT_USER_AGENT': 'git/2.45.1.windows.1 (GitHub Desktop/3.4.2; win32 x64)'
}
```
It seems like this can be circumvented in `pre-commit` by always explicitly supplying an environment to child processes. But I must admit it feels like a hack, and I'm wondering if this issue will not arise in other tools 🤔

**Comment by JohannSig** [comment]
Having this problem. Please sync with the precommit team and come up with a solution ASAP. Having my unstaged changes reverted by precommit renders GitHub Desktop unusable in my workplace.

**Comment by mccarthysean** [comment]
I've been having the same problem with GitHub Desktop. It erases all the changes in some of my files!

![image](https://github.com/desktop/desktop/assets/24639847/c2d777b1-2099-47d1-a7ad-e70614eb820a)

Here's the pre-commit.log file:

### version information

```
pre-commit version: 3.4.0
git --version: git version 2.45.1.windows.1
sys.version:
    3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 64 bit (AMD64)]
sys.executable: C:\Users\seanm\AppData\Local\Programs\Python\Python311\python.exe
os.name: nt
sys.platform: win32
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('C:\\Users\\seanm\\AppData\\Local\\GitHubDesktop\\app-3.4.2\\resources\\app\\git\\mingw64\\bin\\git.EXE', '-c', 'core.autocrlf=false', 'apply', '--whitespace=nowarn', 'C:\\Users\\seanm\\.cache\\pre-commit\\patch1720636898-15384')
return code: 128
stdout: (none)
stderr:
    error: missing config value GIT_CONFIG_VALUE_0
    fatal: unable to parse command-line config
```

```
Traceback (most recent call last):
  File "C:\Users\seanm\AppData\Local\Programs\Python\Python311\Lib\site-packages\pre_commit\staged_files_only.py", line 29, in _git_apply
    cmd_output_b('git', *args)
  File "C:\Users\seanm\AppData\Local\Programs\Python\Python311\Lib\site-packages\pre_commit\util.py", line 110, in cmd_output_b
    raise CalledProcessError(returncode, cmd, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('C:\\Users\\seanm\\AppData\\Local\\GitHubDesktop\\app-3.4.2\\resources\\app\\git\\mingw64\\bin\\git.EXE', 'apply', '--whitespace=nowarn', 'C:\\Users\\seanm\\.cache\\pre-commit\\patch1720636898-15384')
return code: 128
stdout: (none)
stderr:
    error: missing config value GIT_CONFIG_VALUE_0
    fatal: unable to parse command-line config

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\seanm\AppData\Local\Programs\Python\Python311\Lib\site-packages\pre_commit\staged_files_only.py", line 81, in _unstaged_changes_cleared
    _git_apply(patch_filename)
  File "C:\Users\seanm\AppData\Local\Programs\Python\Python311\Lib\site-packages\pre_commit\staged_files_only.py", line 32, in _git_apply
    cmd_output_b('git', '-c', 'core.autocrlf=false', *args)
  File "C:\Users\seanm\AppData\Local\Programs\Python\Python311\Lib\site-packages\pre_commit\util.py", line 110, in cmd_output_b
    raise CalledProcessError(returncode, cmd, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('C:\\Users\\seanm\\AppData\\Local\\GitHubDesktop\\app-3.4.2\\resources\\app\\git\\mingw64\\bin\\git.EXE', '-c', 'core.autocrlf=false', 'apply', '--whitespace=nowarn', 'C:\\Users\\seanm\\.cache\\pre-commit\\patch1720636898-15384')
return code: 128
stdout: (none)
stderr:
    error: missing config value GIT_CONFIG_VALUE_0
    fatal: unable to parse command-line config

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\seanm\AppData\Local\Programs\Python\Python311\Lib\site-packages\pre_commit\staged_files_only.py", line 29, in _git_apply
    cmd_output_b('git', *args)
  File "C:\Users\seanm\AppData\Local\Programs\Python\Python311\Lib\site-packages\pre_commit\util.py", line 110, in cmd_output_b
    raise CalledProcessError(returncode, cmd, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('C:\\Users\\seanm\\AppData\\Local\\GitHubDesktop\\app-3.4.2\\resources\\app\\git\\mingw64\\bin\\git.EXE', 'apply', '--whitespace=nowarn', 'C:\\Users\\seanm\\.cache\\pre-commit\\patch1720636898-15384')
return code: 128
stdout: (none)
stderr:
    error: missing config value GIT_CONFIG_VALUE_0
    fatal: unable to parse command-line config

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\seanm\AppData\Local\Programs\Python\Python311\Lib\site-packages\pre_commit\error_handler.py", line 73, in error_handler
    yield
  File "C:\Users\seanm\AppData\Local\Programs\Python\Python311\Lib\site-packages\pre_commit\main.py", line 386, in main
    return hook_impl(
           ^^^^^^^^^^
  File "C:\Users\seanm\AppData\Local\Programs\Python\Python311\Lib\site-packages\pre_commit\commands\hook_impl.py", line 271, in hook_impl
    return retv | run(config, store, ns)
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\seanm\AppData\Local\Programs\Python\Python311\Lib\site-packages\pre_commit\commands\run.py", line 418, in run
    with contextlib.ExitStack() as exit_stack:
  File "C:\Users\seanm\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 586, in __exit__
    raise exc_details[1]
  File "C:\Users\seanm\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 571, in __exit__
    if cb(*exc_details):
       ^^^^^^^^^^^^^^^^
  File "C:\Users\seanm\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 144, in __exit__
    next(self.gen)
  File "C:\Users\seanm\AppData\Local\Programs\Python\Python311\Lib\site-packages\pre_commit\staged_files_only.py", line 107, in staged_files_only
    with _intent_to_add_cleared(), _unstaged_changes_cleared(patch_dir):
  File "C:\Users\seanm\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 144, in __exit__
    next(self.gen)
  File "C:\Users\seanm\AppData\Local\Programs\Python\Python311\Lib\site-packages\pre_commit\staged_files_only.py", line 91, in _unstaged_changes_cleared
    _git_apply(patch_filename)
  File "C:\Users\seanm\AppData\Local\Programs\Python\Python311\Lib\site-packages\pre_commit\staged_files_only.py", line 32, in _git_apply
    cmd_output_b('git', '-c', 'core.autocrlf=false', *args)
  File "C:\Users\seanm\AppData\Local\Programs\Python\Python311\Lib\site-packages\pre_commit\util.py", line 110, in cmd_output_b
    raise CalledProcessError(returncode, cmd, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('C:\\Users\\seanm\\AppData\\Local\\GitHubDesktop\\app-3.4.2\\resources\\app\\git\\mingw64\\bin\\git.EXE', '-c', 'core.autocrlf=false', 'apply', '--whitespace=nowarn', 'C:\\Users\\seanm\\.cache\\pre-commit\\patch1720636898-15384')
return code: 128
stdout: (none)
stderr:
    error: missing config value GIT_CONFIG_VALUE_0
    fatal: unable to parse command-line config
```

**Comment by sergiou87** [comment]
> Windows does not allow environment variables to be set to empty strings (empty string essentially means the variable does not exist)

But if that was true, how is it that you saw `GIT_CONFIG_VALUE_0: ''` in https://github.com/pre-commit/pre-commit/issues/3245#issuecomment-2206786438 ? Or just how would other `git` calls work? 🤔 

It has to be something in between Desktop and git (other than Windows) that gets it ignored/removed/filtered… 😕 

EDIT: I'm reading your progress on that other issue now, I see it seems python related 😥

**Comment by Repiteo** [comment]
Followed through the linked issue & it seems like python isn't the culprit either.

**Comment by ormaq** [comment]
Hello there, wanted to post what I found and potential issues/ a workaround.

I think [paulloz](https://github.com/paulloz) is correct in saying that we cant have a empty string win var.

If you go to `renderer.js` in `AppData\Local\GithubDesktop\app-3.4.2\resources\app`
You can find the value `GIT_CONFIG_VALUE_0` in this file and it is set to a empty string. This seems to be added jun 4'th in this commit 6905a65

Testing on it if you set the value to pretty much anything the error seems to goes away. If you make it empty again it comes back. Looking online some people set it to just a `*` or something like that.

I did find 1 repository [here](https://github.com/alisw/ali-bot/blob/master/ci/build-loop.sh) that does also use `credential.helper`
and they set the `GIT_CONFIG_VALUE_0` to `store --file /.git-creds`. This is likely specific for their code base, but wanted to leave it here.

Hopefully this helps, as a potential workaround and info.

**Comment by Repiteo** [comment]
I've implemented ormaq's suggestion in the above PR & it worked like a charm!

@sergiou87 Can we get this reopened?

**Comment by mccarthysean** [comment]
> AppData\Local\GithubDesktop\app-3.4.2\resources\app

I set `"GIT_CONFIG_VALUE_0": 0` in C:\Users\seanm\AppData\Local\GitHubDesktop\app-3.4.2\resources\app\renderer.js and it seemed to work for me. `"GIT_CONFIG_VALUE_0": "*"` did not work--same error as before.

**Comment by Repiteo** [comment]
Changed the logic a bit more to make the value `null` instead. For some insane reason, `null` is considered valid while an empty string is considered invalid.

**Comment by sergiou87** [comment]
Thanks for the PR @Repiteo 💖 

However, Desktop is doing what is expected according to the documentation (see [this](https://git-scm.com/docs/gitcredentials#Documentation/gitcredentials.txt-helper) and [this](https://git-scm.com/docs/git-config#ENVIRONMENT)) : it first sets the `credential.helper` config to an empty string to clear it out, and then sets it to `desktop` to make sure is the only value in it.

It is clear that git and Windows have no problem with this empty string, because invocations of git made directly by Desktop work fine.

✅  Desktop ➡ git  ✅ 

The problem appears only when using `pre-commit`. That doesn't mean the problem is introduced by `pre-commit` itself, but maybe by something introduced by the use of it between Desktop and git? They suspected Python could be the cause but they ruled it out… what else is thrown between Desktop and git when using `pre-commit`?

❌  Desktop ➡ _stuff introduced by the use of `pre-commit` but not necessarily `pre-commit` itself_ ➡ git  ❌ 

Until the actual reason behind this issue is found, and as long as Desktop is doing what it's supposed to do, we'd rather not add changes to Desktop that mask the actual problem.

If you can reproduce this issue and feel capable of it, it'd be very helpful if you could try to trace down the env variables and see in which step of this whole process `GIT_CONFIG_VALUE_0` is lost in order to understand who is not passing it down to subsequent steps.

**Comment by Repiteo** [comment]
That's disappointing, but fair. Probably gonna have to dig into this more on pre-commit's end after all.

It still feels weird to close the issue as "completed," though GitHub doesn't offer any options other than "not planned" so I kinda get it. Hopefully this won't stay unanswered for long!

**Comment by sergiou87** [comment]
To be honest, we don't really pay much attention to the "Close as…", we just close it 😅 I just re-closed it as not planned, but as you say it's not super accurate either.

FWIW I checked with git engineers if we were doing anything wrong with that empty env var, and it doesn't seem to be the case, so unless we're missing something, the actual cause of this bug lies somewhere else 😕

**Comment by sgbaird** [comment]
I've been a frequent user of GitHub Desktop on Windows for many years. I also have so many repos with pre-commit hooks that doing temporary fixes by commenting certain pre-commit hooks isn't a reasonable option for me. Using GitHub Desktop is so habitual for me that I find myself forgetting about this and losing my changes. Occasionally I salvage it by committing manually (e.g., through CLI) before closing the pre-commit error dialogue box on GitHub Desktop. However, any files I didn't have staged/checked during that commit are lost. In the interim, I am going to uninstall GitHub Desktop and rely on VS Code extensions, the CLI, and the GitHub UI until this gets resolved. If that gets too annoying, I'll probably try to install the prior release of GitHub Desktop that didn't have this behavior. At least I can say, an issue of this level is unprecedented for me for both pre-commit and GitHub Desktop, so I hope it can get resolved so I can return to my usual workflows.

**Comment by fabiopedrosa** [comment]
@sgbaird as you said

**Comment by aviadr1** [comment]
> I've been a frequent user of GitHub Desktop on Windows for many years. I also have so many repos with pre-commit hooks that doing temporary fixes by commenting certain pre-commit hooks isn't a reasonable option for me. Using GitHub Desktop is so habitual for me that I find myself forgetting about this and losing my changes. Occasionally I salvage it by committing manually (e.g., through CLI) before closing the pre-commit error dialogue box on GitHub Desktop. However, any files I didn't have staged/checked during that commit are lost. In the interim, I am going to uninstall GitHub Desktop and rely on VS Code extensions, the CLI, and the GitHub UI until this gets resolved. If that gets too annoying, I'll probably try to install the prior release of GitHub Desktop that didn't have this behavior. At least I can say, an issue of this level is unprecedented for me for both pre-commit and GitHub Desktop, so I hope it can get resolved so I can return to my usual workflows.

here here

**Comment by ormaq** [comment]
### Hey there everyone
Wanted to post a update as I found a way to consistently get the error, even on a fresh account that has never used lfs or hooks before.

Here are the steps to take to obtain the error message

1. Create a new directory and initialize a Git repository:

   ```bash
   mkdir error_reproduction
   cd error_reproduction
   git init
   ```

2. Set up Git LFS:

   ```bash
   git lfs install
   ```

3. Create a `.gitattributes` file:

   ```bash
   echo "*.bin filter=lfs diff=lfs merge=lfs -text" > .gitattributes
   ```

4. Create a sample binary file:

   ```bash
   dd if=/dev/urandom of=sample.bin bs=1M count=10
   ```

5. Set up pre-commit:

   ```bash
   pip install pre-commit
   ```

6. Create a `.pre-commit-config.yaml` file:

   ```yaml
   repos:
     - repo: https://github.com/pre-commit/pre-commit-hooks
       rev: v4.4.0
       hooks:
         - id: check-case-conflict
         - id: check-yaml
         - id: end-of-file-fixer
         - id: trailing-whitespace
     - repo: https://github.com/psf/black
       rev: 23.3.0
       hooks:
         - id: black
   ```

7. Install the pre-commit hooks:

   ```bash
   pre-commit install
   ```

8. Create a Python file with some intentional style issues:

   ```bash
   echo "def foo():\n    print('Hello, World!')\n    return None" > test.py
   ```
   
   Now try to add that repo to github desktop and commit to master.
   
   This will show the error talking about GIT_CONFIG_VALUE_0 on any account. See that my fix I posted earlier still works and will allow you to commit the files.
   
   Hopefully someone can now deep dive into the issue, Thanks!

**Comment by SmartManoj** [comment]
Script for [the workaround](https://github.com/desktop/desktop/issues/18945#issuecomment-2231589216). Run this and reopen Github Desktop.

```python
import os
import glob
file = r'%LOCALAPPDATA%\GitHubDesktop\app-3*\resources\app\renderer.js'
file = os.path.expandvars(file)
file = glob.glob(file)[-1]
print('Patching file:', file)
find = 'GIT_CONFIG_VALUE_0:""'
replace = 'GIT_CONFIG_VALUE_0:"null"'
with open(file, 'r', encoding="utf-8") as f:
    content = f.read()
    content = content.replace(find, replace)
with open(file, 'w', encoding="utf-8") as f:
    f.write(content)
    print('Successfully patched')
```

**Comment by kyle3s** [comment]
Please re-open this and fix it

**Comment by SmartManoj** [comment]
> However, Desktop is doing what is expected according to the documentation (see [this](https://git-scm.com/docs/gitcredentials#Documentation/gitcredentials.txt-helper) and [this](https://git-scm.com/docs/git-config#ENVIRONMENT)) : it first sets the `credential.helper` config to an empty string to clear it out, and then sets it to `desktop` to make sure is the only value in it.
> 
> It is clear that git and Windows have no problem with this empty string, because invocations of git made directly by Desktop work fine.

@sergiou87, I see your point, but a crucial detail seems to be overlooked. On Windows, setting an environment variable to an empty string [doesn't work](https://stackoverflow.com/a/75826297) as intended—it effectively removes the variable rather than just clearing its value. This causes issues when other processes, like pre-commit, attempt to access these variables later on. 

So, while it might appear that the Desktop is working correctly, the problem arises because the empty string isn't preserved across processes on Windows. This means that when Desktop clears out the `credential.helper` config, it inadvertently breaks the chain when other tools, like pre-commit, get involved.

In this case, it's not about Desktop masking the actual problem but rather about ensuring compatibility across different environments. Windows simply doesn't handle empty environment variables the same way other systems might, which is why this issue emerges.

@Repiteo Do you agree with this?

**Comment by theroggy** [comment]
@SmartManoj I had to add `encoding="utf-8"` to both `open` statements as my windows by default uses encoding `cp1252`... Could you add this in your script, that makes it more portable.

**Comment by gmateus-ilof** [comment]
Please reopen and address this.

**Comment by SmartManoj** [comment]
The workaround is not working in v3.4.4-beta. After that downgrading to v3.4.3 and rebooting also did not work. Need to do a clean install.

**Comment by sergiou87** [comment]
@ormaq I cannot reproduce it with those steps:

![Image](https://github.com/user-attachments/assets/7db9cb86-1a73-490a-a630-356074e6f21d)

**Comment by SmartManoj** [comment]
Steps to reproduce:

1) Change any 2 files.
2) Select only one file to commit.

Now the error will pop up. And the other file changes will be discarded.

**Comment by ormaq** [comment]
> @ormaq I cannot reproduce it with those steps:
> 


Curious, I tried those steps a bunch a month ago and every time it failed. But now it seems that it works displaying the correct issue. Dont know what caused the change. 🤷

**Comment by Repiteo** [comment]
Made a PR, #19192, which should at least partially address this issue. Even if the root cause isn't yet determined, that should be irrelevant when not using Git Credential Manager, as those config settings are only needed in that context. So now these environment variables won't be passed whatsoever if the setting is disabled (which it is by default afaik), effectively circumventing this entire issue for those that aren't relying on the feature.

**Comment by sergiou87** [comment]
@Repiteo I'm afraid that's not an option: we switched from using the "askpass protocol" to the "credential helper protocol" for all users, because "askpass" causes a bunch of issues with certain repositories. Then, we decided to leverage the "credential helper protocol" to add support for Git Credential Manager.

Just curious: for those of you who can reproduce this issue (I cannot but I will try what @SmartManoj just suggested), how hard it is to try and track down in which specific layer the `GIT_CONFIG_VALUE_0` env variable is lost?

**Comment by SmartManoj** [comment]
**Visual steps to reproduce:**

1) Change any 2 files.

![image](https://github.com/user-attachments/assets/fdb820ca-f72c-4237-9b66-39e2ee5dcd95)

2) Select only one file to commit.

![image](https://github.com/user-attachments/assets/54f00f29-bfc8-46c7-a118-0f4bb8d1cb32)

3) Click the commit button. 

![image](https://github.com/user-attachments/assets/a40671b8-c2c4-473f-b3b1-e6a86737c1ea)

4) BOOM - unselected files disappeared (hint: need to switch the windows to trigger the UI update)

![image](https://github.com/user-attachments/assets/381a32da-70b4-4a0d-88da-c7645c0202da)

**Comment by ibabeo** [comment]
Also experiencing the error in 3.4.5

**Comment by jmdesmet-quatra** [comment]
also experiencing the error in 3.4.6

**Comment by steveward** [comment]
@jmdesmet-quatra please download the [beta version](https://github.com/desktop/desktop#beta-channel) of GitHub Desktop -- the fix is currently limited to beta at this time (see https://github.com/desktop/desktop/pull/19333). Let us know if you run into any issues.

**Comment by Snoopy1866** [comment]
also experiencing the error in 3.4.8

3.4.9-beta1 works well for me.

**Comment by SmartManoj** [comment]
@Snoopy1866  https://github.com/desktop/desktop/issues/18945#issuecomment-2402499994

**Comment by gperezz11** [comment]
Any updates?
