### ISSUE TITLE
Cannot select and commit files/lines when stopping at an 'edit' in an interactive rebase

### ISSUE THREAD

**Issue by wessmith** [desktop/desktop#18958]
### The problem

In an interactive rebase, it used to be possible to open GitHub Desktop and select lines specific files and lines to commit to clean up concerns into more deliberate commits. Now that GitHub Desktop recognizes a rebase in progress, it doesn't allow me to do this (or doesn't appear to). I cannot check/uncheck which files I want included. It seems to let me selectively choose lines but my only option is to "Continue rebase". I can't create a new commit from GH Desktop when stopping on an 'edit'. I would assume that if GH Desktop is going to recognize a rebase in progress now, it should also allow editing commits. 

This is a big disappointment. I've used GH Desktop to do this since it was first released. Is there a way to disable GH Desktop from trying to handle a rebase so I can use it to make commits while in a rebase? 

### Release version

3.3.18

### Operating system

macOS 14.3.1

### Steps to reproduce the behavior

My typical flow is the following:

1. in a terminal, set up an interactive rebase back to a specific commit
2. in the commit editor, re-arrange, mark commits with 'edit' as needed
3. when it stops on the 'edit', `git reset --soft` 
4. open GH Desktop and select what files/lines I want in the commit
5. commit via GH Desktop, repeat, etc until done with those changes
6. in terminal, continue the rebase

This was SUPER helpful and rapid way to clean up commits. Today, steps 4 & 5 are not possible given GH Desktop only allows me to continue the rebase and disables file selection/unselection.

**Comment by steveward** [comment]
Thanks for the issue @wessmith. Do you remember when this stopped working for you?

There was discussion in #10460 about a similar scenario, and it was mentioned by @niik in https://github.com/desktop/desktop/issues/10460#issuecomment-694301036 that a change in the rebase backend caused in-progress rebases to be detected. That was four years ago, though, so I'm not sure if your usage was slightly different.

Since that issue aligns with what you are looking for I'm going to close this out and reference it in #10460.
