### ISSUE TITLE
 Error Cloning Repository: RPC Failed; curl 18 transfer closed with outstanding read data remaining

### ISSUE THREAD

**Issue by wasayabasi** [desktop/desktop#18972]
I encountered an error while attempting to clone a repository into D:\trying_repo\Climate-KIC. The process failed with the following error messages:
Cloning into 'D:\trying_repo\Climate-KIC'...
remote: Enumerating objects: 444, done.        
remote: Counting objects: 100% (55/55), done.        
remote: Compressing objects: 100% (44/44), done.        
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
error: 1476 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

Steps to reproduce:
Attempt to clone the repository using the command git clone (https://github.com/OmdenaAI/Climate-KIC).

Observed behavior:
The cloning process starts but fails with the errors mentioned above.

Attempted solutions:
 Retrying the clone operation.
 Checking internet connection.
 Updating Git to the latest version.
 Cloning into a different directory.

None of these solutions resolved the issue. Any guidance on how to resolve this error would be appreciated.

**Comment by steveward** [comment]
@wasayabasi sorry to hear you're having trouble.

Network issues are tricky to diagnose, and there isn't much we can do from our end about them since the underlying Git operations are failing. Some users have had success running the following config option:

`git config --global http.postBuffer 524288000`

There are also some HTTP timeout config operations that may help, or at lease provide additional diagnosis about the timeout. One user previously had success with these commands:

`git config --global http.lowSpeedLimit 1000`
`git config --global http.lowSpeedTime 20`

The `lowSpeedLimit` configures the minimum bytes per second, and the `lowSpeedTime` is the number of seconds. If the operation is lower than that threshold for the set time it will timeout. Adjusting those values may help with timeouts.

There are also pack depth options that have helped some users:

`git config --global pack.window 1`
`git config --global pack.depth 1`

If none of those suggestions work it may be worth trying to set [up a SSH key](https://docs.github.com/en/authentication/connecting-to-github-with-ssh), which some users have had more success with when encountering network issues. You could then switch the remote URL to use SSH in GitHub Desktop by going to `Repository` > `Repository Settings` > `Remote`. 

I'm going to close this out as there isn't anything we can do from our end to resolve this, but if you have any further questions let me know.

**Comment by Tobey14** [comment]
If this happens to you, just reinstall git and it's sorted, don't spend time on any other solution asides cloning using ssh though.

**Comment by yangbo** [comment]
I have the same issue but is in the installlation of 'nRF SDK', the last step like:
```
git clone --branch v2.6.1 https://github.com/nrfconnect/sdk-nrf C:\ncs\v2.6.1.west\manifest-tmp
Cloning into 'C:\ncs\v2.6.1.west\manifest-tmp'...
remote: Enumerating objects: 245315, done.
remote: Counting objects: 100% (1133/1133), done.
remote: Compressing objects: 100% (679/679), done.
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
error: 6175 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
```
I am trying the solutions mentioned before. 
Any other ideas?

**Comment by Farial-mahmod** [comment]
I have tried increasing the http buffer size but that has not helped in my case.

**Comment by Farial-mahmod** [comment]
I have tried increasing the http buffer size but that has not helped in my case.

**Comment by NarhAyiku** [comment]
iv tried all the steps here and nothing seems to work

**Comment by lords-7** [comment]
rien ne fonctionne chez moi.....

**Comment by MohammedAL-Ani** [comment]
I tried a lot, and I think the problem I can't solve is being able to reach GitHub successfully. After I checked, my internet connection to GitHub is stable. 
I found the problem was with my internet, which is weak. Just change the wifi to mobile net, and the install was complete.

**Comment by bilalahmed-344** [comment]
I tried various methods, including increasing the buffer size and following other suggestions, but in my case, the issue was resolved by simply switching from Wi-Fi to my mobile hotspot. It seems the downloading was getting stuck, causing the cloning operation to fail. This was possibly a restriction from my ISP. Switching to mobile data and using it as a hotspot fixed the issue.

**Comment by BrainAnnex** [comment]
As someone else said, *un-installing and re-installing GitHub Desktop* fixed the problem :) 

(Maybe GitHub Desktop had gotten corrupted in its latest update?  It seems to happen once in a while...)
