### ISSUE TITLE
Enable to push changes into my branch

### ISSUE THREAD

**Issue by tharunquickride** [desktop/desktop#18994]
### The problem

If i pull changes in UI its not showing as pulled but in PR changes are showing.

### Release version

latest version

### Operating system

windows 10

### Screenshots

![github_pull](https://github.com/user-attachments/assets/ce01ee93-f179-4c0a-a811-2bb14fe26877)

### Additional context

I tried more then 15 times

**Comment by steveward** [comment]
Thanks for the report @tharunquickride. Are you encountering any errors when you attempt to push your changes? Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
