### ISSUE TITLE
How can I rename a local and pushed branch?

### ISSUE THREAD

**Issue by ajtruckle** [desktop/desktop#19007]
### The feature request

How can I rename a local and pushed branch?

### Proposed solution

n/a

**Comment by tidy-dev** [comment]
👋  @ajtruckle You can find the Rename feature under Branch main menu. This will open a dialog where you can rename your branch. If your branch is only local, you will be good to go. 

If you branch has all ready been pushed, things are a little trickier because we do not know if you have other collaborators that may have also checked out this branch and therefore if we change it, it could cause it to be disconnected from new upstream commits and you disconnected from any commits they have made. Thus, you can still rename it on GitHub Desktop, but that will only rename it locally. Thus, the branch as it was named before will still exist in your repository remotely.  You can then push your newly named branch and work off if it with your team. 

Having the extraneous wrongly named branch won't hurt anything and you can just continue working on your newly named branch; however, if you know that you will not disrupt another repository collaborator (maybe only you work on this repository or branch, and/or have already communicated the change), feel free to delete the wrongly named branch. :)
