### ISSUE TITLE
shows changes in file but there are no changes

### ISSUE THREAD

**Issue by alokrbl** [desktop/desktop#19026]
### The problem

I use Version 3.4.2 (x64). it is unnecessary showing files which has not been modified. Not able to discard them. 

### Release version

Version 3.4.2 (x64)

### Operating system

windows

### Steps to reproduce the behavior

1- checkout project
2- shows diff in few of files
3- switching to another branch
4- asking to stash them
5- discarding those files does not work.

### Log files

No loga

### Screenshots

![github-desktop](https://github.com/user-attachments/assets/53468297-7225-4e05-9877-a62b628417b6)

**Comment by sergiou87** [comment]
Hey @alokrbl 👋 

Could you run `git status` and `git diff` on a terminal to see if it displays any changes?

**Comment by alokrbl** [comment]
Hello @sergiou87,

When i use above commands to check on terminal, I do not see any changes. The only problem is with Github desktop UI

**Comment by sergiou87** [comment]
@alokrbl  Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
