### ISSUE TITLE
Unable to push commit, error giving me "The remote disconnected. Check your Internet connection and try again."

### ISSUE THREAD

**Issue by nickcfisch** [desktop/desktop#19023]
### The problem

Unable to push commit giving me "The remote disconnected. Check your Internet connection and try again." 

My internet connection is fine. 

### Release version

Version 3.4.2 (x64)

### Operating system

Windows 10 Enterprise

**Comment by sergiou87** [comment]
Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by nickcfisch** [comment]
[2024-07-29.desktop.production.log](https://github.com/user-attachments/files/16416176/2024-07-29.desktop.production.log)


Attached

**Comment by steveward** [comment]
Thanks for sharing the log file! It looks like you're trying to push a large amount of changes and it is causing a timeout:

```
error: RPC failed; HTTP 500 curl 22 The requested URL returned error: 500
send-pack: unexpected disconnect while reading sideband packet
Total 227 (delta 30), reused 0 (delta 0), pack-reused 0 (from 0)
fatal: the remote end hung up unexpectedly
Everything up-to-date

(The error was parsed as 5: The remote disconnected. Check your Internet connection and try again.)
```
You can try using the command line to push a subset of commits by using the following command:

`git push origin commit-SHA:branch`

For example, if you have three commits A (4d3bf9) - B (e55b5f) - C (c109e0) and wanted to push A and B to your `main` branch you would run this command:

`git push origin e55b5f:main`

Some users have had also success running this command to try and prevent timeouts:

`git config --global http.postBuffer 157286400`

If you're using Git LFS with a large repository you can try using this config option to increase the timeout:

`git config lfs.activitytimeout 30`

This config sets the maximum time in seconds that the HTTP client will wait for the next TCP read or write. The default is 10 seconds. If you're not using Git LFS and are pushing large files I would also recommend looking into that as an option.

There are also some HTTP timeout config operations that may help, or at lease provide additional diagnosis about the timeout. One user previously had success with these commands:

`git config --global http.lowSpeedLimit 1000`
`git config --global http.lowSpeedTime 20`

The `lowSpeedLimit` configures the minimum bytes per second, and the `lowSpeedTime` is the number of seconds. If the operation is lower than that threshold for the set time it will timeout. Adjusting those values may help with timeouts.

There are also pack depth options that have helped some users:

`git config --global pack.window 1`
`git config --global pack.depth 1`

The [config manual](https://git-scm.com/docs/git-config/) provides more details about these.

If none of those suggestions work it may be worth trying to set [up a SSH key](https://docs.github.com/en/authentication/connecting-to-github-with-ssh), which some users have had more success with when encountering network issues. You could then switch the remote URL to use SSH in GitHub Desktop by going to `Repository` > `Repository Settings` > `Remote`. 

I'm going to close this out since there isn't anything we can do from our end about network timeouts, but let me know if you have any further questions.

**Comment by funkytomato** [comment]
Converting to SSH resolved this for me. :)

**Comment by vijayrathore-eaton** [comment]
@funkytomato , how did you setup the SSH ? Where did you get the SSH key /?

**Comment by DrPsychotic** [comment]
> [@funkytomato](https://github.com/funkytomato) , how did you setup the SSH ? Where did you get the SSH key /?

I figured it out, just go to Options > Advanced >network and credentials and check "Use system OpenSSH
Fixed the issue for me

**Comment by MissPerception** [comment]
I'm still struggling with this issue and I've used the commands too that were suggested for the large files since it is my first initial commit of everything. How would I convert this to ssh and get it pushed? I'm very confused right now. It already says I'm using system openssh... so I dont think that'll fix it for me.
