### ISSUE TITLE
Cherry-pick is not working

### ISSUE THREAD

**Issue by amarkus-clgx** [desktop/desktop#19048]
### The problem

I am doing a cherry-pick from one branch to my current target branch, but it fails with a message that says that I am trying to do a cherry-pick to the same branch.

### Release version

Version 3.4.3 (x64)

### Operating system

windows

**Comment by sergiou87** [comment]
Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by amarkus-clgx** [comment]
Unfortunately, due to privacy concerns, I can not post logs.
Here are the reproducible steps.

1. Create a repo with at least 2 branches, which diverge.
2. Checkout branch2.
3. Locate in the history a recent commit from branch1.
4. Try to cherry-pick it using GitHub Desktop UI.
5. Observe the pop-up saying that you can not do it.

This scenario works via `git gui`: open the Visualize All Branch History and then right-click and cherry-pick. 
Maybe "it is not a bug but a feature", but it confused me and made me think I am messing up with the commit history.

![image](https://github.com/user-attachments/assets/37754e62-5a4f-4764-b1c5-089386607de0)
![image](https://github.com/user-attachments/assets/fb23cf5b-c3d7-4152-924a-f99e9b63c2f5)
[repo.zip](https://github.com/user-attachments/files/16470564/repo.zip)

**Comment by steveward** [comment]
Thanks for sharing that @amarkus-clgx. This looks like the same issue that was reported in https://github.com/desktop/desktop/issues/12688. Since this isn't the common workflow for cherry picking we have not prioritized a fix for this at this time. There is a potential [workaround](https://github.com/desktop/desktop/issues/14217) in the issue as well. I'd recommend subscribing to that issue for further updates about this. I'm going to close this out.
