### ISSUE TITLE
Renaming a branch sometimes doesn't work

### ISSUE THREAD

**Issue by Micnubinub** [desktop/desktop#19052]
### The problem

Renaming a branch sometimes doesn't work

### Release version

3.4.2

### Operating system

MacOS 14.6

### Steps to reproduce the behavior

1. Right click on branch
2. Rename branch

**Comment by sergiou87** [comment]
Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by Romek-cloud** [comment]
Ok
Dane
