### ISSUE TITLE
The remote disconnected. Check your Internet connection and try again.

### ISSUE THREAD

**Issue by appdevelopersurya** [desktop/desktop#19054]
### The feature request

The remote disconnected. Check your Internet connection and try again.

### Proposed solution

The remote disconnected. Check your Internet connection and try again.

### Additional context

The remote disconnected. Check your Internet connection and try again.

**Comment by sergiou87** [comment]
Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by sergiou87** [comment]
Actually, please file a [new issue using the bug report template](https://github.com/desktop/desktop/issues/new?template=bug_report.yaml) and include all important details 🙏 

Thanks for understanding and meeting us half way 😀
