### ISSUE TITLE
the github desktop starts with a white screen and then recovers & the pull request text comes and goes quickly

### ISSUE THREAD

**Issue by erenyavuzs** [desktop/desktop#19068]
### The problem

I got an error when editing commits with Rebase, then I canceled and deleted the repo, then I had problems with GitHub desktop as in the title. when I start the app it now opens late and starts with a white screen and then resolves, every time I click on a repo the preview pull request text comes and goes quickly. I deleted the app, reinstalled it, cleared the cache but it didn't fix the problem. I looked in toogle developer tools and didn't see any errors in the console. what causes this kind of errors and how can I fix it?

Just like that: https://www.youtube.com/watch?v=-qaRY5UZjRI

### Release version

Version 3.4.3

### Operating system

Sonoma 14.5

**Comment by steveward** [comment]
Thanks for the report @erenyavuzs. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by erenyavuzs** [comment]
> Thanks for the report @erenyavuzs. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
> 
> The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
[2024-08-04.desktop.production.log](https://github.com/user-attachments/files/16499532/2024-08-04.desktop.production.log)
[2024-08-05.desktop.production.log](https://github.com/user-attachments/files/16499533/2024-08-05.desktop.production.log)

**Comment by steveward** [comment]
I'm not seeing anything unusual in the log file. The video you shared is from https://github.com/desktop/desktop/issues/8540, which was related to background fetching but I do see the preview pull request option flashing like you mentioned. That's likely due to the app fetching and checking the state of the current branch, which you can see in the `Fetch origin` button. Are there any underlying functional issues or is it just these two behaviors? 

For the white screen we recommend deleting `~/Library/Application Support/Github Desktop/IndexedDB` and then launching the app again to see if that helps.

**Comment by erenyavuzs** [comment]
I did what you said but the problem of starting with a white screen was not solved. there is no underlying functional issues, for now only these two behaviors

**Comment by erenyavuzs** [comment]
I just got an optimization notification for silicon mac from gitHub desktop and when I clicked on it, everything was fixed. 
Thank you for taking the time to help me

**Comment by erenyavuzs** [comment]
I just got an optimization notification for silicon mac from gitHub desktop and when I clicked on it, everything was fixed. 
Thank you for taking the time to help me

**Comment by steveward** [comment]
Glad to hear that got things working!
