### ISSUE TITLE
Clon Failed -RPC failed 

### ISSUE THREAD

**Issue by parthk2510** [desktop/desktop#19067]
### The problem

This is the error occurred when trying to clone a repo with around 1 gb size 
Cloning into 'C:\Users\USER1\OneDrive\Documents\GitHub\Project-working'...
remote: Enumerating objects: 2286, done.        
remote: Counting objects: 100% (314/314), done.        
remote: Compressing objects: 100% (114/114), done.        
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
error: 2815 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

### Release version

Version 3.4.2 (x64)

### Operating system

Windows 11

**Comment by steveward** [comment]
Thanks for the issue @parthk2510. Network issues are tricky to diagnose, and there isn't much we can do from our end about them since the underlying Git operations are failing

Some users have had also success running this command to try and prevent timeouts:

`git config --global http.postBuffer 157286400`

If you're using Git LFS with a large repository you can try using this config option to increase the timeout:

`git config lfs.activitytimeout 30`

This config sets the maximum time in seconds that the HTTP client will wait for the next TCP read or write. The default is 10 seconds. If you're not using Git LFS and are pushing large files I would also recommend looking into that as an option.

There are also some HTTP timeout config operations that may help, or at lease provide additional diagnosis about the timeout. One user previously had success with these commands:

`git config --global http.lowSpeedLimit 1000`
`git config --global http.lowSpeedTime 20`

The `lowSpeedLimit` configures the minimum bytes per second, and the `lowSpeedTime` is the number of seconds. If the operation is lower than that threshold for the set time it will timeout. Adjusting those values may help with timeouts.

There are also pack depth options that have helped some users:

`git config --global pack.window 1`
`git config --global pack.depth 1`

The [config manual](https://git-scm.com/docs/git-config/) provides more details about these.

If none of those suggestions work it may be worth trying to set [up a SSH key](https://docs.github.com/en/authentication/connecting-to-github-with-ssh), which some users have had more success with when encountering network issues. You could then switch the remote URL to use SSH in GitHub Desktop by going to `Repository` > `Repository Settings` > `Remote`.

**Comment by hassanfrooqkhan** [comment]
@parthk2510  Did you get your issue resolved? I can see @steveward just copy pastes the same response to everyone and none of his suggestions actually work
