### ISSUE TITLE
Ability to Organize Projects into Folders

### ISSUE THREAD

**Issue by aligoren** [desktop/desktop#19081]
### The feature request

Could we add the ability to organize cloned projects into folders in the Desktop application?

### Proposed solution

This way, it would be easier to access specific projects when there are many of them. For example:

```
BankProjects/
    Banking.InvestmentProject
    Banking.PaymentProject
InternalProjects/
    CRMApplication
    PhoneCaller
PersonalProjects/
    GoSamples
    DotnetSamples
```

I currently have around 30-35 projects, and when they are all listed one after the other, it looks very long. I think it would be better if they could be grouped like this.

**Comment by steveward** [comment]
Thanks for the feedback @aligoren. At this time we don't have any plans to implement repository grouping, but we do continue to monitor feedback about this for future consideration.

One workaround is to use the repository alias feature and then use that to filter by a specific alias prefix. 

I'm going to close this out since we have existing issues around this request.
