### ISSUE TITLE
It is showing cannot find "indian" whenever I try to clone/create/add existing repository

### ISSUE THREAD

**Issue by hemanth18624** [desktop/desktop#19090]
### The problem

Whenever I am trying to clone/create/add a local repository, it is showing "cannot find indian".

### Release version

version 3.4.3

### Operating system

10

**Comment by steveward** [comment]
Thanks for the report @hemanth18624. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
