### ISSUE TITLE
Windows ARM64 Build

### ISSUE THREAD

**Issue by kennyu** [desktop/desktop#19110]
### The feature request

Native build of Github Desktop for Windows ARM64. Current available version is x64

### Proposed solution

Creates a native app that is energy efficient and works well with laptops with ARM chips

**Comment by steveward** [comment]
@kennyu thanks for the issue. Arm support on Windows is still in beta and that's why it's not available as a separate download on desktop.github.com. 

We're holding off on shipping to production until Git for Windows is able to support arm64 (https://github.com/git-for-windows/git/issues/3107)

You can download our beta version which will automatically update to the arm64 version.
