### ISSUE TITLE
Project importing

### ISSUE THREAD

**Issue by shambhavik24** [desktop/desktop#19111]
### The problem

 Trouble to importing the project 

### Release version

3.4.3

### Operating system

windows 10

**Comment by sergiou87** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by shambhavik24** [comment]
Thank you, I will do that.
