### ISSUE TITLE
Add a refresh menu item

### ISSUE THREAD

**Issue by amithegde** [desktop/desktop#19184]
### The feature request

Often I notice it takes a while to show new local commit when I commit using cli on a large repo. Please add a `Refresh` button which should update the latest local commits.

### Proposed solution

Add refresh memnu item and Assign it keyboard shortcut `F5`

**Comment by steveward** [comment]
@amithegde thanks for the issue. We wouldn't add a refresh option, as cases where changes are taking a while to show up is due to status being computed. We have an existing issue tracking support for an indicator in https://github.com/desktop/desktop/issues/1914, so I'll bump that up with your feedback.
