### ISSUE TITLE
Indicator for repositories w/branches that have stashed changes (similar to uncommitted changes blue dot)

### ISSUE THREAD

**Issue by pedson** [desktop/desktop#19199]
### The feature request

Provide indicators in the dropdown when you click on Current Repository to select a different repository that shows which repositories have one or more branches with stashes.

### Proposed solution

This would be similar the current blue dot indicator for when there are uncommitted changes or the arrow indicator when there are commits to be pushed.  Perhaps just a different color dot in the same place and side by side when both are applicable.  An optional setting if you think it would be too cluttered by default.  But in general, it is helpful to know if you have any kind of change lurking in your repos at a glance from that dropdown, including stashed changes.

**Comment by steveward** [comment]
Thanks for the issue @pedson. We haven't heard feedback about showing a stash indicator in the repository list, but it is something that has been requested for the branch list. We're tracking that improvement in https://github.com/desktop/desktop/issues/8048. We're also tracking support for multiple stashes in https://github.com/desktop/desktop/issues/12699, which would facilitate the creation of a stash list of some type as well if implemented. 

I'm going to close this out since it's unlikely we would add a stash indicator to the repository list but would instead focus on the other areas I mentioned above.
