### ISSUE TITLE
My repositories are not uploading

### ISSUE THREAD

**Issue by iamshadankhan10** [desktop/desktop#19197]
### The problem

When I am trying to push my repositories, it is showing that your repositories are either deleted or empty. But they are in my desktop. I tried several times but it shows the same result. Please help me with this issue.

### Release version

Version 3.4.3

### Operating system

Windows 11

**Comment by steveward** [comment]
@iamshadankhan10 can you share a screenshot of the issue you are experiencing? Are you committing all of your changes and then receiving an error when you attempt to push the changes to the remote repository? Any details you can share would be helpful. 

Could you also upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
