### ISSUE TITLE
Autosuggest for issues is always out of date

### ISSUE THREAD

**Issue by jpike88** [desktop/desktop#19195]
### The problem

An issue was added hours ago, but GitHub desktop's autocomplete doesn't see the issue. It needs to check more often.

### Release version

3.4.3 (arm64)

### Operating system

macOS sonoma

### Steps to reproduce the behavior

1. try to type # in a commit message, look at list for a recently added issue

**Comment by sergiou87** [comment]
I tried to reproduce this but it worked fine for me (we just throttle updates to 1 every minute). Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by POP1854** [comment]
[
[Uploading تأثير البيئة على اسماك البلطى.pdf…]()
](url)
