### ISSUE TITLE
The github desktop is not ignoring folders and files in the gitignore 

### ISSUE THREAD

**Issue by RovicMA** [desktop/desktop#19213]
### The problem

![image](https://github.com/user-attachments/assets/e17478fb-6102-4b31-b56e-6f58338d12d0)
![image](https://github.com/user-attachments/assets/22f79adb-8871-4770-833f-ede2d0dce0d8)

### Release version

Version 3.4.3 (x64)

### Operating system

Windows 11

### Steps to reproduce the behavior

1.Make a pull request
2.Build the project
3.the changes tab start picking up files changes in the build folder which is set to gitignore thus causing the issue

**Comment by sergiou87** [comment]
@RovicMA  thanks for the issue. I think the problem is those files were already tracked before they were ignored, so you will need to run `git rm --cached <file>` to ignore files that are being tracked by Git already. 

We have an open issue around this in https://github.com/desktop/desktop/issues/2537. I'll reference this issue there.
