### ISSUE TITLE
The new integrations feature doesn't work for some paths?

### ISSUE THREAD

**Issue by ChiriVulpes** [desktop/desktop#19217]
### The problem

Trying to replicate what I had in #16980 with the new feature and I can't get it to work for multiple reasons.

This issue is regarding the "Path" input, which doesn't seem to allow me to put in `C:\Chiri\AppData\Local\Microsoft\WindowsApps\wt.exe`, saying "This path does not appear to be a valid executable."

### Release version

3.4.4

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Put the Microsoft Store `wt.exe` path in your "Path" input:
  - `C:\YOURUSERNAME\AppData\Local\Microsoft\WindowsApps\wt.exe`
  - Theoretically `%LOCALAPPDATA%\Microsoft\WindowsApps\wt.exe` should also work but it doesn't either

### Additional context

I am able to workaround this issue by making a custom `.bat` file in another folder that opens `wt.exe` itself, but it's a little silly that I have to do that

**Comment by sergiou87** [comment]
Thanks for your report!

For some reason, [trying to `stat` that file](https://github.com/desktop/desktop/blob/b80f1b780102df80210567786ad6fef927b24dd7/app/src/lib/custom-integration.ts/#L107-L108) throws `EACCESS` error because of lack of permission, but if I skip that check, Desktop is able to open it. I will investigate and see if there are alternatives...

**Comment by sergiou87** [comment]
Submitted a fix in [#19223](https://github.com/desktop/desktop/pull/19223)

**Comment by sergiou87** [comment]
Fixed in the latest v3.4.5 that can be downloaded from https://desktop.github.com

Auto-updates will rollout progressively.

**Comment by melvinpatac** [comment]
dfsgfd
