### ISSUE TITLE
I get many errors in this new release Version 3.4.4 (x64)

### ISSUE THREAD

**Issue by GeoHaber** [desktop/desktop#19214]
### The problem

lots of errors 

### Release version

Version 3.4.4 (x64)

### Operating system

Win 11

**Comment by sergiou87** [comment]
Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
