### ISSUE TITLE
Git clone not working properly

### ISSUE THREAD

**Issue by pradeep3093** [desktop/desktop#19233]
### The problem

Clone repository not working properly. sometimes face 

### Release version

Version 3.4.3 (x64)

### Operating system

windows11

### Steps to reproduce the behavior

clone new repository from github desktop or commandline both not working properly. 

### Log files

[2024-09-10.desktop.production.log](https://github.com/user-attachments/files/16941465/2024-09-10.desktop.production.log)

### Additional context

remote: Enumerating objects: 41366, done.        
remote: Counting objects: 100% (3580/3580), done.        
remote: Compressing objects: 100% (1232/1232), done.        
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
error: 1602 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

**Comment by steveward** [comment]
@pradeep3093 thanks for the issue. Network issues are tricky to diagnose, and there isn't much we can do from our end about them since the underlying Git operations are failing. You can try running this command to see if it helps:

`git config --global http.postBuffer 157286400`

You can try using the command line to push a subset of commits by using the following command:

`git push origin commit-SHA:branch`

For example, if you have three commits A (4d3bf9) - B (e55b5f) - C (c109e0) and wanted to push A and B to your `main` branch you would run this command:

`git push origin e55b5f:main`

I hope that helps. I'm going to close this out as this isn't a specific issue with GitHub Desktop, but if you have any further questions please let me know. My [comment here ](https://github.com/desktop/desktop/issues/19067#issuecomment-2269226714) also has some further suggestions if you're using something like Git LFS.

**Comment by hassanfrooqkhan** [comment]
@pradeep3093 Did you get your issue resolved? I can see @steveward just copy pastes the same response to everyone and none of his suggestions actually work
