### ISSUE TITLE
Github Desktop Failed to install

### ISSUE THREAD

**Issue by Kaiser426** [desktop/desktop#19235]
### The problem

I am attempting to download Github Desktop for the first time and I get an "Installation has failed" pop-up. The "Open Setup Log" shows nothing relevant. The Event Viewer does not show any errors. This also happens to other clients like GitKraken. I have attempted to run as administrator, without a firewall, repaired my .NET, and tried sfc /scannow.

### Release version

Github Desktop 3.4.5

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Download Github Desktop from the official website. 2. Run the installer as administrator 3. Installer immediately fails and a pop-up appears

### Screenshots

![image](https://github.com/user-attachments/assets/511ceb79-7329-4bc1-87c3-ad4677717180)

**Comment by steveward** [comment]
@Kaiser426 thanks for the issue. Can you share the setup log that's linked in that error?

**Comment by Kaiser426** [comment]
[SquirrelSetup.log](https://github.com/user-attachments/files/16983416/SquirrelSetup.log)

**Comment by steveward** [comment]
I'm not seeing anything there that indicates a specific failure point for GitHub Desktop. Since other applications are failing to install as well that likely points to a broader system issue.

Can you try deleting this directory and then attempt a new installation to see if it makes any difference?

` C:\Users\nicho\AppData\Local\SquirrelTemp`

One other thing to try would be to create a new user profile on your Windows machine to see if there's a specific issue with that user profile.

**Comment by Kaiser426** [comment]
Deleting the SquirrelTemp folder fixed the issue. Thanks!

**Comment by kacim** [comment]
if Deleting the SquirrelTemp folder  still hasissue ，  maybe   C:\Users\nicho\AppData\Local has  GitHubDesktop  folder   try del
