### ISSUE TITLE
Support for multiple languages

### ISSUE THREAD

**Issue by jdnjk** [desktop/desktop#19262]
### The feature request

Github Desktop does not support simplified Chinese

### Proposed solution

Support for multiple languages

**Comment by tidy-dev** [comment]
Thanks for the feedback @jdnjk . At this time we do not have plans to provide multilingual support in GitHub Desktop due to the bandwidth it would require from the team, but this may be something we reconsider again in the future. Please see https://github.com/desktop/desktop/issues/8289 for further information.
