### ISSUE TITLE
Not operating or updating github to github desktop

### ISSUE THREAD

**Issue by kahasim** [desktop/desktop#19266]
### The problem

Not operating or updating github to github desktop

### Release version

Version 3.4.0 (x64)

### Operating system

Windows 11

**Comment by steveward** [comment]
@kahasim thanks for the issue. Can you share some more details or screenshots of the errors you'r encountering in GitHub Desktop? Without more information it will be difficult to assist.

Could you also upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`. The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by kahasim** [comment]
Ok give me til the morning

Kahasim


Sent from my T-Mobile 5G Device



-------- Original message --------
From: Steve Ward ***@***.***>
Date: 9/17/24 2:33 PM (GMT-05:00)
To: desktop/desktop ***@***.***>
Cc: KahasimB ***@***.***>, Mention ***@***.***>
Subject: Re: [desktop/desktop] Not operating or updating github to github desktop (Issue #19266)


@kahasim<https://github.com/kahasim> thanks for the issue. Can you share some more details or screenshots of the errors you'r encountering in GitHub Desktop? Without more information it will be difficult to assist.

Could you also upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs. The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
