### ISSUE TITLE
Error in GitHub Desktop

### ISSUE THREAD

**Issue by darshitnextgen** [desktop/desktop#19272]
### The problem

The Internet works well, but I still found this message "The remote disconnected. Check your Internet connection and try again." with a CLOSE button.

### Release version

Version 3.4.5 (x64)

### Operating system

MAC

### Screenshots

![Screenshot 2024-09-17 at 7 49 25 PM](https://github.com/user-attachments/assets/c34abcae-265a-49ba-b95d-2f1317ed2e86)

**Comment by steveward** [comment]
Thanks for the report @darshitnextgen. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by darshitnextgen** [comment]
@steveward "please upload a log file as an attachment from a day where you experienced the issue."  
 Where do I attach that file?

**Comment by steveward** [comment]
@darshitnextgen you can drag-and-drop it directly into an issue comment here to upload it.
