### ISSUE TITLE
Make repository rules bypass warning optional

### ISSUE THREAD

**Issue by lofcz** [desktop/desktop#19281]
### The feature request

Currently, users cannot configure this popup appearance:
![image](https://github.com/user-attachments/assets/01e5e9ca-2fa0-4159-b431-519714091fcf)

This proposes a new setting that allows the popup to be disabled.

### Proposed solution

![image](https://github.com/user-attachments/assets/a099826f-0b41-4dcc-9610-7a729f86d732)

**Comment by steveward** [comment]
Thanks for the issue @lofcz. I'll bring this up for discussion with the team and will get back to you.

**Comment by lofcz** [comment]
I understand this may be a controversial addition, for that reason I've purposefully kept this indicator intact:
![image](https://github.com/user-attachments/assets/4b8d18ec-466a-4487-863f-57039439225b)

I am looking forward to hearing back from you.

**Comment by steveward** [comment]
@lofcz we discussed this in our team sync for a bit and had some follow up questions. 

- Can you share a few more details about your specific need for this feature? Is there a case where you always need to bypass a specific rule? I looked through our issue tracker and couldn't find any previous requests around this, and I believe this is because if a rule is too obtrusive users end up modifying the actual rule itself. 
- We also discussed scoping this to a per-repository basis by putting the checkbox in the `Repository Settings...` menu. in  Is this something you find you need for multiple repositories, or just one specific repository?

**Comment by lofcz** [comment]
Thank you for taking the time to discuss this internally.

I have several repositories where I need to bypass the rules regularly, but I need other collaborators to honor the rules. It might be due to my incompetence, but I haven't been able to configure the ruleset to work like that. The best I could do is to scope the ruleset to the branch I need protected and add the "Repository admin" role to the bypass list.

Even though I need to do this for a few repositories, I like the idea of a per-repository checkbox. I can implement this feature.

**Comment by tidy-dev** [comment]
>  I need to bypass the rules regularly, but I need other collaborators to honor the rules

Sorry to be pedantic, but do you mind expanding on a scenario where you want protective rules, but don't regularly want to follow them yourself?

**Comment by lofcz** [comment]
It's a scenario in which I have a scarce trickle of occasional contributions that must go through PRs. I work on these repositories almost completely alone, and for that reason, making PRs myself is mostly nonsensical - I have nobody to review them.

I think some of the concerns raised in https://github.com/orgs/community/discussions/6292 are relatable to this.

**Comment by tidy-dev** [comment]
@lofcz We discussed this in our team sync this week and compared GitHub Desktop's behavior to that of GitHub.com. It would appear that GitHub Desktop UI is more defensive (a stance we sometimes choose) in that if you can bypass a ruleset for some actions you do not even get a warning about the ruleset and don't get a confirmation.  Since we are providing the warning message above the commit button that states "you can bypass them", we are ok to align with GitHub.com and remove the confirmation prompt.

Would you be interested in creating a PR to remove the prompt instead of adding a setting?


Other discussion points:

GitHub Desktop generally takes the stance of having confirmation popups on actions where a user could easily get themselves into an undesired situation that is hard to get out of such as discarding a change. In this case, if a user is bypassing rules, they have already done the leg work to set up the repository rules such that they can bypass showing intention and knowledge of their actions.

**Comment by lofcz** [comment]
Thanks for the update, I'll open a new PR removing the confirmation popup when bypassing the rules.

**Comment by lofcz** [comment]
I've removed the modal in #19353 - ran into some issues in the other PR, sorry about that.
