### ISSUE TITLE
not able to push my code on github

### ISSUE THREAD

**Issue by iamakmishra11** [desktop/desktop#19306]
### The problem

The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.

### Release version

latest

### Operating system

windows 11

**Comment by steveward** [comment]
Thanks for the report @iamakmishra11. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
