### ISSUE TITLE
pre-fill Pull Request template if found in repository

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#1930]
Depends on https://github.com/desktop/desktop/issues/295

### Description

The Classic Windows and Mac apps didn't look for the Pull Request template when you would go and create a pull request. This seems like an oversight, but I'll leave this open

There's probably some edge cases here to be mindful of (submitting a PR from a fork should use the upstream PR template, for example) and we should wrap our heads around these if we want to bring this into the app.

**Comment by mattbischoff** [comment]
Thanks for moving this over for me!

**Comment by joshaber** [comment]
Thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I'm going to add the `future-proposal` label to this issue and close it out, so that we don't get overwhelmed with our backlog! We'll revisit these as part of our next planning session.

**Comment by mattbischoff** [comment]
😢 Alright, thanks Josh.
