### ISSUE TITLE
Remote losing internet

### ISSUE THREAD

**Issue by jen-ne-sse** [desktop/desktop#19314]
### The problem

I attempt to push data and an error message occurs saying that my remote has lost Internet connection.
<img width="963" alt="Screenshot 2024-09-26 at 1 43 06 PM" src="https://github.com/user-attachments/assets/51f140d4-189d-4b30-9602-4e66fbf37495">

### Release version

Version 3.4.5 (x64)

### Operating system

Mac OS Sequoia 15

### Steps to reproduce the behavior

1. click fetch
2. select push

**Comment by steveward** [comment]
Thanks for the report @jen-ne-sse. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by seaveredge** [comment]
Discussion on this also going on at: https://github.com/desktop/desktop/issues/19343
