### ISSUE TITLE
show contributing link in Pull Request view

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#1931]
Depends on #295 

### Description

The GitHub website will link off to the CONTRIBUTING.md docs when you are creating a pull request:

<img width="1015" alt="screen shot 2017-06-07 at 4 58 28 pm" src="https://user-images.githubusercontent.com/359239/26898491-949beffe-4ba2-11e7-934a-908dc298e0c2.png">

This wasn't something we supported in the classic Desktop apps.

**Comment by joshaber** [comment]
Thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I'm going to add the `future-proposal` label to this issue and close it out, so that we don't get overwhelmed with our backlog! We'll revisit these as part of our next planning session.

**Comment by billygriffin** [comment]
I'm going to remove `future-proposal` here since we have the reference captured in #295 and we aren't supporting PR creation in app today.
