### ISSUE TITLE
Not Understand

### ISSUE THREAD

**Issue by sergey-krasilnikov-1973** [desktop/desktop#19324]
### The problem

listen ENOBUFS: no buffer space available 127.0.0.1

Would you like to retry cloning ?

### Release version

Version 3.4.5 (x64)

### Operating system

Windows 10

**Comment by sergiou87** [comment]
Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
