### ISSUE TITLE
I get an error and cannot push. Only a "publish this repository" button is available

### ISSUE THREAD

**Issue by DianaSwan** [desktop/desktop#19326]
I get the following error:
**Git returned an unexpected exit code '3221225477' which should be handled by the caller (getStatus).'**

and another error:
**Unknown error**

**Comment by tidy-dev** [comment]
@DianaSwan Thank you for reaching out! That error is usually due to an access or permissions violation. Did this just start happening after a system change or user configuration change that could be reverted?  

It can also be caused by antivirus software, you try disabling your antivirus and trying again. 

To further help you, could you [lease upload a log file from a day you experienced the issue? To access the log files go to the menu and select Help > Show Logs.
