### ISSUE TITLE
enableResizingToolbarButtons causes misaligned toolbar on Windows and macOS

### ISSUE THREAD

**Issue by niik** [desktop/desktop#19330]
With the `enableResizingToolbarButtons` feature flag enabled the toolbar buttons are not tall enough on macOS causing a margin underneath each button

![Image](https://github.com/user-attachments/assets/2ef0b025-2fd7-488a-9688-2d1559dcd59a)

And on Windows the toolbar buttons extends beyond the available height of the toolbar causing the separators between each button to extend below the toolbar.

![Image](https://github.com/user-attachments/assets/df5e4768-b0f9-4f3b-ae6f-ce3a19d4c3d8)

cc https://github.com/desktop/desktop/pull/18095
cc https://github.com/desktop/desktop/pull/19239

Suggest we fix this or disable the feature flag until we're able to address it @desktop/core

**Comment by sergiou87** [comment]
@jpedroso would you have time to take a look at this? 🙏

**Comment by tidy-dev** [comment]
> Disable the feature flag 

IMO, this is a minor cosmetic, so I am not sure it worth disabling in beta, but agree we should fix before shipping to production. 

Nice catch! I have to zoom in the app to see that. Meh.. Maybe I need a new glasses prescription. :D It is more noticeable on dark theme which I rarely use.

**Comment by jpedroso** [comment]
@sergiou87 i can have a look later today, although i should add i had trouble getting latest `development` to compile on my machine when i tried just before the beta went out. i’ll keep you posted.

**Comment by jpedroso** [comment]
@sergiou87 @tidy-dev i have a potential fix.

First, below we can see cbetter that the `resizable-component` has a height of 49px, but its child is only getting 47px.

![2024-10-01-003475](https://github.com/user-attachments/assets/91dd57dc-b70c-4bdf-ae89-2032d90f45f5)

The `branch-button` and `push-pull-button` need to have `flex-grow: 1` applied to fill the available height of the parent. Interestingly, the issue is not seen on `sidebar-section` and that’s because it is getting `flex-grow: 1` from the following rule on _toolbar.scss.

```css
.sidebar-section {
    & > :last-child {
      flex-grow: 1;
    }
}
```

Adding `flex-grow: 1` in `.toolbar-dropdown` fixes the issue for `branch-button`, adding to `.toolbar-button` fixes it for `push-pull-button`. Adding the former makes the rule on `.sidebar-section`’s last child redundant so it can be removed.

I will open the pr shortly and we can discuss further.

**Comment by jpedroso** [comment]
@sergiou87 @tidy-dev opened #19340, and it’s ready for review. it’s not possible for me to test the fix on Windows so if someone can give the branch a try and let me know, I appreciate it.
