### ISSUE TITLE
Filter options & sync icon required

### ISSUE THREAD

**Issue by merbin2012** [desktop/desktop#19369]
### The feature request

I have added many repository in my github desktop.
1) I want to keep all the repository updated, So I will open the app and waiting for synchronize but there are no indication for synchronize, so I need to manually open all the repositories and click the "fetch origin" button. This is very difficult

2) I want to filter the repository, commit, pull, push 

### Proposed solution

1) Please add a icon to the left side of repository name [pending, synchronizing, synchronized]
2) Add three filter commit, pull & push

**Comment by steveward** [comment]
Thanks for the issue @merbin2012. The option to fetch all repositories is being tracked in https://github.com/desktop/desktop/issues/13700, so you can follow along there for updates. GitHub Desktop also automatically background fetches to keep your repositories up-to-date.

> 2\. I want to filter the repository, commit, pull, push

Can you explain what you mean here further? Are you wanting to filter by the status indicators GitHub Desktop shows in the repository list? Currently we show uncommitted changes, and if there are new commits that need to be pushed or pulled.

**Comment by merbin2012** [comment]
@steveward 
1) No, it is not working properly. See the attached image. It is not automatically fetched. If I manually click the fetch button for a few repositories, then it sometimes works.

![image](https://github.com/user-attachments/assets/9942d017-720b-44bb-a890-87b5a60b82cb)

In the below image, one of the projects is automatically fetched, but see "0-important" repositories is not fetched automatically. I suggest you to add two more icons
a. Initially show the pending fetch icon for all repositories
b. Whenever the background fetch process is completed, you can hide the pending fetch icon and show its suitable icon (like currently you are showing fetch, commit, and push)

![bug](https://github.com/user-attachments/assets/98064444-e553-44fb-b3dd-da9887aa926e)

2) I have many repositories, so I want to see the pending push, commit, or pull status through the filter option.

**Comment by steveward** [comment]
Thanks for the update. For reference, GitHub Desktop performs fetch operations periodically in the background (at timed intervals), and when it does so, it fast-forwards outdated branches automatically. Sometimes it isn't possible to fast-forward due to changes in the local branch, which is when you would see the `Pull origin` option. 

It's unlikely we would add an in-progress icon to the repository list unless we had an implementation of "Fetch all", so I'm going to capture that feedback and add it to the issue I referenced above. 

> 2\. I have many repositories, so I want to see the pending push, commit, or pull status through the filter option.

At this time we don't have any plans to make changes to the filter option, but I'll add this to https://github.com/desktop/desktop/issues/6460 where we have collected previous feedback about the repository list and filtering options.
