### ISSUE TITLE
The IDE can't watch commit action sometimes. 

### ISSUE THREAD

**Issue by Pdalla** [desktop/desktop#19373]
### The problem

A long time, i got  this bug on GitHubDesktop.
Basically when u commit something, the IDE can't watch this action to disable "commit button" and change the action of "fetch origin button" to "push commit".
Below i got a rec of this bug, to simplify identification. 

https://github.com/user-attachments/assets/400899b1-6782-4c3c-9af3-ba408f5c6ef7

https://github.com/user-attachments/assets/eabd4627-8760-48d5-85e0-316ee5e508f6

### Release version

3.4.6 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

Write a commit title and message
Click on "commit" 
The IDE can't validate  the commit action, so "fecth origin button" doesn't change to "push commit" and button "commit" still enabled. 

### Log files

[2024-10-09.desktop.production.log](https://github.com/user-attachments/files/17310181/2024-10-09.desktop.production.log)

### Additional context

After commit, when u change to "history" and back again to "Changes" the IDE works goog so the "fetch origin button" changed to "push commit" and "commit button" be disabled.

**Comment by steveward** [comment]
@Pdalla thanks for the issue. We've seen cases of this being caused by specific filenames. For instance, https://github.com/desktop/desktop/issues/16264 was a case where this occurred due to trailing spaces in the filename.

Are you able to reproduce this consistently? It would be helpful to know what `git status` shows from the command line as well when you encounter this issue.
