### ISSUE TITLE
Desktop app on vps

### ISSUE THREAD

**Issue by Mhmortensen** [desktop/desktop#19401]
### The problem

Every time i restart my vps/pc github desktop dosnt work anymore, then i need to reinstall??

### Release version

newest

### Operating system

Windows 10

**Comment by steveward** [comment]
@Mhmortensen thanks for the issue. Can you share a few more details about what specifically isn't working? Without more information it will be difficult to assist you further.

Could you also upload the log file from GitHub Desktop so that I could get some more information about these issues? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`. The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
