### ISSUE TITLE
I keep getting an upload error 

### ISSUE THREAD

**Issue by stacksappstudio** [desktop/desktop#19418]
### The problem

Keep getting upload error saying the connection got lost. I Upgraded to Pro today because I thought there was a limit upload on the free account. 

### Release version

version 3.4.6

### Operating system

Mac OS 13.7

### Log files

[2024-10-18.desktop.production.log](https://github.com/user-attachments/files/17435172/2024-10-18.desktop.production.log)

**Comment by steveward** [comment]
Thanks for the issue @stacksappstudio. Network issues are tricky to diagnose, and there isn't much we can do from our end about them since the underlying Git operations are failing

You can try using the command line to push a subset of commits by using the following command:

`git push origin commit-SHA:branch`

For example, if you have three commits A (4d3bf9) - B (e55b5f) - C (c109e0) and wanted to push A and B to your `main` branch you would run this command:

`git push origin e55b5f:main`

Some users have had also success running this command to try and prevent timeouts:

`git config --global http.postBuffer 157286400`

If none of those suggestions work it may be worth trying to set [up a SSH key](https://docs.github.com/en/authentication/connecting-to-github-with-ssh), which some users have had more success with when encountering network issues. You could then switch the remote URL to use SSH in GitHub Desktop by going to `Repository` > `Repository Settings` > `Remote`. 

I hope that helps! I'm going to close this out, but let me know if you have any further questions.
