### ISSUE TITLE
Cloning failure

### ISSUE THREAD

**Issue by GRappolt** [desktop/desktop#19435]
### The problem

I can't clone the Epic Unreal Engine repository to my PC. I've retried several times, without success. The error messages seem to be a bit different each time, but it always fails at the same stage.

Here is a cut-and-paste of the error message from my last attempt:

Cloning into 'C:\Users\grapp\Documents\GitHub\UnrealEngine'...
remote: Enumerating objects: 6403124, done.        
remote: Counting objects: 100% (3727/3727), done.        
remote: Compressing objects: 100% (2195/2195), done.        
remote: Total 6403124 (delta 1646), reused 3473 (delta 1463), pack-reused 6399397 (from 1)        
Receiving objects: 100% (6403124/6403124), 30.01 GiB | 47.15 MiB/s, done.
error: inflate: data stream error (incorrect data check)
fatal: serious inflate inconsistency
fatal: fetch-pack: invalid index-pack output

Would you like to retry cloning Unreal Engine?

### Release version

Version 3.4.6 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Open GitHub Desktop
2. Click in the repositories window
3. Scroll down to select Epic Games - Unreal Engine
4. Click on the Clone button under the repositories window

### Log files

[2024-10-22.desktop.production.log](https://github.com/user-attachments/files/17477905/2024-10-22.desktop.production.log)

### Additional context

I recently linked my GitHub account to the Epic Games repositories. My account has existed for some years and has older repositories for my own (Android) projects.

**Comment by steveward** [comment]
@GRappolt thanks for the issue. That's a very large repository -- almost 30GB in size, so timeouts are likely.

Network issues are tricky to diagnose, and there isn't much we can do from our end about them since the underlying Git operations are failing

Some users have had also success running this command to try and prevent timeouts:

`git config --global http.postBuffer 157286400`

You could also try a shallow clone and specify a branch:

`git clone <repo_URL> --depth=1 --single-branch <branch>`

If you're using Git LFS with a large repository you can try using this config option to increase the timeout:

`git config lfs.activitytimeout 30`

This config sets the maximum time in seconds that the HTTP client will wait for the next TCP read or write. The default is 10 seconds. If you're not using Git LFS and are pushing large files I would also recommend looking into that as an option.

There are also some HTTP timeout config operations that may help, or at lease provide additional diagnosis about the timeout. One user previously had success with these commands:

`git config --global http.lowSpeedLimit 1000`
`git config --global http.lowSpeedTime 20`

The `lowSpeedLimit` configures the minimum bytes per second, and the `lowSpeedTime` is the number of seconds. If the operation is lower than that threshold for the set time it will timeout. Adjusting those values may help with timeouts.

There are also pack depth options that have helped some users:

`git config --global pack.window 1`
`git config --global pack.depth 1`

The [config manual](https://git-scm.com/docs/git-config/) provides more details about these.

If none of those suggestions work it may be worth trying to set [up a SSH key](https://docs.github.com/en/authentication/connecting-to-github-with-ssh), which some users have had more success with when encountering network issues. You could then switch the remote URL to use SSH in GitHub Desktop by going to `Repository` > `Repository Settings` > `Remote`. 

I hope that helps. I'm going to close this out as there isn't much we can do from our end about timeouts for large repositories, but let me know if you have any further questions.
