### ISSUE TITLE
github desktop authentication problem

### ISSUE THREAD

**Issue by ghost** [desktop/desktop#19430]
### The problem

when I try to sign in the github desktop "Failed Retrieving Authenticated User" message is come.
how to solve this problem?

### Release version

Version 3.4.6

### Operating system

windows 11

### Screenshots

![Screenshot (37)](https://github.com/user-attachments/assets/26c62524-e7d3-451b-a92c-8e413a090406)

**Comment by steveward** [comment]
Thanks for the report @Mubarek44. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
