### ISSUE TITLE
Cloning repository with Github Desktop in windows local file path doesn't work

### ISSUE THREAD

**Issue by mduduzik** [desktop/desktop#1944]
### Version

**GitHub Desktop version:** Version 0.5.9
**OS version:** Windows 7/Microsoft Windows [Version 6.1.7601]

### Steps to Reproduce

See attachment

### Logs
Empty.

#### Additional Information
![github_desktop_clone_windows_repo](https://user-images.githubusercontent.com/535655/26943215-c26a60fe-4c52-11e7-8788-2b10cdb8053f.png)

**Comment by shiftkey** [comment]
@mduduzik thanks for the feedback. This isn't something we supported in the classic apps, and this new dialog is focused on getting things from a remote URL or your GitHub/GitHub Enterprise install.

I'm going to mark it as `future-work` because I don't think it's in scope for our 1.0 release, unless someone in the community wants to look into it.

**Comment by mduduzik** [comment]
@shiftkey  thanks for a prompt response; much appreciated.

**Comment by joshaber** [comment]
Thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I'm going to add the `future-proposal` label to this issue and close it out, so that we don't get overwhelmed with our backlog! We'll revisit these as part of our next planning session.

**Comment by billygriffin** [comment]
Since you can add local repos to Desktop and create them in addition to the cloning flows @shiftkey described above, I'm going to remove `future-proposal` here. Thanks!
