### ISSUE TITLE
Disconnection from repository when publishing branches

### ISSUE THREAD

**Issue by kmransom56** [desktop/desktop#19486]
### The problem

Attempting to Publish  a local project to Github, I received the arror message that The remote disconnected. Check your Internet connection and try again

### Release version

3.4.8 (x64)

### Operating system

Windows 11

### Steps to reproduce the behavior

cd /home/keransom/projects/fortigate_configurator
git init
git add .
git commit -m "Initial commit"
git remote add origin https://github.com/kmransom56/fortigate_configurator.git
git push -u origin main

**Comment by steveward** [comment]
Thanks for the issue. Could you send over the log file from GitHub Desktop so that I could get some more information about this error?

To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
