### ISSUE TITLE
Fetching from a local repository hangs and then says Never Fetched

### ISSUE THREAD

**Issue by feedvaal** [desktop/desktop#19521]
### The problem

Sometimes when fetching from a local repository, github desktop freezes/hangs.  If we restart github desktop, it now says Never Fetched for everything.  A git fetch with GIT_TRACE=1 shows that it hangs on a line like the one below.  Any ideas what could be going wrong? 

09:46:03.890766 git.c:463               trace: built-in: git fetch-pack --stateless-rpc --stdin --lock-pack --include-tag --thin http://foo.bar.com/path/to/theFile.git/

### Release version

3.4.8

### Operating system

Windows 11 Business

### Steps to reproduce the behavior

Click to fetch (or git fetch in git bash).

It is intermittent, although it seems like pruning branches cuts down on the probability of it happening

**Comment by steveward** [comment]
Thanks for the report @feedvaal. Could you upload the log file from GitHub Desktop so that I could get some more information about this issue? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
