### ISSUE TITLE
GitHub Desktop auto-creates branches which I never asked for

### ISSUE THREAD

**Issue by mbernson** [desktop/desktop#19533]
### The problem

Hi,
I've noticed recently that GitHub Desktop started doing some behaviour that I wasn't expecting. In certain cases, it automatically creates branches for the pull requests that I check out using the GitHub Desktop app.

This isn't what I want, is there a way to turn off this behaviour? See also my steps to reproduce.

### Release version

3.4.8 (arm64)

### Operating system

macOS Sonoma 14.7.1

## Steps to reproduce
1. In my repository, write some code an commit it to a branch
2. Push the branch and create a pull request on GitHub.com
3. At a later time, switch back to this branch by selecting the pull request in the Pull Requests tab of the branch dropdown
4. Commit some more code and push it
## Expected result
* My changes are pushed to the pull request branch
## Actual result
* GitHub Desktop has created a branch called `pr/73` (PR number) and pushed to that instead. The commits don't show up in my pull request on GitHub.com because they're on this different branch.

**Comment by niik** [comment]
Hey @mbernson, thanks for reaching out!

That's certainly not the intended behavior and I suspect there's something related to your setup here that I'm not quite understanding. The only time GitHub Desktop would create a `pr/number` branch instead of using the branch name associated with the PR is if the upstream branch is on a different remote than the default (typically origin) or `upstream` if you're working in a fork.

See https://github.com/desktop/desktop/blob/368149039d8a2e126c276408e3f1caf10e5a5430/app/src/lib/stores/app-store.ts#L6639-L6653

Could you share your remote setup to help us get some clarity on this? Either by running `git remote -v` and sharing that output (redacted if you so choose) or by sharing the relevant sections from the `.git/config` file in your repository

**Comment by mbernson** [comment]
Hi @niik, thank you for the reply! 

This is a private repo on GitHub with no forks and I have one remote which is called `origin`. But around the time when I experienced this problem, I also noticed that there were two additional remotes pointing to the same repo URL but using HTTPS instead of SSH. 

I don't know where these remotes came from, I didn't add them myself. I assumed I clicked a wrong button in GitHub Desktop, and it had created them for me? I know that Desktop sometimes asks whether I'm using this repo as a source or as a fork to contribute to.

I will pay more attention to that in the future now that I know what triggers this behaviour!
