### ISSUE TITLE
DEsktop just shows Fetching origin (Hang on...)

### ISSUE THREAD

**Issue by salvisagar83** [desktop/desktop#19578]
### The problem

DEsktop just shows Fetching origin (Hang on...). 
Just open dekstop app and it keeps loading, same time extension works just fine

### Release version

Version 3.4.8 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

![image](https://github.com/user-attachments/assets/4b68afa5-7ce7-4464-bc50-6c54c257a0f4)

### Screenshots

![image](https://github.com/user-attachments/assets/b7d14862-b2ac-4089-a6d0-1350b12f9b64)

**Comment by steveward** [comment]
@salvisagar83 thanks for the issue. Are you using SSH or HTTPS with this repository? If you are using SSH, try going to `File` > `Options` > `Advanced` and uncheck the `Use system OpenSSH` checkbox. Let me know if that gets things working.

**Comment by salvisagar83** [comment]
Yes I am using SSH and I unchecked that option but still not helping. Anything I do with that dropdown and it hangs


***@***.***?anonymous&ep=bwmEmailSignature>             Book time to meet with ***@***.***?anonymous&ep=bwmEmailSignature>
________________________________

**Comment by steveward** [comment]
Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue. 

You can also try switching to use HTTPS instead of SSH to see if that gets things working. You would just need to change the remote URL under `Repository` > `Repository Settings` > `Remote`.
