### ISSUE TITLE
issue bug help me to fix

### ISSUE THREAD

**Issue by ghost** [desktop/desktop#19577]
### The problem

nagkakaeror parang old windows app cgiro ang gamit ko kailngn ng bago

### Release version

ey

### Operating system

win 10

### Steps to reproduce the behavior

_ey_

### Screenshots

ey

### Additional context

fix problem

**Comment by sergiou87** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
