### ISSUE TITLE
Getting "Unable to write new index file"

### ISSUE THREAD

**Issue by tophermiller** [desktop/desktop#19596]
### The problem

Getting "Unable to write new index file" on attempt to commit, all of a sudden for no reason.   Was working fine until this came up and now I can't commit.    Tried command line git and it worked so I was able to work around it.

### Release version

3.4.9

### Operating system

Windows 11

### Steps to reproduce the behavior

Try to commit any file

**Comment by steveward** [comment]
Thanks for the report @tophermiller. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by tophermiller** [comment]
Rebooting solved the problem.   Thanks.

…Chris.
