### ISSUE TITLE
The remote disconnected. Check your Internet connection and try again.

### ISSUE THREAD

**Issue by appdevelopersurya** [desktop/desktop#19643]
### The problem

The remote disconnected. Check your Internet connection and try again.

### Release version

The remote disconnected. Check your Internet connection and try again.

### Operating system

The remote disconnected. Check your Internet connection and try again.

### Steps to reproduce the behavior

The remote disconnected. Check your Internet connection and try again.

### Log files

The remote disconnected. Check your Internet connection and try again.

### Screenshots

The remote disconnected. Check your Internet connection and try again.

### Additional context

The remote disconnected. Check your Internet connection and try again.

**Comment by steveward** [comment]
Thanks for the report @appdevelopersurya. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
