### ISSUE TITLE
Remote disconnected while pushing small changes

### ISSUE THREAD

**Issue by AndrewPowers1986** [desktop/desktop#19650]
### The problem

I switched to GitHub Desktop from command line hoping it would solve my issues. The error I'm getting on the desktop app is "The remote disconnected. Check your internet connection and try again." I've tried running "git config --global http.postBuffer 157286400" from the command-line. I also tried switching to a new branch and pushing. No change.

### Release version

3.4.9

### Operating system

Windows 10

### Steps to reproduce the behavior

Publish branch

### Log files

[2024-12-02.desktop.production.log](https://github.com/user-attachments/files/17984485/2024-12-02.desktop.production.log)

### Screenshots

![githubError](https://github.com/user-attachments/assets/30ef3f40-b82d-4cc6-b875-188ec3624ac4)

**Comment by steveward** [comment]
Thanks for the report. This looks like a rather large repository. Are you using Git LFS with it. Network issues are tricky to diagnose, and there isn't much we can do from our end about them since the underlying Git operations are failing. 

You can try using the command line to push a subset of commits by using the following command:

`git push origin commit-SHA:branch`

For example, if you have three commits A (4d3bf9) - B (e55b5f) - C (c109e0) and wanted to push A and B to your `main` branch you would run this command:

`git push origin e55b5f:main`

If you're using Git LFS with a large repository you can try using this config option to increase the timeout:

`git config lfs.activitytimeout 30`

This config sets the maximum time in seconds that the HTTP client will wait for the next TCP read or write. The default is 10 seconds. If you're not using Git LFS and are pushing large files I would also recommend looking into that as an option.

There are also some HTTP timeout config operations that may help, or at lease provide additional diagnosis about the timeout. One user previously had success with these commands:

`git config --global http.lowSpeedLimit 1000`
`git config --global http.lowSpeedTime 20`

The `lowSpeedLimit` configures the minimum bytes per second, and the `lowSpeedTime` is the number of seconds. If the operation is lower than that threshold for the set time it will timeout. Adjusting those values may help with timeouts.

There are also pack depth options that have helped some users:

`git config --global pack.window 1`
`git config --global pack.depth 1`

The [config manual](https://git-scm.com/docs/git-config/) provides more details about these.

If none of those suggestions work it may be worth trying to set [up a SSH key](https://docs.github.com/en/authentication/connecting-to-github-with-ssh), which some users have had more success with when encountering network issues. You could then switch the remote URL to use SSH in GitHub Desktop by going to `Repository` > `Repository Settings` > `Remote`. 

Let me know if that helps.

**Comment by imcalledfyre** [comment]
for me just opening terminal (mac) cmd would work on windows AS ADMIN,

just running `git config --global http.postBuffer 524288000`
