### ISSUE TITLE
Blurry GitHub Desktop on Windows 11

### ISSUE THREAD

**Issue by Kitsune4898** [desktop/desktop#19654]
### The problem

My UI is blurry except where my mouse is tracking.

### Release version

3.4.3 (x64)

### Operating system

Windows 11

### Steps to reproduce the behavior

Open GitHub Desktop

### Screenshots

![Screenshot (2)](https://github.com/user-attachments/assets/8a346470-2426-4740-a6a9-286553fc4de5)
![Screenshot (11)](https://github.com/user-attachments/assets/f221c3ca-5c33-4421-b82d-72f81fbce8d5)

**Comment by steveward** [comment]
Thanks for the report @Markkautz4898. Are you using an NVIDIA GPU? One user had this issue and shared the following:

>The issue was caused by Nvidia's global Antialiasing settings—specifically, the FXAA and Multi-Frame Sampled AA (MFAA) options being turned on. Restoring the default values resolved the blurred UI and font issue

You can also try launching GitHub Desktop with GPU accelerated rendering turned off to verify that it is indeed related to the GPU  by setting the `GITHUB_DESKTOP_DISABLE_HARDWARE_ACCELERATION` environment variable to 1 by running `set GITHUB_DESKTOP_DISABLE_HARDWARE_ACCELERATION=1` in cmd.exe and restarting your machine or by setting it through the UI following a [guide like this](https://docs.oracle.com/en/database/oracle/machine-learning/oml4r/1.5.1/oread/creating-and-modifying-environment-variables-on-windows.html#GUID-DD6F9982-60D5-48F6-8270-A27EC53807D0).

Note that you may have to restart your machine for the changes to take effect. 

I'm going to close this out since we have https://github.com/desktop/desktop/issues/19654 tracking this, but feel free to follow up here with any questions.

**Comment by Kitsune4898** [comment]
I am running a NVIDIA 2060
