### ISSUE TITLE
I pushed my first thing in three years from vs 2019 and it ended up pushed on another account WHITCH I DONT EVEN HAVE ACCESS TO

### ISSUE THREAD

**Issue by jorisstudios** [desktop/desktop#19658]
So it pushed under an account with the name [my front name][my back name] and i dont have access to that, whats goin on?????

**Comment by steveward** [comment]
@jorisstudios thanks for the issue. This is likely due to your name and email address still being the same in your `.gitconfig`. See this article:

https://docs.github.com/en/pull-requests/committing-changes-to-your-project/troubleshooting-commits/why-are-my-commits-linked-to-the-wrong-user

You can update this in GitHub Desktop by going to `File` > `Options` > `Git`. I hope that helps.
