### ISSUE TITLE
Pushing to Origin

### ISSUE THREAD

**Issue by N4CNR** [desktop/desktop#19665]
### The problem

ERROR:
The remote disconnected, Check you internet connection and try again, 

### Release version

3.4.8(X86)

### Operating system

Mac OS Sequoia

### Screenshots

![IMG_0574](https://github.com/user-attachments/assets/35bf9385-0211-4900-becb-3601385d6dba)

**Comment by steveward** [comment]
Thanks for the report @N4CNR. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
