### ISSUE TITLE
Desynchronisatoin without logout

### ISSUE THREAD

**Issue by olehpetrovasyliev** [desktop/desktop#19699]
### The problem

i can`t push changes to my repo when i am logged in on both desktop and browser

### Release version

3.4.9

### Operating system

windows 10

### Steps to reproduce the behavior

1. Make changes in code
2. Commit changes
3. Push the commit to my remote branch
4. Get authorisation error

### Screenshots

![image](https://github.com/user-attachments/assets/9387c4f0-c32d-4879-b490-20266c25765c)

**Comment by niik** [comment]
Hey @olehpetrovasyliev, thanks for reaching out. Without more information we can't help you here as we're not able to reproduce what you're seeing. Please provide logs as outlined in the issue template and provide detailed explanation of what happens when you do sign in after seeing that dialog in your screenshot
