### ISSUE TITLE
cant move it to applications folder in mac

### ISSUE THREAD

**Issue by krysxuu** [desktop/desktop#19705]
Error invoking remote method 'move-to-applications-folder': Error: Failed to copy to applications directory even with authorization

**Comment by steveward** [comment]
Thanks for reaching out @krysxuu!

Would you mind filling out the rest of the issue template so that we can better understand what is causing the problem you are experiencing? Without that information it will be difficult to help you further. It would especially be helpful if you could upload the log file from GitHub Desktop, which will give more details about the specific error you are seeing. 

To access the log files go to the  menu in GitHub Desktop and select `Help` > `Show Logs...`. The log files are created daily -- please send over a log file as an attachment from a day where you experienced the issue.
