### ISSUE TITLE
Why are no features ever added to GitHub desktop?

### ISSUE THREAD

**Issue by jorisw** [desktop/desktop#19714]
### The feature request

Has funding been pulled from GitHub Desktop? It just seems like development of the desktop app has just been maintenance and nothing else. Feature requests go completely unhandled.

Simple features such as [multiple accounts](https://github.com/desktop/desktop/issues/3707), [selective stashing](https://github.com/desktop/desktop/issues/11531) or [multiple stashes](https://github.com/desktop/desktop/issues/12699) have been open for years and years.

Popular competing Git clients feature all of these features.

### Proposed solution

Explain to us why GitHub can't work on features for GitHub Desktop.

**Comment by Risae** [comment]
I sadly have to agree, been following this tool since 2020 and not much has changed. I remember a lot of people doing the work and implementing wanted features, but the devs declined to merge the changes. Not entirely sure why _good_ quality-of-life features are not being worked on.

For example

- https://github.com/desktop/desktop/issues/15244
- Why is Linux not supported?
- Why is there no GitHub Copilot implementation, to automate the creation of commit messages? (and more)
- Why is there no Windows on **ARM** build, but an Mac on ARM exists?

I thought that GitHub is owned by Microsoft?!
Just look at all of these issues, highly voted and marked as `not planned` ?!

![image](https://github.com/user-attachments/assets/1d019277-26b8-476a-9403-303bc60d4d02)

Who, if not for the users, is this tool being made for? Is this tool being held back because another product would get affected by it?
And don't misunderstand me - If you need funding, then let me pay for it. I see the value in it.

**Comment by jorisw** [comment]
I too would pay for a more full featured client. 

~The reason I don’t switch to another client is my being used to the workflow and the tight integration with pull requests.~ — Looks like [GitTower](https://www.git-tower.com) features strong integration with GitHub so will probably switch to that

**Comment by sergiou87** [comment]
👋 

> Has funding been pulled from GitHub Desktop?

No, this has always been a small team. Maybe a bit smaller lately, but Desktop is definitely not in maintenance mode.

There's been a lot of work to make Desktop accessible (you can see many PRs about that in the last ~2 years) which has taken a ton of our time, and now we're trying to get back to new feature work. But we're also doing a lot of internal work around Desktop that might not be visible. Then we are human beings too, have to deal with personal stuff… I can tell you 2024 wasn't the easiest year.

> Why is there no Windows on ARM build, but an Mac on ARM exists?

There is, but only in beta (check our readme file). [We've been waiting for a long time for full ARM support on git](https://github.com/git-for-windows/git/issues/3107), but that's already done so we hope [we can add ARM support for Windows](https://github.com/desktop/dugite-native/pull/515) in production builds in the upcoming weeks/months.

> highly voted and marked as `not planned` ?!

Don't pay much attention to `not planned`: it just means they're not in our roadmap _right now_, it doesn't mean we will never work on it. We're constantly evaluating priorities.

Sorry I don't answer all your questions, but I hope this helps to clarify some of the key ones. Thank you for your patience 🙏
