### ISSUE TITLE
VS code issue in Github Desktop

### ISSUE THREAD

**Issue by Damiyaaina** [desktop/desktop#19718]
my github desktop doesn't have VS code .... how can i fix this issue

**Comment by jun340** [comment]
Javascript enable

**Comment by sergiou87** [comment]
Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by jun340** [comment]
Javascript on
