### ISSUE TITLE
Can we choose to reword some descriptions on GitHub DeskTop

### ISSUE THREAD

**Issue by squirrel-bait** [desktop/desktop#19736]
### The feature request

Currently one of the descriptions of "Publish Branch" within the GitHub DeskTop reads: "Cannot Publish unborn HEAD". While this is factually true, for those of us who have suffered child miscarriages, still born, or horrific medical experiences, this can be quite painful to read for both fathers and mothers. (Don't google unborn head without specifically using git or repository or something of that nature in the search bar)
![Screenshot 2024-12-17 at 10 00 39 AM](https://github.com/user-attachments/assets/bf2ee251-6526-4b0d-88a0-0781acc7bab1)

### Proposed solution

Allow the user to change the wording on descriptions, or if it is already possible, let people know with a small comment pictogram next to the description. 
While I defined a specific reason, this may help others in general by allowing them to define descriptions in their own terms for many other areas.

**Comment by niik** [comment]
Hi, thanks for reaching out!

We’ve taken a look at this and have come to the conclusion that we can rephrase the description without negatively impacting our users’ understanding of what’s going on (we even believe a change might improve the user experience based on online evidence of users searching for an explanation after seeing this description). I've opened #19745 to address this.

While we’re not offering an option for users to change application text contents from within the application itself GitHub Desktop is an open source project so one way to achieve what you describe would be to build the project yourself (see our docs on setting up a development environment: https://github.com/desktop/desktop/blob/development/docs/contributing/setup.md) which would let you modify all aspects of the software including the verbiage.

That said I want to be clear that GitHub Desktop is built on top of Git itself and while in this instance we control the text we are not in control of the verbiage and terminology that Git uses and since we frequently display output from Git we're not going to be able to prevent terms like the one described here from showing in the Desktop app.
