### ISSUE TITLE
Group branches by remote and add count of remote branches

### ISSUE THREAD

**Issue by hazendaz** [desktop/desktop#1977]
### Description

The current drop down simply has 'Default branch' and 'Other branches' grouping.  It would be nice that the grouping was modified to group by remote.  So possibly 'Default Branch', 'origin', 'upstream', and so on for example.  Then additionally, if on the grouping level it could add the count of the remote branches (using something like this -> git branch -r | git remote show origin| wc -l)

### Version

0.6.0

The operating system you are running on may also help with reproducing the
issue:

Windows 10 Creators Update

### Steps to Reproduce

New feature request

### Logs

n/a

#### Additional Information

n/a

**Comment by joshaber** [comment]
Thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I'm going to add the `future-proposal` label to this issue and close it out, so that we don't get overwhelmed with our backlog! We'll revisit these as part of our next planning session.

**Comment by billygriffin** [comment]
Hi @hazendaz, thanks for the issue! We're going to build off of #7755 as your issue here and several others have made us realize we need to consider the context we're providing on branches more holistically. Thanks again for bringing this to our attention.

**Comment by hazendaz** [comment]
@billygriffin Great!  Thanks!
