### ISSUE TITLE
Open Repository in External Editor

### ISSUE THREAD

**Issue by joshaber** [desktop/desktop#2009]
_Split out from https://github.com/desktop/desktop/issues/1554_

Similar to "Open in Atom" in the Classic apps, but with the ability to customize the opening app.

It should be available on both repository list items and on changed files.

**Comment by xt0rted** [comment]
I use a mix of Visual Studio and VS Code, I've missed the Open in Visual Studio option from the old app.

**Comment by rlabrecque** [comment]
Pulling this in from #1554:


#### Open in external program/editor/Atom

- [ ] Changes -> File context menu
- [ ] Repo list -> Repo context menu
- [x] Changes -> Selected file if it's a binary. http://i.imgur.com/hIBnwpj.png Note: This could use some updating as these other features become available.
- [ ] Default to Atom if we can find it installed to keep things in the GitHub brand.
- [ ] Allow the user to specify their default editor in the options.
- [ ] For repos: have this open the options for you to specify your editor?
- [ ] For files: If Atom is not installed then have just open the default Edit verb if available, otherwise open the file normally with [openFile](https://github.com/desktop/desktop/blob/3dc8738e711131047f9973398a5dac08e2cd206e/app/src/lib/open-file.ts), or would we want it to open the options to specify the editor too?
- [ ] Maybe have a recommendation to install Atom in the options? Brand marketing™©®
- [ ] Future work: Make it file type based? You could have atom as the default, then specify say photoshop for images. Perforce's client does this and it's VERY useful.

**Comment by joshaber** [comment]
#2023 added the "Open with External Editor" menu item for changed files.

**Comment by joshaber** [comment]
I changed the title to make it clearer this is about opening _repositories_ in an external editor. We already have the "Open with External Editor" contextual menu item for changed files.

**Comment by joshaber** [comment]
We need some design around how one chooses their preferred editor in Preferences.

**Comment by rlabrecque** [comment]
Well, what do we need here, I don't have any tools on me right now so I can't mock this up, but

Is there design in this area for Open with External Editor for changed files yet? This should be right below it in the preferences and look similar.

Here's what I think we want for the preferences:

```
External Editor to open repositories with:
" (Icon) Current selected editor | none " "Options like passing %1 for the folder path?" [x]
[Reset to Atom (if installed)] [browse]
```

Current selected editor can be the icon, and 'pretty name' of the executable/application if one is selected, if it's not then "None selected" or something like that is probably ideal. The options/ x button can be hidden or greyed out if none is selected.

[x] removes the current editor, resetting it to none.
[Reset to Atom] scans the usual paths to see if atom is installed. If it is then it selects it.
[browse] opens the standard platform browse dialog to select the exe/app.

You need to let users know about the special keys available in the options, I.E. %1 or what ever for the folder name. It would probably be best to put that option by default, and maybe have '?' with a tooltip at the end that explains it?

**Comment by joshaber** [comment]
>Well, what do we need here, I don't have any tools on me right now so I can't mock this up, but

I put this in our Design Review project for @desktop/design to work on.

>Is there design in this area for Open with External Editor for changed files yet?

Not yet, but for this particular issue, we're only looking at opening repositories. Opening files is somewhat handled by the OS already, and customizing file associations is a larger, more complex task.

**Comment by shimpossible** [comment]
I've actually been slowly working on this in the pr marked WIP.



On Jul 24, 2017 12:12 PM, "Riley Labrecque" <notifications@github.com>
wrote:

Well, what do we need here, I don't have any tools on me right now so I
can't mock this up, but

Is there design in this area for Open with External Editor for changed
files yet? This should be right below it in the preferences and look
similar.

Here's what I think we want for the preferences:

External Editor to open repositories with:
" (Icon) Current selected editor | none " "Options like passing %1 for
the folder path?" [x]
[Reset to Atom (if installed)] [browse]

Current selected editor can be the icon, and 'pretty name' of the
executable/application if one is selected, if it's not then "None selected"
or something like that is probably ideal. The options/ x button can be
hidden or greyed out if none is selected.

[x] removes the current editor, resetting it to none.
[Reset to Atom] scans the usual paths to see if atom is installed. If it is
then it selects it.
[browse] opens the standard platform browse dialog to select the exe/app.

You need to let users know about the special keys available in the options,
I.E. %1 or what ever for the folder name. It would probably be best to put
that option by default, and maybe have '?' with a tooltip at the end that
explains it?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/desktop/desktop/issues/2009#issuecomment-317490576>,
or mute
the thread

**Comment by donokuda** [comment]
@niik and I discussed this in our design review today and in addition to being able to set the preferred external editor in the preferences, we'll also want to add an option under the `Repository` menu.

What we've been thinking is something close to:

```
+------------+  +---------------------------+
| Repository | --> Open in *DEFAULT EDITOR* |
+------------+  +---------------------------+---------------------------+
                |  Open in...              --> Atom                     |
                +---------------------------+---------------------------+
                                            |  Visual Studio Code       |
                                            +---------------------------+
                                            |  Select an editor...      |
                                            +---------------------------+
```

It seems to also make sense to have a keyboard shortcut for opening in your default editor. My next step will be to create a space in the preferences for setting this and a preferred shell option (as being discussed in https://github.com/desktop/desktop/issues/888)

**Comment by joshaber** [comment]
👍 💯 

Do we anticipate users switching between Atom and VS Code a lot?

**Comment by donokuda** [comment]
> Do we anticipate users switching between Atom and VS Code a lot?

I don't think so. I think one editor would always be preferred over the other. 🤔 Given that, I'm not sure if it makes sense to show both...

**Comment by joshaber** [comment]
Yeah, that's what I wondered too, so I thought maybe I misunderstood the diagram.

**Comment by donokuda** [comment]
I'll rework my ascii modern art.

**Comment by rlabrecque** [comment]
I can't think of a reason that wouldn't be handled better in different ways. For example opening in Beyond Compare or some other diff tool might be common, but there's different context available for that.

It's pretty much something you set once and never change.

(That ASCII art is fantastic though.)

If the default editor is unset you could have:
```
Repository -> Open in...
```
Which would just open the preferences to that section, once it's set change that to:
```
Repository -> Open in <Selected Editor>
```

**Comment by xt0rted** [comment]
My editors/process is pretty much set with Beyond Compare, VS Code, and Visual Studio. The only thing I'd really need to change is the path/version which sometimes does change (BC3 -> BC4 was a path change of `C:\Program Files\Beyond Compare 3` to `C:\Program Files\Beyond Compare 4` for instance). The proposed functionality by @rlabrecque seems perfect for this.

**Comment by rlabrecque** [comment]
Yeah, but for something like beyond compare, you typically want to do things like... "Compare with previous version" or, "Diff against <branch>", which is a little different than this. You probably never want to just do "Open in Beyond Compare" which would only give you half of what you want in that case. The flow of selecting the application should be similar though.

**Comment by xt0rted** [comment]
My comments were more about how for me it's a set once and not think about it until it randomly stops working one day feature. But yea, diffing is a different beast than opening for editing.

**Comment by donokuda** [comment]
@rlabrecque That's a good point and would simplify the menu a bit too!

@desktop/core Do we want to support certain editors out of the box? If so, it seems to make sense to go with a nested menu approach. If not, I'm in favor of what @rlabrecque proposed.

**Comment by rlabrecque** [comment]
I'd recommend pushing Atom out of the box, but through the preferences dialog. Something like:

Initial state with no editor set, if atom is installed:
```
|-----------------------------------------------------------------------|
|  > External Editor to open repositories with:                                 |
|       Currently selected editor: None                                               |
|       [Set to Atom] [Browse] [Unset]                                                |
|-----------------------------------------------------------------------|
```
Initial state with no editor set, if atom is not installed:
```
|-----------------------------------------------------------------------|
|  > External Editor to open repositories with:                                 |
|       [ We recommend Atom, you can get it from <here>!      [x] ] |
|       Currently selected editor: None                                               |
|       [Browse] [Unset]                                                                      |
|-----------------------------------------------------------------------|
```

With an editor set:
```
|-----------------------------------------------------------------------|
|  > External Editor to open repositories with:                                 |
|       Currently selected editor: (Editors Icon) Editor's name           |
|       Command line options (?): "%1"                                              |
|       [Set to Atom] [Browse] [Unset]                                                |
|-----------------------------------------------------------------------|
```
If you hover over (?) it should tell you what special values you can pass. %1 being the repos folder. Some editors might need to do something like "--OpenDirAsProject %1"
Editor's name could be the full path, or you could have the path in the tooltip.

Then down the road if you guys wanted to support other editors natively just change Set To Atom into some sort of list/selection dialog in a "Select your preferred editor, or browse if it's not supported by default" sort of experience. The big problem with doing something like this is just checking if arbitrary editors are installed, and where they are installed to. You end up with things like... https://github.com/Microsoft/vswhere which.... 🙃

**Comment by shimpossible** [comment]
I'd think its better to allow multiple editor choices at once.  Instead of limiting to just a single editor.  Yes Atom and Code are basically the same editor, but there are others that can open at a directory level.

Also different repos may want to use different editors.  Either save the configuration per repo, or allow multiple in the app and let the user decide.

**Comment by j-f1** [comment]
What about using `.git/config` to store the settings?

**Comment by shimpossible** [comment]
if you support multiple editors in the ui you don't need to store per repo.    You only need to store in .git/config if you  only support a single editor

**Comment by joshaber** [comment]
I think we need to be careful not to scope creep this to death 💀 This particular issue is for the scope we plan to tackle for 1.0.

While it's true that different repositories might need different editors, for 1.0, we're planning to support choosing only one editor for all "Open Repository in Editor" actions. In the future we can come back to the idea of configuring an editor per repository.

>Do we want to support certain editors out of the box?

I imagine if we limit it to a whitelist, we're gonna have users who are upset their favorite editor isn't an option. I'm not sure what the experience is like on Windows from a technical perspective, but on Mac at least we should be able to let the user choose any application they have installed.

**Comment by rlabrecque** [comment]
Yeah, on that page too ^, some 90%+ of users would only ever be using 1 editor universally, lets get the common case going first. Once the foundation is set then it can be expanded from there.

> I imagine if we limit it to a whitelist

I wouldn't recommend whitelisting, but providing default options to pick from /may/ be nice. I think that's where @donokuda was going with that too.
Regardless, you definitely will want to be able to browse for arbitrary on Windows as well.

**Comment by shiftkey** [comment]
Hey all,

Looking at that last comment in https://github.com/desktop/desktop/pull/2039#issuecomment-318926663, it feels like we've not been clear enough with the scope of work here, so I'd like to apologise about not being more hands-on with guidance as that PR progressed, and take a bit here to clarify things before we go further.

## The Original Implementation

We want to make it easy for people to open a repository in their preferred editor. For the classic apps, the macOS version supported opening in Atom, and the Windows app was a bit smarter - it supported Atom too, but also Visual Studio (if you had it installed, and were in a repository with a `.sln` file).

## What We Want To Avoid

The most important thing I want to call out here is that we don't want to go and overengineer something that may not fit the original problem. Let's keep this feature focused, and get it polished and out sooner so we can get feedback and refine it quicker.

We also want to keep in mind users migrating from the existing apps, which is why this is in scope for 1.0. The biggest bit of feedback we had from users of this feature over there was the lack of support their favourite editor (VS Code and Sublime were the most common request). So let's be mindful to keep the feature similar to the existing implementations, and not go overboard.

For things like opening files based on their file extension, we should be deferring to Electron and the file associations configured by the user at the OS level. And if there are problems with that approach, we should go and fix them in Electron so that everyone gets the benefits, not just us.

## 1.0 Scope

With all that out of the way, let's revisit what we've discussed above. As it's been a bit chaotic, I'm going to try and narrow the scope to just enough for the 1.0 release. Apologies if your thing doesn't make it in now, but we need to ship something and not hold up 1.0:

 - **The Feature**: the experience of opening the repository folder outside Desktop
    - file associations should leverage the OS settings.
 - **Editor selection**: let's whitelist a number of editors for the 1.0 scope
    - Atom, VSCode and Sublime, as they're cross-platform and have significant adoption.
    - we can revisit launching arbitrary programs later, based on feedback and aligning with other features.
 - **Preferences dialog**: change the editor you want here (from the Advanced tab?)
 - **Repository menu item**: it's not clear where we ended up on this. There was talk [here](https://github.com/desktop/desktop/issues/2009#issuecomment-318216985) of letting you select the editor in this menu, but I think we can get away with just "Open in XXX" (where XXX is the selected program) and choosing a default editor for the user after updating. If they want to change this, they can get to it under Preferences/Options. @donokuda are we cool?
 -  **Missing Tools:** @rlabreque suggested things for when tools aren't installed [here](https://github.com/desktop/desktop/issues/2009#issuecomment-318510012). I'm neutral on this, but we didn't do much here for the classic apps and I think we should keep whatever we settle on simple for 1.0.

**Comment by rlabrecque** [comment]
Whitelisting is probably harder than selecting an arbitrary program, and slightly less useful in my opinion.

Then the 'whitelisted' editors can just be the the default options for those editors. You still need to do the work to see if they are installed, because you need to figure out where they are installed. (Which is why I was recommending just Atom as the only 'preset' in 1.0.) I'm not sure how much easier this is on OSX, but it's non trivial on Windows :(

In the end all that needs to be stored in the config either way is:
```
DefaultExternalEditor="/path/to/external/editor"
DefaultExternalEditorArgs="%1"
```

**Comment by adamreisnz** [comment]
This is one of my most used features of the old app, so I'm glad to see it coming back.

My only worry after reading the above scope, and looking at the design of the new app, is how to open the current repository in your editor. I wouldn't want to have to click on the repo name, then find the same repo in the list of repos before being able to open it in an editor.

So maybe a right click on the top left located current repo block could also provide the option to `Open in XXXX`

**Comment by shimpossible** [comment]
I've code that will find where the app is installed for osx.  You first find the default handler for an extension and then you find the location of the app.  It's possible in Windows but a little more complicated

**Comment by joshaber** [comment]
@adamreisnz Would a keyboard shortcut alleviate those concerns?

**Comment by adamreisnz** [comment]
@joshaber a keyboard shortcut would be useful. Even just adding it in the Repository menu would help then we can assign our own shortcuts as well if needed;

![image](https://user-images.githubusercontent.com/490562/29041651-cb3d5594-7c07-11e7-8c44-5290bd6c65d1.png)

**Comment by rlabrecque** [comment]
I think that's on the list under as "Repository menu item"

**Comment by joshaber** [comment]
Yup, I think it should definitely have a shortcut 👍

**Comment by shiftkey** [comment]
For reference, #2407 covers both scenarios:

<img width="331" src="https://user-images.githubusercontent.com/359239/29045924-a4d4e858-7c08-11e7-8266-91c50aa74080.png">

<img width="332" src="https://user-images.githubusercontent.com/359239/29045925-a4d8ec28-7c08-11e7-9a1e-bfdab42e088e.png">

**Comment by lewispg228** [comment]
Hi there, I just submitted a feature request that is related to this. I would love your thoughts. If you have a sec, please check it out here:

https://github.com/desktop/desktop/issues/3731

Thanks!

**Comment by gingerbeardman** [comment]
This is closed but the feature is not in the app. What is the status of this? Thanks
