### ISSUE TITLE
Collapsable grouping repository list by organisation

### ISSUE THREAD

**Issue by njbmartin** [desktop/desktop#2037]
### Description

Would be great to organise repositories by their organisation/owner and be able to collapse/expand each group.

I currently have about 35+ repos cloned locally 🙈

**Comment by joshaber** [comment]
Thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I'm going to add the `future-proposal` label to this issue and close it out, so that we don't get overwhelmed with our backlog! We'll revisit these as part of our next planning session.

**Comment by joshaber** [comment]
There are a few pieces to this that I wanna tease apart.

You're absolutely right that this and similar issues have been suggested for years. I remember getting suggestions like this back when we first launched GitHub for Mac over 6 years ago (😱). But a suggestion's age isn't the sole determinant of how it is prioritized. There are a lot of other factors. How many users does it effect? How serious are the problems it is causing/solving? How does it fit the vision for the product? What's the opportunity cost of doing this over another thing? etc.

Our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md) reflects feedback from both the old and new apps. Features likes conflict resolution and CI status have similarly been requested for years.

It's also open to change. Just because something's not on the roadmap now doesn't mean it won't be.

**Comment by adamreisnz** [comment]
> But a suggestion's age isn't the sole determinant of how it is prioritized. There are a lot of other factors. How many users does it effect? How serious are the problems it is causing/solving? How does it fit the vision for the product? What's the opportunity cost of doing this over another thing? etc.

I appreciate that, but 6 years is a long time for a very annoying issue to affect even a relatively smaller group of people. And there is a lot of demand for it, but it's hard to keep track of because the issues that are opened for it seem to keep getting closed:

These are a few I found with a quick search:
- #1533 - grouping repositories by organization
- #2037 - grouping repositories by organization
- #2173 - grouping repositories by organization
- #2324 - grouping repositories by organization
- #264 - grouping repositories by organization

And other organisation related issues:
- #2038 - pin repositories so they appear at the top
- #1598 - custom folders for repositories
- #1929 - support changing description to distinguish between local clones of the same repository

I've looked at the roadmap, but couldn't spot anything on it that has to do with organising or categorising repositories, even though there's so many issues raised about it. It clearly is a pain point for many users.

Can you at least reconsider adding *something* around this feature on the roadmap? Or can we create PR's for it?

**Comment by joshaber** [comment]
We will certainly consider it! We generally plan in 6 month blocks. Since we just had a team meeting about a month ago, our next one will probably be in early 2018.

>Or are you open to PR's for it even if the feature is not on the roadmap?

There's no one-size-fits-all answer for this. It really depends on the exact scope of the feature. Your best bet is to outline exactly what you want to do, start small, and get feedback early and often.

**Comment by njbmartin** [comment]
@joshaber As an open source repo, am I right to assume that if we submit a PR with a useful feature such as this which is not in scope, it will be considered for the next release and not closed due to `out of scope`?

**Comment by joshaber** [comment]
@njbmartin It's hard to say in the abstract. As I said above, your best bet is to outline exactly what you want to do, start small, and get feedback early and often.

**Comment by ruipacheco** [comment]
Is this going somewhere? I really need to organise a large number of repositories and am tired of the errors generated by Source Tree on OSX.

**Comment by joshaber** [comment]
@ruipacheco It's not on our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md), but past 1.2 it's pretty fuzzy.

**Comment by mcfarljw** [comment]
The main reason I want something like this is because lets say I have `organization1/website` and `organization2/website` it makes it more clear when they are grouped by organization. Right now the best way to handle this would is to rename both projects to `organization1/organization1-website` and `organization2/organization2-website` which isn't always an option.

**Comment by adamreisnz** [comment]
Yes I think that's the most common use case. In our case we have separate repositories for client, server, etc. and all of our projects are hence called `foo/client`, `foo/server`, which made them indistinguishable from `bar/client` or `bar/server`. We've also resorted to calling them `foo/foo-client` and `bar/bar-client`.

**Comment by elliotcm** [comment]
My main need for it is one of my clients has over a thousand repositories, so even working on a small fraction will overwhelm the repo listing, and that's just for one client.  Mix in a handful of repos from other clients and it becomes very difficult to navigate.

**Comment by peteamundson** [comment]
We have the same issues with our repos, where we have /[client]/[project]/ and almost all projects are named the same.  Not having a way to organize or create custom displayed names (or maybe even inclusion of the folder structure like GitKraken) itself, makes using this pretty difficult.  We could go through and do a large set of folder renames, but seems like a feature that other tools have (like SourceTree and GitKraken) and many people expect.

**Comment by billygriffin** [comment]
Thanks for the idea! I'm removing `future proposal` in favor of #6460 which tries to capture *all the things*™️ in a more unified way since there have been so many different implementation ideas suggested.

**Comment by UjLion** [comment]
![Annotation 2019-05-02 221401](https://user-images.githubusercontent.com/2406365/57091822-a9b6ea80-6d27-11e9-9f2f-99e58f139fa7.jpg)
It's a nightmare - with local repositories. Please add this feature soon so that sub projects can be organized under a collapsible organization head, which can be manually specified even for local repositories.

**Comment by njbmartin** [comment]
From what I've seen, this functionality is in the beta already. I'm a little confused as to why you have so many duplicate names though...

**Comment by UjLion** [comment]
Oh that's great news! Thanks.
I like to organize the sup-project directories with their generic names under the parent directory with the project title, and I have a structure like this:
ujnotes
	website\project
	website\project\interim
	website\project\framework
wcodes
	website\project
	website\project\interim
	website\project\framework
	android\project
	...

**Comment by billygriffin** [comment]
@UjLion Thanks! As long as these are GitHub repos, I think you should be in good shape with the new direction in #6460 that is currently in beta and should be released to production in about a month. Let us know what you think!

**Comment by UjLion** [comment]
They are but all local only repos :(

**Comment by billygriffin** [comment]
@ujLion Sorry - that's a bummer. It's trickier there and we have no immediate plans to work on that because we haven't seen that people have a ton of local repos that aren't connected to GitHub in any way. However, if we're seeing that as a widespread pain point, we're happy to revisit.

**Comment by ruipacheco** [comment]
This is definitely a pain point to me.

**Comment by ujLion** [comment]
Earlier I would edit the sqlite **cache.db** file at `%LocalAppData%\GitHub\` to override the names. But perhaps now the name is being computed dynamically from the path.

**Comment by ujLion** [comment]
### Workaround:
To override displayed repo names ( to be run in dev-console : [**View\Toggle developer tools**] )

1. `function overrideRepoNames(repoNames) {
	for (x in repoNames) { $x('//*[@id="__ListRow_1-'+(parseInt(x)+1)+'"]/div/div[2]/span/span')[0].innerHTML = repoNames[x] }
}`

2. `overrideRepoNames(['Ujnotes\Website\Framework', 'WCode\Website\Framework', 'WCode\Website\interim', 'WCode\Location\interim', 'Ujnotes\Website\interim', 'WCode\Location\Paper', 'WCode\Website\Project', 'WCode\Android\Project', 'WCode\Windows\Project', 'WCode\Location\Project', 'Ujnotes\Website\\Project'])`

*Note - this is undone when the side navigation pane is redrawn.
-Thus should be hooked to some redraw event or so
