### ISSUE TITLE
Pinned repos!

### ISSUE THREAD

**Issue by njbmartin** [desktop/desktop#2038]
### Description

Much like #2037 for enhanced productivity, the ability to pin repos so they appear at the top of the list for quick and easy access.

**Comment by say25** [comment]
I think given the confusing behind the word star maybe we use pinned?

**Comment by shiftkey** [comment]
Yes, [stars and starring](https://developer.github.com/v3/activity/starring/) are existing concepts on GitHub - probably better to choose a different phrase to avoid confusion here...

**Comment by joshaber** [comment]
Thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I'm going to add the `future-proposal` label to this issue and close it out, so that we don't get overwhelmed with our backlog! We'll revisit these as part of our next planning session.

**Comment by billygriffin** [comment]
Thanks for the idea! I'm removing `future proposal` in favor of #6460 which tries to capture *all the things*™️ in a more unified way since there have been so many different implementation ideas suggested.
