### ISSUE TITLE
inline error messages for dialog require style refresh

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#2052]
Extracted from https://github.com/desktop/desktop/pull/1851#discussion_r122600088

We have an inline error message which is using the current `DialogError` style:

![](https://user-images.githubusercontent.com/1715082/27202529-9991d5aa-51e7-11e7-87b1-72b17d58b99d.png)

We should introduce a new style which looks more like this warning message:

![](https://user-images.githubusercontent.com/359239/27263922-94c64648-5474-11e7-8c48-95ddcf1369cf.png)

**Comment by niik** [comment]
I don't think the problem is the `DialogError` style here, it's that it's not applied correctly. See https://github.com/desktop/desktop/blob/master/docs/technical/dialogs.md#errors

> The DialogError component, if used, must be the first child element of the Dialog itself.

Since this is an error that gets triggered when one hits the `Create Repository` button it should be presented as a `DialogError` attached to the dialog, not an inline style attached to the textbox.

cc @donokuda
