### ISSUE TITLE
Sidebar and don't hide everything in menu?

### ISSUE THREAD

**Issue by danqing** [desktop/desktop#2067]
I'm not sure if there's an existing issue for it (sorry if there is one - kinda hard to search), and I'm not sure if the current design is a conscious choice, but I'd request to have a sidebar and some buttons to quickly access things.

Currently there's no way to clone repo, create branch, etc. unless using the top menu (i.e. not in the UI). The repo and branch dropdown (it'd be great if they can be pinned open, for one) don't allow you to add new repo or branch.

I like the old GitHub for mac a lot, and I'd like to see more frequently-used functionalities surfaced to the main UI.

Thanks!

**Comment by shiftkey** [comment]
@danqing thanks for the feedback! There's a few existing discussions which your feedback touches on, so I'll cross-reference them here.

> Currently there's no way to clone repo, create branch, etc. unless using the top menu (i.e. not in the UI).

There are also keyboard shortcuts for these common tasks which should be familiar:

 - Create New Repository - <kbd>⌘ + N</kbd>
 - Add Local Repository - <kbd>⌘ + O</kbd>
 - Create Branch - <kbd>SHIFT + ⌘ + N</kbd>
 -  and so on

> The repo and branch dropdown (it'd be great if they can be pinned open, for one) don't allow you to add new repo or branch.

The "always shown" repository list discussion is being tracked here #1593 - we wanted to reclaim that real estate, so we moved it into an expander which you can easily switch to using <kbd>⌘ + T</kbd>. I'm not aware of much interest in making the branch selector always shown.

We have a "create branch from the branch selector" discussion tracked here #1575.

The "add repository from UI" scenario is interesting, because it's something we've iterated on a few times - we did have an "Add Repo" menu item in #1018 which also had some earlier redesigns, but then realised it wasn't really providing much that wasn't already available through the menu system or keyboard shortcuts, so it got removed in #1065.

**Comment by danqing** [comment]
Thanks for the summary @shiftkey ! Look forward to how these turn out!

**Comment by shiftkey** [comment]
> It'd be a lot easier to just scroll through the repos and click the one I want. Say the repo is someawesomeorg/backend-python-server, that's a lot of typing and maybe i don't remember the exact name. At least some autocomplete mechanism would be welcomed.

This is being discussed in #57

**Comment by shiftkey** [comment]
> There's currently no button or anything in the UI that allows you to add repo, and I personally don't think putting such important feature in the top menu (or using shortcut) is a great user experience.

We've gone through a lot of change here to end up where we are, and I don't miss the old button, but I'll let the others in @desktop/core chime in on their thoughts on this.

**Comment by joshaber** [comment]
I think we could do to surface more UI affordances, but I'll defer to @niik and @donokuda.

**Comment by j-f1** [comment]
How about something like this?

<img width="254" alt="screen shot 2017-06-26 at 08 38 20" src="https://user-images.githubusercontent.com/25517624/27539535-e5da995e-5a4a-11e7-8d56-2c1f19652c0d.png">

**Comment by danqing** [comment]
@j-f1 I think that's totally great. (and also add the new branch button to the branch dropdown as I think someone has posted in another issue)

**Comment by joshaber** [comment]
I think between https://github.com/desktop/desktop/issues/1595 and https://github.com/desktop/desktop/issues/1593, we have all this captured.
