### ISSUE TITLE
Truncate long branch names in Merge Branch dialog

### ISSUE THREAD

**Issue by iAmWillShepherd** [desktop/desktop#2077]
Up date the footer to truncate long branch names instead of displaying nothing to merge.

For context see this [PR](https://github.com/desktop/desktop/pull/2047), this [comment](https://github.com/desktop/desktop/pull/2047#issuecomment-309307343)  describing the problem, and the [preferred way to fix it](https://github.com/desktop/desktop/pull/2047#issuecomment-309831653).

**Comment by deyton** [comment]
After looking at this a little longer, to me, it seems better to move onto the next line vs. truncating with an ellipsis. I think we have enough space there in the footer to go multi-line. I'm not very familiar with other dialogs so maybe this doesn't make sense with the broader style in the app, though.

<img width="481" alt="screen shot 2018-06-27 at 2 31 01 pm" src="https://user-images.githubusercontent.com/495258/41995385-24220a66-7a17-11e8-8eb7-ab1d9b299996.png">

**Comment by shiftkey** [comment]
@deyton 

> I think we have enough space there in the footer to go multi-line. 

Agreed. This will make it consistent with our Compare dialog

<img width="367" src="https://user-images.githubusercontent.com/359239/41996657-fc2a4536-7a2b-11e8-9296-d5261d8fca98.png">

**Comment by deyton** [comment]
@shiftkey 

I made a simple fix by removing `@include ellipsis`, but now I think a better fix might be to exactly match that section in the compare sidebar, perhaps by reusing the MergeCallToAction component. I was able to get it mostly working and it feels like the “right” thing to do. Do you think that change would be worth it?

I have a bit of a conflict of interest because I’m trying to learn more about the codebase so I’m abnormally inclined toward making bigger changes right now 😜.

**Comment by shiftkey** [comment]
@deyton if you think the fix is all that's needed, feel free to submit a PR with screenshots to compare the change :metal:

**Comment by tierninho** [comment]
As the PR in the original comment is merged and we have updated the Merge modal significantly since 2017, I believe this issue can be closed.

Current view:
<img width="450" alt="screen shot 2018-11-07 at 10 41 52 am" src="https://user-images.githubusercontent.com/14828183/48152978-0b673200-e27a-11e8-9d5f-0473f4e448aa.png">
