### ISSUE TITLE
Allow to clone via SSH

### ISSUE THREAD

**Issue by Eldorado234** [desktop/desktop#2085]
### Description

When cloning via Desktop the remote origin is set to the `https` URL. Since I always use SSH when working on the terminal, I have to change the remote which is really annoying. It would be nice to have a setting where the user can decide if new repos should be cloned via `https` or `ssh`.

### Version

**GitHub Desktop version:** 0.6.1
**OS version:** macOS Sierra 10.12.5 (16F73)

**Comment by joshaber** [comment]
Thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

You can setup an `insteadOf` config to change URLs universally if you like: https://stackoverflow.com/questions/1722807/git-convert-git-urls-to-http-urls

I'm going to add the `future-proposal` label to this issue and close it out, so that we don't get overwhelmed with our backlog! We'll revisit these as part of our next planning session.

**Comment by foresmac** [comment]
Please let me leave a _strong_ +1 on this feature request. I got frustrated with this a lot recently since we're doing like a dozen new projects at the office. Even after manually selecting the ssh ref and pasting that into the clone repository dialog, Github Desktop rewrites them to use the HTTPS URLs.

**Comment by mauriziod** [comment]
Love to see this request moving forward, I feel the pain changing all cloned repos from HTTPS.

**Comment by cmeyertons** [comment]
Expanding on @joshaber 's comment, the workaround can be performed with 

`git config --global url."git@github.com:".insteadOf https://github.com/`

**Comment by foresmac** [comment]
It was easier to just stop using GitHub Desktop altogether, frankly.

**Comment by billygriffin** [comment]
Hi folks - we updated the open issue for this (#2579) to link back to this issue. Since it's already open and provides a bit more info on the overall surface area of the issues, I'm going to remove future proposal here. It's definitely something we're interested in, and we're weighing it against our other priorities to determine when we're able to work on it. Thanks for all the feedback!

**Comment by WaleedAshraf** [comment]
Any update on this?

**Comment by brokenthorn** [comment]
Like @billygriffin said, since this has been closed and a lot more has been added at the newer #2579, #2579 is where you should be heading at.

**Comment by oskarlakner** [comment]
Sorry guys but it's ridiculous that in 2020 it's still impossible to clone via SSH... 🤦‍♂️

**Comment by abdulrauf11** [comment]
Wow! is there still no solution for this?

**Comment by gurpreet-ounce** [comment]
Could you please provide the steps to how to clone via SSH in github desktop?

**Comment by WaleedAshraf** [comment]
I run this script in my main folder, where I have all the repo clones from one org. It'll update all remote URL to SSH.

```bash
for d in */; do
    cd "$d"
    echo ${PWD##*/}
    remote="git@github.com:<YOUR-GITHUB-ORG-NAME>/${PWD##*/}.git"
    echo "${remote}"
    git remote set-url origin $remote
    cd ..
done
```

**Comment by rakesh-ounce** [comment]
Hi Team,

We are not able to clone using SSH. It would be better if you could please add this feature or can let us know the steps to be used for cloning via SSH URL

**Comment by fatbasstard** [comment]
Still not possible to do the clone command with ssh... 

Isn't it an option to make it an application setting?

![image](https://user-images.githubusercontent.com/35613489/109952094-bff4af80-7cde-11eb-88e8-7387955e3e7f.png)

Mainly talking about this option, who not make the clone method a simple option?

**Comment by kennu** [comment]
I also need this for Desktop and CLI interoperability. CLI repositories are cloned with ssh and they don't work in GitHub Desktop.  GitHub Desktop repositories are cloned with https and they don't work on the CLI.

**Comment by alexanderilyin** [comment]
@shiftkey what's the timeline for implementation?

**Comment by andreaswilli** [comment]
I was very surprised to learn this feature is not supported, especially considering you recently started working on advanced features like cherry picking. Would love to see SSH cloning!

**Comment by jseaber** [comment]
SSH should be the default for Desktop, especially as HTTPS is no longer supported from the command line.

**Comment by cossio** [comment]
It's a bit confusing following the status of all these issues. It seems #2579 was closed, however I just installed Github Desktop and it by default clones my repos with the HTTPS url, instead of using SSH. And I can't find any setting to make it use SSH by default instead of HTTPS.

Can someone comment on the current status of this feature?

**Comment by steveward** [comment]
@cossio it isn't possible to set the default option to SSH in GitHub Desktop. The work that was done improved overall SSH support, but you still need to clone a repository via SSH by using the `URL` option in the clone dialog. I hope that helps.

**Comment by cossio** [comment]
@steveward Thank you, I understand.

Are there plans to allow setting SSH as default?

**Comment by marcospgp** [comment]
Would be great to have this, currently I have to clone by URL and use the SSH URL, but it would be easier to search for the repo inside GitHub Desktop itself.

**Comment by badigit** [comment]
need this feature

**Comment by amrelsadany** [comment]
it's 2025 and still not implemented :/ 
is it hard for you guys to implement such a feature !!

**Comment by abhishek-ew** [comment]
nvm back to uninstalling :3
