### ISSUE TITLE
Additional Check to delete repo from disk while removing repo

### ISSUE THREAD

**Issue by Sibiraj-S** [desktop/desktop#2108]
### Description

Additional Checkbox can be provided while removing a repo. Asking the user to check/uncheck `Delete permanently from disk`

### Version

**GitHub Desktop version:**  0.6.2

**OS version:**  MacOS Sierra

**Expected behaviour:** 

Provide additional checkbox allowing the user to permanently delete the repo from disk.
This will be unchecked by default.
If the user checks the checkbox before removing the repo can be deleted permanently from the disk.

**Actual behaviour:** 

Removing a repository removes only from GitHub desktop. Each time to delete, the user has to navigate and delete that manually.

**Comment by j-f1** [comment]
This could also have a less-threatening message if there are no changed files and all of the commits have been pushed to `origin` on all branches.

**Comment by Sibiraj-S** [comment]
It is totally upto users opinion. `If he doesn't want the repo at all / he might decide to clone later`. an extra checkbox will be there enabling to delete the reop totally from disk before removing from GitHub desktop. that's it

Something like this (example)

![untitled](https://user-images.githubusercontent.com/20282546/27516673-2105f48e-59dc-11e7-8a06-a1f8bcf3e004.png)

**Comment by j-f1** [comment]
@Sibiraj-S Why did you close this issue? It hasn’t been fixed yet.

**Comment by Sibiraj-S** [comment]
Sorry I was closing many of issues that was open for a long time and not answered. I was not aware when I closed this one 😕. Reopening this.

**Comment by gingerbeardman** [comment]
I don’t mind this being a preference, if there’s a modifier key to go along with it. That’s because it’s something I will need to decide many times, so I would not want it to be permanently one or the other. I’d like to choose just before I do the task.

Right click = `Remove`
Right click + <kbd>Alt</kbd> = `Remove and Move to Trash`

On macOS it’s common to hold down <kbd>Alt</kbd> to get alternate versions of some menu commands. Example:

regular:
![screen shot 2018-03-15 at 22 10 38](https://user-images.githubusercontent.com/49612/37493889-71faf09c-289e-11e8-9164-9629a4d9edcf.png)

alt:
![untitled](https://user-images.githubusercontent.com/49612/37493904-848007de-289e-11e8-80c0-d7400b8654d5.png)
