### ISSUE TITLE
git flow support

### ISSUE THREAD

**Issue by DerKnerd** [desktop/desktop#2139]
Hello Desktopteam,

it would be cool if you could integrate git flow. Currently we are using SourceTree but if Github Desktop supports git flow we could think about switching the system.

Greetings
Imanuel

**Comment by joshaber** [comment]
Thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I'm going to add the `future-proposal` label to this issue and close it out, so that we don't get overwhelmed with our backlog! We'll revisit these as part of our next planning session.

**Comment by billygriffin** [comment]
@pvspain Thanks for the friendly ping here. In #5398 we’re going through a more organized evaluation of our product goals and priorities. This is one of the things we’ll be evaluating. And while I know patience is a tough ask, we should have a clearer sense of what we’ll be doing and why in the next couple months, and hopefully begin to develop ways for our community to participate more in the process of making GitHub Desktop an even better product for more people.

**Comment by rasmuseeg** [comment]
We are currently using SourceTree, but their client has it's issue. We would like to adopt GitHub Desktop, but it's lacking git flow support.

**Comment by JulianGuppy** [comment]
I too would like to see gitflow in github desktop, please consider adding this. I (and my team) are using gitflow and we find it works well. I would be reluctant to move them to this without gitflow support baked in

**Comment by pokono** [comment]
+1

**Comment by AlexParfyonov** [comment]
www1

**Comment by zhushaojun65** [comment]
+1

**Comment by montypanday** [comment]
+1 on this. Would be extremely beneficial. I am switching between github desktop and Sourcetree a lot for this.

**Comment by Camisoft** [comment]
+1

**Comment by VictorioBerra** [comment]
+1

**Comment by agorskih** [comment]
+1

**Comment by whoisalive** [comment]
+1

**Comment by CraigHutchinson** [comment]
+1

**Comment by matteobissoli** [comment]
+1

**Comment by s0nqr3** [comment]
Hi desktopteam!

As this marks the feature requests ~2,16th year anniversary, I think it might be time to air some updates around the issue.

Are the any plans for the immediate future to support git flow in GitHub Desktop?

**Just Imagine the headlines:**
- Theres a new king in town: GitHub Desktop!
- Exclusive interview with Anonymous Atlassian employee; 
  I use GitHub Desktop to manage the SourceTree project
- Atlassian shuts down ScourceTree; 
  We really though a UI design from the 90's would be great 😢 

..well you get the point 👍 

Regards
Sondre

**Comment by ScruffyHipster** [comment]
+1 on this. The client is great and will only benefit from GitFlow support.

**Comment by tommaineult** [comment]
+1 More than on year asking for this major feature and already asking guys! 👍  Please hear us 🙏

**Comment by MartinBecker** [comment]
+1 We need this Feature

**Comment by theoriginalmarc** [comment]
+1 This is a needed feature.

**Comment by mislav** [comment]
Thank you all for expressing your needs for this feature. It sounds like adding this functionality would certainly help the adoption of GitHub Desktop by certain teams.

This issue has been closed and remains closed because we are no more able to fit this on [our roadmap](https://github.com/desktop/desktop/blob/development/docs/process/roadmap.md) than we were 2 years ago. To provide a bit more context around why, I thought that it might be helpful to first try define the parameters of this feature.

"Gitflow" is two things: it is a [specific branching workflow](https://nvie.com/posts/a-successful-git-branching-model/) that facilitates a software development & release process, and it is a [reference implementation](https://github.com/nvie/gitflow) of that workflow in bash.

GitHub Desktop already supports branching and merging, which makes following the gitflow set of conventions possible, although potentially more cumbersome. When people ask for "git flow support" in Desktop, I assume that the request is that Desktop implements graphical UI features that facilitate starting & stopping of "features", "releases", and "hotfixes" (as per gitflow nomenclature), and that those operations result in underlying git branches of a specific naming convention being created or merged.

Considering that this feature entails that there would also be a UI that helps users set up the repo with git flow and configure the naming conventions for different kind of branches, the scope of implementing and maintaining all this additional functionality within Desktop is not something that the core team is able to take on right now. Even with the graphical UI out of the way, there would still be an engineering overhead in either re-implementing all of gitflow branching operations in Node.js, or around figuring out how to bundle an [existing implementation](https://github.com/petervanderdoes/gitflow-avh) and make sure that the bash scripts run reliably across platforms. (The latter would technically be possible but not straightforward on Windows.)

Finally, even with tehnical aspects of all this brushed aside, the functionality described by gitflow doesn't match our priorities for the set of features we are aiming to implement in Desktop at this moment.

Anyway, I hope this explains our rationale a little bit. Thank you for reading! If you are interested in voting up this or any other feature request, please consider adding :+1: reactions to any of the comments in this thread instead of posting "+1" comments. This helps lower the volume of notifications for this repository.

**Comment by cata0309** [comment]
+1

**Comment by manuelgegenhuber** [comment]
+1

**Comment by BenDavidson90** [comment]
I just downloaded the GitHub Desktop application, at first it seemed like a good application to me except that I couldn't find a way to activate Git Flow.

I was surprised (in the wrong way) when I arrived here to see that Git Flow is still not implemented and that it is not planned.

I find it shameful that a company like GitHub, which now belongs to Microsoft, does not have a team that is "capable of taking on" the development of this functionality while other software such as Atlassian's SourceTree or the small Fournova Software team's Tower does.

So I go back to SourceTree which integrates Git Flow which is now an essential tool. And why not go back to GitLab too.

**Comment by prasob-ef** [comment]
+1

**Comment by ErnestTapias** [comment]
We want git-flow in GitHub Desktop. And a Graph too see merges and branches.

**Comment by mishat-realityi** [comment]
> I just downloaded the GitHub Desktop application, at first it seemed like a good application to me except that I couldn't find a way to activate Git Flow.
> 
> I was surprised (in the wrong way) when I arrived here to see that Git Flow is still not implemented and that it is not planned.
> 
> I find it shameful that a company like GitHub, which now belongs to Microsoft, does not have a team that is "capable of taking on" the development of this functionality while other software such as Atlassian's SourceTree or the small Fournova Software team's Tower does.
> 
> So I go back to SourceTree which integrates Git Flow which is now an essential tool. And why not go back to GitLab too.

WHY THIS COMMENT WAS  MARKED AS OFF-TOPIC. The author is absolutely  right.

**Comment by ErnestTapias** [comment]
> 
> 
> > I just downloaded the GitHub Desktop application, at first it seemed like a good application to me except that I couldn't find a way to activate Git Flow.
> > I was surprised (in the wrong way) when I arrived here to see that Git Flow is still not implemented and that it is not planned.
> > I find it shameful that a company like GitHub, which now belongs to Microsoft, does not have a team that is "capable of taking on" the development of this functionality while other software such as Atlassian's SourceTree or the small Fournova Software team's Tower does.
> > So I go back to SourceTree which integrates Git Flow which is now an essential tool. And why not go back to GitLab too.
> 
> WHY THIS COMMENT WAS MARKED AS OFF-TOPIC. The author is absolutely right.

You are right sir!

**Comment by outofambit** [comment]
https://github.com/desktop/desktop/issues/2139#issuecomment-540180110 was hidden and marked off-topic because the message is abusive and doesn’t offer any insight into why the feature is important to people.

**Comment by ErnestTapias** [comment]
WTF this is north Korea or What?

**Comment by erkkon** [comment]
My comment was minimized and I don't know why I just said this: 
We want git-flow in GitHub Desktop. And a Graph too see merges and branches.
I think that GitHub Desktop is the future of Git client is opensource and made by electron JS like VS Code that it's amazing.
