### ISSUE TITLE
"Keep this code private" is ticked by default even when a user is on a free plan

### ISSUE THREAD

**Issue by chriscn** [desktop/desktop#2165]
### Description

When pushing a repo to GitHub the keep this code private is ticked by default. Most people have public plans so either stop this from being ticked on default or provide an option in the settings.

### Version

**GitHub Desktop version:** 0.6.2

**OS version:** Mac OS X Sierra

**Reproduces how often:** 100%

**Comment by joshaber** [comment]
Right, we _should_ default to private if the user's on a paid plan because we don't want them to accidentally leak code. But for users on free plans, we shouldn't give them a choice.

**Comment by joshaber** [comment]
@chriscn mind if we re-open this? I think it's a legitimate issue 😄

**Comment by chriscn** [comment]
@joshaber Sure, don't see emails of the github chain. I thought we were finished 👍

**Comment by OiYouYeahYou** [comment]
# Preamble

I am assuming:
  1. An unpaid account can publish a private repo to a paid organisation (Given permissions)
  2. A paid account cannot publish a private repo to an unpaid organisation

Therefore, it is necessary to know if a `publishing target` is paid, not just the user account. Extending the user account class is easy. But for organisations, this is a different matter. As currently, the `user/orgs` endpoint does not include the plan object according to the Github API. Meaning that if a Target Based behaviour is used, the `orgs/:org` enpoint needs to be called somewhere, either:

1. At the initial `user/orgs` call, `orgs/:org` is called for each. 
1. Or when an org is selected in the publish dialog a single `orgs/:org` call is made.

## Behaviors

**Existing:-** Privacy always defaults to true and enabled, and is not altered when switching orgs

**Suggested:-** When User is unpaid: Set to false and disable

**Target Based:-** When publisihng target is unpaid: set to false and disable

**Middle of the road:-**

1. When the user is selected: 
    1. If unpaid: set false and disable
    1. If paid: set true and enabled
1. If Org is selected: default to true and enabled, blind of org payment plan

**User controlled default preference:-** Setting in options that dictates whether the initial state of the publish dialog is public/private

## Example usage: Target-Based

1. User (Paid or Unpaid) opens publish repo
1. Selects paid org
1. Toggles privacy off
1. Selects unpaid org, *Private option is set to false and disabled*
1. Selects paid org

When this happens, should user selection be remembered? Or, should the dialog always default to private when a paid target is selected?

# After trying

Aiming at adding a *target based behaviour*, the lack of plan data in the `user/orgs` endpoint stopped me. I am concerned about adding extra and excessive API calls just to add this feature. So I tried the *Middle of the road behaviour*, but disliked this behaviour because it was inconsistent.

I tried default preference in options, which I came to prefer for its simplicity. So users who don't use private repos can have false as default, to save the faff when publishing a repo for the first time.

**Comment by shiftkey** [comment]
@niik were you still working on this?

**Comment by niik** [comment]
> @niik were you still working on this?

@shiftkey Sorry, I missed this during the holidays. No, I started but never finished, removing my assignment.

**Comment by shiftkey** [comment]
@damaneice yeah, this would be a nice one to solve.

I think the notes from @OiYouYeahYou in https://github.com/desktop/desktop/issues/2165#issuecomment-340514024 are a more complete list of the desired behaviour than "user on free plan cannot create private repository", but there might be some more organisation permissions that we need to look at through the API.

**Comment by shiftkey** [comment]
Just bumping this issue to point to a branch that @damaneice and I were pairing on on Friday that makes some progress to address this https://github.com/desktop/desktop/compare/publish-api-should-care-about-free-plans - I don't have the bandwidth to push this on, so I'm going to leave it for someone else who cares about it to continue figuring this out.

**Comment by billygriffin** [comment]
@shiftkey @damaneice What's the current behavior? The box is checked as private, but does it do the right thing and push it public if it's in an unpaid org? Obviously it doesn't align with what the verbiage says, but just wanted to verify that it does actually push and the repo is public.

**Comment by shiftkey** [comment]
@billygriffin I think the server returns an error about upgrading your plan, which we display inline in the publish box

**Comment by billygriffin** [comment]
Oh! Got it, so I get an error that basically says I can't publish private unless I upgrade my plan. Then I uncheck the box and push again? This is annoying, but not catastrophic which is good to hear. 😄

**Comment by chriscn** [comment]
What would be awesome to implement is to use the api to see if the user or any of the organisations the user is part of has paid plans and then if they don't disable the checkbox entirely with a nice hover message: "Neither you or any organisations have any private repos so we have disabled it" and then automatically check the public one because that will be the only one available.

**Comment by shiftkey** [comment]
@chriscn I'd prefer to flip these inputs around because the checkbox is now dependent on what organization you've chosen

<img width="495"  src="https://user-images.githubusercontent.com/359239/43211322-a44351cc-9007-11e8-8c75-372ef417be29.png">

This means the flow becomes:

 - select the organization to target (or skip over it)
 - see the checkbox is either disabled (unable to create private repository) with a helpful message (inline/tooltip/whatever) or enabled (and default to private as usual)
 - if user is not sure, they can try a different organization 
 - if user is really not sure, they can navigate to an external link in the app to understand more about the issue (where to find this?) 
 - otherwise they can continue on to publish the repository with whatever state the checkbox is in

**Comment by billygriffin** [comment]
The only thing that I think is missing above is, via @iAmWillShepherd, we should give the user a nice way to go and upgrade directly on the site if the "Keep code private" isn't available to them. A link with something like, "Upgrade your plan to publish private repos" or something would be great. Let's just not make them search for it.

**Comment by shiftkey** [comment]
@damaneice that works

**Comment by tierninho** [comment]
For any open-source contributor looking to work on this, here is a good place to start:

https://github.com/desktop/desktop/blob/master/app/src/ui/publish-repository/publish-repository.tsx

Please reach out to the team with any questions. Thanks!

**Comment by shiftkey** [comment]
Just bumping this issue with the news that ["GitHub Free" accounts are able to create unlimited private repositories](https://blog.github.com/2019-01-07-new-year-new-github/). There's some limitations around the available features and number of collaborators that can be added to these repositories, but this means we might need to review this feature and identify what changes (if any) need to happen.

@niik also raised some concerns about the logic for checking in https://github.com/desktop/desktop/pull/5273#pullrequestreview-155419553 which we should consider - it talks about users needing to upgrade their plan, which isn't a thing they'll need to do when publishing now on free plans - but mentions interactions and things to be mindful of around this area.

**Comment by chriscn** [comment]
Was about to come here and say this. In my opinion it should default to private to begin with.

**Comment by shiftkey** [comment]
@chriscn that's the initial behaviour, which now aligns nicely with the GitHub Free changes. Maybe this makes it a non-issue now? Let's hold off on closing this until we've had a chance to review things (the issue was from 18 months ago).

**Comment by chriscn** [comment]
Someone could have realistically had two kids in the time between this being opened and now 😛Thank you for all your work on this.

**Comment by billygriffin** [comment]
Hi folks! We ran through a few scenarios internally and it looks like this issue is no longer relevant because of free private repos. The primary differentiator at the repo level is that free private repos cannot have more than 3 collaborators. Because this is never an issue before a repo is published to GitHub, we don't need to be concerned with that here.

The only place where this can go awry is when you're trying to publish a private repo to a free org. In this case, however, you'll get an error message and it won't let you publish, which seems reasonable.

We're happy to revisit if there are flows that make this fall down in the app, but for now we're going to close this issue. Thanks @damaneice and others who have weighed in!
