### ISSUE TITLE
Group by Organization 

### ISSUE THREAD

**Issue by blacktop** [desktop/desktop#2173]
It would be cool to be able to group by orgs, because I have a LOT of repos and now it is overwhelming to find the one I want to work on today.

If you could have groups it would be easier to down filter.

Thanks!

**Comment by niik** [comment]
Hi @blacktop, thanks for opening this issue. We've seen this request and similar ones before (see https://github.com/desktop/desktop/issues/1598) and we are aware of it. We think it's an interesting area to explore in the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

Our approach to issues that are beyond our current scope right now is to add the future-proposal label and close it out, so that we don't get overwhelmed with our backlog and then revisit these as part of our next planning session. As I believe #1598 captures the underlying problem of wanting more ways to organize repositories I'm going to let that issue be the overarching issue covering repo organization with this issue being cross-referenced.
