### ISSUE TITLE
Filter/search "Changes"

### ISSUE THREAD

**Issue by mmunchandersen** [desktop/desktop#2183]
It would be great if there was a way to live filter the "Changes" file list on path.
Something like having a filter textbox at just below the "x changed files" that would live-filter the file list using literal text or regular expression searching the entire file path.

**Comment by niik** [comment]
Thanks for the suggestion @mmunchandersen!

This idea is definitely of interest to us for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I'm going to add the future-proposal label to this issue and close it out, so that we don't get overwhelmed with our backlog! We'll revisit these as part of our next planning session.

**Comment by j-f1** [comment]
@niik I could split up #2046 to address this if you think it’s a good solution.

**Comment by Zaelot** [comment]
I'd also like to add a request for the ability to sort the files in **Changes** by _File Type_ as well as the _Type of Change_ (and possibly by date too).
(Later that would probably be handy for the **History** too.)

**Comment by billygriffin** [comment]
Thanks for the issue @mmunchandersen! Since a new issue on this same topic is a bit more fleshed out in terms of the problem it's solving and thinking around potential solutions, I'm going to remove `future proposal` here and we'll track this in #6407. Thanks again!
