### ISSUE TITLE
"Push origin" pushes to the remote master branch

### ISSUE THREAD

**Issue by hubgit** [desktop/desktop#2188]
### Description

After branching off `origin/master` and committing some changes to the new branch, "Push origin" pushes the commits to the remote master branch, instead of just pushing the current branch to a remote branch with the same name (as `git push` would do).

### Version

**GitHub Desktop version:** 0.6.2

**OS version:** macOS 10.12.5

### Steps to Reproduce

1. `git checkout -b test-push origin/master`
1. `echo 'test' > test.txt`
1. `git add test.txt`
1. `git commit -m "testing"`
1. In GitHub Desktop, check that "test-push" is showing as the Current Branch.
1. In GitHub Desktop, click "Push origin".

**Expected behavior:**

The current branch should be pushed to the remote repository, as if I'd run `git push`.

**Actual behavior:**

`! [remote rejected] test-push -> master (pre-receive hook declined)` - luckily the remote master branch is protected, otherwise it would've been updated!

### Logs

Here's the relevant line from the logs:

`info: [ui] Executing push: git -c credential.helper= push origin test-push:master --progress`

### Additional information

In `~/.gitconfig` I have the following:

```
[push]
        default = current
```

GitHub Desktop seems to be acting as if this is set to "upstream" rather than "current"?

**Comment by niik** [comment]
When you checkout a branch using a remote branch as the starting point Git will set that remote branch up as the tracking branch

```
$ git checkout -b test-local origin/master
Switched to a new branch 'test-local'
Branch test-local set up to track remote branch master from origin.
```

GitHub Desktop will respect that tracking branch as part of pushing.

So I think the problem here is that we don't respect the `push.default` configuration since we explicitly specify the target branch. While it might seem like we could just do `git push ...` without an explicit target branch that wouldn't work in the majority of setups as the default configuration for `push.default` would lead to a fatal error.

```
$ git push origin
fatal: The upstream branch of your current branch does not match
the name of your current branch.  To push to the upstream branch
on the remote, use

    git push origin HEAD:master

To push to the branch of the same name on the remote, use

    git push origin test-local

To choose either option permanently, see push.default in 'git help config'.
```

Since this doesn't look like a scenario you could get into without going to the command line I'm not going to classify this as a bug and by the looks of how complex this issue is we're not going to be able to spend time on it as part of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md). I'm going to label this `future-proposal` and we're happy to hear more feedback from the community and core contributors on this such that we can come back and re-evaluate it as part of our next planning session.

@hubgit It would be helpful to us if you could give us some background on the workflow that made you create the branch on the command line to begin with.

**Comment by hubgit** [comment]
It does look like the default configuration for push.default is `simple`, which pushes to the upstream tracking branch but - importantly - warns if it has a different name from the local branch.

> @hubgit It would be helpful to us if you could give us some background on the workflow that made you create the branch on the command line to begin with.

Just habit, I think - if I'm already in the command line, it's easier to create a branch there than switch to GitHub Desktop. I'll try using `git checkout -b foo master` instead (and/or create branches in GitHub Desktop) which should solve this.

**Comment by ottobackwards** [comment]
@niik This can be a problem if you work with multiple repos, like if you do apache work.
I have my personal fork of an apache project, with a remote to the actual apache github clone.

So I:
```bash
> git fetch apache
> git checkout -b new-apache-feature apache/master
> git push origin new-apache-feature
```

So using desktop, I can't push to origin, it tries to push to apache.

**Comment by billygriffin** [comment]
@hubgit Thanks for the issue here! Because it's not something we've seen come up for other users regularly and as @niik pointed out above, it would require quite a bit of work to tackle, I'm going to remove the future proposal label here to indicate we don't intend to support this in the near term. We're always happy to revisit if we run into more instances of this causing issues for users. Thanks again for bringing this to our attention and sorry it's not something more simple.

**Comment by ottobackwards** [comment]
ok with me too, since I just don't use desktop for anything other than open in desktop

**Comment by hubgit** [comment]
No worries, thanks @billygriffin - I've learned to only create branches in GitHub Desktop now 😄

**Comment by lucascosti** [comment]
👋 @billygriffin I'll add a +1 to this affecting me, too.

I usually have my branches track origin/master to easily see how far I am ahead/behind. But with `push.default` set to `simple`, I know `git push` would never allow pushing directly to master without me manually doing it.

Recently, I was using Desktop to write some co-authored commit messages (which Desktop makes extremely friendly! 🚀 ), but I accidentally clicked the 'Push' button, and was shocked to see that Desktop pushed my branch's changes to our production master. 😱

> So I think the problem here is that we don't respect the push.default configuration since we explicitly specify the target branch.

Yep, I think it's dangerous to not respect git defaults without at least notifying/warning the user, especially so when it involves pushing to default branches like master. 

> Since this doesn't look like a scenario you could get into without going to the command line I'm not going to classify this as a bug and by the looks of how complex this issue is we're not going to be able to spend time on it as part of our current roadmap.

🤔 I can understand this point, but I don't agree on an all-or-nothing approach to assuming Desktop use.

In my case, I would like to use both the CLI and Desktop at the same time: I mostly create and push branches from the CLI, but Desktop is great if I need a GUI to view history or write a fancy commit message.

❓ **Possibly silly question**: Forgive me if I'm incorrect, but it looks like you can't set up tracking branches from within Desktop: so, why does Desktop make assumptions on where to push if there is a tracking branch specified and it overrides the default git behavior?

IMHO, a warning that you're about to push to the repository's default GitHub branch would great regardless of the scenario. In this tracking branch situation, a prompt with a choice on what to do would be even better.

Sorry for the long post! 🙇‍♂️

**Comment by davidhariri** [comment]
> IMHO, a warning that you're about to push to the repository's default GitHub branch would great regardless of the scenario.

+1 Just experienced this too. Was shocked and embarrassed.

**Comment by aeaton-overleaf** [comment]
I ran into this again today, pushed a branch to upstream master without realising what was about to happen 😳

**Comment by hubgit** [comment]
I ran into this again today, pushed a branch to upstream master without realising what was about to happen 😳
