### ISSUE TITLE
"Automatically Sync after Committing" Option Missing

### ISSUE THREAD

**Issue by yeldarby** [desktop/desktop#2191]
### Description

The "Automatically Sync after Committing" functionality from Github Desktop for Mac is not available in Desktop Beta.

### Version

**GitHub Desktop version:** 0.6.2

**OS version:** 10.12.5

### Steps to Reproduce

1. In the menu bar go to "Edit"
2. Look for the option "Automatically Sync after Committing"
3. Find that it's not there

**Expected behavior:** Would love for this feature from Github Desktop for Mac to be carried over.

![image](https://user-images.githubusercontent.com/870796/27886190-954cb2a8-61a0-11e7-8d53-154d0b3ae378.png)

**Actual behavior:** Functionality missing.

**Reproduces how often:** 100%

### Logs

Not relevant.

#### Additional Information

Enhancement/feature request

**Comment by niik** [comment]
Hey @yeldarby,

You're correct in noting that we haven't brought this feature over from the previous client. This was a Mac-specific feature and wasn't present in the Windows client. While we could consider adding this in the future it's beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I'm going to add the `future-proposal` label to this issue and close it out, so that we don't get overwhelmed with our backlog! We'll revisit these as part of our next planning session.

**Comment by stuyam** [comment]
This is an important feature, it's the last thing keeping me from switching to the new electron version of the desktop app.

**Comment by glennreid** [comment]
This is an easy feature, and since you closed it a year ago as "not in roadmap", maybe you could reconsider it.

@shiftkey, Git is a programmer's tool in some ways (hence the rationale for not having "convenience features" like this).  But project teams often use source code revision control systems for other things like documentation and image assets and the like -- which they should: everyone should use it for everything.  But Github is the odd man out in revision control in that it is a distributed system with local repositories.  Just a weird enough model that lots of people make the  mistake of not committing back to the main repo (Github itself).  I personally don't see the value in local repo's, and one could argue that the entire reason Github exists (central repository) is antithetical to local repo's.  Therefore I would suggest that an app called "Github Desktop" should be biased toward one-click Sync and commit-and-push as a conceptual model, rather than adhering strictly to the underlying Git paradigms.

**Comment by glennreid** [comment]
Only if your builds use the local repository instead of (a) your local code base (uncommitted), or (b) the main Github repo.  You can test things without committing as you're developing.  As for build/test procedures, I can't see how that would work with local repositories without unless the build repo was an intermediate repo between your dev machine and Github, which means two sets of Push, which is probably the right thing for big groups but pretty complex.

**Comment by danielthompson** [comment]
This would be a convenient feature to have.

**Comment by rohitkhatri** [comment]
This is the only reason I'm not switching to the newer version, It would be very convenient If the new version had this feature.

**Comment by JackAdams** [comment]
I'm not going to switch back to the old version over it, but it does annoy me every time I click commit and come back a few hours later only to find I forgot to sync the changes to the remote repo.

Wouldn't have thought it too hard to add this feature.

**Comment by atalis** [comment]
I just upgraded to the newest version and didn't realize this feature is missing.  I didn't even remember that i had to explicitly enable this on the previous version, so I was very surprised and annoyed to find, a few hours after doing a commit, that it never made it to the server.  Please do add this feature back.

**Comment by chrisjsewell** [comment]
Yep I'm going to add that this is a (minor) annoyance for me as well, in the hope that the more people that moan about it, the higher it will get pushed up your todo list :)

**Comment by IridescentShadow** [comment]
This is a dealbreaker for me. Will continue to use the old one until it's implemented in the new version.

**Comment by neogithub** [comment]
I was on vacation and all of my commits were still local for 4 projects. Very annoying as I assumed it was still there. Had to remote in and push all of them. Annoying. Please add back in.

**Comment by danielthompson** [comment]
> we think focusing on the core problem is more appropriate than implementing this as requested

For me, the core problem is that 90% of the time, my intent really is to commit and then push. It's not that I have to remember to do it manually, it's that don't want to have to remember to do it manually. 

JetBrains does this right - their older-style commit dialog has a button dropdown that triggers a commit and push:

![jetbrains old](https://user-images.githubusercontent.com/838836/47173341-71901300-d2d3-11e8-8d00-d3f0b751e985.png)

Their newer-style dialog separates these into different buttons:

![jetbrains new](https://user-images.githubusercontent.com/838836/47173357-7ead0200-d2d3-11e8-8364-895e9d399cb6.png)

> We think it's valuable for users to have control over when they make their code visible to others.

Exposing this functionality as in either of the above screenshots would be a great way to do this.

**Comment by atalis** [comment]
I agree with @danielthompson.  I've been working in teams with CI, notifications, etc., and various version control systems for a long time, and I rarely, if ever, had a problem pushing to the server something I didn't intend to.  I never had an issue of accidentally committing something and triggering CI with the previous version of Desktop.  But I do forget to push my changes to the server with the current Desktop version at least once a week, if not more often.  If you worry about rookies, having two options as in the screenshots above would solve the problem.

One of the reasons for using an application vs CLI is that the former makes (or should make) it transparent to the user which or how many CLI commands need to be executed to achieve a task.  Here, the task is to make my changes available to the team/product, and Desktop fails to make transparent the fact that this tasks requires two commands.

**Comment by alandail** [comment]
I would have never upgraded to the new app if I knew this feature was gone.  How do I revert to the old client? I don't understand why there is any issue at all with having this option in the app.  Nobody has to turn it on if it causes problems for them.  I develop from 3 machines at 3 different locations, use GitHub to track my changes and to get the updated code to the other machines.  I do full tests before I send the code revisions to production.  I find myself constantly forgetting to push the changes to GitHub and it's causing all kinds of issues.

**Comment by j-f1** [comment]
I like the dropdown idea — perhaps it could be styled like the merge button on the website, where your choice is remembered.

**Comment by necival85** [comment]
I think I can say this for all of us that want this feature:
Let us choose the option, instead of forcing your workflow on us.

There's many ways to implement this; a second button, or a checkbox under the Commit button, or a global setting in the preferences, or a setting per repo

I like the simplicity of Github Desktop, but I'm using Atlassian's Sourcetree app because it has this feature. They have it as a checkbox on the Commit window, which remembers your last selection (globally across all repos).

![Screen Shot 2019-10-13 at 3 21 34 PM](https://user-images.githubusercontent.com/18435688/66720644-aee78d80-edcd-11e9-8198-f84720aaf62d.png)

**Comment by kerhart** [comment]
I agree that this is a highly needed feature. Those of us switching from other tools are quite used to it and having to remember to push separately is a hassle when you haven't had to do it for years. I agree that not everyone should use this feature, so making it not the default seems like a good compromise. This client is such an improvement over the others I have used, but this one feature is kind of a deal breaker, as forgetting to push one-time and then running a build script wastes like 30 minutes of deployment time in some cases.

**Comment by atalis** [comment]
I am really disappointed that this issue has been closed.  The proposed enhancements, though perhaps useful, will not resolve this issue.  I've been using Desktop for 3 years now, and still find myself in situations where I forget to push something and end up wasting valuable time.  Considering how trivial it would be to implement a choice for users to push or not to push, I really don't understand all the pushback.

**Comment by steveward** [comment]
From https://github.com/desktop/desktop/issues/11809:

>It's substantially tiring to click the Push button every time I made some changes into the document. Can Github Desktop automatically do so?

**Comment by ramirez** [comment]
It's quite disappointing to see this feature removed from the roadmap.

>     1. For beginners especially, this could seem like an enticing feature, but potentially puts them in bad spots where they've pushed something they didn't intend to or that they never wanted to be visible to others.

So this make this tool not a professional tool, but a beginners tool. I understand how it can be problematic, but it is fairly easy to make it an opt-in feature for advanced users. Don't blame it on the beginners. They will not remain beginners forever.

>     2. It renders the "Undo commit" functionality useless because it's already pushed up to the remote.
Same as before. Easy to solve by making it opt-in and adding a warning. Why is more important to allow undo commit than to allow auto-push? A professional tool should not make these decisions for me.

>     3. We think it's valuable for users to have control over when they make their code visible to others. We prioritize workflows for members of teams, and pushes often trigger CI, notifications, and other hooks that we want people to have more control over when those things occur.
Totally understandable, but one can easily argue that you are removing the control you claim to give the users. I want to have my code visible to others every time I commit. That is currently not possible. 

Clearly, these decisions move this tool towards being a beginners tool, by adding training wheels that you can't remove as you become more advanced.

**Comment by Committing** [comment]
This issue is a freak-show. Bottom-heavy excuses not to implement the feature and 3 years on with nothing.

**Comment by Ronaldi2001** [comment]
This option should be allowed for private repositories then if pushing something to the public accidentally wouldn't be a problem. Such a hassle when trying to switch computers, wait for commit, wait for push half the time I forget to push it. Seems stupid for all the extra work..

**Comment by markusstephanides** [comment]
Is there a fork that integrates this change? Seems like a simple feature and I don't understand how this is purposely not being implemented after reading all the feedback from users.

**Comment by roozerxc** [comment]
> This issue is a freak-show. Bottom-heavy excuses not to implement the feature and 3 years on with nothing.

@Committing I agree. Even I need this feature too to save time and resources when working on any project, and if anything the response from the GitHub Desktop developers talking about this feature not being in their "roadmap" aren't all that convincing; to me, this sounds more like PR/corporate speak. Guess we'll all have to deal with manually pushing commits, and with these blatant excuses for what seems to be a very convenient and time-saving feature unless GitHub Desktop developers pick up their slack and actually **listen** to us

**Comment by BlackBullNetwork** [comment]
i kinda find it funny that everyone is complaining about it 
github is clearly not interested in making a feature like that cause they dont listen to the comunity 
so then there is only 1 option left 
make your own github desktop using their api and make a auto push/pull feature in that
and i assume lots of developers use github so that should not be a hard thing to do for a developer who is know with making desktop apps

since clearly github is not interested in listening to their comunity for over 3 years

**Comment by anonimnor** [comment]
"We think it's valuable for users to have control over when they make their code visible to others. We prioritize workflows for members of teams, and pushes often trigger CI, notifications, and other hooks that we want people to have more control over when those things occur." - 

actually we reeal devops here in teams workflows CICD and all want that thing (auto-pushing, - say, once per every 5 minutes project been left intact) intentionally, - you see, when CI starts then it auto-tests all that doodie pushed and traces errors developer have, (maybe even reports them to his supervisor, heh), -

- if CI/CD is set PROPER (if a team/user KNOWS what is doing) this would really turn their work from stages into the flow. - it IS the workFLOW. see, it really is CI wich is continuous integration on the fly with no delays.

cmon cmon uguys the function takes u 3-5 minutes to implement, dont pull the leg )
see we now have to be able to find other solutions, like, installing bat scripts, or even other programs.
thanks.

**Comment by pik33** [comment]
I have (again) lost a day because I forgot to push after commit. Please add the option for one button commit+push. As it is the switchable option, it will not change anything for those who don't want or need it.

**Comment by atalis** [comment]
Maybe we should open another issue, since this one was closed :-(

**Comment by creativetags** [comment]
Would it be an idea to have a hidden keyboard shortcut for power users to use and avoid the issue for beginners?

**Comment by aherrick** [comment]
this is insane this feature can't be implemented. a lot of the personal development i do with github actions (just a solo dev) and when i'm working on github action workflows for example, i just want to commit and have it auto push every time. put the action behind an advanced flag

**Comment by alandail** [comment]
Yes, absolutely insane. The functionality used to be there, they took it out. 6 years of complaints and they haven't added the option back yet. I never, ever don't want my commit to push through to GitHub.

**Comment by marcusnixon-iress** [comment]
This functionality is a must - the amount of times I've forgotten to press Push and realised too late, and that's all because I used to use Visual Studio which has the "commit and push" option.

**Comment by ageesen** [comment]
At first I was looking for this option in Github Desktop, but then thought slightly outside of the box and figured I could likely get my code editor to do this instead.

Looked in VS extensions and of course there are multiple options.  GitDoc is a good one (most downloads), but there are many (haven't tried them).  Best part is, you can auto-push AND auto-commit on save/close (if you're ok with standard messages).

After 6 years, these guys have no plans on this, so we have to hack together more efficient workflows from other angles.

**Comment by merlinnerd922** [comment]
Piling on to add that them actively dismissing our issue is red flag, yellow flag at best

**Comment by VagrantOldFox** [comment]
9 years, and we still don't have basic automation in syncing. Pathetic.

**Comment by rluks** [comment]
It would be pretty handy to have this feature.

**Comment by elan-slovelock** [comment]
I am regularly caught out by this issue and have lost hours, if not days, of my time due to this simple missing option. Source tree has a handy opt in checkbox to do it. It is my goto git client as a result. I only use GitHub Desktop when I have to (working on workflows) as a result. Please let the developer decide if they wish to use this feature or not... don't just not implement it and force your choice upon us.

<img width="559" height="130" alt="Image" src="https://github.com/user-attachments/assets/4e77b021-fec2-4e8f-9254-54a8e75f7398" />

**Comment by asheden** [comment]
hope you guys are excited for the 10 year anniversary of this issue next year! the devs clearly care a lot

**Comment by ageesen** [comment]
> hope you guys are excited for the 10 year anniversary of this issue next year! the devs clearly care a lot

Don't worry it will get fixed next year for sure!  I have faith some A.I. agents will come by this thread one day and finally help us humans out.

**Comment by iLKke** [comment]
Can I still get the old version somewhere?
Seems like it's time we all admitted this is an unsolvable computing problem.
