### ISSUE TITLE
My repos aren't showing up

### ISSUE THREAD

**Issue by Ollie-w** [desktop/desktop#2194]
I have a git repo on my windows computer that I have pushed up to github. 
I get the message "no repositories found".

**Comment by niik** [comment]
Hi @Ollie-w,

We don't automatically import repositories that you've created in previous versions of GitHub Desktop. In order to add your repository you can either drag and drop the folder from Explorer to GitHub Desktop or by clicking on the `Add Local Repository` menu item in the `File` menu.

See #186

**Comment by Ollie-w** [comment]
When you say drag and drop the repo, do you mean the .git file? The reason this is confusing me is because the third option is "Add an existing project on your computer **and publish it to GitHub**" Its already on GitHub

**Comment by shiftkey** [comment]
@Ollie-w apologies for the delay in replying:

> When you say drag and drop the repo, do you mean the .git file?

You can just drag-and-drop the root folder into the app to track an existing repository. If it's not a valid Git repository, it should prompt you to initialize it.

> There's no 4th option for people who have set things up on the command line, but then decide they want to see/manage things with a GUI

As part of `0.7.0` you can run `github .` from the command line to add the current folder to the app.
