### ISSUE TITLE
Pressing tab while inputing username during sign in has unexpected behavior

### ISSUE THREAD

**Issue by Piejak** [desktop/desktop#2200]
### Description

When signing in to the client, pressing tab after typing your username highlights "Forgot password?" instead of the password input.

### Version

**GitHub Desktop version:** 0.6.2

**OS version:** Microsoft Windows Version 6.1.7601

### Steps to Reproduce

1. Logout if already logged in
1. Open sign in dialog
1. Type username
1. Press tab

**Expected behavior:** Password input selected

**Actual behavior:** Forgot password link highlighted

**Reproduces how often:** 100%

**Comment by niik** [comment]
Hi @Piejak, thanks for opening this!

The same issue was raised in https://github.com/desktop/desktop/pull/1513 but since that PR has been closed and I can't find a source issue for this I'm gonna repurpose this as a tracking issue for it and move it into the Design review project.

The comment in https://github.com/desktop/desktop/pull/1513#issuecomment-305205528 still holds true IMO

> We talked this over internally. The problem with changing the tabIndex is that it makes the view less accessible by making the onscreen order and tab index different. The solution we'd prefer is reordering the actual onscreen elements.

**Comment by niik** [comment]
@donokuda Is gonna take a stab at moving the forgot password link to the button row.
