### ISSUE TITLE
Need to have option to install Beta to C:\program files

### ISSUE THREAD

**Issue by rdgsa** [desktop/desktop#2202]
### Description

The GitHub Desktop Beta is installing to "\appdata\local\GitHubDesktop\Github Desktop.exe"

However for enterprise purposes and policies, we need to have the option to install it to c:\program files

It is typical for Windows programs to give a choice of install location.

### Version

**GitHub Desktop version:** 0.6.2

**OS version:** 
Microsoft Windows Version 6.1.7601

**Expected behavior:** Install process allows you to select a location under c:\program files

**Actual behavior:** Install process didn't give a choice, installs it under \appdata\local\GitHubDesktop

**Comment by niik** [comment]
Hi @rdgsa,

Unfortunately this is a constraint in the installation framework we use, [Squirrel.Windows](https://github.com/Squirrel/Squirrel.Windows), see (https://github.com/Squirrel/Squirrel.Windows/issues/314). Squirrel supports machine-wide installs in a different way than conventional Windows installers, see https://github.com/Squirrel/Squirrel.Windows/pull/337.

There's an MSI up on https://desktop.github.com which is built with this and it will (as far as I understand it) more or less "install an installer" machine wide that will then run on login for each user and install it to their AppData directory. Depending on the reasons behind you needing to install machine-wide this might be of interest to you.

Are you primarily wanting to install to `c:\program files` in order to deploy GitHub Desktop to all your users or is there some other constraint in your environment that requires you to have it be installed there?

**Comment by rdgsa** [comment]
Thanks let me take a look at those references.

**Comment by gyg3** [comment]
12

**Comment by joshaber** [comment]
As @niik said, this is currently a known limitation related to Squirrel.Windows. We don't currently have any plans to provided a more customizable installer.
