### ISSUE TITLE
Show Git LFS progress

### ISSUE THREAD

**Issue by joshaber** [desktop/desktop#2226]
We'll need to show it in a few different places:

- [x] Cloning.
- [x] Committing.
- [x] Checking out
  - [x] Reverting
  - [x] Switching branches

**Comment by joshaber** [comment]
Putting this in design review. At minimum the new design needed is progress while reverting. We have some amount of progress reporting in the other places already.

**Comment by joshaber** [comment]
For my own future reference, `GIT_LFS_PROGRESS` is documented at https://github.com/git-lfs/git-lfs/blob/dce20b0d18213d720ff2897267e68960d296eb5e/docs/man/git-lfs-config.5.ronn.

**Comment by donokuda** [comment]
@joshaber Wanted to check in on _all the places_ where we would want to show Git LFS progress if that's aligned with your work happening in [your lfs progress branch](https://github.com/desktop/desktop/tree/l-f-s-p-r-o-g-r-e-s-s). I can also follow up with more specific designs if needed.

**Cloning**:  Seems like a reasonable place for this would be our cloning progress bar
![image](https://user-images.githubusercontent.com/1174461/29146462-19dd1874-7d16-11e7-9d97-d23793829a3e.png)

**Committing:** I believe we already show some sort of status in the primary button when you're committing. If so, then this seems to be a good place to put some information:

<img src="https://user-images.githubusercontent.com/1174461/29146838-4d29b80c-7d18-11e7-80d6-f90666fff1ad.png" width="260" />

How much information does Git LFS give us in terms of progress? Would some of that information help users get an understanding of how long the progress would take (such as file size transfer or anything we can infer a percentage from?)

**Checking out / switching branches:** The branch menu seems to be the appropriate place here since we already display progress when switching.

<img src="https://user-images.githubusercontent.com/1174461/29148232-ee094244-7d20-11e7-8504-7c585c4f772d.png" width="250" />

**Reverting:** Since reverting happens from the history view, if we want to prevent the user from taking any action such as pushing or pulling, would it make sense to disable the Push/Pull/Publish button and display any information around downloading there?

<img src="https://user-images.githubusercontent.com/1174461/29185948-cb47f4ae-7dbf-11e7-8ee9-e7e8ffc52172.png" width="250" />

If there's a reason why we might want to block all user actions while we're checking things out, we could display an overlay instead. Maybe something close to this:

<img src="https://user-images.githubusercontent.com/1174461/29189646-303f00a8-7dcc-11e7-9b9c-4af34001b1e1.png" width="370" />

**Comment by joshaber** [comment]
>Cloning: Seems like a reasonable place for this would be our cloning progress bar

👍 

>Committing: [...]  I believe we already show some sort of status in the primary button when you're committing.

👍 In the particular case of committing, LFS doesn't give us any progress as it's an entirely local operation. The potentially long part is that LFS has to hash the file, but that should _generally_ be pretty fast.

>How much information does Git LFS give us in terms of progress? Would some of that information help users get an understanding of how long the progress would take (such as file size transfer or anything we can infer a percentage from?)

Yup, it gives us bytes transferred and total bytes.

>Checking out / switching branches: The branch menu seems to be the appropriate place here since we already display progress when switching.

👍 

>Reverting: Since reverting happens from the history view, if we want to prevent the user from taking any action such as pushing or pulling, would it make sense to disable the Push/Pull/Publish button and display any information around downloading there?

I think it makes sense to disable them... I'm not totally sure if it makes sense to display progress there. Though I _guess_ I could see how it relates to pulling.

>If there's a reason why we might want to block all user actions while we're checking things out, we could display an overlay instead.

I'd lean towards this. It's hard to say what's a safe operation while a revert is happening. I imagine the index is off limits which means the user can't do much interesting.

**Comment by donokuda** [comment]
I've stubbed out an overlay in the branch [`overlays-are-the-best`](https://github.com/desktop/desktop/tree/overlays-are-the-best):

![image](https://user-images.githubusercontent.com/1174461/30172223-072355dc-93a9-11e7-8021-634c4905d0e5.png)

We'll need to disable any type of click events when the dialog is open. I was hoping to figure out a way to do this with CSS, but I have been unsuccessful with that. 😞

**Comment by joshaber** [comment]
@donokuda and I talked about this in chat. I think I steered him wrong. I said above:

>It's hard to say what's a safe operation while a revert is happening. I imagine the index is off limits which means the user can't do much interesting.

While this is _true_, it's not much different from a lot of other operations the app performs, and we don't block out the entire UI for them.

We decided to go with putting progress in push/pull area:

>@donokuda: I'm :+1: with using the push/pull area since the progress information shown there revolves around transferring data

**Comment by joshaber** [comment]
Moving this to 1.0.x. LFS 2.3.0 landed today but we'll need a little more time to make sure all the progress reporting is up to par.
