### ISSUE TITLE
Configure Git LFS filter

### ISSUE THREAD

**Issue by joshaber** [desktop/desktop#2227]
Run `git lfs install` to set up the global LFS filter.

**Comment by joshaber** [comment]
We have some choices to make here:

Do we run it silently at startup? This is what we did with Classic.

Would we rather prompt the user? If so, when?

**Comment by joshaber** [comment]
(Putting this in design review to get some 💭 on those questions.)

**Comment by joshaber** [comment]
@desktop/design Any thoughts on this?

**Comment by niik** [comment]
@joshaber `git lfs install` will basically only set up the `[filter]` section right? If that's the case then as far as I understand it lfs isn't gonna be invoked unless there's an attributes file that associate some files with that filter, correct?

In other words I'm trying to see where the harm would be with us just installing the filter and the only thing I can think about is if someone has set up the lfs filter with an absolute path because the `git-lfs` binary isn't on `PATH` which I _think_ is a very rare thing. From a design perspective I'd like for this to be handled transparently, i.e. silently. I don't recall any complaints about how we did it in the classic apps either so IMO let's go with silent and adjust if needed.

**Comment by joshaber** [comment]
So there's two levels of setup:

1. Global LFS filters.
2. Pre-push hook.

`git lfs install` does both of those, though (2) needs to be done per-repo. We can do `git lfs install --skip-repo` to only do (1).

**Comment by niik** [comment]
Ah, thanks for that clarification. The pre-push step is new since last I dealt with lfs I believe. So in that case I think we should do the `--skip-repo` on startup and the install when opening a repo *assuming that it's a no-op for non-lfs repositories*

**Comment by joshaber** [comment]
>and the install when opening a repo assuming that it's a no-op for non-lfs repositories

Unfortunately it's not 😞 If LFS isn't in their path, pushing will fail from the command line.

**Comment by joshaber** [comment]
@niik and I talked about this in chat and came to some decisions:

<img width="1084" alt="screen shot 2017-09-01 at 3 18 25 pm" src="https://user-images.githubusercontent.com/13760/29984533-dd848e5a-8f28-11e7-8b07-75d23a453cd4.png">
