### ISSUE TITLE
Why were the "update from master" and "pull request" shortcut buttons removed?

### ISSUE THREAD

**Issue by tgreen7** [desktop/desktop#2237]
### Description

On the old version of github desktop there were easy access buttons in the interface to allow you to update from the master branch or open a pull request. I was just wondering why these were removed?

### Version

**GitHub Desktop version:** 0.6.2

**OS version:** macOS 10.12.5

**Comment by dwilt** [comment]
Agreed. Would love the Open a Pull Request button back!

**Comment by atmyers0** [comment]
I would love to see the pull request button come back as well!

**Comment by j-f1** [comment]
#2195 adds a pull request menu item, if that helps.

**Comment by atmyers0** [comment]
Looks good!

**Comment by donokuda** [comment]
Hi @tgreen7! We removed the "update from master" and "create PR" buttons so that the interface can focus on the branch -> publish/push/pull workflow. By removing them as a "requirement," we were able to explore more iterations for the interface that you see today!

You should still be able to update from master via the `Branch > Update from default branch` menu item. That said, we're always thinking about how can we make certain experiences and workflow better. Specifically for "Update from master," this is something we'll most likely explore with our [1.1 release](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md#11) (as part of  "Show how the current branch relates to the target branch".) 

Hope that helps! I'm going to close out this issue for now, but feel free to follow up with any more questions and I'll do my best to answer them!
