### ISSUE TITLE
Local Change Indicators In Repository Selection View

### ISSUE THREAD

**Issue by Naituw** [desktop/desktop#2245]
### Description

It would be nice to have indicators for changes in the repository selection view.
I'm working on a large project, which combines multiple repository, I may modify multiple repo in the same time too, so indicators for local changes in selection view should be very helpful.

### Version

**GitHub Desktop version:** 0.6.2

**OS version:** macOS 10.13.0

### Steps to Reproduce

1. Add multiple repositories to GitHub Desktop beta
2. Click the "Current Repository" button, brings the repository selection view
3. Looking for repositories with local changes

![2017-07-14 11 59 12](https://user-images.githubusercontent.com/353943/28197803-e66de62e-688b-11e7-84b9-099e6dd40ad2.png)

**Expected behavior:** Indicator appears beside each repo when local changes available

**Actual behavior:** No indicators

**Reproduces how often:** Everytime

**Comment by iAmWillShepherd** [comment]
Thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our current roadmap.

I'm going to add the future-proposal label to this issue and close it out, so that we don't get overwhelmed with our backlog! We'll revisit these as part of our next planning session.

**Comment by billygriffin** [comment]
This exists now so I'm removing future proposal! 😄 Thanks for the suggestion!
