### ISSUE TITLE
Allow Commit & Push with the click of a single button

### ISSUE THREAD

**Issue by Cervenka** [desktop/desktop#2256]
### Description
I'd love to get the commit & push (single button) back. An option could be to have a setting to automatically push after a commit.

Thank you 

### Version
**GitHub Desktop version:** 0.6.2
**OS version:** OS X 10.11.6

**Comment by joshaber** [comment]
Thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I'm going to add the `future-proposal` label to this issue and close it out, so that we don't get overwhelmed with our backlog! We'll revisit these as part of our next planning session.

**Comment by billygriffin** [comment]
Hi @Cervenka, thanks for the issue! We've done quite a bit of work to make it obvious that there are commits to be pushed, mostly via the suggested next step to push to your branch, and that has been exceptionally well received since it shipped in January. Since we think that partially solves the problem of ensuring you don't forget to push after committing and there are a lot of people who prefer to keep things local up until they want to push to GitHub, we're going to keep this as is for now. Thanks again for the idea and we're happy to revisit if we see this as a point of friction for many more users.
