### ISSUE TITLE
Document mouse-free installation with Homebrew

### ISSUE THREAD

**Issue by zeke** [desktop/desktop#2293]
I'm setting up a new machine. I took a gamble and typed `brew cask install github-desktop` and it worked! I think displaying this keyboard-friendly installation option to macOS visitors would be appreciated.

🚫 🐭 🚫

**Comment by joshaber** [comment]
Huh, any idea how that works? Is it automatic or is someone doing that for us?

**Comment by mathieudutour** [comment]
also I find it weird to promote a mouse-free installation for a tool targeting people that don't like the git cli haha

**Comment by zeke** [comment]
> Is it automatic or is someone doing that for us?

Yeah I was wondering that too but haven't delved into it. I assume it's manually maintained by community members but maybe there's some github releases automation.

> tool targeting people that don't like the git cli

I'm not sure I understand what you're talking about.

**Comment by mathieudutour** [comment]
GitHub Desktop is a GUI for git. So it's fair to assume that people who want to use it prefer using their mouse than their terminal to install it. (was just a joke, I love homebrew)

**Comment by zeke** [comment]
> GitHub Desktop is a GUI for git.

Ah of course! But Desktop itself is actually pretty keyboard friendly.

**Comment by shiftkey** [comment]
Looks like it was moved over to the Electron app [recently](https://github.com/caskroom/homebrew-cask/commit/461cae4e0156752330b6729dc59840bd6353e9fc), but was the classic version before that.

If someone wants to add a bit to [this section](https://github.com/desktop/desktop#where-can-i-get-it) with a mention that it's community-managed that'd be great.

**Comment by bbgdzxng1** [comment]
Brew Cask is awesome for GUI apps on macOS.  The code for the community supported Github Desktop installer is available at https://github.com/caskroom/homebrew-cask/blob/master/Casks/github-desktop.rb

The Brew Cask community update the github-desktop script very soon after each stable release.  An interesting question is whether this could be officially supported.  It is only as complex as calculating and updating the SHA-1 checksum on each stable release.

`brew cask reinstall github-desktop` and `brew cask reinstall atom` has been the fastest way to upgrade while "auto-update for non-admin user" has been broken in Squirrel.Mac.  Thankfully, there is now light at the end of the tunnel thanks to the work of the Github Desktop team.

If the documentation did reference brew for macOS users, it should also reference the equally awesome chocolatey https://chocolatey.org/packages/github-desktop for Windows users.

_For unattended install on Windows using the community supported [Chocolatey](https://chocolatey.org/) package manager:_
`c:\> choco install github-desktop`

_For unattended install on macOS using the community supported [Homebrew](https://brew.sh/) package manager:_
`$ brew cask install github-desktop`

And obviously, `apt install github-desktop` when the time comes to merge the Linux ports into the main project. :insert-emoji

**Comment by shiftkey** [comment]
@bbgdzxng1 I'm sure @zeke wouldn't mind if you were keen to submit the PR to the place I mentioned above. And :thumbsup: to mentioning Chocolatey - I'll send some tweaks to the nuspec file over now!

**Comment by bbgdzxng1** [comment]
@zeke, pull request for updating README.md is at #2508.

@shiftkey, thanks for sending the [PR](https://github.com/TakataSanshiro/Chocolatey-Packages/pull/1) to Chocolatey/nuspec.

For any interested readers, here is the metadata for the community-maintained package managers:
- Chocolatey (Windows) nuspec metadata is maintained at: https://github.com/TakataSanshiro/Chocolatey-Packages/tree/master/github-desktop
- Homebrew Cask (macOS) metadata is maintained at: https://github.com/caskroom/homebrew-cask/blob/master/Casks/github-desktop.rb

I do not believe that the docs need to go as far as including Microsoft [PowerShell Package Management](https://docs.microsoft.com/en-us/powershell/module/packagemanagement/?view=powershell-5.1).  Although this method uses official Microsoft tools, the process is more complex than Chocolatey but _still relies_ on Chocolatey for metadata.  Nevertheless, for purposes of completeness within this thread, here is how to install Github Desktop using Windows 10's native PowerShell Package Management.

> PowerShell 5.x users can install Github Desktop using PowerShell Package Management:
> ```
> PS C:\> Install-PackageProvider -Name "chocolatey"
> PS C:\> Install-Package -Name "github-desktop" -ProviderName "chocolatey"
> ```

- PowerShell Package Management is a _manager of package managers_ rather than a _package manager_ itself.  To install Github Desktop using PowerShell Package Management, you still rely on Chocolatey as a package provider.  PowerShell Package Management adds an extra step.
- PowerShell Package Management requires PowerShell 5.x which ships with Windows 10.  For versions prior to Windows 10, you have to first install [Windows Management Framework 5.1](https://www.microsoft.com/en-us/download/details.aspx?id=54616) to get PowerShell 5.1.  For many users, this is again an extra step.
- [PowerShell Core 6](https://github.com/PowerShell/PowerShell) and PowerShell Package Management does now support macOS and Linux, see PowerShell Package Manager's underlying open-source, cross-platform [OneGet](https://github.com/OneGet/oneget) project for more details.  But, since Github Desktop installation using PowerShell Package Manager currently relies on Chocolatey and Chocolatey is Windows-only, you end up limited to Windows anyway, but with the headache of a compatibility matrix.

If anyone feels strongly that documentation for Microsoft's PowerShell Package Management should be added, please comment.  Otherwise, Windows users can enjoy plain Chocolatey for command-line and unattended install of Github Desktop.

**Comment by joshaber** [comment]
Looks like this was done in #2508.

**Comment by zeke** [comment]
🍻 🍫

**Comment by wilsonmar** [comment]
When I tried "brew cask install github-desktop" I get:
Error: Cask 'github-desktop' is unavailable: No Cask with this name exists.

**Comment by shiftkey** [comment]
@wilsonmar looks like it was renamed to `desktop` in https://github.com/caskroom/homebrew-cask/pull/39883 - I'll open a PR to update these docs.

**Comment by zeke** [comment]
It's `github`, right?

**Comment by shiftkey** [comment]
@zeke yep, it's still `github`
