### ISSUE TITLE
It would be convenient to be able to text search the diff listings…

### ISSUE THREAD

**Issue by geowar1** [desktop/desktop#2306]
Version
GitHub Desktop version: Deer Types (222)
OS version: 10.12.6

**Comment by shiftkey** [comment]
@geowar1 thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I'm going to add the `future-proposal` label to this issue and close it out, so that we don't get overwhelmed with our backlog! We'll revisit these as part of our next planning session.

**Comment by shiftkey** [comment]
A more detailed proposal was opened in #4484, so I'm going to favour that as a starting point for discussion.
