### ISSUE TITLE
Add "Go To [Previous/Next] [File/Diff]" commands (buttons, menus, or keys)

### ISSUE THREAD

**Issue by geowar1** [desktop/desktop#2308]
### Description
Whenever GitHub Desktop detects and reloads a diff from disk it returns to the top (losing the place where you're currently viewing diffs).

It would be awesome if it wouldn't do this… ;-)

Regardless of that it would be convenient to have an easy way (other than just the scrollbars) to navigate around the changed files and diff's.

### Version

GitHub Desktop version: Deer Types (222)
OS version: 10.12.6

**Comment by shiftkey** [comment]
cc @niik for feels (or any previous thoughts) about keyboard navigation

**Comment by shiftkey** [comment]
@geowar1 thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I'm going to add the `future-proposal` label to this issue and close it out, so that we don't get overwhelmed with our backlog! We'll revisit these as part of our next planning session.

**Comment by billygriffin** [comment]
@geowar1 Thanks for the idea here! Because we haven't seen this surface more broadly, I'm going to remove future proposal to indicate we don't intend to support it in the near term. However, we're happy to revisit if it becomes something we're seeing as a point of friction for a larger group of users. Thanks again!
