### ISSUE TITLE
Add ability to reorganise repositories and label them

### ISSUE THREAD

**Issue by samdenty99** [desktop/desktop#2324]
`Enhancement`

After upgrading to the Desktop Beta, something that annoyed me was that the repositories were sorted in alphabetical order. Initially I went to drag to reorganise, as this would immensely reduce the time it takes to locate one of hundreds of repositories (by moving favorites to the top).

This could be accompanied by *labels* which each repository could be assigned to (right click `labels>[checkbox] example label`). Each repository could be a member of multiple labels, with optional colors for each label (Top label would take precedence of the repo's color). The colors could be added to the font-color / subtle background color etc.
<br>

**Example of how it could look:**<br>
![example](https://user-images.githubusercontent.com/13242392/28570477-2b18131e-7136-11e7-9faa-68c57ad2eaa7.png)

**Comment by shiftkey** [comment]
@samdenty99 thanks for the suggestions - we've gotten a lot of feedback about things we can do to the repository listing. We've not had the suggestion for applying labels to repositories yet. 

Here's some of the previous discussions we've had around ways to enhance the repository list:

 - #2038 - pin repositories so they appear at the top
 - #2037 - grouping repositories by organization
 - #1598 - custom folders for repositories
 - #1929 - support changing description to distinguish between local clones of the same repository

Currently our planning is based on the current roadmap, which you can view 
[here](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I'm going to add the `future-proposal` label to this issue and close it out once my question below is answered, so that we don't get overwhelmed with our backlog! We'll revisit these as part of our next planning session.

> After upgrading to the Desktop Beta, something that annoyed me was that the repositories were sorted in the order I added them. 

These should be sorted alphabetically by default. If that's not the case, it might be a bug. Could you confirm that's the behaviour you are seeing?

**Comment by samdenty99** [comment]
@shiftkey File explorer sorted directories alphabetically, but they are in fact sorted alphabetically.

**Comment by shiftkey** [comment]
@samdenty99 so we're good?
