### ISSUE TITLE
CMD-S keyboard shortcut broken in latest github desktop

### ISSUE THREAD

**Issue by Pearapps** [desktop/desktop#2325]
### Description

When I use the CMD-S keyboard shortcut, nothing happens, unlike before when it would push my changes.

### Version

**GitHub Desktop version:** 0.7.0

**OS version:** 10.126

### Steps to Reproduce

1. Press CMD-S

**Expected behavior:** My commits are pushed

**Actual behavior:** Nothing

**Reproduces how often:** 100%

**Comment by shiftkey** [comment]
@Pearapps when you say "unlike before" are you referring to the classic Desktop app?

I ask because that keyboard shortcut was mapped to Sync (or Publish for an unpublished branch):

<img width="324"  src="https://user-images.githubusercontent.com/359239/28579993-9f2dc2fa-7134-11e7-8233-514fd6d92dd2.png">

The sync functionality is no longer supported (see #1565 for related discussion) and we instead make Push/Pull explicit:

<img width="207" src="https://user-images.githubusercontent.com/359239/28580040-bf83b474-7134-11e7-8dc0-715a36c68396.png">

**Comment by joshaber** [comment]
Thank you for your issue!

We haven't gotten a response to our questions above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
