### ISSUE TITLE
[feature request] acess to issues & wiki

### ISSUE THREAD

**Issue by EMLVIRUS** [desktop/desktop#2378]
This is relevant to #2376 but not a dup.

Issues feature should include:
- create
- comment
- close
- milestone
- label

Wiki feature should include:
- create page
- edit
- delete page

**Comment by iAmWillShepherd** [comment]
Thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our current roadmap current roadmap.

I added the future-proposal label to this issue and closed it so that we won't get overwhelmed with our backlog! We will revisit this in our next planning session.

**Comment by billygriffin** [comment]
I'm going to remove the label here in favor of #2376 and also want to mention #1866 as well. We're tracking wiki support separately in a currently open bug. I know you called out that it's not the same but I want to focus on the problem we're solving by incorporating issues, as Desktop is not intended to be a local replacement for the functionality of GitHub.com.
