### ISSUE TITLE
Allow discarding of individual lines in a file

### ISSUE THREAD

**Issue by mikeabiezzi** [desktop/desktop#2402]
### Description

It would be convenient to discard individual lines in a file. Currently, I have to first commit the lines I want and then discard the whole file. Sometimes I'm not ready to commit lines, but I would like to get rid of unwanted lines while I'm reviewing the diff.

### Version

**GitHub Desktop version:** 0.7.2

**OS version:** macOS 10.12.6

**Comment by joshaber** [comment]
Huh, I'm surprised we don't already have an issue for this. Thanks @mikeabiezzi!

**Comment by JosephTLyons** [comment]
+1, Atom's GitHub package allows for lines or chunks to be discarded, would love to see that in GitHub Desktop.

**Comment by Janpot** [comment]
@billygriffin As requested, adding these use cases to the ticket:

1.
Right before I commit I usually like to review all my changes in github desktop and basically do a code review of my own commit. Sometimes there are things in there, like console.log that I'd like to revert, or other things that I forgot to clean up. I do want them reverted instead of selected, because I still want to run tests or verify my code still works before actually committing the changes.

2.
Sometimes when working on a change, I notice I made some wrong assumptions about the code halfway, or figure out a better way to do things, and would like to revert some changes and redo a part. This could also be solved by deselecting, committing, reverting what's left and undoing the commit. But the annoying thing about that approach is that visually, those lines that I want reverted are still there, and that makes it hard to properly review the code I'd like to keep during the process.

**Comment by carldunham** [comment]
Why is this closed? Has it been addressed? #3225 was closed referring dismissively to this issue, now it's closed. Huh?

**Comment by Gama11** [comment]
@carldunham Not sure what you mean, [this issue is not closed](https://i.imgur.com/jtcHeqL.png).

**Comment by carldunham** [comment]
Sorry, I had a dumb.

**Comment by carldunham** [comment]
Ironically, having this same conversation about Gitkraken at https://stackoverflow.com/questions/55368879/how-to-discard-line-in-gitkraken/

**Comment by billygriffin** [comment]
As an update, I think this addition makes a ton of sense, but is non-trivial in terms of design and implementation and is unlikely to be prioritized in the very near future. However, it's absolutely something we think would be a great improvement and we definitely want to support it at some point in the future.

**Comment by mnaoumov** [comment]
https://github.com/gitextensions/gitextensions had this feature since forever. Just saying...

**Comment by JohannSig** [comment]
Any progress on this? Just got Desktop and this is an immediate show-stopper, coming from GitExtensions

**Comment by hottestchilipepper** [comment]
I made something similar feature with this. I think the result is same with what you want.
Please review the pull request. Thank you.

**Comment by billygriffin** [comment]
Hi folks, thanks for weighing in. We're working on designs and toward implementation of this. What we'll likely do initially is just to be able to right click any line, and a context menu allows you to discard the selected line. We may also expand this to being able to do the same with a hunk as opposed to just a line, but that's TBD. Without a more thorough iteration on the partial line selection, we're not comfortable shipping the "Discard all unselected lines" as @hottestchilipepper proposed (thanks for the proof of concept though). @ampinsk I'll let you share proposed designs here.

**Comment by ampinsk** [comment]
Thank you for setting context @billygriffin! Here are the related mockups:


### Discarding a single line

<img width="1072" alt="partial-commit" src="https://user-images.githubusercontent.com/10404068/80427788-507f8980-889d-11ea-892a-33e62124acf6.png">


### Discarding a hunk 

<img width="1072" alt="partial-commit-hunk" src="https://user-images.githubusercontent.com/10404068/80427795-54aba700-889d-11ea-85f9-780587da66b4.png">
