### ISSUE TITLE
i want to program a attiny85 not work my way through nonsense.  i think i am in the wrong place

### ISSUE THREAD

**Issue by dwynhrt** [desktop/desktop#2403]
### Description

[Description of the issue]

### Version

**GitHub Desktop version:** [version here]

**OS version:** [version here]

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by j-f1** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

**Comment by dwynhrt** [comment]
i have been using Arduino software to program uno and nano boards.  i have
run across these attiny85 boards and they look like they could be fun.  i
logged onto your site to learn to program them.  is that what You are about
of not???

**Comment by j-f1** [comment]
Although GitHub has resources for many areas of programming, this part of the website (https://github.com/desktop/desktop) is for developing GitHub’s desktop app. I’d recommend [searching](https://github.com/search) for what you need.
