### ISSUE TITLE
When I try to do an initial commit of a large project (about 30000 files big) the desktop app keeps crashing and the command line version ignores everything when I try to add all

### ISSUE THREAD

**Issue by jakob-1** [desktop/desktop#2416]
### Description

[Description of the issue]

### Version

**GitHub Desktop version:** [version here]

**OS version:** [version here]

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by j-f1** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by joshaber** [comment]
Specifically, in the case of a crash, it'd be super helpful to get the logs.

 - If you are on macOS, attach the most recent log file from:
   `~/Library/Application Support/GitHub Desktop/logs/*.desktop.production.log`
 - If you are on Windows, attach the most recent log file from:
   `%APPDATA%\\GitHub Desktop\\logs\\*.desktop.production.log`

**Comment by jakob-1** [comment]
[2017-08-09.desktop.production - Copy.txt](https://github.com/desktop/desktop/files/1210346/2017-08-09.desktop.production.-.Copy.txt)

**Comment by jakob-1** [comment]
I looked through the logs and found the conflicting file and was able to commit the work.
