### ISSUE TITLE
The output from the command could not fit into the allocated stdout buffer. Set options.maxBuffer to a larger value than 10485760 bytes

### ISSUE THREAD

**Issue by mwp1990** [desktop/desktop#2449]
### Description
I used the github desktop to pull the code of linux repository from my github.and then issue it:
The output from the command could not fit into the allocated stdout buffer. Set options.maxBuffer to a larger value than 10485760 bytes

### Version

**GitHub Desktop version:** 0.7.2

**OS version:** Microsoft Windows[version 6.1.7601]

### Steps to Reproduce

1. using the desktop to pull my respository from my github account.
2. my github respository is https://github.com/torvalds/linux
3. 
The output from the command could not fit into the allocated stdout buffer. Set options.maxBuffer to a larger value than 10485760 bytes

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by shiftkey** [comment]
I haven't tested this out on Windows 7 but a quick test on Windows 10 also fails, but in a slightly different way which I think is the same underlying issue as what you're seeing.

There are known issues with cloning the linux repository down to a Windows filesystem - opening **View** | **Toggle Developer tools** shows me the end of a large error message:

<img width="1369" src="https://user-images.githubusercontent.com/359239/29201470-d22e669e-7ea1-11e7-8d31-2864d3a88797.png">

The interesting bit is these messages buried in the output:

```
...
error: unable to create file drivers/gpu/drm/nouveau/nvkm/subdev/i2c/aux.c: No such file or directory
error: unable to create file drivers/gpu/drm/nouveau/nvkm/subdev/i2c/aux.h: No such file or directory
... 
error: unable to create file include/soc/arc/aux.h: No such file or directory
```

These paths are problematic and not recommended for Windows (because they clash with device names from Ye Old Days™). From [MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247%28v=vs.85%29.aspx):

> Do not use the following reserved names for the name of a file:
CON, PRN, **AUX**, NUL, COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9, LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, and LPT9. Also avoid these names followed immediately by an extension; for example, NUL.txt is not recommended. For more information, see Namespaces.

To confirm this, try cloning the repository from the command line using [Git for Windows](git-for-windows.github.io) - you should see the same behaviour.

**Comment by joshaber** [comment]
From https://github.com/desktop/desktop/issues/3309:

>2. Generate 300,000 text files in a sub folder of around 100k each.
>3. Boom! you should have the problem.

**Comment by MachineKing** [comment]
I have the same problem, 
All I did was create a new local repository and started getting this error immediately, it just keeps popping up in the app without me doing anything in the app.

**Comment by splorp** [comment]
I am seeing this same error in the current Mac release (version 1.1.1 running under Sierra 10.12.6) after moving a folder containing approximately 150,000 text files (each between 2–10kb in size) into my repo folder.

The error message stopped appearing once I manually moved the folder containing the files out of the repo folder.

![screenshot 2018-04-20 15 31 13](https://user-images.githubusercontent.com/29835/39074967-d313a940-44b0-11e8-9568-ce90f82bbe53.png)

**Comment by shiftkey** [comment]
@splorp could you attach the full log files? The **Help** | **Show Logs in Finder** menu items should open the logs folder, and inside those are the log files generated by day. This will provide some more information to help troubleshoot.

I suspect this might be some limit we're encountering when having to deal with 150k untracked files in a new repository, but it'd be nice to get some additional clues about how to start digging.

**Comment by splorp** [comment]
@shiftkey Yes, I can do that, but it will have to wait a couple of weeks. I’m on the road for quite a while and that issue was on my desktop machine (where the log files reside).

**Comment by splorp** [comment]
O hai.

Finally following up on this issue, I have attached the log files from the day I experienced the error (April 20th) as well as the previous and next days.

[2018-04-19.desktop.production.log](https://github.com/desktop/desktop/files/2024151/2018-04-19.desktop.production.log)
[2018-04-20.desktop.production.log](https://github.com/desktop/desktop/files/2024152/2018-04-20.desktop.production.log)
[2018-04-21.desktop.production.log](https://github.com/desktop/desktop/files/2024153/2018-04-21.desktop.production.log)

I didn’t notice anything out of the ordinary in the logs, at least relating to the buffer.

If you need me to generate a “fresh” error and log file, let me know.

**Comment by OMortensen** [comment]
I'm seeing this error on a new repository I just created for some code we've moved to github... How do I change the options.maxBuffer?

**Comment by shiftkey** [comment]
@OMortensen `options.maxBuffer` is set internally inside the Git library that we use:

https://github.com/desktop/dugite/blob/0e951af6e73a7ffa536396a2f4f5a25af833fc0e/lib/git-process.ts#L160-L165

Are you able to share a log file which triggers the issue? There's a couple of sets of repro steps here that we've been able to identify, and it'd be nice to see if yours is covered by those.

**Comment by OMortensen** [comment]
@shiftkey We were able to work around the issue by getting our .gitignore file configured properly (10K+ images and other support files that do not need to be source controlled).  Seems like an issue with the number of files in a single repo...

**Comment by shiftkey** [comment]
@nerdneha great work on reproducing it. We do `git status --untracked-files=all` so that we can list all the files under the Changes tab, but clearly we're encountering an upper bound about how many files we can list out from Node in 10MB of process output.

We actually have an option for `maxBuffer` here on the operations we pass into `dugite`:

```ts
      const execOptions: ExecOptionsWithStringEncoding = {
        cwd: path,
        encoding: 'utf8',
        maxBuffer: options ? options.maxBuffer : 10 * 1024 * 1024,
        env
      }
```

That's where the `10485760 bytes` number in the error message comes from. I've opened #5011 to talk about a workaround and whether there are better solutions out there that leverage Git itself.
