### ISSUE TITLE
Different 2FA token UIs depending

### ISSUE THREAD

**Issue by xPaw** [desktop/desktop#2450]
### Version

**GitHub Desktop version:** 0.7.2

**OS version:** Windows 10

### Steps to Reproduce

1. Do a `git push` from CLI on a clean install
2. Enter credentials in a github login window that popups
3. Observe the fancy 2FA token window.

1. Authorise within app's settings
2. Observe a simple text input for the 2FA token

----

Depending on where you get the login prompt, you end up with different login UIs, when pushing from CLI and getting the login prompt, the 2FA login window looks like this:
![11-072641424](https://user-images.githubusercontent.com/613331/29204479-fb6517c8-7e7f-11e7-8bec-2e0315737dba.png)

When logging in from the app UI, it looks like this:
![11-073022401](https://user-images.githubusercontent.com/613331/29204499-1db2f19c-7e80-11e7-99bd-73159ec09688.png)

Perhaps this is something that could be combined into a single consistent UI?

There's also a question of the github app not creating credentials for `git` to use automatically, but that might be a problem for another issue.

**Comment by joshaber** [comment]
That's true. The easy answer is that those are coming from two completely different apps. The former from git itself and the latter from GitHub Desktop.

It might be nice to unify those someday, but it's beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I'm going to add the `future-proposal` label to this issue and close it out, so that we don't get overwhelmed with our backlog! We'll revisit these as part of our next planning session.

**Comment by billygriffin** [comment]
Hi @xPaw, thanks for the suggestion! Because this is mostly cosmetic and both explain pretty well what's going on and what's expected, I'm going to remove `future-proposal` on this as I'm not sure the unification of the UI adds much user value. We're happy to reconsider if we see people getting tripped up on one or another frequently. Thanks again!
