### ISSUE TITLE
I can't connect to my own repository; I have never changed the default security settings.

### ISSUE THREAD

**Issue by I-keep-trying** [desktop/desktop#2453]
I am trying to setup my local Git repository so I can push updates to my GitHub repository. I am currently logged into GitHub, on the same machine that my local Git is on. I just went through the steps in the desktop app, (yes I am signed into the app with the same account) and was able to stage and compare, but I cannot commit; I get a message saying I don't have permission?? It's mine! I looked everywhere in GitHub settings, I don't see any additional permissions I could possibly give myself. 

"Authentication failed. You may not have permission to access the repository. Open options and verify that you're signed in with an account that has permission to access this repository."

GitHub Desktop 
Version 0.7.2
Windows 10

**GitHub Desktop version:** 0.7.2

**OS version:** Windows 10

### Steps to Reproduce

1. Log into GitHub Desktop
2. Add local repository
3. Write summary and description
4. Leave default branch: master
5. Click "Publish branch" 
6. Receive error message: "Authentication failed. You may not have permission to access the repository. Open options and verify that you're signed in with an account that has permission to access this repository."

The help [documentation](https://help.github.com/desktop-beta/guides/getting-started-with-github-desktop/authenticating-to-github/) had nothing to suggest that I did not already do. 

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by shiftkey** [comment]
@I-keep-trying there's a couple of things I'd like you to check to  confirm nothing unexpected is occurring with your setup:

1. From the app, could you open **View | Toggle Developer Tools** when this occurs and share the underlying error? It should be logged to the console.

2. From the app, could you open **File | Options** and confirm you have a GitHub account registered? This is what my setup looks like:

<img width="475" src="https://user-images.githubusercontent.com/359239/29245945-63c06508-802d-11e7-9d6e-0b7126cec7a8.png">

3. From the Start Menu, could you open **Credential Manager**, select the **Windows Credentials** tab and see if there are any GitHub credentials listed under the "Generic Credentials" group? This is what it looks like on my machine:

<img width="827" src="https://user-images.githubusercontent.com/359239/29245972-1762edf6-802e-11e7-8344-7eb595a0ddf9.png">

**Comment by I-keep-trying** [comment]
Hello Brendan, 
Thanks for your quick response! I was beginning to worry I had created a bug report over nothing, but I have verified everything and I still have the same problem :(

Yes I was logged in yesterday, here is what it looked like then and just now:

![capture](https://user-images.githubusercontent.com/26046173/29252923-19fcda60-8036-11e7-8a3a-61cca11c63e9.PNG)

I did not think to check my Windows credentials yesterday, and for a moment I thought that might fix it. When I checked, the username field was blank, so I updated it, so that's why it says "Modified: Today". But after adding my username, I tried to publish again, and got the same error as yesterday. Also, as you can see, I only have credentials for https://api.github.com, not for https://github.com, like you do, am I supposed to?

![credentials](https://user-images.githubusercontent.com/26046173/29252924-2a5dabfa-8036-11e7-8431-ae9224da7716.PNG)

I copied all the error messages I found (thanks for the tip on Developer Tools!) and just pasted them all together in the attached log.  Thanks again,
Andrea
[-1502654604997.txt](https://github.com/desktop/desktop/files/1220874/-1502654604997.txt)

**Comment by I-keep-trying** [comment]
Oops I thought "close and comment" meant to close the message, not the issue!

**Comment by I-keep-trying** [comment]
Well I added https://github.com to my Windows credentials, and still cannot publish. :(

**Comment by shiftkey** [comment]
@I-keep-trying thanks for the log file. It looks like you have everything configured right. 

It looks like one of the repositories you are using is https://github.com/i-keep-trying/fccRandomQuote - is that one that fails to fetch? I ask because it's a public repository, and it's raising an error on fetch (which it shouldn't need).

```
renderer.js:1 `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

(The error was parsed as 2: Authentication failed. You may not have permission to access the repository. Open options and verify that you're signed in with an account that has permission to access this repository.)
error @ renderer.js:1
```

Could you open the repository in the command line and run this command? I want to confirm the remote URLs for your repository is HTTPS, not SSH - this might be the issue.

```
git remote -vv
```

This error is also interesting (seems to happen on every network call) but is not an error I've come across before. This is probably separate to the Git issue.

```
renderer.js:1 fetchAccount: failed with endpoint https://api.github.com
TypeError: Failed to execute 'fetch' on 'Window': Invalid value
```

Are you behind a proxy server?

**Comment by I-keep-trying** [comment]
Here's what I get when I enter ```git remote -vv``` (plus a few other commands I tried just for fun.)

![git-github](https://user-images.githubusercontent.com/26046173/29275814-074232de-80d2-11e7-8232-5e3d90f49ad2.PNG)

I don't *think* I'm behind a proxy, but I guess I could be... my boyfriend plays games online, I guess it's possible he's got us set up in a way that mimics a proxy. Is there a way for me to test?

**Comment by I-keep-trying** [comment]
For what it's worth, checking my IP on a "what's my IP" web site against ipconfig matches. Seems like if there was a proxy it wouldn't match, right?

**Comment by shiftkey** [comment]
@I-keep-trying apologies for the delay in replying.

I couldn't recall the screenshot, but I _think_ you had SSH remotes configured for the repository. I'd recommend changing these over to HTTPS to see if that addresses the issue.

> For what it's worth, checking my IP on a "what's my IP" web site against ipconfig matches. Seems like if there was a proxy it wouldn't match, right?

Possibly, but I don't think that's the issue here. Just something that I like to check whenever we encounter a potential networking issue.

**Comment by I-keep-trying** [comment]
Ha, I got self conscious and took the screenshot down, thinking I might have overexposed myself... with DHCP my IP changes once in a while, but still.

Is SSH remote for using over command line? And HTTPS for the desktop app? If that's the case, it would make sense, because I first started using Git via command line, then decided to learn how to use the desktop app - I thought it might be easier for just getting stuff done. However, the problem appeared initially in the command line response, so I think I may have just answered my own question. Where is SSH configuration done? I don't remember ever setting or changing this, (not that I didn't I just don't remember at the moment) or why I would have done so (that's the problem with following step by step instructions and not really understanding them sometimes). 

Sorry for all the questions - I'm trying to learn everything at once: programming in general, starting with JavaScript (deep into YDKJS), Git and GitHub, Ubuntu (I killed it trying to upgrade- not messing with it for now), and doing it all on my own with help from Stack Exchange, reddit, and people like you. I really appreciate your continued support!

I have a brand new project I'm starting for Free Code Camp, so I have an opportunity to begin a new repository. I really want and need to learn proper Git/GitHub so I can be ready for a junior position SOON. I even made myself another GitHub user so I can pretend to be two people on a project, once I get past this issue. Maybe I should just start fresh with the other account, with the new project, and see what happens?

**Comment by I-keep-trying** [comment]
OK, just for the sake of being thorough, I looked around, and I cannot see *anywhere*, either in the desktop app settings, nor in the settings for any repository, nor in my GitHub profile settings, where I would go about doing SSH remote configuration. I don't even know what that is, let alone how to change it to HTTPS. 
:(

**Comment by shiftkey** [comment]
@I-keep-trying I'm glad you were able to work around the issue!

> Is SSH remote for using over command line? And HTTPS for the desktop app? 

Both SSH and HTTPS are supported over the command line. We haven't spent much time on SSH support in the app, but if you have an external setup it can be detected. 

HTTPS authentication and SSH authentication differ in a few ways:

 - HTTPS credentials are stored by a credential manager configured in Git, SSH keys are managed external to Git by an agent process
 - HTTPS credentials are usually specific to a server (account-based), SSH keys - once the public key is shared like you added it to GitHub - can be used across many servers (identity-based)
 - HTTPS authentication is done for each connection (simpler, but limited), SSH authentication is done for each session (multiple commands can be run in a session, more complex to manage, but SSH is a well-known protocol)

> Where is SSH configuration done?

We have [a guide](https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/#platform-windows) for doing this yourself, but I haven't tested that this integrates nicely with Desktop - I _expect_ this to work, but maybe I've missed something.

> OK, just for the sake of being thorough, I looked around, and I cannot see anywhere, either in the desktop app settings, nor in the settings for any repository, nor in my GitHub profile settings, where I would go about doing SSH remote configuration. I don't even know what that is, let alone how to change it to HTTPS.

So the thing you're looking to configure is all specific to your local machine and covered by the guide I linked to above:

 - you have an SSH public/private keypair on your machine
 - the public key is added to GitHub, so GitHub knows who you are
 - `ssh-agent` process is running, to manage
 - your `~/.ssh/config` entry points to your SSH keys

It's not the most user friendly experience, which is why Desktop will default to cloning over HTTPS. But we've had some pain points that users have encountered when dealing with SSH remotes, I'm going to roll them up into an issue this week and see if we can make this better.

Thanks for all the details, and best of luck in your adventures! Let me know if there's any other questions you have around this...

**Comment by shiftkey** [comment]
Closing this out unless @I-keep-trying has further questions.

**Comment by testautomation-01-2018** [comment]
I thank you for answer too, I've just losted 5 hours for resolve that problem with my win10,  I changed windows credential and it solved my problem
Control panel > User Accounts > Windows Credential

**Comment by EugeneAndrievsky** [comment]
Hello, I have the same problem!
I think the problem is because of shh keys.

When I first time installed git in 2016 and just launched github.desktop. Was created key github_rsa.
In 2017 I started work with git console and created a new key id_rsa (as in guide above) and added it to the github account. it still working for now well by the console.

But github desktop, i think, is trying to use my github_rsa which invalid:
"Key is invalid. It must begin with 'ssh-ed25519', 'ssh-rsa', 'ssh-dss', 'ecdsa-sha2-nistp256', 'ecdsa-sha2-nistp384', or 'ecdsa-sha2-nistp521'. Check that you're copying the public half of the key " 
and i can't add it to github profile.

Github.Desktop use password from github.com but console use another one. I think it is bacause of different ssh keys.
How to "meet" working key with github desktop?

**Comment by dcsobral** [comment]
I can't understand how this issue is closed. Ignoring completely that Github Desktop ignores WSL and uses it's own mini-fake-unix setup, even with Git Bash running, ssh-agent running, either before Github Desktop is started or started from Github Desktop, or both, Github Desktop fails to authenticate remotes using the SSH protocol.

All git commands run _from_ Git Bash work -- not that I'd ever want to use Git Bash (see lack of WSL support above). 

Add to that, there's a total dearth of documentation. Go to the Github Desktop documentation site, search for "SSH", and get nothing back.

**Comment by mrg123** [comment]
I set ssh by git,create new ssh and final work again. thinks

**Comment by dtmartello** [comment]
I can't believe this issue was closed????? Wow!

I am probably uninstalling this from my desktop. Having too many issues in Windows 10. Will give it a chance but...

(1) Having the issue described above, which as been closed without a fix.
(2) Local Git location not detected when I attempt to open a command prompt.
(2a) Doesn't even ask for the location of my local Git binary location. Just assumes it is not there.

Scary stuff when the an application charged with helping me manage Git and GitHub is unable to handle  Git and GitHub security.

**Comment by huaxiao87** [comment]
Have the same issue here, can't publish new repo. It often says "bad credentials", sometimes it says "repository creation failed (name already exists on this account)". The repo shows on the github website under my account, but once I tried to access from the website, I got a 404 error and that repo disappears from the list of my repo on the github website.

More weirdly, in some rare cases, it asks me to check my internet connection which shouldn't be an issue at all.

**Comment by huaxiao87** [comment]
Have the same issue here, can't publish new repo. It often says "bad credentials", sometimes it says "repository creation failed (name already exists on this account)". I found that sometimes the unpublished repo can be shown on the github website under my account, but once I tried to access it from the website, I got a 404 error and that repo disappears from the list of my repo on the github website.

More weirdly, in some rare cases, it asks me to check my internet connection which shouldn't be an issue at all.

**Comment by pnally** [comment]
I am still having an issue with this too. Git Bash works totally fine with ssh setup. However GitHub desktop is not even allowing me to specify which generic credential to use when I try to fetch from origin. I have synced ALL of my github related generic credentials to my account on github and I'm still getting this:
`"Authentication failed. You may not have permission to access the repository or the repository may have been archived. Open options and verify that you're signed in with an account that has permission to access this repository."`
The under lying error is this:
```
`git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

(The error was parsed as 2: Authentication failed. You may not have permission to access the repository or the repository may have been archived. Open options and verify that you're signed in with an account that has permission to access this repository.)
```

**Comment by fthomas54** [comment]
I am still having the same issue.
After having tested everything listed on this page, the problem remain the same.
SSH key exists.
SSH key is added to the agent.
Everything seems ok but... there is no way to go from Git account on web to Git Desktop of go from Git Desktop to my Git account on web. In both direction the error message is the same.
I have tried to remove all and re-install everything several times without success.
All the commands I tested in Git Bash succeed:
$ ls -al #/.ssh
or
$ ssh -T git@github.com

What can I test to get some new idea before to  close my git account ?

**Comment by steveward** [comment]
@fthomas54 does your SSH key have a passphrase associated with it? 

You may also need to follow the steps here to verify that GitHub Desktop is using the correct `ssh` program:

https://github.com/desktop/desktop/issues/5641#issuecomment-421801704

**Comment by mattkefford** [comment]
> @I-keep-trying I'm glad you were able to work around the issue!
> 
> > Is SSH remote for using over command line? And HTTPS for the desktop app?
> 
> Both SSH and HTTPS are supported over the command line. We haven't spent much time on SSH support in the Desktop app, but if you have an external setup it can be detected.
> 
> HTTPS authentication and SSH authentication differ in a few ways:
> 
> * HTTPS credentials are stored by a credential manager configured in Git, SSH keys are managed external to Git by an agent process
> * HTTPS credentials are usually specific to a server (account-based), SSH keys - once the public key is shared like you added it to GitHub - can be used across many servers (identity-based)
> * HTTPS authentication is done for each connection (simpler, but limited), SSH authentication is done for each session (multiple commands can be run in a session, more complex to manage, but SSH is a well-known protocol)
> 
> > Where is SSH configuration done?
> 
> We have [a guide](https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/#platform-windows) for doing this yourself, but I haven't tested that this integrates nicely with Desktop - I _expect_ this to work, but maybe I've missed something.
> 
> > OK, just for the sake of being thorough, I looked around, and I cannot see anywhere, either in the desktop app settings, nor in the settings for any repository, nor in my GitHub profile settings, where I would go about doing SSH remote configuration. I don't even know what that is, let alone how to change it to HTTPS.
> 
> So the thing you're looking to configure is all specific to your local machine and covered by the guide I linked to above:
> 
> * you have an SSH public/private keypair on your machine
> * the public key is added to GitHub, so GitHub knows who you are
> * `ssh-agent` process is running, to handle requests from Git when connecting to GitHub over SSH
> * your `~/.ssh/config` entry points to your SSH keys
> 
> It's not the most user friendly experience, which is why Desktop will default to cloning over HTTPS. But we've had some pain points that users have encountered when dealing with SSH remotes, I'm going to roll them up into an issue this week and see if we can make this better.
> 
> Thanks for all the details, and best of luck in your adventures! Let me know if there's any other questions you have around this...

Hi, I tried following your steps but I still have the error message shown in GitHub Desktop "The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed."

I can access the repo from the command line, just not through GitHub Desktop which is a bit annoying.

I have generated the new SSH key and added it to my GitHub account but I don't see any step for making GitHub Desktop use the new SSH key?

I am on Ubuntu so I cannot use the alternate ssh program as suggested by steveward
