### ISSUE TITLE
Button, Dropdown & Shortcut in GitHub Desktop for Sync All Recursive Functionality

### ISSUE THREAD

**Issue by MaXFalstein** [desktop/desktop#2460]
I would like to be able to sync all of the repositories with a single click of a button, a few clicks in a dropdown or the simple use of a shortcut.

I often have many changes between mobile and desktop environments which are at home and my work desks (as many as thirteen computers). Remembering all of the repositories I worked on is okay for me but it does become an unnecessary chore before being able to continue working on my repositories.

**Comment by j-f1** [comment]
Why not just pull the repos as you start to use them? It should be really quick.

**Comment by shiftkey** [comment]
@MaXFalstein thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md). We also made a conscious decision to drop the sync behaviour from the classic apps - see #1565 for some back story on that. 

I added the `future-proposal` label to this issue and closed it so that we won't get overwhelmed with our backlog! We will revisit this in our next planning session.

**Comment by billygriffin** [comment]
@MaXFalstein Thanks for the issue! Because this hasn't been something we've heard from a significant number of people and the implementation difficulties of getting the idea of "sync" to work as expected from a user perspective, I'm going to remove the `future-proposal` label to indicate that it's not something we intend to support. That said, we're actively looking at improving the ability to visualize the difference between local and remote and whether your branch is up to date with the remote branch. Thanks for the suggestion!

**Comment by vczh** [comment]
My scenario is that, since git submodule cannot support diamond dependency, so I have to manually simulate it by:
1. Build repo a, and export something to a folder, e.g. a pair of C++ file combined from more than 100+ C++ files in this repo.
2. Before building repo b, copy things from that folder.

When I am just developing things in b, it doesn't matter since I don't update the dependency. But before I run build script in a "build computer", it needs to sync all repo and do all these steps.

Until now it is fine, but in Windows, Github Desktop doesn't install ssh keys to PowerShell, so the sync step is done by navigate to every repo and click sync, which is annoying.
