### ISSUE TITLE
[feature request] Add option of ignore space to diff panel

### ISSUE THREAD

**Issue by litefeel** [desktop/desktop#2477]
### Description

When the line end changes, the difference panel will be ugly.

### Version

version: 

**GitHub Desktop version:** [0.7.2] 
**OS version:** [Microsoft Windows [版本 6.1.7601]]

### Steps to Reproduce

1. git global core.autocrlf false
2. change line end
3. now  the difference panel will be ugly.

**Expected behavior:** no line added and no line removed

**Actual behavior:** every line removed and every line added

**Reproduces how often:** Aways

**Comment by shiftkey** [comment]
@litefeel thanks for the feedback. Line endings changes are important to report to the user, so hiding these away feels like it'll lead to more confusion.

**Comment by litefeel** [comment]
@shiftkey
yes, so add an option, user can enable or disable it, click the checkbox.

**Comment by shiftkey** [comment]
I'd rather address the underlying problem here and make the tool better than make this optional behaviour.

Two examples related to line endings that might help move discussion along:

 - when initializing a repository in Desktop, we encourage users to create a `.gitattributes` file at the root of the repository, which overrides `core.autocrlf` and makes it easier to work with repositories across different tools and operating systems.
 - #1859 was a discussion about a bug with line endings changing, and we merged #1906 to make the scenario clearer.

**Comment by litefeel** [comment]
Ok, when space to tab, or tab to space, I want to ignore whitespace change,
So, please add this option.

**Comment by shiftkey** [comment]
@litefeel we're discussing that over in #1940 - please add your comments there.

**Comment by shiftkey** [comment]
Closing this out as I think this problem needs to be discussed in a more specific context.
