### ISSUE TITLE
cursor will cycle history view when you cursor above first item

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#2479]
### Description

In the history view for a repository you can loop around from the first commit to the latest fetched commit, which is a bit confusing.

### Version

**GitHub Desktop version:** 0.8.0
**OS version:** Windows 10

### Steps to Reproduce

1. Add a repository with some history
1. Switch to the history tab
1. Select first commit
1. Press up arrow key

**Expected behavior:** first commit remains selected

**Actual behavior:** latest fetched commit is selected

**Reproduces how often:** 100%

**Comment by apap04** [comment]
For me, it just goes to the first commit made. 🤔 :hurtrealbad:

**Comment by j-f1** [comment]
I think he means hundreds or thousands of commits.

**Comment by shiftkey** [comment]
@apap04 @j-f1 the number of commits doesn't really matter here. I just think the up event when you're at the top of the list shouldn't circle back to the bottom of the list.

**Comment by iAmWillShepherd** [comment]
Added label `future-proposal` so that we are sure to discuss this further in our next sync up.

**Comment by starlingjon** [comment]
any hope of this getting worked on? it's very confusing when scrolling through commits in chronological order (or you've selected a range of commits ending with the most recent one using shift+arrows and you hit the up arrow to deselect while keeping the most recent selected) and all of a sudden you're scrolling through commits from months ago with no quick and obvious way to get back to where you were.

tip for anyone else who gets annoyed by this and ends up here (which i guess is probably nobody since this has been sitting for years) page up does not cycle so if you do need to get to the most recent commit holding page up is the way to go (though of course the more times you get cycled the more of the history loads and the longer it takes to get back to the top)

edit: looks like i didn't do enough digging, there is an open issue for it: #7679
