### ISSUE TITLE
Allow discarding of selected changes

### ISSUE THREAD

**Issue by rthery** [desktop/desktop#2481]
### Description

I often find myself wishing for more granularity in discarding changes. Right now you can either discard changes from file by file or discard them all. It would be nice to have a second option when right-clicking the header such as "Discard selected changes...", where it would discard only changes from the selected files in the list.

### Version

**GitHub Desktop version:** 0.8.0

**OS version:** Microsoft Windows [version 10.0.15063]

**Comment by shiftkey** [comment]
@rthery thanks for the feedback!

> It would be nice to have a second option when right-clicking the header such as "Discard selected changes...", where it would discard only changes from the selected files in the list.

This is currently where "Discard All Changes" resides:

<img width="324" src="https://user-images.githubusercontent.com/359239/29398635-13298c34-8369-11e7-8f43-1aca8884bb2b.png">

I think this belongs as part of #1712 because the real limitation at the moment is the fact that multiple files cannot be selected. I think if you can select multiple files then having "Discard Changes" in the context menu feels more discoverable than the header approach.

@rthery I've added this comment to that issue.

**Comment by rthery** [comment]
Sounds good, thank you @shiftkey!

**Comment by varkor** [comment]
@shiftkey: considering you can select (toggle) files using the checkboxes, why not simply use that for "Discard selected files..." from the header menu?

**Comment by amerikan** [comment]
How can I discard the files that are **ONLY SELECTED**? I find myself try do discard several but at the same time I also want to keep some. In the old Github desktop app, I remember I could do it.

**Example:**

I have 5 files with changes. I want to only discard 3 files and keep the other 2. If I select only the 3 files and click on Discard All changes, it prompts to discard everything instead of just offering to discard the 3 **selected** files.

Is this possible and am I just using it wrong?? Thanks!

**Comment by j-f1** [comment]
You have to use Cmd/Ctrl/Shift+click to select multiple files (not the checkbox, the whole row), then choose “Discard X files.”

**Comment by amerikan** [comment]
@j-f1 pretty counter intuitive way to do it, alas it worked so thanks.

**Comment by ionut-sultana** [comment]
@j-f1 Thanks!

**Comment by ajtruckle** [comment]
What about ability to discard changes to a selected set of lines or code? Possible?
