### ISSUE TITLE
Support more external editors

### ISSUE THREAD

**Issue by theconsultant** [desktop/desktop#2487]
I already use BBEdit on OS X, and would prefer to continue doing so. Is there a way I can add it in as my default editor? I can open files into it from the command line and it works fine as a git commit editor, as I have this setup in my ~/.profile :
```
#editor
EDITOR='/usr/local/bin/bbedit'
export EDITOR
```

If Github Desktop were to look for my existing editor in my environment variables.. that would be too easy ;-)

Could I add in the command line option to edit files using BBEdit in a config file somewhere? or, as a simpler alternative, if I could select a file (usually in History..) then invoke a menu item (Under Repository, for example) to show the file itself in the Finder, instead of the repo, that would resolve my issue.

### Version
Github Desktop 0.8.0
macOS 10.12.6

**Comment by shiftkey** [comment]
@theconsultant currently the "Open in External Editor" experience is focused on Atom, VS Code and Sublime Text. These were chosen because they are cross-platform and have a known CLI interface that Desktop can invoke. We don't use the `GIT_EDITOR` or `EDITOR` environment variables because those are focused on editing a file, rather than opening a folder.

I'm not opposed to integrating new editors, I just haven't had a chance to think about how to handle editors that don't quite fit the existing infrastructure (see #2484 for example).

Please read over the [`editor-integration.md`](https://github.com/desktop/desktop/blob/master/docs/technical/editor-integration.md) docs as a starting point.

**Comment by theconsultant** [comment]
Thanks @shiftkey .. is the beta using a different system than the classic github desktop app? Because in the desktop version I can go into history, right click a file and choose "open with external editor" which does invoke my `EDITOR` environment.

![screen shot 2017-08-17 at 7 03 53 pm](https://user-images.githubusercontent.com/1421526/29437536-18cd12e4-837f-11e7-8e95-bb779df861b4.png)

I've read that Technical Doc.. i'd guess some digging to understand the shim/cli interface would be useful, but not for the main project. Is there any further docs, or files, I can look at to see how it works?

Thanks for your help, much appreciated!

**Comment by shiftkey** [comment]
@theconsultant the new app isn't currently using `EDITOR` for opening a changed file - it's using Electron's `openItem` API, which defers to what the OS has registered for the file extension. This behaviour isn't set in stone, and is probably something we should discuss further.

cc @desktop/core

**Comment by shiftkey** [comment]
Support for Notepad++ (Windows-only) has been requested over in #2551 and while I thought it didn't support opening a folder like VSCode/Atom/Sublime do I see this is currently the case.

<img width="298" src="https://user-images.githubusercontent.com/359239/29900912-274d232c-8e38-11e7-8408-e222543a2500.png">

**Comment by Ben3eeE** [comment]
A [portable mode installation](http://flight-manual.atom.io/getting-started/sections/installing-atom/#portable-mode) of Atom is currently not supported.

This came up in https://github.com/desktop/desktop/issues/2585#issuecomment-329147670

**Comment by IdanAdar** [comment]
`<blasphemy>`I'd love to put WebStorm in the list of editors...`</blasphemy>`

**Comment by shiftkey** [comment]
The development version of Atom doesn't add itself to the registry, and thus won't be detected by Desktop - #2894

**Comment by shiftkey** [comment]
A request for Typora - #3015

**Comment by shiftkey** [comment]
A request for Brackets - #3041

**Comment by shiftkey** [comment]
Hey all, we've made some progress here with supporting external editors in #3038. You can also see the latest documentation about this here: [`docs/technical/editor-integration.md`](https://github.com/desktop/desktop/blob/master/docs/technical/editor-integration.md)

We'll continue to move requests for supporting different editors into this thread rather than adding them to our roadmap for a couple of reasons:

 - we're resource limited on tackling core features and quality in the short-term
 - this feature is relatively isolated from the rest of the codebase, so it's should be approachable for someone who wants to contribute
 - the people using these editors are going to be more familiar than us about how they work and how to hook into them

The [setup guide](https://github.com/desktop/desktop/blob/master/docs/contributing/setup.md) should help ensure you have everything you need to run the development version of Desktop and get hacking - you can run the app in development mode alongside with your existing Desktop installation.

If you stumble upon a problem or have a question about the integration itself, feel free to comment here. It's easy to either update the docs or fix the core integration, if that's what's required.

**Comment by shiftkey** [comment]
A request for Visual Studio 2017: #3148

**Comment by theconsultant** [comment]
Thanks to @niklasbr there's a PR in progress for BBEdit.. https://github.com/desktop/desktop/pull/2941

**Comment by coyoteconscious** [comment]
How about making _any_ editor available as an external, with the caveat that not all editors will have access to all features? I've been using the same editor for twenty years, and use it literally for everything (and have extensive clippings libraries and other custom stuff I use with it), but the only option I get for an external editor is Atom? Not cool.

**Comment by j-f1** [comment]
@coyoteconscious The challenge with supporting any editor is that we have to be able to figure out how to tell it to open a directory, which is hard or impossible to autodetect. What editor are you using?

**Comment by Haacked** [comment]
> @coyoteconscious The challenge with supporting any editor is that we have to be able to figure out how to tell it to open a directory, which is hard or impossible to autodetect. What editor are you using?

Rather than autodetect that, starting with a manual configuration with placeholders would make sense. That way Desktop could support any editor by telling Desktop exactly how to open a file or directory.

**Comment by shiftkey** [comment]
> Rather than autodetect that, starting with a manual configuration with placeholders would make sense. That way Desktop could support any editor by telling Desktop exactly how to open a file or directory.

I'm 👎  on this for a few reasons:

First, there's three variables that we need to track as part of launching an external program (these are the variables for shells, editors might be easier but I'm assuming worst-case complexity):

 - where the executable is located
 - any arguments that need to be passed to the executable
 - other options to provide when spawning the process in Node (some shells specify `cwd` or `shell`, others do not)

Second: we didn't have any sort of support for supporting arbitrary editors in the classic apps. We should be mindful about providing an escape hatch like this, because users do get attached to features once they ship.

Third: we've already had some success with editor and shell support from the community  - getting things merged into core means all users gets the benefits, rather than every user having to manage settings themselves. 

Fourth: this would deviate from what our shell integration supports - do we then let people configure that?

**Comment by Haacked** [comment]
Fair points. :smile:

**Comment by simoniz0r** [comment]
IMO, the user should be able to choose any editor and/or terminal.  GitHubDesktop could provide something like `%s` for the filename/directory that would be opened so that the user could add the necessary arguments to their editor to have the file/directory be opened.

Having a custom input box for the editor and terminal where I could enter something like `/usr/bin/code -r %s` would be great!

**Comment by gtraxx** [comment]
Hi, PHPSTORM is available in the list with Windows 10 ?

**Comment by agisilaos** [comment]
Hello @gtraxx! PhpStorm is not currently supported using Github Desktop on Windows. If you're considering adding this integration in Github Desktop for Windows, take a look at the [Editor Integration Doc](editor-integration.md). The team will be more than happy to review your PR and help you with your contribution. Let me know if you have any other questions.
