### ISSUE TITLE
In a mess and inexperienced. 

### ISSUE THREAD

**Issue by michaelpdebus5** [desktop/desktop#2491]
### Description

[Description of the issue]

### Version

**GitHub Desktop version:** [version here]

**OS version:** [version here]

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by shiftkey** [comment]
@michaelpdebus5 thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by michaelpdebus5** [comment]
I am unsure how to explain issues. Was not on internet from 2003-2013 but it seems like all my devices merged me with my partner who has given me several devices over the last couple years. I do not know much about logging but I feel stalked after finding "things" connected around the house watching and listening to me after our separation. I have, in anger, got rid of some devices that were "given" to me. Google user accounts including this one were created with his assistance... Concerned about new smart TV just gifted to me by him, the chrome I found plugged in, jvc stereo receiver CA-MXGB6 left behind, and the confusion of my phone number never being valid on the straight talk that he pays. 6785909179.
