### ISSUE TITLE
Feature request: syntax highlighting for diffs

### ISSUE THREAD

**Issue by Gama11** [desktop/desktop#2550]
Something that I think helps the readability of diffs immensely is **syntax highlighting**. Unfortunately, none of the Git clients I've tried (SourceTree, GitKraken, GitHub Desktop) have this feature. The only places I've seen it so far are GitHub's and GitLab's diff views. Here's a comparison:

GitHub Desktop:

![](http://i.imgur.com/cRaM4dF.png)

GitHub website:

![](http://i.imgur.com/gTwbaY3.png)

**Comment by shiftkey** [comment]
@Gama11 thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I added the `future-proposal` label to this issue and closed it so that we won't get overwhelmed with our backlog! We will revisit this in our next planning session.

**Comment by shiftkey** [comment]
Just dropping a note in here to say that this was added in #3101 and will be available in the next update.

**Comment by Gama11** [comment]
Wow, awesome. :)
