### ISSUE TITLE
"Open in Atom" menu item despite Atom not being installed

### ISSUE THREAD

**Issue by Gama11** [desktop/desktop#2551]
### Description

The `Repository` menu presents me with the `Open in Atom` option despite Atom not being installed.

![](http://i.imgur.com/odJr53n.png)

When I click it, I get an error message:

![](http://i.imgur.com/9wSdgSp.png)

In the configuration, only VSCode and Sublime are available (which is correct, both are installed). VSCode _seems_ to be selected, but as indicated by the menu item, it's not internally / in GitHub Desktop's config.

![](http://i.imgur.com/5Blbf0l.png)

Selecting Sublime and switching back to VSCode fixes it:

![](http://i.imgur.com/yMU1t9N.png)

### Version

**GitHub Desktop version:** 0.8.0
**OS version:** Microsoft Windows [Version 10.0.15063]

### Steps to Reproduce

1. Install GitHub Desktop (_or_ clear the local storage files in `AppData\Roaming\GitHub Desktop\Local Storage`)
1. Open the `Repository` menu
1. Observe the non-functional `Open in Atom` menu

**Expected behavior:** the menu item should match the selected external editor in `Options -> Advanced` with a fresh config
**Actual behavior:** it's always Atom

**Reproduces how often:** 100%

#### Additional Information

Atom used to be installed on my system, so maybe something is left-over that makes GitHub Desktop think it's still around. This seems unlikely as it's not presented in the external editor dropdown-menu however.

**Comment by coaperator** [comment]
And I have a standard Notepad ++ editor.
In the settings there is only Visual Studio Code, and Notepad ++ is not present.

**Comment by j-f1** [comment]
@coaperator The Notepad++ editor isn’t supported yet in Desktop.

**Comment by coaperator** [comment]
@j-f1 This is bad! Is intellij idea supported?

**Comment by shiftkey** [comment]
@coaperator please have a read of our documentation around the editor integration - https://github.com/desktop/desktop/blob/master/docs/technical/editor-integration.md

**Comment by tierninho** [comment]
Adding some color here as the bug is reproducible. Looks like no registry key is found for the editor selection. 

I have no external editors installed. Tested in Windows 10, v0.8.0.

<img width="445" alt="screen shot 2017-08-28 at 1 27 09 pm" src="https://user-images.githubusercontent.com/14828183/29785362-4e5705cc-8bf5-11e7-84b9-9362c261b0f2.png">
<img width="822" alt="screen shot 2017-08-28 at 1 27 25 pm" src="https://user-images.githubusercontent.com/14828183/29785363-4e5b7c7e-8bf5-11e7-9521-280d8fe9470b.png">

**Comment by Derkades** [comment]
I have the same issue in a fresh GitHub install on a fresh Windows 7 OS. Only Notepad++ installed.

**Comment by shiftkey** [comment]
@tierninho that's an interesting spot to have your Atom installation 🤔 🤔 🤔  

Thinking on this some more, I avoided populating the initial value set for your selected editor because I wanted to avoid adding any additional work to the critical path for launching the app. But the confusion here about displaying Atom even when it's not installed probably means I should revisit this.

**Comment by shiftkey** [comment]
@coaperator @Derkades please have a read of #2487 where we are talking about support for other editors.

**Comment by tierninho** [comment]
@shiftkey I believe Atom was downloaded there automatically, as I never moved it there myself. 🤔

**Comment by j-f1** [comment]
@shiftkey @tierninho I had this happen — That’s the location where Squirrel downloads the update to, and it somehow thinks that it’s the ”real” atom.

**Comment by shiftkey** [comment]
@tierninho @j-f1 well it seems to be failing as expected here (we check that the Atom shim exists before launching), so I'm not sure that one is something we can fix in Desktop.
