### ISSUE TITLE
let users work with tags in the app

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#257]
We currently display tags in TNG alongside remote branches and local branches:

<img width="594" src="https://cloud.githubusercontent.com/assets/359239/17654347/958aba9a-62e5-11e6-98f2-2e20d63fbd06.png">

<img width="233" src="https://cloud.githubusercontent.com/assets/359239/17654348/958c14d0-62e5-11e6-92e2-8ec78456de00.png">

For reference, this is the current behaviour:

<img width="594" src="https://cloud.githubusercontent.com/assets/359239/17654377/f0e8cda0-62e5-11e6-96a4-f7630dbb9d8e.png">

There's likely some UX things we can do differently this time around to make these a proper first-class feature:
- differentiate between branches and tags visually
- help users land in the pit of success when checking out a tag (which puts them in a detached HEAD state) by crafting a workflow to ensure they can switch from that state to a new branch quickly and painlessly when they want to make changes

I'm sure others have their own bright ideas around this.

cc @donokuda

**Comment by joshaber** [comment]
Thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I'm going to add the `future-proposal` label to this issue and close it out, so that we don't get overwhelmed with our backlog! We'll revisit these as part of our next planning session.

**Comment by billygriffin** [comment]
Since this is captured in the open issue #4829, I'm going to remove `future proposal` here. There's a lot of good info here though so we definitely want to refer back to this when we start looking at tags.
