### ISSUE TITLE
undo most recent commit button disappeared in latest GH version.

### ISSUE THREAD

**Issue by atifwaqar** [desktop/desktop#2572]

**Comment by shiftkey** [comment]
@atifwaqar thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by kireerik** [comment]
### Description

"Undo most recent commit..." button is not included in GitHub Desktop version 1.0.3. It is only included within the old GitHub Desktop version Chocolate-Covered Yaks (3.3.4.0) 50415df and before.

### Version

**GitHub Desktop version:** 1.0.3

**OS version:** Microsoft Windows [Version 10.0.15063]

### Steps to Reproduce

1. Open the app and go to the Repository tab and you can see the feature is not there.

**Expected behavior:** A "Undo most recent commit" should be there or maybe somewhere else. Personally I like version 3's interface better. It is more intuitive.

**Actual behavior:** The feature is not there.

**Reproduces how often:** always

**Comment by shiftkey** [comment]
@kireerik thanks for filling out the details. 

We no longer have this feature as a menu item, but instead put it below the commit form in the bottom-left corner.

<img width="340" src="https://user-images.githubusercontent.com/359239/31076344-5f15a710-a7c5-11e7-8079-558935bfd4ff.png">

 Let me know if you have any other questions about this feature.

**Comment by kireerik** [comment]
@shiftkey Thank you so much! I couldn't found it myself. It's on the right spot and shortening the name of the feature also makes sense in this context.

I prefer to use the old version 3, because of the interface is more user friendly in my opinion, but version 1 is faster (it is not crashing) in certain situations (lots of files or file content and so on).
