### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by JejePeyrat** [desktop/desktop#2600]
<!--

Have you read GitHub Desktop's Code of Conduct? By filing an Issue, you are
expected to comply with it, including treating everyone with respect:

https://github.com/desktop/desktop/blob/master/CODE_OF_CONDUCT.md

Update Github readme

OS version

List of files 

user interface

Visio docs

schema

--!>

**Comment by joshaber** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
