### ISSUE TITLE
I am having a very difficult time cloning my github desktop. What can I do to alleviate this difficult challange?

### ISSUE THREAD

**Issue by keppleaj** [desktop/desktop#2633]
### Description

[Description of the issue]

### Version

**GitHub Desktop version:** [version here]

**OS version:** [version here]

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by shiftkey** [comment]
@keppleaj thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by keppleaj** [comment]
[image: Inline image 1]

Brendan thanks for your response. Each and every time I attempted to clone
GitHub desktop, this is what shows up after the system attempt to clone.
The same message pops when I entered the requested information.

**Comment by shiftkey** [comment]
@keppleaj the image wasn't attached to the issue - are you able to attach this through the website?

**Comment by keppleaj** [comment]
Brendan, I have gotten my GitHub desktop cloning now. Thanks again.
Alva J. Kepple
