### ISSUE TITLE
GitHubDesktop ask credentials

### ISSUE THREAD

**Issue by m4ss1m0g** [desktop/desktop#2655]
SO Windows 10 
Git Version 2.14.1.windows.1
GitHubDesktop Version 0.8.0

I have cloned a external repository (TFS online) from command line, when required I write my credentials.
When using VSCode, VS2017, GitGui, no credentials are required.

When Using GitHubDesktop and try to Sync, Fetch or whatever it say 

> Authentication Failed

 and ask for credentials.

I have also setup caching password with 

`git config --global credential.helper wincred`

**Comment by niik** [comment]
Hey @m4ss1m0g,

GitHub Desktop currently doesn't use the globally configured credential helper, it's something that we'll likely explore going forward but for now you're going to have to give GitHub Desktop a valid username/password pair in order to perform network operations on your behalf.

Could you please attach a screenshot of the dialog you're seeing when you're trying to push or fetch?

**Comment by m4ss1m0g** [comment]
Here the screenshot.

![image](https://user-images.githubusercontent.com/4323707/30200156-fb09b4ee-9475-11e7-94ce-12f0a7046499.png)

**Comment by niik** [comment]
@m4ss1m0g Cool, so what happens if you give it your TFS username and password?  If your host (in this case Visual Studio Online) requires you to perform a web flow authentication you're going to have to create a personal access token from the website and use that as your password, see https://www.visualstudio.com/en-us/docs/setup-admin/team-services/use-personal-access-tokens-to-authenticate.

**Comment by m4ss1m0g** [comment]
I used [Alternate Authentication Credentials](https://www.visualstudio.com/en-us/docs/git/auth-overview) and it work, I didn't know you could also use the PAT (in this case I enter ONLY the PAT on the password field ?)

Will support the use of the _globally configured credential helper_ in near future ?

**Comment by niik** [comment]
> I used Alternate Authentication Credentials and it work

🆒 

> I didn't know you could also use the PAT (in this case I enter ONLY the PAT on the password field ?)

Right, you'd use your username as usual and then the PAT in the password field.

> Will support the use of the globally configured credential helper in near future ?

It's not currently on our [roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md) but it's something that we're interested in exploring down the line.

Gonna close this as resolved. Thank you @m4ss1m0g
