### ISSUE TITLE
support resetting the current branch to an earlier commit

### ISSUE THREAD

**Issue by flaminggenius** [desktop/desktop#2662]
### Description

See [https://stackoverflow.com/questions/46127908/git-revert-to-previous-version-does-not-return-all-files-that-were-commited](https://stackoverflow.com/questions/46127908/git-revert-to-previous-version-does-not-return-all-files-that-were-commited)

### Version 

**GitHub Desktop version:** [0.8.0]

**OS version:** [Windows 10]

**Comment by shiftkey** [comment]
@flaminggenius 

> If anyone can also help me understand why git completly corrupted my project files that would also be helpful

It's hard to tell from poking at the repository contents what's changed with those files in particular. But because Git has snapshots of the changes as you've made them, you can jump back to an earlier version of your code and re-test things against that version.

You can do this from the command line by running this command, where `{sha}` is the hash (the identifier) of with the commit:

```
$ git checkout {sha}
```

To go back to your default branch at any time:

```
$ git checkout master
```

To clarify, reverting a commit (using `git revert`) will add a new commit to the tip of your current branch which is the inverse of the original commit. This command is designed to "undo" the changes introduced by a commit - it's not about rolling back to that commit.

Anyway, let me know if you can find a commit where things are working as expected - that should help you trace where the regression was introduced.

**Comment by j-f1** [comment]
From the Stack Overflow question:

> ^files in git have a bunch of `<<<<<<<HEAD` Thrown everywhere in the code causing the .sln file to not load after getting all my files back  – [FlamingGenius](https://stackoverflow.com/users/7950643/flaminggenius) [15 hours ago](https://stackoverflow.com/questions/46127908/git-revert-to-previous-version-does-not-return-all-files-that-were-commited#comment79237627_46127908)

Sounds like a bad merge.

**Comment by shiftkey** [comment]
@j-f1 that often happens if the revert can't be applied cleanly, marking the file as conflicted. Let's see if we can trace to where the regression is introduced, rather than trying to revert things ad-hoc.

**Comment by flaminggenius** [comment]
What more info is needed? I managed to get all my files back from a backup folder however all my files look similiar to this [http://kot90.altervista.org/survius/img/Z25tZzAvEQ](url)

**Comment by shiftkey** [comment]
@flaminggenius looking at the C# it looks like something has replaced all instances of the `d` or `D` characters with `<<<<<<<HEAD`. I don't believe Git is responsible for this, as Git will add the conflict markers (with a space in between the `<` and `HEAD`) at the start of the line, like this:

```
<<<<<<< HEAD
foo
=======
bar
>>>>>>> cb1abc6bd98cfc84317f8aa95a7662815417802d
```

I'm honestly not sure what's causing this, but given the files are marked as modified in Visual Studio it looks like something in the editor might be responsible.

**Comment by flaminggenius** [comment]
I found the issue I had it pasted in the replace all when I was searching for all the head things that were inserted I had it in the replace all field instead of the find field my bad  but that still doesn't resolve the issues of my filesson being corrupted after revertING and there being <<<head place through the code I was able to get a backup luckily through a release I posted on github but I feel like there should be a feature we can post commits as `added new table` and then post a new commit `added new button` and we wanna go back to `added new table` all commits after that go away and we just go back to the exact state we were at when we submitted `added new table`

**Comment by shiftkey** [comment]
@flaminggenius I think what you're interested in is the `reset` and `checkout` commands in Git - this will let you switch between points in time in your repository history. This [StackOverflow answer](https://stackoverflow.com/a/4114122/1363815) covers the options available and are relevant to the issue at hand.

**Comment by shiftkey** [comment]
> there should be a feature we can post commits as `added new table` and then post a new commit `added new button` and we wanna go back to `added new table` all commits after that go away and we just go back to the exact state we were at when we submitted `added new table`.

This is a feature I'm really worried about because as soon as a branch is published to a remote repository, you can cause all sorts of headaches to other people by changing the history underneath them.

This is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md), so I've tweaked the title to reflect the suggestion, added the `future-proposal` label to this issue and closed it so that we won't get overwhelmed with our backlog! We will revisit this in our next planning session.

**Comment by billygriffin** [comment]
Hi @flaminggenius, thanks for the issue! We've discussed this internally and for the reasons @shiftkey described above, we think there's a lot of risk in bringing something like this into Desktop. We're happy to revisit if we find that others are struggling with things that might benefit from something like this, but I'm going to remove the `future-proposal` label to indicate that we don't intend to support it. Thanks again!
