### ISSUE TITLE
hola tengo el siguinete conflicto: Commit failed - exit code 128 received, with output: '*** Please tell me who you are. Run   git config --global user.email "you@example.com"   git config --global user.name "Your Name" to set your account's default identity. Omit --global to set the identity only in this repository. fatal: unable to auto-detect email address (got 'camil@Camilachurruca.(none)')'

### ISSUE THREAD

**Issue by camilachurruca** [desktop/desktop#2666]
### Description

[Description of the issue]

### Version

**GitHub Desktop version:** [version here]

**OS version:** [version here]

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by j-f1** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

---

(máquina traducida por Google, lo siento)
¡Gracias por contactarnos!

Requerimos que la plantilla se complete en todos los nuevos temas. Hacemos esto para que podamos estar seguros de que tenemos toda la información que necesitamos para abordar su presentación de manera eficiente. Esto permite que los mantenedores pasen más tiempo arreglando errores, implementando mejoras y revisando y combinando solicitudes de extracción.

Gracias por la comprensión y la reunión de nosotros a medio camino 😀
