### ISSUE TITLE
Have "update from branch" button on the top level?

### ISSUE THREAD

**Issue by danqing** [desktop/desktop#2667]
So I've raised some design questions in #2067 - I'm not sure if any of them are being considered, but to go down the same path, I'd also love to see the "update from master" button (or merge into branch) be on the top level (i.e. in the application UI), like in the old github desktop.

I don't know if GitHub collects usage analytics, but I think the old app is really nicely designed in terms of UX - most commonly used features are very easily accessible, including the repo list, create new branch button, and the update from branch button.

I have two computers and I installed the new app on one of them a few months back. I have to say that I still find it considerably harder to use than the old app, and as a result I find myself using terminal more often there.

This is not a "bug", and design is surely opinionated, but just want to (re-)express mine.

Thanks!

**Comment by joshaber** [comment]
Thanks for the feedback @danqing!

As part of 1.1 we're gonna be exploring how we can better surface the relationship between the default branch (`master`) and your current branch. We're tracking that in https://github.com/desktop/desktop/issues/2639) and I'm gonna lump this issue in with that one since it seems possible we'd add an "Update from X" affordance.

**Comment by WaleedAshraf** [comment]
Much needed feature 👍
