### ISSUE TITLE
Show CI status in commit history

### ISSUE THREAD

**Issue by mischnic** [desktop/desktop#2668]
### Description

Now that there's PR CI status planned (#2643), what about showing the CI status for a commit like on github.com (I am referring to the small symbols in the commits list) ?

### Steps to Reproduce

**Expected behavior:** Show the status icon in the commit history (e.g. next to the title)

**Comment by joshaber** [comment]
Thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I'm going to add the `future-proposal` label to this issue and close it out, so that we don't get overwhelmed with our backlog! We'll revisit these as part of our next planning session.

**Comment by billygriffin** [comment]
Thanks for the issue @mischnic! Because this isn't something we've seen as something that would solve a problem for many users, we're going to remove future proposal here. As with all issues, we're happy to revisit if we see evidence that more users would benefit from something we initially didn't think we'd support. We really appreciate the idea and hope you're still finding value from Desktop.
