### ISSUE TITLE
env: node: No such file or directory

### ISSUE THREAD

**Issue by ronaiza-cardoso** [desktop/desktop#2686]
### Description

When I commit my changes this message appear:
```env: node: No such file or directory
 (1)```

### Version

**GitHub Desktop version:** Latest
**OS version:** macOS Sierra 10.12.6 

### Steps to Reproduce

1. Add things to commit
2. Hit the commit Button
3. Message appear

**Expected behavior:** The commit happens, on tutorial page the commit works like the expected

**Actual behavior:** The error message appear

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by joshaber** [comment]
Hi @ronaiza-cardoso, could you put a screenshot in here for us to take a look at? Thanks!

**Comment by ronaiza-cardoso** [comment]
Sure, 
![image](https://user-images.githubusercontent.com/7999914/30383211-91590ba2-9877-11e7-8d78-7b6218b27c7a.png)

**Comment by joshaber** [comment]
Thanks! It looks like you're using the Classic Mac app. This repository is for issue with the GitHub Desktop Beta, rewritten on Electron. You can download it from http://desktop.github.com and it may well solve this problem.

I'm gonna close this since this isn't an issue about the Electron beta, but feel free to open a new issue if it's a problem in the beta too.

**Comment by ronaiza-cardoso** [comment]
Yes, It worked! Thank you.
