### ISSUE TITLE
Run the linters on Travis on Linux

### ISSUE THREAD

**Issue by j-f1** [desktop/desktop#2717]
Currently, the project is tested on macOS using CircleCI and on Windows with AppVeyor. Since Travis has quick-loading container-based builds, we should use those to run our linters, and just run the tests on macOS and Windows.

**Comment by shiftkey** [comment]
For reference, the work to get tests also passing isn't too hard once this gets re-enabled: https://github.com/shiftkey/desktop/pull/1 (integration tests were passing on `1.6.11`, gotta figure out whether that's a real issue).

**Comment by j-f1** [comment]
I think we should run the tests on the actual target OSes, because otherwise we won’t catch OS-specific issues. (not saying we shouldn’t run on Linux, just that we should test the other 2 OSes too)

**Comment by shiftkey** [comment]
We're tracking #273 for something rather similar to this, and I'd rather just get the whole CI process in place in one hit and close that issue out. Mind if we close this out in favour of that original issue?

**Comment by j-f1** [comment]
Sure, but I think that it would be valuable to run both the tests and the linter in separate jobs, so that we can get feedback on broken tests faster, and maybe run the tests in different environments without wasting time linting each time.

**Comment by shiftkey** [comment]
Right, now I'm understanding the context. It'd be neat to experiment with how much we can speed this up, but I'm :thumbsup: with breaking this out into a separate job.

**Comment by say25** [comment]
This would imply this is done no? 

https://github.com/desktop/desktop/blob/3e6e969bf3f2d6e68fd8e4e1c1b07c5fbb39749e/.travis.yml#L53-L57

**Comment by krischanglaesel** [comment]
Am 14.11.2017 1:32 vorm. schrieb Steven Yeh <notifications@github.com>:

**Comment by joshaber** [comment]
No, I think the idea behind this issue was to split linting into a separate job so that it could run concurrently with the build step and provide faster turnaround.

**Comment by shiftkey** [comment]
I took a shot at this in https://github.com/shiftkey/desktop/pull/28 and was rather disappointed with the results:

 - `yarn install && yarn lint` takes ~80s on Travis - that seems to be the bare minimum to ensure we're running the right tools when linting, without splitting up the root `package.json` further (we did float this idea [here](https://github.com/desktop/desktop/pull/3949#issuecomment-366973960))
 - by splitting up the Travis build, we can get feedback on linting in about 3.5mins
 - the rest of the overhead is installing dependencies and setup - not sure how much lower we can get this using the hooks in Travis

But I'm currently :thumbsdown: on this current approach for other reasons:

 - the secondary Travis build doesn't become magically quicker - [this build](https://travis-ci.org/shiftkey/desktop/jobs/347153923) took 16mins 30s for example
 - by having the lint running on one platform, we become reliant on Travis being available and providing timely feedback
 - each platform is setup to fail the build as soon as it accounts an issue, so we are catching things as quickly as possible even if it does take a bit longer
 - having all platforms fail in the consistent way keep things simple - for reviewers and contributors

If someone else feels strongly about this, they're more than welcome to explore it. For now I'm fine with keeping the status quo and optimizing the build in ways that work for all platforms (like seeing what gains webpack 4 gives us).

I'm going to close this out on Friday unless I hear convincing arguments otherwise cc @desktop/core @desktop/comrades

**Comment by j-f1** [comment]
> `yarn install && yarn lint` takes ~80s on Travis

From [this build log from your PR](https://travis-ci.org/shiftkey/desktop/jobs/347153922), I see some ways to decrease this time:

- It looks like you’re running `yarn` twice — Travis runs it automatically at L627, and you run it manually at L644. Removing the second install should take off ~20 seconds.
- If you don’t make Yarn rebuild everything in `app/node_modules`, which we don’t use for linting, you could save a lot of time since running `yarn` if nothing needs to change is practically instant.
