### ISSUE TITLE
Label capitalization consistency: Create repository button

### ISSUE THREAD

**Issue by jsejcksn** [desktop/desktop#2720]
### Description

On the web, the text in this button is `Create repository` and on desktop it is `Create Repository`. See screenshots in #2719.

### Version

**GitHub Desktop version:** 0.8.2

**OS version:** macOS 10.12.6

**Comment by j-f1** [comment]
This is because macOS uses Title Case for button/menu labels, while Windows uses Sentence case. On Windows, you’ll get “Create repository.”

**Comment by jsejcksn** [comment]
@j-f1 Thanks for responding. I think you're referring to the macOS HIG doc for [Push Buttons](https://developer.apple.com/macos/human-interface-guidelines/buttons/push-buttons/).

If the app is really efforting to follow these guidelines, then aren't many of the other interface aspects that make it consistent across platforms also in violation of them? I see another just in regard to the buttons in that dialog: **Adjust a push button’s width to accommodate the title**.

In this context, I see that consistency between platforms and adherence to macOS HIG seem to be at odds in many cases. Has there been an established position by the team on the ordering of these two priorities? Having an answer to that question might help me (and others) understand whether some platform inconsistencies are intentional or not.

In regard to the capitalization issue, I found this article to eloquently express the juxtaposition between title/sentence case: https://medium.com/@jsaito/making-a-case-for-letter-case-19d09f653c98

**Comment by joshaber** [comment]
Yeah, our relationship with the HIG is ... complicated.

We do try to be a good citizen on each platform, even though our UI is obviously not native. Title Case vs. Sentence case is one example. Button order in dialogs is another.

So far those are the places where we've found consistency isn't worth the "feels weird" factor.

@desktop/design you all have anything to add or correct there? 😄

**Comment by niik** [comment]
> @desktop/design you all have anything to add or correct there? 😄

Not really, I think you put it quite well. Chances of us reaching 100% compliance with interface guidelines on both platforms are slim and 100% is not a goal. The way I think about it is; if someone who has been using a certain platform (say macOS for example) for a long time feels that some action is going against their muscle memory or "just feels wrong" then we really need to look at that. Dialog button order is a great example of that. Title case vs sentence case is important on macOS due to the high level of uniformity there, it would just "feel wrong" if we didn't title case buttons, menu item, and dialog titles.

We're obviously not using OS-provided controls on either platforms and trying to "fake it" was never on the map for us. We have a custom UI and we don't try to hide that but we want all platforms to feel welcome so we spend time on things like title case, button order, tab order (especially on Windows), keyboard shortcuts etc. That's not to say we're done, this will be a continually evolving thing.

As for this issue, I'm going to close it out as the behavior is per-design.
