### ISSUE TITLE
history UI out of sync with repository after pulling with merge

### ISSUE THREAD

**Issue by 1nfinite9** [desktop/desktop#2737]
### Description

Commits that were created and pushed to remote repository from other people are not shown in the History tab.

### Version

**GitHub Desktop version:** 0.8.2

**OS version:** Microsoft Windows [10.0.14393]

### Steps to Reproduce

1. Commit **A** on local repository on **Mac** and push to remote (shared bare repository not on Github)
1. Commit **B** on local repository on **Windows** before pulling **A** from remote
1. Pull from remote, merge and push changes back to remote

**Expected behavior:** Both commit **A** and **B** should appear in the History tab.

**Actual behavior:** On Mac, both commits are shown, but on Windows only the local commit and merge commit is shown.

**Reproduces how often:** Only initially after pulling the changes from remote. After restarting, all the commits are properly shown again.

**Comment by joshaber** [comment]
Thanks @1nfinite9!

When you pull on Windows, are you on the Changes or History tab? If you switch to a different repository and back, does it show the commits?

**Comment by 1nfinite9** [comment]
Thanks for your reply, @joshaber.

I tried pulling on both the Changes and History tab but same result.
Also got same results even after changing to different repository.

**Comment by 1nfinite9** [comment]
Still happens on version 1.0.6.

What else can I provide that will help with reproduction?
Could it be because a merge is happening when I pull on Windows?

**Comment by shiftkey** [comment]
@1nfinite9 this has kind of fallen down the list because the repro requires a bunch of setup. The only additional things I can think of is screenshots the different history views show them being different, but that's minor.

**Comment by shiftkey** [comment]
There's definitely something up in here, but I'm not sure it's the original issue as reported.

> 1. Commit A on local repository on Mac and push to remote (shared bare repository not on Github)
> 2. Commit B on local repository on Windows before pulling A from remote

I wasn't able to reproduce this scenario as-is because - **if you're also working from a bare repository on the Windows side** - this should end up in a known limitation of Git when you pull at this point:

<img width="436" src="https://user-images.githubusercontent.com/359239/33744994-599a7a1e-dc08-11e7-999e-b04c0b64f177.png">

This happens when you create two distinct "initial" commits in a Git repository and try to merge them. We're tracking this in https://github.com/desktop/desktop/issues/1484 which has some extra details.

With that in mind, I went down a slightly different path to try and recreate the issue with not showing all commits.

Here's the steps I went through (this is on `1.0.10`): 

 - blank repository on GitHub
 - commit and push from macOS
 - clone on Windows (so they both have first commit)
 - create another commit on macOS and push
 - create a commit on Windows
 - fetch so that you see both a local and remote commit
 - pull to merge remote commits
 - push to send the merge to the remote

So here's what we have:

<img width="621" src="https://user-images.githubusercontent.com/359239/33744938-09ecf208-dc08-11e7-8469-235c69708bbb.png">

And using [`git lg`](https://coderwall.com/p/euwpig/a-better-git-log) to look at the log visually:

```
*   a66d84d - (HEAD -> master, origin/master) Merge branch 'master' of https://github.com/shiftkey/testing-blank-repo-commits (3 minutes ago) <Brendan Forster>
|\
| * 8d438c7 - added third file (3 minutes ago) <Brendan Forster>
* | 44caf1a - words go here (4 minutes ago) <Brendan Forster>
|/
* e4cebda - added first file (6 minutes ago) <Brendan Forster>
```

And here's the History view for Windows:

<img width="312" src="https://user-images.githubusercontent.com/359239/33745161-43b99f94-dc09-11e7-8f33-f52300ce0e0c.png">

But on macOS we're actually missing one commit (the second one, which was created on macOS):

<img width="270" src="https://user-images.githubusercontent.com/359239/33745174-55746110-dc09-11e7-922e-486b1eda671f.png">

And this comes good after restarting the app, which is what @1nfinite9 also saw:

<img width="278" src="https://user-images.githubusercontent.com/359239/33745232-bf6d27aa-dc09-11e7-8148-5bab595ddb77.png">

Not quite sure where this is lurking, but at least I've now seen it with my own eyes.

**Comment by vendredvd** [comment]
La boutique en ligne Vendredvd a pour but de mettre en relation des acheteurs avec des produits informatiques. Créé en 2011, vous avez sûrement déjà du entendre parler du site www.vendredvd.com. En effet, on y trouve des produits neufs ou d'occasions dans de nombreux domaines. Si vous êtes à la recherche d'une pièce informatique, pas de problème avec la boutique en ligne Vendredvd. Ce site fera également le bonheur des fan d'Apple iphone, ipad, ipod, ipad pro, imac, macbook pro, macbook, macbook air, macbook pro retina, macbook retina. Que vous soyez à la recherche de matériel informatique ou téléphonie, vous trouverez quantité d'articles à des prix défiant toute concurrence. Les passionistes vont elles aussi adorer le site www.vendredvd.com. En effet, ce dernier regroupe des milliers d'articles souvent introuvables ailleurs. Si vous recherchez
désespérément une pièce dont vous ignorez son existance, il existe certainement sur la boutique en ligne Vendredvd. Il en est de même pour les produits diverts tels que les quincailleries, concernant le paiement, le site est très sécurisé, alors vous n'avez plus qu'à vous faire plaisir !McAfee protégé également les acheteurs sur vendredvd.com. Si vous avez envie de payer votre commande à la livraison pas de problème il suffit de nous envoyer un mail. Vous en trouverez des neufs ou d'occasion sur le site www.vendredvd.com. Alors bonne visite sur la boutique en ligne
Vendredvd et bon shopping notre boutique en ligne!

**Comment by mungojam** [comment]
Getting this too in latest version (1.2.2) on windows:

The two commits that my colleague made show up in `git log` but not in GitHub desktop. His later changes do show up.

![image](https://user-images.githubusercontent.com/3154635/40967065-0b220080-68aa-11e8-8d29-d604feb1b9eb.png)

**Comment by mungojam** [comment]
Now discovered https://github.com/desktop/desktop/issues/3704 which covers my issue and describes how it can be worked around by restarting GitHub Desktop
