### ISSUE TITLE
Column widths are limited — would love to remove those widths

### ISSUE THREAD

**Issue by tjdraper** [desktop/desktop#2745]
### Description

(forgive me if this is an issue already, I looked and couldn't find it)

The various columns in the application are constrained to certain max widths — which makes using the app on larger screens frustrating. Particularly when being able to expand a column to see all the data would be very helpful. The application should not place a width limit on columns so that the user of the application can determine the column widths desired at any time.

<img width="974" alt="github-columns" src="https://user-images.githubusercontent.com/3803475/30488007-bea92c48-99fa-11e7-8e1c-12c8c9f66f39.png">

### Version

**GitHub Desktop version:** 0.8.2

**OS version:** macOS Sierra 10.12.6

### Steps to Reproduce

1. Try to resize a column in the app to any width wider than the limit

**Expected behavior:** Column should resize to any size user would like

**Actual behavior:** Columns have a max-width limit

**Comment by joshaber** [comment]
Thanks @tjdraper! We've done some work to increase those limits, but I agree it'd be nice if they'd be entirely dependent on the window size.

**Comment by tjdraper** [comment]
I’d argue they should be independent of window size and be entirely user defined, but I’d certainly accept them being wider when the window is wider. 🙂

**Comment by niik** [comment]
While this issue pertains to all resizable panes I think the answer I wrote in https://github.com/desktop/desktop/issues/1588#issuecomment-329405096 applies here as well.

**Comment by arfordweb** [comment]
From @niik 's other comment and subsequent responses, it seems the max-width was a temporary solution.  The real solution would be to handle the case for when the panes that currently have max-widths on them have been made wide by the user, then the window is made narrower than the wide column can accommodate.  The widths of those panels need to be recomputed, which sounds to be non-trivial.

I would, though, like to throw in that I'd love to see the column of file path/names expandable as large as we'd like to expand it, in the hopes that maybe it gets prioritized.  It's by far my biggest UX frustration with this otherwise beautiful and intuitive app.

**Comment by glennreid** [comment]
Rather than enforcing MAX constraints, you can just enforce MIN constraints.  The only reason to have a MAX is so you can't a column so wide as to reduce its neighbor to a size that's too small.  Enforcing a MIN limit fixes this, and lets people decide how they want to apportion the window width across columns.

The fewer hard limits the better.  That's a tenet of all programming.

**Comment by richardthombs** [comment]
Surely this is a really quick change? Can't see how @joshaber can say that "we've done some work" - what did you do? Add 10% to the limit or something? Can't you please just remove the limit?

**Comment by iAmWillShepherd** [comment]
@desktop/design How do you feel about replacing the max-width constraint with min-width as @glennreid suggested?

**Comment by cocco3** [comment]
Has there been any movement on this? Seems instead of setting the width to 230px, you can make that a min-width and do `flex-grow: 1` to take up as much space as possible.

**Comment by stonstad** [comment]
Please... some of us have widescreens and the fixed column width is absurdly small when long file paths are used.  +1 for this issue.

e.g. 

![image](https://user-images.githubusercontent.com/3117255/47232642-d8760080-d395-11e8-81b1-916a93860637.png)

**Comment by rog1039** [comment]
Same exact issue as @stonstad Would really love to be able to make the changes/history sidebar wider. I can't see the full path to the files on the left in file view or the complete commit message in history view and my diff ends us just being half whitespace since there is so much unusable room.

Similarly, when in History view examining commits, both the history view as already mentioned is too narrow, and additionally, the file list in the 2nd sidebar showing the commit files is also too small so all the paths get truncated with ellipses even though again half of the diff view on the right is all whitespace.

It's like Github Desktop can't use any extra width at all beyond 1800 pixels or so. With 4k monitors that means ((3840-1800)/3840) about 53% of the application window is just whitespace.

Somewhere else I saw mention of perhaps utilizing some min-width's throughout to prevent sidebars from getting too small while removing the max widths so we could use the rest of our monitor to see more information. Not sure if that is a viable solution to this issue or not but it would be great to have the max-width limits removed.

Thanks.

**Comment by iwanPlays** [comment]
![image](https://user-images.githubusercontent.com/25465450/58647686-5c1ea500-8308-11e9-851b-17668a9b274a.png)
example of the middle column being useless

**Comment by shacker** [comment]
This issue is a frequent problem for my team, where we have a lot of very long paths that can look indistinguishable in the truncated version with non-resizeable column. 

Alternatives to column resizing might be:

A) Show full path on hover
B) Right-click | "Copy file path" 

We just need *some* way to figure out which file we're looking at... (kind of important for a tool that's all about working with files) :)

**Comment by tierninho** [comment]
@shacker You can see the full path on hover. I imagine if we increased the target area to include the entire box and not just the text then it would be more discoverable.

![Screen Shot 2019-09-03 at 2 14 54 PM](https://user-images.githubusercontent.com/14828183/64216647-68f5ec00-ce55-11e9-9f76-198f70bfb117.png)

Apologies if this is giving you problems.

**Comment by shacker** [comment]
@tierninho Ah, so it does! Not sure how I missed that (unless this is a new feature?) Looks like it only appears on hover after 1 second, perhaps I was just moving too quickly. Thanks, this is helpful.

**Comment by stonstad** [comment]
@tierninho It's a substandard end user experience.  Not allowing the divider to be dragged just doesn't make sense given the importance of content contained in either side.

**Comment by tierninho** [comment]
Another request for the same: Ref https://github.com/desktop/desktop/issues/9263

**Comment by specter78** [comment]
Seems to show how misplaced GitHub's priorities are, when something so trivial but so annoying and also important is not resolved even in 3 years.

**Comment by utilityboy** [comment]
Given the adoption of monorepos, this issue is further exacerbated due to tooling conventions like yarn workspaces or similar building out a fairly deeply nested directory structure.  My team is consistently shy by about 50-100px for viewing of full paths for most of our work.

**Comment by Lars-jnk** [comment]
After 3 years nothing happend. I guess the would take less time to implement it then to read all the comments here.

**Comment by utilityboy** [comment]
@Lars-jnk there is a PR graciously provided by @marzepani that hopefully will be merged soon.  🤞🏼

**Comment by Eilon** [comment]
BTW this is the PR: https://github.com/desktop/desktop/pull/10706

**Comment by steveward** [comment]
Requested in https://github.com/desktop/desktop/issues/12576.

**Comment by utilityboy** [comment]
@steveward are there any actions that can be taken on https://github.com/desktop/desktop/pull/10706?  Is there something missing you'd like to see in this PR?

**Comment by steveward** [comment]
Requested in https://github.com/desktop/desktop/issues/13157.

**Comment by rockmandash** [comment]
This is critical since I can't see the location of every file name every time I read commit history; I have to wait for every tooltip to appear. And I've been looking on those tooltips for three years.

**Comment by glennreid** [comment]
[Re-posting my comment from 2018. This is a trivial fix]

Rather than enforcing MAX constraints, you can just enforce MIN constraints. The only reason to have a MAX is so you can't make a column so wide as to reduce its neighbor to a size that's too small. Enforcing a MIN limit fixes this, and lets people decide how they want to apportion the window width across columns.

On the Mac version, you can probably do this in Interface Builder using the constraints mechanism -- doesn't even require any programming.

**Comment by jyxjjj** [comment]
any new progress?

**Comment by stuartmcmahon-h3d** [comment]
This is the number 1 reason I open Sourcetree.
Number 2 is when I want to view the history of an individual file.

**Comment by Luiz-Monad** [comment]
How about this . an amazing invention. 
![image](https://user-images.githubusercontent.com/4574729/150859418-9b14d454-5947-4ca7-8ae8-c11f64830dbf.png)
