### ISSUE TITLE
Who is the owner of GitHubDesktop 3.3.4? It wasn't updated with security fix.

### ISSUE THREAD

**Issue by JarLob** [desktop/desktop#2758]
### Description

Excerpt from https://desktop.github.com/:
"Not ready for Desktop Beta?
Desktop Beta gives you the newest desktop features before they're officially released. If you're looking for an earlier release, the official GitHub Desktop is still available. https://github-windows.s3.amazonaws.com/GitHubSetup.exe"

https://desktop.github.com/release-notes/windows/ 

Who is the owner of the old "official" version?
GitHub Desktop for windows 3.3.4 still contains vulnerable Git version. Meanwhile Desktop Beta was updated in version 0.8.0

### Version

**GitHub Desktop version:** 3.3.4

**OS version:** All Windows (Mac possibly too)

### Steps to Reproduce

1. Open C:\Users\[your user name]\AppData\Local\GitHub\
1. Find subfolder PortableGit_f02737a78695063deace08e96d5042710d3e32db
1. Check git.exe version

**Expected behavior:** Either the insecure 3.3.4 version should be removed and not advertised as an official one or it should be updated to contain Git with the security fix.

**Comment by j-f1** [comment]
The beta version will get its 1.0.0 release this week (hopefully!), and the old versions will be deprecated and removed from the Desktop homepage at that time.

**Comment by iAmWillShepherd** [comment]
The old GitHub desktop will get sunsetted very soon and all future development will take place in this project.

**Comment by JarLob** [comment]
Glad to hear, but the issue is not closed.

**Comment by JarLob** [comment]
@iAmWillShepherd @j-f1 Will 3.3.4 users get a notification that an update is available in the About section of the application itself after 1.0.0 release? It is actually not enough just to release 1.0.0 and to remove the download link to the old version. Users who do not read news are exposed to the security threat more than for a month and will continue to be.

**Comment by j-f1** [comment]
There are plans to put a banner in the old app linking to this one.

**Comment by metalim** [comment]
Huge PING! on this one. Why issue is closed?
I just went through several freaking "WTF I was doing in the future?" and "What malware I have installed?" moments, when trying to compare 2 different github apps I have installed, one saying it's 3.3.4 and the other 1.0.11, both saying they are official Github Desktop and have no updates. And official website telling latest one is 1.*.
Please fix this.

**Comment by j-f1** [comment]
The banner should be showing up about when we release 1.1.

**Comment by JarLob** [comment]
Could you at least reopen and properly track the issue? You said “this week” when I reported it in september. Calculate yourself for how long you have been exposing your users to a security threat.

**Comment by iAmWillShepherd** [comment]
> Could you at least reopen and properly track the issue? You said “this week” when I reported it in September. Calculate yourself for how long you have been exposing your users to a security threat.

@JarLob 

We already have an issue, located in another repo, with this work to be done. This item was closed since the work that needs to be done is unrelated to this project.

**Comment by CollinChaffin** [comment]
I totally agree.  This is really a cluster#(#&$.  I too (on many systems) have not one, but TWO apps installed by official Github supported downloads (all recent), and somehow I am expected to be a mindreader and as a DEV myself not sure what thought went behind even with a total rewrite/rework to do this with your versioning and still have a 3.3.4 on desktops and expect people on the Github product webpage to click the release notes/changelog/about and see it refer to 1.11 as the current release, and not be scratching their heads?!?  Never good to work backwards personally I would have started my rewrite from a mature enough client that it's version # was already up to v3.x perhaps to v4, not v1 without also changing the product name to denote it is a totally new product line.

Looks like it is ~~a nice automatic process by the installer of 1.11~~ up to me/us to manually carve 3.3.4 (currently a serious security risk) off of our systems ourselves, since the "official" 1.11 installer ~~is so thorough in checking for prior installations~~ didn't even recognize the prior "official" github desktop app was installed - which if I read above correctly was the actual reason this topic was opened to begin with that was then for some reason so quickly deemed "closed"/solved without actually taking any action to help resolve.  

IMO this is a pretty darn significant issue considering how many now have this abandonware version 3.3.4 left behind as hacker-bait for all time (while bearing the Github logo).  I second that perhaps this topic was closed a bit prematurely and could have been a bit more sensitive to the folks consuming this product and coming here for support on it.   

:_demonstration:

**Comment by jpluimers** [comment]
> We already have an issue, located in another repo, with this work to be done. This item was closed since the work that needs to be done is unrelated to this project.

@iAmWillShepherd can you please link to that issue so it is clear which one to track?

**Comment by iAmWillShepherd** [comment]
@jpluimers unfortunately I cannot, the issue is in the repository for GitHub Desktop for Windows, which is not an OSS project.

> Note that https://github-windows.s3.amazonaws.com/GitHubSetup.exe is still on-line, so please try to bring that off-line.

We are aware it's still up. We are still deciding what date we're going to pull the plug on the old GitHub Desktop clients (macOS and Windows).
