### ISSUE TITLE
cache user repositories locally

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#2770]
See https://github.com/desktop/desktop/pull/2436#issuecomment-326069611

We don't cache repositories retrieved from the API, so it's really slow on each usage (not just the first) when you have access to hundreds of repositories.

Might also need some design thought about managing the interactions (show cached repositories, while fetching new repositories to refresh, and then merging) so that the app refreshes without interrupting the user. 

cc @desktop/design for feels

**Comment by joshaber** [comment]
From an implementation perspective, there's a few things we should weigh:

1. Cache in `AppState`. It's lost across relaunches, but it'd be an easy win.
1. I'm a little surprised Chromium's caching isn't giving us more here. It might be worth looking into.
1. Could/should we cache the JSON response vs. going through the work of storing them in a database?

**Comment by joshaber** [comment]
@niik and I talked about this a bit, specifically around the race condition where you create a new repository on dotcom, go to clone it in Desktop, and it's missing because we haven't refreshed in time or invalidated the cache.

This was at least part of the motivation for Classic Windows' clone design and it not caching data.

The root problem here is that it takes a looooooooooong time to see your repositories. That's because we currently load _all_ the pages before showing anything in the UI. It'd be nicer if we could progressively show repositories as we get them.

**Comment by iAmWillShepherd** [comment]
I'd prefer using the database since a user's repos shouldn't change too drastically. I believe the typical action is to add a repo...

**Comment by joshaber** [comment]
>since a user's repos shouldn't change too drastically

While it's true that a user's repos don't change often, I think @niik's concern is that they're _more_ likely to change right before you try to clone. For example:

1. Susan creates a new repo on GitHub.com.
1. Susan goes to GitHub Desktop to clone it.
1. It's not in her list because Desktop hasn't refreshed again yet.
1. Susan has to manually refresh.
1. She now has to wait while it refreshes.

In that case, the caching hurts more than it helps. I think @niik's point is that the nature of clone makes them more likely to run into that.

**Comment by niik** [comment]
> In that case, caching hurts more than it helps. I think @niik's point is that the nature of clone makes them more likely to run into that.

:point_up: exactly. And the same goes for organizations. "Let's get started on this new project team! I've created the super-app repo, go clone it".

**Comment by shiftkey** [comment]
This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I added the `future-proposal` label to this issue and closed it so that we won't get overwhelmed with our backlog! We will revisit this in our next planning session.

**Comment by billygriffin** [comment]
Superseded by @niik's work in #5686 so I'm going to remove `future-proposal` here.
