### ISSUE TITLE
Unavailable Git Server Freezes App

### ISSUE THREAD

**Issue by AdrianB93** [desktop/desktop#2782]
Hello,

I need to use a VPN to access my works Bitbucket server. I forgot to start the VPN and clicked fetch. The application froze.

**Comment by shiftkey** [comment]
@AdrianB93 thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
