### ISSUE TITLE
Display base directory of repository

### ISSUE THREAD

**Issue by alexweissman** [desktop/desktop#2783]
### Description

Older versions of the GitHub client would display the base path of the repository just below the list of uncommitted changes.  This was very helpful when working with a large number of similarly-named repositories; I'm not sure why it was removed!

![older version of Github client](https://guides.github.com/introduction/getting-your-project-on-github/mac-commit.jpg)

Compare this to what you get in GitHub Desktop:

![screen shot 2017-09-19 at 5 21 30 pm](https://user-images.githubusercontent.com/5004534/30616076-05388480-9d5f-11e7-84bf-04bb2719677d.png)

### Version

**GitHub Desktop version:** 1.0.0

**OS version:** OSX Sierra

**Comment by shiftkey** [comment]
> This was very helpful when working with a large number of similarly-named repositories; I'm not sure why it was removed!

The minimal commit form is very much inspired by the classic Windows app - I think this is just something accidentally removed because we wanted to reclaim screen space.

We've talked a bit about how to deal with similarly-named repositories in #1929 - which also links off to similar discussions.

**Comment by shiftkey** [comment]
@alexweissman please read over #1929 and add any additional feedback you have to that issue

**Comment by alexweissman** [comment]
@shiftkey can we reopen that issue then, if it's going to be the canonical discussion thread for this?

> I think this is just something accidentally removed because we wanted to reclaim screen space.

To be honest, I'm getting tired of this overall trend in software to remove features in the name of making things pretty.  A git client is a tool, not a decorative piece inspired by the latest trend in interior decorating.  You're sacrificing overall UX in the name of appearance.

At least have this feature as a configurable option, even if it's turned off by default.

**Comment by shiftkey** [comment]
> if it's going to be the canonical discussion thread for this?

@alexweissman we close out issues marked as `future-proposal` so we don't get overwhelmed, and will return to them as part of our next planning session.

**Comment by alexweissman** [comment]
Great!

**Comment by tjtyrrell** [comment]
I would like to add my +1 to this issue. We are in a situation where we have to have the same repository in different folders (one folder per environment). The rational behind this is complicated, but it's related to the limitation of the tools and application we are customizing (each folder has a config that is connected to each environment.

You might ask: "Isn't your scenario stupid?"
Yes, it is really unfortunate.

Then you might ask: "Why then?"
Because we are using a piece of software that isn't compatible with traditional development environments. It also would be too much of a hassle to have multiple repos, one per environment.

So having labels, or letting me name a repo in the list (like "dev", "prod", etc)  would be incredibly helpful. Like listed in this request, even having the parent folder would also solve this.

**Comment by tjtyrrell** [comment]
Just accidentally found out that if you created the repository from the git cli command... Then "Add local repository" will inherit the parent folder name. Good to know, but an unfortunate extra step.

**Comment by peterthomastlc** [comment]
I'd like to add my +1 to this. it's such a big thing for me that, after committing the wrong code a few times,  I've stopped using github desktop because of it, and have moved over to SmartGit.
Not something I'd have done out of choice - it's a necessity.

**Comment by peterthomastlc** [comment]
Re the comment from shifkey:-
> The minimal commit form is very much inspired by the classic Windows app - I think this is just something accidentally removed because we wanted to reclaim screen space.

If it was accidentally removed, then surely this should be categorised as a bug, not an enhancement?
Please bring it back, at least as an option, it's a showstopper for me.
