### ISSUE TITLE
No create a new branch button

### ISSUE THREAD

**Issue by maxence-charriere** [desktop/desktop#2784]
### Description

No obvious button to create a new branch

### Version

**GitHub Desktop version:** 1.0.0

**OS version:** MacOS 10.12.6

### Steps to Reproduce

1. Add a repo
2. See that there is no button to create a new branch.

**Comment by j-f1** [comment]
It should be under Branch → New Branch.

**Comment by maxence-charriere** [comment]
I know but it is not obvious when you use the interface. Same for pull requests.
This new interface is beautiful but honestly, it lacks user friendly elements.

**Comment by maxence-charriere** [comment]
And same for add a new repo. These are the kind of interaction that should be obvious. Not hidden in the titlebar menu that nobody use.

**Comment by shiftkey** [comment]
@maxence-charriere earlier iterations of the UI had these buttons, but were removed to reclaim this space for more contextual tasks along the top toolbar. #1065 is a good example of this.

@desktop/design is there a neat summary you could provide here about the philosophy we've undertaken here?

**Comment by maxence-charriere** [comment]
there is recurrent operations that are often used:
- add a new repository: When clicking on the button to switch repo, a button to add a repo would be nice to have this pane (e.g. under the search bar)
-  create a new branch: When clicking on the branch button, a button to add a new branch would be nice too (again under the search bar).
- Create PR: another button on the right of the fetch origin one would be nice.

Currently, all these actions are hidden in the menu bar. On Mac the menu bar is far from the window. On Windows they are closer but very small.

Next to that, you have these big buttons to see repos, branches, etc... which draw the user attention.
User are expecting to have actions related to these when they click on it.

The first reaction I had when I wanted to use the app was "How the hell I'm doing these things". And look like I'm not the only one to think that (see the hacker news post). 
Eventually I found the buttons in the menu bar and was able to do what I wanted.

The problem is that the menu bar buttons are small, not obvious, and even if there is shortcuts, a lot of people doesn't use them.

Beautiful should not be a tradeoff with usabillity.

**Comment by vojtech-dobes** [comment]
I was also looking for way to do this in the app yesterday (how to create new branch) and taught by GitHub itself, I started to type new branch name in the search field in branches list hoping it would offer me creating that non-existent branch for me. I think it would be nice workflow and inline with how GitHub web app works.

**Comment by danqing** [comment]
I reported this problem a while back at #2067. This is a long standing issue (that the app hides pretty much 90% of the functionality in the menu), and now as 1.0 is out, hopefully they will have time to implement some of these improvements.

**Comment by niik** [comment]
Let's try adding a button using the secondary button style in line with the filter text.

<img width="340" alt="screen shot 2017-09-27 at 15 24 59" src="https://user-images.githubusercontent.com/634063/30915773-192dec20-a398-11e7-9fcc-8854ed976698.png">

<img width="443" alt="screen shot 2017-09-27 at 15 50 52" src="https://user-images.githubusercontent.com/634063/30917182-aed417e2-a39b-11e7-9f88-fab6ef3ae7fb.png">

We'll go with text-only for this one and try to position it so that the left edge lines up with the foldout cliff above and with the same height as the text box.

In my mocks that translates to 61px wide but that might need tweaking once we get it in. Standard foldout margin otherwise and a single spacer (10px) between the filter textbox and the button.

Clicking on the button would be the exact same thing as `Branch -> New Branch`, i.e. it would open the new branch dialog except if there's text in the filter text box we'd prefill the branch name in the new branch dialog with that.

I know that there's also been requests for automatically creating a branch after typing a branch name that doesn't exist. That pattern is something we intentionally removed from the classic clients as we feel it has a very high likelihood of mistakenly created branches. That said I think we can do something to guide users onward while at the same time giving our "No Reposiory Found" blank slate a touch up.

<img width="340" alt="screen shot 2017-09-27 at 15 39 25" src="https://user-images.githubusercontent.com/634063/30916593-132b813c-a39a-11e7-9569-3698f8d11658.png">

I'm still not sure of the first-person voice here in `I can't find` but I think it's still an improvement so let's go with it for now until we figure out whether we want to use that style in the app or not.

Clicking on the 'Create New Branch' button here would be the same as clicking on the `New` button.

For the `<kbd>` elements here we'll try a minimal amount of padding (1px), a standard rounding of 3px and a base border but we'll increase the contrast on the border one notch to `$gray-300`.

**Comment by joshaber** [comment]
@niik and I discussed this and decided to put it in 1.0.x 💥

**Comment by j-f1** [comment]
> I'm still not sure of the first-person voice here in “I can't find” but I think it's still an improvement so let's go with it for now until we figure out whether we want to use that style in the app or not.

How about:

> **No Results**
> <kbd>Create New Branch</kbd>
