### ISSUE TITLE
Why Iam getting error while cloning.Iam not able to clone the repository.Why???

### ISSUE THREAD

**Issue by snigdha-reddy1996** [desktop/desktop#2791]
### Description

[Description of the issue]

### Version
1.0.0

**GitHub Desktop version:** [1.0.0]

**OS version:** [windows 8]

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by tierninho** [comment]
@snigdha-reddy1996  thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
