### ISSUE TITLE
Add a "most often used action" bar/menu

### ISSUE THREAD

**Issue by SimonCropp** [desktop/desktop#2811]
I would like to have functionality that takes the most used actions and places them as buttons somewhere in the UI. so between 5-10 would be a good number. have it constantly be ordered based on how often that feature is used.

So for me the actions would always contain "open in GH", "open in Sublime", "show in explorer".

This behaviour would also make it more touch screen friendly

Location: Either under the menu or to the right of the help menu

**Comment by j-f1** [comment]
This could be under the menu bar on Windows, and in an expanded title bar on macOS.

**Comment by iAmWillShepherd** [comment]
Thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our current roadmap.

I added the future-proposal label to this issue and closed it so that we won't get overwhelmed with our backlog! We will revisit this in our next planning session.

**Comment by billygriffin** [comment]
Hi @SimonCropp, thanks for this issue! With the "No local changes" shipping in 1.6, our intent was very similar to surface the most common actions. We're going to continue to monitor metrics on those to make sure they're actually useful for people, but since that gets at the spirit of this issue, I'm going to remove `future proposal` here. Thanks again!

**Comment by SimonCropp** [comment]
@billygriffin thanks for the update. and that is a reasonable decision
