### ISSUE TITLE
git-flow integration

### ISSUE THREAD

**Issue by artemnovichkov** [desktop/desktop#2816]
I use git-flow on daily basis. SourceTree has native integration of this flow for correct working with different branches (features, for example) and tags. Do you have a plan to add this feature?
![screen shot 2017-09-21 at 16 48 28](https://user-images.githubusercontent.com/5051597/30692329-e4bb0d06-9eec-11e7-85e9-58b075cbbe18.png)

**Comment by joshaber** [comment]
Thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I'm going to add the `future-proposal` label to this issue and close it out, so that we don't get overwhelmed with our backlog! We'll revisit these as part of our next planning session.

**Comment by billygriffin** [comment]
Just realized we're also tracking this in #2139, so I'm going to remove `future proposal` here. Thanks for the issue, it's not something we're looking at near-term but is certainly in consideration for something we may support in the future.
