### ISSUE TITLE
Add a notification foldout

### ISSUE THREAD

**Issue by j-f1** [desktop/desktop#2825]
It would be great to have a notification icon in the corner of the app, just like on the website.

[Notifications API](https://developer.github.com/v3/activity/notifications/)

When switching to a repo connected to GitHub (dotcom or Enterprise):
1. If the app has fetched notifications for the current account Recently™, pull the list of notifications from a cache and display them.
1. Enqueue a fetch for the current account.

When a fetch is enqueued for an account:
1. If a fetch has already been enqueued for the account, return without doing anything.
1. If the next-fetch date stored for the account has passed, fetch for the account immediately.
1. If the next-fetch date has not passed, wait until it has passed, then fetch for the account immediately.

When fetching for an account immediately,
1. `GET` the `/notifications` endpoint, passing the `If-Modified-Since` header with the last-modified date saved in the database for the account.
1. Set the next-fetch date for the account to `Date.now() + Number(headers['X-Poll-Interval']) * 1000`, where `headers` contains the HTTP response headers.
1. Set the last-modified date for the account to the value of the `Last-Modified` header.
1. Update the list of notifications.

**Comment by shiftkey** [comment]
I thought we had an earlier discussion about this but can't find it. Oh well, let's use this.

For reference, we have some CI notifications work on the roadmap for [1.2](https://github.com/desktop/desktop/blob/6df8a6906c18b70af916039f2e1f38ce0fe98ad1/docs/process/roadmap.md#12):

 
> - CI status notifications lite
>     - Only on my PRs
>     - Use OS notifications
>     - Notifications link to the PR on dotcom

These are rough notes, but there's some context here that I should add:

 - it's hard for us to justify having a full notification experience in here, based on our current priorities
 - CI notifications is a nice subset of notifications to start with, as it's part of the "work on your code" -> "open a pull request" -> "review pull request" -> "pull request merged" workflow
 - we can cut some corners and leverage the OS for notifications, deferring work on the UI and managing notifications until later when we have a better idea of what we need

And because this is 1.2 scope, it's fuzzy and subject to change. But that's some insight into where we're heading.

**Comment by shiftkey** [comment]
@j-f1 thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I added the `future-proposal` label to this issue and closed it so that we won't get overwhelmed with our backlog! We will revisit this in our next planning session.

In the meantime, I'd like to hear from people who come across their answers to this question:

 - **Without notifications, what specific tasks and workflows are you doing that require you to switch back to the app or to your inbox to find additional information?**

I'd like to avoid building out a whole notifications experience in the near term, but I'm sure there's some things in between that we can do - and maybe there are things that we can add on our roadmap that integrate these notifications into your workflows, rather than having a standalone foldout.

**Comment by jptaranto** [comment]
Integration with system notifications would be nice too: Someone comments on my PR and then a system notification that I can click to see the comment on github.com for instance.

**Comment by billygriffin** [comment]
Thanks for the request here @j-f1, I totally understand how this could be useful. However, we'd like to think about notifications contextually in the course of various workflows. For example, the notification when diverging from default branch is intended to ensure you have the latest from master on your branch. So as we continue to build out functionality please let us know where you see opportunity to potentially integrate contextual notifications, but I don't think a full port of GitHub notifications into Desktop is going to add a whole lot for folks.

**Comment by nesl247** [comment]
@billygriffin Hopefully you do reconsider at some point, or get the web team to implement push notifications. This is really the big issue.

**Comment by Osiris-Team** [comment]
<div align="center">
<div>
<h1>Notifications for Desktop</h1>
<p>Its a feature request xoxo 💜</p>

<h2>Workflow</h2>
<p>-> Background service listening for notifications ->
Github notification arrives and gets displayed by windows/mac notification
onPressWindowsNotification() -> Opens browser/tab with the issue/pullrequest</p>

<h2>Advantages</h2>
<p>+ Users can react faster to newly opened issues on their repositories. That also means that critical bugs can be fixed faster.</p>
<p>+ Increases users productivity and motivation</p>
<p>+ Increases users interactions with GitHub Desktop</p>

<h2>Design</h2>
<h3>Notification bell icon on the right corner, of the top bar in GitHub Desktop</h3>
<img src="https://i.imgur.com/PqThYx7.png">

<h3>Alternative</h3>
<img src="https://i.imgur.com/D49PTTR.png">

<h3>Windows notification example</h3>
<img src="https://i.imgur.com/s0AW6gJ.png">

<h3>Settings example</h3>
<img src="https://i.imgur.com/28TvPol.png">

</div>

**Comment by tierninho** [comment]
Adding ref to similar request https://github.com/desktop/desktop/issues/10312 for requested changes from code reviews to be seen in Desktop.
