### ISSUE TITLE
Commit without message is not displayed correctly

### ISSUE THREAD

**Issue by dnlfrst** [desktop/desktop#2831]
### Description

Viewing a repository which contains a commit without a message (`--allow-empty-message`) does not provide enough space/margin/padding between the meta information of the commit (_author_, _SHA-1_ and _amount of changes_) and the upper menu.

### Version

**GitHub Desktop version:** 1.0.0

**OS version:** Windows 10 Home (x64), version 1703, build 15063.608

### Steps to Reproduce

_Steps 1 to 4 are accomplished using `cmd.exe`._
1. Navigate to a directory of your choice and initialize a git repository via `git init`.
2. Add a file to said directory and said file to the index of the created repository using `git add [FILE]`.
3. Commit the added file with `git commit --allow-empty-message`.
4. The default editor (Vi) prompts you to enter a commit message, instead type `:wq` to save and quit.
3. Open GitHub Desktop.
4. In the menu navigate to `File > Add local repository`. When prompted, select the path where you just created a git repository. Finally, confirm with _Add repository_.
5. In the left panel, select _History_ and click onto the commit created in steps 3 and 4.

**Expected behavior:**

![expectation](https://user-images.githubusercontent.com/13868083/30723576-88f17f4a-9f38-11e7-8985-f24a59449b3b.PNG)
(_I just added `margin-top: 10px` to the element containing the meta information._)

**Actual behavior:**

![issue](https://user-images.githubusercontent.com/13868083/30723405-6b44ab6c-9f37-11e7-9ba3-cb9042a06df2.PNG)

**Reproduces how often:** 100%

**Comment by shiftkey** [comment]
@Iw1s nice find - I wasn't aware this was an option that Git supported these days!

For reference, this is how it renders in the command line:

<img width="512"  src="https://user-images.githubusercontent.com/359239/30723774-c64f2aec-9f7c-11e7-9072-c0713eff2491.png">

And this is how a normal commit renders:

<img width="587" src="https://user-images.githubusercontent.com/359239/30723777-d0404af4-9f7c-11e7-926a-70a8f4537e2b.png">

I'll do some digging and identify what needs to be fixed so that someone can have a go at it

**Comment by shiftkey** [comment]
This also affects the commit list:

<img width="243" src="https://user-images.githubusercontent.com/359239/30723859-50792b6e-9f7d-11e7-92f3-1aa67bd3fdf7.png">

**Comment by sergiou87** [comment]
![Image](https://github.com/user-attachments/assets/c58dd590-7c88-40d7-bf23-161939b78363)


Fixed in #12480
