### ISSUE TITLE
GitHub Desktop is invisible after starting

### ISSUE THREAD

**Issue by griestopf** [desktop/desktop#2853]
### Description

On a Windows multimonitor setup with the primary monitor being a High-DPI monitor (3000x2000 pixels - DPI-Font-Size set to 200%) and the secondary monitor being an ordinary 27" monitor (DPI-Font-Size set to 100%), when re-starting GitHub Desktop it tries to recreate its screen position somewhere out of the overall screen estate spanned by the two monitors. Unfortunately, GitHub Desktop doesn't obey to any of the commands exposed by the Task-bar's context menu, such as "overlap windows", which helps in similar situations with other misbehaving software in this case. The only workaround I found is to open another program (i.e. windows explorer), drag it to one screen border to tell Windows I want a split-view setup and then choose GitHub Desktop as the other window to display in split view.

### Version

**GitHub Desktop version:** 1.0.1

**OS version:** Microsoft Windows [Version 10.0.15063]

### Steps to Reproduce

1. Make sure you have a multi-monitor setup (perhaps with varying DPI settings)
1. Open GitHub Dekstop for the very first time
1. Place it somewhere on the secondary monitor
1. Close GitHub Desktop
1. Do other work, including rebooting the machine
1. Re-Open GitHub Desktop

**Expected behavior:** GitHub Desktop re-appears at the position and size it was closed OR -even better- GitHub Desktop re-appears at the center of the primary monitor

**Actual behavior:** GitHub Desktop does not appear, though task manager shows that it is running. Minimizing and Deminimizing it from the taskbar button shows that it is placed somewhere outside the screen space covered by the monitors.

**Reproduces how often:** 100%

#### Additional Information

Workaround see description.

**Comment by shiftkey** [comment]
@griestopf thanks for the detailed writeup! 

This sounds similar to #2107, but it doesn't sound  like you are changing your screen setup (disconnecting the secondary monitor). There might also be some changes in Electron behaviour between the two issues - I think they're related, but I'll keep them separate for now.

I did some investigating a while ago of that issue and I think this requires a fix in Electron around how the screen position is reported for each window, but I need to write this up properly and identify where the root of the problem is.

As a workaround, you can delete the `%APPDATA%\GitHub Desktop\window-state.json` file which tracks the screen position between sessions and restart the app to get it back on screen.

**Comment by shiftkey** [comment]
@griestopf I'm going to fold this up into #2107 to simplify things on my end. Please follow along with that issue.

**Comment by Splaxi** [comment]
For people like me

```
Remove-Item "$env:APPDATA\GitHub Desktop\window-state.json" -Force
```
