### ISSUE TITLE
Avatar not updated after sign in, requires restart

### ISSUE THREAD

**Issue by jessetan** [desktop/desktop#2911]
### Description

Signing into a GitHub account should display the avatar in the app immediately, instead this requires an app restart.

### Version

**GitHub Desktop version:** 1.0.2
**OS version:** macOS 10.12.6

### Steps to Reproduce

1. Start GitHub Desktop (not logged in), avatar uses default hubot
1. Open Preferences and login with GitHub account (not enterprise)

**Expected behavior:** Avatar updates to my GitHub profile picture after signing in
**Actual behavior:** Avatar is still hubot until restart of GitHub Desktop
**Reproduces how often:** 100%

**Comment by ausiddiqui** [comment]
I have an issue where the Enterprise avatar is just a missing image. Not just for me but for all members in my team to contribute to the repo as well. 

Version:

GitHub Desktop version: 1.02, 1.03
OS version: macOS 10.12.6, 10.13, Windows 7 Ultimate SP1

**Comment by j-f1** [comment]
@ausiddiqui We’re tracking that issue over in #821. Please follow along there for updates.

**Comment by jessetan** [comment]
Was this closed accidentally? #821 is about caching of images, this issue is about avatars (or perhaps profile information) not being refreshed on log in, but only on app start.

**Comment by niik** [comment]
@jessetan, my apologies. It seems the comment above was only in response to @ausiddiqui's problem.

**Comment by rudifa** [comment]
I would like expand above @jessetan's problem description, as follows:

**Steps to Reproduce**

  1. Start GitHub Desktop (not logged in), avatar uses default hubot _for myself, but also for all other users (e.g. in History of a project cloned from GitHub)_
  2. Open Preferences and login with GitHub account (not enterprise)

**Expected behavior:** Avatar updates to my GitHub profile picture after signing in. _Avatars for all other users are also updated to their GitHub avatars_
**Actual behavior:** Avatar is still hubot _(and so are avatars for all other users)_ until restart of GitHub Desktop
**Reproduces how often:** 100%

_I suggest that a successful sign-in event should cause the History display to refresh and show the avatars known to GitHub._
