### ISSUE TITLE
View/copy full path of file (Changes or History tab)

### ISSUE THREAD

**Issue by artivilla** [desktop/desktop#2944]
### Description

In history mode, view/copy complete file path if it's longer than the given screenspace. View screenshot. Copying gives me `src/main/webapp/WEB-INF/views/web/p…/manage.jsp`

See #2801 for more context.

**GitHub Desktop version:** 0.9.1

**OS version:** 10.12.6

**Actual behavior:**

<img width="894" alt="copy-file" src="https://user-images.githubusercontent.com/2120159/31095122-ad5fc620-a785-11e7-939d-0d274bc2905c.png">

**Reproduces how often:** 100%

**Comment by niik** [comment]
Hey @artivilla. Our component for rendering file paths doesn't, as you've noticed, rely on css to perform truncation. CSS currently only supports truncating text at the end whereas we really wanted a more intelligent truncation for paths where the beginning and end is usually the most important bits.

In this case I think we could add a context menu as well as a hotkey (Cmd/Ctrl+C) when focused on an item to copy the full path. I've added this to the design review project to get some more thoughts on this.

**Comment by LucaT1** [comment]
Trova

**Comment by LucaT1** [comment]
Ok

**Comment by LucaT1** [comment]
Lascia che

**Comment by shiftkey** [comment]
@sbonami opened #5382 which also requested the ability to copy the file path (absolute or relative) from in the Changes tab. I'll update the title to reflect that, rather than keep two separate but related issues around.

**Comment by Amabel** [comment]
Hi, @shiftkey. I've been watching this issue for nearly 1 year. And I've seen that there is no update in this thread recently. Since this will be very helpful to me, so I tried to implement this feature by my self. 

As @niik and https://github.com/desktop/desktop/issues/5382 mentioned, one way to implement this is to add a `Copy` button in the context menu in both tabs ('Changes' and 'History'). 

Here is a gif which can explain my implementation

![oct-15-2018 22-31-35](https://user-images.githubusercontent.com/12688422/47023525-cd0ab580-d19a-11e8-821d-ed56bef08bf4.gif)

I don't know if it's OK to create a pull request since there is no **help wanted** label on this issue, could you please give me some information about that?

**Comment by shiftkey** [comment]
@Amabel thanks for trying that out. I'm going to cc @desktop/product to get their gut feeling on what you have working, and if they're on board with this approach I'll switch it to `help wanted` and you can take it from there.

**Comment by billygriffin** [comment]
Thanks @Amabel for running with @niik's suggestion. Seems reasonable to me. I think the only change I'd recommend is to be a bit more explicit about what exactly is being copied just to make sure people don't think this would copy the contents of the file somehow. In this case, I think "Copy File Path" would work with the same casing as the other things in the context menu. Feel free to go ahead and open a PR and we'll address any additional feedback there.

**Comment by Amabel** [comment]
@shiftkey Thanks for paying attention on this. @billygriffin Thanks for the suggestion and I totally agree with you. I've made a pull request #5920 to address this, hope you can check this out.

**Comment by geogette** [comment]
quelqun peux me dire ou se trouve la tracduction svp merci
