### ISSUE TITLE
Create pull request

### ISSUE THREAD

**Issue by joshaber** [desktop/desktop#295]
Not gonna lie, I'm a lil unsure about this. I find myself using .com a lot, mostly to be able to do image uploads. Thoughts?

<img width="285" alt="screen shot 2016-08-22 at 4 21 20 pm" src="https://cloud.githubusercontent.com/assets/13760/17870216/7df9126a-6884-11e6-829d-a8e42c6a7e12.png">

**Comment by xt0rted** [comment]
Being able to create my PRs through the client is definitely a missed feature for me. It's how I create all of my PRs (I realized it was missing when trying to create my PR to this project).

This is one of the reasons I'm still running the native client side-by-side (dark theme, SHA copying, and easier branching are others).

I really don't want to have to load the website and click through that process to create a PR when it's literally 1 click and pressing enter in the app.

**Comment by Kwpolska** [comment]
Making Pull Requests without going to github.com are the main reason why I open GitHub Desktop. Looks like I need to go back to the old client for now.

**Comment by Eldorado234** [comment]
Same here.

Old workflow:
* Create PR in GH Desktop (publishing included). I only rarely upload images or do some complex md formatting, therefore the text field was alright in 98 % of the cases.
* Click on the button to jump to the PR in the browser
* Assign reviewers, assignees & milestones

New workflow:
* Publish in GH Desktop
* Type in the repo URL (or search trough my tabs)  😒 
* Wait for the "Recently Pushed" banner to appear 😒 
* Create PR with the web form

Preferred workflow:
* Create PR button in GH Desktop publishes the branch and then jumps to the web form
* I can fill the form and are done 🎉

**Comment by Kwpolska** [comment]
> jumps to the web form

The new app can display said form in a window on its own, since it’s built on Electron.

**Comment by Eldorado234** [comment]
> The new app can display said form in a window on its own, since it’s built on Electron.

Yeah, technically right. But I don't know if it is beneficial to show a website in an Application that should look and feel native. I think I would destroy the "illusion" of nativeness. 

And when I see a website, I also expect proper browser controls. What happens when I click on a link somewhere? How do I get back? Stuff like that. I think it would be a lot simpler and coherent to just upon the respective browser.

**Comment by Janpot** [comment]
Also, I feel like every step in a regular PR workflow is in a different place in the UI
1. create new branch => "File" menu
2. commit changes => bottom left corner
3. publish branch => black top bar
4. "compare on github" => "Branch" menu
5. "create pull request" => github website
Maybe it could be interesting to put some of these closer together as to make this flow a little more coherent?

**Comment by Haacked** [comment]
@Eldorado234 

> New workflow:
> 
> Publish in GH Desktop
> Type in the repo URL (or search trough my tabs) 😒

FWIW, you don't have to type in the repo URL. You can go to the Branch menu and select "Compare on GitHub". Or just use the keyboard shortcut `CTRL + SHIFT + C` which takes you right to the compare view for the current branch.

That should streamline your workflow a bit. 

> Wait for the "Recently Pushed" banner to appear 😒

This has been pretty fast for me lately. Are you noticing it takes a noticeable amount of time?

**Comment by Eldorado234** [comment]
> FWIW, you don't have to type in the repo URL. You can go to the Branch menu and select "Compare on GitHub". Or just use the keyboard shortcut CTRL + SHIFT + C which takes you right to the compare view for the current branch.

Cool, good to know. Thx! Just today discovered the "View on GH" which already helped quite a bit.
One question about this function: shouldn't it directly open the PR view when a PR exists for this branch. I can click the button on the website to jump to the PR but it would be nice to get there directly.

> This has been pretty fast for me lately. Are you noticing it takes a noticeable amount of time?

I guess this is mostly the delay until the branch is pushed. I had some PRs with bigger binary files recently which means I was on the website before the push was finished.

However, the best would be that you don't have to actively wait in any way. The was the good thing with the old client: you prepared the PR and then publishing and creating the PR worked automatically. You just had to take another look at a later point to set the assignee, etc. but you were not required to wait for a banner to appear (without any progress indicator).

**Comment by Haacked** [comment]
> However, the best would be that you don't have to actively wait in any way. The was the good thing with the old client: you prepared the PR and then publishing and creating the PR worked automatically. You just had to take another look at a later point to set the assignee, etc. but you were not required to wait for a banner to appear (without any progress indicator).

Really good point on the benefit of the client vs sending people to the web. FWIW, I agree with you. I really liked the dialog. I don't think the team is completely opposed to it, just not sure if it's a priority at the moment.

However this is good feedback.

**Comment by Fancellu2** [comment]
As a general rule, don't take away existing functionality or workflow.

Else you will annoy people.

Its a dangerous road to imagine you know best and are removing things for someone's own good.

**Comment by intemperie** [comment]
I went back to the old version just because of this. Being able to see if there is a PR associated to a branch and being able to create it from there was so useful.

**Comment by georgec-s** [comment]
We've got quite a few GitHub Enterprise users confused why the create pull request button isn't in the beta. Old workflow allowed our users who were not comfortable with the command line to turn _most_ work into just a few operations:
- Create a branch (shift+command+N)
_make some changes_
- Commit AND Sync in one step
- Open a Pull Request (command+R)

The _old_ GitHub Desktop _dramatically simplified_ the workflow for our users. The new one has so much promise, please don't take away the ability to simplify GitHub Flow...

**Comment by 50Wliu** [comment]
(Thanks @shiftkey to linking me here!)
I say that if this is going to be implemented, I would like it to recognize pull request templates so as to reduce maintainer burden.

**Comment by shiftkey** [comment]
@50Wliu also tracked in https://github.com/desktop/desktop/issues/1930

**Comment by shiftkey** [comment]
This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I added the `future-proposal` label to this issue and closed it so that we won't get overwhelmed with our backlog! We will revisit this in our next planning session.

**Comment by shiftkey** [comment]
@mmgfrcs added some feedback on a potential flow over in #5015

**Comment by louman** [comment]
I understand some of the points argued here but I can't see the harm of keeping the feature in. It's not like someone is requesting a new feature to be developed and integrated. The thing was already there, it might not have all the capabilities of the website but it works, it gets the job done and that's how a lot of people out there use it.

I also didn't like the fact that not even a message popped up after I upgraded saying that the feature was gone and that I should now use the website for it. I spent around 5 minutes digging around to see if it was really gone or just moved.

Since now the only thing you can do related to PR's is hit a shortcut and go to github, why not just add a new shortcut for that? Why did you have to remove a feature that a lot of people were already happily  using it?

Yes people might not experience all the nice features the website has but it is what it is. Instead of completely removing the ability to create PR's from within the app, maybe just add a question mark icon saying that you can also create PR's from the website and enjoy all the magic features it comes with.

**Comment by saschanaz** [comment]
👍 for only adding a link to the PR creation page. At least I can get my branch automatically selected then.

**Comment by j-f1** [comment]
@saschanaz You should be able to hit Command/Ctrl+R to open the PR page on GitHub with your current branch selected.

**Comment by billygriffin** [comment]
If we do revisit this we should make sure we properly consider respecting PR templates from #1930. I'm going to remove `future-proposal` from that one but wanted to make sure it's captured properly here as we continue to evaluate this.

**Comment by j-f1** [comment]
Looks like the label didn’t get removed somehow @billygriffin.

**Comment by billygriffin** [comment]
Sorry, I'm not sure if I could've worded that more confusingly if I tried. 

I wanted to convey that if we consider this issue, we should make sure we take #1930 into account. So I removed the label from #1930 and posted here to make sure we didn't lose track of it since I consider them pretty closely related. I'd like to keep this as a `future-proposal` because we haven't had a chance to give this one proper consideration yet. Let me know if that's still unclear. 😄
