### ISSUE TITLE
Add a My Gists section in the clone repo dialog

### ISSUE THREAD

**Issue by iAmWillShepherd** [desktop/desktop#2953]
I have gists and I want to clone them.

**Comment by shiftkey** [comment]
This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I added the `future-proposal` label to this issue and closed it so that we won't get overwhelmed with our backlog! We will revisit this in our next planning session.

**Comment by billygriffin** [comment]
I'm going to leave #2973 as the canonical place for this as we try to streamline future proposals.
