### ISSUE TITLE
external app launches Desktop periodically requesting credentials

### ISSUE THREAD

**Issue by fpcorso** [desktop/desktop#2962]
### Description

I have 7 repos currently used in GitHub Desktop. Several are public and some are private. All of them work fine. However, there is one private repo "vip-inspections" that the app keeps saying I need to add the local repository.

![github-desktop-error](https://user-images.githubusercontent.com/9730040/31188281-66c56aa2-a902-11e7-9192-2d3b8715e651.png)

This modal will pop up every few minutes. I can even close the app and the app will re-open a few minutes later and show this modal. If I click cancel or 're-add' the repo, the modal will go away for a few minutes and then pop up again. However, I can commit, push, pull, and fetch with this repo just fine so it is set up correctly. I have tried restarting the computer. 

It is so annoying that I may have to uninstall the app for now as it will even re-open the entire app even if I close it. I will be in the middle of typing something and the app will open, gain focus, and show this modal.

I have tried deleting the entire repo and going through the cloning process all over and it will still cause this issue but only for this private repo.

### Version

**GitHub Desktop version: 1.0.3** 
**OS version: Microsoft Windows [Version 10.0.15063]**

### Steps to Reproduce

1. Not entirely sure the process to reproduce this issue as it seems to only happen on a single private repo and no others.

**Expected behavior:** To only add the repo once(?)

**Actual behavior:** Modal pops up every 3 to 5 minutes asking to add the local repository

**Reproduces how often:** Every 3 to 5 minutes while the computer is on

### Logs
[2017-10-04.desktop.production.log](https://github.com/desktop/desktop/files/1356687/2017-10-04.desktop.production.log)

**Comment by shiftkey** [comment]
@fpcorso @cliv3dev are there any other programs you are running alongside Desktop at the time? I suspect something is trying to spawn Desktop in a certain way (that's with the `--credentials` command) and we're not handling it correctly.

**Comment by niik** [comment]
I'm trying to figure out where the '--credentials' are coming from. To my knowledge that's not something we use in the app. We did, however, use it back in the day for GitHub Windows classic in order to invoke the special credential helper mode and it was configured in the [system level gitconfig](https://github.com/github/msysgit/blob/devel/etc/gitconfig#L46-L47).

@fpcorso Have you used the classic version of GitHub Desktop on that machine before and do you have it installed right now?

I suspect what's happening here is that, as @shiftkey was saying, something is trying to invoke the old credential manager, that could be either GitHub Desktop classic or, if for some reason the credential helper is configured outside of the system level config, some other tool which attempts to run a fetch. That would end up invoking `github --credentials` which, now that we've installed our github command in `PATH` would call our launch helper script.

Running `github --credentials` in a path named the same thing as described in the issue produces the same behavior for me.

![image](https://user-images.githubusercontent.com/634063/31217330-eca0daee-a9b6-11e7-82e1-59a54fdb4cad.png)

@fpcorso Could you try running `git config --show-origin credential.helper` from a shell and let us know what it says?

**Comment by adamupstream** [comment]
Hi there. I've just come across this too. I'm running Visual Studio Code, and this seems to be making it pop up.

**Comment by niik** [comment]
@adamupstream Ah, that's very interesting. Thank you for jumping in. Could you please try running `git config --show-origin credential.helper` from within the integrated terminal in vs code?

**Comment by msramalho** [comment]
I'm having the same problem on Windows 10, and I also believe Visual Studio Code is triggering GitHub Desktop, here´s the result of running `git config --show-origin credential.helper` on my repo (i've replaced sensitive information with `*`, as i believe it is unrelevant):
```
file:"*\\AppData\\Local\\GitHub\\PortableGit_****\\mingw32/etc/gitconfig" !github --credentials
```

**Comment by niik** [comment]
@msramalho Thank you! That's that mystery solved then. Visual Studio Code [auto-detects GitHub classic's Git installation](https://github.com/Microsoft/vscode/blob/6a6b589eb87046c6d05900dccd38432fed7e26fb/extensions/git/src/git.ts#L121-L133) and uses that [in lieu of other Git installations](https://github.com/Microsoft/vscode/blob/6a6b589eb87046c6d05900dccd38432fed7e26fb/extensions/git/src/git.ts#L135-L141).

In order to solve this you'll need to uninstall GitHub Desktop classic if you still have it installed, that will unfortunately leave the Git Shell installation lying around though so in order to completely remove that you'll need to delete the `%LocalAppData%\GitHub` directory as well. After that you'll need to install [Git for Windows](https://git-scm.com/download/win) if you want to keep using the Git integration in Visual Studio Code.

We could probably tweak our command line tool to ignore the `--credentials` command for now in order to prevent that dialog from popping up periodically. Auth is already broken for vscode in this scenario so we wouldn't be making it any worse.

**Comment by msramalho** [comment]
@niik, thanks for the detailed explanation! However, two questions remain from your explanation:
 1. Do I need to uninstall Github Desktop (not the classic), or can I just leave it as it and uninstall the classic?
 2. What kind of tweaking do you mean? Because I'd love to stop receiving those popups!

**Comment by niik** [comment]
> Do I need to uninstall Github Desktop (not the classic), or can I just leave it as it and uninstall the classic?

No, you don't have to install the current version of GitHub Desktop, only the classic version



> What kind of tweaking do you mean? Because I'd love to stop receiving those popups!

Good news! You should stop receiving them once the classic app and all of its remnants are gone. The tweaks I was referring to was on our side. Since vscode ends up invoking `github --credentials` which is a command line options we're not using in the new app we could add a special case either in our [cli process](https://github.com/desktop/desktop/blob/master/app/src/cli/main.ts) or on [the receiving end](https://github.com/desktop/desktop/blob/master/app/src/main-process/main.ts#L76) in our main app to ignore any invocations with that parameter.

**Comment by shiftkey** [comment]
We're going to have to submit a fix to VSCode to tell them to stop using this git, because it's system config has this value:

```
[credential]
	helper = !github --credentials
```

And because our `github` command line is now on PATH, probably preceding the one from classic Git, it's getting confused.

**Comment by shiftkey** [comment]
As we need to discourage tools from using that version of Git I've opened a PR to stop that. Follow along there: https://github.com/Microsoft/vscode/pull/35965
