### ISSUE TITLE
spawn UNKNOWN error

### ISSUE THREAD

**Issue by helaili** [desktop/desktop#2963]
### Description

👋 team, I'm working with a team working on Windows with limited permissions on their desktop. GitHub's certificate has been whitelisted so Desktop can be installed, but any attempt to start it by users without admin privilege generates a `spawn UNKNOWN` dialog and the software can't be used even after dismissing the dialog: for instance, buttons on the *New Repository* dialog seem enabled but nothing happens. Running as an administrator does succeed though, no error dialog at all.  

![2017-09-26 09_57_40-github desktop_1](https://user-images.githubusercontent.com/2787414/31196090-ce855bee-a94c-11e7-839c-4fd47d2e9519.png)
 

### Version

**GitHub Desktop version:** Github Desktop Version 1.0.3
**OS version:**  Microsoft Windows 6.1.7601

### Logs

```
2017-10-03T12:27:40.484Z - info: [ui] launching: 1.0.1 (Windows 6.1.7601)
2017-10-03T12:27:51.847Z - info: [ui] launching: 1.0.1 (Windows 6.1.7601)
2017-10-03T12:36:50.427Z - info: [ui] launching: 1.0.1 (Windows 6.1.7601)
2017-10-03T12:41:18.035Z - info: [ui] launching: 1.0.3 (Windows 6.1.7601)
2017-10-03T13:01:18.185Z - info: [ui] launching: 1.0.3 (Windows 6.1.7601)
2017-10-03T13:01:26.223Z - info: [ui] launching: 1.0.3 (Windows 6.1.7601)
```

**Comment by j-f1** [comment]
Can you open the DevTools (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd>) and see if there are any errors in the Console tab?

**Comment by helaili** [comment]
@DamienMure, @jmarandet can you please copy paster the DevTools output as asked ☝️

**Comment by jmarandet** [comment]
I guess that I can't catch the first error at launch time, since the Developer Tools (Ctrl-Shift-I) can only be activated when the app has been spawned, isn't it ?

But here is a snapshot of an error that I get when I try to add a repo.


----- Mail original -----
De: "Alain Hélaïli" <notifications@github.com>
À: "desktop/desktop" <desktop@noreply.github.com>
Cc: "Julien Marandet" <julien.marandet@free.fr>, "Mention" <mention@noreply.github.com>
Envoyé: Vendredi 6 Octobre 2017 14:42:50
Objet: Re: [desktop/desktop] spawn UNKNOWN error (#2963)



@DamienMure , @jmarandet can you please copy paster the DevTools output as asked ☝️

**Comment by niik** [comment]
Hey @jmarandet, thanks for that screenshot. That's very helpful. If you have a moment it would be fantastic if you could click on that 'Info' dropdown in devtools and change that from `Info` to `Verbose`, that should show even more details.

From the information in the screenshot we can discern that it's failing while trying to execute a Git command. Looking through the call chain of adding a repository I strongly suspect that the command it's trying to run is `git lfs track` inside of the repository directory. A verbose log would confirm that.

If you've got Git for Windows installed it would be interesting to see what results you get if you use Git Bash to run that exact command `git lfs track` inside of the repository directory.

Since you haven't been able to add a repository yet it's hard to know if all Git commands are failing or just the lfs related ones. I suspect the former though since lfs in this case would be invoked _through git itself_. I'm afraid I have very little experience with the kind of security permissions in play on your system but if GitHub's certificate needed to be trusted it's possible that the same process needs to be applied to the codesign certificate of Git itself and that of LFS.

**Comment by jmarandet** [comment]
Thanks @niik 
Yes, it seems that Git LFS is not installed.
Git is already installed on my computer (version 2.10.0.window.1)

Here is the screenshot with verbose mode and my git bash console showing the lack of git lfs ;
![2017-10-09 09_47_28-test git lfs](https://user-images.githubusercontent.com/32270488/31328839-5ff0a16e-acd7-11e7-8cb9-8bf6ff945349.png)

**Comment by joshaber** [comment]
Thanks @jmarandet! It looks like it's a more general problem than LFS.

Could you try grabbing the logs at `%APPDATA%\GitHub Desktop\logs\*.desktop.production.log`? They might provide us with a bit more information.

**Comment by jmarandet** [comment]
Here you go @joshaber 

[2017-10-09.desktop.production.log](https://github.com/desktop/desktop/files/1368681/2017-10-09.desktop.production.log)
[2017-09-26.desktop.production.log](https://github.com/desktop/desktop/files/1368683/2017-09-26.desktop.production.log)
[2017-10-03.desktop.production.log](https://github.com/desktop/desktop/files/1368684/2017-10-03.desktop.production.log)
[2017-10-06.desktop.production.log](https://github.com/desktop/desktop/files/1368682/2017-10-06.desktop.production.log)


This is all I got in this folder

**Comment by jmarandet** [comment]
Besides, we suspect that it is unlikely that the crash is due to the lack of Git LFS on my computer, since the launch succeed when it is done with an admin privileged account.

**Comment by joshaber** [comment]
>the launch succeed when it is done with an admin privileged account.

That's interesting! @shiftkey can I tag you in? Any thoughts?

**Comment by shiftkey** [comment]
@joshaber sure, coach - I got hoop dreams!

**Comment by DamienMure** [comment]
Hi
I found something.
Using "Process Monitor" from sysinternal I was able to spot this exe file: "$HOME\AppData\Local\GitHubDesktop\app-1.0.1\resources\app\git\cmd\git.exe"

This executable file is not signed with GitHub certificat.
![capture](https://user-images.githubusercontent.com/15243951/31720612-51aa775a-b417-11e7-94b7-a48a001480a0.PNG)

So I need to add this certificat as a trusted one.
I'm not able to test it right now. I'll keep your informed ASAP.

To run an exe file in our environnement a regular user (without admin privilieges) need to:
- run it from "ProgamFiles"
or
- run it from somewhere else only if the exe is signed and trusted by our compagny.

Best Regards.

Damien

**Comment by shiftkey** [comment]
@DamienMure that Git executable isn't signed by us, but should be signed by the [Git for Windows](https://git-for-windows.github.io/) project. You should verify their certificate all the same, but we'll continue to publish Desktop in this way for the foreseeable future.

**Comment by DamienMure** [comment]
Hi.
I now trust the certificat from "Git for Windows" project:
- No more "spawm UNKNOWN" alert
- cloning a repository is now possible.

We can close this issue.
Thank you all.

Regards.

**Comment by shiftkey** [comment]
@DamienMure thanks for that extra clue. @helaili does this seem like it might be a similar issue with the environment you were encountering (only whitelisting certain signed executables)?

**Comment by helaili** [comment]
@shiftkey I just happened to open the issue for @DamienMure so we're talking about the same exact environment. Thanks for your help!
