### ISSUE TITLE
Open in Desktop on dotcom opens the file in Finder

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#2975]
If you click the desktop icon on dotcom that opens the file in Desktop, it results in Desktop opening the repo as expected, but the also the Finder opens the file on top of Desktop.

<img width="1041" alt="screen shot 2017-10-06 at 13 43 29" src="https://user-images.githubusercontent.com/14828183/31278412-c70433b2-aa9c-11e7-8d6f-c38fbf01dd49.png">
<img width="1048" alt="screen shot 2017-10-06 at 13 42 06" src="https://user-images.githubusercontent.com/14828183/31278413-c727b1e8-aa9c-11e7-9517-92de54b4123c.png">

Expected result: the file is opened in the History tab (at least this is what I remember happening)

Also, noticed that if the file is not yet on Desktop, then clicking the desktop icon on dotcom results in a fetch and a suggested pull. Seems intentional, but just wanted to point it out.

<img width="781" alt="screen shot 2017-10-06 at 14 02 30" src="https://user-images.githubusercontent.com/14828183/31278960-08da8e38-aa9f-11e7-8c62-448a076e1941.png">

tested in 1.0.4-beta0, mac

**Comment by shiftkey** [comment]
> Expected result: the file is opened in the History tab (at least this is what I remember happening)

This isn't how the classic apps behaved, and I'll give some back story as to where this was coming from. We were imagining that users wanted to get straight into editing this file on their machine, rather than using the web editor. So this is the workflow we went for:

 - clone the repository, if it doesn't exist
 - checkout to the branch you were looking at on the website
 - focus on the file in Finder/Explorer, so you can then open it in your editor of choice

We haven't gone down the path of opening it in your default program, because it lead to some confusion as users might not have their machine setup right. So we put them just before that point.

If we were to focus on the file in the history tab we'd need to find the most recent commit touching this file (this isn't part of the clone URL, and we can only assume that the file exists in this branch) and select that. I'm not sure the user is interested in seeing the last change to this file, but I'm open to ideas around making this workflow nicer.

> Also, noticed that if the file is not yet on Desktop, then clicking the desktop icon on dotcom results in a fetch and a suggested pull. Seems intentional, but just wanted to point it out.

The fetch sounds right (you've reactivated the app and maybe switched repositories, which would trigger a fetch) but I'm not sure where this suggested pull comes from. More details plz.

**Comment by shiftkey** [comment]
Dropping `bug` from this while we discuss the feature, and wait for more information about the "suggested pull".

**Comment by tierninho** [comment]
@shiftkey Thanks for the color on the decision making process. Seems like the right call leaving it as-is... only intended to call it out as it could have been a bug and I wasn't sure. 

> The fetch sounds right (you've reactivated the app and maybe switched repositories, which would trigger a fetch) but I'm not sure where this suggested pull comes from. More details plz.

As for above, the "suggested pull" is due to the file missing on Desktop but existing on dotcom. When the user clicks the desktop icon on dotcom, the fetch on Desktop notices the file is missing and offers to pull the file down.

Reproduce:
- add new file to dotcom 
- click icon desktop for that file on dotcom
- repo should open on Desktop
- fetch is triggered, and `pull origin 1` is present
- (user has option to pull down the file)

As this seems like the right flow, adding a error message that the file is not there seems like the wrong approach.

**Comment by shiftkey** [comment]
Those repro steps feel like #3006 which is a relatively quick fix. If that's right, I think that's all we need to worry about here for now.

**Comment by tierninho** [comment]
Sounds good. Closing this in light of #3006
