### ISSUE TITLE
Selecting ignore on files does not remove them from the changes list

### ISSUE THREAD

**Issue by agersoncgps** [desktop/desktop#3037]
Mac 1.03
Mac OS 10.11.5

<img width="952" alt="screenshot 2017-10-12 18 44 33" src="https://user-images.githubusercontent.com/336441/31522780-aafc1f1e-af7d-11e7-9d35-d489f513a93e.png">

**Comment by shiftkey** [comment]
@agersoncgps I'm 99% sure this is because the files are already tracked in Git, which is captured in https://github.com/desktop/desktop/issues/2537.

The workaround (and what the app will do in a future update) is to delete the tracked files from disk (if any exist) so they can be committed at the same time.

**Comment by shiftkey** [comment]
Closing this one in favour of #2537
