### ISSUE TITLE
Show recent server address for Enterprise

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#3040]
Would be a nice enhancement to show recent server address(es) that were successfully connect to for Enterprise repos. 

Even if a user only connects to one address, it would be nice not to have to enter it each time. 👍 

<img width="415" alt="screen shot 2017-10-13 at 9 56 32 am" src="https://user-images.githubusercontent.com/14828183/31538347-2d5a7f30-affd-11e7-853f-5f6c85b0556a.png">

**Comment by joshaber** [comment]
>Even if a user only connects to one address, it would be nice not to have to enter it each time. 👍

Though hopefully they're only logging in once 😄

**Comment by shiftkey** [comment]
This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I added the `future-proposal` label to this issue and closed it so that we won't get overwhelmed with our backlog! We will revisit this in our next planning session.
