### ISSUE TITLE
Bring back some functionality from the classic version

### ISSUE THREAD

**Issue by PiezPiedPy** [desktop/desktop#3048]
1. Any chance the history graphic from the classic version can be implemented?
It gave a good way of comparing different branches also the tooltip info of the commits when hovering over the graphic nodes was really helpful.

2. Creating a new branch based on any branch in the branch list was a much better way than the new set up where you only get two choices of either the current or master branch ( grrrr winds me up >.< )

3. How about a Dark view theme, the white screen blinds me at night and gives me a whopping headache :(

4. The button to open the branch in Visual Studio was also pretty handy, I miss that one.

Sorry to say but as it stands I'm reverting back to the Classic version until this new version is finished properly.
A link to Classic on the desktop.GitHub webpage would be helpful for those who still prefer the Classic version.

**Comment by j-f1** [comment]
Thanks for contributing!

> Any chance the history graphic from the classic version can be implemented?

We’re planning to let you filter the history view to show the differences between two branches for 1.1 or 1.2.

> Creating a new branch based on any branch in the branch list was a much better way than the new set up where you only get two choices of either the current or master branch

That’s a cool idea! How are you using that feature in your workflow right now?

> How about a Dark view theme, the white screen blinds me at night and gives me a whopping headache :(

We’re tracking this in #1515. TL;DR: This takes a lot of design effort, meaning that the team wouldn‘t be able to ship as many other new features.

> The button to open the branch in Visual Studio was also pretty handy, I miss that one.

GitHub Desktop currently supports opening repositories in VS Code, Atom, and Sublime Text since they are compatible with macOS, Windows, and Linux. We’re still working on adding support for non-cross-platform editors.

**Comment by shiftkey** [comment]
@PiezPiedPy thanks for the feedback. Some extra things on top of what @j-f1 has already said:

> 1. Any chance the history graphic from the classic version can be implemented?
>
> We’re planning to let you filter the history view to show the differences between two branches for 1.1 or 1.2.

The graph thing is not on our immediate roadmap (see #1634 for that discussion) and the designs for this "Compare two branches" view are here: https://github.com/desktop/desktop/issues/2639#issuecomment-333621771

> 4. The button to open the branch in Visual Studio was also pretty handy, I miss that one.
>
> GitHub Desktop currently supports opening repositories in VS Code, Atom, and Sublime Text since they are compatible with macOS, Windows, and Linux. We’re still working on adding support for non-cross-platform editors.

Some other interesting details from the classic Windows app:

 - `Open in Visual Studio` would only light up with a repository has a `.sln` file in it.
 - We did this "does it have a .sln file?" check because VS2015 does not support opening folders, and I'm pretty sure most VS usage comes from opening a solution anyway. 
 - When it came time to bring this into Desktop Electron, it was the only editor that worked in this way - all others supported opening directories, which made it easy to implement the "Open Directory" action. So it got punted because it deviated from the overall cross-platform story we were shooting for.
 - VS2017 does support opening a folder, but I don't think that's how most people want to work in VS

We've had a bunch of requests for other external editors in #2487, and at this point I can only focus on the core experience because that's all the bandwidth I have currently. We'd need to change the internals a bunch to support this "are there any sln files in the repository currently?" scenario, and I'm not aware of other popular languages/tools that work like this.

If there's demand for this _as well as people keen to get involved_, let's talk about it over in #2487.
