### ISSUE TITLE
Issue installing software to Rstudio

### ISSUE THREAD

**Issue by uctqnlv** [desktop/desktop#3065]
Dear GitHub, 

Rstudio is saying that installation has failed for certain packages. 

Can you explain why this may be the case? 

Many thanks, 

Natasha

Have you read GitHub Desktop's Code of Conduct? By filing an Issue, you are
expected to comply with it, including treating everyone with respect:

https://github.com/desktop/desktop/blob/master/CODE_OF_CONDUCT.md

-->

### Description

[Description of the issue]

### Version

**GitHub Desktop version:** [version here]

**OS version:** [version here]

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by tierninho** [comment]
@uctqnlv  thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by shiftkey** [comment]
@uctqnlv this project is unrelated to RStudio - please get in touch with them over on their home page https://github.com/rstudio/rstudio
