### ISSUE TITLE
Sort list of organizations when publishing a repository

### ISSUE THREAD

**Issue by JeffCohen** [desktop/desktop#3080]
### Description

When publishing a new repo, the Publish dialog shows a list of organizations.  It would be great to sort that list of organizations, either alphabetically or (somehow) by most recently used.

**GitHub Desktop version:** 1.0.4

**OS version:** 10.13

### Steps to Reproduce

1. Create a new repository with at least one commit
1. Click "Publish"

**Expected behavior:** A sorted list of organizations

**Actual behavior:** Currently unsorted, seems random

**Reproduces how often:** 100%

Thank you!

**Comment by iAmWillShepherd** [comment]
Great suggestion! 😀

**Comment by shiftkey** [comment]
Marking this as `help-wanted` because I think this is a simple fix. The easiest place to set this would be in [`renderOrgs`](https://github.com/desktop/desktop/blob/8824fc0ca27e146ffa4fd7365c112d25221614a7/app/src/ui/publish-repository/publish-repository.tsx#L102) in [`publish-repository.tsx`](https://github.com/desktop/desktop/blob/master/app/src/ui/publish-repository/publish-repository.tsx)

I threw together this quick and dirty patch as a starting point, but I'm sure someone else can do better:

```diff
       </option>
     )

+    const orgs = new Array(...this.state.orgs)
+    orgs.sort((x, y) => compare(x.name, y.name))
+
     let selectedIndex = -1
     const selectedOrg = this.props.settings.org
-    for (const [index, org] of this.state.orgs.entries()) {
+    for (const [index, org] of orgs.entries()) {
       if (selectedOrg && selectedOrg.id === org.id) {
         selectedIndex = index
       }
```

The `compare` function is one of our helpers: https://github.com/desktop/desktop/blob/master/app/src/lib/compare.ts

**Comment by JeffCohen** [comment]
If it works, I say ship it :-)

**Comment by Venkat5694** [comment]
@shiftkey I tried fixing this but I'm blocked by #3364 . Can someone guide me as to what the next steps are?
