### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by VladimirDziu** [desktop/desktop#3103]
What this?
Commit failed - exit code 128 received, with output

**Comment by j-f1** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
