### ISSUE TITLE
Update the delete branch error message for Protected branches

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#3128]
Attempting to delete a protected branch is blocked as expected. Perhaps we could make the error message a little more readable?

<img width="531" alt="screen shot 2017-10-23 at 5 30 52 pm" src="https://user-images.githubusercontent.com/14828183/31897897-fb5c6192-b817-11e7-89a3-157e22627e10.png">

v1.0.5beta0, mac

**Comment by shiftkey** [comment]
@tierninho can you log this (and other sorts of `GH***` errors we can handle better) against https://github.com/desktop/dugite and attach the raw error message from the log?

The fix for each of these is rather straightforward (adding some tests [here](https://github.com/desktop/dugite/blob/d1c05d7bed405a5a55d2b44e3314f1dbc90d1cf7/test/fast/git-process-test.ts#L172-L191) and making them pass) and I worry these are getting lost in more complex Desktop issues.

**Comment by shiftkey** [comment]
@tierninho regarding the original discussion about renaming the branch -  we'd need to use the API to find which branches are protected, cache those somewhere, and refresh it periodically we do with other API data such as PRs and issues. If we wanted to go down that path we'd need to sketch it out properly and put it on the roadmap.

**Comment by tierninho** [comment]
@shiftkey No problem. Will logs the errors in dugite. 

As for the renaming, I removed the discussion from this issue for now, as I couldn't reproduce it. Regardless if a you are on a protected branch or not, renaming a branch on Desktop does not reflect on dotcom... (as expected?!?). Let me know if you think its a roadmap item and I'll flush out the details in a new issue.

Will close this issue for now.

**Comment by shiftkey** [comment]
> Regardless if a you are on a protected branch or not, renaming a branch on Desktop does not reflect on dotcom... (as expected?!?). 

Yeah, that's expected. There might be some confusion as we don't support renaming branches on dotcom, and maybe we need to be more careful when the branch is tracking a remote branch, let alone a protected remote branch.
