### ISSUE TITLE
Make "Fetch origin" button drop-down

### ISSUE THREAD

**Issue by yuryleb** [desktop/desktop#3161]
### Description

This is just an idea of enhancement for "Fetch origin" button - make it drop down (similar to "Current repository" and "Current branch") ones with list of all registered remote repositories (produced by `git remote -v`) for the current one. And for dropped down item click do `git fetch <another remote repository>`.

Also it could be great to extend this new UI with possibility to pull from selected remote repository to selected local branch (say `git pull <remote repository> <local master>`) but this could wait a bit :wink:

I hope this enhancement makes synchronization of remote repository clones much more easier and convenient.

### Version
**GitHub Desktop version:** 1.0.4
**OS version:** Microsoft Windows 7 x64 [Version 6.1.7601]

**Comment by joshaber** [comment]
Thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I'm going to add the `future-proposal` label to this issue and close it out, so that we don't get overwhelmed with our backlog! We'll revisit these as part of our next planning session.
