### ISSUE TITLE
Filter History by path feature suggestion

### ISSUE THREAD

**Issue by davesmiths** [desktop/desktop#3178]
### Description
A feature suggestion. Sometimes I would like to know the commit history of a file in a repository, or the commit history of files beginning with a particular path. For example something akin to "git log --author-date-order --name-only path/to/files/*"

### Version

**GitHub Desktop version:** 1.0.5

**OS version:** 10.12.6

### Steps to Reproduce

**Expected behavior:**

1. Select repository
1. Show History
1. (not-yet-existing/suggested-feature behaviour follows)
1. Press CMD+F
1. The filter textbox appears
1. Type a path into the filter textbox
1. Press Enter
1. The list of commits in History is updated to show only commits with changed files matching the filter
1. When a commit is left-clicked, the files-changed list only shows files matching the filter
1. When a commit is right-clicked, a contextual menu shows with something like "View this commit unfiltered"

**Actual behavior:**

1. Select repository
1. Show History
1. The list of commits in History shows all commits to all files as normal

**Reproduces how often:**
n/a

**Comment by joshaber** [comment]
Thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I'm going to add the `future-proposal` label to this issue and close it out, so that we don't get overwhelmed with our backlog! We'll revisit these as part of our next planning session.

**Comment by davesmiths** [comment]
Thanks Josh

**Comment by spitWind** [comment]
Add fork implementation code to your own fork git, then you forget what you are going to do
@davesmiths  
They are not charitable

**Comment by billygriffin** [comment]
Hi @davesmiths, thanks so much for the issue and sorry to take so long to get to a resolution on this issue. Because we haven't seen it come up frequently from other users, we're going to remove future proposal here to indicate that we don't intend to support this in the near term. We likely will look at searching and/or filtering commits at some point, but that's not on our current roadmap. Thanks for the issue and we really appreciate the idea.

**Comment by davesmiths** [comment]
You're welcome, and thanks for having a look. I imagine your inbox is a wee bit on the large size!
