### ISSUE TITLE
Allow user to create origin/HEAD branch?

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#3196]
So if you create a new branch called "origin/HEAD" then you end up with two similar branches: `/heads/` and `/remotes/`. 

When selecting `/heads/` the branch, it is displayed as a detached HEAD in the nav bar, and cannot be published, as expected.

Items we should protect against:
- Blocking the naming of branches with origin/HEAD?
- Trying to commit anything to this branch, ends up with the commit being lost. Error message?
- Also, the Rename, Delete, etc. branch options are still available in the Branch menu. Should be greyed out.

<img width="503" alt="screen shot 2017-10-30 at 11 54 26 am" src="https://user-images.githubusercontent.com/14828183/32167786-5c17efc2-bd6a-11e7-9932-e6890cd12418.png">
<img width="731" alt="screen shot 2017-10-30 at 11 54 10 am" src="https://user-images.githubusercontent.com/14828183/32167787-5c342f20-bd6a-11e7-803f-467efc303c30.png">

tested: mac, 1.0.7-beta0

**Comment by niik** [comment]
I'm inclined to say that we shouldn't address this in the app. When we're creating a branch we're not doing anything magic, we're just handing the branch name off to Git to do it's thing.

Technically speaking what you've done here isn't illegal as far as Git is concerned although it's certainly not easy to understand. You've created a branch called `origin/HEAD` which is distinct from the reference called `HEAD` underneath the `origin` remote (`refs/heads/origin/HEAD` vs `refs/remotes/origin/HEAD`). When you try to check out the remote ref `origin/HEAD` there's no way to check it out by name since it would conflict with the `HEAD` ref so Git detached `HEAD`.

In the case of GitHub repositories the `HEAD` ref (on the remote) is a symbolic ref to the default branch (in this case `master`). So while I don't think there's anything for us to do here as far as the creation phase I wonder if we should perhaps get rid of the `origin/HEAD` ref from the branch list. Either by manually filtering it based on the canonical name (`refs/remotes/\w+/HEAD`) or by getting rid of all symbolic refs from remotes.

@desktop/core any thoughts on this?

**Comment by shiftkey** [comment]
>  I wonder if we should perhaps get rid of the `origin/HEAD` ref from the branch list

I can get behind this idea
