### ISSUE TITLE
Add placeholder name in App

### ISSUE THREAD

**Issue by Pletron** [desktop/desktop#3197]
### Description

The ability to add a local placeholder name for a repo. The application sets the repo name to the name of the folder the repo is located within. It would be great to be able to set a "local" name for each project and not be dependent on the folder within which the project subsides.

### Version

**GitHub Desktop version:** 1.0.6

**OS version:** macOS 10.12.6

### Steps to Reproduce

1. Add a local repository to GitHub Desktop

**Expected behavior:** Prompt to show what to name the repo placeholder title.

**Actual behavior:** Just adds the repo to the app and holds the name of the local repo folder.

**Reproduces how often:** 100%

### Logs

No logs.

#### Additional Information

I now have three repos with the name "app" due to naming the after the folder (see pic).

<img width="1567" alt="screen shot 2017-10-30 at 16 22 29" src="https://user-images.githubusercontent.com/1712993/32179101-c6a831c0-bd8e-11e7-9f8e-1b98a4ae3cb8.png">

**Comment by niik** [comment]
Hey @Pletron, thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I added the `future-proposal` label to this issue and closed it so that we won't get overwhelmed with our backlog! We will revisit this in our next planning session.

**Comment by billygriffin** [comment]
This is similar to https://github.com/desktop/desktop/issues/2324 so I'm going to remove `future proposal` as we're tracking it there. Thank you @phmasek!
