### ISSUE TITLE
希望增加修改的仓库的提示

### ISSUE THREAD

**Issue by ChainGit** [desktop/desktop#3203]
本地仓库再其他地方修改后，希望列表中能有红点或*号提示，这样比较直观方便

**Comment by tierninho** [comment]
@ChainGit  thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
