### ISSUE TITLE
Trouble with merging a branch with a commit on an excel document within it.

### ISSUE THREAD

**Issue by ManuelHJ** [desktop/desktop#3217]
Hi

I need help with the merge of a branch with the master, because, with the pull request, it says something like "this branch has too many unresolved conflicts". I am thinking that the .xls and .doc type of files doesn't apply to a version system like gitHub. 

### Description

[Description of the issue]

### Version

**GitHub Desktop version:** [version here]

**OS version:** [version here]

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by niik** [comment]
Hi @ManuelHJ. You're right that .xls/.doc files are not text but rather binary content which isn't easy to merge by hand. 

Your best bet here would be to manually open both versions of the file and make sure that the necessary changes from both are incorporated or if you know which version should prevail you can pick that one.

In order to pick your version over the other you can merge the master branch into your branch in GitHub Desktop. That will show you which files are conflicted. If you discard the conflicted files you'll have picked your version over that in master.

The conflict resolution support in GitHub Desktop is still being developed so you might be better off following a guide like https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/
