### ISSUE TITLE
Select more than one editor/shell to be in the submenu. 

### ISSUE THREAD

**Issue by adambirds** [desktop/desktop#3221]
# Feature Request

### The current situation

We currently have the ability to select one default shell/editor to be available in the repository submenu.

### What feature I would like to see

I would like the option to be able to pick multiple shells/editors to be shown in the submenu. This is because sometimes I like a different editor/shell depending on what I'm doing.

**Comment by shiftkey** [comment]
> This is because sometimes I like a different editor/shell depending on what I'm doing.

Could you tell me a bit more about this use case? I'm also curious how we'd expose this in the app - let me know what your thoughts were on this...

**Comment by adambirds** [comment]
My Idea would be rather than having the "Open in Atom" or "Open in VSCode" item under the repository drop down, would be to have open in editor which then expands to the right with several editors available, if you get what I mean @shiftkey

**Comment by simoniz0r** [comment]
I would also like to see this.  IMO, the user should be able to choose any editor and/or terminal.  GitHubDesktop could provide something like `%s` for the filename that would be opened so that the user could add the necessary arguments to their editor to have the file be opened.

Having a custom input box where I could enter something like `/usr/bin/code -r %s` would be great!

**Comment by shiftkey** [comment]
This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I added the `future-proposal` label to this issue and closed it so that we won't get overwhelmed with our backlog! We will revisit this in our next planning session.

**Comment by billygriffin** [comment]
I missed this previously but I'm going to remove the future proposal label and track this in the open issue #5891.
