### ISSUE TITLE
New repository behaviour doesn't match GitHub.com

### ISSUE THREAD

**Issue by strafe** [desktop/desktop#3233]
### Description

When creating a new repository through GitHub Desktop with the settings shown below an _"Initial commit"_ gets made for you, adding a default `.gitattributes` file _(which has no new line for whatever reason)_. However, when you create one through GitHub.com with the same settings you get a blank repository to work with. Personally I prefer it to be completely blank, I understand that this commit can be undone straight away but it seems strange to have it different than GitHub.com.
<hr>

### Version

**GitHub Desktop version:** 1.0.6

**OS version:** Windows 10 Home `10.0.15063 - Build 15063`
<hr>

### Steps to Reproduce

1. Create a new repository on GitHub.com with the settings shown below.
1. Create a new respository through GitHub desktop with the settings shown below.
1. See the _"Initial commit"_ that only gets made on the second repository.

**Expected behavior:** A blank repository with no commits.

**Actual behavior:** A repository already containing an _"Initial commit"_.

**Reproduces how often:** 100%
<hr>

### Additional Information

![settings](https://user-images.githubusercontent.com/15663890/32409047-e81ee252-c19b-11e7-8374-63f0e7acdaed.png)

**Comment by shiftkey** [comment]
@strafe this is a behaviour that comes from the classic apps.

We differ from GitHub The Website because we want to avoid potential line endings issues, and so we'll add a simple `.gitattributes` file to the repository as part of the initial commit.

You can immediately undo this first commit if you want, but we recommend keeping this file around because it'll override whatever you have setup for `core.autocrlf` and `core.safecrlf` which can be painful - particularly for Windows users.

Let me know if you have any further questions about this, or suggestions for how we can make this experience better.

**Comment by strafe** [comment]
@shiftkey sorry I haven't replied to this in a few days, not that I'm familiar with any of that but I'm sure if there's a reason it's a good one.

I am still curious why the file doesn't have a new line at the end though since GitHub loves to point those out.

**Comment by shiftkey** [comment]
> I am still curious why the file doesn't have a new line at the end though since GitHub loves to point those out.

Probably because we didn't add one when we insert it:

https://github.com/desktop/desktop/blob/71c268042b6040a49cc5307111ef3d819b691486/app/src/ui/add-repository/git-attributes.ts#L7-L13

Feel free to submit a PR to add that newline, it does make sense for us to avoid unnecessary line ending warnings whenever we can.

**Comment by shiftkey** [comment]
> not that I'm familiar with any of that but I'm sure if there's a reason it's a good one.

Probably the best summary of Git and line endings (and how we ended up with `.gitattributes) is this piece by @tclem: ["Mind the End of Your Line"](http://adaptivepatchwork.com/2012/03/01/mind-the-end-of-your-line/). Have a read of that when you get a chance.

**Comment by strafe** [comment]
@shiftkey thank you, who knew there could be so much to line endings 👀 

I've noticed that if for example I make a `.gitattributes` ahead of time in my project's folder (before it's been initialized) and then create a new repository using `desktop` within that folder it will overwrite my existing one with the default, is that intended too?

**Comment by joshaber** [comment]
Yes, unfortunately line endings are thorny 😱 

>I've noticed that if for example I make a .gitattributes ahead of time in my project's folder (before it's been initialized) and then create a new repository using desktop within that folder it will overwrite my existing one with the default, is that intended too?

Hmm that sounds like a bug. Would you mind opening an issue specifically about that?
