### ISSUE TITLE
problem with upstream adding to forks

### ISSUE THREAD

**Issue by tooomm** [desktop/desktop#3252]
### Description

>just updated my client to 1.0.7
>
>but i get this dialog in a loop now:
![fork](https://user-images.githubusercontent.com/9874850/32501910-96816628-c3d9-11e7-99b6-f4a9f65d1333.png)
>
>two confusions here:
>- why is the current link identical to the expected one?
>- why do i see this dialog every time i switch to that fork? even after hitting `update` ?

from https://github.com/desktop/desktop/pull/3199#issuecomment-342520769

### Version

**GitHub Desktop version:** 1.0.7

**OS version:** Microsoft Windows [Version 10.0.16299.19]

### Steps to Reproduce

1. Switch to a fork in desktop app
2. Popup appears, hit `Update`
3. Switch to another repo and back to the same fork shortly after (or close app in between, doesn't matter)
4. Popup appears again

**Expected behavior:** Only show popup once

**Actual behavior:** Popup shows every time

**Reproduces how often:** always

**Comment by joshaber** [comment]
Thanks @tooomm! Could you run `git remote -v` and paste the output in here?

**Comment by tooomm** [comment]
```
$ git remote -v
origin  https://github.com/tooomm/github-release-stats.git (fetch)
origin  https://github.com/tooomm/github-release-stats.git (push)
prsender        https://github.com/luclu/github-release-stats.git (fetch)
prsender        https://github.com/luclu/github-release-stats.git (push)
upstream        https://github.com/Somsubhra/github-release-stats.git (fetch)
upstream        https://github.com/Somsubhra/github-release-stats.git (push)
```

**Comment by scottnath** [comment]
I am getting this too on enterprise:

![screen shot 2017-11-07 at 11 11 47 am](https://user-images.githubusercontent.com/216931/32504384-b20192aa-c3ad-11e7-9bef-4a71dd7d9b73.png)

I discovered that it is about the Capital letters. If I go into my git config and change my remote to use lower-case letters for the Organization name, then this problem is fixed and it can work with the upstream without issue.

I think the reason it keeps showing the popup after clicking `Update` is that it does not get "fixed". But the fix is that the org needs to be in all lowercase, which is not what it does as the `expected` selection is also using uppercase letters.

**Comment by joshaber** [comment]
@scottnath Yup, that's exactly right! I've opened #3256 to fix this. We should have an update out later today.
