### ISSUE TITLE
how to set proxy in github desktop. I am getting the error Could not resolve host: github.com

### ISSUE THREAD

**Issue by sanjayameher** [desktop/desktop#3264]
### Description

[Description of the issue]

### Version

**GitHub Desktop version:** [version here]

**OS version:** [version here]

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by tierninho** [comment]
@sanjayameher  user-name thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by sanjayameher** [comment]
can you pls let me know which template you want

**Comment by j-f1** [comment]
@sanjayameher If you click the edit button on the first comment of the issue, there should be instructions on filling out the parts of the template in [].
