### ISSUE TITLE
git clone fail. SSL Proxy error. 

### ISSUE THREAD

**Issue by AtomicCons** [desktop/desktop#3316]
During clone getting a fatal error.
Using an SSL proxy. Do not see a way to import the CA like i was able to on older versions of git and with Atom.
schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
Error(s) during clone:
git clone failed: exit status 128

**Comment by joshaber** [comment]
Hi @AtomicCons!

We've had a few reports of this specific error, but it's not been made clear to me how we might be misusing the SChannel APIs, so the best advice I have for you is how to switch over to using the classic OpenSSL APIs alongside your own certificate bundle.

Open a shell to your repository and run these command:

```sh
$ git config --local http.sslBackend "openssl"
$ git config --local http.sslCAInfo [path to .pem file]
```

Then test it out with a `git fetch` to ensure it is able to connect to your server.

**Comment by AtomicCons** [comment]
@joshaber ,
Sorry about the lack of information. Basically my company uses a SSL proxy. Past versions of git desktop and atom allow me to add the pem certificate content directly to the ca file. I was able to install the CA by using 
`git config --global http.sslCAInfo [path to .pem file] `

I'm slightly surprised i cannot copy the content of my CA cert into \app-1.0.8\resources\app\git\mingw64\ssl\cert.pem

**Comment by shiftkey** [comment]
> I'm slightly surprised i cannot copy the content of my CA cert into `\app-1.0.8\resources\app\git\mingw64\ssl\cert.pem`

Some extra context:

Git for Windows has supported switching between OpenSSL and SChannel through configuration for a few releases (since [2.14.0](https://github.com/git-for-windows/git/releases/tag/v2.14.0.windows.1)) and Desktop sets itself to use SChannel in it's system configuration in [the upstream packaging](https://github.com/desktop/dugite-native/blob/master/script/build-win32.sh#L53-L56). We chose this approach to avoid the additional work of synchronizing certificates from the Windows Certificate Store to a bundle - which is what the classic app does.

I'd love to figure out how to interoperate nicely with SSL proxies, but as I understand it we're using vanilla SChannel APIs inside libcurl so more information is needed to try and recreate this in an isolated environment (using just `curl` would be ideal).
