### ISSUE TITLE
Logged in but Commits with my name and "Unknown User" on github

### ISSUE THREAD

**Issue by HammiKnuff** [desktop/desktop#3320]
Logged in but Commits with my name and "Unknown User" on github

**Comment by tierninho** [comment]
@HammiKnuff  thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by joshaber** [comment]
Whoops, looks like our bot got a little too aggressive. Re-opening.

**Comment by niik** [comment]
Thank you for your issue!

We haven't gotten a response to our questions above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by JennHM** [comment]
Logged in but Commits with my name and "Unknown User" on github [Desktop] - This has happened to me.  Please tell me how I can provide more info 
- signed in under "Options"
- can commit using browser
