### ISSUE TITLE
Can't push to existing repository

### ISSUE THREAD

**Issue by Fyvon0** [desktop/desktop#3340]
I've cloned a repository to my pc and now I'm trying to push but it doesn't recognize the existing repo and is asking me if I want to create a new one

**Comment by tierninho** [comment]
@Fyvon0  thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by niik** [comment]
Thank you for your issue!

We haven't gotten a response to our questions.
With only the information that is currently in the issue, we don't have enough
information to take action. I'm going to close this but don't hesitate to reach
out if you have or find the answers we need, we'll be happy to reopen the
issue.
