### ISSUE TITLE
Long branch name is double truncated

### ISSUE THREAD

**Issue by joshaber** [desktop/desktop#3396]
As of #3357 we're supposed to be doing fancy middle truncation. But it looks like we're really doing double truncation 🤔 

The branch name is `ignore-menu-events-when-modal-showing`.

<img width="240" alt="screen shot 2017-11-21 at 9 11 40 am" src="https://user-images.githubusercontent.com/13760/33076885-0be26a58-ce9c-11e7-88c7-9cc7e7cb2e44.png">

**Comment by niik** [comment]
Welp, I really thought I had fixed this. This is what the max-width 100% is supposed to solve. I'll take a look at it.

**Comment by niik** [comment]
So this happens because there's some resizing going on in that button as it's switching branches (and displaying progress). The branch icon is switched for a spinner (which is wider) and the dropdown arrow is hidden. We'll either have to put a resize observer on it or manually calculate the available width like we do in the file lists.

**Comment by joshaber** [comment]
Related but different, this also reverses the direction of slashes for branch names on Windows:

![pasted image at 2017_12_06 12_51 pm](https://user-images.githubusercontent.com/13760/33661055-3924c2cc-da54-11e7-9534-40864964a85a.png)

**Comment by joewiz** [comment]
Should this be closed now that #3598 is merged?

**Comment by shiftkey** [comment]
@joewiz I don't think we got to the branch switcher (which is the original screenshot rather than what was updated in #3598). Is that right @niik?

**Comment by niik** [comment]
> I don't think we got to the branch switcher (which is the original screenshot rather than what was updated in #3598). Is that right @niik?

Yeah, that's right. There were unexpected complications with putting the path truncation strategy to use in the branch button so we reverted it. I think we should close this up, the underlying problem is sufficiently captured in https://github.com/desktop/desktop/issues/4177 and the discussion in the original PR https://github.com/desktop/desktop/pull/3269#issuecomment-344648587 so I'm going to close this one out
