### ISSUE TITLE
API Rate Limit Exceeded Errors

### ISSUE THREAD

**Issue by clinejj** [desktop/desktop#3398]
### Description

After updating to the newest release of the Mac Desktop app, I get "API Rate Limit Exceeded" whenever I try to authorize or add credentials. I do not get the same error when using the command line.

### Version
**GitHub Desktop version:** 1.0.9
**OS version:** MacOS Sierra 10.12.6

### Steps to Reproduce

1. Add github.com authentication (either through the app signin form or using the web login)
1. Error occurs after opening the app

**Expected behavior:** I authenticate successfully and am able to use the app

**Actual behavior:** I cannot authenticate and therefore cannot interact with github.com

**Reproduces how often:** Every time

### Logs

2017-11-21T17:20:47.596Z - warn: [ui] fetchAccount: failed with endpoint https://api.github.com
Error: API rate limit exceeded for clinejj.
    at Object.t.parsedResponse (/webpack:/app/src/lib/http.ts:153:1)
    at <anonymous>
2017-11-21T17:20:47.597Z - warn: [ui] fetchUser: failed with endpoint https://api.github.com
Error: API rate limit exceeded for clinejj.
    at Object.t.parsedResponse (/webpack:/app/src/lib/http.ts:153:1)
    at <anonymous>
2017-11-21T17:20:47.598Z - info: [ui] [SignInStore] error with OAuth flow
Error: API rate limit exceeded for clinejj.
    at Object.t.parsedResponse (/webpack:/app/src/lib/http.ts:153:1)
    at <anonymous>

**Comment by clinejj** [comment]
To note - I tried uninstalling and reinstalling the desktop app with no success

**Comment by j-f1** [comment]
FYI [this](https://github.com/desktop/desktop/blob/master/app/src/lib/http.ts#L151) is the line that the error is thrown from.

**Comment by niik** [comment]
Hi @clinejj. The most likely explanation here is that this error is in fact correct and you've exhausted your API limit for the moment. This doesn't mean that you've done so using GitHub Desktop though.

See [our documentation about rate limiting](https://developer.github.com/v3/#rate-limiting).

> all OAuth applications authorized by a user share the same quota of 5000 requests per hour

Is it possible that you've got other application installed on your account that may be issuing frequent requests to the API? Perhaps polling (CI) or other tools like issue managers that have been configured to query the API frequently or which are connected to loads of repositories?

If you could reach out to [our support team](https://github.com/contact) they'll be happy to help you diagnose what might be using up your limit so quickly. API limit resets on the hour though so right now would be a good time to try again while there's still plenty of requests available for your account.

In the rate limit documentation I mentioned before there's also information on how to query the API for your current rate limit so that you can see whether it's going down quickly or not.

I'm going to close this issue for now but if our support team identifies GitHub Desktop as a source of high API usage we'd love to hear about it so that we can get to the bottom of it. Just add a comment here and we'll reopen if that's the case.

**Comment by clinejj** [comment]
Thanks @niik - waiting an hour seemed to fix it, although a bit confusing to me that the only time I've ever gotten this issue was when updating versions of the app. My token is not getting used in any automation, so the only usage is in the desktop app.
