### ISSUE TITLE
Github Desktop should be considered BETA and GH4W should be offered as an alternative

### ISSUE THREAD

**Issue by Sophist-UK** [desktop/desktop#3400]
### Description

The number of issues with GD is sufficient to demonstrate this.

### Version

**GitHub Desktop version:** 1.08

**OS version:** Windows 10

**Comment by lee-dohm** [comment]
Thanks for the feedback.

One of the core philosophies of most open source is ship early and iterate. We feel we've done that as can be shown by the 490 PRs that [have been merged](https://github.com/desktop/desktop/pulls?utf8=✓&q=is%3Apr%20is%3Amerged%20merged%3A%3E%3D2017-05-16) since we shipped the initial (actually beta) public version of Desktop on May 16, 2017. We can understand if it doesn't meet your specific requirements but we feel that, for most people, it is ready for common use.

Thanks again for your interest in GitHub Desktop :+1:
