### ISSUE TITLE
A better Debian package name

### ISSUE THREAD

**Issue by mitar** [desktop/desktop#3424]
I am looking at Debian package and its name is simply `desktop`. I think renaming it to `github` or `github-desktop` would be much better.

**Comment by shiftkey** [comment]
@mitar can you link to the package? I can't seem to find it on https://packages.debian.org/...

**Comment by mitar** [comment]
It is the one I generated through `yarn package`.

**Comment by niik** [comment]
Hi @mitar, we're happy to review community contributions for Linux support but we don't have enough experience using Linux ourselves. From a naïve point of view I'd say that if they choice had to be made between 'desktop' and 'github-desktop' we'd choose the latter. The macOS and Windows installers use 'GitHub Desktop' and 'GitHubDesktop' respectively. I imagine there's some way to override the name for a particular package?

Since we're not officially supporting Linux right now I am going to close this out but as I said, we're really happy to see work being done towards Linux support.
