### ISSUE TITLE
Debian package desktop binary has a wrong symlink

### ISSUE THREAD

**Issue by mitar** [desktop/desktop#3426]
### Description

I built a Debian package and it seems it creates a `/usr/bin/desktop` symlink to `../lib/desktop/desktop`.

The issue is, it should be `../lib/desktop/GitHub Desktop` because this is what exists.

### Version

**GitHub Desktop version:** update-electron-builder-linux branch

**OS version:** Ubuntu 17.10

### Steps to Reproduce

Built Debian package with `yarn package`. Install it.

**Expected behavior:** Running `desktop` runs.

**Actual behavior:** It does not run.

**Reproduces how often:** Always.

**Comment by mitar** [comment]
Moreover, app's icon is also not found.

**Comment by niik** [comment]
Hey @mitar. The command line tool installation assumes macOS os Windows at the moment but we'd gladly accept a PR to make it work on Linux as well.

Relevant mac logic: https://github.com/desktop/desktop/blob/master/app/src/ui/lib/install-cli.ts#L10-L11
Relevant Windows logic: https://github.com/desktop/desktop/blob/05086e011acc73b5847742fc3325ee2acb9db2ff/app/src/main-process/squirrel-updater.ts#L47-L56

Relevant PR: https://github.com/desktop/desktop/pull/1925

I'm going to close this out for now since we're not officially targeting Linux at the moment but as I said. We'd gladly accept a PR for this. Thanks to community contributions we're slowly working our way towards a stable Linux client.

**Comment by mitar** [comment]
Hm, this is not about installer, but about a package produces by `yarn package`. I see that you are just working on this, so I am reporting issues with current work in progress.
