### ISSUE TITLE
Support external Git installations [request]

### ISSUE THREAD

**Issue by DRSDavidSoft** [desktop/desktop#3435]
### Description

I appreciate the fact that GitHub desktop comes pre-bundled with its own installation of git-for-windows, however it gets really annoying when by using both CLI and GUI, I end up having **two** (or more) instances of `git.exe`.

Is there any way to set GitHub desktop to use the installed `git.exe` in my `%PATH%` instead of installing its own version? (If compatibility issues are to be considered, maybe also using `git.exe --version` to compare the version, and if the `git.exe` is too old or too new, warn the user to either update or use the internal git-for-windows instead.)

Thank you!

**Comment by shiftkey** [comment]
@DRSDavidSoft there's a few reasons why we have an embedded version of Git that ships with Desktop:

 - not everyone has a version of Git installed when they're getting started with Desktop
 - the version of Git we ship is stripped of features that we don't need in an embedded scenario, to reduce the installer size
 - some things that Git distributes causes Desktop headaches (localized error messages is an example)
 - we configure a credential manager with Desktop to handle credentials (this defers to the keychain/credential store) instead of requiring you to configure this

> If compatibility issues are to be considered, maybe also using `git.exe --version` to compare the version, and if the `git.exe` is too old or too new, warn the user to either update or use the internal git-for-windows instead.

We also sometimes opt-in to features that are in recent versions of Git:

 - we can workaround shell limits on Windows by using certain flags that `git reset` supports:  https://github.com/desktop/desktop/pull/2877
 - in Git 2.15 [`git status` supports passing `--no-optional-locks` to speed it up](https://github.com/git/git/blob/master/Documentation/RelNotes/2.15.0.txt#L97-L100)) - we should add this into Desktop

Being able to easily trace which version of Git you are running with a specific build of Desktop does help greatly when we investigate issues, and Git functionality is a core part of Desktop, so removing that assumption does concern me greatly.

**Comment by niik** [comment]
> so removing that assumption does concern me greatly.

I agree fully with what @shiftkey said. It's unlikely that we'll support using an external installation of Git for the internal commands Desktop needs to run in the near-term. I'm going to close this out for now.
