### ISSUE TITLE
Enhacement to see fastly which Repo have been changed/updated

### ISSUE THREAD

**Issue by Portekoi** [desktop/desktop#3463]
We are working with a micro-service structure and we have about 25 projects.

it cool be very nice to see in the list on the left : 
* which Repo have been updated by another developer
* which Repo have been changed by me 

Is it a future enhancement?

List example below : `fr.Vehicles` have been updated this night but I did not see it directly. 

![image](https://user-images.githubusercontent.com/1560754/33424335-d39ce50c-d5bb-11e7-9b62-c2b036d6084d.png)

**Comment by niik** [comment]
Thanks for the suggestion!

This idea is definitely interesting for the future, but it's beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

We've talked about various ways of doing this in the past, ranging from detecting that you've got local, uncommitted, changes to actually fetching all projects in the background. There's a lot of corner cases here though and we'd need to find ways of performing these checks in a performant manner.

I added the `future-proposal` label to this issue and closed it so that we won't get overwhelmed with our backlog! We will revisit this in our next planning session.

**Comment by Portekoi** [comment]
Some news about this suggestion? it's very hard to see easily which repositories are not synchronized and we have now about 20  of it...

**Comment by iAmWillShepherd** [comment]
@Portekoi, have a look at our [roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md) to get a peek at what's coming.

**Comment by shiftkey** [comment]
I'm going to drop the `future-proposal` label from this as #4770 has been merged and will be available in an upcoming update.
