### ISSUE TITLE
Create a new branch from a previous commit

### ISSUE THREAD

**Issue by kaster14** [desktop/desktop#3474]
-Ability to checkout any previous commit, sometimes I want to go back and test something for legacy product support or to find out where a bug first started. For example in the history tab right click on a commit and select "set code to this commit" which would set the code to the way it was at the time of that commit without making a new commit that reverts all of the commits above it.

### Description

Feature request: "checkout previous commit"

**Comment by j-f1** [comment]
“Checkout this commit”

**Comment by shiftkey** [comment]
"Revert" has existing meaning in Git that differs to what's discussed here. It's about undoing a single commit by applying a new commit to the current branch. We also talked about "Rollback" functionality in #2347 that we don't plan to support for reasons outlined in that issue.

I think what's being discussed here is more like `git checkout SHA`, which then puts you in a detached HEAD state.

@kaster14 could you elaborate on what this gives you beyond being able to move to a specific point in the history? Are there specific workflows or features that would make your life easier?

**Comment by TCSDCC** [comment]
@shiftkey - Forgive me if I don't use the proper terminology and therefore don't clearly communicate, I'm not too familiar with the Git cmd line.

I have done a git check SHA before to accomplish this but am looking for a way to do this from the desktop application. What I'm looking to do is essentially "move to a specific point in the history" temporarily.

Use case would be customer calls and says I have firmware x.y.z and I am seeing this bug.
I would then want to load firmware x.y.z and test to see if I can repeat and fix said bug, however version x.y.z was 20 commits ago. It would be nice if I could do something like go to the history, go to the commit that was version x.y.z and right click "go to this point in code" (which does a Git checkout SHA and makes a detached head, but from the desktop application standpoint it would "still in the same branch" just going back in time)
If I then make changes to fix the bug at that point it would create a new branch, I fix the bug, then can pull request and merge the bug fix.

After looking online some more it looks like what I'm looking for is the cmd line equivalent of "Git reset --soft TAG1"  - which would also require being able to make and see tags in the desktop app (If that's possible I'm not aware of how to do that)

**Comment by j-f1** [comment]
For tag support, see #257. If that feature gets implemented, you’ll be able to check out the version tag, fix the bug, and checkout a new branch from the commit.

**Comment by iAmWillShepherd** [comment]
Thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md). I added the `future-proposal` label to this issue and closed it so that we won't get overwhelmed with our backlog! 

We will revisit this in our next planning session.

**Comment by kaster14** [comment]
Thanks @iAmWillShepherd !

**Comment by cdmihai** [comment]
Scenarios that come to mind:
- Run tests. As I code, I don't necessarily want to get interrupted with committing, so often I gather a pile of different code changes that I then split into commits. When I split off a commit from the pile of changes, I then rebase it further down in history (I like to separate `supportive changes for my feature` from `changes for the actual feature`), checkout to the tip of `supportive changes`, run tests, then checkout to branch head and continue on. This reminds of the concept of "commit bubbles": http://static.barik.net/barik/publications/icsenier2015/PID3566869.pdf
- Manual bisect. Sometimes I screw something up in my trail of commits which is not covered by tests so I need to quick jump back a few commits to identity where I screwed up. For this I also save some new test in the git stash that I keep applying on older commits
- Get output from older commits to compare to current commit. Could be logs, performance profiles, or just debugging a recent commit to understand how program flow changed, etc.

Sometimes I use different branches to do these things, sometimes not, depending on whether it's repetitive or not.

**Comment by j-f1** [comment]
> Sometimes I duplicate the repo to have the codebase at two commits at the same time.

You might be interested in [`git worktree`](https://devdocs.io/git/git-worktree), which allows you to have two copies of the repo backed by the same `.git` directory.

**Comment by billygriffin** [comment]
From @the-avid-engineer in #7719 

I often find myself using the CLI to enter a Detached HEAD state in order to see a previous version of a repository, usually to browse the contents with my IDE.

Before 2.0, I did not have to worry about uncommitted changes. But with 2.0, I ran into a problem. The stashing feature (which is **great**, by the way) prevents me from switching to a branch if I happened to have uncommitted changes *before* i switched to the detached head state via CLI.

You can read about that, here: https://github.com/desktop/desktop/issues/7715

**[Optional] Do you have any potential solutions in mind?**
If it was possible to create a branch from a commit, I would never need the CLI; my entire git workflow would be served by GitHub Desktop, and I would never have to enter a detached head state.

![image](https://user-images.githubusercontent.com/36554739/59073691-ec1a9c80-887c-11e9-844e-e55f4c7bd430.png)

Ideally, there would be a new option on this History context menu shown above, such as "Branch from this commit".

Clicking on this option would bring up a "New Branch" modal so the user can name their branch; instead of basing off of a branch, it would be based off of the commit the user chose.

If there are any uncommitted changes, the Switch Branch modal should pop up and ask if the user wants to leave changes on the current branch or bring them to the new branch.

Problem solved!

**Comment by PaulAtST** [comment]
Checking out a specific commit would definitely be a useful feature. 

I often use it when tracking down what commit induced a strange bug.

**Comment by billygriffin** [comment]
Hi folks, thank you for all the feedback and for your patience. We're working on this, and digging into it, we're a bit concerned about the pitfalls of checking out a previous commit on your current branch and how people might get into trouble in ways we can't predict. But in talking with users and investigating other related issue threads, we think @the-avid-engineer's proposed approach is a great one.

So I've renamed this issue to be about creating a new branch from a previous commit, which isn't exactly the same but does attempt to solve the same problem and hopefully in a way that's less apt to cause problems for people. I'm going to reopen this since we've prioritized and started working on it. Please feel free to respond here with any feedback or other thoughts!

**Comment by billygriffin** [comment]
We just merged the PR (#12160) allowing you to create a branch from a previous commit, so I'm going to close this issue! We'll likely ship this to beta sometime next week. 😄

**Comment by the-avid-engineer** [comment]
AWESOME!

**Comment by kaster14** [comment]
Thanks! What I was (am) looking for was exactly what @the-avid-engineer suggested, looking forward to using it :-)

**Comment by the-avid-engineer** [comment]
![image](https://user-images.githubusercontent.com/36554739/122303423-5fb60200-ceb8-11eb-8e3d-0ac88a4f14e1.png)

🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉

**Comment by cyaskoskiAAA** [comment]
Thanks I just had a use case for this today. Couldn't find the feature in the WebUI but was able to use the desktop application to perform the action.

**Comment by cokecocacolamax** [comment]
ในวันที่ ศ. 2 มิ.ย. 2023 01:21 น. cyaskoskiAAA ***@***.***>
เขียนว่า:

**Comment by andrewbunac** [comment]
In TFS, there is a function where you can create a new branch from a specific Git commit in the web interface. I'm not sure if GitHub already has something like this, but I hope it does.

![image](https://github.com/user-attachments/assets/036803ef-c69e-4084-b750-0afbd965c54e)

**Comment by steveward** [comment]
@andrewbunac GitHub Desktop [does have this functionality](https://docs.github.com/en/desktop/making-changes-in-a-branch/managing-branches-in-github-desktop#creating-a-branch-from-a-previous-commit). If you have feedback about GitHub the website please share it [here](https://github.com/orgs/community/discussions).

**Comment by steveward** [comment]
@andrewbunac GitHub Desktop [does have this functionality](https://docs.github.com/en/desktop/making-changes-in-a-branch/managing-branches-in-github-desktop#creating-a-branch-from-a-previous-commit). If you have feedback about GitHub the website please share it [here](https://github.com/orgs/community/discussions).

**Comment by andrewbunac** [comment]
Oh, pardon me, I am in a wrong Thread,  
Thanks , @steveward
