### ISSUE TITLE
offer shallow clone option

### ISSUE THREAD

**Issue by katrinleinweber** [desktop/desktop#3480]
As a user who often contributes translations, documentation improvements, etc. I rarely have much use for an offline copy of a repo's entire history. I [would trade](https://github.com/katrinleinweber/konfig/blob/master/git-Arbeitsdreieck.sh) that for an option to clone shallowly, so that my workflow can be faster.

So, how about something like `[ ] fetch only the repo's current state` that executes `git clone --depth=1 --no-single-branch ...`? Maybe not `1`, but `... only recent history` or some small portion of it. I'm curios about how that could be determined before cloning.

**Comment by iAmWillShepherd** [comment]
Thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our current roadmap.

I added the future-proposal label to this issue and closed it so that we won't get overwhelmed with our backlog! We will revisit this in our next planning session.

**Comment by j-f1** [comment]
This would also be useful for users like me on a metered connection. There’s no need to download hundreds of commits from 2014 to make changes to the latest version of code.

**Comment by iAmWillShepherd** [comment]
> This would also be useful for users like me on a metered connection. There’s no need to download hundreds of commits from 2014 to make changes to the latest version of code.

That's a very good point @j-f1. This would also help those who are in countries with poor internet. This will get addressed in our next planning session soon.

**Comment by j-f1** [comment]
@katrinleinweber Thanks for posting that! I’ve already figured out how to get a shallow clone (`git clone --depth n`, then `git fetch --depth n` to get more history), but it’ll probably help other people who come here.

**Comment by katrinleinweber** [comment]
The main point there is to set up `upstream` & `origin` in one go as well. But it seems I'm carrying coal to Newcastle there: #2364 :-)

**Comment by EwoutH** [comment]
Cloning [WebKit](https://github.com/WebKit/WebKit) with GitHub Desktop was quite fun, over 9 GiB. There should be an option to do a shallow clone.

Using the git clone `--shallow-since` [parameter](https://git-scm.com/docs/git-clone#Documentation/git-clone.txt---shallow-sinceltdategt) could be an option, and only clone the last month or so. Or just allowing a shallow clone with customizable depth (100 by default or so, way better than cloning over 300 branches of about 200000 commits each!).

The engineering division of some company recently wrote [an excellent blogpost](https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone/) about it! :)

**Comment by EwoutH** [comment]
Hi @sergiou87 and @tidy-dev! Is there any chance that you could look into this issue? It would be awesome to have the option for a shallow clone in GitHub Desktop, especially if you are limited in bandwidth or storage.

**Comment by sergiou87** [comment]
Hello! 👋 

We talked about this feature and we're gonna explore our options during the next weeks 😄 

I could be a super easy thing to do… but we want to make sure there are no side-effects when the app is using a shallow clone, so we'll need to investigate a bit 🕵️‍♂️ 

Stay tuned!

**Comment by superusercode** [comment]
shouldn't this issue be reopened if shallow clones are still being considered?

**Comment by billygriffin** [comment]
Hi folks, we explored this and discussed in depth, and ultimately decided that supporting blobless clones may be more appropriate if we were going to pursue this to help solve the problem here about metered connections. However, there's a ton of complexity relating to the commit history that we don't have good answers for, and unfortunately the downsides seem to outweigh the upsides of supporting this type of functionality. Therefore, I'm going to close this issue as something we don't intend to support at this point. I know that's likely a bummer for some, and I'm sorry about that.

**Comment by duckdoom4** [comment]
As a game developer working with massive branches from artists, I would like the default behaviour of this app to be that it only fetches the current branch. This has been blocking my workflow to the point where I'm forced to change git clients to be able to work faster. 
I would like to request this issue to be revisited :)

_If shallow clone is not possible at least give us the option to only fetch the current branch_

**Comment by chakibchemso** [comment]
source tree already been doing this with no side effects at least put it as an option with experimental tag on and no one would complain about it but be thankful

**Comment by chaosvolt** [comment]
I recently tried to get around this by just blobless-cloning a particularly beefy fork in powershell instead, but afterward github desktop wouldn't recognize that I'd cloned the fork that way. Adding it manually via "add an existing repository" makes it think it's a new repo that needs to be published.

**Comment by qycyfjy** [comment]
"discussed `in depth`" and "downsides seem to `outweigh` the upsides" mean what?
