### ISSUE TITLE
GitHub Desktop failed to launch

### ISSUE THREAD

**Issue by waynejohnn** [desktop/desktop#3483]
Error: write EOF
    at exports._errnoException (util.js:1050:11)
    at WriteWrap.afterWrite (net.js:813:14)

Version: 1.0.9
OS: Windows 6.3.9600

**Comment by niik** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

Feel free to either update the body of this issue or add a comment and we'll reopen it. I'd be curious to know if your selected repository contains a lot of untracked and/or changed files.

Thanks for understanding and meeting us half way :grinning:
