### ISSUE TITLE
github desktop deleted al my projects !! 

### ISSUE THREAD

**Issue by heshamelmasry77** [desktop/desktop#3522]
I am writing this because i am so pissed from this app. Today i was working on a project and then i tried to commit  my changes. I found that github desktop added all my projects in my github main folder in the commit. I was like how !!  these other projects not in my current project i am working on.  I discarded the changes then i found it deleted all my apps !!

**Comment by j-f1** [comment]
I’m sorry you had a bad experience! Do these tips help?

1. When you discard changes in GitHub Desktop, they go to your Trash (macOS) or Recycle Bin (Windows)
2. What probably happened is that you tried to add your main GitHub folder to GitHub Desktop instead of adding each project separately. Once you have your projects back, you can select them all, then drag-and-drop them onto the app to add them all at once.

If you encounter any difficulties, please comment here and we’ll do our best to help!

**Comment by iAmWillShepherd** [comment]
@j-f1 is correct here. All of your content is in the recycle bin, so you are still able to restore it assuming you have not emptied your trash.

**Comment by heshamelmasry77** [comment]
Thank you so much guys. I do got my projects back but its kind of weird what happened.
When you download github desktop. It create for a folder call Github and then you can select what every project you want form your github and you use the github desktop. Inside the Github folder you will have all your projects.
What happened with me exactly is like that.

I created a react project. worked on it . then i come to commit what i did. I check on githuh desktop app i see that my other projects is being seen that they are in my current project folder. I selected the folders i want and committed and the i selected the other projects and i discarded BECAUSE i know these other folders not in my current folder. I found hop everything deleted !.
this exactly what happened. Just some weird behavior.

**Comment by iAmWillShepherd** [comment]
Glad you were able to recover your other projects @heshamelmasry77 👍

**Comment by heshamelmasry77** [comment]
Thank you so much man.
