### ISSUE TITLE
Add support for force push

### ISSUE THREAD

**Issue by Yohanna** [desktop/desktop#3580]
### Description

I'd like to request adding a new feature to support force pushing to a repo

### Version

**GitHub Desktop version:** `1.0.10`

**OS version:** `Microsoft Windows [Version 10.0.15063]`

**Expected behavior:** GH Desktop should ask me if it should do a force push or add a dedicated button for *pushing* & *pulling*, the same way SourceTree does.

**Actual behavior:** I get an error:

![image](https://user-images.githubusercontent.com/6926228/33900307-fb05fa5a-df3b-11e7-86f1-faa261b7c472.png)

**Comment by joshaber** [comment]
Thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I'm going to add the `future-proposal` label to this issue and close it out, so that we don't get overwhelmed with our backlog! We'll revisit these as part of our next planning session.

**Comment by drewbaker** [comment]
Really needed this tonight!

**Comment by ArthurSilveira** [comment]
Yeah... This would be nice right about now. Dealbreaker for using GitHub desktop.

**Comment by TimeBomb** [comment]
Could really use this.

**Comment by ParrotCreative** [comment]
+1

**Comment by stefanoric** [comment]
+1

**Comment by anuptripathi4u** [comment]
+1

**Comment by j-f1** [comment]
Please don’t comment “+1” to show your support. Instead, please use the 👍 reaction on the first post.

**Comment by oskardudycz** [comment]
👍

**Comment by billygriffin** [comment]
Hi folks! I wanted to follow up on this and understand a bit more about *when* and *why* you're needing this functionality. I'd love to gather a bit more in terms of what workflows this is enabling. In other words, when are you wanting to force push and therefore overwrite what's on the remote? And is this typically when working on your own or as part of an organization? Force pushing can obviously create some tricky situations for teams working together, so we just want to understand a bit more about when and how you're looking to do it.

**Comment by TimeBomb** [comment]
One of our most common use cases:

1) Person A creates PR with appropriate commits
2) Person B reviews PR, requests changes
3) Person A makes changes, pushes as new commits - making it easy to review the code that has changed since they last reviewed it
4) Person B approves PR
5) Person A **squashes commits and force pushes** before merging PR in

**Comment by mido1966** [comment]
Dankeschön für alle lautet  von ganzem Herzen zum euer Helfa noch mal  Dankeschön

‏‫من الـ iPhone الخاص بي‬

‫في 24‏/01‏/2019 الساعة 11:41 م، كتب/كتبت ‏Jason ‏<notifications@github.com<mailto:notifications@github.com>>:‬


One of our most common use cases:

  1.  Person A creates PR with appropriate commits
  2.  Person B reviews PR, requests changes
  3.  Person A makes changes, pushes as new commits - making it easy to review the code that has changed since they last reviewed it
  4.  Person B approves PR
  5.  Person A squashes commits and force pushes before merging PR in

**Comment by billygriffin** [comment]
Hi @TimeBomb, thank you for the description! I'm curious why the squash and merge can't just happen when the PR gets merged, instead of needing to squash locally and force push?

<img width="405" alt="screen shot 2019-01-29 at 12 48 24 pm" src="https://user-images.githubusercontent.com/5091167/51939426-46ce5400-23c4-11e9-8cdb-a8f783b663ed.png">

**Comment by TimeBomb** [comment]
Hey @billygriffin, good point. My team is aware of `Squash and merge` but hasn't used it because we assumed, per the `squash` terminology, that the feature combined the commit messages of all commits in the pull request.

In our case, only the original commit contained the title and description we wanted to merge.
In the scenario I mentioned, the original commit would contain information about the code changes. Subsequent commits contain information about changes to the PR, but that information was usually only for the pull request reviewer to more easily review subsequent changes to the PR.

For example, the original commit may have been `Update X to implement support for Y` with a commit description going into the reasoning behind this change. Subsequent commits may have been `Fix bug Z in the PR` or `Leverage A instead of B`, i.e. commits describing the changes made to the original commit based off of pull request feedback.

**Comment by TimeBomb** [comment]
An unrelated, alternative use case to why one may force push:
1) I create a PR with 1 commit
2) I realise shortly after-the-fact that either code in the the commit or the commit title/description itself had a typo or bug.
3) I fix that issue, amend the commit with the minor code change I just made, and force push it to the branch.
Don't want to add unnecessary commits, especially if someone hasn't started reviewing it.

**Comment by j-f1** [comment]
@TimeBomb When you opt to squash and merge, GitHub gives you a UI to edit the message for the squashed commit:

![screenshot 2019-01-30 at 12 23 35](https://user-images.githubusercontent.com/25517624/51999939-e30e5e80-2489-11e9-917f-d702357231fc.png)

**Comment by ArthurSilveira** [comment]
@billygriffin for me it happens when I'm working on a feature branch by myself and someone else merges something to master before I'm done.

I then rebase my branch against master

`git rebase master`
`git push --force-with-lease`

**Comment by billygriffin** [comment]
Thanks folks, really appreciate your input on this. Because this issue is a catch-all of things that people could use force pushing for and we already have a few of the specific use cases captured in other issues (#5953 and #1644 as examples), I'm going to remove `future proposal` here. We want to ensure we're looking at any new feature in the context of what value it's enabling for people, and I think we need to be even more rigorous when dealing with potentially destructive actions. We'll be rolling this out slowly as part of our work on rebasing and we'll evaluate from there. Thanks again!

**Comment by C0braD3v** [comment]
+1... This feature would definitely be helpful!

**Comment by UInt2048** [comment]
Interestingly, in the Advanced preferences of GitHub Desktop (at least on Mac) there is this interesting checkbox:
<img width="600" alt="Sin título" src="https://user-images.githubusercontent.com/46784000/89301809-b19ec200-d62f-11ea-902b-1d4fd1663853.png">

**Comment by noobling** [comment]
> Hi folks! I wanted to follow up on this and understand a bit more about _when_ and _why_ you're needing this functionality. I'd love to gather a bit more in terms of what workflows this is enabling. In other words, when are you wanting to force push and therefore overwrite what's on the remote? And is this typically when working on your own or as part of an organization? Force pushing can obviously create some tricky situations for teams working together, so we just want to understand a bit more about when and how you're looking to do it.

A lot of times you work on your own branch which allows you to do whatever you want like force pushing. e.g. you have a bunch of `wip` commits which you want to remove from your git history.

squash rebase is another common one because when you get conflicts you want to just solve it all at once not one by one on each commit. 

In most repos pushing/force pushing shouldn't be a concern because shared branches are locked down and any code going in needs to meet the org's dev practices before a merge.

So please review this feature as many devs use this in their daily work...

**Comment by UInt2048** [comment]
In my opinion, the question you're asking seems like a developer asking in the early stages of GH Desktop: "Why would you want to push a commit?"

People would have all different reasons, but everyone would agree it should be added.

**Comment by CyrusNajmabadi** [comment]
@joshaber Can this be reopened.  There's clearly a lot of interest here:

![image](https://user-images.githubusercontent.com/4564579/104404497-a66d8d80-550f-11eb-9a64-22683558e436.png)

For me, force pushign is a natural part of my git workflow.  I'll commonly make a commit, then amend it numerous times until it has the right shape for me.  However, all throughout that i'm still pushing it as i want CI coverage to ensure good info at every step of the way.

Thanks!

**Comment by shelbykauth** [comment]
Practical Real-world Use Case
---

We have a 'sandbox' branch.  When we push to Sandbox, Jenkins takes it and rebuilds it no matter if it was fast-forward or a force push with different history, etc.  There will be times that Sandbox doesn't make it to Dev.  More often than not, in fact.  So it doesn't make sense to require original bad commits plus revert commits, with zero certainty that there isn't a one-line change that makes or breaks our code, last modified 3 months ago.

I force push to sandbox so frequently, I have an alias for it `alias.deploysandbox=push -f origin HEAD:sandbox`

We recently got a developer who cannot use CLI because of login reasons (which we are trying to resolve).  He solely uses GitHub Desktop.  Any time he wants to show the business folks what he's working on (because they don't have the ability to run a deployment), he has to come to me or our other developers and say "Can you push <x branch> to sandbox for me?" And we have stop what we're doing, stash and whatnot, switch to his branch and push to sandbox for him.  It's frustrating for all involved.  It would be so much easier if he could just go "Push to Branch -> select 'sandbox' -> check the box for 'force' -> click 'Push'" and be done with it.

---

In addition to that, when I'm working on a branch by myself and want to amend my git history so that my Pull Request has 4 good commits instead of the 40 bad commits that occurred while I was working on it, without deleting the whole branch and starting over, or choosing a different branch name, darn tooting I want to force push.

_Though... admittedly... this is why I use the CLI in the first place.  It's far more powerful and looking up a command is easier than looking up how to do something in the GUI and then being disappointed that I can't do the thing I want to do.  Stuff like this makes it clear that GUI is training wheels for new users, CLI is for power users.  That's the reputation that GUIs have. 
 And it's not entirely without merit._

**Comment by UInt2048** [comment]
@billygriffin Please reconsider this.

**Comment by dmolesUC** [comment]
The most common use case is rebasing a feature branch onto an updated main. If you initiate the rebase from GitHub Desktop, it will force-push it for you at the end of the process, but if you do it any other way, GitHub Desktop is stuck. In fact it'll offer to rebase your rebased branch on top of the origin feature branch, which is pretty much the opposite of what you want (and heaven help the GUI user who tries to sort out the commit history).

It's all very well to say "force push considered harmful", but that should be a question for the repository owner and project policy, not a limitation baked into the client-side tooling.

**Comment by UpUpnAwaaaay** [comment]
Thanks for replying to me.  I'm new to this and what you said is still very confusing lol but I'm going to keep working on it   thanks. And other tips or info is greatly appreciate or if there is someone I can add to my repository. Thanks again

⁣Get TypeApp for Android ​

**Comment by Parthasarathy-s** [comment]
After spending some time found this in Mac Github Desktop, (not sure about windows)
Switch to history, tab. 

<img width="426" alt="image" src="https://user-images.githubusercontent.com/19490960/160461350-47759896-5dc5-4286-a050-23afdc3db648.png">

Then click and drag one commit over the other. Squash commit popup will come, choose accordingly.

<img width="400" alt="image" src="https://user-images.githubusercontent.com/19490960/160462212-b9b2fd47-67d7-4796-8ea5-6dbe482536b0.png">

Now you will be able to see force push

<img width="521" alt="image" src="https://user-images.githubusercontent.com/19490960/160461766-5705dd31-4e7c-4cd7-b178-dc600155d43d.png">

**Comment by astubbs** [comment]
The force push detection is not written well. Modifications outside of GitHub desktop can require force pushing, which GH desktop doesn't detect. Just give us an advanced option or whatever to force push. It's a core part of git workflow.

**Comment by steveward** [comment]
@astubbs see https://github.com/desktop/desktop/pull/15521 for work that is being done on this.
