### ISSUE TITLE
exports._errnoException Error at Commit

### ISSUE THREAD

**Issue by mjklopfer** [desktop/desktop#3593]
I experience a crash and receive the following message at program restart when trying to commit.  Restarted PC.
Error: write EOF
    at exports._errnoException (util.js:1050:11)
    at WriteWrap.afterWrite (net.js:813:14)

Version: 1.0.10
OS: Windows 10.0.15063

### Description

[Description of the issue]

### Version

**GitHub Desktop version:** [version here]

**OS version:** [version here]

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by iAmWillShepherd** [comment]
Thanks for reaching out!

We require the template to be filled out with all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway 😀

**Comment by mjklopfer** [comment]
My apologies.  I shortened the path length and the commit worked.  Just wanted to post this if it was a known bug to crash without warning given.

**Comment by iAmWillShepherd** [comment]
Oh yes, Windows has a max path length limit. Check [this](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx#maxpath) out for more info.
