### ISSUE TITLE
Cannot use `esc` on an empty Pull Request

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#3597]
If there are no Pull Requests (on a published branch), and you try to close the list with `esc` key, the Pull Request tab is highlighted and the list is not closed as expected.

<img width="348" alt="screen shot 2017-12-13 at 12 08 47 pm" src="https://user-images.githubusercontent.com/14828183/33960236-ef833aa8-dffe-11e7-98c7-81d665fdafaf.png">

1.0.11-beta0, mac

**Comment by iAmWillShepherd** [comment]
It looks like this behavior is consistent with how the branches drop down. 

It looks like we are relying on the filter text input to capture the `esc` key, but since it's possible for the text input to not be in focus or to not even exists, pressing `esc` doesn't always work.

Is this intentional?

cc, @desktop/design

**Comment by iAmWillShepherd** [comment]
Bump for feedback.

**Comment by donokuda** [comment]
My gut says <kbd>esc</kbd> should close the panel.

**Comment by agisilaos** [comment]
Since #3972 is merged we should close this issue right? @iAmWillShepherd

**Comment by shiftkey** [comment]
@agisilaos nice spot!
