### ISSUE TITLE
Nazwa pliku: GitHubDesktopSetup.exe Pełna ścieżka: c:\Users\Marcin\Downloads\GitHubDesktopSetup.exe  ____________________________  ____________________________   Deweloperzy  GitHub, Inc.  Wersja  1.0.11.0  Zidentyfikowano  18.12.2017 na 12:54:57  Ostatnio używany  Niedostępne  Element grupy Autostart  Nie   ____________________________   Bardzo mało użytkowników Mniej niż 5 użytkowników Norton Community używało tego pliku.  Bardzo nowy Ten plik został wydany mniej niż 1  tydzień temu.  Dobry Produkt Norton nadał temu plikowi ocenę Dobry.   ____________________________   Plik źródłowy: githubdesktopsetup.exe  ____________________________   Podpis cyfrowy pliku – SHA: 2814bb326398fb7fef193416dea26f2aada5496bed80eaed75fdabc409a74d69 Podpis cyfrowy pliku – MD5: ffa0fe388c0e416b059582cee425fdd3

### ISSUE THREAD

**Issue by szumi1** [desktop/desktop#3626]
### Description

[Description of the issue]

### Version

**GitHub Desktop version:** [version here]

**OS version:** [version here]

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by j-f1** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
