### ISSUE TITLE
Pushing doesn't work for local repos with commit history

### ISSUE THREAD

**Issue by ToontownLover** [desktop/desktop#3640]
Description
After adding an local repository, and changing the remote in the repository settings to connect to an different repository, the sync button doesn't let you push the commit history to the new remote.

Version
GitHub Desktop version: 1.0.11

OS version: Windows 10 Build 16299.125

Steps to Reproduce

1. Make New Repo on Github
2. Add Local Repo in Github's Desktop client
3. Go Into Repo settings for Local Repo
4. Copy and Paste the remote for New Repo in the remote box for Local Repo
5. Close out the Window
6. Click the Sync Button for Pushing.
7. Sync Button does nothing

Expected behavior: [What you expected to happen]

Commit history from local repo, to be pushed to new repo

Actual behavior: [What actually happened]

Sync Button did nothing

Reproduces how often: [What percentage of the time does it reproduce?]
100%

**Comment by tierninho** [comment]
@ToontownLover please fill out the missing details in the template so we can better diagnose your issue. Thank you.



### Description

[Description of the issue]

### Version



**GitHub Desktop version:** [version here]



**OS version:** [version here]

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]



**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Logs



#### Additional Information

**Comment by chantalcoolsma** [comment]
Seeing the same since this afternoon. Logs attached.

[2017-12-19.desktop.production.log](https://github.com/desktop/desktop/files/1572974/2017-12-19.desktop.production.log)

Something to do with public key? Pushed several commits today, suddenly it started showing this message:

![schermafbeelding 2017-12-19 om 20 25 39](https://user-images.githubusercontent.com/867632/34174899-ce367bfc-e4fa-11e7-806b-fa34ffe1f1a6.png)

**Comment by chantalcoolsma** [comment]
Deleted SSH key from Settings in GitHub.com and generated new key using https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/

Looks solved for me.

**Comment by jasminmurta70** [comment]
Thank you very much

2017-12-20 8:52 GMT+01:00 Chantal Coolsma <notifications@github.com>:

**Comment by shiftkey** [comment]
@chantalcoolsma I'm glad you were able to work around this.

@ToontownLover could you attach the log files at `%APPDATA%\GitHub Desktop\logs` - this will help with troubleshooting.

**Comment by ToontownLover** [comment]
[2017-12-19.desktop.production.log](https://github.com/desktop/desktop/files/1587613/2017-12-19.desktop.production.log)

**Comment by shiftkey** [comment]
I haven't had a chance to walk through these steps, but it looks the `push` is failing because the local history and remote history aren't able to be reconciled automatically:

```
error: failed to push some refs to 'https://github.com/ToontownLover/Project-Altis--December-2016.git'
hint: not have locally. This is usually caused by another repository pushing
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
(The error was parsed as 10: The repository has been updated since you last pulled. Try pulling before pushing.)
```

```
2017-12-19T04:28:47.933Z - error: [ui] `git -c credential.helper= push origin master:master --progress` exited with an unexpected code: 1.
To https://github.com/ToontownLover/Project-Altis--December-2016.git
 ! [rejected]            master -> master (fetch first)
error: failed to push some refs to 'https://github.com/ToontownLover/Project-Altis--December-2016.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

Is there a reason why you are manually changing the URL here, rather than using **File** | **Clone repository...* to initialize the repository? You can provide a URL in this dialog to clone a non-GitHub repository, if that's what you need to support...

**Comment by ToontownLover** [comment]
I downloaded the .zip version of the repo, and I had it stored on my external hard drive. I no longer have access to the repo that the commit history was connected to originally, this is why I manually changed the remote URL..

**Comment by shiftkey** [comment]
Looking at these repro steps:

> 1. Make New Repo on Github

I think something with initializing the new repository is creating an initial commit, which is why pushing is raising errors as it can't reconcile the two commit histories (we don't support force pushing). 

> 2. Add Local Repo in Github's Desktop client

This sounds like you have an existing repository with history (i.e. the `.git` folder at the root of the folder) and it points to a remote that no longer exists.

What I'd do in this case is remove the reference to this remote from the command line.

Open up a shell to your local repository you want to publish to GitHub and run this command:

```
$ git remote -vv
```

You should have one remote here, probably named `origin`. Let's remove this remote:

```
$ git remote remove origin
```

Now, when you add this repository to Desktop you should see a Publish button across the top, rather than "Push/Pull/Fetch". This will handle the initializing of a new remote repository under your account as well as pushing any existing history, which sounds like what you're looking to do.

Let me know if you have any other questions or issues about this.

**Comment by ToontownLover** [comment]
command line fixed my issue, thanks for the help :)
