### ISSUE TITLE
每次克隆到百分之十五就不动了。

### ISSUE THREAD

**Issue by wind-soft** [desktop/desktop#3694]
### Description

[Description of the issue]

### Version

**GitHub Desktop version:** [version here]

**OS version:** [version here]

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by shiftkey** [comment]
@wind-soft thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by wind-soft** [comment]
Description
每次克隆到百分之十五就不动了。
Version
GitHub Desktop version: 1.0.11
OS version: Windows 10 10.0.16299.125
Steps to Reproduce
1.打开https://github.com/mrdoob/three.js，点击clone，open in desktop
2.克隆到15%就卡住了。
Expected behavior: 完整将整个项目克隆到本地。
Actual behavior: 每次克隆到15%就卡住，无法继续克隆了。
Reproduces how often: 100%
Additional Information
无论是下载zip还是克隆到本地，都无法正常获取整个项目。
希望至少为zip下载支持断点续传，否则中国区用户很堪忧。
