### ISSUE TITLE
I am new for github,I have problem in using the github for windows when clone and publish

### ISSUE THREAD

**Issue by JilinGao** [desktop/desktop#3702]
### Description

[Description of the issue]
I am new for github,I have problem in using the github for windows when clone and publish.
![default](https://user-images.githubusercontent.com/22215292/34454714-0f57369e-edac-11e7-8009-fdc905171e81.png)

![default](https://user-images.githubusercontent.com/22215292/34454728-7a657fa4-edac-11e7-8894-04c2550316b4.png)

### Version

**GitHub Desktop version:** version1.0.11

**OS version:** [version here]
Microsoft Windows [▒汾 6.3.9600]
(c) 2013 Microsoft Corporation▒▒▒▒▒▒▒▒▒▒Ȩ▒▒▒▒
I don't know why there something unvisible ,My computer Operating System is windows 8.1

### Steps to Reproduce
for example clone a repository from github.com , from URL is the same error!
1. [First step]
![default](https://user-images.githubusercontent.com/22215292/34454765-45ae2db4-edad-11e7-895a-93757a49e682.png)

1. [Second step]
![default](https://user-images.githubusercontent.com/22215292/34454777-7669e448-edad-11e7-8af6-e58597e28bb0.png)

1. [and so on]

**Expected behavior:** [What you expected to happen]
clone and publish successful.
**Actual behavior:** [What actually happened]
unkown error!

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by shiftkey** [comment]
@JilinGao thanks for the report!

The version of Git embedded in Desktop uses the Windows SChannel APIs for validating certificates as part of the HTTPS handshake. We've had various reports of this failing due to other tools being installed alongside, like anti-virus programs, or being behind some proxy servers. 

As a workaround, you can revert to the classic OpenSSL behaviour by opening the repository in a shell and running these two commands. 

```
$ git config --global http.sslBackend "openssl"
$ git config --global http.sslCAInfo [path to .pem file]
```

The PEM file is just a bundle of public certificates to validate - [the PEM file](https://curl.haxx.se/docs/caextract.html) distributed by the cURL team should do the trick.

**Comment by shiftkey** [comment]
We're working on explaining this error better in #3406. Please follow along with that issue.
