### ISSUE TITLE
Add option during install to add git to path in Windows

### ISSUE THREAD

**Issue by gmcclins** [desktop/desktop#3708]
### Description

Enhancement request. Add an option during install on Windows to add git provided by desktop to path. This will allow users to also use git from the command line. Also, it will satisfy Visual Basic Codes git check and will allow version control using git.exe provided by desktop from Visual Basic Code.

### Current Setup

**GitHub Desktop version:** 1.0.11

**OS:** Windows 10 Pro

**OS version:** Microsoft Windows [Version 10.0.16299.125]

### Steps to Reproduce

1. Add `C:\Users\user\AppData\Local\GitHubDesktop\app-1.0.11\resources\app\git\cmd` to path

![image](https://user-images.githubusercontent.com/1461924/34466655-3c33bd42-eea9-11e7-97ad-00aaa1491f85.png)

2. You can now use git provided by desktop via powershell, cmd and even in Visual Studio Code

![image](https://user-images.githubusercontent.com/1461924/34466663-a4bcd3f8-eea9-11e7-98c8-6cbc819e1ae7.png)

![image](https://user-images.githubusercontent.com/1461924/34466695-333a4a92-eeab-11e7-8160-d72116645290.png)

#### Additional Information

I'm sure this wouldn't be something everyone wants as you can always install the actual git for windows, but that comes with some config choices. I know I would rather just install desktop to get git functionality in Windows. Since this is something not everyone would want, I'm thinking the best way to implement this would be via adding a checkbox option during install. Something along lines of add git to path.

Not sure this would really make sense on Linux or macOs. Thoughts?

**Comment by j-f1** [comment]
The version of git we bundle has many features removed so we can have a smaller download size. This makes it a poor candidate for use outside of Desktop, since we might remove features of git we don’t use at any time without warning.

**Comment by shiftkey** [comment]
@gmcclins thanks for the suggestion. We made a conscious decision back in the early days of GitHub for Windows to not tamper with your existing environment unless absolutely necessary, and this is one of those cases.

While it seems convenient to do this, it actually introduces a whole lot of problems:

 - the path to our embedded version of Git is tied to the specific version of Desktop - whenever an update is applied, this path will change, leading to potential breakage of anything that is hard-coded to that path (like environment variables)
 - the embedded version of Git we use in Desktop doesn't support terminal features like colorization, pagination and the UNIX toolchain that developers are familiar with, because we want to save space and we don't need them in the app
 - Desktop manages its own credentials using the `GIT_ASKPASS` environment variable (details [here](https://git-scm.com/docs/gitcredentials)), and simply adding Git to your `PATH` won't get credentials working in your terminal or app
 - we discourage depending on our version of Git because it's never been officially supported, and how we embed Git is subject to change. An example of that is VSCode. Early on they took a dependency on the Git found in GitHub for Windows for convenience, and this worked okay until you also installed the Electron Desktop version (we support using these side-by-side) which had it's own CLI integration. This combination broke VSCode because they didn't manage the `PATH` environment variable correctly, and it would continually spawn the Desktop UI. I had to get them to remove this code in https://github.com/Microsoft/vscode/pull/35965

We recommend installing [Git for Windows](https://git-for-windows.github.io/) and ensuring you check the "add to your `PATH`" option in it's installer, as both Desktop and VSCode interop nicely with that.

**Comment by j-f1** [comment]
Would it be possible to / should I open an issue for printing out a warning if you attempt to use the integrated git outside of Desktop?

**Comment by shiftkey** [comment]
@j-f1 nah, I don't think the effort required to do this is worth it

**Comment by gmcclins** [comment]
Thank you for the review and taking the time to explain in detail.

**Comment by gliatrax** [comment]
Thank you.  This was helpful.  saved to re-read for later configurations as well.

**Comment by amjadtbssm** [comment]
I can manually add the path of the git.exe from bin folder and it is working in cmd.exe commands but not by default. There is an option to select the shell in the settings too but all is not working. Why put something that is not working??? Please update or remove the option...

**Comment by steveward** [comment]
@amjadtbssm we don't recommend adding the Git that ships with GitHub Desktop due to it being customized for the app. The shell option in the menu is explicitly to set the shell you want to open from within GitHub Desktop. I  hope that helps explain things.
