### ISSUE TITLE
Decrease the max line length limit

### ISSUE THREAD

**Issue by joshaber** [desktop/desktop#3740]
As per https://github.com/desktop/desktop/pull/3032#issuecomment-354265785, we can probably cut our max line length limit down quite a bit. It's currently at 500,000. We could try 100,000 or even 50k.

See https://github.com/desktop/desktop/blob/b0d5afb37c36116006bb44855c9e3e81d3f554d7/app/src/lib/git/diff.ts#L41-L45

**Comment by iAmWillShepherd** [comment]
I'd say 50k seems reasonable

**Comment by shiftkey** [comment]
![](https://user-images.githubusercontent.com/359239/34688195-b24455e4-f487-11e7-9fa4-63072b83ccb3.png)

**Comment by joshaber** [comment]
The comment that spurred this suggested even 10k, which might be reasonable. What diff is gonna be readable with 10k character lines?

**Comment by iAmWillShepherd** [comment]
I'm in favor of that too, you could even cut that 10k in half.

**Comment by JQuinnie** [comment]
Hi All, I would like to work on this, if still available.

**Comment by iAmWillShepherd** [comment]
@JQuinnie , sure you can take this issue. When you open your PR please include `Fixes #3740` at the beginning of the body.

Also, we thought that 5k might be a good limit to start with. To help you out, here are some of the scenarios I thought of testing through. Hope it helps!
1. New file with 1 line that contains at least 5k characters
2. Existing file with a new line added with at least 5K characters
3. Existing file changing an existing line so that it has at least 5k character

Additionally, the variable `MaxLineLength` is confusing, would you mind renaming to `MaxCharactersPerLine`?

**Comment by pandeer2** [comment]
the bug is hanged up ...

**Comment by iAmWillShepherd** [comment]
Hi @JQuinnie , it looks like you've gotten a little busy lately as there haven't been activity on this in the last month. Is this still something you're interesting in pursuing? Additionally, did we miss any outstanding or blocking questions?

If not, we thought we'd make this issue available to the community again.

**Comment by JQuinnie** [comment]
Hi @iAmWillShepherd , many apologies as you are right... I have been preoccupied with some personal tasks... I have not issues if you want to make this available to others. If no one picks it up at a later time, I take another go.

Thanks for your assistance!

**Comment by mrsimonfletcher** [comment]
@iAmWillShepherd I would be happy to pick this up for @JQuinnie I can probably take a look this week?

**Comment by iAmWillShepherd** [comment]
@mrsimonfletcher that sounds great! I'll go ahead and move this issue to _Taken_.
