### ISSUE TITLE
Upstream error doesn't allow user to pull

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#3766]
I ran across an existing error message guided me to "pull" despite the option being greyed out in the menu. I purposely created the same branch on Desktop and on GitHub.com and tried to "merge" them via Desktop.

<img width="927" alt="screen shot 2018-01-11 at 9 51 44 am" src="https://user-images.githubusercontent.com/14828183/34839308-0c06aa48-f6b6-11e7-9306-351397c3c24e.png">

When creating a local branch with one commit (left the branch unpublished), and also creating the same branch on GitHub.com with a separate PR, the result on Desktop was an error asking me to pull down the latest changes: "The repository has been updated since you last pulled. Try pulling before pushing." 

Note sure how relevant this use case is, but the error could be updated to reflect another action the user could take. 🤔

**Comment by shiftkey** [comment]
> "The repository has been updated since you last pulled. Try pulling before pushing."

Does the button then switch to saying "pull", or does it get stuck in this loop because the branch doesn't have tracking information set?

**Comment by tierninho** [comment]
Gets stuck in the loop. I switched back to master to pull down the dupe branch, then went on the try a publish the original branch.

**Comment by tierninho** [comment]
We are also displaying the an open PR for the same branch...

![screen shot 2018-01-12 at 11 08 54 am](https://user-images.githubusercontent.com/14828183/34891065-07d738ba-f789-11e7-9aa0-ae7660c7a234.png)

**Comment by nerdneha** [comment]
Adding in some notes after thinking but there is still pending reproduction + a potential fix

Steps to reproduce:
1. clone a repo from github
1. create a branch via desktop
1. make a change + commit
1. create a a branch on dotCom with the same name
1. go back to desktop
1. attempt to publish your branch
1. you should see an error dialogue
1. close dialogue and get stuck forever

this is particularly hard because we are pushing without having the correct remote reference
* before pulling we should set a tracking branch, if there is a remote (do in all cases)
* then we should merge the remote branch into ours
* if all goes well, then we can push again after and we should do this automatically

**Comment by tierninho** [comment]
Closing this as it has not come up enough times to be validated as a real problem.
