### ISSUE TITLE
Github Desktop's UI is horrible!

### ISSUE THREAD

**Issue by Joebeazelman** [desktop/desktop#3806]
Github's Desktop UI painful if you want to download a repository and start working on it. Expecting the user to read a long line of blue text on a light blue background to perform a very common operation is just plain bad UI design.  The text is lost among the busy screens of most developers. "Open this repository In Explorer" is confusing.  Is it a message or a link?  What is a hyperlink doing in a desktop application? What's wrong with a button?  Furthermore, it is unclear what will happen when the same operation is called "Show In Explorer" in the Repository Menu.  Up until I actually started writing this, I would normally click on the ComboBox and then look for the repo and then right click on it to open it in explorer.  I am surprised there isn't an option for opening it in Visual Studio IDE.

Speaking of the menubar, it's barely visible!  The gray text against a black background makes it practically disappear.  It doesn't help that it melts into the navigation section under it.  I remember trying to figure out how to move the Window around because the it looked like a frameless window.  

I understand the need to look cool, but not at the expense of busy developers time.  Why are you rewriting the rules of user interface design?

**Comment by ydogus** [comment]
Hi @Joebeazelman. I couldn't resist to reply. :) I think the look and feel is very good in general.
> a long line of blue text on a light blue background to perform a very common operation is just plain bad UI design. The text is lost among the busy screens of most developers.

Actually it is surrounded with dark gray text. So you should be easily locate and read it. Because the contrast is enough: You don't always need *full black / full white* contrast ratio.

> "Open this repository In Explorer" is confusing. Is it a message or a link? What is a hyperlink doing in a desktop application?

Actually speaking for UX, I'm glad it is a hyperlink. This way it gives you a simple message: **I'm going to direct you somewhere else**.

> I am surprised there isn't an option for opening it in Visual Studio IDE.

Yeah I'm dissapointed with that too. Actually this is why I was in this section. I was looking for some information about support on external editors.

> Speaking of the menubar, it's barely visible! The gray text against a black background makes it practically disappear.

Again the contrast is enough to easily read it. You know the menu is on top. So, as it's not the most important content, it doesn't really need to standout.

> I remember trying to figure out how to move the Window around because the it looked like a frameless window.

This is an application targeted for developers. And if there is a developer who can't find out how to drag this application as it was him who implemented the move feature, I have no comment :)

> Why are you rewriting the rules of user interface design?

They are not rewriting it. But if there is something broken, why not fix it? This is Github. They have a good opportunity to fix and spread the new rules out if needed (*Please don't get me wrong. I'm not telling you that all the things they've done were flawless*).

**Comment by j-f1** [comment]
>> I am surprised there isn't an option for opening it in Visual Studio IDE.
> 
> Yeah I'm dissapointed with that too. Actually this is why I was in this section. I was looking for some information about support on external editors.

Check out [our editor integration docs](https://github.com/desktop/desktop/blob/master/docs/technical/editor-integration.md) for some instructions on how to contribute a new external editor. We’d appreciate the help!

**Comment by Joebeazelman** [comment]
Let's see... Visual Studio IDE has been out for how many years now?  Oh wait... It has been out before Github desktop and Visual Studio Code.  And VS Code is younger than Github desktop.  Why does VS Code get the love?  Is it because it's cross platform?  It would suffice to just be able to open at least the solution and project files.

**Comment by iAmWillShepherd** [comment]
@joebeazelman, you you right. We didn't include visual studio because it is not open source. Furthermore, at the time the decision was made, visual studio had no way to open a folder from the command line. This is something we have no control over.

**Comment by Joebeazelman** [comment]
@ydogus 

I remember not understanding what older people meant when they complained the text was too small or there wasn't enough contrast, but I at least tried to understand.  As you get older, your vision changes.  I had better than 20/20 vision for most of my life and today I need bifocals because I've become far-sighted.  It all took a sudden downturn two years ago and I am still getting used to it.

If you think all this doesn't matter because you have a nicer monitor or better vision, I challenge you to drive at normal speed on roads where all the signs have been replaced with plain text on a low contrast background. There is a reason UIs use icons because your brain processes them faster. Github desktop uses cutesy graphics everywhere but where it counts.

As for moving the window, the dimensions, font size, etc. made it appear as a chromeless or frameless window.  The demarcation between the menubar and the rest of the Window is barely visible. Combine this with the low contrast menu items, it becomes easy to miss where the window handles are.  VS IDE doesn't have this issue and I use the dark theme as my default. 

Your attitude demonstrates the common disregard for other people's experiences in the tech world.  Just because you don't have a problem, doesn't mean there isn't a problem. Dismissing the user's complaints as nonexistent or inferring they are inept, shows a blinding level of hubris.

**Comment by NiklasBr** [comment]
> Speaking of the menubar, it's barely visible! The gray text against a black background makes it practically disappear. […] I remember not understanding what older people meant when they complained the text was too small or there wasn't enough contrast, but I at least tried to understand

This, I agree with. The contrast ratio of 4.5:1 just barely passes the minimum recommendation, I _really_ wish it was better.

There are a set of low-contrast issues I have not bothered to report (though I did bother to report #2586). Also there is no support for macOS's [Increased Contrast mode](https://support.apple.com/kb/PH25807?locale=en_GB "macOS Sierra: Display pane of Accessibility System Preferences"). 

I believe this might be an artefact of using Electron rather than sticking to the previous native app. While Electron absolutely brings convenience and stuff it also means no accessibility, no spell checking (#1597) and a slew of other side effects.

**Comment by j-f1** [comment]
I was always under the impression that GitHub Desktop was screen reader-accessible (at least on Macs), but I just checked, and that is **very** incorrect:

<img width="1875" alt="screen shot 2018-01-17 at 06 03 57" src="https://user-images.githubusercontent.com/25517624/35039620-6a8c1342-fb4c-11e7-8124-5888cd0c98a2.png">
<sup>“This app is scrollable.” “What’s inside the scroll area?” ”IDK”</sup>

**Comment by NiklasBr** [comment]
That's some good news at least. However, I don't have any screen reader other than VoiceOver to try with. I do wish Electron supported it and not just external ones.

Anyway, there is more to accessibility than just screen reader support. My personal pet is contrast:

![2018-01-17 14 26 30](https://user-images.githubusercontent.com/279826/35045104-09f7522a-fb93-11e7-8567-891df166ce19.gif)

**Comment by shiftkey** [comment]
This issue seems to have gotten a bit out of hand, so I'll give some guidance about the next steps before wrapping this up:

 - If you have feedback about the UI, please open a new issue with screenshots and details so it's easy for us to discuss _why_ things are currently they way they are. #3543 and #3189 are greats example of this.

- Accessibility support is something we're aware of. #1289 was an example of the work that we did to test with the NVDA screenreader, but if there are other screen readers please open an issue with details so we're aware of what screen readers are being used and what their current support looks like.
