### ISSUE TITLE
Allow browsing branches without checking them out

### ISSUE THREAD

**Issue by meyer** [desktop/desktop#3820]
### Description

At the moment, clicking on a branch checks the branch out (unless you have local uncommitted changes). It’d be swell if there was an option to see the commits on other branches without checking them out.

This would most likely require a minor redesign of how branches are represented in the app.

### Version

**GitHub Desktop version:** 1.0.12

**OS version:** macOS 10.13.2

### Steps to Reproduce

Not a bug.

**Comment by shiftkey** [comment]
@meyer Thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md). We've also made a lot of decision in the application to work with local branches or checkout remote branches, so this assumptions requires a fair bit of thought about how we handle things.

I added the `future-proposal` label to this issue and closed it so that we won't get overwhelmed with our backlog! We will revisit this in our next planning session.

**Comment by billygriffin** [comment]
Hi @meyer, thanks for the suggestion! We've heard a fair amount about how branches are represented generally in the app, but haven't heard a ton from folks who need to see the actual commits on that branch without checking them out. We'll likely be looking at how branches are organized and visualized and what information is presented with them in upcoming months, and we'll keep this in the back of our minds, but we don't plan to support this request as presented. I'm going to remove the future proposal label to indicate that. Thanks so much again for your input!

**Comment by cdmihai** [comment]
I do this all the time. Very often I branch out from my current feature-branch to quickly explore some things, and when I do this I constantly need to be aware of different commits between the two branches. It would be awesome if I could explore the history of branches without checking out to them. Otherwise, it makes dealing with uncommitted changes a bit messy.

**Comment by meyer** [comment]
@cdmihai I ended up switching to [Fork](https://git-fork.com). It’s really well-built, does exactly what I need, and has a Windows version as well (!!!). And it’s free? And it’s a native application?! I really want to use GitHub Desktop, but it seems to be built for a more specific workflow that doesn’t work well with how I use git.

**Comment by garettridge** [comment]
+1 to this request.... I just merged in a branch with complicated conflicts, and while I'm manually resolving them in an editor it would be enormously helpful to review the source branch's history to see what motivated some of the edits I'm looking at to make a better merge decision.  But I can't view another branch's history without a checkout, and I am forbidden from checkout to another branch while there are merge conflicts.  

Having the ability to simply view a branch history without checking it out would solve the problem.  I don't know if there's something wrong with my use case (could be) but GitHub Desktop definitely doesn't seem to support it.
