### ISSUE TITLE
Caret always jumps to the end when inserting a completion

### ISSUE THREAD

**Issue by CarlRosell** [desktop/desktop#3834]
### Description
When inserting an emoji or mention in the commit message, the caret will always jump to the end of the text.

### Version

**GitHub Desktop version:** 8304e9c271a5e5ab4fda797304cd7bcca7158c87

**OS version:** macOS High Sierra

### Steps to Reproduce

1. Start writing a commit message
2. Go to the beginning of the message
3. Insert an emoji or mention

**Expected behavior:** The caret should stay right where the completion was inserted

**Actual behavior:** The caret jumps to the end of the message

**Reproduces how often:** 100%

**Comment by shiftkey** [comment]
This feels very similar to #3354 which we fixed by being more careful with props and `setState` changes - see https://github.com/desktop/desktop/pull/3411 for the fix.

I'll look at #3835 in the meantime but it'd be nice to see if reusing our fixed `TextBox` component can help to address this problem.

**Comment by shiftkey** [comment]
> I'll look at #3835 in the meantime but it'd be nice to see if reusing our fixed `TextBox` component can help to address this problem.

This requires some refactoring of the autocomplete providers, and probably is worth deferring if #3835 addresses the problem well enough.
