### ISSUE TITLE
Pops up over IntelliJ IDEA everytime I make a change

### ISSUE THREAD

**Issue by tzine** [desktop/desktop#3881]
Hi, I just have a minor issue that can be a bit annoying over time, was wondering if there is an easy fix I am missing, the application keeps popping over IntelliJ every time I make a change, even if the program is closed.

### Description

[Description of the issue]

### Version

**GitHub Desktop version:** [version here]

**OS version:** [version here]

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by shiftkey** [comment]
@tzine thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Can you please also share a screenshot of the problem to confirm what you're seeing?

Thanks for understanding and meeting us half way 😀
