### ISSUE TITLE
Co-authors field doesn’t support usernames with a trailing -

### ISSUE THREAD

**Issue by j-f1** [desktop/desktop#3897]
### Description

I can’t @mention users in the Co-Authors field if their name ends with a `-`, ex. `@ArtOfCode-`.

### Version

**GitHub Desktop version:** 1.0.13

**OS version:** 10.13.2 (17C88)

### Steps to Reproduce

1. Click the “Add Co-Authors” button
1. Enter `@ArtOfCode-`

**Expected behavior:** Adds `@ArtOfCode-` as a co-author

**Actual behavior:** The autocomplete box disappears and `@ArtOfCode-` is not a co-author

**Reproduces how often:** 💯%

**Comment by tierninho** [comment]
Good catch @j-f1 !

**Comment by niik** [comment]
Trying to understand the issue here. As far as I'm aware `ArtOfCode-` isn't a valid GitHub username since those can't end with a hyphen. So I imagine the issue is that the autocomplete popup goes away momentarily as you're typing a username that contains a hyphen (where that user is not part of the mentionable list)?

![hypen-username](https://user-images.githubusercontent.com/634063/35728696-b68c7828-080c-11e8-887a-fd471deb65c3.gif)

@j-f1 Would you say that's accurate?

**Comment by j-f1** [comment]
[@ArtOfCode-](https://github.com/ArtOfCode-) is definitely a valid user, but the issue you pointed out is also an issue.

**Comment by niik** [comment]
@j-f1 Welp. This will need some more investigation then. I copied the validation regex from dotcom and the sign-up page definitely seems to prohibit it.

![28884a7d-04c7-4c13-bf2d-b4a98be9def7](https://user-images.githubusercontent.com/634063/35732234-fc18fd92-0818-11e8-812d-e9a56c3cd589.jpeg)

Perhaps this is some legacy thing. I’ll look into it.

**Comment by tierninho** [comment]
So legacy users at GitHub (not sure of exact changeover date) are allowed to maintain their usernames ending with a hyphen, however new users are prohibited. 

@niik I can point to the user model in gh/gh if you want to take a peek.
