### ISSUE TITLE
Failure to login in to an GitHub enterprise account

### ISSUE THREAD

**Issue by jpgsantos** [desktop/desktop#3901]
### Description

Failure to login in to an GitHub enterprise account

### Version

**GitHub Desktop version:** 1.0.13

**OS version:** Microsoft Windows 16299.125

### Steps to Reproduce

1. Open "Options" (File > Options...) 
2. Under the "Accounts" tab, in the "Enterprise" section, click on "Sign in"
3. Paste server address (mine is "https://gits-14.sys.kth.se/")
4. The program tells the following message "Your GitHub Enterprise instance requires you to sign in with your browser"
5. Hit button continue with browser
6. make login on the browser side and get redirected to the GitHub desktop
7. Error message appears in the program "Unable to fetch authenticated user." (see attached image)

![image](https://user-images.githubusercontent.com/19508275/35638366-35509f56-06b7-11e8-8927-5940d381c1e5.png)

**Expected behavior:** Successful login

**Actual behavior:** Unsuccessful login

**Reproduces how often:** 100%

### Logs

[2018-01-31.desktop.production.log](https://github.com/desktop/desktop/files/1682717/2018-01-31.desktop.production.log)

#### Additional Information
The error is reproduced in at least 2 different computers, in various networks and using chrome Mozilla Firefox or edge as the browser.

**Comment by shiftkey** [comment]
@jpgsantos thanks for the report. It looks like we're not calling the right URL when trying to complete the OAuth flow:

```
2018-01-31T14:11:24.476Z - warn: [ui] requestOAuthToken: failed with endpoint https://gits-14.sys.kth.se/api/v3
Error: API error https://gits-15.sys.kth.se/login/oauth/access_token: Not Found (404)
    at Object.t.parsedResponse (C:\Users\Pedro\AppData\Local\GitHubDesktop\app-1.0.13\webpack:\app\src\lib\http.ts:157:34)
    at <anonymous>
```

We correctly identify that the API endpoint you used to sign in is at `https://gits-14.sys.kth.se/api/v3` but instead of calling `https://gits-14.sys.kth.se/api/v3/login/oauth/access_token` we call `https://gits-15.sys.kth.se/login/oauth/access_token` - which doesn't seem to exist. 

It looks like your Enterprise install is hosted on multiple frontends (we call this "clustering"), and you are being switched from one frontend to another during the OAuth flow, which fails for some reason.

I'm going to talk to our Enterprise support team about your scenario and try to understand more about how we (as an OAuth app) can authenticate correctly in this clustered scenario.

**Comment by shiftkey** [comment]
@jpgsantos I had a chat with our support team, and they're curious why you are using `https://gits-14.sys.kth.se/` to sign in, but the application ends up redirecting to `https://gits-15.sys.kth.se/`.

What happens if you use `https://gits-15.sys.kth.se/` to start the sign in flow? Does that still show the same error? If so, could you attach a fresh log file?

**Comment by jpgsantos** [comment]
I was just using the instructions from my institution as to how to login, it seems that your solution worked, using  https://gits-15.sys.kth.se/ instead of https://gits-14.sys.kth.se/ seems to solve the problem :D.
Note however that when trying to login in the website directly both with the https://gits-14.sys.kth.se/ as instructed or the https://gits-15.sys.kth.se/ seems to produced the same result of login me in and redirecting me correctly to https://gits-15.sys.kth.se/.

**Comment by shiftkey** [comment]
> Note however that when trying to login in the website directly both with the https://gits-14.sys.kth.se/ as instructed or the https://gits-15.sys.kth.se/ seems to produce the same result of login me in and redirecting me correctly to https://gits-15.sys.kth.se/.

Because of how Desktop signs in, it uses the first hostname that you enter to represent the account. While the browser is clever enough to handle redirects when doing the signin flow, Desktop doesn't get the new context - it only gets a callback without an indication that the server has "moved", so it tries to use the old hostname and :boom:.

Anyway, I'm glad it's resolved!

**Comment by accenture-ops-ai-mingzhu** [comment]
my problems haven't been solved. :(

**Comment by iAmWillShepherd** [comment]
@accenture-ops-ai-mingzhu please open a new issue detailing your problems and include the log file.

**Comment by julioca2** [comment]
Tofo bien
