### ISSUE TITLE
Git Gui: show ssh key don't show keytype id_ed25519.pub

### ISSUE THREAD

**Issue by goldfinger2** [desktop/desktop#3966]
### Description

Under ~/.ssh are only  one ssh key pair of type  ed25519  
( id_ed25519 and  id_ed25519.pub)
Git GUI don't show it
```
C:\Users\goldfinger2\.ssh>dir /b
agent.env
authorized_keys
id_ed25519
id_ed25519.pub
```

Win32-OpenSSH Beta currently supports only one key type (ed25519). 
 
[Win32-OpenSSH Issue](https://github.com/PowerShell/Win32-OpenSSH/issues/973)

[Installation and SSH Keytype](https://blogs.msdn.microsoft.com/powershell/2017/12/15/using-the-openssh-beta-in-windows-10-fall-creators-update-and-windows-server-1709/)

### Version

**GitHub Desktop version:** 2.16.1windows.2

**OS version:** Microsoft Windows [Version 10.0.16299.214]

### Steps to Reproduce

1. Open  Git Gui
1. Select Help
1. Show SSH Key :  No Keys found

**Expected behavior:**  Showing the ed25519 Key

**Actual behavior:** [What actually happened]

**Reproduces how often:**  100%

#### Additional Information

The problem is located in the find_ssh_key function which  is not searching after id_ed25519.pub
```
find_ssh_key {} {

	foreach name {~/.ssh/id_dsa.pub ~/.ssh/id_rsa.pub ~/.ssh/identity.pub} { 
...
```

**Comment by shiftkey** [comment]
@goldfinger2 thanks for the report!

This issue seems to be related to using [Git for Windows](https://gitforwindows.org/) and it's included GUI tool rather than GitHub Desktop, so I ask you to open an issue against [their issue tracker](https://github.com/git-for-windows/git/issues) so they can co-ordinate with the `Win32-OpenSSH` project to get this resolved.
