### ISSUE TITLE
[RBB] Compare to Branch

### ISSUE THREAD

**Issue by nerdneha** [desktop/desktop#3967]
This is part of #3956 and is for viewing changes as compared to any branch (ex: master).

**Changes:**
- [x] create a feature flag (ideally we don't change anything in the `HistorySideBar` component)
- [x] copy change (history -> compare, changes -> commit [may not be reflected in mocks, talk to @niik])
- [x] `branch selecting input` with new icon in input
- [x] list of branches on `branch selecting input` click (if it's empty) which can be "x"ed out
- [x] clicking on a branch shows commits ahead of the target branch
- [x] filtering

**User Flow to check functionality:**
- click on compare tab and see the commits you made on your branch + all commits from where you branched off of (existing behavior)
- click into the "compare a branch..." input and see a list of branches just like you would for switching branches if you clicked on the "current branch" menu item
- click on "master" and "master" becomes the text in the input and you see all the commits you have ahead of "master"
- press "x" in the branch input and see list of branches again
- select another branch, ex: "new-branch" and "new-branch" becomes the text in the input and you see all the commits you have ahead of "new-branch"
- press "x" in the branch input and see list of branches again
- start typing the name of an existent branch in "compare a branch..." input 
- see all branches filtered with same behavior as we have for the branches container
- select a new target branch, ex: "filtered-branch" and "filtered-branch" becomes the text in the input and you see all the commits you have ahead of "filtered-branch"
- press "x" in the branch input and see list of branches again
- see the compare tab return to default state

**Other pieces**:
- ahead/behind counts for each branch is in #3968 
- toggle for behind/ahead or any behind info in #3997

**Notes:**
@donokuda said this may change soon

**Before:** 
<img width="200" alt="screen shot 2018-02-08 at 2 11 27 am" src="https://user-images.githubusercontent.com/1834387/35967342-6fdd54d4-0c75-11e8-8e4b-f9691b8df380.png">

(branch list in app for reference)
![screen shot 2018-02-12 at 11 02 10 pm](https://user-images.githubusercontent.com/1834387/36137215-08cad424-1049-11e8-83bc-665645388f0f.png)

**After:**
(default view)
![default view](https://user-images.githubusercontent.com/1174461/36275617-6bf326fe-122f-11e8-87d1-ae42c98e36bc.png)

(select branch options)
![select branch options](https://user-images.githubusercontent.com/1174461/36275920-5e04563e-1230-11e8-820f-4093afe1bb81.png)

(selecting branch)
![selecting branch](https://user-images.githubusercontent.com/1174461/36275587-58c5b218-122f-11e8-8711-b1ab9822cfe0.png)

(filtering branch)
![filtering branch](https://user-images.githubusercontent.com/1174461/36275604-62ec48c4-122f-11e8-8d8e-2d2f40554d6f.png)

**Comment by nerdneha** [comment]
@donokuda @niik 
how are recent v other branches grouped in the "branch list"? are we just selecting the 3 most recent branches as "recent"?

**Comment by niik** [comment]
> does the branch list grouping of recent v other exactly match the behavior we have in the branches list for "current branch"?

It should, yeah.

**Comment by iAmWillShepherd** [comment]
Where does the list of branches come from? Remote, local, or both?

**Comment by shiftkey** [comment]
> Where can I get the icon asset for the branch textbox?

I know this one! It should be [this icon](https://octicons.github.com/icon/git-branch/) which can be rendered as an `Octicon` React component using the `OcticonSymbol.gitBranch` symbol.

**Comment by donokuda** [comment]
Because the branch-icon-inside-of-the-text-field is something new, I'm not necessarily sure what the implications are for implementing it.

I've did a [scrappy little prototype](https://codepen.io/donokuda/pen/ff25d1000c5ec86428894755e3782f93) of how I imagined it to behave; but in the potential situation where the cost of implementation is higher than the value of its worth, I think a potential compromise is to always have the icon showing:

![image](https://user-images.githubusercontent.com/1174461/36802546-4cc40738-1c59-11e8-846f-de4b0f442eb0.png)

**Comment by iAmWillShepherd** [comment]
> copy change (history -> compare, changes -> commit [may not be reflected in mocks, talk to @niik])

@nerdneha could you clarify ☝️ ?

**Comment by donokuda** [comment]
@iAmWillShepherd That's around changing the tab label from "Changes" to "Commit"

![image](https://user-images.githubusercontent.com/1174461/36816914-7301869e-1c83-11e8-8325-7705bb0e590e.png)

Sorry for the confusion there 😭

**Comment by iAmWillShepherd** [comment]
@desktop/design, any reason we made the decision to use a `TextBox` and `FilterList` instead of something like a select DOM element or a combo box? 

As I've been building this, it feels like the selection of the branch should happen from something closer in behavior to a select list. I believe we can style each option so that we see the ahead/behind info as well.

**Comment by donokuda** [comment]
> @desktop/design, any reason we made the decision to use a TextBox and FilterList instead of something like a select DOM element or a combo box?

I'd be interested in trying out the combo box approach.

The main reason why we went down the FilterList route is because it's an interaction that already exists in the app itself. My concern with going with just the `<select>` approach is that you can't necessarily search for a branch.

**Comment by donokuda** [comment]
In a past life, I've also explored a combo box in a mock (albeit without behind/ahead information.)

<img src="https://user-images.githubusercontent.com/1174461/37723581-fa13aa04-2ceb-11e8-87f9-633a62976727.png" width="250" />

**Comment by shiftkey** [comment]
> I'd be interested in trying out the combo box approach.
> 
> The main reason why we went down the FilterList route is because it's an interaction that already exists in the app itself.

Somewhat related: I've not used `downshift` yet, but it's been on my radar since i came across it 
months ago. 

To quote the elevator pitch:

> downshift 🏎 is the primitive you need to build simple, flexible, WAI-ARIA compliant React autocomplete/typeahead/dropdown/select/combobox/etc (AKA “item selection”) (p)react ⚛️ components. 

This seems like an ideal opportunity to explore the a combined "select with autocomplete" input element and see if it feels better than our current `FilterList` experience.

The examples in this post give a pretty good idea of what's possible with it, FWIW: https://blog.kentcdodds.com/introducing-downshift-for-react-b1de3fca0817
