### ISSUE TITLE
[RBB]  Ahead/Behind Branch Commit Counts

### ISSUE THREAD

**Issue by nerdneha** [desktop/desktop#3968]
This is part of #3956 and shows how many commits your branch has diverged from other branches

**User Flow to check functionality:**
- click on compare tab
- click into the "compare a branch..." input and see a list of branches
- for each branch, see the # of commits that branch is ahead and behind your current branch
- start typing the name of an existent branch in "compare a branch..." input 
- see the same #s for ahead/behind without recalculating

**Changes:**
- [x] # of commits your branch is `behind \/` that branch
- [x] # of commits your branch is `ahead ^` that branch

**Other pieces**:
- clicking on a branch to compare is in #3967 

**Before:** 
<img width="200" alt="screen shot 2018-02-08 at 2 11 27 am" src="https://user-images.githubusercontent.com/1834387/35967342-6fdd54d4-0c75-11e8-8e4b-f9691b8df380.png">

(branch list in app for reference)
![screen shot 2018-02-12 at 11 02 10 pm](https://user-images.githubusercontent.com/1834387/36137215-08cad424-1049-11e8-83bc-665645388f0f.png)

**After:**
![filtering branch](https://user-images.githubusercontent.com/1174461/35955426-627e29cc-0c33-11e8-8fcb-b0795527830f.png)

**Comment by nerdneha** [comment]
@niik do we have to worry about O(n) calculations here to calculate ahead/behind? would the app stall if there are >100 branches open?

**Comment by niik** [comment]
> @niik do we have to worry about O(n) calculations here to calculate ahead/behind? would the app stall if there are >100 branches open?

Yes, you're right that this can't be done in one operation, we need to shell out for each branch. Doing so is fairly quick though and I think as long as we do it on-demand as items are shown as opposed to running it for every branch regardless of whether it's visible in the list there shouldn't be any problem. We'll probably need to be careful so that we don't spin up as many git processes as there are visible branches in one go though, some task management is probably necessary.

We already calculate ahead/behind for all local branches (that has an upstream) after each background fetch in order to perform the background fast-forward.

**Comment by j-f1** [comment]
You could also cache the numbers in memory and only update them when a commit or fetch happens.

**Comment by jeremyzilar** [comment]
🤔So we have been using the date in the master list dropdown as a way to indicate which branches were most recently updated and/or worked on. The number of commits behind master is not really the same thing as, recency. Might be helpful to have both at some point.
