### ISSUE TITLE
macOS default folder is an iCloud folder

### ISSUE THREAD

**Issue by Superpencil** [desktop/desktop#3970]
On macOS the default folder for cloning repos is ~/Documents/GitHub
On new macOS installations, ~/Documents is an iCloud folder (same as Dropbox) and I'm wondering since it is not recommended to put Repo's inside of Dropbox, is it recommended to put them in iCloud Drive?

**Comment by iAmWillShepherd** [comment]
I believe that since it's not recommended to place git repositories inside of the directory DropBox watches the same holds for iCloud. 

One thing to note is that the clone path is _sticky_ (it's remembered across multiple clones).  So if you select a different clone path, that path will become your new default path. While this may not seem like a good solution, this only needs to be done once.

For a workaround that allows you to keep using your documents folder as a place for repositories, you can go into iCloud settings and uncheck the **Desktop and Documents Folders**.
