### ISSUE TITLE
Running `nom run build:dev` on Linux Mint 18.1 fails on ask-pass.js

### ISSUE THREAD

**Issue by zackeezy** [desktop/desktop#3985]
### Description

I run `git pull` to get the latest version of the repo, then run `npm install` and it works fine, but when I run `npm run build:dev` it fails and spews error messages in to the cl.  

### Version

**GitHub Desktop version:** 1.0.14-beta3 (I think, that's the latest version listed in the changelog)

**OS version:** linux Mint 18.1 

### Steps to Reproduce

1. Clone repo on Linux Mint
2. change directory to desktop
3. run npm install
4. run npm run build:dev

**Expected behavior:** it builds properly

**Actual behavior:** it fails

**Reproduces how often:** 100%

### Logs

https://pastebin.com/udfbbunX

#### Additional Information

I tried running `npm start` before actually building, but I don't think that matters.

**Comment by shiftkey** [comment]
@zackeezy we switched away from using NPM directly ages ago in favour of Yarn, primarily because of more robust support for optional dependencies. The details are in the setup documentation: https://github.com/desktop/desktop/blob/master/docs/contributing/setup.md#verification

When you've got `yarn` installed, `yarn && yarn build:dev` should succeed.

**Comment by iAmWillShepherd** [comment]
@zackeezy I'm going to close this issue out since using `yarn` is the correct way to build and run the application. If you have any additional problems with getting the project, built using `yarn` please drop a comment here. 🙇
