### ISSUE TITLE
Commit failed - exit code 128 received, with output: '*** Please tell me who you are.

### ISSUE THREAD

**Issue by nmirabal** [desktop/desktop#4059]
### Description

[Description of the issue]

### Version

**GitHub Desktop version:** [version here]

**OS version:** [version here]

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by nerdneha** [comment]
Thanks for reaching out!

We require the template to be filled out when submitting all issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway :grinning:

**Comment by steve3p0** [comment]
Description
Commit failed - exit code 128 received with output '*** Please tell me who you are.

Version
GitHub Desktop version: 1.1.1

OS version: Windows 10

Steps to Reproduce

When I try to commit

Expected behavior: 

I expect the files to be committed

Actual behavior: 

Commit failed - exit code 128 received, with output: '*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'steve@DESKTOP-IR063KN.(none)')'

Reproduces how often: 

100%

Logs
Additional Information

**Comment by Ewooral** [comment]
Thanks pal

**Comment by Ewooral** [comment]
Thanks Steve3p0. It worked.

**Comment by LasanthaRanga** [comment]
@steve3p0
 Thank you

**Comment by BibhaDhungel** [comment]
What do I do if I do not have "options" option under "File" menu

**Comment by shiftkey** [comment]
@BibhaDhungel are you on macOS?

**Comment by BibhaDhungel** [comment]
@shiftkey Yes

**Comment by shiftkey** [comment]
@BibhaDhungel from the top menu you want **GitHub Desktop** | **Preferences** to find these options:

<img width="310" src="https://user-images.githubusercontent.com/359239/53578458-2114a600-3b4e-11e9-8a73-0fbd866d2a1a.png">

**Comment by BibhaDhungel** [comment]
@shiftkey Thank you

**Comment by hYdos** [comment]
i signed out then in again and its still happening

**Comment by TaofeekS** [comment]
i follow ur steps and when i press save it did not save if i try commiting i still get same error

**Comment by ibenlim** [comment]
Thanks, It's OK...

**Comment by arpitran** [comment]
> @steve3p0 it seems like you don't have your Git configuration set for committing.
> 
> Try this:
> 
> * From the **File** menu, select **Options** to open the options dialog
> * Select the **Git** tab and fill in your name and email
> * Click **Save** to store those settings
> * Try committing again

This helped in solving my problem

**Comment by un-R3AL** [comment]
Thank you so much @shiftkey .

**Comment by carl0sma** [comment]
the question now is how did the settings get changed?

**Comment by sparethme** [comment]
@shiftkey Thank you kindly!

**Comment by iremaslandogan** [comment]
@shiftkey Thank you

**Comment by acordova200** [comment]
open PowerShell (admin)

and use theses commands

git config --global user.email " you@example.com "
git config --global user.name "Your Name"

**Comment by virginiayjd7** [comment]
Gracias

**Comment by wesleydesenvolvedor** [comment]
Commit failed - exit code 128 received, with output: '*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'Wesley@DESKTOP-SKBHBF1.(none)')

**Comment by steveward** [comment]
@wesleydesenvolvedor see [this comment](https://github.com/desktop/desktop/issues/4059#issuecomment-386841745) for how to set your name and email to prevent this error from occurring.

**Comment by Akhi1** [comment]
> @steve3p0 it seems like you don't have your Git configuration set for committing.
> 
> Try this:
> 
> * From the **File** menu, select **Options** to open the options dialog
> * Select the **Git** tab and fill in your name and email
> * Click **Save** to store those settings
> * Try committing again

This worked perfectly for me, thanks!

**Comment by wesleydesenvolvedor** [comment]
salavar git

**Comment by SwingingRoi** [comment]
add to  .git  config(open it as txt)
[user]
name =" xxx"
email = "xx"

**Comment by SametUCA** [comment]
thank you..

**Comment by teknic-dev** [comment]
Same issue here. I had to manually click Save on the Git section of the Options panel - even though this was already populated an previously saved. Why there's a separate Save button for this option is mysterious and confusing because the formatting of the Options panel looks like Save, should save all options (as one would reasonably expect). 

![image](https://user-images.githubusercontent.com/3734969/90535157-33b6dc80-e140-11ea-9897-f6b0b620f515.png)

**Comment by Nikkhesh** [comment]
thxx @steve3p0  it worked

**Comment by J-Vin** [comment]
Is this too long closed to comment?

**Comment by Akhi1** [comment]
not until it's closed ;)

**Comment by Akhi1** [comment]
not until comments are disabled ;)

**Comment by J-Vin** [comment]
I feel as if I am seeing my ghost. I am consistently seeing this error and always java something. Even had java boss (Nurse Matron, I think) stop me on the i-way. I have bug reports but not sure how any of the above comments are applied personally. How should I proceed? I may need inspector*d0*🤖* that knows how to just fix  🦾 for me 🤣

**Comment by 97joseph** [comment]
Thank you

**Comment by dev-white** [comment]
sometimes you just have to open the app in as an administrator

**Comment by HenriqueMart** [comment]
# Saved my life thank you @shiftkey

**Comment by Agrover112** [comment]
> add to .git config(open it as txt)
> [user]
> name =" xxx"
> email = "xx"

This works thank you
