### ISSUE TITLE
Focus switches from text areas when Shift+Alt were pressed for changing language

### ISSUE THREAD

**Issue by ShoshinNikita** [desktop/desktop#4062]
### Description

Focus switches from text area when Shift+Alt were pressed for changing language

### Version

**GitHub Desktop version:** 1.0.13

**OS version:** Windows 10 Version 1709

### Steps to Reproduce

1. Start to enter some text in Summary or Description form
1. Press Shift+Alt for changing language
1. Focus will switch

**Expected behavior:** Focus doesn't switch when Shift+Alt were pressed

**Actual behavior:** Focus switches when Shift+Alt were pressed

**Comment by iAmWillShepherd** [comment]
This behavior is caused because pressing the `alt` key allows you to interact with an application's menu using your keyboard. A workaround for your issue is to make sure you press and hold the `shift` key **first** followed by the `alt` key. This will behave in the manner that you expect.

### Pressing `shift` first then `alt`
![2018-02-21 12 09 36](https://user-images.githubusercontent.com/1715082/36497223-4daaa8b8-1700-11e8-8142-da8dd10ebdb5.gif)

### Not pressing `shift` first or  holding`shift` down pressing `alt` and pressing `alt` again (without ever releasing the `shift` key)
![2018-02-21 12 09 55](https://user-images.githubusercontent.com/1715082/36497305-8fbe7036-1700-11e8-9da8-647c37dde88e.gif)

**Comment by ShoshinNikita** [comment]
> Pressing `shift` first then `alt`

It doesn't work for me
But pressing `Alt` first then `Shift` works great. It looks like I should retrain)
Thank you.

**Comment by ogamespec** [comment]
Problem still exist if you press Alt+Shift quickly.
