### ISSUE TITLE
Download freeze

### ISSUE THREAD

**Issue by Naasty-Booy** [desktop/desktop#4079]
<!--
I try to download a Game where i joined as an Developer. Ist freezez ramdomly and the download stuck , after a whikle it ticks down to 0 .

**Comment by tierninho** [comment]
@Naasty-Booy  thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by Naasty-Booy** [comment]
Which Template ? 

Gesendet: Donnerstag, 22. Februar 2018 um 20:43 Uhr
Von: "Tiernan L" <notifications@github.com>
An: desktop/desktop <desktop@noreply.github.com>
Cc: Naasty-Booy <c-weisgerber@web.de>, Mention <mention@noreply.github.com>
Betreff: Re: [desktop/desktop] Download freeze (#4079)


@Naasty-Booy thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by tierninho** [comment]
@Naasty-Booy click the `new issue` button and you will see it. Thanks!
