### ISSUE TITLE
Can't clone repository (Authenication failed)

### ISSUE THREAD

**Issue by try0** [desktop/desktop#4091]
### Description

Authenication failed when clone repository.

When the progress bar becomes close to 100% (There is also might have completed), a dialog prompting authentication was displayed.

![2018-02-20 21 50 50](https://user-images.githubusercontent.com/17096601/36592483-4ae20d8a-18d9-11e8-8895-70227d84eb58.png)

When enter user name and password and click "Save and Retry" button, an error dialog was displayed.

![2018-02-20 21 51 22](https://user-images.githubusercontent.com/17096601/36592618-da80ec54-18d9-11e8-81d2-b7e165077a66.png)

### Version

**GitHub Desktop version:** 1.0.13

**OS version:** Microsoft Windows [Version 10.0.16299.248]

### Steps to Reproduce

Clone forked Xamarin.Forms repository.
It was also reproduced in MacOS.

**Expected behavior:** Clone Completion

**Actual behavior:** Authenication failed

**Reproduces how often:** 100%

### Logs

Looking at the log file, there seems to be a folder that can not be found.
If the folder can not be found, is it a specification that results in a fatal error?

[2018-02-23.desktop.production.log](https://github.com/desktop/desktop/files/1751458/2018-02-23.desktop.production.log)

**Comment by shiftkey** [comment]
@try0 thanks for the feedback!

The problem seems to be related to a submodule:

```
Submodule 'Xamarin.Forms.Build' (https://github.com/xamarin/Xamarin.Forms.Build) registered for path 'Xamarin.Forms.Build'
Cloning into 'C:/xamarin/Xamarin.Forms/Xamarin.Forms.Build'...
remote: Repository not found.
fatal: repository 'https://github.com/xamarin/Xamarin.Forms.Build/' not found
```

While your https://github.com/try0/Xamarin.Forms fork is public, the clone will fail because it's not able to clone that specific submodule. As a workaround, if you clone the repository outside Desktop you should be able to drag-and-drop it into Desktop and work with it there.

We're already tracking this limitation in #3242, so please follow along with that issue.

**Comment by try0** [comment]
@shiftkey 
Thanks for presenting a workaround.

I see!. 
I'm Sorry. I did not check issues well.
