### ISSUE TITLE
minimize to system tray

### ISSUE THREAD

**Issue by shellscriptz** [desktop/desktop#4098]
### Description

Want git desktop to have option for tray icon in windows. 

### Version

**GitHub Desktop version:** 1.0.13

**OS version:** windows 10

### Steps to Reproduce

1. github doesn't have a tray icon option

**Expected behavior:** github has option for a tray icon when minimized

**Actual behavior:** desktop does not have option for a tray icon when minimized

**Reproduces how often:** 100%

**Comment by shiftkey** [comment]
@shellscriptz can you tell me a bit more about why you'd like this to be supported? There's no real "background work" that Desktop currently does that might make it preferred to add it to the system tray...

**Comment by Kubrix** [comment]
@shiftkey, when GitHub Desktop is in system tray and not in the taskbar, the application is still running and not clogging the taskbar. It might be useful when you have a lot of open programs - in that case any extra taskbar icon (layout) leads to shrinking the current icons.

**Comment by shiftkey** [comment]
@Kubrix I think the work required to support this is significantly greater than the benefits, and the majority of (Windows) users won't encounter this. I'll see if @desktop/core has any additional feels on this.

**Comment by lee-dohm** [comment]
Isn't what used to be called the "system tray" now the "notifications area"? From the [Windows Design Guidelines](https://msdn.microsoft.com/en-us/library/windows/desktop/dn742495.aspx?f=255&MSPPError=-2147217396):

> The notification area was originally intended as a temporary source for notifications and status. Its efficiency and convenience has encouraged developers to give it other purposes, such as launching programs and executing commands. Unfortunately over time, these additions made the notification area too large and noisy, and confused its purpose with the other desktop access points.

> Don't abuse the notification area. Use it only as a source for notifications and status, and for features without desktop presence.

Since GitHub Desktop is intended to have a desktop presence, the guidelines would seem to say we shouldn't use the notification area this way.

**Comment by shiftkey** [comment]
@lee-dohm excellent points. I'll also make sure to emphasize that last bit:

> Use it only as a source for notifications and status, and for **features without desktop presence**.

The use case for this needs to be more than "declutter the taskbar".

**Comment by niik** [comment]
Seems like we're all in agreement that this is not something we want to add so I'm going to close this out.

There's also third-party solutions for forcing Windows applications to minimize to the tray (though I haven't tried any of them).

**Comment by Clubspeed-Mike** [comment]
> @Kubrix I think the work required to support this is significantly greater than the benefits, and the majority of (Windows) users won't encounter this. I'll see if @desktop/core has any additional feels on this.

I was directed her by Steve, so I will put my comments here. There is absolutely a real and productive way to implement this and I think you all being a bit dismissive because it doesn't fit your vision and/or you just don't want to bother dong it, as a developer I get that but not a good reason to brush it off either.

1. When you have 20-30 windows open to work on a massive enterprise project, yeah even one stupid program icon going to the systray, oh forgive the non-pc word, notification area, make a huge different and actually bring visibility to what the program is doing.

2. If you know your program, you know it does all kind of stuff in the background, you use it right? When you change code, it detects it. When you commit, and or get other feedback, it shows it, so if it was sitting in the systray (screw it I am going to call it what I want you can translate it to your happy place yourself) it would better display badges to show what is pending and needs attention than getting reduced to a measly icon or better ... in the taskbar where you don't see squat and have to fish for it.

3. All the actions taken on the main interface can be done through menu on the systray, EVERYTHING. Which from a UX perspective is alot better than having a program hogging the screen and taskbar when by your own words, it doesn't do anything important enough to be on the screen all the time but it is important for you to move between branches and so on. Again all of which can be far more efficiently handled from systray than it is now.

So plenty of reason, if the will is lacking then just admit that, don't insult the users by saying they are asking for something useless just because you don't use it that way.

**Comment by mislav** [comment]
@Clubspeed-Mike, your comment was removed as a violation of the [Desktop Code of Conduct](https://github.com/desktop/desktop/blob/development/CODE_OF_CONDUCT.md) as it was insulting or derogatory. You may consider this an official warning.

The specific clause being violated was:
> * Trolling, insulting/derogatory comments, and personal or political attacks

**Comment by Clubspeed-Mike** [comment]
@mislav wow, talk about weak. I was sent here to comment by Github, so I am trolling anyone. I was not offensive or derogatory to anyone and if you find being told that you are wrong insulting, then you are in the wrong field and should probably work on thicker skin, professional responsibility and less ego. But, whatever.

**Comment by razvan-flavius-panda** [comment]
@shiftkey @niik @lee-dohm when deciding whether to implement a feature or not do you care more about satisfying user needs (UX) and making their life easier OR do you follow conventions for no other reason then to follow the conventions?

@shiftkey
`I think the work required to support this is significantly greater than the benefits`
How difficult can it be to just get it to minimize to tray? This should not be difficult at all.

**Comment by billygriffin** [comment]
Hi @razvan-flavius-panda, thanks for your view. I would caution that the implication that the people you mentioned don't care about satisfying user needs is insulting as all of these people care deeply about our users and their needs. As I'm sure you can appreciate, working on products, especially in open source, involves having to make decisions that some portion of people will inevitably disagree with no matter what you decide. 

We respectfully disagree and have shared our reasoning. We do try to adhere to conventions unless there's a compelling reason to depart from them, and they can be helpful in making decisions. In this case, the convention seems like a reasonable guide, and we understand that some folks may disagree with that. Hope you continue to enjoy using Desktop in spite of this.

**Comment by razvan-flavius-panda** [comment]
@billygriffin `I would caution that the implication that the people you mentioned don't care about satisfying user needs` I did not say this, you did. Not going to defend a straw man, since that is not at all what I said.

Also I am not here to create drama, I just asked a question and mentioned that implementing this should not be hard. Actually I am sure that one of the developers could have implemented this feature in all the time wasted with these needless discussions about conventions instead of caring about user needs.

`all of these people care deeply about our users and their needs` Maybe they do. I do not know. I never said they do not, another strawman.

Ofc. people will disagree but using evidence and reason people should be able to come to a conclusion for our specific ticket - and it is not what was already decided.

`We respectfully disagree`

1. do not speak for others, you mean `I` not `We`
2. since you pulled a bunch of straw man fallacies and said that I insulted them which is not true I can say pretty clearly that you do not "respectfully disagree" quite the opposite.

`have shared our reasoning` you have not provided any evidence for why your reasoning is better than making this change yet spent lots of time of yours and of the OPs. In that time the functionality could have been easily implemented.

Conventions and rules are not meant to be followed to the letter always and this is one of those exceptions.

### This is my feedback. If you will continue to reply in an aggressive manner or by using straw man fallacies I will not reply anymore since it is not productive.

Also, just cause 3 people agreed does not mean they are right, they provided no evidence for why they chose respecting a rule instead of caring about the users needs.

Thinking that you should do something just cause majority decides is also fallacy - appeal to popularity.

**Comment by Triangle4** [comment]
> 
> 
> @shellscriptz can you tell me a bit more about why you'd like this to be supported? There's no real "background work" that Desktop currently does that might make it preferred to add it to the system tray...

So we dont have to relaunch it every time we want to use it.

**Comment by Triangle4** [comment]
> 
> 
> Hi @razvan-flavius-panda, thanks for your view. I would caution that the implication that the people you mentioned don't care about satisfying user needs is insulting as all of these people care deeply about our users and their needs. As I'm sure you can appreciate, working on products, especially in open source, involves having to make decisions that some portion of people will inevitably disagree with no matter what you decide.
> 
> We respectfully disagree and have shared our reasoning. We do try to adhere to conventions unless there's a compelling reason to depart from them, and they can be helpful in making decisions. In this case, the convention seems like a reasonable guide, and we understand that some folks may disagree with that. Hope you continue to enjoy using Desktop in spite of this.

You should listen to your community. They want a feature that causes you no harm to add and takes less than a couple hours of coding to integrate. It is a poorly design command structure that dismisses the wants of the community because the developer thinks they know better than its users, what the users want. 

I recommend revising your view and adding it, it is oddly ridiculous that I have to relaunch it every time I use it and cannot clear it from my desktop when it is downloading by minimizing to tray. 

Dont be like stack overflow, who thinks that their new innovation can be forced on a community. That is why they are failing to draw new users and why soon they will be as obsolete as myspace.

Failing to provide basic needs of a community, is what gives rise to competitors that stamp out the competition. We like git hub, please give us this simple, harmless, but preferential and useful feature. 
Thank you.

**Comment by Triangle4** [comment]
> 
> 
> @mislav wow, talk about weak. I was sent here to comment by Github, so I am trolling anyone. I was not offensive or derogatory to anyone and if you find being told that you are wrong insulting, then you are in the wrong field and should probably work on thicker skin, professional responsibility and less ego. But, whatever.

I have to agree with this. This is an industry filled with regular critique, and there is no room for hypocrisy in a world of science. 
Computer science is a science, and we are all a community working together, in one way or another, to better that community.
So when your community voices their concerns, disagrees with you, or conversely, offers a suggestion, it is wise to allow such things to strengthen you.

**Comment by Triangle4** [comment]
> 
> 
> @shellscriptz can you tell me a bit more about why you'd like this to be supported? There's no real "background work" that Desktop currently does that might make it preferred to add it to the system tray...

Correct, there is no background work being done. We are asking you to change that. 
The bluetooth icon on my pc does no background work. 
The wireless icon on my pc does no background work.
The network icon does no work.
The volume control icon does no background work.
The dropbox, onedrive, and discord icons show notifications. 

So why dont we do this, why dont you upgrade github desktop to show updates to comments and user interactions as notifications in a tray icon. 
When downloading a git, I can minimize it so that it is not active on my taskbar, and when it is finished it can show me a notification. 

It is very closed minded to be a world leading developer and not see the use and benefit of a tray icon. Nearly unbelievable.

**Comment by Triangle4** [comment]
> 
> 
> Isn't what used to be called the "system tray" now the "notifications area"? From the [Windows Design Guidelines](https://msdn.microsoft.com/en-us/library/windows/desktop/dn742495.aspx?f=255&MSPPError=-2147217396):
> 
> > The notification area was originally intended as a temporary source for notifications and status. Its efficiency and convenience has encouraged developers to give it other purposes, such as launching programs and executing commands. Unfortunately over time, these additions made the notification area too large and noisy, and confused its purpose with the other desktop access points.
> 
> > Don't abuse the notification area. Use it only as a source for notifications and status, and for features without desktop presence.
> 
> Since GitHub Desktop is intended to have a desktop presence, the guidelines would seem to say we shouldn't use the notification area this way.

Arbitrarily describing something as a "Desktop"Application and thus deeming it unworthy of a tray icon is like saying a tangerine isnt an orange and therefore should not have the color orange. 

All applications that run on a desktop pc are a desktop application, and thus by such reasoning no application should have a tray icon. Conversely, if no icon should have a tray icon, yet almost every productivity application made for windows has one, it would stand to reason that github desktop is intentionally deviating from what others do to try and be different. 

Being different is acceptable, when applied to the correct situations, however... Much like trying to type your name on a first generation ipod, reinventing the wheel(no pun intended) is only useful when your new invention helps your apparatus to fly. 

By removing the wheel and replacing it with legs, you decrease the productivity of that aparatus, making it less likely for other to support your choices and business direction. 

I have a corporation with 27 employees and we do not use GitHub yet. 

At this time, I will officially refuse to change that until you decide to add this trivial feature to the application. There is no sense paying anything for a partially developed application. And omitting a tray icon, is the definition of partially developed windows application in the eyes of the common user.

Cheers, again.

**Comment by Triangle4** [comment]
On a personal level, I want to congratulate you for your exceptional website design platform. I use GitHub personally all the time. 
As an avid user, I feel you need to take this matter much more seriously.

Thank you for your time. 
CEO of Triangle4 Studios Inc. 
Vancouver Canada.

**Comment by JorensM** [comment]
Just chiming in to say that I also want this feature! The reason I want this is because I'm not using the app most of the time, but I don't want to relaunch it every time. It also helps me stay organized and not have my taskbar cluttered.

**Comment by lssol** [comment]
A few more arguments in favor of a tray icon:
- The icon could look different when a local repo is out of sync or if some files are not yet committed
- The user could set up some notification to be notified when new commits are pushed in certain branches

Visually, it could look similar to the slack tray icon: a red dot when some messages are unread.

**Comment by irtaza-a** [comment]
Since GitHub Desktop for Microsoft Windows doesn't originally support this feature and it is understandable how it is mentioned in:

- https://github.com/desktop/desktop/issues/4098#issuecomment-368375720

- https://github.com/desktop/desktop/issues/4098#issuecomment-369112293

In addition to @niik's [comment](https://github.com/desktop/desktop/issues/13438), for those who still want this feature for Microsoft Windows, there is an unofficial workaround for this feature. It is not the best solution however it is a solution. Use [Minimize-ToTray](https://www.softpedia.com/get/PORTABLE-SOFTWARE/System/System-Enhancements/Minimize-ToTray.shtml) tool for Microsoft Windows. It is a generic minimize to tray utility for Microsoft Windows.

Cheers!

**Comment by CaptainMirage** [comment]
Everyone have been asking for this since 2018 just add it already, i really want to know how this is even a thing to think about, its just such a good quality of life thing, i am constantly accidentally closing the window just to open the app again and go back into the repo i wanna be in, if you need more reasons than the community wanting it for so long, not sure how it can be hard but just please do it? it would be amazing

cheers

**Comment by QuestionMarkT** [comment]
Just found this issue as I was also wondering how can I drop GitHub Desktop to system tray... kinda weird this feature isn't available in a modern application

**Comment by Roachisserie** [comment]
bump and +1
i would like to have my github desktop not clutter my alt-tab list, or be ever-present on my taskbar when i'm not actively making commits

i would also like to not have to install a 3rd party application just to do something that feels as though it could be a simple addition
