### ISSUE TITLE
App hang a lot now.

### ISSUE THREAD

**Issue by Pritraj** [desktop/desktop#4143]
Beta version was faster than this...
Also, make some validations on buttons until everything is loaded completely(disable them).

I merged the wrong branch due to lack of validations.

**Comment by niik** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

We would love to see you open issues for the specific cases where buttons aren't disabled and how it caused you to merge the wrong branch. I'd also be very interested in hearing about the specific scenarios where the app hangs, I have yet to experience that so I'd obviously like to get to the bottom of why that's happening to you.

Thanks for understanding and meeting us half way :grinning:
