### ISSUE TITLE
Error 500 when trying to download github desktop

### ISSUE THREAD

**Issue by Marcel09** [desktop/desktop#4156]
I cant download github desktop

**Comment by WorkShop-Office** [comment]
yes accepted



Sent from my Redmi 4A
On "request-info[bot]" <notifications@github.com>, Mar 2, 2018 10:23 PM wrote:

Thanks for reaching out!
We require the template<https://github.com/desktop/desktop/blob/master/.github/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report> to be filled out with all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.
Thanks for understanding and meeting us halfway 😀

**Comment by joshaber** [comment]
Hi @Marcel09, this should be fixed now. Please let us know if you still can't download it.
