### ISSUE TITLE
Authentication Fails when cloning a Gitlab repository  (with 2-FA enabled)

### ISSUE THREAD

**Issue by Heikkow** [desktop/desktop#4167]
### Description

I tried to clone a repository from Gitlab but got an error that Authentication failed. If I disable 2-FA (on Gitlab), it works fine.

### Version

**GitHub Desktop version:** 1.1.1-beta1

**OS version:** Windows 10 1709

### Steps to Reproduce

1. Enable 2-FA on Gitlab
1. Try to clone a repository from Gitlab

**Expected behavior:** 
Clone the repository 

**Actual behavior:** 
Get an error -> Authentication Failed

**Reproduces how often:** All the time

**Comment by inatz16** [comment]
>

**Comment by shiftkey** [comment]
@Heikkow thanks for the feedback. We don't currently support handling 2FA from external remotes like GitLab - we only support providing basic authentication.

**Comment by shiftkey** [comment]
This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I added the `future-proposal` label to this issue and closed it so that we won't get overwhelmed with our backlog! We will revisit this in our next planning session.

**Comment by billygriffin** [comment]
Thanks for the suggestion @Heikkow. Because a relatively small percentage of people are using non-GitHub remotes and there are generally workarounds available (for example, using personal access tokens: https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html), I'm going to remove `future-proposal` to indicate this is not something we intend to support in the near term. If we see an increase in this being desired, we may re-evaluate, and we appreciate you letting us know. Thanks again!

**Comment by joanna-natel** [comment]
Glad I found this request, since I couldn't figure out why my authentication kept failing.
