### ISSUE TITLE
ULTRAVARIALHEADSPIN

### ISSUE THREAD

**Issue by 808Ultravarialheadspin** [desktop/desktop#4171]
### Description

[Description of the issue]

### Version

**GitHub Desktop version:** [version here]

**OS version:** [version here]

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by WorkShop-Office** [comment]
Ask the same barack obama



Sent from my Redmi 4A
On ULTRAVARIALHEADSPIN <notifications@github.com>, Mar 5, 2018 8:42 AM wrote:

Description

[Description of the issue]

Version

GitHub Desktop version: [version here]

OS version: [version here]

Steps to Reproduce

  1.  [First step]
  2.  [Second step]
  3.  [and so on]

Expected behavior: [What you expected to happen]

Actual behavior: [What actually happened]

Reproduces how often: [What percentage of the time does it reproduce?]

Logs
Additional Information
