### ISSUE TITLE
Start a Fetch when open the brunch drop down

### ISSUE THREAD

**Issue by pinguin999** [desktop/desktop#4175]
### Description

If I open the brunch Drop-Down I normally search for a brunch to work on. Often the brunch is opened on the server and connected with an Issue. So I have to click the fetch button to get the brunch from the server and than I can change to the brunch.

### Version

**GitHub Desktop version:** 1.1.0

**OS version:** macOS and Windows

### Steps to Reproduce

1. Create a brunch on the git server
2. Open brunch list in GitHub Desktop
3. Search for the brunch name. It's not there. 
4. Click fetch origin
5. The list updates and the brunch is in the list to select.

**Expected behavior:** Fetch every time I open the brunch drop-down

**Actual behavior:** I have to click fetch manually

**Reproduces how often:** Every time

**Comment by iAmWillShepherd** [comment]
Thanks for taking the time to open an issue! 🙇 

Although doing a fetch every time you click the branch drop-down seems like a good idea at first glance, doing so would dramatically increase the number of network requests we do which we would like to avoid. So even though this would solve your issue, it would negatively impact those on metered connections or on slow networks. Going to close since we provide a way to kick off a fetch manually and the app does background fetches at a specific intervals.

**Comment by pinguin999** [comment]
Hi @iAmWillShepherd ,

thanks for explaining it. Maybe we can show the hot key for a fetch next to the pro tip for new branch?

K.
