### ISSUE TITLE
widen the branch selector to support long branch names

### ISSUE THREAD

**Issue by Kubrix** [desktop/desktop#4177]
I like to give my branches long but descriptive names. But the problem is that combobox with the branches names is too short to fit the full name: ![github combobox](https://user-images.githubusercontent.com/33233100/36991986-5f032ad6-20a1-11e8-9ffd-29e5732fea02.PNG)
 
You have some extra unused space after the Push/Pull button. Is it possible to move that button to the right and  widen the abovementioned combobox? Now the combobox is about 11.5 cm wide (1024*768).  Maybe you can make it wider - for example about 15 cm?

I like to see the full branch name without having to mouse over the combobox to do it.

**Comment by iAmWillShepherd** [comment]
Thanks for taking the time to open an issue! 🙇 

That's a good question that @desktop/design could answer better than I can, but I can give a bit of context for you. 

The space to the right of the Fetch button is used when you expand the Repository sidebar. Since we have a minimum window size, the size of the two buttons were made so that they'd fit when the sidebar is at it's maximum expanded state.

![2018-03-05_12-34-59 931](https://user-images.githubusercontent.com/1715082/36992794-a47a4d40-2071-11e8-99a1-f985fe40666b.png)

**Comment by Kubrix** [comment]
My thoughts:
The maximum width of the Changes&History panel seems to depend on resolution - the bigger it is, the lesser is the width.
For example

At 800x600 it is about 65% of the width: https://imgur.com/a/H3NtM
At 1024x768 the maximum width  is half of the screen : https://imgur.com/a/f9Smf
At 1600x900 the maximum width is about one third of the screen size: https://imgur.com/a/Bk4JZ

I think that unless GutHub Desktop is running on 800*600, we might have an extra space for branches combobox.

**Comment by mdiep** [comment]
This is a usability issue for me. My team likes to prefix branch names with things like `feature/M1-13600-`, which is the category and the ticket number. This takes up more than half of the available space, making it very hard for me to tell what the branch actually is.

It seems like this box should just be wider whenever there is available space. That's how it'd work if Desktop was a native app that used Auto Layout. But I wouldn't know what the Electron equivalent is.

**Comment by shiftkey** [comment]
#4569 overlaps with this request and also includes suggestions about resolving the underlying issue, so I'm going to close this out in favour of that issue.
