### ISSUE TITLE
Revert dialog doesn't handle keyboard input as expected (reverts when you may mean cancel)

### ISSUE THREAD

**Issue by DanTup** [desktop/desktop#4187]
I'm fairly new to Mac OS so I may have misunderstood this, but I believe that `<enter>` is supposed to always accept "the blue button" and `<space>` accepts the "blue-bordered-item" which can be tabbed through.

<img width="453" alt="screen shot 2018-03-06 at 20 09 24" src="https://user-images.githubusercontent.com/1078012/37056235-acd3eb80-217b-11e8-92f1-9c2504b7d32d.png">

On this dialog, if I tab to the "Discard changes" button and then press either `<enter>` or `<space>` it still seems to discard, but I expected one to cancel.

**Comment by shiftkey** [comment]
cc @joshaber @maddox for clarification

**Comment by DanTup** [comment]
Here's what I read (though don't know how trustworthy it is):

> It is also the tab key. The difference to Windows is, that the "return" key always pushes the default button (which is the colored one). The currently selected button (which can be changed using the tab key) is marked through a colored border. If you'd like to push this button, you have to press the space bar.
https://apple.stackexchange.com/a/55293/17054

**Comment by DanTup** [comment]
I just tested this on a native dialog, and it does work as described above (enter does the blue button, space does the bordered button (with tab moving the border around)):

<img width="436" alt="screen shot 2018-03-06 at 21 43 22" src="https://user-images.githubusercontent.com/1078012/37060302-c7770e66-2187-11e8-8979-9501ace9ebfa.png">

**Comment by tierninho** [comment]
@DanTup here is some insight to our though process around the choice of button order and colors:
https://github.com/desktop/desktop/issues/5125#issuecomment-403424315

As for `space` and `enter`, in Desktop they both have the same action if a button is highlighted with `tab`. Perhaps @niik can shed some light on this.

**Comment by DanTup** [comment]
I'm a little confused - the linked comment suggests you want to follow macOS, but that doesn't seem to be what's happening. On macOS, `<enter>` does not do the button highlighted with `<tab>`, it does the blue/default button.

(I'm also not sure about the `reviewer-needs-to-reproduce` label?)

**Comment by billygriffin** [comment]
@DanTup Trying to run down the right answer here, and I was wondering where you see that guidance for macOS? In https://developer.apple.com/design/human-interface-guidelines/macos/buttons/push-buttons/ the primary guidance around this is:

> Configure a push button the user is highly likely to select as the default. A default push button is prominent in appearance and automatically performs its action when the user presses Return. There can only be a single default button in a view.

But I couldn't find anything about tabbing to a particular button and the expected behavior at that point. Anecdotally, I asked several macOS users and they all had the expectation that if they've tabbed to a button and click <return>, the selected button is the action that will be taken.

**Comment by DanTup** [comment]
@billygriffin See the link in https://github.com/desktop/desktop/issues/4187#issuecomment-370916152 and the comment below. It wasn't official guidance, it was an SO answer - however I tested it with some built-in dialogs and that matches how it works (I couldn't find it documented anywhere official).

For example, click Empty Trash then press `<tab>` so that one button has Blue BG and one has Blue Outline, and note that <Enter> triggers one and <Space> triggers the other.

**Comment by billygriffin** [comment]
Sorry @DanTup, I just typed "<return>" instead of `<return>` 😞 

I'm going to go through and do a more thorough read of the macOS and Windows docs on all this stuff and hopefully create a set of guidance that describes what we're doing and how it aligns with the OS-level guidance. Thanks for the thoughts here, they're really helpful.

**Comment by DanTup** [comment]
Here's the closest thing I can find to official:

https://support.apple.com/en-gb/HT204434

> Move to the next control | `Tab`
> Choose the selected menu item | `Space bar`
> Click the default button or perform the default action | `Return or Enter`

It says "menu item" so it's not clear, but it does match the behaviour of the built-in dialogs - the blue buttons are *defaults*, accepted with `<enter>` and tab moves the *selection* which is accepted with `<space>`.

**Comment by billygriffin** [comment]
Thanks for the issue @DanTup! We discuss this in great detail this morning, and we're improving the dialog interactions in #8599. After that PR lands, the only time someone could get into this state is when they *explicitly* tab to a different button, and while it has focus, they hit `Return` or `Enter`. I also went through a couple tests with macOS users just to find out if changing this would cause confusion, and each time the person expected that `Return` would select the button that was selected, and not the default button. Since this requires an explicit tabbing to a particular button and then clicking return, we think changing it would cause more confusion than it would alleviate. And hopefully #8599 will clear up some of the confusion around which button has initial focus. Thanks again!

**Comment by DanTup** [comment]
>  I also went through a couple tests with macOS users just to find out if changing this would cause confusion, and each time the person expected that Return would select the button that was selected, and not the default button

I don't doubt that, because macOS's behaviour is (IMO) wonky. However doing the opposite to the rest of the OS because it's what people (that presumably don't use this behaviour - else they'd know how it worked) seems weird. People that don't use these keys aren't going to be impacted, but those people that do will find your behaviour confusing/wrong.

(I don't feel strongly about it, I don't use it much - it just felt a bit weird, especially when the actions can be destructive).

**Comment by billygriffin** [comment]
Totally agree with your critique, it's completely valid. We went back and forth on it and agree that there's not a great answer, but ultimately decided that since `Cancel` will close the dialog, that behavior will be super confusing as well, and since it requires that a user explicitly tabs to the particular button prior to the click, they've signaled their intent sufficiently enough to depart from the macOS behavior in this very narrow case. Thanks again for the issue, it really helped us understand how to think about it.
