### ISSUE TITLE
Github.com Projects won't update after a user switch

### ISSUE THREAD

**Issue by Whippsie** [desktop/desktop#4193]
My issue is relatively simple.
I was connected on githubdesktop using X username. I changed to be connected under Y username.

Main problem is : when I click on the list to show the current projects i am working on right now, it shows the one from the old account. There is no option to "update" these. When i tried to click on it, it obviously said it can't find it.

**Comment by iAmWillShepherd** [comment]
Thanks for taking the time to open an issue! 🙇 

To make sure I understand your problem correctly, I assumed these were the steps to reproduce.
1. Open Desktop
1. Sign out 
1. Sign in with a **different** user
1. Open _Clone a Repository_ dialog
1. Repositories from original logged in account are shown instead of newly signed in account

Following the steps above, I get this screen.
![2018-03-07_09-45-31 334](https://user-images.githubusercontent.com/1715082/37101929-4bed1550-21ec-11e8-9b2b-41f05c49cb98.png)


Could you verify you get the following screen when you attempt to clone a repository? If my steps are not correct, please fill out the issue template as outlined [here](https://github.com/desktop/desktop/blob/master/.github/CONTRIBUTING.md#reporting-bugs)

**Comment by Whippsie** [comment]
Hi
Thanks for taking the time to look into my issue.
For step no 4, I clicked on the little triangle next to "Current Repository" to show the list of repos associated with my account.
![image](https://user-images.githubusercontent.com/24740373/37110093-ecdec90a-2209-11e8-9ee2-2048a720ef9c.png)
![image](https://user-images.githubusercontent.com/24740373/37110150-17e573a6-220a-11e8-912b-6bd6c08eb034.png)

**Comment by shiftkey** [comment]
@Whippsie the repositories in that list are local repositories, and are not tied to any specific account - switching accounts will not change this list.

>  There is no option to "update" these.

I'm not sure I understand this - could you elaborate on what "update" means to you?

> When i tried to click on it, it obviously said it can't find it.

Was an error shown here? The only scenario I can think of here would be if the repository no longer exists on disk.

**Comment by Whippsie** [comment]
Oh, this makes sense then. The label "GitHub.com" made me believe it was the repositories linked to the account on github but on the server side. Turns out all the ones shown were the only repos I had on that specific account. Thus, the confusion.

The "Other" label would be projects that aren't linked yet to my github? Because that project comes from github as well, but I cloned it manually on the website. 

When I said update, I simply meant a refresh button, where the dead repos would disappear.

Anyways, it seems more like a misunderstanding from me than an error, so i'll go ahead and close this issue. Thanks for your time everyone!

**Comment by shiftkey** [comment]
@Whippsie thanks for the clarification

> The "Other" label would be projects that aren't linked yet to my github? Because that project comes from github as well, but I cloned it manually on the website.

The application try and refresh the repository information (which includes matching the repository to a remote) whenever you select the repository, so it might not have worked because you weren't signed into a GitHub account (or the right GitHub account for private repositories) at the time, or if it wasn't able to access the internet.
