### ISSUE TITLE
The list of changes is absurdly narrow

### ISSUE THREAD

**Issue by BasmanovDaniil** [desktop/desktop#4195]
## Description
The maximum width of the left panel and especially of the list of changes in the History tab is severely limited. Here is an example:
![](https://monosnap.com/file/RUDj0i3JukW8N6G09FSk3nugT05EZW.png)
How am I even supposed to interpret this? Hover over each line? Why limit the maximum width?
I have some repositories with very convoluted hierarchies where the paths to changed files appear in the ui with no useful meaning: `Path\To\The\Project\Folder\...\File.txt`.

## Version
* GitHub Desktop: 1.1.0
* Operating system: Windows 10 Pro

## Steps to Reproduce
1. Grab the edge of the panel with commit's list of changes and drag to the right.
2. The edge stops way too soon.

### Expected Behavior
The panel expands to at least a quarer of the screen's width?

### Actual Behavior
It stops at a distance of about 350 pixels.

## Additional Information
![](https://monosnap.com/file/KAXV8GgNzJL3kSB6QwM3hmdoB7GOLS.png)
![](https://monosnap.com/file/GLSoSdFUY24KeKvN2J6R251A4HwaXY.png)

**Comment by Kubrix** [comment]
@BasmanovDaniil please see my comment about the related issue: https://github.com/desktop/desktop/issues/4177#issuecomment-370889665

The right border seems to depend on resolution.

**Comment by niik** [comment]
Hey @BasmanovDaniil, thanks for opening this. I think this request is sufficiently captured in https://github.com/desktop/desktop/issues/1588 (see https://github.com/desktop/desktop/issues/1588#issuecomment-329405096 for some context) and https://github.com/desktop/desktop/issues/2745 so please subscribe to those issues to follow along and please add any specific feedback not already captured in them there. 

The short answer is that we agree and that we'd like to lessen the constraints significantly here but there's some work that needs to be done around dynamically adjusting the max widths for these resizable panels based on the window size (and taking into account zooming). Additionally we'd like to have a more dynamic toolbar that adapts to the available space.

![silly-wide-sidebar](https://user-images.githubusercontent.com/634063/37597000-5139e7c2-2b7e-11e8-8e1a-7997557ea1eb.gif)

Since this is captured elsewhere I'll close this issue out.
