### ISSUE TITLE
The window jump out everytime I made even a tiny change in my project

### ISSUE THREAD

**Issue by piggona** [desktop/desktop#4201]
## Version

* GitHub Desktop:

* Operating system:

**Comment by j-f1** [comment]
Thanks for reaching out!

We require the template to be filled out when submitting all issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway 😀

**Comment by niik** [comment]
Thank you for your issue!

We haven't gotten a response to our questions.
With only the information that is currently in the issue, we don't have enough
information to take action. I'm going to close this but don't hesitate to reach
out if you have or find the answers we need, we'll be happy to reopen the
issue.
