### ISSUE TITLE
git shell

### ISSUE THREAD

**Issue by datason** [desktop/desktop#4203]
## Version

* GitHub Desktop:

* Operating system:

**Comment by j-f1** [comment]
Thanks for reaching out!

We require the template to be filled out when submitting all issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway 😀
