### ISSUE TITLE
Improve text contrast and make the UI elements more visible

### ISSUE THREAD

**Issue by sai-manoj-kumar** [desktop/desktop#4219]
## Description

The text in the desktop application has a very low contrast. The menu bar is almost invisible. Please see the snapshot below in Additional Information section. Also, see the highlighted part where there is grey text on black background. It makes it really hard to read. Also, we should develop keeping in mind those who don't have perfect vision. There are no themes for high-contrast which makes.

## Version
* GitHub Desktop: 1.1.0
* Operating system: Windows 10, Version 1709.

## Steps to Reproduce
1. Open the desktop app.
2. Try to read any text.
3. Compare it with reading text in a simple text editor
### Expected Behavior
Expectation is to be able to read the text and find menu bar easily.
### Actual Behavior
Difficult to read text and other UI elements like menu bar and close, minimize and maximize buttons.

## Additional Information

![image](https://user-images.githubusercontent.com/647333/37250864-b4f35784-252b-11e8-8e3e-c867ee044f58.png)

**Comment by shiftkey** [comment]
@desktop/design I think this is the most specific bit of feedback:

> Also, see the highlighted part where there is grey text on black background. It makes it really hard to read.

This is more noticeable on Windows rather than macOS. I traced the current color value back to https://github.com/desktop/desktop/pull/1713 which was related to switching over to primer-based values - any other context on how we settled on this value?

**Comment by niik** [comment]
> This is more noticeable on Windows rather than macOS

Yeah, I guess that's because Segoe is a little thinner than SF.

> I traced the current color value back to #1713 which was related to switching over to primer-based values

This particular color actually didn't change as part of switching to primer, it was just a matter of importing, and using the appropriate constant.

>  any other context on how we settled on this value?

I believe this has been part of the designs since early on. I can't recall that we had a discussion specifically about this color but our intention with the lower brightness was to further underscore the lower importance of the description text and conversely elevate the title. AFAICT the contrast score does meet WCAG AA standards with a 5.34:1 contrast ratio. I could see us going a little higher (definitely on Windows due to Segoe) but I'll admit that I do worry that if we increase it too much we're going to loose part of the visual separation between the title and the description and end up detracting from the primary piece of information (the title).

Going to gray-300 would clear the WCAG AAA contrast rating with room to spare (9.95:1). I'll open a PR and get some feedback from @donokuda.

As for the menu bar I'm in total agreement after looking at it on Windows. We can and should definitely up the contrast there. I wonder if we should just straight up use the primary text toolbar color even (full white) but at the very least it'll benefit from the increased contrast of the secondary.

**Comment by sai-manoj-kumar** [comment]
@niik, Nice to see that the change is already implemented. Are you considering the right top three buttons; minimize, maximize/restore and close buttons? Also can we think about providing some themes, or theme framework Atom and VS code does? That may be a bigger feature though.
