### ISSUE TITLE
"Open in Desktop" link doesn't work in Chrome on macOS

### ISSUE THREAD

**Issue by mikez302** [desktop/desktop#4231]
I have a brand new Mac, running macOS 10.13.3. I am viewing a repo in Chrome 65, and I am clicking the "Open in Desktop" link under "Clone or Download", and nothing is happening. I mean literally nothing. There are no error messages and no errors in the developer tools console.

Maybe I shouldn't expect the repo to open in GitHub Desktop since I don't have that installed, but I think something definite should happen from the user's point of view. Maybe there should be a page that gives me a chance to download it, or an explanation that I need the app for the link to work.

**Comment by shiftkey** [comment]
@mikez302 thanks for the feedback!

This has been an old issue with the "Clone in Desktop" experience on GitHub The Website, but I have good news - someone has been working on improving this so that we give a helpful error when the tool is missing, and I think it's close to being merged!

I'll update this issue when it's available and confirm it addresses the issue.

**Comment by shiftkey** [comment]
@mikez302 could you test out the "Clone in Desktop" experience again? You should see a prompt like this when you don't have Desktop installed:

<img width="417" src="https://user-images.githubusercontent.com/359239/37358487-71d843aa-26a8-11e8-81bd-c07522c6aa43.png">

**Comment by mikez302** [comment]
I tried it and I saw the prompt.

I moved GitHub Desktop to the Trash, and tried it again, and saw the prompt
again.

**Comment by shiftkey** [comment]
> I tried it and I saw the prompt.

Did it then launch Desktop successfully? If so, I think we're good here.

> I moved GitHub Desktop to the Trash, and tried it again, and saw the prompt
again.

This is expected, but then you shouldn't see Desktop launch (because it's not on the machine).

**Comment by mikez302** [comment]
It launched Desktop when it was able to. When it wasn't, the prompt came
up, but nothing happened (as expected).

**Comment by shiftkey** [comment]
@mikez302 cool, that sounds like the issue is resolved.

Let me know if you encounter anything else unexpected around this area.

**Comment by white-sdev** [comment]
I created a new Chrome profile and it works on my old profile but in the new one it takes me directly to the download website(no prompt) even when having the desktop application open.
(Obviously it is something related with Chrome profiles)

**Comment by shiftkey** [comment]
@white-sdev were you signed into GitHub at the time?

**Comment by white-sdev** [comment]
@shiftkey It is working now, I guess it is because of what you mentioned :S so sry. And thank you!

**Comment by fuhrmanator** [comment]
> @white-sdev were you signed into GitHub at the time?

Indeed - if one is **not** signed in, this won't work - you'll download GitHub Desktop, install it, and clone only to see the download page. 

I hit this bug with a laptop I hadn't used in a while (the sign-in on GitHub had expired) and I was trying to clone a repo. Seems like a more clear error message is in order? I get from this that GitHub wants to track the clone (it can't be done anonymously).

Edit: Oops... I'm on Windows 10 (didn't notice the bug was for MacOS)
