### ISSUE TITLE
Unable to see a “missing” repos on Repo List

### ISSUE THREAD

**Issue by gingerbeardman** [desktop/desktop#4254]
## Description

Often you delete a repo from disk and there’s still a reference in GHD.

GHD Classic used to show such repos
![screen shot 2018-03-15 at 17 45 41](https://user-images.githubusercontent.com/49612/37481435-ab07cfa6-2879-11e8-8830-0f638c0247a3.png)

GHD Electron does not.
![screen shot 2018-03-15 at 17 50 09](https://user-images.githubusercontent.com/49612/37481442-ae764b0e-2879-11e8-9648-3b31d1e4cc1b.png)

**Comment by shiftkey** [comment]
@gingerbeardman nice find! This is definitely something we overlooked during the transition, and an easy thing for someone to contribute.

We're already tracking the `missing` state on a repository, so I think a simple change inside `app/src/ui/octicons/repository.ts` to display the right icon again is all that's needed: 

```diff
diff --git a/app/src/ui/octicons/repository.ts b/app/src/ui/octicons/repository.ts
index b99a22d4e..4db5681b6 100644
--- a/app/src/ui/octicons/repository.ts
+++ b/app/src/ui/octicons/repository.ts
@@ -10,6 +10,10 @@ export function iconForRepository(repository: Repository | CloningRepository) {
     return OcticonSymbol.desktopDownload
   }

+  if (repository.missing) {
+    return OcticonSymbol.alert
+  }
+
   const gitHubRepo = repository.gitHubRepository
   if (!gitHubRepo) {
     return OcticonSymbol.deviceDesktop
```

I chose `alert` here because that seems to be what we were using in the classic Mac app, but the reviewer might suggest a more suitable [Octicon](https://octicons.github.com/).

**Comment by gingerbeardman** [comment]
Done https://github.com/desktop/desktop/pull/4258
