### ISSUE TITLE
Sync button should run git fetch --all

### ISSUE THREAD

**Issue by Pr0methean** [desktop/desktop#4278]
## Description
I recently needed to contribute to a branch that was on the origin, not on my fork, because a fellow contributor had taken over my pull request in order to make some changes while I'd been offline. I couldn't find it on the list even after clicking the Sync button, which was unexpected, although running `git fetch --all` in the shell fixed it.

## Version
* GitHub Desktop: Chocolate-Covered Yaks (3.3.4.0) 50415df
* Operating system: Windows 10 Pro

## Steps to Reproduce
1. Alice forks a repository owned by Bob and clones it in GitHub Desktop.
2. Bob adds a branch to the origin repo.
3. Alice clicks Sync and opens the list of branches.

### Expected Behavior
The new branch is on the list. Alice can check it out from the GUI.

### Actual Behavior
The new branch isn't on the list.

**Comment by shiftkey** [comment]
@Pr0methean thanks for the feedback!

It looks like this issue is with the Classic apps, but this repository is for issues with the redesigned GitHub Desktop (see https://desktop.github.com).

For reference, the new Desktop app initially did `fetch --all` when syncing but we disabled that in #1435 to make this button clearer. I _think_ this scenario should be handled fine in the new Desktop because:

 - the app ensures forks are setup correctly for GitHub repositories: #3199
 - the app will fetch the current, `origin` and `upstream` remotes when doing a fetch, to catch scenarios like this: #4057

Please try out the new Desktop app and confirm we handle this case!
