### ISSUE TITLE
[BUG] Commit name not showing correctly

### ISSUE THREAD

**Issue by karimbenammar** [desktop/desktop#4306]
## Description
Commit summary is being split into two parts, one of them is being shown in the description section.

## Version

* GitHub Desktop: 1.1.0

* Operating system: Windows 10 x64

## Steps to Reproduce
Commit any changes, set this as commit summary (without quotes):
"Added covoiturage fxml interface for create (testing ; github title bug..)."

### Expected Behavior
Commit summary should be (wihout quotes):
"Added covoiturage fxml interface for create (testing ; github title bug..)."

### Actual Behavior
Commit summary is set to (without quotes):
"Added covoiturage fxml interface for create (testing ; github title b…"
And Description is set to (without quotes):
"…ug..)."

## Additional Information
Github Desktop sidebar is showing the commit correctly:
![image](https://user-images.githubusercontent.com/29929026/37781533-2b9873ec-2df1-11e8-9f8b-ee4edce83c7d.png)

But when opening it or viewing it on Github.com it shows incorrectly

Github.com:
![image](https://user-images.githubusercontent.com/29929026/37781450-04f07d20-2df1-11e8-9649-55f825c1d8c2.png)

Github Desktop:
![image](https://user-images.githubusercontent.com/29929026/37781593-46351516-2df1-11e8-81fd-54d9948c2cbd.png)

**Comment by niik** [comment]
Hey @karimbenammar, thanks for opening this! Wrapping the commit message summary is expected behavior. GitHub.com and GitHub desktop will wrap the at 72 characters. This is only a presentation concern though, the commit summary is preserved as you wrote it in the actual commit.

This change was implemented (on desktop) in https://github.com/desktop/desktop/pull/2575 in order to address https://github.com/desktop/desktop/issues/1742.
