### ISSUE TITLE
Problem with large repositories or large file changes on the repo

### ISSUE THREAD

**Issue by burumart** [desktop/desktop#4309]
## Description
Large changes of repositories ( thousands of files ) make the GUI unusable. 

* GitHub Desktop: On any version I've tried on Windows.

## Steps to Reproduce

Create a repo.
Add a thousands of files.

### Expected Behavior
Process some files and don't be overloaded waiting to process all of them.

### Actual Behavior
It gets stuck processing.

**Comment by niik** [comment]
Hi @burumart. Could you attach a log file (You can simply drag your file here to insert it) to this issue so that we can have a look at what's taking so long.

Windows logs location: `%APPDATA%\GitHub Desktop\logs\*.desktop.production.log`

It would also be helpful for us if we understood the workflow that you're in that gets you to a state where you have thousands of modified files. Is it automatically generated files? Do the files need to be part of source control? Etc.

**Comment by shiftkey** [comment]
Closing this out due to inactivity. @burumart if you're able to share the log files from around the time of the issue and answer the questions above we're happy to revisit this.
