### ISSUE TITLE
Add an option to discard all changes

### ISSUE THREAD

**Issue by EpokK** [desktop/desktop#4314]
## Description

It can be great to have an option to discard all current change, the same thing as running `git clean -fdx`

<img width="370" alt="capture d ecran 2018-03-23 a 09 43 34" src="https://user-images.githubusercontent.com/1345786/37819782-f939f09a-2e7e-11e8-8d4f-abe5e29ad202.png">

**Comment by niik** [comment]
Hey @EpokK, right now you can right-click on the "x changed files" header to discard all changes.

<img src="https://user-images.githubusercontent.com/1174461/37114275-b4968720-21fc-11e8-911f-e5e09927a448.png" width="400" />

We're working on making this more discoverable. https://github.com/desktop/desktop/pull/4230 added  the discard all changes menu item to the context menu of individual files. That change will be part of the next release.

Following that #4188 will add support for selecting more than one file in the list and discarding the selected files through the context menu.

I'm going to close this issue as the functionality exists already and since we're on track to make it even better!

**Comment by EpokK** [comment]
@niik Oh thanks for the tip!
