### ISSUE TITLE
Refactor FilterList Component

### ISSUE THREAD

**Issue by iAmWillShepherd** [desktop/desktop#4317]
The filter list component does not support a way to compose the filterable list with an arbitrary text input. This became an issue when implementing issue #3968 because I needed the `TextBox` component to remain visible even when the `FilterableList` was not. I basically did a hack which involved me passing a `TextBox` component to the `FilterList` just to make progress, but we should go back and do it the right way.

**Comment by shiftkey** [comment]
Just had a chat with @iAmWillShepherd about this issue, and while it does feel like some ugly work to get the Compare tab experience working, I don't think this is worth holding up the ship. 

I've moved this into 1.2.x milestone and I'll pair with @iAmWillShepherd on this over the coming days to scout the best way to re-organize the logic of `FilterList` so that the list of results can be decoupled from the textbox without needing to pass around textboxes.

This might also help solve #4458
