### ISSUE TITLE
sport-facility sa46-4B

### ISSUE THREAD

**Issue by zhaoyinqing** [desktop/desktop#4338]
## Version

* GitHub Desktop:

* Operating system:

**Comment by shiftkey** [comment]
@zhaoyinqing thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
