### ISSUE TITLE
it's not working good

### ISSUE THREAD

**Issue by vishnugopy** [desktop/desktop#4343]
## Version

* GitHub Desktop:

* Operating system:

**Comment by iAmWillShepherd** [comment]
Thanks for reaching out!

We require the template to be filled out with all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway 😀
