### ISSUE TITLE
I can't use git bash anymore

### ISSUE THREAD

**Issue by carlosmonteiro** [desktop/desktop#4344]
## Version

* GitHub Desktop: 1.1.1

* Operating system:
Windows 10

**Comment by j-f1** [comment]
Thanks for reaching out!

We require the template to be filled out when submitting all issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway 😀

**Comment by shiftkey** [comment]
Closing this out due to inactivity. @carlosmonteiro  if you're able to fill out the template to assist with troubleshooting we're happy to revisit it.
