### ISSUE TITLE
CSE 442 BUGG ACTIVITY Respiratory on Computer wont add new files from recent pull 

### ISSUE THREAD

**Issue by jayeni** [desktop/desktop#4352]
my local github repository sometimes updates only the classes it has from a new pull request but oeant add new classes that were made from the new pull request(JAVA)

**Comment by iAmWillShepherd** [comment]
Thanks for reaching out!

We require the template to be filled out with all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway 😀

**Comment by shiftkey** [comment]
Closing this out due to inactivity. @jayeni if you're able to fill out the template we're happy to revisit this issue.
