### ISSUE TITLE
This app REALLY needs 32-bit support for Windows (please join that vein!)

### ISSUE THREAD

**Issue by StinkerB06** [desktop/desktop#4366]
I even read that issue that discusses 32-bit Windows support. If you target an app to 64-bit only, it makes the app incompatible with older PCs with up-to-date Windows versions.

Some schools probably use GitHub, especially with the Desktop app. But some students are assigned a 32-bit system as I read about it.

If you only have a 32-bit PC and you want to put hands to GitHub's Desktop app, I'd suggest compiling the libs to 32-bit, alongside the app itself, and releasing a 100% 32-bit installer for Desktop. Some people may not even afford a modern 64-bit system stuck with their crappy 32-bit, lonely without the app. ;-(

Even that URL for the official 64-bit installer EXE file, it lies to you because it says "win32", tricking the person into thinking it's a 32-bit Windows app. It theoretically runs on 32-bit Windows, but eventually shows up with two error message pop-ups.

Why not join the vein where almost every other addictive Windows app is compatible with 32-bit?!? The whole thing for releasing the Windows version makes no sense AT ALL.

**Comment by shiftkey** [comment]
@StinkerB06 as mentioned over in #1214, we haven't addressed 32-bit Windows support because [our analytics](https://github.com/desktop/desktop/issues/1214#issuecomment-294834750) indicate the vast majority of our audience is now on 64-bit Windows. 

But that's not the end of the story. Much like our evolving [Linux support](https://github.com/desktop/desktop/blob/master/docs/contributing/linux-testing-and-you.md) and recent work to get Desktop building on ARM64 https://github.com/desktop/desktop/pull/4198, **contributions from the community are the best way to see what you want happen**. But keep in mind that Electron only [supports Windows 7 or later](https://electronjs.org/docs/tutorial/supported-platforms) currently.

I've opened https://github.com/desktop/dugite-native/issues/86 with details about the work needed to get our embedded version of Git working against 32-bit Windows - that one is critical to success. I'm happy to work with and review contributions from someone if they want to get involved, and once that's in we'll likely uncover other work that needs to be done.

**Comment by StinkerB06** [comment]
There are three free fantasy consoles that are only for 64-bit. PX8, Riko4, and CToy.
https://github.com/Gigoteur/UnicornConsole/issues/61
https://github.com/incinirate/Riko4/issues/10
https://github.com/anael-seghezzi/CToy/issues/16

**Comment by SlySven** [comment]
Please, please, please fix the front page to indicate that **BOTH** Windows downloads are for the 64-bit version, the smaller one *which, admittedly **does** note that it is a `.msi` Microsoft Installer File* just looks like it is the non preferred i.e. 32-Bit one - and the URLS for both of them confounds the issue by saying Win32.

You really must confess out front that currently you do not have a version for us users of older but still operable hardware.

**Comment by StinkerB06** [comment]
The problem is why not support 32-bit in the first place?

**Comment by bopoh13** [comment]
Because the new version was originally developed on [64-bit OS](https://github.com/desktop/desktop/issues/1214). It is strange that their analytics did not show that most people generally sit on the Android 7.
Download the [GutHub Desktop 3.3.6 online-setup for win32](https://github-windows.s3.amazonaws.com/GitHubSetup.exe). It does not update, but it works. Good luck.
