### ISSUE TITLE
Console solution

### ISSUE THREAD

**Issue by hypernewbie** [desktop/desktop#4389]
Please add a console based solution.

**Comment by hypernewbie** [comment]
I mean Github for desktop should offer some kind of sane terminal command option, similar to Git Shell that was available in last version.

git-bash offered by sourcetree is terrible and breaks and conflicts often with build environments, resulting in people having to open like 3 terminals at once. Doesn't really feel like a solution, more like turning a set of problems into a different set of problems.

posh-git option offered by old deprecated Github for Windows was great. But, for some reason new Github Desktop decided to trash that for no apparent good reason.

**Comment by shiftkey** [comment]
@hypernewbie we no longer ship a Git Shell experience in Desktop because:

 - with the switch to Electron it required significant work reimplementing everything
 - Git for Windows had improved significantly from the time we started GitHub for Windows, adding features like SChannel support, GitHub 2FA and auto-updating.
 - Maintaining Git Shell took away engineering work from Desktop UI development and features, which is the core purpose of Desktop

You can read more about this in the original discussion: https://github.com/desktop/desktop/issues/340

Git for Windows is looking to add Posh-Git support at some point in the future, so please follow along with this issue: https://github.com/git-for-windows/git/issues/1384

**Comment by hypernewbie** [comment]
Then why not embed a portable version of Git for Windows, if it has improved so significantly?
Update: Turns out Sourcetree does exactly that.

**Comment by hypernewbie** [comment]
Also, why was the old Github for Windows hastily deprecated, with no download links available, when Github desktop isn't on feature parity?

**Comment by shiftkey** [comment]
> Then why not embed a portable version of Git for Windows, if it has improved so significantly?

In Desktop we use a portable version of Git for Windows (it's based on the MinGit variant) which is designed for applications to embed. It lacks the Unix command line tools that come with a typical Git for Windows install, to keep the install size small.

A vanilla Git for Windows install (minus Posh-Git) is pretty close to what we previously had with Git Shell. That's what we recommend these days for command line usage, and Posh-Git can be [installed](https://github.com/dahlbyk/posh-git#installation) easily on top of that. We'd rather focus on the UI side of things and help contribute upstream to Git for Windows whenever we can (where everyone will see the benefits).

> Also, why was the old Github for Windows hastily deprecated, with no download links available, when Github desktop isn't on feature parity?

Aside from this Git Shell discussion, what do you feel is missing? We might have things on our [roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md) or have open issues tracking them that I can point you to.

**Comment by hypernewbie** [comment]
Thanks for the prompt replies. Never mind me, I'm just being cranky from Github for Windows managing to keep utter chaos at bay for git on Windows being gone.

I would prefer Git for Windows to be exposed and have an option to download utils in the settings. It makes little sense to me to have to set all this interacting things up individually myself to get console to work.

Interacting things break and create chaos. Posh-Git might for example be broken for whatever powershell version I have, or this version of posh-git be broken for the Git for Windows version it is installed on top. Git for Windows update might break a whole bunch of stuff, utilities get updated that can wreck havoc on intricate automated build systems, and so forth. Environment variables need to be set for something, git extension version differences between Github Desktop, local installed Git for Windows causing breakages ...etc.

I personally see something like Sourcetree or Github Desktop as a one-stop-integrated-one-click-contained solution. There is still chaos, Git on Windows is always going to be chaos, but it's contained to a maintained (and in the case for Github for Windows, _well_ maintained) set inside a single folder. As a developer that is what was most helpful to me on Windows.

**Comment by shiftkey** [comment]
> Never mind me, I'm just being cranky from Github for Windows managing to keep utter chaos at bay for git on Windows being gone.

I'd suggest helping to improve these upstream projects by providing good bug reports of the things you encounter so that the maintainers are aware of the issues and can investigate further. The number of configurations they have to support is daunting, so any assistance you can provide them would be great. Git Shell wasn't possible without projects like Git for Windows and Posh-Git.

> I personally see something like Sourcetree or Github Desktop as a one-stop-integrated-one-click-contained solution.

This was something that I maintained for the previous few years, so I'm aware of the pain that it takes away. While I'm glad it had a lot of love from users it was significant overhead that took away from other work - hence my passion for ensuring awareness and support for the upstream projects to thrive.

**Comment by shiftkey** [comment]
@hypernewbie I'm going to close this out as we're not planning to revisit Git Shell in the near or medium term - I hope the context helps understand why that's the case!

**Comment by hypernewbie** [comment]
> it was significant overhead that took away from other work  

Overhead work that users now have to do? The overhead work didn't just disappear, right?
I'm just sad that I can't recommend Github Desktop to colleagues any more with a straight face without a non-chaotic console option.

Thank you for having maintained this in the past.
