### ISSUE TITLE
New GHD Electron does not show changed files the same way as in GHD Classic

### ISSUE THREAD

**Issue by gingerbeardman** [desktop/desktop#4393]
## Description

New GHD Electron does not show changed files the same way as in GHD Classic

## Version

* GitHub Desktop: 1.1.1
* GHD Classic: 223

* Operating system: macOS 10.13.4

## Steps to Reproduce
1. Clone a repo containing .strings files with line endings that are not the same as your host OS.

Possibly also:

2. .gitconfig
```
[diff "localizablestrings"]
textconv = "iconv -f utf-16 -t utf-8"
```

3. .gitattributes
```
*.strings   diff=localizablestrings
```

### Expected Behavior

Both apps should show the same list of changed files

### Actual Behavior

GHD Classic
- shows files with changed line endings (eg. 15 files total)
- shows .strings files as Text

GHD Electron
- _does not_ show files with changed line endings (eg. 10 files total)
- shows some .strings files as _Binary_

## Additional Information

See the affected files in this PR: https://github.com/aonez/Keka/pull/167/files

### Screenshots

GHD Classic
![GHD Classic](https://user-images.githubusercontent.com/49612/38311526-5198fc58-3817-11e8-9adb-41502d8fb0df.png)

GHD Electron
![GHD Electron](https://user-images.githubusercontent.com/49612/38311600-7c999570-3817-11e8-8f59-fae3ceaac3c8.png)

**Comment by shiftkey** [comment]
@gingerbeardman thanks for the report.

I'm not 100% sure of the `git diff` behaviour on the classic Mac app currently, but I'm pretty sure this is related to Desktop Electron including `--no-ext-diff` in #1124 to prevent external diff drivers throwing errors. The goal with that was to ignore interactive diff programs, but it seems like it's a blunt hammer and is also catching your diff driver.

One question about the setup:

```
[diff "localizablestrings"]
textconv = "iconv -f utf-16 -t utf-8"
```

Is this from your global `~/.gitconfig`? Or from somewhere else?

**Comment by gingerbeardman** [comment]
It's from a .gitconfig the root of this particular repo.

**Comment by shiftkey** [comment]
> It's from a .gitconfig in the root of this particular repo.

This is the part that's puzzling to me, because the [Git documentation](https://git-scm.com/docs/git-config#FILES) for config indicates there are four locations for config that it will use - and if you want to embed config into the repository it should be at `.git/config`:

 - `$(prefix)/etc/gitconfig` - System-wide configuration file.
 - `$XDG_CONFIG_HOME/git/config` or `$HOME/.config/git/config` - Second user-specific configuration file. 
 - `~/.gitconfig` - User-specific configuration file. Also called "global" configuration file.
 - `$GIT_DIR/config`

On Windows' there's one more "system" location but that's unimportant to the issue at hand.

Could you run this command from within the problem repository to confirm that it's detecting the diff setting, and where it's coming from?

```
$ git config --show-origin -l | grep diff
```

On my machine it's detecting it from the global configuration (I also have some branches named "diff" which get caught by this):

```
$ git config --show-origin -l | grep diff
file:/Users/shiftkey/.gitconfig	diff.localizablestrings.textconv=iconv -f utf-16 -t utf-8
...
```

**Comment by shiftkey** [comment]
There's an outstanding question here about the setup, but enough here to try and reproduce the issue to confirm the problem =.

**Comment by tierninho** [comment]
@gingerbeardman Sorry for the delay in responding to this issue. Any chance you could:

> Could you run this command from within the problem repository to confirm that it's detecting the diff setting, and where it's coming from?

> `$ git config --show-origin -l | grep diff`

> On my machine it's detecting it from the global configuration (I also have some branches named "diff" which get caught by this):

> `$ git config --show-origin -l | grep diff
file:/Users/shiftkey/.gitconfig	diff.localizablestrings.textconv=iconv -f utf-16 -t utf-8`

Also, are you requesting we enhance Electron Desktop or are you saying this a bug? It seems we prevent the display of these diffs on purpose, but we could do a better job at identifying diff drivers.

> I'm not 100% sure of the git diff behaviour on the classic Mac app currently, but I'm pretty sure this is related to Desktop Electron including --no-ext-diff in #1124 to prevent external diff drivers throwing errors. The goal with that was to ignore interactive diff programs, but it seems like it's a blunt hammer and is also catching your diff driver.

**Comment by gingerbeardman** [comment]
@tierninho closed with what resolution? Thanks

**Comment by tierninho** [comment]
@gingerbeardman Thanks for the question and look forward to your thoughts on the following:

I am curious if this is a problem in your daily workflow, or is it an enhancement request to the new Desktop -- despite it being an existing feature in Classic? In general, we have no plans to bring over every feature from Classic to the new Desktop due to various reasons. 

We are still open to it though, especially if it is a problem. If so, it would be great to understand how it manifests. Please share more.

I closed the issue during routine maintenance, as the last comment received no response: https://github.com/desktop/desktop/issues/4393#issuecomment-426012730 

Thanks for your time and patience.

**Comment by gingerbeardman** [comment]
The problem for me is that I had (with Classic) come to expect to see files that have changed and Desktop changed the behaviour unexpectedly, without any announcement. As well as being unexpected I then had to waste some time figuring out what was wrong (arguably nothing, but the surprise of the new app doing things differently) and then even more time posting this issue.

I mean, we are a year on from this issue being posted, so I am sure the horse has bolted already, but big changes in behaviour like this should be signposted and/or revertible because being forced to move from one working app to a new app that does things a differently for no obvious reason, seems wrong. Migrations should be as smooth as possible, forced migrations even more so.

I can't remember whether I thought this was a bug, or whether I was asking for Desktop to work like Classic. I think I was just annoyed having to spend time figuring out WTF when I shouldn't have had to. IMHO

Also, having just re-read the thread I see that I missed a request for further info. Sorry about that!

> $ git config --show-origin -l | grep diff
```
matt@MacBookPro-Matt:~/Projects/Keka$ git config --show-origin -l | grep diff
file:/Users/matt/.gitconfig	difftool.sourcetree.cmd=opendiff "$LOCAL" "$REMOTE"
file:/Users/matt/.gitconfig	difftool.sourcetree.path=
file:/Users/matt/.gitconfig	mergetool.sourcetree.cmd=/Applications/SourceTree.app/Contents/Resources/opendiff-w.sh "$LOCAL" "$REMOTE" -ancestor "$BASE" -merge "$MERGED"
file:/Users/matt/.gitconfig	diff.tool=opendiff
matt@MacBookPro-Matt:~/Projects/Keka$ 
```

**Comment by billygriffin** [comment]
Hi @gingerbeardman, that's a reasonable thing to be concerned with and sorry for the lack of comms around the change. The Mac app and the Windows app also worked somewhat differently when they were separate apps, so when we merged them into the current one, there were bound to be a few things that were inconsistent when moving from old to new. Again, I apologize that you were thrown off by the inconsistency, and hopefully moving forward we're able to do a better job in making things intuitive and reasonably consistent over time. I certainly hope our continued improvements to Desktop will make you more enthusiastic about using it, and otherwise I hope you find the right tool to meet your needs and help make you as productive and your work as enjoyable as possible. 😄
