### ISSUE TITLE
Account sign in error  --  UNIX[Permission denied]

### ISSUE THREAD

**Issue by loccs-spring** [desktop/desktop#4413]
Account sign in error
I like github desktop very much. When I sign in with my account, github desktop prompted error
as follow:

UNIX[Permission denied]

I don't know why. Thanks.

## Version

* GitHub Desktop:

* Operating system:

**Comment by shiftkey** [comment]
@loccs-spring thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Also, a screenshot of the error source will help with troubleshooting.

Thanks for understanding and meeting us half way 😀

**Comment by shiftkey** [comment]
Closing this out as inactive. @loccs-spring if you can answer the questions above and provide a screenshot of the error we're happy to revisit it.
