### ISSUE TITLE
LFS progress temp directories are not being cleaned up 

### ISSUE THREAD

**Issue by twistedatrocity** [desktop/desktop#4414]
I left github desktop open for a couple of days, I did maybe 25 commits, all small files. However it is leaving thousands of temp directories/files in the User/App/Local/Temp area (windows 7)

I'm guessing this is maybe from it's frequent automatic polling to github to check if anything needs to be pushed/pulled etc. which is fine behavior, however it really needs to clean up after itself better as leaving all this behind on disk for something else to clean up is not good.

I have to go into Temp and manually clean those out every few days because the desktop app just leaves them there forever:

![image](https://user-images.githubusercontent.com/25940480/38478271-442a5f7e-3ba7-11e8-9926-2d24aaa59915.png)

**Comment by shiftkey** [comment]
@twistedatrocity thanks for the report. This is some interoperability that Desktop and Git LFS perform so that we can report progress in the app.

Here's the flow:

1. We ask the OS for a temporary path to use:

https://github.com/desktop/desktop/blob/5b22bc9c94b05962dbf18a8311717829a5d3107f/app/src/lib/progress/lfs.ts#L6-L17

2. We set this as an environment variable that Git LFS understands so it can write progress information to that file (by `tail`-ing output to the file):

https://github.com/desktop/desktop/blob/176a5f1bdf874915e4db894b048f66ce32764adf/app/src/lib/progress/from-process.ts#L25-L33

3. After the LFS process is done, we `unlink` the temporary path, which should delete the file on disk:

https://github.com/desktop/desktop/blob/176a5f1bdf874915e4db894b048f66ce32764adf/app/src/lib/progress/from-process.ts#L63-L68

Reading over [this SO answer](https://stackoverflow.com/a/20801823/1363815) suggests that `unlink` on Windows only marks the file for deletion, and the OS will when the process (so Desktop) is closed. 

> When NodeJS on Windows deletes a file, it's actually not calling an API to directly delete a file. Instead, it's using a low level function called `ZwSetInformation` ([reference](http://msdn.microsoft.com/en-us/library/windows/hardware/ff567096%28v=vs.85%29.aspx)). With that function, it's setting a field called `DeleteFile` to TRUE for the specified file (handle). That's used so that when all file handles are closed for that file, it will be automatically deleted. Files in NodeJS are opened with the access mode of FILE_SHARE_DELETE so that they can be deleted properly by use of the other function.

Does that match up with how you're using Desktop?

**Comment by twistedatrocity** [comment]
Thanks for the detailed reply. The behavior I'm experiencing is that even when the app is closed (and even after an OS reboot) those empty directories remain. Which when I took that screenshot several thousand exist. They are all empty.

I can open the app for an hour then close and the temp dirs remain, or leave it open for a couple days and observe the same behavior.

One thing I noticed though is the code snippets you referenced, do not contain the appended -hash naming that I am seeing in the temp directories created on my system.

**Comment by shiftkey** [comment]
> The behavior I'm experiencing is that even when the app is closed (and even after an OS reboot) those empty directories remain. 

The empty folders isn't something I'd thought about, but it makes sense because the LFS progress file looks like this:

<img width="617" alt="screen shot 2018-04-09 at 2 58 48 pm" src="https://user-images.githubusercontent.com/359239/38480065-a0825484-3c06-11e8-9189-e92adacc2889.png">

If you `unlink` the full path it's probably not going to clean up the directory that's contains the file.

**Comment by shiftkey** [comment]
I'm going to mark this as `help wanted` as I think it's something ideal for someone to dig into. Here's a rough patch for what I think needs to change in here:

```diff
diff --git a/app/src/lib/progress/from-process.ts b/app/src/lib/progress/from-process.ts
index 56571f4f1..1b2c909e2 100644
--- a/app/src/lib/progress/from-process.ts
+++ b/app/src/lib/progress/from-process.ts
@@ -1,5 +1,6 @@
 import { ChildProcess } from 'child_process'
 import * as Fs from 'fs'
+import * as Path from 'path'
 import * as byline from 'byline'
 
 import { GitProgressParser, IGitProgress, IGitOutput } from './git'
@@ -49,13 +50,13 @@ export async function executionOptionsWithProgress(
  */
 function createProgressProcessCallback(
   parser: GitProgressParser,
-  lfsProgressPath: string | null,
+  lfsProgressFilePath: string | null,
   progressCallback: (progress: IGitProgress | IGitOutput) => void
 ): (process: ChildProcess) => void {
   return process => {
-    if (lfsProgressPath) {
+    if (lfsProgressFilePath) {
       const lfsParser = new GitLFSProgressParser()
-      const disposable = tailByLine(lfsProgressPath, line => {
+      const disposable = tailByLine(lfsProgressFilePath, line => {
         const progress = lfsParser.parse(line)
         progressCallback(progress)
       })
@@ -64,7 +65,9 @@ function createProgressProcessCallback(
         disposable.dispose()
         // NB: We don't really care about errors deleting the file, but Node
         // gets kinda bothered if we don't provide a callback.
-        Fs.unlink(lfsProgressPath, () => {})
+        const tempDirectory = Path.dirname(lfsProgressFilePath)
+        Fs.unlink(lfsProgressFilePath, () => {})
+        Fs.unlink(tempDirectory, () => {})
       })
     }
``` 

I wanted to make it clearer that `lfsProgressFilePath` is a file path, and to try and unlink the directory too when cleaning up. We might even be able to get away with unlinking _just_ the directory, but I haven't tested this yet so I'll leave it for someone who wants to get into contributing to Desktop.

**Comment by shiftkey** [comment]
> One thing I noticed though is the code snippets you referenced, do not contain the appended -hash naming that I am seeing in the temp directories created on my system.

@twistedatrocity that's the NodeJS [`Fs.mkdtemp`](https://nodejs.org/dist/latest-v8.x/docs/api/fs.html#fs_fs_mkdtemp_prefix_options_callback) function we're using:
 
> Creates a unique temporary directory.
>
> Generates six random characters to be appended behind a required `prefix` to create a unique temporary directory.

**Comment by twistedatrocity** [comment]
Aha ok it all makes sense to me now. Thanks for the quick responses!
