### ISSUE TITLE
Commit failed - exit code 1 received

### ISSUE THREAD

**Issue by Deanang** [desktop/desktop#4432]
## Version

* GitHub Desktop:

* Operating system:

**Comment by shiftkey** [comment]
@Deanang thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by steveward** [comment]
@Deanang some users have [run into this error](https://github.com/desktop/desktop/issues/3701#issuecomment-375905661) due to having nested .git directories. Can you try searching your repository to see if you have multiple .git directories?

**Comment by shiftkey** [comment]
Closing as inactive. I gather the :thumbsup: on @steveward's comment indicates it's the same issue, and if you haven't found a workaround then please provide more details and we can revisit this.

**Comment by kunisettykumar** [comment]
Perfect. My issue also got resolved.

**Comment by BoundaryStudio** [comment]
@kunisettykumar how did it got solved cuz i just ran into it

**Comment by adelra** [comment]
> Perfect. My issue also got resolved.

How was your issue resolved?

**Comment by steveward** [comment]
@adelra are you also encountering this issue? Is it possible you have nested .git directories?

**Comment by adelra** [comment]
Yes, Indeed the problem was due to .git somewhere in my directories. 
I can confirm that the solution is what @steveward explained, i.e. nested .git

**Comment by jlangvad** [comment]
I solved this by checking git status in terminal.

**Comment by robbiegod** [comment]
I got this error message too. Here is why.  I had downloaded some files that hadn't changed locally. In github desktop it showed a list of files all marked "no change".  I was trying create a commit because i didn't notice there file change status.  A few minutes later they just disappeared from the list.  Basically, what it boild down too is you need to some file with some changes otherwise you will get this error. Thanks!

**Comment by douglasrcjames** [comment]
I just ran into this error while using the Github Windows 10 desktop app. I was trying to remove folders I meant to gitignore from the repo. I followed the guide below to just use command line and it worked!
(https://github.community/t5/How-to-use-Git-and-GitHub/How-to-delete-multiples-files-in-Github/td-p/4623)

**Comment by jackdolgin** [comment]
I don't know if this will work for others but I found just restarting Github Desktop and quitting out of Atom (where my committed changes were coming from) did the trick!

**Comment by ipkpjersi** [comment]
Since a lot of people seem to have run into this problem because of having multiple nested `.git` directories (myself included), perhaps a warning about checking this should be added to the exit code 1 message?

**Comment by steveward** [comment]
@ipkpjersi thanks for the feedback. Providing better error messaging is definitely something that is always on our minds (see https://github.com/desktop/desktop/pull/7649 for an example). The `exit code 1` error can be thrown in a variety of situations, so we would need to somehow check specific scenarios in order to return a more verbose error message. I'm going to make a note to add this to the [known-issues](https://github.com/desktop/desktop/blob/development/docs/known-issues.md) document for referencing.

**Comment by RickSeta** [comment]
I don't know if this was your case, but i was trying to commit from a cloned repository to a rep that i didn't have permit. Then i forked the rep, commited to it, then i made a pull request and it worked.

**Comment by minhkhai1992** [comment]
I used GitHub Desktop and I got the same yours guys problems. 
my solution that I got "Add local repository" and find a folder where project located and add and submit.

My respective : they don't want folder over another folder . it mean they only want 1 folder and the rest of files will be locate in the folder.

**Comment by zq-Aux** [comment]
If anyone still has this issue and nested .git folders are not the cause, check out [this thread](https://github.com/desktop/desktop/issues/6389) for another possible solution

**Comment by Harris-Logic** [comment]
even in the child folder, i had an unknown .git directory. might been wrong created sometimes.

**Comment by mishz** [comment]
في أربعاء، 1 أبريل، 2020 في 9:12 ص، كتب Harris Logic <
notifications@github.com>:

**Comment by 29er** [comment]
turned out some other git process was 'corrupted' for me . I had to delete a .git/index file and it worked.

**Comment by luquibotbol** [comment]
If you have 2 or more README.md it'll give you an error message

**Comment by Valeka** [comment]
> 
> 
> I got this error message too. Here is why. I had downloaded some files that hadn't changed locally. In github desktop it showed a list of files all marked "no change". I was trying create a commit because i didn't notice there file change status. A few minutes later they just disappeared from the list. Basically, what it boild down too is you need to some file with some changes otherwise you will get this error. Thanks!

The same thing happened to me and I'm not sure how to solve it or should just ignore it. So the same error meesage but there was no duplicated .git folder. When I copy updated files (wordpress plugins updated) and commit changes I received error and later I've found that I already uploaded these files.

**Comment by tierninho** [comment]
@Valeka Thanks for the note. Please submit a [new issue](https://github.com/desktop/desktop/issues/new?template=bug_report.md) if you'd like us to assist you.

**Comment by jesulesvf** [comment]
https://we.tl/t-7OSOidjeEY?src=dnl
