### ISSUE TITLE
Git UserName and Email Don't Always Switch with Checkout

### ISSUE THREAD

**Issue by say25** [desktop/desktop#4453]
## Description
Git UserName and Email Don't Always Switch with Checkout

## Version
* GitHub Desktop: 1.1.2-beta2
* Operating system: Windows 10

## Steps to Reproduce
1. Clone an enterprise repo
2. Clone a regular .Com repo
3. Notice your Git config user.name and user.email dont change

### Expected Behavior
Email and Username change with repos when changing who forks it.

### Actual Behavior
Email and Username does NOT change with repos when changing who forks it.

### Logs
[2018-04-16.desktop.beta.log](https://github.com/desktop/desktop/files/1916793/2018-04-16.desktop.beta.log)

**Comment by steveward** [comment]
Thanks for opening this @say25. This is the expected behavior, since GitHub Desktop picks up the name and email address that are in your local .gitconfig file, and it will not change unless you change it in the .gitconfig or directly in GitHub Desktop. The best workaround I can recommend is to add the same email address to both your GitHub and GitHub Enterprise accounts -- that way your commits will be properly attributed to each account. Let me know if that doesn't make sense!
