### ISSUE TITLE
how to submit a repo?

### ISSUE THREAD

**Issue by arindamiitan** [desktop/desktop#4467]
## Version

* GitHub Desktop:

* Operating system:

**Comment by j-f1** [comment]
Thanks for reaching out!

We require the template to be filled out when submitting all issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway 😀

**Comment by steveward** [comment]
@arindamiitan you can find out help documentation for getting started with GitHub Desktop here:

https://help.github.com/desktop/guides/contributing-to-projects/

There's a section on 'Adding and cloning repositories' -- hopefully that is helpful to you! If you run into any issues please feel free to [contact support](https://github.com/support) directly so we can assist you further.
