### ISSUE TITLE
Cannot clone torvalds/linux

### ISSUE THREAD

**Issue by TheBestPessimist** [desktop/desktop#4473]
## Description
A fresh installation of version 1.1.1 on a fresh windows 10 pro VM.

I am trying to download torvalds/linux and right at the end i get an error.

## Version
* GitHub Desktop: 1.1.1

* Operating system: Windows 10 x64 Pro in a vmware vm

## Steps to Reproduce
Try and clone the repository at https://github.com/torvalds/linux

### Expected Behavior
Repository is cloned successfully and i can see all the files.

### Actual Behavior
An error is shown almost at the end of the process

### Logs
[2018-04-19.desktop.production.log](https://github.com/desktop/desktop/files/1928456/2018-04-19.desktop.production.log)

**Comment by shiftkey** [comment]
@TheBestPessimist thanks for the report. This is a [known Windows limitation](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396#naming_conventions) where repositories with certain file paths :

> Do not use the following reserved names for the name of a file: CON, PRN, AUX, NUL, COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9, LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, and LPT9. Also avoid these names followed immediately by an extension; for example, NUL.txt is not recommended.

This affects the `torvalds/linux` repository because it has files that violate this rule:

```
...
error: unable to create file drivers/gpu/drm/nouveau/nvkm/subdev/i2c/aux.c: No such file or directory
error: unable to create file drivers/gpu/drm/nouveau/nvkm/subdev/i2c/aux.h: No such file or directory
...
error: unable to create file include/soc/arc/aux.h: No such file or directory
```

Unfortunately this isn't something that we can fix in Git, due to the underlying Windows limitation.

**Comment by TheBestPessimist** [comment]
Ah, i did not know about this limitation.

Please excuse me for creating the bug and close it whenever you see fit.
