### ISSUE TITLE
my repositories are not available in github desktop

### ISSUE THREAD

**Issue by manthanchauhan** [desktop/desktop#4488]
## Version

* GitHub Desktop:

* Operating system:

**Comment by shiftkey** [comment]
@manthanchauhan thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by niik** [comment]
Thank you for your issue!

We haven't gotten a response to our questions.
With only the information that is currently in the issue, we don't have enough
information to take action. I'm going to close this but don't hesitate to reach
out if you have or find the answers we need, we'll be happy to reopen the
issue.

**Comment by manthanchauhan** [comment]
My issue was solved by a friend. Thank you for your fast and reliable support. I really appreciate your support team for their wonderful work. Please close the issue.




Get Outlook for Android







On Mon, Apr 30, 2018 at 8:42 PM +0530, "Markus Olsson" <notifications@github.com> wrote:












Thank you for your issue!


We haven't gotten a response to our questions.

With only the information that is currently in the issue, we don't have enough

information to take action. I'm going to close this but don't hesitate to reach

out if you have or find the answers we need, we'll be happy to reopen the

issue.
