### ISSUE TITLE
we were unable to authenticate with github.com. please enter username and password to try again

### ISSUE THREAD

**Issue by tpankaj92** [desktop/desktop#4489]
## Version

* GitHub Desktop:

* Operating system:

**Comment by shiftkey** [comment]
@tpankaj92 thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by jdunham22** [comment]
This looks similar to my issue https://github.com/desktop/desktop/issues/4524

**Comment by Phil-Factor** [comment]
Created a gist, clicked on the 'save to your computer ...blah..GitHub Desktop'. All worked fine. Created a new gist and saved it to a file in Github directory created by the previous operation. saved in local directory. Tried to push to Github. 'Bang'. "We were unable to authenticate with gist.github.com. Please enter your usemame and password to try again." I did, Ir repeated etc etc. stuck in endless loop.

**Comment by Klaus-Valse** [comment]
Anything new here? It's a tiny bit frustrating...

**Comment by steveward** [comment]
@Klaus-Valse could you open a new issue and fill out the template to describe the problem you are having? Thanks!
