### ISSUE TITLE
fatal: unable to access 'https://git.netcom.corp/portal/': schannel: SNI or certificate check failed: SEC_E_WRONG_PRINCIPAL (0x80090322)

### ISSUE THREAD

**Issue by RedRenar** [desktop/desktop#4503]
## Version

* GitHub Desktop:

* Operating system:

**Comment by shiftkey** [comment]
@RedRenar thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by shiftkey** [comment]
Closing this out due to inactivity.

@RedRenar if you're able to fill out the template and provide more details about your setup we're happy to revisit this issue.
