### ISSUE TITLE
hello! You Can Tell Me??

### ISSUE THREAD

**Issue by Yibhvat** [desktop/desktop#4520]
## Version

* GitHub Desktop:

* Operating system:

**Comment by shiftkey** [comment]
@Yibhvat thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by Yibhvat** [comment]
![logo](https://user-images.githubusercontent.com/38113403/39217530-b4994742-47dd-11e8-8cd4-7c56655c977a.png)
