### ISSUE TITLE
Cannot commit

### ISSUE THREAD

**Issue by BestitzanosDimitris** [desktop/desktop#4555]
When I try to commit from the github desktop i get an error that contains "exit code 128"

**Comment by j-f1** [comment]
Thanks for reaching out!

We require the template to be filled out when submitting all issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway 😀

**Comment by shiftkey** [comment]
Closing this out due to inactivity.

@BestitzanosDimitris if you're able to fill out the template and attach a log file we're happy to revisit this.
