### ISSUE TITLE
Big Backupfiles that are part of extractable code sets cannot be uploaded due to network timeout (5GB)

### ISSUE THREAD

**Issue by BenniProbst** [desktop/desktop#4594]
## Version

* GitHub Desktop:

* Operating system:

**Comment by shiftkey** [comment]
@BenniProbst thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by shiftkey** [comment]
Closing this out due to inactivity.

@BenniProbst if you're able to fill out the template to assist with troubleshooting we can revisit it.
