### ISSUE TITLE
Hitting "undo" is a little too easy: a saga of odd merge behavior

### ISSUE THREAD

**Issue by feministy** [desktop/desktop#4596]
## Description

Today a tragedy occurred: I accidentally hit "undo" twice, and one of the commits I inadvertently undid was a master merge. I re-committed right away and pushed up, and imagine my surprise when my PR diff ballooned to include all of the code from master I was supposed to have merged 😭 
 (https://github.com/github/github/pull/89415)

So while the UX could maybe be improved with "maybe we shouldn't undo multiple times, or warn people first", I think there might be a larger issue around undoing a merge of another branch.

## Version

* GitHub Desktop: 1.1.1
* Operating system: Mac OS 10.12.6

## Steps to Reproduce

1. Merge master into an existing branch with commits
2. Make some changes
3. Commit those changes
4. Hit undo (your changes)
5. Hit undo again (your merge)
6. Commit your merge again
7. Push up and BE SAD

### Expected Behavior

I expected the merge to be performed as usual without attaching all that code to my PR.

### Actual Behavior

EXTREME SADNESS

It wasn't actually a merge as I would have expected 😬 - all the commits appeared in the diff.

## Additional Information

PR linked above, you can see it internally 👀 

### Logs

Attached!

[2018-05-03.desktop.production.log](https://github.com/desktop/desktop/files/1972685/2018-05-03.desktop.production.log)

**Comment by shiftkey** [comment]
xref another issue when clicking undo multiple times #3717

**Comment by shiftkey** [comment]
@feministy I'm not sure how familiar you are with the under-the-hood behaviour here, but I'll brain dump anyway for anyone else who is curious.

What happens when we undo a commit is that the work in the previous commit contents are left in your working directory, and the commit details are added to the commit form, so you can amend things and try again. We see it as a more safe version of "amend commit" because it lets you revisit the files you included in the commit, and we only let you undo commits that haven't been published.

Undoing multiple local commits is the equivalent to squashing together multiple commits, but then letting the user tweak things as if they were making a normal commit. The fact that your work was combined into the previous merge commit as part of the second "undo" is the root of the problem here. 

I think the app should jump in here and warn you about the impending Bad Life Choices™ when these two criteria are satisfied:

 - the user attempts to undo a merge commit (that is, you previously pulled other work into your branch)
 - you have existing working directory changes that will get smooshed into the undone merge commit, which doesn't even make sense

@feministy is warning and blocking you from continuing enough in this case? I think the goal here is to catch you and let you deal with the working directory changes without introducing the merge commit contents too, but there might also be some other ideas here (for example, remove the merge rather than add it to the working directory) but I want to avoid shaving unnecessary yaks here.

**Comment by feministy** [comment]
>I think the app should jump in here and warn you about the impending Bad Life Choices™ when these two criteria are satisfied:
>
>- the user attempts to undo a merge commit (that is, you previously pulled other work into your branch)
>- you have existing working directory changes that will get smooshed into the undone merge commit, which doesn't even make sense
>
>@feministy is warning and blocking you from continuing enough in this case? 

Yes! That would be super helpful for me! I had no idea I was making poor choices 😂 😭 🙈

**Comment by NickCraver** [comment]
As rare as hitting undo is, and the ease of clicking it next to "Commit to...", I **really** think it should have a confirmation prompt.

For example, today I was editing the markdown engine we use, methodically committing individual changes and documenting them in commits one at a time. Clicking undo (accidentally) suddenly "merged" the last commit changes with current. I lost my pending commit message and had to go line by line selecting changes to re-create the last commit. An action meant to save time cost a ton of it instead.

Can we please add a confirmation of some sort to the undo button?

**Comment by j-f1** [comment]
Perhaps it should change into “**Confirm**” and “Cancel” buttons when clicked?

**Comment by shiftkey** [comment]
Another side effect of #6075 is that it can interfere with any subsequent merge. I suggested a couple of ways that undoing the merge and leaving it in the working directory might be problematic:

> What I think we should be doing here - when you undo a merge commit in the app - is to ask the user whether they want to keep the changes in the working directory. This workflow has never felt great for me, for a few reasons:
>
> - leaving the results of the merge in the working directory feels confusing to the end user - we should encourage the user to start the merge again
> - when we undo the commit we don't restore the state of the merge, so if the user tries to commit again they'll have a plain commit rather than the merge itself

**Comment by aateeque** [comment]
I'd like to echo sentiments here already around the ease of the "undo" button...in my case I tab from Summary to Description to Commit & Enter on the keyboard. You hit tab one extra time and you end up "Undoing" the commit rather than commiting. This is a UI enhancement maybe solved by a prompt or moving the undo button elsewhere in the UI or from the tab group?
