### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by Steven005** [desktop/desktop#4603]
I'm receiving an unknown error every time I open the app.  Attached is a screenshot of the issue.  Please let me know how to fix, thanks

![image](https://user-images.githubusercontent.com/35708593/39626290-e6ad2fc4-4f66-11e8-9ef6-7bc487117d70.png)
![unknown error](https://user-images.githubusercontent.com/35708593/39626317-ffc61bf6-4f66-11e8-9501-531bc07230aa.JPG)

**Comment by steveward** [comment]
Thanks for reaching out @Steven005!

We require the template to be filled out with all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway. 😀

**Comment by shiftkey** [comment]
Closing this out due to inactivity.

@Steven005 if you're able to fill out the template and share the log files from in the **Help** | **Show Logs in Explorer** menu items to assist with troubleshooting we're happy to revisit it.
