### ISSUE TITLE
Please remove minimum width & height restrictions

### ISSUE THREAD

**Issue by vmbrasseur** [desktop/desktop#4605]
## Description

The new desktop app enforces minimum width and height dimensions for the app, whereas the classic version did not. The new version now takes up too much space on my 2017 MBP screen, which was not a problem with the classic version.

Please remove these arbitrary width and height restrictions and allow users to control their own desktop environment again.

## Version

* GitHub Desktop: v1.1.1

* Operating system: macOS v10.13.4

## Steps to Reproduce

Open the app. Try to resize it smaller. Be prevented at a certain point.

### Expected Behavior

Be able to resize the window to suit my needs.

### Actual Behavior

Blocked from resizing due to arbitrarily imposed restrictions.

**Comment by niik** [comment]
Hi @vmbrasseur, thanks for opening this.

This issue is captured in https://github.com/desktop/desktop/issues/1702 and there's a bit of an explanation about the constraints we've chosen in https://github.com/desktop/desktop/issues/1702#issuecomment-312952005 so I'm going to close this issue in favor of that. It'd be helpful if you could add a comment in that issue about what dimensions you would like the Desktop window to be able to function at.
