### ISSUE TITLE
publish

### ISSUE THREAD

**Issue by absou4000121** [desktop/desktop#4609]
## Version

* GitHub Desktop:

* Operating system:

**Comment by shiftkey** [comment]
@absou4000121 Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by shiftkey** [comment]
Closing this out as inactive.

@absou4000121 if you're able to fill out the template we're happy to revisit this.
