### ISSUE TITLE
GitHub Cloning Repository

### ISSUE THREAD

**Issue by DreyMisfit-Inc** [desktop/desktop#4633]
Cloning reaches around 10% then suddenly spits out an error "The remote is disconnected". My internet connection is fine and I can browse around but every attempt at cloning a repository fails like this, please help.

**Comment by shiftkey** [comment]
@DreyMisfit-Inc Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Could you also attach the full log files? The **Help** | **Show Logs in Explorer** menu items should open the logs folder, and inside those are the log files generated by day. This will provide some more information to help troubleshoot.

Thanks for understanding and meeting us half way 😀

**Comment by shiftkey** [comment]
Closing this out due to inactivity.

@DreyMisfit-Inc if you're able to fill out the template we're happy to revisit this.
