### ISSUE TITLE
Add support for WSL Bash on Windows 10

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#4641]
**Is your feature request related to a problem? Please describe.**
Windows Subsystem for Linux has available `bash` environment that's available as an optional extra in recent versions of Windows 10.

<img width="499" alt="screen shot 2018-05-09 at 2 08 05 pm" src="https://user-images.githubusercontent.com/359239/39795279-7515d066-5392-11e8-9bf8-39d9ede47f90.png">

It would be nice to light this up as an option in Desktop and let users choose this shell.

**Describe the solution you'd like**
The checks that Desktop need to perform should be added into [`app/src/lib/shells/win32.ts`](https://github.com/desktop/desktop/blob/master/app/src/lib/shells/win32.ts) and we have [documentation](https://github.com/desktop/desktop/blob/master/docs/technical/shell-integration.md) outlining how to add support for additional shells.

The high-level steps for looking this up are basically:

 - are you on Windows 10? If not, return `false`
 - Have you enabled WSL? This seems to be the magic registry key `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Component Based Servicing\Notifications\OptionalFeatures\Microsoft-Windows-Subsystem-Linux` and it contains these values:

<img width="1079" src="https://user-images.githubusercontent.com/359239/39795138-7d0e3598-5391-11e8-8afc-765d27a21660.png">

If not found inthe registry, return `false`

 - Lastly, does `C:\Windows\System32\bash.exe` exist on disk. That seems to be enough for an entry point but it'd also be nice to be able to detect that you have a Linux distro installed (otherwise you would see a prompt to visit the store and install, which is fine). 

We need to ensure that it launches in the user's repository, and I think we can lean on `cwd` like this:

```
return spawn(pathToBashExe, [ ], {
  shell: true,
  cwd: path,
})
```

**EDIT:** @JordanMussi added some extra context from their setup below - feel free to use that alongside the above rules.

**Teachability, Documentation, Adoption, Migration Strategy**

This should all just work, but I'm not sure on the right label for this shell to prevent it from being confused with Git Bash. In the start menu you search on the Linux distro you have, which means support for multiple distros is possible - maybe that's a stretch goal for this?

<img width="401" src="https://user-images.githubusercontent.com/359239/39795444-907eed82-5393-11e8-9703-f5863242cfde.png">

**Comment by JordanMussi** [comment]
> Lastly, does C:\Windows\System32\bash.exe exist on disk. That seems to be enough for an entry point but it'd also be nice to be able to detect that you have a Linux distro installed (otherwise you would see a prompt to visit the store and install, which is fine).

There is also `C:\Windows\System32\wsl.exe` which is my preferred entry over `bash` since it respects using a shell other than `/bin/bash` (see more below). I prefer executing the command within Hyper rather than using the terminal window the `exe`s launch themselves. Supporting this would add unnecessary complexity and it isn't much effort to choose the desired terminal as the shell to launch in GitHub and then launch the shell manually from there.

> In the start menu you search on the Linux distro you have, which means support for multiple distros is possible - maybe that's a stretch goal for this?

It [looks like]((https://docs.microsoft.com/en-us/windows/wsl/wsl-config#managing-multiple-linux-distributions)) using the name of the distro as a command launches the correct shell. 

`wslconfig /list` can be used to find which distros are installed (once the app knows WSL is installed).

![4641-wslconfig](https://user-images.githubusercontent.com/2552068/39832438-1233dbc8-53bf-11e8-93eb-c27b48fe090e.png)

As you can see above, I only have Ubuntu installed, I've just tested using `ubuntu` and it is slightly different to `wsl` and bash. Note that the increased time for `wsl`/`ubuntu` is due to launching ZSH.
- `bash` and `wsl` launch with a pwd of the path launched from but `ubuntu` does not (I tried [this advice](https://superuser.com/a/396430) using the `start` command but `ubuntu` still launches to `~`). This limitation is actually mentioned on the linked documentation page:
  > The disadvantage of running a distribution from the command line in this way is that it will automatically change your working directory from the current directory to the distribution's home directory.
- `wsl` and `ubuntu` respect the default shell chosen with `chsh` but `bash` launches `/bin/bash`

![4641-shells](https://user-images.githubusercontent.com/2552068/39832133-524456ee-53be-11e8-9ca5-cb003a8b1e72.gif)

Running `where ubuntu.exe` in `cmd.exe` gives me the path `C:\Users\Jordan\AppData\Local\Microsoft\WindowsApps\ubuntu.exe` so I presume the other distributions' launchers will land there too. However I'm not sure how reliably the executable name can be determined from the `wslconfig /list` command since there [doesn't seem to be a strict naming scheme](https://github.com/Microsoft/WSL-DistroLauncher#contents). Sure you can assume it's the name given but lower case, except this might not be true for future distributions.

**Comment by shiftkey** [comment]
@JordanMussi thanks for that extra context!

**Comment by minvedacat** [comment]
@shiftkey Does this issue and #4657 actually enable us to start github client from WSL directly?
Currently when execue in WSL(and WSL inside Hyper) fails:
```
min@MMM:/mnt/d/joe5y$ github
sh: 0: Can't open /mnt/d/joe5y/AppData/Local/GitHubDesktop/bin/..\app-1.2.3\resources\app\static\github.sh
min@MMM:/mnt/d/joe5y$
```

**Comment by shiftkey** [comment]
@minvedacat that's a separate issue to this (please open an issue so we're tracking it).

[This is the script](https://github.com/desktop/desktop/blob/master/app/static/win32/github.sh), but I didn't test it from WSL at the time I was working on it. It works from Git Bash, so I'd love to get to the bottom of what's different between the two as that error doesn't make sense to me at first glance.

**Comment by dlloyd123** [comment]
Hi @shiftkey 

I have had a go at this locally as a bit of fun, and now have a local working copy of this which supports WSL Bash, and all the distro variants (ubuntu, kali, opensuse42, sles-12, debian) being supported. Some re-work might be needed on 'parse' method in 'shells/win32.ts' as at the moment I have added an extra enum for each distro to keep it simple, and wsl bash too, in the Shell enum declared in that file. I was thinking of allowing this to be a bit more dynamic for future distro variants, so a generic WSL enum value and some method to do further parsing/name checks for labels in the UI other than the parse method declared there. 

I have added a few checks for making sure its Win10 (via registry), that WSL is installed (via registry), and calling the wslconfig.exe /list via command line and parsing the results as best I could (its a double byte char set return string from what I debugged/saw). I have made an assumption that each distro is installed to: C:\Users\<user>\AppData\Local\Microsoft\WindowsApps\ as noted by another comment above, so it may need to alter this to be a bit more dynamic if this moves etc.

I havent looked at unit tests yet, so might have a delve into this if you wish to make sure this is covered before submitting a PR/branch. I am working on/off some evenings after work where I can so it might take a few days if alterations or changes are needed.

**Comment by jayschwa** [comment]
#6420 is waiting for review. cc @shiftkey

**Comment by ADustyOldMuffin** [comment]
@shiftkey I'd be interested in taking this over since it seems to be almost done and in need of a owner.

**Comment by tierninho** [comment]
@ADustyOldMuffin Go for it! ✨
