### ISSUE TITLE
win10 desktop APP blackout 

### ISSUE THREAD

**Issue by tonya090** [desktop/desktop#4643]
I installed Github APP on my desktop, the app works after the installation but every time I tryed to open it again, it only shows a black screen. I can close it on the close icon place but it just shows nothing

**Comment by shiftkey** [comment]
@tonya090 thanks for the report!

Are you working on a laptop? We've had some reports of some graphics cards causing issues with Desktop due to the lack of hardware acceleration, and we have a [workaround](https://github.com/desktop/desktop/blob/master/docs/known-issues.md#i-get-a-black-screen-when-launching-desktop) that might help you get back to a happy place.

**Comment by tonya090** [comment]
@shiftkey thank you so much about the response. It works! Have a nice day!
