### ISSUE TITLE
WONT LET ME ACCESS

### ISSUE THREAD

**Issue by hgytduh** [desktop/desktop#4665]
## Description

it wont let me update my github reporistory

## Version

* GitHub Desktop:

* Operating system:

**Comment by steveward** [comment]
Thanks for reaching out @hgytduh!

We require the template to be filled out with all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway. 😀

**Comment by shiftkey** [comment]
Closing this out due to inactivity.

@hgytduh if you're able to fill out the template and help us to reproduce the issue we're happy to revisit it.
