### ISSUE TITLE
Any chance Desktop could affect git-svn?

### ISSUE THREAD

**Issue by vmbrasseur** [desktop/desktop#4682]
## Description

For the past year I've used exactly the same git-svn process to work with a simple, unbranched, untagged repository (a repo I don't control).

The day after I upgraded Desktop to the latest version, that git-svn process stopped working. There were no other changes to my entire system. I installed no other apps, upgraded no other software, made no changes to the process. There were no changes in how the repo is operated at the SVN side of things.

Considering I upgraded Desktop from a much earlier version (sorry, I don't have that version number handy as it's gone with the wind now), I have to wonder whether Desktop includes some backend git components that may be changing how git-svn operates?

## Version

* GitHub Desktop: v1.1.1

* Operating system: macOS v10.13.4

## Steps to Reproduce

I have no clue.

### Expected Behavior

git-svn not be affected by Desktop

### Actual Behavior

git-svn is affected by Desktop…?

**Comment by shiftkey** [comment]
@vmbrasseur thanks for the feedback!

> The day after I upgraded Desktop to the latest version, that git-svn process stopped working. 

Could you elaborate on how you are using Git SVN? Is this the `git svn [command]` command line usage, or something else? And I gather you have SVN remotes enabled in the repository?

>  I have to wonder whether Desktop includes some backend git components that may be changing how git-svn operates?

I don't believe we ship `git-svn` inside Desktop, which might be the cause of the problem here. Could you check for any log files under **Help** | **Show Logs in Finder** that might contain helpful errors?

**Comment by iAmWillShepherd** [comment]
> I was finally able to resolve the issue by deleting my local repo as well as the Github repo...

@vmbrasseur, I'm glad you were able to find a solution to this. If you have any other issues, don't hesitate to open another. I'm going to close out this issue since you've resolved it.
