### ISSUE TITLE
Via configuration, allow 'pull -r' rather than 'pull'

### ISSUE THREAD

**Issue by timor-raiman** [desktop/desktop#4711]
This is a simpler case of #1652 - 'rebase'. (and #4456).
This is a concrete suggestion to implement #3422 via global or per-repository configuration.

Rather than a generic rebase, which is a complicated flow to implement in GUI elements, it would be of great use to our team if it were possible to specify globally or per-repository that all 'pull' operations should rather be 'pull -r'.

This would remove 90% of unintended merge commits.

**Comment by iAmWillShepherd** [comment]
Thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md). I added the `future-proposal` label to this issue and closed it so that we won't get overwhelmed with our backlog! 

We will revisit this in our next planning session.

**Comment by iAmWillShepherd** [comment]
@timor-raiman , although you're asking for something a bit different than #3422, your issue is similar enough to be a part of that issue. I'm going to post your comment in #3422 for more 👀 . Please use that issue going forward if you have any additional details you'd like to add.

**Comment by billygriffin** [comment]
Removing the label because we're using the linked issue above to track.
