### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by jasmohan** [desktop/desktop#4732]
## Description

fatal: This operation must be run in a work tree

-- as soon as i install git on my PC, I immediately receive the above stated error

## Version

* GitHub Desktop:

* Operating system:

**Comment by iAmWillShepherd** [comment]
Thanks for reaching out!

We require the template to be filled out with all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway 😀

**Comment by peteros77** [comment]
Thanks for your help and support and I think you all are the best people ever

**Comment by shiftkey** [comment]
Closing this out as inactive. @jasmohan if youre able to fill out the template we're happy to revisit the issue.
