### ISSUE TITLE
Cannot clone repository - SSL Cerficate Problem

### ISSUE THREAD

**Issue by ghost** [desktop/desktop#4738]
## Description

When trying to clone a repository of a group project I am working on, I keep getting the error:

SSL certificate problem: self signed certificate in certificate chain

I have Googled this issue and cannot find a solution. A couple of weeks ago, I was able to clone without a problem.

## Version

* GitHub Desktop:

* Operating system:

**Comment by shiftkey** [comment]
@KylaPrograms are you able to fill out [the issue template](https://github.com/desktop/desktop/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) and provide more details about your setup and the remote repository you're trying to clone down?

**Comment by steveward** [comment]
Thanks for filling that out @FaintingHope. Are you possibly running any antivirus software (i.e. Kaspersky, NOD32) on your machine? We have seen cases where certain antivirus software can perform SSL filtering and cause issues like this.

**Comment by FaintingHope** [comment]
@steveward 

I do have Kaspersky (Total Security) and have had it installed since Day 1 of this PC's lifespan. I have been able to operate GitHub Desktop since installation on June 29, 2017 without issue and without needing to add GitHub Desktop to the exclusion list. Additionally, I have not received any installation updates or changes in the past few days that would have impacted the antivirus software's configuration.

I feel it is important to note that I when I went to recreate the issue today (with the intention of making sure the error still occurs before I added GitHub Desktop to Kaspersky's exclusion list to test if there was a difference), I am now able to clone and pull repositories without issue.

The only other action I have taken since the reported failure was to restore to Windows 10 version 1709 (due to what appears to be an audio defect).

I know that I was previously able to successfully use GitHub Desktop in version 1709. I also know that I was never able to successfully use the application in version 1803. I cannot recall if I experienced the issue originally in version 1709 and then updated to 1803 as part of my personal troubleshooting to resolve the error, or if that might have been an unexpected coincidence.

I will follow-up if I begin to experience this issue again. I'm sorry I am no longer able to recreate it.

**Comment by steveward** [comment]
@FaintingHope I'm glad to hear things are working for you now. There have been a few other users who have run into this issue with Kaspersky, so my guess is that they may have pushed out an update that caused this SSL error to appear in GitHub Desktop. Let us know if you have any further issues!

**Comment by githubhermit** [comment]
@steveward Hi, I was looking into the same issue and found this thread. Is there going to be any update coming out soon to compensate the issue of not cloning?

**Comment by shiftkey** [comment]
> Is there going to be any update coming out soon to compensate the issue of not cloning?

@githubhermit You'd have to get in touch with Kaspersky Support, but this suggestion from [this comment](https://github.community/t5/How-to-use-Git-and-GitHub/Getting-quot-SSL-certificate-problem-self-signed-certificate-in/m-p/7954#M2732) might help resolve your issue:

> Turning off Web Anti-Virus in Kaspersky did the trick.

**Comment by patieru12** [comment]
Fixed by Turning OFF Kaspersky temporary.

**Comment by githubhermit** [comment]
Kaspersky blocks SSL 2.0, so if Medusa uses SSL 2.0, it won't work. Medusa also doesn't scan for update or episodes if Encrypted Connection Scan is active.

**Comment by steveward** [comment]
@githubhermit it looks like you may be referring to https://github.com/pymedusa/Medusa. If you are having issues with that project I would recommend opening an issue directly in their issue tracker. If you are still having any issues with GitHub Desktop, please let me know.
