### ISSUE TITLE
Github Desktop and Default text editors + EmEditor

### ISSUE THREAD

**Issue by killerwife** [desktop/desktop#4753]
Currently github desktop only supports selective text editors on windows. It does not respect two following key settings:
1. using default text editor as setup in windows for given file type
2. using default text editor set in git config

I have both of these set to EmEditor, the old Github desktop client is capable of using them properly, but the new one does not even give the option to change this. Using notepad is insanity when doing cross platform development, and installing an additional editor just because the client does not support setting it in some sane way is no good either.

Reason for using EmEditor: we use extremely huge files and as a result, most of not all software is incapable of handling it well. (talking about 1GB + files here)

I have not seen an EmEditor thread around here yet.

**Comment by killerwife** [comment]
Absolutely. When I associate a given editor with .cpp or .h or .py, I would expect the Github Desktop app to use that associated program. Just to clarify on windows 10 its the menu called "Choose default apps by file type".

**Comment by steveward** [comment]
> When I associate a given editor with .cpp or .h or .py, I would expect the Github Desktop app to use that associated program

GitHub Desktop should respect that default program when you right-click on a file in the `Changes` view and select `Open with default program`. Let me know if I'm misunderstanding what you are wanting to do here.

**Comment by killerwife** [comment]
Yes. When I used https://imgur.com/a/W2n3mAB "Open with default program", notepad was used. When I used "show in explorer" and doubleclicked the file, EmEditor was used.

**Comment by shiftkey** [comment]
There's some extra context here about the differences between the classic Windows app and the new Electron app, and it requires some understanding of how Windows handles opening files.

Windows app all end up funnelling through [`ShellExecute`](https://msdn.microsoft.com/en-us/library/windows/desktop/bb776886(v=vs.85).aspx) to ask the OS how to handle a given file. Electron too has support for opening a file in the user's preferred program - [`shell.openItem(fullPath)`](https://electronjs.org/docs/api/shell#shellopenitemfullpath) and [`openExternal(url)`](https://electronjs.org/docs/api/shell#shellopenexternalurl-options-callback).

How [`openExternal` works on Windows](https://github.com/electron/electron/blob/eb63bea87c299b3c440d6a36ccced3cc9653e1c4/atom/common/platform_util_win.cc#L302-L317) is important:

```c
  if (reinterpret_cast<ULONG_PTR>(ShellExecuteW(NULL, L"open",
                                                escaped_url.c_str(), NULL, NULL,
                                                SW_SHOWNORMAL)) <= 32) {
    // We fail to execute the call. We could display a message to the user.
    // TODO(nsylvain): we should also add a dialog to warn on errors. See
    // bug 1136923.
    return false;
  }
```

Notice that ` L"open",`? This is where the first problem comes in: Windows expects a `verb` to `ShellExecute` to hint at what the user wants to do with the file, and Electron currently hard-codes `open`.

So while `EmEditor` does declare itself as an _editor_ for text files, Electron is only leveraging programs that support _opening_ a given extension. That's the core of the differences between Classic Desktop and Desktop Electron, and why that menu item is currently labelled **Open in default program** and not **Edit in default program**.

Putting that aside, I tested out installing EmEditor and Desktop and associating it with opening a file extension (in this case `.md`). On first usage I got this prompt, which makes sense:

<img width="429" src="https://user-images.githubusercontent.com/359239/40592812-7c33e5ac-6262-11e8-990e-573fbeda0075.png">

So I chose EmEditor and it opened fine. Second time through, I hit this error:

<img width="644" src="https://user-images.githubusercontent.com/359239/40592819-895805ce-6262-11e8-83d4-ec983e8a9d91.png">

This is our generic error handler when Electron raises an error inside [`open-file.ts`](https://github.com/desktop/desktop/blob/2d2feff2aa0a1535c6706a2b7766c01e41a4210c/app/src/lib/open-file.ts):

https://github.com/desktop/desktop/blob/2d2feff2aa0a1535c6706a2b7766c01e41a4210c/app/src/lib/open-file.ts#L11-L15

That probably needs to be investigated here.

> It does not respect two following key settings:
>
> ...
> 2. using default text editor set in git config

I believe this was working because we set `core.editor` to `gitpad` in your config - [`GitPad`](https://github.com/github/gitpad) being a tool that we bundled in Git Shell. We don't have plans to bring Git Shell across to Desktop Electron.

**Comment by zekrom-vale** [comment]
It is annoying that "Open in external editor" is not hidden if there is no external editor, cluttering up the context menu.  I would think this is easy to check and hide.

**Comment by shiftkey** [comment]
@killerwife in reference to this feature that is no longer set by Desktop Electron:

> using default text editor set in git config

In Desktop Classic on Windows we set `core.editor=gitpad` which would launch the default program for editing text files. A while ago the Git for Windows project added the ability to choose the editor from a list of installed tools at install time:

<img width="519" src="https://user-images.githubusercontent.com/359239/44156291-f701f178-a085-11e8-8870-de127ca622cd.png">

This is great for discoverability, but all it does under the hood is set `core.editor` to the program and provide the necessary arguments to launch the program and detect when it was closed.

Here's what it adds to my test machine's system config for Notepad++:

```
[core]
	editor = 'C:\\Program Files\\Notepad++\\notepad++.exe' -multiInst -notabbar -nosession -noPlugin
```

Desktop isn't really concerned about this flow in the UI (commits are done in the app, rather than launching the editor) so I'm not sure when we'll get to this.

For the moment I'd see if you can add an entry like this to your `~/.gitconfig` to address this gap from the old app:

```
[core]
	editor = 'C:\\Users\[account]\\AppData\\Local\\Programs\\EmEditor\\EmEditor.exe' 
```

I'm not sure if there are any other arguments to add on the end, based on [the options available](http://www.emeditor.org/en/howto_file_file_commandline.html).

**Comment by shiftkey** [comment]
> 1. using default text editor as setup in windows for given file type
> 2. using default text editor set in git config

After discussion in #5406 about `1.` I've extracted the current details about Desktop's limitations to #5411, and I believe `2.` should be covered by a config change, so I'm going to close this out because I don't think there's anything more I can do to support EmEditor currently.

**Comment by KirkH420** [comment]
[Notepad++] Amount of files is too large to open.
2535 files are about to be opened.
Are you sure to open them?

....that's just silly.
