### ISSUE TITLE
dont let me up a web page

### ISSUE THREAD

**Issue by ElvisTheKing10** [desktop/desktop#4773]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I have an issue when [...]

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Add any considered drawbacks.

**Describe alternatives you've considered**

**Teachability, Documentation, Adoption, Migration Strategy**
If you can, explain how users will be able to use this. This will help the core team understand how the feature would work, and assist with future work like documentation.
Screenshots or mockups here are a great help!

**Comment by shiftkey** [comment]
@ElvisTheKing10 thanks for reaching out!

We require the template to be filled out on all new feature requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by shiftkey** [comment]
Closing this out as inactive. @ElvisTheKing10 if you're able to fill out the template to help us understand the situation we can revisit this.
