### ISSUE TITLE
Add support for launching Emacs.app as "Open in External Editor" entry

### ISSUE THREAD

**Issue by osculabo-carnifex** [desktop/desktop#4785]
**Is your feature request related to a problem? Please describe.**
Emacs.app is not picked up as an external editor

**Describe the solution you'd like**
Set arbitrary app as editor and pass it files as arguments

**Describe alternatives you've considered**
Painstakingly list every editor in existence or gently remind people to switch to Atom

**Teachability, Documentation, Adoption, Migration Strategy**
Use the current heuristic to list known editors, have a button to select the application/path to application outright below it.

**Comment by MagicMarvMan** [comment]
Hello. I would like to take this issue. :+1: 
I will open a PR when I'm done.

@shiftkey 

Thank you,
Kind regards, 
MagicMarvMan

**Comment by MagicMarvMan** [comment]
Hmm... I am trying to solve it, but it isn't detecting Emacs as an editor. An additionally the editor style looks really weird:
![Screenshot](https://user-images.githubusercontent.com/24806960/41856818-4e8fbafa-7896-11e8-89a1-baa75826e7e8.png)
Do you have an idea, @shiftkey ?
Thank you.

**Comment by iAmWillShepherd** [comment]
@MagicMarvMan, thanks for picking this issue up. Would you mind @-mentioning me or `@desktop/eng` when you create your PR?

**Comment by Rexogamer** [comment]
It’s been a year; I’ll take this up

**Comment by billygriffin** [comment]
Since this has sat for so long without any additional demand or interest in working on it, I'm going to close this. We're definitely open to supporting additional external editors but for anything outside the largest ones, we rely on the community to build those integrations. If you're interested in doing this work and know how to implement it, please let us know and we can reopen. Thanks for the issue!

**Comment by lcolen** [comment]
I'm setting up an environment for developing code on Linux (Ubuntu 20.04), am using emacs as my editor and currently using Eclipse as my IDE.  github desktop only gives me choices of Atom (a discontinued product), Visual Studio Code and Gnome text editor.  
Emacs has been one of the two "standard" *nix editors since not only before github, but probably since most of the people working on github desktop were born.  The basic emacs editing commands are standard in the shells that come with both Linux and Mac.  
It really needs to be added as a default editor.

**Comment by fchenunsw** [comment]
If this happens, it'll be great!
