### ISSUE TITLE
How about adding marks that show if the friends saw my messages or not?

### ISSUE THREAD

**Issue by jji1902** [desktop/desktop#4786]
Hi, I'm studying a open source.(Amature)
((I want to contribute 'qtox' a little bit.))
1. How about adding marks that show if the friends saw my messages or not?><...
It will be convenient!!
2. And How about making color changing?
I like pink. Please make many colors~

They can be ridiculous, but it's my small ideas!! Thank you!!:0

**Comment by agisilaos** [comment]
@jji1902 thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by niik** [comment]
Hey @jji1902, this is the repository for the open source project GitHub Desktop. It looks like you are talking about some other project so I'm going to close this one out. Please open an issue in the specific project's repository instead.
