### ISSUE TITLE
 语言支持 (Edit: Support multi language)

### ISSUE THREAD

**Issue by AiJiangnan** [desktop/desktop#4787]
支持语言的切换，例如：简体中文，English

**Comment by steveward** [comment]
Thanks for reaching out!

We require the template to be filled out with all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway. 😀

**Comment by ChuckIsReady** [comment]
Put out language documents, which can be translated with the help of the community.
