### ISSUE TITLE
Discarding wrong items

### ISSUE THREAD

**Issue by IanKeen** [desktop/desktop#4788]
## Description

Right clicking and choosing to 'discard changes' works as expected, however it seems selection jumps to the first item in the list and a subsequent right click and choosing 'discard changes' appears to be choosing the right row _visually_... but it actually discards the first time in the list

## Version

* GitHub Desktop: 1.2.0

* Operating system: 10.13.4 (17E199)

## Steps to Reproduce

1. have a repo with unstaged changes
2. right click on something down the list
3. choose 'discard changes'
4. without clicking anywhere else first, right click on something else down the list
5. choose 'discard changes' 

### Expected Behavior

I expect the second thing I right clicked on to be discarded 

### Actual Behavior

The first item in the list is discarded

### Logs

[2018-05-25.desktop.production.log](https://github.com/desktop/desktop/files/2040376/2018-05-25.desktop.production.log)

**Comment by steveward** [comment]
Good catch @IanKeen! I was able to reproduce this as well, so I'm going to mark this as a 🐛 .

**Comment by DanTup** [comment]
I wonder if this is [what I've been seeing](https://twitter.com/DanTup/status/1016598879389745153). On several occasions the wrong files have been discarded, but I could never repro.

Luckily the changes go to Trash, but unlike on Windows it seems on a Mac I have to then manually navigate to the specific folder and drag them back, which is a bit tedious.

**Comment by DanTup** [comment]
Ok I just saw my issue again; though I'm not sure if it's exactly what's reported above. Basically, if you right-click on any file that is not selected, then click Discard, the prompt has the previously-selected file in it (like the context menu decides which item is selected *before* the selection moves to the item under the mouse on the click).

The file shown in the discard prompt is, as far as I can tell, accurate to what gets discarded. So the danger is if you don't read the filename in the prompt rather than it just deleting a different file.

**Comment by billygriffin** [comment]
Confirmed @DanTup's feedback that it's the previously selected file that is the one shown in the prompt. Thanks for clarifying!
