### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by BlackGameStudioTM** [desktop/desktop#4790]
fatal: unable to access 'https://github.com/BlackGameStudioTM/hello-world.git/': schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - ������� ������ �� ������ ���������� �������� ������ ��� �����������.

**Comment by shiftkey** [comment]
@BlackGameStudioTM please have a look at our [known issue](https://github.com/desktop/desktop/blob/master/docs/known-issues.md#certificate-revocation-check-fails---3326) about `InitializeSecurityContext` - some network products can interfere with certificate revocation, and there's a workaround to revert to using OpenSSL rather than the Windows SChannel APIs.

**Comment by shiftkey** [comment]
I'm going to close this out as this is related to a known issue with a documented workaround.
