### ISSUE TITLE
Setup custom url for issue numbers

### ISSUE THREAD

**Issue by YvesR** [desktop/desktop#4816]
**Is your feature request related to a problem? Please describe.**
We use github.com as a team, but do have our own issue system.
When we enter a issue number like #12345 a click in GitHub desktop try to open https://github.com/company/repo/issues/12345.
As we do not track our issues there, it does not work for us.

**Describe the solution you'd like**
Id like to have a preferences settings where I can enter a custom url for this link.
Preferences already have a Advanced tab, so it would be nice to edit a custom url here, that is used instead.

Example `https://my-issue-tracking.com/id/` as url would create a link `https://my-issue-tracking.com/id/12345` in the title of the history.

**Teachability, Documentation, Adoption, Migration Strategy**

- Field is empty: Default behavior.
- Field is filled: Custom url used. Die issue id is added to this url.

![github-desktop](https://user-images.githubusercontent.com/4928882/40716135-3d81aa72-6408-11e8-997d-7ebeecb53a11.png)

**Comment by shiftkey** [comment]
@YvesR thanks for the suggestion. 

This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md). At this point we haven't really thought much about introducing flexibility around these sorts of setups, but awareness of these definitely helps.

I added the `future-proposal` label to this issue and closed it so that we won't get overwhelmed with our backlog! We will revisit this in our next planning session.

**Comment by billygriffin** [comment]
Hi @YvesR, thanks so much for your suggestion. We haven't heard your use case as very widely used for Desktop users so we're going to remove the `future-proposal` label to indicate that we don't intend to support this at this time. However, this issue will still continue to exist and if we hear from more users that differentiation of different issue tracking systems would be useful for them in Desktop, we're always open to revisiting. Thanks again!
