### ISSUE TITLE
Self Signed Certificate Chain Error - Reversion

### ISSUE THREAD

**Issue by Reahreic** [desktop/desktop#4821]
## Description

After desktops auto update this morning i can no loner push, pull or clone via my companies enterprise GitHub server. The below error is thrown

Fatal: unable to access 'https://github.mycompany.com/myname/myrepo.git/': SSL certificate problem: self signed certificate in certificate chain.

Changing the http.sslBackend as recommended in an earlier appearance of this issue (https://github.com/desktop/desktop/issues/2514) between "schannel" and "openssl" changes the error message slightly, but still has the same problem.
schannel: CertGetCertificateChain trust error CERT_TRUST_IS_UNTRUSTED_ROOT

## Version

* GitHub Desktop: 1.2.1

* Operating system: Windows 10

## Steps to Reproduce
1. GitHub Enterprise on a closed intranet system.
2. Update to V1.2.1
3. Perform Push, Get, or clone

### Expected Behavior

Desktop operates as usual

### Actual Behavior

Fatal error 'SSL certificate problem: self signed certificate in certificate chain' for openssl and 'CertGetCertificateChain trust error CERT_TRUST_IS_UNTRUSTED_ROOT' for schannel

## Additional Information

This self signed cert issue also exists under command line git with the common googl-able workarounds being hit and miss.
https://stackoverflow.com/questions/11621768/how-can-i-make-git-accept-a-self-signed-certificate
https://stackoverflow.com/questions/39004750/how-to-solve-ssl-certificate-self-signed-certificate-when-cloning-repo-from-git

In accordance with the guidance on https://github.com/desktop/desktop/issues/4738
Anti virus is an enterprise version managed by IT. as far as i can tell it's not been changed in the last 3 days.

### Logs

[2018-05-30.desktop.production.log](https://github.com/desktop/desktop/files/2054219/2018-05-30.desktop.production.log)

**Comment by niik** [comment]
Hey @Reahreic, thanks for opening this. We're tracking this over in #4817. We've upgraded Git to fix a security vulnerability and it looks to have had unintended consequences on Windows. This is the first report we've had of this on Windows 10 so this information is very useful.

Let's move this discussion over to #4817 so that we can easier judge the impact this is having and discuss how to proceed.

**Comment by nerdneha** [comment]
Hi @Reahreic, we just released 1.2.2 to address your and others' issues without requiring a workaround. Do you mind confirming that 1.2.2 addresses your issue?

**Comment by cristinamghita** [comment]
Hi!

@nerdneha , I got same issue, with github desktop version 1.2.3 and windows 7, service pack 1.

**Comment by iennacca** [comment]
+1; Windows 7 Enterprise, Service Pack 1; using IE 11.09600, but was doing a clone from Github Desktop.

**Comment by shiftkey** [comment]
@cristinamghita @iennacca I think the issue here is that Git's behaviour with respect to `http.sslCAInfo` changed around this time. Are you able to run this command from CMD and see if Git returns anything?

```
git config --show-origin http.sslbackend
git config --show-origin http.sslcainfo
```

If it does, this is probably related to the certificate bundle not containing the right certificates. This should be skipped if your `http.sslbackend` is `schannel`, but that release also had a change to the underlying `curl` library that affected the default behaviour.

Please open a fresh issue and fill out the template so we can troubleshoot further.

**Comment by roynes** [comment]
Me too. 
Win7
![sslcainfo](https://user-images.githubusercontent.com/12960236/44891737-8dcff480-ad13-11e8-8aff-a69d44348c6e.png)
