### ISSUE TITLE
Connection Managers Issue

### ISSUE THREAD

**Issue by vnaggelly** [desktop/desktop#4838]
Recently made changes to the SSIS ETL Packages in two different projects  and pushed to GIT hub
(I can see the changes in the Git Hub), when my colleague trying to clone his repository, just the connection mangers from a specific project are not getting cloned **Just connection managers only** and it reflected the changes from the other project.

I tried all the possible ways to clone even in my system as well but it did not reflected the changes in my system too.
Even I tried to make changes into the package and pushed it and tried to clone still did not showing up only to that specific project, where as I can able to clone the other project.
so cloud you please let me know if there is any other steps or methods to clone those changes.

**Comment by iAmWillShepherd** [comment]
Thanks for reaching out!

We require the template to be filled out with all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway 😀

p.s. The main things that would help here is your log file which can be access by going to **Help** -> **Show logs in Explorer**  and a bit of info on how your repo is setup (the `.gitignore` file would be a good start.)
