### ISSUE TITLE
Bring back Graph View

### ISSUE THREAD

**Issue by mikeytag** [desktop/desktop#4851]
This is starting to get silly. Please please please bring back the simplified graph view between 2 branches that was present in the old client.

![68747470733a2f2f676974687562656e67696e656572696e672e636f6d2f696d616765732f63726f73732d706c6174666f726d2d75692d696e2d6769746875622d6465736b746f702f636f6d70617269736f6e2d67726170682d6f732d782e706e67](https://user-images.githubusercontent.com/219403/40861332-89eae78e-659d-11e8-8abe-b90c6edb8a51.png)

The button to update from the other branch represented is also sorely missed by me. I've got a great flow that works around the tree and that button. I'm nowhere near as productive in the new client. I tried it for a few weeks and went back to the old client for just this reason. The speed of the new one is great, but missing the graph view and Update From button is a show stopper for me.

Seriously, who do I need to convince/pay off to make this happen? We have the technology!

#1634 #1694 #1733 #1853 #1864 #1939 #2420 #2885 #2958 #3048 #3322 #4628

**Comment by mikeytag** [comment]
I'm now wondering if there's something technical at a low level with Electron that makes generating the graph view really difficult.

**Comment by lee-dohm** [comment]
@mikeytag, I understand you're frustrated that a feature you used and enjoyed is not available in the new version of Desktop. As a software developer and enthusiast, I can relate.

However, deliberately and wittingly opening a duplicate issue is considered harassment under the [Desktop Code of Conduct](https://github.com/desktop/desktop/blob/master/CODE_OF_CONDUCT.md). I say "deliberately" because you included links to all of the other duplicates of the [original issue](https://github.com/desktop/desktop/issues/1634) and "wittingly" because you've [commented](https://github.com/desktop/desktop/issues/1634#issuecomment-312329074) [already](https://github.com/desktop/desktop/issues/1634#issuecomment-393995219) twice on the original. So you're aware of our team's answer, are refusing to respect it, and attempting to, [through repetition](https://github.community/t5/Studies-in-Community/How-can-you-tell-when-something-is-a-Code-of-Conduct-violation/ba-p/5445), get a different answer. This is why we consider this kind of activity harassment.

Additionally, taking the time to answer these kinds of antics takes time that the developers could put to better use, like implementing features. Every time that we have to compose a lengthy, considered, and well-thought-out response is time that could be invested in the product that you obviously care very deeply about. I hope you can see how that is counter-productive?

Any further repeats of this kind of behavior will incur an official warning and, if necessary, permanent blocking from the @desktop organization.

Thanks for listening.

**Comment by tegila** [comment]
I'm with @mikeytag on this issue. 
If your user is getting upset maybe is time to care more!
If you don't care maybe is time to blame the user. 

Also he made a good job at showing you how this is very important.
By the likes you can see the users thought and maybe reflect a little more.

Thank you!

**Comment by lee-dohm** [comment]
@tegila your comment was deleted as a violation of the [Desktop Code of Conduct](https://github.com/desktop/desktop/blob/master/CODE_OF_CONDUCT.md) as it was insulting or derogatory. You may consider this an official warning.

Additionally, if anyone is interested in the current status of this issue (where our team regularly participates and we do our best to give updates as we can), please subscribe to #1634.
