### ISSUE TITLE
A glitch with a file

### ISSUE THREAD

**Issue by Starlord2307** [desktop/desktop#4852]
## Description

Theres a glitch with a file it wont delete.

## Version

* GitHub Desktop:

* Operating system:

**Comment by shiftkey** [comment]
@Starlord2307 thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by shiftkey** [comment]
Closing this out as inactive. @Starlord2307 if you're able to fill out the template to help us with troubleshooting we're happy to revisit this.
