### ISSUE TITLE
no txt file on computer

### ISSUE THREAD

**Issue by nahuja20** [desktop/desktop#4861]
## Description

I am not able to access the text files on my computer even tho they are showing on the desktop version of github. Even after syncing the program on the github desktop application.

## Version

* GitHub Desktop:

* Operating system:

**Comment by shiftkey** [comment]
@nahuja20 thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by shiftkey** [comment]
@nahuja20 I've re-added the issue template because I need more details about your setup.

> I am not able to access the text files on my computer even tho they are showing on the desktop version of github. 

There is a **Repository** | **Show in Finder** or **Show in Explorer** menu item to open the repository in your default file explorer. Is that what you are looking for?

**Comment by shiftkey** [comment]
Closing this out as inactive. @nahuja20 if you're able to fill out the template to help us to troubleshoot the issue we're happy to revisit it.

**Comment by shiftkey** [comment]
We are also tracking making the publish dialog better detect free plans in #2165
