### ISSUE TITLE
Feature Request - Clippy

### ISSUE THREAD

**Issue by AzureDiamond** [desktop/desktop#4867]
**Is your feature request related to a problem? Please describe.**
Since Microsoft [bought](https://techcrunch.com/2018/06/04/microsoft-has-acquired-github-for-7-5b-in-microsoft-stock/) GitHub for 7.5 billion USD, we, Github fans thought that it would be great if good old Clippy was added to Github Desktop.

**Describe the solution you'd like**
Users really need a helpful assistant in complicated software, such as Git.

Something like this:
![Git Clippy](https://pbs.twimg.com/media/De0-66dWAAAqL8H.jpg)

**Comment by shiftkey** [comment]
@AzureDiamond thanks for the comment!

For the moment I think we're going to avoid adding explicit Clippy support, but if there's scenarios you can think of where the application can do better to guide the user we'd love to hear about them...

**Comment by shiftkey** [comment]
This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I added the `future-proposal` label to this issue and closed it so that we won't get overwhelmed with our backlog! We will revisit this in our next planning session.

**Comment by billygriffin** [comment]
This is amazing in so many ways, but as we're going through the `future-proposal` label and trying to provide more clarity in what we intend to work on and what we're looking for community support to do, I'm going to remove the label.
