### ISSUE TITLE
hide upstream refs when working in a fork of a repo

### ISSUE THREAD

**Issue by Koklin** [desktop/desktop#4880]
Do not show the branches of oroginal repo for the forked repo.

How to reproduce:

1) Fork a repo using site
2) Clone the forked repo to your PC.
3) Open the forked repo in GHD and observe the brabches of forked repo

At some point you wil see two sets of branches - origin/* (forked repo) abd upstream/* (original repo).
it is possible to NOT show the branches of original repo since I am now working with it?

it confuses me to see that many branches and I can`t open them anyway as I get the "A branch with that name already exists." message when trying to  open the original repo brancch.

Windows 10 pro
GHD 1.2.2

**Comment by shiftkey** [comment]
@Koklin thanks for the suggestion!

> At some point you wil see two sets of branches - origin/* (forked repo) abd upstream/* (original repo).
it is possible to NOT show the branches of original repo since I am now working with it?

This idea is interesting, and I'll add some context here about the current behaviour. For reference, [this is the code](https://github.com/desktop/desktop/blob/master/app/src/lib/git/for-each-ref.ts) that's getting all the refs in a repository.

We show all refs because that's close to what Git does. The only exception to this is hiding the Desktop-specific remotes (these are prefixed with `github-desktop-[author]`) which we add to make checking out a fork PR seamless.

I'm a bit nervous about hiding all `upstream/*` refs because there might be cases where new commits are added to an `upstream/*` ref that you might want to merge into your current branch. We're doing work currently to add workflows to make merging easier, and lots of workflows need to be aware of `upstream/*`.

I haven't explored the impact of this deeply, but it might be worth experimenting with **hiding an `upstream/xyz` ref when it points to the same commit id as the `origin/xyz`** ref. This might strike a better balance between hiding stale refs and keeping track of new upstream work, but I also worry about confusing people who expect to see all the refs for all the remotes.

> it confuses me to see that many branches and I can`t open them anyway as I get the "A branch with that name already exists." message when trying to open the original repo brancch.

We're tracking this bug in #4527, and this has some more details about the underlying issue.

**Comment by jwillmer** [comment]
As @shiftkey mentioned it is sometimes important to display the upstream branch. I currently have a project that I don't have write access. In order to participate I fork the repo, create a new branch "issue-59" and the create a pull request to the upstream repo. In order to merge the changes from upstream to my repo it is necessary(?) to see the repo.

**Comment by shiftkey** [comment]
I'm 👎 on this change as we don't want to be hiding remotes that the user might be interested in. 

@Koklin if you're not interested in the upstream remote any more I'd recommend removing it from Git (I'm guessing the remote is named `upstream`, but your mileage may vary):

```
$ git remote rm upstream
```

I believe that should resolve it, but I'm monitoring #3715 where someone believes Desktop will add the remotes back, so please keep an eye on that discussion.

@billygriffin any other input or suggestions about this UX?

**Comment by billygriffin** [comment]
@shiftkey That makes sense to me, and agreed with @jwillmer's rationale as well. I think this has the potential to introduce more confusion than we'd be clearing up. I also agree that the combination of #4527 and improved messaging around branch names conflicting will help improve this. I'm going to go ahead and close this for those reasons, and thanks again @Koklin for the idea and helping us understand the problem.
