### ISSUE TITLE
Changing letters case in branch name

### ISSUE THREAD

**Issue by greegus** [desktop/desktop#4881]
## Description
When renaming a branch, changing just the letters case would lead to an error `A branch with that name already exists.`

## Version
* GitHub Desktop: 1.2.2
* Operating system: macOS (10.13.5)

## Steps to Reproduce
1. Create a branch with name `FOO`
2. Try to rename the branch to `foo`

### Expected Behavior
Branch should be renamed with changed case

### Actual Behavior
Error alert `A branch with that name already exists.`

**Comment by iAmWillShepherd** [comment]
Thanks for taking the time to open an issue! 🙇

@greegus this is expected behavior and inline with how Git performs in the CLI.

```
─williamshepherd@Hera ~/Desktop
╰─$ mkdir test && cd test && git init
Initialized empty Git repository in /Users/williamshepherd/Desktop/test/.git/
─williamshepherd@Hera ~/Desktop/test  ‹master›
╰─$ echo file > f1.txt                                                    128 ↵
╭─williamshepherd@Hera ~/Desktop/test  ‹master*›
╰─$ git add .
╭─williamshepherd@Hera ~/Desktop/test  ‹master*›
╰─$ git commit f1.txt -m "file"
[master (root-commit) 832d406] file
 1 file changed, 1 insertion(+)
 create mode 100644 f1.txt
╭─williamshepherd@Hera ~/Desktop/test  ‹master›
╰─$ git branch foo
╭─williamshepherd@Hera ~/Desktop/test  ‹master›
╰─$ git branch FOO
fatal: A branch named 'FOO' already exists.
╭─williamshepherd@Hera ~/Desktop/test  ‹master›
╰─$ git checkout foo                                                        128 ↵
Switched to branch 'foo'
╭─williamshepherd@Hera ~/Desktop/test  ‹foo›
╰─$ git branch -m FOO
fatal: A branch named 'FOO' already exists.
```

As you can see, trying to rename the branch to the same name with a different case produces an error. Since treating branches as case-sensitive can cause issues, I recommend you rename you branch to something else before trying to rename it to the thing you want.

```
╭─williamshepherd@Hera ~/Desktop/test  ‹foo›
╰─$ git branch -m foo-tmp                                                   128 ↵
╭─williamshepherd@Hera ~/Desktop/test  ‹foo-tmp›
╰─$ git branch -m FOO
╭─williamshepherd@Hera ~/Desktop/test  ‹FOO›
╰─$ git branch
* FOO
  master
```

I know this workaround may not seem ideal, but it does allow you to go from `foo` -> `Foo`. One thing to note is that this will only change the branch name on _your_ machine, not others, so renaming a branch could cause more trouble than it's worth.

**Comment by michael-zarif** [comment]
This issue is still existing till now in GitHub Desktop.
I know that the workaround works, however, I think that the solution should be to exclude the current branch name (e.g. FOO) from the search of other branch names (to check name uniqueness), if it has a max count of 1 (only the current branch) regardless of its case. As this is a renaming process, and hence the old name won't exist anymore after the process.
