### ISSUE TITLE
I can see github desktop on full screen statement, I can't find my github desktop window, Please find that. 

### ISSUE THREAD

**Issue by Janet4676** [desktop/desktop#4886]
## Version

* GitHub Desktop:

* Operating system:

**Comment by shiftkey** [comment]
@Janet4676 thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by DivAnanand** [comment]
Hi 
I just download the GitHub Desktop.
I want to clone my repository.
But it is showing some error about the security certified.
Please Help me.

**Comment by shiftkey** [comment]
@DivAnanand could you please open a new issue and fill out the template, so we can help with troubelshooting?

**Comment by nerdneha** [comment]
Hi @Janet4676, I'm going to close this out due to inactivity but if you can provide more details about the issue, we're happy to re-open and help!
