### ISSUE TITLE
fetch origin

### ISSUE THREAD

**Issue by orange-jacky** [desktop/desktop#4888]
fatal: unable to access 'https://gitee.com/goio/client.git/': schannel: CertGetNameString() failed to match connection hostname (gitee.com) against server certificate names

**Comment by niik** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by Dd-ouni** [comment]
我也遇到一个的情况

**Comment by Dd-ouni** [comment]
I also met one case.

**Comment by nerdneha** [comment]
Hi @orange-jacky, I'm going to close this out due to inactivity but if you can provide more details about the issue, we're happy to re-open and help!

**Comment by meetmrharish** [comment]
Even I am facing the same issue using github desktop application. Using git commands, I don't have any problems though.

**Comment by shiftkey** [comment]
@harishp1213 please look at https://github.com/desktop/desktop/issues/4817 for more details and ensure you are running the latest version (1.2.3).

**Comment by harishp1213** [comment]
@shiftkey Thank you.. Removing the below line from C:\ProgramData\Git\config file fixed the issue

sslCAInfo = C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
