### ISSUE TITLE
I get this error when I click Commit to master

### ISSUE THREAD

**Issue by eaglesfan1** [desktop/desktop#4903]
Commit failed - exit code 128 received, with output: '*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'Owner@Toshiba.(none)')'

Could you please tell me what I am doing wrong?

**Comment by eaglesfan1** [comment]
Please tell me what I am doing wrong.

**Comment by eaglesfan1** [comment]
My email address is mkclemens@comcast.net

**Comment by steveward** [comment]
Thanks for opening this @eaglesfan1.  Can you go to the file menu in GitHub Desktop and select `File` > `Options` > `Git` and verify that your name and email address are correctly set there? 

You will want to make sure that the email address matches an email address that is under your GitHub account so that you receive proper commit attribution. After you set those values you should see this error go away.

**Comment by eaglesfan1** [comment]
Thanks very much for your help.  I was wondering if you could tell me 
how I can upload a replacement index.html file because I want to make 
some changes on my index.html file and re upload it again. If you could 
tell me how that would be great.


Thanks again,

Mark Clemens

**Comment by shiftkey** [comment]
>I was wondering if you could tell me how I can upload a replacement index.html file because I want to make some changes on my index.html file and re upload it again.

@eaglesfan1 if you make the changes to the file, switch to Desktop and create another commit (you should see the file as modified) and then push the changes to the remote repository you should be back to a good place!

**Comment by shiftkey** [comment]
@eaglesfan1 I'm going to close this out as I believe the original issue has been resolved.
