### ISSUE TITLE
Multiple checkouts of the same repository are indistinguishable

### ISSUE THREAD

**Issue by jswigart** [desktop/desktop#4922]
**Is your feature request related to a problem? Please describe.**
Multiple checkouts of the same repository are indistinguishable under the current repository drop down

**Describe the solution you'd like**
Something simple like showing the local file path out next to the repository would be great.

**Describe alternatives you've considered**
None

**Teachability, Documentation, Adoption, Migration Strategy**
Should be pretty self explanatory to the user what showing the local path next to the repository name represents.

Here is how it looks now

![image](https://user-images.githubusercontent.com/4065267/41294630-21c0ff16-6e1e-11e8-8783-8b15a5d4ca1e.png)

**Comment by jswigart** [comment]
I just realized there is a tool tip with the local path information, but I largely stumbled on it. Perhaps still consider something more obvious? Otherwise you can nuke this request.

**Comment by iAmWillShepherd** [comment]
Thanks for taking the time to open an issue! 🙇 

I think this is a good issue for someone interested in contributing to Desktop.The code below is a good starting point and the `title` attribute can be modified so that the path is also included in the tool-tip.

https://github.com/desktop/desktop/blob/be53d2c96d6b43ed58573b0e5ff7ae16d91b26c2/app/src/ui/app.tsx#L1442-L1485
