### ISSUE TITLE
revocation server is offline unable to clone repositery erreo 

### ISSUE THREAD

**Issue by mdakib9758** [desktop/desktop#4923]
## Version

* GitHub Desktop:

* Operating system:

**Comment by steveward** [comment]
👋 @mdakib9758 

This error is usually caused by your network blocking the attempt by Windows to check the revocation status of a certificate, which then causes the whole operation to error. You can find a workaround for this issue here:

https://github.com/desktop/desktop/blob/master/docs/known-issues.md#certificate-revocation-check-fails---3326

If you have any questions about the workaround, please let me know.
