### ISSUE TITLE
Local Repo Name is empty due to being on drive root

### ISSUE THREAD

**Issue by BenWLeon** [desktop/desktop#4924]
## Description
When adding a new local repo, if the added repo is at the root if the drive ( say Z:\ ), no name is pulled from for the repo

## Version

* GitHub Desktop: Version 1.2.3 
* Operating system: Microsoft Windows [Version 6.1.7601]

## Steps to Reproduce

List the steps to reproduce your issue **below** this comment
ex,
1. Click on File -> Add local Repository  Ctrl+O
2. Select Mapped Drive with Repo on it's root ( Z:\) 
3. Click Add repository
4. Click on 'Current repository' to see list of all repositories 

### Expected Behavior
It should pull in the name of the mapped drive and if there's an issue allow the user to name it or rename it.

### Actual Behavior
Repo is added, but there is an empty name

### Logs
[2018-06-12.desktop.production.log](https://github.com/desktop/desktop/files/2095293/2018-06-12.desktop.production.log)

**Comment by nerdneha** [comment]
Thanks for the bug report @bwleon!
*Clarifying Question*
Would you expect the "name of the mapped drive" that you want to appear as the repository name to be `Z:\` or specifically a name you've specified elsewhere? 

I was able to reproduce this on my mac by doing the following things:
Steps:
1. `cd /`
1. `git init`
1. Go to Desktop app
1. Add root (`/`) as a local repository
1. Verify there's no name

I got a gif of this:
![jun-14-2018 20-31-26](https://user-images.githubusercontent.com/1834387/41448854-2dbfd526-7012-11e8-9925-6566e0bfadd5.gif)

**Comment by bwleon** [comment]
Thank you for getting back to me @nerdneha. 

I would expect it to be named the description from the mapped drive which is pulled from the folder on the remote folder. However, this isn't the best idea, because in other OS not all drives have names. 

I'd prefer if it showed `Z:\`  or in your example `/`.

In the future will we be able to change the name displayed for the repo or add a description from the Deskop application?
