### ISSUE TITLE
discard changes from keyboard

### ISSUE THREAD

**Issue by jenfan** [desktop/desktop#4936]
**Is your feature request related to a problem? Please describe.**
I cant discard changes by simple deleting it from keyboard (e.g. like deleting files, no one deletes files through context menu), on macos I have to do it with trackpad through right click + choosing in the context menu and I feel wasting my time. I miss this feature for 2 years and I think if this app is about changes, it needs this functional. I plead you :)

**Describe the solution you'd like**
I think to let discard changes by pressing `delete` button or `cmd + delete`. simple and usual

Rare I need to delete files, so if I were a developer, I'd add `remove file` to the context menu. But its really rare, and I very need mentioned discard feature)

ps: sorry for my bad english and спасибо)

**Comment by nerdneha** [comment]
Hi @jenfan, if I understand correctly, your requested behavior is as follows:

**Initial Steps**
* Go to the changes tab and see the outstanding changed files
* Click on a file and see it highlighted blue, indicating that it is selected

**Requested Behavior**
When I press the `delete` or `cmd + delete` button, I see the selected file removed from the changes tab and those changes in that file are discarded

**Clarifying Questions**
1. When you go to the changes tab, do you expect one of the files to be selected automatically so that you can delete it?
2. Are you using a mac or a windows keyboard? The mac `delete` button reads as `backspace` on windows and so I'd like to clarify 😄

**Comment by nerdneha** [comment]
Looks like this is related to this issue also: https://github.com/desktop/desktop/issues/2456.
@jenfan can you add your request in that issue? Closing this issue but it would be helpful to get the answers to the clarifying questions in that issue, also!

**Comment by jenfan** [comment]
@nerdneha 
answer the questions:
1. Yes, I expect one of the files to be selected
2. I use macbook only, so I have delete only. I almost forgot that backspace btn exists >< 

thank you!
