### ISSUE TITLE
When sign in as Enterprise account, it asked to use browser for SSO. However, need to know how to handle the x-github-client link.

### ISSUE THREAD

**Issue by TakWong2018** [desktop/desktop#4961]
## Version

* GitHub Desktop:

* Operating system:

**Comment by shiftkey** [comment]
@TakWong2018 thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by shiftkey** [comment]
Closing this out due to inactivity. @TakWong2018 if you're able to fill out the template we can revisit this issue.
