### ISSUE TITLE
Add an option to send a 2FA code to a backup number

### ISSUE THREAD

**Issue by secondsun** [desktop/desktop#4994]
**Is your feature request related to a problem? Please describe.**
I have 2FA activated, but I don't use a authenticator app; I just have you send a SMS.  In the web site there is a button to send a code to my phone, but there isn't one in the desktop app.

**Describe the solution you'd like**
I would like the 2FA screen on the desktop to have an option to send a 2FA code

**Describe alternatives you've considered**
I can work around this by opening an incognito window, starting a sign in, and request a backup code and then using that code in the app instead of in the website.

**Comment by shiftkey** [comment]
@secondsun we're limited by what the OAuth flow let's us do, and because GitHub The Website sends a response after providing your username/password that it expects a code from an authenticator app, that's the prompt we display to the user. 

I'm curious whether "Sign in using your browser" is a suitable workaround for your issue:

<img width="429" alt="screen shot 2018-06-22 at 8 41 26 am" src="https://user-images.githubusercontent.com/359239/41774948-329d8778-75f8-11e8-8710-681c38834e60.png">

If you're already signed into GitHub The Website, this means Desktop can avoid having to sign in again.

**Comment by shiftkey** [comment]
Closing this out as not something we plan to support in the future.
