### ISSUE TITLE
Unable to access repository

### ISSUE THREAD

**Issue by sowmyaumesh** [desktop/desktop#5010]
on windows git desktop connecting to git enterprise
version 1.2.3
-->
![image](https://user-images.githubusercontent.com/33002347/41793707-8c3b5ce2-767a-11e8-9549-89ed2bb0892d.png)

getting and error below:
schannel: CertGetNameString() failed to match connection hostname (github.ibm.com) against server certificate names

**Comment by shiftkey** [comment]
@sowmyaumesh thanks for the report.

If you're able to open a shell and run this command:

```
git config -l --show-origin
```

You should see an entry like this:

```
file:"C:\\ProgramData/Git/config"       http.sslcainfo=C:/Program Files/Git/ming
w64/ssl/certs/ca-bundle.crt
```

This certificate file is being loaded, rather than using the operating system's certificate store.

If you open up this `C:\\ProgramData/Git/config` you should see this config value:

```
[http]
sslCAInfo = C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
```

If you remove those two lines you should be back to a good place.

**Comment by sowmyaumesh** [comment]
@shiftkey I dont see the below path on my windows 7 machine
C:\\ProgramData/Git/config

**Comment by shiftkey** [comment]
@sowmyaumesh `C:\ProgramData` is a hidden directory by default - you might need to manually specify the folder to get there.

**Comment by sowmyaumesh** [comment]
@shiftkey I could get the config file, but I am getting access denied. Unable to edit the file. I tried changing the file permission too

**Comment by sowmyaumesh** [comment]
@shiftkey thanks so much I could edit config and issue is resolved
