### ISSUE TITLE
GitHub desktop changes git global configuration without consent

### ISSUE THREAD

**Issue by m4heshd** [desktop/desktop#5017]
I was really super late when i found out about this. I use multiple accounts for multiple projects. I also use multiple IDEs. Most of the time i use IDE integrated git tools to save a lot of time. I recently logged into GitHub desktop using another(personal) account other than my regular account. Once i was finished with the project connected with that account i went back to working on my commercial projects which i collaborate with multiple colleges. I use netbeans for that particular project and i didn't realize i was committing using that private git user because GitHub desktop decided to change the global user. Netbeans git tools use the global config. I didn't want anybody to know about that account. It's really messed up and unnecessary. Please get rid of that feature.

**Comment by shiftkey** [comment]
@m4heshd thanks for the report.

The Welcome Wizard for Desktop should, after signing into your GitHub account, should check that you have a `user.name` and `user.email` setting for committing.

<img width="678" src="https://user-images.githubusercontent.com/359239/41851707-2549175e-785f-11e8-904e-c7e0686ba464.png">

The key decisions that it makes here are:

 - if you have an existing `user.name` and `user.email` global setting, display those
 - if you don't have a `user.name` and `user.email` setting, populate these based on the GitHub account you just signed in with

It's not clear to me how NetBeans was configured at the time, but Desktop is setup to use your global configuration around committing, so I'm not sure how this was able to be triggered. Are you able to provide more detailed steps about how to trigger this:

 - how your global configuration was setup before?
 - the steps when signing into Desktop to trigger the config change?

**Comment by shiftkey** [comment]
> I saw that GitHub automatically inserts the global author in the login. 

@m4heshd I'm interested in what's in your `~/.gitconfig` for defining your commit information. Desktop looks for `user.name` and `user.email`, so I'd love to understand what your configuration is like before you launch Desktop that might be causing the conflict.

**Comment by m4heshd** [comment]
That's what i explained. Before it was **User A** and after logging in it was **User B**. I don't want to post specific details here.

**Comment by shiftkey** [comment]
> I don't want to post specific details here.

I have lots of questions that will help me understand the steps to reproduce this issue:

 - which OS are you running on?
 - which version of NetBeans?
 - how are you adding your commit author details to NetBeans?
 - how are you signing into Desktop to trigger this issue? Is it just through the Welcome Wizard (screenshot below)?

<img width="993" src="https://user-images.githubusercontent.com/359239/41878607-21dfefe6-78ac-11e8-9091-328ed34d78b4.png">

 - after signing in, does the **Configure Git** form fields look correct (screenshot below)? Is it at this point that you see the values change to what's in the other (wrong) account?

<img width="974" src="https://user-images.githubusercontent.com/359239/41878647-43ef7476-78ac-11e8-81ac-083e5367f489.png">

**Comment by m4heshd** [comment]
Let's take NetBeans out of the question because i realize it's irrelevant at this point. I just mentioned it to explain the difficulty i was having. It was indeed the welcome wizard. OS is Windows 10. Does "Configure Git" step of the wizard change the Global user? If it is then why? I have suggestions.

- The author specified in the wizard should be app specific. It shouldn't be global
- GitHub desktop should fetch the author from repo config instead of global. (just like IDEs)
- There should be an option to select the author when committing (Should include author from repo config and global config)

I just edited the user from GitHub desktop options and it changed the global user. That's what shouldn't happen. I should be able to use multiple users throughout multiple applications. For an example "GitKraken" has the exact behavior i'm requesting. GitKraken never changes the global config. Instead it keeps an app specific config. So when i do commits i'm well aware which author i'm using to do that commit.

**Comment by shiftkey** [comment]
> Does "Configure Git" step of the wizard change the Global user? If it is then why?

This sets whatever was specified in the inputs and, as I mentioned above, should be derived from existing information:

 - if you have an existing `user.name` and `user.email` global setting, display those
 - if you don't have a `user.name` and `user.email` setting, populate these based on the GitHub account you just signed in with

This is to ensure you have _something_ set when you make a commit.

> GitKraken never changes the global config. Instead it keeps an app specific config.

Are you referring to [Profiles](https://support.gitkraken.com/start-here/profiles) here? 

> So when i do commits i'm well aware which author i'm using to do that commit.

That's the intent of the avatar inside the commit form - you can hover over it and see what your commit details look like for the current repository:

<img width="384" src="https://user-images.githubusercontent.com/359239/41919275-78e10ff4-7934-11e8-80c2-40a3e3c72ddf.png">

I'd still love to confirm our current behaviour around the global configuration is working by design, so let's see if we can settle on some steps to test the behaviour of the Welcome Wizard. How does this look for steps to reproduce the problem?

 - I set my global user details to some values:
   - `git config --global user.name "Previous Name Goes Here"`
   - `git config --global user.email "old-email@example.com`
 - I start from a fresh install of Desktop
 - I sign into my account from the Welcome Wizard
 - I see the **Configure Git** step
 - **Expected behaviour:**
   - I see "Previous Name Goes Here" and "old-email@example.com" as the values
   - I click **Continue** and complete the Welcome Wizard
   - I check my global configuration again
      - `git config --global user.name`
      - `git config --global user.email`
 - **Actual behaviour:** ???

If that makes sense to illustrate the issue I'll have a shot at recreating the issue on a fresh Windows machine.

If you're more interested in the ability to manage app-specific profiles that don't touch the global git config, please open a [feature request](https://github.com/desktop/desktop/issues/new?template=feature_request.md) with the context from our discussion.

**Comment by m4heshd** [comment]
I'll try to narrow this down more. I have no idea why the issue is so hard to explain. Could be an issue of communication because English isn't my native language. Sorry about that.

> Are you referring to Profiles here?
Yes.

> So when i do commits i'm well aware which author i'm using to do that commit.
By this i meant software other than GD. Because i may not know which user i'm using to do commits from other tools since GD changes it.

Ok i just ran a test case. I created a local repo and set the repo config to a different user. Miraculously GD picked it up. I swear to god that it didn't happen with the previous update. Now i'm on v1.2.6. I know this is a new update because i didn't have the dark theme option before.

It seems like the confusion is in the welcome wizard. It picked up the Global user details which i didn't wanna use to do commits. I though if i left that it'll use those details to do commits from GD instead of the account i used to log in. I assumed that even though it did a GET to fetch the global user for "Configure Git" window, it won't do a SET if i changed that because i'm used to the procedure of GitKraken and other git tools. If this is unavoidable it should mention that "If you change this it will replace the global user". 

It is indeed a massive confusion. To overcome this GD should mention to the user how users are selected to do commits. User from the GitHub login, Global user or the user from local repo config because all of these could be different from each other in somebody's scenario. Correct me if i'm wrong. To my understanding at this point, it never use the details from GitHub login right? Instead it uses the repo user if available else it'll use the global user.

So here's where i messed up because i was mislead. My repo user and GitHub login user was similar but the global user was different. I think in a scenario like this, anybody would change the user details from "Configure Git" step because of the lack of clarity, without knowing that it would change the global user. In my case GD was meant to handle a completely different user from my global user which is used by all the other tools throughout my PC.

I really hope this clears the issue out because this is the best i can do in explaining this.

**Comment by shiftkey** [comment]
@m4heshd no problem - and thanks for working through to get to the bottom of this.

> Ok i just ran a test case. I created a local repo and set the repo config to a different user. Miraculously GD picked it up. I swear to god that it didn't happen with the previous update. 

This is good, and was my primary concern when the issue was first opened. I'm not aware of any recent changes around the Welcome Wizard itself, so this is a relief to hear.

> It is indeed a massive confusion. To overcome this GD should mention to the user how users are selected to do commits. User from the GitHub login, Global user or the user from local repo config because all of these could be different from each other in somebody's scenario. 

Implementation details aside, that's the exact purpose of the Configure Git dialog - we show you the settings and what a commit will look like using those details. Also keep in mind that we can only deal with the _global_ context here. If a repository has overridden `user.name` and `user.email` in it's local config, this will only show when they are viewing that repository - which is why we show the avatar and committer details in the commit form.

I'm open to suggestions on improvements to the copy here, but I don't want to overwhelm people here who are less familiar with Git concepts like global configuration. 

Here's the source, if someone wants to try and improve things:

https://github.com/desktop/desktop/blob/1c443bcf02c59dbf0833975211c9cffaaaa489ea/app/src/ui/welcome/configure-git.tsx#L18-L21

> Correct me if i'm wrong. To my understanding at this point, it never use the details from GitHub login right? Instead it uses the repo user if available else it'll use the global user.

If you don't have an existing global `user.name` and `user.email` set, Desktop will suggest a `user.name` and  `user.email` derived from your GitHub account. That's the extent to which we inject ourselves into this process - once you **Continue** here the values are saved to your global config.

>  In my case GD was meant to handle a completely different user from my global user which is used by all the other tools throughout my PC.

Yeah, this is what we've talked about earlier in issues like #1860, and my thoughts on this are mostly explained in https://github.com/desktop/desktop/issues/1860#issuecomment-305519523.

I'd prefer that Desktop uses the global configuration so that we interop nicely with other tools that also use the global configuration to manage identity, but if you think there are benefits to using "profiles" then I'm happy to move that to a fresh discussion.

**Comment by m4heshd** [comment]
Thank you for the detailed response. I think i can agree with you. An improvement in this matter would simply be an update for the text instructions as you mentioned. I'll make sure to be a part of that.

**Comment by Aeolun** [comment]
I see Github desktop still feels the need to modify your global configuration. I don't understand why a very clearly distinct application feels the need to mess with my global git configuration?

I don't want desktop to *ever* modify my global git configuration. Reading it to figure out a nice default user is fine, but don't write back to the global configuration when I opt to select a different account for desktop.

**Comment by cypok** [comment]
I don't like GUI git clients but I've wanted to show my students that there are such options. I've installed yesterday GitHub Desktop and it messed my global config at work laptop!

It was:
```
[include]
  # my name and personal email are there:
  path = ~/.dotfiles/gitconfig
[user]
  email = full.name@somecompany.com
```
It became:
```
[include]
  # my name and personal email are there:
  path = ~/.dotfiles/gitconfig
[user]
  email = short.name@personaldomain.com
  name = Short Name
```
So I've ended committing to work repositories under my personal email address and non-official name.

Please, add an option "skip it and don't touch global config".

**Comment by rvnash** [comment]
GitHub Desktop does not seem to be aware that the `.gitconfig` file can have `[include]` or `[includeIf]` statements which allow you to set configurations in other files, or conditionally set them in other files. GitHub Desktop treats `.gitconfig` as if it were a flat list of configurations, and writes things like user.email and user.name in there unconditionally. The only simple solution to this is to have GitHub desktop not write the file at all, and to read the information from the same place as the `git config` command does, which can depend on which repository is open.

**Comment by steveward** [comment]
@rvnash that issue is being tracked in https://github.com/desktop/desktop/issues/12041.
