### ISSUE TITLE
cannot publish unborn head

### ISSUE THREAD

**Issue by AgbajeMike** [desktop/desktop#5057]
## Version

* GitHub Desktop:

* Operating system:

**Comment by shiftkey** [comment]
@AgbajeMike thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by steveward** [comment]
@AgbajeMike usually the `UNBORN HEAD` error happens when you are attempting to publish a branch that has no commits. If that is the case, make an initial commit and then try publishing your branch again. If you have any further issues, please fill out the template so that we can better help you!

**Comment by shiftkey** [comment]
Closing this out due to inactivity. @AgbajeMike if @steveward's advice doesn't help with your situation, you can fill out the template and we can investigate further.
