### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by ENVY14** [desktop/desktop#5076]
Cannot read last commit information from GitHub repository ENVY14/github: HTTP GET to https://api.github.com/repos/ENVY14/github/branches/master returned status code 404: Not Found Full response body: {"message":"Branch not found","documentation_url":"https://developer.github.com/v3/repos/branches/#get-branch"}

**Comment by steveward** [comment]
Thanks for reaching out!

We require the template to be filled out with all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway. 😀
