### ISSUE TITLE
Ignore functionalty

### ISSUE THREAD

**Issue by durgesh-vaishy-ngi** [desktop/desktop#5108]
## Description

Ignore all <file> not working.

## Version

1.2.6
* GitHub Desktop:

* Operating system:
Windows 10

**Comment by shiftkey** [comment]
@durgesh-vaishy-ngi thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by shiftkey** [comment]
Closing this out due to inactivity. @durgesh-vaishy-ngi if you're able to fill out the template we can revisit this issue.
