### ISSUE TITLE
 schannel: failed to open CA file 'C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt': No such process

### ISSUE THREAD

**Issue by Pkrishna412** [desktop/desktop#5110]
## Version

* GitHub Desktop:

* Operating system:

**Comment by shiftkey** [comment]
@Pkrishna412 thanks for the report.

I believe your issues is the same as https://github.com/desktop/desktop/issues/4832, because of system config entry that looks like this:

```
file:"C:\ProgramData/Git/config" http.sslcainfo=/bin/curl-ca-bundle.crt
```

This entry is no longer valid (Git installations should not be adding this entry to this file) and removing this entry

```
[http]
  sslCAinfo = /bin/curl-ca-bundle.crt
```

from `C:\ProgramData\Git\config` should address the issue for Desktop.

**Comment by shiftkey** [comment]
@Pkrishna412 I'm going to close this out because it's a known issue with a workaround, but please fill out the template to provide more details if you are still encountering issues.
