### ISSUE TITLE
Unable to authenticate due to existing API_Endpoint environment variable

### ISSUE THREAD

**Issue by chris-crowther** [desktop/desktop#5137]
## Description

GitHub Desktop is unable to authenticate with GitHub.com because it uses an environment variable called `API_Endpoint` to override the API address and _our_ application uses an environment variable called - you guessed it - `API_Endpoint` for its own nefarious ends.
See https://github.com/desktop/desktop/issues/794

I think the lesson for all of us is to prefix our environment variable names to make them more specific!

## Version
* GitHub Desktop: 1.2.6
* Operating system: Windows 10

**Comment by j-f1** [comment]
The app should probably only be checking for this environment variable in development mode, although it would make sense to namespace it, perhaps `GITHUB_DESKTOP_DOTCOM_API_ENDPONT`?

**Comment by shiftkey** [comment]
@chris-crowther thanks for the report. This is the problem code, which we added back in #805 and I don't think we every documented it properly:

https://github.com/desktop/desktop/blob/bc2d297ae520119e788711364cb0b40bbb72f16c/app/src/lib/api.ts#L827-L830

This really should be a Desktop-specific environment variable like @j-f1 said, because it's really only for those of us who develop against GitHub locally.

**Comment by meaghanlewis** [comment]
@shiftkey is there a good way to test this fix?

**Comment by shiftkey** [comment]
@meaghanlewis I'd set the `DESKTOP_GITHUB_DOTCOM_API_ENDPOINT` to some URL that you know won't respond as expected (like `https://example.com`) and confirm the app errors in strange ways. Not really worth spending more time than that in here - it's for internal purposes only.

**Comment by meaghanlewis** [comment]
Okay, got it. Thank you!
