### ISSUE TITLE
Local branch name conflicts with remote branch name

### ISSUE THREAD

**Issue by CreatorVilius** [desktop/desktop#5141]
Ok so i was trying to push files into my repo

and i came across this thing

[Error Click Here](https://cdn.discordapp.com/attachments/425750108223569982/466542651596865556/Untitled.png)

So i tried to pull, but when i tried that

[I saw this](https://cdn.discordapp.com/attachments/425750108223569982/466542648790876161/Untitled2.png) 

> **Can anyone help me? Please?**

> Can't do pull request either, same error for some reason...

**Thanks niik, i made new branch `oof` and made it default, then deleted master branch and now it works.**

**Comment by niik** [comment]
I believe what has happened is that a branch with the same name as your local branch was either created on, or already existed on the server/remote when you created your local branch. That branch on the remote had diverged from your local branch such that a fast-forward push was impossible.

### Steps to reproduce

1. Clone an existing repository
2. Create a local branch `test` and create one dummy commit
3. Before pushing/publishing, create a branch on the server called `test` and create one dummy commit
4. Try publishing your local branch.

### Alternative steps to reproduce

1. Clone an existing repository
2. Find an existing branch on the remote that has diverged from master
3. Create a new branch locally with the same name as the remote branch
4. Attempt to publish that branch.

We should certainly be doing a better job of handling this scenario and describing what's going on but the easiest way forward for you right now would be to rename your local branch by going to the `Branch` menu and clicking on `Rename...` and then publishing your new branch.

@desktop/core I think that, at a minimum we should alert users if they're creating a branch with a name that conflicts with an already existing branch on the remote. More long term we should probably have messaging that's closer to 'There's already a branch on the remote named `foo`. ' rather than the generic messaging we have now.

**Comment by shiftkey** [comment]
> I think that, at a minimum we should alert users if they're creating a branch with a name that conflicts with an already existing branch on the remote. More long term we should probably have messaging that's closer to 'There's already a branch on the remote named `foo`. ' rather than the generic messaging we have now.

👍 I can get behind this

**Comment by Daniel-McCarthy** [comment]
> I think that, at a minimum we should alert users if they're creating a branch with a name that conflicts with an already existing branch on the remote. More long term we should probably have messaging that's closer to 'There's already a branch on the remote named foo. ' rather than the generic messaging we have now.

>I can get behind this

I am interested in this suggestion. I would be happy to give it a try.

From what I have seen, if a branch exists on remote (ex. `test`) but not on local, I can still see and select it as `origin/test`.

I see two immediate options I'd like to ask about:

- Would it be sufficient to check for `origin/test` similar to how it already checks if a local branch of the name `test` exists? (It looks for it in this.props.allBranches)

- Otherwise there is a function in lib/git/branch that `deleteBranch` uses that is not currently exported that can check if a branch exists on remote.

**Comment by outofambit** [comment]
@Daniel-McCarthy thank you! i think something closer to the first approach would be fine, so long as it can handle a "default" remote who's name isn't `origin`
