### ISSUE TITLE
Detect file name case change using Windows Explorer

### ISSUE THREAD

**Issue by gojanpaolo** [desktop/desktop#5151]
Is it possible for GitHub desktop to detect a change in a file name if the only change was its case?
For example: "Foo.txt" --> "foo.txt"

GitHub does not detect the change if I use the Windows Explorer.

What I did for now is to use the command `git mv Foo.txt foo.txt`.

**Comment by shiftkey** [comment]
@gojanpaolo we had an earlier discussion about this in #2672 and I added some context about what Git is doing here. 

I recommend the `git mv` workaround as this will both update the filesystem and add the change to the index. If you just make the change in Explorer and commit both files in Desktop then Git will probably consider it a rename, but because the changes are not staged by default it considers them as two separate changes.

**Comment by gojanpaolo** [comment]
@shiftkey Thanks for directing the main thread. 

It's funny that I used the same example `git mv Foo.txt foo.txt` as with the comments. :D
