### ISSUE TITLE
possible git-flow implementation

### ISSUE THREAD

**Issue by Chris1904** [desktop/desktop#5159]
Hi everyone,

I enjoy using [git-flow](https://nvie.com/posts/a-successful-git-branching-model/) and currently only Sourectree (& Git Tower and maybe others) supports this feature:

<img width="782" alt="screen shot 2018-07-13 at 2 52 01 pm" src="https://user-images.githubusercontent.com/6228425/42716524-c26d1c38-86b0-11e8-9a2b-03f847b36c5d.png">

I thought this might be a cool idea to add into GitHub Desktop as it seems to be a pretty popular workflow!

Thanks so much for this!

**Comment by shiftkey** [comment]
@Chris1904 thanks for the suggestion. We're already tracking this in #2139, so please follow along with that issue.

**Comment by bduman** [comment]
+1

**Comment by adam-buckley** [comment]
Since that other ticket is locked (understandably) I'll add a comment here.

I'm on Linux and am loving Github Desktop after rediscovering it recently, the layout is nice and minimal (as far as git clients go) and it's extremely easy and a pleasure to use. But the lack of git-flow support is a deal breaker and now I have to either try and manually mimic git-flow (which is a massive pain) in this app or go back to using Gitkraken which, while it works great, is a massive resource hog, can be slow and has too much going on. Unfortunately Sourcetree, Fork et al. don't have native Linux clients otherwise I'd be using those.

Adding git-flow to Github Desktop would give me zero reasons to use Gitkraken and allow me to make this app a strong recommendation for Linux users within our company.

Thanks for your time.

**Comment by masoodmunshie** [comment]
Adding git flow would be so awesome. I wouldn't need to use other software.

**Comment by nichitaa** [comment]
the visual part of `github-desktop` client is so much better then `sourcetree`, but the luck of the git-flow feature makes me stick with `sourcetree`.
