### ISSUE TITLE
Make the top bar more seamless?

### ISSUE THREAD

**Issue by danqing** [desktop/desktop#5168]
This is purely an aesthetic thing, but any chance we can make the top bar more "immersive"?

<img width="209" alt="screen shot 2018-07-16 at 12 20 31 pm" src="https://user-images.githubusercontent.com/5134133/42743036-d6458ef4-88f2-11e8-812e-bcf79baf4315.png">

Currently the bar with the traffic lights looks semi-native - not really native but has a gradient. Below are Atom and VSCode, and I think this "edgeless" design looks much nicer:

<img width="186" alt="screen shot 2018-07-16 at 12 20 18 pm" src="https://user-images.githubusercontent.com/5134133/42743054-f96ef51e-88f2-11e8-80f2-431dbc42ffe3.png">
<img width="245" alt="screen shot 2018-07-16 at 12 20 40 pm" src="https://user-images.githubusercontent.com/5134133/42743056-fc480c80-88f2-11e8-815c-36174c0293e0.png">

**Comment by shiftkey** [comment]
@danqing thanks for the feedback. 

I went digging for recent discussions on this, but I could only find where we settled on moving from the original gray title bar to a darker version here: https://github.com/desktop/desktop/issues/549#issuecomment-254923749 I think we wanted to retain the clear region that supports maximizing, but the original gray made us all rather sad.

I'll also point out that since that original comment, Slack has returned to a gray title bar with gradient:

<img width="242" src="https://user-images.githubusercontent.com/359239/42757142-3532d2be-88d5-11e8-9807-42115c225fa9.png">
 
> (at least on Mac)?

Because macOS integrates with the menu bar it doesn't need to support a window menu. On Windows, we choose to override the default menu (which doesn't fit nicely with the dark header) to draw our own menu:

<img width="993" src="https://user-images.githubusercontent.com/359239/42757373-2dfcb36a-88d6-11e8-8c6c-6c391d958cdf.png">

**Comment by danqing** [comment]
<img width="171" alt="screen shot 2018-07-16 at 8 00 28 pm" src="https://user-images.githubusercontent.com/5134133/42757525-ff9acf04-8932-11e8-834d-a9db82785e6f.png">
Slack uses a custom bar if you have multiple workspaces it seems.

Anyway, I understand that there are many important features to implement and this is a minor thing. Just this looks a tad better..

**Comment by shiftkey** [comment]
@danqing The title bar [component](https://github.com/desktop/desktop/blob/master/app/src/ui/window/title-bar.tsx) and [stylings](https://github.com/desktop/desktop/blob/master/app/styles/ui/window/_title-bar.scss) are here, if someone wants to hack on it and see if they can figure out something better than what we currently have.

**Comment by billygriffin** [comment]
Thanks for the suggestion @danqing!

While this idea does seem interesting, we feel the time and effort to spend here are currently better spent elsewhere. We have limited resources to invest in the project, and we want to ensure our efforts are going toward solving the highest priority problems. That said, we do really appreciate you bringing it up and the comparison to other apps.

I'm going to close this out so we can keep our issue tracker at a manageable level. Thanks again!
