### ISSUE TITLE
plz Add  FontSize tuning

### ISSUE THREAD

**Issue by heartacker** [desktop/desktop#5179]
font size is two small,Thx

**Comment by steveward** [comment]
Thanks for reaching out! Is the issue you have with font sizes similar to https://github.com/desktop/desktop/issues/3543? There are some workarounds to increase the font size mentioned in that issue thread. You can increase the font size by using the zoom option, which can be accessed from the GitHub Desktop file menu by going to `View` > `Zoom In`. 

It would be helpful if you edit the issue body to fill out the required template -- we require the template to be filled out with all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway. 😀

**Comment by shiftkey** [comment]
Closing this out due to inactivity. @heartacker I've re-opened #3543 to investigate that further so please follow along with that issue.
