### ISSUE TITLE
error with branch upstream/master

### ISSUE THREAD

**Issue by vincent3569** [desktop/desktop#5181]
## Description
that is probably a follow up of this issue https://github.com/desktop/desktop/issues/4130

I want to keep my fork sync with the original master (upstream)
so I follow this guideline:
https://help.github.com/articles/configuring-a-remote-for-a-fork/
https://help.github.com/articles/syncing-a-fork/

as far I can see, the 1st steps add a new branch upstream/master in github Desktop
as far I understand the help of github Desktop, I can't sync my fork from the upstream with github Desktop, so I follow the 2nd steps to do it with git bash. And it works well.

But in github Desktop, if I want to change the branch to upstream/master, I have this error message:
A branch with that name already exists
![capture](https://user-images.githubusercontent.com/1224809/42873637-c9cbadd2-8a7f-11e8-99fd-9129bf6c7669.PNG)

## Version
* GitHub Desktop: 1.3.0-beta2
* Operating system: window10

## Steps to Reproduce
see the description above

### Expected Behavior
I wish it could be possible to sync fork from upstream with github Desktop (more simple than using git).
And, at least, this error message should not appear in github Desktop

### Logs
[2018-07-18.desktop.beta.log](https://github.com/desktop/desktop/files/2205229/2018-07-18.desktop.beta.log)

there is something strange in this log:
`2018-07-18T09:35:49.910Z - warn: [ui] fetchRepository: 'vincent3569/zenphoto-perso' returned a 404`
but this repository exists on github (https://github.com/vincent3569/zenphoto-perso).
and in fact, I can push my commit to github, and I have this error:

![capture2](https://user-images.githubusercontent.com/1224809/42873681-e5bb1d98-8a7f-11e8-8f89-f8c65c9c5cdd.PNG)

**Comment by shiftkey** [comment]
@vincent3569 apologies for the delay in replying to this.

> I wish it could be possible to sync fork from upstream with github Desktop (more simple than using git).

We're going in a slightly different direction with Desktop to what those docs outline, and I'm going to walk you through the steps using `shiftkey/desktop`, which is a fork of `desktop/desktop`.

For convenience, I just made a fresh clone of the fork in Desktop to do this - your setup might be different currently. 

### Updating `master`

1. Open the repository in Desktop, and switch to the default branch

<img width="593" src="https://user-images.githubusercontent.com/359239/43219502-e48c79c8-901d-11e8-8d79-ab62d136c04b.png">

In the background the app periodically checks if there are new commits on the default branch, and if so the blue dot appears next in the History tab.

2. Switch to the history tab, and be greeted by this message:

<img width="588" src="https://user-images.githubusercontent.com/359239/43219563-08bea4ba-901e-11e8-8161-496370989d94.png">

This gives you some context that there are commits available to merge into this branch, and two options:

  - `Merge` takes you to the merge commit dialog, ready to commit

<img width="534"  src="https://user-images.githubusercontent.com/359239/43219655-4f08934a-901e-11e8-9d58-3a81c6e9ca0c.png">

 - `View commits` shows the ahead/behind details, and let's you then merge in the changes

<img width="360" alt="screen shot 2018-07-25 at 3 27 11 pm" src="https://user-images.githubusercontent.com/359239/43220020-44ba0eb8-901f-11e8-8168-c3b6f03e7d84.png">

Both of these are the same outcome, one just lets you see the details of what's going to be merged.

### Manually merging upstream

If you want to do this manually to some arbitrary branch, here's the steps:

1. Checkout the branch in your fork

2. Like before, switch to the History branch, but now in the compare list, select `upstream/master` from the list of available branches

3. View the ahead/behind details, and then merge into your branch:

<img width="367" src="https://user-images.githubusercontent.com/359239/43220072-6f7547bc-901f-11e8-8663-de3e390b1b12.png">

> `2018-07-18T09:35:49.910Z - warn: [ui] fetchRepository: 'vincent3569/zenphoto-perso' returned a 404`
>
> And, at least, this error message should not appear in github Desktop

I'm really not sure about this one - manually retrieving this repository through the API works fine, so I'm not sure why we're 404ing.

Are you able to share the remotes you have configured for this repository?

```
$ git remote -v
```

**Comment by vincent3569** [comment]
@shiftkey: your forks seems to go in the right direction for merging upstream in a fork!

here you can see my remotes configured for my repository:
![capture](https://user-images.githubusercontent.com/1224809/43305584-a390df84-9178-11e8-999f-1bddf225646a.PNG)


and my .git config file:
````
[core]
	repositoryformatversion = 0
	filemode = false
	bare = false
	logallrefupdates = true
	symlinks = false
	ignorecase = true
[submodule]
	active = .
[remote "origin"]
	url = https://github.com/vincent3569/zenphoto-perso.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
	remote = origin
	merge = refs/heads/master
[remote "upstream"]
	url = https://github.com/zenphoto/zenphoto.git
	fetch = +refs/heads/*:refs/remotes/upstream/*
````

I'm unable to see errors in it

**Comment by shiftkey** [comment]
@vincent3569 

Apologies fro the delay in this, but this might be a clue:

<img width="425" src="https://user-images.githubusercontent.com/359239/43854145-689901a0-9b18-11e8-921c-8daa88966d69.png">

Is this the repository that has been renamed to `https://github.com/vincent3569/zenphoto-dev`? It's now 404ing for me when I hit it from Fiddler.

What happens if you change this remote URL?

```
> git remote set-url origin https://github.com/vincent3569/zenphoto-dev.git
```

I suspect that something has changed with the redirects when you rename a repository - it might only remember the previous name, I'm not aware of what's changed here.

**Comment by vincent3569** [comment]
hi
when I created the issue, the remote was `zenphoto-test`.
as I can't work with upstream, I often delete my repository in order to fork the original master (the upstream) to be sync with it.
I am on hollidays, but I will have another try later in august.

**Comment by shiftkey** [comment]
@vincent3569 thanks for the update. I suspect there's some combination of these two issues that's related here, but I'm unclear on the order:

 - renaming the fork repository - this should add redirects
 - deleting the fork to simplify keeping up to date with upstream - probably removes the redirects

Please try out the new compare steps outlined here to keep your fork up to date with upstream https://github.com/desktop/desktop/issues/5181#issuecomment-407853248.

For the moment, I'm going to close this out so we can keep the backlog under control, but please follow up if there's anything else interesting to share.

**Comment by wireddown** [comment]
Hi, the Past! I got here from a Google search for _github desktop "a branch with that name already exists" master_ because I wanted to update my fork from the original upstream repository. When I tried switching to its `master` branch, Desktop showed that error message.

# Desktop 1.5.0

In this version, the workflow appears to have changed.

1. Switch to your default branch using the **Current branch** dropdown
    * For the use case of updating your fork from the upstream original, this is typically your `master` branch.
1. Open the *Current branch* dropdown again.
1. Below the list of your branches, at the bottom, there's a button called **Choose a branch to merge into _master_**
1. Click that and select the name for your fork's upstream branch.
    * Often this is called `upstream/master`.

# Feedback on the 1.5.0 workflow

* When I open my repository in Desktop, **I don't know whether or not the upstream repo has any new changes to consider for merging** -- the *History* tab doesn't have a "look at me!" dot like @shiftkey's screenshot. I acknowledge that a repo might have many branches to compare against, but if you don't want to guess which one is the tracking/upstream branch, would you let users configure which one to "auto compare"?
* The error message is incomplete -- there's no remedy or suggestion offered ([4th bullet](https://docs.microsoft.com/en-us/windows/desktop/debug/error-message-guidelines#best-practices)). When `master` or `origin` or `upstream` is in the name of the branch, it seems reasonable to guess that the user is trying to update their fork and adding _"If you're trying to update from another repository that has a branch with this name, see $HELP_URL for more information."_ would at least give the user a next step rather than a dead end.
* Going further, this workflow seems like a hot path through the application. Would adding mouse/keyboard accelerators help users avoid these pitfalls?

## Missing "dirty dot"

![compare-branches](https://user-images.githubusercontent.com/8404598/48923522-20d88080-ee64-11e8-809c-c14701015fa3.gif)

**Comment by HunterDG** [comment]
Same issue - December 2019 - no 'dirty' dot though upstream/master has changed, and "a branch with that name already exists" when trying to switch to it.

**Comment by Whippsie** [comment]
Same issue - January 2020. Trying to also keep a fork up to date. 

Can't use the previous answer (@wireddown ) above because I am trying to only sync a branch. The master is already up to date.

A possible solution I think would to be able to remove the branches in the "Recent branches" tab. This way you could then switch to origin/branchname and merge with upstream/branchname rather than the opposite (which gives a permission error since you don't have access to the original project).

**Comment by Gangula2** [comment]
Sam issue - September 2020
