### ISSUE TITLE
Blank GitHub Desktop window after closing GitHub Desktop after installation

### ISSUE THREAD

**Issue by RusticDogDev** [desktop/desktop#5189]
Once I finish installing GitHub desktop, it opens the GitHub desktop window and everything is working fine,
but once I close the program and re-open it either one or two more times I get a completely black blank window.
I looked at the console and got no errors
I've reinstalled multiple times, get same blank window.
I've updated my display drivers,
I've deleted the GitHub Desktop %Appdata% files.
I'm using Windows 10 Version 1803 (OS Build 17134.165)

![git](https://user-images.githubusercontent.com/30129613/42905796-f8decac2-8ad0-11e8-9b32-eb5a9dad675e.PNG)
![git2](https://user-images.githubusercontent.com/30129613/42905869-22b47a68-8ad1-11e8-9bae-1bd5c70e3f0a.PNG)

Thanks

**Comment by shiftkey** [comment]
@RusticDogDev thanks for the report.

Are you working on a laptop? We've had some reports of some graphics cards causing issues with Desktop due to the lack of hardware acceleration, and we have a [workaround](https://github.com/desktop/desktop/blob/master/docs/known-issues.md#i-get-a-black-screen-when-launching-desktop) that might help you get back to a happy place.

**Comment by RusticDogDev** [comment]
That was quick.
Yes I'm working on a laptop with an AMD Radeon discrete graphics card.

That seems to have done the trick!
Thank you! :)

**Comment by shiftkey** [comment]
@RusticDogDev thanks for confirming the workaround!
