### ISSUE TITLE
I cannot open any project

### ISSUE THREAD

**Issue by Tanayban** [desktop/desktop#5195]
## Description

It is just giving the message of cloning error

## Version

* GitHub Desktop:

* Operating system:

**Comment by shiftkey** [comment]
@Tanayban thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Could you also attach the full log files generated by Desktop? The **Help** | **Show Logs in Explorer/Finder** menu items should open the logs folder, and inside those are the log files generated by day. This will provide some more information to help troubleshoot.

Thanks for understanding and meeting us half way 😀

**Comment by shiftkey** [comment]
Closing this out due to inactivity.

@Tanayban if you're able to fill out the template and provide more details about the issue we're happy to revisit this.
