### ISSUE TITLE
fatal: not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by shirinsheikh** [desktop/desktop#5228]
## Description

in local repository is not opening. Its showing the (Not a git repository ) error.

## Version

* GitHub Desktop:

* Operating system:

**Comment by shiftkey** [comment]
@shirinsheikh Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by shiftkey** [comment]
Closing this out due to inactivity. @shirinsheikh if you're able to fill out the template so we can reproduce the issue we're happy to revisit it.
