### ISSUE TITLE
Change local branch directory?

### ISSUE THREAD

**Issue by CreatorVilius** [desktop/desktop#5236]
How do i change local branch directory?

My web files are outside my app and i want to put those files inside my Local Branch `web`, how do i do it?

Tried to search all buttons and found nothing.

**Comment by iAmWillShepherd** [comment]
> How do i change local branch directory?

![2018-07-24 13 01 22](https://user-images.githubusercontent.com/1715082/43157146-b74d129c-8f41-11e8-8c37-65b185365cc3.gif)

> My web files are outside my app and i want to put those files inside my Local Branch web, how do i do it?

You just need to copy the files into your `web` directory while you have the branch you want checked out. 

Since there is no issue with Desktop itself, I'm going to close this issue out to ensure our backlog stays small. You will still be able to reply to this issue so no need to worry about it going unnoticed 👍
