### ISSUE TITLE
No me puedo loguear en la aplicación de escritorio

### ISSUE THREAD

**Issue by Antonio830** [desktop/desktop#5237]
<img width="832" alt="captura de pantalla 2018-07-24 a la s 13 26 47" src="https://user-images.githubusercontent.com/40401851/43158426-40f5ff38-8f45-11e8-9383-cb256feea95c.png">
En el sitio web si puedo iniciar pero en la aplicación de escritorio no

**Comment by shiftkey** [comment]
@Antonio830 thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by JosephTLyons** [comment]
I get this message when I’ve deleted a repo from GitHub.com and try to access it from GitHub.  I have to use the terminal command to delete the remote url:

https://help.github.com/articles/removing-a-remote/

Then Desktop will let me republish the repo, as long as I have a local copy of it.

**Comment by JosephTLyons** [comment]
This may not be your issue, but that is the only time I see that message on my end.

**Comment by shiftkey** [comment]
Closing this out due to inactivity. @Antonio830 if you're able to fill out the template to help us troubleshoot the issue we're happy to revisit it.
