### ISSUE TITLE
Default Commit Message Text

### ISSUE THREAD

**Issue by JosephTLyons** [desktop/desktop#5240]
**Is your feature request related to a problem? Please describe.**
It is not related to a problem, it is more related to convenience of use.

**Describe the solution you'd like**
On GitHub.com, if you edit a single file, the default commit text "Update `filename`" appears, which is actually quite useful in some cases when making small tweaks to non-code files (Markdown files, CHANGELOGs, etc.).  It would be nice if this feature was available in Desktop.  I would assume it would only be provided if the user had only one file selected, or it could go further and say "Update `filename`, `filename`, ..." if multiple files were selected, but I think having it work with only one file is fine.

**Describe alternatives you've considered**
Really there are none, a lot of times I just manually insert this default commit message text when making small, trivial commits.

**Teachability, Documentation, Adoption, Migration Strategy**
Users will be able to use this to increase their workflow speed.  Many times, I find myself correcting 4 or 5 mistakes, back-to-back, and committing each one with default text of "Update `filename`".  Having this text show up automatically would increase the speedy workflow of Desktop.

**Comment by iAmWillShepherd** [comment]
Thanks for taking the time to open an issue! 🙇 

I can definitely see how this is useful and I'm hoping we can work together to hash out what this would look like.

> I would assume it would only be provided if the user had only one file selected, or it could go further and say "Update filename, filename, ..." if multiple files were selected, but I think having it work with only one file is fine.

How do you imagine this working with multiple files if we choose not to have default commit messages for multi-file changes? I'm asking because Git has a convention of keeping commit summaries short and having a default commit message that includes an arbitrary number of files will go against that convention.


Additionally, for the case of one file, do you have any ideas on how to surface the fact that a commit message will have a default value on commit? Initally I jumped to using the `placeholder` attribute on `input` elements, but then we'd have an inconsistent experience where you sometimes have to give a summary and others times you may not.

**Comment by shiftkey** [comment]
> How do you imagine this working with multiple files if we choose not to have default commit messages for multi-file changes?

The web editor on GitHub only lets you commit one file at a time, so they have the luxury of just defining this placeholder and not worrying about multiple files.

My two cents: this could be the pre-filled text if you only have one file selected to commit. Otherwise I would leave it empty because the user needs to provide more context.

**Comment by JosephTLyons** [comment]
@shiftkey I was thinking the same thing, only fill out the default commit message if one file is selected.  I almost mentioned the same fact you did, that on GitHub.com, only one file can be changed at a time, so it is limited in that respect and Desktop could just implement it to only work with one file.  And as you said, if multiple files are selected, it should display the same message that it currently displays, which is something along the lines of “a commit message is needed.”

**Comment by shiftkey** [comment]
cc @billygriffin - would love your thoughts on how we should proceed with this

**Comment by iAmWillShepherd** [comment]
I think if we were to go with the pre-filled text box, we'd have to make it super obvious why you're able to commit one file without giving a commit summary and unable to do the same thing when multiple files are selected. 

Initially, I was thinking we can use the placeholder text for that, but it sounds like what you're suggesting is to set the input's value to some default message. If we go that route, I can see this being easier to implement as we'd be able to take advantage of all the logic we already have in place for enabling/disabling the commit button.

**Comment by JosephTLyons** [comment]
@iAmWillShepherd I'm not entirely sure how it would be implemented, as I am not familiar with the Github Desktop code, but I assume text would be greyed out in both scenarios:

- If one file is selected, there would be greyed-out text stating "Update `filename`", and the commit button would be accessible.  The minute you place your cursor in the field and insert a character, the greyed out text would disappear, like that of GitHub.com

<img width="919" alt="screen shot 2018-07-24 at 5 55 40 pm" src="https://user-images.githubusercontent.com/19867440/43168319-e3efd090-8f6a-11e8-8d12-47dd3a6717f5.png">
<img width="929" alt="screen shot 2018-07-24 at 5 55 47 pm" src="https://user-images.githubusercontent.com/19867440/43168324-e5c1cd10-8f6a-11e8-9329-611598a90a0d.png">


- If more than one file is selected, there would be greyed-out text stating "Summary (required)", and the commit button would be deactivated.

**Comment by JosephTLyons** [comment]
Yes, this sounds exactly like the workflow improvement I was thinking :)

**Comment by iAmWillShepherd** [comment]
cc @ampinsk @donokuda for design input.

**Comment by billygriffin** [comment]
@ampinsk and I chatted about this, and we both agree that this feels low risk to implement, could speed up people's workflow as @JosephTLyons noted, and is consistent with dotcom.

@shiftkey @iAmWillShepherd Do you think this would be a reasonable `help-wanted` and `good-first-issue` candidate?

**Comment by JosephTLyons** [comment]
Sounds great!

**Comment by redSlug** [comment]
I'm looking at this

**Comment by redSlug** [comment]
Seeking clarification: in the case that the file is in a directory, do we want to display the full file path, or just the file name in the placeholder text? I think the full file path would be a better user experience because it would eliminate confusion. Thoughts @outofambit @lean257?

**Comment by outofambit** [comment]
@redSlug @lean257 I am leaning towards parity with github.com, which is just the filename.

<img width="1074" alt="file edit commit screenshot" src="https://user-images.githubusercontent.com/964912/43663972-3b55fd20-9739-11e8-86a1-0b391f26bdd8.png">

any thoughts @desktop/design?

**Comment by donokuda** [comment]
> Seeking clarification: in the case that the file is in a directory, do we want to display the full file path, or just the file name in the placeholder text? I think the full file path would be a better user experience because it would eliminate confusion. 

I'm with @outofambit on keeping it consistent with github.com and using only the filename.

Another reason why I would lean towards the filename only is that the full path might be too long for the input field, which might end up pushing the filename out of the textfield view.

Thanks for tackling this! ✨ 😄

**Comment by JosephTLyons** [comment]
I agree with just the filename and no path.  Thanks for picking this up!

**Comment by redSlug** [comment]
@shiftkey to add the filename to the commit message, for the case that there is only one file, we first need to have some way of keeping track of the state of which files are checked, so if there is just one file checked, we can know what file it is and put it in the placeholder. do you know if this already exists?

To provide a little more context, we already have `selectedFiles` and `selectedRows` and `this.props.selectedFileIDs`, but this referrers to items which the mouse has selected / highlighted, but not checked. 

If there is not already a way of keeping track of which check boxes are checked, these are two possible approaches:

-  add a `checked` field to `WorkingDirectoryFileChange` or 
- to add `this.props.checkedFileIDs`, similar to `this.props.selectedFileIDs` to the store.

I'm leaning toward the first option, since @outofambit mentioned possibly ripping out the redux-ish code. 

Do you have any thoughts or preferences regarding these two approaches? 

Also, just to give you a heads up, I’m not sure how much more time I’ll be able to commit to this. @lean257 and I have been looking at it together. She might have more bandwidth than me

**Comment by shiftkey** [comment]
@redSlug I don't think we need to add extra fields here to identify which files are included in the commit. I was able to use this snippet in `app/src/ui/changes/changes-list.tsx` to filter on files that were marked for inclusion:

```ts
    const filesSelected = this.props.workingDirectory.files.filter(
      f => f.selection.getSelectionType() !== DiffSelectionType.None
    )
```

It might look a bit confusing, but already leverages our existing checks for files that are partially staged for committing.
