### ISSUE TITLE
Not Properly Synced Up

### ISSUE THREAD

**Issue by kvinnedge** [desktop/desktop#5249]
## Description

The desktop tool did not show that my local repository was out of date with remote and therefore prevented me from fetching the latest checkins.

## Version

* GitHub Desktop:

* Operating system:

**Comment by shiftkey** [comment]
@kvinnedge Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Also, could you attach the full log files? The **Help** | **Show Logs in Explorer/Finder** menu items should open the logs folder, and inside those are the log files generated by day. This will provide some more information to help troubleshoot.

Thanks for understanding and meeting us half way 😀

**Comment by shiftkey** [comment]
Closing this out due to inactivity. @kvinnedge if you're able to fill out the template and provide details so we can reproduce this problem we can revisit this.
