### ISSUE TITLE
Add new repo-level settings

### ISSUE THREAD

**Issue by iAmWillShepherd** [desktop/desktop#5254]
**Is your feature request related to a problem? Please describe.**

The granularity of app preferences prevents people from opting out of new features for specific repos. This all-or-nothing approach should be improved.

![screen shot 2018-07-25 at 3 39 27 pm](https://user-images.githubusercontent.com/1715082/43226261-f6b6a24c-9020-11e8-86c3-d87902573ac2.png)

**Related issues:** #5230, #5042

Ideally, we can add these new repository-level settings:
1. Enable/Disable NDDB* - #4646 
1. Enable/Disable More repo info* -   #4770

`*` indicates potential performance gains

I considered just adding these to our global app settings, but I don't feel that's the correct level of granularity. By doing it at the global level, people will have to choose between not getting any notifications or getting all the notifications. Since all repositories are not created equal, some repos will produce tons of notifications while others will be fine. So in short, we want more granularity that our global preferences cannot provide.

![screen shot 2018-07-25 at 3 39 15 pm](https://user-images.githubusercontent.com/1715082/43226271-ff521f3a-9020-11e8-9a4e-d0d3fbec3259.png)

I'm not too sure what a design would look like, but maybe we can have 2 tabs:
1. Git specific settings (Remotes, git ignore, etc)
1. Desktop specific settings (Diff line-endings, NDDB, repo updates, etc)

cc @desktop/core

**Comment by billygriffin** [comment]
Thanks for introducing this discussion @iAmWillShepherd!

A couple thoughts: I would just say that we should be *super* deliberate about things that belong at the repo level, as it does get you more granularity, but has the potential of introducing a lot of cognitive load (instead of managing one setting, if a general preference of mine changes, I'm now expected to change the setting for *every single repo*, which would be bad), and also confusion. 

A possible way around this is for the ability to configure something to live at the repo level, but still be possible to do something like "apply this to all repositories."

**Comment by iAmWillShepherd** [comment]
> I'm now expected to change the setting for every single repo, which would be bad), and also confusion.

That's one of the things I didn't have a good answer for. I like your idea to have a _master switch_ in the app preferences. I'm not sure how that will behave though. Right now, I'm thinking we should make app-preferences take precedence over repo settings instead of resetting repo settings to be whatever is in app preferences (or vice versa so that repo settings take precedence over app prefences).

**Comment by billygriffin** [comment]
I think it's more like if you adjust the setting on one repo, there's an obvious way *in that same context* to let us know that you want that to apply to all your repos. There wouldn't be separate menus. I'd be interested in @ampinsk's thoughts on how we might approach that, assuming we agree that users do want to optionally configure certain settings for their repos.

**Comment by shiftkey** [comment]
> Right now, I'm thinking we should make app-preferences take precedence over repo settings instead of resetting repo settings to be whatever is in app preferences (or vice versa so that repo settings take precedence over app preferences).

I'd love to identify a compelling example of a feature that a user might want to enable globally, but disable for a specific repository (or vice versa), because maybe there's an interim step in here to do rather than go the full journey right now.

**Comment by billygriffin** [comment]
+1 to @shiftkey on identifying specific areas where this is applicable and would be different from repo to repo and/or globally but exceptions for certain repos.

**Comment by billygriffin** [comment]
I'm going to close this issue because I think it's too broad and not solving a specific problem, but I think we should continue to think about it as an interesting way to potentially implement one or more things that make sense to be configurable at a repo level, in line with @shiftkey's thinking above. But we'll want to make sure there's a compelling reason to enable that configuration first.
