### ISSUE TITLE
I cannot sign in to desktop

### ISSUE THREAD

**Issue by dcastadyepsilon** [desktop/desktop#5255]
I keep getting this error, my username and password are **definitely** correct. 
<img width="437" alt="screen shot 2018-07-25 at 4 50 31 pm" src="https://user-images.githubusercontent.com/26171528/43229581-de03ab28-902a-11e8-99cd-db2bfcb5f382.png">

**Comment by iAmWillShepherd** [comment]
Thanks for reaching out!

We require the template to be filled out with all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway 😀

At the very least, details about how you are logging in (browser, username/pass, 2FA) and what version of the app you are using. Some additional context would be helpful too. Is this your first time using Desktop or did it work before and stop? What's your OS and do you have a rule in your firewall that could be blocking communication on the internet?

**Comment by shiftkey** [comment]
@dcastadyepsilon I actually think this is related to the keychain on macOS due to the mention of `passphrase` in the error message.

Can you have a read of the workaround instructions [here](https://github.com/desktop/desktop/blob/master/docs/known-issues.md#the-username-or-passphrase-you-entered-is-not-correct-error-after-signing-into-account---3263) to see if that enables Desktop to add the details it needs into your keychain?

**Comment by shiftkey** [comment]
Closing this out due to inactivity. @dcastadyepsilon if the workaround mentioned in my earlier comment doesn't help, could you answer the questions @iAmWillShepherd asked earlier? This will help us understand the situation and potentially troubleshoot the underlying issue.
