### ISSUE TITLE
Repository selection

### ISSUE THREAD

**Issue by BananaAcid** [desktop/desktop#5275]
There are 3 things, i really dislike.

1. After an update, my cloned repositories are not in the list anymore - I have to frag in all local folders.
Solution: configure a home folder for my cloned repos, to get most of them into the overview again.

2. cloning a repo from my github: finding and selecting them is un-intuitive. I always have to find this list of my github repos "clone repository > Github.com".
Solution: after logging in, I would like to see all of them right in the list of already cloned repos, grayed out, with a filter button to show or hide them.
- double clicking them could get me going in seconds. (I am using multiple computers: this could also make it easier)

3. selecting my github base folder in "clone repository > local path" again, it shows a "destination already exists".
YES, that is the same folder the GitHub-App had been pointing to before, so it will of course contain exiting gitHub repos.
- I CAN NOT clone other repos, unless I move all subfolders out, clone the new one in the now empty folder, and move the previously cloned back in.

**Comment by iAmWillShepherd** [comment]
Thanks for taking the time to open an issue! 🙇 

Regarding your last item,
> selecting my github base folder in "clone repository > local path" again, it shows a "destination already exists".
Once you enter a repo to clone, that warning goes away. There is no need to clear the folder and clone.

_this gif is long because I have a ton of repos_ 😮 
![2018-07-30 10 30 24](https://user-images.githubusercontent.com/1715082/43407269-df368224-93e3-11e8-85e7-1576f1ca91cb.gif)

**Comment by iAmWillShepherd** [comment]
> After an update, my cloned repositories are not in the list anymore - I have to frag in all local folders.

Could you send along your log for this (_Help -> Show Logs in Finder_)? You repos should not be removed after updating Desktop and this is the first report of this behavior we've received.

**Comment by BananaAcid** [comment]
Alright - works here as well. The first one was the one I wanted to clone - and was not there.  The warning goes away when I click on different repos and then back to the topmost. Thanks.

Second: I just realized, I have 2 APPS (Windows): "GitHub" - Desktop App and "GitHub Desktop" as well. The new one after updating was "GitHub Desktop", Icon BG is white. Config did not shift over. I thought it was the same app, but the update installed a new one.

**Comment by steveward** [comment]
> Second: I just realized, I have 2 APPS (Windows): "GitHub" - Desktop App and "GitHub Desktop" as well. The new one after updating was "GitHub Desktop", Icon BG is white. Config did not shift over. I thought it was the same app, but the update installed a new one.

The `GitHub` application is the classic version of the app that is no longer being supported. Since the new version of GitHub Desktop is entirely rewritten using Electron your settings and repositories will not carry over. If you have a large number of repositories to still add you can bulk-select the repositories in File Explorer and then drag-and-drop them directly into GitHub Desktop to add them. I believe this answers your first question as well -- let me know if I can clarify anything further.

> cloning a repo from my github: finding and selecting them is un-intuitive. I always have to find this list of my github repos "clone repository > Github.com".
> Solution: after logging in, I would like to see all of them right in the list of already cloned repos, grayed out, with a filter button to show or hide them.

Thanks for the feedback. Is the specific frustration you have related to needing to navigate to the menu option to clone a repository? If so, you can use the shortcut `Control + Shift + O` to quickly access the `Clone` view.

**Comment by BananaAcid** [comment]
Thanks. All clear.

"Is the specific frustration you have related to needing to navigate to the menu option to clone a repository?"
Introducing this tool to 3 companies and their scripters, they faced the same frustration as my self. Feeling like creating a new repo, even thought is states to clone, but is hidden behind a new dialog even thought being logged in. It is not intuitive. 
You may call my suggestion a newbie hurdle, or usability enhancement for non hardcore coders.

**Comment by iAmWillShepherd** [comment]
Ahh, got it. We currently do not import repositories from the old application into the new version of GitHub Desktop. We do support dragging-and-dropping a selection of repositories though, so that should make the migration a little bit smoother.

I'm going to go ahead and close this issue as this seemed to be a mix up with the old app. Feel free to reopen if you are still running into those problems you listed.
