### ISSUE TITLE
Commits didn't got pushed event though I did pushed them

### ISSUE THREAD

**Issue by lsonnino** [desktop/desktop#5276]
I have GitHub Desktop v1.2.6 and I just discovered that a lot of my last commits didn't get saved even though I committed them and pushed them from the desktop app. Unfortunately, I cancelled the folder from my computer thinking that every commits I pushed did actually get pushed. Does anyone know how to prevent it from happening again and if there is maybe a magical way to recover those lost commits ?
Thanks in advance

**Comment by lsonnino** [comment]
It was a month ago so I do not remember the details. I remember I had troubles working with someone else on the same project with IntelliJ because of the ```.idea``` folder that didn't got ignored in the ```.gitignore```. I committed and pushed the changes and it looked like it worked.
Unfortunately, given that those commits were done the last last month, the logs got delated and the local folder containing the git clone as well. I don't think there is much to do here...

**Comment by steveward** [comment]
@lsonnino if you are interested I would be happy to look into this further. Would you mind contacting GItHub Support directly via our [contact form](https://github.com/contact)? Make sure to mention GitHub Desktop so that your email gets routed to me. It would also be helpful if you could specify the name of the repository, which will allow me to take a look on our end to see if there is anything in the logs to indicate what might have happened here. I'm going to close this issue out, but please don't hesitate to reach out.
