### ISSUE TITLE
when i tries to push 

### ISSUE THREAD

**Issue by anupkage** [desktop/desktop#5277]
## Version

* GitHub Desktop:

* Operating system:

**Comment by j-f1** [comment]
Thanks for reaching out!

We require the template to be filled out when submitting all issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway :grinning:

**Comment by shiftkey** [comment]
Closing out due to inactivity. @anupkage if you're able to fill out the template to provide more details about the issue you're seeing we're happy to revisit it.
