### ISSUE TITLE
Unable to fetch repository - authentication failure in new desktop app but not in prior version of github (unnecessary Sequel (3.3.6.1))

### ISSUE THREAD

**Issue by willett** [desktop/desktop#5288]
I all of a sudden lost the ability to fetch a specific repository from Github Desktop (1.3.0) with an authentication error (see logfile entry below).

I CAN fetch it using the old version of Github Desktop (unnecessary Sequel (3.3.6.1)).

Logfile entry:
2018-07-30T21:15:47.420Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: Sunshine - willett (has token)
2018-07-30T21:15:48.305Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

(The error was parsed as 2: Authentication failed. You may not have permission to access the repository or the repository may have been archived. Open options and verify that you're signed in with an account that has permission to access this repository.)

**Comment by steveward** [comment]
👋 @willett 

The new Electron version of GitHub Desktop (v1.3.1) does not automatically handle configuring SSH keys like the previous version of GitHub Desktop (v3.3.6.1) did. We recommend using HTTPS authentication instead of SSH, but if you need to use SSH you can follow the steps in this article to generate a key and add it to `ssh-agent`:

https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/

We also have a help article that walks through resolving the `permission denied (publickey)` error:

https://help.github.com/articles/error-permission-denied-publickey/

Let me know if you run into any problems with that.

I would also recommend following along in #2579 for updates about improving SSH support in GitHub Desktop. Please feel free to drop any feedback you have into that issue.

**Comment by OlegShatin** [comment]
Hi. I just set up GitHub desktop and faced with same issue with existing ssh key. (Logs identical with above). I already used repo before with ssh (through Visual Studio team explorer). I also tried to run commands from logs in Git Bash and they runs successful.
I also did:
- run `eval $(ssh-agent -s)`
- run ` ssh-add ~/.ssh/id_rsa` - where my key with passphrase is stored.
- ensure my key has been added with `ssh-add -l`
- run GitHub desktop and try to fetch - unsuccesseful.
What else I should do?
