### ISSUE TITLE
error 128

### ISSUE THREAD

**Issue by elielrob** [desktop/desktop#5303]
## Version

* GitHub Desktop:

* Operating system:

**Comment by billygriffin** [comment]
Thanks for reaching out @elielrob!

We require the template to be filled out when submitting all issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

This looks like it might be the same as #5291 so feel free to check there for what's likely causing your issue until the PR gets released to production (likely later this week). And if it is the same, feel free to close this issue.

Thanks for understanding and meeting us halfway 😀

**Comment by shiftkey** [comment]
@elielrob I'm going to close this out because I think #5291 is the same issue, which has been addressed in `1.3.2` - please update your Desktop install and confirm this is resolved!
