### ISSUE TITLE
push failed 

### ISSUE THREAD

**Issue by ambipati** [desktop/desktop#5306]
## Description

![image](https://user-images.githubusercontent.com/37832185/43519610-c3579496-95ad-11e8-8930-a967a1d79c1f.png)
![push failed](https://user-images.githubusercontent.com/37832185/43519641-e1610710-95ad-11e8-908c-a99cf7b487bc.png)

## Version

* GitHub Desktop:

* Operating system:

**Comment by steveward** [comment]
👋 @ambipati 

Would you mind filling out the issue template and uploading the log file?

We require the template to be filled out with all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway. 😀

**Comment by shiftkey** [comment]
Closing this out due to inactivity. @ambipati if you're able to fill out the template and attach the log files from **Help** | **Show logs in Explorer** we're happy to revisit this issue.
