### ISSUE TITLE
thank

### ISSUE THREAD

**Issue by machunyugit** [desktop/desktop#5309]
![qq 20180801213820](https://user-images.githubusercontent.com/29645994/43525016-44bc7018-95d3-11e8-8f5d-7458670b6f25.png)

I cloned my project on github locally and reported this error, but I did not have this problem when I cloned it before. I would like to ask this is the reason, thank you very much.

github version 1.3.1

**Comment by shiftkey** [comment]
@machunyugit thanks for the report!

I believe your issues is the same as https://github.com/desktop/desktop/issues/4832, because of system config entry that looks like this:

```
file:"C:\ProgramData/Git/config" http.sslcainfo=/bin/curl-ca-bundle.crt
```

You should be able to see this entry by running this command:

```
$ git config -l --show-origin
```

This entry is no longer valid (Git installations should not be adding this entry to this file) and removing this entry:

```
[http]
  sslCAinfo = /bin/curl-ca-bundle.crt
```

from `C:\ProgramData\Git\config` should address the issue for Desktop.

**Comment by machunyugit** [comment]
Thank you very much, I solved the problem.

**Comment by shiftkey** [comment]
@machunyugit I'm glad you were able to get to the bottom of it!
