### ISSUE TITLE
diff markers should not be selectable

### ISSUE THREAD

**Issue by IdanAdar** [desktop/desktop#5321]
If web GitHub can do it, so can GitHub Desktop.
https://blog.github.com/changelog/2018-07-31-unselectable-diff-markers/

**Comment by shiftkey** [comment]
@IdanAdar we already exclude these when copying-and-pasting (see #1499 and the fix #2438)

**Comment by billygriffin** [comment]
Going to go ahead and close this since it's implemented, but if something wasn't clear or it's not working as expected, please let us know @IdanAdar.

**Comment by cfreeley** [comment]
I also just assumed this feature didn't exist in this app probably for the same reason- I believe in the older client, you weren't able to select line markers at all, so it was clear visually that they weren't being copied. When I upgraded to this client, until I actively sought out this issue, I saw that the markers were being selected and thus never tried copying pasting diffs in the client because I didn't want to have to deal with deleting the markers. Now that I know they're not copied I'll use this feature, but it would've been nice if it was visually clear these markers weren't actually being selected

<img width="229" alt="Screen Shot 2019-03-21 at 12 01 06 PM" src="https://user-images.githubusercontent.com/3210491/54766085-0f647280-4bd1-11e9-967f-50054bf1e73d.png">
