### ISSUE TITLE
the diff is too large to be displayed by default.you can try to show it anyways,but performance may be negatively impacted

### ISSUE THREAD

**Issue by StarChaw** [desktop/desktop#5355]
## Version

* GitHub Desktop:

* Operating system:

**Comment by shiftkey** [comment]
@StarChaw thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by StarChaw** [comment]
Ok,Thanks.i will do it better.I am really sorry that i can't explain my question clearly.and now i have solved my question by updating my environment.

**Comment by shiftkey** [comment]
@StarChaw no problem!
