### ISSUE TITLE
GitHub keeps popping up

### ISSUE THREAD

**Issue by LeonColombo** [desktop/desktop#5393]
Example:

> GitHub desktop keeps popping up while writing code, interrupting the process. 

**[Optional] Do you have any potential solutions in mind?**
Make it so a notification pops up and not the entire window.

Thanks

**Comment by LeonColombo** [comment]
Hello @shiftkey, none. Everytime I change something in Android Studio, GitHub Desktop pops up

**Comment by shiftkey** [comment]
@LeonColombo I suspect what is happening here is that Android Studio is referencing the old Git installation that came with GitHub Desktop on Windows. The combination of:

 - an external program trying to use the old Git Shell environment
 - the old GitHub Desktop program (named `github.exe`) being used as an credential helper
 - the new GitHub Desktop shortcut on `PATH` (named `github.bat`) being launched too
 - our CLI is just designed to launch itself, so that's why it gets prompted

I think you need to install [Git for Windows](https://gitforwindows.org/) and use that in Android Studio as our old Git Shell environment was not designed for use by external programs.

**Comment by LeonColombo** [comment]
Thank you very much, solved.
