### ISSUE TITLE
Crash while launching with no warnings

### ISSUE THREAD

**Issue by danielhaitao** [desktop/desktop#5396]
System: windows 7 with .net framework 4.5.2

when i opened github, the program just closed with no window or warnings.

**Comment by steveward** [comment]
Thanks for the report @danielhaitao! Could you upload the log file from GitHub Desktop to see if that gives some more information about this crash?

Windows logs location: `%APPDATA%\GitHub Desktop\logs\`

Please grab a log file from a day you experienced the crash and upload it to this issue thread.

It would also be helpful if you could fill out the rest of the issue template. We require the template to be filled out with all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway. 😀

**Comment by shiftkey** [comment]
Closing this out due to inactivity. @danielhaitao if you're able to provide more information about what you're experiencing we're happy to investigate.
