### ISSUE TITLE
Github Desktop cannot detect VSCode Version 1.26.1 on Windows 8

### ISSUE THREAD

**Issue by coder137** [desktop/desktop#5432]
On previous versions of VSCode, Github Desktop was able to open the project folders. 

However, with the recent update, I uninstalled the previous version of VSCode and installed the recommended VSCode version 1.26.1.

However, On using `Control+Shift+A` I get the following error

> Unable to open external Editor

> No suitable editors installed for Github Desktop to launch. Install Atom for your platform and restart Github Desktop to try again.

1. Is there a certain conflict when I uninstalled my older version of VSCode and installed the newer version?

2. Or is this a bug?

Additional Information

```
VSCODE VERSION
Version: 1.26.1
Commit: 493869ee8e8a846b0855873886fc79d480d342de
Date: 2018-08-16T18:38:57.434Z
Electron: 2.0.5
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
```

```
Github Desktop Version 1.3.3 (Latest)
```

**Comment by shiftkey** [comment]
@coder137 thanks for the report! This is because the default VS install now doesn't require elevation, so it is now located at a different location in the registry that Desktop isn't aware of.

We have an earlier issue tracking this #5281 and also a PR open #5420 which will go out with the next update (`1.3.4`) so keep an eye out for that.

**Comment by mirai-zoom** [comment]
ブレンダン・フォスターさま
＃5281と＃5420　難しい？

**Comment by mirai-zoom** [comment]
推奨VSCodeバージョン1.26.1をインストール？

**Comment by shiftkey** [comment]
@coder137  just to let you know that `1.3.4` has been published and should support the new User scope install.
