### ISSUE TITLE
whn im pushing updates to my repository getting this error,what i want to do this?

### ISSUE THREAD

**Issue by BROjohnny** [desktop/desktop#5436]
## Description

![image](https://user-images.githubusercontent.com/36418402/44309820-036dc380-a3ea-11e8-80be-fefd3acb1d78.png)
why im getting this error when pushing to my repository?

## Version

* GitHub Desktop:

* Operating system:

**Comment by shiftkey** [comment]
@BROjohnny thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Could you also ensure to attach the full log files? The **Help** | **Show Logs in Explorer** menu items should open the logs folder, and inside those are the log files generated by day. This will provide some more information to help troubleshoot.

Thanks for understanding and meeting us half way 😀

**Comment by BROjohnny** [comment]
i logout from the github Desktop and again log in to usingmy profile then it was fixed so im fine now thkz

**Comment by shiftkey** [comment]
@BROjohnny thanks for the update, and I'm glad you were able to get it working again!
