### ISSUE TITLE
Expand the commit message only as much as needed

### ISSUE THREAD

**Issue by smartygus** [desktop/desktop#5446]
When viewing a commit from the history, and the commit message is larger than the default view allows, you can click on the Expand button, but the expanded commit message takes up the whole right hand pane, which is often unnecessary, especially if the commit message is only a few lines longer than the default view size.

This is a huge waste of space, and means it's not possible to look at the whole commit message and diffs at the same time.

Example:

![github_desktop_expand_commit_message_space](https://user-images.githubusercontent.com/706508/44403747-88c1b700-a555-11e8-85d7-1cd9cd9fba96.gif)

Ideally, for commit messages that are shorter than a certain limit, the commit message view should expand just as much as is needed to show the full message, and the diff browser should remain visible.

Mockup:

![github_desktop-mockup-expand_commit_message_only_as_much_as_needed](https://user-images.githubusercontent.com/706508/44403834-beff3680-a555-11e8-8023-503ce7704d9c.gif)

For longer commit messages, then it could either expand to take up the whole right hand pane (current behavour), or (my preferred solution) just expand to a set limit (say 33% of the height, or 50%), where the diff browser remains viewable, and then the commit message becomes scrollable.

**Comment by smartygus** [comment]
Related to #2813, where it's suggested that the pane divider between commit message and diff viewer should be draggable. Also a good idea.

**Comment by shiftkey** [comment]
@smartygus thanks for the suggestion. I'll also cross-reference the PR where we added this current behaviour, as that shows the areas to investigate as part of changing this: https://github.com/desktop/desktop/pull/1080

I think this is related to being able to measure when content overflows, and the current behaviour of either a fixed height or showing the full height (with the ability to scroll if even that isn't enough) highlights there's a chance to see if we can handle that middle case (expand "just enough" to not obscure the commit details below).

I'm hazy on this area of the app, but I marked it as `help wanted` because this feels like a great chance for someone to dig into the area and see if they can make this better.

**Comment by billygriffin** [comment]
Do we think that #5471 solves the main issues communicated here and we can close this?

**Comment by shiftkey** [comment]
Opened #5506 to track the polish task

**Comment by smartygus** [comment]
Thanks everyone and in particular @aryyya! :)
