### ISSUE TITLE
Branch switcher for Pull Requests is slow on initial load, especially with lots of PRs

### ISSUE THREAD

**Issue by annevk** [desktop/desktop#5448]
For projects that have tens if not hundreds of outstanding Pull Requests, it takes a really long time to load those Pull Request titles in the branch switcher.

Furthermore, while that loading is happening, you cannot start searching for the branch you want to look at.

It would be much better if the UI was not gated on the load completing and the load could be influenced by what you type in the box, thereby reducing the amount of data that needs to be exchanged. (It's still somewhat puzzling to me why this takes so long to begin with, but perhaps it's an expensive query on the server?)

**Comment by annevk** [comment]
About GitHubt Desktop says 1.3.3. I'm on macOS High Sierra (both MacBook and iMac experience the same issue).

**Comment by billygriffin** [comment]
Thanks for the additional information @annevk! We're working on how we might address this and similar issues. Would you mind sharing how many PRs you've got in your project when you're noticing the slow behavior, and approximately how long it's actually taking in that case (in other words, are we talking 2 seconds or 10 seconds)? We're trying to get a sense of what might be causing this especially since you're on a newer machine and OS. 

And just to verify, you're in the tab with the below screenshot, right?

<img width="304" alt="screen shot 2018-08-24 at 6 49 43 pm" src="https://user-images.githubusercontent.com/5091167/44613274-98980000-a7ce-11e8-9cfb-5d3671299fb8.png">

**Comment by annevk** [comment]
Yes, that tab. I notice it on, e.g., https://github.com/web-platform-tests/wpt, which has >450 PRs at the moment, and it takes about a minute for them to appear after a fresh pull (fortunately cached afterwards). And yeah, the iMac I did this measurement is from last year and we got a 1gbit connection.

**Comment by annevk** [comment]
For https://github.com/whatwg/html with >80 PRs it takes over ten seconds. Projects with around 10 PRs only take a couple seconds, if that. Still seems somewhat slow, but much better comparatively.

**Comment by billygriffin** [comment]
@annevk Super helpful, thank you! Is that just after initially cloning those repos into Desktop, or is this a recurring issue (you mentioned fortunately cached afterward)? It _should_ be significantly faster after the first time, so I'm wondering whether this is a one-time per repo impact for people, or whether it's each time they're trying to interact with the PR tab in the app.

**Comment by billygriffin** [comment]
I was able to reproduce this on a very fast machine with good internet. About 90 seconds after each app restart to load the list of PRs with a repo with more than 700 pull requests. 

@annevk We're evaluating several performance (and UI when performance is necessarily inhibited) improvement vectors, so this is really helpful in framing a potential area of exploration. Thank you again!

**Comment by annevk** [comment]
It's a recurring issue. It is cached until there's new commits upstream (which happens quite frequent for these larger repositories).

**Comment by billygriffin** [comment]
@annevk Thanks so much for this issue! We're going to be looking at it in #6982, and I'd love if you'd follow along there.
