### ISSUE TITLE
Windows/WSL global gitignore not used

### ISSUE THREAD

**Issue by JaKXz** [desktop/desktop#5453]
## Description
I have `git` installed via WSL and have a global gitignore file configured like so: `core.excludesfile=/home/jasonkurian/.gitignore_global`. It seems that GitHub Desktop for Windows is not respecting the rules in this file.

Please let me know if I can provide any more information.

## Version
* GitHub Desktop: 1.3.3
* Operating system: Windows 10 Pro + Ubuntu 18.04
* Git version: 2.17.1

**Comment by shiftkey** [comment]
@JaKXz thanks for the report!

Can you confirm that the global config file mentioned above is at `%USERPROFILE%\.gitconfig`? I suspect that Git for Windows isn't able to read `/home/jasonkurian/` because this is outside the WSL "sandbox" (there's likely a more accurate word for this, but it's been a while since I've been in there).

Is there a reason why you can't store this file in your `%USERPROFILE%` directory and map to that inside your WSL `.gitconfig`, if you're trying to share your global ignore rules between environments I believe WSL has better context to interop with Win32-land currently than the other way round.

```
[core]
    excludesfile = "/mnt/c/Users/[account]/.gitignore_global"
```

**Comment by billygriffin** [comment]
Hi @JaKXz, thanks again for the issue! Hopefully @shiftkey's suggestion above will be helpful. I'm going to close this, but don't hesitate to reach out if you need more guidance, and we'll be happy to reopen the issue.
