### ISSUE TITLE
Upgrade breaks existing repo settings.

### ISSUE THREAD

**Issue by billw2012** [desktop/desktop#5461]
## Description

I just upgraded to 1.3.4 and it appears to have moved the resources folder which contained the ca-bundle.crt but not updated my local repo settings to reflect this move. So now I get an error when trying to Pull: 
"fatal: unable to access 'https://github.com/billw2012/\<my repo\>/': schannel: failed to open CA file 'C:/Users/\<my windows username\>/AppData/Local/GitHubDesktop/app-1.3.2/resources/app/git/mingw64/ssl/certs/ca-bundle.crt': No such process"
I already fixed this once by manually moving this file, but this seems like a bug in the upgrade process and I couldn't find an existing open one. #5110 looks the same and says to fill out a report if it still happens, so here it is.

## Version

* GitHub Desktop: 1.3.4 just upgraded from 1.3.3

* Operating system: Microsoft Windows [Version 10.0.16299.611]

**Comment by shiftkey** [comment]
@billw2012 can you run this command from a terminal and share the output?

```
> git config -l --show-origin
```

I'd like to confirm whether you have a `http.sslCAInfo` value already set somewhere, because Desktop doesn't need to use this (it uses the Windows Secure Channel APIs for validating SSL/TLS certificates). See #4832 for one of the earlier examples of this issue.

**Comment by DJPEREZ** [comment]
Hello @shiftkey ,

I am also encountering this issue. I am a network administrator with a bit of knowledge on software development. In my organization, we have software developers and business analysts that use GitHub. The software developers use the command line interface, whereas the business analysts use GitHub Desktop.

In our organization, the firewall decrypts all SSL traffic (MITM forward proxy). This means that the software developers install Git using the openSSL, then append our trusted firewall certificate to the ca-bundle used by Git to successfully clone/push/fetch.

For the business analysts using Github Desktop, I had to manually look into the program files, and edit the gitconfig located in C:\Users\<user>\AppData\Local\GitHubDesktop\app-1.3.2\resources\app\git\mingw64\etc. I changed the gitconfig file to use openSSL instead of schannel, and provided a path for sslcainfo. This was how I made GitHub Desktop, work with my organization's self-signed certificate, as there are no menu options to edit these settings from the Desktop GUI.

The latest update seem to erase these settings. It appears the update creates a new folder in C:\Users\<user>\AppData\Local\GitHubDesktop with a higher version number, and as a result, creates a new gitconfig file with the default values. 

Is it possible to keep the existing gitconfig file, or import self signed certificates into GitHub Desktop?

If you have any questions, or are curious to see more, please let me know.

Thank you for reading,

Daniel

**Comment by shiftkey** [comment]
> Is it possible to keep the existing gitconfig file, or import self signed certificates into GitHub Desktop?

@DJPEREZ you shouldn't be changing the system config under `C:\Users<user>\AppData\Local\GitHubDesktop\` as that will change between versions. You should make changes to your global `~/.gitconfig` as those will not only override the Desktop defaults, but will persist between updates.

**Comment by billw2012** [comment]
````
file:"C:\\ProgramData/Git/config"       core.symlinks=false
file:"C:\\ProgramData/Git/config"       core.autocrlf=true
file:"C:\\ProgramData/Git/config"       core.fscache=true
file:"C:\\ProgramData/Git/config"       color.diff=auto
file:"C:\\ProgramData/Git/config"       color.status=auto
file:"C:\\ProgramData/Git/config"       color.branch=auto
file:"C:\\ProgramData/Git/config"       color.interactive=true
file:"C:\\ProgramData/Git/config"       help.format=html
file:"C:\\ProgramData/Git/config"       http.sslcainfo=C:/Users/<username>/AppData/Local/GitHubDesktop/app-1.3.2/resources/app/git/mingw64/ssl/certs/ca-bundle.crt
file:"C:\\ProgramData/Git/config"       sendemail.smtpserver=/bin/msmtp.exe
file:"C:\\ProgramData/Git/config"       diff.astextplain.textconv=astextplain
file:"C:\\ProgramData/Git/config"       rebase.autosquash=true
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    http.sslbackend=openssl
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    diff.astextplain.textconv=astextplain
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    filter.lfs.clean=git-lfs clean -- %f
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    filter.lfs.smudge=git-lfs smudge -- %f
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    filter.lfs.required=true
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    filter.lfs.process=git-lfs filter-process
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    credential.helper=manager
file:C:/Users/<username>/.gitconfig       filter.lfs.required=true
file:C:/Users/<username>/.gitconfig       filter.lfs.clean=git-lfs clean -- %f
file:C:/Users/<username>/.gitconfig       filter.lfs.smudge=git-lfs smudge -- %f
file:C:/Users/<username>/.gitconfig       filter.lfs.process=git-lfs filter-process
file:C:/Users/<username>/.gitconfig       user.name=billw2012
file:C:/Users/<username>/.gitconfig       user.email=<email>
````

**Comment by shiftkey** [comment]
> file:"C:\\ProgramData/Git/config"       http.sslcainfo=C:/Users/<username>/AppData/Local/GitHubDesktop/app-1.3.2/resources/app/git/mingw64/ssl/certs/ca-bundle.crt

@billw2012 this value is unnecessary, and can be removed from `C:\\ProgramData/Git/config`

> [http]
> 	sslCAInfo =C:/Users/<username>/AppData/Local/GitHubDesktop/app-1.3.2/resources/app/git/mingw64/ssl/certs/ca-bundle.crt

**Comment by billw2012** [comment]
I don't think I added this value myself, was it added by an older version of github desktop?

**Comment by shiftkey** [comment]
@billw2012 no, Desktop's Git installation is under `C:\Users\<user>\AppData\Local\GitHubDesktop\`

**Comment by shiftkey** [comment]
@jlano you want to see what your config looks like by running this:

> git config -l --show-origin

You probably have an entry that looks like this:

```
file:"C:\\ProgramData/Git/config"       http.sslcainfo=C:/Program Files (x86)/Git/mingw32/ssl/certs/ca-bundle.crt
```

If you find it, it corresponds to these lines in `C:\\ProgramData\Git\config` and can be removed:

```
[http]
sslCAInfo=C:/Program Files (x86)/Git/mingw32/ssl/certs/ca-bundle.crt
```

**Comment by jlano** [comment]
Thanks for your help.  This thread helped me figure out that it was a GIT update that broke GitHubDesktop.

**Comment by shiftkey** [comment]
Closing this out as this is a variation of #4832 and has a known workaround
