### ISSUE TITLE
Minor issue: username displayed

### ISSUE THREAD

**Issue by Trebor-Huang** [desktop/desktop#5476]
Take my username `Trebor-Huang` as an example. When a change is made through GitHub Desktop, the name displayed is `Trebor`; when the change is through the web browser, `Huang` is used. It's a minor problem, but... perfectionists *do* appreciate the work. :)

**Comment by shiftkey** [comment]
@Trebor-Huang thanks for the report. Two things we need to dig deeper into this:

 - are you able to share screenshots of the different behaviour so we can see where in the app this is occurring?
 - could you share what your `user.name` and `user.email` commit settings are for creating commits?

I suspect that this is because we don't associate your GitHub account with the commits you made when displaying the history, and instead just show the name associated, but I'd like to confirm that for completeness.

**Comment by Trebor-Huang** [comment]
![bugscrsht](https://user-images.githubusercontent.com/41145779/44629027-3d0b7500-a97c-11e8-9643-9f2d152a6491.png)

My account name is `Huang`, and my Git name is `Trebor`.

**Comment by iAmWillShepherd** [comment]
@Trebor-Huang, I'm currently trying to reproduce this issue.

Would you mind sharing the result of running `git log --oneline --pretty="%s - %an <%ae>" -n 10`?

I suspect that `user.name` in your git config does not match what's on your GitHub [profile](https://github.com/settings/profile), if that turns out to be the case, you should update that setting to match what's on GitHub. Also, the typical usage of `user.name` is to use your full name.

**Comment by shiftkey** [comment]
@Trebor-Huang no problem, and thanks for working through this with us!
