### ISSUE TITLE
Co-authors field doesn't appear after clicking 'add' button

### ISSUE THREAD

**Issue by cheshire137** [desktop/desktop#5490]
In version 1.3.4 in macOS, clicking the "add co-authors" button just toggled the icon from blue to gray, and made the text say "Add co-authors" and "Remove co-authors", but did not make the field to type the co-authors name appear.

![image 25](https://user-images.githubusercontent.com/82317/44687347-9a540480-aa16-11e8-8511-1fcaf7774e39.png)

This was the first time running the app, right after signing into GitHub and adding a local repository. Upon exiting and reopening the app, the "add co-authors" button worked as expected.

**Comment by iAmWillShepherd** [comment]
Thanks for taking the time to open an issue! 🙇 

This could be caused by mentionables (our made-up word for people you can @-mention) were not completely loaded when you attempted this. I'm going to see if I can force this to happen again to verify if my hunch is correct.

**Comment by iAmWillShepherd** [comment]
I was able to reproduce by clearing storage in Chrome DevTools.

**Comment by shiftkey** [comment]
> I was able to reproduce by clearing storage in Chrome DevTools.

Can you elaborate on "storage" here? Local Storage or IndexedDB databases or both?

**Comment by iAmWillShepherd** [comment]
Here's an extra-long GIF of the behavior.

![2018-08-27 16 53 54](https://user-images.githubusercontent.com/1715082/44688600-5c58df80-aa1a-11e8-8b51-e161ba9419e1.gif)

I've verified that users not being loaded yet is not the cause of this issue after noticing that remounting the component causes it to work as expected (just click the _History_ tab and go back to the _Commit_ tab and the toggle shows the input as expected).

**Comment by iAmWillShepherd** [comment]
> Can you elaborate on "storage" here? Local Storage or IndexedDB databases or both?

I cleared all storage.

![screen shot 2018-08-27 at 5 02 37 pm](https://user-images.githubusercontent.com/1715082/44688836-12bcc480-aa1b-11e8-8169-1e7a087f5257.png)

**Comment by iAmWillShepherd** [comment]
Dig some more digging and I think I've narrowed it down to how state is being updated:
https://github.com/desktop/desktop/blob/5e9f1aa366dff6b97f4f8199085670633286fb20/app/src/ui/changes/commit-message.tsx#L337-L342

I noticed that after clicking the toggle button, `nextProps` did not have the values I expected, namely `showCoAuthoredBy` being set to `true`
https://github.com/desktop/desktop/blob/5e9f1aa366dff6b97f4f8199085670633286fb20/app/src/ui/changes/commit-message.tsx#L135

**Comment by iAmWillShepherd** [comment]
Looks like the cause of this issue has to do with metadata being missing on the `Repository` type, specifically, `GitHubRepository` is null when the check is made.

https://github.com/desktop/desktop/blob/42c5b3fa1894595fb2b241b6e9845bef09bc3643/app/src/ui/changes/sidebar.tsx#L88-L112

That failing check means the `UserAutocompletionProvider` provider is never inserted into the `autocompletionProviders` list. Which causes `state.userAutocompletionProvider` to be null in the `CommitMessage` component due to the following function.

https://github.com/desktop/desktop/blob/42c5b3fa1894595fb2b241b6e9845bef09bc3643/app/src/ui/changes/commit-message.tsx#L86-L96

**Comment by iAmWillShepherd** [comment]
Digging even deeper, to figure out why `GitHubRepository` is `null`, I've come across the `matchGitHubRepository` function that's called from `repositoryWithRefreshedGitHubRepository`.

https://github.com/desktop/desktop/blob/4f9f7eea3b9ac251efa120c4a09805cbc0a7769d/app/src/lib/stores/app-store.ts#L2269

 `matchGitHubRepository` returns `null` when called on a newly added repo, likely because `gitStore.defaultRemote` is `null`.
