### ISSUE TITLE
Support pushing to collaborator forks

### ISSUE THREAD

**Issue by haacked** [desktop/desktop#550]
Today, we have this really cool way of cloning the branch of a PR from a fork.

![image](https://cloud.githubusercontent.com/assets/19977/19368773/84c83030-9156-11e6-8034-2fc7fa493177.png)

This one click operation conveniently replaces a several step command line process.

Recently, GitHub also shipped the ability for collaborators working on a fork to allow [authors on the target repository](https://github.com/blog/2247-improving-collaboration-with-forks) to push to their PR branch.

Desktop today doesn't support this. If I click "open this in GitHub Desktop" on a fork PR, make a change, and then try to push, it defaults to pushing to origin and not the fork branch.

Ideally, we would detect (I assume there's an API we can hit) if we actually have write access to the fork PR branch and if so, push to that instead. If the developer's intention is ambiguous, we could prompt asking where they would like to push.

**Comment by shiftkey** [comment]
Bumping this because I think the upcoming 1.1 release (already on the beta channel) will address much of what was necessary here:

 - Desktop now lists Pull Requests in the app, including PRs from forks
 - when you checkout a PR from a fork, Desktop will set the tracking information so you can pull in new changes if the PR gets updated
 - Similarly, if you have permissions to push to the PR, you can make commits and push to the PR branch

https://github.com/desktop/desktop/pull/3835 is an example of this. 

There's probably some polish here:

 - there's a `maintainer_can_modify` flag on PRs that's returned by [the Pull Request API](https://developer.github.com/v3/pulls/#get-a-single-pull-request), we don't look at that currently 
 - I think we also need to look at the `permissions` hash returned by the [repository API](https://developer.github.com/v3/repos/#get), which indicates what the current user can do with the repository

**Comment by billygriffin** [comment]
Desktop does allow maintainers to push to collaborator forks of a particular repo. @outofambit and I tested it on #8934 with great success. And the problem of checking out a branch of a fork in Desktop is captured in #8509, Problem 5. I'll open up a separate issue for that to be more specific to the checkout of the PR branch from forks, but since the pushing operation is allowed, I'm going to close this.
