### ISSUE TITLE
Revert #4285

### ISSUE THREAD

**Issue by Grinderofl** [desktop/desktop#5515]
**Please describe the problem you think should be solved**
The upgrade nag is annoying. I have no desire to start using the electron version. Stop pushing it on users who don't want it. Features in old desktop app were plenty.

**[Optional] Do you have any potential solutions in mind?**
Get rid of the nag screen and release the old version as open source so community could maintain it if you have no interest.

**Comment by billygriffin** [comment]
Hi @Grinderofl, thanks for the issue! That's totally fair that you prefer to continue to use the classic app. Since the version we're supporting and actively building on is the Electron version, we do want to make sure people know what's available to them and easily be able to switch over at their convenience. We chose every 30 days for the exact reason you state here, to not just annoy people every time they start up the app. I appreciate that if you have no intention of ever upgrading, even seeing it once a month can be annoying, but we want to continue to provide that option to do so easily for folks that may have been on the fence initially.

We have no plans to open source the classic apps, as there is quite a bit of overhead involved in that and we want to ensure a standard of quality. Thanks again for your feedback.

**Comment by Grinderofl** [comment]
@billygriffin Why does it have to do it _every single time_ it starts up? If you are fine with people using older version, yet want to make sure "folks that may have been on the fence initially" know about the new version, wouldn't it be a good middle ground to have an option "don't show this again"?
