### ISSUE TITLE
"github clone url" when URL ends in .git adds another .git and causes auth error

### ISSUE THREAD

**Issue by peterlobster** [desktop/desktop#5529]
## Description
When trying to clone a repository thru using the command `github clone...`, the command opens the Desktop Application, which prompts for your GitHub information. When trying to login with the correct information, the application fails. It's also worth noting, in my case, I was already authenticated in the Application...and was able to clone the repository without any issue using the application's interface.

## Version

* GitHub Desktop: 1.3.6
* Operating system: 10.13.6

## Steps to Reproduce
Installed thru `brew cask install github`
Open Application and sign into Github
Run "Install Command Line Tool..."
Try to clone any repository

### Expected Behavior
For the repository to be cloned, or for the login to authenticate properly.

### Actual Behavior
Repository fails to clone because login fails to authenticate.

### Logs
[2018-09-01.desktop.production.log](https://pastebin.com/QM3kJykT)

**Comment by niik** [comment]
Confirmed. This happens because we [always append .git](https://github.com/desktop/desktop/blob/9c96a9f0cac29f1276d8f1174dd78c318b96201a/app/src/lib/parse-app-url.ts#L108) to clone URLs. This behaviour dates back [several years](https://github.com/desktop/desktop/commit/f16808620fd345dae127bd3011ccfa2393d34241#diff-3c7628daaf182e98a641832c584316bf).

### Steps to reproduce

1. Install command line tools
2. Execute `github clone https://github.com/desktop/desktop.git`
3. 💥 

I believe we could drop the append here but I want us to take a few moments to look at the implications of doing so seeing how it's been this way since before we released the app.

**Comment by niik** [comment]
Thanks for letting us know about this @peterlobster! Until we can get this fixed I'd recommend not adding the `.git` suffix to clone URLs when cloning from the command line.

**Comment by j-f1** [comment]
I don’t think the `.git` is necessary — many of my remotes don’t have it and they work just fine.

**Comment by peterlobster** [comment]
@niik Thanks for all the great insight! I'm glad I could do my part.

**Comment by j-f1** [comment]
*self-assigns*
