### ISSUE TITLE
Breaking Change

### ISSUE THREAD

**Issue by Legend669** [desktop/desktop#5536]
## Version

* GitHub Desktop:

* Operating system:

**Comment by niik** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by shiftkey** [comment]
Closing this out as inactive. @Legend669 if you're able to fill out the template we're happy to revisit it!
