### ISSUE TITLE
Github Desktop does not update paths/filenames in case-sensitive way

### ISSUE THREAD

**Issue by teodor-ionesco** [desktop/desktop#5537]
## Description
I am not sure whether this is an issue or a problem which should be solved. Github does not recognize case-sensitive path/filename changes. It's vital to update the case-sensitive paths/filenames otherwise some apps which are being cloned from github.com may fail under UNIX distributions (which unlike Windows OS, they treat paths in a case-sensitive manner).

## Version
* GitHub Desktop: 1.3.4
* Operating system: Windows 7 Ultimate, Service Pack 1, x64

## Steps to Reproduce
1. I am writing the code. 
2. I am naming the file with uppercase letters: Framework.php
3. I am committing
4. I am pushing to master
5. I am pushing to origin
6. I need to change filename from: 'Framework.php' to: 'framework.php'
7. I am renaming 'Framework.php' to: 'framework.php' in Windows Explorer
8. Github Desktop does not recognize this change 
9. I am pushing to master. Instead of pushing the file under name 'framework.php' it pushes it as 'Framework.php' still.

### Expected Behavior
Github should keep an eye for directory/file name in case-sensitive manner and should update path/file names accordingly.

### Actual Behavior
Github does not keep an eye for directory/file name in case-sensitive manner.

## Additional Information
There is nothing more to add.

### Logs
[Uploading 2018-09-03.desktop.production.log…]()

**Comment by niik** [comment]
Hey @teodor-ionesco, thanks for opening this issue! While I'll grant you that this certainly is confusing, especially from a Windows point of view, this is unfortunately the expected behavior of Git. @shiftkey wrote an answer to a very similar issue over at 
https://github.com/desktop/desktop/issues/2672#issuecomment-329011490 and I'd encourage you to check that out. There's also a good article about this over at [MS docs](https://docs.microsoft.com/en-us/vsts/repos/git/case-sensitivity?view=vsts).

I'm going to close this issue out as I believe #2672 covers this problem. If that's not the case please let me know and I'll reopen and we can take another look.

**Comment by teodor-ionesco** [comment]
Issue #2672 covers this one as well. Thank you for your reply.
