### ISSUE TITLE
VFS For Git

### ISSUE THREAD

**Issue by rickhopkins** [desktop/desktop#5544]
It'd be nice if they desktop client could change the name of a repo, just locally I mean... like an alias. I say this because we are starting to use GVFS (https://gvfs.io/) and when I add the repo it points to the src directory created by GVFS. So all my local repositories in the desktop client are called "src". It'd be nice if I could alias them to be something else...

**Comment by shiftkey** [comment]
@rickhopkins we don't currently support VFS for Git repositories in GitHub Desktop due to limitations about we embed Git. I've got an upstream issue about this that you can follow along for more details: https://github.com/desktop/dugite-native/issues/45

For the alias suggestion, we're tracking this in #1929, so please add any extra details you have to that issue.
