### ISSUE TITLE
Non funziona la pagina iniziale

### ISSUE THREAD

**Issue by ebureli** [desktop/desktop#5548]
## Description

la pagina iniziale non funziona

## Version

* GitHub Desktop:

* Operating system:

**Comment by shiftkey** [comment]
@ebureli thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by ebureli** [comment]
sorry I opened a issue for error because we are trying to use github

**Comment by billygriffin** [comment]
No problem @ebureli, thanks for letting us know! 😄
