### ISSUE TITLE
Improve merge flow

### ISSUE THREAD

**Issue by billygriffin** [desktop/desktop#5555]
Over the past several releases, we've focused on making it easier for people to collaborate using GitHub Desktop. There are several features we've released to that end, including the ability to compare one branch to another and subsequently merge (https://github.com/desktop/desktop/issues/3956) and notifying users when master has commits that their branch does not (https://blog.github.com/2018-07-30-github-desktop-1.3/).

We think it would be helpful to take a step back and evaluate what things are intuitive and working well and where there might be opportunities for improvement. Since we're still exploring our handling of merge conflicts in Desktop, the scope of this evaluation is intended to be from the moment a user decides they'd like to get work from one branch to another (intent, regardless of where they are in the app) up to the point where they actually initiate the merge.

The goals here are:

1. Take a look at the metrics relating to the current merge flow to understand how it's being used to date.
2. Identify the areas of confusion in the current merge flow and where things are not discoverable, and evaluate whether that aligns with what metrics show. This part should involve at least some interaction/usability testing with users outside of GitHub.
3. Propose potential solutions for making that flow more intuitive and discoverable to help reduce friction for individuals and teams that use Desktop as part of their collaboration.

cc: @desktop/design @desktop/analytics 

### Task Issues:
- [x] Make it obvious which branch is being merged into which branch - #5930
- [x] Place merge button in branch list dropdown - #5929

**Comment by billygriffin** [comment]
We discussed this today and I wanted to share a more clarified set of observations and problem statements:

### Observations

We've not seen considerable evidence that people find value in comparing the commits of one branch to another when trying to merge. Additionally, in usability testing, when attempting to merge, most users went first to the "Branch" dropdown, not to the "History" tab where the compare flow currently lives. Therefore, the most discoverable way to merge one branch to another is through the menu bar. If this is working for users, we have no problem if people choose to continue that flow, but we think beginners would benefit from a more intuitive merge flow.

### Problem statements

1. It's not obvious how to merge one branch into another in Desktop.
2. In the branch dropdown, the branch filter input is confusing in its current location next to the "New branch" button. It should be obvious to people what action is for what purpose.
3. The directional merge flow is not as obvious as it could be. It should be perfectly clear which branch you're merging into which branch.
4. There's no way to see a diff of one branch to another to fully understand what's being merged in and what it will look like after the merge is completed.

For the purposes of this initial effort, we're viewing problems 1-3 as in scope, and 4 as an iteration that we may tackle later.

### How will we measure success?

1. % of total active users who merge in a given period should go up.
2. The % of total merges done in the app via the in-app flow (as opposed to via the menu bar) should go up.
3. Total merges in Desktop should go up.

cc: @nerdneha @ampinsk @iAmWillShepherd

**Comment by ampinsk** [comment]
In order to address problems 1 and 3, we're proposing these updates to the branch panel and the subsequent `Merge into current branch` modal. 

### Branch panel
We're adding a button to the bottom of the panel: "Choose a branch to merge into [current branch]"

<img width="1010" alt="branch menu 1 13 2x" src="https://user-images.githubusercontent.com/10404068/46970036-c120d580-d06c-11e8-9fd9-31a54974977c.png">

### Merge modal
Two small changes here: 
1. Using the modal title to explain more clearly what branch is merging into what
2. Moving the conflicts hint before the button

<img width="1010" alt="header 1 5 2x" src="https://user-images.githubusercontent.com/10404068/46970037-c120d580-d06c-11e8-9de7-a733ca241440.png">

Both of these changes may adapt as we build them out and use them with real data (especially when it comes to how these behave with long branch names), but this is our first step to move the needle on these problems 😄

**Comment by iAmWillShepherd** [comment]
@j-f1, thanks for the input. I think we want to do small iterative changes over larger sweeping changes. The team still has not settled on the best path forward for the relationship between branches feature, so we have to figure that part out first. The changes @ampinsk is suggesting meets the goal of small changes since it only involves updating a label.

If you're interested in helping out in this area of the app, I'm happy to pair with you on it. I'd like to get these changes shipped in the next next release, so I'll be getting started on these changes this week.

**Comment by iAmWillShepherd** [comment]
@billygriffin, could clarify if this is related to a marketing release?

**Comment by billygriffin** [comment]
@iAmWillShepherd I added the label for 1.5. It's not the end of the world if we don't get it in by then, but that's my goal for this to be a part of the next marketing release. I like the story around improving the ease of merging **and** merge conflicts. cc: @nerdneha

**Comment by iAmWillShepherd** [comment]
This work was was completed in #6027, #5977, and #5957.
