### ISSUE TITLE
Block invalid refspec in branch names

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#5594]
We allow Desktop to name branches as `+`, which will trigger a `git -c credential.helper= push origin + --set-upstream --progress exited with an unexpected code: 128. fatal: Invalid refspec '+'` error when attempting to publish the branch. 

We should disable the ability for users to name their branches `+` and/or clarify in the messaging why we do not allow such branches to be published.

Note, you cannot name a repo `+`, as is converted into `-`. 

<img width="589" alt="screen shot 2018-09-10 at 3 44 22 pm" src="https://user-images.githubusercontent.com/14828183/45328331-68f83000-b510-11e8-8d4e-011539a38171.png">

**Comment by Daniel-McCarthy** [comment]
This is a great catch! I'd love to give this a try.
___
When you mention updating the messaging, did you have a suggestion in mind? Is this for the user?

For both the `Rename-Branch-Dialog` and the `Create-Branch-Dialog` if one creates a repository with the name `^` it will result in "`^` is not a valid name." Do you feel this should explain why?

Additionally the documentation for `sanitizedBranchName(name: string)` can be updated to explain why it is not allowed.

**Comment by outofambit** [comment]
"^ is not a valid name." seems like a good starting place. I would love if the error message could be more informative, but do would we be able to know why their branch name was invalid? @Daniel-McCarthy

**Comment by Daniel-McCarthy** [comment]
>I would love if the error message could be more informative, but do would we be able to know why their branch name was invalid?

This depends a bit. I believe displaying to the user what is wrong is somewhat intuitive currently. Here is how the behavior acts currently:
- If one enters `A^B` it will tell the user that it will be created as `A-B`.
- If one enters `^A` it will tell the user that it will be created as `A`
- If one enters `-A` it will tell the user that it will be created as `A`
- If one enters `-` it will tell the user `-` is not a valid name.

This _may_ be reactive enough for the user.

However, if we're interested in explaining why that character is not allowed, this would change a bit depending on what characters are being used. There is a regular expression in [`/lib/sanitize-branch.ts`](https://github.com/desktop/desktop/blob/master/app/src/lib/sanitize-branch.ts) that covers which characters are invalid.

For example, the documentation includes a link that covers information on a number of characters. Additionally it mentions some characters do not work on Windows that would otherwise legal.
___
Regarding fixing the fatal error: we need to update the regular expression to not allow plus to be the first character of the name during sanitization. I have done this as well as added some unit tests to check this behavior. I can create a pull request soon.

I'd love to hear what we're thinking in regards to the user notification aspect.
