### ISSUE TITLE
Clarify error when primary remote repository is empty

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#5625]
When removing and then saving your Repo remote url, the error that follows should be more user friendly. 

Current error:
<img width="492" alt="screen shot 2018-09-12 at 3 10 20 pm" src="https://user-images.githubusercontent.com/14828183/45456162-9541b700-b69e-11e8-9f8a-1ec6ee40ed65.png">

Suggested error:
Error: Please check your remote url in the Repository Settings as no path was specified. See 'man git-pull' for valid url syntax.

Repro:
- Delete the url in Repository > Repository Settings > Remote, save it
- Do a fetch

tested in 1.4.1-beta0, mac

**Comment by AlecR** [comment]
I'm looking to contribute to Github Desktop and this looks like a good task to get acquainted with the codebase. If it not already done, I'd like to take on this issue

**Comment by tierninho** [comment]
@AlecR Please give it a shot and reach out if you have any questions. Thanks!

**Comment by AlecR** [comment]
@tierninho This unclear error is provided by git, and it is not something the client is setting. When the client tries to complete a git operation and receives an error, the error is then displayed in a modal shown in the image above. Because of this, changing this error message would either have to happen on git's end (not the desktop client), or there would have to be drastic changes in the desktop app to allow for more customized error messages rather than just spitting out the error response from git.

**Comment by tierninho** [comment]
@AlecR thanks for the clarification. Will close this out as it is an issue with git and low priority. 

Hope you can contribute to Desktop elsewhere. Thanks!

**Comment by tierninho** [comment]
Reopening this issue on the suggestion that we should add some text to the Repository Settings modal (above the URL field) outlining the ramifications when changing the primary URL. Thoughts? 

We do something similar on the gitignore tab and as a lot of our base are novice users, we should clarify what the setting does.

![image](https://user-images.githubusercontent.com/14828183/51060763-ac89a600-15a5-11e9-85e5-da3a7d433631.png)

**Comment by tierninho** [comment]
Closing this as it has not come up enough times to be validated as a real problem.
