### ISSUE TITLE
Infected with virus

### ISSUE THREAD

**Issue by crypticterminal** [desktop/desktop#5652]
Virus scanner is detecting an exploit (Html.Exploit.CVE_2016_7200-1) in the source code as well as the compiled version.

**Comment by lee-dohm** [comment]
Thanks for reaching out!

Given that the [exploit you mention](https://nvd.nist.gov/vuln/detail/CVE-2016-7201) is specific to Edge's Chakra JavaScript engine and Desktop runs on [Electron](https://electronjs.org) which uses Chromium's V8 JavaScript engine, this doesn't apply to us. Additionally, a vulnerability is not generally characterized as a "virus" unless it has self-replicating features, even when detected by a virus scanner.

In the future, if you have security vulnerabilities that you would like to report to us, please send them to opensource+desktop@github.com so that we can investigate and remediate them fully without exposing people to attack.

**Comment by j-f1** [comment]
Should we put a comment mentioning security issyes in the issue template so people are more clearly asked not to report them here?

**Comment by shiftkey** [comment]
@j-f1 maybe? I'd also rather it be more prominently displayed on the README for anyone landing on the repository. Or perhaps we need something on `desktop.github.com`?
