### ISSUE TITLE
Github Enterprise and clone the repository issue

### ISSUE THREAD

**Issue by ghost** [desktop/desktop#5667]
**Please describe the problem you think should be solved**
A clear and concise description of what the problem is and who else might be impacted. Screenshots are encouraged.

Github Enterprise and clone the repository issue:

-->Authentication failed. You may not have permission to access the repository or the repository may have been archived. Open options and verify that you're signed in with an account that has permission to access this repository.

![github issue](https://user-images.githubusercontent.com/42945016/45625295-1edff300-baaa-11e8-9e16-2ecc8fd2b06f.PNG)

**Comment by steveward** [comment]
Thanks for the report @nasarbabu.

Some other users at IBM have reported a similar issue that seems to be caused by using Firefox as the default browser on Windows 7. I have not been able to directly reproduce this myself as of yet. If you are using Firefox can you try temporarily switching your default browser to Internet Explorer to see if that gets things working? You can read how to change your default browser here:

https://support.microsoft.com/en-us/help/18539/windows-7-change-default-programs

Let me know if that does not help.
