### ISSUE TITLE
precession denied

### ISSUE THREAD

**Issue by Fancy93** [desktop/desktop#5679]
## Version

* GitHub Desktop:

* Operating system:

**Comment by steveward** [comment]
@Fancy93 thanks for reaching out!

We require the template to be filled out with all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway. 😀

**Comment by shiftkey** [comment]
Closing this out due to inactivity. @Fancy93 if you're able to fill out the template we're happy to revisit the issue.
