### ISSUE TITLE
111

### ISSUE THREAD

**Issue by Marina-medved** [desktop/desktop#5687]
## Version

* GitHub Desktop:

* Operating system:

**Comment by shiftkey** [comment]
@Marina-medved Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by Marina-medved** [comment]
Добрый! Не совсем поняла, простите?))))

**Comment by shiftkey** [comment]
@Marina-medved the issue template was not filled out, and so we closed the issue after 7 days due to inactivity. Are you able to fill out the issue template to explain the problem you are seeing?
