### ISSUE TITLE
I can't change the default branch by the branch I want to

### ISSUE THREAD

**Issue by pmcastell** [desktop/desktop#5688]
I would like to change de default branch in my GitHub Desktop, but I can't do it

**Comment by steveward** [comment]
Thanks for opening this @pmcastell. At this time you can only change the default branch of your repository either [directly on GitHub](https://help.github.com/articles/setting-the-default-branch/) or [via the API](https://developer.github.com/v3/repos/#edit). 

Is there a specific reason you are wanting to change the default branch in GitHub Desktop instead of directly on github.com?

**Comment by tierninho** [comment]
@pmcastell We are closing this issue as we haven't gotten a response and your question was answered above. Please don't hesitate to reach out again if you need help. Thanks.
