### ISSUE TITLE
List & clone GitHub repositories

### ISSUE THREAD

**Issue by joshaber** [desktop/desktop#57]
Mac and Windows had different designs for this, so we'll need to decide on one.

**Comment by rlabrecque** [comment]
I'm cloning a repo from the client for the first time and having automatic suggestions would be a very welcome UX addition. I'd also only expect them after the /

**Comment by thephez** [comment]
FWIW, the easy cloning without having to look up the URL or remember the exact name was the first feature I attempted to use after installing the new Desktop Beta.  Without that, it's feels like just another client and I'm prone to using the command line (or downgrading to the old Desktop version).  I would personally prefer a list, but would expect autocomplete otherwise.

**Comment by dragonwolf83** [comment]
I agree with @thephez here. I just installed GitHub Desktop and the list of GitHub Repos was my first expectation. In fact, I haven't gotten past it. I'm either going to revert to GitHub for Windows for now or just use my IDE to get started since this is beta.

As a new user or existing user, I often need to clone more than one Repository when joining a new organization. Having a list of Repositories for me to select and clone at once will get me started more quickly.

Here are my design ideas on what I would like to see:
* Clone Repository should enter a full page to give room for listing Repos. 
* URL And Local Path at the top and center. Focus on URL box.
* On top Left is a my GitHub Account with a drop-down supporting multiple accounts
  * GitHub.com Account Personal
  * GitHub.com Account Organizations
  * GitHub Enterprise Account Personal
  * GitHub Enterprise Account Organizations
  * Future support for GitLab and other "Cloud-based" Git Repos
* List of Repositories below the Account drop-down
* Typing in URL box will filter the list
* Allow multiple selections on the list to Clone all into selected Local Path with their respective names

Sorry that I don't have a good sketch so hopefully it makes sense. 

For the account listing, I was thinking of optgroups to group GitHub Accounts so that it the GitHub.com vs Enterprise are first level with second level being the Personal vs Organization lists.

Either way, focusing on the account as an option allows you to extend this to other Cloud Repos so that this could be a generic Git client while putting GitHub first. If a user doesn't sign in at all, then hide all of that UI with just the focus on user selecting URL or Path to a Repo to clone.

**Comment by christoff-1992** [comment]
Mac user here, got to say I do miss the list of available repos, but it’s also not a lot of work to go copy the url etc.

**Comment by Torxed** [comment]
It makes no sense why the list of repos I have access to, is not in the client I use to manage my repos.
Why am I being forced to download a app, and also use a browser in order to even know about any repos?
I literally can't use the application, without first finding a bunch of repos.

I'd might as well stick to cmd-line and a browser since it leaves a smaller footprint on my machine and gives me about the same features as of today.

Bring back something along the lines of:
![ui](https://user-images.githubusercontent.com/861439/27654333-3909bd14-5c42-11e7-89b5-ec9a8eaeb8d8.png)

**Comment by MikeKovarik** [comment]
I'm missing the "my repos list" very much. There should be a filterable combo box or at least an autocomplete in the "clone a repository" dialog. It's annoying typing out the whole `my-name/my-repo-name`, especially for the long ones, with dashes. I understand there are some UI concerns but removing the list altogether is the deal breaker for me and I'm downgrading to the old client because of it (for now).

**Comment by joshaber** [comment]
Thanks for all the feedback! This is something we plan to address for 1.0. We're not sure exactly what it will look like yet, but we recognize the current approach is less than great.

**Comment by dragonwolf83** [comment]
I updated my previous comments on design. After going back to GitHub for Windows, the UI there is actually pretty close to perfect. My updated comments reflects the desire that it focus on multiple accounts and allow multiple repo selection in one-go.

For companies with lots of repos, the search that is in the current GitHub Desktop and paginating the repo list should help make it load quickly and be easy to use.

**Comment by donokuda** [comment]
Taking another pass at cloning repositories. For reference, here's what the previous clients did:

**macOS**

<img src="https://user-images.githubusercontent.com/1174461/28130590-1c0af6c4-66ec-11e7-8461-8b78ae6ae125.png" width="448" />

**Windows**

<img src="https://user-images.githubusercontent.com/1174461/28130622-3b8641ca-66ec-11e7-8d6e-ad74a3943f8f.png" width="448" />

Here's what we currently do as of this comment:

<img src="https://user-images.githubusercontent.com/1174461/28131149-e42cb57e-66ed-11e7-95db-2ff8cd4c1e97.png" width="548" />

Taking a look at what we did before and how we treat repositories now, I think this approach makes the most sense:

**Viewing a list of repositories on GitHub**

<img alt="clone repository 2x" src="https://user-images.githubusercontent.com/1174461/28129628-da4a426a-66e8-11e7-9332-28ddefd3ab5c.png" width="430" />

I kept the list of repositories as close to how we do them in the repository menu dropdown. We'll show all the repositories based on what you have access too with your GitHub account. You'll also set the The only main concern here is that this modal is starting to look a little boxy to me.

**Cloning via HTTPS/SSH**

<img alt="clone via url 2x" src="https://user-images.githubusercontent.com/1174461/28129627-da3c67da-66e8-11e7-9a34-34a93cd612d3.png" width="430" />

I opted for cloning via a URL since you can grab it via the **Clone or Download** dropdown on a repo page. This also lets us just set the origin URL with what the user provides instead of trying to infer something based on the `org/repo` pattern. I think this also alleviates [any concerns around cloning from a GHE instance](https://github.com/desktop/desktop/issues/57#issuecomment-241856688).<sup>[[citation needed]](https://en.wikipedia.org/wiki/Wikipedia:Citation_needed)</sup>

Would love to gather thoughts around this approach.

**Comment by j-f1** [comment]
It might be useful to autocomplete your username, as well as the names of any organizations you’re in before the `/`.

**Comment by joshaber** [comment]
>You'll also set the 

Set the what? SET THE WHAT

![687474703a2f2f636f6f70657273636f726e65722e696e666f2f77702d636f6e74656e742f75706c6f6164732f323031322f31302f37322e6a7067](https://user-images.githubusercontent.com/13760/28132550-28f657a6-670b-11e7-9815-4718a3e1b754.jpeg)

**Comment by donokuda** [comment]
> Set the what? SET THE WHAT

Whoops! You'll set the save location there.

**Comment by joshaber** [comment]
@donokuda In those mocks, what do we do if the user has both a GitHub.com and an Enterprise account? Do we put all the repositories in that one list? If so, how do we potentially disambiguate repositories with the same org/name on both .com and Enterprise?

**Comment by donokuda** [comment]
> @donokuda In those mocks, what do we do if the user has both a GitHub.com and an Enterprise account? Do we put all the repositories in that one list? If so, how do we potentially disambiguate repositories with the same org/name on both .com and Enterprise?

I feel like it would make sense to have the repos from an Enterprise in its own tab. The biggest benefit is that we would disambiguate what is on GitHub.com vs. on an enterprise instance. Another benefit is that it would make finding the enterprise repos easier when you're already apart of many orgs with many repos:

<img src="https://user-images.githubusercontent.com/1174461/30082142-956496b0-923e-11e7-94fd-fd68de1b38db.png" width="400" />

**Comment by joshaber** [comment]
👍 💯

**Comment by rlabrecque** [comment]
What happens if there's no GitHub Enterprise account attached?

Should that tab have info about Enterprise, and a button to get onto the path to add an account?

**Comment by joshaber** [comment]
I think we'd only include the GitHub Enterprise tab if they have an authenticated Enterprise account. @donokuda thoughts?

**Comment by joshaber** [comment]
Though I guess on the Publish Repository view, we always show the Enterprise tab 🤔 I'll go with that for party.

**Comment by rlabrecque** [comment]
Hiding the enterprise tab is negative in that it could be annoying for muscle memory for those that have enterprise on a work machine, but not at home. And it could create confusion like: "Where's the Enterprise tab?!".
It gives a good sales pitch area too.

Based on the above, but with no Enterprise account: 
```
Clone a Repository
GitHub   |   GitHub Enterprise   |   URL
                  -----------------------

You do not have a GitHub Enterprise account authenticated!

If you have a GitHub Enterprise account, then you can add it in the Settings to gain access to your repositories.                                                                                       -----------
                                clickable, closes this modal and opens the settings ^

Otherwise, to learn more about GitHub Enterprise and to start your free trial today visit:
https://enterprise.github.com/home
----------------------------------------------


                                                              [Cancel] [Clone (grey/unclickable)]
````

**Comment by donokuda** [comment]
> Though I guess on the Publish Repository view, we always show the Enterprise tab 🤔 I'll go with that for parity.

👍 and just for reference, we could use the same prompt in the publish repo tab.

<img src="https://user-images.githubusercontent.com/1174461/30131579-2abc45b4-9302-11e7-8cb0-6fb6489248b8.png" width="458" />

**Comment by joshaber** [comment]
💯💥 

<img width="471" alt="screen shot 2017-09-06 at 1 46 01 pm" src="https://user-images.githubusercontent.com/13760/30126466-fee31fbe-9309-11e7-89a1-6736bb7be2b0.png">

**Comment by donokuda** [comment]
Fastest turnaround evar! 😄 

I'm curious if it makes sense to not render the Cancel / Clone buttons here unless we're signed in. Is it possible to conditionally render the action buttons?

**Comment by rlabrecque** [comment]
Just disable the Clone button (grey/inactive) if there's no repo selected, and it might already work like that. It basically automatically fixes this too, because you can never select a repo in this case.

**Comment by joshaber** [comment]
>I'm curious if it makes sense to not render the Cancel / Clone buttons here unless we're signed in. Is it possible to conditionally render the action buttons?

Yup! Again this matches the existing Publish dialog nicely.

<img width="473" alt="screen shot 2017-09-06 at 4 43 16 pm" src="https://user-images.githubusercontent.com/13760/30133716-d97a4252-9322-11e7-9c8c-594215a269dd.png">
