### ISSUE TITLE
Clone  behavior not  as expected 

### ISSUE THREAD

**Issue by gengjiawen** [desktop/desktop#5713]
## Description
git clone not using ssh url, even if I choose it.

## Version
1.4.0
* Operating system:
Windows 10.

### choose repo to clone 
![image](https://user-images.githubusercontent.com/3759816/45914242-bb244400-be74-11e8-8a3a-196c9edd3b33.png)

### Expected Behavior
Github clone use ssh url.

### prompt change to http url
![image](https://user-images.githubusercontent.com/3759816/45914263-f7f03b00-be74-11e8-8178-9c19ff9aa1b8.png)
### check with git remote -v
![image](https://user-images.githubusercontent.com/3759816/45914301-941a4200-be75-11e8-8964-11b853267738.png)

**Comment by mo7sener** [comment]
I don't think the "Download ZIP" and the "Open in Desktop" options get affected by whether you chose to use HTTP or SSH. That's because if you chose one of those, then you probably don't care whether it's done using SSH or HTTP. That's because when you're invoking Desktop, it's less troubling to send it the current page's URL than accessing a database or parsing it to SSH.

**Comment by shiftkey** [comment]
> That's because if you chose one of those, then you probably don't care whether it's done using SSH or HTTP. 

Yep, the browser ignores whether you've set "Use HTTPS" or "Use SSH" for the "Open in Desktop". 

Also, if you paste the SSH URL and we detect it's a GitHub remote and choose the `clone_url` value from the API:

https://github.com/desktop/desktop/blob/28d9f9569ba1b5bdc5d60bd24d3e4c1ca2e757eb/app/src/ui/clone-repository/clone-repository.tsx#L354-L361

We've designed it in this way because we have some GHE customers wanted to be SSH-only, but maybe our "Use SSH" or "Use HTTPS" setting doesn't flow through the API yet, and it continues to favour HTTPS.

**Comment by shiftkey** [comment]
I've opened #5721 to address the "I pasted in an SSH URL and it changed it to an SSH URL" issue, but the browser and API behaviour requires me to chase up some other teams (which will take time and I'm not sure how that will go).

**Comment by steveward** [comment]
Closing this out as stale.
