### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by eoindouglas1** [desktop/desktop#5724]
Cannot Login using Github Desktop. 

"failed to fetch" pop up warning. 

![image](https://user-images.githubusercontent.com/4404419/45960320-e5603800-c013-11e8-9e3a-454d6d3407ca.png)

**Comment by tierninho** [comment]
@eoindouglas1  thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
