### ISSUE TITLE
'Please tell me who you are' error was thrown even though name/email were set in the `Git` tab

### ISSUE THREAD

**Issue by ori1337** [desktop/desktop#5746]
## Description

i did what "shiftkey" said to do and it worked 

but the bug in here is 
that everything was filled i only press save in there ... 
its a bug becuase it didnt read it Or save it for some reason

## Version

* GitHub Desktop:

* Operating system:

**Comment by shiftkey** [comment]
@ori1337 Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Also, could you attach the full log files? The **Help** | **Show Logs in Explorer** menu items should open the logs folder, and inside those are the log files generated by day. This will provide some more information to help troubleshoot.

Thanks for understanding and meeting us half way 😀

**Comment by steveward** [comment]
@ori1337 I think I understand the issue you experienced -- please let me know if I have this correct:

1. You experienced the same error as https://github.com/desktop/desktop/issues/4059, where an error is thrown if a name and email are not set in the .gitconfig.
2. You followed the steps that @shiftkey provided in https://github.com/desktop/desktop/issues/4059#issuecomment-386841745, but when you went to the menu to fill out your name and email those two fields were already populated.

Let me know if I am correct in this assumption. It would also be helpful to know if you remember previously setting your name and email during the initial installation of GitHub Desktop, or if you had previously set it using the command line or another GUI application.

**Comment by ori1337** [comment]
yes 
i did what he say 
http://prntscr.com/kz0bkk
everything was in place so i just press save
and its just worked

**Comment by steveward** [comment]
@ori1337 Thanks for the update. Would you mind uploading a log file from the day you experienced this issue? The log file should show some more details about what may have happened here.

To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`. It would be helpful if you could send a log file from the day that you first launched GitHub Desktop.

**Comment by shiftkey** [comment]
@steveward this reminds me a bit of #5046 where the user wasn't able to save their changes and we didn't show the error

**Comment by tierninho** [comment]
@ori1337 As we haven't heard back from you, we will be closing this issue for now. We are happy to revisit the issue if you have more questions. Thank you.
