### ISSUE TITLE
100MB file size issue-Git wont let me push and says that I have to clear the file from history

### ISSUE THREAD

**Issue by Tmbutts** [desktop/desktop#5755]
## Version

* GitHub Desktop:

* Operating system:

**Comment by outofambit** [comment]
Hi @Tmbutts! Thanks so much for taking the time to file an issue. I'm sorry you've run into this. This particular problem is a known issue—we're tracking it over at https://github.com/desktop/desktop/issues/997.

We also have some workarounds at https://github.com/desktop/desktop/issues/5718#issuecomment-423957795. I'm going to close this issue, but feel free to reopen and comment if you have additional questions! Thank you!

**Comment by leighjboyd** [comment]
To people finding this old thread and are new to Git and GitHub, there is a simple alternative to all the complex solutions posted on this topic.  They will tell you you need to clone your repository, monkey around inside the local repo to find and delete these files with special tools that you need to download (like the methods listed here:

Removing sensitive data from a repository - GitHub Docs

However, I found a much simpler way:

in GitHubDesktop, click on the History tab, 
you will see a list of commits with an up arrow beside them indicating that they have not yet been pushed.
starting from the top, and working your way down:

(If you want to set things back exactly as you had them, look through each commit and take note of what files were committed and what comments/description were used for each commit.  In my case I am working alone and don't really care too much to get the history exactly right, as long as my files are safe in version control somewhere)

right click -> revert changes in commit
Are you sure? Yes..
do this until all the commits with the up arrows are gone.

Now you can re-commit these changes since all the modified files will now reappear in the changes tab.
(re commit as a group, or individually using the notes you took from above)

Much easier than attempting surgery on a local repo!
