### ISSUE TITLE
Update login error message to reflect form input

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#5766]
When using the login form (welcome flow or Preferences) we display an error message if the username/email/password is incorrect.

"Incorrect username or password."

However, the above error message is generic and only reflects the the username field. The error message should recognize when a user attempts to login with an email address.

- Do we make the error message dynamic or simply update the text? As the latter is easier, so I suggest we update the message to: "Incorrect username/email or password."

<img width="554" alt="screen shot 2018-09-27 at 9 51 38 am" src="https://user-images.githubusercontent.com/14828183/46161734-3140f600-c23b-11e8-84ea-f80e97082778.png">
<img width="406" alt="screen shot 2018-09-27 at 9 50 57 am" src="https://user-images.githubusercontent.com/14828183/46161735-3140f600-c23b-11e8-8c90-e2fd864baa91.png">

Code:
https://github.com/desktop/desktop/blob/0bf1cc9192e9e6935de0aa283414f5038a8b31d1/app/src/lib/stores/sign-in-store.ts#L357

1.4.2-beta0, mac

**Comment by Daniel-McCarthy** [comment]
I see a pull request is already currently open for this to update the message to include email in the error.

Though, if at a later time it's decided it would be preferable to go more dynamic, for deciding which to show it would likely be sufficient to check if the input text contains an `@` since it is not a legal GitHub name character.

Just wanted to mention this as food for thought. :+1: 
It's great seeing the good first issue tag being used more.

**Comment by tierninho** [comment]
@tiagodenoronha thanks for the quick fix!!

@Daniel-McCarthy Yes, the dynamic route is a good option. I'll let the team weigh in first. Many thanks for the input and all the hard work!

**Comment by tiagodenoronha** [comment]
That is actually a nice solution. Check whether the input has an @ and present a different message per case!

**Comment by tiagodenoronha** [comment]
@tierninho Close if it's ok!
