### ISSUE TITLE
error name="(unset)"

### ISSUE THREAD

**Issue by argon27dv** [desktop/desktop#5780]
An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.645" (uid=1000 pid=24246 comm="/snap/github-desktop/35/opt/GitHubDesktop/desktop ") interface="org.freedesktop.Secret.Service" member="OpenSession" error name="(unset)" requested_reply="0" destination=":1.18" (uid=1000 pid=2067 comm="/usr/bin/gnome-keyring-daemon --daemonize --login ")

Cloning into '/home/cesar/Документы/GitHub/ubuntu-scripts'...
/snap/github-desktop/35/opt/GitHubDesktop/resources/app/git/libexec/git-core/git-remote-https: error while loading shared libraries: libcurl.so.4: cannot open shared object file: No such file or directory

## Version

* GitHub Desktop:

* Operating system:

**Comment by iAmWillShepherd** [comment]
Thanks for reaching out!

We require the template to be filled out with all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway 😀
