### ISSUE TITLE
https://hackerone.com/github

### ISSUE THREAD

**Issue by bernarddanielgaudin1** [desktop/desktop#5784]
## Version

* GitHub Desktop:

* Operating system:

**Comment by iAmWillShepherd** [comment]
Thanks for reaching out!

We require the template to be filled out with all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway 😀

**Comment by ASDOPRIGJEHO** [comment]
рейд в клубе https://vk.com/app4397521_312213956
