### ISSUE TITLE
error on desktop

### ISSUE THREAD

**Issue by vankasrini** [desktop/desktop#5793]
fatal: unable to access 'https://github.com/KLVJPinnacleTeam/NeptuneUI.git/': schannel: next InitializeSecurityContext failed: Unknown error (0x80092013) - The revocation function was unable to check revocation because the revocation server was offline.

**Comment by iAmWillShepherd** [comment]
Thanks for taking the time to open an issue! 🙇 

Without additional context, this issue seems related to a [known issue](https://github.com/desktop/desktop/blob/master/docs/known-issues.md#certificate-revocation-check-fails---3326) around certificate revocation failing.

I'm going to close this since we have a workaround in place. If it does not work for you, feel free to re-open this issue. 👍
