### ISSUE TITLE
GitHub Notifications via Desktop

### ISSUE THREAD

**Issue by jeremyzilar** [desktop/desktop#5811]
As a user who works across a number of open-source projects, I would like to be able to get notified (via the Desktop App?) when I have been tagged or mentioned in an issue or PR of any project that I may be working with in GitHub.

At the moment, I am getting notifications via email https://github.com/settings/notifications
and those are technically working, but email is a unfixable swamp and there is still too much friction.

Things that would be nice to haves:
- Get notifications via the GitHub Desktop App
- Get notifications in Slack, DM'd to me directly
- Use an app on my phone that sends push notifications when I've been tagged or mentioned _(a bit sub-optimal, but it would be better than nothing)_

**Comment by iAmWillShepherd** [comment]
Thanks for taking the time to open an issue! 🙇 

cc @desktop/product for thoughts as this is something they may have an interest in.

**Comment by billygriffin** [comment]
Hey @jeremyzilar! Echoing Will, really appreciate you opening this.

In Desktop specifically, we're not looking at notifications except in the context of individual workflows (for example, being notified when your branch has diverged from your default branch: https://blog.github.com/2018-07-30-github-desktop-1.3/).

More broadly, I agree with you that GitHub more broadly could make some improvements to help users separate signal from noise and ensure that things of particular importance don't get lost in the shuffle. I've passed that along and it's something we're evaluating how to improve.

Since we don't intend to tackle this is Desktop, I'm going to close this issue, and thanks again!
