### ISSUE TITLE
how to create remote branch by git branch -b 

### ISSUE THREAD

**Issue by yipeng2000** [desktop/desktop#5819]
**Please describe the problem you think should be solved**
A clear and concise description of what the problem is and who else might be impacted. Screenshots are encouraged.

Example:

> “When I run into a merge conflict, I don’t know where to go to resolve it. Anyone who works off of multiple branches will likely run into this problem at least occasionally.”

**[Optional] Do you have any potential solutions in mind?**
A clear and concise description of one or more solutions you think might solve the problem. Please include any considered drawbacks or tradeoffs, and how users might use your solution(s). Screenshots or mockups are helpful here!

**Comment by steveward** [comment]
@yipeng2000 thanks for contributing.

>how to create remote branch by git branch -b

Once you [create a branch](https://help.github.com/desktop/guides/contributing-to-projects/creating-a-branch-for-your-work/) in GitHub Desktop you will see the `Publish branch` option appear. This will publish your local branch up to the remote repository on GitHub. Let me know if you have any other questions about this.

---

In the future it would also be helpful if you could fill out the template when you submit a new issue. We do this so that we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests. Thanks!
