### ISSUE TITLE
Making a commit with a username that is not logged in.

### ISSUE THREAD

**Issue by waygou** [desktop/desktop#5821]
## Description
I've logged in with another user in Github desktop but when I commit data to the repository, it commits with the previous user that I was logged in.
Also, the icon in the commit description doesnt change (minor issue).

## Version
1.4.1

* Operating system:
Windows 10

## Steps to Reproduce
1. Log in with a user.
2. Make some commits in a repo.
3. Log off and log with another user.
4. Make more commits in the repo.

### Expected Behavior
The commit should be made with the current logged user.

### Actual Behavior
Somehow, the commit is made with the previous user.
![image](https://user-images.githubusercontent.com/39349827/46533168-f0cd2200-c8a3-11e8-9886-9d792c2c4da8.png)
![image](https://user-images.githubusercontent.com/39349827/46533189-0a6e6980-c8a4-11e8-89ec-cdb0298d7b55.png)
![image](https://user-images.githubusercontent.com/39349827/46533217-1bb77600-c8a4-11e8-8cb6-ca7efc38ccd8.png)

**Comment by steveward** [comment]
Thanks for contributing @waygou.

This issue is due to the fact that the name and email address in your `.gitconfig` file still point to the initial user account you logged in to GitHub Desktop with. When you first launch GitHub Desktop, we help you to sign in to your GitHub account, and after that we pre-fill the Git configuration information (for committing) using the name and email address from your GitHub account. From there, any time you create commits in Desktop, they will have this name and email address attached to them. You can read more about this in our [help article](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/).

We don't do any extra work to update your Git configuration if you happen to change accounts. As a workaround you can directly update your Git configuration by going to the File menu and selecting `File` > `Options` > `Git`. You can follow along in https://github.com/desktop/desktop/issues/610 for updates about a feature that would warn users who are committing with an email address that is not associated with their current account.
