### ISSUE TITLE
Error with unreadable characters when clone

### ISSUE THREAD

**Issue by Artemonim** [desktop/desktop#5838]
## Description
I tried to clone a repository to which I had no rights.
An error with unreadable characters appeared.

## Version
* GitHub Desktop: 1.4.2
* Operating system:  Windows 10.0.17134

## Steps to Reproduce
Try to clone a repository to which you hadn't rights.

## Additional Information
![2018-10-08 00-09-21](https://user-images.githubusercontent.com/36363466/46587071-099a2b00-ca90-11e8-8e2e-a4eb6646625c.png)
The error could occur because Russian is the main language in my system.

### Logs

[2018-10-07.desktop.production.log](https://github.com/desktop/desktop/files/2454329/2018-10-07.desktop.production.log)

**Comment by steveward** [comment]
Thanks for contributing @Artemonim.

This error is usually caused by your network blocking the attempt by Windows to check the revocation status of a certificate, which then causes the whole operation to error. You can find a workaround for this issue here:

https://github.com/desktop/desktop/blob/master/docs/known-issues.md#certificate-revocation-check-fails---3326

We have also seen cases where Kaspersky AV software has caused this, so if you are running that I would recommend temporarily disabling it to see if it fixes this issue.
