### ISSUE TITLE
i CANT see any files when there are files in the folder but not in github desktop app

### ISSUE THREAD

**Issue by GamingMineblox** [desktop/desktop#5845]
## Version

* GitHub Desktop:

* Operating system:

**Comment by billygriffin** [comment]
Hi @GamingMineblox, thanks for reporting the issue. We ask that you fill out the template to make sure we have enough information to properly figure out what's going on and see if we can get it fixed. Screenshots are particularly helpful.

Thanks for understanding and meeting us halfway! 😄

**Comment by GamingMineblox** [comment]
here is an screenshot
![image](https://user-images.githubusercontent.com/42892277/46613559-cf726d00-cb13-11e8-826f-128b3958a865.png)

**Comment by billygriffin** [comment]
Thanks @GamingMineblox. Would you mind also filling out the template so we can understand what flow you were trying to accomplish. I suspect the culprit is that nothing has *changed* in those files you've screenshotted, so you shouldn't expect anything to show up as changed in GitHub Desktop. The app isn't designed to see all your files - we usually recommend using an editor (like [Atom](https://atom.io/)!) or your explorer like you're doing there on the left of the screenshot. Hope that helps!

**Comment by shiftkey** [comment]
Closing this out because the template is still empty and @billygriffin's previous comment explains the current behaviour.

@GamingMineblox please open a ["Problem to Raise"](https://github.com/desktop/desktop/issues/new?template=problem-to-raise.md) issue if you'd like to suggest changes to this behaviour.

**Comment by dataman132** [comment]
why doesn't git hub show the files. isnt that the purpose?
