### ISSUE TITLE
too slow

### ISSUE THREAD

**Issue by ram-wavity** [desktop/desktop#5862]
## Description

It's not responding properly when i do some actions with existing options on menu. basically It's  hanging. 

I am using windows 10 system and also my github desktop is uptodate.

## Version

* GitHub Desktop:

* Operating system:

**Comment by tierninho** [comment]
@ram-wavity thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by shiftkey** [comment]
@ram-wavity are you able to record a timeline profile of the app when it has this issue, so we can troubleshoot further? I've updated the document in this PR: https://github.com/desktop/desktop/pull/5899

**Comment by shiftkey** [comment]
Closing this out due to inactivity. @ram-wavity if you're able to provide more information about the issue we're happy to troubleshoot further.
