### ISSUE TITLE
Make newly-published repos default to public

### ISSUE THREAD

**Issue by Boundarybreaker** [desktop/desktop#5869]
Publishing new repositories in the desktop app currently defaults them to private. There's no option to change this anywhere, so I have to remember to check the box while publishing (that was default-public in desktop classic) so that anyone else can see my code. I, and many, many others, use GitHub to share open-source projects with the world. Making the official desktop app default to working against that is unhelpful, especially when there's no way to change that behavior. I understand it's to push people towards private repositories since those are Github's source of income, but that's still not a reason to make it impossible to change.

**Comment by billygriffin** [comment]
Hi @Boundarybreaker, thanks for the idea! Our rationale on this doesn't have anything to do with private repos being GitHub's source of income. Rather, it's to help mitigate risk for people who don't want their repos to accidentally be made public because they forgot to change the default selection. We don't want to put people in a bad spot where they're accidentally exposing code they did not intend to. Hope that helps in understanding, and I also totally understand that it's occasionally frustrating for you. I'm going to close this as we don't intend to change the existing behavior.
