### ISSUE TITLE
Error while clone repo

### ISSUE THREAD

**Issue by tsivakishore** [desktop/desktop#5888]
Hi,
I am trying to clone repo from github desktop to in my local machine, i am getting the below error: 
"Cloning into 'E:\MyPrograms\MyPorjects\xxxxxxxxxxx\xxxxxxxxxxx'...
fatal: unable to access 'https://github.com/xxxxxxxxxxx/xxxxxxxxxxx.git/': schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate."

Please provide the solution.

**Comment by billygriffin** [comment]
Hi @tsivakishore, thanks for the report. We ask that you fill out the bug template so we have enough information to properly diagnose the issue.

Thanks for understanding and meeting us halfway! :smile:

**Comment by steveward** [comment]
@tsivakishore this error is usually caused by your network blocking the attempt by Windows to check the revocation status of a certificate, which then causes the whole operation to error. You can find a workaround for this issue here:

https://github.com/desktop/desktop/blob/master/docs/known-issues.md#certificate-revocation-check-fails---3326

We have also seen this error occurring for users running certain antivirus software like Kaspersky due to the filtering it performs. If you are running Kaspersky try temporarily disabling it to see if that fixes this issue, and let us know if you run into any further issues.
