### ISSUE TITLE
My Repos are not showing up

### ISSUE THREAD

**Issue by gct165201b** [desktop/desktop#5897]
I have a repository, but it is not showing up on Github Desktop Application.

**Comment by Daniel-McCarthy** [comment]
Hello @gct165201b ,
Upon logging in to GitHub Desktop, to start working in any of your repositories you must first clone the repository via `File->Clone Repository...`. You will have to do this for each repository you wish to work in.

If this is not quite the issue you are running into then I would encourage adding more details to this Issue and filling out the template so that others can help you better.

**Comment by billygriffin** [comment]
I also suspect this might be helped by https://github.com/desktop/desktop/pull/5878 😄

**Comment by tierninho** [comment]
@gct165201b As we have no heard back from you, we are closing this issue for now. Please feel free add any new details and we can open it back up. Thanks!
