### ISSUE TITLE
Feature request: override git name / email by repository

### ISSUE THREAD

**Issue by Seb33300** [desktop/desktop#5902]
I am working as freelance for multiple companies and most of them give me an email address I have to use for everything related to the job.

So I am always switching from an email to another and sometime I forget to do...

I think it could be nice if you can add a tab in the repository settings to override the default git name & email options.

**Comment by billygriffin** [comment]
@Seb33300 Thanks for the request!

We had a similar discussion to this in #2829, which goes a little more into why we're hesitant to make the change without fully thinking through the consequences this would have on other projects and users who don't juggle two accounts. Please feel free to add your thoughts to that issue about this problem.

@shiftkey also mentions a workaround in #2829 to set your commit email per-repository through the command line:

> git config --local user.email sampleuser@example.com

Once you've done that, it will override what Git has setup. In this way, you can at least differentiate the default email between your two email accounts for your different projects. Hope that helps!

I'm going to close this since we're tracking handling of multiple accounts in #2829. Thanks again!

**Comment by Seb33300** [comment]
Fixed by https://github.com/desktop/desktop/pull/11595

Thank you @sergiou87

**Comment by billygriffin** [comment]
Just want to note here that a lot of this is @say25 as well! Thanks so much! ❤️
