### ISSUE TITLE
Failure to clone repository due to remote error:    Repository not found.

### ISSUE THREAD

**Issue by tronster** [desktop/desktop#5912]
WHY?
Instead of a template of what to write for bug reports, why not prefill it from the client?   I did press "Help > "Report Issue" from your own client; it should be able to fill this out.

This repository: https://github.com/gamaral/marshmallow_h fails to clone via your desktop app.

## Version

* GitHub Desktop: 1.4.2

* Operating system: macOS 10.13.16

## Steps to Reproduce

1. On a Mac, in Google Chrome, browser to: https://github.com/gamaral/marshmallow_h fails 
2. Select "Clone or Download"
3. In the popup area now select "Open in Desktop"

### Expected Behavior

Repository to clone.

### Actual Behavior

After a few seconds of copying down files, it fails.

## Additional Information

Attempted twice.

### Logs

End of the log (name replaced with <USERNAME>):
Cloning into '/Users/<USERNAME>/Source/github/marshmallow_h/contrib/libogg/code'...
fatal: remote error: 
  Repository not found.
fatal: clone of 'git://github.com/gamaral/libogg.git' into submodule path '/Users/<USERNAME>/Source/github/marshmallow_h/contrib/libogg/code' failed
Failed to clone 'contrib/libogg/code' a second time, aborting

**Comment by shiftkey** [comment]
@tronster thanks for the feedback!

The clone will fail from the command line if you specify `--recurse-submodules` e.g. `git clone https://github.com/gamaral/marshmallow_h --recurse-submodules`

The problem is that this submodule:

<img width="471" src="https://user-images.githubusercontent.com/359239/47039493-78474a80-d15a-11e8-97e5-3153c4646696.png">

Refers to a commit that no longer exists: https://github.com/gamaral/libogg/tree/337aec81bab31c4c1ae460a9d7dd28f593881801

We have an open issue about letting you proceed with a missing submodule #3242 (which I gather is what you are looking for here) so I'll add your details to that so we can track it.
