### ISSUE TITLE
Not visually apparent which repo is selected to clone

### ISSUE THREAD

**Issue by dsanders11** [desktop/desktop#5937]
**Please describe the problem you think should be solved**
This issue is borne out of some bad experiences with the Clone a Repository dialog. Since the issues all seem to stem from a root design choice, I'm going to group them all here under one issue, with the generic title.

- The three tabs (GitHub.com, Enterprise, URL) have shared state with regards to the repository URL and the local path. This creates weird UX:
  - Changing the local path under any tab affects the others.
  - The 'Clone' button might do something entirely different than you expect for the tab you're on.
    - Use the GitHub.com account shortcut (say, `desktop/desktop`) under the URL tab. Go to GitHub.com tab and change the local path. Ask someone else to look at the screen and predict what will happen if you hit clone.
- The GitHub.com tab's behavior is confusing.
  - There's no visual indication regarding which repository will be cloned. If you've selected something in the list that *might* be what will be cloned, unless a bug like #3596 exists, or you switch tabs and then go back to the list which will result in nothing being visually selected. There's no definitive visual indication about what will be cloned when you click the clone button.
  - Filtering, selecting a repository, then clearing the filter also has issues. The selected repository is now somewhere in your long list of repositories, and there's no way to see which one was selected without scrolling down the list until you see which one has the visual indication.

**[Optional] Do you have any potential solutions in mind?**
Personally I think this dialog could use a UI refresh.

- Get rid of shared state across the tabs, make them each independent like they logically seem.
- The main GitHub.com tab should have a 'Selected Repository' UI element that you can clear and which is separate from the selection list, which would be just for selecting, and would be disabled if there is already a selected repository.
- Drop the magic GitHub username and repository text from the URL tab, leave that tab for the simple task of providing a URL to clone into a local path. By making it magic text under that tab you make rich functionality too cumbersome to add, such as checking if it's a valid GitHub.com repo before trying to clone.
  - Instead put this functionality under the GitHub.com tab. Turn the 'Filter' box into a more generic 'Find', and include GitHub.com results under a separate header which will be below 'Your Repositories' (with de-duplication as necessary).

Here are some (awful) mockups of how the GitHub.com tab might look after those suggested changes.

![image](https://user-images.githubusercontent.com/5820654/47174209-d3954c00-d2c4-11e8-8e0c-293910fec095.png)

![image](https://user-images.githubusercontent.com/5820654/47173924-32a69100-d2c4-11e8-89c2-d5b304d94506.png)

**Comment by billygriffin** [comment]
Thanks @dsanders11, we appreciate the thoughts. For a bit of feedback, this issue is pretty difficult to digest and it'd be helpful to more clearly state the problem(s) you're describing instead of lumping into a "Bad UX" issue.

As I understand it, there is one primary problem that you're articulating:

**If I select a repo in any of the tabs, that repo remains selected (even across tabs) but it's not visually apparent that it is the repo that will be cloned when I click "Clone."**

Would you say that's accurate?

**Comment by dsanders11** [comment]
@billygriffin, I stated several problems in the bullet points which I feel cause the bad UX, I'm not sure how I can more clearly state them. That may just be a communication issue on my side.

> Would you say that's accurate?

Yes...and no. :-) It's accurate on face value, but I don't feel it fully addresses the issue. Reducing the issue to a one-liner may produce a 'solution' which is too narrow and doesn't fix all of the bad UX. That's why I tried to list the different bad UX I'd run into with the dialog and what I thought was the root cause of them.

The one-liner you broke it down to (while a nice concise description of a subset of the problem) leaves out the shared state between tabs in a way that may not produce a solution which addresses that. It may just kick the can down the road, tightening up a few edge cases currently, but I believe the current design of the dialog will continue to cause more edge cases and bugs.

So, to give it another quick go, I think the primary problem is the dialog has hidden state which makes for unclear UX and bugs:
* The state is shared across the tabs, which is unintuitive
* The user may not understand that the dialog has state, or what that state currently is
  * The dialog's UI has no concrete concept of 'selected repo'
    * The user sees they can select a repo in a list under the first tab, but due to various issues (some of them legit bugs like #3596), what is visually selected isn't always what the dialog thinks is the 'selected repo'
    * The clone button may be available when visually there is nothing selected

**Comment by billygriffin** [comment]
Thanks @dsanders11 for clarifying, really appreciate it.

I chatted about this with a few folks, and I think your observations are accurate, and also that they likely don't present a problem for the vast majority of users going through the cloning workflow. People are likely going to go to one place, find a repo (or paste a URL) and click clone. I think it'll be a fairly rare case where someone is clicking around a bunch between tabs, especially after they've taken some initial action (like pasting in a repo in the URL tab or selecting one in the GitHub.com tab).

So I agree that this could be improved, I think it's pretty low priority just because I don't think it's blocking many people from accomplishing what they're trying to. I'm going to chat about it with our team internally to see whether there's something lightweight that we could do to make people less likely to get into trouble here. Thanks again! 😄
