### ISSUE TITLE
Github desktop not sensitive to rename a file !

### ISSUE THREAD

**Issue by ziaratban** [desktop/desktop#5959]
hi
when i rename my file in repository (by windows explorer), github desktop not any change !

**Comment by niik** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
