### ISSUE TITLE
Authentication failed error when Pushing signed in with permitted GitHub account

### ISSUE THREAD

**Issue by miracleflame** [desktop/desktop#5965]
## Description

Authentication failed error when Pushing signed in with permitted GitHub account. I have narrowed down the issue to be isolated for my domain user profile. If I log in as local user on the same PC configuration there is no issue at all. When using domain account the app is totally confused on the matter of who is committing. I've had my domain account and e-mail address randomly and automatically switched to as committer which I've never asked for or provided anywhere! Even in the Options the only account signed in is my GitHub account. Why is the app even concerned whether I am using domain or local windows user profile and what's my e-mail address for the domain account?

## Version

1.4.3
* GitHub Desktop:

* Operating system:
Microsoft Windows [Version 10.0.17134.345]

## Steps to Reproduce

1. Log into Windows using domain account
2. install the latest GitHub Desktop
3. Sign in with permitted GitHub account
4. clone own repo
5. make file change
6. commit
7. push

### Expected Behavior

The error message pops-up stating "Authentication failed. blah blah make sure you're signed in with account that has permissions blah..."

### Actual Behavior

Sometimes the Committer is randomly and automatically switched to my domain account name with domain e-mail address as if I've ever provided this data to the app or asked for using it. Even if that does not happen it is never possible to Push commits due to authentication error though pulling is okay.

## Additional Information

Not really but this is about ANY repo while I am signed in as miracleflame under domain user profile.

### Logs

[2018-10-01.desktop.production.log](https://github.com/desktop/desktop/files/2500458/2018-10-01.desktop.production.log)

**Comment by niik** [comment]
Hey @miracleflame, thanks for opening this. Based on the logs you provided it looks like the push is succeeding but fetch is failing due to Git being unable to write an object to your machine

```
2018-10-01T00:15:53.570Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
remote: Counting objects: 36, done.        
remote: Compressing objects:   6% (1/15)           
remote: Compressing objects:  13% (2/15)           
remote: Compressing objects:  20% (3/15)           
remote: Compressing objects:  26% (4/15)           
remote: Compressing objects:  33% (5/15)           
remote: Compressing objects:  40% (6/15)           
remote: Compressing objects:  46% (7/15)           
remote: Compressing objects:  53% (8/15)           
remote: Compressing objects:  60% (9/15)           
remote: Compressing objects:  66% (10/15)           
remote: Compressing objects:  73% (11/15)           
remote: Compressing objects:  80% (12/15)           
remote: Compressing objects:  86% (13/15)           
remote: Compressing objects:  93% (14/15)           
remote: Compressing objects: 100% (15/15)           
remote: Compressing objects: 100% (15/15), done.        
error: unable to write sha1 filename .git/objects/d3/9eb3bd987cc287fd60b267989d037cab279878: Permission denied
fatal: failed to write object
fatal: unpack-objects failed
```

Is is possible that, when you're signed in to your domain account, your home directory is actually a network directory? The "permission denied" message seen above is likely coming from your file system or from an anti-virus solution.

Could you try capturing a new log file when the error occurs?

> Sometimes the Committer is randomly and automatically switched to my domain account name with domain e-mail address as if I've ever provided this data to the app or asked for using it.

Are you perhaps signed in to your account on more than one machine? GitHub Desktop stores its user settings under the roaming profile on Windows so I'm wondering if you have two machines competing. GitHub Desktop only sets the user name and email in the global Git config file during the first launch, or when manually changed through the preferences dialog. Other than that we respect the values set in the .gitconfig in your home directory.

**Comment by miracleflame** [comment]
This is labelled more information needed.

What more information shall I provide?

**Comment by shiftkey** [comment]
@miracleflame apologies for the delay in replying. There's a couple of interesting things in the logs you provided.

The `domain.log` file shows a successful clone operation (this looks like it was a different repository to the original `gog_bloodlines_cz` repository that reported the issue):

```
2018-10-22T15:16:04.257Z - info: [ui] Executing clone: git -c credential.helper= clone --recursive --progress -- https://github.com/miracleflame/radio.git C:\Users\fg4p8y\Documents\GitHub\radio (took 11.585s)
```

@miracleflame are you able to test a clone of the original problem repository with a local and a domain account? The contents of a specific repository might be needed to trigger the original issue.

Also, I see a significant amount of network-related errors - whether for `domain` or `local` accounts.

For example: fetching details from the GitHub API fails because the credentials are not valid (this should be a token generated by Desktop after doing the OAuth flow to sign in):

```
2018-10-22T15:16:05.455Z - warn: [ui] fetchPullRequests: failed for repository miracleflame/radio
Error: Bad credentials
    at Object.t.parsedResponse (C:\Users\fg4p8y\AppData\Local\GitHubDesktop\app-1.4.3\webpack:\app\src\lib\http.ts:161:4)
    at <anonymous>
```

I also see this network error when trying to push changes:

```
2018-10-22T15:13:34.675Z - error: [ui] `git -c credential.helper= push origin master:master --progress` exited with an unexpected code: 1.
Enumerating objects: 3, done.
Counting objects:  33% (1/3)   
Counting objects:  66% (2/3)   
Counting objects: 100% (3/3)   
Counting objects: 100% (3/3), done.
Delta compression using up to 8 threads
Compressing objects:  50% (1/2)   
Compressing objects: 100% (2/2)   
Compressing objects: 100% (2/2), done.
Writing objects:  50% (1/2)   
Writing objects: 100% (2/2)   
Writing objects: 100% (2/2), 236 bytes | 78.00 KiB/s, done.
Total 2 (delta 1), reused 0 (delta 0)
fatal: the remote end hung up unexpectedly
fatal: the remote end hung up unexpectedly
error: RPC failed; HTTP 401 curl 22 The requested URL returned error: 401
Everything up-to-date
```

I've seen a few reports about this in the past that seem to be traced to proxy servers in between your computer and GitHub that meddle with the traffic - not sure how important this is to you, but I believe it's a separate issue to the one originally reported.

**Comment by miracleflame** [comment]
The issue is not isolated to any specific repo. ALL repos are affected!

All errors in local.log are caused by temporary WiFi signal drop as mentioned already.

This issue must be something with the particular domain userprofile itself as I have tried under different user profile and it worked.

Could you list all the user profile related data in AppData, ProgramData and HKCU registry related to GitHub? I'll try to purge them all and test anew.

**Comment by shiftkey** [comment]
> Could you list all the user profile related data in AppData, ProgramData and HKCU registry related to GitHub? 

 - `APPDATA` and `LOCALAPPDATA` usage are detailed here https://github.com/desktop/desktop/blob/master/docs/installation.md#windows-1
 - `ProgramData` is not used
 - `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\GitHubDesktop`

**Comment by shiftkey** [comment]
@miracleflame no problem, and good luck!
