### ISSUE TITLE
Unable to deploy Struts application to Azure Devops from GitHub repository. Please guide steps to deploy

### ISSUE THREAD

**Issue by pavankumarProFit** [desktop/desktop#5975]
![capture1](https://user-images.githubusercontent.com/44398848/47358049-4009b400-d6e6-11e8-8e2f-8fe7315a8a35.PNG)
![capture](https://user-images.githubusercontent.com/44398848/47357980-033dbd00-d6e6-11e8-98f9-1e3171b219b2.PNG)

**Comment by steveward** [comment]
Thanks for contributing @pavankumarProFit. The 'upgrade' error you are encountering in GitHub Desktop is being thrown because you are on a free GitHub plan, and creating a private repository requires a [paid plan](https://github.com/pricing). 

It does look like you already have a public repository created at https://github.com/pavankumarProFit/ProFit, though. If you want to clone this repository in GitHub Desktop you can go to `File` > `Clone Repository` > `GitHub.com` and select the repository from the list. Once you have cloned the repository to GitHub Desktop you can make commits and push them back to GitHub. This should fix the issue you are seeing in Azure Pipelines where it can't find any commits. You can read our [help docs](https://help.github.com/desktop/guides/) for more information about working with GitHub Desktop.

I'm going to close this issue out, but please let me know if you have any other questions I can help with.
