### ISSUE TITLE
I dont know what's wrong but i cant commit  a change 

### ISSUE THREAD

**Issue by satyamohlan** [desktop/desktop#5976]
![2018-10-23 1](https://user-images.githubusercontent.com/35026814/47359469-7cd7aa00-d6ea-11e8-941a-20f3613d9931.png)

## Version

* GitHub Desktop:

* Operating system:

### Logs

[****](url)

**Comment by steveward** [comment]
Thanks for contributing @satyamohlan. Can you go to the file menu in GitHub Desktop and select `GitHub Desktop` > `Preferences` > `Git` and verify that your name and email address are correctly set there? 

You will also want to make sure that the email address matches an email address that is under your GitHub account so that you receive proper commit attribution.

**Comment by satyamohlan** [comment]
thanks for your help!
