### ISSUE TITLE
Push/pull button

### ISSUE THREAD

**Issue by joshaber** [desktop/desktop#598]
_From #549_

---

### Magic sync button

A very common feedback with the current clients has been that the sync button is scary. We believe that it currently serves two groups of users very well, the first being those who deeply understand Git and realize what it's doing and the second is those users who have deep trust in the app and doesn't care all that much about its inner workings. It doesn't work so well for the remainder of users and various suggestions have been made over the years on how to address this. The most current thinking being that we'd keep it but with some sort of combo/dropdown so that users could explicitly pull or explicitly push.

We've taken another approach by replacing the ambiguous sync button with a contextual button that changes from “Push,” “Pull,” and “Publish” based on how far or ahead you are from the remote branch. In essense we'll present the action that would be taken by a sync button.

We've opted for using Git terminology primarily so that the button text is something users can throw into Google in order to understand what the action does. Additionally in the case of errors we'll be able to present the underlying error as received from Git to the user (for them to Google). Note that this concept assumes that we keep background fetching in TNG:9000 as we'll need to reflect changes to the remote.

If your branch has commits not yet on the remote we’ll give you the option to push. If this fails (non-fast-forward) we'll present the user with information about why and offer to do a pull. If the user opts out the sync button state will have updated to reflect the now-known fact that the remote is ahead.

<img src="https://cloud.githubusercontent.com/assets/1174461/19458520/713389e2-9481-11e6-92d5-79911fce4522.png" width="315" />

If your branch has fallen behind the remote we’ll give you the option to pull.

<img src="https://cloud.githubusercontent.com/assets/1174461/19458521/7134b1fa-9481-11e6-9d1c-4216c5f3ad2f.png" width="315" />

If you’re both ahead and behind, we’ll make you do a pull before giving you the ability to push. This is similar to what Sync does today except we will do a pull and merge but we will not automatically push that merge commit. Instead we'll leave that action to the user so that we'll never push a result that they're not comfortable with. We might consider updating the button text in this state to something like 'Pull and merge'.

<img src="https://cloud.githubusercontent.com/assets/1174461/19458519/71334310-9481-11e6-8189-973c0cea0977.png" width="315" />

In the scenario where the client thinks you're neither ahead nor behind we'll offer to refresh the repository (a fetch). We've used 'Refresh' as the terminology here. We considered using 'fetch' but we then decided to add the 'Last fetched...' subtitle to all button states as a way of indicating that we do perform background fetches. It'll also give us a place to indicate that a background fetch is underway (we'll spin the sync arrows)

<img src="https://cloud.githubusercontent.com/assets/634063/19492704/26b751d0-9578-11e6-96e2-39ddbb64a458.png" width="315" />

If you haven’t published a repository or branch, this is where you’ll complete that action.

<img src="https://cloud.githubusercontent.com/assets/1174461/19458523/7137908c-9481-11e6-946b-53a772dfa343.png" width="315" />
<img src="https://cloud.githubusercontent.com/assets/1174461/19458586/ea1cd26e-9481-11e6-874e-77eed3d19ca9.png" width="315" />

If you aren’t logged into GitHub, then we’ll prompt for you to login.

![publish repository github](https://cloud.githubusercontent.com/assets/1174461/19457406/ff50f61c-947a-11e6-80dd-5cb318cd0512.png)
![publish repository enterprise step 1](https://cloud.githubusercontent.com/assets/1174461/19457405/ff4d47b0-947a-11e6-8fb1-7568addc17c0.png)
![publish repository enterprise step 2](https://cloud.githubusercontent.com/assets/1174461/19457404/ff4c245c-947a-11e6-9bb9-eda995473df6.png)

**Comment by spacebaconllc** [comment]
Sorry this is laughable UX. Well thought out but limited perspective on solving the actual issue. So we're stuck with two opposing functions sharing the same exact position. Your leet users that "have a deep understanding" should just stick to command line. "The rest of us" that actually use a gui do so for the exact reason of not having a deep understanding of the app. You should make it idiot proof. -resident idiot and ux guy

**Comment by spacebaconllc** [comment]
https://youtu.be/X6WHBO_Qc-Q

**Comment by j-f1** [comment]
@spacebaconllc Here is how we (or at least I) see the issue:

- if you have nothing to push, there is no need to show you a “push” button
- if you have nothing to pull, there is no need to show you a “pull” button
- if there isn’t a remote branch connected to the current branch, there’s no need to show a ”pull” button (we rename “push” to “publish” here so it’s clear what’s going to happen)
- if you have something to push and something to pull, the push will fail (since you don’t have the latest changes locally), so we only offer to let you pull. When you pull, we create a merge commit, which you can look over before you push.

We (or at least I) feel that this is a good compromise between ease-of-use (click that button until it says “fetch” and your code has been updated on the remote) and search-ability (if the “push” fails, you can google that term and get some help).

**Comment by spacebaconllc** [comment]
Great response , I certainly see it from your point of view also.  But what are we defending? The simplicity of one button? Screen realestate? Design ego? I'm confused. There is a fundamental UX flaw that leads to really messy history which has been voiced by "many" that has been patched rather than addressed in full . Two seperate buttons with inactive states is much more friendly and considerate of those with disabilities and will totally solve the accidental push issue.

I have extremely poor vision for example and often do not rely on text alone to make interface decisions. Button placement and function is critical in determining information heirarchy and usability. It shouldn't require an elaborate explanation. It should be intuitive by nature.

Let me give you a real life example of the flaw. 

Developer: hey Space Bacon, I'm pushing the latest right now! Check it out.

Me: great! I'll pull it right away! Hits the button, oh ship! I just pushed my .env file for the world to see (yes I know this can be excluded but not by a noob). Revert, revert again, revert. Oops I just reverted a reverts revert. Now I'm really confused and delete the folder for a fresh start. 

Why must we sustain this misery and for what cause?

**Comment by spacebaconllc** [comment]
PS the app I indeed beautiful and it pains me to think of adding another button. However this unfortunately is a textbook example of form over function and we need to address it :(.

**Comment by spacebaconllc** [comment]
"Form ever follows function, and this is the law. Where function does not change, form does not change." 
-Louis Sullivan

We have two functions within the same form (Atom in our case). 
If you indeed subscribe to the ideology that form ever follows function then we can assume if function changes so does form.
 If possible the two functions should expressed through two seperate forms designed specifically for that function.

**Comment by j-f1** [comment]
cc @desktop/design for 💭

**Comment by lee-dohm** [comment]
@spacebaconllc your comment was deleted as a violation of the [Desktop Code of Conduct](https://github.com/desktop/desktop/blob/master/CODE_OF_CONDUCT.md) as it was insulting or derogatory. You may consider this an official warning.

**Comment by spacebaconllc** [comment]
@lee-dohm that's a bit of a stretch but ok, I accept your decision. I'm here to help solve an issue with the app a lot of us are having.

**Comment by lee-dohm** [comment]
Constructive criticism is certainly welcome :grinning: If you're trying to work with us to make the product better, then let's focus on the positive and make things better. :+1:

**Comment by spacebaconllc** [comment]
Absolutely, as I intended. We've had a misunderstanding. Please take my POV into consideration. I also see it your way but am not yet convinced it needs to be the same button.
