### ISSUE TITLE
my github desktop doesnot publish repository

### ISSUE THREAD

**Issue by ashish9977** [desktop/desktop#5985]
## Version

* GitHub Desktop:

* Operating system:

**Comment by billygriffin** [comment]
Thanks for reaching out @ashish9977!

We require the template to be filled out when submitting all issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway 😀
