### ISSUE TITLE
FR : set git diff parameters

### ISSUE THREAD

**Issue by ggrrll** [desktop/desktop#5987]
Hi, 

it would be nice to have configurable `git diff` , such has for instance for 

- [ ] `diff-pdf --view`  for .pdf 
- [ ] `--word-diff` for .tex 

etc...

Thanks

**Comment by ggrrll** [comment]
@billygriffin  you are welcome :)

I cannot come up now with many examples ...but for those two cases:

- pdf is simply missing the viz -- I notice that you added the very cool comparison for png, with the different technique: onion skin, etc... (would be nice to have something similar for pdf too, especially for us that work with stats, ml, etc...)

- latex:  the default `git diff` on latex gives often a whole paragraph as 'chaneged' when you actually changed only a letter in a word -- this could be improved for instance with the `--word-diff` flag -- see for instance [this SO post](https://stackoverflow.com/questions/36368060/how-to-automatically-use-git-diff-word-diff-option-for-tex-files-but-not-oth)

hope this clarifies a bit

**Comment by billygriffin** [comment]
Thanks @ggrrll, that's helpful, appreciate it. We have an open issue for PDF support https://github.com/desktop/desktop/issues/5009 with `help wanted` there if someone from the community finds it useful and wants to explore it. We haven't seen a significant number of requests for this, so I'm not positive how common it is to have PDFs in repos, especially where an image-type diff would be helpful. That said, we're absolutely open to supporting it so we'll likely keep that issue open if someone wants to investigate. Notably, the current image diff was a community contribution, and we love to see those.

Regarding latex, similar to the above, if we see something as a more common use case I think we're open to it, but GitHub Desktop is not intended to be a replacement for everything you get with Git. So it's unlikely we would support the --word-diff flag unless it becomes much more common. Hope that makes sense, and I'm going to close this since we're tracking PDF support in #5009. Thanks again! 😄

**Comment by ggrrll** [comment]
sure no problem 
 At the same time – just to understand the 'philosophy' behind –  the comparison you introduced for png is much more than one would get from a simple git diff :) ... how does that fit with 

>  is not intended to be a replacement for everything you get with Git. 
? :)

Thanks

**Comment by billygriffin** [comment]
Great question, sorry for the lack of clarity. 😄 What I mean is that Git offers a whole bunch of config flags that offer basically endless configuration preferences. We generally think that the goal of trying to replicate all of Git's configuration is in opposition to making things obvious and intuitive. So for very common workflows we try to support the patterns that give folks the greatest ability to accomplish their goals, but we don't want to replace Git's functionality and config on a one-for-one basis. There's a bit more about how we think about those and other tradeoffs here: https://github.com/desktop/desktop/blob/master/docs/process/what-is-desktop.md

**Comment by ggrrll** [comment]
yes, this is great ;) ! ...and this is indeed basically why I started to use git for all my projects, thanks to simplicity of GUIs like GH-D ... and that's also the rationale that moved me to propose those features, pretty much in line with that you already did for the png (even if I have no idea of how that is implemented 😅 ) ...
