### ISSUE TITLE
Creating branch can fail silently

### ISSUE THREAD

**Issue by CoderCoco** [desktop/desktop#5997]
## Description
If I have a branch `enhancement/1` and I try to create `enhancement/1/test` in the desktop GUI, it doesn't create the branch as expected.

## Version
* GitHub Desktop: 1.4.3
* Operating system: Microsoft Windows [Version 6.1.7601]

## Steps to Reproduce
1. Create any branch with this format: `some/branch/name`
2. Attempt to create a branch using the name from step 1 like this: `some/branch/name/any/number/of/slashes`

### Expected Behavior
I would have expected that the branch would be created or that I would be notified that it couldn't be created.

### Actual Behavior
The create branch box closes with no error indication and no branch created.

## Additional Information
I did attempt to create a similar structure branch in git and received this error:

```
git branch "enhancement/1/test"
fatal: cannot lock ref 'refs/heads/enhancement/1/test': 'refs/heads/enhancement/1' exists; cannot create 'refs/heads/enhancement/1/test'
```

### Logs
[2018-10-25.desktop.production.log](https://github.com/desktop/desktop/files/2516218/2018-10-25.desktop.production.log)

**Comment by billygriffin** [comment]
I was able to reproduce, thanks for the detailed steps @CoderCoco! I don't *think* this is something we've seen before so I suspect it's a relatively uncommon branching pattern, but we should absolutely let folks know. I'm going to label this as a bug and help wanted to see if someone wants to dig into it.

**Comment by shiftkey** [comment]
Here's the underlying Git error from a recent test run:

<img width="1073" src="https://user-images.githubusercontent.com/359239/47569414-f6011800-d909-11e8-94a1-6b07f3e67232.png">

> Based on some research you cannot have both a file, and a directory with the same name.

This is precisely the issue, because I previously created `first/branch` Git adds a file named `branch` here:

```
$ tree .git/refs
.git/refs
├── heads
│   ├── first
│   │   └── branch 
│   └── master
└── tags
```

It then tries to create a directory named `branch` to then create a file within it named `whatever` to represent the `first/branch/whatever` ref. I suspect this is one of those filesystem limitations about on-disk Git repositories that very few stumble upon. 

I think we need to change up the error handling to show a more meaningful message within the component (currently it flows through our default error handling, which doesn't display anything because you're in the middle of a modal at the time).

**Comment by tierninho** [comment]
Suggested error message: 
"[warning-helper-text .octicon] A file and a directory cannot have the same name."

In line with our current messaging, it should be placed here:
<img width="392" alt="screen shot 2018-10-26 at 8 35 35 am" src="https://user-images.githubusercontent.com/14828183/47576951-951e1380-d8fa-11e8-975e-0a667933f450.png">

Good place to start:
https://github.com/desktop/desktop/blob/master/app/src/ui/lib/branch-name-warnings.tsx

**Comment by Daniel-McCarthy** [comment]
@tierninho Perhaps this may be a good candidate for catching this error when the user tries to create the branch and throwing a new error that is friendlier at the top of the UI.

I suggest this because if I understand correctly, these branch names can have any number of slashes.
Branch one might be: `1/2/3/4/5/6/7/8/9/0/1/2/../x`
Branch two might be: `1/2/3/4/5/6/7/8/9/0/1/2/../x/../c/b/a`

And the conflict would be the x in the middle. However, if we're trying to put a warning before the user creates a branch we may have to check each folder for a potential conflict and have to do this each time the user types a letter in the name of the branch.

Though perhaps I may be confused on how to properly detect this issue.

**Comment by NickCraver** [comment]
We had this on a project as well, we had `/channels` (a demo/proof-of-concept branch) which turned into a massive project and we wanted `/channels/question-list`, `/channels/auth-relay`, etc. I'm not sure it's uncommon...I think the transform of something minor into something that grows might hit this case fairly often.

I'd suggest a more generic error message, telling the user:
> This branch path name conflicts with an existing path: `<conflict branch path>`. You can either change this branch or remove the previous branch to continue.

...or some such. Just saying: the fact that it's directories underneath need not be a concern of the user IMO, I agree with others here on that front.
