### ISSUE TITLE
I can not clone repository to a local space.

### ISSUE THREAD

**Issue by qushiwan** [desktop/desktop#6031]
Cloning into 'E:\Git\alljoyn\core-alljoyn'...
fatal: unable to access 'https://github.com/alljoyn/core-alljoyn.git/': Failed to connect to github.com port 443: Timed out

Please kindly help me to resolve this problem.

**Comment by q00317454** [comment]
I will try later, thanks.

**Comment by steveward** [comment]
@q00317454 I noticed that you are using a SSH URL, but it does not look like you have a valid SSH key associated with your GitHub account. That is likely what is causing this issue.

I would recommend trying to clone that repository using the HTTPS clone URL to see if that succeeds, since HTTPS authentication is what GitHub Desktop defaults to. The HTTPS URL would be `https://github.com/alljoyn/core-alljoyn.git`. 

Let me know if cloning that URL works for you.

**Comment by billygriffin** [comment]
I think what @steveward posted should resolve this, and we haven't heard back, so I'm going to close this. Hope things are working for you now @q00317454!
