### ISSUE TITLE
Git merge error after undoing recent merge conflict 

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#6075]
If you resolve a merge conflict, undo the commit, and then attempt to resolve the conflict again, a git merge error is surfaced as soon as you attempt to resolve the merge conflict. 

The error blocks access to the merge conflict tool.

Reproduce:
- open merge conflict in Desktop (do not resolve)
- open terminal and resolve by removing file
- Desktop merge conflict modal should close automatically
- Undo the commit
- Attempt to resolve the merge conflict again (in Desktop this time)

![nov-01-2018 09-41-13](https://user-images.githubusercontent.com/14828183/47865781-5684cf00-ddba-11e8-9052-ac4819af9237.gif)

Logs:
```
error: Your local changes to the following files would be overwritten by merge:
	README.md
	TestWebAppProject/TestWebAppProject.csproj
	TestWebAppProject/Views/Shared/Error.cshtml
	TestWebAppProject/appsettings.Development.json
	UnitTestProject3/UnitTestProject3/UnitTestProject3.csproj
Please commit your changes or stash them before you merge.
error: The following untracked working tree files would be overwritten by merge:
	UnitTestProject1/UnitTestProject1.sln
	UnitTestProject1/UnitTestProject1/Properties/AssemblyInfo.cs
	UnitTestProject1/UnitTestProject1/UnitTest1.cs
	UnitTestProject1/UnitTestProject1/UnitTestProject1.csproj
	UnitTestProject1/UnitTestProject1/packages.config
	UnitTestProject3/UnitTestProject3/UnitTest2.cs
	WindowsFormsApplication1/WindowsFormsApplication1.sln
	WindowsFormsApplication1/WindowsFormsApplication1/App.config
	WindowsFormsApplication1/WindowsFormsApplication1/Form1.Designer.cs
	WindowsFormsApplication1/WindowsFormsApplication1/Form1.cs
	WindowsFormsApplication1/WindowsFormsApplication1/Program.cs
	WindowsFormsApplication1/WindowsFormsApplication1/Properties/AssemblyInfo.cs
	WindowsFormsApplication1/WindowsFormsApplication1/Properties/Resources.Designer.cs
	WindowsFormsApplication1/WindowsFormsApplication1/Properties/Resources.resx
	WindowsFormsApplication1/WindowsFormsApplication1/Properties/Settings.Designer.cs
	WindowsFormsApplication1/WindowsFormsApplication1/Properties/Settings.settings
	WindowsFormsApplication1/WindowsFormsApplication1/WindowsFormsApplication1.csproj
	appveyor.yml
	msbuild.binlog
	output.binlog
	tools/MSBuildLogOctokitChecker.psd1
	tools/MSBuildLogOctokitChecker.psm1
Please move or remove them before you merge.
Aborting
```

tested w/: 1.5.0-beta2, mac

**Comment by shiftkey** [comment]
> - Undo the commit
> - Attempt to resolve the merge conflict again (in Desktop this time)

These two steps don't quite make sense to me, because Git is warning you that your untracked changes are going to be overwritten as part of the merge you're attempting at the last step. @tierninho can you confirm whether you discarded changes to start fresh, or whether you just left the working directory as-is? It looks like from the GIF that we're trying to merge into a branch with changes, which I've mentioned in #5691 as something we don't currently have opinions on.

What I think we should be doing here - when you undo a merge commit in the app - is to ask the user whether they want to keep the changes in the working directory or not. This workflow has never felt great for me, for a few reasons:

 - leaving the results of the merge in the working directory feels confusing to the end user - we should encourage the user to start the merge again
 - when we undo the commit we don't restore the state of the merge, so if the user tries to commit again they'll have a plain commit rather than the merge itself
  
For reference, #4596 also touches on this path (undoing merge commits).

**Comment by tierninho** [comment]
@shiftkey 

Tried reproducing this in a new branch of a new repo and nada. Looking at the gif again and yes, it looks like I was "trying to merge into a branch with changes". I think we can consider this resolved, however your comment below might warrant further discussion:

> What I think we should be doing here - when you undo a merge commit in the app - is to ask the user whether they want to keep the changes in the working directory. This workflow has never felt great for me, for a few reasons:
> - leaving the results of the merge in the working directory feels confusing to the end user - we should encourage the user to start the merge again
> - when we undo the commit we don't restore the state of the merge, so if the user tries to commit again they'll have a plain commit rather than the merge itself

**Comment by shiftkey** [comment]
@tierninho thanks for the extra info. I'll bump #5691 to cross-reference this discussion, rather than track this in two separate places.
