### ISSUE TITLE
everything i  commit on github desktop is not showing up on github.com

### ISSUE THREAD

**Issue by kennisburg** [desktop/desktop#6117]
## Version

* GitHub Desktop:

* Operating system:

**Comment by shiftkey** [comment]
@kennisburg thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by billygriffin** [comment]
Since we haven't heard back with more details, I'm going to close this out. One note is that the biggest reason this might occur is if you have committed in Desktop but haven't yet published your repository or pushed it to GitHub.com. Hope that's helpful, and thanks for the issue.
