### ISSUE TITLE
.reg (Windows Registry) files are detected as binary files

### ISSUE THREAD

**Issue by sharunkumar** [desktop/desktop#6175]
## Description
When a .reg file is added / modified in a repository, the file is considered to be a binary file.

## Version
* GitHub Desktop: 1.4.3
* Operating system: Microsoft Windows [Version 6.1.7601] (Windows 7)

## Steps to Reproduce
1. Add / Modify a .reg file to a repository (can be obtained by exporting from the registry editor - regedit.exe)
2. View the file in the list of files in GitHub desktop

### Expected Behaviour
The file diff should be shown as a text file

### Actual Behavior
"The binary file has changed" message is shown in the diff viewer

### Logs
[logs.zip](https://github.com/desktop/desktop/files/2571397/logs.zip)

**Comment by shiftkey** [comment]
@sharunkumar thanks for the report. This is actually a limitation of Git, because it's binary file detection involves scanning for a `NUL` character in the first 3000 characters.

```shellsession
$ git diff --no-index /dev/null typora.reg
diff --git a/typora.reg b/typora.reg
new file mode 100644
index 0000000..d41953f
Binary files /dev/null and b/typora.reg differ
```

The fix here is to use a `.gitattributes` file to make clear what the encoding of the file is, like this:

```
*.reg   text working-tree-encoding=UTF-16
```

This will address it for both Git and GitHub Desktop:

<img width="954" src="https://user-images.githubusercontent.com/359239/48427926-449f1680-e740-11e8-800c-d5dc2902000f.png">

**Comment by acuna-public** [comment]
It helps, thanks!
