### ISSUE TITLE
Github desktop repository cloning "hanged up unexpectedly"

### ISSUE THREAD

**Issue by FerencRozsa** [desktop/desktop#6193]
## Description
 
When using github dekstop, If I clone a repository, or publish a repository to github, made with unreal engine c++, It then throws out a "fatal: the remote host hang up unexpectedly" error. this doesnt happen with non unreal engine projects that I tried. 
My thinking is that the projects are too big for my github desktop to clone or publish from my pc, since It works fine in the college PCs I used.

## Version
 
* GitHub Desktop: Version 1.4.3

* Operating system: Windows 10

### Expected Behavior

for the repository to clone into my github desktop so i can work on projects, or for repositories using unreal engine 4 c++ to be published
### Actual Behavior

at a certain percentage depending on project size or computer, it throws out an error like so:
`https://pastebin.com/72S18rD5`
above the error log for cloning repository
`https://pastebin.com/Rzdfbrwp`
above the error when publishing repository in home pc

**Comment by billygriffin** [comment]
Hi @FerencRozsa, is this related to #6158? Just want to make sure we aren't duplicating issues so we can help solve your problem appropriately.

**Comment by billygriffin** [comment]
No problem @FerencRozsa, my ask wasn't very specific. 😄 I closed the other issue and it's referenced here. Is it a public repository? If so, I'd love to try to reproduce your issue to see if we can figure it out.

**Comment by billygriffin** [comment]
cc: @desktop/support on this one as I'm not sure.

**Comment by steveward** [comment]
@FerencRozsa there have been cases where users hit timeouts due to the size of Unreal Engine repositories. However this is the error I am seeing in the log file you uploaded:

`error: RPC failed; curl 56 Failure when receiving data from the peer`

One other user ran into this error in https://github.com/desktop/desktop/issues/4356 and it was related to a firewall issue. Are you just running the standard Windows Defender firewall on this machine? It may be worth trying to temporarily disable your firewall to see if that helps at all with this issue.

**Comment by illusive-git** [comment]
Hello! I solved it permanently by adding Github Desktop to the Firewall Exceptions on Windows 10:

Firewall -> Allow App Access through Firewall -> Change Settings -> Add other App
Then add the GitHubDesktop.exe file found in User/AppData/Local/GitHubDesktop

No need to disable the Firewall now on my machine.
