### ISSUE TITLE
[Metrics] Commits in Desktop not attributed to a GitHub user

### ISSUE THREAD

**Issue by billygriffin** [desktop/desktop#6194]
In exploring #610, we don't have any knowledge of how frequently people are committing via Desktop without attribution to their GitHub accounts.

To determine whether we should prioritize design work for how we can make it more obvious when your commits will not be attributed on GitHub, we want to understand how frequently this happens.

I think there are two metrics I'd like here:

1. Absolute number of commits in GitHub Desktop on GitHub repos that aren't attributed to a GitHub user.
2. Percentage of total commits in GitHub Desktop on GitHub repos that aren't attributed to a GitHub user.

Considerations:

- How do we deal with commits on repos connected to other remotes? Can we ignore those for this purpose?
- How do we deal with co-authored commits where one person is attributed and one is not? I imagine this would be considered an unattributed commit for the purpose of this.

**Comment by shiftkey** [comment]
Some initial thoughts:

> How do we deal with commits on repos connected to other remotes? 

We can differentiate between GitHub, GitHub Enterprise and non-GitHub remotes fairly easily using account details in the app.

> Can we ignore those for this purpose?

I would focus on GitHub repositories as a first step, but also point out #2829 which is a thorny issue specific to Github Enterprise that might be affected by this investigation.

> How do we deal with co-authored commits where one person is attributed and one is not?

I wouldn't focus on co-authored commits here, as co-authors are typically chosen via the autocomplete input which is sourced from the GitHub API and much more likely to be up-to-date (because it gets refreshed periodically).

Users can manually specify the co-authors if they know the `Co-authored-by: Name <email>` syntax but I suspect they're in the vast minority currently (see #4308 for a related issue).

**Comment by billygriffin** [comment]
Do we think this is reasonable for 1.5.1 or should we target 1.6? My only reasoning for slightly preferring 1.5.1 is that 1.6 will contain some onboarding work from @niik that may help lower the percentage of unattributed commits, so having a baseline in place before then would be better, but not absolutely necessary.

**Comment by shiftkey** [comment]
@billygriffin in terms of the details we already have the ability to fetch the user's emails:

https://github.com/desktop/desktop/blob/483d4ae3b7ea733b7bc0df5d791112473257dd25/app/src/lib/api.ts#L298-L308

And we check this when refreshing the current user, so if we need to store this somewhere that's the time to do it:

https://github.com/desktop/desktop/blob/483d4ae3b7ea733b7bc0df5d791112473257dd25/app/src/lib/api.ts#L717-L724

And then we could check it after we create the commit, like we do with some other things:

https://github.com/desktop/desktop/blob/483d4ae3b7ea733b7bc0df5d791112473257dd25/app/src/lib/stores/app-store.ts#L1794-L1814

The only bit we don't have is reading the details of the commit that was just created (to see what identity was set in the commit).

**Comment by billygriffin** [comment]
@niik @iAmWillShepherd @outofambit Thoughts about getting this into 1.5.1?
