### ISSUE TITLE
cannot publish unborn head

### ISSUE THREAD

**Issue by billyobuya** [desktop/desktop#6207]

**Comment by billyobuya** [comment]
how can I solve the problem of not publishing unborn head

**Comment by billyobuya** [comment]
i have  a problem in that after creating an account with git hub and
signing it to git hub using my own credentials in the git hub desktop
application and try to clon a reposiory i am told that unborn head cannot
be established

**Comment by billygriffin** [comment]
@billyobuya As presented above, in order to understand what's happening for you, we ask that you fill out the template (you can copy over from https://github.com/desktop/desktop/issues/new?template=bug_report.md if you'd like). This allows us to gather enough information about what's happening for you to actually help resolve the issue. Thanks for understanding and meeting us halfway! 😄

**Comment by tierninho** [comment]
@billyobuya usually the `UNBORN HEAD` error happens when you are attempting to publish a branch that has no commits. If that is the case, make an initial commit and then try publishing your branch again. If you have any further issues, please fill out the template so that we can better help you!

**Comment by shiftkey** [comment]
Closing this out because an unborn branch cannot be published (because there are no commits to push), and without more information the advice in @tierninho's last comment is the best workaround.
