### ISSUE TITLE
Resolve conflicts before merging - add explanation when there is no external editor to open files in.

### ISSUE THREAD

**Issue by MappingSteve** [desktop/desktop#6216]
STEPS TO REPRODUCE:
* Fresh installation of Github Desktop v1.5.0 on a new Windows 10 PC.
* Clone repository from Github to local.
* Make a change.
* Have someone else make a conflicting change and check that in to Github.
* Commit your change (locally).

* In GD, click "Pull origin":
Pull detects the conflict, and opens a dialog titled
  "Resolve conflicts before merging origin/master into master".

Then there is a list of files.  To right of each file is a button titled "Open in Editor".

PROBLEM:
**Because no external editor has been installed, that button is disabled.**

User may have no idea what to do next.

NOTE:
This "what do I do now" confusion is more serious than it used to be, because in earlier GD versions (not sure exactly which ones, or what settings might have been different), it was possible to get out of this dialog, in a way that showed user the list of changed files.  
This seems to no longer be possible. If "Changes" tab is visible, I can see that list of changed files *below* the "Resolve conflicts" dialog, but when that dialog is closed, the changed list goes away
(because the pull is aborted.)

SUGGESTED FIX:

When no editor is found, add to this dialog explanatory text below the list of files. Something like:

    "Open in Editor" buttons disabled because no external source editor found.  
     Click here to install "Atom", or click "Abort merge", and install a compatible text editor.  
     See [Configuring a default editor](https://help.github.com/desktop/guides/getting-started-with-github-desktop/configuring-a-default-editor/)
     for more information.

SEE ALSO:  
Menu "Repository" / "Open in external editor" has similar logic, including the button for installing Atom.

**Comment by tierninho** [comment]
@MappingSteve Thanks for filing this. Although we did address the missing editor in https://github.com/desktop/desktop/pull/6109 it could be improved on to communicate the resolution in a clearer manner. I will reach out to the team to revisit this issue. 

Perhaps we could alter the following text from:

`You can also open the command line to resolve` to
 `You can also open the command line to resolve or install an editor` 

with the word "install" linked to the Preferences?

**Comment by billygriffin** [comment]
@MappingSteve Thank you! This type of feedback is super valuable and really appreciated. For the "Open in editor" disabled button, did you notice the tooltip (that's what we shipped in #6109 that @tierninho referenced above)? It's seems that may not be quite obvious enough to provide a signal for what you're supposed to do next in those cases.

 > This "what do I do now" confusion is more serious than it used to be, because in earlier GD versions (not sure exactly which ones, or what settings might have been different), it was possible to get out of this dialog, in a way that showed user the list of changed files.
This seems to no longer be possible. If "Changes" tab is visible, I can see that list of changed files below the "Resolve conflicts" dialog, but when that dialog is closed, the changed list goes away
(because the pull is aborted.)

This seems like it may be a separate problem you're identifying. Attempting to restate, it sounds like you want to be able to exit the guided flow *without* aborting to be able to see the diff of the conflicted files. Is that accurate? If so, it it just driven by not being able to directly open it in an editor because you don't yet have one configured, or is it separate?

Thanks again for the detailed feedback - it's really helpful as we iterate on how this works for folks.

**Comment by killroy42** [comment]
I'm currently stuck with this. How can I see the conflict so I can resolve it as usual? I do not seem to be able to get out of this modal, and I have no idea why this modal exists? I initiated my merge in a console and just wanted to use github to see the conflict and find the lines more easily. Not I can only click abort, which seems to undo the merge I'm trying to do!

**Comment by billygriffin** [comment]
@killroy42 Thanks for the feedback and sorry you're having a tough time with it. Please follow along in #6213 as I think that's the issue you're running into and we're looking at a way to improve it.

**Comment by billygriffin** [comment]
Thanks for this @MappingSteve! Hopefully what we shipped in 1.5.1 was helpful in alleviating the pain, but we're still looking at this in #6386. It's definitely something we want to improve soon so thanks for putting it on our radar. I'm going to close this issue so we can track it in #6386.
