### ISSUE TITLE
Apparent loss of stashed work when upgrading to "new native" app

### ISSUE THREAD

**Issue by jimmyland** [desktop/desktop#6224]
The Classic app supported 'magic' stashing, and the new app does not.
I didn't see notices around this on the upgrade website or messages.

Users of the old app who add an old repo to the new app will expect stashed changes to be automatically restored when switching branches, because they are not informed about the feature change.  They will appear to have lost work that is 'hidden' in the stash.  They may not initially notice the loss, or they may not be able to figure out what happened (since the old app did not tell them about stashing).

To help users not lose work, there should at least be some messaging about this change on the website / upgrade notices.

**Comment by billygriffin** [comment]
Hi @jimmyland, thanks so much for leaving an issue. That's a reasonable suggestion. Unfortunately since it is a brand new app and since there was quite a bit of divergence from both the Windows and macOS app as they converged, there would be too many behavior changes to call out individually. Given that and the fact that we're starting to explore something related to stashing now in #6107, I'm going to close this, and it'd be great if you follow along there. 😄
