### ISSUE TITLE
commit from personal email address pushed to organization repository

### ISSUE THREAD

**Issue by pramitsawant** [desktop/desktop#6235]
Security related issue was faced by me when committing code using GitHub Desktop.

I was working on a project repo which is **private** and only 3 collaborators( work related ).
the email which i was using here is my company email 
no other person have access to this repos other then my team members.

On same system i was also working on my personal project. and my personal email does not have access to my other work related projects.

When i committed code in my work project. somehow it got committed using my personal email.
my personal email does not have access to my work related repos.

my personal email id was added to the contributors of the private repo

**Comment by pramitsawant** [comment]
@

**Comment by iAmWillShepherd** [comment]
@pramitsawant 

> my personal email id was added to the contributors of the private repo

This is controlled by the `user.email` key in Git's global configuration.

Run `git config user.email` in your repository. What email address shows up? If it's your personal address, then that is the reason it shows up as the committer on GitHub.

One thing you could try is adding your a local Git configuration to the repos you work in. To do this, just run `git config --local user.emal <your_email>`.

I hope this helps 👍

**Comment by pramitsawant** [comment]
yes, that is correct But how was I able to commit from my personal email to a private repo where i don't have access to.??
that should not happen right?

**Comment by shiftkey** [comment]
> But how was I able to commit from my personal email to a private repo where i don't have access to.??

Git handles commit identity (the name and email address uses in a commit) and authentication (the credentials required to push commits to a remote) very differently, because of how it is designed.

When you are challenged to authenticate by GitHub part of doing a `git push`, this is using your GitHub credentials - the commit identity stored in the commits being pushed is irrelevant here.

The `user.name` and `user.email` config values for commit identity that @iAmWillShepherd referred to are free-form text.  The only restrictions that GitHub enforces on pushes around commit identity is a privacy measure to prevent you from pushing a [commit with a private email address](https://help.github.com/articles/blocking-command-line-pushes-that-expose-your-personal-email-address/). 

It sounds to me like what you're looking for is the ability for organizations to control what commits can be pushed to their repositories, so they can whitelist and ensure commits only come from specific domains. Am I understanding that right @pramitsawant?

**Comment by tierninho** [comment]
@pramitsawant As we have not heard anything back from you, we are closing this issue for now. Please reach out if you need further help and we'd be happy to reopen the issue. Thanks!
