### ISSUE TITLE
'Last fetched' notification unwanted and annoying when reviewing code

### ISSUE THREAD

**Issue by mikew1** [desktop/desktop#6247]
I use this program to do code reviews.

When reading code, I am interrupted by the auto fetch "notification", which causes a loss of concentration. At the very least there should be an option to switch this off / eliminate the visual disturbance.

It's infuriating and I may have to stop using this program for code reviews as a result.

Also, maybe it's just me, but I also accidentally pushed to a repo once, the big button invites you to push it.  git push is a significant command, not quite at the level of rm- rf, but i'm not sure i agree it should be made so obvious and inviting as has been in this ui.

I'm considering going back to use the old version.

**Comment by billygriffin** [comment]
Hi @mikew1, thanks for the feedback. To be honest, we generally hear the opposite of what you said. Most folks have said they want the "push" button to be *more* obvious, not less. We don't want people to get into situations where they've committed and they just assume their code is up on GitHub, but since they forgot to push, it's actually only still local.

Regarding the feedback on fetching, similarly we're looking at ways to make feedback after interactions more obvious about what just occurred. There's likely a distinction between background operations and ones initiated by a positive action from the user, but we still want people to understand what the app is doing and when, and we've heard that desire countless times from users. We're considering the frequency of background operations elsewhere, so that might be helpful for you when we're able to tackle that. 

Thanks again for your thoughts. I'm going to close this to indicate we don't intend to do either of these things, but it's helpful to have it available and we're always open to reconsidering if our assumptions are off base.
