### ISSUE TITLE
Push repository with large files

### ISSUE THREAD

**Issue by sagnikbanerjee15** [desktop/desktop#6261]
I tried to push a repository which had a file over 100MB. I split up the file into 3 parts. Each of those parts is less than 100 MB. But the attempts to push the repository still keeps on failing. I am using GitHub desktop.

Thank you.

**Comment by billygriffin** [comment]
Hi @sagnikbanerjee15, thanks for the report and sorry about that. I’m not positive, but likely that you already committed the file at some point, so it’s in your commit history, even if it’s been split up since then. We have an upcoming pull request to fix this from @Daniel-McCarthy (https://github.com/desktop/desktop/pull/6013) that will warm you prior to initially trying to commit large files. And a few possible workarounds in the mean time are here https://github.com/desktop/desktop/issues/997

**Comment by billygriffin** [comment]
I’m going to close this since we’re tracking it in #997

**Comment by Daniel-McCarthy** [comment]
Hi @sagnikbanerjee15,
Part of the issue here is that in order to push a file larger than 100 MB to GitHub one must set up Git LFS to track the files you're trying to push.

Assuming you have already created a commit that contains the >100 MB file, you can either undo the commit, or set up Git LFS so that you can push the commit to your remote repository.

If you would like to set up Git LFS so that the file can be pushed, there is [information on this page](https://help.github.com/articles/versioning-large-files/) that can help you with that.
___
I hope this helps you with your current situation.

**Comment by sagnikbanerjee15** [comment]
Thank you very much for your help. I will try out the options.

Thanks
