### ISSUE TITLE
Home/End keys do not work in diff view

### ISSUE THREAD

**Issue by jessetan** [desktop/desktop#6295]
## Description
It can be convenient to jump to the end of a long list of changed files using the End key. It can also be convenient to jump to the end of a long diff by pressing the End key.

The first one works, the second doesn't 😢 

## Version

* GitHub Desktop: 1.5.0
* Operating system: macOS 10.13.6

## Steps to Reproduce

1. Open a repo and make changes to multiple files, so that the list does not fit in the window height
2. Click a file name
3. Press End and Home to jump to the bottom and top of the list
4. Click on a file that has a large diff that does not fit in the window height
5. Click on the diff to focus it
6. Press End and Home to attempt to jump to the button and top of the diff
7. Be slightly disappointed when nothing happens in 6.

### Expected Behavior
The diff can be navigated using Home and End keys.

### Actual Behavior
Diff window does not respond to Home and End keys (it does respond to PgUp and PgDn).
Changed files list only responds when the focused file is on screen. If it scrolls outside the visible area, keys no longer function.

**Comment by iAmWillShepherd** [comment]
Thanks for creating this issue, @jessetan 

This is likely because all the engineers (4 of us) use MacBook Pros for development. As far as I know, there is no <kbd>Home</kbd> or <kbd>End</kbd> keys on our keyboards. This could be 100% false, two of our engineers are not based in America, so maybe their keyboards have it 🤔 .

In any case, I'm going to add the `help wanted` label to this for anyone in the community who is interested in tackling this.

**Comment by msftrncs** [comment]
@jessetan, CTRL-HOME and CTRL-END seem to work for me in the DIFF view.  Both seem to work in the changed files list of a commit view.  They only seem to work once while in the commit history list; in this case, the selection is removed from the item, the display moves accordingly and then nothing happens if you try HOME or END or CTRL-HOME or CTRL-END until another item is selected.

**Comment by jessetan** [comment]
<kbd>Cmd</kbd>+<kbd>Up</kbd> and <kbd>Cmd</kbd>+<kbd>Down</kbd> also work for me in diff view, but the native <kbd>Home</kbd> and <kbd>End</kbd> keys don't.

I also see what @msftrncs is reporting in the Changes file list: only if the focused item is visible on the screen the <kbd>Home</kbd> and <kbd>End</kbd> keys work, otherwise they do nothing

**Comment by tierninho** [comment]
Looks like three parts of the History feature would benefit from this, as outlined in the pic.

<img width="1311" alt="screen shot 2018-11-28 at 11 06 27 am" src="https://user-images.githubusercontent.com/14828183/49175851-58c94300-f2fe-11e8-9a0c-7c43f4ca2116.png">

Currently, Fn+Left/Right arrows kind of work on a Mac for Home & End, but it is far from perfect and functionality is inconsistent. 

Ideally, cmd+up/down arrows seems like a better fit to be implement.

**Comment by AndreiMaga** [comment]
I wanna take a swing at this one. 
So the expected behavior is :

- Press ```Home``` => Jump to start of the diff
- Press ```End``` => Jump to end of diff

Without messing with the current shortcuts.
Is there anything else on top of this ?
