### ISSUE TITLE
Hitbox for RMB clicks is smaller than hitbox for LMB clicks in "Changes" panel

### ISSUE THREAD

**Issue by jessetan** [desktop/desktop#6296]
## Description
In the "Changes" panel, the area that is clickable with the right mouse button to open the context menu, is smaller than the area that is clickable with the left mouse button to select the file.

## Version
* GitHub Desktop: 1.5.0
* Operating system: macOS 10.13.6

## Steps to Reproduce
1.  Open a repo with multiple changed files
2. Click on a file name in "Changes" to select it
3. Click on a different filename, veeeery close to the dividing gray line, to select the other file
4. Right-click on the middle of a file name to open the context menu
5. Close the context menu
6. Right-click a filename, veeery close to the dividing gray line, which should open the context menu
7. Observe that the context menu does not open, but the file is selected instead

### Expected Behavior
7. The context menu opens for the correct file

### Actual Behavior
7. The context menu does not open, but the file is only selected.

## Additional Information
- This behaviour is not present in the "History" panel where the rows are higher
- This behavior is also present in the list of repositories, although there is no dividing line between the rows

Approximate area that is clickable:
![github-rmb](https://user-images.githubusercontent.com/3284111/49084655-62946d00-f250-11e8-9872-34a7e4048901.png)

**Comment by iAmWillShepherd** [comment]
Thanks for opening this issue, @jessetan 👍 

The difference in click target between primary and secondary clicks is caused by attaching the secondary click event handler to a separate component.

Here is the component that the context menu is attached to:
https://github.com/desktop/desktop/blob/de96ea63e8c4410ef6e2dca82e9163e3bbec2321/app/src/ui/changes/changes-list.tsx#L169-L181

Here is the component responsible for keeping track of selected row items:
https://github.com/desktop/desktop/blob/de96ea63e8c4410ef6e2dca82e9163e3bbec2321/app/src/ui/changes/changes-list.tsx#L425-L435
As you can see, this component is responsible for rendering the content of each row. Since each row is larger than the actual content, the row is clickable everywhere while the content is only clickable on the area it takes up.

<img width="1915" alt="screen shot 2018-11-27 at 10 07 20 am" src="https://user-images.githubusercontent.com/1715082/49094640-51396980-f22c-11e8-976f-c731f42b774f.png">
<img width="1915" alt="screen shot 2018-11-27 at 10 07 28 am" src="https://user-images.githubusercontent.com/1715082/49094641-51396980-f22c-11e8-8407-663ad54db87f.png">

A potential fix is to increase the touch target for secondary clicking is to add a bit of CSS that targets the `ChangedFile` component and gives it a bit of extra width and height (I have verified this works on my system).

**Comment by JQuinnie** [comment]
Hi All,

I would like to work on this issue if there are no time constraints... will likely be able to look into it closer to the end of the week but wanted to comment here first.

**Comment by JQuinnie** [comment]
@iAmWillShepherd per your description above, I did first trial by adding a height property to the `.file` class and made it take up all the space, see height property below;

```  
.file {
    display: flex;
    align-items: center;
    flex-grow: 1;

    // See https://css-tricks.com/flexbox-truncated-text/
    min-width: 0;
    height: 100%;
```

<img width="1328" alt="screen shot 2018-12-09 at 4 11 20 pm" src="https://user-images.githubusercontent.com/29465981/49704203-450ac000-fbcd-11e8-83fd-6cdbe1c65170.png">

Would this be acceptable or are there style variables I should be introducting/removing?

Thanks!

**Comment by shiftkey** [comment]
@desktop/design I'd love your thoughts on what @JQuinnie asked in https://github.com/desktop/desktop/issues/6296#issuecomment-445581601 about whether that's a suitable solution to this issue.

**Comment by ampinsk** [comment]
That solution makes sense to me, but @niik might know better!

**Comment by niik** [comment]
I think @JQuinnie's suggestion of making the file component's `height` to 100% is a great start though I suspect it only addresses part of the problem

Looking at the current state of the container for which the context menu handler is attached we can see that it indeed doesn't extend to cover the available space within the parent list item container.

![image](https://user-images.githubusercontent.com/634063/52277849-f58b0b00-2955-11e9-8940-7f401df73d49.png)

Adding a height 100% solves the problem in the vertical dimension (think of the blueish highlighted area as the hitbox for the context menu) but not in the horizontal dimension as the padding from the parent component is claiming that space.

![image](https://user-images.githubusercontent.com/634063/52277872-020f6380-2956-11e9-80bd-b60a58f9cc5f.png)

Seen again from the parent container's perspective

![image](https://user-images.githubusercontent.com/634063/52277885-076cae00-2956-11e9-8293-ba459f3257ad.png)


In order to solve it for both we need to also remove the padding from the list row wrapper (the crossed over section)

![image](https://user-images.githubusercontent.com/634063/52277934-223f2280-2956-11e9-8ab8-466cb1bb5141.png)

And add it to the `.file` wrapper

![image](https://user-images.githubusercontent.com/634063/52277948-2bc88a80-2956-11e9-9090-99255ee0d977.png)

The combination of your suggestion @JQuinnie and moving the padding would make an excellent addition and we'd be delighted to review such a PR.

For the future and in order to solve this more holistically I think we should also consider not applying our context menu handlers to individual components like this but rather move it to being the `List` component's responsibility in the same way that selection is.

**Comment by JQuinnie** [comment]
@shiftkey @ampinsk @niik Thank you all for the feedback! I will go ahead and get a PR up this week. Always appreciate the help 😃
