### ISSUE TITLE
Error in git desktop while pulling origin 

### ISSUE THREAD

**Issue by triptiverma31** [desktop/desktop#6302]
fatal: unable to access 'https://github.com/crisetime/smart-leave.git/': schannel: next InitializeSecurityContext failed: Unknown error (0x80092013) - The revocation function was unable to check revocation because the revocation server was offline.

Please help me out to resolve this error.

**Comment by billygriffin** [comment]
@triptiverma31 Thanks for the report and sorry it was failing for you. This error is usually caused by your network blocking the attempt by Windows to check the revocation status of a certificate, which then causes the whole operation to error. You can find a workaround for this issue here:

https://github.com/desktop/desktop/blob/master/docs/known-issues.md#certificate-revocation-check-fails---3326

We have also seen this error occurring for users running certain antivirus software like Kaspersky due to the filtering it performs. If you are running Kaspersky try temporarily disabling it to see if that fixes this issue, and let us know if you run into any further issues. I'm going to close this because the workaround almost always resolves it, but please let us know if not. 😄
