### ISSUE TITLE
Pulling repo only pulls current branch

### ISSUE THREAD

**Issue by ezracelli** [desktop/desktop#6304]
## Version

* GitHub Desktop: **1.5.0**

* Operating system: **MacOS Mojove 10.14.1**

## Steps to Reproduce

1. Check out a different branch, e.g. switch from `repo/branch-1` to `repo/branch-2`
2. Make changes to the previously checked out branch, e.g. `repo/master`, from a different source (like adding commits or deleting the branch)
3. Pull repo in Desktop via `Repository > Pull` or `Shift + Command + P`

### Expected Behavior

All branches should be pulled.

### Actual Behavior

Only the current branch is pulled.

## Additional Information

I believe this issue was not present in a present in previous versions of Desktop.

-----

Commits added to the branch not checked out, e.g. `branch-1`, are not reflected in Desktop after pulling the repository via above steps, so for example attempting to merge from that branch into, say, `branch-2` may yield *"`branch-2` is up-to-date"* when in fact it is not. The workaround in this case is to stash any staged/unstaged changes, check out `branch-1`, pull, return to `branch-2`, and merge.

Checked out branch `staging` has additional commits on remote
![image](https://user-images.githubusercontent.com/6758913/49168408-69c98280-f305-11e8-9202-79c63b850704.png)

Check out branch `conflicts-expansion` and pull from remote
![image](https://user-images.githubusercontent.com/6758913/49168377-59190c80-f305-11e8-8e6f-fa5bdfcba50d.png)

Attempt to merge from `staging` into `conflicts-expansion`
![image](https://user-images.githubusercontent.com/6758913/49168521-a8f7d380-f305-11e8-88b2-68e680c28e5d.png)

After switching to `staging`, pulling, then switching back to `conflicts-expansion`
![image](https://user-images.githubusercontent.com/6758913/49168647-f6744080-f305-11e8-8688-907f8f8ff36e.png)

-----

If, say, `branch-2` is deleted, it is still in Desktop (on the local machine) and commits can be added. When attempting to pull while this branch is checked out, a modal says, *"Your configuration specifies to merge with the ref 'refs/heads/branch-2' from the remote, but no such ref was fetched."* Desktop does recognize the branch was deleted as it does give the option to publish`branch-2`.

A deleted branch is checked out
![image](https://user-images.githubusercontent.com/6758913/49168066-bfe9f600-f304-11e8-8d17-13cceee099a3.png)

Attempting to pull from a deleted branch
![image](https://user-images.githubusercontent.com/6758913/49168174-f6277580-f304-11e8-8dd0-fb37f4221352.png)

**Comment by outofambit** [comment]
Hi @ezracelli thanks so much for this detailed write up. we'll need to reproduce it locally, but i'm sure this is a bug. for our added context, could you share how disruptive this is to your workflow with desktop? sorry you're hitting this. thank you!!

**Comment by ezracelli** [comment]
I wouldn't call it disruptive, as there is a workaround (stash, switching, pulling, switching, stash pop), but it can be troublesome if you think you're up to date and you're not. It's really more of an annoyance than anything else.

Take the example I used above.

```
X-X-X-X-Y            staging
       \-X-X-X-X     conflicts-expansion
```

Say someone working on `staging` mentioned to me that they fixed a bug, adding the commit `Y`. I (still in `conflicts-expansion`) pull and merge from `staging` into `conflicts-expansion` and see the bug is still there &mdash; because commit `Y` was never actually pulled, but there is no indication in Desktop. They try to reproduce the issue and can't. Finally I check out `staging` and see that there is an unpulled commit.

**Comment by shiftkey** [comment]
@ezracelli apologies for the delay in replying. I'd like to understand a bit more about this situation:

> All branches should be pulled.

Desktop has functionality to fast-forward branches that runs during fetch/push/pull:

https://github.com/desktop/desktop/blob/8b48476bd9338bf39a677165e3fe6b1ba3f5e4cd/app/src/lib/stores/app-store.ts#L3560

This looks for branches that track an upstream branch, and that upstream branch is "ahead" of the local branch, and there are no commits on the local branch. If all of those conditions are satisfied, the app will update the local ref to point to the remote ref (much faster than a `pull`):

https://github.com/desktop/desktop/blob/8b48476bd9338bf39a677165e3fe6b1ba3f5e4cd/app/src/lib/stores/app-store.ts#L3600-L3608

I appreciate that it's been a while since you looked at this issue, but if you're still noticing something strange about this behaviour I'd love to see some detailed instructions about your setup and the steps to reproduce it so that we can unpack that further.

There is some other feedback in here that about workflows that I'll address in a follow-up comment.

**Comment by shiftkey** [comment]
> Commits added to the branch not checked out, e.g. `branch-1`, are not reflected in Desktop after pulling the repository via above steps, so for example attempting to merge from that branch into, say, `branch-2` may yield _"`branch-2` is up-to-date"_ when in fact it is not. The workaround in this case is to stash any staged/unstaged changes, check out `branch-1`, pull, return to `branch-2`, and merge.

This is related to how we de-duplicate upstream branches which track a local branch in the list, and I had a discussion with someone about this a while ago in the context of rebasing, but I'm not sure if that got written up at all.

> If, say, `branch-2` is deleted, it is still in Desktop (on the local machine) and commits can be added. When attempting to pull while this branch is checked out, a modal says, _"Your configuration specifies to merge with the ref 'refs/heads/branch-2' from the remote, but no such ref was fetched."_ Desktop does recognize the branch was deleted as it does give the option to publish`branch-2`.

I gather this is the difference between using the `Pull` shortcut and clicking the `Publish` button. We're discussing in #1325, please follow along with that.

**Comment by steveward** [comment]
@ezracelli I'm going to close this out due to inactivity. It looks like [this specific case](https://github.com/desktop/desktop/issues/7805#issuecomment-690349188)  is the same as your request (fetching changes to ensure branches are up-to-date when performing a merge). You can follow https://github.com/desktop/desktop/issues/10687 for updates about that.
