### ISSUE TITLE
Branch icon flashes after branch is renamed

### ISSUE THREAD

**Issue by iAmWillShepherd** [desktop/desktop#6320]
## Description
Spotted this visual issue while reviewing #6305 

Notice the icon next to the renamed branch changes from the _selected_ icon to the _branch_ icon and finally back to the _selected_ icon.
![issue](https://user-images.githubusercontent.com/5228723/49190342-d37b7800-f369-11e8-99d4-cc367a3703cb.gif)

## Steps to Reproduce
1. Select a branch to rename
1. Rename it

### Expected Behavior
I expected the branch to be renamed without the state of the icon changing

### Actual Behavior
What happens is the icons flashes states

**Comment by iAmWillShepherd** [comment]
@gnehcc has taken this issue.

**Comment by niik** [comment]
@billygriffin I'm proposing we downgrade this from a priority-2 to a priority-3.

Priority-2
> Bug that affects more than a few users in a meaningful way but doesn't prevent core functions

Priority-3
> Bugs that affect small number of users and/or relatively cosmetic in nature

I think this fits pretty squarely in prio-3.

@gnehcc Was kind enough to take a stab at solving this in #6340 which illustrates the complexity of problem. Given the complexity and the (in my opinion) minor issue I have a hard time justifying we invest in solving this unless a straightforward approach is found but I'm curious to hear your opinion @billygriffin.

**Comment by billygriffin** [comment]
I agree with you @niik, and thanks for the detailed explanation. The most important part of the original issue to the user is that the renamed branch is treated in the same manner as the original branch (and continues to be in recent branches if the original one was). The flash as the icon changes is suboptimal but in no way prevents any meaningful user interaction. If there's a way to fix this that's more straightforward, I'm 👍 but otherwise I agree. Also changed it to a priority-3 as I agree that's a better categorization for this (specifically, the difference between "affects users in a meaningful way" and "relatively cosmetic in nature").

And thanks @gnehcc for the PR and trying to find a way to make it work! I'm interested to hear your thoughts as well.

**Comment by gnehcc** [comment]
@billygriffin while I was working on #6340, I noticed that the repository state has been updated quite a few times when doing an operation like branch-renaming, and "a dirt state" will happen during the process (old current branch with latest branches data or new current branch with old branches). which causes the icon flash issue. (might also be not so performance friendly as well I guess)
like @niik commented under the #6430, kind of need a better and consistent way to update the repository state.
I will try to continue working on the pr seeing if there is anything new I can get.
cheers.

**Comment by billygriffin** [comment]
Given the difficult in implementation here, I think the costs are larger than the benefits, and this is a minor visual inconvenience that doesn't actually block anything. While it would be nice to fix it, I'm going to make the call that it's not worth further consideration at this point. Thanks so much for your efforts @gnehcwu and sorry it became more difficult than we anticipated!
