### ISSUE TITLE
Editor integration can cache incorrect path if update occurs while enumerating

### ISSUE THREAD

**Issue by adamreisnz** [desktop/desktop#6324]
## Description
It appears Github Desktop doesn't like Atom Nightly much.
After I updated Atom to the latest version, Github Desktop complains it can't open the external editor:

I don't know why it's looking in my Caches for the app:

![image](https://user-images.githubusercontent.com/490562/49324921-559fb280-f59d-11e8-946f-592f5f7f2350.png)

When I open preferences it's marked correctly:

![image](https://user-images.githubusercontent.com/490562/49324926-5df7ed80-f59d-11e8-8971-d5bdd73fdeaf.png)

Any tips on how to fix this issue or prevent it from happening again after an updated?

## Version
* GitHub Desktop: 1.5.0
* Operating system: OS X

### Logs
Logs didn't contain any related errors or info.

**Comment by adamreisnz** [comment]
In the end I had to re-install the shell commands for Atom and restart Github Desktop a few times to get this to work again.

**Comment by billygriffin** [comment]
Huh, that is strange @adamreisnz. @desktop/engineering or @desktop/support any ideas why this would happen? 

@adamreisnz Would you mind letting us know if the next time you update Atom you experience the same issue?

**Comment by adamreisnz** [comment]
Yes will do, anything else you'd like me to check?

**Comment by billygriffin** [comment]
Not at the moment, just that would be helpful for now. Thank you!

**Comment by say25** [comment]
I wonder if we need to support Atom Nightly like we do VS Code Insiders?

https://github.com/desktop/desktop/blob/master/app/src/lib/editors/linux.ts#L7. I can take a look tonight and see if that might resolve it.

**Comment by billygriffin** [comment]
That'd be great if you wouldn't mind looking into it @say25. Thanks!

**Comment by say25** [comment]
It would appear to me that our current integration can not distinguish between Atom, Atom Beta and Atom Nightly particularly on macOS where they all have a bundle identifier of `com.github.atom`.

**Comment by adamreisnz** [comment]
@billygriffin It's happened again, on my laptop this time.

**Comment by shiftkey** [comment]
The best theory I have about this is that our detection of Atom doesn't work well _when we query for it while it's being updated_.  The error message there contains the path `com.github.atom.ShipIt` which suggests when the app queried for the install location the files were in a temporary location, so perhaps we should ignore this path and not cache it.

I think there's some other potential headaches here because once we do this initial check we cache the values, so we'd consider Atom "missing" rather than try and look for it again. #6114 has some extra context about how to handle changes to editors without restarting Desktop.

**Comment by adamreisnz** [comment]
I think that theory makes sense. Sometimes what happens as well, is that Github desktop opens a "different" version of Atom than what I already have open and running. Presumably this also happens after an update. So that leaves me with two distinct instances of Atom running.

**Comment by shiftkey** [comment]
> It would appear to me that our current integration can not distinguish between Atom, Atom Beta and Atom Nightly particularly on macOS where they all have a bundle identifier of `com.github.atom`.

There's been some packaging changes to the Atom beta and nightly channels  recently, and I was hoping this was no longer the case, but it still appears they are the same bundle id:

```
$ mdfind kMDItemCFBundleIdentifier = "com.github.atom"
/Applications/Atom Beta.app
/Applications/Atom Nightly.app
/Applications/Atom.app
```

This is also an additional pain, because the current app behaviour is probably not what you expect when you have all three installed:

<img width="375" src="https://user-images.githubusercontent.com/359239/62146066-fc725500-b2ca-11e9-8734-a1346280528f.png">

Ideally I'd love for each channel to be an option here that we can detect, but that requires asking the Atom team to break their beta and nightly channels to change the bundle identifiers.

Putting that aside, I think there's two potential solutions here:

 - address the caching of editors - #6114 - this means we'd be able to detect the paths changing as part of an update
 -  don't cache paths that we know don't make sense, for that situation where an update is happening. This feels a bit editor specific, but maybe there are other situations where we'd also need to do this

I'm going to update the issue to indicate this is related to updates and caching paths, rather than the specific editor channel.

**Comment by dboyce-gh** [comment]
It may help to add another data point to this issue.  I have experienced the equivalent error for the VS Code editor, because I moved Visual Studio Code.app from Downloads (where GitHub Desktop is looking for it) to Applications (where launcher finds it, but not GHD).

**Comment by sarankani** [comment]
I got this error
![image](https://user-images.githubusercontent.com/113065/139385908-dbf10ecb-1fd6-48fe-b952-a5cabc592d68.png)
