### ISSUE TITLE
Cannot clone a repository

### ISSUE THREAD

**Issue by gavinayling** [desktop/desktop#6325]
## Description

I do the following:
File, Clone Repository..., URL, paste this "https://github.com/smndtrl/Signal-UWP.git'
I get a fatal error telling me that the folder I chose does not exist. It does not exist, but if I create a Local Path does exist, it tells me that "The destination already exists:.

## Version

* GitHub Desktop: 1.5.0

* Operating system:
Microsoft Windows [Version 10.0.17134.407]

## Steps to Reproduce

See description

### Expected Behavior

Repository downlods

### Actual Behavior

Error messages as mentioned in description

**Comment by steveward** [comment]
Thanks for the report @gavinayling. Could you upload the log file from GitHub Desktop so that I could take a closer look at what might be causing this?

To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`.

The log files are created daily -- please send over a log file as an attachment from a day where you experienced the issue.

**Comment by tierninho** [comment]
@gavinayling As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you!
