### ISSUE TITLE
Use other editor than Atom in Github Desktop

### ISSUE THREAD

**Issue by danielb987** [desktop/desktop#6332]
I have [EditPlus](https://www.editplus.com/) on my computer and would like to use it to edit conflicts. On Windows, it should be easy to open any editor with a filename, so my suggestion is that an option is added to Github Desktop to select which editor to use to edit files.

The problem is when I merge a branch into the current branch and there is a conflict. I then need to edit the file that has the conflict, but I don't want to install Atom in order to do this.

**Comment by billygriffin** [comment]
Hi @danielb987, thanks for the issue! You can update your default editor selection in "Preferences" as shown below:

<img width="445" alt="screen shot 2018-12-03 at 7 13 45 am" src="https://user-images.githubusercontent.com/5091167/49378911-1b343380-f6cb-11e8-91a1-33ae31102551.png">

Here's our documentation on currently available editor integrations: https://github.com/desktop/desktop/blob/master/docs/technical/editor-integration.md

It doesn't look like EditPlus is one of the ones currently available. We're open to adding new editors and there are instructions in that document on how to add new ones to the list of editors that Desktop detects and has available for use. Please let me know if you'd like to add detection support for EditPlus, in which case we can keep this issue open, and otherwise hopefully another one on the list works well for your needs. 😄

**Comment by danielb987** [comment]
Thanks for the info.
