### ISSUE TITLE
unable to commit after cmd+enter

### ISSUE THREAD

**Issue by fschroiff** [desktop/desktop#6334]
## Description

Partial crash. Unable to commit after hitting cmd+enter when having altered a single file. 

## Version

* GitHub Desktop: 1.5.0

* Operating system: macOS 10.14.1 (18B75)

## Steps to Reproduce

1. edit one file in repo. 
2. hit cmd+enter

### Expected Behavior

File gets committed with commit message "Updated foo.bar". 

This is what happens when you manually click "Commit to master" instead of using the cmd+enter keyboard shortcut.
This is also what happens when you focus the Summary field and then hit cmd+enter.

### Actual Behavior

"Commit to master" button is disabled, file is not committed. Client has to be restarted to be able to commit.

## Additional Information

none

### Logs

[2018-12-03.desktop.production.log](https://github.com/desktop/desktop/files/2640073/2018-12-03.desktop.production.log)

**Comment by tierninho** [comment]
@fschroiff Yes, this is a bug or at least something we can iterate on to make the feature more fluid.

The underlying issue is that when a commit is lying in wait, a user cannot immediately use the `cmd+enter` functionality as intended, and most therefore either click the `Commit` button manually or place the cursor in the summary or description fields, then `cmd+enter`.

I didn't find the `Commit` button to be disabled (greyed out), nor a restart req'd in order to resolve. 

Opening this up as `help-wanted` as it is a good candidate.

v1.5.1-beta0, mac

**Comment by tierninho** [comment]
@fschroiff Thanks for the update. Possible to include a pic or gif? I tried to reproduce this again, but no luck. 

I did get into a similar state by clicking the checkbox, then `cmd+enter`, which toggled on/off the `Commit` button. However, this intended behavior as seen here:

<img width="273" alt="screen shot 2018-12-04 at 8 17 03 am" src="https://user-images.githubusercontent.com/14828183/49456251-9e25be80-f79d-11e8-87e3-5e5fde3456bb.png">


Also, can you clarify about the "partial crash". Did Desktop crash by itself or you manually restarted the app?

**Comment by fschroiff** [comment]
@tierninho there might not have been a crash, I just interpreted the UI-state as being unresponsive. I had never even noticed the checkboxes ☑️ 👀. I learned now that focus on a file plus `cmd+enter` deselects the file (= un-checks the checkbox). And focus on the summary field plus `cmd+enter` triggers a commit. This is the source of my confusion. 

So I'll turn this from a bug-report into a feature request: When there's an autogenerated summary (which is the case when only one file has been edited) `cmd+enter` should trigger a commit even when the files pane is focussed.

**Comment by billygriffin** [comment]
Hi @fschroiff, we discussed this quite a bit internally and unfortunately the technical work to achieve something that captures the commit keyboard shortcut outside of the commit area is nontrivial, and we're not sure this would provide benefit for most users since we haven't heard this before. I totally understand how this could make things more convenient for you, but it's not something we intend to support unless we hear evidence that it's causing more widespread pain and/or confusion (or frustration from lack of convenience).

I really appreciate you describing your expectation of how this would work, and hope you'll continue to weigh in on things you'd like to see improved or that are causing frustration for you in the future. Thanks again! 😄 

One note for future reference: the toggle of the checkboxes is just caused by hitting the `enter` key alone.
