### ISSUE TITLE
Github desktop open external editor without any response

### ISSUE THREAD

**Issue by BettyZeng** [desktop/desktop#6352]
## Version

* GitHub Desktop: 1.5.0

* Operating system: windows 10

**Comment by steveward** [comment]
Thanks for contributing @BettyZeng.

We require the template to be filled out with all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway. 😀
