### ISSUE TITLE
Program: About to wait for parent PID XXXX

### ISSUE THREAD

**Issue by gimlin0610** [desktop/desktop#6353]
## Version

* GitHub Desktop:

* Operating system:

**Comment by gimlin0610** [comment]
Hello,
github desktop just stopped working on W10 from one day to the other! I uninstalled and  removed "GitHubDesktop" folder. New install always hangs at:
"program: About to wait for parent PID XXXX" -> where PID XXXX can't be found in processes!
seen in:
C:\Users\XXX\AppData\Local\GitHubDesktop\app-1.5.0\SquirrelSetup.log

**Comment by steveward** [comment]
@gimlin0610 thanks for the report. Could you fill out the issue template so that we have information about your setup? It would also be helpful if you could upload the `SquirrelSetup.log` that you mentioned. That should give some more information about why the installation is failing.

> github desktop just stopped working on W10 from one day to the other! I uninstalled and removed "GitHubDesktop" folder

Did you delete both the `%AppData%\GitHubDesktop` and the `%LocalAppData%\GitHubDesktop` directories prior to reinstalling GitHub Desktop?

**Comment by gimlin0610** [comment]
Deleting: 
%AppData%\GitHubDesktop
was the solution.
Thanks

**Comment by gimlin0610** [comment]
> @gimlin0610 thanks for the report. Could you fill out the issue template so that we have information about your setup? It would also be helpful if you could upload the `SquirrelSetup.log` that you mentioned. That should give some more information about why the installation is failing.
> 
> > github desktop just stopped working on W10 from one day to the other! I uninstalled and removed "GitHubDesktop" folder
> 
> Did you delete both the `%AppData%\GitHubDesktop` and the `%LocalAppData%\GitHubDesktop` directories prior to reinstalling GitHub Desktop?

Deleting:
%AppData%\GitHubDesktop
was the solution.
Thanks

**Comment by steveward** [comment]
@gimlin0610 I'm glad to hear that got things working!
