### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by Bram-Wel** [desktop/desktop#6354]
## Version

* GitHub Desktop:

* Operating system:

**Comment by billygriffin** [comment]
Thanks for reaching out @Bram-Wel!

We require the template to be filled out when submitting all issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway 😀

**Comment by Bram-Wel** [comment]
Exception Unhandled
Unhanled exception at 0x169FCBFEB (xul.dll) in frefox.exe
OxC0000005: Access violation writing location 0x00000000.

**Comment by Bram-Wel** [comment]
I experienced this while setting up GitHub on my desktop

**Comment by steveward** [comment]
@Bram-Wel are you still having difficulties installing GitHub Desktop, or were you able to successfully install? If you are continuing to have issues installing it would be helpful if you could fill out the template like @billygriffin mentioned. Thanks!

**Comment by Bram-Wel** [comment]
Well, I did install it eventually.
Thank you anyway.
