### ISSUE TITLE
BAT/CMD/SH prevented from Open in 'supported' editors.

### ISSUE THREAD

**Issue by msftrncs** [desktop/desktop#6361]
**Please describe the problem you think should be solved**
'BAT', 'CMD' and 'SH' files are blocked from being opened with the 'supported' editors, at least on Windows platform.

https://github.com/desktop/desktop/blob/3c98475e5dd89a428fa04a5222b2243ccf3cf3ad/app/src/ui/changes/changes-list.tsx#L266

https://github.com/desktop/desktop/blob/3c98475e5dd89a428fa04a5222b2243ccf3cf3ad/app/src/ui/changes/changes-list.tsx#L359-L371

https://github.com/desktop/desktop/blob/3c98475e5dd89a428fa04a5222b2243ccf3cf3ad/app/src/ui/lib/context-menu.ts#L22-L27

https://github.com/desktop/desktop/blob/3c98475e5dd89a428fa04a5222b2243ccf3cf3ad/app/src/ui/lib/context-menu.ts#L1

This seems like a mistake from the handling of 'Open with default program', which would definitely be a bad thing to do, but the 'supported' (aka 'external') editors should be trusted to open all file extensions, as it should be a requirement for 'support'.

**Comment by billygriffin** [comment]
Thanks @msftrncs. I'm not sure about the reason for those restricted files types, but maybe someone from @desktop/engineering or @desktop/support might know?

**Comment by Daniel-McCarthy** [comment]
@billygriffin I think the concern here is that it may be potentially dangerous to be running a command with files of these extensions. If for example passing a `.bat` file, the user may be intending to edit the script, but if the default program ran the `.bat` file instead of read it in, the result may be dangerous for the user.

The shell, batch files, executables could be potentially anything and be for a potentially destructive action if it were to be executed (such as a script that deletes files recursively, deleting contents of all sub-folders). I think they have been restricted as a safety precaution. 

This issue appears to suggest ensuring supported editors can handle these extensions without unexpectedly running them as a requirement for support rather than restricting the extensions outright.

**Comment by outofambit** [comment]
cc @niik for additional thoughts

**Comment by shiftkey** [comment]
The original context for this restriction was #2464 - when you open an executable-like file on Windows using the "Open in Default Program" Electron API, it gets executed. I've written a bunch here about what happens under the hood and the current limitations: https://github.com/desktop/desktop/issues/4753#issuecomment-392394769

Where I think we went wrong was applying the same restrictions to our "Open in External Editor" context menu action, because we have more control over the behaviour. In this flow, we know what program we're going to launch, and we know it isn't going to execute the contents, so it doesn't make to restrict files like `.bat` and `.sh` from being edited.

**Comment by billygriffin** [comment]
Given @shiftkey's explanation above, this seems like we could maybe exclude those file restrictions from the "Open in editor" flow assuming there's a valuable user-facing reason to do so.

@desktop/engineering and @desktop/comrades Thoughts on whether that makes sense?

**Comment by JC3** [comment]
Hi. Notepad++ doesn't run these files when you open them. Therefore, this restriction is pointless and annoying, so it should be removed. Or just add an option in the preferences.

Also, I'm not sure how .sh is any more or less dangerous than .py, .pl, .js, or any number of other file extensions that can be (and usually are) associated with a default program that runs them. Or .h, if I've set `cmd /C "del *"` as its default editor. GHD can't know any of that, it just disables the menus for some arbitrary file extensions in a mediocre attempt at solving a problem it's not supposed to be solving. Plus, the fact that they included .bat but not .ps1, or .exe but not .com (or .msi, or .scr), is kind of odd.

**Comment by JC3** [comment]
Also, I'm not sure how .sh is any more or less "dangerous" than .py, .ps1, .pl, or any number of other file extensions that can be associated with a default program that runs them.

Or .txt, if I've set `cmd /C "del *"` as its default program. GHD can't know any of that, it just disables a few arbitrary file extensions with a mediocre attempt at solving a problem it's not supposed to be solving.

**Comment by JC3** [comment]
All right, I figured out how to disable the restrictions:

1. Open the GHD installation folder.
2. Edit *app-2.8.1/resources/app/renderer.js* (replace 2.8.1 with whatever version).
3. Search for the string ".bat", case sensitive. Eventually you'll see some obfuscated JS like:

       const ma=[".cmd",".exe",".bat",".sh"];

4. Edit that list of extensions to your heart's content, then save the file, and restart GHD.

Tada, now both "Open In" options work. If you update GHD you'll have to reapply the patch.

![image](https://user-images.githubusercontent.com/5651184/116946455-25660d80-ac48-11eb-85b4-27862990c77c.png)
