### ISSUE TITLE
Ignore all .class Files is not working...Still showing in the view....

### ISSUE THREAD

**Issue by c003894** [desktop/desktop#6422]
## Version

* GitHub Desktop:

* Operating system:

**Comment by tierninho** [comment]
@c003894 thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
