### ISSUE TITLE
Cannot Open Existing Local Repository, located on my OneDrive. Yet others work just fine?

### ISSUE THREAD

**Issue by HeavenlyEntity** [desktop/desktop#6431]
## Description

I do not understand how all other repositories work just not this particular one. Can anyone help me figure this out? 
![2018-12-15_17-29-48](https://user-images.githubusercontent.com/39228141/50048807-3a02d480-0092-11e9-9783-e9bbf931529e.gif)

I even paused the sync so see if that had an issue.

@codealtgeek 
Help!

## Version

* GitHub Desktop:

* Operating system:

**Comment by shiftkey** [comment]
@HeavenlyEntity thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by msftrncs** [comment]
@HeavenlyEntity, possibly it is a GIT problem, possibly corruption in the GIT database.  There is probably a GIT error in the logs that will explain.

**Comment by shiftkey** [comment]
Closing this out due to inactivity.

@HeavenlyEntity if you're able to include the log files (that will have the error and some underlying details about the repository) we're happy to revisit the issue and troubleshoot further. The **Help** | **Show Logs in Explorer** menu items should open the logs folder, and inside those are the log files generated by day.
