### ISSUE TITLE
Support submodules fully

### ISSUE THREAD

**Issue by RFL369** [desktop/desktop#6450]
> When can we expect github desktop to fully support submodules?

**Please describe the problem you think should be solved**
A clear and concise description of what the problem is and who else might be impacted. Screenshots are encouraged.

Example:

> “When I run into a merge conflict, I don’t know where to go to resolve it. Anyone who works off of multiple branches will likely run into this problem at least occasionally.”

**[Optional] Do you have any potential solutions in mind?**
A clear and concise description of one or more solutions you think might solve the problem. Please include any considered drawbacks or tradeoffs, and how users might use your solution(s). Screenshots or mockups are helpful here!

**Comment by steveward** [comment]
Thanks for opening this @RFL369. There are a number of open issues related to submodules -- are there any specific problems you are having that have not been previously reported? There have also been some improvements to submodules that have shipped, like https://github.com/desktop/desktop/pull/5154. 

It would also be helpful if you could fill out the template. We request you fill out the template so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

**Comment by shiftkey** [comment]
Closing this out due to inactivity.

@RFL369 if you're able to answer the questions from @steveward and fill out the template (I edited the original comment to add in the template, in case you weren't able to find it) we're happy to revisit this.
