### ISSUE TITLE
The Branch menu turn grey, I can't use that. If I close and restart github desktop, It will ok.

### ISSUE THREAD

**Issue by JoeZhou266** [desktop/desktop#6456]
## Version

* GitHub Desktop:

* Operating system:

**Comment by billygriffin** [comment]
Thanks for reaching out @JoeZhou266!

We require the template to be filled out when submitting all issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway 😀
