### ISSUE TITLE
Repositories are difficult to find, navigate, and differentiate

### ISSUE THREAD

**Issue by billygriffin** [desktop/desktop#6460]
**Please describe the problem you think should be solved**

We've seen many issues suggesting to change the way we either visualize or group repositories in GitHub Desktop. Right now we just organize repos alphabetically and it's tricky to differentiate many of them visually because it's just in the format of [repo name], which doesn't account for a variety of different scenarios. We have a tooltip that displays on hover, but it's relatively undiscoverable, slow to appear, and requires you to look at each repo individually to differentiate. We also group repos that are on GitHub.com separate from those that are purely local or on another remote. We do have filtering repos via a text input in place today, which should be helpful, but obviously not sufficient based on the feedback. 

There have many different implementations suggested, so I wanted to try organize most of the issues I could find in one place to attempt to get our arms around the problem areas as we try to determine a path forward. Ideally, whatever we implement would be something we could work forward from and we could therefore close and/or remove `future proposal` from all the previous issues.

**Relevant issues:**

Group repos by organization and show full repo name: https://github.com/desktop/desktop/issues/1533
Ability to "pin" repos to top of list: https://github.com/desktop/desktop/issues/2038
Allow repo list to be always expanded: #1593 
Group repos by organization (and make orgs collapsable): https://github.com/desktop/desktop/issues/2037
Add categories for repos to be grouped together: https://github.com/desktop/desktop/issues/4945
Add folders for repos to be grouped together: https://github.com/desktop/desktop/issues/1598
Group or filter repos by [Topics](https://blog.github.com/2017-01-31-introducing-topics/): https://github.com/desktop/desktop/issues/4958
Drag and drop and/or add labels to repos: https://github.com/desktop/desktop/issues/2324
Add visual differentiation for repos: https://github.com/desktop/desktop/issues/1929
Add a keyword to repos in Desktop: https://github.com/desktop/desktop/issues/4940
Add placeholder name for repos in Desktop: https://github.com/desktop/desktop/issues/3197
Support multiple windows: https://github.com/desktop/desktop/issues/3606
Don't persist repo filter after selecting one: https://github.com/desktop/desktop/issues/4273
Filter across multiple repos with OR operator: https://github.com/desktop/desktop/issues/5280
Repo order is not maintained alphabetically after filtering: https://github.com/desktop/desktop/issues/4184

Slight variation
Some way to visually distinguish worktrees: https://github.com/desktop/desktop/issues/5764

Additional contextual things:
Which repos have unpushed changes without having to go through the whole list: https://github.com/desktop/desktop/issues/7053

**Potential problems on ordering/grouping:**

1. I want to access the same [x] repos frequently, and navigating to them is unnecessarily time-consuming.
2. When I'm a member of many organizations, I'm only interested in repos for a particular org at a time and having them intermixed and always visible makes it hard to find the ones I care about.
3. Similar to 2 above, filtering only filters on the repo name, but if I want to see the repos in a particular org, for example, there's no way to accomplish that.
4. My mental model of organizing my repos doesn't fit nicely into alphabetical / by GitHub org / other out of the box way of grouping them together. 
5. I can't always remember the name of the repo I'm looking for exactly for filtering to work.

**Potential problems related to visualizing:**

1. If I have the same repo cloned in multiple locations locally, there's no way to visually differentiate between them without the tooltip, which is slow to appear and undiscoverable.
2. I sometimes can't remember what each repo is actually for just by the name, and it would be helpful to have some metadata to trigger my memory.
3. If repos have the same name but are under different orgs, there's no way to differentiate between them except with the tooltip (see 1 above).

**Additional considerations**

1. We should account for forks
2. Not all repos are pushed up to GitHub - ensure we account for that
3. Org names and repo names are often long and this should account for that
4. Worktrees also share the same problems of visually distinguishing them (see: #5674)

I'm sure I didn't capture everything here, so please feel free to suggest edits to this, and feedback is absolutely welcome.

cc: @desktop/design @desktop/support @nerdneha @adamreisnz

**Comment by elliotcm** [comment]
Thanks @billygriffin.

All of the above are useful suggestions.  It feels to me like the crux is not necessarily a difficulty in finding something per se (though that's the case for some things), but for me it's about cognitive load.

Out of all the repos in the world we're already filtered down to the ones that we work on enough to have bothered to import them into Desktop, so we just need a few tools to speed up the last bit of sorting and filtering to get us from dozens down to 1.

That's why most of the features you have here are sorting (most recent, most frequent, pinned repos) or filtering (various kinds of collapsible groups act as filters).  You mention that the list currently has filtering but really it has searching, which is a different sort of task.

**Comment by adamreisnz** [comment]
Thanks for putting this together @billygriffin , I think it's a good summary of the problems/considerations.

Maybe a good idea to also try and list some of the suggested possible ways of addressing these problem, and see which ones are plausible and make the most sense.

I'll start off by listing a few off the top of my head, with potential pros and cons that come to mind.

### Display organisation name in front of the repo name in a muted colour
Pros
- Simple and tidy solution
- Organisations are already an established way of organising repo's
- Quick visual identification of repo possible, provided organisation name is meaningful

Cons
- Organisation name can be long
- Repository may be non-github and not have an identifiable organisation name
- Doesn't help people much who have large organisations with many repo's

### Display the parent folder name in front of the repo name in a muted colour
Pros
- More control over what's shown than displaying the often static organisation name
- Quick visual identification of repo possible, provided folder name is meaningful

Cons
- There may be no parent folder
- Folder name may me meaningless and just add noise
- Forces people to organise their folders well

### Filter repo list by organisation
Pros
- All organisation repo's visible at the same time
- Focus only on the org you're working with/on at that time
- Relatively low effort to implement, as the current search filter could be adapted to also match organisation name

Cons
- Repository may be non-github and not have an identifiable organisation name
- Doesn't help people much who have large organisations with many repo's
- Adding another filter dropdown to the repo list may clutter the UI

### Custom grouping of repo's in virtual folders/groups
Pros
- The most flexibility to organise repo's as you see fit
- Doesn't matter if a repo is Github hosted or elsewhere
- Works also when a repo doesn't have an organisation or parent folder

Cons
- Doesn't offer users a point to start with
- Requires the user to pro-actively maintain and organise repo grouping by hand
- Filtering/search may still need to be adjusted to account for groups
- Larger effort to implement

### Pinned/favourite repo's
Pros
- Simple, light-weight solution
- Probably sufficient for a large number of users
- Quickly have the repo's you work with the most at the top of the list, without needing to filter/search in addition
- Doesn't matter if a repo is Github hosted or elsewhere
- Works also when a repo doesn't have an organisation or parent folder

Cons
- Only useful if the number of repo's you work on at any given moment in time is limited
- Still doesn't differentiate repo's if they share the same name
- Doesn't address the problem of not remembering/knowing what a repo is by name (although if you've pinned it, you can be assumed to know what repo it is)

### Add keywords to repo's
Pros
- Can add multiple keywords for multi-dimensional organising
- Flexibility to organise repo's as you see fit
- Doesn't matter if a repo is Github hosted or elsewhere
- Works also when a repo doesn't have an organisation or parent folder

Cons
- You may forget the keywords
- Still doesn't differentiate repo's if they share the same name
- Will need to adjust the search filter to also match keywords, which could sometimes result in false positives (e.g. if a repo name partially matches a keyword)

**Comment by say25** [comment]
Just something to add from my personal experience. I personally manage two copies of the same repo because the project is rather large and sometimes running two copies of the same project for debugging purposes is nice.

**Comment by felga** [comment]
For me just being able to set a alias to the repo will be enough. I can put numbers or anything I want in the begining to group and continue to use the current ordering.

**Comment by ampinsk** [comment]
Adding a note on analytics from a discussion in Slack: 

- The majority of Desktop users have 3 or fewer repos.
- Median is 2 repos, 75th percentile is 5 repos, 90th percentile is 10 repos

As @billygriffin put it: 
> So for improved repo organization purposes, it seems like we're solving it for maybe around 10-20% of users, where the other 80-90% won't see a big difference.
> However, that's not as relevant for visualization of repos, where the absolute number of repos is less important than how they're displayed.

**Comment by Janpot** [comment]
> So for improved repo organization purposes, it seems like we're solving it for maybe around 10-20% of users, where the other 80-90% won't see a big difference.

Is plain user count the right metric here? What if those 10-20% users use the app way more often?

**Comment by billygriffin** [comment]
@Janpot Oh absolutely, we just wanted to share _a_ metric that helped to color the impact of the first set of problems. Totally agree that it's not the full story, we just wanted to share this to add context to any potential solutions.

**Comment by xt0rted** [comment]
I've got 35 repos right now (cleaned some out last month) and expect to be adding another 10+ over the next month or so. I also use the app every day.

**Comment by ampinsk** [comment]
Thanks everybody for the extra context! To echo what @billygriffin said, just because in pure numbers the majority have a small amount of repos doesn't mean we aren't interested in working on alleviating the frustration of having many repos. If anything, we just don't want to make the experience _worse_ for users who have a few 😄

**Comment by StefanoCecere** [comment]
Usually pros with many repos need advanced features, that Desktop doesn’t have.. that’s why 90% Desktop users have 3 repos, they are casual users... I (60 repos, like many using git daily for everything ) would use Desktop as “non advanced client” only if it had some groupings, like discussed here.. so it is a must feature to attract advanced users

**Comment by adamreisnz** [comment]
Done!

**Comment by Janpot** [comment]
Sure

**Comment by kuro68k** [comment]
> * The majority of Desktop users have 3 or fewer repos.
> * Median is 2 repos, 75th percentile is 5 repos, 90th percentile is 10 repos
#3816 

Is that because they only want 5 repos, or because organizing more than 5 becomes a real pain?

I have had 40+ repos at work for various projects because I had to, and anything that encourages people to use more repos instead of single giant repos has to be a good thing.

**Comment by kuro68k** [comment]
Tagging is effective and flexible. With the ability to "pin" tags the user could create their own custom views, as well as quickly doing tag searches when required. Tags are somewhat preferable to folders because a project can have as many tags as needed, where as generally it can only be in one folder.

Ideally the tags would sync with Github so that the same search/filtering options are available via the web and to all members of an org.

Personally I preferred the old UI where there was a list down the left hand side with a search box. Fast access is important when you have many repos and switch often.

**Comment by adamreisnz** [comment]
@kuro68k 

> Personally I preferred the old UI where there was a list down the left hand side with a search box. Fast access is important when you have many repos and switch often.

I also missed the sidebar originally, but you can bring it up with `CMD-T` now, and the search box gets focus automatically, so it's pretty quick still to access the sidebar once you get used to it.

**Comment by DorothyLindman** [comment]
When you decide on the UX around this issue, please remember to add something into the documentation or help files explaining what the grouping scheme is, what the icons mean, etc. In about 15 minutes of searching, I haven't found anything that explains this. 

(Is there any maintained documentation on how to read the UI? I wrote a brief intro several months ago, but it's already out of date, and I haven't found the necessary docs to update it.)

**Comment by kuro68k** [comment]
It seems like some of the tagging could be automatic, e.g. language used.

I was in a company with hundreds of repos, initially organized in a hierarchy. We found that tags were a much better solution.

**Comment by billygriffin** [comment]
Thanks for the perspective folks - we're working through a few other things and still digesting this so sorry for the delay, but this is all helpful context and we appreciate it.

>  In about 15 minutes of searching, I haven't found anything that explains this.

Hi @DorothyLindman! I'm curious what specifically you're referring to. Do you mean related to this issue or more generally in GitHub Desktop? If you'd be willing to chat about that separately, I'd love it if you'd fill out the form reference in [this comment](https://github.com/desktop/desktop/issues/6460#issuecomment-454538858) and I'll reach out.

**Comment by TheGrimSilence** [comment]
I guess I'll add to this. There are a variety of ways the organization can be done.

Virtual folders, groups, etc, are all nice. The organization is a very tedious task, and maintaining it is a pain. I personally recommend a form of multi-layered organization. Anywhere between visual hints to actual rendering changes can be helpful.

## Visual Hints
### Public vs Private
One of the issues we immediately face is being able to tell one kind of repo from another, this includes public and private. The book and lock icons are all the same color in a tight space, I recommend subtle color changes like giving the lock a slight red tint or something similar.

### Clone vs Source vs Fork
This organization can be achieved by dropdown groups.

### Organizations
In a tree of repos, we can simply add the org's icon in front of a dropdown with the org's name similar to how users are rendered in commit history, and then let the user decide if it should be alphabetical or orgs-before-repos.

### Parent folder
Adding a muted parent folder would help greatly. There should always be a parent, whether its a folder like `/var` or a drive like `C:/`. We don't have to hold the user accountable for organizing their folders, it would just give them an idea of where it is in the file system and they may remember what it's for automatically. 

**I don't think the parent should come before, because variable length names would break uniformity.** Instead, the parent should be placed _above, below, or to the right of,_ the repo name, in a smaller font in a muted style.

### Description
This one is honestly a helper. Not every repository has a description, and so it should be a conditional render. Descriptions should be placed preferably under the repo name in a smaller, and dimmer (but not muted), style.

**Comment by gingerbeardman** [comment]
I've come from #1593 and just wanted to say that I have ~45 repos in Desktop (mix of own projects and OSS). I miss the always present repo list of Classic. My use case for it was just like the favourites sidebar in Finder. Like a list of sources. It could even be considered a list of tabs.

It's just annoying to have to click the top left corner (small target compared to Windows size) every time I want to switch repos. It feels like a task/trial/test I am forced to do every time I want to switch repo. I know the repos are there, I put them there, just let me at them with minimal clicks.

Generally I don't like things that can be used frequently being hidden behind dropdowns or popups. This is one thing that still keeps me loading up Classic mostly.

For reference I am the type of person that has a lot of icons in my Dock and a lot of Tabs open in Safari, for the same reasons. FWIW

**Comment by j-f1** [comment]
The Cmd+T shortcut also works to open the sidebar.

**Comment by kuro68k** [comment]
Is there any reason why it couldn't just be the default target for any random keyboard input?

Like when you have the Windows start menu open, no matter what you are doing with it if you just start typing it immediately opens the search page and starts capturing the input. No shortcuts or anything needed, just start typing.

Another option would be some kind of "omnibar" like a web browser. Shows the address or repo name, acts as a search box, accepts commands for people who like the CLI...

**Comment by adamreisnz** [comment]
I like the omnibar idea :+1:

**Comment by BrunoScheufler** [comment]
Are there any updates or decisions already made regarding the repository groups/pins/etc. ?

**Comment by billygriffin** [comment]
@BrunoScheufler We're still thinking through the larger question of navigating amongst repos, but the latest beta release that went out today contains https://github.com/desktop/desktop/pull/6923, which sorts the repos by owner, and adds the org name to the filter so you can quickly get all repos for a particular owner. It'll likely stay on beta for awhile as we're iterating on it, but that's where we're at right now.

**Comment by adamreisnz** [comment]
@billygriffin I think you mentioned earlier but I can't seem to find it, is this beta publicly accessible somewhere or invite-only?

**Comment by tierninho** [comment]
Please find beta here: https://central.github.com/deployments

**Comment by say25** [comment]
@tierninho I don’t think we can all see that.
@adamreisnz here is the README link to the betas
https://github.com/desktop/desktop/blob/development/README.md#beta-channel

**Comment by adamreisnz** [comment]
> but the latest beta release that went out today contains #6923, which sorts the repos by owner, and adds the org name to the filter so you can quickly get all repos for a particular owner.

This is great! Already a huge improvement in navigating and discoverability of repo's, awesome work.

**Comment by cloewen8** [comment]
The **one thing** keeping me from switching from the classic to the newer version is that the repository list is hidden by default (#1593). It saves real estate but it hurts usability a lot.

Going from,
- moving to the repository -> clicking,

to

- moving to the button -> clicking -> moving to the repository -> clicking,

is a fairly large jump. My workflow involves switching between repositories frequently and every action adds up over time.

Since Desktop uses web technologies, why not use a responsive design? Hide the list if a break-point in the design is hit, but keep it always visible otherwise.

**Comment by penCsharpener** [comment]
@cloewen8 I agree but with ctrl + T could can jump straight into the repo search box which speeds things up significantly.

**Comment by xavierfoucrier** [comment]
This could be an option in Github Desktop, and may be just **splitting repos by public/private** could be a start. :wink:

**Comment by billygriffin** [comment]
Thanks for the feedback @cloewen8. Were you familiar with the Cmd/Ctrl + T shortcut to get to the repo dropdown? I'm curious if that makes it easier for you. We've generally heard good things from users who have a lot of repos and use that to quickly get to the list, but I'm curious how having it always open makes that easier for you.

**Comment by cloewen8** [comment]
I was not familiar with `Ctrl + T` before @billygriffin . I tried it out after it was suggested and I generally found it to be **about the same**. I generally interact with Desktop using a mouse, so for the most part I'm just swapping moving my mouse for moving to a keyboard.
I'd imagine that people who already know about the shortcut also know about other related shortcuts. **Could be a correlation**, I don't have the aggregates.

My main point is that it requires **twice as many actions**, and forces the user **to focus far more** when they don't see what they are looking for. The best interfaces are those that you don't have to think about.

**Comment by shiftkey** [comment]
In #7178 @IdanAdar suggested making the new changes opt-in (or configurable)

**Comment by shiftkey** [comment]
@IdanAdar I'd move this suggestion to the issue related to the change, but #7132 has been closed so I figure I'd ask here:

  - can you elaborate on why you don't want to see the "Recent Repositories" list?
  - is there changes to how "Recent Repositories" work that would change your mind about using it?

**Comment by IdanAdar** [comment]
Sure. 

In my role as SRE/DevOps, I frequently update most if not all of our repositories. As such they are all “recently used repositories” and I don’t want/need the list of repositories to branch out as it becomes a cognitive burden to have the repositories “switch places” all the time. 

I’d much prefer the option to manually order/sort the repositories to my liking instead.

**Comment by kuro68k** [comment]
I can second this. Anything which results in lists being re-ordered is just frustrating and burdensome.

Solutions like having multiple repos open in tabs work better for switching between a bunch of items currently being worked on, if that is what the user wants to do.

**Comment by daGUY** [comment]
I have a couple of issues related to this that I didn't see explicitly called out.

The way we organize projects at my company is we have a Bitbucket project and then inside of that a repo named after the CMS used. So the path to a particular repo looks like this: https://me@bitbucket.mycompany.com/scm/project/cms.git.

Since all of our projects come from the same source/organization (Bitbucket), and all the individual repos are named the same, my list of repos looks like this:

- cms
- cms
- cms
- cms
- cms
- cms
- etc.

Worse, because all these repos have the same name, the sort order is determined by the order in which I cloned them locally. So the underlying order (with the path revealed, but which I can't actually see from the UI) is not alphabetical:

- project_f/cms
- project_h/cms
- project_b/cms
- project_a/cms
- project_g/cms
- project_z/cms
- etc.

Worse still, I can't even manually drag-reorder these into alphabetical order by project. I'm just stuck with them like this.

The only way I can differentiate all of these identical-looking repos is to hover over each one individually to see its full path in a tooltip, but that's very slow and cumbersome, especially since they're not in alphabetical order and the project I'm looking for could be literally anywhere in the list. I have to start at the top and hover over every single one, one at a time, until I find the one I'm looking for.

It would be _really_ useful if, at a minimum, the parent folder of the repo was also displayed directly in the list like I've shown it above. It would be even better if the sort order then was alphabetical by parent folder instead of repo name.

**Comment by gingerbeardman** [comment]
@daGUY out of interest, how did GitHub Desktop Classic cope with your setup?

**Comment by billygriffin** [comment]
Thanks for the feedback y'all, it's really appreciated. We know what we ship here isn't going to solve everyone's problems because some people use very different workflows, but we're hoping it will help with many of the problems raised.

> it would be really useful if, at a minimum, the parent folder of the repo was also displayed directly in the list like I've shown it above

The problem with always showing the parent folder is that repo length is often pretty long, and we quickly run into horizontal spacing issues. In grouping repos by org, that was an attempt to solve what many people were struggling with there without a pretty huge redesign of the repo list more generally, which we're not prepared to take on without evidence that it's negatively affecting a lot of users.

> I frequently update most if not all of our repositories. As such they are all “recently used repositories” and I don’t want/need the list of repositories to branch out as it becomes a cognitive burden to have the repositories “switch places” all the time.

To be clear, the Recent section doesn't displace the rest of the list, so those repos will still exist in their respective orgs, and they're also filterable. We're also shortening the 5 recent repos to 3 as that provides quick access to 4 different repos (your current one and the previous 3 that you opened).

> Solutions like having multiple repos open in tabs work better for switching between a bunch of items currently being worked on

We played with some tab design concepts, but couldn't find a way to implement them without significantly redesigning the app, so we're hoping this will be a reasonable compromise for those who switch back and forth between a few repos throughout the day.

**Comment by adamreisnz** [comment]
Love the new grouping by organisation in the beta version 🎉 😍

**Comment by daGUY** [comment]
> > it would be really useful if, at a minimum, the parent folder of the repo was also displayed directly in the list like I've shown it above
> 
> The problem with always showing the parent folder is that repo length is often pretty long, and we quickly run into horizontal spacing issues.

I totally understand and agree with the concern, but there are a number of ways to mitigate that:

1. Resize the repo list to be wider (this is already supported, up to ~500px wide)
2. Display parent folder names _only_ for repos within the same organization that have the same name, so that they don't clutter up the list for other repos that can already be differentiated by name only
3. Display parent folder names on a separate line, so that the amount of horizontal space available to display the repo's name isn't lessened by the length of the parent folder's name
4. Worst case scenario, add a toggle to the app's settings that lets the user choose if parent folder names are shown or hidden

Again, I recognize my use case is in the minority. But not displaying parent folder names at all makes the app practically unusable for me, whereas adding them shouldn't be detrimental to other use cases, especially if they were only shown selectively or could be turned off entirely.

**Comment by koenpunt** [comment]
> 2\. Display parent folder names _only_ for repos within the same organization that have the same name

@daGUY it's not possible to have the same repo twice in an organization. So or you're having multiple copies, or you're using worktrees. If the former is true, I can recommend you looking into using [`git worktree`](https://git-scm.com/docs/git-worktree) instead. For worktrees, I think it should not be the parent directory that is shown, but simply the branch that's checked out, as I proposed here: https://github.com/desktop/desktop/issues/5764

**Comment by billygriffin** [comment]
@daGUY Thanks for the additional feedback! Which version of the app are you using currently, out of curiosity? I'm interested in understanding how what is currently shipped to beta either makes your life easier or not. You can download the beta here if you're not currently using it: https://github.com/desktop/desktop#beta-channel

**Comment by daGUY** [comment]
> @daGUY out of interest, how did GitHub Desktop Classic cope with your setup?

I don't know, I never ran into this situation until recently. I can't remember if the classic version showed repo parent folder names or not.

> @daGUY it's not possible to have the same repo twice in an organization.

Maybe I'm not understanding how grouping by organization works, or I'm using the wrong terminology. All my repos are hosted in Bitbucket. All the repo names are the same (`cms.git`), but they're all in different projects in Bitbucket, so they're not copies of each other. The projects all have unique names. In GitHub Desktop, my sidebar just has one section called "Other" and all of my repos are listed under there.

> @daGUY Thanks for the additional feedback! Which version of the app are you using currently, out of curiosity?

I'm using the stable build, but I tried the beta and it's no different – all my repos are grouped together under one section in the sidebar called "Other," with the same sorting issues and everything as discussed above.

**Comment by say25** [comment]
Looking into this area. Would it be possible to sort by repo name then path? This way the repo order is consistent for those of us with multiple checkouts of the same repo. https://github.com/desktop/desktop/blob/50b9a95d70db463e4323b98b475ea9ba4bfaa606/app/src/ui/repositories-list/group-repositories.ts#L91

**Comment by mort666** [comment]
> Adding a note on analytics from a discussion in Slack:
> 
> * The majority of Desktop users have 3 or fewer repos.
> * Median is 2 repos, 75th percentile is 5 repos, 90th percentile is 10 repos
> 
> As @billygriffin put it:
> 
> > So for improved repo organization purposes, it seems like we're solving it for maybe around 10-20% of users, where the other 80-90% won't see a big difference.
> > However, that's not as relevant for visualization of repos, where the absolute number of repos is less important than how they're displayed.

I really don't know where you get your data from, most power users disable your telemetry thus your choices based on it are flawed. As a result so you are often making decisions about a class of user you actually have no data on because they disable a system you use to collect data you base your decisions on. This is fundamentally one of the biggest flaws in decision making based on telemetry systems. At someone has had to make those sort of decision for our products, I am acutely aware of this.

Myself and my entire engineering team of over 100 people now have over 150 repos for our product we develop. 

About half the team use the old Native Github Desktop software still because the new Electron Github Desktop client is not fit for purpose. Some have moved to other solutions because of lack of an always visible repo list that can show the entire repo name and is filterable.

Take a look at the old code FFS, it does the job really well, issue #1593 has been voicing this deficiency now for 3 years.

**Comment by tierninho** [comment]
From #7589 

> Can we get a mode to look and surf repo's like you can do on the website? Look at repos, and search up users and repos.

cc @MoniS10

**Comment by amcgregor** [comment]
> … most power users disable your telemetry thus your choices based on it are flawed.

Can confirm; several teams on my side of the fence, none of them leave telemetry enabled, on anything in their system.

> Myself and my entire engineering team of over 100 people now have over 150 repos for our product we develop.

My open source suite has 46 active projects (18 archived legacy projects), and my modular work codebase comprises ~37.  There are about a dozen third-party dependencies I also track for changes via local check-out, netting just over 100 total repositories.

My particular issue is that I'm… almost religiously un-creative naming the projects.  "Session handling" for my web framework is `web.session`, checked out into `~/Documents/Marrow/Code/session` — I strip common prefixes.  The organization-specific customizations of that go in `cegid.session`, likewise checked out as `session` under `~/Documents/Cegid/Code/session`.  This pattern repeats for most elements/aspects of a web application.

Now, I do notice that a change has been made such that if there is more than one common checked-out name, it prefixes it in the listing with the organization, a la:

![Screen Shot 2019-05-28 at 8 39 11 AM](https://user-images.githubusercontent.com/76750/58478449-20c38100-8124-11e9-94b3-fb8a5361030d.png)

This is almost acceptable.  Almost.  Except the ghosted organization name doesn't actually exist for the purposes of filtering; it is purely visual.  Additionally, the above screenshot had to wait a good 30 seconds for the sort order to settle down, the items were literally flapping back and forth.  Not a stable sort.

> About half the team use the old Native Github Desktop software still because the new Electron Github Desktop client is not fit for purpose.

I would generally agree on this point; the vast majority of my Git interactions are via command-line, with the GitHub Desktop client relegated to visual hunk selection duties.  Only when I need to commit a portion of a change do I use it, and even then, I often have to disable things like pre-commit, since GitHub Desktop doesn't let you control the execution context for those calls.  (I require either a virtual environment be active—modified `PYTHONPATH` and `PATH`—or that the interpreter from within the `.venv/bin` directory be directly invoked.)

> Some have moved to other solutions because of lack of an always visible repo list that can show the entire repo name and is filterable.

My DIY "life hack" for this is to split-screen a Finder window next to GitHub Desktop; I check out all of my code repositories into `~/Documents/<org>/Code/*` — a tab per org and I'm essentially good to go on that.  There are a few tools (App Store and otherwise) available to badge Finder icons with SCM status, e.g. [Stat](https://itunes.apple.com/ca/app/stat/id931063335?mt=12) (just badges) or [SnailGit](https://itunes.apple.com/ca/app/snailgit-git-for-finder/id847260112?mt=12) (more complete integration), or the open source [GitStatus](https://github.com/glegrain/GitStatus) (badges) or [Seeker](https://github.com/jyuhuan/Seeker) (right-click command invocation).  Of course, on a secondary display, Electron apps take up way, way too much space—could not find an option to disable word wrapping, which gets absolutely ludicrous.

![hey-there--a-little-space-please](https://user-images.githubusercontent.com/76750/58480356-35a21380-8128-11e9-8f76-a0ad25cbd3f1.png)

**Comment by billygriffin** [comment]
Hi folks, I really appreciate y'all weighing in on this. 

Re: the metrics, we totally agree that it's not perfectly representative, but the opt-in rate is high enough that we think it's a decent starting point. We don't make decisions exclusively based on that kind of data, but rather just use it as one input of many.

Re: BitBucket repos showing up in "Other," we haven't done anything fancy around organization of non-GitHub repos, and we don't have as solid an understanding of what we get back from repos from other hosting providers. While we intend to continue basic support for repos from other sources, our primary goal is for the GitHub <-> GitHub Desktop experience to shine.

Re: the individual configuration issues, I hope you'll understand that some people have wildly varying personal preferences here and configurations (as evidenced by the initial collection of issues linked from this one, all of which specify different solution that would upset someone ), so we try to make decisions that will improve things for as many users as we can, and not materially regress the experience of others. While we hope GitHub Desktop can be a great tool for as many people as possible, we also know that if we try to please everyone, we'll end up pleasing no one. We're definitely not wedded to this as the forever and always solution, but we do want to give it time to breathe after the ship and for more people to start using it so we can learn from as representative a population as possible and continue to iterate from there.

I'm going to close this issue since this has now shipped to production in 2.0, and we'll continue to collect feedback and go from here. Thanks again!

**Comment by lalomartins** [comment]
Thanks for weighing in (back) @billygriffin and thanks for the release. I for one am happy with the current implementation, although my experience does agree with the idea that heavier power-users are precisely the ones most likely to turn off telemetry, so opt-in numbers are not in question — it's a matter of (possible) data bias.

As for ‘other’, I'd suggest just displaying the domain for the primary remote? IDK. Won't help for people who have tons of stuff on gitlab/bitbucket/etc, but the overlap between those and users of Github Desktop shouldn't be that big, maybe. For most of us who have just a few it would help.

Anyway, thanks again.

**Comment by xavierfoucrier** [comment]
Hi @billygriffin,

It sounds perfect for me in **Github Desktop 2.0.3**, nice work! :v: :tada:

**Comment by varkor** [comment]
> The problem with always showing the parent folder is that repo length is often pretty long, and we quickly run into horizontal spacing issues.

Is it not possible to only display the parent folder if there are two or more folders with identical names? This is what text editors like Visual Studio Code do and it works well. At the moment, this particular issue isn't addressed at all. It seems like displaying the parent in the identical folder name case would be strictly an improvement and wouldn't regress users who don't have duplicate names.

**Comment by adamreisnz** [comment]
Thanks for your work on this team 🚀 🎉

**Comment by karim** [comment]
What about Wikis hosted on GitHub?

At the moment, they are displayed under `Other` and not under their owner.

**Comment by amcgregor** [comment]
> What about Wikis hosted on GitHub?
> 
> At the moment, they are displayed under `Other` and not under their owner.

I resolve these by, for each project utilizing a GitHub wiki, attaching the wiki repository as a submodule to the primary one. Doesn't make use and interaction easier, but does keep GitHub Desktop's repository list somewhat cleaner.

**Comment by karim** [comment]
Thanks @amcgregor, I never thought about that. :smiley: 

I was hoping GitHub Desktop would treat wikis as normal repos and place them under the owner name but they are somehow treated differently, but I will do it your way for now. Thanks a lot.

**Comment by EdOverride** [comment]
How about we just allow to create single level category and move repos in that?

This solution would be easiest to implement and would be enough for most people, who have 30+ repos in the list.

![GitHub Desktop 2019-07-13 19 51 38](https://user-images.githubusercontent.com/52044016/61174417-5cb58700-a5a8-11e9-893e-afe9070788d6.png)

**Comment by Timelapser** [comment]
#8158

**Comment by MartinNiederl** [comment]
Now more than a year has passed since the last comment.
Are there any updates?

**Comment by jil-jeep** [comment]
yea

**Comment by JimmyCushnie** [comment]
The update is that they closed the issue, and apparently don't think there's a problem anymore.

Github Desktop is so frustrating, everything about it is great except for this ONE giant glaring missing feature.

**Comment by cloewen8** [comment]
Re-read the problem, and looking at my list of repositories, it is still a problem.
I've had to adapt by avoiding features that would create repositories with similar or identical names (namely wikis and partially branches).

**Comment by JimmyCushnie** [comment]
I've thought of a solution. If I make a second github account called `___________JimmysPinnedRepos`, and I move all my important repos to that account, they will stay at the top of the list.

The only downside is that it would be fucking stupid

**Comment by steveward** [comment]
@JimmyCushnie I've edited your comment to remove profanity, and it is considered to be a violation of the [GitHub Desktop Code of Conduct](https://github.com/desktop/desktop/blob/development/CODE_OF_CONDUCT.md). You may consider this an official warning.

**Comment by kuro68k** [comment]
Given that this is closed I think we can take it that there is no intention to improve the app in this aspect. Which is of course fine, it can be a simple app for low end users with only a small number of repositories.

**Comment by steveward** [comment]
@kuro68k please only comment with feedback that is beneficial to GitHub Desktop's community -- consider this is a warning. If an issue is closed it does not mean that we will not reconsider changing things going forward, it just means it is not something the team is not currently focused on.

**Comment by amcgregor** [comment]
Difficult to have positive, beneficial feedback on something that is out of our own control to correct and has seemingly been put on ice, and furthermore is now approaching **three years in age**.  Is throwing a screenshot up demonstrating the uselessness of the current arrangement beneficial?

![repositories](https://user-images.githubusercontent.com/76750/94564000-72f34580-0235-11eb-9fd4-8671d575aef9.png)

That represents one fifth of the total scrollable area for the repository listing, and is notable in the use of prefix namespacing. (Which can be elided similar to multiple depths of folder inclusion and used for automatic grouping.)  It's almost unusable as-is, barring the auto refreshing problem, which makes it **completely** unusable, ref #1128 which I sincerely hope does not end up the way this issue did.

⌘T and jumping to a repository by filtering is _almost_ acceptable, but that completely ignores the "design" of that sidebar in favour of Vim-like CtrlP motion.  If I want that, I can stay within Vim, CtrlP is good people, and there is extensive and excellent Git integration available for that editor.  The only purpose for which I formerly had used GitHub Desktop is now easily accomplishable there, that is, marking subset hunks of a file for commit vs. committing the whole file, and lets me unify project management and manipulation under a single environment. And avoid mouse-based wrist hurt disease while doing so.

**Comment by kuro68k** [comment]
> @kuro68k please only comment with feedback that is beneficial to GitHub Desktop's community -- consider this is a warning. If an issue is closed it does not mean that we will not reconsider changing things going forward, it just means it is not something the team is not currently focused on.

@steveward I have reported this comment as a COC violation. You might consider revising it. There is no need for this kind of hostility, I was explaining the situation in neutral language in order to de-escalate. Please be aware that it can be difficult to infer tone from text comments so you should usually assume good faith where possible. Unfortunately your comment is unambiguously hostile and unwelcoming.

**Comment by steveward** [comment]
@kuro68k saying that GitHub Desktop "can be a simple app for low end users with only a small number of repositories" is not helpful feedback and goes against [Our Standards](https://github.com/desktop/desktop/blob/development/CODE_OF_CONDUCT.md#our-standards), which is why I issued a warning. 

I appreciate the feedback and enthusiasm everyone has shared for us to make changes to the repository list, but I am going to lock this issue for the time because the discussion is starting to stray away from that.
