### ISSUE TITLE
Why there isn't repo browser function?

### ISSUE THREAD

**Issue by TerryChan** [desktop/desktop#6491]
Why there isn't repo browser(or call it repo file explorer) function that we can view the whole files/contents of a repo, currently we can only view the changed files/contents. Will you add this feature(repo browser) in GitHub Desktop?

**Comment by billygriffin** [comment]
Hi @TerryChan, thanks for the idea. As of now we don’t have any intention of adding this to GitHub Desktop and we think it exists nicely elsewhere (via Finder/Explorer and a user’s chosen editor). So I’m going to close this issue to reflect that. However, I’d love to understand how you would use this feature and why it’s not working well for you at present? Under what circumstances would you want to browse the present state of a repo in Desktop instead of in your editor or Explorer/Finder? Thanks!

**Comment by TerryChan** [comment]
Thanks for you reply @billygriffin 
I want to do some git action on the files, such as view the change history of a spcified file like below, so that I can know more about the change history of the file.
![image](https://user-images.githubusercontent.com/5396286/50464403-81129300-09cb-11e9-98d3-0f571453ff60.png)

**Comment by billygriffin** [comment]
Thanks @TerryChan! That’s really helpful context. We’re definitely tracking an issue somewhere that is looking at history of lines, files, etc. I’m on my phone now and wasn’t able to find it offhand, but I’m glad that’s tracked elsewhere and we’re open to considering something like that. Thanks again!
