### ISSUE TITLE
Browser authentication was disturbed by TortoiseGit

### ISSUE THREAD

**Issue by TerryChan** [desktop/desktop#6492]
## Description
When I use browser authentication in GitHub Desktop, the browser tried to launch TortoiseGit client instead of GitHub Desktop after the authentication of browser. It can be authenticated by browser successfully before I install TortoiseGit. I tried to launch GitHub Desktop many times to verify this issue, all reproduced. My browser is Chrome.

## Version
* GitHub Desktop:
v1.5.1
* Operating system:
windows 10

## Steps to Reproduce
1. install GitHub Desktop 1.5.1
2. launch GitHub Desktop
3. authenticate in browser - succeed
4. install TortoiseGit
5. sign out in GitHub Desktop
6. close GitHub Desktop
7. launch GitHub Desktop (repeat many times)
8. click File-Options-Accounts-Sign in(GitHub.com)-sign in using your browser-authorized

### Expected Behavior
the browser launch GitHub Desktop

### Actual Behavior
the browser tried to launch TortoiseGit client (the browser show popups as below):
![image](https://user-images.githubusercontent.com/5396286/50447549-d6f92380-0956-11e9-9080-47ce893337d9.png)

## Additional Information
I found the "x-github-client" protocal was registered by TortoiseGit in Control Pannel:
![image](https://user-images.githubusercontent.com/5396286/50447578-19bafb80-0957-11e9-9006-6b6c75b6ba4c.png)

**Comment by steveward** [comment]
Thanks for the report @TerryChan. This issue was previously reported in https://github.com/desktop/desktop/issues/4754, and @shiftkey determined that this was a problem on TortoiseGit's end of things. There was also an [issue opened in the TortoiseGit issue tracker](
https://gitlab.com/tortoisegit/tortoisegit/issues/3215) about this. I would recommend bumping that issue up to see if the TortoiseGit developers have any updates about fixing this.

I'm going to close this issue out, but let us know if there is anything we can help out with in regards to this issue from our end.
