### ISSUE TITLE
Account used to commit does not change with global setting

### ISSUE THREAD

**Issue by darkenergy100** [desktop/desktop#6528]
## Version
* GitHub Desktop:
1.5.1
* Operating system: Microsoft Windows
[Version 10.0.17763.195]

## Steps to Reproduce
1. log into an account
2. clone a repo from another account
3. log out of the first account, and into the account that owns the cloned repo
4. commit changes

### Expected Behavior
The commit would be made with the currently logged in account

### Actual Behavior
The commit is always made with the first account

## Additional Information
The application seems to be stuck with the first account as the author, even after deleting and re-cloning the remote repo under the second account

### Logs
[2019-01-03.desktop.production.log](https://github.com/desktop/desktop/files/2722599/2019-01-03.desktop.production.log)

**Comment by steveward** [comment]
Thanks for opening this @darkenergy100.

This issue is due to the fact that the name and email address in your `.gitconfig` file still point to the initial user account you logged in to GitHub Desktop with. When you first launch GitHub Desktop, we help you to sign in to your GitHub account, and after that we pre-fill the Git configuration information (for committing) using the name and email address from your GitHub account. From there, any time you create commits in Desktop, they will have this name and email address attached to them. You can read more about this in our [help article](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/).

We don't do any extra work to update your Git configuration if you happen to change accounts. As a workaround you can directly update your Git configuration by going to the File menu and selecting `File` > `Options` > `Git`. You can follow along in https://github.com/desktop/desktop/issues/610 for updates about a feature that would warn users who are committing with an email address that is not associated with their current account.

I'm going to close this issue out since we have plans to improve this in #610, but let me know if you have any further questions.

**Comment by darkenergy100** [comment]
I updated my email and name in File > Options> Git, but it is still committing using the settings of the other account.
