### ISSUE TITLE
How does GitHub Desktop use the credentials after oauth?

### ISSUE THREAD

**Issue by TerryChan** [desktop/desktop#6533]
I'm reading the source code of GitHub Desktop, but I'm very confused on how GitHub Desktop use the credentials to execute git commands like clone/pull if I authenticated with oauth?
The scenario is after I autheicated with oauth, I clone a repo in my repo list, it didn't ask me to input username and password, and cloned successfully, I guess it used the access token which got from the oauth, is that right? Can it use the access token to execute git command?
And, when I do the clone action, I didn't find it execute the ask-pass-trampoline.bat and ask-pass.ts(I added my trace log in them). Anybody know why it didn't execute them, but it can pass the authentication of git? Can you show me the source code on how it pass the authentication? Thanks in advance.

**Comment by shiftkey** [comment]
@TerryChan thanks for the interest!

> The scenario is after I autheicated with oauth, I clone a repo in my repo list, it didn't ask me to input username and password, and cloned successfully, I guess it used the access token which got from the oauth, is that right?

The access token that GitHub Desktop gets after completing the OAuth flow is stored in the OS credential store (Keychain on macOS, Credential Manager on Windows) and then retrieved when the Git operation requests it. The rest of it is a bit complex, but I'll try and describe the rest of the flow here.

While most users will setup a credential manager for their command line Git, Desktop uses the AskPass protocol that Git also supports. We do this for a couple of reasons:

 - Desktop can authenticate without relying on your existing credential manager settings (you may not have this setup)
 - Desktop can avoid overwriting any saved credentials you might already have in your credential manager

The relevant setup for this is the environment variables in here:

https://github.com/desktop/desktop/blob/04052c3d1af857eb55ed51be0b5ef06acc470fdb/app/src/lib/git/authentication.ts#L7-L14

`GIT_ASKPASS` allows us to set a program that Git will launch **when it is challenged to authenticate by the remote server**. This context matters, because not all Git network operations require authentication (cloning a public repository won't trigger the authentication challenge, for example).

If the Git operation needs to authenticate, it'll invoke the trampoline script we set as an environment variable earlier.

https://github.com/desktop/desktop/blob/04052c3d1af857eb55ed51be0b5ef06acc470fdb/app/static/win32/ask-pass-trampoline.bat#L1-L9

 It'll invoke it twice (first to request a username, then to get a password) - this is the same flow that Git will perform on the command line if you don't have your credential manager configured.

The trampoline script (we call it a "trampoline" because it's only purpose is to pass context back to the Desktop application and workaround limitations with the `GIT_ASKPASS` protocol) is setup to run the `ask-pass.js` which passes the account name (set as an environment variable) and the access token (read from the OS credential store) to Git.

https://github.com/desktop/desktop/blob/04052c3d1af857eb55ed51be0b5ef06acc470fdb/app/src/ask-pass/main.ts#L1-L13

> And, when I do the clone action, I didn't find it execute the ask-pass-trampoline.bat and ask-pass.ts(I added my trace log in them)

All this work occurs in a separate process, which is running as plain Node process rather than Electron, so you won't be able to debug this in the renderer, and instead need to [enable Node debugging](https://nodejs.org/en/docs/guides/debugging-getting-started/). You can see the process launch on Windows using a tool like [`procmon`](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) if you don't care about live debugging.

>  Anybody know why it didn't execute them, but it can pass the authentication of git? Can you show me the source code on how it pass the authentication? 

A few reasons come to mind about why you won't be able to see this:

 1. you're working with an SSH remote (that's a different setup to how authentication works with HTTP remotes)
 2. Git will only invoke the `GIT_ASKPASS` program when it receives a `401 Authentication Required` from the remote, and public repositories will let you clone and fetch/pull without authenticating
 3. you haven't configured Node to break into the debugger when invoking the `ask-pass.js` script

I was able to test this on macOS by doing this:

  - pass `--inspect-brk` with the trampoline script [(docs here)](https://electronjs.org/docs/tutorial/debugging-main-process)
  - build and run the development mode app
  - open my Chrome browser's Dev Tools
  - run an operation that needs authentication, see the Node icon light up in the top-left

<img width="272" alt="screen shot 2019-01-03 at 12 59 59 pm" src="https://user-images.githubusercontent.com/359239/50650704-99e4f080-0f57-11e9-93bd-b40445090fef.png">
 
 - click the Node icon to debug into the minified `ask-pass.js` script (or `.ts` file if you prefer)

<img width="841" src="https://user-images.githubusercontent.com/359239/50650777-d31d6080-0f57-11e9-8561-d81b8da32d77.png">

The steps should be similar for Windows.

**Comment by TerryChan** [comment]
@shiftkey Thanks very much for your detailed explanation, it's very helpful.

> It'll invoke it twice (first to request a username, then to get a password) - this is the same flow that Git will perform on the command line if you don't have your credential manager configured.

> The trampoline script (we call it a "trampoline" because it's only purpose is to pass context back to the Desktop application and workaround limitations with the GIT_ASKPASS protocol) is setup to run the ask-pass.js which passes the account name (set as an environment variable) and **the access token** (read from the OS credential store) to Git.

But I still have a question, can it work to pass the access token to Git which need a password? And how it works with the access token which need a password? Is there any doc on this?
![image](https://user-images.githubusercontent.com/5396286/50673457-cf054780-1018-11e9-826b-c3bef8107f13.png)
You can see when it reqeust a password(the prompt is "Password for ... :"), we returned the access token to Git.
Sorry for I didn't have a private github repo to verify it, I just used another git server to verify it, but it didn't pass the authentication with the username and token returned when I do clone.
Thanks again for your reply!

**Comment by TerryChan** [comment]
After spend some time to investigate, I think I found the answer of my question above, so let me answer it.

Yes, we can use the oauth token instead of username&password to do clone/push/pull operations which need authentication. [This doc](https://blog.github.com/2012-09-21-easier-builds-and-deployments-using-git-over-https-and-oauth/#using-oauth-with-git) described the ability. And I think gitlab and bitbucket also have the ability: [gitlab](https://gitlab.com/gitlab-org/gitlab-ce/commit/54f6d8c7b5a1c67a222011c35ad70909da0e686d), [bitbucket](https://developer.atlassian.com/cloud/bitbucket/oauth-2/)

**Comment by shiftkey** [comment]
@TerryChan yes, the access token can be used in place of a password for GitHub remotes.

**Comment by shiftkey** [comment]
I'm going to close this out as it looks like your questions have been answered! Thanks again @TerryChan!
