### ISSUE TITLE
Add Hide Button on Merge Conflict Popup

### ISSUE THREAD

**Issue by fr-irene** [desktop/desktop#6571]
**Please describe the problem you think should be solved**
If I merge develop branch to my current branch, and it has some conflict, then the popup always shows. I want to see the diff after the changes, or I want to discard what I changed in local. But I can't do anything because the popup is always there until I merge the conflict.

I hope the Popup can be hidden. Or there is a setting to disable Merge Conflict Popup.

**Comment by shiftkey** [comment]
@fr-irene thanks for the report!

In https://github.com/desktop/desktop/pull/6382 we made the merge conflicts dialog dismissable, so that you could close the dialog and see the changes. Are you running version 1.5.1 of GitHub Desktop? That version should support what you are looking for:

 - Close the merge conflicts dialog

<img width="527" alt="screen shot 2019-01-10 at 9 31 08 am" src="https://user-images.githubusercontent.com/359239/50971674-01042700-14bb-11e9-864e-8d376dfcee8a.png">

 - While you're in the middle of a merge, you'll see this banner that guides you back to confirming everything has been resolved

<img width="519" alt="screen shot 2019-01-10 at 9 34 28 am" src="https://user-images.githubusercontent.com/359239/50971673-01042700-14bb-11e9-8d8b-e955a5221d55.png">

**Comment by shiftkey** [comment]
Closing this out because I believe the current version already addresses the feedback. @fr-irene if you have any further questions, please let us know.
