### ISSUE TITLE
Consistenency when navigating to filters and text fields

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#6585]
When selecting Branch > Compare to Branch menu option the user is taken to a blank compare branch filter, however if the user is already on that tab and the field is currently populated, then selecting that menu option will still clear the filter. This may be intended, but the behavior is not consistent with other parts of Desktop. 

For instance, if the same action were performed when selecting View > Go to Summary, any pre-populated text is retained and the cursor appears after the text. 

Thoughts? Bug? Not worth fixing? 

1.6.0-beta1, mac

**Comment by shiftkey** [comment]
> When selecting Branch > Compare to Branch menu option the user is taken to a blank compare branch filter, however if the user is already on that tab and the field is currently populated, then selecting that menu option will still clear the filter. 

@iAmWillShepherd I'd love your input on the intent here

**Comment by iAmWillShepherd** [comment]
Full-disclosure that I've forgotten many of the details of the comparison feature, but I believe I cleared the textbox because I felt that a user clicking that button would likely be doing it with the intent to do a new comparison. Once the comparison is made, we continue to show ahead/behind info until the compare is completed. Since we continue to show the comparison, I thought clearing it to start a new one made sense.

**Comment by tierninho** [comment]
Closing this as it has not come up enough times to be validated as a real problem.
