### ISSUE TITLE
Publish button in new onboarding section does not activate

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#6598]
The Publish button in the new onboarding section is disabled, despite the top nav Publish button being active. I expect the button to be active.

Repro:
- Add new repo
- Try to click the blue Publish button (class="blankslate-action primary")

![image](https://user-images.githubusercontent.com/14828183/51062505-f5445d80-15ab-11e9-8307-fe4a2855fa08.png)

1.6.0-beta2, WIndows 10

**Comment by billygriffin** [comment]
This feels like pri-2 to me, as it likely introduces confusion for something that feels very first-class.

**Comment by billygriffin** [comment]
Actually, I was able to click it but was not able to activate it on hitting `Enter`

**Comment by niik** [comment]
This happens because we don't have a dedicated 'Publish' repository menu item, only a 'Push' which enables both. The action is backed by the menu so as long as the menu item is disabled the action will be as well. So apparently we don't have a way of publishing a repository using only the menu. I'll look into it
