### ISSUE TITLE
submodule not found when building project

### ISSUE THREAD

**Issue by kingov** [desktop/desktop#6618]
when i run "yarn buid:dev"    appear   no such file or directory

Building for development…
Removing old distribution…
Copying dependencies…
  Installing dependencies via yarn…
  Installing 7zip (dependency for electron-devtools-installer)
  Copying git environment…
  Copying app-path binary…
Packaging emoji…
Error: ENOENT: no such file or directory, lstat '/Users/wangzheng/code/electron/desktop-release-1.5.1/gemoji/images/emoji'
    at Object.fs.lstatSync (fs.js:941:11)
    at /Users/wangzheng/code/electron/desktop-release-1.5.1/node_modules/graceful-fs/polyfills.js:297:22

**Comment by tierninho** [comment]
@kingov thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by shiftkey** [comment]
@kingov did you download the repository rather than clone it? That path is to submodule which might not be created as part of our usual flow because of how Git works.

Are you able to clone the Desktop repository and try it again?

```shellsession
$ git clone https://github.com/desktop/desktop desktop-latest
$ cd desktop-latest
$ yarn
$ yarn build:dev
```
