### ISSUE TITLE
Fix pointy corners on the commit description box

### ISSUE THREAD

**Issue by j-f1** [desktop/desktop#6635]
See #6234 — that fix broke autocomplete popups, so this has to be done a different way.

**Comment by lisavogtsf** [comment]
Where "pointy corners on the commit description box" refers to this (as detailed more thoroughly in #6234)
![image](https://user-images.githubusercontent.com/7121497/52170458-a3e94300-26ff-11e9-88a4-5239976eb6d7.png)

The problems with autocomplete popups that arose from the attempted fix in #6234 (adding overflow: hidden;) are detailed in #6459.

I am looking into taking this on, but I need to understand the expected behavior of the autocomplete popups first. Also I wasn't sure what pointy corners meant, hence the looking around at other issues and PRs.

**Comment by j-f1** [comment]
Sorry about that — I should’ve been more clear. In this case, setting the `border-radius` of the text area would probably work.

**Comment by lisavogtsf** [comment]
Ok, I was kind of thinking of writing a test or two around the autocomplete so we wouldn't be able to break it again without knowing. But I'll see about border-radius :)

**Comment by lisavogtsf** [comment]
@j-f1 @outofambit 
I made a border-radius adjustment that seems to help with the pointy corners. 
![image](https://user-images.githubusercontent.com/7121497/52189236-24856d80-27ec-11e9-95f2-e524375c87df.png)
![image](https://user-images.githubusercontent.com/7121497/52189239-2a7b4e80-27ec-11e9-842e-f21e8fd716c1.png)

I can't get the autocompletion behavior to work at all, even in Github Desktop 1.6.1, so I can't tell whether this would affect it.
