### ISSUE TITLE
git bash doesn't use same credentials as GUI for Enterprise - problem for LFS

### ISSUE THREAD

**Issue by JoFAM** [desktop/desktop#6642]
## Description

I stumbled upon this when trygin git-lfs. I use Github Desktop for most of my work, as we have quite a few people and students not familiar with git. To use lfs however, we need to use the bash. 

I have a git version with bash installed, but that one doesn't use the credentials as used by the GUI Github Desktop. This means that if I click "Open in bash" and try a simple git pull, I get an authentication error. 

I am aware I can get around this by also configuring my other git installation to access both github.com and our own enterprise. It would be nice though to have a better solution so I don't have to solve all authentication issues on our students' computers.

## Version

* GitHub Desktop: 1.5.1

* Operating system: Windows 10

## Steps to Reproduce

1. Install Github Desktop
2. install git for Windows
3. set up credentials for Github.com in Github Desktop
4. Clone repository from Github Desktop
5. Click on Repository > Open in git Bash
6. try `git pull`

### Expected Behavior

Success

### Actual Behavior

Following error:

remote: Invalid username or password.                                            
fatal: Authentication failed for 'https://github.xxxxx.xx/orgname/reponame.git/'

--

### Logs

[2019-01-16.desktop.production.log](https://github.com/desktop/desktop/files/2764756/2019-01-16.desktop.production.log)

**Comment by outofambit** [comment]
Hi @JoFAM! Thanks so much for this excellent write up. I'm going to mark this as an enhancement for now. @desktop/product what are your thoughts on this?

**Comment by shiftkey** [comment]
> To use lfs however, we need to use the bash.

@JoFAM I'd love to hear more about what LFS actions you are doing that require dropping into the command line. 

GitHub Desktop should support committing and push/pull/fetch operations for LFS-enabled repositories with the credentials stored in Desktop, but if there's other tasks you are doing that aren't possible within the app I'd love to ensure we're aware of them and tracking them on our end.

**Comment by shiftkey** [comment]
> It would be nice though to have a better solution so I don't have to solve all authentication issues on our students' computers.

There's some extra context here that will affect what our options are.

To "remember" your Git credentials there is typically a credential manager configured. GitHub Desktop consciously avoids the credential manager so that it doesn't interfere with your current setup (the last time I looked in this area I believe I saw Git implicitly erasing credentials if authentication failure happened because the credentials didn't work).

Instead Desktop uses the `GIT_ASKPASS` protocol to provide the required information using credentials it maintains.

If we go down this path of sharing credentials with programs outside of Desktop, we get into the business of: 

 - ensuring users have a credential manager installed and configured
 - dropping our `GIT_ASKPASS` implementation to use a credential manager
 - ensuring that we don't overwrite existing credentials after signing in
 - potentially using credentials generated by another program that don't have access to what Desktop needs (Personal Access Tokens have [scopes](https://developer.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/) that control what they can access)

While sharing credentials between Git installations sounds like a simple proposition, I'd first prefer to identify the underlying motivation for why users are leaving the Desktop UI to perform LFS actions because that might be easier to address than changing how the app manages credentials.

@JoFAM are you able to share more details?

**Comment by shiftkey** [comment]
Putting this back to `user-research` so we can understand more about the LFS usage

**Comment by JoFAM** [comment]
> 
> 
> > To use lfs however, we need to use the bash.
> 
> @JoFAM I'd love to hear more about what LFS actions you are doing that require dropping into the command line.
> 
I can `git pull` to get the hash references, but I need to go to the bash to do `git lfs pull` to download the actual files. And that's where I need to set up my own git installation with the right credentials, as it won't download the files otherwise.

So if I can get around the bash to download the actual files from a repo I cloned, the problem is solved as well. Note that this occured when I cloned an existing repo as opposed to set up my own. If I need to test additional scenarios, I can devote some time to that next week.

Cheers
Joris

**Comment by shiftkey** [comment]
@JoFAM thanks for that extra context. We ship Git LFS inside Desktop, and should be asking you to initialize the repository for Git LFS if it detects rules in your `.gitattributes` (see dialog in https://github.com/desktop/desktop/pull/2619). This installs the hooks that Git LFS needs:

```
$ ls .git/hooks | grep -v ".sample"
post-checkout
post-commit
post-merge
pre-push
```

Ideally those hooks (which run before or after specific Git commands) should then invoke the necessary Git LFS operations, but maybe something is missing?

We want things to just work so that you don't need to do manual Git LFS operations, but maybe we need to do some more work in the app. We should retest the flow you've talked about above involving `git pull`.

**Comment by Arlen22** [comment]
This doesn't actually solve the underlying problem, unfortunately, which is that GitHub desktop does not support all the git commands (nor could I expect it to, that would be awful). But I would like to source the GitHub desktop credentials into the shell for just one session, or in some other way tell git to use the github desktop credentials using an environment variable if that's possible. 

For instance, I need to update my branch on GitHub using `git push --force origin master` because I need to reset it, and it's just easier to use the credentials.

**Comment by steveward** [comment]
Closing this out since as was mentioned GitHub Desktop does provide Git LFS support, and at this time we don't have any plans integrate GitHub Desktop's credentials with the command line.
