### ISSUE TITLE
Commit hashes are too short for large repos

### ISSUE THREAD

**Issue by danpalmer** [desktop/desktop#6662]
**Problem**

Commit hashes in the app are 7 characters. This is insufficient for larger repos where collisions become more common. Git adapts some of its reporting over time to larger repos, it would be great if GitHub Desktop could too.

**Potential Solution**

I mostly use the commit hashes by copying/pasting from the UI. A possible solution would be to have a copy button/on-click handler on the commit hash that copies the full hash. A full hash causes no issues for me, or that I can imagine in general, but removes any ambiguity.

**Comment by danpalmer** [comment]
@shiftkey Great, thanks for the quick response! Delegating this responsibility to Git sounds like a great idea.

**Comment by shiftkey** [comment]
Here's a rough sketch of the changes that I think need to be made here.

First, the easy thing to would be to just add a new field to the model for `shortSha`:

```diff
diff --git a/app/src/models/commit.ts b/app/src/models/commit.ts
index bdaefc327..9700e22f1 100644
--- a/app/src/models/commit.ts
+++ b/app/src/models/commit.ts
@@ -65,6 +65,7 @@ export class Commit {
    */
   public constructor(
     public readonly sha: string,
+    public readonly shortSha: string,
     public readonly summary: string,
     public readonly body: string,
     public readonly author: CommitIdentity,
```

And then using that in the `CommitSummary` component:

```diff
diff --git a/app/src/ui/history/commit-summary.tsx b/app/src/ui/history/commit-summary.tsx
index 049407964..f73ecd5c1 100644
--- a/app/src/ui/history/commit-summary.tsx
+++ b/app/src/ui/history/commit-summary.tsx
@@ -292,7 +292,7 @@ export class CommitSummary extends React.Component<
     const fileCount = this.props.files.length
     const filesPlural = fileCount === 1 ? 'file' : 'files'
     const filesDescription = `${fileCount} changed ${filesPlural}`
-    const shortSHA = this.props.commit.sha.slice(0, 7)
+    const shortSHA = this.props.commit.shortSha
 
     const className = classNames({
       expanded: this.props.isExpanded,
```


Introducing this new field will raise a whole bunch of compiler errors, but the important places are where we create these `Commit` models from Git output.

`git for-each-ref` is how we get the list of branches together, and we already have a neat way to get the pieces of data that we want out of it using `--format`, so inserting a new field for the abbreviated SHA and reading it out later is easy:

```
diff --git a/app/src/lib/git/for-each-ref.ts b/app/src/lib/git/for-each-ref.ts
index c8b69f87f..03dd0c148 100644
--- a/app/src/lib/git/for-each-ref.ts
+++ b/app/src/lib/git/for-each-ref.ts
@@ -26,6 +26,7 @@ export async function getBranches(
     '%(refname:short)',
     '%(upstream:short)',
     '%(objectname)', // SHA
+    '%(objectname:short)', // short SHA
     '%(author)',
     '%(committer)',
     '%(parent)', // parent SHAs
@@ -76,7 +77,8 @@ export async function getBranches(
     const name = pieces[1]
     const upstream = pieces[2]
     const sha = pieces[3]
-
+    const shortSha = pieces[4]
+    // TODO: increment all the index lookups because 4 is now the new field
     const authorIdentity = pieces[4]
     const author = CommitIdentity.parseIdentity(authorIdentity)
 
@@ -99,6 +101,7 @@ export async function getBranches(
 
     const tip = new Commit(
       sha,
+      shortSha,
       summary,
       body,
       author,
```

Same thing inside `git log` which enumerates commits from inside the repository:

```diff
diff --git a/app/src/lib/git/log.ts b/app/src/lib/git/log.ts
index ea7965959..5abea3a66 100644
--- a/app/src/lib/git/log.ts
+++ b/app/src/lib/git/log.ts
@@ -69,6 +69,7 @@ export async function getCommits(
   const delimiterString = String.fromCharCode(parseInt(delimiter, 16))
   const prettyFormat = [
     '%H', // SHA
+    '%h', // abbreviated SHA
     '%s', // summary
     '%b', // body
     // author identity string, matching format of GIT_AUTHOR_IDENT.
@@ -117,6 +118,8 @@ export async function getCommits(
   const commits = lines.map(line => {
     const pieces = line.split(delimiterString)
     const sha = pieces[0]
+    const shortSha = pieces[1]
+    // TODO: increment all the index lookups because 1 is now the new field
     const summary = pieces[1]
     const body = pieces[2]
     const authorIdentity = pieces[3]
@@ -140,6 +143,7 @@ export async function getCommits(
 
     return new Commit(
       sha,
+      shortSha,
       summary,
       body,
       author,
```

You might note in here that I've chosen a specific place inside the formatter to add these, rather than adding them to the end. I chose this approach to keep the structure in place, with the trailers at the end of each formatted row. But this requires incrementing every subsequent value in the array, and the parsing will likely break if you don't do this.

Once those are updated, there are some tests and other places that need to be updated. And then you can run `yarn test:unit` to verify the Git tests :metal:

**Comment by danpalmer** [comment]
Just saw this update. Thanks again to @say25 and @shiftkey!

**Comment by pajenterprisesllc** [comment]
hello teams welcome help is here
