### ISSUE TITLE
Endless spinning of "Switching to Branch" button

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#6701]
The Switching to Branch button spins forever as it got stuck after publish a repository and then switching branches right away. I cannot click the branch button and see the branch list because of this. 

Reproduce:
- make new repo, don't publish
- make new branch and switch to new branch
- publish repo and immediately switch to another branch (be quick!)

![image](https://user-images.githubusercontent.com/14828183/51644349-b8ba1f80-1f24-11e9-9559-ac9264f27f1c.png)

Should we lock branch switching when a repo is being published? Note, you can escape this but you have to quit the app or publish a new branch.

Nothing in the logs. Labeling a P3 as it is unlikely to be reproduced anytime soon.

1.6.2-beta0, mac

**Comment by tierninho** [comment]
Closing this as it has not come up enough times to be validated as a real problem.

**Comment by barloff-sd** [comment]
I still get this problem in `2.5.3` when simply switching branches.  In one instance I was expecting it to ask me to stash my changes or bring them with me.  It instead did not and is stuck looping between the branches in the "Current Branch" dropdown - making it unusable.  The biggest problem is that even if uninstall and reinstall, the problem remains when I try to switch to the branch that originally caused the error.  I have run into this several times, in past cases I have worked around it by deleting the problematic branch because there was little changes, but this happening switching to `master` makes the workaround impossible.

**Comment by tierninho** [comment]
@barloff-sd Thanks for the report. Did you experience this (see the gif) https://github.com/desktop/desktop/issues/9297?

**Comment by barloff-sd** [comment]
Yes, thank you.  I couldn't find an open ticket for it.

**Comment by SandraSilvaDavis** [comment]
When I go to publish my branch it just gets stuck in an eternal spinning wheel and nothing gets added to my GitHub.
<img width="419" alt="Screen Shot 2022-09-27 at 11 24 26 AM" src="https://user-images.githubusercontent.com/113466967/192594847-59bece0d-828d-436c-88ad-b9ad98d31585.png">

**Comment by steveward** [comment]
@SandraSilvaDavis if you can share your log file I can take a look to see what the issue might be.

To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
