### ISSUE TITLE
I see a bug when use GitHub Desktop

### ISSUE THREAD

**Issue by kiendinhkhoi** [desktop/desktop#6711]
## Version

* GitHub Desktop:

* Operating system:

### Logs

When i change my github username, i cant push commit until i sign out and sign in again <3

**Comment by steveward** [comment]
Thanks for the report @kiendinhkhoi. This is similar to #6453, which is about when a password changes.

> When i change my github username, i cant push commit until i sign out and sign in again <3

This is because the token that is stored by GitHub Desktop when you authenticate with your GitHub account is associated with a specific username and password. You can see that in the log file:

`2019-01-25T14:55:25.974Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: desktop - steveward (has token)`

When your username or password changes you will need to authenticate again to regenerate a new token associated with the new name. 

I will make a note of mentioning this in a 'common problems' document I'm working on putting together that walks through how to resolve common authentication problems. We're also planning to provide better clarity around these errors, along with an easy way of letting users quickly jump to the `Accounts` view to authenticate again. You can follow along in https://github.com/desktop/desktop/issues/6453 for updates about that. I'm going to close this issue out in favor of #6453, but please let us know if you have any further feedback!
