### ISSUE TITLE
32 бин есть githab? а то у меня не грузит 64 бин банка на 32

### ISSUE THREAD

**Issue by Danisca121** [desktop/desktop#6716]
## Version

* GitHub Desktop:

* Operating system:

**Comment by iAmWillShepherd** [comment]
Thanks for reaching out!

We require the template to be filled out when submitting all issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway 😀
