### ISSUE TITLE
Unreal Engine 4 Project not uploading all files

### ISSUE THREAD

**Issue by PrecursorsLegacyDev** [desktop/desktop#6723]
## Version

* Operating system:
Windows 10

## Steps to Reproduce

1. I make a new repository on google chrome
2. I connect to the repository on the desktop app
3. I publish to source
4. Half of my files are missing

### Expected Behavior
I expected to upload all of the files in my folder for the desktop app

### Actual Behavior
It only uploads a few and leaves the main ones un-uploaded

## Additional Information
This is for an Unreal Engine 4 project so every file counts... I need them uploaded and so far, your service isn't doing a good job

**Comment by steveward** [comment]
Thanks for the report @PrecursorsLegacyDev. 

Is it possible that these project files are being ignored in the .gitignore file in the root of your repository? There's a recommended .gitignore file for Unreal Engine 4 that ignores quite a few files, since they are not recommended to be stored in version control:

https://github.com/github/gitignore/blob/master/UnrealEngine.gitignore

You can view the list of currently ignored files by going to the menu in GitHub Desktop and selecting `Repository` > `Repository Settings` > `Ignored Files`. Let me know if that's the case.

**Comment by billygriffin** [comment]
@PrecursorsLegacyDev Thanks for the issue! Since we haven't heard back, I'm going to close this issue, but please feel free to reach back out if @steveward's suggestion didn't work.
