### ISSUE TITLE
GitHub lets you version your code, collaborate with others, and share what you’ve built with the world. We’re excited to see what you make.

### ISSUE THREAD

**Issue by SosHakobyan** [desktop/desktop#6750]
S

**Comment by shiftkey** [comment]
@SosHakobyan thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
