### ISSUE TITLE
Authentication Failed after adding an existing repo

### ISSUE THREAD

**Issue by FerretedHeart** [desktop/desktop#6754]
## Description

I installed GitHub Desktop and added an existing repo from my hard drive which was already an existing git repo as using git bash works fine. However, I get an authentication failed error when I try to fetch, even though it recognizes recent changes and commits.

## Version

* GitHub Desktop:
Version 1.6.1

* Operating system:
Microsoft Windows 10 Enterprise

## Steps to Reproduce

1. Install GitHub Desktop
2. Connect to GitHub Enterprise repo
3. File - Add local repository
4. Choose existing repo on the local drive
5. Click on Fetch

### Expected Behavior

I expect for the repo to fetch from origin and update the repo.

### Actual Behavior

I get the following error:
Authentication failed. You may not have permission to access the repository or the repository may have been archived. Open options and verify that you're signed in with an account that has permission to access this repository.

### Logs

[2019-01-31.desktop.production.log](https://github.com/desktop/desktop/files/2817904/2019-01-31.desktop.production.log)

**Comment by steveward** [comment]
Thanks for contributing @FerretedHeart. It looks like you are using SSH with this specific repository, but GitHub Desktop is not able to find a valid key associated with your account:

```
git@ghe.coxautoinc.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

There are a couple of solutions to this:

1. Change your repository to use a HTTPS `origin` remote URL instead of SSH. You can do this in GitHub Desktop by going to the menu and selecting `Repository` > `Repository Settings` > `Remote`. Since you are using GitHub Enterprise it should look like `https://ghe.coxautoinc.com/<user>/<repo>.git`.

2. Set up GitHub Desktop to use your SSH key. If you already have an existing key then you may just need to make sure your key is [loaded into `ssh-agent`](https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/#adding-your-ssh-key-to-the-ssh-agent). Please note that you may need to follow [this workaround](https://github.com/desktop/desktop/issues/5641#issuecomment-421801704) in order to get SSH working on Windows.

Let me know if either of those solutions does not gets things working for you.

**Comment by FerretedHeart** [comment]
The first one is definitely not an option as it's my company repo.

I tried the suggestion on number 2. Although now I don't get the error message, fetching doesn't end. Progress, I suppose.

**Comment by steveward** [comment]
> The first one is definitely not an option as it's my company repo.

If you are using GitHub Enterprise then it should support both HTTPS and SSH, unless there is a specific rule in place requiring the use of SSH. You won't be changing anything about the repository on the server side. If you are logged in to GitHub Desktop with your GitHub Enterprise account you should be able to use HTTPS without issue.
