### ISSUE TITLE
Account switch problem

### ISSUE THREAD

**Issue by EverGreen7112** [desktop/desktop#6774]
## Version

* GitHub Desktop:

* Operating system:

### Logs

When I switch accounts to my team's account, I still see my own account's repositories.

**Comment by tierninho** [comment]
@EverGreen7112  thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
