### ISSUE TITLE
Highlight changes and unpushed commits in current repository

### ISSUE THREAD

**Issue by damieng** [desktop/desktop#678]
Jumping between repos a lot can mean unfinished or unpushed commits.  It would be great if the repository list could show that, e.g.

![image](https://cloud.githubusercontent.com/assets/118951/20501636/890ce0c0-afef-11e6-8ccd-1b909c419695.png)

**Comment by rlabrecque** [comment]
Just moving this over here from #1599:

This was my favourite feature of the old SourceTree which they got rid of when they killed their repository bookmarks sidebar. Just being able to see at a quick glance what the state of your repos is in. If you have uncommitted changes, or need to fetch changes was a part of my workflow that I had no idea how much I relied on it until it was gone.

It also displayed the branch the repo was on which was useful.

Example:
![image](https://cloud.githubusercontent.com/assets/2047188/26217805/f6a84662-3bc5-11e7-9ece-a01821d6c40c.png)

If most people don't really have many repos anyway then taking up an additional row for more information for each repo shouldn't be that big of a deal IMO. Then if this gets combined with 
Just moving this over here from #1599:

This was my favourite feature of the old SourceTree which they got rid of when they killed their repository bookmarks sidebar. Just being able to see at a quick glance what the state of your repos is in. If you have uncommitted changes, or need to fetch changes was a part of my workflow that I had no idea how much I relied on it until it was gone.

It also displayed the branch the repo was on which was useful.

Example:
![image](https://cloud.githubusercontent.com/assets/2047188/26217805/f6a84662-3bc5-11e7-9ece-a01821d6c40c.png)

If most people don't really have many repos anyway then taking up an additional row for more information for each repo shouldn't be that big of a deal IMO. Then if this gets combined with something like #1598 💯 💯 💯

**Comment by shiftkey** [comment]
I'm going to close this out because 1.3.0 is going to go out on Monday with #4770 enabled (already on the beta channel) which indicates the untracked changes, along with pending commits to push and pull for the current branch - basically what the first screenshot illustrated:

![](https://user-images.githubusercontent.com/6842965/40548790-fc3892e0-6035-11e8-80ea-ece1a11ec9f5.png)

@rlabrecque for the moment we're not really keen to clutter this area with more contextual information without more thought. We're also tracking a few requests about what to do in the repository sidebar so we'll combine those with the feedback we get from the new indicators and see what refinements should be undertaken.
