### ISSUE TITLE
Does not support x86 nor Arm-64 for install on for Windows WOS.

### ISSUE THREAD

**Issue by LivefromRaleighwood** [desktop/desktop#6785]
I thought MS purchased this company??? - So "why" does the desktop client not support x86 nor Arm-64 for install on for Windows WOS?

**Comment by shiftkey** [comment]
@LivefromRaleighwood thanks for the report! 

We talked about 32-bit Windows support in #1214 but [our data at the time](https://github.com/desktop/desktop/issues/1214#issuecomment-294834750) showed that the classic Desktop app was installed on a small percentage of the user base:

> FWIW it looks like we're currently holding pretty steady at 3% of our users on 32-bit only operating systems on Windows over the last month. 

I'm not aware of any technical blockers for Desktop to be built for x86 since our Git package is also build for Windows x86.

I've not looked at Windows on ARM64 support, and because we're an Electron app we're limited by what Electron itself can do. Please keep an eye on this discussion over on the Electron project: https://github.com/electron/electron/issues/9456

Once the Electron team supports Windows on ARM64, we can revisit what it would take to get Desktop and it's dependencies running on Windows on ARM64.

**Comment by shiftkey** [comment]
@billygriffin anything you'd like to add here?

**Comment by shiftkey** [comment]
Closing this out in favour of these issues:

 - #6874 for investigating building Desktop on x86
 - https://github.com/electron/electron/issues/9456  for Electron support for ARM64

**Comment by matze19999** [comment]
x86 builds exist and electron supports arm64 platform now.

**Comment by LivefromRaleighwood** [comment]
Per - https://desktop.github.com/ - only x64 and no ARM64.

**Comment by J-DubApps** [comment]
Bump.  I see no native support for Windows 10 or 11  ARM64 Desktops yet.    Is this still not the case?   Why does it run native on Apple Silicon ARM, and not Windows Native ARM yet?  What is the constraint?  Is a dependency missing etc?  There has to be a reason, in the near 3 years this issue was opened, that nothing has changed and you still  only have Intel x64 builds and virtually nothing else...
