### ISSUE TITLE
Add "Open in Shell" to actions on front page with no local changes

### ISSUE THREAD

**Issue by jlperla** [desktop/desktop#6786]
I *love* the new'ish feature showing things you can do in a repository with no local changes.

Conspicuously missing is the ability to Open in a Shell that you have in the other Advanced Configuration steps.  Any way to add that to the front page as well?

**Comment by billygriffin** [comment]
Hi @jlperla, we're so glad you like the new suggested next steps. The concept of opening in shell being included is something we considered but decided to leave out of the first version. We're planning to instrument metrics for the usage of each of the actions in an upcoming release, and at that point we'll decide whether we think it's a good idea to add this as well (or as a replacement for something else).

There is a keyboard shortcut for opening in shell, however, so if that's something you're doing frequently I'd definitely recommend using that (you can see it in the `Repository` menu).

Since it's not something we intend to support until we have more information, I'm going to close this issue. Thanks again for weighing in!
