### ISSUE TITLE
git: 'remote-https' is not a git command. See 'git --help'.

### ISSUE THREAD

**Issue by dhruvgandhi** [desktop/desktop#6787]
**Please describe the problem you think should be solved**
A clear and concise description of what the problem is and who else might be impacted. Screenshots are encouraged.

Example:

> “When I run into a merge conflict, I don’t know where to go to resolve it. Anyone who works off of multiple branches will likely run into this problem at least occasionally.”

**[Optional] Do you have any potential solutions in mind?**
A clear and concise description of one or more solutions you think might solve the problem. Please include any considered drawbacks or tradeoffs, and how users might use your solution(s). Screenshots or mockups are helpful here!

**Comment by billygriffin** [comment]
Thanks for the issue @dhruvgandhi! Would you mind filling out the bug report template with all the details so we can better diagnose what's going on? Since it'll be easier to just create a separate issue, I'll go ahead and close this one. Here's the template: https://github.com/desktop/desktop/issues/new?template=bug_report.md
