### ISSUE TITLE
Github desktop signin problem

### ISSUE THREAD

**Issue by kaster14** [desktop/desktop#6797]
On the github desktop app there are times where I need to make a commit from the company login. I go to file, options, then sign out, then sign in as the company account. The problem is that when I go to the changes tabon the mains screen and go to make a commit it still shows my personal account as making the commit (or at least shows my picture).

I find I also have to go to file, options, select the "git" tab, and change the information there to the company account, hit save, and then have to restart github desktop before the changes take place.

I would expect to be able to go to file, options, sign out, then sign in as the company profile and have commits immediately start being made from the company account without any further steps being needed.

This seems similar to issues #3066 and #610

**Comment by iAmWillShepherd** [comment]
Thanks for opening this @kaster14. This issue also feels fairly similar in nature to #2829. 

As a work around, you can modify your git configuration on a per repo level by using the following command in your repo of choice: `git config user.email <your_email>`. There should be no need to pass the `--local` option here since git will default to writing to config file of the repo it's working in. 

In the meantime, we will review this and related issues to figure out a nice path forward 👍

**Comment by billygriffin** [comment]
I'm going to close this issue in favor of #610 as we'd like to consider the full picture here. Thanks so much for the feedback @kaster14 and I'm going to paste your feedback into that issue.
