### ISSUE TITLE
Set conflict resolution tool

### ISSUE THREAD

**Issue by joshaber** [desktop/desktop#68]
Let the user select a conflict resolution tool that we can open for them.

**Comment by SurajGupta** [comment]
I'd like to make another pitch for an external diff tool.  I'm looking at the current product roadmap and the upcoming releases seem to tackle some pretty niche problems.  One of the most basic scenarios/needs of a version control system is determining what's changed before you commit.  It's no offense to this product, but the existing diff-view is just mediocre.  Often enough it's actually misleading because is over or under emphasizes the extent of the changes to a file.  That's no surprise, it's a hard problem and other companies have been focused on this space for over a decade.  It's gotten to point now where I don't even look at the diff in GitHub Desktop, I switch to Source Tree so I can quickly perform a UI driven External Diff.  I think y'all are underestimating the impact an External Diff feature would have from Day 1 of release.
