### ISSUE TITLE
Getting Exception while opening project in visual studio code : from github desktop

### ISSUE THREAD

**Issue by vishnudeotiwari** [desktop/desktop#6808]
```
Error: spawn C:\WINDOWS\system32\cmd.exe;C:\Program Files\Java\jdk8\bin;C:\Program Files\Java\jre8\bin ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

Version: 1.6.1
OS: Windows 10.0.17134
```

**Comment by shiftkey** [comment]
@vishnudeotiwari thanks for the report. Were you trying to launch the Command Prompt at the time?

I ask because we use the `COMSPEC` environment variable, if set, to launch it. 

https://github.com/desktop/desktop/blob/58ef7a70d2e331f67c18bf71e38280b07e1a4389/app/src/lib/shells/win32.ts#L51-L56

This environment variable is meant to be a single value representing the default command line interpreter, but in your case it seems to have multiple values.

**Comment by shiftkey** [comment]
> Were you trying to launch the Command Prompt at the time?

While this part wasn't part of the workflow from what I can understand, we changed the behaviour of some of the editors #6181 to launch some editors from a shell environment. VSCode was one of these.

From the NodeJS docs:

> `shell <boolean> | <string>` If `true`, runs command inside of a shell. Uses `'/bin/sh'` on UNIX, and **`process.env.ComSpec` on Windows**. A different shell can be specified as a string. See Shell Requirements and Default Windows Shell. Default: `false` (no shell).

@vishnudeotiwari you'll need to fix your `COMSPEC` environment variable to just be `C:\WINDOWS\system32\cmd.exe` to resolve this issue.
