### ISSUE TITLE
Autocomplete of filenames?

### ISSUE THREAD

**Issue by StefKors** [desktop/desktop#6852]
Currently there is a "Updated script.js" default message. I think it would be useful to be able to autocomplete/suggest filenames (and possibly function names?)

Would this is an easy thing to do for a first time contribution? If so I would like to give it a try

**Comment by shiftkey** [comment]
@StefKors thanks for the feedback! 

For reference, this feature came from #5240 and was implemented in #5389 and #6018 - please have a read of those links for more context about the feature. The goal here was to bring a similar experience to the app when making a change to one, coming from using the web editor on GitHub itself.

> I think it would be useful to be able to autocomplete/suggest filenames (and possibly function names?)

This feature was relatively straight-forward to implement because the use case was well-known and we had an existing implementation to refer to. It also doesn't do any auto-completing based on files - it's just special-casing that "one file to commit" scenario.

I'd love to hear more about the sorts of use cases you think would benefit from this feature.

**Comment by StefKors** [comment]
Thanks I'll have a read at the referenced issues. As for the use-case, I think that it would greatly improve writing and flexibility of the commit summary or descriptions for being specific about changes within files while reducing the effort, typo's. Especially if they have long file names. This has been a basic feature in code editors for a while now, and the commit messages a an logical extension

Also instead of "Create script.js" I would be easy to imagine a situation that non english user would like to use different words and or sentences thus increasing accessibility.

**Comment by shiftkey** [comment]
Moving this to `user-research` because I think we need to investigate the value of this to Desktop's workflows.

**Comment by steveward** [comment]
I'm going to close this out as it isn't something we've heard feedback about over the past few years. If it gets more interest in the future we can re-open.
