### ISSUE TITLE
Authentication failed. You may not have permission to access the repository...

### ISSUE THREAD

**Issue by pradeep-madheswaran** [desktop/desktop#6858]
Hi Team,

Please guide me how to resolve this issue...

## Version

* GitHub Desktop:

* Operating system:

**Comment by steveward** [comment]
Thanks for reaching out @pradeep-madheswaran!

Would you mind filling out the rest of the issue template so that we can better understand what is causing the problem you are experiencing? Without that information it will be difficult to help you further. It would especially be helpful if you could upload the log file from GitHub Desktop, which will give more details about the specific error you are seeing. 

To access the log files go to the  menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`. 

The log files are created daily -- please send over a log file as an attachment from a day where you experienced the issue

Thanks for understanding and meeting us halfway. 😀

**Comment by billygriffin** [comment]
@pradeep-madheswaran I added the template to your issue so it'd be easy for you to just edit the original message to add those details. But if you don't mind, please respond to this issue when you have updated it so we get notified. Thanks!
