### ISSUE TITLE
While I was loading my repo from GitHub desktop popup error appeared Unable to find path to repository on disk.

### ISSUE THREAD

**Issue by Gopal2696** [desktop/desktop#6860]
## Version

* GitHub Desktop:

* Operating system:

**Comment by steveward** [comment]
Thanks for reaching out @Gopal2696!

Would you mind filling out the rest of the issue template so that we can better understand what is causing the problem you are experiencing? Without that information it will be difficult to help you further. It would especially be helpful if you could upload the log file from GitHub Desktop, which will give more details about the specific error you are seeing. 

To access the log files go to the  menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`. 

The log files are created daily -- please send over a log file as an attachment from a day where you experienced the issue

Thanks for understanding and meeting us halfway. 😀

**Comment by shiftkey** [comment]
Closing this out due to inactivity. @Gopal2696 if you're able to fill out the template and provide the logs to help with troubleshooting the issue we'd be happy to revisit the issue.
