### ISSUE TITLE
Fresh install of desktop is not running authentication agent

### ISSUE THREAD

**Issue by borpin** [desktop/desktop#6865]
This started when trying to link balenaCloud account to GitHub login - it returned no SSH Key.  I followed the instructions to create a key, but when I try and add the key I am getting "Could not open a connection to your authentication agent.".

The documentation says, in many places, 

> If you're using Git Shell that's installed with GitHub Desktop, you don't need to follow these steps. GitHub Desktop automatically launches ssh-agent for you.

But it isn't.

To be sure I uninstalled Git and GiHub desktop, downloaded new distributions, reinstalled desktop first then git.

At some point I am sure I installed MINGW on this machine and I am wondering if that is causing issues as I see this (is that normal)?

![image](https://user-images.githubusercontent.com/1322749/52897431-38f23e80-31cc-11e9-9d46-b7be21190c78.png)

I do have PuTTY installed but did not select to use it when installing Git.

**Comment by niik** [comment]
> If you're using Git Shell that's installed with GitHub Desktop, you don't need to follow these steps. GitHub Desktop automatically launches ssh-agent for you.

Hey @borpin, could you please provide a link to the documentation that said this. I believe this is still referring to the classic version of GitHub Desktop as we no longer ship a Git shell alongside the client. We should update that documentation to reflect that.

> This started when trying to link balenaCloud account to GitHub login - it returned no SSH Key.

Unfortunately I'm not familiar with that product but I can say that GitHub Desktop heavily favors the use of http remotes rather than SSH at the moment. We have an issue open at https://github.com/desktop/desktop/issues/2579 to improve upon this in the future but for now the http protocol is the recommended approach. Is there a particular reason why you have to use ssh?

**Comment by borpin** [comment]
> could you please provide a link to the documentation that said this

https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/
https://help.github.com/articles/working-with-ssh-key-passphrases/

I'm sure I read it again somewhere, but I may have been going round documentation circles...

**Comment by niik** [comment]
@borpin Thank you so much for those links!

@steveward Do you think you could take a look at that documentation and/or coordinate with the docs team to make sure we don't have any loose references to classic anymore?

**Comment by borpin** [comment]
@niik Sorry I missed this question
> Is there a particular reason why you have to use ssh?

No there isn't, I was just following the docs to create a key on GitHub.

**Comment by steveward** [comment]
@borpin thanks again for the report. I've opened an issue to have our documentation updated to correctly reflect the current state of SSH in GitHub Desktop. I'm going to close this issue out, but let us know if you have any further questions.
