### ISSUE TITLE
no access to local hub for clonning

### ISSUE THREAD

**Issue by JJimenezSa** [desktop/desktop#6869]
i can't clone a repository with my local github and i put the url for clone and when i clic to clone. the autentification said im not sign in but i just login in the local github.
![screenshot_2](https://user-images.githubusercontent.com/46530702/52979978-0439df00-33a6-11e9-908d-6c8496bab2db.png) and again and again

## Version

* GitHub Desktop:

* Operating system:

**Comment by niik** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

In particular what would be useful here is if you could include a copy of the log file from the day the problem occurred. Open GitHub Desktop and select the `Help` menu followed by `Show Logs in Explorer`.

Thanks for understanding and meeting us half way :grinning:

**Comment by billygriffin** [comment]
@JJimenezSa I added the template to your original issue, so feel free to edit that with the additional information we need to investigate and let us know here when it's updated, and we'll be happy to take a look.
