### ISSUE TITLE
When i commit & push, it's just spinning.

### ISSUE THREAD

**Issue by rajeevbbqq** [desktop/desktop#6872]
**When i commit & push, it's just spinning.**

When i commit and try to push, just spinning the spinner. I'm only able to push after restarting the application.

## Version

* GitHub Desktop:

* Operating system:

**Comment by niik** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by billygriffin** [comment]
@rajeevbbqq I went ahead and added the template to your original issue body, so feel free to just edit that when you have the information and let us know here, and we're happy to try to dig into it to figure out what's going on.

**Comment by shiftkey** [comment]
Closing this out due to inactivity. @rajeevbbqq if you're able to fill out the template and provide more details about the issue we're happy to investigate further.
