### ISSUE TITLE
[experiment] a 32-bit build Desktop for Windows

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#6874]
This issue is tracking the ability to build and test a 32-bit version of the app locally. This will mean users may be able to run Desktop on 32-bit Windows. **This issue is not about shipping a 32-bit version of GitHub Desktop, as this is not planned based on the details we talked about at the time in #1214**. 

`dugite` and `dugite-native` now ship with a 32-bit Git package since https://github.com/desktop/dugite-native/pull/93, so this issue is tracking anything else platform-specific that blocks a 32-bit version of the app being built locally.

In particular:

 - our `app/.npmrc` is hard-coded to `x64`

https://github.com/desktop/desktop/blob/3f2084e1cb88a08abc9e5cf8123ef256a59096f8/app/.npmrc#L1-L4

This affects what native modules are used when installing dependencies locally.

I haven't used a 32-bit version of Windows in years, so I'm not the person to lead this up, but if someone wants to have a go at this I'm happy to help answer questions about what they uncover as part of this process.

**Comment by earthtopomaps** [comment]
Hello Look my website https://googleearthcenter.wordpress.com/ 32-bit build Desktop for Windows

**Comment by ahmelsayed** [comment]
I had to replace `x64` with `ia32` few different places (see https://github.com/ahmelsayed/desktop/commit/fadc224787ef0cd534c4e8e2d00baebc578d804c) 

_the `max_old_space_size` change is probably only needed because I was running the build on a Windows 32bit machine to make sure things actually work_

After that following the steps in [`docs/contributing/setup.md`](https://github.com/desktop/desktop/blob/development/docs/contributing/setup.md)

```bash
yarn install
yarn build:prod
yarn package
```

I have a release on my fork for the commit linked above. I haven't spent any time testing it beyond local git operations and git push. These are the only scenarios I care about to teach some high school students how to use git on ancient school machines.

**Comment by dennisameling** [comment]
@ahmelsayed 
Just tried your 32-bit build on Surface Pro X (this device can't run x64 apps, only arm64 and x86 programs). Tested the following things:

- Logged in with GitHub account
- Cloned a repo
- Committed a file
- Pushed a file to GitHub

All works without any issues. This covers my basic usage scenario! Thanks! :)

**Comment by theAlphaBeth** [comment]
Does this work for x32 users?
Thanks for the response!

**Comment by Rexogamer** [comment]
@theAlphaBeth do you mean x86?

**Comment by winikisa** [comment]
helo

**Comment by steveward** [comment]
I'm going to close this out as stale.
