### ISSUE TITLE
padding issue with emoji/user/issue autocomplete forms

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#6895]
## Description

![image](https://user-images.githubusercontent.com/359239/53116694-a29d8000-351f-11e9-90c8-a88d6d131b14.png)

## Version
* GitHub Desktop: `1.6.3-beta1`
* Operating system: macOS

## Steps to Reproduce

Use the `:` in the commit summary to trigger the emoji selection. 

### Expected Behavior

Emoji icon has padding on left-hand side

### Actual Behavior

Emoji is squished against left edge

## Additional Information

I believe this is related to our Electron 3 upgrade in #6713 so you might not notice this in the current production build.

**Comment by tierninho** [comment]
Both the `#` and `@` autocompletion-popup are also affected.

**Comment by murrelljenna** [comment]
Hi there! I'm a first-timer and I'd like to try working on this issue. I've reproduced the issue and I'm currently looking at desktop/app/styles/ui/_autocompletion.scss. I'm going to take a longer look later today and tomorrow.

**Comment by shiftkey** [comment]
@murrelljenna that's great, and good luck - let us know if you have any other questions about this area!

**Comment by niik** [comment]
> I believe this is related to our Electron 3 upgrade in #6713 so you might not notice this in the current production build.

This got me anxious since bumping Chromium really shouldn't affect styling, they take incredible care not to regress in this area so I felt the need to go digging and it turns out that this was simply an unexpected side-effect of another change where a little overly ambitious CSS selector matched too greedily. The change was https://github.com/desktop/desktop/commit/83ddcf0f82ceafb2d50a4589488b60d868a8e0ab#diff-5c3655a73143215d8edebe5ad471326b where `.file-list .list-item` had its padding removed and it turns out that `.file-list` isn't actually a list but a rather all-encompassing wrapper in the sidebar meaning that any list item underneath that was affected by the same style.

**Comment by shiftkey** [comment]
Thanks for unpacking this @niik - the first reports I'd heard about this were all running the beta so I put  2+2 together and got 5.
