### ISSUE TITLE
Modal does not recentre if window is resized

### ISSUE THREAD

**Issue by phawxby** [desktop/desktop#6903]
## Description
Modal does not recentre if window is resized

## Version
* GitHub Desktop: 1.6.2
* Operating system: Windows 10 x64 Build V1809

## Steps to Reproduce
1. Make window full screen (ideally on a 4k display)
2. Trigger a merge conflict modal
3. Scale window down

### Expected Behavior
Modal moves into centre of resized window
### Actual Behavior
Modal stays in position and cannot be clicked
![image](https://user-images.githubusercontent.com/1090602/53159649-2dcd5300-35be-11e9-9ffe-3c6517c03661.png)

**Comment by niik** [comment]
Hey @phawxby, thanks for reporting this!

For positioning of the dialog we actually rely on the positioning logic of the browser itself since we're using the [HTML dialog](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog) element in a modal state. The default behavior (at least for Chromium) is to position the dialog once and then keep its position static and in general this is a sound approach as it means the dialog won't jump around if the content in it changes.

For this particular scenario though I agree that it isn't ideal. I'd suggest that if/when we decide to look at this we don't try to go down the path of simply positioning it at the 50% mark with CSS but rather opt for a more deliberate approach where we react to the Window size changing (and potentially other events such as the zoom changing) and then try to position it using the same logic that the browser uses for the initial placement.

I'm going back and forth on the prioritisation of this but given that this behavior has been in since the introduction of modals I'm leaning more heavily towards priority-3 but I don't feel very strongly about that.

**Comment by phawxby** [comment]
If that's the case I wonder if this should be considered a Chromium bug. But I agree with your priority regardless, I only noticed this issue because I dragged it between a 4k and 1080p monitor and couldn't click the button.

**Comment by tidy-dev** [comment]
This is was addressed when modal accessibility and stacking was updated.
