### ISSUE TITLE
Can't push to branch

### ISSUE THREAD

**Issue by konopkoman** [desktop/desktop#6920]
## Description

Can't push to branch repeatedly, but on 3rd or 4th time it's finally succeed

## Version

* GitHub Desktop:

* Operating system:

**Comment by shiftkey** [comment]
@konopkoman Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Could you also attach the full log files? The **Help** | **Show Logs in Explorer/Finder** menu items should open the logs folder, and inside those are the log files generated by day. This will provide some more information to help troubleshoot.

Thanks for understanding and meeting us half way 😀
