### ISSUE TITLE
app follows repository redirects even after a new repository created with same name

### ISSUE THREAD

**Issue by douglasrcjames** [desktop/desktop#6927]
## Version
* GitHub Desktop: Version 1.6.2
* Operating system: Microsoft Windows [Version 10.0.17134.590]

### Expected Behavior
Not a huge bug, but took me a little to figure out exactly what to do, and some users may get stuck with this. I renamed one of repositories, call it `projectA` to `projectA-old`, and recreated a new repo with the same name on the web app. I removed the local repo on my PC to start fresh.

### Actual Behavior
When I re-cloned `projectA`, the `projectA-old` kept persisting as the name. I wasnt able to access the branches of `projectA`, I kept seeing the branches from `projectA-old`.  I tried to reinstall Github to refresh the cached version, didn't help. 

### Work Around
I had to delete both GitHubDesktop folders under AppData/Roaming & AppData/Local, which solved the problem.

### Possible fix
When doing a reinstall at the very least delete folders from both Roaming and Local in AppData. Or even better, remove the repo that is cached in those same folders, presumably.

### Logs
Logs were deleted fixing the issue

**Comment by shiftkey** [comment]
@douglasrcjames thanks for the report! I'd love to reproduce this on my end to figure out what we can do better, and I want to confirm the steps you went through to end up in this state:

> I renamed one of repositories, call it `projectA` to `projectA-old`

Was this renamed using the GitHub repository settings page or renamed on disk?

> and recreated a new repo with the same name on the web app.

There's an interesting thing in here about [repository redirects](https://github.blog/2013-05-16-repository-redirects-are-here/) that I want to mention:

 - if you have a repository named `projectA` and rename it to `projectA-old` GitHub will redirect requests from `projectA` (both on the website and through the API) to `projectA-old`
 - the Desktop app uses the API to query for information about a repository

> When I re-cloned `projectA`, the `projectA-old` kept persisting as the name.

This to me feels like repository redirects were involved - redirecting you to clone `projectA-old` when you wanted the newer `projectA`. From that link above about repository redirects:

> As a special bonus, we’ll also be servicing all Git clone, fetch, and push requests from previous repository locations.

Some extra context on this issue from [this support question](https://github.community/t5/How-to-use-Git-and-GitHub/How-long-does-github-forward-renamed-moved-repos/td-p/3256):

> We keep redirects for moved and renamed repos indefinitely, but new repos take priority over redirects. That means if a new repo is created at an old location, the redirects will break in favor of displaying the new repo, for as long as that new repo exists.

My thinking here is there is some window of time where redirects are being chosen rather than the new repository (for API or Git operations or both) after making the change in the settings, and then things switch to the intended state (with the recreated repository overriding the redirect).

> I had to delete both GitHubDesktop folders under AppData/Roaming & AppData/Local, which solved the problem.

I'm not 100% sure this is the right solution here given the above, but I'll report back based on what I can reproduce on my end.

**Comment by douglasrcjames** [comment]
+ Renamed using settings page on web app
+ Sounds like redirect might have been involved here as well, definitely shouldn't be the intended behavior after a full reinstall however

- Just thought you guys might want to know in case this happens to other users!

**Comment by shiftkey** [comment]
@douglasrcjames thanks for the extra details!

> * Sounds like redirect might have been involved here as well, definitely shouldn't be the intended behavior after a full reinstall however

A reinstall of the client won't affect what results we get from the GitHub API for the repository if it's in this unclear state between "redirect to old repository" and "added new repository to replace redirect". The application doesn't cache the repositories the user can access from the API (#2770 talks about this in more detail).

**Comment by shiftkey** [comment]
@danqing in #7202 also encountered this issue:

> Say I have a repo named `danqing/repo1`, which is synced using GH Desktop. I rename it to `danqing/repo2`, and GH Desktop picks up the renaming (good). But then if I create another repo named `danqing/repo1` and try to clone it, Desktop still renames it to `danqing/repo2`, and now I end up with 2 `danqing/repo2`s in the app.

**Comment by danqing** [comment]
Actually today I noticed that in my case, `repo1`'s `git remote` still points to the old URL (GH Desktop only updates the name in the UI, but doesn't update the actual git config). After I create `repo2`, the app gets completely confused and simply refuses to work with `repo1`, citing different upstream. I had to manually change my `git remote` for the old repo.

(The naming bug still persists)

**Comment by shiftkey** [comment]
> the app gets completely confused and simply refuses to work with `repo1`, citing different upstream

@danqing are you able to share the relevant log messages related to this error?

**Comment by danqing** [comment]
What kind of log messages do you need and where can I find them?

**Comment by tierninho** [comment]
@danqing Please see the Help menu in Desktop to find your logs.
