### ISSUE TITLE
syntax highlighting not working for @supports (scroll-snap-type) in SCSS file

### ISSUE THREAD

**Issue by obendev** [desktop/desktop#6974]
## Description
This might be related to a issue i created in Microsoft/vscode#63116
Seems like the syntax for `@supports (scroll-snap-type: x mandatory)` isnt supported since `scroll-snap-type: x mandatory` is marked in red, but `display: grid` isnt.

![@supports bug](https://i.imgur.com/I02QocB.png)
![CSS Scroll-snap specification history](https://developers.google.com/web/updates/images/2018/07/css-scroll-snap/specification-history.png)

## Version
* GitHub Desktop: 1.6.2
* Operating system: Windows 10.0.17763.316

**Comment by shiftkey** [comment]
@obendev thanks for the report! We're using Codemirror to render diffs in the app, and we have an upgrade under review in #6918 that might address this.

**Comment by shiftkey** [comment]
I was still able to see the problem syntax highlighting using Codemirror `5.44.0` which is the latest version available on NPM:

<img width="980" src="https://user-images.githubusercontent.com/359239/53567373-6e384e00-3b35-11e9-97ad-0a062d19d8bc.png">

If you look at these two examples you'll see the first is being correctly parsed (note the `cm-property` CSS class attributes):

<img width="428" src="https://user-images.githubusercontent.com/359239/53567492-c2433280-3b35-11e9-8d5a-b0bec2489085.png">

Whereas the second example isn't parsed correctly (note the `cm-error` class attributes):

<img width="456" src="https://user-images.githubusercontent.com/359239/53567493-c2dbc900-3b35-11e9-958d-6dc75e53b3aa.png">

The quickest way to get this resolved in Desktop would be to raise a bug report against Codemirror itself. @obendev if you have time, they have [instructions](https://github.com/codemirror/CodeMirror/blob/master/CONTRIBUTING.md#submitting-bug-reports) for how to submit a good bug report - it shouldn't be a browser-specific issue.

**Comment by obendev** [comment]
I will take a look into this tonight.
Please keep this issue open so I can give feedback when codemirror fixed this and you can bump the version in Github Desktop.

**Comment by shiftkey** [comment]
Moving this to `help wanted` because the Codemirror team has acknowledged how to address this: https://github.com/codemirror/CodeMirror/issues/5794#issuecomment-468958516

**Comment by shiftkey** [comment]
I'm going to close this out for two reasons rather than let this linger: 

 - it's a low-priority bug (diffs still work fine)
 - it isn't something we can address directly in Desktop (requires patching Codemirror)

It requires:

 - a contributor to fix the upstream problem in Codemirror, get it reviewed and merged https://github.com/codemirror/CodeMirror/issues/5794
 - an update to be published by the maintainers to NPM

After those two things have happened, someone is welcome to comment here to remind us about this. Then we can figure out when we want to pull the Codemirror update into the project.
