### ISSUE TITLE
Detached HEAD state midstream during Rebase

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#6980]
As part of testing rebasing, specifically [test case](https://github.com/shiftkey/rebase-test-cases/tree/2-simple-rebase-conflict-base-branch/2-simple-rebase-conflict), I noticed a detached HEAD state during the merge conflict process. 

Although this is a common side-effect of the rebasing process, I am wondering if we should consider any other language or UI treatment to convey that this is not an error?

As rebasing is for the more advanced user, this may not be needed. 🤷‍♂️Thoughts? or feel free to close.

![image](https://user-images.githubusercontent.com/14828183/53598050-d55efe00-3b47-11e9-9837-31a7ffab1646.png)

**Comment by shiftkey** [comment]
A couple of suggestions:

 - when in a rebase, don't show the publish button at all - this might be too radical
 - keep the button around but update the message to be clearer (that a rebase is in progress)

**Comment by j-f1** [comment]
Maybe 🗑 + “Cancel rebase” with the subtitle ”Can’t push while a rebase is in progress”?

**Comment by billygriffin** [comment]
Thanks @tierninho for spotting this and @shiftkey and @j-f1 for throwing out a few ideas.

I'd like to keep expectations around the primary interface elements consistent (and therefore I don't want to change the functionality of the button or remove it entirely), but since the "Publish" button is greyed out, I think it can mirror the branch dropdown next to it. 

Replacing "Cannot publish detached HEAD" with "Rebase in progress" when in the middle of a rebase makes sense to me. Let me know if that works @shiftkey or if you think there's some additional context I'm missing.

**Comment by shiftkey** [comment]
@billygriffin that works for me, and I agree with not overloading the button with extra responsibility. I should be able to get a PR open tomorrow for review.
