### ISSUE TITLE
File name no spaces

### ISSUE THREAD

**Issue by jsmith2021Brandeis** [desktop/desktop#6991]
## Description

I couldn't merge automatically because my file had spaces in it, when I changed spaces to underscore, the button turned green and I merged automatically. When the merge change button appears and we can't merge automatically, I think a list of common reasons why github can't merge automatically should be presented, such as spaces in file names.

## Version

* GitHub Desktop:

* Operating system:

**Comment by shiftkey** [comment]
@jsmith2021Brandeis Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Also, could you attach the full log files? The **Help** | **Show Logs in Explorer/Finder** menu items should open the logs folder, and inside those are the log files generated by day. This will provide some more information to help troubleshoot.

Thanks for understanding and meeting us half way 😀

**Comment by jsmith2021Brandeis** [comment]
Thanks, but I realized this is a github browser issue and not really a github desktop issue, I'm sending to 
[support@github.com](mailto:support@github.com).
