### ISSUE TITLE
Get more context around the code I'm looking at in a diff

### ISSUE THREAD

**Issue by varkor** [desktop/desktop#7014]
At the moment, the context of (lines preceding and following) the diffs is fixed. It would be useful to allow the user to unfold lines around the diff, like in GitHub itself.

For example, this is how a change is currently displayed in GitHub Desktop:
![image](https://user-images.githubusercontent.com/3943692/53873026-6bd36980-3ff7-11e9-9831-f799171e5a01.png)

This is how it looks like in GitHub on the web (with an unfold button):
![image](https://user-images.githubusercontent.com/3943692/53873072-83aaed80-3ff7-11e9-8ad6-7b91e694a01a.png)

https://github.com/desktop/desktop/issues/1544 seems related, but I couldn't find this precise issue anywhere.

**Comment by steveward** [comment]
Dropping in to mention that I also recently got a feature request for this via Halp.

**Comment by varkor** [comment]
> Would you mind sharing a couple examples of scenarios where you would use this, and what problem it’s solving for you so we can understand it a bit better?

I think the reason I don't run into this more often is because I mainly navigate code on GitHub, rather than through the app (and the commits I'm making are usually in a context I'm familiar with, so I don't need to unfold so frequently). However, when I've made a change to a part of a codebase I'm not so familiar with, and I'm looking back at a commit I've made in the past, having a little more context can be enough to jog my memory (especially details like enclosing function names, etc.).

**Comment by billygriffin** [comment]
@varkor Makes total sense to me, thank you! I'm going to leave this here and remove `future proposal` from the issue you referenced because I think this captures the problem nicely, which is the ability to gain additional context on parts of the code you aren't as intimately familiar with during your workflow.

I think this would be a nontrivial change based on discussions we've had in the past, so I want to understand more about whether other people are experiencing this pain and how. If anyone else has a similar pain point, I'd love it if you'd react to the original issue here and/or respond with how it impacts you.

**Comment by danra** [comment]
@billygriffin Same pain here. I would really like to be able to easily see a "full" split view with all the context (GitKraken for example has that mode available). I'm personally using the web interface, not the desktop.

Thanks!
Dan

**Comment by dkeirouz** [comment]
Similar thing here. Working in a project I don't know, I usually scroll through the diff before I commit to make sure I understand all the changes I made and didn't do anything stupid. If I noticed I changed a line, but don't immediately remember why, I tend to want to look at the function name or at least some surrounding code, which would be a lot easier if I could expand for some context.

**Comment by PhilZ-cwm6** [comment]
yes, please, this really a pain in the A**

**Comment by daniel31079** [comment]
does that mean the External Diffs are getting added tool per tool (means a new Issue for each different tool) or will there be added a "general support"?

We are currently keep using Sourcetree because Github Desktop doesn't support Araxis Merge - it's kinda like the only thing which keeps us from switching.

**Comment by billygriffin** [comment]
Hi folks, just wanted to update you that we're working on this and our initial version is now on beta! You can download the beta here if you'd like to try it out: https://github.com/desktop/desktop#beta-channel

Because we're only planning minor follow-up work on this, I'm going to close this issue. Please let us know your feedback from using it if you wouldn't mind. ❤️

**Comment by danielb987** [comment]
> Please let us know your feedback from using it if you wouldn't mind.

I appreciate this very much! Thank you!

**Comment by PhilZ-cwm6** [comment]
thanks a lot

**Comment by VipsDicks** [comment]
> At the moment, the context of (lines preceding and following) the diffs is fixed. It would be useful to allow the user to unfold lines around the diff, like in GitHub itself.
> 
> For example, this is how a change is currently displayed in GitHub Desktop: ![image](https://user-images.githubusercontent.com/3943692/53873026-6bd36980-3ff7-11e9-9831-f799171e5a01.png)
> 
> This is how it looks like in GitHub on the web (with an unfold button): ![image](https://user-images.githubusercontent.com/3943692/53873072-83aaed80-3ff7-11e9-8ad6-7b91e694a01a.png)
> 
> #1544 seems related, but I couldn't find this precise issue anywhere.

<details><summary>Details</summary>
<p>

[Códigos de backup.pdf](https://github.com/user-attachments/files/15757197/Codigos.de.backup.pdf)


</p>
</details>
