### ISSUE TITLE
Colours after update

### ISSUE THREAD

**Issue by PeGoe** [desktop/desktop#7021]
The colours of the words "Current repository, Current branch, Last fetched..." are difficult for me to read. 

Please give the option to view the UI as before.

[GitHub Desktop Screenshot.docx](https://github.com/desktop/desktop/files/2937858/GitHub.Desktop.Screenshot.docx)

## Version

* GitHub Desktop:

* Operating system:

**Comment by shiftkey** [comment]
@PeGoe thanks for the feedback!

I've lifted the screenshot out of the document to make this easier to follow:

![](https://user-images.githubusercontent.com/359239/53906186-a1d91380-4020-11e9-9bd1-4e93f99e3b32.png)

Can you confirm the version of the application you are running?

**Comment by billygriffin** [comment]
Hi @PeGoe, thanks for the issue! This seems unexpected and we haven't seen it elsewhere. Would you mind filling out the template so we can understand what version and OS and such you're using and we can try to reproduce? I'm updating your original comment with the template.

**Comment by shiftkey** [comment]
@PeGoe two other things I'd like to learn more about that aren't covered in the template:

 - Can you provide a better screenshot of the app? You can drag-and-drop images when making a comment to upload them.
 - Are there any customizations that you have to the default Desktop themes? The purple colour on the commit button is very interesting, and I want to know more about what might be causing that...

**Comment by PeGoe** [comment]
Hi Brendan,

 

my version is 1.6.3

 

Thank you for your quick answer.

 

Greetings

 

Peter Göbel

Grasbergstr. 13

97616 Salz

 

09771 688414

 

Von: Brendan Forster [mailto:notifications@github.com] 
Gesendet: Mittwoch, 6. März 2019 20:02
An: desktop/desktop
Cc: PeGoe; Mention
Betreff: Re: [desktop/desktop] Colours after update (#7021)

 

@PeGoe <https://github.com/PeGoe>  thanks for the feedback!

I've lifted the screenshot out of the document to make this easier to follow:

 <https://user-images.githubusercontent.com/359239/53906186-a1d91380-4020-11e9-9bd1-4e93f99e3b32.png> 

Can you confirm the version of the application you are running?

**Comment by PeGoe** [comment]
Hi Brendan,

 

is this screenshot better? I have no concsious customization. I use Windows 10 Professional. The colour changed after the last update of GitHub Desktop.

 

Greetings

 

Peter

 

 

 

 



 

 

 

 



 

 

 

Peter Göbel

Grasbergstr. 13

97616 Salz

 

09771 688414

 

Von: Brendan Forster [mailto:notifications@github.com] 
Gesendet: Mittwoch, 6. März 2019 20:11
An: desktop/desktop
Cc: PeGoe; Mention
Betreff: Re: [desktop/desktop] Colours after update (#7021)

 

@PeGoe <https://github.com/PeGoe>  two other things I'd like to learn more about that aren't covered in the template:

*	Can you provide a better screenshot of the app? You can drag-and-drop images when making a comment to upload them.
*	Are there any customizations that you have to the default Desktop themes? The purple colour on the commit button is very interesting, and I want to know more about what might be causing that...

**Comment by PeGoe** [comment]
Hi Brendan,

 

with the dark theme:

 



 

Peter Göbel

Grasbergstr. 13

97616 Salz

 

09771 688414

 

Von: Brendan Forster [mailto:notifications@github.com] 
Gesendet: Mittwoch, 6. März 2019 20:11
An: desktop/desktop
Cc: PeGoe; Mention
Betreff: Re: [desktop/desktop] Colours after update (#7021)

 

@PeGoe <https://github.com/PeGoe>  two other things I'd like to learn more about that aren't covered in the template:

*	Can you provide a better screenshot of the app? You can drag-and-drop images when making a comment to upload them.
*	Are there any customizations that you have to the default Desktop themes? The purple colour on the commit button is very interesting, and I want to know more about what might be causing that...

**Comment by shiftkey** [comment]
@PeGoe none of the attachments made it through. Are you able try again commenting directly on GitHub?

**Comment by PeGoe** [comment]
Screenshot:
![grafik](https://user-images.githubusercontent.com/47083981/54142520-3203c800-4428-11e9-88af-7bd550e6c1d2.png)

**Comment by PeGoe** [comment]
Screenshot dark theme:
![grafik](https://user-images.githubusercontent.com/47083981/54142612-68d9de00-4428-11e9-9d5c-05650ce828bd.png)

**Comment by shiftkey** [comment]
@PeGoe do you have a color profile or color correction enabled for that monitor? The reason I ask is that I was able to emulate your screenshot fairly closely by taking the default screenshot of the app and tweaking the hue and saturation in an image editor.

<img width="1151" src="https://user-images.githubusercontent.com/359239/54378195-8b0c6f80-4665-11e9-89bc-2a61717c2069.png">

You'll also see that the text looks blurry up close as a result:

<img width="360" src="https://user-images.githubusercontent.com/359239/54378417-0c640200-4666-11e9-9d70-7205c520e840.png">

This isn't a 100% satisfactory answer, because some parts of your screenshot (which look like images) are not affected by this:

<img width="64" src="https://user-images.githubusercontent.com/359239/54378291-c149ef00-4665-11e9-81ac-9c6b1f2e74b5.png">
<img width="136" src="https://user-images.githubusercontent.com/359239/54378292-c149ef00-4665-11e9-86c7-897f0624be54.png">

I was able to find this PR https://github.com/electron/electron/pull/15898 which talks more about this limitation that affects Chromium and let's Electron apps opt-out of the default behaviour, but it hasn't been backported to the current version of Electron that we are using currently.

**Comment by tierninho** [comment]
@PeGoe As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
