### ISSUE TITLE
Unknown error when trying to clone a repo from my GitHub account

### ISSUE THREAD

**Issue by HackcatDev** [desktop/desktop#7040]
I got this error message every time I'm trying to clone my existing repo to hard drive
![image](https://user-images.githubusercontent.com/35487139/54019376-1ab0aa80-419c-11e9-8272-2b84f3c6a8ed.png)

This began once I updated my GitHub Desktop to 1.6.4

* Operating system: Windows 8.1 x64 (activated)

### Logs
[2019-03-08.desktop.production.log](https://github.com/desktop/desktop/files/2945141/2019-03-08.desktop.production.log)
Logging out and doing a re-login didn't help

**Comment by repl-pushker-yadav** [comment]
It seems your system does not have enough space to checkout the code.

**Comment by HackcatDev** [comment]
> It seems your system does not have enough space to checkout the code.

No, I have almost 120 GB free on my hard drive. In my opinion it's new update issue, because when I re-installed GitHub Desktop from old package (v1.6.2) everything is working correctly

**Comment by shiftkey** [comment]
@HackcatDev thanks for the report. 

The `Unknown error` message is because Git doesn't return any `stdout`  or `stderr` to go with this exit code, which is very interesting:

```
2019-03-08T06:12:30.887Z - warn: [ui] Error refreshing pull requests for 'CHIP8'
GitError: Unknown error
    at Object.t.git (C:\Users\Vitalik\AppData\Local\GitHubDesktop\app-1.6.3\webpack:\app\src\lib\git\core.ts:174:2)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

It also looks like all Git operations are failing in the same way, which might suggest something is corrupted with the install:

```
2019-03-08T06:12:20.092Z - error: [ui] `git lfs install --skip-repo` exited with an unexpected code: 3221225495.
...
2019-03-08T06:12:21.377Z - error: [ui] `git rev-parse --show-cdup` exited with an unexpected code: 3221225495.
...
2019-03-08T06:12:43.772Z - error: [ui] `git config -z --global protocol.version` exited with an unexpected code: 3221225495.
```

It's not clear to me whether the reinstall addressed the issue - can you confirm?

**Comment by shiftkey** [comment]
> This began once I updated my GitHub Desktop to 1.6.4

The logs you provided are reporting version `1.6.3` - can you confirm what version you have installed?

**Comment by HackcatDev** [comment]
@shiftkey Yes, I used 1.6.3 version for long time, but yesterday version 1.6.4 has been installed automatically. Problem is definitely caused by this update because I have an package of 1.6.3 version when I installed it over 1.6.4 and tried to re-sync my repo, no errors appeared. Unfortunately, there is no button like "Enable auto-updating the app", so version 1.6.4 has been installed again and I have this problem every time I try to re-sync any repo.

**Comment by shiftkey** [comment]
@HackcatDev are you referring to the beta channel, which is currently tagged `1.6.4-beta0`? That was bumped to ensure https://github.com/desktop/desktop/pull/7016 was available there - otherwise it's the same as `1.6.3` currently.

**Comment by kapi14** [comment]
Hello.
Probably I have the same error
GitHub Desktop, windows, 1.6.3

2019-03-11T12:42:15.805Z - info: [ui] Executing getConfigValueInPath: git config -z --global protocol.version (took 18.520s)
2019-03-11T12:42:15.806Z - error: [ui] `git config -z --global protocol.version` exited with an unexpected code: 3221225495.

**Comment by shiftkey** [comment]
@HackcatDev @kapi14 I went looking for that exit code (Git error codes are typically small integers) and stumbled upon [this document](https://www.febooti.com/products/automation-workshop/online-help/events/run-dos-cmd-command/exit-codes/) and suggestion:

<img width="706" src="https://user-images.githubusercontent.com/359239/54134138-213a5e80-43f6-11e9-9d42-6004e00c5d93.png">

> _Not enough virtual memory is available_
> Indicates that Windows has run out of memory.

Does this sound like the situation you're encountering?

**Comment by Erilarn** [comment]
@shiftkey my GitHub client has consumed 1.8K MB of virtual memory before the crash

**Comment by shiftkey** [comment]
@Erilarn I'm not aware of how crashes are involved in this. Are you able to open a new [bug report](https://github.com/desktop/desktop/issues/new?template=bug_report.md) and fill out the template so we can confirm whether it's related to an existing issue?

**Comment by shiftkey** [comment]
We have published `1.6.4-beta1` just now which reverts the embedded Git in Desktop from `2.20.1.windows.1` to `2.19.2.windows.1`, which we believe will address this issue.

In the process of investigating we've identified at least two known issues with `2.20.1.windows.1` that have since been fixed in Git for Windows:

 - https://github.com/git-for-windows/git/issues/1989
 - https://github.com/git-for-windows/git/issues/2075

Because of the complexity of the setup to trigger these issues **we are looking for any Windows users to help us confirm this problem has been resolved, which requires installing [the latest beta](https://github.com/desktop/desktop#beta-channel) and testing their problem repositories again**.

We plan to make this available today to everyone, but it would be great to know in advance that these specific issues are addressed.

Thanks again for working with us to get this resolved!

**Comment by kapi14** [comment]
@shiftkey Perfect. Thank you. It's working great!

**Comment by shiftkey** [comment]
@kapi14 that's great to hear!

**Comment by shiftkey** [comment]
I'm going to close this out because `1.6.4` is now out on production, which should resolve this issue. 

Please open a fresh issue and fill out the template if this is still occurring for you.
