### ISSUE TITLE
improvement: filter repos list for commits not yet pushed

### ISSUE THREAD

**Issue by penCsharpener** [desktop/desktop#7053]
I'm mainly working with Visual Studio on C# projects. 
My solutions often contain many projects from multiple repos. 
I like that in the repo list I can see which repos have commits not pushed to origin yet. 
However with over 50 repos in the list it takes to long to scroll through and see where I have forgotten to push yet. 

Could you add a filter for the repo list for 
* Repos with local commits that are not yet pushed to remote/origins
* Repos that have remote commits to pull

**Comment by billygriffin** [comment]
Hi @penCsharpener, thanks for the feedback! Since we're looking at the repo list in the context of #6460 (which I know you've weighed in on), I think I'd like to roll this into that as I don't want to add a specific filter for things on a one-off basis but instead try to understand whether it's a broad problem that affects more than just a few folks.

I do have a question if you don't mind. Of the 50 repos you referenced, how many of those are you working with regularly on any given day or week?

cc: @outofambit

**Comment by penCsharpener** [comment]
sure. So I would work on 1 or 2 programs at any time but all the solutions are comprised of 10 to 20 projects, maybe more. Some of those I turn in to nuget packages because I'm not changing anything in there but it doesn't work with other. 5 of those projects in the solution are in the repo of the program.  The other ones referenced in the solution are separate repos, grow larger/better over time and are also further developed by other devs. 

Hense it would help a lot if I could see all projects that have commits incoming and also outgoing. Within Visual Studio I don't always notice or think about when I'm making changes to a project that is a separate git repo. Then I end up having uncommited changes or unpushed commits hanging around that other either depend on or have to merge against.

**Comment by billygriffin** [comment]
Thanks for sharing that context!
