### ISSUE TITLE
commit error with error: cannot run gpg2:  mac Mojave 10.14.3

### ISSUE THREAD

**Issue by fords** [desktop/desktop#7059]
I updated the Mac version today. And I started to have the problem with git commit . I didn't have the problem before updating.  Error messages are as below.
```
error: cannot run gpg2: No such file or directory
error: gpg failed to sign the data
fatal: failed to write commit object
```
Issue 1391 suggest to use $ git config commit.gpgsign false . It works . However, I would need to use it for every repo.

I tried other ways as below and still not working.
git config --global gpg.program gpg1

brew install gnupg gnupg2 pinentry-mac
git config --global user.signingkey <YOUR_SIGNING_KEY>
git config --global commit.gpgsign true
git config --global gpg.program gpg

**Comment by juancarlovieri** [comment]
why is this not working for me?
`$ git config commit.gpgsign false`

**Comment by ghost** [comment]
been through same issue try this one 
`git config --global gpg.program $(which gpg)`
`echo "no-tty" >> ~/.gnupg/gpg.conf`

**Comment by juancarlovieri** [comment]
I am no longer using Mac, can't try it.

**Comment by jimconner** [comment]
ghost's solution worked nicely on my Mac (Big Sur). Thanks :-)

**Comment by aneta-s** [comment]
> been through same issue try this one `git config --global gpg.program $(which gpg)` `echo "no-tty" >> ~/.gnupg/gpg.conf`

I've been trying your solution, and I stuck after I type `echo "no-tty" >> ~/.gnupg/gpg.conf` in the terminal
It says `zsh: no such file or directory: /Users/aneta-s/.gnupg/gpg.conf`
![Screenshot 2021-10-15 at 13 42 03](https://user-images.githubusercontent.com/54153719/137481451-f204f881-d20f-4094-8943-e80b2b71995a.png)

Any idea how to solve it?

**Comment by jimconner** [comment]
@aneta-s The error you're getting is just because you're using append notation '>>' and the the gpg.conf file doesn't exist on your machine. 
Try using `echo "no-tty" > ~/.gnupg/gpg.conf` instead. 

The '>' will create the file if it doesn't exist yet (and overwrite it if it did) - You might also need to `mkdir ~/.gnupg` if that folder isn't there too.

**Comment by aneta-s** [comment]
> @aneta-s The error you're getting is just because you're using append notation '>>' and the the gpg.conf file doesn't exist on your machine. Try using `echo "no-tty" > ~/.gnupg/gpg.conf` instead.
> 
> The '>' will create the file if it doesn't exist yet (and overwrite it if it did) - You might also need to `mkdir ~/.gnupg` if that folder isn't there too.

I have created a folder and hit your command. It worked, actually. Do I need to repeat this steps every time I create new project?
![Screenshot 2021-10-15 at 14 24 35](https://user-images.githubusercontent.com/54153719/137486619-7edbba5d-39a7-4613-a71a-e2b5443c8056.png)

One thing what I still can't resolve is that my commits are not shown my contributions in my count contribution window. Do you know what is going on?

**Comment by jimconner** [comment]
@aneta-s 
"Do I need to repeat this steps every time I create new project?" - No - this is a one-time only operation. Now that you've told git how to work with gpg it won't forget.

"One thing what I still can't resolve is that my commits are not shown my contributions in my count contribution window. " - I'm afraid I've no clue  about that... I don't even know what the contribution count window is. Sorry.

**Comment by aneta-s** [comment]
@jimconner  Thank you so much, your help is appreciated. Actually I mean this window, your contributions to your Github profile :) Everytime you commit changes to your repository, Github displays your commits 
![Screenshot 2021-10-18 at 13 36 10](https://user-images.githubusercontent.com/54153719/137723545-ad41e2fc-18c0-4cc3-b696-78b7f4b0be83.png)

**Comment by aneta-s** [comment]
@jimconner I was wondering if you could have a look at this error in my new repository. After I command `echo "no-tty" > ~/.gnupg/gpg.conf ` it says `➜  gatsby-simplefolio git:(master) ✗ git add .
➜  gatsby-simplefolio git:(master) ✗ git commit -m 'add file'
husky > pre-commit (node v14.17.5)
⚠ Some of your tasks use `git add` command. Please remove it from the config since all modifications made by tasks will be automatically added to the git commit index.

ℹ No staged files match any configured task.
error: cannot run gpg2: No such file or directory
error: gpg failed to sign the data
fatal: failed to write commit object`

**Comment by jimconner** [comment]
@aneta-s - I'm afraid I've got no idea what's going on with that particular problem. It loks as if you have some pre-commit hooks set up in git, but I don't think that the problem is in any way related to adding the 'no-tty' option to your gpg config.
It looks more like there was soething that got added when you did your `git add .` that the pre-commit hook objected to. Without knowing what is in the pre-commit hooks, Internet people aren't going to be able to help.

**Comment by aneta-s** [comment]
@jimconner I can also try committing without git add . because it says it is automatically added. How can I see what is in the pre-commit hooks?

**Comment by jimconner** [comment]
@aneta-s  - That would depend on how hooks are set up within your organisation. The default is to have a 'hooks' directory within each repo but it can be configured to something else as part of your gitconfig... core.hooksPath configuration is the setting name. Check the git documentation for more.

**Comment by prasadsunny1** [comment]
Thank you very much,
It worked on my macos sonoma with GnuPG
