### ISSUE TITLE
Startup screen of the git client for windows does not have the possibility to switch user.

### ISSUE THREAD

**Issue by MikeTheFox** [desktop/desktop#7075]
**Please describe the problem you think should be solved**
A clear and concise description of what the problem is and who else might be impacted. Screenshots are encouraged.

Example:

> “When I run into a merge conflict, I don’t know where to go to resolve it. Anyone who works off of multiple branches will likely run into this problem at least occasionally.”

**[Optional] Do you have any potential solutions in mind?**
A clear and concise description of one or more solutions you think might solve the problem. Please include any considered drawbacks or tradeoffs, and how users might use your solution(s). Screenshots or mockups are helpful here!

**Comment by billygriffin** [comment]
Hi @MikeTheFox, thanks for the issue. We require that the template be filled out so that we can better understand the problem you're facing. If you could share some screenshots of the area you're referring to and how it's causing you problems, that would be great. In other words, what are you trying to do that you're unable to do?

**Comment by shiftkey** [comment]
Closing this out due to inactivity. @MikeTheFox if you're able to fill out the template and provide more details about the request we're happy to discuss further.
