### ISSUE TITLE
Chrome OS Support

### ISSUE THREAD

**Issue by justingolden21** [desktop/desktop#7077]
Please consider releasing Github Desktop to Chrome OS. It would many many peoples' lives easier and continue to spread the use of Desktop to more platforms.

Currently, the only ways to use git on chromebooks are by either installing linux, using android apps, or using the *website*. On many chromebooks, such as my own, the first two are not even options, as there is no support for either of those on my model, and I think we can all agree that dragging and dropping and downloading the zip and unzipping it every time is suboptimal and annoying.

It would also extend Github Desktop support to the less tech-savvy, that would rather not have to install linux and use git from the command line. I personally would be completely fine with this, if I was able to.

Github Desktop is built on Electron so I feel that this shouldn't be too hard to port to a chrome app, on an operating system built on the browser that electron is built on. 

Thank you for listening.

**Comment by steveward** [comment]
Thanks for the feedback @justingolden21. At this time we do not have any plans to provide direct support for installing GitHub Desktop on Chrome OS, and currently [Electron does not support Chrome OS](https://github.com/electron/electron/issues/12712). GitHub Desktop does have [Linux builds available](https://github.com/shiftkey/releases), which have been confirmed to work in the beta Linux support in Chrome OS. 

It is unfortunate that only certain versions of Chrome OS support the Linux beta -- hopefully broader support will happen in the future so that you can install GitHub Desktop. You can also follow along in https://github.com/desktop/desktop/issues/1525 for updates about Linux support.

I'm going to close this issue out, but please let us know if you have any other questions!

**Comment by jatin-cbs** [comment]
Lier github desktop no binaries are available not on snap store not on this link or a deb or RPM package. After acquisition github is now only focusing on microsoft.

**Comment by j-f1** [comment]
Check out https://GitHub.com/shiftkey/desktop/releases @jatin-cbs.
