### ISSUE TITLE
"Open Conflict Resolution Tool" button

### ISSUE THREAD

**Issue by joshaber** [desktop/desktop#71]
If there are conflicts, we should offer to open the conflict resolution tool.

**Comment by yellis** [comment]
In other tools (SourceTree being the one I am most familiar with) if there are merge conflicts they are listed, you can right click on them, have quick resolution options (resolve using mine/theirs) or option to open in 3rd party diff application (Winmerge, Beyond Compare, etc). When it is resolved there go back to the main screen and it cleans itself up. Might be easier to implement this way rather than having to do up your own diff/merge visualization.

**Comment by joshaber** [comment]
One of the big open questions here is, what do we encourage users to do if they don't have a merge tool configured? If our typical user is a less advanced git user, it's easy to imagine they wouldn't have one already. (Anecdotally, I literally just set one up for working on this feature.)

This is further complicated by the fact that a lot of the merge tools git knows about are command line tools. On Mac, the default for me was `vimdiff`. If someone's using GitHub Desktop, I doubt they want to use `vimdiff` for merge conflicts.

One thought I had was leveraging their External Editor. I expect Atom, VS Code, and Sublime could all function decently as a merge tool.

**Comment by j-f1** [comment]
> One thought I had was leveraging their External Editor. I hope Atom, VS Code, and Sublime could all function decently as a merge tool.

I ❤️ Atom’s merge conflict resolution. It would be great to be able to open Atom to fix the conflicts.

**Comment by shiftkey** [comment]
> One of the big open questions here is, what do we encourage users to do if they don't have a merge tool configured?

If they don't have one configured, we could look at the output of `git mergetool --tool-help` as that tells us what they have installed:

```
 ~  git mergetool --tool-help
'git mergetool --tool=<tool>' may be set to one of the following:
		emerge
		opendiff
		vimdiff
		vimdiff2
		vimdiff3

	user-defined:
		sourcetree.cmd /Users/shiftkey/Applications/SourceTree.app/Contents/Resources/opendiff-w.sh "$LOCAL" "$REMOTE" -ancestor "$BASE" -merge "$MERGED"

The following tools are valid, but not currently available:
		araxis
		bc
		bc3
		codecompare
		deltawalker
		diffmerge
		diffuse
		ecmerge
		examdiff
		gvimdiff
		gvimdiff2
		gvimdiff3
		kdiff3
		meld
		p4merge
		tkdiff
		tortoisemerge
		winmerge
		xxdiff

Some of the tools listed above only work in a windowed
environment. If run in a terminal-only session, they will fail.
```

We could then set this as their configured merge tool. The downside to this is that there's lots of CLI tools, and nicer experiences like Atom probably won't be detected...

**Comment by joshaber** [comment]
>The downside to this is that there's lots of CLI tools

Yeah, that's the catch to using `--tool-help`. It's really command line-centric 😞

**Comment by fenduru** [comment]
I'm trying to help my non-technical designers get set up with an easy to use workflow. It would be really nice if there was some level of support baked into Github Desktop for basic kinds of conflicts.

Introducing yet another tool for them to learn would be more difficult from a training perspective, and often times dedicated conflict resolutions try to be very powerful (which has been a turn off for other git GUIs that try to support every possible git feature - Github Desktop has been wonderfully simple in this regard).

**Comment by shiftkey** [comment]
@fenduru we've called out better conflict resolution [on our roadmap](https://github.com/desktop/desktop/blob/9da51e8197750cdc286374d1341a4bc382400253/docs/process/roadmap.md#12), so stay tuned for that as we get closer to planning what that looks like.

**Comment by jonagillag** [comment]
Can we at least get a simple Resolve Mine / Resolve Theirs right click menu for simple conflict resolution? We are trying to have the artists on our team use Github Desktop exclusively, but the lack of this feature means it's functionally unusable for them, since they would still need SourceTree or another tool installed to handle any conflicts that arise.

**Comment by shiftkey** [comment]
@jonagillag I think you'll be interested in following along with #5400

**Comment by billygriffin** [comment]
Since we're tracking this in #5400 I'm going to close this in favor of that as it's basically a duplicate. We completely agree that improving this flow will be helpful for users, just don't want to preliminarily specify the exact solution (and there are some good ideas in this thread that we'll be sure to reference).
