### ISSUE TITLE
Recent Repositories Group

### ISSUE THREAD

**Issue by outofambit** [desktop/desktop#7132]
motivated by #6460 

This is a sub-feature tracking issue for adding a recent repositories group to the repositories switcher dropdown. The goal is to facilitate faster switching between a small group of repos related to a single task the user is working on.

![Recents mockup reproduction](https://user-images.githubusercontent.com/964912/54762776-f8faee80-4bb1-11e9-8b0b-52eebc9e9514.png)

## Details

It will:

* include 5 most recently opened repos, not including the current one
* disambiguate names when needed (`owner/repo` if 2 repos have the same name)
* filterable (with the existing filter text box)
* these repos will still appear under their own groups in the rest of the list
* persist between launches of desktop

## Revisions

We expect to make small revisions to this after we get feedback on beta. Things explicitly up for revisiting:

* number of recent repos (is 5 too many?)
* should the recent group include the current repo? if so, how do we highlight it in addition to where it appears in the list?

**Comment by 0xa08ab242** [comment]
any chance on giving the user the option to toggle this feature on|off? one size != fit all

**Comment by billygriffin** [comment]
Thanks @0xa08ab242! We don't intend to provide a toggle for this as it's intended to be relatively unobtrusive. I'm curious what you don't like about it relative to the previous implementation - we're definitely not opposed to iterating as we hear feedback.

**Comment by CollinChaffin** [comment]
Unobtrusive?!  You just did a massive change to the visual workflow in desktop and the way it sorts.  Now, without any toggle I have no choice but to MANUALLY TYPE names in filter because I cannot simply toggle to a 2nd view of the old (aka YESTERDAY) view of simple alphabetical REPO/PROJECT name and not OWNER.  It is absolutely absurd that you chose a DEV tool/platform that was this limited that things that were done for DECADES in GUIs like simple view toggles are now just too hard to implement because Javascript was simply never meant to be such a massive DEV platform as it has been forcibly made over the years.

**Comment by billygriffin** [comment]
Thanks for your thoughts @CollinChaffin. As I’m sure you can imagine, with nearly every piece of the UI, there is someone who wants things to behave slightly differently, and invariably the request is to just provide a toggle. If we provided a toggle for every part of the UI to look or behave differently, the product would quickly spiral into something completely unusable for anyone. We’re not limited by JavaScript in this regard, but rather we think adding toggles for everything would make the product less intuitive, and would require people using it to think about far more things unnecessarily. I appreciate you sharing your thoughts, and we’re definitely open to revisiting any product decision as we continue to get more feedback.
