### ISSUE TITLE
Word wrap in history tab

### ISSUE THREAD

**Issue by paul321** [desktop/desktop#7136]
Can we please have a word wrap enable / disable option in history?
We ask for it because it's very annoying, screenshot attached
![Untitled](https://user-images.githubusercontent.com/555502/54781342-aeff2080-4c24-11e9-9754-3859643d81ed.png)

**Comment by billygriffin** [comment]
Hi @paul321, thanks for the issue! We haven't heard this feedback from any other users despite it being the default behavior of a core part of the app since it originally shipped. I'm curious how it would be beneficial for you in this context, and why it's particularly annoying or painful so I can understand what impact we might be causing that we don't understand particularly well yet. We're open to reconsidering if we get quite a bit more feedback about how this causes problems for folks, but this isn't something we intend to support in the near-term as the default behavior seems to work quite well for folks. Thanks again!
