### ISSUE TITLE
filter text disabled when current branch selected in rebase dialog

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#7139]
If you select the current branch in the rebase model, the modal filter will lock up temporarily until you switch branches. 

For consistency with the merge conflict modal, we should allow the branch to be selected, but keep the `rebase` button disabled. 

The filter should always remain intact and functional.

Repro:
- Select `rebase from current branch` option in the menu
- Modal opens, now select the current branch in the branch list, or type it in the filter.

![image](https://user-images.githubusercontent.com/14828183/54793662-8ad11e80-4be7-11e9-80e4-598e931d3304.png)

24c697c144, mac

**Comment by shiftkey** [comment]
@tierninho 

> If you select the current branch in the rebase model, the modal filter will lock up temporarily until you switch branches.

To clarify, are you referring to the filter and the submit button? The only other part that can be interacted with is the close button, and that seems to work fine.

The submit button being disabled when you select your current branch comes from the Merge Branch dialog, and we don't show any extra messaging or tooltip there. I'd be open to surfacing extra context.

The filter text being disabled is a probable bug due to disabling the whole form when this condition is true:

https://github.com/desktop/desktop/blob/55f51c894dad68648525a3af9e09933dc2e95e92/app/src/ui/rebase/rebase-branch-dialog.tsx#L107

**Comment by tierninho** [comment]
> The filter text being disabled is a probable bug due to disabling the whole form when this condition is true.

Yes, the filter was what I was referring to. The submit button should remain disabled.

> I'd be open to surfacing extra context.

Sounds good 👍
