### ISSUE TITLE
tt5335

### ISSUE THREAD

**Issue by Radosia** [desktop/desktop#7148]
**Please describe the problem you think should be solved**
A clear and concise description of what the problem is and who else might be impacted. Screenshots are encouraged.

**Comment by tierninho** [comment]
@Radosia  We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
