### ISSUE TITLE
Flashing of black squares in the app window

### ISSUE THREAD

**Issue by konopkoman** [desktop/desktop#7201]
Flashing of black squares in the app window, look at attached video. Win10/64
[VID_20190402_114807.zip](https://github.com/desktop/desktop/files/3033084/VID_20190402_114807.zip)

**Comment by niik** [comment]
Hi @konopkoman,

Without knowing more about your environment I would suspect this is due to your graphics card (or even more likely) your graphics card drivers. I would suggest ensuring that you have the latest version of your graphics card driver installed and if that fails try [disabling hardware acceleration](https://github.com/desktop/desktop/blob/f68738aa9fb295ff90e3bd8a1f9c16483b4ac7c3/docs/known-issues.md#i-get-a-black-screen-when-launching-desktop) by setting the `GITHUB_DESKTOP_DISABLE_HARDWARE_ACCELERATION` environment variable on your machine.

Please let us know if that solves your issue

**Comment by tierninho** [comment]
@konopkoman As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
