### ISSUE TITLE
what manual conflict??

### ISSUE THREAD

**Issue by dapple0110** [desktop/desktop#7214]
## Description

What is manual conflict?
I setted '*.jpg binay' in gitattributes.
but 'manual conflict' was displayed.
and same result - 'Use the modified file from master', 'Use the modified file from origin/master'

i can't select their version that pushed latest.

## Version

* GitHub Desktop: 1.6.5

* Operating system: windows 10, osx 10.14.3
<img width="1234" alt="screenshot" src="https://user-images.githubusercontent.com/46529026/55538181-d233d080-56f8-11e9-8f3e-11ccfad81ab1.png">

## Steps to Reproduce

1. 'user A' commit and push 'file A'(jpg file)
2. 'user B' edit 'file A' in local and commit 'file A'
3. 'user B' fetch and merge from repository.
4. conflict 'file A'.

### Expected Behavior

I Hope to choose one of two selection. 'use my version file A' or 'use latest repository version file B'.

### Actual Behavior

Github desktop displayed 'use the modified file from master', 'use the modified file from origin/master'(too confused words..)

there is same result that use my version whether I choice upper message or bottom message.

**Comment by niik** [comment]
Hi @dapple0110, thanks for opening this. I can definitely see how this can be confusing and this is valuable feedback for us as we continue to iterate on the conflict resolution flow in the application (cc @billygriffin, @outofambit).

Let me try to shine some light on what's going on here. You said:

> I Hope to choose one of two selection. 'use my version file A' or 'use latest repository version file B'.

That is what the application is letting you do although it's using different terminology. Your `master` branch exists in two places, on your local machine, and on the remote (or "server" in other words). The branch on the server is being referred to here as `origin/master`. Origin being a Git term and convention meaning the default remote (or "server"). So what GitHub Desktop is asking you to do is choose between the file on your local branch (`master`) or the file on the remote/server `origin/master`.

I'd recommend taking a look at the chapter in the book Pro Git titled [Remote Branches](https://git-scm.com/book/en/v2/Git-Branching-Remote-Branches). The entire book is available for free at https://git-scm.com/book/en/v2 and is an excellent resource to understanding the intricacies of Git.

I hope this helps clarify things. Since we don't consider this to be a bug per-se I'm going to close this issue for now but feel free to add more comments if there's anything else we can do to help.
