### ISSUE TITLE
Add Syntax Highlighting for TeX, PGP, Pascal and 17 other languages

### ISSUE THREAD

**Issue by KennethSweezy** [desktop/desktop#7217]
**Add support for syntax highlighting of Tex, PGP, Pascal and 17 other languages**
1. Open a .tex, .rq, .styl, .soy, .st, .slim, .sieve, .ss, .sls, .scm, .rst, .rpm, .q, .pp, .pug, .proto, .properties, .ini, .pig, .pgp, .m, .oz, or .pas file.
2. Observe that there is no syntax highlighting on the file.

**Wireup CodeMirror to provide syntax highlighting**
Add TeX, SparQL, Stylus, Soy, Smalltalk, Slim, Sieve, Scheme, reStructuredText, RPM, Q, Puppet, Pug, ProtoBuf, Properties, Apache Pig, PGP, Octave, Oz, and Pascal to the syntax highlighting docs.
Add configuration for TeX, SparQL, Stylus, Soy, Smalltalk, Slim, Sieve, Scheme, reStructuredText, RPM, Q, Puppet, Pug, ProtoBuf, Properties, Apache Pig, PGP, Octave, Oz, and Pascal to syntax highlighting file.

At the time of submitting this issue, I have [created a pull request in desktop/highlighter-tests](https://github.com/desktop/highlighter-tests/pull/35) containing test files for all of the modes listed above.

**Comment by niik** [comment]
Hi @KennethSweezy,

Thank you so much for the work you've already put in here! The biggest reason as to why we didn't include all languages to start with was wanting to keep the load times down for the highlighting web workers but since https://github.com/desktop/desktop/pull/4764 landed we only load the modes we need at the time so there should be no performance overhead in adding these. As such we'd be delighted if you were to create a PR to add these languages to our list of supported syntax highlighting.

I assume you're interested in doing so given that you've already done a lot of the work over in highlighter-tests so I'm going to assign you to this issue. If that's premature of me please let me know and I'll rectify that.

We're currently ramping up to ship our next release so please bear with us if your upcoming PR doesn't get reviewed right away, we'll likely have to wait to bring that in until after the next major version has shipped and the dust has settled.

**Comment by KennethSweezy** [comment]
@niik Thank you for assigning this issue to me. I will begin work on this ASAP.

**Comment by varkor** [comment]
There is also no syntax highlighting for `Makefile`s, which would be nice to have.

**Comment by HavrHorosUazar** [comment]
БЕЙСИК GUD.
