### ISSUE TITLE
Rebase suggestions and questions for post release 

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#7218]
Had some questions / suggestions for rebasing. Nothing here is urgent and can be address post 1.7.0 release.

- The `resolve` carrot is warped. Shouldn't it look like the Open in Editor one?
<img width="106" alt="Screen Shot 2019-04-04 at 7 55 42 AM" src="https://user-images.githubusercontent.com/14828183/55580088-78f67d80-56b5-11e9-901d-346743ba359c.png">
<img width="114" alt="Screen Shot 2019-04-04 at 8 39 53 AM" src="https://user-images.githubusercontent.com/14828183/55580091-798f1400-56b5-11e9-840f-bf7cc953a17c.png">

- When using `git rebase --skip` in the cmd line, I noticed there was nothing in the Desktop UI that popped up. Does anything from this need to be surfaced in the Desktop UI?
<img width="564" alt="Screen Shot 2019-04-04 at 8 01 47 AM" src="https://user-images.githubusercontent.com/14828183/55580273-eacec700-56b5-11e9-9a93-93d575396de1.png">

- Should we use an alternate word instead of "Continue rebase" as I noticed that when the button is active, it does not entirely mean the same thing as `git rebase --continue` cmd. This may be confusing to newer users, but I have no strong feelings on this one.
<img width="913" alt="Screen Shot 2019-04-04 at 8 12 38 AM" src="https://user-images.githubusercontent.com/14828183/55580468-5153e500-56b6-11e9-9ad4-b48b04bdfd05.png">

**Comment by shiftkey** [comment]
@tierninho thanks for this input!

> The `resolve` carrot is warped. Shouldn't it look like the Open in Editor one?

Probably - these styles were borrowed from Merge Conflicts so I'll see what's available there.

> * When using `git rebase --skip` in the cmd line, I noticed there was nothing in the Desktop UI that popped up. Does anything from this need to be surfaced in the Desktop UI?

I'm not sure I understand this bit - what `git rebase --skip` does is ignore the current commit in the rebase (because it doesn't contain any tracked changes to use) and continues rebasing commits until it either completes successfully or encounters conflicts.

For the example screenshot above, it looks like you've got conflicts again to resolve, and switching back to Desktop should show those. Do you recall what Desktop did at the time? There might be some context in the log about whether it was able to detect the conflicted state again...

> * Should we use an alternate word instead of "Continue rebase" as I noticed that when the button is active, it does not entirely mean the same thing as `git rebase --continue` cmd.

I've got mixed feelings on this - `--skip` is mostly just like `--continue` but it drops the current path:

>[`--skip`](https://git-scm.com/docs/git-rebase#Documentation/git-rebase.txt---skip)
>   Restart the rebasing process by skipping the current patch.

I feel like changing the UI to sometimes say "we're gonna skip this commit because there's nothing to do" feels confusing in a different way, especially to users who aren't familiar with what `git rebase` is doing underneath. I'd hold off on exposing more context until we've gotten feedback from users about what makes sense and what might be a source of confusion.

**Comment by tierninho** [comment]
> Do you recall what Desktop did at the time? 

When I use `git rebase --skip` it goes to the next conflict, as expected. If you use `git rebase --skip` multiple times in a row, eventually you run our of conflicts and the modal closes in Desktop. This is what I'd expect to happen.

**Comment by tierninho** [comment]
Piling on top of the "Resolve" comment stated above, I think we should add the "Are you sure? confirmation dialogue when this is present *and* the user has already selected an option from the dropdown.  

<img width="250" alt="Screen Shot 2019-04-05 at 10 13 07 AM" src="https://user-images.githubusercontent.com/14828183/55653848-72d2d080-578b-11e9-8ab0-34269aad0723.png">

**Comment by shiftkey** [comment]
> Piling on top of the "Resolve" comment stated above, I think we should add the "Are you sure? confirmation dialogue when this is present _and_ the user has selected the "modified" option from the dropdown

I think this was caught because of #7255 - thankfully this has been fixed in #7261 and went out with the `1.7.0-beta4`.

**Comment by shiftkey** [comment]
Coming back to the last outstanding questions:

> Does anything from this need to be surfaced in the Desktop UI?

I'm not sure what we can do here if the rebase was completed outside the app aside from closing out the dialog because we no longer detect `.git/REBASE_HEAD` - we could poke at the reflog to see some recent activity, but I think if you're finishing the rebase outside the app you don't need our help.

If you `rebase --skip` ahead and encounter conflicts Desktop should update itself when you switch back, to help you resolve these conflicts and continue. 

> Should we use an alternate word instead of "Continue rebase" as I noticed that when the button is active, it does not entirely mean the same thing as `git rebase --continue` cmd.

You're right in that we might `--skip` underneath if there's no changes to apply as part of the commit, but I'm fine with this button representing "proceed with the rebase" without being a literal representation of the plumbing.

I've got some other feedback about the information we show when setting up the rebase that I'd like to tackle before this goes out to everyone. I'll keep these things in mind, but for the moment I'm going to close this out to focus on the current iteration of the rebase flow.
