### ISSUE TITLE
"Rebase in progress" modal freezes due to unstaged files

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#7223]
I ran across an instance where the "Rebase in progress" dialogue would just freeze and thereby force the user to quit Desktop in order to recover. It seems the uncommitted file warning interrupted the rebase flow of things, and Desktop was unable to fix it. I was able to repeat this a few times to make sure it was indeed a bug. 

I had an odd setup, but regardless there may be a bug buried in here. 

**Update:** After committing the file, the rebase worked. We can attribute the problem to the uncommitted file.

~~Setup:~~
~~Enterprise repo, logged out~~
~~One uncommitted file~~
~~Rebasing onto master~~
~~In a `Pull origin with rebase` state~~

![image](https://user-images.githubusercontent.com/14828183/55591555-802b8480-56d1-11e9-92c9-2331b6995a25.png)

Logs:
```
debug: [ui] Executing getRemotes: git remote -v
debug: [ui] Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT
debug: [ui] Executing getConfigValueInPath: git config -z trailer.separators
debug: [ui] [AppStore] initializing compare state
debug: [ui] Executing getCommits: git log HEAD --date=raw --max-count=100 --pretty=%H%x1F%h%x1F%s%x1F%b%x1F%an <%ae> %ad%x1F%cn <%ce> %cd%x1F%P%x1F%(trailers:unfold,only) -z --no-show-signature --no-color --
debug: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z
debug: [ui] Executing getConfigValueInPath: git config -z trailer.separators
debug: [ui] Executing getChangedFiles: git log 5ea4c974617d7d284a8894046f5c375fd1a7db76 -C -M -m -1 --no-show-signature --first-parent --name-status --format=format: -z --
debug: [ui] Executing getCommitDiff: git log 5ea4c974617d7d284a8894046f5c375fd1a7db76 -m -1 --first-parent --patch-with-raw -z --no-color -- dsfsd
debug: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo
info: [ui] launching: 1.7.0-beta1 (Mac OS 10.14.4)
info: [ui] execPath: '/Users/tierninho/github/desktop/dist/GitHub Desktop-dev-darwin-x64/GitHub Desktop-dev.app/Contents/Frameworks/GitHub Desktop-dev Helper.app/Contents/MacOS/GitHub Desktop-dev Helper'
debug: [ui] Executing getCommitsInRange: git rev-list fcaea364d8c2c57af9f4309d293df1babed3f0fc..5ea4c974617d7d284a8894046f5c375fd1a7db76 --reverse --oneline --no-abbrev-commit --
info: [ui] [rebase] starting rebase for sdfsdf-1 at 5ea4c974617d7d284a8894046f5c375fd1a7db76
info: [ui] [rebase] to restore the previous state if this completed rebase is unsatisfactory:
info: [ui] [rebase] - git checkout sdfsdf-1
info: [ui] [rebase] - git reset 5ea4c974617d7d284a8894046f5c375fd1a7db76 --hard
debug: [ui] Executing getCommitsInRange: git rev-list master..sdfsdf-1 --reverse --oneline --no-abbrev-commit --
debug: [ui] Executing rebase: git rebase master sdfsdf-1
error: [ui] `git rebase master sdfsdf-1` exited with an unexpected code: 1.
First, rewinding head to replay your work on top of it...
error: The following untracked working tree files would be overwritten by checkout:
	.gitignore
Please move or remove them before you switch branches.
Aborting
could not detach HEAD
(The error was parsed as 37: Some of your changes would be overwritten.)
debug: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z
debug: [ui] Executing getWorkingDirectoryDiff: git diff --no-ext-diff --no-index --patch-with-raw -z --no-color -- /dev/null .gitignore
info: [ui] [rebase] completed rebase - got Error and on tip 5ea4c974617d7d284a8894046f5c375fd1a7db76 - kind Valid
```

**Comment by tierninho** [comment]
Git seems to think no rebase is in progess:

```
➜  blah git:(sdfsdf-1) ✗ git rebase --abort
No rebase in progress?
➜  blah git:(sdfsdf-1) ✗ git rebase
Cannot rebase: You have unstaged changes.
Please commit or stash them.
```

**Comment by shiftkey** [comment]
So I think there's two distinct things in play here:

> I ran across an instance where the "Rebase in progress" dialogue would just freeze and thereby force the user to quit Desktop in order to recover.

This was the scenario I stumbled upon on Monday, and in a nutshell:

 - inside `RebaseFlow` we'd do this check to see if we found new conflicts while showing progress

https://github.com/desktop/desktop/blob/64a075b1019b9e4358777449ef87cdebde52c1ac/app/src/ui/rebase/rebase-flow.tsx#L143-L149

 - the `this.state.lastResolvedConflictsTip !== conflictState.currentTip` was a check ensure it only switches when the tip of the repository has moved
 - I saw your same behaviour when a rebase happens to skip consecutive commits (because the changes became unnecessary after resolving a conflict) which meant the tip was unchanged the second time (so it wouldn't skip)
 - this lead me to opening #7203 which kills off this code and push the transitions down into `AppStore`

I'm on the lookout for any cases that might look like this, but for the moment the example rebase I had on Monday completes without needing a restart.

> After committing the file, the rebase worked. We can attribute the problem to the uncommitted file.

This specific message looks like it blocks switching branches because the uncommitted change clashes with something on the base branch:

```
First, rewinding head to replay your work on top of it...
error: The following untracked working tree files would be overwritten by checkout:
	.gitignore
Please move or remove them before you switch branches.
Aborting
could not detach HEAD
(The error was parsed as 37: Some of your changes would be overwritten.)
```

There's a specific `GitError` here that we can detectt, and after #7203 lands I'll see if I can isolate a repro so the behaviour here (show the dialog warning about the change) is the same as what happens when attempting a merge.

**Comment by tierninho** [comment]
Repro steps:
- make change to `gitignore` file so it shows in Changes list
- attempt rebase
