### ISSUE TITLE
Update from default branch menu item provides no feedback when branch is already up to date

### ISSUE THREAD

**Issue by bikram-neetable** [desktop/desktop#7227]
## Description

Updating from the default branch provides no feedback when the default branch is already up to date with the current branch.

## Version

* GitHub Desktop:

* Operating system: platform-independent

## Steps to Reproduce

1. Checkout the default branch
2. Create a new branch based on the default branch
3. Check out said branch
4. Click the 'update from [default branch]' menu item underneath the Branch menu

### Expected Behavior

It'd be nice if we showed a banner saying that the branch is already up to date

### Actual Behavior

There's no feedback that the menu item was clicked.

**Comment by niik** [comment]
Hi @bikram-neetable, I suspect the reason you're not seeing anything when you attempt to update from master is because there are no changes on master relative to your current branch.

If you attempt to merge manually using the command line I suspect you'll see something like this

```
$ git merge master -n
Already up to date.
```

Now, that should hopefully explain why it would appear as if the update from master menu item "does not do anything". That said I definitely don't think this is ideal, I think we should still show a message. but one similar to what Git outputs.

I'm going to assign this to myself in order to bring it up at the next planning meeting to see if this is something we'd consider looking into.

**Comment by bikram-neetable** [comment]
Hi Markus,

Well it is a bug. Because i compared the changes after using "Update from Master" button.
The bug is - It shows that already in sync with Master but changes are not reflecting.

Here is the scenario where i faced this issue

1) I created 2 branches from Master named "A" and "B"
2) Made some changes in both the branches.
3) Did "Update from Master" in branch "B".
4) Merged changes of "B" into "A".
5) Reverted the changes of "B" from "A"
6) Did "Update from Master" in branch "A"

When i compare the "A" and master branch, i see the changes of Master are not reflecting in A
And i checked it to confirm.

Regards,
Bikram
________________________________

**Comment by niik** [comment]
@bikram-neetable I _think_ what you described would lead you to the same scenario that I outlined above, i.e. that there are no new changes on master for you to bring in to branch "A". Let me try to step through your steps and you can tell me if I'm missing something.

## The Setup

Let's call the tip commit on `master` `0001`

## The Steps

1. Create Branch A (tip of Branch A is now `0001`) and Branch B (tip of Branch B is now `0001`).

<img width="123" alt="image" src="https://user-images.githubusercontent.com/634063/55639229-2b6b3500-57c9-11e9-9faf-7f5ee8878657.png">

2. Make some changes in Branch A (tip of branch A is now `0002`) and some changes in Branch B (tip of Branch B is now `0003`).

<img width="248" alt="image" src="https://user-images.githubusercontent.com/634063/55639289-52c20200-57c9-11e9-8a6d-9cffbeb1f092.png">


3. Go back to master, make some changes (tip of master is now `0004`)

<img width="258" alt="image" src="https://user-images.githubusercontent.com/634063/55639553-ef849f80-57c9-11e9-977d-6d6824ed4771.png">


4. Checkout branch B and merge master into branch b (tip of branch B is now `0005` which is a merge commit between `0002` and `0004`).

<img width="403" alt="image" src="https://user-images.githubusercontent.com/634063/55639606-15aa3f80-57ca-11e9-974b-cff3c3f27ead.png">

5. Checkout branch A and merge changes from Branch B (tip of Branch A is now `0006` which is a merge commit between `0002` and `0005`)

<img width="500" alt="image" src="https://user-images.githubusercontent.com/634063/55639748-5f932580-57ca-11e9-8433-d7cca2da41cb.png">

6. Revert the `0006` merge commit (tip of Branch A is now `0007`)

<img width="652" alt="image" src="https://user-images.githubusercontent.com/634063/55639814-90735a80-57ca-11e9-8578-da75e3c89ca6.png">

7. Execute 'Update from master' and no feedback is given

The important part here is that at point 6 there are no commit on master that's not already reachable from the tip commit in Branch A.

I suspect the confusion here is between reverting a commit and undoing a commit. A reverted commit is the exact opposite to the commit it's reverting. It signals that you've decided that you do have decided against using the changes in a particular commit from here on. Had you undone the `007` commit it would have been as if the merge from branch b never happened and in that case the `Update from master` button would have had changes to bring into Branch A.

I hope that helps clarify things a little. I still think that the issue here is valid, we should be showing some form of feedback when a merge results in no changes being brought into the branch.

**Comment by billygriffin** [comment]
Hi @bikram-neetable! Just following up on @niik's comment above to find out if that sounds right based on what you're seeing.

**Comment by tierninho** [comment]
@bikram-neetable As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
