### ISSUE TITLE
[Stashing] Error when switching branches while in a merge conflict state

### ISSUE THREAD

**Issue by iAmWillShepherd** [desktop/desktop#7247]
Stashing will fail when in the middle of a merge conflict so we can either check merge state at branch checkout to prevent the stash dialog from appearing or we disable the branch selector while in a merge conflict state. 

**Repro steps**
1. Produce a merge conflict
1. Dismiss the conflict resolution dialog
1. Checkout a new branch
1. Select either option in the stash dialog and click _Switch Branch__
1. Observe that stash dialog hangs around

![2019-04-09 09 51 21](https://user-images.githubusercontent.com/1715082/55810442-2bab4f00-5aad-11e9-8619-56d32e6d99f6.gif)

The errors in the console are expected, I'm not handling them because I want these errors to be surfaced in the logs.

**Comment by tierninho** [comment]
A side-effect of this results in any existing stashes being wiped. For instance, a user has stash on a branch, and later decides to resolve a merge commit manually, but ultimately wants to switch to another branch before finishing the merge commit. 

Although the stash dialogue does ask the user if they want to stash and override the changes, the new stash fails because the current index must be resolved first. Now the original stash is lost. 

We should not allow stashing in a merge/rebase conflict state.

1.7.0-beta6, mac

**Comment by billygriffin** [comment]
I'm not positive about this, but my gut reaction is that the risk of conditionally disabling things here might be greater than the risk of people getting into this situation in the first place, especially since we haven't seen it reported since shipping this last year. Happy to revisit if others disagree, but I'm going to close this for now.
