### ISSUE TITLE
[Stashing] Move away from git log and use stash list with --pretty format

### ISSUE THREAD

**Issue by iAmWillShepherd** [desktop/desktop#7254]
Desktop currently uses `git log -g refs/stash --pretty="%H@%gs"` to get the list of stash entries in a repo. This was done because Desktop relies on the commit SHA of the stash entry to uniquely identify them. 

https://github.com/desktop/desktop/blob/50cb1fa524b9a41ece7bc09e7702ecf231a62061/app/src/lib/git/stash.ts#L29-L45

While not necessarily harmful, this causes errors to be logged in the console when `.git/logs/refs/stash` is not present. Since the file only exists when there is at least one stash, this error can get logged often and pollute the logs.

<img width="715" src="https://user-images.githubusercontent.com/359239/55893187-c70ff300-5b85-11e9-809b-89b79d482274.png">

https://github.com/desktop/desktop/pull/7210#issuecomment-480456627

Using `git stash list --pretty=%H@%gs` will accomplish the same goal as using `git log -g refs/stash` with the added benefit that it will not fail when `.git/logs/refs/stash`  does not exist.

```shell
$ git stash list --pretty=%H@%gs
7c4cced8d4763a0538bc6c0a6f05f7e050cd3a4b@WIP on linux: 5b1f0a6b3 tidy up badges
$ git stash drop
Dropped refs/stash@{0} (7c4cced8d4763a0538bc6c0a6f05f7e050cd3a4b)
$ git stash list --pretty=%H@%gs
$ echo $?
0
$ git log -g --pretty=%H%gs refs/stash
fatal: ambiguous argument 'refs/stash': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

Shoutout to @shiftkey for letting me know `git stash list` accepts a pretty format! 🥇

**Comment by niik** [comment]
If we want to switch got git stash list that's okay but I feel like this is a mischaracterisation of the reason:

> This was done because Desktop relies on the commit SHA of the stash entry to uniquely identify them.

This was not, in my mind, the reason. My reason was twofold, first to avoid running three executables where one would suffice (git stash, git rev-parse, and git log).

The second being that `git stash` differs between the platforms (i.e. it's a shell script on macOS/Linux and a builtin c program on Windows) and I felt it would be wise to try to avoid that ambiguity as far as possible. Furthermore, since the only thing `git stash list` does is to run `git rev-parse refs/stash` before running `git log` I didn't see why simply check to see if the exit code of `git log` is 128.

This is the [implementation of git stash list](https://github.com/git/git/blob/e35b8cb8e212e3557efc565157ceb5cbaaf0d87f/git-stash.sh#L402-L405) in `git/git`

```sh
have_stash () {
	git rev-parse --verify --quiet $ref_stash >/dev/null
}

list_stash () {
	have_stash || return 0
	git log --format="%gd: %gs" -g --first-parent -m "$@" $ref_stash --
}
```

In fact, we rely on this exact behavior of checking to see whether the exit code of `git log` is 128 for non-existing references already:

https://github.com/desktop/desktop/blob/50cb1fa524b9a41ece7bc09e7702ecf231a62061/app/src/lib/git/log.ts#L102-L105

**Comment by niik** [comment]
I think a reason to switch to `git stash list` that I would happily get behind would read more like this: 

> We're willing to accept a, likely, small loss in performance as well as the platform inconsistency in order to guard ourselves against future alterations of `git-stash` with the added benefit of making our logic easier to understand for those not intimately familiar with the inner workings of Git

**Comment by iAmWillShepherd** [comment]
I see, I had forgotten to consider the performance implication. I'm happy to close this out in favor of just adding the exit code `128` to the list of expected output. While guarding for future changes to the implementation would be cool, I'd prefer waiting until it becomes a problem and avoid the performance hit.

cc/ @shiftkey for thoughts on keeping the current implementation.

**Comment by iAmWillShepherd** [comment]
Removed myself from issue until we decide on the best path forward.

**Comment by outofambit** [comment]
> I'm happy to close this out in favor of just adding the exit code 128 to the list of expected output.

it looks like this was done in https://github.com/desktop/desktop/commit/6eae14970d20f5446a4274e0bcc0d84fdad731bb (via https://github.com/desktop/desktop/pull/7268), so i'm going to close this.
