### ISSUE TITLE
[Stashing] New branch is created in background when uncommitted changes are present

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#7288]
If there are files in the Changes column on existing branch and you create a new branch, the branch is created in the background but now you remain on the existing branch.

**Expected result**: user is taken to the new branch and asked to stash/move changes along the way. (Note: You can select the new branch and stash, but now it takes an additional step). 

Not much in the logs:

```
s:unfold,only)%00%1F refs/heads/sdfsdf
debug: [ui] Executing getConfigValueInPath: git config -z trailer.separators
```

5977a42c21, mac

**Comment by billygriffin** [comment]
😬 Yeah, this one seems more important because it disrupts previous expected behavior that creating a branch should take you to the branch you've just created. My gut says this is pre-beta, but I'm open to post-beta and pre-production. This definitely has to be fixed prior to the production release, unless I'm not understanding it correctly.

**Comment by iAmWillShepherd** [comment]
When creating a new branch, should I show the stash dialog or take the path of least resistance and move the changes over to the new branch?

**Comment by iAmWillShepherd** [comment]
I went ahead and updated the flow to reflect what @tierninho expected.

**Comment by billygriffin** [comment]
Great, thanks @iAmWillShepherd. If there are uncommitted changes, we definitely want to incorporate the stashing option into the "Create new branch" flow as well, and sounds like that's what you've done.
