### ISSUE TITLE
[stashing] display right-click menu in stash diff

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#7290]
The right-click menu is also nice when clicking on an individual file, however its use in the stash diff page may lead to two conflicting files.

Yes, the user can still get in this position otherways, but let's not make it too easy. I suggest we remove some or all of the items in the right-click menu.

<img width="840" alt="Screen Shot 2019-04-12 at 3 14 17 PM" src="https://user-images.githubusercontent.com/14828183/56072773-fb2a1600-5d35-11e9-9e9f-6d9e68fb91cd.png">

5977a42c21, mac

**Comment by billygriffin** [comment]
What's interesting about this is that "Open in..." anything might be misleading because these are stashed changes and therefore won't be reflected in the current state of the file until they're restored. So I think I agree with disabling most of the functionality of the context menu (maybe with the exception of "Copy File Path"?), though I think it's a nice to have and definitely doesn't need to get in prior to beta.

**Comment by shiftkey** [comment]
I'm going to look into what's required to be able to disable the context menu. Currently this list is hard-coded inside `file-list.tsx` and it always behaves the same:

https://github.com/desktop/desktop/blob/f3898a8f58aa1d8a3f74e3353b4cff4bc43006f9/app/src/ui/history/file-list.tsx#L107-L159

**Comment by shiftkey** [comment]
For the moment the stash diff does not show a context menu, as #7307 was merged.

I've tweaked the title to indicate this issue can now focus on what to show in the context menu, but feel free to open a fresh issue here if you prefer.

**Comment by billygriffin** [comment]
I'm inclined to just leave it here for now unless we get feedback on it. The stash doesn't need to be an exit point imo unless we hear from users that there's a reason why they're using it for some purpose we haven't thought about. I'm going to close this issue but happy to reopen if y'all disagree.
