### ISSUE TITLE
What's the function of pull request in GitHub Desktop?

### ISSUE THREAD

**Issue by TerryChan** [desktop/desktop#7292]
I found there is a pull request tab in GitHub Desktop, but I don't know what's the function of the pull request in GitHub Desktop, could someone explain it? 
I found it's just list the pull requests I created in GitHub website, When I click a pull request, looks like nothing happen, it didn't show the pull request info, can we do code review for a pull request in GitHub Desktop?
![image](https://user-images.githubusercontent.com/5396286/56090826-fa31e980-5ed9-11e9-9ccd-e8ae3ec77764.png)

**Comment by Cvbeek** [comment]
My Wallet Authentication Code: 6F01E

**Comment by billygriffin** [comment]
Hi @TerryChan, thanks for the question! The list should display all the pull requests for a given repo, and when you click on one, your current branch should switch to the pull request branch so you're able to look at the current state of the pull request locally. You can't do code reviews in Desktop, but we've found that some people like to use that functionality to check out the PR branch locally while they're doing a code review so they can, for example, build the app in the same state of the PR to check to ensure things are working as expected. I'm going to close this issue, but hope that's helpful and feel free to ask any further questions!

**Comment by shiftkey** [comment]
> but we've found that some people like to use that functionality to check out the PR branch locally while they're doing a code review so they can, for example, build the app in the same state of the PR to check to ensure things are working as expected

To add to this comment, PRs submitted from forks are challenging to use from the command line, and Desktop takes care to manage all of this heavy lifting behind the scenes when you choose to checkout a PR:

 - add a new remote associated with the fork
 - checkout the branch associated with the PR to work with it locally
 - set the tracking branch so that new commits pushed by the contributor can be `pull`-ed by the maintainer
 - maintainers can push new commits to the contributor branch if they have permission to do so

There's less work when the PR is from a local branch, but this is a common pain point for open source maintainers, and is something I use in Desktop day-to-day.
