### ISSUE TITLE
Folder name change

### ISSUE THREAD

**Issue by Zanatus** [desktop/desktop#7293]
Hi, 
when I change folder name from "TEST" to "Test" the github desktop app(win) doesn't see it as a change, and if I check online on the github page, in the folder tree the folder shown will be "TEST". How can I make Github recognize the capitalization in words on foldernames?

Cheers

**Comment by steveward** [comment]
Thanks for contributing @Zanatus! Git has an `ignorecase` option that is set to `false` by default. It sounds like your repository config or global .gitconfig has the value set to `true`, which is causing Git to ignore those case changes. To change this configuration option you will need to launch the command line (`Repository` > `Open in <command_line_application>` in GitHub Desktop) and run the following command:

`git config --local core.ignorecase false`

This will set the config value on a per-repository basis. If you would like to set this for all repositories you can use the `--global` flag instead of the `--local` flag. I'd also recommend reading the [official documentation](https://git-scm.com/docs/git-config#Documentation/git-config.txt-coreignoreCase) about this.

I hope that helps! I'm going to close this issue out, but let me know if you have any other questions.

**Comment by steveward** [comment]
@Zanatus I would also recommend reading through @shiftkey's comment here about case changes:

https://github.com/desktop/desktop/issues/2672#issuecomment-329011490

Git tries to detect how it should handle case changes based on your operating system and the repository, so please be wary that changing this value could cause other issues.

**Comment by haroldaexcomweb** [comment]
you can also do a throwaway commit to rename it to TEST-1 and then do another commit renaming it to test
