### ISSUE TITLE
Contextual menu is white even though appearance theme is set to dark.

### ISSUE THREAD

**Issue by daf121** [desktop/desktop#7308]
menu should be dark too.

**Comment by tierninho** [comment]
@daf121 Thanks for filing. Possible to add a screenshot so we can see the menu you are referencing? Thanks for the contribution.

**Comment by daf121** [comment]
Yes: ![image](https://user-images.githubusercontent.com/6278151/56176542-748d6700-5fc9-11e9-8434-7b1c691923c8.png)

Contextual menu is dark on windows explorer when theme is set to dark.

**Comment by shiftkey** [comment]
> windows explorer's contextual menu is dark on when theme is set to dark.

I think this is a newer part of Windows 10 - @daf121 can you confirm which build of Windows you're running by running this command and attaching the output:

```
> cmd /c ver
```

With that bit of information, the next steps are to investigate upstream about whether this is something already supported in Electron or whether there needs to be support added there.

**Comment by daf121** [comment]
output: Microsoft Windows [Version 10.0.17763.437]

it's basiclaly Windows 10, version 1809

https://wccftech.com/enable-windows-10-file-explorer-dark-mode/

**Comment by shiftkey** [comment]
This is something that need to be addressed in Electron itself, and I've opened an issue to start the discussion with the maintainers: https://github.com/electron/electron/issues/18119

Closing this out because this isn't something we can currently address inside Desktop. @daf121 please follow along with the upstream discussion.
