### ISSUE TITLE
Files marked with checkbox should be staged for commit for consistency with other apps and terminal

### ISSUE THREAD

**Issue by castus** [desktop/desktop#7321]
**Please describe the problem you think should be solved**
To have a consistent experience with other apps as well as terminal, files marked with checkbox should be staged for commit. 

Example:
When I have some files with checkboxes checked, when I run `git status` in the terminal I should have those files presented in `Changes staged for commit`. Files that are not marked with checkbox should be in the section `Changes not staged for commit`.

**[Optional] Do you have any potential solutions in mind?**
You can take an inspiration from SourceTree app which works exactly how I describe it. This is very convenient for me, because I can start marking files to commit and end with the terminal or vice versa.

**Comment by billygriffin** [comment]
Hi @castus, thanks so much for the issue. This has come up a few times, but we've found that overall people are generally happy with the approach we've taken. As you note, Desktop effectively bypasses the index. This makes partial committing work nicely and the app only have to worry about the index when the user is making the commit. Obviously there are some downsides to this approach, the biggest one being the issue that you describe. However, we find that the vast majority of users aren't bouncing back and forth between Desktop and other apps during the commit prep process.

I'm curious what your workflow is that would make you want to stage some files in Desktop, and then pick it up from there in Terminal, or visa versa?

For now, I'm going to close this issue since it was an intentional design choice, but we're always open to revisiting things like this if we feel like there's sufficient evidence that a lot of people are negatively affected. Thanks again!

**Comment by castus** [comment]
I respect your design decision however I cannot agree with it. For me GH Desktop is a GUI for Git. It should work with the cooperation from both sides. I love it because it is blazing fast but I cannot use it because of issue I mentioned. Aside of my workflow, all famous Git Clients like Tower or SourceTree did this. Maybe this is not a key feature, but I will expect that you will implement it in near future. However from your words I think it won't gonna happened. This makes me sad :(

**Comment by billygriffin** [comment]
Sorry to hear that @castus. As I mentioned, if we see enough evidence in hearing from users and talking to more of them and seeing how it negatively impacts them, we're always open to revisiting things like this. And we definitely don't take the approach of implementing a feature because it's in other Git clients, as we think Desktop should be differentiated from others a the simplest and most intuitive product there is for getting your workflows done. I really appreciate you sharing though.

I still am interested in your workflow and what makes you want to bounce back and forth between Desktop and Terminal during the process of committing files?

**Comment by castus** [comment]
I started learning GIT only from the Terminal. There is one very annoying thing for me; when I need to check changes to stage. That's why I use all GIT clients only for visually check changes and stage/unstage files. All other things (commit, rebase, reset, etc.) I'm doing from the terminal. All GIT clients that I've tried (SourceTree, GitKraken, Tower) work with my workflow very well, but they are slow comparing to Github Desktop. I noticed it right away when trying your app. For ex. as iOS developer I need to tackle merge conflicts in project files called `.pbxproj`. That file has more than 100k lines of code. I don't know how you did it, but GH Desktop is blazing fast showing me the changes in that file ;)
That is why I started to use it. Unfortunately it doesn't have the ability to synchronise index with the git and it was my big disappointment. This is something so much important to me, that I'm unable to use GH Desktop.

**Comment by billygriffin** [comment]
Thank you so much for the additional clarification @castus - glad the speed of Desktop is solid for you. And I'm sorry the design choice we made doesn't work well with your workflow. We have seen people who didn't previously use Desktop to commit have great luck with it when they tried to do increased parts of their workflow with the app, and you wouldn't need to contend with the Git index. Anyway, I appreciate the feedback and if it's something we see significantly more of, we'll definitely revisit. Thanks again!
