### ISSUE TITLE
Desktop client for windows is ignoring project folder randomly.

### ISSUE THREAD

**Issue by ProHackTech** [desktop/desktop#7322]
### Issue
Github Desktop client is ignoring sub folder(s) in the project. I don't know how developers could reproduce this properly but here is a glimpse: When a folder is made under the repository, it is not being registered in the client. The client fails to acknowledge that there is a _new folder_ in the local repository copy.

### System Information

- Operating System : Windows 10 Home
- Version: 1809
- OS Build: 17763.437
- Client Version: 1.6.5

### Reproduce Issue
As mentioned above, this is such as random issue that it may be hard to reproduce. Here are the screenshots to visualize the issue:
![Capture](https://user-images.githubusercontent.com/47453894/56246452-99223580-60d4-11e9-8854-63c228f6f9ef.PNG)

**Comment by steveward** [comment]
Thanks for the report @ProHackTech. I have a few questions to help narrow down this issue:

1) Are the directories that are not being detected empty directories, or do they contain files? Git does not track empty directories so that could be a cause of this issue.

2) Does this repository have a `.gitignore` file? If so, could you share contents of that file so that I can check to see if certain directory names are being ignored by Git?

3) Are you able to reproduce this across multiple repositories, or is this only occurring in this specific repository?

**Comment by ProHackTech** [comment]
Hello. Thanks for the response.

It was an issue with the gitignore file ignoring the directory sub-folder names, which made the main folder seem empty.

Issue fixed

**Comment by billygriffin** [comment]
Great, thanks @ProHackTech!

**Comment by RaisTheCoder** [comment]
If it detects the Project as just a folder without contents in it, try to make hidden folders visible and get rid of ".git" inside of the folder in your repository. You can't have .git on the folders inside of repository.
