### ISSUE TITLE
GitHub desktop will not open anymore and only white screen when trying to select a dropdown option

### ISSUE THREAD

**Issue by MikeLonsdale** [desktop/desktop#7342]
## Version

* GitHub Desktop:

* Operating system:

**Comment by steveward** [comment]
Thanks for reaching out @MikeLonsdale !

Would you mind filling out the rest of the issue template so that we can better understand what is causing the problem you are experiencing? Without that information it will be difficult to help you further.

Based on the title it sounds like you are running into https://github.com/desktop/desktop/issues/4054. You can try following the steps in https://github.com/desktop/desktop/issues/4054#issuecomment-367567297 to see if that gets things working for you.

**Comment by steveward** [comment]
@MikeLonsdale Due to inactivity I am going to close this issue out. If you are still encountering problems, please fill out the issue template and we'd be happy to dig into this further.
