### ISSUE TITLE
Investigate spawn error 

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#7358]
Don't really have details about this spawn error, as I spotted after the fact in 1.7.0beta4. 

<img width="1343" alt="Screen Shot 2019-04-18 at 3 29 13 PM" src="https://user-images.githubusercontent.com/14828183/56400391-6d47a280-61ef-11e9-8ffb-3cbf83a300d6.png">

As this is unlikely to be enough info, feel free to close.

**Comment by shiftkey** [comment]
`ENOTDIR` suggests the location where the Git operation was run was not a directory. I'm curious about whether you can stumble into this again, because it might be a chance to improve our error handling in `dugite`:

https://github.com/desktop/dugite/blob/8af3f540344e3406e413a986748c3285687d9cc8/lib/git-process.ts#L184-L193

**Comment by tierninho** [comment]
Closing for now unless I can provide more details.
