### ISSUE TITLE
[stashing] Update stash warning language

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#7361]
Based on user feedback here: https://github.com/desktop/desktop/issues/6107#issuecomment-484919607 we should consider updating the language used in the buttons and text.

<img width="611" alt="56428862-e3e7ad00-628e-11e9-9463-e214c64cbfa4" src="https://user-images.githubusercontent.com/14828183/56435914-dbcf4380-6275-11e9-8b6f-cb7fc32f2521.png">

At minimum, change "clear" to "discard" to match the new button name.

Feedback:

> The wording on that might be a little confusing. When I skim it, I see "Clear or restore...", along with a continue button, which can look like it's guiding me somewhere to fix things, rather than deleting the old stash. It makes sense as a whole, but the main things I looked at weren't clearly destructive.

and

> But if it stays as is, the buttons should be something like Cancel and Overwrite.

1.7.0beta4, mac

**Comment by billygriffin** [comment]
I agree this verbiage is confusing. Here's a suggestion based on the feedback:

"Are you sure you want to proceed? This will overwrite your existing stash by stashing your current changes on this branch."

Button options: `Cancel` and `Overwrite` with `Cancel` as the default button since this is a destructive action.

cc: @eschafer & @barbara-sfx (thank you! ❤️)
