### ISSUE TITLE
Can't Publish Branch Created from Commit

### ISSUE THREAD

**Issue by dsanders11** [desktop/desktop#7372]
## Description

When creating a new branch from a commit (or other branch) from the command line `git`, Git Desktop does not show the 'Publish Branch' option. Adding a commit to the branch will make Git Desktop show 'Push origin`, but doing so does not push the new branch to the origin.

## Version

* GitHub Desktop: 1.6.5

* Operating system: MacOS 10.14.4

## Steps to Reproduce

1. Using command line `git`, create a new branch from an existing branch, specific commit, etc, using `git checkout -b <branch-name> <commit>` such as `git checkout -b my-new-branch origin/master`.

### Expected Behavior

Expected 'Publish branch' to be visible in Github Desktop for this branch.

### Actual Behavior

'Publish branch' is not visible.

**Comment by shiftkey** [comment]
@dsanders11 thanks for the feedback! 

I went through the steps to reproduce this and it looks like you might be encountering some default Git behaviour:

```
$ git checkout -b my-new-branch origin/development 
Branch 'my-new-branch' set up to track remote branch 'development' from 'origin'.
Switched to a new branch 'my-new-branch'
```

Note the comment on the output from Git here - it's assuming you're interested in pushing changes to the remote to update the branch (because you used a named reference), so it associates your new branch with the existing remote branch.

To workaround this, I can think of two options:

 -  using the commit SHA on `git checkout` to avoid this behaviour

```
$ git checkout [sha] -b [new-branch-name]
```

 - stop tracking the upstream branch after creating the new branch

```
$ git branch --unset-upstream [branch-name]
```

Once you do that, Desktop should detect you're no longer tracking a remote branch and ask you to publish the new branch to the remote.

**Comment by dsanders11** [comment]
@shiftkey, thanks for the clarification, that's good detail.

Seems like `git` being a bit strange, as I've used this technique from the command line before without having issues. The `git push` always creates the new branch on the remote.

I tried again and found that both `git push origin HEAD` and `git push origin my-new-branch` both create the branch on the remote with commits on the branch I made. That's confusing because the second command is what you'd normally use to push a branch created with `git -b my-new-branch` as well. It then gets more confusing because Git Desktop is showing the commits I just pushed as local commits (can undo, no 'View on Github' in history view), even though if I browse to github.com they're there on the named branch as expected. Doing a fetch resolves that.

So you're right, it appears the way I created the branch leaves it tracking the other branch, and the more correct way would be to do `git checkout master; git checkout -b my-new-branch`. I'd gotten used to the previous way of doing it as that's a quick and easy way to make branches from a tag (and doesn't have these issues since there's no remote branch to track). Practically, though, it seems from the command line that the tracking a different remote has little impact since doing `git push my-new-branch` was creating the remote branch anyway.

I'm going to go ahead and close this as there's probably not much that can be done in Github Desktop to resolve the confusion. I think a warning banner (dismissable) if the branch is tracking a remote with a different name might be useful, but it's probably not worth the effort for this niche case.
