### ISSUE TITLE
Branches with names containing '/' can cause problems in GitHub Desktop

### ISSUE THREAD

**Issue by MarkFern** [desktop/desktop#7397]
## Description

I created several branches with names containing the '/' character using GitHub Desktop. Later on, I found that one of my commits appeared to disappear which could possibly be another bug.

Anyway, when looking at the GitHub files stored by GitHub Desktop on my local computer, I noticed something seeming to be quite irregular. Folder names for certain logs seemed to be cut short just at the point where '/' appeared in my branch names. Upon descending into such folders, I found the files contained in such folders bore names matching the text seemingly missing from their parent-folder names minus the '/' character.

What seems to be happening is that the '/' in my branch names is being misinterpreted as denoting the end of a parent-folder name & the beginning of the name of a child folder contained in a parent folder.

#### Example 
Branch Name is:

&nbsp;&nbsp;&nbsp;`MF-PATCH_Variant-data-type.md_part/full-scrub`.

This branch name seemed to trigger the creation of the following file:

&nbsp;&nbsp;&nbsp;`C:\Users\mark.j.fernandes\Documents\GitHub\VBA-Docs\.git\logs\refs\heads\MF-PATCH_Variant-data-type.md_part\full-scrub`.

However, I have another branch called:

&nbsp;&nbsp;&nbsp;`MF-PATCH_Assignments-to-variants-with-&-without-'Set'` 

and the corresponding file for this branch appears to be:

&nbsp;&nbsp;&nbsp;`C:\Users\mark.j.fernandes\Documents\GitHub\VBA-Docs\.git\logs\refs\heads\MF-PATCH_Assignments-to-variants-with-&-without-'Set'`.

This file appears to likely have the correct path & filename.

#### Big Problem?
To be honest, I don't know whether this issue causes many problems. However, I think it might be a bug to be concerned with just in case variant forms of the bug are occurring elsewhere in the GitHub Desktop software.
 
## Version

* GitHub Desktop: Version 1.6.5

* Operating system: Microsoft Windows [Version 6.3.9600] (8.1)

## Steps to Reproduce

1. Create a branch that has a name containing the '/' character from within GitHub Desktop.
2. Go to the `...\.git\logs\refs\heads` directory for your locally cloned repository that the branch is associated with.
3. Notice that there is a folder with only part of your branch name there - specifically, the name has been cut short at the '/' character.

### Expected Behavior

I expected that the branch name would be the name of a file in the folder.

### Actual Behavior

Instead, a sub-folder is created for the branch, with only part of the branch name as its name.

## Additional Information

![Screenshot of possibly incorrect filenames for GitHub branches](https://user-images.githubusercontent.com/49532200/56752897-46561700-6781-11e9-97c0-2d2483377d4d.png)
![Screenshot showing names of most of my GitHub branches](https://user-images.githubusercontent.com/49532200/56752898-46eead80-6781-11e9-87d5-06e2ad44ba27.png)

**Comment by MarkFern** [comment]
By the way, the commit that seems to have gone missing was for a branch that has the `'` character twice in its name. The 8 other branches that I created in the same way as this other branch, and that each has at least one of my commits, all seem to be correct. None of their names have the `'` character in their names.

A coincidence?

**Comment by niik** [comment]
> ### Expected Behavior
> I expected that the branch name would be the name of a file in the folder.
> 
> ### Actual Behavior
> Instead, a sub-folder is created for the branch, with only part of the branch name as its name.

Hey @MarkFern, thanks for opening this and for including such detailed reproduction steps and screenshots, that's always appreciated.

In this case I believe that the actual behaviour is actually the expected behavior. Git has its roots in posix-based systems (i.e. Linux) where the forward slash character is used as the directory separator (on Windows the separator is, as you know, a backslash character).

While it's legal to have a file name contain backslash characters on most posix systems the opposite isn't true on Windows. A file name on Windows can't contain either a forward slash or a backslash character. You can test this yourself by trying to rename a file to contain either of those characters.

![image](https://user-images.githubusercontent.com/634063/56806001-f895e900-682a-11e9-98ac-dc6fdd023ad7.png)

With the perspective of Git originally being built for posix systems it should make a little more sense why the forward slash character generates a folder. Some Git projects leverage this convention in order to group their branch names by feature, type, or author (i.e. `big-feature/sub-feature`, `hotfix/launch-crash`, or `niik/feature-a`). The rules for what constitutes a valid branch name are rather complex but if you're curious you can read more about them in the [git-check-ref-format](https://git-scm.com/docs/git-check-ref-format) documentation.

In fact, what you name your branch is only one part of it's fully qualified name. The fully qualified ref name of a branch name such as master would be `refs/heads/master` which would match the directory structure that you see under the `.git/refs` folder whereas the tracking branch on the remote would be `refs/remotes/origin/master`. Note that not all references will necessarily exist as files underneath the `.git/refs` folder though. Once you start to accumulate enough branches Git will pack these up into a fast, compact format stored under `.git/packed-refs`.

As for the missing commit we'd love it if you could open up a separate issue focused just on that so that we can debug it in isolation. I'd suggest starting with reading up on the [reflog](http://effectif.com/git/recovering-lost-git-commits) ([docs](https://git-scm.com/docs/git-reflog)). The reflog keeps track of every commit you've made in the last 90 days by default so you should be able to find your commit in there.

As for this issue I'm going to close it seeing as the directory behavior is what we expect it to be.

**Comment by MarkFern** [comment]
Hello @Niik,

Thank you for your lengthy explanation. It is especially useful to know that some projects leverage the sub-folder-creation behavior caused by forward-slashes.

I probably should have consulted the GitHub documentation to check that what I was seeing wasn't expected behavior, before I created the issue. Sorry about that. I think I probably thought that the problem was probably connected to me losing my commit, so was a bit hasty.

I managed to retrieve the commit using reflog so that was great news. If I have time, I'll try to reproduce any possible commit bug that I encountered. I'm not sure whether it was a bug or just my own human error, to be honest.

**Comment by NazarieCiprian** [comment]
Hi, 

We are experiencing similar issue recently. In case the branch name contains a / we can't perform a fetch operation. Is this intendend behavior? Note that we would like to use slashes in order to maintain the structure in our commits.
