### ISSUE TITLE
facing error ahile cloning repository "remote-https' is not a git command. See 'git --help"

### ISSUE THREAD

**Issue by Abuthahirsha** [desktop/desktop#7451]
**Please describe the problem you think should be solved**
A clear and concise description of what the problem is and who else might be impacted. Screenshots are encouraged.

Example:

> “When I run into a merge conflict, I don’t know where to go to resolve it. Anyone who works off of multiple branches will likely run into this problem at least occasionally.”

**[Optional] Do you have any potential solutions in mind?**
A clear and concise description of one or more solutions you think might solve the problem. Please include any considered drawbacks or tradeoffs, and how users might use your solution(s). Screenshots or mockups are helpful here!

**Comment by steveward** [comment]
Thanks for reaching out @Abuthahirsha!

Would you mind filling out the rest of the issue template so that we can better understand what is causing the problem you are experiencing? Without that information it will be difficult to help you further. It would especially be helpful if you could upload the log file from GitHub Desktop, which will give more details about the specific error you are seeing. 

To access the log files go to the  menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`. 

The log files are created daily -- please send over a log file as an attachment from a day where you experienced the issue

Thanks!

**Comment by Abuthahirsha** [comment]
while pushing or cloning the repository it shows the attached alert.

**Comment by steveward** [comment]
@Abuthahirsha there may be an issue with your installation of GitHub Desktop.

Can you try performing a fresh installation of GitHub Desktop by following these steps?

1. Close GitHub Desktop 
2. Remove all of the files in `%APPDATA%\GitHub Desktop\`
3. Remove all of the files in `%LocalAppData%\GitHubDesktop`
4. Reinstall GitHub Desktop from http://desktop.github.com

Let me know if that doesn't fix things.

**Comment by tierninho** [comment]
@Abuthahirsha As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.

**Comment by arijit1** [comment]
facing an error while cloning repository "remote-https' is not a git command. See 'git --help" #7451

Tried below-mentioned steps still issue persists -

Close GitHub Desktop
Remove all of the files in %APPDATA%\GitHub Desktop\
Remove all of the files in %LocalAppData%\GitHubDesktop
Reinstall GitHub Desktop from http://desktop.github.com

**Comment by tierninho** [comment]
@arijit1 Please file a new issue with your details so we may assist independently of this issue. Thank you.
