### ISSUE TITLE
multiple fork from same project by same person

### ISSUE THREAD

**Issue by XenoAmess** [desktop/desktop#7455]
## Description

In short it is a bug that if you fork the same project several times in different organizations, and once some other conditions exist, then the desktop will not be able to figure out the forked projects.

The details will be shown in Steps to Reproduce

## Version

* GitHub Desktop:

1.6.5
* Operating system:
Windows 10

## Steps to Reproduce

1. We register a user XenoAmess. 
2. XenoAmess create an organization cyanpotion.(and make sure he is the only one man in the organization )
3. XenoAmess forked gabomdq/SDL_GameControllerDB as XenoAmess/SDL_GameControllerDB 
4. XenoAmess clone the project to local using github desktop.
5. XenoAmess transfer XenoAmess/SDL_GameControllerDB to organization cyanpotion , thus it becomes cyanpotion/SDL_GameControllerDB.
6. XenoAmess renames cyanpotion/SDL_GameControllerDB to cyanpotion/SDL_GameControllerDB_Util
7. XenoAmess fork the  gabomdq/SDL_GameControllerDB to XenoAmess/SDL_GameControllerDB
8. Now clone the new XenoAmess/SDL_GameControllerDB to local using github desktop.
9. Now github desktop cannot distinguish XenoAmess/SDL_GameControllerDB and cyanpotion/SDL_GameControllerDB_Util, and if you commit on each of them , the commit will be commited to both of the projects.
10. That is what I suffered last night. At last I have to delete XenoAmess/SDL_GameControllerDB to make my life easier...

### Expected Behavior

the desktop should distinguish XenoAmess/SDL_GameControllerDB and cyanpotion/SDL_GameControllerDB_Util

### Actual Behavior

the desktop should distinguish XenoAmess/SDL_GameControllerDB cannot distinguish cyanpotion/SDL_GameControllerDB_Util, and pull every commit to each of them upon both of them.

### Logs

[2019-04-30.desktop.production.log](https://github.com/desktop/desktop/files/3138958/2019-04-30.desktop.production.log)
[2019-05-01.desktop.production.log](https://github.com/desktop/desktop/files/3138959/2019-05-01.desktop.production.log)
[2019-05-02.desktop.production.log](https://github.com/desktop/desktop/files/3138960/2019-05-02.desktop.production.log)

**Comment by outofambit** [comment]
Hi @XenoAmess and thank you for filing this issue! I'm sorry you're hitting this, its a peculiar situation.

I think the problem in this case is that your new repository is pointing to the same remote URL as one of the repository's you've since transferred to another organization. Currently, GitHub Desktop (and all git clients as far as I know) don't automatically detect that a repository has been moved. So, whenever you move or rename a repository, you'll need to manually update the remote in your local clones (you can see steps for this in https://help.github.com/en/articles/renaming-a-repository).

Hope this helps! I'm going to close out this issue but feel free to comment if you have any questions and we can reopen it.
