### ISSUE TITLE
[ENHANCEMENT] add a way to pin certain files to be opened somehwere on the top bar

### ISSUE THREAD

**Issue by Hellzbellz123** [desktop/desktop#7462]
add a way to pin a file to one of the bars so we can open certain files directly form within Github Desktop and maybe also automatically add in Solution files from VS studio and other similar file types?
also support for VSCodium would be nice
possible design outlined in picture made by me in ms paint
![Capture](https://user-images.githubusercontent.com/31550512/57154937-541a2680-6d97-11e9-9d8e-224f69e09fed.PNG)

**Comment by billygriffin** [comment]
Hi @Hellzbellz123, thanks for the issue! I know it's hard when opening issues in open source projects to know exactly how teams want them structured. For our part, we generally try to frame issues in terms of problems to be solved as opposed to direct feature requests without a clear understanding the problem and who it affects (and how painful it is). We also have a strong belief that not overloading the UI with additional features helps to keep focus on the most important things, so we're really hesitant to add something like this so prominently.

You can open files with your editor (assuming it is one of Desktop's detected editors) in places where lists of files are shown by right clicking and using the context menu, like below:

<img width="452" alt="Screen Shot 2019-05-03 at 11 47 29 AM" src="https://user-images.githubusercontent.com/5091167/57155686-53828f80-6d99-11e9-8295-73782aa05081.png">

Visual Studio isn't currently one of the detected editors because the implementation is tricky, but we have an issue https://github.com/desktop/desktop/issues/7033 to try to learn more about how that affects folks, so if you have feedback there, please feel free to comment in that issue. Since we don't intend to implement this and there are other ways to open files in an editor, I'm going to close this issue. Thanks again!
