### ISSUE TITLE
Github Desktop not responding

### ISSUE THREAD

**Issue by hu7go** [desktop/desktop#7469]
## Description

After about 5 seconds after opening Github desktop freezes on whatever I was just doing and stops working.

I would like it to work as normal where I can click stuff.

## Version

Github Desktop Version 1.6.5
* GitHub Desktop:

* Operating system:
Microsoft Windows [Version 10.0.17134.706]

## Steps to Reproduce

These are the steps it did when it first started happening.
1. Open Github Desktop
2. Open my Repo
3. Push changes
4. The push got stuck at 99% so I decided to cancel

After that, it has behaved as the description described

### Expected Behavior

I would like it to be able to click on the button in Github Desktop and be able to pull and push repos.

### Actual Behavior

Github freezes and I can't do anything but to force quit it with TaskManager.

## Additional Information

This is how it looks when it freezes:
![GithubDesktopFreezeError](https://user-images.githubusercontent.com/31646629/57218612-9a52dc80-705a-11e9-9633-d054304153b2.PNG)

### Logs

[2019-04-15.desktop.production.log](https://github.com/desktop/desktop/files/3147421/2019-04-15.desktop.production.log)

**Comment by shiftkey** [comment]
@hu7go thanks for the report! I'm not 100% sure of what might be triggering this, and based on the logs it looks like the pushes do take a bit of time but still complete:

```
2019-04-15T14:47:09.090Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: PA-RougeLike - hu7go (has token)
2019-04-15T14:47:12.785Z - info: [ui] Executing push: git -c credential.helper= -c protocol.version=2 push origin master:master --progress (took 3.591s)
```

Because this is an Electron app we also have access to the Chrome Dev Tools to debug the running app, and there's a couple of things I'd like for you to try and see if they show interesting clues.

Ensure you've launched the Dev Tools before trying the actions you think were a problem (using the **View** | **Toggle Developer Tools** menu item, and then move it out to its own window).

With the dev tools accessible I'd love to check these two things after you run through the repro steps and get stuck again:

 1. Is there any interesting output in the **Console** tab that might be a clue about what's happening at the time?

<img width="675"  src="https://user-images.githubusercontent.com/359239/57230206-2f6bbc00-6fee-11e9-9c8f-6db1da45b23b.png">

2. If you switch over to the **Sources** tab and then press the **Pause** icon, where does the app appear to be "stuck"? A snapshot of the stacktrace here would be great, if you can grab it:

<img width="885"  src="https://user-images.githubusercontent.com/359239/57230272-56c28900-6fee-11e9-8c13-499556fd3df6.png">

**Comment by hu7go** [comment]
Hello shiftkey
Thank you so much for responding.
However, I have been able to find a fix to the problem but I'm not sure if its a perfect solution,
I fixed it by deleting the repo and then cloning the previous push to desktop.
Should I still try to reproduce the issue to try your suggestion?

**Comment by shiftkey** [comment]
@hu7go no, that's okay. Thanks for following up.
 
If you stumble upon it again please have a go at the steps above and we can reopen this issue to try and investigate further.
