### ISSUE TITLE
Github desktop freez windows 10 

### ISSUE THREAD

**Issue by fifou17** [desktop/desktop#7515]
## Description

when i open github on windows 10 the entire apps freez and desktop freez 

## Version

* GitHub Desktop:

* Operating system:

**Comment by shiftkey** [comment]
@fifou17 thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by fifou17** [comment]
@shiftkey sure i will fill the form
