### ISSUE TITLE
Commit failed - exit code 128 received, with output: '*** Please tell me who you are. Run   git config --global user.email "you@example.com"   git config --global user.name "Your Name" to set your account's default identity. Omit --global to set the identity only in this repository. fatal: unable to auto-detect email address (got 'Destroy@DESKTOP-LL1JHIN.(none)')'

### ISSUE THREAD

**Issue by zahidul123** [desktop/desktop#7533]
## Version

* GitHub Desktop:

* Operating system:

**Comment by tierninho** [comment]
@zahidul123 thanks for reaching out!

We require the [template](https://github.com/desktop/desktop/issues/new?template=bug_report.md) to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
