### ISSUE TITLE
Search Within Diffs

### ISSUE THREAD

**Issue by bob-zs** [desktop/desktop#7538]
**Please describe the problem you think should be solved**
Some diffs can get pretty large. A simple search feature on a diff would be helpful in just finding a term or a line of code.

Example:

> When I am looking at the changes I made, I want to hit `ctrl f` and search for a certain term or possible mistake.

**[Optional] Do you have any potential solutions in mind?**
Maybe something similar to google chrome's search as a ui? The search bar sticks out at the top right.
![Screen Shot 2019-05-15 at 1 40 35 PM](https://user-images.githubusercontent.com/4698973/57796832-0d251d00-7717-11e9-9867-eb46f7dc756b.png)

**Comment by niik** [comment]
Hey @bob-zs, thanks for opening this! I too have habitually hit Ctrl+F in the diff at times so I understand where you're coming from with this. I'll bring this up at the next planning meeting.

**Comment by billygriffin** [comment]
@ivolazy referenced something similar in #4484 

    step 1 - Open a repo that has changes
    step 2 - Click on Changes to see the changed files and click on one of the changed files
    step 3 - This is where I'd like to be able to do a search in the right panel for a term so that I can decide whether to include or not in the current commit.

**Expected Behavior**

I'd like to be able to do a search in the right panel for a term so that I can decide whether to include or not in the current commit.

In addition, also in that issue @pforhan brought up wanting to do a final gutcheck in the diff to check for things like #TODO notes.
