### ISSUE TITLE
Updating the latest edition is very slow to use

### ISSUE THREAD

**Issue by zhaoty009** [desktop/desktop#7540]
## Version

* GitHub Desktop:

* Operating system:

**Comment by havefive** [comment]
same issue

**Comment by health901** [comment]
me too, any way to rollback to the last version?

**Comment by havefive** [comment]
Beta Channel:
https://central.github.com/deployments/desktop/desktop/latest/win32?env=beta

**Comment by luhaopeng** [comment]
> Beta Channel:
> https://central.github.com/deployments/desktop/desktop/latest/win32?env=beta

I'm trying out 1.7.0-beta7, and it's still slow, though much faster than 1.6.6.
To be specific, 1.7.0-beta-7 is slow in: 
* commit & undo, the ui changes slowly.
* switching among the changed file, the diffs show slowly.

And 1.6.6 is slow in:
* **Everything** and **Incredibly slow**.

---

imo, 1.6.5 is the ideal version. Any ideas how I can rollback to 1.6.5 ?

**Comment by shiftkey** [comment]
Thanks for the report everyone! I'd love to know a bit more about your setup:

 - are you running on Windows or macOS?
 - what things you are performing in the app that are slow?

Please be as specific as possible

Could you also attach the log files from your machines? The **Help** | **Show Logs in Explorer** menu items should open the logs folder, and inside those are the log files generated by day. This will provide some more information to help troubleshoot.

**Comment by shiftkey** [comment]
After an initial investigation of the latest build I couldn't spot any obvious regressions.

Unassigning myself from this until there's some logs or examples to step through to help troubleshoot further...

**Comment by zhaoty009** [comment]
on Windows,every step is slow,version 1.6.6

**Comment by tierninho** [comment]
@zhaoty009 Could you also attach the log files from your machines? The Help | Show Logs in Explorer/Finder menu items should open the logs folder, and inside those are the log files generated by day. This will provide some more information to help troubleshoot.

**Comment by luhaopeng** [comment]
@shiftkey @tierninho 

## Environment

* GitHub Desktop: v1.6.6
* Operating System: Windows 10
* Memory: 8GB, taken up around 54% - 58%
* Application present: Chrome, VS Code, GitHub Desktop
* My computer never had a reboot since a couple day ago. Hope that won't affect.

## Description
Slow performance in:

* UI change. e.g. hovering among the ui elements, their background change with some delay.
It appeared well after staying focused for a few seconds(> 8s), but switching from other applications made a disaster.
* File diffs. Besides the focus thing above, the changed file diff shows after an unexpected delay(about 0.5s). I couldn't find a way to rollback to 1.6.5 so that I'm not sure if this is normal. I suppose it's longer than I expected.
* Commit & undo. When commiting, the author form with summary and description changes **incredibly** slow, and it's nothing to do with that focus thing. It's slow **always**. So is the changed files list.

## Logs

The Desktop was updated on 5-16, so I'll paste these two log files.
* [2019-05-16.desktop.production.log](https://github.com/desktop/desktop/files/3189554/2019-05-16.desktop.production.log)
* [2019-05-17.desktop.production.log](https://github.com/desktop/desktop/files/3189553/2019-05-17.desktop.production.log)

And for comparison, here's the ones before update, in case you need them.
* [2019-05-14.desktop.production.log](https://github.com/desktop/desktop/files/3189563/2019-05-14.desktop.production.log)
* [2019-05-15.desktop.production.log](https://github.com/desktop/desktop/files/3189564/2019-05-15.desktop.production.log)

## Note

I'm not native English speaker. Hope things are well understood.

And if necessary, I could record a video for demonstration.

**Comment by shiftkey** [comment]
@luhaopeng thanks for the logs - I'm going to pore over them this morning and see if I can understand better what you're seeing. if I have any follow-up questions I'll be in touch.

**Comment by niik** [comment]
Hi @luhaopeng, thank you so much for this detailed error report, it's incredibly helpful to us as we investigate further. We'd appreciate if anyone else who's experiencing this problem could submit their log files as well to help us narrow down on a root cause.

@luhaopeng: The log files from 2019-05-14 and 2019-05-15 did not include any version information which usually means that the app was running continuously over those two days. Could you check back on older log files and see if you find a line that looks like `info: [ui] launching: 1.x.x (Windows 10.0.17763)` so that we can verify that you were indeed on 1.6.5 before you upgraded to 1.6.6?

**Comment by shiftkey** [comment]
@luhaopeng are you running any anti-virus software on your machine?

**Comment by luhaopeng** [comment]
Hi @niik , yes, it's on 2019-05-13:  
[2019-05-13.desktop.production.log](https://github.com/desktop/desktop/files/3193621/2019-05-13.desktop.production.log)

@shiftkey yes. I'm currently running [QQPCMgr](https://guanjia.qq.com/), which is an anti-virus product from Tencent. 
I quited QQPCMgr and restarted GitHub Desktop. Magic! It performed as smoothly as I am familiar with.

Now I think I should report to Tencent instead. I guess it's something to do with the so-called File Guardian of QQPCMgr, which watchs files change and protects them from being encrypted by blackmail viruses. But apparently, it has some side effect.

Problem solved. Thank you for your great effort @shiftkey @niik @tierninho !

@zhaoty009 @health901 @havefive Check if you have installed any anti-virus software that has similar features, and please try quit it or turn off the feature and see if GitHub Desktop works well.

**Comment by luhaopeng** [comment]
I tried switching off the File Guardian and the File System Protection of QQPCMgr, but neither worked.
So far, the only way is to directly quit it.

I've report this issue to the forum of QQPCMgr and see if they'll reply ( I really doubt that).
Before that, I think I should better uninstall and use Windows Defender instead.

**Comment by luhaopeng** [comment]
It's not a problem or bug about GitHub Desktop. It's something to do with your anti-virus software. Thanks to @shiftkey . **In that, this issue may close**. 

Below I'm gonna share something about the cause that I am currently aware of, in case you're experiencing the same issue and don't know the reason to it.

---

(Based on QQPCMgr)

Someone from the forum of QQPCMgr reached to me right after I posted the report. (Thumb up)

After some testing, it came out that one feature called _process protection_ was the main cause.

You could find it here and switch it off for temporary use or simply quit the application.
![screenshot](https://user-images.githubusercontent.com/13071103/57965323-5ecae300-7975-11e9-897b-fd879b431f12.png)

They are looking into it, and it may take a while before the solution come out.

**Comment by shiftkey** [comment]
@luhaopeng thanks for working through this with us, and confirming this theory about anti-virus being a factor.

I'd love to confirm that this is isolated to this specific AV product, so please @zhaoty009 @health901 @havefive confirm that you are running the same product and the same workaround mentioned here https://github.com/desktop/desktop/issues/7540#issuecomment-493651528 addresses the issue for you, before we close this out.

> Still, I'm curious why it is 1.6.6 that is awfully affected. I've tried 1.7.0-beta7 and it was affected much lesser. What's the unique difference in 1.6.6 ?

I don't have the full answer to this, but based on my experiences it can take anti-virus software some time to become aware of new updates and to trust them. When they encounter a new update they might act in one of two ways:

 - trusting - let the updated app proceed as is, based on code-signing values found and reputation of the entity that signed it
 - paranoid - not to trust the new update, and to inspect the app in case it's trying to do something bad

While we mark one version as "beta" and the other as "production" the interesting difference here is when they were published:

 - `1.7.0-beta7` was released by us on the 9th of May, around 6pm UTC
 - `1.6.6` was released on the 15th of May, around 5pm UTC (almost a week later)
 - this issue was opened at approximately 2am UTC on the 16th of May (about 9 hours later the release was published)

My theory of what happened here is:

 - `1.7.0-beta7` had likely been installed and used enough for vendors to "see" it and know that it was safe
 - some people who updated to `1.6.6` as soon as it was available but also had an anti-virus program that didn't trust the update
 - the anti-virus program would impede our Git processes from executing to the point it affected the overall experience of the app, because it needed to know that nothing bad was happening

"Process protection" does sound like something that would impact Desktop's operations.

For reference, here are some old issues where anti-virus products impact GitHub Desktop - #2837 #5247 #5652. There's not really much we can do here aside from work with the vendors to understand the problems better, so thank you again @luhaopeng for doing that on our behalf!

**Comment by zhaoty009** [comment]
Yes, I also run QQPCMgr，thanks for everyone！

**Comment by luhaopeng** [comment]
@zhaoty009 
2019-05-20 13:26:11
Team from QQPCMgr has just fixed the issue. Everything should work as usual. A reboot is needed.
