### ISSUE TITLE
The shell doesn't show command menu

### ISSUE THREAD

**Issue by OmerJog** [desktop/desktop#7575]
![Capture](https://user-images.githubusercontent.com/44576851/58017340-a03fc780-7b08-11e9-8d34-f081fb9dbc8b.PNG)

This is my shell after doing 
`git rebase -i HEAD~4`

I need to change the pick into squash but I can't.
I can not edit the file. I can't even exit the file as I don't know what is the exit combination.
There is a secret combination of keys to enter edit mode & then save.
None are listed in the shell and it's been impossible to find it with google.

1. What are the keys? I managed to find that `qa! `something says exit? Please post the full edit keys.
2. Please add the keys menu in the window so users can see it.

**Comment by shiftkey** [comment]
@OmerJog thanks for the report. As this isn't a problem related to the GitHub Desktop product I'm going to close this, but I'll provide some extra context.

In situations where Git requires you to edit a file to complete an operation (in this case an interactive rebase), it'll check your config for a suitable editor or use a fallback editor. In your situation, it's using an editor named `vim` which isn't the best option if you're not familiar with it.

I'd also recommend checking Google for "how to make Git use [your editor of choice]" because there's plenty of resources out there.

> What are the keys? I managed to find that `qa!` something says exit? Please post the full edit keys.

I recommend [this cheat sheet](https://vim.rtorr.com/) for the keyboard shortcuts, but also [this guide](https://www.openvim.com/) to learn more about how to use Vim.

**Comment by OmerJog** [comment]
@shiftkey Acually the answer was:
press `I `to enter edit mode
edit the text
Press `ESC`
then Press 
`:wq `to save and exit.

It was a nightmare to figure this out.

Github Desktop knows on which platform it's installed (linux, windows) you can show the correct keys for the platform to help the users.
