### ISSUE TITLE
Fetch Origon on mutiple repo

### ISSUE THREAD

**Issue by CrescendoTechDevManager** [desktop/desktop#7578]
Is there a way to update all repos from origin at once? I have several projects and I would like to just click a button to update all repo from origin. What ever default branch or selected branch I am on.

**Comment by steveward** [comment]
Thanks for the feedback @CrescendoTechDevManager. This feature has been previously discussed in #2460 and #6482. At this time we have not decided to move forward with this due to it not being an area that we see as a pain point in GitHub Desktop. 

I'm going to close this issue out, but if you have any further feedback about how this feature would make GitHub Desktop more valuable for you please feel free to drop it in here.
