### ISSUE TITLE
When merging branches, unable to see the full path of files to merge

### ISSUE THREAD

**Issue by AdamUpstreamArcade** [desktop/desktop#7580]
When I'm merging branches, I'm often unable to see the full path and name of files to resolve. Anyone who merges with a project with a file structure multiple folders deep will probably run into this often.

![image](https://user-images.githubusercontent.com/11279011/58024848-062d4e80-7b0b-11e9-8c5d-1991e61a1a90.png)

**[Optional] Do you have any potential solutions in mind?**
I'd recommend widening the merge/resolve window. I'd also wrap the path and filename so that no matter what, you know what you're merging.

**Comment by steveward** [comment]
Thanks for the report @AdamUpstreamArcade! This issue is being tracked in https://github.com/desktop/desktop/issues/6666, so I'm going to close this out. Please follow along there for updates.

**Comment by mido1966** [comment]
No Email  pls an oll No Email  mor pls



Von meinem Samsung Galaxy Smartphone gesendet.


-------- Ursprüngliche Nachricht --------
Von: Adam Langridge <notifications@github.com>
Datum: 20.05.19 15:26 (GMT+01:00)
An: desktop/desktop <desktop@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [desktop/desktop] When merging branches, unable to see the full path of files to merge (#7580)


When I'm merging branches, I'm often unable to see the full path and name of files to resolve. Anyone who merges with a project with a file structure multiple folders deep will probably run into this often.

[image]<https://user-images.githubusercontent.com/11279011/58024848-062d4e80-7b0b-11e9-8c5d-1991e61a1a90.png>

[Optional] Do you have any potential solutions in mind?
I'd recommend widening the merge/resolve window. I'd also wrap the path and filename so that no matter what, you know what you're merging.
