### ISSUE TITLE
Remove unnecessary call to emitUpdate in updateLastStashCheckDate

### ISSUE THREAD

**Issue by outofambit** [desktop/desktop#7583]
_(from @niik)_

> When we update the last stash check date in `updateLastStashCheckDate` we trigger an update from the repositories store which in turn causes the app store to pick up on the changed repository and run a refresh operation on it (since earlier we’ve believe the only time the repo will get updated is if the path changes). This triggers an additional repository refresh run.
> This shouldn’t happen since we check for whether the repository.hash has changed in `updateRepositorySelectionAfterRepositoriesChanged`

_____

_(from me, @outofambit)_

Regardless, I don't think we need to attempt a refresh at the end of `updateLastStashCheckDate`, since the salient change is to `lastStashCheckCache`, which is manually updated in this method, and will be picked up in subsequent calls to `getLastStashCheckDate`.

https://github.com/desktop/desktop/blob/4a22c4669b3c5962a20bb069e4c4a4cb085985c9/app/src/lib/stores/repositories-store.ts#L271

**Comment by niik** [comment]
Thanks for writing this up @outofambit. It took me another reading of the code to understand the solution what you've already arrived to so I just wanted to put in writing that the reason why removing `emitUpdate` is safe here is because it's not part of the `Repository` object, it's only stored alongside it in the database so updating it won't be of any significance to the consumers of the `onDidUpdate` event of the repositories store.

In hindsight another potential solution here would have been what [we did for the lastUpdated field for PRs](https://github.com/desktop/desktop/blob/58ea4bd88cc3c9a5dfdd753f9320248d21a2ce08/app/src/lib/databases/pull-request-database.ts#L108) and kept the data in a separate table which would also avoid the need to [load the repository shape from the database just to write it back again](https://github.com/desktop/desktop/blob/58ea4bd88cc3c9a5dfdd753f9320248d21a2ce08/app/src/lib/stores/repositories-store.ts#L188-L190) with a preserved `lastStashCheckDate`.

**Comment by billygriffin** [comment]
This was closed in #8845. :noice:
