### ISSUE TITLE
Old account is still saved and active eventhough logged out.

### ISSUE THREAD

**Issue by OmerJog** [desktop/desktop#7590]
I installed github with user https://github.com/ron819
Later I changed my user to https://github.com/OmerJog
So I sign-out with ron819 and sign-in with OmerJog
 

The problem:
While I'm singed in as OmerJog and the repository AIRFLOW-986 (https://github.com/OmerJog/airflow/tree/OmerJog-AIRFLOW-986 ) is of OmerJog.
The commit https://github.com/OmerJog/airflow/commit/b523e4d49f6ece20a8ea08e1552c5b033dc468a1  if of two users: OmerJog and ron819 

It's impossible to remove ron819.
Everything I do with GitHub desktop has ron819 signature eventough it's not the account signed in.
Even removing GitHub desktop and reinstall didn't help.
There is only "add co author" there is no way to remove ron819.
see attached images:

<img width="805" alt="a1" src="https://user-images.githubusercontent.com/44576851/58080998-ece4da80-7bbc-11e9-9136-03749214ada6.png">
<img width="184" alt="a2" src="https://user-images.githubusercontent.com/44576851/58080999-ece4da80-7bbc-11e9-8c95-97dfb3e0b214.png">
<img width="184" alt="a2" src="https://user-images.githubusercontent.com/44576851/58081000-ece4da80-7bbc-11e9-99ae-ca68dc6dcc19.png">

**Comment by steveward** [comment]
👋 @OmerJog 

When you log in to a different account in GitHub Desktop your local `.gitconfig` does not change, which is why you are still seeing the same name and email address. GitHub uses the name and email address in your .gitconfig to associate your commits with your GitHub account. You can make changes to the name and email that are set in your .gitconfig by going to the `Git` section of the `Options` view in GitHub Desktop.

[This article](https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user) provides some further explanation about how commit attribution works. I hope that is helpful! Let me know if you have any other questions about this.

**Comment by mido1966** [comment]
Bitte nicht mher  Email  danke  No Email  Tank you




Von meinem Samsung Galaxy Smartphone gesendet.


-------- Ursprüngliche Nachricht --------
Von: Steve Ward <notifications@github.com>
Datum: 21.05.19 15:39 (GMT+01:00)
An: desktop/desktop <desktop@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [desktop/desktop] Old account is still saved and active eventhough logged out. (#7590)


Closed #7590<https://github.com/desktop/desktop/issues/7590>.

**Comment by OmerJog** [comment]
@steveward Intresting. May I point that Github support does not know about this? The answers I got with the support team are absolutely wrong.

**Comment by steveward** [comment]
@OmerJog the `.gitconfig` should be located in the root of your user folder, i.e. `~/.gitconfig`.

**Comment by darkdoom973** [comment]
Hey steve, SpideyBasit here. Did you find out the solution I am facing the same problem.
I was using another github account (abc@gmail.com), but now I wanted to use xyz@gmail.com account, and signout signin still keeps the repositories of abc@gmail.com

**Comment by steveward** [comment]
@darkdoom973 signing out of GitHub Desktop will not remove the local repositories that you have cloned from another account.
