### ISSUE TITLE
Branch pruner not using remote info to determine if a branch can be pruned

### ISSUE THREAD

**Issue by iAmWillShepherd** [desktop/desktop#7604]
There is a currently a bug in the branch pruner that causes branches to be pruned when they have not been deleted from the remote. 

![Screen Shot 2019-04-03 at 4 25 53 PM](https://user-images.githubusercontent.com/1715082/55514251-36895e00-562d-11e9-9ab1-7981829e7f8a.png)

**Reproduction steps**
1. Create a PR on dotcom
2. Merge the PR into the default branch, but **don't** delete the branch
3. Go back to Desktop and perform a fetch
4. Click Help -> Prune branches and observe the console
5. You should notice the branch that was recently merged is _marked_ as prune-able

**What I expected**
No branches should have been marked as prune-able since only 2 of 3 condition are met: 
* Branch is merged into default branch
* Branch hasn't been checked out in 14 days (this constraint is skipped when selecting Help -> Prune branches)

**Root cause**
This bug is caused by not checking to see if the remote still exists on the server. The fix would involve either using `git ls-remote` to get a list of all refs on the remote or using state that Desktop already has. I was planning to pair with @niik on implementing the latter of the two options.

_Originally posted by @iAmWillShepherd in https://github.com/desktop/desktop/pull/6916#issuecomment-479664139_

**Comment by outofambit** [comment]
_continuing on from https://github.com/desktop/desktop/pull/7616#issuecomment-495433334_

In looking through #7616, I wonder if instead of running `getBranches` for each individual branch with a filter for a particular remote branch, we could run `getBranches` once with the [pattern](https://git-scm.com/docs/git-for-each-ref#Documentation/git-for-each-ref.txt-ltpatterngt82308203) of `refs/remotes`, collect a single list of remote branches, and then use that in-memory list as we iterate through branches. (The thing I haven't figured out yet is where this single call to `getBranches` would be best inserted in the current logic of `pruneLocalBranches`.)

This would let us avoid refactoring as much of `BranchPruner` (unless we think that's worthwhile for other reasons) to add this check.

@shiftkey what are your thoughts on this approach?

**Comment by shiftkey** [comment]
> @shiftkey what are your thoughts on this approach?

I think I'm fine with trying that out. The big benefit of getting these remote branches in one batch is that we could do this before filtering, which could mean `filterBranches` no longer needs to a `Promise`-returning API and would avoid the work needed to extract a function.

I've opened #7629 to help clean up and make this flow easier to test, and I think after that's landed we can take another shot at this.
