### ISSUE TITLE
Authentification fail on non-GitHub after renaming repository

### ISSUE THREAD

**Issue by KarlvanMen** [desktop/desktop#7625]
## Description

A non-GitHub repository was renamed. Even after updating the Repository settings, I cannot log in. I updated the settings via command line and I can do regular git actions there, but the GitHub Desktop is still not working. 

## Version
* GitHub Desktop: 1.6.6
* Operating system: Microsoft Windows [Version 10.0.17763.503]

## Steps to Reproduce
1. Sync a non-GitHub repo
2. Rename repo
3. Fetch origin

### Expected Behavior
Smooth sync

### Actual Behavior
"Authentication failed"
We were unaible to authenticate with sample.url. Please enter your username and password to try again.

## Additional Information
![image](https://user-images.githubusercontent.com/19591923/58312329-c10f6200-7e13-11e9-903f-854db1638d3d.png)

### Logs
[2019-05-24.desktop.production.log](https://github.com/desktop/desktop/files/3215766/2019-05-24.desktop.production.log)

**Comment by steveward** [comment]
Thanks for the report @KarlvanMen. Just to make sure I'm understanding correctly -- does `Repository` > `Repository Settings` > `Remote` point to the correct repository location?

**Comment by shiftkey** [comment]
@steveward @KarlvanMen there's an interesting clue in the URL that we're apparently using to store new credentials:

```
2019-05-24T07:51:21.612Z - info: [ui] storing generic credentials for '[host-name]/DefaultCollection/201806_RIX_DVS_izstr%C4%81de_2._k%C4%81rta' and '[email]'
```

Note the `%` characters - this suggests a potential encoding/decoding issue. I checked this in the Chrome Dev Tools and was able to decode those characters to `201806_RIX_DVS_izstrāde_2._kārta` which might be the problem here (if we're not encoding or decoding correctly there's a good chance we're not getting the credentials in or out of the credential store).

**Comment by shiftkey** [comment]
Closing this out due to inactivity. @KarlvanMen there are some outstanding questions we have to assist with investigating these issues:

 - does `Repository` > `Repository Settings` > `Remote` point to the correct repository location?
 -  were those non-ASCII characters added as part of the repository rename?

If you can provide that information we're happy to revisit and investigate further...

**Comment by KarlvanMen** [comment]
@shiftkey Yes those non-ASCII characters were added after renaming.
@steveward Yes, it does point correctly

Sorry, for my late response.

**Comment by rgreenhalge** [comment]
I have the same issue with a github.com repository. The repo was renamed, I updated via command line and Desktop UI shows the correct repo in settings and even the correct name in the top-left of the UI; but I get "Authentication Failed" error if I try to pull/push/fetch. Should I open a new issue?
