### ISSUE TITLE
Missing alert when create existed branch

### ISSUE THREAD

**Issue by jenkijo** [desktop/desktop#7637]
**Please describe the problem you think should be solved**
When I create a branch with slash, if the name before slash exist I don't get alert

- I've branch: **develop/model**
- I would to like a new branch with name: **develop**

With Git, it will raise an error but Github Desktop is not

**VS Code Git:**
![vscode](https://2.pik.vn/2019a786a87f-26e0-42d7-ae46-45dbbc4fda82.jpg)

**Github Desktop**
![Github Desktop](https://2.pik.vn/2019b706c768-17c9-46e8-ae74-764cb070f5ac.jpg)

**Comment by shiftkey** [comment]
@jenkijo thanks for the report!

What happens if you press "Create Branch" in GitHub Desktop? Does it show an error, or something else?

**Comment by jenkijo** [comment]
Hi @shiftkey, when I clicked "Create branch" then the popup is closed but nothing happen (no error message too)

**Comment by shiftkey** [comment]
@jenkijo I tested this out with version `1.7.1-beta1` and found this underlying error:

<img width="862" alt="Screen Shot 2019-05-30 at 2 48 10 PM" src="https://user-images.githubusercontent.com/359239/58652468-0935f500-82ea-11e9-8997-b02eb8c9e3c0.png">

This looks like we're failing in a similar way to what VSCode reports (the first error), but we don't surface the error to the user (the second error).

Because of how Git uses the `/` separator to represent a directory (Windows considers it a special character and so it can't be used in a file name), you won't ever be able to create the `develop` branch because there's an existing `develop/model`. But I'll leave this open to ensure we handle this better in the app.

**Comment by tidy-dev** [comment]
This surfaces the error now.

![Shows error dialog of "Fatal: cannot lock ref" refs/heads/releaese': 'refs/heads/releases/3.3.-10-test1' exists; cannot create 'refs/heads/releases`](https://github.com/user-attachments/assets/338b99d4-f826-494c-a1f7-05603b84be7d)


Other thoughts: We could improve by detecting the error in Dugite and providing a easier to digest error. But, this clearly states the reason so I am closing as fixed.
