### ISSUE TITLE
Can't upload my project

### ISSUE THREAD

**Issue by Steveycat** [desktop/desktop#7686]
## Description
I deleted an older repository on GitHub as some things messed up and now I am trying to add the same project folder to GitHub. However, every time I select my project folder to upload it as an existing repository, it seems to try to commit to the deleted repository. No matter what I do, it just keeps on trying to commit to the no longer existing repo. I have even tried to create a repo from the desktop but identifies that it's "already on GitHub" when I know it isn't as I deleted it.

## Version

* GitHub Desktop:
1.6.6
* Operating system:
Microsoft Windows [Version 10.0.17763.504]

## Steps to Reproduce
Step 1: Have a Visual Studio Project folder and uploaded to a repo on GitHub
Step 2: delete the repo on GitHub and remove it from GitHub Desktop (without moving project to recycling bin)
Step 3: Try to upload the project again via GitHub Desktop

### Expected Behavior
Able to start a new repo with my already made project

### Actual Behavior
Tells me to push 6 commits to the origin remote
Error message when doing so: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.

### Logs
[2019-06-05.desktop.production.log](https://github.com/desktop/desktop/files/3255182/2019-06-05.desktop.production.log)

**Comment by PremoDisaB** [comment]
Fuck you

**Comment by Steveycat** [comment]
That isn't helpful in the slightest

**Comment by steveward** [comment]
@Steveycat thanks for the report. Just to clarify -- are you adding the same local repository that you previously had added to GitHub Desktop?

If that is the case then the issue is likely due to the repository's remote URL still being set to point to a repository on GitHub, which is causing the error to be thrown since you deleted that repository. You can verify this by going to `Repository` > `Repository Settings` > `Remote`. To resolve this I would recommend creating a repository with the same name on GitHub, but don't select the `Initialize this repository with a README` option. You should then be able to push your commits up to that repository.

Let me know if that does not get things working.

**Comment by Steveycat** [comment]
@steveward Thanks for getting back to me and I forgot to mention that I have managed to find a work around.
What I did was:
1. Copied the project files out of the folder they were in
2. Created a repository on GitHub with a README.md file
3. Cloned the repository and set the local repository location to where my project was
4. Copy the project into the new folder and commit the files

I will be sure to use your method if this happens again as it seems less hassle then what I did and once again, I am sorry for not closing this when I found my work around :)

**Comment by billygriffin** [comment]
No worries, glad you got it figured out @Steveycat and apologies for the confusion.

**Comment by christopher-dG** [comment]
Any chance that Desktop can create the repo if it doesn't already exist in this case? I had someone run into this issue when using [my package](https://github.com/invenia/PkgTemplates.jl) which creates local Git repos that have a remote already created.
