### ISSUE TITLE
Co-author field is not reset on a commit

### ISSUE THREAD

**Issue by robotboy655** [desktop/desktop#7695]
**The problem**
The co-author field is not reset after making a commit with a co-author, unlike the summary and the description fields.

Why it needs changing? To be consistent with the summary and the description fields. How often does someone need to do multiple commits with the same co-author(s) in a row?

**Potential solutions**
Feels like it should be reset on commit or at the very least an option for it to be reset on a commit should be added.

**Comment by steveward** [comment]
@robotboy655 thanks for the feedback. This was brought up in https://github.com/desktop/desktop/issues/3895, where the reasoning behind this behavior was shared:

>This is expected and intended behavior. The scenario we're primarily supporting are people who pair during their day and need to make multiple commits with the same attribution

Since this is not something that we are planning to change I am going to close this issue out. If you have any further feedback about this feel free to drop it here.
