### ISSUE TITLE
Multiple files selected after viewing History tab

### ISSUE THREAD

**Issue by svivian** [desktop/desktop#7710]
## Description

If you click History and then Changes, it selects all your files. To reproduce:

1. Make some changes in a repo, in multiple files.
2. On the Changes tab, select one file to see the changes.
3. Click the History tab.
4. Click the Changes tab.

Now all the files are selected, instead of showing the file you were just looking at.

## Version

* GitHub Desktop: 2.0.3

* Operating system: macOS Mojava 10.14.5

**Comment by steveward** [comment]
Thanks for the report @svivian. I've been unable so far to reproduce this behavior, but there may be something I am missing. Would you be able to upload a GIF of this behavior? Thanks!

**Comment by svivian** [comment]
Sure, here we go:

![GitHubDesktopbug](https://user-images.githubusercontent.com/207887/59117270-42531280-8945-11e9-8a9c-71be991d4229.gif)

**Comment by tierninho** [comment]
@svivian Ah, I see what you mean. I thought the issue was about the checkboxes but it is about the diff view. 

When you are on Changes, the selected file/diff is in view, and when you navigate back from History tab, all files are still selected and the default image is shown like so:

![Screen Shot 2019-06-07 at 11 41 25 AM](https://user-images.githubusercontent.com/14828183/59135076-53862a00-8919-11e9-9066-40a6ca108121.png)

cc @desktop/design for thoughts

**Comment by svivian** [comment]
Why is this tagged with `needs-design-input` and not `bug` ?

**Comment by outofambit** [comment]
Hi @svivian, the label is here to make sure we have an explicit review with one of our designers before we jump into implementing this.

There are a number of tabs, panels, etc. in the app where we don't remember _all_ of the UI state when you leave and come back, so we'll likely consider this within the larger context of our UX patterns.

**Comment by TerryChan** [comment]
@outofambit Any progress on this issue? I have the same issue. it it a bug or by design?
![image](https://user-images.githubusercontent.com/5396286/61228778-86fa7680-a759-11e9-83f5-4749b33d70a6.png)

**Comment by RayrayCf9** [comment]
Ffffc
