### ISSUE TITLE
Branch from this commit

### ISSUE THREAD

**Issue by the-avid-engineer** [desktop/desktop#7719]
**Please describe the problem you think should be solved**
I often find myself using the CLI to enter a Detached HEAD state in order to see a previous version of a repository, usually to browse the contents with my IDE.

Before 2.0, I did not have to worry about uncommitted changes. But with 2.0, I ran into a problem. The stashing feature (which is **great**, by the way) prevents me from switching to a branch if I happened to have uncommitted changes *before* i switched to the detached head state via CLI.

You can read about that, here: https://github.com/desktop/desktop/issues/7715

**[Optional] Do you have any potential solutions in mind?**
If it was possible to create a branch from a commit, I would never need the CLI; my entire git workflow would be served by GitHub Desktop, and I would never have to enter a detached head state.

![image](https://user-images.githubusercontent.com/36554739/59073691-ec1a9c80-887c-11e9-844e-e55f4c7bd430.png)

Ideally, there would be a new option on this History context menu shown above, such as "Branch from this commit".

Clicking on this option would bring up a "New Branch" modal so the user can name their branch; instead of basing off of a branch, it would be based off of the commit the user chose.

If there are any uncommitted changes, the Switch Branch modal should pop up and ask if the user wants to leave changes on the current branch or bring them to the new branch.

Problem solved!

**Comment by the-avid-engineer** [comment]
My solution was previously suggested: https://github.com/desktop/desktop/issues/3474

**Comment by shiftkey** [comment]
Tagging @desktop/product for their :eyes: and 💭here, as this sentence is a nice way to put the benefits of this proposal:

> If it was possible to create a branch from a commit, I would never need the CLI; my entire git workflow would be served by GitHub Desktop, and I would never have to enter a detached head state.

**Comment by billygriffin** [comment]
Hi @the-avid-engineer, I'd love to dig into the reason you're using this workflow in the first place to understand it a bit better, and explore potential solutions from there. In that vein, from your post I'm attracted to this piece in particular:
> in order to see a previous version of a repository, usually to browse the contents with my IDE.

It *looks* like that's the same core problem as the one mentioned in #3474, and based on your follow up comment that seems to be the case. If so, I'm going to roll this issue into that one, and paste the contents of your proposed solution because that was pretty clear as one way to solve this problem.

For context, we're still working through the future proposal issues to try to prioritize them alongside the open ones, and reopen the ones we intend to support. We have about 40 of them left to go through, of which that is one. So the fact that it's closed doesn't mean it isn't still being considered.

I'm going to go ahead and close this and roll it into that other issue, and please feel free to add anything else there that you'd like. Thanks again for the suggestion, makes total sense to me.
