### ISSUE TITLE
"Pretty print" option. Pentaho CDE Support

### ISSUE THREAD

**Issue by dmartinezgomez** [desktop/desktop#7721]
It's hard to manage single line files, without any identation, and it will be nice to have a "pretty-print" option while checking what are you commiting.

**Pentaho CDE dashboards**, for example, are just **JSON+javascript** single lined files, and it's impossible to know what are you doing while checking diffs with GithubDesktop.

A "pretty print" option could be 

- add support for **.cdfde** extension as json file. (Pentaho CDE dashboard)
- add "**pretty-print**" option.
- JSON **auto-identation** while pretty-printing.
- JSON **highlighting**.
- Replace encoded "**\r\n**" characters with new lines.

**Comment by shiftkey** [comment]
@dmartinezgomez thanks for the feedback!

Our syntax highlighting support based on Codemirror and the detection is based on file extensions, so if there's an existing solution we can use it might be possible to plug it in. Please have a read of this document to learn more: https://github.com/desktop/desktop/blob/development/docs/technical/syntax-highlighting.md

The other features about auto-indentation and replacing characters sound more challenging, because transforming the diff we get from Git may impact areas like our partial commit support. Please follow along with #6818 where we're talking about this in more detail.

**Comment by billygriffin** [comment]
Thanks @dmartinezgomez for the idea. Until there's something more specific that we can use to solve this, it seems like a limitation of our libraries, so I'm going to close this for now. If folks have ideas about how to leverage codemirror to make this possible *and* for it to work elegantly with partial committing, we're definitely open to reopening. Thanks!
