### ISSUE TITLE
Azure Devops Integration

### ISSUE THREAD

**Issue by thompson-tomo** [desktop/desktop#7722]
Summary 
I like how easy it is to clone GitHub repos, it would be great if this experience was extended to Microsoft's other repository system.

New Features 
- Add Azure Devops Account
- Add Azure Devops Server Account
- Clone repo using UI from new providers

#Nice to have
- A way to add third party git providers
- Either Dynamically populate tabs of available clone sources or rename url tab to other and load in repos from all additional accounts. Note could be same tab as DevOps

**Comment by steveward** [comment]
Thanks for contributing @thompson-tomo! 

GitHub Desktop does support working with non-GitHub repositories, but at this time we do not have any plans to add official support for non-GitHub hosting services. You can take a look at our [docs for integrations](https://github.com/desktop/desktop/tree/development/docs/integrations) to find the steps needed to authenticate using Azure DevOps.

I'm going to close this issue out since this is not something we are planning to work on at this time, but thank you for your feedback in sharing how we can make GitHub Desktop better for you!

**Comment by sbingham-MET** [comment]
Since it may well be 10 years until ADO gets feature parity with GitHub Enterprise, can this feature request be re-evaluated?
