### ISSUE TITLE
Stash UI not appearing

### ISSUE THREAD

**Issue by seanknox** [desktop/desktop#7736]
## Description

Was curious to try out the stashing feature, but it doesn't seem to be working for me in v2.0.3. Am I missing something?

## Version

* GitHub Desktop: 2.0.3

* Operating system: MacOS Mojave

## Steps to Reproduce

1. Stash a file with git on the command line
2. Open GitHub Desktop (or switch to it if open)

### Expected Behavior

Stash UI appears

### Actual Behavior

GitHub Desktop doesn't indicate presence of any stashes

**Comment by iAmWillShepherd** [comment]
@seanknox 

Desktop will only show stash entries that it creates on your behalf. That means, if you'd like to see your stashed changes, you must switch branches while you have uncommitted changes and select the option to stash changes on your local branch.

**Comment by seanknox** [comment]
Why is this by design? What developer using git would expect stashing to work this way

**Comment by billygriffin** [comment]
Hi @seanknox, thanks so much for the feedback! Based on quite a bit of user research, we decided to scope our initial iteration of stashing to the workflow on switching branches. For a number of reasons, we chose not to surface stashes made *outside of Desktop* because they don't have that same branch association and because the possibility of restoring a stash, only to have another one pop in behind it was flagged as something that would be confusing for folks we spoke with in interviews and usability testing. We're open to iterating on this concept, but for now that's why we made the decision we did for the initial iteration. Thanks for the feedback!

**Comment by seanknox** [comment]
Totally understand the motivation to simplify the use stashes. Though I think the decision to tie stashes to a branch greatly reduces their usefulness as well as teach a behavior that isn't part of git. I also worry about teaching a workflow that's only achievable through the GUI.

**Comment by billygriffin** [comment]
That's totally fair criticism. We're definitely not wedded to our current implementation, and we're going to see how people engage with this over the next couple months and go from there. Generally, our philosophy is that Desktop isn't intended to have any sort of feature parity with Git or be a tool that just puts a button for everything you can do with Git, but rather tries to reduce friction in the things that people are trying to accomplish. Hopefully for beginners, this introduces them to Git in a way that feels less intimidating, but provides enough conceptual understanding such that they can work in any environment as they learn more over time. Thanks again for the feedback!

**Comment by jaydenseric** [comment]
I'm a Tower user, and every so often I'll download GitHub Desktop and see how it is coming along. I just wasted 10 minutes trying to figure out why GitHub Desktop wasn't letting me see all my Git stashes:

<img width="282" alt="Screen Shot 2020-05-29 at 10 29 26 am" src="https://user-images.githubusercontent.com/1754873/83207759-58319700-a197-11ea-895e-d45b7f60776d.png">

If the features is not Git stashes at all, it should be called something else. I'm not stupid for thinking that a "Show Stashed Changes" button in a Git app would show the Git stashed changes. Please don't mistake my frustrated tone for entitlement; if it was clear this app doesn't support stashes I would patiently wait for the day it does.

**Comment by tierninho** [comment]
@jaydenseric Thank you for the feedback and apologies if we didn't provide the feature set you were expecting. What part of the Stash feature was frustrating to you? We are interested in learning more to help improve the application. Were you expecting to be able to stash and pop on-demand? That would be a totally fair expectation if so.

Some limitations with Desktop:
- Currently, the stash dialogue is only prompted when you are switching branches. 
- A stash was initiated from within Desktop. 
- There is no manual mechanism to stash on-demand... yet.

**Comment by jaydenseric** [comment]
@tierninho if you "stash" using GitHub Desktop (i.e. when switching branches), can that stash be seen using other Git apps like Tower, or the Git CLI?

**Comment by tierninho** [comment]
Short answer is no, a stash cannot be seen outside of Desktop if initiated within Desktop. We chose stashing to be controlled via the UI instead of via git as it is traditionally done for a few reasons.

I think this explains our philosophy around the choice to do so: 
> Generally, our philosophy is that Desktop isn't intended to have any sort of feature parity with Git or be a tool that just puts a button for everything you can do with Git, but rather tries to reduce friction in the things that people are trying to accomplish. Hopefully for beginners, this introduces them to Git in a way that feels less intimidating, but provides enough conceptual understanding such that they can work in any environment as they learn more over time. 

Thanks again for the feedback, and note we're definitely not wedded to our current implementation. We're going to see how people engage with this over the next couple months and go from there.

**Comment by jaydenseric** [comment]
2 main pieces of feedback then, in order of importance:

1. Since the "stash" functionality has nothing to do with Git stash, call it something else like a "snapshot" or "backup" of changes. This will prevent a LOT of unnecessary confusion for beginners and experts:
   - There is a responsibility to teach a beginner the right terminology. A lot of beginners will dabble in the CLI and get confused that their stashes are not showing up, and use the word "stash" incorrectly with colleagues if someone tries to help them out.
   - An expert will be confused why UI related to "stashes" seemingly doesn’t work properly, like I was.
2. Viewing, creating and applying Git stashes are an essential feature of a Git app, to the point that I wouldn't consider an app without it useful. People who don't stash either copy and paste code to notes (missing out on nice diffs that add a lot of context), commit commented out code, or avoid multitasking; at any rate they move slower or reduce code quality. There seems to be 2 main reasons given why actual Git stashes are not supported already:
   - It's difficult to implement. But surely it's less complicated than managing commits?
   - Git stashes are "not beginner friendly" and create "friction". This is not true at all. You click a button and it backs up your changes, what's complicated about that?

**Comment by jaydenseric** [comment]
Something else undesirable about GitHub Desktop only stashing; it locks you into that app. Something nice about using an industry standard tool like Git is that you can switch between all sorts of GUIs and CLIs and be productive without lock-in.

**Comment by tierninho** [comment]
Thanks for taking your time to add your thoughts @jaydenseric very helpful feedback! We look forward to exploring your ideas during the next iteration of stashing. Again, apologies if this caused some confusion. Have a good weekend.

**Comment by billygriffin** [comment]
Hi @jaydenseric - I just wanted to clarify a couple points. 

First, if you make stashes in Desktop, they should be visible elsewhere. It's only stashes made *outside* Desktop that are not visible *in* Desktop due to the way we designed the feature.

We are looking at adding the ability to stash without switching branches in #8197. Though that will leverage our current design paradigm in which stashes are tied to branches. I totally understand the criticism of that approach, though we still think it's a much more intuitive way of thinking about stashes than just inheriting Git's exact implementation, and the feedback we've gotten from the vast majority of people has confirmed that.

Hope that's helpful!
