### ISSUE TITLE
Human error working with branches

### ISSUE THREAD

**Issue by davesmiths** [desktop/desktop#7744]
Hi

**Please describe the problem you think should be solved**
When I use branches I often find myself making commits to the wrong branch. I believe this is because I'm not used to using git and GitHub Client with branches. I imagine other new and occasional users could find this a problem.

The problem as I see it is that it is difficult to keep a mental model of a repository and its branches. My eye sees the Current Repository, Changes, Summary field, Description field and Commit button in a vertical flow. In the moment I do not see the Current Branch, which is to the right, nor do I take-in the commit button telling me the name of the branch to commit to.

**[Optional] Do you have any potential solutions in mind?**
My suggestion would be to place the Current Branch switcher in the vertical flow immediately after Current Repository. Then it could read Current Repo, Current Branch, Changes, Summary field, Description field, Commit button

I have no basis to say whether this would work or not. And there may be a better way.
It might not help.
But I believe it would.
It at least seems logical to me writing it ;)

Thanks for GitHub Client. I am most grateful for not having to use the command line.

all the best
Dave

**Comment by billygriffin** [comment]
Hi @davesmiths! The proposed solution would necessitate a pretty huge design change in the app, so I'm going to close this issue because we'd want to hear a lot more feedback that others are experiencing this problem before we'd want to go down that road. However, I am really interested in learning more about how you're experiencing this. When you're committing to the wrong branch, is it that you're committing to `master` when you intended to be committing to a new branch off of `master` instead? We've got [this issue](https://github.com/desktop/desktop/issues/7023) describing a guiding flow for when folks are on a protected branch, and I'm wondering if the problem you're describing is along similar lines. Thank you!!

**Comment by davesmiths** [comment]
Hi Billy

Funnily enough my recent error was the other way around. I end up committing to a branch instead of master.

I'm trying to use GitHub the way I believe it makes sense, which is to create a branch for a particular feature/change to the code, like "add new thing".

So I work away on the "add new thing" branch for a few minutes and then, before thinking (and committing), my job calls for me to work on something else (on the master)

I diligently work away, unforunately making changes to the branch instead of the master.

In theory if I spot the issue there and then I can work it out by committing certain changes to the branch and others to the master. Thank you for adding this possibility!

But before now, and recently, I have committed branch and master changes to the branch, and then it's too much of a mess to figure out XD

Thankfully nothing too crucial done wrong so far, and with discipline I'm sure I'll get myself straightened out.

Thanks for getting in touch and asking!

I'm happy to answer more questions should you have any

all the best
Dave
________________________________
