### ISSUE TITLE
How to set up auto update server?

### ISSUE THREAD

**Issue by TerryChan** [desktop/desktop#7747]
Currently I'm reading the code on auto update of GitHub Desktop, I can understand the part in GitHub Desktop client, I found it used the autoUpdater of Electron. For the server side, I found it used an API endpoint to see if there is a new version of the app. If there is no new version, the endpoint will return HTTP 204. If there is a new version, it will return a HTTP 200 JSON-formatted response, containing a url to a .zip file, and I found both Wndows and MacOS use the same API endpoint, but I have some questions on the server of the auto update: Since the API endpoint only returns a .zip file for macos, how does the server response for Windows requests? What's the difference for Windows and Macos in the server side? Can you share some knowledge on how can I build my own auto update server to let GitHub Desktop work? Thank you.

**Comment by shiftkey** [comment]
@TerryChan we use [`Squirrel.Mac`](https://github.com/Squirrel/Squirrel.Mac) and [`Squirrel.Windows`](https://github.com/Squirrel/Squirrel.Windows) for our update frameworks in Desktop, and these have documentation for what the server implementation needs to do:

 - for `Squirrel.Mac` - https://github.com/Squirrel/Squirrel.Mac#server-support
 - for `Squirrel.Windows` it's can be done on any HTTP server that can serve files - the client tries to download a `RELEASES` file under the given URL, compares the available versions against it's current version, and works out what it needs to download to get up to date (delta packages can be used rather than downloading the full package).  [This document walks through the update process](https://github.com/Squirrel/Squirrel.Windows/blob/develop/docs/using/update-process.md#update-process) and the docs provide examples for hosting on [IIS](https://github.com/Squirrel/Squirrel.Windows/blob/develop/docs/using/microsoft-iis.md), [Amazon S3](https://github.com/Squirrel/Squirrel.Windows/blob/develop/docs/using/amazon-s3.md) and [GitHub releases](https://github.com/Squirrel/Squirrel.Windows/blob/develop/docs/using/github.md)
