### ISSUE TITLE
Standalone Installer

### ISSUE THREAD

**Issue by pmn** [desktop/desktop#776]
Similar to the standalone installer for GitHub Desktop on Windows, users in the enterprise will want a standalone installer. 

Requested features of a standalone installer: 
* Can be installed with no internet connection. 
* Support for silent / automated installs for purposes of network deployment.
* Ability to install for all users (lower priority)

**Comment by josephrowe** [comment]
I found this thread with google. I'm looking for an MSI installer for schools. I need to install git desktop app using my teacher account, and when other users logon they don't have to re-install the app.

please send me a trusted URL, on the git domain. I've seen several MSI installers, but they come from very odd URLS. If there is a way to hack the default installer please list those steps. Thanks, J

current steps:

logon as teacher to win7 pro using school active directory authentication
install git desktop app
restart, have student logon
result: No ability to run git desktop app

expected result: Some type of installer with option to install for all users

**Comment by niik** [comment]
> expected result: Some type of installer with option to install for all users

Hey @josephrowe, we're using Squirrel.Windows for our installation framework which does offer an MSI but it doesn't quite behave like standard machine-wide install. I'm certainly no expert on how it works but from my limited understanding it installs a logon script that launches the installer for each user which signs in. There's no machine-wide installation available in the classic sense. The MSI is available at https://central.github.com/deployments/desktop/desktop/latest/win32?format=msi if you want to experiment with it and there's some [basic documentation](https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/machine-wide-installs.md) available in the Squirrel.Windows repository.

**Comment by josephrowe** [comment]
Hello Markus (niik)  I'm still trying to find a way to install git desktop for all users. 


Currently when I install the app and I logout, and a new user logs on there is no app for the new user.  When I install python they have an option "install for all users" .  I'd like that option.   I'd really appreciate a trusted URL to an installer.   I'm the teacher installing git desktop for students.  

The MSI download you suggested downloads a file from a domain githubusercontent.com
I tried to use network solutions to check that domain ownership and got no results.

**Comment by niik** [comment]
Hi @josephrowe, I'm sorry to hear that you're having problems getting Desktop installed for your students. The state of installation on Windows has unfortunately not changed since the last time we visited this issue and we're still limited to what the Squirrel.Windows project supports and one of its core features is that installation are on a per-user basis. If you're willing to try the MSI installer that's great but unfortunately there's not much documentation beyond what I already linked above and it's possible that there's caveats that we're not familiar with yet.

> I'd really appreciate a trusted URL to an installer.

The URL I provided above (https://central.github.com/deployments/desktop/desktop/latest/win32?format=msi) is the official source for the MSI installer. You can also find the same link on https://desktop.github.com.

> The MSI download you suggested downloads a file from a domain githubusercontent.com

I suspect that's the application icon:

https://github.com/desktop/desktop/blob/04cb3aaefed772f3d1657f20c87886727fdac998/script/package.ts#L84

> I tried to use network solutions to check that domain ownership and got no results.

The domain is signed with GitHub's certificate which should alleviate any fears of malicious actors

![image](https://user-images.githubusercontent.com/634063/58085336-d3439300-7bbc-11e9-99c2-7ee1967b53c5.png)

**Comment by josephrowe** [comment]
Hi Marcus,

I'm really thankful you are there at GitHub still..I've got to get up early
and we have faculty meetings until 5pm.. teaching is great but so many
headaches...

I will email you later...I very much appreciate your help

Joe
