### ISSUE TITLE
rebasing in repos with >20 branches can leave branch stale

### ISSUE THREAD

**Issue by outofambit** [desktop/desktop#7761]
I often find myself in situations where rebasing onto a local branch doesn't include the latest changes on the remote version of that branch. My current workaround is to switch to that branch, update it (via the pull button), and then switch back to my working branch and rebase it onto the now updated branch.

The root cause is that during fetch we don't update branches in repos with more than 20 branches.

https://github.com/desktop/desktop/blob/d2cdde4bf37672141fb4f9431ae420f16cb642ee/app/src/lib/stores/app-store.ts#L3053-L3066

A couple possible solutions:
* add logic to the rebasing flow to use remote branches instead of locals ones when they are ahead
~~* the vast majority of the time i'm rebasing, i'm rebasing on the default branch. perhaps we could always update the default branch, even when there are > 20 branches?~~ (this is the current implementation)

**Comment by shiftkey** [comment]
> perhaps we could always update the default branch, even when there are > 20 branches?

Just coming in here to suggest this change, so big 👍 to this improvement

**Comment by billygriffin** [comment]
+1 to the suggestion for a middle ground of *always* updating the default branch.

**Comment by tierninho** [comment]
Tested this issue and here are the steps for rebasing with 20 branches:

- **Prereq**: Repo has more than 20 branches
- Add LOCAL branch, don’t publish it
- Go to an existing branch and find it on Github
- Add file there and return to Desktop
- Go back to the LOCAL branch
- Select Rebase menu option
- Select the existing branch and complete rebase

**Result**: the file that I added was not on the local branch after completing the rebase

#### Screenshots

Rebase local on existing branch:
![Screen Shot 2019-08-05 at 10 59 59 AM](https://user-images.githubusercontent.com/14828183/62496575-0ab1ec80-b775-11e9-87f4-a0f491c246ba.png)

After rebase, existing branch still had not pull the file down from GitHub:
![Screen Shot 2019-08-05 at 11 02 56 AM](https://user-images.githubusercontent.com/14828183/62496577-0ab1ec80-b775-11e9-8ee4-1f793e52a832.png)

After fetching, the file shows up (latest commit):
![Screen Shot 2019-08-05 at 11 03 19 AM](https://user-images.githubusercontent.com/14828183/62496578-0b4a8300-b775-11e9-9f98-2d97c6604264.png)

v2.1.0, mac

**Comment by kuychaco** [comment]
@outofambit and I dug deeper into this issue and I want to share some context that we unearthed. 

GitHub Desktop periodically fetches and fast forwards all local branches to match what exists on the remote, and allows you to manually trigger this by clicking the "Fetch origin" button. For performance reasons this is done only if the number of branches in the repo is less than 20. For repos with greater than 20, only the default branch is fast forwarded. 

@outofambit originally hit this issue by manually updating branches by clicking "Fetch origin" and then rebasing onto a non-default branch. In order to address this case, we made it so that all recent branches get fast-forwarded in addition to the default branch. This increases the likelihood that a rebase will contain commits fetched from the remote branch first. See #8081 for fix.
