### ISSUE TITLE
github desktop is not working while clicking on fetch origin

### ISSUE THREAD

**Issue by SurbhiAbrol** [desktop/desktop#7763]
## Version

* GitHub Desktop:

* Operating system:

**Comment by shiftkey** [comment]
@SurbhiAbrol thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by tierninho** [comment]
@SurbhiAbrol if you are using Enterprise, please follow along with #7713 which is likely the same issue.
