### ISSUE TITLE
Stash disappears after undoing initial commit

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#7773]
If you revert the initial commit and a stash was present, then the stash is hidden until the initial commit is submitted again. 

I think the likelihood of this getting repeated is very slim, but I wanted to file in case there is a similar scenario that might result in the same thing 🤷‍♂ Perhaps a user wants the initial files stashed? 

Happy to close this otherwise.

Repro:
- Set up new repo with two branches
- make stash on default branch
- revert all commits on default branch

2.0.4-beta1, mac

**Comment by shiftkey** [comment]
> If you revert the initial commit and a stash was present,

@tierninho can you confirm this is related to **undoing** the first commit (which removes it from history), rather than **reverting** the first commit (which adds a new commit to the history).

This is a tricky case, because the "View Stash" functionality is associated with the current branch, and removing the first commit turns the repository back into an unborn repository without a branch (the mentions of `master` in the UI are literally a placeholder at this point).

**Comment by tierninho** [comment]
@shiftkey I reverted the initial commit and then clicked undo, so I guess it became an unborn repository without a branch. Makes sense now, thanks 👍 

As this logic is expected and due to the unlikelihood of this becoming a real problem, then I will close for now.
