### ISSUE TITLE
showModal fails due to not being in a document

### ISSUE THREAD

**Issue by outofambit** [desktop/desktop#7785]
This error traces back to https://github.com/desktop/desktop/blob/3862ddbd87c59d1e887524b88af806b404a3dcc6/app/src/ui/dialog/dialog.tsx#L207 and is really only possible if `componentDidMount` was called before `onDialogRef`, which [according to the React docs](https://reactjs.org/docs/refs-and-the-dom.html#callback-refs) shouldn't be possible? Still investigating...

**[InvalidStateError](https://haystack.githubapp.com/desktop/rollups/a192b575e178fafb18250102360d2c26)** &mdash; First occurred on 2019-06-11 01:32:40 -0700

```
Failed to execute 'showModal' on 'HTMLDialogElement': The element is not in a Document.
```

**Comment by tierninho** [comment]
Spotted this Chromium issue with the same error: https://chromium.googlesource.com/chromium/blink/+/678d890f35dc3a88685c4e51a2637ade37adcdfe/LayoutTests/fast/dom/HTMLDialogElement/dialog-show-modal-expected.txt

**Comment by outofambit** [comment]
thanks @tierninho that's a good find! i followed some links there to https://codereview.chromium.org/85773002/patch/1/10007 which confirms that this error means the dialog failed to open entirely.

**Comment by DanielMoss** [comment]
Hi. I had the same problem, and found this issue while I was trying to figure out what was going on. Here's what I've learnt since:
https://github.com/facebook/react/issues/9117#issuecomment-284228870 - You can successfully mount into elements that aren't part of the DOM. In my case, I effectively had the following initialisation code:
```javascript
var container = document.createElement('div');
ReactDOM.render(<ModalComponent />, div);
document.body.appendChild(container);
```
Since `showModal` was running in the `componentDidMount` block for `ModalComponent`, it was happening before line three had been executed, and that meant that the `dialog` I'd constructed hadn't actually reached the DOM yet. I swapped lines two and three, and that eliminated the problem.

I also found [this stackoverflow thread](https://stackoverflow.com/questions/26556436/react-after-render-code) helpful, before I figured out that my personal problem was due to how I was initialising things.

**Comment by outofambit** [comment]
oh hey, this definitely shouldn't be assigned to me anymore. fyi @tidy-dev @sergiou87 😄

**Comment by tidy-dev** [comment]
This seems to be addressed by a [null check](https://github.com/desktop/desktop/pull/8290) added in this PR.
