### ISSUE TITLE
Handle multiple files for check / uncheck 

### ISSUE THREAD

**Issue by gilbdev** [desktop/desktop#7790]
**Please describe the problem you think should be solved**
- currently we can only check changed files one-by-one
- i would like to select multiple file and check/uncheck them all
- clicking on checkboxes should not invalidate the current multiple selection

**[Optional] Do you have any potential solutions in mind?**
have all selected file be checked/unchecked when multiple files are selected
-if some mixed checkd/unchecked status for the files, sohuld get the check state from the line the user is currently checking

[x] fileA
[  ] fileB
[x] fileC

=> if user select those 3 files, and click on the checkbox of fileB, mark all as checked, but if clicking on fileA or C, uncheck all (then  check all on second click)

**Comment by billygriffin** [comment]
Hi @gilbdev, thanks for the issue! I think part of this is the competing selection possibilities between selecting a file and checking that file for inclusion in a commit. I'm going to try to restate the problem statement here, please let me know if this seems accurate:

"I'm often trying to include many files in a commit, and while there's a way to select multiple files and get a context menu, there's no way to check multiple files at a time for inclusion in a commit."

I would like to point out that the checkbox in the `x changed files` header area will check or uncheck all the boxes, so my understanding is that this issue is about partial inclusion of files in a commit.

Do I have all this correct?

**Comment by tierninho** [comment]
@gilbdev Thanks for filing your suggestion. Have you tried selecting any files with either `shift` or `cmd/ctrl` buttons and then clicking the `enter` key as it will toggle between check and unchecked?

> clicking on checkboxes should not invalidate the current multiple selection

It sounds like you would like the checkbox selections to be independent of the any highlighted files. I understand this could be frustrating, but by clicking on a checkbox you shift the focus away from any selected files.

**Comment by gilbdev** [comment]
@billygriffin i think you got it right :)
@tierninho thanks for the tip! clicking the `enter` key does effectiveley do (almost) what i'm looking for !
i think this can be enhanced though, as it's not intuitive (i didn't find it right away ^^)

could be either in the contextual menu, just like the "discard n selected changes.." we could have a "check/uncheck n selected changes for commit" or just have the mouse click do the check/uncheck on the whole selection and not the only line (that would require a bit more work, to keep the selection while clicking on the checkbox, and this could be misunderstanded too)

**Comment by tierninho** [comment]
@gilbdev Great to hear! We will keep your suggestions in mind for the next iteration of this area. Thanks for using Desktop.

**Comment by hubgit** [comment]
Pressing `Enter` after selecting multiple files was what I needed - I expected to find this action in the context menu.

For context, I'd run `prettier` over a large number of files, and wanted to select some of those files to add to a commit.

**Comment by st4rdog** [comment]
> Pressing `Enter` after selecting multiple files was what I needed - I expected to find this action in the context menu.
> 
> For context, I'd run `prettier` over a large number of files, and wanted to select some of those files to add to a commit.

Pressing Spacebar also works.

**Comment by kaster14** [comment]
I would also like to see a "right click" option to "check selected" when selecting files to include in a commit. Use case is I have several hundred files that are modified and I only want commit them 100 at a time, don't want to manually check them. Using "enter" or "space" does work but not at all intuitive. [
![forGithub](https://user-images.githubusercontent.com/13577286/125344901-df06ec00-e325-11eb-8611-8ee7592eac98.png)
](url)

**Comment by SplenectomY** [comment]
Agreed that the enter key / space key to multi-select is not obvious, and a context menu option would make sense here. Typically, in other applications, it's common that when you have a lot of selected options (blue state), simply clicking the toggle box on one of those selected objects will apply the same toggle to all the selected items. This would be the expected UX for the majority of people.

**Comment by shagunMathur** [comment]
There should be a search dialog box too so that user can search a particular file to check/uncheck from a number of files. This will help to a great extent.

**Comment by tidy-dev** [comment]
Copied from #14198

### The feature request

If you select a list or range of files, you can right-click and **_discard_** those changes, but you can't add them to the selected files that you want **_included_** in the commit.

![image](https://user-images.githubusercontent.com/7254992/158875877-137f1167-6b77-4e1c-a7b7-c1387369c8ef.png)

This would be very helpful when dealing with a large numbers of changed files that I am wanting to selectively add to different commits. At present the only option is to select them one by one after clicking to select all or select none. This can get rather tedious when working with hundreds of files.

### Proposed solution

Add a context menu option named "Include 16 selected files". In functionality, this would check the box for each selected item to include it in the list of files included in the commit.

### Additional context

I realize that probably the biggest barrier here is in making the terminology clear. You have a _selection_ that means you checked the box, and a _selection_ that means you have highlighted the file in the list. It would confuse the user if we give them the option to "Add the selection to the selection", or to "Remove the selected files from the selection".

We could use terms like **Include** to refer to the checkbox, and **selection** for the files that are selected in the list. The rationale behind this is that the end goal is to select which files should be included in the commit.

Along those lines, I would propose the following wording for the context menu:

- **Include 16 selected files**
- **Do not include 16 selected files**

For the second item, I intentionally did not use the logical antonym _Exclude 16 selected files_ because this could easily be confused with _ignoring_ the files in git, which is not the intent. It keeps the focus on the end result of which files are _included_ in the commit.

To make this even more intuitive, I would suggest that the context menu also be aware of whether the items are checked to include in the commit. If nothing is currently selected (no boxes checked), we only need to show them the option to include the files. Similarly, if all the files are selected, the only relevant option is to _not include_ them. If we have a mixed selection, we can show both options.

Thanks for your consideration!!
