### ISSUE TITLE
I don't seem to have a way to force a fetch

### ISSUE THREAD

**Issue by paterasMSFT** [desktop/desktop#7805]
If GitHub Desktop knows I've got remote changes, I can't seem to tell it to fetch, because the pull button replaces the fetch button:

![image](https://user-images.githubusercontent.com/35780775/59523569-a888e980-8e9f-11e9-97aa-ebbee864a47b.png)

and as near as I can tell Desktop doesn't have another way to fetch (at least not an intuitive one). There isn't even an option in the repository context menu:

![image](https://user-images.githubusercontent.com/35780775/59523829-4c729500-8ea0-11e9-8f82-e99d1280b5c2.png)

When working with a large repo, I sometimes don't want to pull if I'm somewhat close to remote/master. But I don't know that if it hasn't fetched recently. In the above example, it's only been 20 minutes, but earlier today, the last fetch was over a day prior. That might have been large enough to justify a pull, but I had no way to tell since my only option was to pull.

I can manually do a command-line fetch, of course, but it would be very nice to have the option to force a fetch within GitHub desktop, even if I've got remote changes.

**Comment by tierninho** [comment]
@paterasMSFT Thanks for the suggestion. Here is a [good explanation](https://github.com/desktop/desktop/issues/4950#issuecomment-397694857) of our background fetching process.

> In the above example, it's only been 20 minutes, but earlier today, the last fetch was over a day prior.

Note that we can tell from the API when the last push to that repository was, and if we know there’s not been anything pushed since then there’s no point trying to fetch. This is probably why the button did not update.

> I can manually do a command-line fetch, of course, but it would be very nice to have the option to force a fetch within GitHub desktop, even if I've got remote changes.

We will consider this for the next iteration when we touch this area of code. 👍

**Comment by billygriffin** [comment]
@paterasMSFT Would you mind helping us understand *why* you don’t want to pull, and in what cases that becomes particularly important? I’m trying to understand if others might have a similar problem and how we can validate it before we think about solutions. Thanks!

**Comment by paterasMSFT** [comment]
>Note that we can tell from the API when the last push to that repository was, and if we know there’s not been anything pushed since then there’s no point trying to fetch. This is probably why the button did not update.

In that particular case, there were a dozens of commits that needed to be fetched.

>Would you mind helping us understand why you don’t want to pull, and in what cases that becomes particularly important?

Sure. Simply put, our build process is long, and I don't like having code that's out of sync with my local deployment for debugging purposes. If I'm not too far out of sync with master, I don't pull so I don't put myself in that position.

Thanks for the quick response, and for this really great product. I'm very much enjoying it thus far!

**Comment by niik** [comment]
cross-referencing https://github.com/desktop/desktop/issues/3054 here since they seem to be similar.

**Comment by billygriffin** [comment]
In #3054, @robrix requested something similar to this **except with a keyboard shortcut as well.** I wanted to make sure the specifics of that was captured here as I'm going to close that issue and combine it with this one.

**Comment by yannickrondeau** [comment]
@billygriffin It's been a while since you've asked, but wanted to add on top of the answer you got.

> Would you mind helping us understand why you don’t want to pull

In my specific case, I had a local branch that wasn't already pushed; therefore I had the push button. 

However, I wanted to do a code review / testing of a specific branch created by a colleague. The branch wasn't appearing in the list of branch. My first though was, "Well, I will fetch the origin !". I couldn't do that because of the push button, I had to switch to the main branch before, then fetch origin. Normally, I think that GitHub Desktop should have fetched automatically, but didn't.

**Comment by KyokaKirk** [comment]
> If GitHub Desktop knows I've got remote changes, I can't seem to tell it to fetch, because the pull button replaces the fetch button:
> 
> ![image](https://user-images.githubusercontent.com/35780775/59523569-a888e980-8e9f-11e9-97aa-ebbee864a47b.png)
> 
> and as near as I can tell Desktop doesn't have another way to fetch (at least not an intuitive one). There isn't even an option in the repository context menu:
> 
> ![image](https://user-images.githubusercontent.com/35780775/59523829-4c729500-8ea0-11e9-8f82-e99d1280b5c2.png)
> 
> When working with a large repo, I sometimes don't want to pull if I'm somewhat close to remote/master. But I don't know that if it hasn't fetched recently. In the above example, it's only been 20 minutes, but earlier today, the last fetch was over a day prior. That might have been large enough to justify a pull, but I had no way to tell since my only option was to pull.
> 
> I can manually do a command-line fetch, of course, but it would be very nice to have the option to force a fetch within GitHub desktop, even if I've got remote changes.
