### ISSUE TITLE
Marketingplatforms.Github.com

### ISSUE THREAD

**Issue by Verdinjoshua26** [desktop/desktop#7811]
## Version

* GitHub Desktop:

* Operating system:

**Comment by Verdinjoshua26** [comment]
embed github to marketingplatforms.verdinjoshua26.com

**Comment by shiftkey** [comment]
@Verdinjoshua26 thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
