### ISSUE TITLE
I just can play my game more mine computer every moment when i use stranges start a confusion and severe attacks in machine

### ISSUE THREAD

**Issue by MarcoRhodes** [desktop/desktop#7833]
## Version

* GitHub Desktop:

* Operating system:

**Comment by MarcoRhodes** [comment]
i need people private chat and i try to explain

**Comment by shiftkey** [comment]
@MarcoRhodes thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by NewbeSouken** [comment]
Hello brother sorry for my ignorance I very much need your help and all who can me and want me to become a productive and useful person.
Thank you so much for everything!

**Comment by NewbeSouken** [comment]
Dear fellow and brother I unfortunately do not know for sure what is
happening I know you as I can say brought me to reality again but
there are some things I have to do because I want to repay the help
you gave me just I'm not studying for over 12 years so i don't
remember i have a bit of difficulty so i would like patience and start
from the beginning.
Thanks for listening
Good vibes for everyone.
forgive my ignorance but neither git for windows i know how to use
correctly i don't know what i should do when cloning the repositories
so i would need a little attention so i can start developing and
walking again


Em sex, 23 de ago de 2019 às 19:49, MA <notifications@github.com> escreveu:
