### ISSUE TITLE
Pre-fIlled Branch Creation Name Input

### ISSUE THREAD

**Issue by barnesheaton** [desktop/desktop#7837]
**Problem**
When creating a new branch, I'd like to be able to pre-fill the **Name Input**. This is because 90% of the time my branches have identical prefixes around 10 characters longs.

**Potential Solution**
MacOS has a built in text replacer for abbreviations, but it only works in certain applications. There may be some way to enable this (I believe it's called `Text Replacement`) for the text inputs inside the app?

However it would wonderful to have some sort of preference where I could set pre-filled text for the branch creation **Name Input**

**Comment by billygriffin** [comment]
Hi @barnesheaton, thanks for the idea! Because we haven't seen this come up before, people have such varying ways of using and naming branches, and our research hasn't indicated that there are similar widespread patters, I don't think this use case is likely to be widespread. My response is based on some assumptions, and if those aren't quite right and we see further evidence of this likely reducing friction for many more users, we're always happy to revisit. I really appreciate you making the issue, and hope the app is otherwise working well for you.
