### ISSUE TITLE
Use the local git user if exists instead of global

### ISSUE THREAD

**Issue by TryHardDood** [desktop/desktop#7848]
When setting the git user for a local repository it uses the global user instead of the local one.

After setting the user in a repo (Saved in .git/config)
`git config user.name 'username'` 
`git config user.email 'email@example.com'`

It still uses the values of the global config file.

**Comment by shiftkey** [comment]
@TryHardDood thanks for the report! I wasn't able to reproduce this with GitHub Desktop 2.0.4 on macOS, and I'll walk you through the steps I took to see if I've missed any details.

1. Check my global settings in Desktop under the **Preferences** menu:

<img width="504" src="https://user-images.githubusercontent.com/359239/59920031-9529d100-93ff-11e9-96c0-bb6a6239344b.png">

2. Open the repository in a terminal and change the settings:

```
$ git config user.name "Not Brendan Forster"
$ git config user.email foo@example.com
$ git config --local  -l --show-origin
file:.git/config        core.repositoryformatversion=0
file:.git/config        core.filemode=true
file:.git/config        core.bare=false
file:.git/config        core.logallrefupdates=true
file:.git/config        core.ignorecase=true
file:.git/config        core.precomposeunicode=true
file:.git/config        user.name=Not Brendan Forster
file:.git/config        user.email=foo@example.com
```
3. Switch back to Desktop and note the avatar in the commit form - it's rendering the gravatar fallback because it can't find anything related to my fake email address.

<img width="277" src="https://user-images.githubusercontent.com/359239/59920011-82170100-93ff-11e9-900d-c6cec82a214a.png">

4. You can hover your mouse over the avatar and see the commit details that Desktop will use:

<img width="291"  src="https://user-images.githubusercontent.com/359239/59920030-9529d100-93ff-11e9-8e07-4c4b0c273e64.png">

5. Make a commit in the repository, and switch over to History to see that it's showing the same details:

<img width="742" src="https://user-images.githubusercontent.com/359239/59920199-21d48f00-9400-11e9-973f-295fcd2600cf.png">

6. Confirm in the terminal the `user.name` and `user.email` are the local configuration:

```
$ git show HEAD
commit 13b6cc7349c476a799d406a40d11b314a5981846 (HEAD -> master)
Author: Not Brendan Forster <foo@example.com>
Date:   Fri Jun 21 08:33:38 2019 -0300

    made a commit

diff --git a/FOO.md b/FOO.md
new file mode 100644
index 0000000..e69de29
```

**Comment by TryHardDood** [comment]
Yep, I was wrong. 😅
I can't believe I did it wrong twice.

Everything is working as intended. Thanks!
