### ISSUE TITLE
Rename repository in the UI (or via a Workaround)

### ISSUE THREAD

**Issue by he-dev** [desktop/desktop#7856]
I have a couple of repositories checked out in multiple folders. When I add them to `GitHub Desktop` I see the same name of each of the repositories a couple of times. I can distinguish between them only by hovering with the cursor on their names.

I'd be very useful if `GitHub Desktop` allowed to rename what is shown in the UI. 

---

But maybe until this is (ever) implemented there is a workaround like modifying its settings in the `Roaming` folder?

**Comment by niik** [comment]
Hi @he-dev, thanks for opening this.

At the moment there's no good way to differentiate between several copies of the same repository cloned to different locations in the app. We have been making strides addressing some of the most reported issues with repository organization in https://github.com/desktop/desktop/issues/6460.

It would be very helpful to us if you could describe the workflow which requires you to keep multiple copies of the same repository in more detail. Apart from https://github.com/desktop/desktop/issues/1929 it's not something we hear about all that often.

**Comment by he-dev** [comment]
@niik sure, in my case the typical workflow looks like this:

- I checkout repository (A) from GitHub in my _GitHub_ folder where I keep a clean copy of it that I push back to GitHub
- I then checkout the same repository (A) also from GitHub in another folder, let's call it _work_ where I keep a copy that is modified for internal purposes and that has multiple remotes; this one is pushed mainly to the internal server and only sporadically back to GitHub (when _neutral_ modifications are made).

There is also a 3rd use case when I need to maintain two branches at the same time and have each of them checkedout in a different folder (it's sometimes easier to have two folders, one for each branch, than switching between branches because this way you can have multiple IDEs open at the same time and work with different branches).

As a workaround, until it's officially supported by the application, I had hoped that _GitHub Desktop_ would store its settings in a _sqlite_ database inside the _Roaming_ folder but couldn't find anything editable there.

**Comment by Rodion8888** [comment]
http://example.com/svn/ <= Don’t include trunk or branches

**Comment by adamkiss** [comment]
@niik I'll chime in here — I also have two different branches checked out at the same moment — I'm working through complete rewrite, and having both old version (`master`) and new version (`in-progress`) helps with comparing what I'm working on right now vs how it was in the old version.

**Comment by SewoonNam** [comment]
I have same issue. i need DirectoryName or i want make nickname option.

**Comment by subspacefield** [comment]
@niik I also reported this issues (#8593).  I work with 2 remote teams and I might have to do a code review, help with a merge issue or debug an issue.  If I am in the middle of a task I prefer to checkout the branch to a separate folder.

**Comment by Timelapser** [comment]
Another use case for this could be differentiating between different work trees & branches. Different copies of the same repository are more likely when having multiple trees or branches for quick switching.

As described in #5764 and #8158 there is no way to visually distinguish different versions of the same repo. Since automatic tagging is not currently possible: renaming/nicknaming/labeling repositories manually could very well be a viable intermediate solution.

**Comment by steveward** [comment]
Requested by @lefebvrecharlie in #8671.

**Comment by steveward** [comment]
Requested by @valentinpc in #9307:

> >### Problem
> >I am facing the situation where the same repository is required on different locations on my hard-drive. >This scenario is easy to handle with command-line, however the desktop app makes it impossible. I >can add multiple instances of the same repository on my hard drive, however they all show up with the >exact same name. I can not distinguish them.
> 
> >### Solutions
> 1. Allow rename for a repository name in the repository list. Indicate with color that the name has changed.
> 2. Show folder name of cloned repo instead of git repo name in the list.
> 3. Allow to add a comment next to the name.

**Comment by lefebvrecharlie** [comment]
Still waiting for this feature. :)

**Comment by ericdrobinson** [comment]
I would also like to throw my support into this ticket. My workflow involves building assets for the [Unity](https://unity3d.com/) and I end up having multiple copies of the same repository on the same machine so that I can quickly test changes on different versions of Unity.

In the Repository listing I end up seeing all of the repositories with the same **repository** name. What I really want is the ability to either:

1. Provide a Repository-specific nickname to use within the GitHub Desktop application.
1. Optionally view the repositories by their local directory name. This could be done by, for example, either:
   1. Providing an option to toggle showing repos by "Repository Name" or "Local Root Directory Name" in the GitHub Desktop preferences.
   1. Providing a hotkey (e.g. Shift) that, when the mouse is hovering over the list, would reveal the local root directory names.

I understand that the Hover Tooltip contains the Repo->Directory mapping. This is suboptimal as the text is extremely verbose and the wait is really annoying when trying to work quickly.

**Comment by wshaver** [comment]
Ran into this issue today, where we have one repo with two very different branches. A months-long merge process from two separate teams. Both branches installed locally. Would be lovely to tell which one you're in at a glance. Both in the big repo list, and in the "current repository" thing when the list is closed.

**Comment by jsunsawyer** [comment]
This is something that I could also benefit from. My use case is for a project where I'm currently working on a branch to create a new theme for a sister website of the main site. I need unique .env and asset files for this site, so it's set up in its own path, and has its own url, and all that. Not being able to tell these apart is really confusing, and makes me constantly second guess my commits. (Always double checking to make sure I'm working in the right spot.)

**Comment by JamesCatt** [comment]
+1 for this feature.

In my case, I have several different apps that pull data/content from a centralized repository—which has to be cloned for each app when working with it locally. The result is the same repo in the list with the same name over and over, so I have to resort to hovering over each one individually to see the path before I can find the one I'm looking for.

**Comment by billygriffin** [comment]
Hi folks, we're working on this and will plan to ship it to beta next week. We merged a PR #12000 and we've got a couple minor iterations to do on it, and then it'll be available.

**Comment by billygriffin** [comment]
Since the followup PRs here are now merged on onto beta, I'm going to close this issue. Thanks for all the feedback and as always sorry for the delay, but hope this is useful for you! I should go out to production sometime in the next few weeks, or if you want to use the beta, you can do so here: https://github.com/desktop/desktop/#beta-channel

**Comment by staabm** [comment]
This feature saves me minutes every day. Love it <3

Thanks to everyone involved

**Comment by daGUY** [comment]
Thank you, thank you, thank you! I have been [asking for this feature](https://github.com/desktop/desktop/issues/6460#issuecomment-480100806) for _years_. Due to the particular naming convention I use at work, I have literally dozens of repositories that all have the same name. I can finally just give them all aliases now!
