### ISSUE TITLE
GitLab Support

### ISSUE THREAD

**Issue by zzj0402** [desktop/desktop#7875]
Add GitLab Account login

**Comment by niik** [comment]
Hey @zzj0402, thanks for opening this issue. I'm going to quote [a response that @billygriffin wrote to a similar issue](https://github.com/desktop/desktop/issues/7791#issuecomment-501788755) a few weeks ago

> GitHub Desktop does support using BitBucket, GitLab, Azure DevOps repos, and it's documented how to clone them here: https://github.com/desktop/desktop/tree/development/docs/integrations
>
> While we intend to continue basic support for repos from other sources, our primary goal is for the GitHub <-> GitHub Desktop experience to shine. We don't intend to support publishing local repos to other hosts *from Desktop* in the near term, so I'm going to close this issue. Thanks again!

Since this question has been answered in that other issue I'm going to close this issue.
