### ISSUE TITLE
reset branch to other commit in repository

### ISSUE THREAD

**Issue by konopkoman** [desktop/desktop#7882]
Can't do Rebase with the follow branching logic:
- Create feature branch B from A
- Make changes in B
- Switch to A, merge with B
- Create feature branch C from A
- Make changes in C
- Switch to A, merge with C
- Switch to B again
- Want rebase B from A, but _This branch is up to date with B_

Maybe I'm wrong doing Rebase?
Thanks

**Comment by shiftkey** [comment]
@konopkoman thanks for the details. I think I understand the workflow but please correct me if I've missed some details.

The rebase flow will only run if there are commits on `B` that don't exist on `A`, and I believe this step, when all the commits from `B` are merged into `A`, means the rebase won't run:

 - Switch to A, merge with B

Can you clarify what you are trying to do in this last step? 

 - Want rebase B from A

Are you looking to reset `B` so that it points to the tip of `A`? Or something else?

**Comment by konopkoman** [comment]
> Can you clarify what you are trying to do in this last step?
Here I need update A with changes from B 

> Are you looking to reset `B` so that it points to the tip of `A`? Or something else?
Here I need update B with changes of A+C

**Comment by shiftkey** [comment]
There's some context to the workflow here that I want to clarify.

> Here I need update A with changes from B

Rebasing a branch is about taking a range of commits and applying them to a different part of the repository history. The issue in this specific scenario is that there are no outstanding commits on `B` at this time, so a rebase isn't possible with how Desktop currently works. If you were to continue to work in `B` and make more commits, you would then be able to rebase those on top of `A` later on.

> Here I need update B with changes of A+C

If you don't have any outstanding commits in `B`, but want to bring it up to date with the commits in `A` (which also contains `C` because of the previous merge) , this feels like you're interested in `reset`-ing `B` to point to a different commit. 

This isn't supported currently in Desktop, but on the command line, it would look like this: `git checkout B && git reset A --hard`. This updates `B` to point to the commit associated with `A`, which is a different flow to how rebasing works.

**Comment by konopkoman** [comment]
> This isn't supported currently in Desktop, but on the command line, it would look like this: `git checkout B && git reset A --hard`. This updates `B` to point to the commit associated with `A`, which is a different flow to how rebasing works.

Thanks, I hope this feature will be implemented soon

**Comment by shiftkey** [comment]
@konopkoman I can't make any promises at this point about whether this is a scenario we will support, but I'll defer to @desktop/product to see if they have any questions or thoughts.

**Comment by billygriffin** [comment]
Hi @konopkoman, thanks for the issue! This is not something we've heard previously that I was able to find. We're certainly open to revisiting if it's something we hear about more from users wanting similar functionality, but given that this isn't a workflow that we see most folks using, supporting it seems complex relative to the amount of benefit it would provide. Thanks for the suggestion, and it's nice that this issue exists for future evaluation if we see more evidence.
