### ISSUE TITLE
Suggestion: notification on successful remote operation (push, pull, etc.) if the app isn't the active window

### ISSUE THREAD

**Issue by iamtheyammer** [desktop/desktop#7898]
**Please describe the problem you think should be solved**

We use a monorepo at my company, and it takes a bit to push, pull, etc. from remote. I'd love to get a notification when they finish running in the background (if the app is not the active window).

**[Optional] Do you have any potential solutions in mind?**
A notification like "Push complete" would be great so I check email while waiting for the push/pull/etc.

**Comment by tierninho** [comment]
@iamtheyammer Thank you for filing the issue. I am going to cross-reference it with an existing issue touching on the same feature.

Here is our current stance on notifications: https://github.com/desktop/desktop/issues/2825#issuecomment-438807773

**Comment by billygriffin** [comment]
@iamtheyammer Thanks for the issue! Just to add a bit more color since this does pertain to a specific problem you're having that notifications might be helpful to solve, there are pretty dramatically different preferences about push notifications, and most folks we've talked with would find them distracting so if we were to support these, configurability would be really important. Because it's not a light lift, we'd want the evidence to be stronger that this is something a lot of people would benefit from, and we're not there yet. I really appreciate you bringing it up though and it's helpful to hear from more folks.
