### ISSUE TITLE
Move multiple repositories into new folders in one go

### ISSUE THREAD

**Issue by he-dev** [desktop/desktop#7904]
I'm reorganizing my repositories and need to move many of them into different folders. `desktop` wants me however to pick each one manully. This is a lot of tedious work so I was wondering whether there is any _hidden_ trick for updating paths in one go? `desktop` must be storing these settings somewhere. Could you tell me which file I have to edit?

It's the `C:\Users\%USER%\AppData\Roaming\GitHub Desktop\IndexedDB\file__0.indexeddb.leveldb\*`, right? But how do I open it? What format is it?

OK, I've found it in the [repositories-database.ts](https://github.com/desktop/desktop/blob/bee4c6bb74d8060c6514fad3ab6a3f366d4c8eaf/app/src/lib/databases/repositories-database.ts), it's [Dexie](https://dexie.org). Now, let's see how I can edit it...

**Comment by outofambit** [comment]
hi @he-dev thanks for reaching out! i don't think there's any shortcuts for that. you could perhaps remove the repos from desktop, move them into new folders and bulk add them back into desktop? you can multi-select and drag folders from explorer into the desktop app window and it will add all of them to its list. i think that would be the fastest. let me know if you have any further questions!

**Comment by CollinChaffin** [comment]
I second this request.  In order to bulk drag from new location, you first must deal with the VERY ugly remnants and popups from the orphans of "not found".  The only viable workaround to the above suggestion right now is to literally blow away your entire APPDATA and reset GHdesk to defaults, first.

It would just be nice to (even in devtools) have a documented method to edit the db paths.  I too have found the Dexie tables, but it takes someone with pretty decent JS know-how to then put that code together to dump into devtools to facilitate an export/import process.
