### ISSUE TITLE
Unable to see full path in changed files

### ISSUE THREAD

**Issue by jjxtra** [desktop/desktop#7906]
Please let us resize the left panel in the changes window so we can see the entire path. Why limit the width of that panel? Very frustrating...

**Comment by outofambit** [comment]
Thanks for reaching out!

We require the template to be filled out when submitting all issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway 😀

**Comment by outofambit** [comment]
We haven't heard back so I'm going to close this, but feel free to comment and we can reopen the issue. Thanks!
