### ISSUE TITLE
Untrusted Server Error

### ISSUE THREAD

**Issue by UgurAldanmaz** [desktop/desktop#7925]
## Description
I use GitHub Desktop without any Enterprise configuration. I have some repositories which are not hosted on GitHub as well as hosted on GitHub (public and private repositories).

I have been seeing an error dialog which tells "This may indicate attackers are trying to steal your data". Please see the following screenshot.

What is it and what should I do?

## Version
* GitHub Desktop: 2.1.0
* Operating system:  Microsoft Windows [Version 10.0.18362.175]

## Steps to Reproduce
It occurs arbitrary. I have no idea what triggers it.

### Logs

![image](https://user-images.githubusercontent.com/5686267/60754580-c7d0ed80-9feb-11e9-943f-88536c940f74.png)

**Comment by UgurAldanmaz** [comment]
@Daniel-McCarthy is it you that mentioned in the error message

> The certificate (Daniel) is invalid or untrusted.

**Comment by steveward** [comment]
@UgurAldanmaz thanks for the report. Could you send over the log file from GitHub Desktop so that I could get some more information about this error?

To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`. The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue. Thanks!

**Comment by UgurAldanmaz** [comment]
[2019-07-06.desktop.production.log](https://github.com/desktop/desktop/files/3374791/2019-07-06.desktop.production.log)
Hi @steveward, thank you for your interest. Here is the log file you requested. 

P.S I have redacted some private repository addresses with <REDACTED>

**Comment by tierninho** [comment]
@steveward 

Not much in the logs. Maybe proxy blocking the user?

```
2019-07-06T09:17:09.735Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
fatal: unable to access 'https://git.<REDACTED>:8011/<REDACTED>.com.git/': Could not resolve host: git.<REDACTED>
```

**Comment by UgurAldanmaz** [comment]
Thanks for the answer @tierninho. 

> Maybe proxy blocking the user?

What does it mean exactly? The git URL in the log lines you pasted is accesible only VPN and it is highly possible that most of the time my VPN is not active. I have been using GitHub Desktop with that repos for 2 years, but this error is very new for me.

The warning phrase on the error dialog makes me worry about safety of my data.

> This may indicate attackers are trying to steal your data

I don't think that this information text has been put by you just for "proxy blocking" issue. There should be a serious problem. Otherwise, this text is too much to show for my case.

**Comment by tierninho** [comment]
@UgurAldanmaz That message was directed at another employee as he may have dealt with something similar before. 

The problem could also be a result of a setting on your VPN. Have you checked?

**Comment by steveward** [comment]
@UgurAldanmaz my feeling is that there could be an issue with the SSL certificates on your machine, which is why this error is being thrown. Are you running any antivirus/security software that could be performing SSL filtering? We've seen that causes these types of issues in the past.

The `Could not resolve host` error is usually a network issue, either caused by a firewall, proxy, or a misconfiguration with your network (or possibly your VPN). 

Are you able to successfully perform Git operations using the command line?

**Comment by 82andre** [comment]
I have the same problem, but the untrusted certificate instead of "Daniel" was "zxv10".
Worse, I thought the "Add Certificate" button would take me to a certificate registration window, but it just disappeared with the message.
The Github desktop is working, but I don't know if I opened any exploits on my system.
I don't know if it's really installed and how I could remove zxv10, I looked for this name in certmgr.msc but it has nothing like that.

I always hibernate the system, so github was open when system restarted, and without internet until it found wifi, this could be part of the problem. I started using the app 3 days ago.
GitHub Version: 2.1.0
Windows 7 Home Premium
LogFile: 
[2019-07-30.desktop.production.log](https://github.com/desktop/desktop/files/3449252/2019-07-30.desktop.production.log)

**Comment by tierninho** [comment]
@82andre Are you able to successfully perform Git operations using the command line? Are you running any antivirus/security software that could be performing SSL filtering?

The `Could not resolve host` error is usually a network issue, either caused by a firewall, proxy, or a misconfiguration with your network (or possibly your VPN).

**Comment by tierninho** [comment]
Closing this issue out due to inactivity. Please reach out if there is new information and we will be happy to reopen it.

**Comment by Andrea-Serrani** [comment]
@tierninho 
I have the same problem, happened once at the moment.
I'm not using VPN and i can perform Git operations using the command line.
Any advice on checking vulnerability?

<img width="631" alt="Schermata 2020-01-27 alle 21 03 34" src="https://user-images.githubusercontent.com/53516933/73244749-f7735d00-41aa-11ea-9a6f-fce9bde98314.png">

**Comment by tierninho** [comment]
@Andrea-Serrani a couple of questions:

 - are you running any sort of proxy tool?
 - if you open a browser to `https://api.github.com/zen` what do you see for the browser's security information?

Here's mine on Chrome:

<img width="435" alt="screen shot 2017-07-27 at 9 58 53 am" src="https://user-images.githubusercontent.com/359239/28671242-57ceaecc-72b2-11e7-8e55-009a58f7d45d.png">


Also, possible to include your logs? See the Help menu in Desktop. Thanks!

**Comment by Andrea-Serrani** [comment]
Hi!
• No proxy
• Attached
• Attached
[2020-01-27.desktop.production.log](https://github.com/desktop/desktop/files/4126883/2020-01-27.desktop.production.log)
<img width="410" alt="Schermata 2020-01-29 alle 09 16 48" src="https://user-images.githubusercontent.com/53516933/73339103-476c2580-4278-11ea-81c8-9f5d18399d06.png">

**Comment by tierninho** [comment]
@Andrea-Serrani I spotted this error in your logs. Please try moving Desktop out of the downloads folder and updating to the latest version. See the `GitHub Desktop > About GitHub Desktop` menu to update.

> 2020-01-27T08:11:47.388Z - error: [ui] Error checking for updates
Error: Cannot update while running on a read-only volume. The application is on a read-only volume. Please move the application and try again. If you're on macOS Sierra or later, you'll need to move the application out of the Downloads directory. See https://github.com/Squirrel/Squirrel.Mac/issues/182 for more information.

Let us know if that resolves things.

**Comment by katronai** [comment]
@tierninho
I also have the same problem, just happened recently.

- no VPN
- no proxy
- no antivirus/security software
- can perform Git operations using the command line
- https://api.github.com/zen shows "It's not fully shipped until it's fast."
- [Log file](https://github.com/desktop/desktop/files/6795565/2021-07-10.desktop.production.log)

GitHub Desktop: 2.9.0 (x64) (latest version, without any Enterprise configuration)
Operating system: macOS Big Sur [Version 11.4]

Should I be worried about something?

<img width="594" alt="Screenshot 2021-07-10 at 18 51 12" src="https://user-images.githubusercontent.com/3822815/125169335-616e9f00-e1b2-11eb-85e7-6c5cedeb0c73.png">

**Comment by AdilBNC** [comment]
Same problem happens on our end while using a secured by VPN connection to reach our Internal Github Enterprise Server.
The browser acces works fine and the deployed SSL certificate is trusted.
Github Desktop have some kind of isse.
Nothing in the logs!

**Comment by amish25** [comment]
Having this same issue too via Github Enterprise Server - the problem seems to be linked with having 8.8.8.8 as an alternative DNS server however this cannot be changed. All git commands over command line work without fail?

**Comment by Blueteak** [comment]
I had this issue, and it was due to my System Date/Time being incorrect, google chrome also refused to load but gave that reason. After resolving the Date/Time issue both Chrome and Github Desktop worked without complaint.

**Comment by geomorillo** [comment]
how to stop this message i know my server is unsecure but this window appearing every 5 seconds is really anoying please how to disable it

**Comment by Happyrobot33** [comment]
can confirm this still happens even with a global git config set to not verify SSL. Please fix! its extremely annoying!

**Comment by hezzze** [comment]
it's still happnening, there should be a way to disable it

**Comment by geomorillo** [comment]
this is still happenning please help

**Comment by artivilla** [comment]
Unless this is a critical issue, I would urge we can get rid of this messaging. It's confusing at best and isn't serving any purpose other than scaring users away.

**Comment by geomorillo** [comment]
Not working still happening on Version 3.4.15 (x64)
