### ISSUE TITLE
Authentication Faile

### ISSUE THREAD

**Issue by pmadhar2** [desktop/desktop#7942]
I have been trying to clone existing repository, but it fails with the 
Authentication Failed message, I am trying to resolve this from past 3 mnths

https://github.optum.com/icue/icue-impl.git

**Comment by outofambit** [comment]
Hi @pmadhar2, thanks for reaching out!

We require the template to be filled out when submitting all issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway 😀

**Comment by tierninho** [comment]
@pmadhar2  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
