### ISSUE TITLE
Authentication Failed when publishing new local repo - Already logged in

### ISSUE THREAD

**Issue by Ali-Parandeh** [desktop/desktop#7944]
## Description

Created a new folder. Initialised a local repo with git. Wrote a csharp file and committed to local HEAD. Opened Github desktop and selected the local repo to push to my account. Window pops up asking for username and password. Upon submission, form pops up again and says authentication has failed and asks for username and password again. Tried signing out and in but didn't work.

Had to create a remote repo from my browser. Clone it to desktop. Move my files in there and commit it then push it up to my remote.

## Version

* GitHub Desktop: V2.1.0

* Operating system: Microsoft Windows [Version 10.0.17763.615]
## Steps to Reproduce

1. Create a folder
2. Create a file
3. Initialise a local repo with git
4. Commit to the repo on local HEAD
5. Open Github Desktop and add local repo
6. Press publish to remote
7. Fill in username and password and press enter
8. Sign out and Sign in
9. Repeat steps 6 and 7.

### Expected Behavior

Published repo on my github account.

### Actual Behavior

Authentication window keep opening up asking for username and password.
p.

### Logs

Log file attached.
[2019-07-13.desktop.production.log](https://github.com/desktop/desktop/files/3388736/2019-07-13.desktop.production.log)

**Comment by steveward** [comment]
@Ali-Parandeh thanks for the report! It looks like you were already successfully logged in:

`2019-07-13T11:31:48.163Z - info: [ui] [AppStore] found account: Ali-Parandeh (Ali Parandeh)`

But the operations were failing due to invalid remote repository URLs:

```
stderr:
remote: Not Found
fatal: repository 'https://github.com/Ali-Parandeh/' not found
```

That URL points to your user profile and not a specific repository under your account.

I also see this error, which points to a repository that does not exist:

```
remote: Repository not found.
fatal: repository 'https://github.com/Ali-Parandeh/devops-intro-project.git/' not found
```

These types of issues will cause the authentication dialog to appear, which is confusing since it is not an authentication issue but an invalid remote issue. We're tracking this in https://github.com/desktop/desktop/issues/5661. Sorry for the confusion there.

I'm going to close this issue out, but let me know if you run into this again and I can assist you in debugging the issue.

**Comment by Ali-Parandeh** [comment]
Thank you Steve for looking into this for me.

I wasn't expecting my remote to be pointing to the intro-to-devops repo at all since I had deleted it long ago and been pushing to my other repos for a while.

You said the operations are failing due to invalid remote repository URLs:
`stderr:
remote: Not Found
fatal: repository 'https://github.com/Ali-Parandeh/' not found`

But I was trying to create a new repo and the correct url wasn't yet generated for me to point the local repo towards to. Does that mean I will have to create a repo on Github then push the local to it? Can I not make a local repo, push it to github and have github repo created for me as well?

Thank you,
Ali
