### ISSUE TITLE
 <>

### ISSUE THREAD

**Issue by 9105090515007** [desktop/desktop#7948]
## Version

* GitHub Desktop:

* Operating system:

**Comment by Rexogamer** [comment]
..?

**Comment by steveward** [comment]
Thanks for reaching out @9105090515007!

Would you mind filling out the rest of the issue template so that we can better understand what is causing the problem you are experiencing? Without that information it will be difficult to help you further. It would especially be helpful if you could upload the log file from GitHub Desktop, which will give more details about the specific error you are seeing. 

Thanks for understanding and meeting us halfway. 😀
