### ISSUE TITLE
https1891993

### ISSUE THREAD

**Issue by thtcc1891993** [desktop/desktop#7950]
## Version

* GitHub Desktop:

* Operating system:

**Comment by steveward** [comment]
Thanks for reaching out @thtcc1891993!

Would you mind filling out the rest of the issue template so that we can better understand what is causing the problem you are experiencing? Without that information it will be difficult to help you further. It would especially be helpful if you could upload the log file from GitHub Desktop, which will give more details about the specific error you are seeing. 

To access the log files go to the  menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`. 

The log files are created daily -- please send over a log file as an attachment from a day where you experienced the issue

Thanks for understanding and meeting us halfway. 😀
