### ISSUE TITLE
Changes in a warehouse in desktop cannot be all selected for one-time submission

### ISSUE THREAD

**Issue by moon-cup** [desktop/desktop#7958]
Changes in a warehouse in desktop cannot be all selected for one-time submission

**Comment by steveward** [comment]
Thanks for reaching out @moon-cup!

Would you mind filling out the rest of the issue template so that we can better understand what is causing the problem you are experiencing? Without that information it will be difficult to help you further. It would especially be helpful if you could upload the log file from GitHub Desktop, which will give more details about the specific error you are seeing. 

Thanks for understanding and meeting us halfway. 😀

**Comment by tierninho** [comment]
By "warehouse", I believe you mean "repository". 

You cannot select all the changed files by clicking here:
![Screen Shot 2019-07-18 at 11 49 26 AM](https://user-images.githubusercontent.com/14828183/61494560-2b470d80-a952-11e9-9c35-ba37253b631b.png)

Happy to reopen this issue if you need further assistance.
