### ISSUE TITLE
Cannot logout

### ISSUE THREAD

**Issue by Chethana-S** [desktop/desktop#7960]
**Please describe the problem you think should be solved**
A clear and concise description of what the problem is and who else might be impacted. Screenshots are encouraged.

Example:

> “When I run into a merge conflict, I don’t know where to go to resolve it. Anyone who works off of multiple branches will likely run into this problem at least occasionally.”

**[Optional] Do you have any potential solutions in mind?**
A clear and concise description of one or more solutions you think might solve the problem. Please include any considered drawbacks or tradeoffs, and how users might use your solution(s). Screenshots or mockups are helpful here!

**Comment by steveward** [comment]
Thanks for reaching out @Chethana-S! If you need to log out of GitHub Desktop you can do so by going to `File` > `Options` `Accounts`.

If that is not helpful, would you mind filling out the rest of the issue template so that we can better understand what is causing the problem you are experiencing? Without that information it will be difficult to help you further. It would especially be helpful if you could upload the log file from GitHub Desktop, which will give more details about the specific error you are seeing. 

Thanks for understanding and meeting us halfway. 😀
