### ISSUE TITLE
fatal: the remote end hung up unexpectedly error: RPC failed; curl 55 Send failure: Connection was aborted Everything up-to-date

### ISSUE THREAD

**Issue by Radicaii** [desktop/desktop#7975]
Hello, I am aware my file size is larger then the allowed allotted space but how do I configure github to work with this so I can collaborate on this project with friends as I can not Publish, is there a way to exclude a particular assets directory/folder which we can keep upto date locally via our cloud file sharing?

[2019-07-17.desktop.production.log](https://github.com/desktop/desktop/files/3401980/2019-07-17.desktop.production.log)

I have tried lfs which created this file:

.gitattributes
# Auto detect text files and perform LF normalization
* text=auto
Content/ filter=lfs diff=lfs merge=lfs -text

**Comment by Radicaii** [comment]
I have tried

.gitattributes
# Auto detect text files and perform LF normalization
* text=auto
Content/ filter=lfs diff=lfs merge=lfs -text

**Comment by iAmWillShepherd** [comment]
@Radicaii 

I think this help article is a good first step to move forward. Looking over your logs, this issue is not a Desktop issue, so I'll instead refer you to [GitHub Support](https://help.github.com/en/articles/about-github-support).

> is there a way to exclude a particular assets directory/folder

The short answer is yes, but without knowing any details on your project or your needs, I'm not sure if my solution is a fit for your problem, but I will share anyways just in case it is.
1. Add the directory to `.gitignore`
1. Remove them from the index `git rm <file> --cached`

**Comment by iAmWillShepherd** [comment]
@Radicaii, I forgot to include the link I mentioned when I first posted my response. I've since gone and updated it with the link. Sorry about that.
