### ISSUE TITLE
Can't install Application

### ISSUE THREAD

**Issue by rowboater** [desktop/desktop#7976]
So when I try to install GitHub for Windows I get an error 
![image](https://user-images.githubusercontent.com/2257238/61383878-6809fa80-a8a7-11e9-8fe7-d2a81bb85ece.png)

This laptop does have some funny security settings on it.

Does anyone know a way around this?

I also get this issue with:
Atom, Slack & Gitkraken

**Comment by iAmWillShepherd** [comment]
@rowboater, sorry you're having issues getting Desktop up and running. Given that you are having this problem with other applications, my suspicion is this is caused by antivirus. Can you share the details our issue template specified?

**Comment by rowboater** [comment]
I'll do my best. We don't run any anti-virus bar the M$ stuff so I don't think thats what it is. But what I hav e looked into suggests that its the result of a section of the registry not being accessible... problem is I don't know what.
I have noticed that these are all electron based apps.

**Comment by iAmWillShepherd** [comment]
@rowboater, given that this is happening with multiple Electron apps, I not confident this is a Desktop issue. I recommend opening an issue over in https://github.com/electron/electron as that team is in a better position to help.

**Comment by shiftkey** [comment]
For reference, the error code `0xc0000364` might be this entry in the [Windows Error Code](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/1bc92ddf-b79e-413c-bbaa-99a5281a6c90) list, which maps to `STATUS_ACCESS_DISABLED_BY_POLICY_OTHER`:

<img width="664" src="https://user-images.githubusercontent.com/359239/61652870-5782c700-ac8f-11e9-8723-9a610f8acaa4.png">

I'm not 100% sure it's this, because I thought the error message would also include the relevant group policy rule responsible for this, based on the template message. @rowboater I'm curious if your computer does use Group Policy here, as it'd be great to know a bit more about this error if it's affecting different Electron apps.

**Comment by rowboater** [comment]
@iAmWillShepherd ok Thanks yeah, that probably a better place to raise it.
@shiftkey yes, we do use a group policy. I'm assuming its something major as it slows my machine from booting by a good minute or so. I'll try asking the infrastructure team but I'm pretty sure they wont have a clue which policy is causing the problem.
