### ISSUE TITLE
Auto-fetch repository when the current repository is changed

### ISSUE THREAD

**Issue by andreazorzi** [desktop/desktop#7985]
When the current repository is changed it would be better if an auto fetch were performed.

**Comment by tierninho** [comment]
@andreazorzi Thanks for the suggestion. We already implement background fetching at set intervals and also every time you switching repos. 

What action happened that you were you expecting a fetch to occur?

**Comment by shiftkey** [comment]
Putting this back to `more-info-needed` to indicate there are some outstanding questions

**Comment by andreazorzi** [comment]
@tierninho Hi, it seems to work intermittently, sometimes when I switch a repository it performs an automatic fetch other times it doesn't, I attach some screenshots made after changing repositories, doing some tests it seems that it doesn't perform an automatic fetch in the first minutes after opening GitHub Desktop

![Cattura](https://user-images.githubusercontent.com/15615862/61781710-23c9ad80-ae05-11e9-8af0-431ee2bce149.PNG)
![Cattura2](https://user-images.githubusercontent.com/15615862/61781711-23c9ad80-ae05-11e9-855e-3b2b1b9b617b.PNG)

**Comment by Rexogamer** [comment]
> @tierninho Hi, it seems to work intermittently, sometimes when I switch a repository it performs an automatic fetch other times it doesn't, I attach some screenshots made after changing repositories, doing some tests it seems that it doesn't perform an automatic fetch in the first minutes after opening GitHub Desktop
> 
> ![Cattura](https://user-images.githubusercontent.com/15615862/61781710-23c9ad80-ae05-11e9-8af0-431ee2bce149.PNG)
> ![Cattura2](https://user-images.githubusercontent.com/15615862/61781711-23c9ad80-ae05-11e9-855e-3b2b1b9b617b.PNG)

Are you able to provide any logs?

**Comment by andreazorzi** [comment]
@Rexogamer I tried to see if there was a log file, but it doesn't seem to be there

**Comment by Rexogamer** [comment]
> @Rexogamer I tried to see if there was a log file, but it doesn't seem to be there

Hmm....

**Comment by tierninho** [comment]
@andreazorzi Logs are under the `Help` menu in case you were looking elsewhere. 

Also, were there any changes made to that repo/branch that you expected to be fetched?

Note that we can tell from the API when the last push to that repository was, and if we know there’s not been anything pushed since then there’s no point trying to fetch. 

Here is a [good explanation](https://github.com/desktop/desktop/issues/4950#issuecomment-397694857) of our background fetching process.

**Comment by shiftkey** [comment]
> Note that we can tell from the API when the last push to that repository was, and if we know there’s not been anything pushed since then there’s no point trying to fetch.

I think this is what is happening in this case, and without more information it's not clear to me what's actionable here.

The `pushed_at` field is what we use:

<img width="492" src="https://user-images.githubusercontent.com/359239/62063990-5824db80-b202-11e9-987f-849c097e8af8.png">

@andreazorzi what we're looking to confirm here is whether this path is encountered: 

https://github.com/desktop/desktop/blob/f0b548ea970c8c24f7a619cdcaa2b3b42146c67b/app/src/lib/stores/app-store.ts#L1540-L1542

This isn't put into the log files because of how often we might do this check, but if you open the dev tools and use the repository you should see it when we skip performing a fetch:

**Comment by tierninho** [comment]
@andreazorzi As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
