### ISSUE TITLE
Code format

### ISSUE THREAD

**Issue by c1nq0** [desktop/desktop#7992]
There seems to be a different how files are downloaded from github.

With normal download to zip and extract documents are in Unix format.
When cloning with Git Desktop the files appear in windows format.

This is a bit annoying, especially when using winmerge, etc.. (whole document is different)

**Comment by shiftkey** [comment]
@c1nq0 thanks for the feedback!

A zip archive of a repository can differ from the cloned repository because of the presence of the `.gitattributes` file (that can influence the line endings of a file).

If you have a specific repository that you believe isn't working as expected, please contact [GitHub Support](https://github.com/contact) as this isn't something the Desktop team can help you with.
