### ISSUE TITLE
Hide resent repos

### ISSUE THREAD

**Issue by notiv-nt** [desktop/desktop#8002]
Should be an opportunity hide this list

![Layer 1](https://user-images.githubusercontent.com/10743009/61649839-e6f19f80-acba-11e9-8521-041466076c55.png)

**Comment by billygriffin** [comment]
Hi @notiv-nt, thanks for the issue. We understand that everyone doesn't have the same preferences when it comes to how repos are organized. However, for essentially every feature we release, there are a few people who ask for their to be a toggle to disable it. Our general philosophy is that there should be consistent expectations from the product from users, and therefore we very rarely offer toggles to disable a particular feature, usually when it's blocking a typical and common workflow (for example, we added the ability to cancel out of the merge conflicts modal so folks who prefer a more manual conflict resolution path could still do that). We haven't seen enough evidence that this is blocking or too disruptive for people since its release, so we don't have plans to add a toggle to disable it. Thanks again for weighing in.

**Comment by notiv-nt** [comment]
Why is it just not possible to turn it off? Do you care about users?
