### ISSUE TITLE
"sorry, i" text when filter does not find a match

### ISSUE THREAD

**Issue by Rexogamer** [desktop/desktop#8013]
**Please describe the problem you think should be solved**
The wording used for certain errors is "Sorry, I cant find that _thing_". I think this should be changed to "Sorry, that <thing> could not be found." 

**Example:**
If you're in a repo you don't own, you might want to make a PR for your changes. You mgith want a new branch to be made; if you try typing the name of this new branch in, you get "Sorry, I can't find that branch."

**[Optional] Do you have any potential solutions in mind?**
As I said, change the text to "Sorry, that _thing_ could not be found."

**Comment by Rexogamer** [comment]
@shiftkey provided a [list of instances where this can be found.](https://github.com/desktop/desktop/search?q=sorry&unscoped_q=sorry)

**Comment by tierninho** [comment]
@Rexogamer were you planning on working on this or is this available for the community?

**Comment by Rexogamer** [comment]
> @Rexogamer were you planning on working on this or is this available for the community?

Right now it’s up for grabs, as I’m currently gonna focus on adding Codium support.

**Comment by agisilaos** [comment]
I'm going to assign that to myself since it's a pretty quick one (if that's alright) @tierninho!

**Comment by tierninho** [comment]
@agisilaos Go for it! Thanks

**Comment by doc-han** [comment]
@agisilaos I'm available for this quick fix :)

**Comment by Rexogamer** [comment]
With Codium done and dusted, I think I’ll do this.

**Comment by outofambit** [comment]
Hey @Rexogamer thanks for filing this issue but this isn't something we're interested in changing at this time. Since the proposed change centers on writing style, I think we'd need to have a discussion about why the new wording would be more aligned with the tone and voice of GitHub Desktop before we make any changes.

I know there's a `help wanted` label on this issue (and you commented before starting). I'm sorry for the mis-triaging of this issue and for us not catching and communicating it sooner.
