### ISSUE TITLE
LFS Git Push Blocks Other Traffic

### ISSUE THREAD

**Issue by widescape** [desktop/desktop#8015]
When I push commits with large files (Git LFS), the GitHub Desktop app on my MacOS 10.13.6 doesn't behave like a good citizen in respect to the available network bandwidth. 

Network requests by other apps during the push of GitHub Desktop get delayed.

Other apps like Dropbox have settings like limiting upload and download bandwidth:
![Bildschirmfoto 2019-07-24 um 18 31 48](https://user-images.githubusercontent.com/80869/61811253-65784980-ae41-11e9-9a7d-8fc765ac8b51.png)

**Comment by shiftkey** [comment]
@widescape thanks for the suggestion.

Because Git LFS is a command-line tool that we ship in GitHub Desktop, I recommend opening an issue with them over on https://github.com/git-lfs/git-lfs to enquire about this change. If that becomes something that's supported there (via config is the most likely option) we can then talk about making it clearer in Desktop. 

This functionality doesn't currently exist in Git LFS, and is something we're not able to address in Desktop alone.

**Comment by shiftkey** [comment]
For reference, this is the documentation about how Git LFS can be configured: https://github.com/git-lfs/git-lfs/blob/master/docs/man/git-lfs-config.5.ronn

**Comment by shiftkey** [comment]
@widescape I'm going to close this out to keep our backlog under control, as I see you linked to this over on https://github.com/git-lfs/git-lfs/issues/3731

**Comment by widescape** [comment]
Thanks for the insights and references, @shiftkey!

**Comment by widescape** [comment]
For everyone else facing this, here's a workaround by @bk2204:

> Try setting lfs.concurrenttransfers to a lower number (the default is 8)

    git config --add lfs.concurrenttransfers 4

I tried it and it solves the issue for me.

**Background:** "Git LFS has no concept of the bandwidth of the connection because Go has no concept of the bandwidth of the connection. […] try setting `lfs.concurrenttransfers` to a lower number […] doing so should reduce the number of transfers that occur at once, which will likely make your system and network prioritize other traffic as well" – @bk2204 https://github.com/git-lfs/git-lfs/issues/3731#issuecomment-515047386

**Comment by steveward** [comment]
Thanks for sharing that info @widescape!
