### ISSUE TITLE
Add syntax highlighting for Makefile

### ISSUE THREAD

**Issue by varkor** [desktop/desktop#8017]
See https://github.com/desktop/desktop/issues/7217 for another example of missing syntax highlighting for various languages.

**Comment by shiftkey** [comment]
@varkor thanks for the suggestion! Unfortunately it doesn't seem that Codemirror (which we rely on for all our syntax highlighting support) covers Makefiles.

I'm going to close this out because we can't directly address this in Desktop, and it needs a contribution to Codemirror to support it. I recommend starting with the upstream issue https://github.com/codemirror/CodeMirror/issues/5408 where this was discussed last year.
