### ISSUE TITLE
 github Desktop推送到远程是出现 bad credentials这个错误

### ISSUE THREAD

**Issue by liurongbo** [desktop/desktop#8029]
## Version

* GitHub Desktop:

* Operating system:

**Comment by shiftkey** [comment]
@liurongbo thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by steveward** [comment]
@liurongbo If you are encountering a credentials issue I would first recommend trying to log out and then log back in by going to the GitHub Desktop menu and selecting `File` > `Options` > `Accounts`.
