### ISSUE TITLE
Number of merge conflicts are incorrect in merge hint

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#8049]
We initially opened  #7445 as a proof-of-concept for using worktrees to detect conflicts as part of a rebase, and if we are happy with shipping this to address #6960 we should apply this same approach to our existing merge conflict detection.

This will address at least two known issues with our current `git merge-tree` approach:

 - #5664 - incorrectly reporting there will be conflicts
 - #5568 - incorrectly reporting the number of conflicted files

The worktree approach is favourable here because it lets us rely on Git's behaviour when merging and rebasing, rather than using an approximation. It should also let us perform the work while not affecting the user's working directory.

**Comment by Aimmejoe43** [comment]
Opt out

**Comment by Aimmejoe43** [comment]
Opt out

**Comment by adamreisnz** [comment]
I am running into this quite often, which is causing our decision making process to be influenced incorrectly.

For example, we avoided merging a particular branch because GHD said there would be 17 conflicts. We didn't want to deal with that at the time.

In the end, it turned out to be only 1 conflict after the merge was done.

How come there's such a large discrepancy between the reported number of conflicts and actual conflicts?

**Comment by adamreisnz** [comment]
This really flips me out 😆 

![image](https://user-images.githubusercontent.com/490562/73234037-4d68f480-41ed-11ea-91b1-9c919d87df56.png)

![image](https://user-images.githubusercontent.com/490562/73234046-58238980-41ed-11ea-9e91-eca4f1e66f86.png)

**Comment by CHallski** [comment]
I would add that this is still breaking in Desktop release 2.5.2: #9192 (mentioned above, but closed as a duplicate?) has detailed reproduction steps for creating a case where it is impossible to rebase a branch through GitHub Desktop because it claims that the branches are up-to-date with each other. Thankfully the CLI and GitGraph in Visual Studio both work fine, but that means shifting workflow to another interface.

I can understand why 9192 might have been flagged as a duplicate if the logic for detecting conflicts is incorrectly showing that there are no changes, but the manifestation is very different and arguably more critical since a grayed out Rebase button can't be bypassed in Desktop.

**Comment by ozonexo3** [comment]
2 years and this is still not fixed :| 
I get into this every few days when Im trying to rebase my branch and in such cases i just cant rebase branch using Github Desktop. 
If this is hard to fix then at least add option to force rebase anyway, can be another button or as option under the arrow.
![obraz](https://user-images.githubusercontent.com/9513043/144028498-b7129c34-1d94-4d95-9e0a-e9afd5278ecb.png)

**Comment by ryanleichty** [comment]
I can also confirm this is still an issue. The screenshot added by @ozonexo3 is exactly what I see.

**Comment by DavidTheExplorer** [comment]
4 years since this was posted and rebasing is still impossible on Github Desktop, this is hilarious.
I use it only when working on private repos, because the free version of GitKraken doesn't allow you to manage private repos.

**Comment by Martin-Vancado** [comment]
I still mainly use "Github Desktop", but from the beginning I use "Sublime Merge" next to it or use the terminal for the more complicated tasks.
