### ISSUE TITLE
Checking out upstream master results in error

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#8062]
While testing another issue I ended up forking a public repo and when open the branch list, I noticed two branches: `master` and `upstream/master`. 

Every time I click the upstream one I get the following error:

```
install.ts:23 `git -c credential.helper= -c protocol.version=2 checkout --progress upstream/master -b master --recurse-submodules --` exited with an unexpected code: 128.
stderr:
fatal: A branch named 'master' already exists.

(The error was parsed as 26: A branch with that name already exists.)
```

![Screen Shot 2019-08-01 at 2 46 30 PM](https://user-images.githubusercontent.com/14828183/62336252-2b273180-b46b-11e9-91c4-6903642969f0.png)

Not sure what the correct resolution is here, but this should be more user-friendly.

2.1.1-beta3, mac

**Comment by borpin** [comment]
Ha just raised something similar #8063 

The reason is that when you select a branch, Desktop creates a `local` branch of that name, tracking the branch you selected, say `origin/master`. You can see this by using `git branch -vv`. You will also note than on the branch list the entry `origin/master` probably does not exist as the `master` branch is tracking it.

If you then try and select `upstream/master` it again tries to create the local branch but can't as the name already exists.

**Comment by shiftkey** [comment]
This is an long-running problem due to multiple remotes sharing some common branches: #4527

I added some extra thoughts about how to change the workflow to support this case in that issue.

**Comment by tierninho** [comment]
Gonna close this issue out as https://github.com/desktop/desktop/issues/8063 address the problem more clearly and as #4527 already exists.
