### ISSUE TITLE
diff highlighting: c++ keywords

### ISSUE THREAD

**Issue by marc2k3** [desktop/desktop#8114]
## Version

* GitHub Desktop:
2.1.1

* Operating system:
Microsoft Windows [Version 6.3.9600] (8.1)

## Steps to Reproduce
At first glance, it seems C++ keywords are displayed using a reddish colour but this breaks down on some diffs.

### Expected Behavior
Highlighting should be consistent like this diff on the website...

https://github.com/marc2k3/foo_jscript_panel/commit/a400b4b5b86958843b240df004f133f7eff7a9d1#diff-d519b86210f51425125bc1a3e29deda7

### Actual Behavior
This is what the same file looks like in Desktop..

![Untitled](https://user-images.githubusercontent.com/34617027/63149015-d8b54b80-bffa-11e9-8716-f94f97d7c952.png)

Note the odd highlighting on old line 15 and new line 13.

**Comment by niik** [comment]
Hi @marc2k3, GitHub.com and Desktop uses two [different methods of syntax highlighting](https://github.com/desktop/desktop/blob/development/docs/technical/syntax-highlighting.md). In our case we use [CodeMirror](https://github.com/codemirror/codemirror) and more specifically for C++, the [clike](https://github.com/codemirror/CodeMirror/blob/master/mode/clike/clike.js) highlighting mode. For that reason we can unfortunately expect there to be some discrepancy between the two.

As for the highlighting bug here I believe that was fixed in https://github.com/codemirror/CodeMirror/commit/a2e4fdb734a574052fd45302627bde92e7632224#diff-ea2f2fc902d69677f96be9133af4cb4e so it should hopefully get resolved the next time we update CodeMirror.

**Comment by marc2k3** [comment]
Cool. Thanks for the speedy reply and I'll look forward to whenever the fix is released.

**Comment by marc2k3** [comment]
Thanks!
