### ISSUE TITLE
Can't switch branches.

### ISSUE THREAD

**Issue by money0609** [desktop/desktop#8120]
Can't switch branches.

**Comment by steveward** [comment]
Thanks for reaching out @money0609 !

Would you mind filling out the rest of the issue template so that we can better understand what is causing the problem you are experiencing? Without that information it will be difficult to help you further. It would especially be helpful if you could upload the log file from GitHub Desktop, which will give more details about the specific error you are seeing. 

To access the log files go to the  menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`. The log files are created daily -- please send over a log file as an attachment from a day where you experienced the issue

Thanks!

**Comment by tierninho** [comment]
@money0609  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
