### ISSUE TITLE
An option to disable automatic fast-forward

### ISSUE THREAD

**Issue by tomsgrinbergs** [desktop/desktop#8146]
Hi,

I've been struggling with this for a while now, and it seems I have finally found it's GitHub Desktop that's causing it.

Perhaps it's an issue with my workflow and I'm interested in hearing what others do to avoid this.

Whenever I pull down changes done by my co-workers I always check the affected file list to see if there are any maintenance tasks I must do:
 - if `package.json` or `composer.json` have been changed I should install the new dependencies
 - if our js or css source files have been changed I should re-run our build process
 - if database migration files have been changed I should run them to get my database up-to-date

With GitHub Desktop fast-forwarding my branches automatically I'm now missing these steps and have to stumble upon a fatal error to notice that, for example, a database is not up to date.

**Comment by billygriffin** [comment]
Hi @tomsgrinbergs, thanks for the issue. This has been a long-standing paradigm that GitHub Desktop uses, primarily for convenience so you're not always having to switch branches and pull new things from that branch prior to merging, or having to keep track of which things are updated and which aren't. Usually this adds convenience in the context of merging, but it's also just one fewer action as you're bouncing back and forth between branches.

With respect to workarounds to make what you're discussing simpler, I'd love to understand whether you're sharing branches with co-workers, or whether the updates from co-workers are typically brought in via the default branch.

Because this is something that's so core to the app and intended to reduce friction, and because we haven't come up regularly, I'm going to close this issue to communicate that we don't intend to provide an option to disable it. Sorry it causes frustration for you.
