### ISSUE TITLE
Code commit shows wrong user.

### ISSUE THREAD

**Issue by vittoria-ravi** [desktop/desktop#8208]
## Description

Incorrect Committed User from Mac Desktop App.

## Version

* GitHub Desktop: 2.1.3

* Operating system: macOS Mojave

## Steps to Reproduce

1. Logged in as user eg. user_X
2. Cloned repository to local
3. Downloaded Github Desktop App
4. Fetch Origin source
5. Verified user login in preference and it shows user_X
6. Modified Code 
7. Committed to Github 
8. Committed user is showing different user eg. user_Y

Please note user_X and user_Y is belong to same person. user_X is for official account where as user_Y is personal account. 

I don't see any where it is sign in as user_Y. 

### Expected Behavior

Code commit should be user_X because this user has all the access to the repository.
### Actual Behavior

Code was committed by wrong user_Y and this user does NOT have access to the repository.

**Comment by steveward** [comment]
👋 @vittoria-ravi 

It is likely that the email address in your local .gitconfig file is using an email address that has been registered to a different account on GitHub. You can read more about this issue here:

https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user

You can check the email address that GitHub Desktop is currently using by going to the file menu and selecting `GitHub Desktop` > `Preferences` > `Git`. Make sure that email address matches an email address under your GitHub account. You can view your current email addresses here:

https://github.com/settings/emails

In the future we would like to automatically detect if the email address you are committing with is associated with your currently logged-in GitHub account. That would prevent this type of issue from occurring as frequently. You can follow along in https://github.com/desktop/desktop/issues/610 for more information about that.
