### ISSUE TITLE
Modal / Popup too easy dismissive

### ISSUE THREAD

**Issue by alexandruspataru** [desktop/desktop#8276]
Hi there, 

First of all, thank you for creating an easy way to work with GitHub from a GUI. 

Now, the issue: I want to create a repository so I open up the modal / popup. I had to redo all the steps over and over again because whenever I clicked outside the popup, it closed... 

Seriously, this should not be dismissive unless we click the `close` / `cancel` button. 

![image](https://user-images.githubusercontent.com/15632210/64918893-07b30e80-d7ad-11e9-9619-1f3b74465895.png)

* GitHub Desktop: 2.1.3
* Operating system: Windows 10

Thank you,
Alex S.

**Comment by tanyadigman49** [comment]
Delete all my info I've been hacked.the user is stealing all my info and
coding my phone and accounts

**Comment by alexandruspataru** [comment]
@tanyadigman49 wait, what? I think you're off topic here.

**Comment by tanyadigman49** [comment]
What do you mean mentioned and to who

**Comment by plslaug** [comment]
I'm glad you're feeling up to it I will get back to you in a formal request
for the informative email with a link on the website you're imply on a
device that someone else I've entrusted whom gave information about my
Framework fraudulent charges are for sure merging

**Comment by tierninho** [comment]
@alexandruspataru Thank you for filing the issue. Some of our modals only close when the user clicks `X` and some when the user clicks on the background. Unfortunately, you experienced the latter which was not ideal given the amount of data you have to re-type. 

Going to keep this open so other team members can weigh in.

**Comment by MinganMuon** [comment]
I have the same gripe about popups too easily closing; my specific problem (running 2.1.3 under Windows 10) was that if I tried to select text from a text box using the mouse and dragged the mouse over to the area outside the popup before releasing the mouse button, the popup would close. Extremely frustrating; I was going to open an issue but then I found this issue.

**Comment by mislav** [comment]
@MinganMuon @alexandruspataru Thank you for sharing that. I agree that any modal dialog that has the potential to lose someone's work shouldn't be accidentally dismissible like that. For example, the New Repository dialog should be, in my opinion, only dismissible by clicking on “X” or “Cancel” buttons.

If our team doesn't get to this sooner, pull requests to address this are welcome! 🌟

**Comment by MinganMuon** [comment]
After a quick foray into the codebase, it seems to me that this is a relatively easy fix because the `disableClickDismissalAlways` option of `dialog` just needs to be set to `true` on every dialog that shouldn't be easily dismissed. I'll set up a dev environment later today (or tomorrow) and test my intuition. Should all dialogs that take user input be not easily dismissable, or should only those that require custom input (i.e. not copy-pasting a GitHub repo URL) be not easily dismissable?

**Comment by billygriffin** [comment]
Hi folks, we shipped a fix for the problem causing most of this frustration in #8547 because it would previously close the dialog on a mouse up event, and that was particularly unexpected when people were dragging their cursor as @MinganMuon described above. The question of whether to dismiss dialogs by clicking outside them is a more general design decision, and unfortunately different people have different preferences on that question. 

@MinganMuon's PR #8349 attempts to thread the needle by only disabling this behavior for dialogs that contain text inputs, but we're concerned that while this might be a reasonable choice now, it's almost certain that whomever implements the next dialog with a text input won't have the context to know that's what we do and therefore this rule is likely to be applied inconsistently over time.

Since #8547 fixed the problem of the dragging and letting go of your mouse dismissing the dialog and since we have not heard this come up at all from others since that shipped, I'm going to close this issue as we'll keep the intentional design choice in place. @niik is also following up with a PR that removes `disableClickDismissalAlways={true}` on other dialogs where it probably shouldn't be there so we can remain consistent across all of them, and users have a consistent expectation for what will happen when they take particular actions.

Thanks for the issue and the discussion that helped us arrive here!
