### ISSUE TITLE
The repositary folders are empy

### ISSUE THREAD

**Issue by JanGray** [desktop/desktop#8287]
## Version

* GitHub Desktop:

* Operating system:

**Comment by JanGray** [comment]
![FOX](https://user-images.githubusercontent.com/43710436/65083749-fca7dc00-d96e-11e9-83e6-bfbfb9ac5f44.JPG)

**Comment by tierninho** [comment]
@JanGray thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by steveward** [comment]
@JanGray if you're just getting started with GitHub Desktop we [have a guide](https://help.github.com/en/desktop/getting-started-with-github-desktop/creating-your-first-repository-using-github-desktop) that may be helpful. If you have any specific questions let us know!

**Comment by tierninho** [comment]
@JanGray As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
