### ISSUE TITLE
Git push buffer too low, push stops

### ISSUE THREAD

**Issue by jgwill** [desktop/desktop#8293]
## Description

Pushing hang and stop

## Version
Latest

* GitHub Desktop:

* Operating system:

Windows 10

## Steps to Reproduce
1. Commit a huge enough file
2. Push it

### Expected Behavior
Successful push

### Actual Behavior

Push starts and stop at a certain percentage

**Comment by steveward** [comment]
@jgwill thanks for the report. Could you upload the log file from GitHub Desktop so that I could get some more information about this error?

To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`. The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

If you are working with large files I would also recommend taking a look at [Git LFS](https://help.github.com/en/articles/configuring-git-large-file-storage), which is designed to support versioning of large files. GitHub Desktop provides support for Git LFS without needing to install anything -- you just need to track the files.

**Comment by tierninho** [comment]
@jgwill  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.

**Comment by IsisVgoddess** [comment]
I will need to get to the laptop cause I am currently working on K-12 project.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by IsisV33** [comment]
Uhmm, why am I blocked? I will be back on tonight to get everything straightend out...---...

**Comment by lee-dohm** [comment]
@IsisVgoddess @IsisV33 if you have questions about why you were temporarily blocked, you can reach us at the address in the [Desktop Code of Conduct](https://github.com/desktop/desktop/blob/development/CODE_OF_CONDUCT.md), opensource@github.com to discuss it.

**Comment by jgwill** [comment]
> @jgwill thanks for the report. Could you upload the log file from GitHub Desktop so that I could get some more information about this error?
> 
> To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`. The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
> 
> If you are working with large files I would also recommend taking a look at [Git LFS](https://help.github.com/en/articles/configuring-git-large-file-storage), which is designed to support versioning of large files. GitHub Desktop provides support for Git LFS without needing to install anything -- you just need to track the files.

Sorry for the late reply (too much momentum on email getting in my mailbox :) )
Where can I find the Desktop log ?

regards

**Comment by steveward** [comment]
@jgwill To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`. The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by ArkadiyT3** [comment]
Hi . Same issue . Did you solve it?
