### ISSUE TITLE
[Onboarding tutorial] Quicker update of "Open a pull request" 

### ISSUE THREAD

**Issue by kuychaco** [desktop/desktop#8317]
As of now (30ebea1650) it takes a minute or two for this step to update which leaves the user feeling confused or dissatisfied because they don't get the positive feedback that they've done the right thing and completed the tutorial (based on actual usability testing by @billygriffin)

Ideally, the user creates the PR on dotcom, switches back to Desktop and immediately sees that the step has a nice green check mark and that they have successfully completed the tutorial 🎉

**Comment by billygriffin** [comment]
Also for this, in multiple usability tests, the person has actually merged the PR and deleted the branch on dotcom (in one case without coming back to Desktop). If they do that flow and then come back to Desktop, it'll never get checked off, right?

**Comment by billygriffin** [comment]
In discussions with @ampinsk, @kuychaco, and @nerdneha today we talked about this a bit more. If it's not possible for the update to propagate immediately when someone returns to the app so they see the green checkmark after they've created a PR, we want to propose a different path.

The (6) should instead turn into a green checkmark as soon as the person clicks the "Open pull request" button or uses the keyboard shortcut to open a PR. That way, the step is marked as complete right away and we don't have to worry about the detection in Desktop.

The downside of this is that we won't be checking it based on whether they *actually* created the PR, but rather just that they went to the PR page. The upside is that if they do go ahead and merge the PR right away all in one flow, the box will still be checked as complete instead of Desktop potentially losing knowledge of the PR's existence.

**Comment by outofambit** [comment]
took a look at this earlier today, before i learned that @niik was going to look at it soon. it looks straightforward to hook up the pull request update event to re-assessing the current tutorial step but i think this is still a more reliable approach:

> The (6) should instead turn into a green checkmark as soon as the person clicks the "Open pull request" button or uses the keyboard shortcut to open a PR. That way, the step is marked as complete right away and we don't have to worry about the detection in Desktop.

@kuychaco and I talked about some alternative ways to check for a PR that don't rely on the exisiting PR database and update mechanisms. It would help to have more information about the rate limiting concerns from @niik so we can assess if those are worth looking into later, but that can wait until after this ships.

**Comment by niik** [comment]
> @niik so we can assess if those are worth looking into later, but that can wait until after this ships.

I can certainly talk about this in more depth, perhaps a zoom session would be most productive for that though. Me and @billygriffin synced up on this yesterday and came to the same conclusion as you that faking this is the right way to go for now.
