### ISSUE TITLE
[onboarding] show a generic error popup for errors that occur during tutorial repo creation

### ISSUE THREAD

**Issue by outofambit** [desktop/desktop#8351]
the main idea here is to make sure we don't mislead people with an specific, but inaccurate error message.

i'm think a standard "something went wrong" popup with the message from whatever `Error` was thrown.

**Comment by niik** [comment]
The description is a bit sparse here but I'm assuming this issue stemmed from the realization that any error thrown by the API when actually creating the tutorial repository on GitHub.com/GHE triggered a dialog that said that "the likely cause" was that the repository already existed on the server.

This caused some confusion when other API errors such as invalid credentials occurred which is understandable.

I think, slightly contrary to what's being proposed here though, i.e to make all errors generic, that we should show an *even more specific* error when we **know** that it failed due to the repository already existing. And then show a more generic error for all other errors. I'll take a stab at that

**Comment by outofambit** [comment]
> that we should show an even more specific error when we know that it failed due to the repository already existing. And then show a more generic error for all other errors.

@niik yes that’s what i was thinking too! that sounds great. apologies for the sparse description.
