### ISSUE TITLE
Desktop still upgrade when local version is greater than remote version

### ISSUE THREAD

**Issue by TerryChan** [desktop/desktop#8356]
I built a local version with version no 2.6.0, and the server version is 2.1.3. When I run the local build version of desktop, it still download the version in remote, event local version is greater than remote version.
![image](https://user-images.githubusercontent.com/5396286/65755501-cd9b2280-e145-11e9-8d16-93059f175851.png)
The app folder:
![image](https://user-images.githubusercontent.com/5396286/65755521-dc81d500-e145-11e9-8f99-79cea604158c.png)
The SquirrelSetup.log:
![image](https://user-images.githubusercontent.com/5396286/65755695-3387aa00-e146-11e9-9116-0f7972f67f82.png)

But when I restart Desktop, it's still use the local built version, didn't upgrade really, and show the restart to upgrade banner again.

**Comment by mislav** [comment]
Thank you for this information; it is very useful! I'm guessing that we haven't anticipated the case where the current version that the app could be newer than the latest version available on our servers.

**Comment by mislav** [comment]
After consulting with my colleagues, we've reached a decision that this is intended behavior of Squirrel update system: it was designed to support downgrades. 

Since you seem to be maintaining a fork on your own release cadence (I'm guessing this is why you maintain a newer version number), I would suggest that you either disable the auto-update system by returning early here https://github.com/desktop/desktop/blob/19640b429f13102ea2a9cf7396b34992155dbadf/app/src/ui/app.tsx#L498 or change the URL to your own servers https://github.com/desktop/desktop/blob/19640b429f13102ea2a9cf7396b34992155dbadf/script/dist-info.ts#L121-L123.
