### ISSUE TITLE
Desktop Install Location on Enterprise 

### ISSUE THREAD

**Issue by hecon5** [desktop/desktop#8397]
When installing on an enterprise environment, the program appears to install to the syswow location in \Windows.

This seems to be due to the fact it's trying to actually install to a user's AppData folder, which is not permitted. Found a potentially similar issue: https://github.com/desktop/desktop/issues/3757, and another: https://github.com/desktop/desktop/issues/1086

Please provide a way to install this program without requiring a user to install to their app directory without needing an external packaging tool: this will never be permitted on my environment.

**Comment by tierninho** [comment]
@hecon5 Thanks for filing this. Good question!

@niik or @joshaber any recommendations here?

**Comment by steveward** [comment]
@hecon5 thanks for opening this. This is also similar to #2202, where @niik gave a writeup describing the limitations that GitHub Desktop's Squirrel installer has. 

One user worked around the installation location issue by creating a [portable build of GitHub Desktop](https://github.com/daemondevin/GitHubDesktopPortable) (please note this is not officially supported by GitHub). I have tested the portable version out to verify it works and auto-updates correctly.

Since this is being tracked in #1086 I am going to close this issue out.
