### ISSUE TITLE
working with $username-patch-$i branches

### ISSUE THREAD

**Issue by staabm** [desktop/desktop#8417]
working with branches like staabm-patch-3 (assume its one created on github.com with my username) I am facing the following problem from time 2 time:

STR
- you work on github.com on e.g. a branch staabm-patch-3
- you make this branch available on your local workstation by cloning and checking it out etc.
- you work on the branch
- you merge the branch via a github.com PR and delete it in the master repo. your local github desktop is not involved and the branch is still present
- ... some time goes by ...
- you create a new branch on github.com.. which again will automatically be namend staabm-patch-3 
- you create a pull request for this new branch
- you checkout the new pull request with github desktop locally
-> github desktop tries to merge the still existing staabm-patch-3 branch with the newly created one
=> you get a crazy mix of changes in your local branch as the changes merged together are semantically not related

using Version 2.2.0 on windows10x64

**Comment by mislav** [comment]
Thank you for detailing your problem, and sorry that this is making friction for you!

Let me see if I understand:
- you work on a branch e.g. "patch-1" in Desktop, which tracks "patch-1" on a git remote;
- on the remote, "patch-1" gets deleted with no involvement from Desktop;
- later, a new branch with the same name "patch-1" gets created with no involvement from Desktop;
- upon returning to Desktop, the app still tries to track "patch-1" and pull changes from it as if it were the old branch, but it's not aware that it's an entirely "new" branch.

If so, this is a very tricky problem. By just looking at git data that it fetched from a remote, Desktop cannot know that the old "patch-1" and the new "patch-1" branches are not semantically related, and that the branch got deleted in the meantime. To it, it simply looks like the branch got updated on the remote.

What behavior would you expect Desktop to have in this case?

**Comment by staabm** [comment]
thx for the feedback.

> If so, this is a very tricky problem. By just looking at git data that it fetched from a remote, Desktop cannot know that the old "patch-1" and the new "patch-1" branches are not semantically related, and that the branch got deleted in the meantime. To it, it simply looks like the branch got updated on the remote.

thats right.
 
> What behavior would you expect Desktop to have in this case?

I would expect that gitub desktop either ..
a) realize when the remote branch was merged and therefore would archive/delete the local branch when fetching. then a new pull request fetched weeks/days after the first one with the same branch name cannot clash.
b) github.com should not "recycle" branch names in such a short period of time

**Comment by kuychaco** [comment]
@staabm thanks for helping us better understand the issue you are facing and for elaborating on your expectations.

For (a) GitHub Desktop does periodic branch pruning roughly every 4 hours and should be deleting branches that are deleted on remotes. Ideally this prevents such branch name collisions from happening a majority of the time. That said, I can certainly see cases where it would not (ex: Desktop is not open so branch pruning does not occur, or a new branch is created within four hours of a branch with the same name being deleted). 

Could you please help us understand the frequency and severity of this issue so that we can assess the impact it has on your workflow? 

It might also be helpful for you to send over your log files. The **Help | Show Logs in Explorer** menu items should open the logs folder, and inside those are the log files generated by day. This will provide some more information to help us troubleshoot.

**Comment by staabm** [comment]
> Could you please help us understand the frequency and severity of this issue so that we can assess the impact it has on your workflow?

I experienced the issue 1-2 times a week. Since we use a mergebot on github.com which merges PRs and deletes branches it seems to happen from time to time. Its not super important.

> For (a) GitHub Desktop does periodic branch pruning and should be deleting branches that are deleted on remotes

When will the pruning gets executed?

**Comment by tierninho** [comment]
> When will the pruning gets executed?

Please see this [pull request](https://github.com/desktop/desktop/pull/6544) for the logic behind pruning. Thanks.

**Comment by tierninho** [comment]
Closing this issue up for now. If further assistance is required, please reach out!
