### ISSUE TITLE
Renamed file status lost after commiting other files

### ISSUE THREAD

**Issue by Seb33300** [desktop/desktop#8420]
### Describe the bug

When you rename a file, it renders with a blue arrow icon into q single line:
```
old/file/name => new/file/name       (=>)
```

If you commit some other files (but you want to keep the renamed files and not commit it), it will create a commit, but the renamed file will be splited into 2 lines:
- a removed file (red minus icon)
- an added file (green plus icon)
```
old/file/name       (-)
new/file/name       (+)
```

### Version & OS

I am using GitHub Desktop for Windows.

### Steps to reproduce the behavior

1. Rename a file
2. Edit another file
3. See 2 changes pending: `1 renamed file, 1 edited file`
4. Commit the edited file only
5. See 2 changes pending: `1 removed file, 1 added file`

### Expected behavior

Step 5 should display `1 renamed file`.

**Comment by AndreiMaga** [comment]
Correct me if I'm wrong, but as far as I know this happens because of how git works. 
As soon as you move/rename a file by the book with ```git mv``` it stages it as a rename. 
But when you commit something else you have to unstage it using ```git restore --staged <file>```. 
If you do this in git, the same behavior happens, you have a deletion and a untracked file. 
But as soon as you stage them back by using ```git add <file>``` you got the "rename" back. 
[And as far as I know Github Desktop only stages right before the commit only with the selected files](https://github.com/desktop/desktop/blob/14ca60704897d85b4c015de7fd72ebe85ffe2fc6/app/src/lib/git/commit.ts#L14). That's why you see it as a removed and added file, they are not staged. It's not a "visual bug", it has a lot more stuff behind the scenes and I don't think there is an easy way around it.

**Comment by kuychaco** [comment]
Ah yes, @AndreiMaga hit the nail on the head. Here's what's happening...

- `git mv old-name new-name`
- `git status` shows `renamed:    old-name -> new-name`
- edit another file 
- `git status` shows `renamed:    old-name -> new-name` and `modified:   file.txt`
- in Desktop ensure that only `file.txt` is selected and commit
- under the hood, desktop unstages everything (via `git reset -- .`) and then stages and commits `file.txt` changes. 
- `git status` shows `deleted:    old-name` and `untracked files:   new-name` -- because the latter is a newly created file that has not been staged, it is untracked and therefore Git does not take it into consideration when evaluating renames. As far as I can tell, there's no way to instruct Git to consider untracked files when checking for renames...

A potential solution would be to have Desktop ensure that all files are staged (as much as possible) so that Git will recognize the rename. But this feels heavy-handed and I wouldn't necessarily recommend it. There's always the chance that folks are updating with their stage/index outside of Desktop and wouldn't want the app mucking with it. Curious to get thoughts from @billygriffin.

**Comment by kuychaco** [comment]
Just checked to see if there was any way of instructing Git to consider untracked files when calculating renames and the answer is unfortunately “no”. Given that there is no clear way of avoiding this visual discrepancy, and that the user impact is minimal (albeit confusing for sure), we are opting to close this issue in favor of focusing on higher impact work. We have limited resources to invest in the project, and we want to ensure our efforts are going toward solving the highest priority problems. Thanks for pointing this out @Seb33300!

**Comment by Seb33300** [comment]
I think the information about the renamed file stays stored somewhere, because event if the renamed file is split after a commit, if after that you commit the deleted and created file, it will appears back as a renamed file
