### ISSUE TITLE
repository

### ISSUE THREAD

**Issue by mifsudl64** [desktop/desktop#8435]
resolve bug report

**Comment by steveward** [comment]
Thanks for reaching out @mifsudl64 !

Would you mind filling out the rest of the issue template so that we can better understand what is causing the problem you are experiencing? Without that information it will be difficult to help you further. It would especially be helpful if you could upload the log file from GitHub Desktop, which will give more details about any specific errors you are encountering.

To access the log files go to the  menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`. 

The log files are created daily -- please send over a log file as an attachment from a day where you experienced the issue

Thanks!
