### ISSUE TITLE
[Feature request] : Allow to always use SSH for remote urls (including upstream)

### ISSUE THREAD

**Issue by LouisCAD** [desktop/desktop#8443]
### Describe the feature or problem you’d like to solve

Allow to always use SSH for remote urls (including upstream).

Right now, it uses https urls by default, which is annoying since it requests credentials from the terminal on each usage (and also breaks automation for things like publishing scripts). I have to set the url back to an ssh one every time I clone a new repo from GitHub Desktop, resulting in systemic loss of time.

### Proposed solution

In the cloning popup, allow to switch to SSH url, and remember the choice, until we change back to https. Pretty much like on the web version when you want to look at the git url and can use either of the 2 options.

**Comment by steveward** [comment]
Thanks for the feedback @LouisCAD. I'm going to lump this into #2579, where we are tracking better SSH support in GitHub Desktop.

The best workaround I can recommend would be to use this handy config option to force Git to use SSH instead of HTTPS:

`git config --global url."git@github.com:".insteadOf "https://github.com/"`

I hope that is helpful!
