### ISSUE TITLE
Show percent of code fetched for the Fetch button

### ISSUE THREAD

**Issue by Arshiamidos** [desktop/desktop#8451]
### Describe the feature or problem you’d like to solve
show code percent next to fetch tab
### Proposed solution
divide extra area to show percents.. up to 10

**Comment by Rexogamer** [comment]
what do you mean by code percent?

**Comment by tierninho** [comment]
I believe @Arshiamidos is requesting a status indicator for the Fetch button, like "5% fetched"... "10% fetched", etc...

This is an interesting idea and we will consider it for the next iteration of this area. Thank you.

![Screen Shot 2019-10-14 at 8 37 48 AM](https://user-images.githubusercontent.com/14828183/66774698-f0c01480-ee5d-11e9-8e69-0f3d8c35a0c9.png)

**Comment by Rexogamer** [comment]
Ahhh. I like the idea.

**Comment by Arshiamidos** [comment]
@tierninho thanks for defending my idea 😅.   
but my request is something like below.  
![Screen Shot 1398-07-22 at 22 31 37 copy](https://user-images.githubusercontent.com/6451804/66776259-e2601000-eed2-11e9-9720-673501b4293a.png)

**Comment by Rexogamer** [comment]
Ohhhh, the language make-up of the code as found on the website. If you don’t mind, I’ll make a separate issue for the presumed idea as I like it.

**Comment by billygriffin** [comment]
Hi @Arshiamidos, since this is information about the repo and not specific to something with the local workflow, we prefer to defer to GitHub.com for those types of repository insights. So I'm going to close this issue. If there's a particular case that I'm missing as to why this should be so prominent to be in the app as part of the core workflow of a large percentage of developers, we're happy to reconsider.
