### ISSUE TITLE
Allow user to pick branch to PR into

### ISSUE THREAD

**Issue by WillGoldstein** [desktop/desktop#8455]
### Describe the feature or problem you’d like to solve

In the old GUI, you could pick which branch you were PR'ing into. Now, you just PR into master and have to change the branch later. Why the step backwards?

### Proposed solution

Make it so in the UI you can pick your branch to PR into, which then ensures correct setup on the website.

**Comment by tierninho** [comment]
@WillGoldstein As the new Desktop was written from scratch, not every feature was implemented from the inception. 

Thank you for the suggestion, and we will consider it for the next iteration in this area.

**Comment by billygriffin** [comment]
Hi @WillGoldstein, thanks for the issue. I've gone through the flow for creating a PR, and because GitHub Desktop no longer allows you to fully create a PR in the app, you'll have to choose the target branch at some point regardless. So whether you're doing that *in* Desktop or on the page on GitHub.com, it's still an explicit change you have to make. As such, I think it would add more friction in the app for people who are using the default branch as the target PR branch, and I don't want to add an unnecessary step for them. Thanks again for the idea.

**Comment by WillGoldstein** [comment]
@tierninho - been there get that, thanks for the explanation.

@billygriffin - got it, thanks for the explanation.
