### ISSUE TITLE
I can't fetch origin even if signed in

### ISSUE THREAD

**Issue by roberto-ebizmarts** [desktop/desktop#8475]
### Describe the bug
I can't **Fetch origin** even if:
1. I am signed up.
2. I have signed out and signed in. (Token refreshed)
3. Even I can move among branches
See Screenshot
### Version & OS
At least, at:
**GitHub Desktop version: 2.1.0** on **MacOS Mojave version 10.14.5**
and
**GitHub Desktop version: 2.2.1** on **MacOS Mojave version 10.14.5**

### Steps to reproduce the behavior
1. Click on 'Fetch Origin'

### Expected behavior
Fetch origin is done.

### Actual behavior
See Screenshots section

### Screenshots
![github desktop](https://user-images.githubusercontent.com/51710909/66926795-0459af80-f005-11e9-9f9c-25e815c684e2.png)

### Logs
(The error was parsed as 2: Authentication failed. Some common reasons include:

- You are not logged in to your account: see GitHub Desktop > Preferences.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.)
2019-10-16T14:21:55.042Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.885s)
2019-10-16T14:21:55.043Z - error: [ui] `git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

(The error was parsed as 2: Authentication failed. Some common reasons include:

- You are not logged in to your account: see GitHub Desktop > Preferences.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.)

**Comment by steveward** [comment]
@roberto-ebizmarts it looks like you are using SSH with this repository. Can you verify that you have a key loaded and `ssh-agent` is running? You'll need to open up the command line to check that. See [this help article](https://help.github.com/en/articles/error-permission-denied-publickey#make-sure-you-have-a-key-that-is-being-used). If that doesn't working, then you may need to verify that the correct [SSH version](https://github.com/desktop/desktop/issues/5641#issuecomment-421801704) is being used on your machine.

You can also switch the repository to use HTTPS instead of SSH by going to the menu and selecting `Repository` > `Repository Settings` > `Remote`. That should get things working as well.

**Comment by tierninho** [comment]
@roberto-ebizmarts  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
