### ISSUE TITLE
Provide git commands that underlie each GitHub Desktop 

### ISSUE THREAD

**Issue by paulponcet** [desktop/desktop#8516]
It would be useful to see the underlying git commands that are applied whenever one executes actions within GitHub Desktop. 

This would help GitHub Desktop users being accompanied toward Git, for those who wish to go for a more programmatic way of managing their code.

**Comment by Rexogamer** [comment]
Could be tied into the onboarding tutorial.

**Comment by steveward** [comment]
Thanks for the feedback @paulponcet. This is an interesting idea, but but not something that we will likely tackle in the near-term. I'm going to label this issue as an enhancement and close it out -- if we get further feedback that this would be a valuable addition to GitHub Desktop it may be something we consider in the future.

If you are interested in viewing the specific actions that GitHub Desktop is performing you can open up the Developer Tools by going to the menu and selecting `View` > `Toggle Developer Tools` and selecting the `Console` tab. You will see the the specific Git commands that are being run, along with other output. For the most verbose output you can click the `All levels` dropdown and select `Verbose`. The log files also provide a historical view of this data, and you can access those by going to `Help` > `Show Logs...`. Hope that helps! If you have any specific questions about the commands that are being run let me know.

**Comment by Rexogamer** [comment]
pardon me, but I thought standard practice was to add the future-proposal label, or to just leave the issue

**Comment by billygriffin** [comment]
Hi @paulponcet and @Rexogamer. This isn't something that we intend to do because the actual commands under the hood that Desktop runs are quite involved and use a bunch of oddities to achieve the behaviors we're enabling. This also came up in https://github.com/desktop/desktop/issues/1570#issuecomment-304685549, and we still have no intention of doing this because it would add more confusion than benefit. Thank you for the idea though!

**Comment by olleharstedt** [comment]
Well that sucks for traceability.
