### ISSUE TITLE
"Open in Sublime Text" broken from list of changed files

### ISSUE THREAD

**Issue by BasThomas** [desktop/desktop#8537]
### Describe the bug

Using "Open in Sublime Text" opens a write-protected version of the file, rather than the actual file that can be found in Finder.

### Version & OS

GitHub Desktop Version 2.2.2
macOS Catalina 10.15 (19A602)

### Steps to reproduce the behavior

1. Go to a repository
2. Make sure there's a changed file
3. Right click > 'Open in Sublime Text'
4. **Observe that it opens an empty file**
5. Make a change in that file
6. Try to save it
7. **Observe "Overwrite write-protected file `path-to-file`?" dialog**

### Expected behavior

At 3., it should open the exact file shown when using "Reveal in Finder"

### Actual behavior

It opens another, write-protected version of the file.

### Screenshots

Add screenshots to help explain your problem, if applicable.
<img width="532" alt="image" src="https://user-images.githubusercontent.com/4190298/67642295-a1242300-f90a-11e9-92c1-979ca0cc8c80.png">
<img width="532" alt="image" src="https://user-images.githubusercontent.com/4190298/67642341-109a1280-f90b-11e9-9186-94a5087727a0.png">

**Comment by niik** [comment]
Hi @BasThomas, sorry to hear you're having problems.

I'm not aware of any change made to our Sublime Text integration recently that would explain this so we're gonna need a little bit more information in order to troubleshoot effectively. Has this been working for you before and if so did it stop working as a result of a GitHub Desktop update?

Is it just one repository that's affected or all of them? Could you try changing to another editor to see if that still works?

**Comment by BasThomas** [comment]
Hi @niik!

I was already afraid of that / confused by it. I think both GitHub Desktop has had a bunch of updates, and the same for Sublime. It's been broken for... a few weeks I think?

All repositories are affected. I'm going to try another editor and get back to you 👍

**Comment by BasThomas** [comment]
How do I test this with another editor? I downloaded Atom but it doesn't seem to show up as an option to open files from.

**Comment by BasThomas** [comment]
I (indeed) can't seem to reproduce this with Atom.

Can you help point out the difference in opening it via "Changes" vs "History" in GitHub Desktop? Then I can file this bug to Sublime :)

**Comment by niik** [comment]
> Can you help point out the difference in opening it via "Changes" vs "History" in GitHub Desktop? Then I can file this bug to Sublime :)

Sure thing, the menu item that invokes the open in editor action from the changes tab is located here

https://github.com/desktop/desktop/blob/2ea8c4f7dd4989c20d8cd0edf8edfaed55ec79c3/app/src/ui/changes/changes-list.tsx#L386

And that ends up calling

https://github.com/desktop/desktop/blob/2ea8c4f7dd4989c20d8cd0edf8edfaed55ec79c3/app/src/ui/dispatcher/dispatcher.ts#L1191-L1196

From what I can tell that's the exact same method that ends up getting invoked from history

https://github.com/desktop/desktop/blob/2ea8c4f7dd4989c20d8cd0edf8edfaed55ec79c3/app/src/ui/history/selected-commit.tsx#L276-L278

Are you saying that you get a different behavior when choosing to open a file from the history tab rather than the changes tab?

**Comment by BasThomas** [comment]
Hah... so it seems like it works for existing documents, but not for new ones (the file in Changes is new, while the one in History isn't). Weird stuff, but good to know. I'll see if I can report this to Sublime somewhere.
