### ISSUE TITLE
Github Desktop App won't allow login anymore

### ISSUE THREAD

**Issue by CyberChristy919** [desktop/desktop#8538]
### Describe the bug

After update, I can no longer log in

### Version & OS

Version 2.2.2 running on Windows 10

### Steps to reproduce the behavior

1. Can see my repositories
2. Clone a repository from the internet
3. Login
4. Failed

### Expected behavior

be able to login and clone the repository

### Actual behavior

Nothing happened.

### Screenshots
![image](https://user-images.githubusercontent.com/37598796/67645210-a169f180-f8fd-11e9-8b7e-1f9b6b75e85c.png)

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by niik** [comment]
Hi @CyberChristy919,

Judging from the screenshot you provided I believe you've entered a URL pointing to a specific folder inside of the repository rather than a URL to the repository itself and that's likely what's causing problems for you.

If you visit the repository page on GitHub.com there should be a button labelled `Clone or download` which you can click to either open the repository in Desktop directly or copy the repository URL and paste it into the clone dialog in Desktop.

![image](https://user-images.githubusercontent.com/634063/67688729-944f1000-f99a-11e9-82c5-f587d86342c4.png)

I believe you've entered

`https://github.com/linuxacademy/content-aws-csa2019/tree/master/lab_files` into the clone dialog

![image](https://user-images.githubusercontent.com/634063/67689027-0889b380-f99b-11e9-8398-0c36d03a4312.png)

Try using `https://github.com/linuxacademy/content-aws-csa2019` instead, that's the URL to the repository and it should let you clone.

![image](https://user-images.githubusercontent.com/634063/67689064-14757580-f99b-11e9-8830-a99006520175.png)

Let me know if that doesn't work for you and we'll do some more troubleshooting!

**Comment by yesenvidnath** [comment]
Hi i tried to log in to a git hub desktop in ubuntu 20.04 but it is not login to git hub

**Comment by omaisali** [comment]
i have same issue on pop os, github desktop signin not working

**Comment by bugs181** [comment]
Can confirm the app version in Pop! Shop does not work. Can not confirm what version this is since the `Help -> About Github Desktop` menu is greyed out. Instead used a `.deb` from the releases page of [shiftkey/desktop](https://github.com/shiftkey/desktop) fork (installed with Eddy) and that works.
