### ISSUE TITLE
Mac OS Crash

### ISSUE THREAD

**Issue by fasil-advance** [desktop/desktop#8539]
### Describe the bug

```
Error: spawn /Applications/GitHub Desktop.app/Contents/Resources/app/git/bin/git EAGAIN
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:19)
    at onErrorNT (internal/child_process.js:429:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
```

### Version & OS

Version: 2.2.2
OS: Mac OS 10.15.0

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by niik** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by tierninho** [comment]
@fasil-advance This looks like #5416 and may have to do with resource limits. Would you mind restarting your machine and seeing if that fixes it?

**Comment by fasil-advance** [comment]
@niik and @tierninho Restarting the machine fixed it. Thanks both.
