### ISSUE TITLE
Publishing branch results in Authentication error 

### ISSUE THREAD

**Issue by alphadev11** [desktop/desktop#8552]
### Describe the bug

Public branch gives error. Authentication failed. 

### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

![1](https://user-images.githubusercontent.com/56959474/67845952-d0f54580-fb19-11e9-9f46-8aa0aaa10855.PNG)

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by niik** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by tierninho** [comment]
Please reach out again if you need further assistance. Thank you.
