### ISSUE TITLE
Keep repository list open to the side

### ISSUE THREAD

**Issue by GriffinSauce** [desktop/desktop#8560]
### Describe the feature or problem you’d like to solve

I constantly work in multiple repo's for different services that interact, switching very often. The dropdown feels like one click too many. On top of that, the list changes a lot for different reasons, keeping it visible would help me understand why and where my repos are moving and what their status is.

### Proposed solution

An option to keep the repo list open to the left. 

This halves the amount of repo-switching clicks and makes it visible what's happening to the list.

**Comment by niik** [comment]
Hi @GriffinSauce, thanks for reaching out! I believe this issue is similar to, and can be rolled up into, #1593 which we decided to track as part of https://github.com/desktop/desktop/issues/6460.

At the moment we don't have any plans for allowing the repository sidebar to stay open all the time but we appreciate your feedback as it helps us inform future direction. #1593 contains some more reasoning around this as well as some tips on the keyboard shortcuts that we already support for quickly switching repositories.

**Comment by GriffinSauce** [comment]
Hi @niik, I decided to create a new one because those issues are much larger in scope. Especially #1593 is super side tracked from this single problem. I understand it might be part of a bigger theme, but the whole theme doesn't necessarily have to be solved as one massive issue. I don't feel like tracking those issues will do anything for me here.

Thanks for the quick response though. Am still very happy with GHD and looking forward to future developments.
