### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by choonghee1** [desktop/desktop#8568]
![asd](https://user-images.githubusercontent.com/57249389/68069302-b3d2a800-fda1-11e9-9772-8a3b4db41ab5.PNG)
![asdf](https://user-images.githubusercontent.com/57249389/68069303-b3d2a800-fda1-11e9-8fb8-486015bb4e01.PNG)

how can I solve these problems?

**Comment by niik** [comment]
Hi @choonghee1, thanks for opening this.

It looks like the repository you're trying to clone contains at least two files with names that are not valid on a Windows file system.

```
config/S_Iron/<111>
config/Silicon/<311>
```

These two files contain `<` and `>` characters, both of which are forbidden on Windows file systems (see https://stackoverflow.com/a/31976060/2114). In order to be able to clone the repository you're going to have to reach out to the authors of the projects and check to see if they'd be willing to rename those two files (and any other following the same pattern).

I hope you're able to resolve your problem, I'm going to close this issue as this is an underlying limitation in the platform you're on.
