### ISSUE TITLE
i cant publish new branch from my desktop to my origin at github.com

### ISSUE THREAD

**Issue by PeterBarrettq** [desktop/desktop#8577]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by niik** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by PeterBarrettq** [comment]
I get authentication failure when I try and publish my projects to github.com.

This is message I get.
![image](https://user-images.githubusercontent.com/33948770/68261322-d90e3180-0093-11ea-9372-27811394de96.png)

**Comment by outofambit** [comment]
@PeterBarrettq Thanks for the additional info! Is the remote on GitHub? If so, can you confirm that you are signed in to GitHub Desktop?

Does pushing from the command line work?

**Comment by tierninho** [comment]
@PeterBarrettq  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
