### ISSUE TITLE
unable to push

### ISSUE THREAD

**Issue by ehinson69** [desktop/desktop#8620]

**Comment by ehinson69** [comment]
React-Portfolio file unable to push changes

**Comment by billygriffin** [comment]
@ehinson69 Sorry you're having problems! In order to figure out what might be going on, we need the information from the [bug report issue template](https://github.com/desktop/desktop/issues/new?template=bug_report.md), including OS version, GitHub Desktop version, reproduction steps, screenshots, and logs (from `Help` -> `Show Logs in Finder/Explorer`).

**Comment by tierninho** [comment]
@ehinson69 Please try the steps outlined here: ![Screen Shot 2019-11-13 at 9 31 56 AM](https://user-images.githubusercontent.com/14828183/68797498-cbf3c400-05f8-11ea-81a1-344bec729c2f.png)
