### ISSUE TITLE
No Menu Bar found in Windows app

### ISSUE THREAD

**Issue by maintsmartdan** [desktop/desktop#8625]
I have downloaded git hub desk top onto a new windows 10 PC. There is no menu bar. The only way to close the app in through the task manager.

**Comment by billygriffin** [comment]
HI @maintsmartdan, this is definitely not expected behavior. Would you mind filling out the [bug report template](https://github.com/desktop/desktop/issues/new?template=bug_report.md) either adding it to your issue here or closing this and making a new one with the details around your OS version, Desktop version, screenshots, etc. to help us diagnose the problem. Otherwise it's really difficult to figure out how to reproduce it. Thanks!

**Comment by tierninho** [comment]
@maintsmartdan  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.

**Comment by maintsmartdan** [comment]
sorry I got side-tracked. am buying git kraken.

**Comment by billygriffin** [comment]
@maintsmartdan If you wouldn't mind sharing with us the circumstances and a screenshot if you have an opportunity, that would be really helpful to make sure this doesn't impact others. Totally understand if you don't have the time though. Best of luck either way!

**Comment by maintsmartdan** [comment]
Brian, Thank you for you reply and your obvious dedication to solving issues such as this. I am currently taking care of my elderly mother out of state and out of office where this system resides at least until next week. I will reply then.

Thank you.

Daniel Cook
MaintSmart Software, Inc.
+1-541-751-0450
+1-888-398-0450
dcook@maintsmart.com
skype: maintsmart
http://www.maintsmart.com
