### ISSUE TITLE
Change the appearance of the push icon (up arrow) to be more distinctive than the down arrow

### ISSUE THREAD

**Issue by young-versacall** [desktop/desktop#8641]
### Describe the feature or problem you’d like to solve

On the repository list, lots of times I have down arrows indicating that there are changes to be downloaded.  As I work with a team, I don't care about getting the latest of every repo.  Sometimes, I forget to push my changes and the indication (an up arrow) is easily lost in the sea of down arrows as they are the same color.

### Proposed solution

Make the up arrow a different color (blue background for example). This will help distinguish it from the down arrow (for anyone that isn't color blind I suppose).

### Additional context

![github desktop pull vs push icons](https://user-images.githubusercontent.com/40874939/68962824-50c21780-078a-11ea-85fa-a42ee9ea8978.PNG)

**Comment by tierninho** [comment]
@young-versacall Thanks for the suggestion. I am going to link this issue to another recent issue as they are semi-related https://github.com/desktop/desktop/issues/8624.

cc @desktop/design

**Comment by billygriffin** [comment]
@young-versacall Thanks for the issue! We discussed this internally and while we think there might be room for improvement in differentiating these, we haven't seen enough signal and we're leery of changing visual things like this unless a lot of people are having issues with it because we want it to be a generally consistent and expected experience over time. We're definitely open to revisiting this if we see more evidence that it's causing problems for more people, but for now we're going to close. Thanks again!
