### ISSUE TITLE
Surface .gitconfig lockfile errors on `Configure Git`screen

### ISSUE THREAD

**Issue by steveward** [desktop/desktop#8675]
There have been two issues (https://github.com/desktop/desktop/issues/8505 and https://github.com/desktop/desktop/issues/8657) and a few Zendesk reports where users were unable to press `Continue` on the `Configure Git` section of the welcome flow. This is caused by a `.gitconfig.lock` file being present, which prevents the `.gitconfig` file from being written to. This was also an issue in classic Desktop but as far as I'm aware we didn't surface any error messaging there either.

To reproduce this you can nuke `%AppData%\GitHub Desktop` and go through the welcome flow. Once you hit `Configure Git` create a dummy `.gitconfig.lock` file in your home directory and try to press `Continue`. Here's an example error that's thrown if I have an existing `.gitconfig` and I'm trying to change my user.name:

```
2019-11-22T16:45:18.202Z - error: [ui] `git config --global --replace-all user.name steveward` exited with an unexpected code: 255.
stderr:
error: could not lock config file C:/Users/steve/.gitconfig: File exists
```

It'd be ✨ if we could surface these errors and tell the user to go to their home directory and delete the `.gitconfig.lock` file to get things working again.

**Comment by billygriffin** [comment]
@steveward Thanks! Do you know *why* a users would already have that file in their home directory? I'm definitely 👍 on solving this for people, just trying to understand how and why it's happening to them in the first place.

**Comment by steveward** [comment]
@billygriffin in the past we've seen .lock files get left around due to Git processes crashing, which causes the file not to be cleaned up. If the user has other Git applications that could be a cause of this. See https://github.com/desktop/desktop/issues/6871 for a similar scenario where an `index.lock` file prevents Git operations from being complete. We surface the error message for those cases.

**Comment by steveward** [comment]
Two more reports of this via Zendesk.

**Comment by billygriffin** [comment]
@steveward brought up a potential implementation for this, in giving users the option to delete the .lock file directly from error prompt. That would allow them to stay in the welcome flow instead of having to switch out to Explorer -> enable hidden files -> find the file -> delete it. 

This could also be useful if we ever also want to do something similar for users who run into the index.lock issue (i,e https://github.com/desktop/desktop/issues/6871).

Potential considerations are the message we present to users, and that we don't delete an index.lock file when it’s valid. We'd like to check whether Windows would prevent us from deleting an index.lock file that is being used by another active Git process. In order to implement this solution we'd also need to be able to reliably detect the location of the file in order to delete it. Just food for thought for whomever picks up this issue.
