### ISSUE TITLE
Clone succeeded, but checkout failed

### ISSUE THREAD

**Issue by frandominguez03** [desktop/desktop#8694]
### Describe the bug

I'm trying to clone one of my private repos by directly using the "Open in Desktop" option. I get the following error:
![image](https://user-images.githubusercontent.com/10365222/69499800-49231100-0ef6-11ea-89a2-49ca2eb45cf2.png)

### Version & OS

GitHub Desktop 2.2.3
Windows 10 Pro

### Logs

> 2019-11-24T19:08:08.400Z - error: [ui] `git -c credential.helper= -c protocol.version=2 clone --recursive --progress -- https://github.com/frandominguez03/IG.git C:\Users\X\Documents\GitHub\IG` exited with an unexpected code: 128.
> 
> error: unable to create file Practica1/aux.h: No such file or directory
> fatal: unable to checkout working tree
> warning: Clone succeeded, but checkout failed.
> You can inspect what was checked out with 'git status'
> and retry the checkout with 'git checkout -f HEAD'
> 
> 
> 2019-11-24T19:08:08.400Z - warn: [ui] Open Repository from URL failed, did not find or clone repository: https://github.com/frandominguez03/IG - payload: {"branch":null,"filepath":null,"name":"open-repository-from-url","pr":null,"url":"https://github.com/frandominguez03/IG"}
> 2019-11-24T19:08:57.107Z - info: [ui] Background fetch for 5 repositories took 2.113sec

**Comment by steveward** [comment]
@frandominguez03 what you are running into is an issue that is specific to Windows machines. There are  certain reserved names that cannot be used in filenames. In this specific case the `aux.h` file is causing the clone to fail because `aux` is a reserved word. The Linux kernel is a common cause of this as it has a file named `aux.c` that prevents it from being cloned on Windows machines. See [this Microsoft help article](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN#naming-conventions) for the full list of reserved characters and words.

One solution would be to use the [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10) to clone this specific repository.

I'm going to close this issue out as this is not specific to GitHub Desktop, but let me know if you have any other questions about this.

**Comment by NoahPerez** [comment]
I' m having the same issues but I have a macOS Catalina version 10.15.3.
What should I do?

Error invalid path 'src/redux/user /user.actions.js

fatal: unable to checkout working tree

warning: Clone succeeded, but checkout failed

You can inspect what was checked out with 'git status'

and try with 'git restore --source=HEAD :/

**Comment by vipulsaini2327** [comment]
Resolving deltas: 100% (217752/217752), done.
error: unable to create file EIF-CustomCode/eif-client-artifact/doc/com/ekaplus/eif/client/dataobject/cpp/procurementplanitem/ProcurementPlanItemData.ProcurementPlanDetails.ProcurementPlanItems.ProcurementPlanItemDetails.PlanItemByPeriods.html: Filename too long
error: unable to create file EIF-CustomCode/eif-client-artifact/doc/com/ekaplus/eif/client/dataobject/cpp/procurementplanvolume/ProcurementPlanItemData.ProcurementPlanDetails.ProcurementPlanItems.ProcurementPlanItemDetails.PlanItemByPeriods.html: Filename too long
Updating files: 100% (42013/42013), done.
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'



git did not exit cleanly (exit code 128) (73375 ms @ 09-11-2020 11:33:19)



How do I resolve this?

**Comment by steveward** [comment]
@vipulsaini2327 you can resolve that error by running this command from the command line (you will need to install Git for Windows if you have not already):

`git config --global core.longpaths true`

That should get things working for you.

**Comment by migueljb001** [comment]
So if I run Git Bash in administrator mode and run this command -  git config --global core.longpaths true  
This will globally set all new cloned repositorys to accept long names from here on out?  Any help would be appreciated.

**Comment by steveward** [comment]
@migueljb001 that's correct. It will set the option in your `.gitconfig` to allow longer file paths than the Windows default.
