### ISSUE TITLE
Can't authenticate github desktop account and won't let me clone my project. 

### ISSUE THREAD

**Issue by aporier** [desktop/desktop#8699]
Github desktop has been working just fine for my project until yesterday. It told me it couldn't locate my project even though it was in the location where github was looking. I decided to clone my project from online into a new location and now it's saying "Authentication failed. We were unable to authenticate with github.com. Please enter your username and password to try again". I've done this over and over. 
I've tried uninstalling Github, logging in and out, and trying to clone to different locations on my computer. Googling the issue doesn't help either.

I have github desktop 2.2.3.
Windows 10

1. Open Github Desktop
2. Click on your repository
3. Clone your repository
4. Check to make sure URL is correct and pick the location to save to.
5. Click clone.
6. The files are downloaded and put in said location.
7. Error appears and files don't connect with Github desktop as part of my repository.

### Expected behavior

Should have added my repository to GetHub desktop

### Actual behavior

Says "Authentication Failed"

**Comment by steveward** [comment]
Thanks for the report @aporier. Could you upload the log file from GitHub Desktop so that I could get some more information about this error?

To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`. The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by niik** [comment]
Thank you for your issue!

We haven't gotten a response to our questions.
With only the information that is currently in the issue, we don't have enough
information to take action. I'm going to close this but don't hesitate to reach
out if you have or find the answers we need, we'll be happy to reopen the
issue.
