### ISSUE TITLE
Github Desktop - Missing Features

### ISSUE THREAD

**Issue by kcak11** [desktop/desktop#8703]
### Describe the feature or problem you’d like to solve

Below is a list of features that are currently missing in the Github Desktop client:

1. Ability to apply a patch from a .patch file
2. Ability to manage tags
3. Ability to stash changes (stashing currently works when changing branch, but there is no dedicated UI to create a stash with custom name and apply a stash selectively / manage stashes.)
4. Ability to create a commit template with preset text that can be reused across various commits
5. Ability to delete multiple local/remote branches in a single action.
6. Ability to selectively stage/discard hunks

### Proposed solution

How will it benefit Desktop and its users?

It will benefit the developers a lot because there a quite a few other Git clients that support these options, but Github Desktop doesn't currently. Hence we are forced to use the other alternatives.

**Comment by billygriffin** [comment]
Hi @kcak11, thanks for the issue. We try to keep issues confined to discussion about one particular problem users are facing, and we also try to avoid just implementing features without understanding what problems users are solving. Many of these already have open issues associated with them - please do a quick search of the existing issues prior to opening new ones, if you don't mind. Thanks!

**Comment by kcak11** [comment]
@billygriffin my intention was just to just help the Github Desktop by consolidating some important Git features which every developer uses it on a daily basis.

> we also try to avoid just implementing features without understanding what problems users are solving

I guess I had already described that enough in the issue description.

Anyways, looks like I will have to continue using Sourcetree for now as it has all the listed features .

**Comment by billygriffin** [comment]
Hi @kcak, sorry you're feeling like Desktop doesn't have what you need. We're likely never going to have feature parity with other tools because making the overall experience simpler and solving for the workflows that most developers are doing regularly, at the expense of including every possible feature, is the way that we know how to make the best possible product. Unfortunately, every decision like that involves a tradeoff of not having every feature that any given developer might want. Several of the things you mentioned have open issues already and are things we intend to do, so we're definitely not just saying no to everything, but we do want to make sure we understand the problem and that it's widespread enough to warrant prioritizing it. We also believe that people should use whatever tool works best for them, and we hope that's GitHub Desktop, but if not we hope that you're still loving being a GitHub user more generally. Thanks again!
