### ISSUE TITLE
Show commit title and description separately in history tab.

### ISSUE THREAD

**Issue by m-ahmadi** [desktop/desktop#8712]
The commit messages in Github Desktop are shown in one long line and there's no separation between commit title and commit description like it is in github.com website.  

github.com website:
![5](https://user-images.githubusercontent.com/16363767/69734206-d60eda00-1143-11ea-95b5-66fca5fd897a.png)

but in Github desktop:
![4](https://user-images.githubusercontent.com/16363767/69735671-59c9c600-1146-11ea-9648-bc5b320790fa.png)

So I think it's very hard to read commits that way.

**Comment by niik** [comment]
Hi @m-ahmadi, did you create the commit selected above in Desktop? The reason I ask is because by convention the commit summary and description are supposed to be [separated by a newline](https://git-scm.com/docs/git-commit#_discussion). Looking at your commit they're not.

```
MacBook-Pro:tc markus$ git log -1 757525adb102023fcf5d9251b596bb5c19e07d95
commit 757525adb102023fcf5d9251b596bb5c19e07d95
Author: m-ahmadi <...>
Date:   Tue Nov 5 07:55:26 2019 +0330

    removed unused functions from lib/util
    minor formatting
```

Git will treat that entire commit message as one long commit title (or "subject" as Git calls it). See this command where I ask Git to extract the commit subject (%s) out of your commit

```
MacBook-Pro:tc markus$ git log -1 --format=%s 757525adb102023fcf5d9251b596bb5c19e07d95
removed unused functions from lib/util minor formatting
```

When I try to recreate that same commit in Desktop

![image](https://user-images.githubusercontent.com/634063/69737841-60037680-1135-11ea-9b2d-706b11c01496.png)

The commit message is formatted as I'd expect

```
MacBook-Pro:tc markus$ git log -1 7346d06
commit 7346d063ed08d917c0f0f41a8f2763c33b0e9770 (HEAD -> master)
Author: Markus Olsson <...>
Date:   Wed Nov 27 16:45:55 2019 +0100

    removed unused functions from lib/util
    
    minor formatting
```

and rendered as I'd expect

![image](https://user-images.githubusercontent.com/634063/69737866-6bef3880-1135-11ea-9d17-0b06b0821784.png)

I recognize that GitHub.com has different semantics here but we've intentionally decided to use Git's internal parsing logic for commit messages.

**Comment by m-ahmadi** [comment]
Well, those commits were made mostly with VS Code.
I usually commit with VS Code and sometimes git CLI or Visual Studio, but I never knew up till now that there was supposed to be a new line between the title and the description.

I'm closing this now. only one thought remains which I try to explain in the following.

I guess the reason I assumed there wasn't a new line between them, is mostly because of using github.com and VS Code out of the box. I know it's somewhat pointless to try to figure out the correct way of doing things in this world, but I wish the behavior of these products (`github.com`, `Github Desktop`, `VS Code`, `Visual Studio`, `etc`) was the same in this regard, and I know it's kinda short-sided to judge them based on my knowledge, but it seems like the `Github Dekstop` way is the more correct way since the link you provided was from the official git website. I guess I'm just a little frustrated with the inconsistencies.

Anyways, thanks for your helpful reply.
