### ISSUE TITLE
Can't clone specific commit

### ISSUE THREAD

**Issue by lyndmi** [desktop/desktop#8718]
### Describe the bug

Can't clone specific commit. It always says authentication failed and asking me to login
The commit is not private and can be visited and download as zip without account
https://github.com/akallabeth/FreeRDP/tree/b89fd2d8e5cdd4400c05ecac3859dc302452c355

### Version & OS

Version 2.2.3
Windows 10 x64

### Steps to reproduce the behavior

1. Click on File -> Clone repository...
2. Put this url https://github.com/akallabeth/FreeRDP/tree/b89fd2d8e5cdd4400c05ecac3859dc302452c355
3. Click on Clone

### Expected behavior

Be able to clone specific commit without an account

### Actual behavior

Authentication failed and asking me to login

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

[2019-11-28.desktop.production.log](https://github.com/desktop/desktop/files/3900620/2019-11-28.desktop.production.log)

### Additional context

None

**Comment by niik** [comment]
Hi @lyndmi, I'm afraid neither GitHub Desktop nor Git supports cloning and checking out a specific commit by entering the GitHub url to a commit.

In order to accomplish what you're after I'd enter `https://github.com/akallabeth/FreeRDP` into the clone URL box and then, once the repository has been cloned, check out the specific commit.

Note that GitHub Desktop doesn't support checking out a specific commit (see https://github.com/desktop/desktop/issues/8580) but it seems like the specific commit you're referring to is the tip of a branch called `win_clipboard_ignore_open_fail` so you should be able to switch to that branch to achieve the same effect.
