### ISSUE TITLE
Cannot push origin to GitHub from GitHub Desktop

### ISSUE THREAD

**Issue by phucanhuynh** [desktop/desktop#8721]
### Describe the feature or problem you’d like to solve

I don't know what I do wrong, I just changed my username and deleted a repository. When I use GitHub Desktop to create new repository and try to fetched to GitHub. there's a error: "The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed". I even removed GitHub Desktop and reinstalled, try to create a repository in local then tried to push to GitHub as a new project but it doesn't work

**Comment by niik** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

A log file from the day you experienced this issue would be helpful. As a general troubleshooting tip I'd start by making sure you're signed in to the correct account by opening the preferences dialog and signing out of your account and then back in again.

Thanks for understanding and meeting us half way :grinning:

**Comment by tierninho** [comment]
@pholleran  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
