### ISSUE TITLE
Cloning of fork clones original repo instead

### ISSUE THREAD

**Issue by Gitjas** [desktop/desktop#8733]
### Describe the bug

I try to clone a fork on my GitHub useraccount, but it keeps on cloning the original repo from an organization I am member in. I could reproduce this for two different organizations and repos. I should add that I was owner of the organizations' repos before but transferred the original repos, then forked them into my own account.

### Version & OS

GitHub Desktop Version 2.2.3
Windows 7 Ultimate

### Steps to reproduce the behavior

1. Create a repo in your own GitHub useraccount with clone on your Desktop
2. Transfer ownership of your repo to an organization account where you have the rights
3. fork the now transferred repo to your GitHub useraccount
4. remove and delete your local repo using GitHub Desktop
5. clone the fork from your useraccount to your desktop
6. notice that it is not the forked repo but the original (now from the organization) the cloned repo is pointing at with its origin

### Expected behavior

If I clone a repo from my useraccount I expect the cloned repo on my desktop to link to the one in my useraccount, not to the original GitHub repo elsewhere.

### Actual behavior

If I clone a repo from my useraccount that is a fork from a repo elsewhere (where I had the owner rights before and am still with editing rights there), the clone on my desktop is linked to the original repo, not my fork.

### Additional context

As mentioned above, it might be related that I had the original repos in my useraccount before transferrring ownership and forking them back. I did removed and deleted the cloned repos using GitHub Desktop and tried cloning the forks several times with always the same outcome.
I never had problems with this earlier but didn't use it for a while now, but from my perspective this might be related to the last Desktop update.

**Comment by niik** [comment]
Hi @Gitjas, sorry to hear you're having problems. We've had similar reports of problems when renaming repositories and I suspect your issue stems from the same root cause.

See https://github.com/desktop/desktop/issues/3855, https://github.com/desktop/desktop/issues/8590, and a potential fix https://github.com/desktop/desktop/pull/8132.

Could you take a look at the repository settings dialog (`Repository` -> `Repository settings` menu) and see if the remote URL there is what you'd expect it to be.

For now the only reported workaround to this problem is to remove the [application data folder for GitHub Desktop](https://github.com/desktop/desktop/issues/3855#issuecomment-524457126) and start from scratch. I'm not sure if that's something you'd be willing to try but for now that might be the best solution.

**Comment by tierninho** [comment]
@Gitjas  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.

**Comment by Gitjas** [comment]
Yes, sorry for being slow. I'll come back to this when I'll work with this again and then I'll try out the tips. Thanks!

**Comment by Gitjas** [comment]
More feedback:
If I go to Repository/Repository settings and them chose
-> Primary remote repostory (origin)
it links to the original master. 
If I put the path to my fork in here, my clone is linked to my fork as I want it.

So, this can be corrected by manually setting the path to the fork for Primary remote repostory (origin) under Repostory Settings after cloning.

Thanks!
