### ISSUE TITLE
Cannot use the command line tools after install

### ISSUE THREAD

**Issue by RyanMitchellWilson** [desktop/desktop#8755]
I installed this because I read that it will install the command line tools for you. I've installed the desktop app and then went into Options > Advanced and switched my Shell to PowerShell. I then reboot PowerShell and typed `git -h` and I get:
```
git : The term 'git' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ git -h
+ ~~~
    + CategoryInfo          : ObjectNotFound: (git:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by RyanMitchellWilson** [comment]
There is little to no documentation about this or how to set things up. The site just says install and use but clearly that isn't the case here.

**Comment by steveward** [comment]
@RyanMitchellWilson thanks for contributing. GitHub Desktop does not automatically install Git for Windows on your machine -- you will need to [download](https://git-scm.com/download/win) and install it separately. After doing that you should be able to use Git in PowerShell.

If you attempt to use Git from within GitHub Desktop without it being installed (via `Repository` > `Open in PowerShell`) the application will throw an error that Git is not installed on your system and provide a link to download it. Since you launched PowerShell outside of GitHub Desktop you never received this message. I'll make a note to add more information  about this to our documentation.

Let me know if you run into any further problems.

**Comment by SystemDZ** [comment]
Solved same problem by reinstalling GIT.
And Refresh npm.
Than closed editor and reopened it
