### ISSUE TITLE
Cannot clone/link from github thru github desktop

### ISSUE THREAD

**Issue by Teeina** [desktop/desktop#8758]
### Describe the feature or problem you’d like to solve
Not able to link to the 443 port of github through github desktop

A clear and concise description of what the feature or problem is.

```
stderr:
Cloning into 'C:\Users\ruoyuyin\Documents\GitHub\serving'...
fatal: unable to access 'https://github.com/knative/serving.git/': Failed to connect to github.com port 443: Timed out
```

**Comment by niik** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by tierninho** [comment]
@Teeina Are you possibly behind a proxy or firewall that could be blocking access to GitHub?

if your proxy requires credentials there are some steps you can take to configure it:

Go to the file menu and select `Repository > Open in Terminal (macOS)` or `Open in command prompt` (Windows)

Run the following command:
`git config --global http.proxy http://proxyuser:proxypwd@proxy.server.com:8080`

Replace `proxyuser` with your proxy username and `proxypwd` with your proxy password. Also, `proxy.server.com:8080` needs to point to the URL of your proxy server.

Attaching your logs from the Help menu would also help. Let me know.
