### ISSUE TITLE
File exceeding 100MB limit error doesn't specify what file

### ISSUE THREAD

**Issue by Sievaxx** [desktop/desktop#8767]
### Describe the feature or problem you’d like to solve
When you have one or more files exceeding the 100MB limit, the error message preventing you from uploading only tells you a file went over the limit, and nothing more. It would be nice if the error message actually specified the file with a path and/or file name.

### Proposed solution
Add the path to the file(s) and/or the file name(s) to the 'File(s) exceed 100MB upload limit' error message.

**Comment by steveward** [comment]
Thanks for contributing @Sievaxx. If you attempt to commit files over 100MB we do show a list of the problematic files that need to be removed, but I can understand how this would be frustrating if you have an existing local repository with large files already in it. This has been previously discussed in https://github.com/desktop/desktop/issues/997 and https://github.com/desktop/desktop/issues/5079. #7849 is also of interest since it proposes the idea to check a repository for large files during the process of adding it to GitHub Desktop.

Since we have the commit warning already in place that should prevent most cases of this, but I'm always in favor of improving our error messaging so I'm going to throw an` enhancement` label on this.

You can also refer to [this comment](https://github.com/desktop/desktop/issues/5718#issuecomment-423957795) if you need assistance removing large files from your repository.
