### ISSUE TITLE
Unable to publish repository using github desktop.....it says error 128

### ISSUE THREAD

**Issue by Akshay6890** [desktop/desktop#8773]

**Comment by steveward** [comment]
@Akshay6890 thanks for the report. Could you send over the log file so that I could take a closer look at this error?

To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`. The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by Akshay6890** [comment]
This is the log file
[2019-11-25.desktop.production.log](https://github.com/desktop/desktop/files/3940710/2019-11-25.desktop.production.log)

**Comment by steveward** [comment]
@Akshay6890 it looks like there may be an issue with your name and email in your .gitconfig. Can you go to the menu in GitHub Desktop and select `File` > `Options` > `Git` and verify your name and email are set there?

**Comment by tierninho** [comment]
@Akshay6890  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
