### ISSUE TITLE
"friendly suggestion" really doesn't work when said by a computer program

### ISSUE THREAD

**Issue by brianharvey** [desktop/desktop#8822]
### Describe the feature or problem you’d like to solve

"Here are some friendly suggestions for what to do next" is creepy, especially when it's basically always there.  Maybe the first time that message appears it'd be okay, but it would be vastly improved by removing the "friendly."

I realize this isn't the most important of problems, but on the other hand it should be easy to fix!

### Proposed solution

Remove "friendly" from the message.  It'll make the user experience less creepy.

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by Rexogamer** [comment]
I don’t personally see the creepiness, can you elaborate

**Comment by tierninho** [comment]
For reference, this is what @brianharvey is referring to:

![Screen Shot 2019-12-19 at 9 23 26 AM](https://user-images.githubusercontent.com/14828183/71203097-78047c80-2241-11ea-8d5b-b7cfbec47f9a.png)

The interpretation of the word is subjective, but leaving it/removing it is of no consequence...

**Comment by brianharvey** [comment]
It's kind of like walking up to a stranger and saying "I'm really friendly" only worse because it's a computer, and neither friendly nor unfriendly.  But if nobody else thinks so, don't worry about it.

**Comment by outofambit** [comment]
Hey @brianharvey thanks for filing this issue! Since the proposed change centers on writing style, I think we'd need to have a discussion about why the new wording would be more aligned with the tone and voice of GitHub Desktop before we make any changes.

It doesn't seem like there's a clear answer either way here, so I'm leaning towards leaving it the way it is for now. I'm going to close this issue, but happy to reopen if there's more information to consider.
