### ISSUE TITLE
ACCESS DENIED

### ISSUE THREAD

**Issue by rapheal1101** [desktop/desktop#8823]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by steveward** [comment]
@rapheal1101 thanks for contributing! 

Would you mind filling out the rest of the issue template so that we can better understand what is causing the problem you are experiencing? Without that information it will be difficult to help you further. It would especially be helpful if you could upload the log file from GitHub Desktop, which will give more details about the specific error you are seeing. 

To access the log files go to the  menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`. The log files are created daily -- please send over a log file as an attachment from a day where you experienced the issue. Thanks!

**Comment by billygriffin** [comment]
@rapheal1101 Since we haven't heard back from you, I'm going to close this issue for now, but if you're willing to share what was asked above, we're happy to take another look!
