### ISSUE TITLE
me sale un aviso de que no tengo permiso de master para push, como lo solucionaria

### ISSUE THREAD

**Issue by MariaElena22** [desktop/desktop#8834]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by niik** [comment]
Automatic translation of title:

```I get a warning that I don't have a master permit for push, how would I solve it?```

---

Hi @MariaElena22, the warning you're seeing means that you have not been given write access to the repository in question, see [Permission levels for a user account repository](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/permission-levels-for-a-user-account-repository).

The usual method of contributing to a repository that you don't own yourself is to [fork the repository](https://help.github.com/en/github/getting-started-with-github/fork-a-repo) and contribute changes using a [pull request](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests).

I hope that helps. If you believe the warning is inaccurate please open a new issue and fill out the issue template so that we can help you troubleshoot what's wrong.
