### ISSUE TITLE
Cannot Pull

### ISSUE THREAD

**Issue by dereklau33** [desktop/desktop#8835]
### Describe the bug

When trying to pull, there is an error displaying "Fatal: file name in tree entry contains backslash: .."

### Version & OS

v 2.2.4 on windows 10

### Steps to reproduce the behavior

1. Click Fetch Origin

### Expected behavior

Code is pulled successfully

### Actual behavior

Outputs Error Message shown in Screenshots

### Screenshots

![image](https://user-images.githubusercontent.com/47903763/71496097-39a12b80-2806-11ea-8bda-b8c6fbe674f3.png)

### Additional context

This error did not occur until today despite having the new updated version for the past two weeks. I did not have this error when pulling last week

**Comment by niik** [comment]
Hi @dereklau33, thanks for reporting this. I believe what's happened here is that someone with access to the repository has created a file containing a backslash character (`\`). Using backslash characters in filenames is allowed on POSIX filesystems such as the ones commonly used by Linux or macOS but they're not allowed on Windows where the backslash character is reserved as the directory separator character. Since this is a technical limitation in the operating system Github Desktop won't be able to create the file.

The fact that you say that it's started occurring relatively recently makes me suspect that the file in question has also appeared recently. I would look at the repository on GitHub.com and locate the file in question, see who added it and consult them about renaming it. You can delete or [rename the file](https://help.github.com/en/github/managing-files-in-a-repository/renaming-a-file) using the GitHub.com web interface.
