### ISSUE TITLE
unable to use post-commit hook if it includes 'git push' command

### ISSUE THREAD

**Issue by pepeworld** [desktop/desktop#8847]
### Describe the bug
What I am trying to do is having an automated `git push` after a commit is done.
The issue is when a `post-commit` hook includes `git push` command, the application's commit process gets stuck.

![image](https://user-images.githubusercontent.com/56680359/71613341-63b86c00-2bbf-11ea-95c3-0e7eee2bba5e.png)

### Version & OS

Github Desktop: version 2.2.4
OS: Windows 10 Version 1903

### Steps to reproduce the behavior

1. I have the following script in my hooks directory:

```
#!/bin/sh

git push 
```
2. updated any file in the repo
3. with the commit message written, pressed on the "commit to master" button

### Expected behavior

Commits and pushes the commit automatically.
**Doing a commit from git bash or vs code will run the hook without a problem.**

### Actual behavior

the commit process gets stuck.
![image](https://user-images.githubusercontent.com/56680359/71613341-63b86c00-2bbf-11ea-95c3-0e7eee2bba5e.png)
The commit does happen, but the hook action doesn't, and the commit button doesn't revert back to the non-blocked "in progress" state.

### Logs

```git.log
2019-12-31T07:22:03.305Z - info: [ui] [AppStore] loading 6 repositories from store
2019-12-31T07:22:03.305Z - info: [ui] [AppStore] found account: pepeworld (bugs)
2019-12-31T07:22:04.093Z - info: [ui] launching: 2.2.4 (Windows 10.0.18362)
2019-12-31T07:22:04.093Z - info: [ui] execPath: 'C:\Users\potato\AppData\Local\GitHubDesktop\app-2.2.4\GitHubDesktop.exe'
2019-12-31T07:22:04.330Z - info: [ui] Current tutorial step is NotApplicable
2019-12-31T07:22:04.612Z - info: [ui] Current tutorial step is NotApplicable
2019-12-31T07:22:05.200Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 1.122s)
2019-12-31T07:22:10.015Z - info: [ui] Current tutorial step is NotApplicable
2019-12-31T07:22:12.631Z - info: [ui] Current tutorial step is NotApplicable
2019-12-31T07:22:12.878Z - info: [ui] [Timing] Action 'create commit' for 'pepeworld/React-Tick-Tac' took 1.092s
2019-12-31T07:22:29.957Z - info: [ui] Current tutorial step is NotApplicable
2019-12-31T07:22:32.393Z - info: [ui] Current tutorial step is NotApplicable
```

### Additional context

redirecting the script to run a python script would help getting certain git commands to run:
```sc.sh
#!/bin/sh
echo 'Running post commit hook' > ~/Desktop/pythonoutput.txt

python .git/hooks/pushrepo.py >~/Desktop/pythonoutput.txt
```
pushrepo.py:
``` pushrepo.py
import os
import subprocess

print(os.getcwd())
subprocess.Popen("git --version")
```
output:
```out.txt
C:\Users\potato\Documents\GitHub\React-Tick-Tac
git version 2.19.2.windows.4
```

however running `git push` would once again produce the same behavior, with this output:
```out.txt
C:\Users\potato\Documents\GitHub\React-Tick-Tac
```

**Comment by steveward** [comment]
@pepeworld thanks for the report. I was able to reproduce this issue as well on my machine. One interesting note -- I have a test repository that uses a SSH remote URL and the `post-commit` hook worked successfully in that repository.

**Comment by riexn** [comment]
for context, this is what I am using:
* Windows 10
* VS Code
* Git Bash

I looked into this issue by building the **development environment** of github desktop.

In the hooks, whenever a git command that requires authentication to work is called in a git hook, it would prompt the user to put in their username and password. 
This is with commands such as `git push`

In order to get the prompt:
* Login into github desktop
* create a `post-commit` hook in a repository that already has remote set up with this code:
```
git push
```
* make changes in the repo and commit them in desktop

and this prompt will appear:

![image](https://user-images.githubusercontent.com/37214468/89714651-46e3e280-d9b1-11ea-872f-b1856e42eacc.png)


after putting in the username and the password, the hook will work fine without any issues in **development environment** only.

This prompt never appears in the production build, and this is why the **committing to master** button hangs forever.
and this is exactly why running the hook in a repository that has SSH remote set up works, but HTTPS doesn't.

Overall, it seems like the cached credentials are not carrying over to the hooks when running them through github desktop.

No clue on how to solve this issue, but those are my findings.

**Comment by steveward** [comment]
@riexn thanks for sharing your findings! That's helpful.

**Comment by Mr1262** [comment]
Thanks sir

**Comment by tidy-dev** [comment]
I have retested and was unable to reproduce. I assume the changes to the auth flow since this ticket was opened appears to have resolved it.
