### ISSUE TITLE
Stash / bring changes no more asked on protected branch

### ISSUE THREAD

**Issue by Seb33300** [desktop/desktop#8851]
### Describe the bug

When switching from a protected branch to another, popup modal to ask if I want to bring or stash my changes doesn't appear.

### Version & OS

Version 2.2.4 on Windows 10

### Steps to reproduce the behavior

1. Modify a file on a protected branch
2. Switch to another branch
3. Changes are applied to the selected branch without warning

### Expected behavior

The popup to ask if we want to stash or bring changes should appear.

### Actual behavior

The popup only appear when we switch between unprotected branches.

### Additional context

I usually work on my local environment with the protected master branch and commit my changes to a new branch when my development is done.
So I can easily pull new commits from master without the need to rebase all the time.
But sometime I need to switch to another branch to fix an issue but I don't want to bring my current work and the popup doesn't appear anymore in the last version for protected branches.

**Comment by niik** [comment]
Hi @Seb33300, thanks for opening this issue and thanks for taking the time to describe your workflow, that's always helpful to us!

The behavior you describe is intentional and came out of https://github.com/desktop/desktop/issues/8664 and was implemented in https://github.com/desktop/desktop/pull/8714.

I'll CC @billygriffin who has more context than me on this particular design decision to see if he's gott any input into this discussion but for now I'm afraid there's no workaround other than creating the branch before you start making changes. 

This has the added benefit of letting you commit frequently and thus create good fallback points as you develop your changes. As for the problem of not wanting to rebase so frequently I wanted to point out that GitHub Desktop fetches and fast-forwards branches in the background so rebasing should be as simple as hitting <kbd>Ctrl+Shift+E</kbd> to bring up the rebase dialog (it starts with the default branch pre-selected) which should then tell you whether a rebase is necessary or not. I hope that is of some use to you.

**Comment by Seb33300** [comment]
I am working on a big repository used by many developers pushing on it all the time.

Most of the time, my development is done in few hours.
Most of the time I only need to commit once when my development is finish.
That why I am working on master, so I can continuously pull changes (just 1 click) and test my code without the need to rebase my branch (which can be boring and useless manipulation - since I also need to fill my password to force push - when you need to do it 10 times a day). 

I am working the way you describe only when my development will take several days.

**Comment by kuychaco** [comment]
@Seb33300 thanks for shedding light on how this is impacting you. It sounds painful indeed, and your feedback is valuable.

This particular way of handling switching branches when there are changes on a protected branch is intended to reduce friction where possible. I'm going to close this issue for now because this was an intentional design choice and we know there will unfortunately be tradeoffs. If we learn that more people are having this issue then we will revisit and consider alternate implementations.
