### ISSUE TITLE
I have to rename a file to force push to the repository

### ISSUE THREAD

**Issue by Lkjhg** [desktop/desktop#8873]
### Describe the bug

When I commit the change the file is not posted until I change its name.

### Version & OS

Version 2.2.4
Windows 10

### Steps to reproduce the behavior

1. Commit an image file to the repository
2. Change image properties in the local repo - for example image size
3. Try to commit changes - the file is recognized as changed, but the file itself is not pushed (my webp age shows old /not resized image after successful commit  and a number of refreshes).

### Expected behavior

Updated image file detected as changed/modified should be pushed to the repository.

### Actual behavior

The image file is marked as changed but is not pushed to the main repository.

**Comment by Lkjhg** [comment]
Actually I wanted to look for a similar post first  .. but I created a new one.
Typing without reading.   I am sorry.

To the point.
I often have to change size of images that are already posted to the repository.
When I commit the change the file is not posted until I change its name.

So, I have to change the file name that contains resized image and I have to update the code that is using this image.
Maybe Github client could also check "last change timestamp" not only filename ?

**Comment by tierninho** [comment]
@Lkjhg Please fill out the template above so we have info to go on. Thanks for meeting us half way.

**Comment by Lkjhg** [comment]
Maybe this time its better :)

**Comment by tierninho** [comment]
Not required, but if you are ok with attaching the logs, that would be helpful. See the Help menu in Desktop.

**Comment by niik** [comment]
> 3\. Try to commit changes - the file is recognized as changed, but the file itself is not pushed (my webp age shows old /not resized image after successful commit  and a number of refreshes).

Hi @Lkjhg, since the file is showing up as changed in GitHub Desktop and you're able to commit it I suspect this issue is related to cache settings on your website hosting platform rather than GitHub Desktop. Given that changing the file name allows you to view it on your website further reinforces this.

I'd suggest reading a bit about [web caching mechanisms](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/http-caching) and perhaps particularly about [cache busting](https://www.keycdn.com/support/what-is-cache-busting) and see if that helps explain things.

Since this isn't directly related to GitHub Desktop I'm going to close this issue. If you're using [GitHub Pages](https://pages.github.com) to host your website I'd suggest [contacting our support team](https://support.github.com) for more details about caching on GitHub Pages.
