### ISSUE TITLE
Preferred shell options

### ISSUE THREAD

**Issue by iAmWillShepherd** [desktop/desktop#888]
Users should be able to select their preferred shell in settings. In cases where no selection is made, we should use the OS default.

**Comment by kmscode** [comment]
Would love to see this in Windows prior to 1.0 since cmd.exe is just terrible. Looks like you've got a fair amount of users looking for this as well between up-votes and referenced issues...

I would love to see an option to use git-bash.exe, but powershell at a minimum. Thanks!

**Comment by joshaber** [comment]
Thanks @kmscode, we're planning to do this for 1.0 👍

**Comment by joshaber** [comment]
This needs design around how we set it in Preferences.

**Comment by joshaber** [comment]
I assume this'll be more or less like "Open in External Editor."

What shells do we wanna support? For Mac, I'd guess:

* Terminal
* iTerm2
* Hyper

And for Windows I have no idea 😆

**Comment by Tajnymag** [comment]
For Windows, shells which I could imagine to be wanted are:
- PowerShell (probably the most wanted) 
- Bash on Ubuntu on Windows
- MSYS2

**Comment by kmscode** [comment]
For windows, I would hope that the following options would be available at a minimum:

- %ProgramFiles%\Git\bin\bash.exe (if available)
- %windir%\System32\WindowsPowerShell\v1.0\powershell.exe (if available)
- %windir%\system32\cmd.exe
- Custom (fill in the blank with a full path)

Notes:
The options as listed above look ugly and since the current UI is so nice, maybe pretty up the front end and list:

- Git-Bash
- PowerShell
- CMD
- Custom
 
Or something like that.

The installdir for Git can be found in the registry:

    HKEY_LOCAL_MACHINE\SOFTWARE\GitForWindows\InstallPath

as it may be different than specified above.

CMD will be available on all systems. PowerShell will be available on more modern systems out of the box, but will require a separate install on older Windows versions. Just another pitfall that you may have to account for...

Other popular ones might be Cygwin, and [Bash that is available in later versions of Windows 10](https://msdn.microsoft.com/en-us/commandline/wsl/about). However, the "custom" field covers all of these (at least for now) since they are less likely to be available out-of-the-box.

**Comment by joshaber** [comment]
Thanks @Tajnymag, @kmscode! 💖

**Comment by forrestab** [comment]
Just wondering, what happened to the Custom option, it doesn't appear in the 1.0.13 version. I would like to use WSL/Bash on Ubuntu on Windows, however, my only options are Command Prompt, Powershell, Hyper and Git Bash.

**Comment by shiftkey** [comment]
@forrestab we don't currently have plans to bring back the custom shell, for reasons I outlined in a different issue: https://github.com/desktop/desktop/issues/2487#issuecomment-347375512

We're open to taking contributions to enable WSL as an option, the details about how to add support is covered by our docs: https://github.com/desktop/desktop/blob/master/docs/technical/shell-integration.md

**Comment by shiftkey** [comment]
> Also, will changing this also change where git hooks are ran?

I'm not aware of any issues like this with Git hooks.

**Comment by forrestab** [comment]
@shiftkey the git hooks appear to only have problems if the npm scripts you want to run in them were installed via WSL because there is no executable or `*.cmd` file for windows to execute. It is not any issue per-se, but what I believe is a disconnect between the two systems (windows and wsl).

Thanks for the response though.
