### ISSUE TITLE
Using old node version

### ISSUE THREAD

**Issue by jonaskkristensen** [desktop/desktop#8884]
### Describe the bug
I can't commit anything when using Husky. It works fine running cmd in terminal. I'm getting the error message
`Commit failed - exit code 1 received, with output: 'Husky requires Node 8.6.0, can't run Git hook.'`

### Version & OS

Github Desktop 2.2.4
MacOS Mojave 10.14.6

### Screenshots
<img width="599" alt="Screenshot 2020-01-08 at 09 32 44" src="https://user-images.githubusercontent.com/26645731/71963190-6dfbeb00-31fb-11ea-88d8-cafd45d758e1.png">

**Comment by niik** [comment]
Hi @jonaskkristensen, sorry to hear you're having problems. GitHub Desktop ships with an internal version of Git which we use for all actions inside the app. As such the environment within which your commit hooks execute will likely not exactly match that of your normal environment.

Are you by chance using a Node version manager such as `nvm`, 'asdf-nodejs`, or `nodenv`? These tools usually require custom environment variables to be configured in order to redirect the node binary to a specific version. Since we don't ship a node environment accessible from the Git subsystem my suspicion is that Node 8.6.0 is the version of node which you've got installed globally on your machine.

**Comment by tierninho** [comment]
@jonaskkristensen As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.

**Comment by Kevnz** [comment]
This is actually still an issue and not just for the person who reported. Closing it a week later seems a little like telling people to go away.

**Comment by tierninho** [comment]
@Kevnz Thank you for your thoughts. The issue was closed as we did not obtain a reply which would have given us the necessary info to properly address the submission efficiently. By no means do we wish our community to go away -- sorry to hear that. We generally give a user a week to reply, and if nothing, we close the issue. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Is there anything we can help you resolve? Happy to reopen if you are having the same problem.

**Comment by jonaskkristensen** [comment]
I never resolved this issue. But I figured out, this error message will show each time husky catch an error under commit. If husky don't catch any errors, it will commit just fine with Desktop.
So everytime husky catched the error, it was necessary for me to commit by terminal, to see what the error message was from husky, then fix it and then commit with Desktop.

**Comment by tierninho** [comment]
@jonaskkristensen Thanks for circling back with the helpful solution to your issue. Cheers

**Comment by dpwiese** [comment]
I think the best solution is to specify node version with `.nvmrc` in the project and call `nvm use` in `~/.huskyrc` to switch to the correct version. This could be similarly accomplished for whatever your node version manager of choice is.

The use of a `.nvmrc` file in the project repo shouldn't harm anything for those who don't use nvm, and if nothing else allows people to see which node version may be required for a project. (I'm actually surprised this is not more common, rather than checking a status badge in a readme or something to determine node version.) And for those who _do_ use nvm it makes life easy to switch to the correct node version with `nvm use`, or even adding a small function to your `.zshrc` or equivalent to automatically check for the existence of `.nvmrc` and call `nvm use` automatically when changing into a dir.

**Comment by tinymachine** [comment]
I ran into a similar issue with GitHub Desktop using node 11.15.0 even though I had already used nvm to `use` LTS (node 14.17.3 at time of writing). I didn't realize that using the `nvm use` command only changes the current environment, not all environments. To fix this, I ran `nvm alias default 14.17.3` and then restarted GitHub Desktop. That fixed my problem — now GitHub Desktop appears to use that newer nvm default version.

**Comment by michealroberts** [comment]
This is STILL an issue in 2023.

**Comment by michealroberts** [comment]
Who is maintaining this project? This is STILL an issue in November 2023. **_Can we get an answer_** as to whether this is being worked on, or do we just deprecate our usage of Github Desktop?

All logs of what node version the system is using is coming back with 20.9.0 for me, but Github Desktop is still stating it is set to 17.

I have used nvm, node and also pnpm env use ... nothing works.

**Comment by philwhln** [comment]
@michealroberts Does using `nvm alias default 20` work for you? We just resolved this using this solution.

**Comment by philwhln** [comment]
The docs still should be updated, as the steps outlined here are not sufficient
https://github.com/desktop/desktop/blob/5c494415c80869af02234397b0e4637cd87090cc/docs/contributing/setup-macos.md?plain=1#L26-L48

**Comment by philwhln** [comment]
I'm guessing the node version for GitHub Desktop is defaulting to this :point_down: if `nvm alias default` is not set
https://github.com/desktop/desktop/blob/5c494415c80869af02234397b0e4637cd87090cc/.node-version

**Comment by lezama** [comment]
This issue is still occurring for me. Even with a `.nvmrc` file in the project specifying Node 22, GitHub Desktop still uses the system's Node version (20.8.1 in my case) for Husky pre-commit hooks. 

The workaround I found is to add nvm initialization to `~/.config/husky/init.sh`:
```bash
if [ -f ~/.nvm/nvm.sh ]; then
  . ~/.nvm/nvm.sh
  nvm use
fi
