### ISSUE TITLE
Add support for opening a file to a specific line in the editor

### ISSUE THREAD

**Issue by percyhanna** [desktop/desktop#8886]
### Describe the feature or problem you’d like to solve

When viewing a diff of a file, it would be very convenient to click/right-click on a line in the diff view, and have your editor of choice automatically navigate to that line.

### Proposed solution

I know that Sublime Text supports navigating to a specific line by appending the line number in the format of `:{line}` at the end of the path being opened, e.g. `/path/to/README.md:100`. I assume other editors might have similar support.

### Additional context

n/a

**Comment by outofambit** [comment]
Hi @percyhanna, thanks for writing this up! This is something we've discussed internally in the past and I agree would be useful. Unfortunately, it's hard to justify as a focus for engineering work since Desktop has so many editor integrations—we would have to add this integration editor by editor (after doing the Desktop UI portion). This might be easier to approach later in the development of Desktop if we focus on editors and integrations more as a theme, but there are no plans for that currently. I'm going to close this for now, thanks!
