### ISSUE TITLE
Feature request - allow multiple instances

### ISSUE THREAD

**Issue by NeilMacMullen** [desktop/desktop#8912]
### Describe the feature or problem you’d like to solve

I would like to analyse the changes on two branches/repositories at the same time (I want to compare how one changed vs the other).  Unfortunately it seems that it's not possible to run multiple instances of the desktop client - there's no apparent keyboard shortcut or menu-item to open up another view window and the 'standard' shift-click on the taskbar icon (windows) simply changes focus to the already-open instance.

### Proposed solution
A new menu item "View/New Instance" should create a new instance with its own state.

How will it benefit Desktop and its users?

Working on "two things at once" (TM) seems like a fairly common scenario.  Being able to maintain state for each of them saves time.  Allowing them both to be visible facilitates scenarios where you want to compare them.

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by niik** [comment]
Hi @NeilMacMullen, thanks for opening this! There's a fair bit of context and history about why we've not implemented this feature in https://github.com/desktop/desktop/issues/3606 so I'm going to close this issue in favor of that one. Please add a 👍 to that issue (as an emoji reaction) and if you feel like there's context that's not captured in there feel free to add it as a comment.

This issue will also be cross-references in #3606 so that we can get to the context should we decide to revisit supporting multiple windows.
