### ISSUE TITLE
desktop app size

### ISSUE THREAD

**Issue by reavesprater** [desktop/desktop#8923]
I would like to be able to minimize the app window smaller but it seems to have a minimal size constraint.

**Comment by tierninho** [comment]
Yes, the app has a minimal size constraint in order to maintain the integrity of the app. 

Please share your reasoning as we would like to learn more about your situation. Thanks.

**Comment by reavesprater** [comment]
Takes up a lot of space.  Standard Macbook pro.  Should be able to see
changes without taking up so much space.

[image: image.png]

Thanks,
<https://www.ovation.io> <reaves@ovation.io>

**Comment by billygriffin** [comment]
Hi @reavesprater, sorry you're having a hard time with the size. Because of the way the app functions, we do maintain the minimum window size to ensure that the right things are always visible in the app. This is an intentional decision that we don't intend to change, and I'm sorry that the minimum size is still too large for your liking.

**Comment by Moosbrugger** [comment]
App window so large it goes off screen.

**Comment by sh0ckx23** [comment]
same struggle here. @billygriffin is there somewhere a settings file where we can "hack" the max hights?

**Comment by kc75093** [comment]
Same here, my laptop native resolution is 1366x768, and the commit button can not be seen, it's below screen.

**Comment by DoctorDerek** [comment]
Still a problem
