### ISSUE TITLE
Hanging at writing objects 0% all day

### ISSUE THREAD

**Issue by GuSo187** [desktop/desktop#8963]
### Describe the feature or problem you’d like to solve
I cannot push an update, it hangs at 0% all day.

I even tried a new branch.

I even tried on a new project

### Proposed solution

So I & others can continue using the software

**Comment by GuSo187** [comment]
The remote end hung up unexpectedly
The remote end hung up unexpectedly
RPC failed; curl 56 send failure; Connection was reset

**Comment by steveward** [comment]
Thanks for the report @GuSo187. Could you upload the log file from GitHub Desktop so that I could get some more information about this error?

To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`. The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by tierninho** [comment]
In addition to the logs request, the RPC error relates to some issue that prevented the data from being received. Temporarily disable any firewall or anti-virus software and attempt to clone again.

**Comment by tierninho** [comment]
@GuSo187  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
