### ISSUE TITLE
[Metrics] Forking flow

### ISSUE THREAD

**Issue by nerdneha** [desktop/desktop#8971]
👋 We'd like to get a better idea of how helpful the Forking flow (#8509) is that we're creating and whether the solution we've proposed makes a difference in the problem that people experience when they have worked on a repo they don't have write permissions to and want to keep their work. 

Here are some initial thoughts about what we're trying to measure here:
 1. How many people are committing their work to a repo that they don't have write permissions for? How is that number changing each month? 

This will help us know whether this is a consistent problem that people run into.

 2. Of those people who try to push their work, how many people create a fork because of the functionality that we provide?

This will give us a signal on whether the solution we're providing is one that our users understand and want to use.

cc @outofambit @billygriffin

**Comment by billygriffin** [comment]
> How many people are trying to push their work to a repo that they don't have write permissions for? How is that number changing each month?

What if this was "how many people are committing" instead of "how many people are trying to push"? In other words, are you doing work on a repo where you don't have write access? And how does that compare to the number who end up creating a fork in order to contribute instead of having that work effectively orphaned. Since there's a path to create a fork prior to actually attempting to push, I feel like the commit level might be a better level of granularity.

**Comment by nerdneha** [comment]
@billygriffin that's a great point. i agree that we'd want to measure from the minute we expose a path out -- i've gone ahead and updated the description to reflect that!

**Comment by billygriffin** [comment]
Awesome @nerdneha, thank you! I think your updated description accurately describes what @outofambit and I discussed as well. We want to be able to understand something along the lines of: "Last month, x% of Desktop users committed to [# of repos] repos that they didn't have permission to push to. This month, x% of those users forked [# of repos] using GitHub Desktop, bringing down the number of repos where someone committed work they couldn't push by x%."

To be able to understand something like this, we'll need to know:
1. total repos where a user without write access commits at least once
2. total number of commits in a repo where they don’t have write access
3. number of forks created from desktop (potentially split between the two paths to create a fork, though not necessarily)

@outofambit also mentioned wanting to know the conversion rate for the "push failed" dialog to fork creation. In other words, if people are hitting that dialog because they don't have the correct permissions, are they creating a fork via Desktop nearly all the time, or is there something else we might be missing?
