### ISSUE TITLE
Easy path to create an issue from GitHub Desktop

### ISSUE THREAD

**Issue by billygriffin** [desktop/desktop#8989]
### Describe the feature or problem you’d like to solve

In https://github.com/desktop/desktop/issues/2376, @TheGrimSilence proposed an idea to be able to create issues in GitHub Desktop. Generally we've felt like an integrated approach goes too far in the direction of in-app project management, but we do frequently hear that in the context of doing your work, if you see something that warrants creating a new issue, there's not a great path for that currently without causing considerable context switching and related cognitive overhead.

### Proposed solution

Our proposal here is to create a menu item and associated keyboard shortcut to direct people to the correct issue creation path on GitHub.com. This is dependent on a single path that accounts for repositories that use issue templates and those that do not, which doesn't currently exist but hopefully will in the near future.

This menu item should live in the `Repository` menu.

### Considerations

1. This is dependent on work on GitHub.com that provides a common path that satisfies the use case of repositories that use issue templates *and* those that do not. Currently the path would need to be /issues/new/choose for repositories using templates, and /issues/new for those not using templates.
2. We'll have to determine how to handle the cases where repositories do not have issues enabled at all (which is true for newly created forks by default - thanks @Rexogamer).

**Comment by MakePixelsWork** [comment]
This still means you are redirected to another environment and have to switch back and forth. Having a full in-app (desktop) solution seems better to me... so you can keep it all in one central place and let the contents sync with the online Github environment and vice versa. One of the pillars of Git, right?

I'm not against a link that facilitates this from within the Desktop version, but a full integration seems better.

**Comment by billygriffin** [comment]
Thanks @MakePixelsWork - we've talked about that several times, and though we agree that it would likely be useful for some folks, we don't think project management is core enough to the app's core functionality to warrant the prominence of an integrated experience. At least that's our working assumption to date, though we're not opposed to revisiting after this initial implementation.

**Comment by Rexogamer** [comment]
another thing to note: forks by default don’t have issues enabled, so we’ll have to work around that

**Comment by billygriffin** [comment]
> another thing to note: forks by default don’t have issues enabled, so we’ll have to work around that

This is a great point, thanks @Rexogamer! I was hoping we wouldn't need any information from the API for this and we could just rely on a common target URL, but it sounds like that edge case might present some difficulties. I added a "Considerations" section to the issue body so we sort those things out in implementation.

**Comment by Kruithne** [comment]
Personally, I would love to see issues actually integrated into the GitHub Desktop app rather than just an external link. It seems like something that should definitely be in-scope for a GitHub first-party application given that issues are an integral part of GitHub. If the primary platform of the application was Git rather than GitHub, the reasoning for keeping them separate would make more sense, but "GitHub Desktop" gives the impression it should be a desktop alternative to GitHub, not a half-measure.

In the current implementation, without built-in UI for handling issues, there's not an encouraging amount of reason to use GitHub Desktop as an alternative over solutions provided by most IDEs already which are pretty much on parity. Moving between an IDE, GitHub Desktop, and the web GitHub when managing a project is more friction than it's worth.

 It doesn't make sense for something like VSCode to expand it's source control support for GitHub issues, but I personally think it makes the most sense anywhere for GitHub Desktop to support GitHub issues.

**Comment by billygriffin** [comment]
@Kruithne Thanks for your perspective. While I appreciate that you think GitHub Desktop should enable people to do everything that GitHub.com does, we disagree. The app is not intended to be a replacement for the functionality of GitHub.com, but a mechanism that enables people to be more productive in doing their work locally in tandem with GitHub.com. Sometimes this means that we'll enable functionality directly in GitHub Desktop, and sometimes it means that we just try to reduce friction in the handoff between your local environment and your browser. In this case, we're starting with making the handoff easier and more direct.

**Comment by Kruithne** [comment]
@billygriffin That makes a lot of sense, I appreciate the clarification. Even knowing the mindset behind the choice I still hope one day the team will reconsider this. I agree that GitHub Desktop should not replace the browser version; there's a lot of stuff that GitHub offers that could happily remain on the web version as they're not integral to a development workflow. For example, setting up actions or adjusting templates isn't something that's done with excessive frequency.

When it comes to issues, I still strongly believe this should be a core feature in GitHub Desktop and would excel it's value as an every-day development tool. Maybe I am bias due to workflows I am familiar with, but for me cross-referencing between the code-base and GitHub issues is almost as frequent as actually committing changes.

When it comes to making commit messages, I will almost always need GitHub open side-by-side with GitHub Desktop to recall an issue ID or add relevant details to a commit, which requires flicking between, rather than simply being able to have issues on the right-hand side as an alternative view to the file diff, as one example of the frequent usage.

Either way, thank you for the consideration! I hope one day the team will reconsider. 👍

**Comment by digitalentropy** [comment]
I'd like to chime in here and say that it feels like a glaring omission that there is no ability to comment on, or manage issues in the desktop client considering it's such a integral part of team-based development. There are plenty of folks who for different reasons do not leave their browser logged into web apps (clearing all cookies automatically).

Please, please, add this. I don't understand why there is such extreme resistance to it, other than trying to dictate to others how they should work.

**Comment by isaaccloos** [comment]
Issue integration for GitHub Desktop would improve my work. I hope this is still on the table despite being closed and several years old. 

Extending the functionality of the GitHub desktop client to include more of the websites feature set would benefit the whole community.

**Comment by Matherone** [comment]
Yes, please – the ability to create, edit and close Github issues directly from within a git client is quite nifty.

+1 for adding Github issue control to Github Desktop.

For inspiration, or for users who need this feature now, the git client **Gitkraken** offers built-in tools for managing Github issues since 2020 – and it works quite well. See e.g.: https://www.gitkraken.com/blog/gitkraken-git-gui-v7-3-github-issues

**Comment by tidy-dev** [comment]
Feedback from #17749 


> Let people manage issues of repositories from GitHub Desktop.

 > This will help GitHub Desktop users to stay inside one designated app for their work. Opening a web browser to check Issues feels clunky and sometimes leads to loosing yourself in the web (like watching a *short* YouTube video.. we all know how this cycle continues.) 

> After they downoad their repository from GitHub/upload their repository to Github, fill in the unused space next to "Fetch origin" with Issues tab.
![image](https://github.com/desktop/desktop/assets/108594296/f99d1faa-314f-4bbc-b205-267f751c9219)
*the screenshot was taken in the minimum width of the app*
