### ISSUE TITLE
Hitting Refresh should not send cache headers anywhere in the app

### ISSUE THREAD

**Issue by jzabroski** [desktop/desktop#8999]
### Describe the bug

Related to #5865

### Version & OS

GitHub version 2.2.4

### Steps to reproduce the behavior

1. Go to open a local repository
2. Click on the master branch dropdown/tab
3. Click on the pull requests nested tab
4. Click on the refresh button

### Expected behavior

1. Request: No HTTP cache headers.
2. Response: should not be 304 Not Modified
3. Response: should be 200 OK with fresh content
4. Optimistic concurrency test: Two successive refresh requests should not have the same ETags if the number of pull requests has changed between requests.

### Actual behavior

HTTP cache headers are sent, indicating my program is making a cached request, with no option to override this behavior.

### Screenshots

![Cache Headers on Refresh](https://user-images.githubusercontent.com/447485/73300859-b6e20680-41df-11ea-98b7-a370737be238.png)

### Logs

n/a 

### Additional context

n/a

**Comment by niik** [comment]
Hi @jzabroski, thanks for opening this and for providing detailed screenshots, that always helps!

You are correct that we send an `If-None-Match` header when refreshing the list of pull requests, this is intentional and shouldn't interfere with the refresh logic.

The request that you've captured asks for the 10 most recently updated pull requests regardless of state (i.e. open, closed) and uses the result of that to determine whether anything has changed since the last time the list of open pull requests was refreshed.

The ETag lets us avoid transferring the full response from the API as long as the top 10 most recently updated pull requests were the same as the last time (the ETag in this case is a product of the entire response meaning that as long as the order or any property of a pull request changes the ETag would change). I think enforcing revalidation could be interesting for the refresh button since there is a 60 second `max-age` directive from the server that can be confusing if you're attempting to refresh immediately after opening a PR for example but event then we should still send the `If-None-Match` header.

The fact that you're seeing the API return a 304 here means that the pull requests has not changed since the last time Desktop attempted to refresh which in turn means that the problem you are experiencing must lie elsewhere. GitHub Desktop stores what it believes to be the timestamp of the most recently updated PR for a particular repository. The next step would be to figure out if that somehow has gotten out of sync but let's move that back into #5865.

**Comment by jzabroski** [comment]
As a customer used to web browsers, the response that I cannot override your caching policy is just weird to me.  Without being pedantic, "that's now how the web works".  I need a flexible way to express I do not want a cached copy.  Web browsers support modular, hard refresh for this reason.  You just refresh the one page you need refreshed.

> The fact that you're seeing the API return a 304 here means that the pull requests has not changed since the last time Desktop attempted to refresh which in turn means that the problem you are experiencing must lie elsewhere.

With all due respect, I am skeptical of this claim.  Just because you say "304, ergo No Change" doesn't make it true - and, objectively, it's not true since we can see my screenshots don't match the reality.  Until I actually get a chance to try it out (by overriding this behavior), how do you know it's true?  Furthermore, how can I collaboratively help to resolve this annoying problem if you just tell me what the problem isn't?  Users have gone to long lengths in #5865 to workaround this problem by deleting their LevelDB, which basically affirms there is something wrong with the caching infrastructure (e.g., are you using a database like MongoDB that is known to fails Jepsen tests?), even if you say there isn't a problem.    By deleting LevelDB, we're basically doing a hard refresh of EVERYTHING, which is just extremely wasteful, both of GitHub resources and my time to reconfigure everything.
