### ISSUE TITLE
Real name displayed instead of username

### ISSUE THREAD

**Issue by SevenSpheres** [desktop/desktop#9000]
### Description

When viewing the commit history for [this repository](https://github.com/CelestiaProject/CelestiaContent) in GitHub Desktop, one of two commits by @LukeCEL shows their username, but the other shows what I assume to be their real name (Luka Sato). This is a serious privacy concern as they haven't added their name to their GitHub profile.

Luke is unable to duplicate this.

### Version & OS

GitHub Desktop 2.2.4; Windows 10.

### Steps to reproduce the behavior

1. Clone [this repo](https://github.com/CelestiaProject/CelestiaContent)
2. View commit history
3. As of now the commit in question is right at the top

### Expected behavior

"LukeCEL authored" displayed in the commit history.

### Actual behavior

"Luka Sato authored" displayed in the commit history.

### Screenshots

![luke1](https://user-images.githubusercontent.com/56284207/73324084-f96b0980-4206-11ea-857c-e14b10c713ad.png)
![luke2](https://user-images.githubusercontent.com/56284207/73324085-f96b0980-4206-11ea-95d3-e59dbe8734ce.png)

Edit: :nine::zero::zero::zero:

**Comment by steveward** [comment]
Thanks for contributing @SevenSpheres. 

The behavior you are encountering is due to how Git stores your name and email address, and how GitHub uses that information to provide commit attribution. GitHub matches the email address associated with a commit to a GitHub account that has that same email address. If the email address that is used for a commit is not being used with a GitHub account then GitHub will display the `user.name` value associated with that commit (which is what you are seeing in this instance). If you add `.patch` to the end of a commit URL you can view the name and email that was used for that specific commit. You can read more about this in the following help article:

https://help.github.com/en/github/committing-changes-to-your-project/why-are-my-commits-linked-to-the-wrong-user

The name and email address used by Git can be configured in GitHub Desktop by going to `File` > `Options` > `Git`. To remove the name from the repository you would need to rewrite the history. We have a script along with steps for how to do that here:

https://help.github.com/en/github/using-git/changing-author-info

Please note the warnings in that article -- rewriting the history of a repository is destructive and can cause issues for other contributors. I hope that helps explain things!

**Comment by vicaba** [comment]
Shouldn't his behaviour be changed? I think one expects Github to use their Github username as the commit author instead of their real name.

**Comment by steveward** [comment]
@vicaba the Git username is not the same as your GitHub username, since you may use other Git hosting services besides GitHub.

**Comment by owopeachy** [comment]
you need to change the git config of whichever git instance on your local machine made the push to the username you choose. From within the git environment run `git config user.name` to view the current name, and add a name to the end of that command to set the name. (e.g. `git config user.name owopeachy` To change the default systemwide name put `--global` after `git config`

**Comment by darianmorat** [comment]
Its pretty funny cause usernames are unique, so it would make sense to use it as the Author name... when I commit locally I have darianmorat, but if I use the GUI in github I get Darian Toledo, when it would make sense to use the username!

**Comment by austinfoemmel-maker** [comment]
i just want me username
