### ISSUE TITLE
Many Git For Windows executables running in background

### ISSUE THREAD

**Issue by pythonInRelay** [desktop/desktop#9028]
### Describe the bug

When running Git for Windows, it spawns a very high amount of executables running in the background. 

### Version & OS

2.3.1

### Steps to reproduce the behavior

1. Run Git for Windows application
2. Check Task Manager -> See the below image:

https://ibb.co/pwJzgq9

This also happens as part of another program, e.g. with Unity where the amount of executables can be between 2 and ~20. See the image below:

https://ibb.co/rp2gLxp

### Expected behavior

There shouldn't be so many instances of this executable running in the background

### Additional context

Possible dupe of #3465, but no fix was given for this issue either.

### Log

[2020-02-01.desktop.production.log](https://github.com/desktop/desktop/files/4142664/2020-02-01.desktop.production.log)

**Comment by outofambit** [comment]
Hi @pythonInRelay thanks for filing this issue. Are you experiencing poor performance on your machine or in GitHub Desktop because of this? (Obviously its better to not have these hanging out in the background, just assessing impact on you.)

It sounds like you experience this with GitHub Desktop and Unity. Do you use https://unity.github.com/ by any chance? Or have it installed?

**Comment by tierninho** [comment]
@pythonInRelay  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
