### ISSUE TITLE
Missing organization repos and can't do nothing if cloned from cli and imported

### ISSUE THREAD

**Issue by Yanujz** [desktop/desktop#9041]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by steveward** [comment]
Thanks for reaching out @Yanujz!

Would you mind filling out the rest of the issue template so that we can better understand what is causing the problem you are experiencing? Without that information it will be difficult to help you further. It would especially be helpful if you could upload the log file from GitHub Desktop, which will give more details about the specific error you are seeing. 

To access the log files go to the  menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`. The log files are created daily -- please send over a log file as an attachment from a day where you experienced the issue

**Comment by Yanujz** [comment]
Hi! First of all thank's to quickly reply!

Sorry for my poor information, I'll try to explain.

I belong to this organization called MAGICMOTORSPORT:
![Screenshot from 2020-02-05 09-10-19](https://user-images.githubusercontent.com/36811836/73822950-8ad60f00-47f7-11ea-9a38-91dfc8343df3.png)

and as you can see i'm in this repo:
![Screenshot from 2020-02-05 09-08-50](https://user-images.githubusercontent.com/36811836/73823003-a80add80-47f7-11ea-848d-510a7b661faa.png)

But if a try to clone this repo from the desktop app:
![Screenshot from 2020-02-05 09-10-50](https://user-images.githubusercontent.com/36811836/73823114-e2747a80-47f7-11ea-9bb5-79c79b3911af.png)


I hope now is more clear.

If you need other info, please tell me!

Thank's

**Comment by steveward** [comment]
@Yanujz do you not even see the repository you are looking for in the `GitHub.com` repository list in GitHub Desktop? Let me know if this is still an issue for you and we can debug it further.
