### ISSUE TITLE
UI should refresh within short window after file system change.

### ISSUE THREAD

**Issue by deanius** [desktop/desktop#9070]
### Describe the feature or problem you’d like to solve

There is no reason the UI should lag behind the file system indefinitely, as it has done in recent builds.

### Proposed solution

GH Desktop used to be reactive-  if i reverted files in the CLI, the GUI updated within little time after changing the FS. Now, the GUI will gladly display stale data until I focus it. I am not glad to GUI displays stale data about changes by default. It's non-obvious that focusing the app is needed in order to get it to reflect reality - it should reflect reality as it happens, which it once did if I'm not mistaken.

**Comment by afwn90cj93201nixr2e1re** [comment]
![изображение](https://user-images.githubusercontent.com/9306996/74092949-e26cc700-4ae4-11ea-959e-38dedfcee0d0.png)
![изображение](https://user-images.githubusercontent.com/9306996/74092959-f7495a80-4ae4-11ea-8356-0c62efaf9d2b.png)
What's wrong with UI on latest win 10?

**Comment by niik** [comment]
Hi @afwn90cj93201nixr2e1re, please open a new issue if you're having problems with the application appearance

**Comment by niik** [comment]
Hi @deanius, thanks for opening this.

GitHub Desktop attempts to balance the use of system resources while in the background with automatically refreshing when changes are detected. The refresh-on-focus method is one we've been using for a long time now and one that's generally been well received. I don't believe we ever had immediate refresh though it's possible that the refresh interval has changed somewhat since the beginning.

Right now the app will refresh itself on focus and (I believe) every five minutes or so when not in focus. We don't have any plans of changing this behavior but we appreciate that you took the time to call out a behavior that was felt wrong to you. If we receive more reports of this being confusing to users we'll revisit but for now the refresh behavior is intentional.

**Comment by afwn90cj93201nixr2e1re** [comment]
nice support, this bug exists on latest win 10, after github desktop update, no, i don't wanna create new issue and describe everything, it's takes too much time.

**Comment by Rexogamer** [comment]
@afwn90cj93201nixr2e1re we can’t help you much unless you create a new issue fowlloing the bug template

**Comment by afwn90cj93201nixr2e1re** [comment]
;( i don't wanna, sry. I think it's was reported, but, idk where.
