### ISSUE TITLE
GitHub Desktop Authentication Failed

### ISSUE THREAD

**Issue by stevearchuleta** [desktop/desktop#9090]
### Describe the bug

Error Message when attempting to Publish Branch: Authentication Failed "We were unable to authenticate with github.com"

### Version & OS
GitHub Desktop 2.3.1
OS X El Capitan 10.11.6

### Steps to reproduce the behavior

1. Go to Publish you branch.
2. Click on Publish Branch button.
3. Enter correct username and password.
4. See error (Authentication Failed)

### Expected behavior

I expect to publish the current branch (master) to the remote.

### Actual behavior

Error Message when attempting to Publish Branch: Authentication Failed "We were unable to authenticate with github.com"

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

### Additional context

I have logged out of gitHub desktop then logged back in (same authentication error message).
I have locked then unlocked my MacBook KeyChain Access (exact same result when I try to publish)

**Comment by niik** [comment]
Thanks for the report @stevearchuleta. Could you upload a log file from GitHub Desktop so that I could get some more information about this issue? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue. Thanks!

**Comment by tierninho** [comment]
@stevearchuleta  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
