### ISSUE TITLE
Introduce auto completion in summary and description fields for commit like in Co-Authors

### ISSUE THREAD

**Issue by Alvin-Seville** [desktop/desktop#9097]
### Describe the feature or problem you’d like to solve

Introduce auto completion in `summary` and `description` fields for commit like in `Co-Authors` which works when I press `Ctrl`+`Space`.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by niik** [comment]
Hi @Alvin-Seville, thanks for opening this.

Ctrl+Space works in the Co-Authors field because there's you can only autocomplete usernames there whereas in the summary and description fields you can autocomplete usernames, issues, and emoji. Because of this we've elected to follow the same convention as GitHub.com uses in comment fields, and issues like the one you just created which is to trigger the autocompletion flow when typing `@`, `#`, or `:` in the textbox.

This is not something we've heard a lot of feedback about and it's not something we're planning on changing but if we hear more requests we can always revisit.

**Comment by Alvin-Seville** [comment]
It `Rider` there is an autocompletion for commit comment for instance for changed files.
