### ISSUE TITLE
Introduce git stashes support

### ISSUE THREAD

**Issue by Alvin-Seville** [desktop/desktop#9099]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by niik** [comment]
Hi @Alvin-Seville, we introduced support for stashing your changes when switching branches in GitHub Desktop 2.0, see our [blog post](https://github.blog/2019-06-05-github-desktop-expands-to-support-stashing-and-rebasing/) about that release for more details.

Right now we're not looking to expand on that support to include manual creation of stashing (see  https://github.com/desktop/desktop/issues/8197#issuecomment-527249225). Please subscribe to https://github.com/desktop/desktop/issues/8197 to stay notified of any developments on that front.

**Comment by JosephTLyons** [comment]
Just hear to voice my opinion that I think manual creation of stashes should exist in GitHub Desktop.  I've gathered that GitHub wants to limit some things in Desktop In order to keep it user-friendly to those not intimately familiar with Git (new programmers, etc.) and to keep their application simple to use, but I feel that because stashes were introduced (in a limited way), they should be accessible in the normal way as well (manual creation of them).

**Comment by cpetry** [comment]
I also vote for this feature!
