### ISSUE TITLE
Quit and Restart

### ISSUE THREAD

**Issue by nikhil-mongo** [desktop/desktop#9104]
### Describe the bug

Error: spawn /Applications/GitHub Desktop.app/Contents/Resources/app/git/bin/git EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:19)
    at onErrorNT (internal/child_process.js:429:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)

### Version & OS
Version: 2.2.3
OS: Mac OS 10.15.3
### Screenshots

https://share.getcloudapp.com/7KuR19xD

**Comment by niik** [comment]
Hi @nikhil-mongo, thanks for opening this. Sorry to hear you're having problems.

I noticed that you're running an older version of GitHub Desktop (2.2.3), the most recently released version is 2.3.1. Could you attempt to upgrade to the latest version by clicking on the `GitHub Desktop` -> `About GitHub Desktop` menu item?

If you're unable upgrade because of crashes then I'd suggest downloading the app again from https://desktop.github.com and replacing your copy in the Applications folder with the newly downloaded version.

If the problem persists after upgrading to the latest version please let us know and we can reopen this issue.
