### ISSUE TITLE
Clone starred projects

### ISSUE THREAD

**Issue by Tokusei** [desktop/desktop#9119]
### Describe the feature or problem you’d like to solve

Hi, I have a lot of projects which I have starred on the website, Which I would like quick access to via the github desktop application, Also it would be nice if I could organize the repos I have starred into different categories (via tags/folders/language)

### Proposed solution

The current GUI displays user repos, and ones from an org they are linked to.

![image](https://user-images.githubusercontent.com/4631534/74601118-36733f00-50d5-11ea-93a5-f68628f6647b.png)

Add a section which lists the repos which a user has starred, so they have quick access to cloning them. Additionally add some filters (Repo Owner, Primary Language, Custom Tags).

You can also create a drag and drop folder interface, where the user can organize their own repos and starred ones into different sections. this would be useful pre and post cloning the project. You can cache the folder structure locally or add it as a user configuration to their account.

**Comment by billygriffin** [comment]
Hi @Tokusei, thanks for the issue! Because stars are used so differently by users on GitHub and can often be something more akin to a "like," we don't plan to add them to the cloning flow as there's not a shared signal for what they should be and the load time of the list would increase dramatically for people who have starred a lot of repos. Thanks for the idea!
