### ISSUE TITLE
No repos for me

### ISSUE THREAD

**Issue by spottedmahn** [desktop/desktop#9124]
### Describe the bug
The app says I don't [have any repos](https://github.com/spottedmahn?tab=repositories):

![image](https://user-images.githubusercontent.com/14079228/74677246-c670c180-5185-11ea-9754-2e2e4dc53d7d.png)

### Version & OS
Win 10 v1909
Version 2.3.1

### Steps to reproduce the behavior

1. Go to 'Add Repo'

### Expected behavior

[A list of my repos](https://github.com/spottedmahn?tab=repositories)

### Actual behavior

It says I don't have any repos.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

>2020-02-17T15:39:09.223Z - info: [ui] [AppStore] loading 12 repositories from store
2020-02-17T15:39:09.224Z - info: [ui] [AppStore] found account: spottedmahn (Michael DePouw)
2020-02-17T15:39:10.789Z - info: [ui] launching: 1.1.1 (Windows 10.0.18363)
2020-02-17T15:39:10.790Z - info: [ui] execPath: 'C:\Users\mdepouw\AppData\Local\GitHubDesktop\app-1.1.1\GitHubDesktop.exe'
2020-02-17T15:39:11.284Z - warn: [ui] fetchAccount: failed with endpoint https://api.github.com
Error: Bad credentials
    at Object.t.parsedResponse (C:\Users\mdepouw\AppData\Local\GitHubDesktop\app-1.1.1\webpack:\app\src\lib\http.ts:162:1)
    at <anonymous>

### Additional context
From the above log it appears I need to sign back in but the app isn't automatically telling me that like it should IMHO.

**Comment by outofambit** [comment]
@spottedmahn thanks for this bug report! you are right that you mostly likely need to sign in again to fix this. and you are right that the app should tell you this. i'm going to mark this a p-2 bug since it's not easily recoverable for a user that isn't reading their logs (which i imagine is most).

cc @desktop/support are there other places we've seen similar problems? ie something fails becuase of auth and the user isn't properly notified?

**Comment by spottedmahn** [comment]
>you most likely need to sign in again to fix this

Yep, that fixed it, FYI 😀

Wonder if it is related to 2 factor auth? 🤔

**Comment by spottedmahn** [comment]
fixed? 🤞
