### ISSUE TITLE
When HDR display is found, the window is dark on SDR display

### ISSUE THREAD

**Issue by RocketRobz** [desktop/desktop#9129]
### Describe the bug

The window is shown fine when one or all displays have HDR turned off.    
But when turning HDR on, on the HDR-supported display, the window becomes dark on the non-HDR display.

### Version & OS

* Version 2.3.1
* Windows 10

### Step to reproduce the behavior

Enable HDR on one of your displays that support it, while keeping one display with HDR turned off.

### Expected behavior

Window brightness is the same on SDR display.

### Actual behavior

Window is dark on SDR display, but is at the correct brightness on the HDR display.

### Screenshots

![GitHub Desktop dark](https://user-images.githubusercontent.com/16110127/74695300-bc17ed00-51b0-11ea-80ff-e9ad95b8e09c.png)

**Comment by steveward** [comment]
Thanks for the report @RocketRobz. This was reported in #7233, and is caused by a [specific issue in Electron](https://github.com/microsoft/vscode/issues/68069) that should be resolved when GitHub Desktop updates to Electron 7. Could you try installing the [beta version](https://github.com/desktop/desktop#beta-channel) of GitHub Desktop to verify that the issue has been fixed? The beta version has Electron 7 support. Let us know if that doesn't fix things for you.

**Comment by RocketRobz** [comment]
Yep, the beta fixes it.

**Comment by steveward** [comment]
@RocketRobz great, thanks for confirming!
