### ISSUE TITLE
git-lfs plugin

### ISSUE THREAD

**Issue by necrose99** [desktop/desktop#9133]
github plugins or Desktop Extensions could be added to extend funtionality of GH desktop/Enterprise desktop while keeping base app small. 

after adding lfs plugin , desktop console ui will just hopefully wrap it ... 
**https://github.com/git-lfs/git-lfs** 

**GitHubDesktop\app-2.3.1\plugin\git-lfs.exe**

git-lfs from cmd line, would be a plus. and or tag files drag drop as is. 

*.xfiile > ios etc git lfs. 

```
>git lfs migrate import --include="*.tbz2" --everything
git: 'lfs' is not a git command. See 'git --help'.

The most similar command is
        flow
```

granted i'd should use linux , but i havent bought or setup as home server..

**Comment by steveward** [comment]
@necrose99 thanks for contributing. GitHub Desktop does include Git LFS by default, so any existing LFS repositories should work without issue. If you want to use Git LFS from the command line you will need to install Git for Windows, which also includes Git LFS by default now.

Are you wanting to see specific features of Git LFS directly implemented into GitHub Desktop?

**Comment by necrose99** [comment]
mainly was trying to initialize  the branch for 1st time.  
after that it should just work like any other code push . 

only other wish list , Linux desktop port would be so sweet. 

any rate , just getting LFS started via gui was less , intuitive. 

after big push hopefully the python code will work on ebuild and push but since its from a gentoo fork taking a few tearks to get lfs//runing.. 

just from cli getting i added gittabutes... to .git folder.. etc.. 
ideally you could open cli add git-lfs cmd's > .git settings add tarballs to inventory tracing  and push

**Comment by outofambit** [comment]
hi @necrose99 those are a lot of different ideas! we're not planning to change our support for git-lfs in the forseeable future (see #8419 for a recent discussion about this). let us know if you have any further questions. thanks!

also, there's an unofficial linux desktop fork at github.com/shiftkey/desktop if you want to take a look over there.

**Comment by rgraniero** [comment]
I just downloaded and installed Github Desktop and it would not allow large file commit and suggested I use Git-lfs. What am I missing?

**Comment by steveward** [comment]
@rgraniero you will need to track the file or filetype by running the command `git lfs track "file"`. See [this guide](https://docs.github.com/en/github/managing-large-files/configuring-git-large-file-storage) for more information. GitHub Desktop does not currently have built-in functionality for adding files to be tracked by Git LFS.

**Comment by rgraniero** [comment]
Thank you, Steve for your response. However, when I do that I receive this
error:

” 'git' is not recognized as an internal or external command,

operable program or batch file.”



So then I downloaded git-lfs and run it I get the same thing.



Then I tried git-lfs track
C:\Users\…\GithubRepos\LEG_Butterfly_BillReview\*.accdb I receive:

Error getting git version: exec: "git": executable file not found in %PATH%



However, I checked my %PATH% and Git-lfs is there. So, now what am I
missing?





<https://www.salusworkerscomp.com/>

*Rico Graniero, MCTS* *| ** salusworkerscomp.com
<https://www.salusworkerscomp.com/>*
Assistant Director of Information Systems  |  o469-312-5636 c214-642-9511
This message contains confidential information intended solely for the use
of the parties named above.





*From:* Steve Ward <notifications@github.com>
*Sent:* Thursday, August 20, 2020 12:14 PM
*To:* desktop/desktop <desktop@noreply.github.com>
*Cc:* Rico Graniero <rgraniero@salusworkerscomp.com>; Mention <
mention@noreply.github.com>
*Subject:* Re: [desktop/desktop] git-lfs plugin (#9133)



@rgraniero <https://github.com/rgraniero> you will need to track the file
or filetype by running the command git lfs track "file". See this guide
<https://docs.github.com/en/github/managing-large-files/configuring-git-large-file-storage>
for more information. GitHub Desktop does not currently have built-in
functionality for adding files to be tracked by Git LFS.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/desktop/desktop/issues/9133#issuecomment-677791377>, or
unsubscribe

**Comment by steveward** [comment]
@rgraniero it looks like Git is not installed on your system. You can download it from https://git-scm.com/download/win.

**Comment by rgraniero** [comment]
Ah. So I need both Git and Github Desktop?

My company does have a Github account that I am trying to upload to using
Github Desktop. It works fine with files less than 100 mb. So, I also need
Git?





<https://www.salusworkerscomp.com/>

*Rico Graniero, MCTS* *| ** salusworkerscomp.com
<https://www.salusworkerscomp.com/>*
Assistant Director of Information Systems  |  o469-312-5636 c214-642-9511
This message contains confidential information intended solely for the use
of the parties named above.





*From:* Steve Ward <notifications@github.com>
*Sent:* Thursday, August 20, 2020 12:29 PM
*To:* desktop/desktop <desktop@noreply.github.com>
*Cc:* Rico Graniero <rgraniero@salusworkerscomp.com>; Mention <
mention@noreply.github.com>
*Subject:* Re: [desktop/desktop] git-lfs plugin (#9133)



@rgraniero <https://github.com/rgraniero> it looks like Git is not
installed on your system. You can download it from
https://git-scm.com/download/win.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/desktop/desktop/issues/9133#issuecomment-677798786>, or
unsubscribe

**Comment by steveward** [comment]
GitHub Desktop does not include Git for Windows, so to use Git from the command line you need to install it separately. You can launch the command line from the menu by selecting `Repository` > `Open in <command line application>`.

**Comment by rgraniero** [comment]
Thank you @steveward for your help on this. I am up and running with Github desktop, Git-lfs, and Git.
