### ISSUE TITLE
Failure to Launch on Windows Server 2016

### ISSUE THREAD

**Issue by alex-pax** [desktop/desktop#9134]
### Won't launch on Windows Server 2016

Unable to successfully launch GitHub desktop 2.3.1 on Windows Server 2016 v. 1607 OS 14393.3443.  I've successfully installed it.  The directories C:\Users\user_name\AppData\Local\GitHubDesktop\ and C:\Users\user_name\AppData\Roaming\GitHub Desktop\ exist and are populated with the expected files.  

When I run GitHubDesktop.exe, the icon appears in my taskbar, but it either never loads up or it takes >10 minutes to load.

**Comment by steveward** [comment]
Thanks for the report @alex-pax. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue. Thanks!

**Comment by alex-pax** [comment]
Is there a way to access them outside of GitHub Desktop?  My issue is that the application won't open, so I don't have a way to follow your instructions.

**Comment by steveward** [comment]
@alex-pax obviously that would be an issue -- sorry about that. You can go to `%AppData%\GitHub Desktop\logs` to see if there is anything available. It may also be worth checking `Event Viewer` to see if anything interesting is showing up there.

**Comment by alex-pax** [comment]
Thanks, here's my log: 
2020-02-19T15:16:00.292Z - info: [main] Received possible protocol arguments: 2
2020-02-19T15:16:00.293Z - error: [main] Malformed launch arguments received: C:\Users\my_user_name\AppData\Local\GitHubDesktop\app-2.3.1\GitHubDesktop.exe,--squirrel-firstrun

**Comment by steveward** [comment]
@alex-pax thanks for sharing that -- unfortunately there isn't much there to determine why the app isn't launching consistently. I spun up a test instance of Server 2016 and was able to get GitHub Desktop working without issue. Is there possibly anything running on this machine that could be preventing the app from launching (i.e. security software)?

**Comment by alex-pax** [comment]
@steveward Yes, there's almost certainly security software, and I understand if that's outside of the scope of what you can assist with.

Could I clarify one thing with you: the two directories created during installation are `%AppData%\Local\GitHubDesktop\` and `%AppData%\Roaming\Github Desktop\`.  The second one is where my logs go, and it's not exactly the same path that you pointed me to for the logs.  Could that be causing some of my issues?

**Comment by steveward** [comment]
@alex-pax `%AppData%` is an env variable that points to `AppData\Roaming`, so that isn't the issue. 

Are you able to try temporarily disabling the security software you are running on this machine? We don't officially support Windows Server for GitHub Desktop but since it's based off of Windows 10 it should work. My guess is that something is locked down and preventing GitHub Desktop from running correctly in this case.

**Comment by tierninho** [comment]
@alex-pax  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
