### ISSUE TITLE
Automatic fetch and pull

### ISSUE THREAD

**Issue by itsacrimetorhyme** [desktop/desktop#9145]
Have a setting that when enabled, automatically fetches every 30 seconds and automatically creates a pull request if there is a change.

This would make it so much easier for people who use their phone/another computer to make changes to something running on a server/other computer. Instead of pushing the code, remoting into the server/other computer, fetching, then pulling, all that would happen automatically.

**Comment by billygriffin** [comment]
Hi @itsacrimetorhyme, we do a fast forward merge for branches that you're not on as part of the auto-fetching process in the background, but not for your current branch because that can get dicey. This felt like a reasonable compromise and still does, so I'm going to close this as something we don't intend to support, but I'm curious why the current implementation is falling down for your use case.
