### ISSUE TITLE
In history 'commited X days ago' is obfuscatory, show the dates when more than one day instead.

### ISSUE THREAD

**Issue by shamilovtim** [desktop/desktop#9147]
In the history tab, when commits in history are more than one or two days old, provide a date of when the commit was made rather than saying 'X days ago'.  It's really not obvious what date my commit was when it says e.g. "11 days ago." The mental math should not be necessary if I want to get a date for my commit.

Example of the problem:
<img width="250" alt="Screen Shot 2020-02-20 at 4 01 48 PM" src="https://user-images.githubusercontent.com/3495974/74978386-7e0e0980-53fa-11ea-94e0-a54552aa52b0.png">

**Comment by billygriffin** [comment]
Thanks for the issue @shamilovtim, but this has been a longstanding GitHub convention that's mirrored on issues, PRs, commits, and diverging from that isn't something we're keen on doing unless there's widespread agreement that it's a good choice. So I'm going to close this to indicate that this isn't something we intend to change, but really appreciate you sharing your perspective!

**Comment by shamilovtim** [comment]
Hey @billygriffin doesn't the convention includes the date though? The Desktop convention omits the dates entirely.

Attached see Github commit history:
![image](https://user-images.githubusercontent.com/3495974/74979090-e9a4a680-53fb-11ea-83ec-458b2f660c2f.png)

**Comment by billygriffin** [comment]
@shamilovtim In that example it does as a header. You can also hover your cursor over the "7 days ago" and get the timestamp (thanks @lee-dohm for reminding me to mention that as well), which is also true for most if not all of these instances on GitHub.com as well.

**Comment by shamilovtim** [comment]
Thanks! It wouldn't hurt to add segment titles with dates to the listview though! I don't see a drawback to adding it and it would help with the UX quite a bit.

**Comment by billygriffin** [comment]
We haven't heard from many people that the specific date is a super important piece of information to know for a commit that's more than a couple days old, and generally we try to only elevate the most broadly agreed upon important information. So given that if you want that extra bit of information there's a way to do so, I'm inclined to leave it as is for now, but we're always open to revisiting if it becomes obvious that this is causing problems for a broad cross-section of users. Thanks again!

**Comment by zjkuang** [comment]
I totally agree with @shamilovtim 
cc: @billygriffin

**Comment by UhuruNUru** [comment]
Your "Feedback" is from those actively working on projects, and relates to commits, but many users are directed here by links
only want to know when a specific version is released.
if you can have a setting to set emoticon skin shades, and set local time, just add a setting to display date & time per user account.
it's not that hard in fact I'm pretty sure you're recording actual time, then site code is obfuscating this for some dumb reason, that never made any real sense, so a simple user toggle would suffice.

It especially annoys me to see the LCD (Lowest Common Denominator) defence that Microsoft always rolls out, when removing user choice.
"We haven't heard from many people", 
So what, just one means thousands agree, but just found a 3rd party tool that does what they want?
It shouldn't ever matter how many nag you about it, the LCD is called DEFAULT settings, and that's how it's meant to be.
Power Users find user scripts to force their will upon unhelpful web sites.

I love getting my games from GOG via the browser, but must have two dedicated User Scripts to make it work how I want.
So no most users that find this annoying, have long ago given up telling MS, why should they you never listen.
You jump straight to LCD defence, we never ask you to change "Default", just give us a choice, that only we see.

User setting to display absolute times was added to  GitLab 14.1 (July 2021) two years ago, so no excuses accepted now
GitLab displays relative times (for example, 30 minutes ago) in a lot of places.
You can now change your user profile preferences to display absolute times instead, for example, ‘May 18, 2021, 3:57 PM’.
Absolute times respect your browser settings and format dates and times based on your preferred locales, for example, British English over US English.
This new display option gives more information at a glance for users that need it for workflows like correlating actions in GitLab to external systems.

**Comment by ICEknigh7** [comment]
Needed to quickly check the exact moment of a submission on my phone and was met with "last week".

Whose idea was this again?

**Comment by ICEknigh7** [comment]
Needed to quickly check the exact date of a PR on my phone and was met with "last week".

How useful. 😒

**Comment by henriquemattos** [comment]
The management of date and time in GitHub is somewhat confusing. And I agree with the request of this Issue that would be good (or better) to have a timestamp instead of "X days ago", especially on the PR's commit history, where the date is used as group header for the commits.

When you take a look at how the PR's list are displayed, it gets even more confusing.

In the repository @opauth/facebook, look at it:
<img width="1255" alt="Screenshot 2023-09-08 at 11 07 37" src="https://github.com/desktop/desktop/assets/2782214/8c1022de-b7b6-42b1-847a-e0f55d1ddb96">

It's not clear what "Newest" mean for sorting, as we have PR's `closed on Apr 5, 2017` before one `closed on Jul 19,  2018`. And one `closed two weeks ago` (which was `Aug 22, 2023`) after one `closed on Aug 9`.

With that said, I wanted to take a screenshot of a commit list in a PR with a timestamp, WHICH GITHUB OFFERS AS TITLE ATTRIBUTE, for every commit, but I cannot:
<img width="1299" alt="Screenshot 2023-09-08 at 11 11 37" src="https://github.com/desktop/desktop/assets/2782214/e11b7183-ff73-4fec-94aa-afea64eabd68">

Therefore I'm imagining, like @UhuruNUru, @zjkuang and @shamilovtim, how difficult could it be to introduce a configuration setting that lets the user decide how to display the date.

@billygriffin, please reconsider this request not only for GitHub desktop, but to the web and mobile version too.

Kind regards,
Henrique

**Comment by pierrevano** [comment]
How is that possible to display _2 years ago_ when not even a full year has passed since the commit has been pushed?
![Capture d’écran 2024-01-04 à 23 52 59](https://github.com/desktop/desktop/assets/1529169/bbc295cc-ef61-4fdf-8c5b-b73b095dc6b0)
Link for ref: https://github.com/pierrevano/whatson/commits/main/.gitignore

**Comment by nekoniaow** [comment]
> this has been a longstanding GitHub convention that's mirrored on issues, PRs, commits,

Is there a convincing usability basis to that convention? And what damage would existing users incur if the original commit information was displayed instead?
If there are on both counts, then indeed change should indeed be considered carefully but I struggle to think of any.

> and diverging from that isn't something we're keen on doing unless there's widespread agreement that it's a good choice.

Where should we expect such an agreement to be collected?

> So I'm going to close this to indicate that this isn't something we intend to change, but really appreciate you sharing your perspective!

Could you provide the arguments behind the choice of a relative date, which usability and information wise, is an extremely low granularity, imprecise and muddy piece of information?
People do infer this information directly from the direct date instantly so why this would be preferred to the _original commit information_ is very surprising.

Display of the date should at the very least be provided as an option, both for desktop and the website.

It seems unlikely that both the desktop software and website do not rely on a dedicated date display function to provide the actual string for display. Giving this function an additional boolean relative/absolute parameter seems perfectly within reach if the information architecture of the software is reasonably designed.

**Comment by shamilovtim** [comment]
@steveward looks like a lot of people are passionate about your software and want this old issue of mine reopened for both the website and the desktop app. what do you think?

**Comment by antonydandrea** [comment]
Why is this even an argument? Seeing the date is infinitely more useful and mobile doesn't have hover functionality! I'm coming across this issue all of the time

**Comment by Alokkumar8** [comment]
date should be default. im facing this issue too. i wanted to see commit of specific date but i just get 2 months ago. now how the hell do i find commit of 13 may from '2 months ago'

**Comment by arienshibani** [comment]
> Isn't something we're keen on doing unless there's widespread agreement that it's a good choice.

We **literally** have widespread agreement that it's a good choice to show timestamps. Please fix...

**Comment by aterbo** [comment]
Can you please reopen this issue?

**Comment by HughWarrington** [comment]
Here is yet another more-or-less dupe of this issue, filed independently, and with its own 31 upvotes: #17702.

> diverging from that isn't something we're keen on doing unless there's widespread agreement that it's a good choice

Perhaps now is an appropriate time to review whether there is sufficient evidence of support for this improvement?

**Comment by steelbytes** [comment]
apparently us programmers are too dumb to handle accurate information so github dumbs it down for us.

**Comment by antonydandrea** [comment]
> apparently us programmers are too dumb to handle accurate information so github dumbs it down for us.

This is what I don't understand the most. In our field of work, it is surely more preferable to have the precise date and time

**Comment by quasiDigi** [comment]
Super annoying, in some cases, I would even like to have the option to see all the timestamps (date + time) at once. Atm, we need to roll-over the commit times to be able to see them individually.

**Comment by mhswtf** [comment]
I just want to throw in my support for this issue. I very often need to find out which commits were made on a specific date. It is absolutely tedious and unnecessary to hover over relative day numbers, or do math to figure it out, or even worse, find a date amongst 100's of "2 months ago" commits. 
I don't understand why this is not just the standard. You could even show both, I would be fine with that!

Edit: Oh and by the way, the "x days ago" is based on 24 hour intervals i guess, which means that, e.g. "5 days ago" and "6 days ago" can be the same date, which is also very annoying. 
The reverse is also true btw. "5 days ago" will span 2 dates, depending on which time of day I'm viewing, so now I need to hover over each to find out what the last commit on a specific date was.

**Comment by geoffmeyers** [comment]
found this issue while trying to google my way around how to get the real timestamps in the website UI.  in a site this large, multiply one user by a hundred or even a thousand.  

also, i guess i have to go back to a terminal to actually find the lines i want because i can't even search for "days ago" -- they've overloaded the search function.  to be perfectly clear, as an end user, this is an anti-pattern and a little obnoxious.

**Comment by ICEknigh7** [comment]
@billygriffin Why did you close this as "completed"?

**Comment by pauladkisson** [comment]
Commenting to add my support: commits should be labeled with time and date.

**Comment by mrneont** [comment]
I agree that adding more clear, precise time and date would be useful.  

If there didn't seem like widespread support for this functionality previously (which was the reason given for closing this issue without addressing the valid need), it is that people didn't know it existed yet.  There seem like a lot of programmers here asking for it...

**Comment by gbmarc1** [comment]
I agree. I am struggling right now at finding merged PRs between specific date. But I can't see that in the UI.

**Comment by folterj** [comment]
Github Desktop is now my favourite tool over SourceTree, mainly due to persistent credential issues in the latter.
Displaying an absolute date is infinitely more informative than 'X days ago'. Please name one argument how relative days would be more informative.
And it gets even worse. After 29 days, it says 'last month', so then you can't even calculate what date that may have been.
Please stop this madness, and the argument 'we've always done it this way so we can't change it'.

**Comment by shamilovtim** [comment]
I got bit by this the other day again. Don't understand the stubbornness.

**Comment by ICEknigh7** [comment]
> We haven't heard from many people that the specific date is a super important piece of information to know for a commit that's more than a couple days old, and generally we try to only elevate the most broadly agreed upon important information. So given that if you want that extra bit of information there's a way to do so, I'm inclined to leave it as is for now, but we're always open to revisiting if it becomes obvious that this is causing problems for a broad cross-section of users. Thanks again!

@billygriffin Are all these people above enough?

**Comment by StornWhite** [comment]
Pushing updates to production, the question is what PRs have been merged since the last push.  Seems like this question could be solved with...  computer technology??  I think knowing the date and time that a PR is merged would be technically feasible if the product managers would just get out of the way.

**Comment by MrBryan** [comment]
Please switch to precise date for comments! super annoying trying to trace back when an issue changed etc

**Comment by positiveVibes4all** [comment]
BUMP! 

Why would the development team be so defensive on showing actual dates or at least a user setting on how they like to see the data. Looking through historical data without actual dates is quite a hindrance IMO.

**Comment by AndrewJayStudio** [comment]
I would also like to show my support to display full date information instead of "X time ago". Just now I needed to see when the first commit was made in a branch, but I was not at my desk to check. Hoping to use the mobile app, I checked to see all it says is "2 months ago". Is that the start of the month? The middle? The end? It makes a big difference if it's 32 days vs 60 days. And on mobile there is no possible way to display the exact date. Hover is not triggered, long pressing does nothing, and nothing available in settings. I will now have to delay my response until I can get back to my desk. Please fix this, we are programmers, not social media viewers.

**Comment by HughWarrington** [comment]
> We haven't heard from many people that the specific date is a super important piece of information to know for a commit that's more than a couple days old, and generally we try to only elevate the most broadly agreed upon important information.

@billygriffin could it be time to review the evidence? It's been a few years and there are hundreds of upvotes and comments in support of this change across this ticket and its web of linked duplicates: #5395, #9147, #14611, #17456, #17690, #17702, #17828, #17976, #18136, #18273, #18442, #18443, #18959, #19154, #19469, #19549 and probably others.

**Comment by rtapella** [comment]
Why not consider how that information is being used. What evidence does the GitHub team have that the relative dates are useful? In what context?

it almost seems like the people making this decision:
- have not bothered trying to get evidence about the right way to display this information (which is fine… priorities)
- Are not actually developing software, and therefore have no personal experience trying to consume this information (in which case the community raising this issue for years and offering a clear solution to a very well bounded problem should probably be heavily weighted)

The pain created by treating a commit history like my social network posts is high. It is obvious to anyone doing software development that hiding (or progressively disclosing) the real time stamps makes consumption of that information difficult and inefficient. I have yet to see a single person support the current approach on its merits.

**Comment by cocoelacanth** [comment]
I personally find the relative timestamps very unhelpful, especially with the rather aggressive upward rounding that GitHub tends to do.

Here are a couple of examples:
![image](https://github.com/user-attachments/assets/94ea7eaa-27bb-4061-9a6c-0bfb2f827864)

![image](https://github.com/user-attachments/assets/1b832fef-756b-41d5-bcdc-c1c3c97a98ab)

As of December 21st, 2024, neither of these timestamps are correct, nor will they be correct for another two weeks... at which point I wouldn't be surprised to see _different_ incorrect numbers in place of these ones.

This is illogical even compared to most other implementations of relative timestamps; the typical method is to round _down_ to the nearest unit. If I see "3 years ago," I'm naturally going to assume that it has been _**at least**_ three years since then.

**Comment by quickfoxcreative** [comment]
> The pain created by treating a commit history like my social network posts is high. It is obvious to anyone doing software development that hiding (or progressively disclosing) the real time stamps makes consumption of that information difficult and inefficient. I have yet to see a single person support the current approach on its merits.

I completely agree with this . I often go back to the git history for reporting what I've done on a given day, which would be much easier if there was an actual date rather than this x-days ago format. There are a ton of benefits to having an exact date, and just like everyone else on here, I'm really struggling to see any benefit of the way things currently are. Please change this.

**Comment by ipsi-apant** [comment]
I believe the person who closed this issue already left in 2022. Referenced from his github profile. I think posting on this issue wouldn't get noticed to the concern team.

**Comment by ICEknigh7** [comment]
Somebody @ an active dev please.

**Comment by HughWarrington** [comment]
I imagine the devs don't have time to pay attention to closed tickets. Of the huge list of duplicates I compiled above, only #14611 is still open so you could try nagging there. Or perhaps make a brand new ticket, since #14611 is a flawed report in my opinion as it asks for several different things at once in a vague way.

**Comment by antonydandrea** [comment]
I gave up waiting and built my own Chrome and Firefox extension to do it for me. I'll make public at some point. Doesn't solve problem on mobile which is where the issue is most apparent since you can not do hover.

**Comment by ICEknigh7** [comment]
> I imagine the devs don't have time to pay attention to closed tickets.

They should receive the notifications anyway.

**Comment by bartyushenkocarlo** [comment]
as for me that should be a settings, as for some users exact dates is not needed - and for others it's the only matters.

**Comment by gbmarc1** [comment]
Hello Folks, 
I discovered that you can hover on the "agos" and see the timestamps!

![Image](https://github.com/user-attachments/assets/29bea626-4973-4bfb-a20e-cfc7e6896a52)

**Comment by ICEknigh7** [comment]
> Hello Folks, I discovered that you can hover on the "agos" and see the timestamps!


@gbmarc1 How do you hover on mobile

**Comment by jangorecki** [comment]
@niik please re-open. There is definitely agreement on desired behaviour here.

**Comment by quasiDigi** [comment]
> > Hello Folks, I discovered that you can hover on the "agos" and see the timestamps!
> 
> [@gbmarc1](https://github.com/gbmarc1) How do you hover on mobile

Also, as someone said before (here or somewhere else), it's not a clear overview, as you can only check one at the time, AND it's cumbersome.

**Comment by jangorecki** [comment]
> > > Hello Folks, I discovered that you can hover on the "agos" and see the timestamps!
> > 
> > 
> > [@gbmarc1](https://github.com/gbmarc1) How do you hover on mobile
> 
> Also, as someone said before (here or somewhere else), it's not a clear overview, as you can only check one at the time, AND it's cumbersome.

More importantly, as said before, it doesn't work on touch screen devices where there is no way to hover.

**Comment by slw07g** [comment]
Maybe the path forward is for paying Github customers to escalate this through Github support.

**Comment by parkerroan** [comment]
I would prefer this option as well. Frustrating to be browsing releases to see if any correspond to the date of an incident and only see relative dates.

**Comment by sliedes** [comment]
Here's a use case for you. I was asked if an issue I filed "2 months ago" is still relevant. I seem to remember that there was a commit fixing it shortly after I filed it. At least I can see in my mailbox when I filed the issue even if GitHub hides it from me. Now,

1) how can I figure out which commits were made shortly after September 15?

2) How useful are these timestamps really?

![Image](https://github.com/user-attachments/assets/9b9757ee-38b9-4804-a9e5-d7beb046322b)

**Comment by jsmcortina** [comment]
Use case for me was to work out when a branch began so I could locally create the diff to the first commit. Knowing that the branch began "two weeks ago" isn't helpful to me. The hover did work, but I agree with other users here that I'd prefer to see the actual date/time normally.

**Comment by HughWarrington** [comment]
<img width="1417" height="265" alt="Image" src="https://github.com/user-attachments/assets/5311addb-64da-4f6e-b937-64ca9228a7f3" />

Maybe things have changed since Billy's comment 5 years ago (or should I say 6 years ago?)

**Comment by beadon** [comment]
comments have changed, but the github commit history for the repo still has this "approximate" garbage.
