### ISSUE TITLE
Seting to hide recent repositories

### ISSUE THREAD

**Issue by CharlesStover** [desktop/desktop#9156]
### Describe the feature or problem you’d like to solve

When I open the repositories dropdown, the top of the list ("recent") is distracting and useless to me. I have dozens of repositories that are each updated frequently (often daily). Every so often, I click down the list on each repository in order to "pull latest" to keep my local copies up to date. When I open the repository list, I look for the ⬇ icon that signifies that an update to this repository exists. The top repositories are the first thing I see, but they are duplicates of the repositories below them. I often find myself clicking a recent repository because it needs updating, clicking pull latest, then clicking that same repository not on the recent list, because that duplicate entry also has the ⬇ icon next to it while the updating is pulling.

This is difficult to gauge which repositories need updating.

Given I work in so many repositories, the recent list is always arbitrary and useless. I never look to it to find a repository. It just gets in the way, and it causes the aforementioned problem.

### Proposed solution

A setting to hide recent from the list

### Additional context

N/A

**Comment by tierninho** [comment]
@CharlesStover Thank you for the feedback. This is a relatively new feature https://github.com/desktop/desktop/issues/7132 and any toggle or setting to hide it is not intended at this point. We will take you suggestion into consideration for the next iteration of this area.

**Comment by IdanAdar** [comment]
1+ years later, we should have this setting. It's very annoying. @tierninho

**Comment by igroglaz** [comment]
Please add this tiny thingy

**Comment by fritze2** [comment]
This is very annoying.

**Comment by maheshbasnet089** [comment]
Is it implemented?

**Comment by serg3y** [comment]
Its 2023:
+10
please...

**Comment by quisido** [comment]
# Baffling, enraging, bedeviling...

>I'm going to close this for now as something we don't intend to support.

It's been 2 years, and I'm still mad about this reply. Absolutely baffled that a service can receive so much negative feedback for a "feature" and _multiple_ pull requests to fix it with no downsides, just to tell users to shove it up their 🦋. Absolutely baffled.

It's been 3 years since this came out, and there have been non-stop feature _and_ pull requests to address it. How do you even respond to this at this point?

+10 will do nothing. There's already +100. They just close the PRs and the issues. It's like a 12-line fix!
