### ISSUE TITLE
Don't have write acces to own repository

### ISSUE THREAD

**Issue by Tjardok** [desktop/desktop#9158]
### Describe the bug

I want to push two commits to my Github repository. But i get the notification that i don't have write acces. How can i give myself write to my own repo?

### Version & OS
version 2.3.1

### Steps to reproduce the behavior

1. Go to current repo on Git
2. Click on 'push origin'
3. See error. 'it looks like you don't have write acces to tjardok/Darts etx'

### Expected behavior

to pushed it to my repo 

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by steveward** [comment]
Thanks for the report @Tjardok. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue. Thanks!

**Comment by Tjardok** [comment]
Hi Steve,

The problem is already solved, thanks anyway!

**Comment by joely-nelson** [comment]
What was the fix?
