### ISSUE TITLE
Resize layout problem with post welcome flow landing page

### ISSUE THREAD

**Issue by niik** [desktop/desktop#9175]
### Describe the bug

The post-welcome flow landing page on Windows doesn't respond as intended when being resized. Assuming this is related to #8791 or #8959 (i.e #8967).

Tentatively putting this in the 2.4 release as it appears to be a regression from what's on prod at the moment.

### Version & OS

Latest development build (452c89d0de300878e2320c5da7bdeb42e949d765). Windows 10 and macOS 10.15.3

### Steps to reproduce the behavior

1. Remove all repositories to get to the post-welcome flow landing page
2. Wait until the list of cloneable repositories has loaded
3. Select any repository from the list such that the blue clone button shows up at the bottom of the page

![image](https://user-images.githubusercontent.com/634063/75269892-f4937880-57f9-11ea-96be-74a2571d73a4.png)

4. Resize the application window

### Expected behavior

That the ProTip box as well as the clone button to be anchored toward the bottom of the view

![image](https://user-images.githubusercontent.com/634063/75269892-f4937880-57f9-11ea-96be-74a2571d73a4.png)

### Actual behavior

The clone button and the ProTip box are positioned outside of the bounds of the application Window.

![image](https://user-images.githubusercontent.com/634063/75269985-18ef5500-57fa-11ea-9bf7-62946fe2ecb7.png)

### Screenshots

![welcome-resize-bug](https://user-images.githubusercontent.com/634063/75270056-34f2f680-57fa-11ea-9332-a7236d2ae4d5.gif)

### Logs

N/A

**Comment by rafeca** [comment]
After looking at it for a bit I've found that this can get fixed by adding an `overflow: auto` property to the [`.filter-list-container` selector](https://github.com/desktop/desktop/blob/development/app/styles/ui/_filter-list.scss#L19-L22).

I'm going to try to find an alternative solution since I'd prefer to not touch the styling of `FilterList` that is used by many other components in the app (although I don't think that the change would be risky).
