### ISSUE TITLE
Stashed changes not shown if stashed via cli

### ISSUE THREAD

**Issue by vonas** [desktop/desktop#9195]
### Describe the bug

After having changed a few files and running `$ git stash` the changes disappear in GitHub Desktop (as expected), but the stash is not shown at the bottom (like usual, when you're switching branches). This is kind of an edge case, but for completeness's sake it might make sense to implement this.

### Version & OS

Version 2.3.1 on Windows 7 Home Premium

### Steps to reproduce the behavior

*See above*

### Expected behavior

Stash should be shown, even if it's not stashed by GitHub Desktop.

### Actual behavior

Stashed changes are not shown

### Additional context

Why I stashed my changes via cli you might ask?  
Because I couldn't rebase through GitHub Desktop, see #9192.

**Comment by billygriffin** [comment]
Hi @vonas, sorry you're running into a couple known limitations today. We chose not to surface stashes made from outside of Desktop because many people have old stashes, and stashes aren't inherently attached to branches in Git, whereas our implementation diverged from that somewhat.

You can workaround that by naming your stash using the same naming convention we use:

```
$ git stash push -m "!!GitHub_Desktop<my_branch_name>"
```
(being sure to include the `<` and `>` characters)

If you want to include untracked changes in your stash, you'll also need to stage them first or things might not work properly in Desktop.

Apologies again you're running into this, and since this was an explicit design choice I'm going to close this issue.

**Comment by vonas** [comment]
Thank you for the clarification.
