### ISSUE TITLE
Feature request: Pin to top your favorite repositories

### ISSUE THREAD

**Issue by JakubSteplowski** [desktop/desktop#9203]
### Describe the feature or problem you’d like to solve

Add ability to pin favorite repositories to top of the list.
I have 40+ repositories on my PC, I would like to pin to top a few of them to have them always at the beginning of the list.

### Proposed solution

The most used repositories are already in a separate group at the top of the list (but a limited amount), something similar could be done with only the repos you choose (maybe without limits?).

I've seen that other issues like this has been closed... would like to know why this feature seems not useful and if your plans changed.
Can't find any technical reason to not implement it, since something similar is already there.

**Comment by billygriffin** [comment]
@JakubSteplowski Thanks for the issue. You referenced the issues where this request has been closed - would you mind responding in those instead of creating a new issue. To make the feedback easier to digest in one place as we're considering whether we should reconsider decisions like that, it's best for it all to be there. Thanks.

**Comment by JimmyCushnie** [comment]
The issue in question is #8183
