### ISSUE TITLE
Need embedded git terminal like VS Code

### ISSUE THREAD

**Issue by gokulyc** [desktop/desktop#9215]
### Describe the bug

Feature Request

### Version & OS

Version 2.3.1

### Steps to reproduce the behavior

NA

### Expected behavior

A terminal similar in Visual Code

### Actual behavior

NA

### Screenshots

![image](https://user-images.githubusercontent.com/13468848/75872782-cb479d80-5e34-11ea-96b7-ff899318df3b.png)

### Logs

NA

**Comment by steveward** [comment]
Thanks for the feedback @gokulyc. We do not have any plans to implement a built-in command line tool directly into GitHub Desktop, so I am going to close this issue out. GitHub Desktop provides a few options to launch a command line directly from within the application, and the quickest way is to use the  'Control+`' shortcut. Thanks for using GitHub Desktop!

**Comment by haseeb-fmlx** [comment]
@steveward  i think we should review it since Git Kraken is already providing the functionality , it makes work easy, and there's nothing bad in getting it integrated, it will certainly improve the developer experience. Today i was search through the internet to find a tool that has an integrated terminal and was sad to know that Github Destop isnt providing one and became disappointed to know that there are no plans to get it integrated
