### ISSUE TITLE
Defining a Default Branch in app (for non-Github repos)

### ISSUE THREAD

**Issue by nlourenco-tsd** [desktop/desktop#9227]
### Describe the feature or problem you’d like to solve

I would like to define a default branch within Desktop without needing to have my repo up in Github.

### Proposed solution

Create a _Repository > Default Branch_ item in the context menu.

### Additional context

Users utilizing platforms other than Github will be able to define a default branch.

**Comment by tierninho** [comment]
@nlourenco-tsd  Thanks for the suggestion. Whenever you change the location to create a new repository or clone an existing repository, this value is remembered and persisted to local storage. We don't show this option as something explicit to change - we just automatically update this when it gets changed as part of your normal activities.

We already have this issue here https://github.com/desktop/desktop/issues/2106. Although closed, we are happy to revisit the enhancement should more users request it. Thanks for using Desktop!
