### ISSUE TITLE
unable to access(0x80092013)

### ISSUE THREAD

**Issue by byWindy** [desktop/desktop#9266]
### Describe the bug

自动更新到新版本之后，操作 Pull Origin 时会提示 unable to access(0x80092013)
![ZH3}A`AZ6 2AM`Z(GPAQ8B5](https://user-images.githubusercontent.com/16983677/76477647-fdfb2280-6440-11ea-94b6-ac04c4a75daf.png)

### Version & OS

Version : 2.3.1
OS : Win10

**Comment by tierninho** [comment]
@byWindy Thanks for the report and sorry it was failing for you. This error is usually caused by your network blocking the attempt by Windows to check the revocation status of a certificate, which then causes the whole operation to error. You can find a workaround for this issue here:

https://github.com/desktop/desktop/blob/master/docs/known-issues.md#certificate-revocation-check-fails---3326

**Comment by niik** [comment]
@byWindy Hey, thanks for opening this! We've just [recently shipped](https://github.com/desktop/desktop/pull/9188) support for detecting and dealing with this particular error to our [beta channel](https://github.com/desktop/desktop#beta-channel) and we'd be delighted if you'd consider installing our beta version and letting us know if that solves your problem.

See our [README](https://github.com/desktop/desktop#beta-channel) for information on how to download and install the beta channel.
