### ISSUE TITLE
Show Current Branch in Repository Dropdown

### ISSUE THREAD

**Issue by JosephTLyons** [desktop/desktop#9281]
### Describe the feature

I would love it is Desktop would show what branch a project is in in the repository dropdown list.  At my work, we build a piece of software that has multiple repositories with identical branches and requires me to make sure I'm on the same branch for each repository.  It would save me a lot of time to be able to just look at the repository dropdown to see which branch each repository was on versus having to actually switch to each repository to find out.

**Comment by AndreiMaga** [comment]
That sounds good but why are you guys not using submodules for this kind of stuff?

**Comment by niik** [comment]
Hi @JosephTLyons, I'm doing a bit of issue cleanup and this feature has been requested before in https://github.com/desktop/desktop/issues/8158 so I'm going to close this issue in favor of that. That issue is currently closed as we haven't prioritized it but please add a 👍 reaction to that issue, we use that and other factors when we decide what work to prioritize.
