### ISSUE TITLE
Import/Export projects or Sync projects

### ISSUE THREAD

**Issue by RyKaj** [desktop/desktop#9295]
### Describe the feature or problem you’d like to solve
Is there a way we can import and export the all projects. I have two systems (office and personal) I would like to have both both systems updated with that projects I have

### Proposed solution

1. Ability to Import/Export project
2. Use the Github account to centralize all projects to be sync on different systems

How will it benefit Desktop and its users?
Less reconfiguration and passing information through Slack or personal email.

**Comment by steveward** [comment]
@RyKaj thanks for contributing. The ability to sync all repositories has been previously requested in https://github.com/desktop/desktop/issues/2460 and https://github.com/desktop/desktop/issues/6482. 
 See this [comment](https://github.com/desktop/desktop/issues/6482#issuecomment-449604915) for our decision about not including this feature. 

It also isn't possible to clone all of the repositories associated with your current GitHub account -- we don't believe having to perform an initial clone of your repositories is a friction point when using GitHub Desktop.

You mentioned this point:

> How will it benefit Desktop and its users?
> Less reconfiguration and passing information through Slack or personal email.

Can you share what you are referring to? I'm not sure I understand the workflow you are using. 

I'm going to close this issue out since it is not something that we are planning on supporting, but please let me know if I can help with any questions you may have about using GitHub Desktop.
