### ISSUE TITLE
Github denied access from Proxy Server, Error 407

### ISSUE THREAD

**Issue by austinpolin** [desktop/desktop#9310]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by austinpolin** [comment]
Please assit rectify this ERROR.

**Comment by steveward** [comment]
Thanks for the report @austinpolin. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue. Thanks!

**Comment by lemon-0** [comment]
A

**Comment by austinpolin** [comment]
> Thanks for the report @austinpolin. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`.
> 
> The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue. Thanks!
-------------------------------------------
Below is the ERROR message.
[
![GitError](https://user-images.githubusercontent.com/12632545/77026086-84ce7300-69de-11ea-9236-d232453c4349.JPG)
](url)

**Comment by lemon-0** [comment]
Y

**Comment by steveward** [comment]
@austinpolin we have a [beta version](https://github.com/desktop/desktop#beta-channel) of GitHub Desktop available that has better support for proxies -- would you be willing to try downloading that to see if you are able to configure your proxy successfully? Let us know if you run into any issues.
