### ISSUE TITLE
Can be stage files on current branch

### ISSUE THREAD

**Issue by Quineone** [desktop/desktop#9325]
### Describe the feature or problem you’d like to solve

Want be able to  stage files on current branch

### Proposed solution

Make the pre-commit works correctly

### Additional context

1.Smartgit stage feature make it works when run `pre-commit: lint-staged`
2.Github Desktop no idea how to stage files on current branch

**Comment by tierninho** [comment]
@Quineone Thank you for reaching out. 

Currently, the only way to stage files on the current branch is to:

1. Make you changes to files
2. Navigate to another branch. 
3. Upon doing so, you will be asked to stage the files on the current branch or take them to the new branch. 

You may change the preferences for step 3 in the GitHub Desktop > Preferences (Mac) or File > Options (Windows) menu.

As for `lint-staged`, I imagine you are trying to stage the files on the current branch so you can run the tool and look for linting errors. Let us know if this does not work once you have resolved above.

**Comment by Quineone** [comment]
@tierninho Thank you for your reply.
1.Yes, I know we can stashed files when we switch to a new branch.
 
2. And as for `lint-staged`,  yes, you got what I want, but it does not work when we stashed files on the current branch, because when you run command `yarn pre-commit` in the vscode, then there will be `No staged files found.`, So for now, I have to use the another tool( `smartgit`) to stage the files on current branch.

**Comment by tierninho** [comment]
Thank you for confirming your use case. My apologies, I misread the initial report as "stashing" instead of "staging".  

Is this a feature request or are you reporting a bug?

**Comment by Quineone** [comment]
@tierninho , I think this should be a feature request, nice to have. Thank you ^-^.

**Comment by billygriffin** [comment]
Hi @Quineone - unfortunately with any design choice there are tradeoffs, and with our decision to abstract the concept of "staging files" in Desktop, it sounds like maybe your pre-commit hooks aren't working properly. Introducing the concept of staging files isn't something we're considering because overall the feedback has been very positive about our approach, and I'm sorry it falls down for you. If you want to share more detail about the pre-commit hooks that aren't working properly and we can think about ways we can solve the problem without a fundamental redesign of the app, we're open to looking into that. Thanks!
