### ISSUE TITLE
Unity not pull with github

### ISSUE THREAD

**Issue by Idreesepic** [desktop/desktop#9357]
### Describe the bug
Error pulling 
Failed pull 
### Version & OS
Android 10
Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Steps to reproduce the behavior

1. Go to '...' add file
2. Click on '....' commit
3. Scroll down to '....' loading
4. See error fail due to master pull

### Expected behavior
May b large size 168MB

### Actual behavior
Again guidance githube
A clear and concise description of what actually happened.

### Screenshots
Nil
Add screenshots to help explain your problem, if applicable.

### Logs
Nil
Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

### Additional context
No

**Comment by steveward** [comment]
@Idreesepic thanks for the report. Can you share a few more details about the issues you are experiencing with GitHub Desktop? Are you running into an error when attempting to push due to a large file in your repository.

Could you also upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by tierninho** [comment]
@Idreesepic As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
