### ISSUE TITLE
I can't changed a branch

### ISSUE THREAD

**Issue by Vanesardgz** [desktop/desktop#9363]
Hi,

Last week i've upload a Branch with name NVL-CSS-P3a, and it's appear an message about an error, but when i pass the cursor over the signal doesn't show a message where i can read what's happening, and i can't upload another branch because appear one sentence who say that before to upload another branch, i have to fix the problem. 

Could you say ne what is goin on? I need to fix it becase like i said, i can't upload anything until i fixed the problema

![Práctica NVL-CSS -P3a](https://user-images.githubusercontent.com/62300013/77663855-d0a08f80-6f7d-11ea-9fb4-45fccfac561c.JPG)

**Comment by steveward** [comment]
Thanks for the report @Vanesardgz. It looks like you ran into merge conflicts when restoring a stash. The merge conflicts are indicated by the `<<<<` `=====` `>>>>` markers. You can find GitHub's guide for how to work through merge conflicts here (you can use GitHub Desktop instead of the command line):

https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/resolving-a-merge-conflict-using-the-command-line

If you have any questions about this I'd be happy to help.
