### ISSUE TITLE
Feature Suggestion: Make it possible to make a release from the program

### ISSUE THREAD

**Issue by AwesomeKalin** [desktop/desktop#9395]
I think it would be a nice feature to make a release straight from the app, instead of having to go onto Github and upload the release.

**Comment by billygriffin** [comment]
Hi @AwesomeKalin, thanks for the issue! We're currently looking at creating and viewing tags in #4829 and the use case for that is almost universally related to releases. Would having the ability to tag a commit make this possible for you, or are you looking for something more fully featured for releases specifically?

**Comment by AwesomeKalin** [comment]
I mean to make a release for your project for example, as you would make on this page: https://github.com/desktop/desktop/releases

**Comment by billygriffin** [comment]
@AwesomeKalin Thanks! May I ask what your current process is for creating releases? Do you push a release tag, or how do you do this currently? As much detail as you're open to sharing would be helpful for us to think through the overlap with #4829.

**Comment by AwesomeKalin** [comment]
Currently, I goto my GitHub repository and fill in all the information required an upload my files. I would like to do this on GitHub Desktop instead of having to go to the repository.

**Comment by steveward** [comment]
I'm going to close this out as it's not likely something we'll attempt to duplicate in the near-term in the app due to the number of options that are present in creating a release on github.com (like asset uploads). Creating tags in GitHub Desktop and then quickly jumping to the browser to create a release is likely going to be the best workflow for the time being.
