### ISSUE TITLE
Add place to store tags in desktop

### ISSUE THREAD

**Issue by outofambit** [desktop/desktop#9425]
(not persistently, just in app state and caches)

we currently don't parse or store tags anywhere in desktop

_____
part of work for #9424

**Comment by rafeca** [comment]
Something worth to mention is that we're going to store the tags as inside the commit model (done in #9383).

We could additionally store somewhere the list of all the repository tags (along with their metadata), the same way that we do for branches, but it seems like we're not going to show anywhere all the repo tags (at least for the first iteration) so that's not going to be necessary.

(maybe that's obvious, just wanted to point it out 😅).
