### ISSUE TITLE
i hosted html file , but could'nt connect web server

### ISSUE THREAD

**Issue by rays5** [desktop/desktop#9447]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by Krissf1971** [comment]
- [ ] 

> ### Describe the bug
> A clear and concise description of what the bug is.
> 
> ### Version & OS
> Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.
> 
> ### Steps to reproduce the behavior
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> ### Expected behavior
> A clear and concise description of what you expected to happen.
> 
> ### Actual behavior
> A clear and concise description of what actually happened.
> 
> ### Screenshots
> Add screenshots to help explain your problem, if applicable.
> 
> ### Logs
> Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.
> 
> ### Additional context
> Add any other context about the problem here.

**Comment by tierninho** [comment]
@rays5 thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
