### ISSUE TITLE
Allow Changing Git Config Per Repository

### ISSUE THREAD

**Issue by say25** [desktop/desktop#9449]
### Describe the feature or problem you’d like to solve

I have multiple git configurations (due to multiple git accounts/configs).
 
I have a global default one of:

```bash
git config --global user.name Steven Yeh
git config --global user.name Steven.Yeh@vauto.com
```

and this account my public one

```bash
git config user.name say25
git config user.email say25@cornell.edu
```

### Proposed solution

Add a tab in the repository setting menu to change user.name and user.email without a command line.

![repo-settings](https://user-images.githubusercontent.com/7467062/78412732-11ca1c80-75da-11ea-8568-60eefec248b1.png)

#### Related 
#6534 - `Display better message when adding a repository with malformed .git/config`
#9255 - `2.3.2 beta 4 changed my git name to my github username`

**Comment by say25** [comment]
I assigned myself for now as I am willing to work on the above proposed solution assuming @billygriffin and @ampinsk agree with the idea.

**Comment by outofambit** [comment]
@say25 and I chatted about this on Friday offline. The underlying problem here (as I see it) is that if a user has different git identities for different projects (day job vs side projects for example) there's no way to manage that in desktop currently. You get one identity setting that we apply everywhere via their global git config.

A bigger version of this feature could be Desktop setting your git identity based on your GitHub account used to push/pull/clone a repo, but that's prone to Desktop overwriting manual user configuration. This low-weight solution lets users manually manage their git identity on a per-repo case, and certainly doesn't preclude something more involved at a later point (if we want to do that someday).

**Comment by maxloh** [comment]
@outofambit Maybe you can add a checkbox for that, just like the "Keep me signed in" checkbox in login page of some websites.
