### ISSUE TITLE
Add copy link entry to the commit menu

### ISSUE THREAD

**Issue by feel-the-dz3n** [desktop/desktop#9454]
It would be useful to have this entry there:

![image](https://user-images.githubusercontent.com/25367511/78459653-406ff200-76c3-11ea-987f-9cdd73b33a15.png)

**Comment by osdeverr** [comment]
### **Y**_e_`s`

**Comment by feel-the-dz3n** [comment]
@tierninho 

Yes, you correctly understood what I want. 

Sometimes I need to share commit link with someone, so I have to click "View on GitHub" and copy link from a browser. Instead of this, me and other users could use "Copy GitHub link" menu entry. I believe this would help to speed the productivity of developers using GitHub Desktop.

**Comment by billygriffin** [comment]
Hi @feel-the-dz3n, thanks for the idea and I definitely understand where you're coming from. However, to my knowledge this is the first we've heard of this slowing people down. Since it's possible to get the link by the existing "View on GitHub" menu item, I think we'd need to hear from more than just a few users that not having this is slowing people down or causing frustration. I know that's not a great answer and we're definitely not opposed to revisiting, but just wanted to share my current thinking. Apologies, and thanks again for the issue.
