### ISSUE TITLE
Allow to disable progress bar in taskbar

### ISSUE THREAD

**Issue by vhashimotoo** [desktop/desktop#9489]
### Describe the feature or problem you’d like to solve

Desktop tries to pull/fetch things in the background when having very many repositories updates very frequently, the progress bar in the taskbar starts very frequently flashing.

### Proposed solution

Ability to disable progress bar in the taskbar, or choose the events for when that should be.

**Comment by tierninho** [comment]
@HashimotoYT Thanks for the suggestion. We are tracking this feature here https://github.com/desktop/desktop/issues/1128. Please follow along there.

**Comment by HashimotoYT** [comment]
@tierninho I'm don't want to disable background fetching, It's ok to have enabled for me. Here request to disable progress bar in taskbar fully, for any request (pull/fetch/push). Also, I think it's still showing for the current repository that also what's not very comfortable for me.

**Comment by tierninho** [comment]
Thank for the clarification. I reopened the issue for further commenting.

**Comment by say25** [comment]
I will say after updating to the latest beta, I noticed how often this was happening, kinda elevates #1128 IMHO.

**Comment by billygriffin** [comment]
@HashimotoYT Thanks for the feedback. Just to be clear, this is new since yesterday's beta release, correct? Just wanted to make sure this is related to https://github.com/desktop/desktop/pull/8587, which is what I suspect.

**Comment by say25** [comment]
@billygriffin you are correct

**Comment by outofambit** [comment]
My proposal here is to only use the task bar progress bar when the _currently selected_ repo is updating. This allows us to offer the signal for your current repo consistently, and avoids the rapid progressbar loop when the user has more than a couple repos in desktop

**Comment by say25** [comment]
@outofambit only using the task bar progress bar when the currently selected repo is updating makes sense to me

**Comment by billygriffin** [comment]
> My proposal here is to only use the task bar progress bar when the currently selected repo is updating
My biggest concern about this is that the feedback we've received is that you're seeing taskbar activity in the background even when you don't care about it. Unless I'm misunderstanding this, this background fetching for the current repo will still happen every 15 mins (if I recall correctly) as part of the background fetching process. So it wouldn't show up for as long as it does now, but the frequency wouldn't change, which strikes me as not likely solving the problem of it being annoying and separate from the original problem. 

The original problem, as I understand it, is that you're waiting for something to happen and so you leave Desktop, but you want to see when the current operation completed. So this would certainly do that, but it would also show the progress bar at a bunch of other times repeatedly when you're not interacting with Desktop at all.

It's certainly possible I'm not understanding it properly, But if I am, unless it can be scoped to operations that were started *when someone already had Desktop focused*, I'd prefer to just remove this functionality since it is so noisy.
