### ISSUE TITLE
Can't create branch names starting with `[`

### ISSUE THREAD

**Issue by gabbpuy** [desktop/desktop#9510]
### Describe the bug

Can't create branch names starting with `[`

### Version & OS

Version 2.4.0
Mac OSX

### Steps to reproduce the behavior

1. Go to Create New Branch
2. Try to create a branch name `[BUG-500] Some Description`
3. See text says 'Will be created as `BUG-500]-Some-Description`
4. Enter infinite number of starting `[` and see no change to text

### Expected behavior
Branch names starting with `[` should be created

### Actual behavior
Branch names starting with `[` are not created, the text is not cosmetic.

### Screenshots

![image](https://user-images.githubusercontent.com/13398367/79168435-be588b00-7d9e-11ea-8581-a30845e824f4.png)

![image](https://user-images.githubusercontent.com/13398367/79168456-cf090100-7d9e-11ea-9afa-b39873131efd.png)

### Logs

N/A

### Additional context

Sad-face with poorly named branches

![image](https://user-images.githubusercontent.com/13398367/79168485-e516c180-7d9e-11ea-9a95-3bfbf4cf17f5.png)

**Comment by billygriffin** [comment]
Hi @gabbpuy, thanks for the issue. Unfortunately this is a limitation with Git itself in that it does not allow certain characters (see this [Stack Overflow](https://stackoverflow.com/questions/12093748/how-do-i-check-for-valid-git-branch-names) question), so the design of Desktop warns you when you use one of those characters and displays what the branch will be created as instead. Since we're not able to solve this issue, I'm going to close it, but hopefully that explains why that's the case.

**Comment by gabbpuy** [comment]
Huh. Well I feel slightly foolish now :-)

Thanks Billy.

**Comment by billygriffin** [comment]
No worries! Git is confusing. 😄
