### ISSUE TITLE
Getting the error while creating a clone fatal: unable to access 'https://github.com/docker/doodle.git/': SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by Atif-byte** [desktop/desktop#9511]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by steveward** [comment]
@Atif-byte this error can be caused by a few things -- are you running any security software on your machine that could be interfering with your connection to GitHub? Some security software will man-in-the-middle your connection. 

You can also check out this issue thread https://github.com/desktop/desktop/issues/3684 for some specific steps to debug this issue. To check if there are any configuration issues on your machine it would be helpful if you could open up Git for Windows and run the following command:

`git config -l --show-origin`

Let me know the output of that.

**Comment by Atif-byte** [comment]
Hi,

PFB the required output

C:\>git config -l --show-origin
file:C:/Program Files/Git/etc/gitconfig diff.astextplain.textconv=astextplain
file:C:/Program Files/Git/etc/gitconfig filter.lfs.clean=git-lfs clean -- %f
file:C:/Program Files/Git/etc/gitconfig filter.lfs.smudge=git-lfs smudge -- %f
file:C:/Program Files/Git/etc/gitconfig filter.lfs.process=git-lfs filter-process
file:C:/Program Files/Git/etc/gitconfig filter.lfs.required=true
file:C:/Program Files/Git/etc/gitconfig http.sslbackend=openssl
file:C:/Program Files/Git/etc/gitconfig http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
file:C:/Program Files/Git/etc/gitconfig core.autocrlf=true
file:C:/Program Files/Git/etc/gitconfig core.fscache=true
file:C:/Program Files/Git/etc/gitconfig core.symlinks=false
file:C:/Program Files/Git/etc/gitconfig credential.helper=manager

**Comment by steveward** [comment]
@Atif-byte it looks like you have `http.sslbackend` set to `openssl`, which means GitHub Desktop isn't using the Windows certificate store. Running the command `git config --global http.sslBackend schannel` should resolve this issue and allow your stored certificate to be picked up. Let me know if that doesn't get things working.

**Comment by Atif-byte** [comment]
Thanks a lot Steve the issue has been fixed. Have a great day ahead

**Comment by DannyCKing** [comment]
I love 5 second fixes.  Thanks!

**Comment by AcerousKylin** [comment]
Really helpful, thanks!
