### ISSUE TITLE
[Request] Allow option to automatically download repos into chosenfolder/author/project instead of chosenfolder/project

### ISSUE THREAD

**Issue by MostHated** [desktop/desktop#9570]
Hello,
I would very much like to request that when downloading projects, have the ability to set an option so that by default when you download a repo via the link that auto opens desktop, to download to chosenfolder/author/project instead of chosenfolder/project similar to how Golang's "go get" structure works. This would greatly help organization out of the box since multiple projects from the same author would be in the same folder, as well as eliminate any naming conflicts with simplistically named projects, such as "gallery" or "tools" since each author name is unique. 

Thanks,
-MH

**Comment by rafeca** [comment]
Thanks for the suggestion @MostHated ! 😃 

Having the repository owner as part of the path of the cloned project has been asked before in https://github.com/desktop/desktop/issues/8461 . We haven't seen many people requesting this change though, so right now we're not considering implementing it (we try to keep the configuration settings of Desktop as minimal as possible to not overwhelm our users).

Anyways, feel free to subscribe to https://github.com/desktop/desktop/issues/8461 to get updates, since we may revisit this in the future as we learn more from how people use Desktop.

I'm going to close this issue in favor of https://github.com/desktop/desktop/issues/8461
