### ISSUE TITLE
Automatically change git name and email on account switching

### ISSUE THREAD

**Issue by maxloh** [desktop/desktop#9571]
### Describe the feature or problem you’d like to solve

I have two accounts, one for personal hobby projects and one for the college assignments.

I switch between two accounts frequently and I need to update git info every time I switch accounts.

### Proposed solution

When user sign in for a new account, prompt a confirmation dialog to let user choose if they want to update git info alongside the login.

**Comment by rafeca** [comment]
Hey @maxloh ! Thanks for the suggestion! We have this issue to allow configuring different git dentities depending on the project: https://github.com/desktop/desktop/issues/9449

Would  the solution suggested in #9449 help you? I'm asking because your suggested approach seems a bit different than the one described in #9449. From what I understand you have two completely different GitHub accounts right?

Anyways, I suggest commenting in #9449 exposing your use case so we can find a solution that works for as many people as possible. I'm going to close this issue, thanks again for filling it!
