### ISSUE TITLE
Can't push the changes to github enterprise account 

### ISSUE THREAD

**Issue by varsharani09** [desktop/desktop#9583]
I can't push the changes to my github enterprise account

**Comment by steveward** [comment]
Thanks for reaching out @varsharani09!

Would you mind filling out the rest of the issue template so that we can better understand what is causing the problem you are experiencing? Without that information it will be difficult to help you further. It would especially be helpful if you could upload the log file from GitHub Desktop, which will give more details about the specific error you are seeing. 

To access the log files go to the  menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`. The log files are created daily -- please send over a log file as an attachment from a day where you experienced the issue

**Comment by matjue85** [comment]
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>404 - File or directory not found.</title>
<style type="text/css">
