### ISSUE TITLE
how to edit the repository

### ISSUE THREAD

**Issue by fareeha904** [desktop/desktop#9603]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by steveward** [comment]
@fareeha904 it would be helpful if you could fill out the template fully so that we could better understand your question. 

It is not possible to edit a repository directly in GitHub Desktop, but you can launch an [editor of your choice](https://github.com/desktop/desktop/blob/development/docs/technical/editor-integration.md) directly from the file menu by going to `Repository` > `Open in <external editor>`. If you are interested in editing files directly on GitHub please [refer to this article](https://help.github.com/en/github/managing-files-in-a-repository/editing-files-in-your-repository).
