### ISSUE TITLE
Cant push to github

### ISSUE THREAD

**Issue by EmpireofZakuul** [desktop/desktop#9607]
### Describe the bug

This is the bug I am receiving when I try to push to Github.
warning: url has no scheme: helperselector
fatal: credential url cannot be parsed: helperselector

I am using Github desktop and the version is 2.4.2. I was using the version before for about a day and it was working perfectly and after it was updated it won't allow me to push to GitHub now.

I am using this on windows 10.

sorry I am new to this.

I looked at the form for this bug and people were saying to go into the gitconfig file and change stuff. not sure what I am meant to do.

under the gitconfig file, this I what I have:

[credential "helperselector"]
	selected = <no helper>
[difftool "sourcetree"]
	cmd = '' \"$LOCAL\" \"$REMOTE\"
[mergetool "sourcetree"]
	cmd = "'' "
	trustExitCode = true
[filter "lfs"]
	clean = git-lfs clean -- %f
	smudge = git-lfs smudge -- %f
	process = git-lfs filter-process
	required = true

not sure what I have to change 

thanks

**Comment by rafeca** [comment]
@EmpireofZakuul thanks for filling this report, the current investigation of this bug is being discussed in https://github.com/desktop/desktop/issues/9597. This is related to a `git` issue and the `git` core team is working hard to fix it. Once there's a fix we'll update GitHub Desktop.

In the meantime, you can fix it in your machine by manually editing the `gitconfig file` (the one you pasted). You just need to delete the following lines from that file:

```
[credential "helperselector"]
selected =
```

I hope this helps!
