### ISSUE TITLE
file duplicate with case difference on same file

### ISSUE THREAD

**Issue by serfend** [desktop/desktop#9626]
### Version & OS 
Version 2.4.2 in win10 1903 

### Steps to reproduce the behavior

1. Create a repository and create a file such as 'Base.Vue'
2. Save file
3. See error

### Expected behavior

it should only one file for the file is just one 

### Actual behavior

see pic follow

### Screenshots

![https://github.com/serfend/Util.Static.OnlyForRead/blob/master/20200426@github_desktop.issue/20200426183915.jpg?raw=true](https://github.com/serfend/Util.Static.OnlyForRead/blob/master/20200426@github_desktop.issue/20200426183915.jpg?raw=true)

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by tierninho** [comment]
@serfend Thank you for the issue. Please share you logs if possible so we may have more information on the this. See the Help menu in Desktop to locate the logs. 

Also, if you hover over each of those files, do you see the same path in the tooltip?

**Comment by serfend** [comment]
yes ofcourse，but i'd lookup for any clue in entire logfiles.also it's exactly same path which is `/src/views/register/components/Base.vue`.
![bug fix commit](https://github.com/serfend/Util.Static.OnlyForRead/blob/master/20200426@github_desktop.issue/20200428073242.jpg?raw=true)

**Comment by tierninho** [comment]
Hey @serfend While I'll grant you that this certainly is confusing, especially from a Windows point of view, this is unfortunately the expected behavior of Git. @shiftkey wrote an answer to a very similar issue over at 
https://github.com/desktop/desktop/issues/2672#issuecomment-329011490 and I'd encourage you to check that out. There's also a good article about this over at [MS docs](https://docs.microsoft.com/en-us/vsts/repos/git/case-sensitivity?view=vsts).

I'm going to close this issue out as I believe #2672 covers this problem. If that's not the case please let me know and I'll reopen and we can take another look.
