### ISSUE TITLE
Unable to push or fetch after latest update.

### ISSUE THREAD

**Issue by joelcahalan** [desktop/desktop#9647]
### Describe the bug

Unable to push or pull due to credential has no scheme

### Version & OS

2.4.3 on osx 10.15.4

### Steps to reproduce the behavior

Click fetch origin or push to remote

### Expected behavior

Fetch/Push to github remote

### Actual behavior
Error

### Screenshots

<img width="504" alt="Screen Shot 2020-04-28 at 11 25 28 AM" src="https://user-images.githubusercontent.com/55459818/80506415-8a0ad000-8943-11ea-8a32-77fd089d9dd7.png">

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by joelcahalan** [comment]
From the logs it looks like it is running a command that sets the credential.helper to nothing thus causing this error:

`2020-04-28T15:49:41.018Z - error: [ui] `git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin` exited with an unexpected code: 128.`

Is there a way to make it use my .gitconfig instead?

**Comment by rafeca** [comment]
Hey @joelcahalan ! Apologies for this issue :( this is currently is being tracked in https://github.com/desktop/desktop/issues/9597 . This is caused by a problem in the latest git version, which was recently fixed for Windows but there's still no patch for osx/linux.

In the meantime, you can edit your `.gitconfig` to work around the problem. You should look for a `[credential]` section there and delete it if it's invalid. If you can't figure out how to do it please paste your `.gitconfig` and we can try to assist you.

**Comment by joelcahalan** [comment]
My gitconfig includes: 

```
[credential]
	helper = store
```

which works fine from the command line. I don't think it is invalid. The problem is that Github desktop is setting the helper to nothing which requires manual input which it doesn't seem to be set up to do...

**Comment by rafeca** [comment]
Hi @joelcahalan ,

GitHub Desktop uses its own credentials mechanism via the system keychain provider, this is why it sets the credentials to nothing why performing `git` operations (it's been like this for a very long time).

The root problem here is that the `git` version that the latest version of GitHub Desktop uses ([`v2.23.3`](https://github.com/git/git/releases/tag/v2.23.3)) is more picky when parsing credential urls (you could probably reproduce this same issue in the command line if you installed `git@v2.23.3`).

Can you check if you have a `~/.git-credentials` file with some empty/invalid URLs? Also can you check whether commenting the two lines you posted from your gitconfig solves the problem?

**Comment by joelcahalan** [comment]
Neither of your proposed solutions works.  There are no invalid URLs in `~/.git-credentials`. I am currently using git version 2.26.2.  I guess I will have to stop using Github Desktop for now.

**Comment by rafeca** [comment]
Sorry about that 😞  as a last resort I would try the solution by @dima-y: https://github.com/desktop/desktop/issues/9597#issuecomment-621450266, since it looks like they have the same issue as yours.

If this still does not work, you can subscribe to https://github.com/desktop/desktop/issues/9597#issuecomment-621450266, since we're going to give progress updates about there and close the issue once the problem is resolved.

Note that [a patch for this problem](https://github.com/desktop/desktop/issues/9597#issuecomment-621450266) has already been sent to the `git` repository, but since this issue does not affect `v2.26.x` it may take a few more days until the patch gets accepted and a new version of git `v2.23.x` gets released.
