### ISSUE TITLE
Console Windows Flashing Making GitHub Desktop Unusable

### ISSUE THREAD

**Issue by ooodummy** [desktop/desktop#9701]
### Describe the bug

The application %temp%\3582-490\git.exe constantly opens and closes when GitHub is open and opens about every 5 minutes not having GitHub desktop-focused

### Version & OS

I'm unable to go top the GitHub desktop about due to the bug making it almost impossible to use the application, I am using the newest install as of 5/4/2020 since I factory reset my computer thinking something was corrupted and I am still getting this behavior.

OS: Windows 10 1909 also I downloaded a new iso to make sure there was no problem with that.

### Steps to reproduce the behavior

Whenever I have GitHub desktop open or in the background.

### Expected behavior

No console windows flooding my screen.

### Actual behavior

A flashing console window on my screen as well as it showing publish repository instead of fetch repository due to it not being able to read new data?

### Screenshots

https://i.imgur.com/C0iZeHL.jpg

### Logs

I cannot go to the log menu due to the severity of this bug.

### Additional context

I factory reset my computer and still had the issue, I thought this was due to windows not properly removing everything on install so I reset again using an entirely new windows USB, and the problem still consists.

### Software Installed

Brave
Discord
Process Hacker 2 (with driver enabled)
ShareX
Steam
Origin
Apex Legends
GitHub Desktop
GeForce Experience
RiseUp VPN
Notepad++

**Comment by steveward** [comment]
@ooodummy thanks for the report. I don't believe this is related to GitHub Desktop, since any .exes involving GitHub Desktop are stored in `%LocalAppData%`. To me this sounds like the behavior of a virus on your machine -- have you tried running a scan to see if your system could possibly be infected with malware? Have you looked in `%temp%\3582-490` to see what's actually in there?

**Comment by ooodummy** [comment]
inside of the temp folder was git.exe and in no way was this malware etc on my machine because this problem repeatedly happened even after downloading a new windows iso and cleaning the drive and reinstalling, a temp fix I could do to the problem was to uninstall GitHub desktop and reinstall it but on my next boot the problem would come back. Currently I just factory reset again to a new iso and it has been working for a hour or so, the last time it worked for a bit then stopped working for no apparent reason.

This problem may just be windows media creation tool not working correctly I guess, but it’s odd that it has happened over and over.

**Comment by steveward** [comment]
@ooodummy there's a [superuser thread](https://superuser.com/questions/356971/weird-execution-of-ruby-git-executables-in-windows) (granted it is rather old) that seems to indicate this could be malware. I'd recommend running a scan to be on the safe side. I'm going to close this out since it is a specific system issue and not something related to GitHub Desktop.

**Comment by Bang1338** [comment]
I know this is 4 years old, but.
> 3582-490

which mean your computer is infected with [Neshta.A](https://blogs.blackberry.com/en/2019/10/threat-spotlight-neshta-file-infector-endures)
