### ISSUE TITLE
Crash reports from Sentry - read ENOTCONN

### ISSUE THREAD

**Issue by billygriffin** [desktop/desktop#9710]
### Describe the bug

We're seeing a crash report with the error `read ENOTCONN`

### Version & OS

Seems to be specific to macOS and 2.4+

**Comment by outofambit** [comment]
These are likely caused by https://github.com/nodejs/node/issues/26315, which we likely inherited when we moved to electron `v7.x`. This wasn’t fixed in nodejs until in the `v12.13.1` release, which isn’t included in electron v7.x. (They’ve only upgraded it to nodejs `v12.8.1`.) The next release of Electron (`v8.2.6`) will likely include a version of nodejs with the fix for this.

**Comment by plivesey** [comment]
The app crashes consistently on launch for me. Is there a workaround to fix this locally? It suddenly started happening and I'm not sure what changed.

```
Error: read ENOTCONN
    at Socket._read (net.js:530:20)
    at Socket.Readable.read (_stream_readable.js:481:10)
    at new Socket (net.js:328:12)
    at Object.Socket (net.js:237:41)
    at createSocket (internal/child_process.js:311:14)
    at ChildProcess.spawn (internal/child_process.js:424:23)
    at spawn (child_process.js:553:9)
    at Object.execFile (child_process.js:237:17)
    at Object.module.<computed> [as execFile] (electron/js2c/asar.js:163:31)
    at file:///app/renderer.js:16:254915

Version: 2.4.3
OS: Mac OS 10.15.4```

**Comment by plivesey** [comment]
Looks like for me it was because I had too many processes running. My whole computer was bricked: `fork: Resource temporarily unavailable`. I needed to go to Activity Monitor and kill a process which had 1000s of copies of itself.

The service is DTServiceHub which seems to be an Xcode related service. So I think my original cause was a bug in Xcode which bricks your computer.

**Comment by outofambit** [comment]
> The next release of Electron (`v8.2.6`) will likely include a version of nodejs with the fix for this.

It did not, it turns out. but electron `v9.0.0` did. (it has nodejs `v12.14.1`)

**Comment by billygriffin** [comment]
Since we're now on Electron 9, I think this should be fixed. Please let us know if you run into this issue again!
