### ISSUE TITLE
Allow sorting git history

### ISSUE THREAD

**Issue by vague369** [desktop/desktop#9722]
### Describe the feature or problem you’d like to solve

Users should be able to sort the displayed git history in ascending or descending order of commit date.

### Proposed solution

Desktop users can quickly jump to the first ever commit in a repository and work their way up to the latest commit, rather than scrolling manually to the bottom of the history list.

### Additional context

This is similar to the --reverse option of the git cli

**Comment by billygriffin** [comment]
Hi @vague369, thanks for the idea. This isn't something I've seen come up before from users wanting it, and also isn't possible on GitHub.com. Would you mind sharing how this would be useful for you? Generally I think this is likely a bit niche to expose in the app, and people who really want it are able to get it using the CLI as you pointed out, but I'd love to understand it better first. Thanks!

**Comment by vague369** [comment]
Thanks for replying @billygriffin. I am a relatively new user (Installed it just yesterday), so pardon me if it doesn't align with the project's vision. I needed to check the earliest commits of an open source project and had to manually scroll down pages of the git history to get there; Like I added, it is basically the --reverse option of the git cli, I just love the efficiency of the Github Desktop interface so much I'd love to be able to have that feature there.

**Comment by billygriffin** [comment]
@vague369 No problem at all! I really appreciate you bringing it up, as it was something you were hoping to see and especially as a new Desktop user. Hearing this type of feedback is helpful for us, even if we don't end up supporting most of the things people suggest because we try to keep the product as focused and intuitive as possible. I'm sorry for all the questions and if you don't want to go further into it, that's absolutely fine, but when you say: `I needed to check the earliest commits of an open source project` I'm curious why you needed to look at those earliest commits? 

Typically we try to keep new feature development intentionally more tightly scoped to things we see evidence that a lot of people will benefit of, and ideally on a pretty regular basis.

I know this isn't the answer you were hoping for, but wanted to share our reasoning. I'm going to close this for now, but I'm certainly not opposed to reopening it if there's a more frequent and/or compelling use case that would be likely to be used more frequently by more people. Thanks again and please feel free to open issues for other bugs and issues you run into!

**Comment by vague369** [comment]
I checked the earliest commits to get an understanding of how the project had grown or changed over time. I understand why the issue was closed, thank you for your time. It's good to be heard and I hope to be able to help the project grow. Beautiful stuff really, this project!

**Comment by chenxiaoyao6228** [comment]
I got the same problem, it would be really nice to have this feature

**Comment by percy507** [comment]
+1.
Allow reverse git history for reading source code from first commit.🥸

**Comment by parakhiya** [comment]
+1.
there should be a feature to see commits in orders.

**Comment by doom-cat** [comment]
+1.
I would like to revert a forked repository to a prior release. Seeing the commits in order would assist with that. Seeing releases would help even more.

**Comment by BishalN** [comment]
+1.
there should be a feature to see commits in orders.

**Comment by Jackie-gurung** [comment]
+1

**Comment by wonderland2-0** [comment]
Nooo9oooooooooooooooloo

**Comment by eugenewainaina** [comment]
I would like to see the newest commits first on the Github.com UI but it shows oldest first..
Quite annoying..
There should be a way to sort the list
