### ISSUE TITLE
upgrade to typescript 3.7

### ISSUE THREAD

**Issue by outofambit** [desktop/desktop#9735]
## Benefits

[TypeScript 3.7](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html) introduces some very nice syntax additions:

- https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#optional-chaining
- https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#nullish-coalescing

We work around these cases with far more verbose code quite often in our project.

There's also better [typechecking for functions that return `never`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#better-support-for-never-returning-functions) (which we also use in many places) and [the addition of assertions](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#assertion-functions) (which @rafeca and I have previously discussed as being a useful tool for us.)

## Risks

There are [some breaking changes](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#37-breaking-changes) in TypeScript 3.7. None of these should affect us significantly, and can all be caught and fixed at compile-time. Therefore the risk here is fairly small.

## Dependencies

We'll need the following things upgraded first or in tandem to keep our tooling compatible:

- [ ] prettier to >= `v1.19`
- [ ] typescript-eslint to >= `2.4.0`

**Comment by rafeca** [comment]
yay! I'm specially looking forward for assertions (to be able to implement an `invariant()` function) and optional chaining (to remove a few of the `null` checks).

**Comment by niik** [comment]
> yay!

:point_up:

This is an upgrade of TypeScript that I'm excited about. I think it has the potential of significantly increasing readability by letting us get rid of many explicit type narrowing gates.

I'm in favor of moving us to this version sooner rather than later but even though no-one is even suggesting it I want to caution against the urge of rewriting all the things (even though it's so incredibly incredibly tempting).

I think we should take a slow, gradual approach towards leveraging these new tools so that we don't inadvertently introduce subtle behavioral changes and so that we have time to find any unforeseen nuances (if any).

**Comment by rafeca** [comment]
TypeScript has already been upgraded in https://github.com/desktop/desktop/pull/10025, we can close this issue! 🎉
