### ISSUE TITLE
bad credentials

### ISSUE THREAD

**Issue by handiandida** [desktop/desktop#9748]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by steveward** [comment]
Thanks for reaching out @handiandida!

Would you mind filling out the rest of the issue template so that we can better understand what is causing the problem you are experiencing? Without that information it will be difficult to help you further. 

For a 'bad credentials' error I would first recommend trying to log out and then log back in to your GitHub account in GitHub Desktop to see if that gets things working. You can read [this article](https://help.github.com/en/desktop/getting-started-with-github-desktop/authenticating-to-github) for the steps required to access the authentication dialog. Let me know if that doesn't get things working!
