### ISSUE TITLE
Add heic file previews

### ISSUE THREAD

**Issue by v57** [desktop/desktop#9761]
### Describe the feature or problem you’d like to solve
Current version of Github Desktop doesn't show heic images in commit preview

### Proposed solution
Add heic image preview

### Additional context
<img width="1072" alt="Screen Shot 2020-05-12 at 01 15 41" src="https://user-images.githubusercontent.com/2669441/81617616-6d17d780-93ee-11ea-9da7-e8a36ec4e640.png">
<img width="1072" alt="Screen Shot 2020-05-12 at 01 15 50" src="https://user-images.githubusercontent.com/2669441/81617624-6f7a3180-93ee-11ea-8187-ef6834b12692.png">

**Comment by outofambit** [comment]
hi @v57 thanks for filing this! i've marked this as an enhancement since it would be a nice improvement on our image display functionality. unfortunately, there's no support for HEIC file formats in browsers currently, so i'm afraid we're blocked on this. i'm going to close this for now, but we can revisit when HEIC support begins in Chrome, etc.

see more info at: https://caniuse.com/#feat=heif
