### ISSUE TITLE
Unable to upload new files through github desktop

### ISSUE THREAD

**Issue by DanielekPark** [desktop/desktop#9765]
![issue](https://user-images.githubusercontent.com/54155014/81634005-d8e44b00-93c2-11ea-8f45-048bb33e0596.PNG)
### Describe the bug
I am unable to upload files to my account, when I try to upload the attached screenshot appears

### Version & OS
I am using github version 2.4.3 os is windows 10 home

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Expected behavior

I expected to open a new repository and upload my file
### Actual behavior
The screenshot appears and I am unable to upload the file
A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.
 

- [ ] @[

1. 

](url)

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.
[2020-05-12.desktop.production.log](https://github.com/desktop/desktop/files/4613185/2020-05-12.desktop.production.log)

**Comment by steveward** [comment]
@DanielekPark thanks for contributing. It looks like you haven't [committed your files](https://help.github.com/en/desktop/contributing-to-projects/committing-and-reviewing-changes-to-your-project), which is why you are seeing the `Cannot publish unborn branch` message appear in the `Publish branch` section. Once you make an initial commit to your repository you should be able to publish your branch. Let me know if you run into any issues.
