### ISSUE TITLE
Repository doesn't clone correctly

### ISSUE THREAD

**Issue by smrgeoinfo** [desktop/desktop#9797]
### Describe the bug

I'm trying to clone https://github.com/EnvironmentOntology/envo.git, both by clicking the 'clone or download/Open in Desktop' and by doing a 'Add repository' from desktop using the URL.  Process runs through 'resolving deltas' then I get a screen full of gobbledygook (attached), and the repo directory has a .git folder, but nothing else.
![Screenshot 2020-05-14 09 55 14](https://user-images.githubusercontent.com/513380/81964255-2cc18080-95cb-11ea-93d9-9ba2ae112766.png)

### Version & OS

GitHub Desktop 2.5.0, Window 10.

### Steps to reproduce the behavior

1. Go to https://github.com/EnvironmentOntology/envo
2. Click on 'Clone or Download/Open in Desktop'

no error message appears. 

### Expected behavior
I should have the repo cloned locally on my desktop

### Actual behavior

a .git directory is generated (I didn't look to see what's in it), but the rest of the repo is empty.

### Screenshots

Add screenshots to help explain your problem, if applicable.

**Comment by steveward** [comment]
Thanks for the report @smrgeoinfo. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`. Thanks!

**Comment by smrgeoinfo** [comment]
Steve—here’s logs from the last two days. Yesterday (5/13) should show something about when I tried to pull from the ENVO repo yesterday, and today what happened when I deleted my existing clone and tried to reclone.

 

steve

**Comment by steveward** [comment]
@smrgeoinfo it looks like your log file didn't make it as an attachment. If you attached it via an email reply then it won't get uploaded to the issue. You'll need to drag-and-drop it directly into an issue comment to share it here.

**Comment by smrgeoinfo** [comment]
[2020-05-14.desktop.productionENVO.log](https://github.com/desktop/desktop/files/4630547/2020-05-14.desktop.productionENVO.log)
 Here's the part of the log with interactions with the ENVO repo.

**Comment by smrgeoinfo** [comment]
OOPs didn't mean to close...

**Comment by steveward** [comment]
@smrgeoinfo thanks for uploading that. Here's the error you're running into that's causing the clone to fail:

```
error: invalid path 'src/envo/subsets/RO:0002259.json'
fatal: unable to checkout working tree
```
The issue here is that there is a `:` in that .json filename, which is an [illegal character](http://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx#naming_conventions) on Windows. 


The best recommendation I have would be to [rename the file](https://help.github.com/en/github/managing-files-in-a-repository/renaming-a-file) directly on GitHub. If you do not have write access to this repository you could [create a fork](https://help.github.com/en/github/getting-started-with-github/fork-a-repo) and then rename the file in your fork. This would allow you to clone the repository. It may be also worth creating a pull request to change this filename since this would cause issues for anyone else who is also on Windows. I hope that helps!

**Comment by smrgeoinfo** [comment]
Thanks Steve!
