### ISSUE TITLE
schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - Funkcja 

### ISSUE THREAD

**Issue by artur-wasik** [desktop/desktop#9811]
Hello I have a problem:

schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - Funkcja odwołania nie może sprawdzić odwołania certyfikatu

Can you help me?

**Comment by rafeca** [comment]
Hey @artur-wasik ! 

This is a known issue caused by your network administrator blocking the usage of of the SChannel APIs on Windows (which `git` uses to verify the certificate of the git server).

You can read more about this in this [document](https://github.com/desktop/desktop/blob/development/docs/known-issues.md#certificate-revocation-check-fails---3326), which also explains an escape hatch to make `git` work.
