### ISSUE TITLE
If newer commits are found, offer to pull instead of fetch

### ISSUE THREAD

**Issue by Alexejhero** [desktop/desktop#9817]
### Describe the feature or problem you’d like to solve

If newer commits are found on the remote, desktop currently offers to fetch them, then the user needs to pull them. 

### Proposed solution

If there's a guarantee that newer commits are on the remote, desktop should offer to pull them, instead of fetch them.

**Comment by rafeca** [comment]
Hey @AlexejheroYTB ! GitHub Desktop perform `fetch` operations on the background every certain time, and when it does so, it fast forwards the outdated branches automatically.

Desktop only shows the `fetch` button when it doesn't know whether there are new commits in the remote (because there weren't the last time a fetch was performed).

Have you experienced any situation where Desktop should have known that there were new commits and it still showed a `fetch` button?

**Comment by AlexejheroYTB** [comment]
To clarify my original suggestion, I meant offer to pull instead of fetch in the "There are newer commits on the remote" pop-up, which always shows a fetch button no matter if they've already been fetched or not.

**Comment by rafeca** [comment]
Thanks for the clarification @AlexejheroYTB !

In some situations it won't be possible to perform a pull operation right away from that modal (for example when the user has local changes in their working copy).

That scenario could cause some complications to users: they would get an error when clicking "Pull" from the modal but would not be able to fix the problem since the modal is on their way. If they closed the modal and fixed the problem, it won't straightforward how to perform a Pull operation again.

That modal is meant to provide an easy solution for users that get a conflict error when trying to push, so I think it's better to show a safer action like fetch (even if involves two clicks) than an action that can fail without an easy way to move forward.

Something we could do is to detect when there are no local changes (and other potential scenarios that may cause immediate failures on the pull operations) and then show a Pull button there, so I'm leaving an "enhancement" label to this issue.
