### ISSUE TITLE
Use Checks API for PR combined status

### ISSUE THREAD

**Issue by Raul6469** [desktop/desktop#9819]
### Describe the feature or problem you’d like to solve

GitHub Desktop displays head commit combined status next to PR informations (in the PR list or on the branch selector button). But it only requests the [status API](https://developer.github.com/v3/repos/statuses/), and some services (such as GitHub Actions) uses the [checks API](https://developer.github.com/v3/checks/), and they don't appear in the interface.

### Proposed solution

We could also request the checks API in addition to the status API, and display a combined status as it's already the case, so no UI change. This way all users will be able to see the combined PR status regardless of the used CI services.

### Additional context

Both endpoints are independent, and the checks API does not provide a "combined status" out of the box as the status API does. Therefore, I think we will have to determine by ourselves what the combined status is, based on both requests results.

If you think this could be a great addition, I would gladly work on it! 🙌  (with a little bit of help though 😇 )

**Comment by rafeca** [comment]
Thanks for the suggesion @Raul6469 ! I do think this would be a great addition, but before you start working on this we need to do a bit of investigation to be able to answer some questions that I initially have:

1. It seems that the Checks API is currently in public beta ([source](https://developer.github.com/v3/checks/runs/#list-check-runs-for-a-git-reference)). Will this have any impact? (e.g some users/repo won't be able to use it or is it opened to everybody?).
2. How's the current combined status calculated internally? is it green when all statuses are green or there's more logic into it?
3. Can there be duplication between the states reported by the Checks API and the Status API? (e.g the same job being reported in both).

If you're up to, you can do some investigation about these points (although it may be a bit easier for somebody in our team to answer some of them since we have more internal info available).

Depending on the answers of these questions we can decide how to add information about the checks API into Desktop.

**Comment by Raul6469** [comment]
Hi @rafeca ! Here are some answers to your questions:

1. It looks like the Checks API is available for everyone and for all repos, but I don't know if breaking changes are planned in the near future, you might have more information on it

2. The current combined status is returned by the Status API directly, and indeed, it's green when all statuses are green. But if we add support for the Checks API, I think we will have to implement our own combined status logic from both endpoints.

3. I don't think this is possible, both APIs are independent from one another. For me, a status will always be a status, and can not be converted or duplicated as a check.
