### ISSUE TITLE
cant find my repositories on google

### ISSUE THREAD

**Issue by kirtimunot** [desktop/desktop#9822]
I can't find my github repositories on google

**Comment by tierninho** [comment]
@kirtimunot thanks for reaching out!

We require the [template to be filled out](https://github.com/desktop/desktop/issues/new?template=bug_report.md) on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
