### ISSUE TITLE
been having problems with pushing comits to origin remote

### ISSUE THREAD

**Issue by jess-hub** [desktop/desktop#9836]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by rafeca** [comment]
Hey @jess-hub ! Thanks for filling this issue and apologies for the caused inconvenice.

From the title of the issue seems the same issue as described in #9776, feel free to download [the Desktop beta](https://github.com/desktop/desktop#beta-channel) since this issue has been fixed there.

If this doesn't work you can open a new issue but please fill out the required template so we have the needed information to investigate the problem.
