### ISSUE TITLE
allow repo tab to show folder name instead of repository name

### ISSUE THREAD

**Issue by gilm123** [desktop/desktop#9837]
### Describe the feature or problem you’d like to solve
I'm cloning a repository more than once, to 2 different folders, but both tabs are showing the repo name so i don't know which is who.

### Proposed solution
show / let me decide if the repository tab should present the repo name or the folder i cloned the repo to.

How will it benefit Desktop and its users?
described above.

### Additional context
most common git clients are doing the same

Add any other context like screenshots or mockups are helpful, if applicable.
![image](https://user-images.githubusercontent.com/20421380/82535348-6d7f4380-9b4f-11ea-8d1d-9adcc429094d.png)

**Comment by rafeca** [comment]
Thanks for filling this issue @gilm123 !

We're tracking a similar improvement in https://github.com/desktop/desktop/issues/7856 (that issue is more centered about the ability to customized the name that appears on the list, but the problem it tries to solve seems to be the same one).

Feel free to subscribe to that issue to get updates (or comment if you want to share your use case/ideas).
