### ISSUE TITLE
Desktop gitHub  push not working

### ISSUE THREAD

**Issue by etezare** [desktop/desktop#9849]
Authentication failed. Some common reasons include:
-You are not logged in to your account: see File> Options.
-You may need to log out and log back in to refresh token
-You do not have permission to access this repository
-The repository is archived on GitHub. Check the repository settings to confirm permitted to push commits.
-If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account

**Comment by niik** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

With that said this _could_ be related to https://github.com/desktop/desktop/issues/9843. If the repository you're trying to access is hosted with another Git hosting provider. It's impossible to say with the information provided but the timing seems right. Take a look at that issue and if that seems like the issue you're having you can try installing the [beta version](https://github.com/desktop/desktop#beta-channel) which has a fix for that issue.

**Comment by etezare** [comment]
Thanks it’s working now.


Sent from Yahoo Mail for iPhone


On Friday, May 22, 2020, 10:35, Markus Olsson <notifications@github.com> wrote:




Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

With that said this could be related to #9843. If the repository you're trying to access is hosted with another Git hosting provider. It's impossible to say with the information provided but the timing seems right. Take a look at that issue and if that seems like the issue you're having you can try installing the beta version which has a fix for that issue.
