### ISSUE TITLE
 Contributions stopped to count

### ISSUE THREAD

**Issue by azagorowski** [desktop/desktop#9850]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is.
I have made some commits and they did not count to my contrbutions
### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by tierninho** [comment]
@azagorowski thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by azagorowski** [comment]
@tierninho  I would very much appreciate it if you could delete this issue. There is nothing I can do to solve it for this time.
