### ISSUE TITLE
Unable to sign in

### ISSUE THREAD

**Issue by Pilsam** [desktop/desktop#9851]
Hey,

I can't sign in using my desktop because it fails to fetch, why is this happening when I have a lot of stuff to do. What's going on with such inconveniences? I need urgent help here.

**Comment by niik** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

With an issue like the one your describing a copy of your log file would go a long ways toward diagnosing the issue.

Thanks for understanding and meeting us half way :grinning:
