### ISSUE TITLE
Please give back the ability to Stash on protected branches

### ISSUE THREAD

**Issue by Justin-JHG** [desktop/desktop#9858]
### Describe the feature or problem you’d like to solve

Recent update of GitHub Desktop has removed the ability to Stash on protected branches.
Personally I think it is very useful to be able to stash on all branches regardless of it's protected or not. 
It really doesn't hurt to allow us to stash on whatever branch we want. 
it's a stash not a commit. What could fail if we stash something on a protected branch

### Proposed solution
Give back the ability to stash on all branches

How will it benefit Desktop and its users?
We have different build information on different branches and don't want to commit them to all branches as when merging have to dealing with conflict on build configuration files.

if we could have the ability to stash on the protected branches this issue will go away. 

I just don't understand why Desktop allow users to commit on a protected branch but not allow us to stash.

Thanks

**Comment by billygriffin** [comment]
Hi @Justin-JHG, this was a design choice intended to help make switching away from a protected branch more convenient and not having the dialog. I don't think we've seen a ton of evidence that more people dislike that choice, but totally understand what you're saying and sorry it's causing problems. One mitigation might be our proposal to allow stashing independent of branch switching in #8197, and that way for those who want it, you'll have a bit more control over that. So since that's open, I'm going to close this. Thanks for the issue!

**Comment by Justin-JHG** [comment]
hi @billygriffin, 
thank you for the reply. the issue #8197 is quite different to this one, even that one implemented we still can't stash changes on protected branches. 

if users don't want to dialog to pop up when switching away from protected branch then they can configure to not show the dialog. but for us who need to stash on protected branches there is no way to do. 

So yes just asking you to reconsider this and even adding a configuration to allow stash on protected branches would be very beneficial and it will feel consistent as well. 

Thank you.
