### ISSUE TITLE
Add capability to checkout a specific commit

### ISSUE THREAD

**Issue by benplay2** [desktop/desktop#9879]
### Describe the feature or problem you’d like to solve

There are times when a developer has a need to checkout a commit in the history of the current branch. I have not found a method to do this using GitHub Desktop.

### Proposed solution

One simple method to add this feature would be to add an option to the context menu when right-clicking on a commit in the history pane. A potential name: `checkout this commit`

After this operation, the user would likely be in a dethatched head state and would need to switch branches to get back to the original branch.

This simple addition would make it simpler for a developer to checkout a previous commit.

**Comment by billygriffin** [comment]
Hi @benplay2, thanks for the issue. We're looking at this in https://github.com/desktop/desktop/issues/3474, which is still in the `future proposal` bucket for potential things we'll consider down the road but don't have plans for soon. If you'd like to add more context there that might not already be in the issue, please do so. I agree that this would be useful but also might get people into trouble and confused, so that's why we've been a bit reticent to prioritize it up to now. Thanks again!
