### ISSUE TITLE
publish branch desktope

### ISSUE THREAD

**Issue by helengateso** [desktop/desktop#9886]
git remote https is not a git command

**Comment by steveward** [comment]
Thanks for reaching out @helengateso!

Would you mind filling out the rest of the issue template so that we can better understand what is causing the problem you are experiencing? Without that information it will be difficult to help you further. It would especially be helpful if you could upload the log file from GitHub Desktop, which will give more details about the specific error you are seeing. 

To access the log files go to the  menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`. 

The log files are created daily -- please send over a log file as an attachment from a day where you experienced the issue. Thanks!

**Comment by steveward** [comment]
@helengateso as we have not heard back from you I am going to close this issue out. Please let us know if you are still having trouble and we can assist you further.
