### ISSUE TITLE
Desktop app crashing on launch

### ISSUE THREAD

**Issue by ray-newby** [desktop/desktop#9895]
### Describe the bug

I wanted to put GitHub Desktop on a second computer, so I downloaded the file and installed it. I attempted to clone a repo, and had to log in via my school Enterprise login. But the app crashed. And then I opened it again, and it immediately crashed. I opened it a third time and instead of an error message I received a white box. I uninstalled the app and reinstalled it. Again, I got an immediate crash without logging in or doing anything. Each time I install a fresh version, it crashes immediately twice and the third time opens a white box of nothingness.
I would imagine it has something to do with my school repository because I finally caught a screenshot during the microsecond before the crash. It seems to be constantly trying to load repositories from my school account. I've used this app with my same school account before while working on my older computer. I'm not sure what I can do here to prevent this from happening. I'd love to just not have it not load those repositories, but I can't stop it.

### Version & OS

I can't see the 'About GitHub Desktop' menu, but since I just downloaded it, I know it is the latest version -- 2.5.0. 
I'm using Mac OS Catalina 10.15.5 (just updated from 10.15.4, but I have the same behavior on both). 

### Steps to reproduce the behavior

Nothing except: Open GitHub Desktop

### Expected behavior

I expect it not to immediately crash.

### Actual behavior

It crashes immediately.

### Screenshots
Shows for a fraction of a second:
![image](https://user-images.githubusercontent.com/11397007/83316419-96f53a80-a1f3-11ea-9392-e57686f6ec3d.png)

And this error appears:
<img width="598" alt="image" src="https://user-images.githubusercontent.com/11397007/83316223-b17ae400-a1f2-11ea-894f-b8af90e5b5e8.png">

### Logs

This option isn't available, as the app has already crashed and not done anything at all.

**Comment by niik** [comment]
Hi @ray-newby, sorry to hear you're having issues using the application. There seems to be a very rare condition on your GitHub Enterprise Server instance (`github.[redacted].edu`) that's causing this for you.

I've put together a fix in #9911 but since it may take some time before that's been tested and released to production I want to make sure you're not stuck unable to use the application.

The problem occurs when trying to load the list of repositories available for you to clone (see where it says "Loading repositories..."). In order to get around that we're gonna have to trick the application a little, starting with _not_ signing in to your account.

First we're gonna have to clear the application data.

1. Start the app, wait for it to crash
2. When looking at the crash window click the  'View -> Toggle Developer Tools' menu item.
3. Click the Application tab, select "Clear Storage" from the left hand sidebar
4. Click on the "Clear site data" button

<img width="779" alt="image" src="https://user-images.githubusercontent.com/634063/83404418-ec576480-a40a-11ea-91be-9597907cce9a.png">

Once that's done you should be able to restart the application without it crashing. You'll be presented with the welcome wizard which will ask you to sign in to your account. Here's the key *don't sign in to your GitHub Enterprise Server account*. Either skip signing in or sign in with your GitHub.com account first.

Once you've gotten to the "Let's get started!" view you can either create a local empty repository, add an existing repository on your machine, or clone a repository from GitHub.com. Once you've added your first repository you can open the Preferences dialog and sign in again with your GitHub Enterprise account. The clone repository dialog will still be broken but you'll be able to clone repositories using the "Clone or Download" button on the website

![image](https://user-images.githubusercontent.com/634063/83404770-861f1180-a40b-11ea-8d22-f0dcfdd3c40c.png)

I you're able to use that workaround until we've gotten a proper fix in place.

**Comment by ray-newby** [comment]
Perfect workaround! Thank you so much!
