### ISSUE TITLE
github desktop not opening repositories

### ISSUE THREAD

**Issue by Insidewhale** [desktop/desktop#9898]
### Describe the feature or problem you’d like to solve
I have downloaded git hub desktop, on the github page i have made a repository i clicked setup on desktop and it opens the page where you download github desktop and not the actual app

**Comment by niik** [comment]
Hi @Insidewhale, this issue usually happens because you haven't signed in using your `Insidewhale` account in GitHub Desktop. The account you're signed in to on the web needs to match that which you signed in to using GitHub Desktop.

Take a look at the preferences (or options if your on Windows) dialog and make sure that you're signed in with the correct account. If you are, try signing out and back in again.

Please let us know if the issue persists.

**Comment by niik** [comment]
Thank you for your issue!

We haven't gotten a response to our questions.
With only the information that is currently in the issue, we don't have enough
information to take action. I'm going to close this but don't hesitate to reach
out if you have or find the answers we need, we'll be happy to reopen the
issue.
