### ISSUE TITLE
can not locate the git bash path by manual

### ISSUE THREAD

**Issue by uscq** [desktop/desktop#9906]
### Describe the bug

I can not find a setting to locate my git bash that installed by manual without polluted my system path environment.

### Version & OS

version 2.5.0 on Window 10

### Expected behavior

I can locate my git bash anywhere or locate it smart enough, not just open my browser and tell me how. computer should make thing easier that is why it made.

**Comment by steveward** [comment]
@uscq during the installation process Git for Windows asks you if you would like to add it to your system PATH. Since this issue tracker is for GitHub Desktop I am going to close this issue out. Please see the [Git for Windows](https://github.com/git-for-windows/git) issue tracker for issues specifically related to Git for Windows.

**Comment by uscq** [comment]
If Git for Windows installed without add the path to system PATH before installing GitHub Desktop, it dose not locate the path, also it even not tell me to reinstall the Git for Windows and add the path is required.
