### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by GokseLW** [desktop/desktop#9925]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

![image](https://user-images.githubusercontent.com/57256097/83618489-2fdcda80-a593-11ea-901d-c98762320224.png)

**Comment by niik** [comment]
Hey @GokseLW, thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

While you fill out the template please make sure to upload a log file from GitHub Desktop as well. To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

Thanks for understanding and meeting us half way :grinning:
