### ISSUE TITLE
When loging new account [ENTER] should not open the browser

### ISSUE THREAD

**Issue by crimson-med** [desktop/desktop#9935]
### Describe the feature or problem you’d like to solve

I often have to switch between company and personal account on github desktop. 
When having the signed in screen.
 - type username
 - press [TAB]
 - type password
 - press [ENTER]
 - sign in window is then blocked and I have to quit and restart

Enter simulates click on the "Sign in using browser button". 

### Proposed solution

If the active field is `Username` or `Password` then [ENTER] key should simulate the "Sign In" button.

### Additional context

![Jun-04-2020 11-29-55](https://user-images.githubusercontent.com/28290546/83711788-c58d6e00-a656-11ea-9efb-ac7039ff31a6.gif)

**Comment by niik** [comment]
Hi @crimson-med, thanks for opening and sorry for the inconvenience!

We're tracking this in https://github.com/desktop/desktop/issues/9899 and merged a fix (https://github.com/desktop/desktop/pull/9920) yesterday that should make its way into the next release. In the meantime the workaround is to manually click on the sign in button instead of hitting Enter.
