### ISSUE TITLE
repository is not publishing and pull and push also not working properly

### ISSUE THREAD

**Issue by afaqshaikh** [desktop/desktop#9941]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by steveward** [comment]
Thanks for reaching out @afaqshaikh!

Would you mind filling out the rest of the issue template so that we can better understand what is causing the problem you are experiencing? Without that information it will be difficult to help you further. It would especially be helpful if you could upload the log file from GitHub Desktop, which will give more details about the specific errors you are seeing. 

To access the log files go to the  menu in GitHub Desktop and select `Help` > `Show Logs..`. The log files are created daily -- please send over a log file as an attachment from a day where you experienced the issue.

**Comment by afaqshaikh** [comment]
This type of error occoured while publishing our repository. Tell me how this  problm can be resolved
________________________________

**Comment by steveward** [comment]
@afaqshaikh if you are having issues please upload a log file from GitHub Desktop into a reply in this issue thread. You can find the logs by going to `Help` > `Show Logs...`.
