### ISSUE TITLE
 I have problems with clone code from bitbucket, it says something like this while I am logged in and completely correct account

### ISSUE THREAD

**Issue by tuanskyxox** [desktop/desktop#9943]
![image](https://user-images.githubusercontent.com/52083837/83892022-409a7580-a778-11ea-904c-c2a05fde621b.png)

![image](https://user-images.githubusercontent.com/52083837/83892226-8b1bf200-a778-11ea-9378-df5a50c652a3.png)

**Comment by rafeca** [comment]
Hi @tuanskyxox!

The accounts section on the preferences modal shows the logged in information for GitHub.com, so that's not related to other git hosting services like bitbucket.

A couple of questions:

- What error message are you getting?
- What GitHub Desktop version are you using? 

If you're not using the latest Desktop version (v2.5.2), please try upgrading to it. There was a known issue in the previous version which affected logging into exernal git providers like bitbucket (see https://github.com/desktop/desktop/issues/9843).

**Comment by tierninho** [comment]
@tuanskyxox  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
