### ISSUE TITLE
Following system theme should be a default

### ISSUE THREAD

**Issue by ardacebi** [desktop/desktop#9959]
The macOS version of GitHub Desktop apparently has an appearance option (which I'm recently finding out and is the inspiration to this issue) which let's us use a dark theme and an automatic switching feature that follows the system theme along with the other apps. But the default of following the system theme doesn't come enabled by default causing people to not even know about the feature (if you're using the program for a long time and haven't come across with the dark/light option on the introduction page).

The best and most logical solution would be to enable the following of the system theme by default.

Important note: Not sure about the latest behavior of the app (the installation wizard, defaults etc.) and suggesting this to have a discussion on it. Don't hesitate to correct any of my errors, as at the end this is a suggestion to improve the app.

<img width="1072" alt="Screen Shot 2020-06-08 at 01 35 54" src="https://user-images.githubusercontent.com/17576065/83981654-72ead500-a928-11ea-9e9c-b23c1519052d.png">

**Comment by rafeca** [comment]
Thanks for the suggestion! We were just talking about this last week with @niik !

There were a couple of things we discussed related to this:

1. What happens with existing users? with the current logic in place, if we only change the default value, users that have manually changed their theme will keep using it while existing users that have never change the theme through the "Appearance" tab will automatically get enrolled to follow the system theme. Is this behaviour ok or do we prefer to only apply the default value to new installations of Desktop?
2. While we're changing this, it would be cool to change the UI of the theme selector on the appearance tab: instead of chosing between Dark and Light and having a checkbox for the automatic switch we could have the 3 options in the same selector component, since they are mutually exclusive.

**Comment by ardacebi** [comment]
I'm glad to hear it's on the table!

Here are my solutions and thoughts:

1. Existing users can be presented with a modal (just like the installation wizard but one step) that asks them whether they want to switch to following the system theme or ignore (keep the current setting). Not touching or informing the existing users that this feature is present probably will make them miss the feature, as I've told that the feature exists to my other friends (they didn't know it as well). As I told before, a modal is a must but the thing that needs discussion is that should the modal present the release notes of the latest update (in general and should be presented for all future releases) and include this feature or just inform the users of the theme feature only (only for this release).

2. Having three options on the same dropdown is definitely a better practice, for the sake of simplicity. Then it will be Dark, Light and System (Auto).

**Comment by ardacebi** [comment]
Bump?

**Comment by say25** [comment]
Hey guys, I helped implement the system theme. All these things make sense to me.

With regards the modal should it replace the “welcome” initial signup theme selection?

Somehow we ended up with the check box idea instead of the “third option approach” https://github.com/desktop/desktop/issues/5037 though I like the third option approach better.

**Comment by niik** [comment]
I'm not convinced that presenting a modal here is the right thing to do. We've generally steered away from blocking flows during app launch/restart unless we've had no other choice (the privacy consent dialog is an exception that comes to mind). If we only present the user with a choice once and only when the selected theme is Light and the system theme is Dark we'd target a smaller percentage of users which would be better but I'm still hesitant.

In order to not halt this work on this while we iron out the flow for existing users I think we should move ahead and make theme selection be automatic as default and redesign the appearance tab with three options.

> With regards the modal should it replace the “welcome” initial signup theme selection?

I'm likely misinterpreting here but I don't believe we have any initial signup theme selection in the welcome flow. Regardless I think that once we have "auto" as the default we won't need any initial selection.

> Somehow we ended up with the check box idea instead of the “third option approach” #5037 though I like the third option approach better.

Hard same

**Comment by say25** [comment]
I can take the initial work on to default to the system theme and make it a “third option” approach.

**Comment by ardacebi** [comment]
I'd prefer:
- The welcome prompt should stay as it is, with slight modifications such as following the system theme option should be selected by default, while other options should stay available for the user to change on setup
- Instead of the checkbox approach, a third option approach is much better inside settings
- And per existing users, after the update, there can be a pop-up dialog that states the changes in default behavior. Not sure about the details about existing users and needs discussion, but these are my thoughts.

Also, consider checking out my other thoughts I said on my first and second posts.

**Comment by ardacebi** [comment]
@niik 

> I'm not convinced that presenting a modal here is the right thing to do.

About this, I might have a solution: We can let **new users** know that by default, GitHub Desktop follows the system theme and this can be changed manually from the app settings (and by the prompt itself as a dropdown). For existing users, we can present a bottom left or right notification that informs them about the changes that the app follows the system theme by default. The bottom notification thing is a better version of this:

![e7f015fc-e073-4701-9d6e-3edd47a34ff9](https://user-images.githubusercontent.com/17576065/90652616-ed987080-e246-11ea-99ec-98f9d7c272db.png)

What that needs urgent discussion is whether the update will override user selection of the theme or not. If the user changed the theme before, should it be changed to following the system or only for those who didn't change it manually?

**Comment by naablole** [comment]
[https://naabzist.com/](https://naabzist.com/)
