### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by Hassan557-tech** [desktop/desktop#9960]
### Describe the feature or problem you’d like to solve
in the GitHub desktop repo is not clone
A clear and concise description of what the feature or problem is.
repo is not cloning 
### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups that are helpful, if applicable.

**Comment by niik** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by Hassan557-tech** [comment]
What is hepened to my desktop Sent from Mail for Windows 10 From: Markus OlssonSent: Monday, June 8, 2020 2:23 PMTo: desktop/desktopCc: Gul Hassan; AuthorSubject: Re: [desktop/desktop] error (#9960) Closed #9960.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
