### ISSUE TITLE
Warn me before I commit large files without using Git LFS

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#997]
Dropped a 1G file in my local repo and committed it. No error validation prevented me from doing so. 

Do we have a limit as I tried dropping same file into dotcom UI and was limited to 100MB? Isn't LFS supposed to do this?

<img width="1170" alt="screen shot 2017-03-01 at 4 08 57 pm" src="https://cloud.githubusercontent.com/assets/14828183/23487327/21244f58-fe9a-11e6-80db-dcf65167ce04.png">

**Comment by shiftkey** [comment]
#5079 was opened to indicate that it'd be nice to even list the files that were committed that are over 100MB - the Git server doesn't include these when it fails the `git push` - but I think it'd be nicer to warn the user before committing.

**Comment by canerelci** [comment]
![image](https://user-images.githubusercontent.com/1029955/47016310-f9e9a900-d157-11e8-8c69-d37ba57bf90f.png)

I have no idea which one of hundreds of files...

**Comment by HedvigS** [comment]
I have the same problem. I often find myself not being able to find the file and resolve the conflict. My current method of solving these situations is rather crude :/ , but has proven successful.

* move the folder where I have made changes to outside of the repos
* remove the clone from Github Desktop and move to trash
* re-clone the same repos
* put the folder back into re-cloned repos
* comity and push and pull again

**Comment by HedvigS** [comment]
Thanks @steveward . The problem now is more to do with the resolution, I just thought it'd be good if the dialogue box also included this information.

If I've committed a file to my local branch that's too large, even if I remove it from the folder I still can't push. Hence the whole re-cloning thing :)

**Comment by shiftkey** [comment]
> If I've committed a file to my local branch that's too large, even if I remove it from the folder I still can't push. Hence the whole re-cloning thing :)

@HedvigS this is because it's still preserved in the Git history in a previous commit, and pushing the branch  after cleaning it up will still try to push that old commit containing the 100MB file

**Comment by HedvigS** [comment]
@shiftkey Yes.
So could there be a stop at the commit level already instead of later at the push-stage? 
Or is there an easy way to clean the commit history inside the app right now?

**Comment by billygriffin** [comment]
@HedvigS Yep, that's exactly what this issue is about. See @shiftkey's comment above: https://github.com/desktop/desktop/issues/997#issuecomment-402241709

Unfortunately no easy way to clean the commit history in the app, but hopefully if we can help prevent this on the front end prior to committing, it'll make that significantly less common.

**Comment by HedvigS** [comment]
@billygriffin 

If there just was a warning when committing, that would probably sort out most of these cases. For me, these are often just files that are right at the edge and I'm not fully aware that they're that large (Rdata files for example). If I'd just be stopped at the commit stage, that'd probably clear most of it up :)

**Comment by Daniel-McCarthy** [comment]
I have started looking into this Issue. I was able to add a function that can check for oversized files (if LFS is not in place) and get the names and file sizes of each of them.

From here I think we would need to decide how to present it. There were two immediate suggestions:
- Let the user know before committing that their files are over sized.
- Upon a commit failing due to a large file, display a list of the files that caused it.

>This should not materially slow down the speed of commits (will likely be most visible when a user is committing a lot of files).

I feel the least amount of slow down would come from generating attempting to commit. However, it would be convenient to be able to generate a warning before hand.
___
I would love to hear some thoughts on this and what is preferable. If nothing else we could try one and iterate on it.

**Comment by j-f1** [comment]
IMO the error should be before the commit is created since the current error only occurs on push, which could be a long time after the affected commit is made.

**Comment by Daniel-McCarthy** [comment]
This is a great point. To clarify, I was thinking we should validate when the commit button is pressed. When it is pressed there are some checks done to make sure that a commit can be created in the current state before continuing.

I was thinking this may be a good time to have it check the sizes of the files selected for the commit. Then perhaps we could inform the user at this point, cancel the commit, and display the situation to the user in some way. This way it can be detected before the user attempts to commit the file.

Otherwise, if we weren't concerned about running this check more regularly, perhaps we could run it when the user selects a new file, and detect only if that specific file is over the size limit and display some sort of notification.

**Comment by HedvigS** [comment]
As a user who has faced this issue several times, I would prefer the commit failing than getting a message later about the commit not being able to push.

**Comment by outofambit** [comment]
i think checking at when the user presses the commit is a good first iteration! i'd lean towards (eventually) having an indicator in the changes list to show that a file is too big to be committed and have the corresponding checkbox inactive. perhaps we could only check binaries for this, since they are (probably) the vast majority of cases?

would love to get thoughts from @desktop/design too! 💖

**Comment by billygriffin** [comment]
Thanks folks! Chatted with @ampinsk, @donokuda, and @nerdneha about this briefly. Here's the direction we're thinking for the initial iteration - I'm also totally down for @outofambit's suggestion as a potential follow-on to this.

Steps:
1. Add a file > 100MB
2. Write commit message
3. Click "Commit"
4. Try to push to GitHub
5. Be sad all day

New behavior:

Upon clicking "Commit", a warning message comes up (title and buttons should be cased appropriately per platform). 

<img width="671" alt="screen shot 2018-10-22 at 12 45 06 pm" src="https://user-images.githubusercontent.com/5091167/47312058-8da7f300-d5f8-11e8-9676-d39f252cd033.png">

Note: We'd like to link the "use Git LFS" to https://help.github.com/articles/versioning-large-files/
Note 2: We'd like the "If you commit these files, you will no longer be able to push this repository to GitHub.com." to be bold.

> I feel the least amount of slow down would come from detecting this when attempting to commit. However, it would be convenient to be able to generate a warning before hand.

I think what I mean is that if someone is trying to commit 50 files, and this check running on each of the files takes 150ms (or even 20ms), that quickly adds up. I just want to make sure we're not regressing significantly on the speed of committing.

@Daniel-McCarthy Does that give you what you need to proceed with a PR?

**Comment by HedvigS** [comment]
@steveward Thanks. I have used git via command line before, but I find it a bit cumbersome. Next time this happens though, I'll give these options a try before doing the whole re-cloning again :)

**Comment by Daniel-McCarthy** [comment]
@billygriffin That's fantastic! Thank you for polling the team and sharing this very detailed information, and to everyone who shared their input.

Yes, I believe this should be sufficient. I will continue working on this over the coming days and attempt to replicate this suggestion.

**Comment by billygriffin** [comment]
Awesome @Daniel-McCarthy, thanks! Looking forward to it, this will definitely help people avoid a lot of pain if we can get it right. 😄

**Comment by Daniel-McCarthy** [comment]
Just as an update for now, I have been working on the dialog as suggested. Since the list of files being committed that are over sized can be of any length, and potentially very large, I have made it so the list will scroll after a certain amount of files.

A short list not requiring scrolling does not have any:
![image](https://user-images.githubusercontent.com/4957200/47453101-76e8d400-d791-11e8-849d-3cae7a7dfaf4.png)

A large list that can be scrolled to view the full list:
![image](https://user-images.githubusercontent.com/4957200/47453147-92ec7580-d791-11e8-8b1e-107827c11c8c.png)

I felt this was worth an update since this behavior was not outlined previously, so I would show it in case there is additional feedback.

___
Also: Among the last tasks necessary: I need to wire up the "Commit Anyway" button to do what is expected. However I am having some difficulties with this. It seems most pop-up dialogs implement the functionality of the buttons within the dialog, or use the dispatcher.

However in this case, to behave correctly, it seems to need access to the `commit-message` functions since it needs to both commit, then clear the commit summary after committing. I am not sure how best to do this, I will continue looking into when I have more time later today.

**Comment by billygriffin** [comment]
Thanks @Daniel-McCarthy, the scrolling behavior you proposed seems to work exactly as I'd expect. Thanks for updating with that! 

Maybe someone from @desktop/maintainers might have some thoughts on the "Commit Anyway" action you're struggling with?

**Comment by outofambit** [comment]
Hi @Daniel-McCarthy, these are really good questions. I've been working through a similar problem in #5809. :)

> While I could attempt to pass the variables I need in order to copy the commit functionality that occurs in commit-message and the createCommit function, another issue is that even if I re-implemented the same functionality in this new Dialog, after committing another function is meant to be called to clear the commit summary.

I think this is basically the right approach (barring a large refactor of how we do commits from the UI). Let's get this working and then we can figure out how to handle clearing the commit summary afterwards. (I have an idea but I want to see if there's a better way first.)

I'm thinking the popup should only need to repeat this part of the createCommit function (and the requisite arguments, of course):

https://github.com/desktop/desktop/blob/237695fbe9d9b7e604b6b0cc344b59fde2f9d09c/app/src/ui/changes/commit-message.tsx#L257-L264

Do you want to share the new Popup type you're thinking? If we're on the same page there, we should be good. The rest you've already figured out! :)

**Comment by Daniel-McCarthy** [comment]
> I think this is basically the right approach (barring a large refactor of how we do commits from the UI). 

>Let's get this working and then we can figure out how to handle clearing the commit summary afterwards. 

Sounds great! Thank you for pointing me in the right direction and sharing this extra context. I will give this a try tomorrow and see how it goes.

> Do you want to share the new Popup type you're thinking?

Certainly. I've pushed a branch to my fork with the changes as I have them right now. [Here](https://github.com/Daniel-McCarthy/desktop/commit/ad6a09f3df692ae9e1ee8dd6f34542d33a0709dc) is the commit with the addition of the Popup dialog.

Thanks again!

**Comment by outofambit** [comment]
just took a look, @Daniel-McCarthy, and this is looking great!

```ts
  | {
      type: PopupType.OversizedFiles
      fileList: string[]
    }
```

so what i'm thinking is this could have a few more properties so the popup could do the commit itself. :) let me know if you have any questions as you're working through this.

**Comment by Daniel-McCarthy** [comment]
@outofambit I have just pushed some more commits to the branch. I have sent all the properties necessary to perform the commit and that is all working as expected now. I believe all that is left is clearing the commit summary afterwards.

Other than that, the dialog seems to be working as requested, both being able to cancel the commit after displaying the information to the user as well as being able to create the commit regardless after they have been notified.

**Comment by outofambit** [comment]
> I believe all that is left is clearing the commit summary afterwards.

Oh nice!! Ok, so my thoughts on that are to pass a (fat arrow) function to the popup that wraps the `clearCommitMessage` function and then call that from the popup if the commit is successful. Does that make sense? Its a _little_ bit of a hack but it _should_ work (and if others have better ideas they can comment on the PR).

**Comment by Daniel-McCarthy** [comment]
@outofambit
This is what I had tried initially with a couple of the other functions and I couldn't seem to get it working as expected. I gave it a try again with the `clearCommitMessage` function but it errors out saying that "this.setState is not a function".

Perhaps there is another way to do it? I tried by passing the function as `() => void`.

**Comment by outofambit** [comment]
@Daniel-McCarthy i bet its because 

https://github.com/desktop/desktop/blob/237695fbe9d9b7e604b6b0cc344b59fde2f9d09c/app/src/ui/changes/commit-message.tsx#L221-L223

is not bound to the component instance. 😞

i'm wondering if we should solve that in a different PR after your PR and #5809 land (since both have the same issue). i'm thinking we need to use the `dispatcher` et al to reset the `commit-message` state whenever a commit is made (i think this would mean setting the app's state directly inside `app-store` and calling `emitUpdate`. i'm happy to take a run at that and put a PR up for it on monday. How does that sound?

**Comment by Daniel-McCarthy** [comment]
@outofambit 
If I understand correctly, you're suggesting proceeding to a PR for the current progress and addressing the issue of the commit message clearing separately?

Does this mean I should create the PR as it is without the code that tries to call the `clearCommitMessage` function?

I think that would be wonderful if you're interested in taking a look at this issue. Thanks again for your help!

**Comment by outofambit** [comment]
> If I understand correctly, you're suggesting proceeding to a PR for the current progress and addressing the issue of the commit message clearing separately?

> Does this mean I should create the PR as it is without the code that tries to call the clearCommitMessage function?

@Daniel-McCarthy yes exactly! thank you again! just mention that its a known issue in the PR description and tag me as agreeing to fix that separately :)

**Comment by Daniel-McCarthy** [comment]
@outofambit Fantastic! I will do that now.

**Comment by outofambit** [comment]
@Daniel-McCarthy 

> i'm thinking we need to use the dispatcher et al to reset the commit-message state whenever a commit is made (i think this would mean setting the app's state directly inside app-store and calling emitUpdate.

apparently this already exists! its just buried here:
https://github.com/desktop/desktop/blob/f94a5cf81ffb22af6800ca81c6f96c61c8c1cdbd/app/src/lib/dispatcher/dispatcher.ts#L526-L531

so you (and I) should be able to call this dispatcher method to clear the field! 🎊

**Comment by shiftkey** [comment]
@outofambit @Daniel-McCarthy best of luck - last time I was looking at "how can i clear the commit programatically" I had some regrets and eventually had to roll back the changes - https://github.com/desktop/desktop/pull/5208 https://github.com/desktop/desktop/pull/5260 https://github.com/desktop/desktop/pull/5269

**Comment by outofambit** [comment]
thanks for the heads up @shiftkey ! i'm gonna say let's stick with the original plan of that being its own PR then.

**Comment by shiftkey** [comment]
@outofambit I will say a little prayer for you 

![](https://media.giphy.com/media/3ohhwmhHHrEe92UsV2/giphy.gif)
