### ISSUE TITLE
Cannot Continue After 100mb limit

### ISSUE THREAD

**Issue by CptPuddleboat** [desktop/desktop#9985]
### Describe the bug

After attempting to push a file that is over 100mb, you get told to remove the file from the history, and try again. This is impossible, and locks your repository, preventing future pushes.

### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Steps to reproduce the behavior

1. Push a commit that includes a file over 100mb
2. Get an error saying the push failed because of that file, and be advised to delete the file from history
3. Removing the file from history is not possible (as far as I can tell), and attempting future pushes of commits to revert the original commit fail, because the first commit has not yet been pushed

### Expected behavior

Allowing you to remove files from your commit history, or allowing you to completely remove commits that can't be pushed, thus allowing you to perform future commits

### Actual behavior

Removing a file from commit history is not possible, and reverting to previous commits is not possible without pushing the original commit, which can't happen if it contains a file over 100mb.

### Additional context

All assistance I found relating to this problem talked about working on the command line for git, so as far as I know, there is no way to fix this problem on Github Desktop

**Comment by rafeca** [comment]
Hi @CptPuddleboat! Thanks for reporting this issue!

It's possible to undo the latest commit done in a branch in Desktop if that commit has not been pushed to the remote repository. In that case a prompt should appear at the bottom of the left hand column on Desktop:

<img width="429" alt="Screen Shot 2020-06-11 at 15 32 06" src="https://user-images.githubusercontent.com/408035/84391209-f17d9600-abf8-11ea-8705-8be6e3f18d2d.png">

From your report it seems like you haven't been able to push the commit to the remote because of the large file, so you should be able to undo it without issues (note that undoing will remove the commit and get rid of the large file from the history, while reverting a commit will just create a new commit that reverts the changes but the file will remain in the history).

Note that if you added the large file a few commits ago, you'll need to undo all the commits until you reach the relevant commit and then re-do the commits again. Good news is that when you undo a commit, the changes from that commit are not completely lost but they appear as local changes (so you can discard them or store them however you want).

Let me know if this helps.

**Comment by rafeca** [comment]
Going to close the issue since I think the response above should solve your problem, but please reopen if that's not the case.

**Comment by rafeca** [comment]
@CptPuddleboat something worth to note (thanks @billygriffin for letting me know this!) is that GitHub Desktop should have displayed a warning when you tried to create commit with a file larger than 100MB.

Did you create the commit via GitHub Desktop? if so, do you remember seeing this warning? if that's not the case it would be worth testing if the warning is working correctly under all scenarios

**Comment by CptPuddleboat** [comment]
Thanks for the quick responses! I'm a fool and forgot to mention that I'm using UE4's Source Control to make the actual commits. That seems to have sort of half-completed the commit without actually allowing the push to happen, only hsowing the error upon attempting to push. Also because of this, I don't think the commit undo option appears, since the commit wasn't made through the app. I recognise now this might actually be more of an issue with UE4's finnicky source control system.

Again, thanks for the help!
